{
  "formatVersion": "1.1",
  "component": {
    "group": "net.titan",
    "module": "titan-plugin-api",
    "version": "0.1.73",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "7.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "titan-plugin-api-0.1.73.jar",
          "url": "titan-plugin-api-0.1.73.jar",
          "size": 9117480,
          "sha512": "e2296d2973d1d4c12fdb9475df251482073b317f73d9d324b081eb106310a2080f930f33f31d3f4ed09df44a1df2e8ffa54f68b155eb5a575efde85b97a26382",
          "sha256": "27121962b4cbb01d539eafc6643272c7793b09903cb99a05c9735324712ab1fb",
          "sha1": "c42438b3027d8e4439f0a78e6d7c879816e1cadd",
          "md5": "ef073baa6ac325e6d5aa6df3e9db71c3"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "7.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "titan-plugin-api-0.1.73.jar",
          "url": "titan-plugin-api-0.1.73.jar",
          "size": 9117480,
          "sha512": "e2296d2973d1d4c12fdb9475df251482073b317f73d9d324b081eb106310a2080f930f33f31d3f4ed09df44a1df2e8ffa54f68b155eb5a575efde85b97a26382",
          "sha256": "27121962b4cbb01d539eafc6643272c7793b09903cb99a05c9735324712ab1fb",
          "sha1": "c42438b3027d8e4439f0a78e6d7c879816e1cadd",
          "md5": "ef073baa6ac325e6d5aa6df3e9db71c3"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "titan-plugin-api-0.1.73-sources.jar",
          "url": "titan-plugin-api-0.1.73-sources.jar",
          "size": 4745868,
          "sha512": "9e0746934f59d3d48d1d0a1a32f7cfb2d5ef634285eebb9db667175810f58b4a2a6646ae6ccdda9cdbd4fac2711a2e7e3698dc6d41fa57963e1913f199c99156",
          "sha256": "aa4e785e19b88bb6c731f105e93e51ba6096db2ff0f9bc847212f36ae9187fb8",
          "sha1": "e654486db28e94e5ccb506813bdb3fadcaf274e6",
          "md5": "319a19cba51ccb96eaaf47947671a8de"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "titan-plugin-api-0.1.73-javadoc.jar",
          "url": "titan-plugin-api-0.1.73-javadoc.jar",
          "size": 22419807,
          "sha512": "ae1184a8173582e67a1b0c776b0f8fa79c4472f70c7ad4246e4a79e246e98f7370c9457b80a45d3a53876b8068c422bd18bd8b5eeaa51aa92848c9196aa8172a",
          "sha256": "f7189decb93f4eff24f9c748f9e16af5bd1e4321ab78ece549cb47c93d71ef4b",
          "sha1": "38a9735cb7bb9955e078a1a5d7568472635a35d0",
          "md5": "d6426eb256110dad22c6c901939b435c"
        }
      ]
    }
  ]
}
