{
  "formatVersion": "1.1",
  "component": {
    "group": "net.titan",
    "module": "titan-plugin-api",
    "version": "0.1.73",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "7.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "titan-plugin-api-0.1.73.jar",
          "url": "titan-plugin-api-0.1.73.jar",
          "size": 9117480,
          "sha512": "62db66b59ddc8823b597a456c566e487020e74b7b556c4bfc0f4221b1295ae795085258748063a1363a04c61d7e40d9344a4401385329f46adaa292330d3d836",
          "sha256": "03318e2648c4432bc92f234f37b69e9ae4bf698bfca8f360ad9275687c008add",
          "sha1": "54d74d7a40a96e6e921b769ceb63590958bf504e",
          "md5": "7629587b47f2f8dc6ea0192dc0051030"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "7.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "titan-plugin-api-0.1.73.jar",
          "url": "titan-plugin-api-0.1.73.jar",
          "size": 9117480,
          "sha512": "62db66b59ddc8823b597a456c566e487020e74b7b556c4bfc0f4221b1295ae795085258748063a1363a04c61d7e40d9344a4401385329f46adaa292330d3d836",
          "sha256": "03318e2648c4432bc92f234f37b69e9ae4bf698bfca8f360ad9275687c008add",
          "sha1": "54d74d7a40a96e6e921b769ceb63590958bf504e",
          "md5": "7629587b47f2f8dc6ea0192dc0051030"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "titan-plugin-api-0.1.73-sources.jar",
          "url": "titan-plugin-api-0.1.73-sources.jar",
          "size": 4745868,
          "sha512": "86ffd359b0c6a8ea0665b94163118395b6d10fff0fde58a94d8759365afca13aefd9535a85a1aebc4691ab0ff625a34abe3901016b5e52aa0b0bb22b718fae47",
          "sha256": "682d45aa6396dae81a3329b4c37b762fd4242bc2e81b4c59a5e0b6dbde419275",
          "sha1": "bb864961dd14081ca4d42aa486d9af7b7d10839c",
          "md5": "adb5bcadcbb00e06792f9b240c824376"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "titan-plugin-api-0.1.73-javadoc.jar",
          "url": "titan-plugin-api-0.1.73-javadoc.jar",
          "size": 22419807,
          "sha512": "e52afbfaa5f77666675ed4af0e5c11ba7c2c3047bf3f692b069786daac30eaded6c51701a3a472d8ea72728d9ef272c07c057b8c3dee790f30d368d8b3493814",
          "sha256": "8c4615893b4ec544e8fdcd1e1ffc0187dcbc300ffcf013419ea39cdf38890154",
          "sha1": "5ca3089cd47bf763510d1625f5c5dfea85867456",
          "md5": "45daaacce3d85b4842e8944278945151"
        }
      ]
    }
  ]
}
