{
  "formatVersion": "1.1",
  "component": {
    "group": "net.titan",
    "module": "titan-dev-gradle-plugin",
    "version": "0.1.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "titan-dev-gradle-plugin-0.1.1.jar",
          "url": "titan-dev-gradle-plugin-0.1.1.jar",
          "size": 108737,
          "sha512": "48adf17399c15d4c688a005ae8e0c653b83be18186db731a23524eccba4781bd60bbdfd344d0041e74a9c48c16a94446024113e00fca2dbef5e5e9a0eb0696a7",
          "sha256": "702c16a838680c8ae07ce16bce63ee2ee9a0da1b34f0130a36f06f3cb919f350",
          "sha1": "62a9afc19ab43840cc60dd3fa7c5fc8325ee194e",
          "md5": "3e67a414e4ff64e5c2a6dd4a0970a675"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "titan-dev-gradle-plugin-0.1.1.jar",
          "url": "titan-dev-gradle-plugin-0.1.1.jar",
          "size": 108737,
          "sha512": "48adf17399c15d4c688a005ae8e0c653b83be18186db731a23524eccba4781bd60bbdfd344d0041e74a9c48c16a94446024113e00fca2dbef5e5e9a0eb0696a7",
          "sha256": "702c16a838680c8ae07ce16bce63ee2ee9a0da1b34f0130a36f06f3cb919f350",
          "sha1": "62a9afc19ab43840cc60dd3fa7c5fc8325ee194e",
          "md5": "3e67a414e4ff64e5c2a6dd4a0970a675"
        }
      ]
    }
  ]
}
