{
  "formatVersion": "1.1",
  "component": {
    "group": "net.titan",
    "module": "titan-dev-gradle-plugin",
    "version": "0.1.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "titan-dev-gradle-plugin-0.1.1.jar",
          "url": "titan-dev-gradle-plugin-0.1.1.jar",
          "size": 108737,
          "sha512": "c5d8c5573324d3cb6b86655beb5c1933493347b538fc0cd5710d8eca1982956fefea3edc09b242e2f6707e84b887120085b201dc89e654bd5a2bcc6194977845",
          "sha256": "bf603017e6ddd30b210c7ef2535b30d6088aa1885253d61df56ae3d23575210a",
          "sha1": "f4621f50b1a6f0648b683aa104a1d74f333a20b1",
          "md5": "1c337452093f85b5ab12d1549c04548a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "titan-dev-gradle-plugin-0.1.1.jar",
          "url": "titan-dev-gradle-plugin-0.1.1.jar",
          "size": 108737,
          "sha512": "c5d8c5573324d3cb6b86655beb5c1933493347b538fc0cd5710d8eca1982956fefea3edc09b242e2f6707e84b887120085b201dc89e654bd5a2bcc6194977845",
          "sha256": "bf603017e6ddd30b210c7ef2535b30d6088aa1885253d61df56ae3d23575210a",
          "sha1": "f4621f50b1a6f0648b683aa104a1d74f333a20b1",
          "md5": "1c337452093f85b5ab12d1549c04548a"
        }
      ]
    }
  ]
}
