{
  "formatVersion": "1.1",
  "component": {
    "group": "net.titan",
    "module": "titan-dev-gradle-plugin",
    "version": "0.1.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "titan-dev-gradle-plugin-0.1.1.jar",
          "url": "titan-dev-gradle-plugin-0.1.1.jar",
          "size": 108737,
          "sha512": "2f7d6353e90f555b66042f7a2a4fe7bfc17fe5e1ad590a416c270b8fbd721adfdcb4c62df109828c6ddfa3ab91379524a982745d7ada2033c9318bbf6afbceed",
          "sha256": "597f4ae0c40ee32e12709740fdae9c39759d9ecca999dbd7b77e13d6cc756112",
          "sha1": "4738d88061a7be503cce3de34f8e125d6b06454c",
          "md5": "9037619791dd7b763757c77ddf64e422"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "titan-dev-gradle-plugin-0.1.1.jar",
          "url": "titan-dev-gradle-plugin-0.1.1.jar",
          "size": 108737,
          "sha512": "2f7d6353e90f555b66042f7a2a4fe7bfc17fe5e1ad590a416c270b8fbd721adfdcb4c62df109828c6ddfa3ab91379524a982745d7ada2033c9318bbf6afbceed",
          "sha256": "597f4ae0c40ee32e12709740fdae9c39759d9ecca999dbd7b77e13d6cc756112",
          "sha1": "4738d88061a7be503cce3de34f8e125d6b06454c",
          "md5": "9037619791dd7b763757c77ddf64e422"
        }
      ]
    }
  ]
}
