{
  "formatVersion": "1.1",
  "component": {
    "group": "net.titan",
    "module": "titan-plugin-api",
    "version": "0.1.33",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "7.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "titan-plugin-api-0.1.33.jar",
          "url": "titan-plugin-api-0.1.33.jar",
          "size": 9140455,
          "sha512": "d69848bff1e335c2150b9a1f18f5c036a98fcab894e5c7747c5b64bee3ca46753b85804fee333343266d21453a9329023bbf00771b83e04ae219bfcfd589fb2b",
          "sha256": "cf1e4cef4d5cfa611246b9279688e5df6167fa7031ccd41cb5dbc42989786f4e",
          "sha1": "049a9ef34b03e9675ab046a129c8b1407e2d2546",
          "md5": "d63cd79ed3db8237958d9cc6b12be7b8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "7.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "titan-plugin-api-0.1.33.jar",
          "url": "titan-plugin-api-0.1.33.jar",
          "size": 9140455,
          "sha512": "d69848bff1e335c2150b9a1f18f5c036a98fcab894e5c7747c5b64bee3ca46753b85804fee333343266d21453a9329023bbf00771b83e04ae219bfcfd589fb2b",
          "sha256": "cf1e4cef4d5cfa611246b9279688e5df6167fa7031ccd41cb5dbc42989786f4e",
          "sha1": "049a9ef34b03e9675ab046a129c8b1407e2d2546",
          "md5": "d63cd79ed3db8237958d9cc6b12be7b8"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "titan-plugin-api-0.1.33-sources.jar",
          "url": "titan-plugin-api-0.1.33-sources.jar",
          "size": 4722702,
          "sha512": "2d4249fdd46b729bbc98320c967ddde23fac55151672b662f23867b1d29b6bf689f3ed1a4fdb3d4054120561e41bd19226a5edc00ae2495a8a0ce83e9928260c",
          "sha256": "a0b40b4080306c7691233b63b6c692e40d2ba76eeb8f6646a5b85156c38c6d5e",
          "sha1": "047d5c7e6e1aaa77c7c51cb1915a701aacba9508",
          "md5": "19b6843436b4e785edb794a336b31b65"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "titan-plugin-api-0.1.33-javadoc.jar",
          "url": "titan-plugin-api-0.1.33-javadoc.jar",
          "size": 22335403,
          "sha512": "18050efc9c2834f64c89b03db9d5f91df4d9160f62bbc20a602bc607d6880800923ebcf7967f5ec99b87d4bf411f4e0e1037cc46cde39ff96e5eaa9de2103904",
          "sha256": "d55ab685b33b3ffce5c65a2e2ff6afba3a848e30cd9f3060fde1379e541e00b3",
          "sha1": "9929a3520d89ee9473104033860b5d3d4c2d1837",
          "md5": "0b839027b9d7c014ef16b77e26a6bd51"
        }
      ]
    }
  ]
}
