{
  "formatVersion": "1.1",
  "component": {
    "group": "net.titan",
    "module": "titan-plugin-api",
    "version": "0.1.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "7.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "titan-plugin-api-0.1.1.jar",
          "url": "titan-plugin-api-0.1.1.jar",
          "size": 163616,
          "sha512": "d22ea1edb09d68bce34659502a767b6a99e6fd75a29a941738077ba72699b6d4487645f83e00bdc5ef46c3e2d06ffd6283b4d87025c174db98ac476b3431af21",
          "sha256": "1859d2c22fe2791755d9ad1d4913a26310fae3ad10a01dd07c4c753e3e9a3c4b",
          "sha1": "da44a4eb1f40f81b3fdb2fc58067baff9272c837",
          "md5": "a70ecb2f060a8692cac621ae540b5e07"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "7.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "titan-plugin-api-0.1.1.jar",
          "url": "titan-plugin-api-0.1.1.jar",
          "size": 163616,
          "sha512": "d22ea1edb09d68bce34659502a767b6a99e6fd75a29a941738077ba72699b6d4487645f83e00bdc5ef46c3e2d06ffd6283b4d87025c174db98ac476b3431af21",
          "sha256": "1859d2c22fe2791755d9ad1d4913a26310fae3ad10a01dd07c4c753e3e9a3c4b",
          "sha1": "da44a4eb1f40f81b3fdb2fc58067baff9272c837",
          "md5": "a70ecb2f060a8692cac621ae540b5e07"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "titan-plugin-api-0.1.1-sources.jar",
          "url": "titan-plugin-api-0.1.1-sources.jar",
          "size": 86434,
          "sha512": "74affde6963e3d9a6c5f0454ceaa04ee8882c55eba8a290f6cb7448f9d4f17a84a5c73f05f3d1f748eb683694c9d02bb934d370f80417b8ee257bbd37d105cea",
          "sha256": "8438f334ddfc22707f8d0770ca572b8a4008786a8a2de368feca0090f7299eb5",
          "sha1": "75dd53c15ab810cf047d41300573fb74176571ba",
          "md5": "65f9ff98b399a76458a9cad42e08c3f9"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "titan-plugin-api-0.1.1-javadoc.jar",
          "url": "titan-plugin-api-0.1.1-javadoc.jar",
          "size": 832640,
          "sha512": "dffdf87e2b7a9243e4fdecf10dc8e00d13cd8a14ab7df4841fba65c1531c1bada0dced39b28b1f3fa5638876d5c33c02a2e5cf0f085936cdb8fe00aad3316e20",
          "sha256": "b0bae9b47da0e1300fd73a51c308f3b1aa38e796b88686e4b6836d2c634f301a",
          "sha1": "48e8db604ca511c88d5bcf047d20283b32d6d3c3",
          "md5": "10dfb22ba44bb15d615924644065f707"
        }
      ]
    }
  ]
}
