{
  "formatVersion": "1.1",
  "component": {
    "group": "net.titan",
    "module": "titan-plugin-api",
    "version": "0.1.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "7.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "titan-plugin-api-0.1.1.jar",
          "url": "titan-plugin-api-0.1.1.jar",
          "size": 33861,
          "sha512": "17666b81977c861e1966ba52a48f09da805eae8321f17688e6946e4545e0bc9b3ea1a3d888cb025cea9c9bfd802804ec7906b16e95ce7a8ef40e173e32d8c48a",
          "sha256": "76bb19b2e9bb752c91c06ab7d82196ca8015453cb25e8f97a597ba9ad190424d",
          "sha1": "b19da17c9c44d477b4fb75d8114548d4b6173909",
          "md5": "4176d0afd72b0786ade0d5bff7443d27"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "7.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "titan-plugin-api-0.1.1.jar",
          "url": "titan-plugin-api-0.1.1.jar",
          "size": 33861,
          "sha512": "17666b81977c861e1966ba52a48f09da805eae8321f17688e6946e4545e0bc9b3ea1a3d888cb025cea9c9bfd802804ec7906b16e95ce7a8ef40e173e32d8c48a",
          "sha256": "76bb19b2e9bb752c91c06ab7d82196ca8015453cb25e8f97a597ba9ad190424d",
          "sha1": "b19da17c9c44d477b4fb75d8114548d4b6173909",
          "md5": "4176d0afd72b0786ade0d5bff7443d27"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "titan-plugin-api-0.1.1-sources.jar",
          "url": "titan-plugin-api-0.1.1-sources.jar",
          "size": 20951,
          "sha512": "ed11dba27997ee3b2d7cefd499577492b7f58dd35f12c579bda7d2405c879111e046dc584dd6295bc0293a4c3d3a47723121e3edc67933612b1895fa5f804345",
          "sha256": "df19e9237d90c962cc0c2cc7d5c57d0c4f38f7ae11e83de55d595542c451c115",
          "sha1": "f1866a76f4dda03b2316c7244729d3e783bc7560",
          "md5": "cd98ecd06ca3039a33ceaf5ffeaf68cf"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "titan-plugin-api-0.1.1-javadoc.jar",
          "url": "titan-plugin-api-0.1.1-javadoc.jar",
          "size": 464670,
          "sha512": "ff629db64ea87d5b90d57d6f35b85c4eea9d4fd7411e262038675ff5f580941620f34144e26697638dd0b4884d9a05f1bcfbc388cb47636a27c00c36c9ead0a3",
          "sha256": "558de05bef680ab20e0e35b57287b2a0ddf31c33a30d605415fe0bc254083d32",
          "sha1": "ffeb358afca923939ee61b898c568b7353b49c3d",
          "md5": "1e9d52637649f177fb09dc181ea8fe7c"
        }
      ]
    }
  ]
}
