{
  "formatVersion": "1.1",
  "component": {
    "group": "net.titan",
    "module": "titan-plugin-api",
    "version": "0.1.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "7.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "titan-plugin-api-0.1.1.jar",
          "url": "titan-plugin-api-0.1.1.jar",
          "size": 163616,
          "sha512": "df87c41e447744d99e1db754971a7e84c3ab8a061f42f2e2684d0676047648b3385424215523f2d89190edbb8da89c91fa02910bfa8757d4bcef8dfcbf75ba72",
          "sha256": "851cdb24bfa7cbf740c36b8ba3b98b6e9b89275e89273d58442dfd8afb50e793",
          "sha1": "20eb79272721a2cfe3b9795bd03a29cb63f8a3ad",
          "md5": "4eb4cc99b38af0883a8e15f6143b7462"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "7.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "titan-plugin-api-0.1.1.jar",
          "url": "titan-plugin-api-0.1.1.jar",
          "size": 163616,
          "sha512": "df87c41e447744d99e1db754971a7e84c3ab8a061f42f2e2684d0676047648b3385424215523f2d89190edbb8da89c91fa02910bfa8757d4bcef8dfcbf75ba72",
          "sha256": "851cdb24bfa7cbf740c36b8ba3b98b6e9b89275e89273d58442dfd8afb50e793",
          "sha1": "20eb79272721a2cfe3b9795bd03a29cb63f8a3ad",
          "md5": "4eb4cc99b38af0883a8e15f6143b7462"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "titan-plugin-api-0.1.1-sources.jar",
          "url": "titan-plugin-api-0.1.1-sources.jar",
          "size": 86434,
          "sha512": "0d95d80527e59ccc24b48a82b6c77462100f1ece68e76063381255a92f3638b92623758d0ff856fd8cee1566119577afca00d994f71f2ba30d453a74452c753a",
          "sha256": "396bfc4e31ce0da996ecf03afc54d515b6f8071f9140a0663c981f9717ec3feb",
          "sha1": "bb1749404b26d7266bc9b27d32800822b4eadb23",
          "md5": "eb932ee828cc03a8e65aa8336b10ec47"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "titan-plugin-api-0.1.1-javadoc.jar",
          "url": "titan-plugin-api-0.1.1-javadoc.jar",
          "size": 832641,
          "sha512": "cd017587f415247e7b90ca05e85f5b90f924fd0d8ae7a2251b93d3ea89dc0a9ac953cf0a6fb62f375b595b5e7ae5e24e825bac215c460fe562760cea3865fd1f",
          "sha256": "01c7c79c86db289bca2d49a7e2d67b3ddb5bd0d6bdbe2a6dde1edbb0fe7634f6",
          "sha1": "e43444bb0b9d37321fc47c363aa7040a1563ac60",
          "md5": "55114bca46bd6ede9273bf119d9681e3"
        }
      ]
    }
  ]
}
