{
  "formatVersion": "1.1",
  "component": {
    "group": "net.titan",
    "module": "titan-plugin-api",
    "version": "0.1.14",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "7.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "titan-plugin-api-0.1.14.jar",
          "url": "titan-plugin-api-0.1.14.jar",
          "size": 5311812,
          "sha512": "629a3fe6944016ad2c291181052529e1170291d5c1c504ae302e22bc63162517bd53c5da125e7114d5f194999535d3a2ecf32577df7f564af0e45e8f5fc0aacd",
          "sha256": "2a1eb85e3aa91d3f31864e735fdf639a9589a437e3b6dd0e3400772775fb72ee",
          "sha1": "90e4013afbbe19f3beb3748eeacb4fdf3375628b",
          "md5": "3a7fe122ce61441663aad2e477447966"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "7.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "titan-plugin-api-0.1.14.jar",
          "url": "titan-plugin-api-0.1.14.jar",
          "size": 5311812,
          "sha512": "629a3fe6944016ad2c291181052529e1170291d5c1c504ae302e22bc63162517bd53c5da125e7114d5f194999535d3a2ecf32577df7f564af0e45e8f5fc0aacd",
          "sha256": "2a1eb85e3aa91d3f31864e735fdf639a9589a437e3b6dd0e3400772775fb72ee",
          "sha1": "90e4013afbbe19f3beb3748eeacb4fdf3375628b",
          "md5": "3a7fe122ce61441663aad2e477447966"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "titan-plugin-api-0.1.14-sources.jar",
          "url": "titan-plugin-api-0.1.14-sources.jar",
          "size": 2621224,
          "sha512": "f75b31abd0d63b235292addebecb7d781a1f5119cc51b08e869f8ed695f3b120213e807fd68bfc1f87c372750a9a9357eb13a61fa27033e7c61f694963943a70",
          "sha256": "5da2d748dc6aa49ba5a113ff44d40720832420a8be20c234e27f0f6fa50f063c",
          "sha1": "def36886863cd8a280cc91c99d02c67821a352d6",
          "md5": "ed94d10da8381cc74e0d186745985d79"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "titan-plugin-api-0.1.14-javadoc.jar",
          "url": "titan-plugin-api-0.1.14-javadoc.jar",
          "size": 15347228,
          "sha512": "9bb6c2de5d73dc295a761a473f51205ebea567cfa9a7ff69827518121921f03b558966d97cdd616074cee7d54d4a7901fd7a2c8a7d8b2e006beaa83c27b7e644",
          "sha256": "f509d9f8d9cc2c84183539e5f8fd269ca7f0f61f98df7b4b2526923e1991e4ea",
          "sha1": "d7e48eea659a34fab07844b2cb46e3982524543d",
          "md5": "bb41e2bcabf942d7a7db9f718f201b20"
        }
      ]
    }
  ]
}
