{
  "formatVersion": "1.1",
  "component": {
    "group": "net.titan",
    "module": "titan-plugin-api",
    "version": "0.1.19",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "7.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "titan-plugin-api-0.1.19.jar",
          "url": "titan-plugin-api-0.1.19.jar",
          "size": 9122334,
          "sha512": "3d3a7d851cb50233f16f8310e106b23b9e9c32e1594fa86332c3dfa7cc1292d2a3be74c456b19309104a3e1cb68e32fd5fdd69d9a7a6dc12ca919f54b551e405",
          "sha256": "e52989163ff7b318a076d16c300925f3597bb8fd25c59e751de60ed2a329e4f2",
          "sha1": "5631b1f6f0079a4f566e1edcbafaf9d6bc502476",
          "md5": "9034dc0b3b6e9cbe1a74111c7c74b1ab"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "7.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "titan-plugin-api-0.1.19.jar",
          "url": "titan-plugin-api-0.1.19.jar",
          "size": 9122334,
          "sha512": "3d3a7d851cb50233f16f8310e106b23b9e9c32e1594fa86332c3dfa7cc1292d2a3be74c456b19309104a3e1cb68e32fd5fdd69d9a7a6dc12ca919f54b551e405",
          "sha256": "e52989163ff7b318a076d16c300925f3597bb8fd25c59e751de60ed2a329e4f2",
          "sha1": "5631b1f6f0079a4f566e1edcbafaf9d6bc502476",
          "md5": "9034dc0b3b6e9cbe1a74111c7c74b1ab"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "titan-plugin-api-0.1.19-sources.jar",
          "url": "titan-plugin-api-0.1.19-sources.jar",
          "size": 4711001,
          "sha512": "5f72d7c281cf320d979abc9ac33d308da6b13f65eecf73d0b2ac874f6026c661da07feb8b535e222cc8d90e958477ed0a454ad72977a6ddb440a19b3d68bbcae",
          "sha256": "c288c37802cddd8e708b06953b445c97b0c81b209be9596d1e95f549575938ab",
          "sha1": "0b44d25f84591270953f43ace7cc249ece77e80d",
          "md5": "0dee8f2f71bff06b0d1f9794aa53ffd4"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "titan-plugin-api-0.1.19-javadoc.jar",
          "url": "titan-plugin-api-0.1.19-javadoc.jar",
          "size": 22289197,
          "sha512": "0c0135c90c2b1a77b6e0594fae58de72730459d814b176a8ca4bc8d3a40044f56536b1da6cff4ceccf8a97a699d036cdeacb0f1ce87d6bcd3855bbd6322a7629",
          "sha256": "4e4165b976a5dc677a2dc46d484ae40c34464f1f43e81188afd95619e415638e",
          "sha1": "62a1d8f74ffbd8eabb5481f5bb573d819b87b364",
          "md5": "61edd40c5d82f497c8b3357903ba34aa"
        }
      ]
    }
  ]
}
