{
  "formatVersion": "1.1",
  "component": {
    "group": "net.titan",
    "module": "titan-plugin-api",
    "version": "0.1.19",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "7.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "titan-plugin-api-0.1.19.jar",
          "url": "titan-plugin-api-0.1.19.jar",
          "size": 9122334,
          "sha512": "98deb2c665aa478dafe26c2fb21c322db41fc645beb1c75e8859c11ba7861a47f9a9360e5bd2db69da02a3d62cf84a12414d0783e00f5c86cd14c9eda262fd8d",
          "sha256": "ac3966c0c5d9011ca379caf020392508494fcec94ec209838d4cdef1b203d234",
          "sha1": "02252f62d444ed5962da4200e59ea133a8271911",
          "md5": "48fdfd0e20f24e33db6572a1b048a580"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "7.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "titan-plugin-api-0.1.19.jar",
          "url": "titan-plugin-api-0.1.19.jar",
          "size": 9122334,
          "sha512": "98deb2c665aa478dafe26c2fb21c322db41fc645beb1c75e8859c11ba7861a47f9a9360e5bd2db69da02a3d62cf84a12414d0783e00f5c86cd14c9eda262fd8d",
          "sha256": "ac3966c0c5d9011ca379caf020392508494fcec94ec209838d4cdef1b203d234",
          "sha1": "02252f62d444ed5962da4200e59ea133a8271911",
          "md5": "48fdfd0e20f24e33db6572a1b048a580"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "titan-plugin-api-0.1.19-sources.jar",
          "url": "titan-plugin-api-0.1.19-sources.jar",
          "size": 4711001,
          "sha512": "be2a07900be8fefed0498b802ac3755381aa8bf8f0c4975f6fc3e0917de1653e6adfc1fe5589cb1e9f2d61ab99a90cebeefd5447ee74c31478b3b40eabb93465",
          "sha256": "72c87622d074f72c84d9f4cedff03933b71a5ef173c8d07db89bae91fd12ab50",
          "sha1": "e14fb0d8d053647dedb3fd0d2a498c4f0eb7959e",
          "md5": "880731f8ec0fbd70577f683441b77e3a"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "titan-plugin-api-0.1.19-javadoc.jar",
          "url": "titan-plugin-api-0.1.19-javadoc.jar",
          "size": 22289197,
          "sha512": "5704cfa2fe231f009acda0910b84579accf63c18e68365371b468853d52f73c7d97915c2f0ab7d3f138b63280d6df634bb3328feb4494c5dd5b165c1b29e268b",
          "sha256": "0c7b13db526056e14646e5ff46d10c0391581f6c27af61e0c7976a849fdd2528",
          "sha1": "d9aba3c341b2ffc4581c4a63ec206fda0232e558",
          "md5": "9ccdc700525c86986a1841d9d48fe5c5"
        }
      ]
    }
  ]
}
