{
  "formatVersion": "1.1",
  "component": {
    "group": "net.titan",
    "module": "titan-plugin-api",
    "version": "0.1.60",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "7.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "titan-plugin-api-0.1.60.jar",
          "url": "titan-plugin-api-0.1.60.jar",
          "size": 9079116,
          "sha512": "61d828106bb813a31c11fe0c5ae678f77e37af18a2d276c88b7b7fe9753867d0f0dd6b0b126798b3b5ba1973602db1222a31a6520da9695e6b624a611e9a4ad3",
          "sha256": "07ca7b9beda25386c0580ea4cba1106c26adfb1330487ef61aba8baa5514c914",
          "sha1": "d16cd9f9e229067f901d7f379b97137ae1cfca40",
          "md5": "822f6d18ac64660f4967c5c8fdf03f4f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "7.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "titan-plugin-api-0.1.60.jar",
          "url": "titan-plugin-api-0.1.60.jar",
          "size": 9079116,
          "sha512": "61d828106bb813a31c11fe0c5ae678f77e37af18a2d276c88b7b7fe9753867d0f0dd6b0b126798b3b5ba1973602db1222a31a6520da9695e6b624a611e9a4ad3",
          "sha256": "07ca7b9beda25386c0580ea4cba1106c26adfb1330487ef61aba8baa5514c914",
          "sha1": "d16cd9f9e229067f901d7f379b97137ae1cfca40",
          "md5": "822f6d18ac64660f4967c5c8fdf03f4f"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "titan-plugin-api-0.1.60-sources.jar",
          "url": "titan-plugin-api-0.1.60-sources.jar",
          "size": 4717484,
          "sha512": "74310dc2697d9e9f689dc214c618df69d10bfcfb2b747254a4bfde7bae6754ada90d07d691b9cf61205be7e42d69f8da2f44c9e516a2c6d3e5a2b90acbc5c254",
          "sha256": "42226ac017d91ebfd8e1bf6c2db6a6f3538ebdeef2dd7d22dd4956c3cdd6b854",
          "sha1": "daa3fb034981a60ec9b95966ffd56c11ad829b75",
          "md5": "b1f477998f873239b6565ae88a4c793f"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "titan-plugin-api-0.1.60-javadoc.jar",
          "url": "titan-plugin-api-0.1.60-javadoc.jar",
          "size": 22292139,
          "sha512": "5e0c0f569a985cce0ceb23f04753cecb5311b0a77c56a9cfcfec2b16cd3efcd7c48ea746f94b8c7e0b93b6fa4b8246c757bc1a40e56ac97b5cf282adde0e5582",
          "sha256": "4e852c6ca3f5ff4218eeb96391699c8df9242bb4532d97c0b4cc3cb73eff83c3",
          "sha1": "1038ea7137b4a41f33f8f748836c87160f207309",
          "md5": "e83c996054f43ca9b578dfc264033be3"
        }
      ]
    }
  ]
}
