{
  "formatVersion": "1.1",
  "component": {
    "group": "net.titan",
    "module": "titan-dev-gradle-plugin",
    "version": "0.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "titan-dev-gradle-plugin-0.1.0.jar",
          "url": "titan-dev-gradle-plugin-0.1.0.jar",
          "size": 101663,
          "sha512": "62d84afdcf0dae1646b3f81e29adb97af93f753dda904ca90a2021ec4d40917aa04691259993ff86bb90e5f58bc10f8cf2b13d4cef7ec027f2dd4bfa19a62d6e",
          "sha256": "ed6fa4fb1e4342ff1b69a9656045c49ad25df07c73c38a1b20ebecdbb1a44680",
          "sha1": "53c4fcbcf1f4f0321bbb837e77b18a6e0f8386f2",
          "md5": "70812ee36dc23f23369e463a5695c999"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "titan-dev-gradle-plugin-0.1.0.jar",
          "url": "titan-dev-gradle-plugin-0.1.0.jar",
          "size": 101663,
          "sha512": "62d84afdcf0dae1646b3f81e29adb97af93f753dda904ca90a2021ec4d40917aa04691259993ff86bb90e5f58bc10f8cf2b13d4cef7ec027f2dd4bfa19a62d6e",
          "sha256": "ed6fa4fb1e4342ff1b69a9656045c49ad25df07c73c38a1b20ebecdbb1a44680",
          "sha1": "53c4fcbcf1f4f0321bbb837e77b18a6e0f8386f2",
          "md5": "70812ee36dc23f23369e463a5695c999"
        }
      ]
    }
  ]
}
