{
  "formatVersion": "1.1",
  "component": {
    "group": "net.titan",
    "module": "titan-dev-gradle-plugin",
    "version": "0.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "titan-dev-gradle-plugin-0.1.0.jar",
          "url": "titan-dev-gradle-plugin-0.1.0.jar",
          "size": 101663,
          "sha512": "08c72c89aabfb77cfe72e0661bbf67131b71bbecc161666b754d738f16dd1ba3d8bcbbedbd7cfcb24d80090195e0880f497d1cbebe7e28737f799bc502668654",
          "sha256": "6eb0c314da1395f24e34ee32f170f5319f5b13c00c7e3c62e903ff51eb0c21ee",
          "sha1": "90210671eb1630cea55ba7ac4466eba0cfd10350",
          "md5": "99177ba6b2c86176d28933a5a043c4e2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "titan-dev-gradle-plugin-0.1.0.jar",
          "url": "titan-dev-gradle-plugin-0.1.0.jar",
          "size": 101663,
          "sha512": "08c72c89aabfb77cfe72e0661bbf67131b71bbecc161666b754d738f16dd1ba3d8bcbbedbd7cfcb24d80090195e0880f497d1cbebe7e28737f799bc502668654",
          "sha256": "6eb0c314da1395f24e34ee32f170f5319f5b13c00c7e3c62e903ff51eb0c21ee",
          "sha1": "90210671eb1630cea55ba7ac4466eba0cfd10350",
          "md5": "99177ba6b2c86176d28933a5a043c4e2"
        }
      ]
    }
  ]
}
