{
  "formatVersion": "1.1",
  "component": {
    "group": "net.titan",
    "module": "titan-plugin-api",
    "version": "0.1.31",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "7.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "titan-plugin-api-0.1.31.jar",
          "url": "titan-plugin-api-0.1.31.jar",
          "size": 9139713,
          "sha512": "1ec26c4d9d4e8d65da0074c4ae2e92dcaf22ff4ef0ee074f225dda26ab30c301e1e9f3e8f1309c94be5b688bee2393f2fe5129a3c7d66d3f4fb8eaa2572a0a70",
          "sha256": "bdf26904cc5dbeef9cb6ce720cf21223135579a9d8b284ea04f664abd0cedc5a",
          "sha1": "1187cd90dcba3cf62009e77cf049b78cfc2dc016",
          "md5": "517f378cddd1296c73f73cb23545c479"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "7.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "titan-plugin-api-0.1.31.jar",
          "url": "titan-plugin-api-0.1.31.jar",
          "size": 9139713,
          "sha512": "1ec26c4d9d4e8d65da0074c4ae2e92dcaf22ff4ef0ee074f225dda26ab30c301e1e9f3e8f1309c94be5b688bee2393f2fe5129a3c7d66d3f4fb8eaa2572a0a70",
          "sha256": "bdf26904cc5dbeef9cb6ce720cf21223135579a9d8b284ea04f664abd0cedc5a",
          "sha1": "1187cd90dcba3cf62009e77cf049b78cfc2dc016",
          "md5": "517f378cddd1296c73f73cb23545c479"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "titan-plugin-api-0.1.31-sources.jar",
          "url": "titan-plugin-api-0.1.31-sources.jar",
          "size": 4722172,
          "sha512": "7089e962a0e8fb2f094512c9ae41b8b1ebbea03f2ac5b8dc94193c58d480e370389de66279c720857f361ca301ef754bca56ea2b8a021accee0f465da152e248",
          "sha256": "e7924efa4e48cc21b5eb9d04bcdfd65ec69cba4fb83c88c5111fee34bad0e3e8",
          "sha1": "6d394ac17fc0dd8025e15606a10ba515ee02dbb9",
          "md5": "850bc98f4163c8888a69f46745f2a24f"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "titan-plugin-api-0.1.31-javadoc.jar",
          "url": "titan-plugin-api-0.1.31-javadoc.jar",
          "size": 22334795,
          "sha512": "b8eee29686c0abeb857b351a20596865f3d6ec466c807421230abd6b6684744b07cb3ec0c8a200ab2a1099c2b2f3fc476f3542d603fe11dd3604dd60561c762b",
          "sha256": "417f63763facead3996c9929c7c652875ea617cc4cd814966e610272678609f5",
          "sha1": "c53ff9f535f565bdca97342fde65bfb06d30a1a5",
          "md5": "d2ed431f8bb7569f3760378c8a938e3b"
        }
      ]
    }
  ]
}
