{
  "formatVersion": "1.1",
  "component": {
    "group": "net.titan",
    "module": "titan-plugin-api",
    "version": "0.1.31",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "7.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "titan-plugin-api-0.1.31.jar",
          "url": "titan-plugin-api-0.1.31.jar",
          "size": 9139713,
          "sha512": "cb5dc80f873282f4f8ee71881b168e2922ccdceb8f957337b86f43cbd20dc1ebe3afbad7f8d793eca6031674444f04f38c2eb641075bc814b454deceb47159d6",
          "sha256": "72dc73f5fb771ef4525a0d0eb939019c328e1f7ed6ddb3f14b16b69f61cff8d1",
          "sha1": "b48b13a2f612f68017c4441fb730c06e3d933b2b",
          "md5": "eb72e91d74f0ad53332868c070919149"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "7.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "titan-plugin-api-0.1.31.jar",
          "url": "titan-plugin-api-0.1.31.jar",
          "size": 9139713,
          "sha512": "cb5dc80f873282f4f8ee71881b168e2922ccdceb8f957337b86f43cbd20dc1ebe3afbad7f8d793eca6031674444f04f38c2eb641075bc814b454deceb47159d6",
          "sha256": "72dc73f5fb771ef4525a0d0eb939019c328e1f7ed6ddb3f14b16b69f61cff8d1",
          "sha1": "b48b13a2f612f68017c4441fb730c06e3d933b2b",
          "md5": "eb72e91d74f0ad53332868c070919149"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "titan-plugin-api-0.1.31-sources.jar",
          "url": "titan-plugin-api-0.1.31-sources.jar",
          "size": 4722172,
          "sha512": "3658b0e7535c2d4321d7891a0efb4378517d4a5bf8e4b799d1530f69e0dbaa6449b78ccaa7dbdf00ac805f67f3802063d00e51ca6f24ec35defbf80138ea2824",
          "sha256": "0467b8173c0b5bea88f9145cb0a17b397c1d6f5d6711e5ca6dca0b02f58355e8",
          "sha1": "4b82419bded9ad8f0add7c05993e00e6626679cb",
          "md5": "cd3b56d77e10c3de8e0bebaa1a7659a3"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "titan-plugin-api-0.1.31-javadoc.jar",
          "url": "titan-plugin-api-0.1.31-javadoc.jar",
          "size": 22334791,
          "sha512": "f56acdf3b0e4a018cb6c77f354e3c87fd4b54e56d0b80291a15a0af2d586413674f4db96b5412a71f4345b2574a5b40e60b49455ab5bb0cb0a6790d9d27c36dd",
          "sha256": "68cdb4a5fe544230cd22fe0386b7979da3d0948876099697a1094e5beb01037b",
          "sha1": "8a41423b8a9181e0fd62f59624913f04a28fa591",
          "md5": "b4ab3551617b0e17935946af5578fca2"
        }
      ]
    }
  ]
}
