{
  "formatVersion": "1.1",
  "component": {
    "group": "net.titan",
    "module": "titan-plugin-api",
    "version": "0.1.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "7.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "titan-plugin-api-0.1.21.jar",
          "url": "titan-plugin-api-0.1.21.jar",
          "size": 9124945,
          "sha512": "fa4e7359b35d3733de89104735d92f754a48eaacc8f73cab59470bc3945d12e3c76c9df552ef527136898bec732d2764ebf7f5f7cd23472b92e67ddd4f29df81",
          "sha256": "153f9212acfec6a716aba93828d04cc8d85a19f36700d8c896d1401eceb0b2ea",
          "sha1": "db09be8c44fed7840b9a025751c37ffe76929012",
          "md5": "4d08cb54bb49784da89fcfede0a702ab"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "7.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "titan-plugin-api-0.1.21.jar",
          "url": "titan-plugin-api-0.1.21.jar",
          "size": 9124945,
          "sha512": "fa4e7359b35d3733de89104735d92f754a48eaacc8f73cab59470bc3945d12e3c76c9df552ef527136898bec732d2764ebf7f5f7cd23472b92e67ddd4f29df81",
          "sha256": "153f9212acfec6a716aba93828d04cc8d85a19f36700d8c896d1401eceb0b2ea",
          "sha1": "db09be8c44fed7840b9a025751c37ffe76929012",
          "md5": "4d08cb54bb49784da89fcfede0a702ab"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "titan-plugin-api-0.1.21-sources.jar",
          "url": "titan-plugin-api-0.1.21-sources.jar",
          "size": 4712190,
          "sha512": "e64f60715f0cfe4024067a16c7190156b6a4a25de188003294d5892ee981b28cba627bc48bbfd3e2a16eecfca7ffac6dc0fd060e973ca17c4592ba4701fdc90d",
          "sha256": "cb2e1a6d45812c5eb44aa56b4d7a4ff3854df3936354e63e9e712fc4ab600342",
          "sha1": "0841347abd72b3646275b80e4dbef47d0ea685be",
          "md5": "82649f21132051efe31161500de3090e"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "titan-plugin-api-0.1.21-javadoc.jar",
          "url": "titan-plugin-api-0.1.21-javadoc.jar",
          "size": 22292406,
          "sha512": "4e75dceda486eca1bf5efb1ab867e491c2d386e5210c2857f350f26aa5cfbeaf889dc0a6bf0862354295251f1809080a08582a435dda94caeddeda272136725e",
          "sha256": "e55aaaa45866398e6897ab0e900493d614195c7d0186122553e64de92d316ed0",
          "sha1": "77bc69a070c87994783c5fdaee4c7e5375ac6f66",
          "md5": "f23211bf4f00856d465ea8c9b840b17e"
        }
      ]
    }
  ]
}
