{
  "formatVersion": "1.1",
  "component": {
    "group": "net.titan",
    "module": "titan-plugin-api",
    "version": "0.1.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "7.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "titan-plugin-api-0.1.21.jar",
          "url": "titan-plugin-api-0.1.21.jar",
          "size": 9124945,
          "sha512": "c95ddc321f868898e3e591c71c5591f7f73aad51d472e4007e7f2a667e69e762decd50c97c92c218c9584aadf4b854eef48bad641692d1a68b92e29ba39c49a0",
          "sha256": "5c336f8e83b5d345e9f2164d2aa94ad067f7bd39ff7c47f09680cb66347d2ec0",
          "sha1": "9fc5b169b586a08d802ae00ba548066450d91c41",
          "md5": "ac3c31de5d33630914a1b009ecb4f6e9"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "7.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "titan-plugin-api-0.1.21.jar",
          "url": "titan-plugin-api-0.1.21.jar",
          "size": 9124945,
          "sha512": "c95ddc321f868898e3e591c71c5591f7f73aad51d472e4007e7f2a667e69e762decd50c97c92c218c9584aadf4b854eef48bad641692d1a68b92e29ba39c49a0",
          "sha256": "5c336f8e83b5d345e9f2164d2aa94ad067f7bd39ff7c47f09680cb66347d2ec0",
          "sha1": "9fc5b169b586a08d802ae00ba548066450d91c41",
          "md5": "ac3c31de5d33630914a1b009ecb4f6e9"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "titan-plugin-api-0.1.21-sources.jar",
          "url": "titan-plugin-api-0.1.21-sources.jar",
          "size": 4712190,
          "sha512": "a51820eaf456c1f8fbabf2ab61318b5423a7a6dccea8846b87c9ff9cb5bf6575667319dc7fd45847a7031366cc9db70fb396aee199a380e7f57295e06087c0c7",
          "sha256": "ad863c0a0c6e15445ca68cd816217ccd2a9189ef1171142854bd959b0cdb3c8b",
          "sha1": "34b690ea46af1d192425697aa979dcfeff05626e",
          "md5": "c4a4da5f826fa997f76d4d0a575fb241"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "titan-plugin-api-0.1.21-javadoc.jar",
          "url": "titan-plugin-api-0.1.21-javadoc.jar",
          "size": 22292406,
          "sha512": "2f53e786665e0863f0b21e947585e25e675e631d89008cba1f341e1070683a649b35a13328b9a7484999c1b8a82337ee91322f6ecacb80845e0af75506e595f3",
          "sha256": "29d579193df7ecc7f3010eafcff710dfa2703d3c63cac75f199d8143b732fe39",
          "sha1": "84193178f4ff8b7b718ba5c56bc571c947e255c7",
          "md5": "866dd7223ee59ee4164d0499f37d956d"
        }
      ]
    }
  ]
}
