package net.titan.gamevals.internal;

import java.util.Optional;

import net.titan.gamevals.GamevalEntry;
import net.titan.gamevals.QuestEntry;

final class DbRowIDEntries_0 {
    private DbRowIDEntries_0() {}

    static GamevalEntry[] entries() {
        return new GamevalEntry[] {
            new GamevalEntry(0, "ID_0", "", "rowtypes"),
            new GamevalEntry(1, "ID_1", "", "rowtypes"),
            new GamevalEntry(2, "ID_2", "", "rowtypes"),
            new GamevalEntry(3, "ID_3", "", "rowtypes"),
            new GamevalEntry(4, "ID_4", "", "rowtypes"),
            new GamevalEntry(5, "ID_5", "", "rowtypes"),
            new GamevalEntry(6, "ID_6", "", "rowtypes"),
            new GamevalEntry(7, "ID_7", "", "rowtypes"),
            new GamevalEntry(8, "ID_8", "", "rowtypes"),
            new GamevalEntry(9, "ID_9", "", "rowtypes"),
            new GamevalEntry(10, "ID_10", "", "rowtypes"),
            new GamevalEntry(11, "ID_11", "", "rowtypes"),
            new GamevalEntry(12, "ID_12", "", "rowtypes"),
            new GamevalEntry(13, "ID_13", "", "rowtypes"),
            new GamevalEntry(14, "ID_14", "", "rowtypes"),
            new GamevalEntry(15, "ID_15", "", "rowtypes"),
            new GamevalEntry(16, "ID_16", "", "rowtypes"),
            new GamevalEntry(17, "ID_17", "", "rowtypes"),
            new GamevalEntry(18, "ID_18", "", "rowtypes"),
            new GamevalEntry(19, "ID_19", "", "rowtypes"),
            new GamevalEntry(20, "ID_20", "", "rowtypes"),
            new GamevalEntry(21, "ID_21", "", "rowtypes"),
            new GamevalEntry(22, "ID_22", "", "rowtypes"),
            new GamevalEntry(23, "ID_23", "", "rowtypes"),
            new GamevalEntry(24, "ID_24", "", "rowtypes"),
            new GamevalEntry(25, "ID_25", "", "rowtypes"),
            new GamevalEntry(26, "ID_26", "", "rowtypes"),
            new GamevalEntry(27, "ID_27", "", "rowtypes"),
            new GamevalEntry(28, "ID_28", "", "rowtypes"),
            new GamevalEntry(29, "ID_29", "", "rowtypes"),
            new GamevalEntry(30, "ID_30", "", "rowtypes"),
            new GamevalEntry(31, "ID_31", "", "rowtypes"),
            new GamevalEntry(32, "ID_32", "", "rowtypes"),
            new GamevalEntry(33, "ID_33", "", "rowtypes"),
            new GamevalEntry(34, "ID_34", "", "rowtypes"),
            new GamevalEntry(35, "ID_35", "", "rowtypes"),
            new GamevalEntry(36, "ID_36", "", "rowtypes"),
            new GamevalEntry(37, "ID_37", "", "rowtypes"),
            new GamevalEntry(38, "ID_38", "", "rowtypes"),
            new GamevalEntry(39, "ID_39", "", "rowtypes"),
            new GamevalEntry(40, "ID_40", "", "rowtypes"),
            new GamevalEntry(41, "ID_41", "", "rowtypes"),
            new GamevalEntry(42, "ID_42", "", "rowtypes"),
            new GamevalEntry(43, "ID_43", "", "rowtypes"),
            new GamevalEntry(44, "ID_44", "", "rowtypes"),
            new GamevalEntry(45, "ID_45", "", "rowtypes"),
            new GamevalEntry(46, "ID_46", "", "rowtypes"),
            new GamevalEntry(47, "ID_47", "", "rowtypes"),
            new GamevalEntry(48, "ID_48", "", "rowtypes"),
            new GamevalEntry(49, "ID_49", "", "rowtypes"),
            new GamevalEntry(50, "ID_50", "", "rowtypes"),
            new GamevalEntry(51, "ID_51", "", "rowtypes"),
            new GamevalEntry(52, "ID_52", "", "rowtypes"),
            new GamevalEntry(53, "ID_53", "", "rowtypes"),
            new GamevalEntry(54, "ID_54", "", "rowtypes"),
            new GamevalEntry(55, "ID_55", "", "rowtypes"),
            new GamevalEntry(56, "ID_56", "", "rowtypes"),
            new GamevalEntry(57, "ID_57", "", "rowtypes"),
            new GamevalEntry(58, "ID_58", "", "rowtypes"),
            new GamevalEntry(59, "ID_59", "", "rowtypes"),
            new GamevalEntry(60, "ID_60", "", "rowtypes"),
            new GamevalEntry(61, "ID_61", "", "rowtypes"),
            new GamevalEntry(62, "ID_62", "", "rowtypes"),
            new GamevalEntry(63, "ID_63", "", "rowtypes"),
            new GamevalEntry(64, "ID_64", "", "rowtypes"),
            new GamevalEntry(65, "ID_65", "", "rowtypes"),
            new GamevalEntry(66, "ID_66", "", "rowtypes"),
            new GamevalEntry(67, "ID_67", "", "rowtypes"),
            new GamevalEntry(68, "ID_68", "", "rowtypes"),
            new GamevalEntry(69, "ID_69", "", "rowtypes"),
            new GamevalEntry(70, "ID_70", "", "rowtypes"),
            new GamevalEntry(71, "ID_71", "", "rowtypes"),
            new GamevalEntry(72, "ID_72", "", "rowtypes"),
            new GamevalEntry(73, "ID_73", "", "rowtypes"),
            new GamevalEntry(74, "ID_74", "", "rowtypes"),
            new GamevalEntry(75, "ID_75", "", "rowtypes"),
            new GamevalEntry(76, "ID_76", "", "rowtypes"),
            new GamevalEntry(77, "ID_77", "", "rowtypes"),
            new GamevalEntry(78, "ID_78", "", "rowtypes"),
            new GamevalEntry(79, "ID_79", "", "rowtypes"),
            new GamevalEntry(80, "ID_80", "", "rowtypes"),
            new GamevalEntry(81, "ID_81", "", "rowtypes"),
            new GamevalEntry(82, "ID_82", "", "rowtypes"),
            new GamevalEntry(83, "ID_83", "", "rowtypes"),
            new GamevalEntry(84, "ID_84", "", "rowtypes"),
            new GamevalEntry(85, "ID_85", "", "rowtypes"),
            new GamevalEntry(86, "ID_86", "", "rowtypes"),
            new GamevalEntry(87, "ID_87", "", "rowtypes"),
            new GamevalEntry(88, "ID_88", "", "rowtypes"),
            new GamevalEntry(89, "ID_89", "", "rowtypes"),
            new GamevalEntry(90, "ID_90", "", "rowtypes"),
            new GamevalEntry(91, "ID_91", "", "rowtypes"),
            new GamevalEntry(92, "ID_92", "", "rowtypes"),
            new GamevalEntry(93, "ID_93", "", "rowtypes"),
            new GamevalEntry(94, "ID_94", "", "rowtypes"),
            new GamevalEntry(95, "ID_95", "", "rowtypes"),
            new GamevalEntry(96, "ID_96", "", "rowtypes"),
            new GamevalEntry(97, "ID_97", "", "rowtypes"),
            new GamevalEntry(98, "ID_98", "", "rowtypes"),
            new GamevalEntry(99, "ID_99", "", "rowtypes"),
            new GamevalEntry(100, "ID_100", "", "rowtypes"),
            new GamevalEntry(101, "ID_101", "", "rowtypes"),
            new GamevalEntry(102, "ID_102", "", "rowtypes"),
            new GamevalEntry(103, "ID_103", "", "rowtypes"),
            new GamevalEntry(104, "ID_104", "", "rowtypes"),
            new GamevalEntry(105, "ID_105", "", "rowtypes"),
            new GamevalEntry(106, "ID_106", "", "rowtypes"),
            new GamevalEntry(107, "ID_107", "", "rowtypes"),
            new GamevalEntry(108, "ID_108", "", "rowtypes"),
            new GamevalEntry(109, "ID_109", "", "rowtypes"),
            new GamevalEntry(110, "ID_110", "", "rowtypes"),
            new GamevalEntry(111, "ID_111", "", "rowtypes"),
            new GamevalEntry(112, "ID_112", "", "rowtypes"),
            new GamevalEntry(113, "ID_113", "", "rowtypes"),
            new GamevalEntry(114, "ID_114", "", "rowtypes"),
            new GamevalEntry(115, "ID_115", "", "rowtypes"),
            new GamevalEntry(116, "ID_116", "", "rowtypes"),
            new GamevalEntry(117, "ID_117", "", "rowtypes"),
            new GamevalEntry(118, "ID_118", "", "rowtypes"),
            new GamevalEntry(119, "ID_119", "", "rowtypes"),
            new GamevalEntry(120, "ID_120", "", "rowtypes"),
            new GamevalEntry(121, "ID_121", "", "rowtypes"),
            new GamevalEntry(122, "ID_122", "", "rowtypes"),
            new GamevalEntry(123, "ID_123", "", "rowtypes"),
            new GamevalEntry(124, "ID_124", "", "rowtypes"),
            new GamevalEntry(125, "ID_125", "", "rowtypes"),
            new GamevalEntry(126, "ID_126", "", "rowtypes"),
            new GamevalEntry(127, "ID_127", "", "rowtypes"),
            new GamevalEntry(128, "ID_128", "", "rowtypes"),
            new GamevalEntry(129, "ID_129", "", "rowtypes"),
            new GamevalEntry(130, "ID_130", "", "rowtypes"),
            new GamevalEntry(131, "ID_131", "", "rowtypes"),
            new GamevalEntry(132, "ID_132", "", "rowtypes"),
            new GamevalEntry(133, "ID_133", "", "rowtypes"),
            new GamevalEntry(134, "ID_134", "", "rowtypes"),
            new GamevalEntry(135, "ID_135", "", "rowtypes"),
            new GamevalEntry(136, "ID_136", "", "rowtypes"),
            new GamevalEntry(137, "ID_137", "", "rowtypes"),
            new GamevalEntry(138, "ID_138", "", "rowtypes"),
            new GamevalEntry(139, "ID_139", "", "rowtypes"),
            new GamevalEntry(140, "ID_140", "", "rowtypes"),
            new GamevalEntry(141, "ID_141", "", "rowtypes"),
            new GamevalEntry(142, "ID_142", "", "rowtypes"),
            new GamevalEntry(143, "ID_143", "", "rowtypes"),
            new GamevalEntry(144, "ID_144", "", "rowtypes"),
            new GamevalEntry(145, "ID_145", "", "rowtypes"),
            new GamevalEntry(146, "ID_146", "", "rowtypes"),
            new GamevalEntry(147, "ID_147", "", "rowtypes"),
            new GamevalEntry(148, "ID_148", "", "rowtypes"),
            new GamevalEntry(149, "ID_149", "", "rowtypes"),
            new GamevalEntry(150, "ID_150", "", "rowtypes"),
            new GamevalEntry(151, "ID_151", "", "rowtypes"),
            new GamevalEntry(152, "ID_152", "", "rowtypes"),
            new GamevalEntry(153, "ID_153", "", "rowtypes"),
            new GamevalEntry(154, "ID_154", "", "rowtypes"),
            new GamevalEntry(155, "ID_155", "", "rowtypes"),
            new GamevalEntry(156, "ID_156", "", "rowtypes"),
            new GamevalEntry(157, "ID_157", "", "rowtypes"),
            new GamevalEntry(158, "ID_158", "", "rowtypes"),
            new GamevalEntry(159, "ID_159", "", "rowtypes"),
            new GamevalEntry(160, "ID_160", "", "rowtypes"),
            new GamevalEntry(161, "ID_161", "", "rowtypes"),
            new GamevalEntry(162, "ID_162", "", "rowtypes"),
            new GamevalEntry(163, "ID_163", "", "rowtypes"),
            new GamevalEntry(164, "ID_164", "", "rowtypes"),
            new GamevalEntry(165, "ID_165", "", "rowtypes"),
            new GamevalEntry(166, "ID_166", "", "rowtypes"),
            new GamevalEntry(167, "ID_167", "", "rowtypes"),
            new GamevalEntry(168, "ID_168", "", "rowtypes"),
            new GamevalEntry(169, "ID_169", "", "rowtypes"),
        };
    }

    static Optional<GamevalEntry> byId(int id) {
        for (GamevalEntry entry : entries()) {
            if (entry.id() == id) return Optional.of(entry);
        }
        return Optional.empty();
    }

}
