package net.titan.gamevals.internal;

import java.util.Optional;

import net.titan.gamevals.GamevalEntry;
import net.titan.gamevals.QuestEntry;

final class ItemIDEntries_23 {
    private ItemIDEntries_23() {}

    static GamevalEntry[] entries() {
        return new GamevalEntry[] {
            new GamevalEntry(11776, "BLACK_MASK_8_I", "Black mask (8) (i)", "objtypes"),
            new GamevalEntry(11777, "BLACK_MASK_7_I", "Black mask (7) (i)", "objtypes"),
            new GamevalEntry(11778, "BLACK_MASK_6_I", "Black mask (6) (i)", "objtypes"),
            new GamevalEntry(11779, "BLACK_MASK_5_I", "Black mask (5) (i)", "objtypes"),
            new GamevalEntry(11780, "BLACK_MASK_4_I", "Black mask (4) (i)", "objtypes"),
            new GamevalEntry(11781, "BLACK_MASK_3_I", "Black mask (3) (i)", "objtypes"),
            new GamevalEntry(11782, "BLACK_MASK_2_I", "Black mask (2) (i)", "objtypes"),
            new GamevalEntry(11783, "BLACK_MASK_1_I", "Black mask (1) (i)", "objtypes"),
            new GamevalEntry(11784, "BLACK_MASK_I", "Black mask (i)", "objtypes"),
            new GamevalEntry(11785, "ARMADYL_CROSSBOW", "Armadyl crossbow", "objtypes"),
            new GamevalEntry(11786, "ID_11786", "", "objtypes"),
            new GamevalEntry(11787, "STEAM_BATTLESTAFF", "Steam battlestaff", "objtypes"),
            new GamevalEntry(11788, "ID_11788", "", "objtypes"),
            new GamevalEntry(11789, "MYSTIC_STEAM_STAFF", "Mystic steam staff", "objtypes"),
            new GamevalEntry(11790, "ID_11790", "", "objtypes"),
            new GamevalEntry(11791, "STAFF_OF_THE_DEAD", "Staff of the dead", "objtypes"),
            new GamevalEntry(11792, "ID_11792", "", "objtypes"),
            new GamevalEntry(11793, "AGILITY_STRENGTH", "Agility strength", "objtypes"),
            new GamevalEntry(11794, "GODSWORD_SHARDS_1_2", "Godsword shards 1 & 2", "objtypes"),
            new GamevalEntry(11795, "ID_11795", "", "objtypes"),
            new GamevalEntry(11796, "GODSWORD_SHARDS_1_3", "Godsword shards 1 & 3", "objtypes"),
            new GamevalEntry(11797, "ID_11797", "", "objtypes"),
            new GamevalEntry(11798, "GODSWORD_BLADE", "Godsword blade", "objtypes"),
            new GamevalEntry(11799, "ID_11799", "", "objtypes"),
            new GamevalEntry(11800, "GODSWORD_SHARDS_2_3", "Godsword shards 2 & 3", "objtypes"),
            new GamevalEntry(11801, "ID_11801", "", "objtypes"),
            new GamevalEntry(11802, "ARMADYL_GODSWORD", "Armadyl godsword", "objtypes"),
            new GamevalEntry(11803, "ID_11803", "", "objtypes"),
            new GamevalEntry(11804, "BANDOS_GODSWORD", "Bandos godsword", "objtypes"),
            new GamevalEntry(11805, "ID_11805", "", "objtypes"),
            new GamevalEntry(11806, "SARADOMIN_GODSWORD", "Saradomin godsword", "objtypes"),
            new GamevalEntry(11807, "ID_11807", "", "objtypes"),
            new GamevalEntry(11808, "ZAMORAK_GODSWORD", "Zamorak godsword", "objtypes"),
            new GamevalEntry(11809, "ID_11809", "", "objtypes"),
            new GamevalEntry(11810, "ARMADYL_HILT", "Armadyl hilt", "objtypes"),
            new GamevalEntry(11811, "ID_11811", "", "objtypes"),
            new GamevalEntry(11812, "BANDOS_HILT", "Bandos hilt", "objtypes"),
            new GamevalEntry(11813, "ID_11813", "", "objtypes"),
            new GamevalEntry(11814, "SARADOMIN_HILT", "Saradomin hilt", "objtypes"),
            new GamevalEntry(11815, "ID_11815", "", "objtypes"),
            new GamevalEntry(11816, "ZAMORAK_HILT", "Zamorak hilt", "objtypes"),
            new GamevalEntry(11817, "ID_11817", "", "objtypes"),
            new GamevalEntry(11818, "GODSWORD_SHARD_1", "Godsword shard 1", "objtypes"),
            new GamevalEntry(11819, "ID_11819", "", "objtypes"),
            new GamevalEntry(11820, "GODSWORD_SHARD_2", "Godsword shard 2", "objtypes"),
            new GamevalEntry(11821, "ID_11821", "", "objtypes"),
            new GamevalEntry(11822, "GODSWORD_SHARD_3", "Godsword shard 3", "objtypes"),
            new GamevalEntry(11823, "ID_11823", "", "objtypes"),
            new GamevalEntry(11824, "ZAMORAKIAN_SPEAR", "Zamorakian spear", "objtypes"),
            new GamevalEntry(11825, "ID_11825", "", "objtypes"),
            new GamevalEntry(11826, "A_ARMADYL_HELMET", "A Armadyl helmet", "objtypes"),
            new GamevalEntry(11827, "ID_11827", "", "objtypes"),
            new GamevalEntry(11828, "ARMADYL_CHESTPLATE", "Armadyl chestplate", "objtypes"),
            new GamevalEntry(11829, "ID_11829", "", "objtypes"),
            new GamevalEntry(11830, "ARMADYL_CHAINSKIRT", "Armadyl chainskirt", "objtypes"),
            new GamevalEntry(11831, "ID_11831", "", "objtypes"),
            new GamevalEntry(11832, "BANDOS_CHESTPLATE", "Bandos chestplate", "objtypes"),
            new GamevalEntry(11833, "ID_11833", "", "objtypes"),
            new GamevalEntry(11834, "BANDOS_TASSETS", "Bandos tassets", "objtypes"),
            new GamevalEntry(11835, "ID_11835", "", "objtypes"),
            new GamevalEntry(11836, "BANDOS_BOOTS", "Bandos boots", "objtypes"),
            new GamevalEntry(11837, "ID_11837", "", "objtypes"),
            new GamevalEntry(11838, "SARADOMIN_SWORD", "Saradomin sword", "objtypes"),
            new GamevalEntry(11839, "ID_11839", "", "objtypes"),
            new GamevalEntry(11840, "DRAGON_BOOTS", "Dragon boots", "objtypes"),
            new GamevalEntry(11841, "ID_11841", "", "objtypes"),
            new GamevalEntry(11842, "KNIGHT_S_NOTES", "Knight's notes", "objtypes"),
            new GamevalEntry(11843, "KNIGHT_S_NOTES_11843", "Knight's notes", "objtypes"),
            new GamevalEntry(11844, "ID_11844", "", "objtypes"),
            new GamevalEntry(11845, "ID_11845", "", "objtypes"),
            new GamevalEntry(11846, "ID_11846", "", "objtypes"),
            new GamevalEntry(11847, "BLACK_H_WEEN_MASK", "Black h'ween mask", "objtypes"),
            new GamevalEntry(11848, "RANCID_TURKEY", "Rancid turkey", "objtypes"),
            new GamevalEntry(11849, "MARK_OF_GRACE", "Mark of grace", "objtypes"),
            new GamevalEntry(11850, "GRACEFUL_HOOD", "Graceful hood", "objtypes"),
            new GamevalEntry(11851, "GRACEFUL_HOOD_11851", "Graceful hood", "objtypes"),
            new GamevalEntry(11852, "GRACEFUL_CAPE", "Graceful cape", "objtypes"),
            new GamevalEntry(11853, "GRACEFUL_CAPE_11853", "Graceful cape", "objtypes"),
            new GamevalEntry(11854, "GRACEFUL_TOP", "Graceful top", "objtypes"),
            new GamevalEntry(11855, "GRACEFUL_TOP_11855", "Graceful top", "objtypes"),
            new GamevalEntry(11856, "GRACEFUL_LEGS", "Graceful legs", "objtypes"),
            new GamevalEntry(11857, "GRACEFUL_LEGS_11857", "Graceful legs", "objtypes"),
            new GamevalEntry(11858, "GRACEFUL_GLOVES", "Graceful gloves", "objtypes"),
            new GamevalEntry(11859, "GRACEFUL_GLOVES_11859", "Graceful gloves", "objtypes"),
            new GamevalEntry(11860, "GRACEFUL_BOOTS", "Graceful boots", "objtypes"),
            new GamevalEntry(11861, "GRACEFUL_BOOTS_11861", "Graceful boots", "objtypes"),
            new GamevalEntry(11862, "BLACK_PARTYHAT", "Black partyhat", "objtypes"),
            new GamevalEntry(11863, "RAINBOW_PARTYHAT", "Rainbow partyhat", "objtypes"),
            new GamevalEntry(11864, "SLAYER_HELMET", "Slayer helmet", "objtypes"),
            new GamevalEntry(11865, "SLAYER_HELMET_I", "Slayer helmet (i)", "objtypes"),
            new GamevalEntry(11866, "SLAYER_RING_8", "Slayer ring (8)", "objtypes"),
            new GamevalEntry(11867, "SLAYER_RING_7", "Slayer ring (7)", "objtypes"),
            new GamevalEntry(11868, "SLAYER_RING_6", "Slayer ring (6)", "objtypes"),
            new GamevalEntry(11869, "SLAYER_RING_5", "Slayer ring (5)", "objtypes"),
            new GamevalEntry(11870, "SLAYER_RING_4", "Slayer ring (4)", "objtypes"),
            new GamevalEntry(11871, "SLAYER_RING_3", "Slayer ring (3)", "objtypes"),
            new GamevalEntry(11872, "SLAYER_RING_2", "Slayer ring (2)", "objtypes"),
            new GamevalEntry(11873, "SLAYER_RING_1", "Slayer ring (1)", "objtypes"),
            new GamevalEntry(11874, "BROAD_ARROWHEADS", "Broad arrowheads", "objtypes"),
            new GamevalEntry(11875, "BROAD_BOLTS", "Broad bolts", "objtypes"),
            new GamevalEntry(11876, "UNFINISHED_BROAD_BOLTS", "Unfinished broad bolts", "objtypes"),
            new GamevalEntry(11877, "EMPTY_VIAL_PACK", "Empty vial pack", "objtypes"),
            new GamevalEntry(11878, "ID_11878", "", "objtypes"),
            new GamevalEntry(11879, "WATER_FILLED_VIAL_PACK", "Water-filled vial pack", "objtypes"),
            new GamevalEntry(11880, "ID_11880", "", "objtypes"),
            new GamevalEntry(11881, "FEATHER_PACK", "Feather pack", "objtypes"),
            new GamevalEntry(11882, "ID_11882", "", "objtypes"),
            new GamevalEntry(11883, "BAIT_PACK", "Bait pack", "objtypes"),
            new GamevalEntry(11884, "ID_11884", "", "objtypes"),
            new GamevalEntry(11885, "BROAD_ARROWHEAD_PACK", "Broad arrowhead pack", "objtypes"),
            new GamevalEntry(11886, "ID_11886", "", "objtypes"),
            new GamevalEntry(11887, "UNFINISHED_BROAD_BOLT_PACK", "Unfinished broad bolt pack", "objtypes"),
            new GamevalEntry(11888, "ID_11888", "", "objtypes"),
            new GamevalEntry(11889, "ZAMORAKIAN_HASTA", "Zamorakian hasta", "objtypes"),
            new GamevalEntry(11890, "ID_11890", "", "objtypes"),
            new GamevalEntry(11891, "SARADOMIN_BANNER_11891", "Saradomin banner", "objtypes"),
            new GamevalEntry(11892, "ZAMORAK_BANNER_11892", "Zamorak banner", "objtypes"),
            new GamevalEntry(11893, "DECORATIVE_ARMOUR_11893", "Decorative armour", "objtypes"),
            new GamevalEntry(11894, "DECORATIVE_ARMOUR_11894", "Decorative armour", "objtypes"),
            new GamevalEntry(11895, "DECORATIVE_ARMOUR_11895", "Decorative armour", "objtypes"),
            new GamevalEntry(11896, "DECORATIVE_ARMOUR_11896", "Decorative armour", "objtypes"),
            new GamevalEntry(11897, "DECORATIVE_ARMOUR_11897", "Decorative armour", "objtypes"),
            new GamevalEntry(11898, "DECORATIVE_ARMOUR_11898", "Decorative armour", "objtypes"),
            new GamevalEntry(11899, "DECORATIVE_ARMOUR_11899", "Decorative armour", "objtypes"),
            new GamevalEntry(11900, "DECORATIVE_ARMOUR_11900", "Decorative armour", "objtypes"),
            new GamevalEntry(11901, "DECORATIVE_ARMOUR_11901", "Decorative armour", "objtypes"),
            new GamevalEntry(11902, "LEAF_BLADED_SWORD", "Leaf-bladed sword", "objtypes"),
            new GamevalEntry(11903, "ID_11903", "", "objtypes"),
            new GamevalEntry(11904, "ENTOMOLOGIST_S_DIARY", "Entomologist's diary", "objtypes"),
            new GamevalEntry(11905, "TRIDENT_OF_THE_SEAS_FULL", "Trident of the seas (full)", "objtypes"),
            new GamevalEntry(11906, "ID_11906", "", "objtypes"),
            new GamevalEntry(11907, "TRIDENT_OF_THE_SEAS", "Trident of the seas", "objtypes"),
            new GamevalEntry(11908, "UNCHARGED_TRIDENT", "Uncharged trident", "objtypes"),
            new GamevalEntry(11909, "ID_11909", "", "objtypes"),
            new GamevalEntry(11910, "CHOCOLATE_STRAWBERRY", "Chocolate strawberry", "objtypes"),
            new GamevalEntry(11911, "ID_11911", "", "objtypes"),
            new GamevalEntry(11912, "BOX_OF_CHOCOLATE_STRAWBERRIES", "Box of chocolate strawberries", "objtypes"),
            new GamevalEntry(11913, "ID_11913", "", "objtypes"),
            new GamevalEntry(11914, "BOX_OF_CHOCOLATE_STRAWBERRIES_11914", "Box of chocolate strawberries", "objtypes"),
            new GamevalEntry(11915, "ID_11915", "", "objtypes"),
            new GamevalEntry(11916, "SLICE_OF_BIRTHDAY_CAKE", "Slice of birthday cake", "objtypes"),
            new GamevalEntry(11917, "SLICE_OF_BIRTHDAY_CAKE_11917", "Slice of birthday cake", "objtypes"),
            new GamevalEntry(11918, "BIRTHDAY_PRESENT", "Birthday present", "objtypes"),
            new GamevalEntry(11919, "COW_MASK", "Cow mask", "objtypes"),
            new GamevalEntry(11920, "DRAGON_PICKAXE", "Dragon pickaxe", "objtypes"),
            new GamevalEntry(11921, "ID_11921", "", "objtypes"),
            new GamevalEntry(11922, "LAVA_DRAGON_BONEMEAL", "Lava dragon bonemeal", "objtypes"),
            new GamevalEntry(11923, "BROKEN_PICKAXE_11923", "Broken pickaxe", "objtypes"),
            new GamevalEntry(11924, "MALEDICTION_WARD", "Malediction ward", "objtypes"),
            new GamevalEntry(11925, "ID_11925", "", "objtypes"),
            new GamevalEntry(11926, "ODIUM_WARD", "Odium ward", "objtypes"),
            new GamevalEntry(11927, "ID_11927", "", "objtypes"),
            new GamevalEntry(11928, "ODIUM_SHARD_1", "Odium shard 1", "objtypes"),
            new GamevalEntry(11929, "ODIUM_SHARD_2", "Odium shard 2", "objtypes"),
            new GamevalEntry(11930, "ODIUM_SHARD_3", "Odium shard 3", "objtypes"),
            new GamevalEntry(11931, "MALEDICTION_SHARD_1", "Malediction shard 1", "objtypes"),
            new GamevalEntry(11932, "MALEDICTION_SHARD_2", "Malediction shard 2", "objtypes"),
            new GamevalEntry(11933, "MALEDICTION_SHARD_3", "Malediction shard 3", "objtypes"),
            new GamevalEntry(11934, "RAW_DARK_CRAB", "Raw dark crab", "objtypes"),
            new GamevalEntry(11935, "ID_11935", "", "objtypes"),
            new GamevalEntry(11936, "DARK_CRAB", "Dark crab", "objtypes"),
            new GamevalEntry(11937, "ID_11937", "", "objtypes"),
            new GamevalEntry(11938, "BURNT_DARK_CRAB", "Burnt dark crab", "objtypes"),
            new GamevalEntry(11939, "ID_11939", "", "objtypes"),
            new GamevalEntry(11940, "A_EM_DARK_FISHING_BAIT", "A( ?M) Dark fishing bait", "objtypes"),
            new GamevalEntry(11941, "LOOTING_BAG", "Looting bag", "objtypes"),
            new GamevalEntry(11942, "ECUMENICAL_KEY", "Ecumenical key", "objtypes"),
            new GamevalEntry(11943, "LAVA_DRAGON_BONES", "Lava dragon bones", "objtypes"),
            new GamevalEntry(11944, "ID_11944", "", "objtypes"),
            new GamevalEntry(11945, "ID_11945", "", "objtypes"),
            new GamevalEntry(11946, "ID_11946", "", "objtypes"),
            new GamevalEntry(11947, "ID_11947", "", "objtypes"),
            new GamevalEntry(11948, "ID_11948", "", "objtypes"),
            new GamevalEntry(11949, "ID_11949", "", "objtypes"),
            new GamevalEntry(11950, "ID_11950", "", "objtypes"),
            new GamevalEntry(11951, "EXTENDED_ANTIFIRE_4", "Extended antifire(4)", "objtypes"),
            new GamevalEntry(11952, "ID_11952", "", "objtypes"),
            new GamevalEntry(11953, "EXTENDED_ANTIFIRE_3", "Extended antifire(3)", "objtypes"),
            new GamevalEntry(11954, "ID_11954", "", "objtypes"),
            new GamevalEntry(11955, "EXTENDED_ANTIFIRE_2", "Extended antifire(2)", "objtypes"),
            new GamevalEntry(11956, "ID_11956", "", "objtypes"),
            new GamevalEntry(11957, "EXTENDED_ANTIFIRE_1", "Extended antifire(1)", "objtypes"),
            new GamevalEntry(11958, "ID_11958", "", "objtypes"),
            new GamevalEntry(11959, "BLACK_CHINCHOMPA", "Black chinchompa", "objtypes"),
            new GamevalEntry(11960, "EXTENDED_ANTIFIRE_MIX_2", "Extended antifire mix(2)", "objtypes"),
            new GamevalEntry(11961, "ID_11961", "", "objtypes"),
            new GamevalEntry(11962, "EXTENDED_ANTIFIRE_MIX_1", "Extended antifire mix(1)", "objtypes"),
            new GamevalEntry(11963, "ID_11963", "", "objtypes"),
            new GamevalEntry(11964, "AMULET_OF_GLORY_T6", "Amulet of glory (t6)", "objtypes"),
            new GamevalEntry(11965, "ID_11965", "", "objtypes"),
            new GamevalEntry(11966, "AMULET_OF_GLORY_T5", "Amulet of glory (t5)", "objtypes"),
            new GamevalEntry(11967, "ID_11967", "", "objtypes"),
            new GamevalEntry(11968, "SKILLS_NECKLACE_6", "Skills necklace(6)", "objtypes"),
            new GamevalEntry(11969, "ID_11969", "", "objtypes"),
            new GamevalEntry(11970, "SKILLS_NECKLACE_5", "Skills necklace(5)", "objtypes"),
            new GamevalEntry(11971, "ID_11971", "", "objtypes"),
            new GamevalEntry(11972, "COMBAT_BRACELET_6", "Combat bracelet(6)", "objtypes"),
            new GamevalEntry(11973, "ID_11973", "", "objtypes"),
            new GamevalEntry(11974, "COMBAT_BRACELET_5", "Combat bracelet(5)", "objtypes"),
            new GamevalEntry(11975, "ID_11975", "", "objtypes"),
            new GamevalEntry(11976, "AMULET_OF_GLORY_5", "Amulet of glory(5)", "objtypes"),
            new GamevalEntry(11977, "ID_11977", "", "objtypes"),
            new GamevalEntry(11978, "AMULET_OF_GLORY_6", "Amulet of glory(6)", "objtypes"),
            new GamevalEntry(11979, "ID_11979", "", "objtypes"),
            new GamevalEntry(11980, "COIN_COLLECTION_11980", "Coin Collection", "objtypes"),
            new GamevalEntry(11981, "ID_11981", "", "objtypes"),
            new GamevalEntry(11982, "COIN_COLLECTION_11982", "Coin Collection", "objtypes"),
            new GamevalEntry(11983, "ID_11983", "", "objtypes"),
            new GamevalEntry(11984, "COIN_COLLECTION_11984", "Coin Collection", "objtypes"),
            new GamevalEntry(11985, "ID_11985", "", "objtypes"),
            new GamevalEntry(11986, "COIN_COLLECTION_11986", "Coin Collection", "objtypes"),
            new GamevalEntry(11987, "ID_11987", "", "objtypes"),
            new GamevalEntry(11988, "COIN_COLLECTION_11988", "Coin Collection", "objtypes"),
            new GamevalEntry(11989, "ID_11989", "", "objtypes"),
            new GamevalEntry(11990, "FEDORA", "Fedora", "objtypes"),
            new GamevalEntry(11991, "ID_11991", "", "objtypes"),
            new GamevalEntry(11992, "LAVA_SCALE", "Lava scale", "objtypes"),
            new GamevalEntry(11993, "ID_11993", "", "objtypes"),
            new GamevalEntry(11994, "LAVA_SCALE_SHARD", "Lava scale shard", "objtypes"),
            new GamevalEntry(11995, "PET_CHAOS_ELEMENTAL", "Pet chaos elemental", "objtypes"),
            new GamevalEntry(11996, "HOLIDAY_TOOL", "Holiday tool", "objtypes"),
            new GamevalEntry(11997, "ZREANIMATES_A_LOW_LEVELLED_CREATURE", "ZReanimates a low levelled creature", "objtypes"),
            new GamevalEntry(11998, "SMOKE_BATTLESTAFF", "Smoke battlestaff", "objtypes"),
            new GamevalEntry(11999, "ID_11999", "", "objtypes"),
            new GamevalEntry(12000, "MYSTIC_SMOKE_STAFF", "Mystic smoke staff", "objtypes"),
            new GamevalEntry(12001, "ID_12001", "", "objtypes"),
            new GamevalEntry(12002, "OCCULT_NECKLACE", "Occult necklace", "objtypes"),
            new GamevalEntry(12003, "ID_12003", "", "objtypes"),
            new GamevalEntry(12004, "KRAKEN_TENTACLE", "Kraken tentacle", "objtypes"),
            new GamevalEntry(12005, "ID_12005", "", "objtypes"),
            new GamevalEntry(12006, "ABYSSAL_TENTACLE", "Abyssal tentacle", "objtypes"),
            new GamevalEntry(12007, "JAR_OF_DIRT", "Jar of dirt", "objtypes"),
            new GamevalEntry(12008, "ID_12008", "", "objtypes"),
            new GamevalEntry(12009, "SOFT_CLAY_PACK", "Soft clay pack", "objtypes"),
            new GamevalEntry(12010, "SOFT_CLAY_PACK_12010", "Soft clay pack", "objtypes"),
            new GamevalEntry(12011, "PAY_DIRT", "Pay-dirt", "objtypes"),
            new GamevalEntry(12012, "GOLDEN_NUGGET", "Golden nugget", "objtypes"),
            new GamevalEntry(12013, "PROSPECTOR_HELMET", "Prospector helmet", "objtypes"),
            new GamevalEntry(12014, "PROSPECTOR_JACKET", "Prospector jacket", "objtypes"),
            new GamevalEntry(12015, "PROSPECTOR_LEGS", "Prospector legs", "objtypes"),
            new GamevalEntry(12016, "PROSPECTOR_BOOTS", "Prospector boots", "objtypes"),
            new GamevalEntry(12017, "SALVE_AMULET_I", "Salve amulet(i)", "objtypes"),
            new GamevalEntry(12018, "SALVE_AMULET_EI", "Salve amulet(ei)", "objtypes"),
            new GamevalEntry(12019, "COAL_BAG_12019", "Coal bag", "objtypes"),
            new GamevalEntry(12020, "GEM_BAG_12020", "Gem bag", "objtypes"),
            new GamevalEntry(12021, "CLUE_SCROLL_MEDIUM_12021", "Clue scroll (medium)", "objtypes"),
            new GamevalEntry(12022, "CASKET_MEDIUM_12022", "Casket (medium)", "objtypes"),
            new GamevalEntry(12023, "CLUE_SCROLL_MEDIUM_12023", "Clue scroll (medium)", "objtypes"),
            new GamevalEntry(12024, "CASKET_MEDIUM_12024", "Casket (medium)", "objtypes"),
            new GamevalEntry(12025, "CLUE_SCROLL_MEDIUM_12025", "Clue scroll (medium)", "objtypes"),
            new GamevalEntry(12026, "CASKET_MEDIUM_12026", "Casket (medium)", "objtypes"),
            new GamevalEntry(12027, "CLUE_SCROLL_MEDIUM_12027", "Clue scroll (medium)", "objtypes"),
            new GamevalEntry(12028, "CASKET_MEDIUM_12028", "Casket (medium)", "objtypes"),
            new GamevalEntry(12029, "CLUE_SCROLL_MEDIUM_12029", "Clue scroll (medium)", "objtypes"),
            new GamevalEntry(12030, "CASKET_MEDIUM_12030", "Casket (medium)", "objtypes"),
            new GamevalEntry(12031, "CLUE_SCROLL_MEDIUM_12031", "Clue scroll (medium)", "objtypes"),
            new GamevalEntry(12032, "CASKET_MEDIUM_12032", "Casket (medium)", "objtypes"),
            new GamevalEntry(12033, "CLUE_SCROLL_MEDIUM_12033", "Clue scroll (medium)", "objtypes"),
            new GamevalEntry(12034, "CASKET_MEDIUM_12034", "Casket (medium)", "objtypes"),
            new GamevalEntry(12035, "CLUE_SCROLL_MEDIUM_12035", "Clue scroll (medium)", "objtypes"),
            new GamevalEntry(12036, "CASKET_MEDIUM_12036", "Casket (medium)", "objtypes"),
            new GamevalEntry(12037, "CLUE_SCROLL_MEDIUM_12037", "Clue scroll (medium)", "objtypes"),
            new GamevalEntry(12038, "CASKET_MEDIUM_12038", "Casket (medium)", "objtypes"),
            new GamevalEntry(12039, "CLUE_SCROLL_MEDIUM_12039", "Clue scroll (medium)", "objtypes"),
            new GamevalEntry(12040, "CASKET_MEDIUM_12040", "Casket (medium)", "objtypes"),
            new GamevalEntry(12041, "CLUE_SCROLL_MEDIUM_12041", "Clue scroll (medium)", "objtypes"),
            new GamevalEntry(12042, "CASKET_MEDIUM_12042", "Casket (medium)", "objtypes"),
            new GamevalEntry(12043, "CLUE_SCROLL_MEDIUM_12043", "Clue scroll (medium)", "objtypes"),
            new GamevalEntry(12044, "CASKET_MEDIUM_12044", "Casket (medium)", "objtypes"),
            new GamevalEntry(12045, "CLUE_SCROLL_MEDIUM_12045", "Clue scroll (medium)", "objtypes"),
            new GamevalEntry(12046, "CASKET_MEDIUM_12046", "Casket (medium)", "objtypes"),
            new GamevalEntry(12047, "CLUE_SCROLL_MEDIUM_12047", "Clue scroll (medium)", "objtypes"),
            new GamevalEntry(12048, "CASKET_MEDIUM_12048", "Casket (medium)", "objtypes"),
            new GamevalEntry(12049, "CLUE_SCROLL_MEDIUM_12049", "Clue scroll (medium)", "objtypes"),
            new GamevalEntry(12050, "CASKET_MEDIUM_12050", "Casket (medium)", "objtypes"),
            new GamevalEntry(12051, "CLUE_SCROLL_MEDIUM_12051", "Clue scroll (medium)", "objtypes"),
            new GamevalEntry(12052, "CASKET_MEDIUM_12052", "Casket (medium)", "objtypes"),
            new GamevalEntry(12053, "CLUE_SCROLL_MEDIUM_12053", "Clue scroll (medium)", "objtypes"),
            new GamevalEntry(12054, "CASKET_MEDIUM_12054", "Casket (medium)", "objtypes"),
            new GamevalEntry(12055, "CLUE_SCROLL_MEDIUM_12055", "Clue scroll (medium)", "objtypes"),
            new GamevalEntry(12056, "CHALLENGE_SCROLL_MEDIUM_12056", "Challenge scroll (medium)", "objtypes"),
            new GamevalEntry(12057, "CLUE_SCROLL_MEDIUM_12057", "Clue scroll (medium)", "objtypes"),
            new GamevalEntry(12058, "CHALLENGE_SCROLL_MEDIUM_12058", "Challenge scroll (medium)", "objtypes"),
            new GamevalEntry(12059, "CLUE_SCROLL_MEDIUM_12059", "Clue scroll (medium)", "objtypes"),
            new GamevalEntry(12060, "CHALLENGE_SCROLL_MEDIUM_12060", "Challenge scroll (medium)", "objtypes"),
            new GamevalEntry(12061, "CLUE_SCROLL_MEDIUM_12061", "Clue scroll (medium)", "objtypes"),
            new GamevalEntry(12062, "CHALLENGE_SCROLL_MEDIUM_12062", "Challenge scroll (medium)", "objtypes"),
            new GamevalEntry(12063, "CLUE_SCROLL_MEDIUM_12063", "Clue scroll (medium)", "objtypes"),
            new GamevalEntry(12064, "CHALLENGE_SCROLL_MEDIUM_12064", "Challenge scroll (medium)", "objtypes"),
            new GamevalEntry(12065, "CLUE_SCROLL_MEDIUM_12065", "Clue scroll (medium)", "objtypes"),
            new GamevalEntry(12066, "CHALLENGE_SCROLL_MEDIUM_12066", "Challenge scroll (medium)", "objtypes"),
            new GamevalEntry(12067, "CLUE_SCROLL_MEDIUM_12067", "Clue scroll (medium)", "objtypes"),
            new GamevalEntry(12068, "CHALLENGE_SCROLL_MEDIUM_12068", "Challenge scroll (medium)", "objtypes"),
            new GamevalEntry(12069, "CLUE_SCROLL_MEDIUM_12069", "Clue scroll (medium)", "objtypes"),
            new GamevalEntry(12070, "CHALLENGE_SCROLL_MEDIUM_12070", "Challenge scroll (medium)", "objtypes"),
            new GamevalEntry(12071, "CLUE_SCROLL_MEDIUM_12071", "Clue scroll (medium)", "objtypes"),
            new GamevalEntry(12072, "CHALLENGE_SCROLL_MEDIUM_12072", "Challenge scroll (medium)", "objtypes"),
            new GamevalEntry(12073, "CLUE_SCROLL_ELITE", "Clue scroll (elite)", "objtypes"),
            new GamevalEntry(12074, "CLUE_SCROLL_ELITE_12074", "Clue scroll (elite)", "objtypes"),
            new GamevalEntry(12075, "CLUE_SCROLL_ELITE_12075", "Clue scroll (elite)", "objtypes"),
            new GamevalEntry(12076, "CLUE_SCROLL_ELITE_12076", "Clue scroll (elite)", "objtypes"),
            new GamevalEntry(12077, "CLUE_SCROLL_ELITE_12077", "Clue scroll (elite)", "objtypes"),
            new GamevalEntry(12078, "CLUE_SCROLL_ELITE_12078", "Clue scroll (elite)", "objtypes"),
            new GamevalEntry(12079, "CLUE_SCROLL_ELITE_12079", "Clue scroll (elite)", "objtypes"),
            new GamevalEntry(12080, "CLUE_SCROLL_ELITE_12080", "Clue scroll (elite)", "objtypes"),
            new GamevalEntry(12081, "CLUE_SCROLL_ELITE_12081", "Clue scroll (elite)", "objtypes"),
            new GamevalEntry(12082, "CLUE_SCROLL_ELITE_12082", "Clue scroll (elite)", "objtypes"),
            new GamevalEntry(12083, "CLUE_SCROLL_ELITE_12083", "Clue scroll (elite)", "objtypes"),
            new GamevalEntry(12084, "CASKET_ELITE", "Casket (elite)", "objtypes"),
            new GamevalEntry(12085, "CLUE_SCROLL_ELITE_12085", "Clue scroll (elite)", "objtypes"),
            new GamevalEntry(12086, "CLUE_SCROLL_ELITE_12086", "Clue scroll (elite)", "objtypes"),
            new GamevalEntry(12087, "CLUE_SCROLL_ELITE_12087", "Clue scroll (elite)", "objtypes"),
            new GamevalEntry(12088, "CLUE_SCROLL_ELITE_12088", "Clue scroll (elite)", "objtypes"),
            new GamevalEntry(12089, "CLUE_SCROLL_ELITE_12089", "Clue scroll (elite)", "objtypes"),
            new GamevalEntry(12090, "CLUE_SCROLL_ELITE_12090", "Clue scroll (elite)", "objtypes"),
            new GamevalEntry(12091, "CLUE_SCROLL_ELITE_12091", "Clue scroll (elite)", "objtypes"),
            new GamevalEntry(12092, "CLUE_SCROLL_ELITE_12092", "Clue scroll (elite)", "objtypes"),
            new GamevalEntry(12093, "CLUE_SCROLL_ELITE_12093", "Clue scroll (elite)", "objtypes"),
            new GamevalEntry(12094, "CLUE_SCROLL_ELITE_12094", "Clue scroll (elite)", "objtypes"),
            new GamevalEntry(12095, "CLUE_SCROLL_ELITE_12095", "Clue scroll (elite)", "objtypes"),
            new GamevalEntry(12096, "CLUE_SCROLL_ELITE_12096", "Clue scroll (elite)", "objtypes"),
            new GamevalEntry(12097, "CLUE_SCROLL_ELITE_12097", "Clue scroll (elite)", "objtypes"),
            new GamevalEntry(12098, "CLUE_SCROLL_ELITE_12098", "Clue scroll (elite)", "objtypes"),
            new GamevalEntry(12099, "CLUE_SCROLL_ELITE_12099", "Clue scroll (elite)", "objtypes"),
            new GamevalEntry(12100, "CLUE_SCROLL_ELITE_12100", "Clue scroll (elite)", "objtypes"),
            new GamevalEntry(12101, "CLUE_SCROLL_ELITE_12101", "Clue scroll (elite)", "objtypes"),
            new GamevalEntry(12102, "CLUE_SCROLL_ELITE_12102", "Clue scroll (elite)", "objtypes"),
            new GamevalEntry(12103, "CLUE_SCROLL_ELITE_12103", "Clue scroll (elite)", "objtypes"),
            new GamevalEntry(12104, "CLUE_SCROLL_ELITE_12104", "Clue scroll (elite)", "objtypes"),
            new GamevalEntry(12105, "CLUE_SCROLL_ELITE_12105", "Clue scroll (elite)", "objtypes"),
            new GamevalEntry(12106, "CLUE_SCROLL_ELITE_12106", "Clue scroll (elite)", "objtypes"),
            new GamevalEntry(12107, "CLUE_SCROLL_ELITE_12107", "Clue scroll (elite)", "objtypes"),
            new GamevalEntry(12108, "CLUE_SCROLL_ELITE_12108", "Clue scroll (elite)", "objtypes"),
            new GamevalEntry(12109, "CLUE_SCROLL_ELITE_12109", "Clue scroll (elite)", "objtypes"),
            new GamevalEntry(12110, "CLUE_SCROLL_ELITE_12110", "Clue scroll (elite)", "objtypes"),
            new GamevalEntry(12111, "CLUE_SCROLL_ELITE_12111", "Clue scroll (elite)", "objtypes"),
            new GamevalEntry(12112, "CASKET_ELITE_12112", "Casket (elite)", "objtypes"),
            new GamevalEntry(12113, "CLUE_SCROLL_ELITE_12113", "Clue scroll (elite)", "objtypes"),
            new GamevalEntry(12114, "CLUE_SCROLL_ELITE_12114", "Clue scroll (elite)", "objtypes"),
            new GamevalEntry(12115, "CLUE_SCROLL_ELITE_12115", "Clue scroll (elite)", "objtypes"),
            new GamevalEntry(12116, "CLUE_SCROLL_ELITE_12116", "Clue scroll (elite)", "objtypes"),
            new GamevalEntry(12117, "CLUE_SCROLL_ELITE_12117", "Clue scroll (elite)", "objtypes"),
            new GamevalEntry(12118, "CLUE_SCROLL_ELITE_12118", "Clue scroll (elite)", "objtypes"),
            new GamevalEntry(12119, "CLUE_SCROLL_ELITE_12119", "Clue scroll (elite)", "objtypes"),
            new GamevalEntry(12120, "CLUE_SCROLL_ELITE_12120", "Clue scroll (elite)", "objtypes"),
            new GamevalEntry(12121, "CLUE_SCROLL_ELITE_12121", "Clue scroll (elite)", "objtypes"),
            new GamevalEntry(12122, "CLUE_SCROLL_ELITE_12122", "Clue scroll (elite)", "objtypes"),
            new GamevalEntry(12123, "CLUE_SCROLL_ELITE_12123", "Clue scroll (elite)", "objtypes"),
            new GamevalEntry(12124, "CLUE_SCROLL_ELITE_12124", "Clue scroll (elite)", "objtypes"),
            new GamevalEntry(12125, "CLUE_SCROLL_ELITE_12125", "Clue scroll (elite)", "objtypes"),
            new GamevalEntry(12126, "CLUE_SCROLL_ELITE_12126", "Clue scroll (elite)", "objtypes"),
            new GamevalEntry(12127, "CLUE_SCROLL_ELITE_12127", "Clue scroll (elite)", "objtypes"),
            new GamevalEntry(12128, "CHALLENGE_SCROLL_ELITE", "Challenge scroll (elite)", "objtypes"),
            new GamevalEntry(12129, "CASKET_ELITE_12129", "Casket (elite)", "objtypes"),
            new GamevalEntry(12130, "CLUE_SCROLL_ELITE_12130", "Clue scroll (elite)", "objtypes"),
            new GamevalEntry(12131, "CASKET_ELITE_12131", "Casket (elite)", "objtypes"),
            new GamevalEntry(12132, "CLUE_SCROLL_ELITE_12132", "Clue scroll (elite)", "objtypes"),
            new GamevalEntry(12133, "CLUE_SCROLL_ELITE_12133", "Clue scroll (elite)", "objtypes"),
            new GamevalEntry(12134, "CLUE_SCROLL_ELITE_12134", "Clue scroll (elite)", "objtypes"),
            new GamevalEntry(12135, "CLUE_SCROLL_ELITE_12135", "Clue scroll (elite)", "objtypes"),
            new GamevalEntry(12136, "CLUE_SCROLL_ELITE_12136", "Clue scroll (elite)", "objtypes"),
            new GamevalEntry(12137, "CLUE_SCROLL_ELITE_12137", "Clue scroll (elite)", "objtypes"),
            new GamevalEntry(12138, "CLUE_SCROLL_ELITE_12138", "Clue scroll (elite)", "objtypes"),
            new GamevalEntry(12139, "CHALLENGE_SCROLL_ELITE_12139", "Challenge scroll (elite)", "objtypes"),
            new GamevalEntry(12140, "CLUE_SCROLL_ELITE_12140", "Clue scroll (elite)", "objtypes"),
            new GamevalEntry(12141, "CLUE_SCROLL_ELITE_12141", "Clue scroll (elite)", "objtypes"),
            new GamevalEntry(12142, "CLUE_SCROLL_ELITE_12142", "Clue scroll (elite)", "objtypes"),
            new GamevalEntry(12143, "CLUE_SCROLL_ELITE_12143", "Clue scroll (elite)", "objtypes"),
            new GamevalEntry(12144, "CLUE_SCROLL_ELITE_12144", "Clue scroll (elite)", "objtypes"),
            new GamevalEntry(12145, "CLUE_SCROLL_ELITE_12145", "Clue scroll (elite)", "objtypes"),
            new GamevalEntry(12146, "CLUE_SCROLL_ELITE_12146", "Clue scroll (elite)", "objtypes"),
            new GamevalEntry(12147, "CLUE_SCROLL_ELITE_12147", "Clue scroll (elite)", "objtypes"),
            new GamevalEntry(12148, "CLUE_SCROLL_ELITE_12148", "Clue scroll (elite)", "objtypes"),
            new GamevalEntry(12149, "CLUE_SCROLL_ELITE_12149", "Clue scroll (elite)", "objtypes"),
            new GamevalEntry(12150, "CLUE_SCROLL_ELITE_12150", "Clue scroll (elite)", "objtypes"),
            new GamevalEntry(12151, "CLUE_SCROLL_ELITE_12151", "Clue scroll (elite)", "objtypes"),
            new GamevalEntry(12152, "CLUE_SCROLL_ELITE_12152", "Clue scroll (elite)", "objtypes"),
            new GamevalEntry(12153, "CLUE_SCROLL_ELITE_12153", "Clue scroll (elite)", "objtypes"),
            new GamevalEntry(12154, "CLUE_SCROLL_ELITE_12154", "Clue scroll (elite)", "objtypes"),
            new GamevalEntry(12155, "CLUE_SCROLL_ELITE_12155", "Clue scroll (elite)", "objtypes"),
            new GamevalEntry(12156, "CLUE_SCROLL_ELITE_12156", "Clue scroll (elite)", "objtypes"),
            new GamevalEntry(12157, "CLUE_SCROLL_ELITE_12157", "Clue scroll (elite)", "objtypes"),
            new GamevalEntry(12158, "CLUE_SCROLL_ELITE_12158", "Clue scroll (elite)", "objtypes"),
            new GamevalEntry(12159, "CLUE_SCROLL_ELITE_12159", "Clue scroll (elite)", "objtypes"),
            new GamevalEntry(12160, "CASKET_ELITE_12160", "Casket (elite)", "objtypes"),
            new GamevalEntry(12161, "PUZZLE_BOX_ELITE", "Puzzle box (elite)", "objtypes"),
            new GamevalEntry(12162, "CLUE_SCROLL_EASY_12162", "Clue scroll (easy)", "objtypes"),
            new GamevalEntry(12163, "CASKET_EASY_12163", "Casket (easy)", "objtypes"),
            new GamevalEntry(12164, "CLUE_SCROLL_EASY_12164", "Clue scroll (easy)", "objtypes"),
            new GamevalEntry(12165, "CASKET_EASY_12165", "Casket (easy)", "objtypes"),
            new GamevalEntry(12166, "CLUE_SCROLL_EASY_12166", "Clue scroll (easy)", "objtypes"),
            new GamevalEntry(12167, "CLUE_SCROLL_EASY_12167", "Clue scroll (easy)", "objtypes"),
            new GamevalEntry(12168, "CLUE_SCROLL_EASY_12168", "Clue scroll (easy)", "objtypes"),
            new GamevalEntry(12169, "CLUE_SCROLL_EASY_12169", "Clue scroll (easy)", "objtypes"),
            new GamevalEntry(12170, "CLUE_SCROLL_EASY_12170", "Clue scroll (easy)", "objtypes"),
            new GamevalEntry(12171, "CASKET_EASY_12171", "Casket (easy)", "objtypes"),
            new GamevalEntry(12172, "CLUE_SCROLL_EASY_12172", "Clue scroll (easy)", "objtypes"),
            new GamevalEntry(12173, "CLUE_SCROLL_EASY_12173", "Clue scroll (easy)", "objtypes"),
            new GamevalEntry(12174, "CLUE_SCROLL_EASY_12174", "Clue scroll (easy)", "objtypes"),
            new GamevalEntry(12175, "CLUE_SCROLL_EASY_12175", "Clue scroll (easy)", "objtypes"),
            new GamevalEntry(12176, "CLUE_SCROLL_EASY_12176", "Clue scroll (easy)", "objtypes"),
            new GamevalEntry(12177, "CLUE_SCROLL_EASY_12177", "Clue scroll (easy)", "objtypes"),
            new GamevalEntry(12178, "CLUE_SCROLL_EASY_12178", "Clue scroll (easy)", "objtypes"),
            new GamevalEntry(12179, "CLUE_SCROLL_EASY_12179", "Clue scroll (easy)", "objtypes"),
            new GamevalEntry(12180, "CASKET_EASY_12180", "Casket (easy)", "objtypes"),
            new GamevalEntry(12181, "CLUE_SCROLL_EASY_12181", "Clue scroll (easy)", "objtypes"),
            new GamevalEntry(12182, "CLUE_SCROLL_EASY_12182", "Clue scroll (easy)", "objtypes"),
            new GamevalEntry(12183, "CLUE_SCROLL_EASY_12183", "Clue scroll (easy)", "objtypes"),
            new GamevalEntry(12184, "CLUE_SCROLL_EASY_12184", "Clue scroll (easy)", "objtypes"),
            new GamevalEntry(12185, "CLUE_SCROLL_EASY_12185", "Clue scroll (easy)", "objtypes"),
            new GamevalEntry(12186, "CLUE_SCROLL_EASY_12186", "Clue scroll (easy)", "objtypes"),
            new GamevalEntry(12187, "CLUE_SCROLL_EASY_12187", "Clue scroll (easy)", "objtypes"),
            new GamevalEntry(12188, "CLUE_SCROLL_EASY_12188", "Clue scroll (easy)", "objtypes"),
            new GamevalEntry(12189, "CLUE_SCROLL_EASY_12189", "Clue scroll (easy)", "objtypes"),
            new GamevalEntry(12190, "CLUE_SCROLL_EASY_12190", "Clue scroll (easy)", "objtypes"),
            new GamevalEntry(12191, "CLUE_SCROLL_EASY_12191", "Clue scroll (easy)", "objtypes"),
            new GamevalEntry(12192, "CLUE_SCROLL_EASY_12192", "Clue scroll (easy)", "objtypes"),
            new GamevalEntry(12193, "ANCIENT_ROBE_TOP", "Ancient robe top", "objtypes"),
            new GamevalEntry(12194, "ID_12194", "", "objtypes"),
            new GamevalEntry(12195, "ANCIENT_ROBE_LEGS", "Ancient robe legs", "objtypes"),
            new GamevalEntry(12196, "ID_12196", "", "objtypes"),
            new GamevalEntry(12197, "ANCIENT_CLOAK", "Ancient cloak", "objtypes"),
            new GamevalEntry(12198, "ID_12198", "", "objtypes"),
            new GamevalEntry(12199, "ANCIENT_CROZIER", "Ancient crozier", "objtypes"),
            new GamevalEntry(12200, "ID_12200", "", "objtypes"),
            new GamevalEntry(12201, "ANCIENT_STOLE", "Ancient stole", "objtypes"),
            new GamevalEntry(12202, "ID_12202", "", "objtypes"),
            new GamevalEntry(12203, "ANCIENT_MITRE", "Ancient mitre", "objtypes"),
            new GamevalEntry(12204, "ID_12204", "", "objtypes"),
            new GamevalEntry(12205, "BRONZE_PLATEBODY_G", "Bronze platebody (g)", "objtypes"),
            new GamevalEntry(12206, "ID_12206", "", "objtypes"),
            new GamevalEntry(12207, "BRONZE_PLATELEGS_G", "Bronze platelegs (g)", "objtypes"),
            new GamevalEntry(12208, "ID_12208", "", "objtypes"),
            new GamevalEntry(12209, "BRONZE_PLATESKIRT_G", "Bronze plateskirt (g)", "objtypes"),
            new GamevalEntry(12210, "ID_12210", "", "objtypes"),
            new GamevalEntry(12211, "BRONZE_FULL_HELM_G", "Bronze full helm (g)", "objtypes"),
            new GamevalEntry(12212, "ID_12212", "", "objtypes"),
            new GamevalEntry(12213, "BRONZE_KITESHIELD_G", "Bronze kiteshield (g)", "objtypes"),
            new GamevalEntry(12214, "ID_12214", "", "objtypes"),
            new GamevalEntry(12215, "BRONZE_PLATEBODY_T", "Bronze platebody (t)", "objtypes"),
            new GamevalEntry(12216, "ID_12216", "", "objtypes"),
            new GamevalEntry(12217, "BRONZE_PLATELEGS_T", "Bronze platelegs (t)", "objtypes"),
            new GamevalEntry(12218, "ID_12218", "", "objtypes"),
            new GamevalEntry(12219, "BRONZE_PLATESKIRT_T", "Bronze plateskirt (t)", "objtypes"),
            new GamevalEntry(12220, "ID_12220", "", "objtypes"),
            new GamevalEntry(12221, "BRONZE_FULL_HELM_T", "Bronze full helm (t)", "objtypes"),
            new GamevalEntry(12222, "ID_12222", "", "objtypes"),
            new GamevalEntry(12223, "BRONZE_KITESHIELD_T", "Bronze kiteshield (t)", "objtypes"),
            new GamevalEntry(12224, "ID_12224", "", "objtypes"),
            new GamevalEntry(12225, "IRON_PLATEBODY_T", "Iron platebody (t)", "objtypes"),
            new GamevalEntry(12226, "ID_12226", "", "objtypes"),
            new GamevalEntry(12227, "IRON_PLATELEGS_T", "Iron platelegs (t)", "objtypes"),
            new GamevalEntry(12228, "ID_12228", "", "objtypes"),
            new GamevalEntry(12229, "IRON_PLATESKIRT_T", "Iron plateskirt (t)", "objtypes"),
            new GamevalEntry(12230, "ID_12230", "", "objtypes"),
            new GamevalEntry(12231, "IRON_FULL_HELM_T", "Iron full helm (t)", "objtypes"),
            new GamevalEntry(12232, "ID_12232", "", "objtypes"),
            new GamevalEntry(12233, "IRON_KITESHIELD_T", "Iron kiteshield (t)", "objtypes"),
            new GamevalEntry(12234, "ID_12234", "", "objtypes"),
            new GamevalEntry(12235, "IRON_PLATEBODY_G", "Iron platebody (g)", "objtypes"),
            new GamevalEntry(12236, "ID_12236", "", "objtypes"),
            new GamevalEntry(12237, "IRON_PLATELEGS_G", "Iron platelegs (g)", "objtypes"),
            new GamevalEntry(12238, "ID_12238", "", "objtypes"),
            new GamevalEntry(12239, "IRON_PLATESKIRT_G", "Iron plateskirt (g)", "objtypes"),
            new GamevalEntry(12240, "ID_12240", "", "objtypes"),
            new GamevalEntry(12241, "IRON_FULL_HELM_G", "Iron full helm (g)", "objtypes"),
            new GamevalEntry(12242, "ID_12242", "", "objtypes"),
            new GamevalEntry(12243, "IRON_KITESHIELD_G", "Iron kiteshield (g)", "objtypes"),
            new GamevalEntry(12244, "ID_12244", "", "objtypes"),
            new GamevalEntry(12245, "X_A_BEANIE", "X A Beanie", "objtypes"),
            new GamevalEntry(12246, "ID_12246", "", "objtypes"),
            new GamevalEntry(12247, "RED_BERET", "Red beret", "objtypes"),
            new GamevalEntry(12248, "ID_12248", "", "objtypes"),
            new GamevalEntry(12249, "IMP_MASK", "Imp mask", "objtypes"),
            new GamevalEntry(12250, "ID_12250", "", "objtypes"),
            new GamevalEntry(12251, "GOBLIN_MASK", "Goblin mask", "objtypes"),
            new GamevalEntry(12252, "ID_12252", "", "objtypes"),
            new GamevalEntry(12253, "ARMADYL_ROBE_TOP", "Armadyl robe top", "objtypes"),
            new GamevalEntry(12254, "ID_12254", "", "objtypes"),
            new GamevalEntry(12255, "ARMADYL_ROBE_LEGS", "Armadyl robe legs", "objtypes"),
            new GamevalEntry(12256, "ID_12256", "", "objtypes"),
            new GamevalEntry(12257, "ARMADYL_STOLE", "Armadyl stole", "objtypes"),
            new GamevalEntry(12258, "ID_12258", "", "objtypes"),
            new GamevalEntry(12259, "ARMADYL_MITRE", "Armadyl mitre", "objtypes"),
            new GamevalEntry(12260, "ID_12260", "", "objtypes"),
            new GamevalEntry(12261, "ARMADYL_CLOAK", "Armadyl cloak", "objtypes"),
            new GamevalEntry(12262, "ID_12262", "", "objtypes"),
            new GamevalEntry(12263, "ARMADYL_CROZIER", "Armadyl crozier", "objtypes"),
            new GamevalEntry(12264, "ID_12264", "", "objtypes"),
            new GamevalEntry(12265, "BANDOS_ROBE_TOP", "Bandos robe top", "objtypes"),
            new GamevalEntry(12266, "ID_12266", "", "objtypes"),
            new GamevalEntry(12267, "BANDOS_ROBE_LEGS", "Bandos robe legs", "objtypes"),
            new GamevalEntry(12268, "ID_12268", "", "objtypes"),
            new GamevalEntry(12269, "BANDOS_STOLE", "Bandos stole", "objtypes"),
            new GamevalEntry(12270, "ID_12270", "", "objtypes"),
            new GamevalEntry(12271, "BANDOS_MITRE", "Bandos mitre", "objtypes"),
            new GamevalEntry(12272, "ID_12272", "", "objtypes"),
            new GamevalEntry(12273, "BANDOS_CLOAK", "Bandos cloak", "objtypes"),
            new GamevalEntry(12274, "ID_12274", "", "objtypes"),
            new GamevalEntry(12275, "BANDOS_CROZIER", "Bandos crozier", "objtypes"),
            new GamevalEntry(12276, "ID_12276", "", "objtypes"),
            new GamevalEntry(12277, "MITHRIL_PLATEBODY_G", "Mithril platebody (g)", "objtypes"),
            new GamevalEntry(12278, "ID_12278", "", "objtypes"),
            new GamevalEntry(12279, "MITHRIL_PLATELEGS_G", "Mithril platelegs (g)", "objtypes"),
            new GamevalEntry(12280, "ID_12280", "", "objtypes"),
            new GamevalEntry(12281, "MITHRIL_KITESHIELD_G", "Mithril kiteshield (g)", "objtypes"),
            new GamevalEntry(12282, "ID_12282", "", "objtypes"),
            new GamevalEntry(12283, "MITHRIL_FULL_HELM_G", "Mithril full helm (g)", "objtypes"),
            new GamevalEntry(12284, "ID_12284", "", "objtypes"),
            new GamevalEntry(12285, "MITHRIL_PLATESKIRT_G", "Mithril plateskirt (g)", "objtypes"),
            new GamevalEntry(12286, "ID_12286", "", "objtypes"),
            new GamevalEntry(12287, "MITHRIL_PLATEBODY_T", "Mithril platebody (t)", "objtypes"),
        };
    }

    static Optional<GamevalEntry> byId(int id) {
        for (GamevalEntry entry : entries()) {
            if (entry.id() == id) return Optional.of(entry);
        }
        return Optional.empty();
    }

}
