package net.titan.gamevals.internal;

import java.util.Optional;

import net.titan.gamevals.GamevalEntry;
import net.titan.gamevals.QuestEntry;

final class ItemIDEntries_8 {
    private ItemIDEntries_8() {}

    static GamevalEntry[] entries() {
        return new GamevalEntry[] {
            new GamevalEntry(4096, "CERT_MYSTIC_GLOVES", "cert_mystic_gloves", "objtypes"),
            new GamevalEntry(4097, "MYSTIC_BOOTS", "Mystic boots", "objtypes"),
            new GamevalEntry(4098, "CERT_MYSTIC_BOOTS", "cert_mystic_boots", "objtypes"),
            new GamevalEntry(4099, "MYSTIC_HAT_DARK", "Mystic hat (dark)", "objtypes"),
            new GamevalEntry(4100, "CERT_MYSTIC_HAT_DARK", "cert_mystic_hat_dark", "objtypes"),
            new GamevalEntry(4101, "MYSTIC_ROBE_TOP_DARK", "Mystic robe top (dark)", "objtypes"),
            new GamevalEntry(4102, "CERT_MYSTIC_ROBE_TOP_DARK", "cert_mystic_robe_top_dark", "objtypes"),
            new GamevalEntry(4103, "MYSTIC_ROBE_BOTTOM_DARK", "Mystic robe bottom (dark)", "objtypes"),
            new GamevalEntry(4104, "CERT_MYSTIC_ROBE_BOTTOM_DARK", "cert_mystic_robe_bottom_dark", "objtypes"),
            new GamevalEntry(4105, "MYSTIC_GLOVES_DARK", "Mystic gloves (dark)", "objtypes"),
            new GamevalEntry(4106, "CERT_MYSTIC_GLOVES_DARK", "cert_mystic_gloves_dark", "objtypes"),
            new GamevalEntry(4107, "MYSTIC_BOOTS_DARK", "Mystic boots (dark)", "objtypes"),
            new GamevalEntry(4108, "CERT_MYSTIC_BOOTS_DARK", "cert_mystic_boots_dark", "objtypes"),
            new GamevalEntry(4109, "MYSTIC_HAT_LIGHT", "Mystic hat (light)", "objtypes"),
            new GamevalEntry(4110, "CERT_MYSTIC_HAT_LIGHT", "cert_mystic_hat_light", "objtypes"),
            new GamevalEntry(4111, "MYSTIC_ROBE_TOP_LIGHT", "Mystic robe top (light)", "objtypes"),
            new GamevalEntry(4112, "CERT_MYSTIC_ROBE_TOP_LIGHT", "cert_mystic_robe_top_light", "objtypes"),
            new GamevalEntry(4113, "MYSTIC_ROBE_BOTTOM_LIGHT", "Mystic robe bottom (light)", "objtypes"),
            new GamevalEntry(4114, "CERT_MYSTIC_ROBE_BOTTOM_LIGHT", "cert_mystic_robe_bottom_light", "objtypes"),
            new GamevalEntry(4115, "MYSTIC_GLOVES_LIGHT", "Mystic gloves (light)", "objtypes"),
            new GamevalEntry(4116, "CERT_MYSTIC_GLOVES_LIGHT", "cert_mystic_gloves_light", "objtypes"),
            new GamevalEntry(4117, "MYSTIC_BOOTS_LIGHT", "Mystic boots (light)", "objtypes"),
            new GamevalEntry(4118, "CERT_MYSTIC_BOOTS_LIGHT", "cert_mystic_boots_light", "objtypes"),
            new GamevalEntry(4119, "BRONZE_ARMOURED_BOOTS", "Bronze boots", "objtypes"),
            new GamevalEntry(4120, "CERT_BRONZE_ARMOURED_BOOTS", "cert_bronze_armoured_boots", "objtypes"),
            new GamevalEntry(4121, "IRON_ARMOURED_BOOTS", "Iron boots", "objtypes"),
            new GamevalEntry(4122, "CERT_IRON_ARMOURED_BOOTS", "cert_iron_armoured_boots", "objtypes"),
            new GamevalEntry(4123, "STEEL_ARMOURED_BOOTS", "Steel boots", "objtypes"),
            new GamevalEntry(4124, "CERT_STEEL_ARMOURED_BOOTS", "cert_steel_armoured_boots", "objtypes"),
            new GamevalEntry(4125, "BLACK_ARMOURED_BOOTS", "Black boots", "objtypes"),
            new GamevalEntry(4126, "CERT_BLACK_ARMOURED_BOOTS", "cert_black_armoured_boots", "objtypes"),
            new GamevalEntry(4127, "MITHRIL_ARMOURED_BOOTS", "Mithril boots", "objtypes"),
            new GamevalEntry(4128, "CERT_MITHRIL_ARMOURED_BOOTS", "cert_mithril_armoured_boots", "objtypes"),
            new GamevalEntry(4129, "ADAMANT_ARMOURED_BOOTS", "Adamant boots", "objtypes"),
            new GamevalEntry(4130, "CERT_ADAMANT_ARMOURED_BOOTS", "cert_adamant_armoured_boots", "objtypes"),
            new GamevalEntry(4131, "RUNE_ARMOURED_BOOTS", "Rune boots", "objtypes"),
            new GamevalEntry(4132, "CERT_RUNE_ARMOURED_BOOTS", "cert_rune_armoured_boots", "objtypes"),
            new GamevalEntry(4133, "SLAYERGUIDE_CRAWLINGHAND", "Crawling hand", "objtypes"),
            new GamevalEntry(4134, "SLAYERGUIDE_CAVECRAWLER", "Cave crawler", "objtypes"),
            new GamevalEntry(4135, "SLAYERGUIDE_BANSHEE", "Banshee", "objtypes"),
            new GamevalEntry(4136, "SLAYERGUIDE_ROCKSLUG", "Rockslug", "objtypes"),
            new GamevalEntry(4137, "SLAYERGUIDE_COCKATRICE", "Cockatrice", "objtypes"),
            new GamevalEntry(4138, "SLAYERGUIDE_PYRFIEND", "Pyrefiend", "objtypes"),
            new GamevalEntry(4139, "SLAYERGUIDE_BASILISK", "Basilisk", "objtypes"),
            new GamevalEntry(4140, "SLAYERGUIDE_INFERNALMAGE", "Infernal mage", "objtypes"),
            new GamevalEntry(4141, "SLAYERGUIDE_BLOODVELD", "Bloodveld", "objtypes"),
            new GamevalEntry(4142, "SLAYERGUIDE_JELLY", "Jelly", "objtypes"),
            new GamevalEntry(4143, "SLAYERGUIDE_TUROTH", "Turoth", "objtypes"),
            new GamevalEntry(4144, "SLAYERGUIDE_ABERRANTSPECTER", "Aberrant spectre", "objtypes"),
            new GamevalEntry(4145, "SLAYERGUIDE_DUSTDEVIL", "Dust devil", "objtypes"),
            new GamevalEntry(4146, "SLAYERGUIDE_KURASK", "Kurask", "objtypes"),
            new GamevalEntry(4147, "SLAYERGUIDE_GARGOYLE", "Gargoyle", "objtypes"),
            new GamevalEntry(4148, "SLAYERGUIDE_NECHRYAEL", "Nechryael", "objtypes"),
            new GamevalEntry(4149, "SLAYERGUIDE_ABYSSALDEMON", "Abyssal demon", "objtypes"),
            new GamevalEntry(4150, "SLAYERGUIDE_BROAD_ARROWS", "Broad arrows", "objtypes"),
            new GamevalEntry(4151, "ABYSSAL_WHIP", "Abyssal whip", "objtypes"),
            new GamevalEntry(4152, "CERT_ABYSSAL_WHIP", "cert_abyssal_whip", "objtypes"),
            new GamevalEntry(4153, "GRANITE_MAUL", "Granite maul", "objtypes"),
            new GamevalEntry(4154, "CERT_GRANITE_MAUL", "cert_granite_maul", "objtypes"),
            new GamevalEntry(4155, "SLAYER_GEM", "Enchanted gem", "objtypes"),
            new GamevalEntry(4156, "SLAYER_MIRROR_SHIELD", "Mirror shield", "objtypes"),
            new GamevalEntry(4157, "CERT_SLAYER_MIRROR_SHIELD", "cert_slayer_mirror_shield", "objtypes"),
            new GamevalEntry(4158, "SLAYER_LEAFBLADED_SPEAR", "Leaf-bladed spear", "objtypes"),
            new GamevalEntry(4159, "CERT_SLAYER_LEAFBLADED_SPEAR", "Leaf-bladed spear", "objtypes"),
            new GamevalEntry(4160, "SLAYER_BROAD_ARROWS", "Broad arrows", "objtypes"),
            new GamevalEntry(4161, "SLAYER_BAG_OF_SALT", "Bag of salt", "objtypes"),
            new GamevalEntry(4162, "SLAYER_ROCK_HAMMER", "Rock hammer", "objtypes"),
            new GamevalEntry(4163, "CERT_SLAYER_ROCK_HAMMER", "cert_slayer_rock_hammer", "objtypes"),
            new GamevalEntry(4164, "SLAYER_FACEMASK", "Facemask", "objtypes"),
            new GamevalEntry(4165, "CERT_SLAYER_FACEMASK", "cert_slayer_facemask", "objtypes"),
            new GamevalEntry(4166, "SLAYER_EARMUFFS", "Earmuffs", "objtypes"),
            new GamevalEntry(4167, "CERT_SLAYER_EARMUFFS", "cert_slayer_earmuffs", "objtypes"),
            new GamevalEntry(4168, "SLAYER_NOSEPEG", "Nose peg", "objtypes"),
            new GamevalEntry(4169, "CERT_SLAYER_NOSEPEG", "cert_slayer_nosepeg", "objtypes"),
            new GamevalEntry(4170, "SLAYER_STAFF", "Slayer's staff", "objtypes"),
            new GamevalEntry(4171, "CERT_SLAYER_STAFF", "cert_slayer_staff", "objtypes"),
            new GamevalEntry(4172, "SLAYER_BROAD_ARROWS_5", "slayer_broad_arrows_5", "objtypes"),
            new GamevalEntry(4173, "SLAYER_BROAD_ARROWS_4", "slayer_broad_arrows_4", "objtypes"),
            new GamevalEntry(4174, "SLAYER_BROAD_ARROWS_3", "slayer_broad_arrows_3", "objtypes"),
            new GamevalEntry(4175, "SLAYER_BROAD_ARROWS_2", "slayer_broad_arrows_2", "objtypes"),
            new GamevalEntry(4176, "_50_MAGIC_DART", "ZA magic dart of slaying", "objtypes"),
            new GamevalEntry(4177, "WAA_HELPER", "waa_helper", "objtypes"),
            new GamevalEntry(4178, "CERT_WAA_HELPER", "Abyssal whip", "objtypes"),
            new GamevalEntry(4179, "WAA_STICK", "Stick", "objtypes"),
            new GamevalEntry(4180, "CERT_WAA_STICK", "1 Dragon platelegs", "objtypes"),
            new GamevalEntry(4181, "WEREWOLF_SLIDE_HOLD", "Mouth grip", "objtypes"),
            new GamevalEntry(4182, "CERT_WEREWOLF_SLIDE_HOLD", "1( W?5 W?!- Goutweed", "objtypes"),
            new GamevalEntry(4183, "FENK_STAR_AMULET", "Star amulet", "objtypes"),
            new GamevalEntry(4184, "FENK_MAUSOLEUM_KEY", "Cavern key", "objtypes"),
            new GamevalEntry(4185, "FENK_TOWER_KEY", "Tower key", "objtypes"),
            new GamevalEntry(4186, "FENK_SHED_KEY", "Shed key", "objtypes"),
            new GamevalEntry(4187, "FENK_MARBLE_AMULET", "X T 0 Marble amulet", "objtypes"),
            new GamevalEntry(4188, "FENK_OBSIDIAN_AMULET", "X T 0 Obsidian amulet", "objtypes"),
            new GamevalEntry(4189, "FENK_CANE", "Garden cane", "objtypes"),
            new GamevalEntry(4190, "FENK_BRUSH0", "Garden brush", "objtypes"),
            new GamevalEntry(4191, "FENK_BRUSH1", "Extended brush", "objtypes"),
            new GamevalEntry(4192, "FENK_BRUSH2", "Extended brush", "objtypes"),
            new GamevalEntry(4193, "FENK_BRUSH3", "Extended brush", "objtypes"),
            new GamevalEntry(4194, "FENK_TORSO", "Torso", "objtypes"),
            new GamevalEntry(4195, "FENK_ARMS", "Arms", "objtypes"),
            new GamevalEntry(4196, "FENK_LEGS", "Legs", "objtypes"),
            new GamevalEntry(4197, "FENK_HEAD_EMPTY", "Decapitated head", "objtypes"),
            new GamevalEntry(4198, "FENK_HEAD_FULL", "8 Decapitated head", "objtypes"),
            new GamevalEntry(4199, "FENK_BRAIN", "Pickled brain", "objtypes"),
            new GamevalEntry(4200, "FENK_LIGHTNING_MOULD", "Conductor mould", "objtypes"),
            new GamevalEntry(4201, "FENK_CONDUCTOR", "Conductor", "objtypes"),
            new GamevalEntry(4202, "RING_OF_CHAROS", "Ring of charos", "objtypes"),
            new GamevalEntry(4203, "FENK_JOURNAL", "Journal", "objtypes"),
            new GamevalEntry(4204, "FENK_LETTER", "Letter", "objtypes"),
            new GamevalEntry(4205, "ROVING_OLD_CONSECRATION_SEED", "Consecration seed", "objtypes"),
            new GamevalEntry(4206, "ROVING_NEW_CONSECRATION_SEED", "Consecration seed", "objtypes"),
            new GamevalEntry(4207, "CRYSTAL_SEED_OLD", "Crystal weapon seed", "objtypes"),
            new GamevalEntry(4208, "CERT_CRYSTAL_SEED_OLD", "cert_crystal_seed_old", "objtypes"),
            new GamevalEntry(4209, "ROVING_CADARN_BOOK", "Cadarn lineage", "objtypes"),
            new GamevalEntry(4210, "CERT_ROVING_CADARN_BOOK", "cert_roving_cadarn_book", "objtypes"),
            new GamevalEntry(4211, "ROVING_ELF_CRYSTAL", "Elf crystal", "objtypes"),
            new GamevalEntry(4212, "ROVING_CRYSTAL_BOW_NEW", "New crystal bow", "objtypes"),
            new GamevalEntry(4213, "CERT_ROVING_CRYSTAL_BOW_NEW", "New crystal bow", "objtypes"),
            new GamevalEntry(4214, "ROVING_CRYSTAL_BOW_1000", "Crystal bow full", "objtypes"),
            new GamevalEntry(4215, "ROVING_CRYSTAL_BOW_900", "Crystal bow 9/10", "objtypes"),
            new GamevalEntry(4216, "ROVING_CRYSTAL_BOW_800", "Crystal bow 8/10", "objtypes"),
            new GamevalEntry(4217, "ROVING_CRYSTAL_BOW_700", "Crystal bow 7/10", "objtypes"),
            new GamevalEntry(4218, "ROVING_CRYSTAL_BOW_600", "Crystal bow 6/10", "objtypes"),
            new GamevalEntry(4219, "ROVING_CRYSTAL_BOW_500", "Crystal bow 5/10", "objtypes"),
            new GamevalEntry(4220, "ROVING_CRYSTAL_BOW_400", "Crystal bow 4/10", "objtypes"),
            new GamevalEntry(4221, "ROVING_CRYSTAL_BOW_300", "Crystal bow 3/10", "objtypes"),
            new GamevalEntry(4222, "ROVING_CRYSTAL_BOW_200", "Crystal bow 2/10", "objtypes"),
            new GamevalEntry(4223, "ROVING_CRYSTAL_BOW_100", "Crystal bow 1/10", "objtypes"),
            new GamevalEntry(4224, "ROVING_CRYSTAL_SHIELD_NEW", "New crystal shield", "objtypes"),
            new GamevalEntry(4225, "ROVING_CRYSTAL_SHIELD_1000", "Crystal shield full", "objtypes"),
            new GamevalEntry(4226, "ROVING_CRYSTAL_SHIELD_900", "Crystal shield 9/10", "objtypes"),
            new GamevalEntry(4227, "ROVING_CRYSTAL_SHIELD_800", "Crystal shield 8/10", "objtypes"),
            new GamevalEntry(4228, "ROVING_CRYSTAL_SHIELD_700", "Crystal shield 7/10", "objtypes"),
            new GamevalEntry(4229, "ROVING_CRYSTAL_SHIELD_600", "Crystal shield 6/10", "objtypes"),
            new GamevalEntry(4230, "ROVING_CRYSTAL_SHIELD_500", "Crystal shield 5/10", "objtypes"),
            new GamevalEntry(4231, "ROVING_CRYSTAL_SHIELD_400", "Crystal shield 4/10", "objtypes"),
            new GamevalEntry(4232, "ROVING_CRYSTAL_SHIELD_300", "Crystal shield 3/10", "objtypes"),
            new GamevalEntry(4233, "ROVING_CRYSTAL_SHIELD_200", "Crystal shield 2/10", "objtypes"),
            new GamevalEntry(4234, "ROVING_CRYSTAL_SHIELD_100", "Crystal shield 1/10", "objtypes"),
            new GamevalEntry(4235, "CERT_ROVING_CRYSTAL_SHIELD_NEW", "New crystal shield", "objtypes"),
            new GamevalEntry(4236, "OAK_LONGBOW_SIGNED", "Signed oak bow", "objtypes"),
            new GamevalEntry(4237, "BOWL_NETTLEWATER", "Nettle-water", "objtypes"),
            new GamevalEntry(4238, "ECTOPLASM_PUDDLE", "Puddle of slime", "objtypes"),
            new GamevalEntry(4239, "BOWL_NETTLETEA", "Nettle tea", "objtypes"),
            new GamevalEntry(4240, "BOWL_NETTLETEA_MILKY", "Nettle tea", "objtypes"),
            new GamevalEntry(4241, "NETTLES_PICKED", "Nettles", "objtypes"),
            new GamevalEntry(4242, "CUP_OF_NETTLETEA", "Cup of tea", "objtypes"),
            new GamevalEntry(4243, "CUP_OF_NETTLETEA_MILKY", "Cup of tea", "objtypes"),
            new GamevalEntry(4244, "CHINACUP_EMPTY", "Porcelain cup", "objtypes"),
            new GamevalEntry(4245, "CHINACUP_OF_NETTLETEA", "Cup of tea", "objtypes"),
            new GamevalEntry(4246, "CHINACUP_OF_NETTLETEA_MILKY", "Cup of tea", "objtypes"),
            new GamevalEntry(4247, "AHOY_ROBES_OF_NECROVARUS", "Mystical robes", "objtypes"),
            new GamevalEntry(4248, "AHOY_BOOK_OF_HARICANTO", "Book of Haricanto", "objtypes"),
            new GamevalEntry(4249, "AHOY_TRANSLATION_MANUAL", "Translation manual", "objtypes"),
            new GamevalEntry(4250, "AMULET_OF_GHOSTSPEAK_ENCHANTED", "Ghostspeak amulet", "objtypes"),
            new GamevalEntry(4251, "ECTOPHIAL", "Ectophial", "objtypes"),
            new GamevalEntry(4252, "ECTOPHIAL_EMPTY", "Ectophial", "objtypes"),
            new GamevalEntry(4253, "AHOY_TOY_BOAT", "Model ship", "objtypes"),
            new GamevalEntry(4254, "AHOY_TOY_BOAT_REPAIRED", "Model ship", "objtypes"),
            new GamevalEntry(4255, "POT_BONEMEAL", "Bonemeal", "objtypes"),
            new GamevalEntry(4256, "POT_BONEMEAL_BAT", "Bat bonemeal", "objtypes"),
            new GamevalEntry(4257, "POT_BONEMEAL_BIG", "Big bonemeal", "objtypes"),
            new GamevalEntry(4258, "POT_BONEMEAL_BURNT", "Burnt bonemeal", "objtypes"),
            new GamevalEntry(4259, "POT_BONEMEAL_BURNT_JOGRE", "Burnt jogre bonemeal", "objtypes"),
            new GamevalEntry(4260, "POT_BONEMEAL_BABYDRAGON", "Baby dragon bonemeal", "objtypes"),
            new GamevalEntry(4261, "POT_BONEMEAL_DRAGON", "Dragon bonemeal", "objtypes"),
            new GamevalEntry(4262, "POT_BONEMEAL_WOLF", "Wolf bonemeal", "objtypes"),
            new GamevalEntry(4263, "POT_BONEMEAL_SMALL_NINJA_MONKEY", "Small ninja bonemeal", "objtypes"),
            new GamevalEntry(4264, "POT_BONEMEAL_MEDIUM_NINJA_MONKEY", "Medium ninja bonemeal", "objtypes"),
            new GamevalEntry(4265, "POT_BONEMEAL_NORMAL_GORILLA_MONKEY", "Gorilla bonemeal", "objtypes"),
            new GamevalEntry(4266, "POT_BONEMEAL_BEARDED_GORILLA_MONKEY", "Bearded gorilla bonemeal", "objtypes"),
            new GamevalEntry(4267, "POT_BONEMEAL_NORMAL_MONKEY", "Monkey bonemeal", "objtypes"),
            new GamevalEntry(4268, "POT_BONEMEAL_SMALL_ZOMBIE_MONKEY", "Small zombie monkey bonemeal", "objtypes"),
            new GamevalEntry(4269, "POT_BONEMEAL_LARGE_ZOMBIE_MONKEY", "Large zombie monkey bonemeal", "objtypes"),
            new GamevalEntry(4270, "POT_BONEMEAL_SKELETON", "Skeleton bonemeal", "objtypes"),
            new GamevalEntry(4271, "POT_BONEMEAL_JOGRE", "Jogre bonemeal", "objtypes"),
            new GamevalEntry(4272, "AHOY_BONE_KEY", "Bone key", "objtypes"),
            new GamevalEntry(4273, "AHOY_CHEST_KEY", "Chest key", "objtypes"),
            new GamevalEntry(4274, "AHOY_MAP_SCRAP_1", "Map scrap", "objtypes"),
            new GamevalEntry(4275, "AHOY_MAP_SCRAP_2", "Map scrap", "objtypes"),
            new GamevalEntry(4276, "AHOY_MAP_SCRAP_3", "Map scrap", "objtypes"),
            new GamevalEntry(4277, "AHOY_MAP_COMPLETE", "Treasure map", "objtypes"),
            new GamevalEntry(4278, "ECTOTOKEN", "Ecto-token", "objtypes"),
            new GamevalEntry(4279, "ECTOTOKEN_2", "ectotoken_2", "objtypes"),
            new GamevalEntry(4280, "CERT_ECTOTOKEN_2", "cert_ectotoken_2", "objtypes"),
            new GamevalEntry(4281, "ECTOTOKEN_3", "ectotoken_3", "objtypes"),
            new GamevalEntry(4282, "CERT_ECTOTOKEN_3", "cert_ectotoken_3", "objtypes"),
            new GamevalEntry(4283, "AHOY_PETITION", "Petition form", "objtypes"),
            new GamevalEntry(4284, "AHOY_BEDSHEET", "Bedsheet", "objtypes"),
            new GamevalEntry(4285, "AHOY_BEDSHEETGREEN", "Bedsheet", "objtypes"),
            new GamevalEntry(4286, "BUCKET_ECTOPLASM", "Bucket of slime", "objtypes"),
            new GamevalEntry(4287, "RAW_BEEF_UNDEAD", "Raw beef", "objtypes"),
            new GamevalEntry(4288, "CERT_RAW_BEEF_UNDEAD", "cert_raw_beef_undead", "objtypes"),
            new GamevalEntry(4289, "RAW_CHICKEN_UNDEAD", "Raw chicken", "objtypes"),
            new GamevalEntry(4290, "CERT_RAW_CHICKEN_UNDEAD", "cert_raw_chicken_undead", "objtypes"),
            new GamevalEntry(4291, "COOKED_CHICKEN_UNDEAD", "Cooked chicken", "objtypes"),
            new GamevalEntry(4292, "CERT_COOKED_CHICKEN_UNDEAD", "cert_cooked_chicken_undead", "objtypes"),
            new GamevalEntry(4293, "COOKED_MEAT_UNDEAD", "Cooked meat", "objtypes"),
            new GamevalEntry(4294, "CERT_COOKED_MEAT_UNDEAD", "cert_cooked_meat_undead", "objtypes"),
            new GamevalEntry(4295, "PICKPOCKET_GUIDE_FHAM", "Female h.a.m.", "objtypes"),
            new GamevalEntry(4296, "CERT_PICKPOCKET_GUIDE_FHAM", "cert_pickpocket_guide_fham", "objtypes"),
            new GamevalEntry(4297, "PICKPOCKET_GUIDE_MHAM", "Male h.a.m.", "objtypes"),
            new GamevalEntry(4298, "HAM_SHIRT", "Ham shirt", "objtypes"),
            new GamevalEntry(4299, "CERT_HAM_SHIRT", "cert_ham_shirt", "objtypes"),
            new GamevalEntry(4300, "HAM_ROBE", "Ham robe", "objtypes"),
            new GamevalEntry(4301, "CERT_HAM_ROBE", "cert_ham_robe", "objtypes"),
            new GamevalEntry(4302, "HAM_HOOD", "Ham hood", "objtypes"),
            new GamevalEntry(4303, "CERT_HAM_HOOD", "cert_ham_hood", "objtypes"),
            new GamevalEntry(4304, "HAM_CLOAK", "Ham cloak", "objtypes"),
            new GamevalEntry(4305, "CERT_HAM_CLOAK", "cert_ham_cloak", "objtypes"),
            new GamevalEntry(4306, "HAM_BADGE", "Ham logo", "objtypes"),
            new GamevalEntry(4307, "CERT_HAM_BADGE", "cert_ham_badge", "objtypes"),
            new GamevalEntry(4308, "HAM_GLOVES", "Ham gloves", "objtypes"),
            new GamevalEntry(4309, "CERT_HAM_GLOVES", "cert_ham_gloves", "objtypes"),
            new GamevalEntry(4310, "HAM_BOOTS", "Ham boots", "objtypes"),
            new GamevalEntry(4311, "CERT_HAM_BOOTS", "cert_ham_boots", "objtypes"),
            new GamevalEntry(4312, "CERT_PICKPOCKET_GUIDE_MHAM", "cert_pickpocket_guide_mham", "objtypes"),
            new GamevalEntry(4313, "ROVING_CRYSTAL_BOOK", "Crystal singing for beginners", "objtypes"),
            new GamevalEntry(4314, "CERT_ROVING_CRYSTAL_BOOK", "cert_roving_crystal_book", "objtypes"),
            new GamevalEntry(4315, "WILDERNESS_CAPE_1", "Team-1 cape", "objtypes"),
            new GamevalEntry(4316, "CERT_WILDERNESS_CAPE_1", "cert_wilderness_cape_1", "objtypes"),
            new GamevalEntry(4317, "WILDERNESS_CAPE_2", "Team-2 cape", "objtypes"),
            new GamevalEntry(4318, "CERT_WILDERNESS_CAPE_2", "cert_wilderness_cape_2", "objtypes"),
            new GamevalEntry(4319, "WILDERNESS_CAPE_3", "Team-3 cape", "objtypes"),
            new GamevalEntry(4320, "CERT_WILDERNESS_CAPE_3", "cert_wilderness_cape_3", "objtypes"),
            new GamevalEntry(4321, "WILDERNESS_CAPE_4", "Team-4 cape", "objtypes"),
            new GamevalEntry(4322, "CERT_WILDERNESS_CAPE_4", "cert_wilderness_cape_4", "objtypes"),
            new GamevalEntry(4323, "WILDERNESS_CAPE_5", "Team-5 cape", "objtypes"),
            new GamevalEntry(4324, "CERT_WILDERNESS_CAPE_5", "cert_wilderness_cape_5", "objtypes"),
            new GamevalEntry(4325, "WILDERNESS_CAPE_6", "Team-6 cape", "objtypes"),
            new GamevalEntry(4326, "CERT_WILDERNESS_CAPE_6", "cert_wilderness_cape_6", "objtypes"),
            new GamevalEntry(4327, "WILDERNESS_CAPE_7", "Team-7 cape", "objtypes"),
            new GamevalEntry(4328, "CERT_WILDERNESS_CAPE_7", "cert_wilderness_cape_7", "objtypes"),
            new GamevalEntry(4329, "WILDERNESS_CAPE_8", "Team-8 cape", "objtypes"),
            new GamevalEntry(4330, "CERT_WILDERNESS_CAPE_8", "cert_wilderness_cape_8", "objtypes"),
            new GamevalEntry(4331, "WILDERNESS_CAPE_9", "Team-9 cape", "objtypes"),
            new GamevalEntry(4332, "CERT_WILDERNESS_CAPE_9", "cert_wilderness_cape_9", "objtypes"),
            new GamevalEntry(4333, "WILDERNESS_CAPE_10", "Team-10 cape", "objtypes"),
            new GamevalEntry(4334, "CERT_WILDERNESS_CAPE_10", "cert_wilderness_cape_10", "objtypes"),
            new GamevalEntry(4335, "WILDERNESS_CAPE_11", "Team-11 cape", "objtypes"),
            new GamevalEntry(4336, "CERT_WILDERNESS_CAPE_11", "cert_wilderness_cape_11", "objtypes"),
            new GamevalEntry(4337, "WILDERNESS_CAPE_12", "Team-12 cape", "objtypes"),
            new GamevalEntry(4338, "CERT_WILDERNESS_CAPE_12", "cert_wilderness_cape_12", "objtypes"),
            new GamevalEntry(4339, "WILDERNESS_CAPE_13", "Team-13 cape", "objtypes"),
            new GamevalEntry(4340, "CERT_WILDERNESS_CAPE_13", "cert_wilderness_cape_13", "objtypes"),
            new GamevalEntry(4341, "WILDERNESS_CAPE_14", "Team-14 cape", "objtypes"),
            new GamevalEntry(4342, "CERT_WILDERNESS_CAPE_14", "cert_wilderness_cape_14", "objtypes"),
            new GamevalEntry(4343, "WILDERNESS_CAPE_15", "Team-15 cape", "objtypes"),
            new GamevalEntry(4344, "CERT_WILDERNESS_CAPE_15", "cert_wilderness_cape_15", "objtypes"),
            new GamevalEntry(4345, "WILDERNESS_CAPE_16", "Team-16 cape", "objtypes"),
            new GamevalEntry(4346, "CERT_WILDERNESS_CAPE_16", "cert_wilderness_cape_16", "objtypes"),
            new GamevalEntry(4347, "WILDERNESS_CAPE_17", "Team-17 cape", "objtypes"),
            new GamevalEntry(4348, "CERT_WILDERNESS_CAPE_17", "cert_wilderness_cape_17", "objtypes"),
            new GamevalEntry(4349, "WILDERNESS_CAPE_18", "Team-18 cape", "objtypes"),
            new GamevalEntry(4350, "CERT_WILDERNESS_CAPE_18", "cert_wilderness_cape_18", "objtypes"),
            new GamevalEntry(4351, "WILDERNESS_CAPE_19", "Team-19 cape", "objtypes"),
            new GamevalEntry(4352, "CERT_WILDERNESS_CAPE_19", "cert_wilderness_cape_19", "objtypes"),
            new GamevalEntry(4353, "WILDERNESS_CAPE_20", "Team-20 cape", "objtypes"),
            new GamevalEntry(4354, "CERT_WILDERNESS_CAPE_20", "cert_wilderness_cape_20", "objtypes"),
            new GamevalEntry(4355, "WILDERNESS_CAPE_21", "Team-21 cape", "objtypes"),
            new GamevalEntry(4356, "CERT_WILDERNESS_CAPE_21", "cert_wilderness_cape_21", "objtypes"),
            new GamevalEntry(4357, "WILDERNESS_CAPE_22", "Team-22 cape", "objtypes"),
            new GamevalEntry(4358, "CERT_WILDERNESS_CAPE_22", "cert_wilderness_cape_22", "objtypes"),
            new GamevalEntry(4359, "WILDERNESS_CAPE_23", "Team-23 cape", "objtypes"),
            new GamevalEntry(4360, "CERT_WILDERNESS_CAPE_23", "cert_wilderness_cape_23", "objtypes"),
            new GamevalEntry(4361, "WILDERNESS_CAPE_24", "Team-24 cape", "objtypes"),
            new GamevalEntry(4362, "CERT_WILDERNESS_CAPE_24", "cert_wilderness_cape_24", "objtypes"),
            new GamevalEntry(4363, "WILDERNESS_CAPE_25", "Team-25 cape", "objtypes"),
            new GamevalEntry(4364, "CERT_WILDERNESS_CAPE_25", "cert_wilderness_cape_25", "objtypes"),
            new GamevalEntry(4365, "WILDERNESS_CAPE_26", "Team-26 cape", "objtypes"),
            new GamevalEntry(4366, "CERT_WILDERNESS_CAPE_26", "cert_wilderness_cape_26", "objtypes"),
            new GamevalEntry(4367, "WILDERNESS_CAPE_27", "Team-27 cape", "objtypes"),
            new GamevalEntry(4368, "CERT_WILDERNESS_CAPE_27", "cert_wilderness_cape_27", "objtypes"),
            new GamevalEntry(4369, "WILDERNESS_CAPE_28", "Team-28 cape", "objtypes"),
            new GamevalEntry(4370, "CERT_WILDERNESS_CAPE_28", "cert_wilderness_cape_28", "objtypes"),
            new GamevalEntry(4371, "WILDERNESS_CAPE_29", "Team-29 cape", "objtypes"),
            new GamevalEntry(4372, "CERT_WILDERNESS_CAPE_29", "cert_wilderness_cape_29", "objtypes"),
            new GamevalEntry(4373, "WILDERNESS_CAPE_30", "Team-30 cape", "objtypes"),
            new GamevalEntry(4374, "CERT_WILDERNESS_CAPE_30", "cert_wilderness_cape_30", "objtypes"),
            new GamevalEntry(4375, "WILDERNESS_CAPE_31", "LE? ?FT Team-31 cape", "objtypes"),
            new GamevalEntry(4376, "CERT_WILDERNESS_CAPE_31", "cert_wilderness_cape_31", "objtypes"),
            new GamevalEntry(4377, "WILDERNESS_CAPE_32", "LE? ?FT Team-32 cape", "objtypes"),
            new GamevalEntry(4378, "CERT_WILDERNESS_CAPE_32", "cert_wilderness_cape_32", "objtypes"),
            new GamevalEntry(4379, "WILDERNESS_CAPE_33", "LE? ?FT Team-33 cape", "objtypes"),
            new GamevalEntry(4380, "CERT_WILDERNESS_CAPE_33", "cert_wilderness_cape_33", "objtypes"),
            new GamevalEntry(4381, "WILDERNESS_CAPE_34", "LE? ?FT Team-34 cape", "objtypes"),
            new GamevalEntry(4382, "CERT_WILDERNESS_CAPE_34", "cert_wilderness_cape_34", "objtypes"),
            new GamevalEntry(4383, "WILDERNESS_CAPE_35", "LE? ?FT Team-35 cape", "objtypes"),
            new GamevalEntry(4384, "CERT_WILDERNESS_CAPE_35", "cert_wilderness_cape_35", "objtypes"),
            new GamevalEntry(4385, "WILDERNESS_CAPE_36", "LE? ?FT Team-36 cape", "objtypes"),
            new GamevalEntry(4386, "CERT_WILDERNESS_CAPE_36", "cert_wilderness_cape_36", "objtypes"),
            new GamevalEntry(4387, "WILDERNESS_CAPE_37", "LE? ?FT Team-37 cape", "objtypes"),
            new GamevalEntry(4388, "CERT_WILDERNESS_CAPE_37", "cert_wilderness_cape_37", "objtypes"),
            new GamevalEntry(4389, "WILDERNESS_CAPE_38", "LE? ?FT Team-38 cape", "objtypes"),
            new GamevalEntry(4390, "CERT_WILDERNESS_CAPE_38", "cert_wilderness_cape_38", "objtypes"),
            new GamevalEntry(4391, "WILDERNESS_CAPE_39", "LE? ?FT Team-39 cape", "objtypes"),
            new GamevalEntry(4392, "CERT_WILDERNESS_CAPE_39", "cert_wilderness_cape_39", "objtypes"),
            new GamevalEntry(4393, "WILDERNESS_CAPE_40", "LE? ?FT Team-40 cape", "objtypes"),
            new GamevalEntry(4394, "CERT_WILDERNESS_CAPE_40", "cert_wilderness_cape_40", "objtypes"),
            new GamevalEntry(4395, "WILDERNESS_CAPE_41", "L ? ' Team-41 cape", "objtypes"),
            new GamevalEntry(4396, "CERT_WILDERNESS_CAPE_41", "cert_wilderness_cape_41", "objtypes"),
            new GamevalEntry(4397, "WILDERNESS_CAPE_42", "L ? ' Team-42 cape", "objtypes"),
            new GamevalEntry(4398, "CERT_WILDERNESS_CAPE_42", "cert_wilderness_cape_42", "objtypes"),
            new GamevalEntry(4399, "WILDERNESS_CAPE_43", "L ? ' Team-43 cape", "objtypes"),
            new GamevalEntry(4400, "CERT_WILDERNESS_CAPE_43", "cert_wilderness_cape_43", "objtypes"),
            new GamevalEntry(4401, "WILDERNESS_CAPE_44", "L ? ' Team-44 cape", "objtypes"),
            new GamevalEntry(4402, "CERT_WILDERNESS_CAPE_44", "cert_wilderness_cape_44", "objtypes"),
            new GamevalEntry(4403, "WILDERNESS_CAPE_45", "L ? ' Team-45 cape", "objtypes"),
            new GamevalEntry(4404, "CERT_WILDERNESS_CAPE_45", "cert_wilderness_cape_45", "objtypes"),
            new GamevalEntry(4405, "WILDERNESS_CAPE_46", "L ? ' Team-46 cape", "objtypes"),
            new GamevalEntry(4406, "CERT_WILDERNESS_CAPE_46", "cert_wilderness_cape_46", "objtypes"),
            new GamevalEntry(4407, "WILDERNESS_CAPE_47", "L ? ' Team-47 cape", "objtypes"),
            new GamevalEntry(4408, "CERT_WILDERNESS_CAPE_47", "cert_wilderness_cape_47", "objtypes"),
            new GamevalEntry(4409, "WILDERNESS_CAPE_48", "L ? ' Team-48 cape", "objtypes"),
            new GamevalEntry(4410, "CERT_WILDERNESS_CAPE_48", "cert_wilderness_cape_48", "objtypes"),
            new GamevalEntry(4411, "WILDERNESS_CAPE_49", "L ? ' Team-49 cape", "objtypes"),
            new GamevalEntry(4412, "CERT_WILDERNESS_CAPE_49", "cert_wilderness_cape_49", "objtypes"),
            new GamevalEntry(4413, "WILDERNESS_CAPE_50", "L ? ' Team-50 cape", "objtypes"),
            new GamevalEntry(4414, "CERT_WILDERNESS_CAPE_50", "cert_wilderness_cape_50", "objtypes"),
            new GamevalEntry(4415, "FAVOUR_JUNGLEFORESTERAXE_BLUNT", "Blunt axe", "objtypes"),
            new GamevalEntry(4416, "FAVOUR_HERBAL_TINCTURE", "Herbal tincture", "objtypes"),
            new GamevalEntry(4417, "CUP_GUTHIX_REST_4", "Guthix rest(4)", "objtypes"),
            new GamevalEntry(4418, "CERT_CUP_GUTHIX_REST_4", "cert_cup_guthix_rest_4", "objtypes"),
            new GamevalEntry(4419, "CUP_GUTHIX_REST_3", "Guthix rest(3)", "objtypes"),
            new GamevalEntry(4420, "CERT_CUP_GUTHIX_REST_3", "cert_cup_guthix_rest_3", "objtypes"),
            new GamevalEntry(4421, "CUP_GUTHIX_REST_2", "Guthix rest(2)", "objtypes"),
            new GamevalEntry(4422, "CERT_CUP_GUTHIX_REST_2", "cert_cup_guthix_rest_2", "objtypes"),
            new GamevalEntry(4423, "CUP_GUTHIX_REST_1", "Guthix rest(1)", "objtypes"),
            new GamevalEntry(4424, "CERT_CUP_GUTHIX_REST_1", "cert_cup_guthix_rest_1", "objtypes"),
            new GamevalEntry(4425, "FAVOUR_MATRESS_STODGY", "Stodgy mattress", "objtypes"),
            new GamevalEntry(4426, "FAVOUR_MATRESS_COMFY", "Comfy mattress", "objtypes"),
            new GamevalEntry(4427, "FAVOUR_IRON_OXIDE", "Iron oxide", "objtypes"),
            new GamevalEntry(4428, "FAVOUR_ANIMATE_ROCK", "Animate rock scroll", "objtypes"),
            new GamevalEntry(4429, "FAVOUR_DIRECTIONALS_BROKEN", "Broken vane part", "objtypes"),
            new GamevalEntry(4430, "FAVOUR_DIRECTIONALS_FIXED", "Directionals", "objtypes"),
            new GamevalEntry(4431, "FAVOUR_ORNAMENT_BROKEN", "Broken vane part", "objtypes"),
            new GamevalEntry(4432, "FAVOUR_ORNAMENT_FIXED", "Ornament", "objtypes"),
            new GamevalEntry(4433, "FAVOUR_PILLAR_BROKEN", "Broken vane part", "objtypes"),
            new GamevalEntry(4434, "FAVOUR_PILLAR_FIXED", "Weathervane pillar", "objtypes"),
            new GamevalEntry(4435, "FAVOUR_WEATHER_REPORT", "Weather report", "objtypes"),
            new GamevalEntry(4436, "FAVOUR_AIRTIGHT_POT", "Airtight pot", "objtypes"),
            new GamevalEntry(4437, "CERT_FAVOUR_AIRTIGHT_POT", "cert_favour_airtight_pot", "objtypes"),
            new GamevalEntry(4438, "POTLID_UNFIRED", "Unfired pot lid", "objtypes"),
            new GamevalEntry(4439, "CERT_POTLID_UNFIRED", "cert_potlid_unfired", "objtypes"),
            new GamevalEntry(4440, "POTLID", "Pot lid", "objtypes"),
            new GamevalEntry(4441, "CERT_POTLID", "cert_potlid", "objtypes"),
            new GamevalEntry(4442, "FAVOUR_BREATHING_SALTS", "Breathing salts", "objtypes"),
            new GamevalEntry(4443, "FAVOUR_CHICKEN_CAGE", "Chicken cage", "objtypes"),
            new GamevalEntry(4444, "FAVOUR_JUNGLEFORESTERAXE_SHARP", "Sharpened axe", "objtypes"),
            new GamevalEntry(4445, "FAVOUR_MAHOGANY_LOG", "Red mahogany log", "objtypes"),
            new GamevalEntry(4446, "FAVOUR_KEY_RING", "Steel key ring", "objtypes"),
            new GamevalEntry(4447, "THOSF_REWARD_LAMP", "Antique lamp", "objtypes"),
            new GamevalEntry(4448, "FAVOUR_DUMMY_KEY", "favour_dummy_key", "objtypes"),
            new GamevalEntry(4449, "CERT_FAVOUR_DUMMY_KEY", "cert_favour_dummy_key", "objtypes"),
            new GamevalEntry(4450, "FAVOUR_DEFAULT_KEY_OUTLINE", "favour_default_key_outline", "objtypes"),
            new GamevalEntry(4451, "CERT_FAVOUR_DEFAULT_KEY_OUTLINE", "cert_favour_default_key_outline", "objtypes"),
            new GamevalEntry(4452, "FAVOUR_TROLL_KEY_OUTLINE", "favour_troll_key_outline", "objtypes"),
            new GamevalEntry(4453, "CERT_FAVOUR_TROLL_KEY_OUTLINE", "cert_favour_troll_key_outline", "objtypes"),
            new GamevalEntry(4454, "FAVOUR_SHADE_KEY_OUTLINE", "favour_shade_key_outline", "objtypes"),
            new GamevalEntry(4455, "CERT_FAVOUR_SHADE_KEY_OUTLINE", "cert_favour_shade_key_outline", "objtypes"),
            new GamevalEntry(4456, "BOWL_HOT_WATER", "Bowl of hot water", "objtypes"),
            new GamevalEntry(4457, "CERT_BOWL_HOT_WATER", "cert_bowl_hot_water", "objtypes"),
            new GamevalEntry(4458, "CUP_WATER", "Cup of water", "objtypes"),
            new GamevalEntry(4459, "CERT_CUP_WATER", "cert_cup_water", "objtypes"),
            new GamevalEntry(4460, "CUP_HOT_WATER", "Cup of hot water", "objtypes"),
            new GamevalEntry(4461, "CERT_CUP_HOT_WATER", "cert_cup_hot_water", "objtypes"),
            new GamevalEntry(4462, "FAVOUR_HERBTEA_RUINED", "Ruined herb tea", "objtypes"),
            new GamevalEntry(4463, "CERT_FAVOUR_HERBTEA_RUINED", "cert_favour_herbtea_ruined", "objtypes"),
            new GamevalEntry(4464, "FAVOUR_CUP_HARRALANDER", "Herb tea mix", "objtypes"),
            new GamevalEntry(4465, "CERT_FAVOUR_CUP_HARRALANDER", "cert_favour_cup_harralander", "objtypes"),
            new GamevalEntry(4466, "FAVOUR_CUP_GUAM", "Herb tea mix", "objtypes"),
            new GamevalEntry(4467, "CERT_FAVOUR_CUP_GUAM", "cert_favour_cup_guam", "objtypes"),
            new GamevalEntry(4468, "FAVOUR_CUP_MARRENTILL", "Herb tea mix", "objtypes"),
            new GamevalEntry(4469, "CERT_FAVOUR_CUP_MARRENTILL", "cert_favour_cup_marrentill", "objtypes"),
            new GamevalEntry(4470, "FAVOUR_CUP_HARRALANDER_MARRENTILL", "Herb tea mix", "objtypes"),
            new GamevalEntry(4471, "CERT_FAVOUR_CUP_HARRALANDER_MARRENTILL", "cert_favour_cup_harralander_marrentill", "objtypes"),
            new GamevalEntry(4472, "FAVOUR_CUP_HARRALANDER_GUAM", "Herb tea mix", "objtypes"),
            new GamevalEntry(4473, "CERT_FAVOUR_CUP_HARRALANDER_GUAM", "cert_favour_cup_harralander_guam", "objtypes"),
            new GamevalEntry(4474, "FAVOUR_CUP_GUAM_GUAM", "Herb tea mix", "objtypes"),
            new GamevalEntry(4475, "CERT_FAVOUR_CUP_GUAM_GUAM", "cert_favour_cup_guam_guam", "objtypes"),
            new GamevalEntry(4476, "FAVOUR_CUP_GUAM_MARRENTILL", "Herb tea mix", "objtypes"),
            new GamevalEntry(4477, "CERT_FAVOUR_CUP_GUAM_MARRENTILL", "cert_favour_cup_guam_marrentill", "objtypes"),
            new GamevalEntry(4478, "FAVOUR_CUP_HARRALANDER_MARRENTILL_GUAM", "Herb tea mix", "objtypes"),
            new GamevalEntry(4479, "CERT_FAVOUR_CUP_HARRALANDER_MARRENTILL_GUAM", "cert_favour_cup_harralander_marrentill_guam", "objtypes"),
            new GamevalEntry(4480, "FAVOUR_CUP_GUAM_GUAM_MARRENTILL", "Herb tea mix", "objtypes"),
            new GamevalEntry(4481, "CERT_FAVOUR_CUP_GUAM_GUAM_MARRENTILL", "cert_favour_cup_guam_guam_marrentill", "objtypes"),
            new GamevalEntry(4482, "FAVOUR_CUP_GUAM_GUAM_HARRALANDER", "Herb tea mix", "objtypes"),
            new GamevalEntry(4483, "CERT_FAVOUR_CUP_GUAM_GUAM_HARRALANDER", "cert_favour_cup_guam_guam_harralander", "objtypes"),
            new GamevalEntry(4484, "MDAUGHTER_SAFETY_GUARANTEE", "Safety guarantee", "objtypes"),
            new GamevalEntry(4485, "MDAUGHTER_WHITE_PEARL_FRUIT", "White pearl", "objtypes"),
            new GamevalEntry(4486, "MDAUGHTER_WHITE_PEARL_SEED", "White pearl seed", "objtypes"),
            new GamevalEntry(4487, "MDAUGHTER_HALF_ROCK", "Half a rock", "objtypes"),
            new GamevalEntry(4488, "MDAUGHTER_DAUGHTER_CORPSE", "Corpse of woman", "objtypes"),
            new GamevalEntry(4489, "MDAUGHTER_NECKLACE", "Asleif's necklace", "objtypes"),
            new GamevalEntry(4490, "MDAUGHTER_MUD", "Mud", "objtypes"),
            new GamevalEntry(4491, "CERT_MDAUGHTER_MUD", "cert_mdaughter_mud", "objtypes"),
            new GamevalEntry(4492, "MDAUGHTER_ROCK", "Muddy rock", "objtypes"),
            new GamevalEntry(4493, "CERT_MDAUGHTER_ROCK", "cert_mdaughter_rock", "objtypes"),
            new GamevalEntry(4494, "MDAUGHTER_STICK", "Pole", "objtypes"),
            new GamevalEntry(4495, "CERT_MDAUGHTER_STICK", "Null", "objtypes"),
            new GamevalEntry(4496, "MDAUGHTER_BROKEN_STICK", "Broken pole", "objtypes"),
            new GamevalEntry(4497, "CERT_MDAUGHTER_BROKEN_STICK", "cert_mdaughter_broken_stick", "objtypes"),
            new GamevalEntry(4498, "MDAUGHTER_ROPE", "Rope", "objtypes"),
            new GamevalEntry(4499, "CERT_MDAUGHTER_ROPE", "cert_mdaughter_rope", "objtypes"),
            new GamevalEntry(4500, "MDAUGHTER_POLEVAULT", "Pole", "objtypes"),
            new GamevalEntry(4501, "CERT_MDAUGHTER_POLEVAULT", "Null", "objtypes"),
            new GamevalEntry(4502, "MDAUGHTER_BEAR_HELMET", "Bearhead", "objtypes"),
            new GamevalEntry(4503, "CASTLEWARS_SWORD_2", "Decorative sword", "objtypes"),
            new GamevalEntry(4504, "CASTLEWARS_ARMOUR_BODY_2", "Decorative armour", "objtypes"),
            new GamevalEntry(4505, "CASTLEWARS_ARMOUR_LEGS_2", "Decorative armour", "objtypes"),
            new GamevalEntry(4506, "CASTLEWARS_MED_HELM_2", "Decorative helm", "objtypes"),
            new GamevalEntry(4507, "CASTLEWARS_SHIELD_2", "Decorative shield", "objtypes"),
            new GamevalEntry(4508, "CASTLEWARS_SWORD_3", "Decorative sword", "objtypes"),
            new GamevalEntry(4509, "CASTLEWARS_ARMOUR_BODY_3", "Decorative armour", "objtypes"),
            new GamevalEntry(4510, "CASTLEWARS_ARMOUR_LEGS_3", "Decorative armour", "objtypes"),
            new GamevalEntry(4511, "CASTLEWARS_MED_HELM_3", "Decorative helm", "objtypes"),
            new GamevalEntry(4512, "CASTLEWARS_SHIELD_3", "Decorative shield", "objtypes"),
            new GamevalEntry(4513, "CASTLEWARS_HOOD_SARADOMIN_PRIZE", "Castlewars hood", "objtypes"),
            new GamevalEntry(4514, "CASTLEWARS_CLOAK_SARADOMIN_PRIZE", "Castlewars cloak", "objtypes"),
            new GamevalEntry(4515, "CASTLEWARS_HOOD_ZAMORAK_PRIZE", "Castlewars hood", "objtypes"),
            new GamevalEntry(4516, "CASTLEWARS_CLOAK_ZAMORAK_PRIZE", "Castlewars cloak", "objtypes"),
            new GamevalEntry(4517, "GIANT_FROG_LEGS", "Giant frog legs", "objtypes"),
            new GamevalEntry(4518, "CERT_GIANT_FROG_LEGS", "cert_giant_frog_legs", "objtypes"),
            new GamevalEntry(4519, "SWAMP_WALLBEAST", "Swamp wallbeast", "objtypes"),
            new GamevalEntry(4520, "SWAMP_CAVE_SLIME", "Swamp cave slime", "objtypes"),
            new GamevalEntry(4521, "SWAMP_CAVE_BUG", "Swamp cave bug", "objtypes"),
            new GamevalEntry(4522, "OIL_LAMP_UNLIT", "Oil lamp", "objtypes"),
            new GamevalEntry(4523, "CERT_OIL_LAMP_UNLIT", "cert_oil_lamp_unlit", "objtypes"),
            new GamevalEntry(4524, "OIL_LAMP_LIT", "Oil lamp", "objtypes"),
            new GamevalEntry(4525, "OIL_LAMP_EMPTY", "Empty oil lamp", "objtypes"),
            new GamevalEntry(4526, "CERT_OIL_LAMP_EMPTY", "cert_oil_lamp_empty", "objtypes"),
            new GamevalEntry(4527, "CANDLE_LANTERN_EMPTY", "Empty candle lantern", "objtypes"),
            new GamevalEntry(4528, "CERT_CANDLE_LANTERN_EMPTY", "cert_candle_lantern_empty", "objtypes"),
            new GamevalEntry(4529, "CANDLE_LANTERN_UNLIT", "Candle lantern", "objtypes"),
            new GamevalEntry(4530, "CERT_CANDLE_LANTERN_UNLIT", "cert_candle_lantern_unlit", "objtypes"),
            new GamevalEntry(4531, "CANDLE_LANTERN_LIT", "Candle lantern", "objtypes"),
            new GamevalEntry(4532, "CANDLE_LANTERN_BLACK_UNLIT", "Candle lantern", "objtypes"),
            new GamevalEntry(4533, "CERT_CANDLE_LANTERN_BLACK_UNLIT", "cert_candle_lantern_black_unlit", "objtypes"),
            new GamevalEntry(4534, "CANDLE_LANTERN_BLACK_LIT", "Candle lantern", "objtypes"),
            new GamevalEntry(4535, "OIL_LANTERN_EMPTY", "Empty oil lantern", "objtypes"),
            new GamevalEntry(4536, "CERT_OIL_LANTERN_EMPTY", "cert_oil_lantern_empty", "objtypes"),
            new GamevalEntry(4537, "OIL_LANTERN_UNLIT", "Oil lantern", "objtypes"),
            new GamevalEntry(4538, "CERT_OIL_LANTERN_UNLIT", "cert_oil_lantern_unlit", "objtypes"),
            new GamevalEntry(4539, "OIL_LANTERN_LIT", "Oil lantern", "objtypes"),
            new GamevalEntry(4540, "OIL_LANTERN_FRAME", "Oil lantern frame", "objtypes"),
            new GamevalEntry(4541, "CERT_OIL_LANTERN_FRAME", "cert_oil_lantern_frame", "objtypes"),
            new GamevalEntry(4542, "BULLSEYE_LANTERN_LENS", "Lantern lens", "objtypes"),
            new GamevalEntry(4543, "CERT_BULLSEYE_LANTERN_LENS", "cert_bullseye_lantern_lens", "objtypes"),
            new GamevalEntry(4544, "BULLSEYE_LANTERN_NOLENS", "Bullseye lantern (unf)", "objtypes"),
            new GamevalEntry(4545, "CERT_BULLSEYE_LANTERN_NOLENS", "cert_bullseye_lantern_nolens", "objtypes"),
            new GamevalEntry(4546, "BULLSEYE_LANTERN_EMPTY", "Bullseye lantern (empty)", "objtypes"),
            new GamevalEntry(4547, "CERT_BULLSEYE_LANTERN_EMPTY", "cert_bullseye_lantern_empty", "objtypes"),
            new GamevalEntry(4548, "BULLSEYE_LANTERN_UNLIT", "Bullseye lantern", "objtypes"),
            new GamevalEntry(4549, "CERT_BULLSEYE_LANTERN_UNLIT", "cert_bullseye_lantern_unlit", "objtypes"),
            new GamevalEntry(4550, "BULLSEYE_LANTERN_LIT", "Bullseye lantern", "objtypes"),
            new GamevalEntry(4551, "WALLBEAST_SPIKE_HELMET", "Spiny helmet", "objtypes"),
            new GamevalEntry(4552, "CERT_WALLBEAST_SPIKE_HELMET", "cert_wallbeast_spike_helmet", "objtypes"),
            new GamevalEntry(4553, "_74_TELEOTHER_LUMBRIDGE", "ZTeleports target to Lumbridge", "objtypes"),
            new GamevalEntry(4554, "_82_TELEOTHER_FALADOR", "ZTeleports target to Falador", "objtypes"),
            new GamevalEntry(4555, "_85_TELEPORT_BLOCK", "ZStops your target from teleporting", "objtypes"),
            new GamevalEntry(4556, "_90_TELEOTHER_CAMELOT", "ZTeleports target to Camelot", "objtypes"),
            new GamevalEntry(4557, "TELESCOPE_DUMMY", "telescope_dummy", "objtypes"),
            new GamevalEntry(4558, "EASTER_EGG_2005_LIGHTBLUE", "Blue sweets", "objtypes"),
            new GamevalEntry(4559, "EASTER_EGG_2005_DARKBLUE", "Deep blue sweets", "objtypes"),
            new GamevalEntry(4560, "EASTER_EGG_2005_WHITE", "White sweets", "objtypes"),
            new GamevalEntry(4561, "EASTER_EGG_2005_PURPLE", "Purple sweets", "objtypes"),
            new GamevalEntry(4562, "EASTER_EGG_2005_RED", "Red sweets", "objtypes"),
            new GamevalEntry(4563, "EASTER_EGG_2005_GREEN", "Green sweets", "objtypes"),
            new GamevalEntry(4564, "EASTER_EGG_2005_PINK", "Pink sweets", "objtypes"),
            new GamevalEntry(4565, "EASTER_BASKET_2005", "Easter basket", "objtypes"),
            new GamevalEntry(4566, "RUBBER_CHICKEN", "Rubber chicken", "objtypes"),
            new GamevalEntry(4567, "DWARF_GOLDROCK_HELMET", "Gold helmet", "objtypes"),
            new GamevalEntry(4568, "DWARF_ROCK_BOOK", "Dwarven lore", "objtypes"),
            new GamevalEntry(4569, "DWARF_ROCK_PAGE1", "Book page 1", "objtypes"),
            new GamevalEntry(4570, "DWARF_ROCK_PAGE2", "Book page 2", "objtypes"),
            new GamevalEntry(4571, "DWARF_ROCK_PAGE3", "Book page 3", "objtypes"),
            new GamevalEntry(4572, "DWARF_ROCK_PAGEX2", "Pages", "objtypes"),
            new GamevalEntry(4573, "DWARF_ROCK_PAGEX3", "Pages", "objtypes"),
            new GamevalEntry(4574, "DWARF_ROCK_BASE_SCHEMATIC", "Base schematics", "objtypes"),
            new GamevalEntry(4575, "DWARF_ROCK_SCHEMATIC1", "Schematic", "objtypes"),
            new GamevalEntry(4576, "DWARF_ROCK_SCHEMATIC2", "Schematics", "objtypes"),
            new GamevalEntry(4577, "DWARF_ROCK_SCHEMATIC3", "Schematics", "objtypes"),
            new GamevalEntry(4578, "DWARF_ROCK_SCHEMATIC_ASSEMBLED", "Schematic", "objtypes"),
            new GamevalEntry(4579, "DWARF_ROCK_CANNONBALL_GOLD", "Cannon ball", "objtypes"),
            new GamevalEntry(4580, "BLACK_SPEAR", "Black spear", "objtypes"),
            new GamevalEntry(4581, "CERT_BLACK_SPEAR", "cert_black_spear", "objtypes"),
            new GamevalEntry(4582, "BLACK_SPEAR_P", "Black spear(p)", "objtypes"),
            new GamevalEntry(4583, "CERT_BLACK_SPEAR_P", "cert_black_spear_p", "objtypes"),
            new GamevalEntry(4584, "TBWT_BLACK_SPEAR_KP", "Black spear(kp)", "objtypes"),
            new GamevalEntry(4585, "DRAGON_PLATESKIRT", "Dragon plateskirt", "objtypes"),
            new GamevalEntry(4586, "CERT_DRAGON_PLATESKIRT", "cert_dragon_plateskirt", "objtypes"),
            new GamevalEntry(4587, "DRAGON_SCIMITAR", "Dragon scimitar", "objtypes"),
            new GamevalEntry(4588, "CERT_DRAGON_SCIMITAR", "cert_dragon_scimitar", "objtypes"),
            new GamevalEntry(4589, "FEUD_MAYORS_HOUSE_KEYS", "Keys", "objtypes"),
            new GamevalEntry(4590, "FEUD_MAYORS_JEWELS", "Jewels", "objtypes"),
            new GamevalEntry(4591, "FEUD_KARIDIAN_TURBAN", "Kharidian headpiece", "objtypes"),
            new GamevalEntry(4592, "CERT_FEUD_KARIDIAN_TURBAN", "cert_feud_karidian_turban", "objtypes"),
            new GamevalEntry(4593, "FEUD_KARIDIAN_FAKEBEARD", "Fake beard", "objtypes"),
            new GamevalEntry(4594, "CERT_FEUD_KARIDIAN_FAKEBEARD", "cert_feud_karidian_fakebeard", "objtypes"),
            new GamevalEntry(4595, "FEUD_KARIDIAN_FAKEBEARD_AND_HAT", "Karidian disguise", "objtypes"),
            new GamevalEntry(4596, "CERT_FEUD_KARIDIAN_FAKEBEARD_AND_HAT", "cert_feud_karidian_fakebeard_and_hat", "objtypes"),
            new GamevalEntry(4597, "FEUD_FIB_HINT", "Note", "objtypes"),
            new GamevalEntry(4598, "FEUD_NOS_NOTE", "Note", "objtypes"),
            new GamevalEntry(4599, "BLACKJACK_OAK", "Oak blackjack", "objtypes"),
            new GamevalEntry(4600, "BLACKJACK_WILLOW", "X A( &? Willow blackjack", "objtypes"),
            new GamevalEntry(4601, "FEUD_CAMEL_POOH_BUCKET", "Ugthanki dung", "objtypes"),
            new GamevalEntry(4602, "FEUD_CAMEL_POISON_POOH_BUCKET", "Ugthanki dung", "objtypes"),
            new GamevalEntry(4603, "FEUD_CAMEL_RECEIPT", "Receipt", "objtypes"),
            new GamevalEntry(4604, "POISON_FROM_HAG", "Hag's poison", "objtypes"),
            new GamevalEntry(4605, "SNAKE_FLUTE", "Snake charm", "objtypes"),
            new GamevalEntry(4606, "BASKET_FOR_SNAKE", "Snake basket", "objtypes"),
            new GamevalEntry(4607, "BASKET_WITH_SNAKE", "Snake basket full", "objtypes"),
        };
    }

    static Optional<GamevalEntry> byId(int id) {
        for (GamevalEntry entry : entries()) {
            if (entry.id() == id) return Optional.of(entry);
        }
        return Optional.empty();
    }

}
