package net.titan.gamevals.internal;

import java.util.Optional;

import net.titan.gamevals.GamevalEntry;
import net.titan.gamevals.QuestEntry;

final class ItemIDEntries_15 {
    private ItemIDEntries_15() {}

    static GamevalEntry[] entries() {
        return new GamevalEntry[] {
            new GamevalEntry(7680, "ID_7680", "", "objtypes"),
            new GamevalEntry(7681, "GAME_BOOK", "Game book", "objtypes"),
            new GamevalEntry(7682, "HOOP", "Hoop", "objtypes"),
            new GamevalEntry(7683, "ID_7683", "", "objtypes"),
            new GamevalEntry(7684, "DART", "Dart", "objtypes"),
            new GamevalEntry(7685, "ID_7685", "", "objtypes"),
            new GamevalEntry(7686, "BOW_AND_ARROW", "Bow and arrow", "objtypes"),
            new GamevalEntry(7687, "ID_7687", "", "objtypes"),
            new GamevalEntry(7688, "KETTLE", "Kettle", "objtypes"),
            new GamevalEntry(7689, "ID_7689", "", "objtypes"),
            new GamevalEntry(7690, "FULL_KETTLE", "Full kettle", "objtypes"),
            new GamevalEntry(7691, "HOT_KETTLE", "Hot kettle", "objtypes"),
            new GamevalEntry(7692, "POT_OF_TEA_4", "Pot of tea (4)", "objtypes"),
            new GamevalEntry(7693, "ID_7693", "", "objtypes"),
            new GamevalEntry(7694, "POT_OF_TEA_3", "Pot of tea (3)", "objtypes"),
            new GamevalEntry(7695, "ID_7695", "", "objtypes"),
            new GamevalEntry(7696, "POT_OF_TEA_2", "Pot of tea (2)", "objtypes"),
            new GamevalEntry(7697, "ID_7697", "", "objtypes"),
            new GamevalEntry(7698, "POT_OF_TEA_1", "Pot of tea (1)", "objtypes"),
            new GamevalEntry(7699, "ID_7699", "", "objtypes"),
            new GamevalEntry(7700, "TEAPOT_WITH_LEAVES", "Teapot with leaves", "objtypes"),
            new GamevalEntry(7701, "ID_7701", "", "objtypes"),
            new GamevalEntry(7702, "TEAPOT", "Teapot", "objtypes"),
            new GamevalEntry(7703, "ID_7703", "", "objtypes"),
            new GamevalEntry(7704, "POT_OF_TEA_4_7704", "Pot of tea (4)", "objtypes"),
            new GamevalEntry(7705, "ID_7705", "", "objtypes"),
            new GamevalEntry(7706, "POT_OF_TEA_3_7706", "Pot of tea (3)", "objtypes"),
            new GamevalEntry(7707, "ID_7707", "", "objtypes"),
            new GamevalEntry(7708, "POT_OF_TEA_2_7708", "Pot of tea (2)", "objtypes"),
            new GamevalEntry(7709, "ID_7709", "", "objtypes"),
            new GamevalEntry(7710, "POT_OF_TEA_1_7710", "Pot of tea (1)", "objtypes"),
            new GamevalEntry(7711, "ID_7711", "", "objtypes"),
            new GamevalEntry(7712, "TEAPOT_WITH_LEAVES_7712", "Teapot with leaves", "objtypes"),
            new GamevalEntry(7713, "ID_7713", "", "objtypes"),
            new GamevalEntry(7714, "TEAPOT_7714", "Teapot", "objtypes"),
            new GamevalEntry(7715, "ID_7715", "", "objtypes"),
            new GamevalEntry(7716, "POT_OF_TEA_4_7716", "Pot of tea (4)", "objtypes"),
            new GamevalEntry(7717, "ID_7717", "", "objtypes"),
            new GamevalEntry(7718, "POT_OF_TEA_3_7718", "Pot of tea (3)", "objtypes"),
            new GamevalEntry(7719, "ID_7719", "", "objtypes"),
            new GamevalEntry(7720, "POT_OF_TEA_2_7720", "Pot of tea (2)", "objtypes"),
            new GamevalEntry(7721, "ID_7721", "", "objtypes"),
            new GamevalEntry(7722, "POT_OF_TEA_1_7722", "Pot of tea (1)", "objtypes"),
            new GamevalEntry(7723, "ID_7723", "", "objtypes"),
            new GamevalEntry(7724, "TEAPOT_WITH_LEAVES_7724", "Teapot with leaves", "objtypes"),
            new GamevalEntry(7725, "ID_7725", "", "objtypes"),
            new GamevalEntry(7726, "TEAPOT_7726", "Teapot", "objtypes"),
            new GamevalEntry(7727, "ID_7727", "", "objtypes"),
            new GamevalEntry(7728, "EMPTY_CUP_7728", "Empty cup", "objtypes"),
            new GamevalEntry(7729, "ID_7729", "", "objtypes"),
            new GamevalEntry(7730, "CUP_OF_TEA_7730", "Cup of tea", "objtypes"),
            new GamevalEntry(7731, "CUP_OF_TEA_7731", "Cup of tea", "objtypes"),
            new GamevalEntry(7732, "PORCELAIN_CUP_7732", "Porcelain cup", "objtypes"),
            new GamevalEntry(7733, "CUP_OF_TEA_7733", "Cup of tea", "objtypes"),
            new GamevalEntry(7734, "CUP_OF_TEA_7734", "Cup of tea", "objtypes"),
            new GamevalEntry(7735, "PORCELAIN_CUP_7735", "Porcelain cup", "objtypes"),
            new GamevalEntry(7736, "CUP_OF_TEA_7736", "Cup of tea", "objtypes"),
            new GamevalEntry(7737, "CUP_OF_TEA_7737", "Cup of tea", "objtypes"),
            new GamevalEntry(7738, "TEA_LEAVES", "Tea leaves", "objtypes"),
            new GamevalEntry(7739, "ID_7739", "", "objtypes"),
            new GamevalEntry(7740, "BEER_7740", "Beer", "objtypes"),
            new GamevalEntry(7741, "ID_7741", "", "objtypes"),
            new GamevalEntry(7742, "BEER_GLASS_7742", "Beer glass", "objtypes"),
            new GamevalEntry(7743, "ID_7743", "", "objtypes"),
            new GamevalEntry(7744, "ASGARNIAN_ALE_7744", "Asgarnian ale", "objtypes"),
            new GamevalEntry(7745, "ID_7745", "", "objtypes"),
            new GamevalEntry(7746, "GREENMAN_S_ALE_7746", "Greenman's ale", "objtypes"),
            new GamevalEntry(7747, "ID_7747", "", "objtypes"),
            new GamevalEntry(7748, "DRAGON_BITTER_7748", "Dragon bitter", "objtypes"),
            new GamevalEntry(7749, "ID_7749", "", "objtypes"),
            new GamevalEntry(7750, "MOONLIGHT_MEAD", "Moonlight mead", "objtypes"),
            new GamevalEntry(7751, "ID_7751", "", "objtypes"),
            new GamevalEntry(7752, "CIDER_7752", "Cider", "objtypes"),
            new GamevalEntry(7753, "ID_7753", "", "objtypes"),
            new GamevalEntry(7754, "CHEF_S_DELIGHT_7754", "Chef's delight", "objtypes"),
            new GamevalEntry(7755, "ID_7755", "", "objtypes"),
            new GamevalEntry(7756, "PAINTBRUSH", "Paintbrush", "objtypes"),
            new GamevalEntry(7757, "ID_7757", "", "objtypes"),
            new GamevalEntry(7758, "ID_7758", "", "objtypes"),
            new GamevalEntry(7759, "TOY_SOLDIER", "Toy soldier", "objtypes"),
            new GamevalEntry(7760, "ID_7760", "", "objtypes"),
            new GamevalEntry(7761, "TOY_SOLDIER_WOUND", "Toy soldier (wound)", "objtypes"),
            new GamevalEntry(7762, "ID_7762", "", "objtypes"),
            new GamevalEntry(7763, "TOY_DOLL", "Toy doll", "objtypes"),
            new GamevalEntry(7764, "ID_7764", "", "objtypes"),
            new GamevalEntry(7765, "TOY_DOLL_WOUND", "Toy doll (wound)", "objtypes"),
            new GamevalEntry(7766, "ID_7766", "", "objtypes"),
            new GamevalEntry(7767, "TOY_MOUSE", "Toy mouse", "objtypes"),
            new GamevalEntry(7768, "ID_7768", "", "objtypes"),
            new GamevalEntry(7769, "TOY_MOUSE_WOUND", "Toy mouse (wound)", "objtypes"),
            new GamevalEntry(7770, "ID_7770", "", "objtypes"),
            new GamevalEntry(7771, "TOY_CAT", "Toy cat", "objtypes"),
            new GamevalEntry(7772, "ID_7772", "", "objtypes"),
            new GamevalEntry(7773, "BRANCH_7773", "Branch", "objtypes"),
            new GamevalEntry(7774, "REWARD_TOKEN", "Reward token", "objtypes"),
            new GamevalEntry(7775, "REWARD_TOKEN_7775", "Reward token", "objtypes"),
            new GamevalEntry(7776, "REWARD_TOKEN_7776", "Reward token", "objtypes"),
            new GamevalEntry(7777, "LONG_VINE", "Long vine", "objtypes"),
            new GamevalEntry(7778, "SHORT_VINE", "Short vine", "objtypes"),
            new GamevalEntry(7779, "FISHING_TOME", "Fishing tome", "objtypes"),
            new GamevalEntry(7780, "FISHING_TOME_7780", "Fishing tome", "objtypes"),
            new GamevalEntry(7781, "FISHING_TOME_7781", "Fishing tome", "objtypes"),
            new GamevalEntry(7782, "AGILITY_TOME", "Agility tome", "objtypes"),
            new GamevalEntry(7783, "AGILITY_TOME_7783", "Agility tome", "objtypes"),
            new GamevalEntry(7784, "AGILITY_TOME_7784", "Agility tome", "objtypes"),
            new GamevalEntry(7785, "THIEVING_TOME", "Thieving tome", "objtypes"),
            new GamevalEntry(7786, "THIEVING_TOME_7786", "Thieving tome", "objtypes"),
            new GamevalEntry(7787, "THIEVING_TOME_7787", "Thieving tome", "objtypes"),
            new GamevalEntry(7788, "SLAYER_TOME", "Slayer tome", "objtypes"),
            new GamevalEntry(7789, "SLAYER_TOME_7789", "Slayer tome", "objtypes"),
            new GamevalEntry(7790, "SLAYER_TOME_7790", "Slayer tome", "objtypes"),
            new GamevalEntry(7791, "MINING_TOME", "Mining tome", "objtypes"),
            new GamevalEntry(7792, "MINING_TOME_7792", "Mining tome", "objtypes"),
            new GamevalEntry(7793, "MINING_TOME_7793", "Mining tome", "objtypes"),
            new GamevalEntry(7794, "FIREMAKING_TOME", "Firemaking tome", "objtypes"),
            new GamevalEntry(7795, "FIREMAKING_TOME_7795", "Firemaking tome", "objtypes"),
            new GamevalEntry(7796, "FIREMAKING_TOME_7796", "Firemaking tome", "objtypes"),
            new GamevalEntry(7797, "WOODCUTTING_TOME", "Woodcutting tome", "objtypes"),
            new GamevalEntry(7798, "WOODCUTTING_TOME_7798", "Woodcutting tome", "objtypes"),
            new GamevalEntry(7799, "WOODCUTTING_TOME_7799", "Woodcutting tome", "objtypes"),
            new GamevalEntry(7800, "SNAIL_SHELL", "Snail shell", "objtypes"),
            new GamevalEntry(7801, "SNAKE_HIDE_7801", "Snake hide", "objtypes"),
            new GamevalEntry(7802, "ID_7802", "", "objtypes"),
            new GamevalEntry(7803, "YIN_YANG_AMULET", "Yin yang amulet", "objtypes"),
            new GamevalEntry(7804, "Q_ANCIENT_MJOLNIR", "q Ancient mjolnir", "objtypes"),
            new GamevalEntry(7805, "ID_7805", "", "objtypes"),
            new GamevalEntry(7806, "ANGER_SWORD", "Anger sword", "objtypes"),
            new GamevalEntry(7807, "ANGER_BATTLEAXE", "Anger battleaxe", "objtypes"),
            new GamevalEntry(7808, "ANGER_MACE", "Anger mace", "objtypes"),
            new GamevalEntry(7809, "ANGER_SPEAR", "Anger spear", "objtypes"),
            new GamevalEntry(7810, "JUG_OF_VINEGAR", "Jug of vinegar", "objtypes"),
            new GamevalEntry(7811, "POT_OF_VINEGAR", "Pot of vinegar", "objtypes"),
            new GamevalEntry(7812, "GOBLIN_SKULL", "Goblin skull", "objtypes"),
            new GamevalEntry(7813, "BONE_IN_VINEGAR", "Bone in vinegar", "objtypes"),
            new GamevalEntry(7814, "GOBLIN_SKULL_7814", "Goblin skull", "objtypes"),
            new GamevalEntry(7815, "BEAR_RIBS", "Bear ribs", "objtypes"),
            new GamevalEntry(7816, "BONE_IN_VINEGAR_7816", "Bone in vinegar", "objtypes"),
            new GamevalEntry(7817, "BEAR_RIBS_7817", "Bear ribs", "objtypes"),
            new GamevalEntry(7818, "RAM_SKULL", "Ram skull", "objtypes"),
            new GamevalEntry(7819, "BONE_IN_VINEGAR_7819", "Bone in vinegar", "objtypes"),
            new GamevalEntry(7820, "RAM_SKULL_7820", "Ram skull", "objtypes"),
            new GamevalEntry(7821, "UNICORN_BONE", "Unicorn bone", "objtypes"),
            new GamevalEntry(7822, "BONE_IN_VINEGAR_7822", "Bone in vinegar", "objtypes"),
            new GamevalEntry(7823, "UNICORN_BONE_7823", "Unicorn bone", "objtypes"),
            new GamevalEntry(7824, "GIANT_RAT_BONE", "Giant rat bone", "objtypes"),
            new GamevalEntry(7825, "BONE_IN_VINEGAR_7825", "Bone in vinegar", "objtypes"),
            new GamevalEntry(7826, "GIANT_RAT_BONE_7826", "Giant rat bone", "objtypes"),
            new GamevalEntry(7827, "GIANT_BAT_WING", "Giant bat wing", "objtypes"),
            new GamevalEntry(7828, "BONE_IN_VINEGAR_7828", "Bone in vinegar", "objtypes"),
            new GamevalEntry(7829, "GIANT_BAT_WING_7829", "Giant bat wing", "objtypes"),
            new GamevalEntry(7830, "WOLF_BONE", "Wolf bone", "objtypes"),
            new GamevalEntry(7831, "BONE_IN_VINEGAR_7831", "Bone in vinegar", "objtypes"),
            new GamevalEntry(7832, "WOLF_BONE_7832", "Wolf bone", "objtypes"),
            new GamevalEntry(7833, "BAT_WING", "Bat wing", "objtypes"),
            new GamevalEntry(7834, "BONE_IN_VINEGAR_7834", "Bone in vinegar", "objtypes"),
            new GamevalEntry(7835, "BAT_WING_7835", "Bat wing", "objtypes"),
            new GamevalEntry(7836, "RAT_BONE", "Rat bone", "objtypes"),
            new GamevalEntry(7837, "BONE_IN_VINEGAR_7837", "Bone in vinegar", "objtypes"),
            new GamevalEntry(7838, "RAT_BONE_7838", "Rat bone", "objtypes"),
            new GamevalEntry(7839, "BABY_DRAGON_BONE", "Baby dragon bone", "objtypes"),
            new GamevalEntry(7840, "BONE_IN_VINEGAR_7840", "Bone in vinegar", "objtypes"),
            new GamevalEntry(7841, "BABY_DRAGON_BONE_7841", "Baby dragon bone", "objtypes"),
            new GamevalEntry(7842, "OGRE_RIBS", "Ogre ribs", "objtypes"),
            new GamevalEntry(7843, "BONE_IN_VINEGAR_7843", "Bone in vinegar", "objtypes"),
            new GamevalEntry(7844, "OGRE_RIBS_7844", "Ogre ribs", "objtypes"),
            new GamevalEntry(7845, "JOGRE_BONE", "Jogre bone", "objtypes"),
            new GamevalEntry(7846, "BONE_IN_VINEGAR_7846", "Bone in vinegar", "objtypes"),
            new GamevalEntry(7847, "JOGRE_BONE_7847", "Jogre bone", "objtypes"),
            new GamevalEntry(7848, "ZOGRE_BONE", "Zogre bone", "objtypes"),
            new GamevalEntry(7849, "BONE_IN_VINEGAR_7849", "Bone in vinegar", "objtypes"),
            new GamevalEntry(7850, "ZOGRE_BONE_7850", "Zogre bone", "objtypes"),
            new GamevalEntry(7851, "MOGRE_BONE", "Mogre bone", "objtypes"),
            new GamevalEntry(7852, "BONE_IN_VINEGAR_7852", "Bone in vinegar", "objtypes"),
            new GamevalEntry(7853, "MOGRE_BONE_7853", "Mogre bone", "objtypes"),
            new GamevalEntry(7854, "MONKEY_PAW", "Monkey paw", "objtypes"),
            new GamevalEntry(7855, "BONE_IN_VINEGAR_7855", "Bone in vinegar", "objtypes"),
            new GamevalEntry(7856, "MONKEY_PAW_7856", "Monkey paw", "objtypes"),
            new GamevalEntry(7857, "DAGANNOTH_RIBS", "Dagannoth ribs", "objtypes"),
            new GamevalEntry(7858, "BONE_IN_VINEGAR_7858", "Bone in vinegar", "objtypes"),
            new GamevalEntry(7859, "DAGANNOTH_RIBS_7859", "Dagannoth ribs", "objtypes"),
            new GamevalEntry(7860, "SNAKE_SPINE", "Snake spine", "objtypes"),
            new GamevalEntry(7861, "BONE_IN_VINEGAR_7861", "Bone in vinegar", "objtypes"),
            new GamevalEntry(7862, "SNAKE_SPINE_7862", "Snake spine", "objtypes"),
            new GamevalEntry(7863, "ZOMBIE_BONE", "Zombie bone", "objtypes"),
            new GamevalEntry(7864, "BONE_IN_VINEGAR_7864", "Bone in vinegar", "objtypes"),
            new GamevalEntry(7865, "ZOMBIE_BONE_7865", "Zombie bone", "objtypes"),
            new GamevalEntry(7866, "WEREWOLF_BONE", "Werewolf bone", "objtypes"),
            new GamevalEntry(7867, "BONE_IN_VINEGAR_7867", "Bone in vinegar", "objtypes"),
            new GamevalEntry(7868, "WEREWOLF_BONE_7868", "Werewolf bone", "objtypes"),
            new GamevalEntry(7869, "MOSS_GIANT_BONE", "Moss giant bone", "objtypes"),
            new GamevalEntry(7870, "BONE_IN_VINEGAR_7870", "Bone in vinegar", "objtypes"),
            new GamevalEntry(7871, "MOSS_GIANT_BONE_7871", "Moss giant bone", "objtypes"),
            new GamevalEntry(7872, "FIRE_GIANT_BONE", "Fire giant bone", "objtypes"),
            new GamevalEntry(7873, "BONE_IN_VINEGAR_7873", "Bone in vinegar", "objtypes"),
            new GamevalEntry(7874, "FIRE_GIANT_BONE_7874", "Fire giant bone", "objtypes"),
            new GamevalEntry(7875, "ICE_GIANT_RIBS", "Ice giant ribs", "objtypes"),
            new GamevalEntry(7876, "BONE_IN_VINEGAR_7876", "Bone in vinegar", "objtypes"),
            new GamevalEntry(7877, "ICE_GIANT_RIBS_7877", "Ice giant ribs", "objtypes"),
            new GamevalEntry(7878, "TERRORBIRD_WING", "Terrorbird wing", "objtypes"),
            new GamevalEntry(7879, "BONE_IN_VINEGAR_7879", "Bone in vinegar", "objtypes"),
            new GamevalEntry(7880, "TERRORBIRD_WING_7880", "Terrorbird wing", "objtypes"),
            new GamevalEntry(7881, "GHOUL_BONE", "Ghoul bone", "objtypes"),
            new GamevalEntry(7882, "BONE_IN_VINEGAR_7882", "Bone in vinegar", "objtypes"),
            new GamevalEntry(7883, "GHOUL_BONE_7883", "Ghoul bone", "objtypes"),
            new GamevalEntry(7884, "TROLL_BONE", "Troll bone", "objtypes"),
            new GamevalEntry(7885, "BONE_IN_VINEGAR_7885", "Bone in vinegar", "objtypes"),
            new GamevalEntry(7886, "TROLL_BONE_7886", "Troll bone", "objtypes"),
            new GamevalEntry(7887, "SEAGULL_WING", "Seagull wing", "objtypes"),
            new GamevalEntry(7888, "BONE_IN_VINEGAR_7888", "Bone in vinegar", "objtypes"),
            new GamevalEntry(7889, "SEAGULL_WING_7889", "Seagull wing", "objtypes"),
            new GamevalEntry(7890, "UNDEAD_COW_RIBS", "Undead cow ribs", "objtypes"),
            new GamevalEntry(7891, "BONE_IN_VINEGAR_7891", "Bone in vinegar", "objtypes"),
            new GamevalEntry(7892, "UNDEAD_COW_RIBS_7892", "Undead cow ribs", "objtypes"),
            new GamevalEntry(7893, "EXPERIMENT_BONE", "Experiment bone", "objtypes"),
            new GamevalEntry(7894, "BONE_IN_VINEGAR_7894", "Bone in vinegar", "objtypes"),
            new GamevalEntry(7895, "EXPERIMENT_BONE_7895", "Experiment bone", "objtypes"),
            new GamevalEntry(7896, "RABBIT_BONE", "Rabbit bone", "objtypes"),
            new GamevalEntry(7897, "BONE_IN_VINEGAR_7897", "Bone in vinegar", "objtypes"),
            new GamevalEntry(7898, "RABBIT_BONE_7898", "Rabbit bone", "objtypes"),
            new GamevalEntry(7899, "BASILISK_BONE", "Basilisk bone", "objtypes"),
            new GamevalEntry(7900, "BONE_IN_VINEGAR_7900", "Bone in vinegar", "objtypes"),
            new GamevalEntry(7901, "BASILISK_BONE_7901", "Basilisk bone", "objtypes"),
            new GamevalEntry(7902, "DESERT_LIZARD_BONE", "Desert lizard bone", "objtypes"),
            new GamevalEntry(7903, "BONE_IN_VINEGAR_7903", "Bone in vinegar", "objtypes"),
            new GamevalEntry(7904, "DESERT_LIZARD_BONE_7904", "Desert lizard bone", "objtypes"),
            new GamevalEntry(7905, "CAVE_GOBLIN_SKULL", "Cave goblin skull", "objtypes"),
            new GamevalEntry(7906, "BONE_IN_VINEGAR_7906", "Bone in vinegar", "objtypes"),
            new GamevalEntry(7907, "CAVE_GOBLIN_SKULL_7907", "Cave goblin skull", "objtypes"),
            new GamevalEntry(7908, "BIG_FROG_LEG", "Big frog leg", "objtypes"),
            new GamevalEntry(7909, "BONE_IN_VINEGAR_7909", "Bone in vinegar", "objtypes"),
            new GamevalEntry(7910, "BIG_FROG_LEG_7910", "Big frog leg", "objtypes"),
            new GamevalEntry(7911, "VULTURE_WING", "Vulture wing", "objtypes"),
            new GamevalEntry(7912, "BONE_IN_VINEGAR_7912", "Bone in vinegar", "objtypes"),
            new GamevalEntry(7913, "VULTURE_WING_7913", "Vulture wing", "objtypes"),
            new GamevalEntry(7914, "JACKAL_BONE", "Jackal bone", "objtypes"),
            new GamevalEntry(7915, "BONE_IN_VINEGAR_7915", "Bone in vinegar", "objtypes"),
            new GamevalEntry(7916, "JACKAL_BONE_7916", "Jackal bone", "objtypes"),
            new GamevalEntry(7917, "K_G_RAM_SKULL_HELM", "K g Ram skull helm", "objtypes"),
            new GamevalEntry(7918, "BONESACK", "Bonesack", "objtypes"),
            new GamevalEntry(7919, "BOTTLE_OF_WINE", "Bottle of wine", "objtypes"),
            new GamevalEntry(7920, "ID_7920", "", "objtypes"),
            new GamevalEntry(7921, "EMPTY_WINE_BOTTLE", "Empty wine bottle", "objtypes"),
            new GamevalEntry(7922, "AL_KHARID_FLYER", "Al kharid flyer", "objtypes"),
            new GamevalEntry(7923, "ID_7923", "", "objtypes"),
            new GamevalEntry(7924, "ID_7924", "", "objtypes"),
            new GamevalEntry(7925, "ID_7925", "", "objtypes"),
            new GamevalEntry(7926, "ID_7926", "", "objtypes"),
            new GamevalEntry(7927, "EASTER_RING", "Easter ring", "objtypes"),
            new GamevalEntry(7928, "EASTER_EGG_7928", "Easter egg", "objtypes"),
            new GamevalEntry(7929, "EASTER_EGG_7929", "Easter egg", "objtypes"),
            new GamevalEntry(7930, "EASTER_EGG_7930", "Easter egg", "objtypes"),
            new GamevalEntry(7931, "EASTER_EGG_7931", "Easter egg", "objtypes"),
            new GamevalEntry(7932, "EASTER_EGG_7932", "Easter egg", "objtypes"),
            new GamevalEntry(7933, "EASTER_EGG_7933", "Easter egg", "objtypes"),
            new GamevalEntry(7934, "FIELD_RATION", "Field ration", "objtypes"),
            new GamevalEntry(7935, "ID_7935", "", "objtypes"),
            new GamevalEntry(7936, "PURE_ESSENCE", "Pure essence", "objtypes"),
            new GamevalEntry(7937, "ID_7937", "", "objtypes"),
            new GamevalEntry(7938, "DARK_ESSENCE_FRAGMENTS", "Dark essence fragments", "objtypes"),
            new GamevalEntry(7939, "TORTOISE_SHELL", "Tortoise shell", "objtypes"),
            new GamevalEntry(7940, "ID_7940", "", "objtypes"),
            new GamevalEntry(7941, "IRON_SHEET", "Iron sheet", "objtypes"),
            new GamevalEntry(7942, "FRESH_MONKFISH", "Fresh monkfish", "objtypes"),
            new GamevalEntry(7943, "FRESH_MONKFISH_7943", "Fresh monkfish", "objtypes"),
            new GamevalEntry(7944, "RAW_MONKFISH", "Raw monkfish", "objtypes"),
            new GamevalEntry(7945, "ID_7945", "", "objtypes"),
            new GamevalEntry(7946, "MONKFISH", "Monkfish", "objtypes"),
            new GamevalEntry(7947, "ID_7947", "", "objtypes"),
            new GamevalEntry(7948, "BURNT_MONKFISH", "Burnt monkfish", "objtypes"),
            new GamevalEntry(7949, "ID_7949", "", "objtypes"),
            new GamevalEntry(7950, "BONE_SEEDS", "Bone seeds", "objtypes"),
            new GamevalEntry(7951, "HERMAN_S_BOOK", "Herman's book", "objtypes"),
            new GamevalEntry(7952, "AXE_HANDLE_7952", "Axe handle", "objtypes"),
            new GamevalEntry(7953, "ID_7953", "", "objtypes"),
            new GamevalEntry(7954, "BURNT_SHRIMP", "Burnt shrimp", "objtypes"),
            new GamevalEntry(7955, "ID_7955", "", "objtypes"),
            new GamevalEntry(7956, "CASKET_7956", "Casket", "objtypes"),
            new GamevalEntry(7957, "WHITE_APRON_7957", "White apron", "objtypes"),
            new GamevalEntry(7958, "MINING_PROP", "Mining prop", "objtypes"),
            new GamevalEntry(7959, "HEAVY_BOX", "Heavy box", "objtypes"),
            new GamevalEntry(7960, "EMPTY_BOX", "Empty box", "objtypes"),
            new GamevalEntry(7961, "BURNT_DIARY", "Burnt diary", "objtypes"),
            new GamevalEntry(7962, "BURNT_DIARY_7962", "Burnt diary", "objtypes"),
            new GamevalEntry(7963, "BURNT_DIARY_7963", "Burnt diary", "objtypes"),
            new GamevalEntry(7964, "BURNT_DIARY_7964", "Burnt diary", "objtypes"),
            new GamevalEntry(7965, "BURNT_DIARY_7965", "Burnt diary", "objtypes"),
            new GamevalEntry(7966, "LETTER_7966", "Letter", "objtypes"),
            new GamevalEntry(7967, "ENGINE", "Engine", "objtypes"),
            new GamevalEntry(7968, "SCROLL_7968", "Scroll", "objtypes"),
            new GamevalEntry(7969, "PULLEY_BEAM", "Pulley beam", "objtypes"),
            new GamevalEntry(7970, "LONG_PULLEY_BEAM", "Long pulley beam", "objtypes"),
            new GamevalEntry(7971, "LONGER_PULLEY_BEAM", "Longer pulley beam", "objtypes"),
            new GamevalEntry(7972, "LIFT_MANUAL", "Lift manual", "objtypes"),
            new GamevalEntry(7973, "BEAM", "Beam", "objtypes"),
            new GamevalEntry(7974, "SERVANT_BELL", "Servant bell", "objtypes"),
            new GamevalEntry(7975, "CRAWLING_HAND_7975", "Crawling hand", "objtypes"),
            new GamevalEntry(7976, "COCKATRICE_HEAD", "Cockatrice head", "objtypes"),
            new GamevalEntry(7977, "BASILISK_HEAD", "Basilisk head", "objtypes"),
            new GamevalEntry(7978, "KURASK_HEAD", "Kurask head", "objtypes"),
            new GamevalEntry(7979, "ABYSSAL_HEAD", "Abyssal head", "objtypes"),
            new GamevalEntry(7980, "KBD_HEADS", "Kbd heads", "objtypes"),
            new GamevalEntry(7981, "KQ_HEAD", "Kq head", "objtypes"),
            new GamevalEntry(7982, "STUFFED_CRAWLING_HAND", "Stuffed crawling hand", "objtypes"),
            new GamevalEntry(7983, "STUFFED_COCKATRICE_HEAD", "Stuffed cockatrice head", "objtypes"),
            new GamevalEntry(7984, "STUFFED_BASILISK_HEAD", "Stuffed basilisk head", "objtypes"),
            new GamevalEntry(7985, "STUFFED_KURASK_HEAD", "Stuffed kurask head", "objtypes"),
            new GamevalEntry(7986, "STUFFED_ABYSSAL_HEAD", "Stuffed abyssal head", "objtypes"),
            new GamevalEntry(7987, "STUFFED_KBD_HEADS", "Stuffed kbd heads", "objtypes"),
            new GamevalEntry(7988, "STUFFED_KQ_HEAD", "Stuffed kq head", "objtypes"),
            new GamevalEntry(7989, "BIG_BASS", "Big bass", "objtypes"),
            new GamevalEntry(7990, "STUFFED_BIG_BASS", "Stuffed big bass", "objtypes"),
            new GamevalEntry(7991, "BIG_SWORDFISH", "Big swordfish", "objtypes"),
            new GamevalEntry(7992, "STUFFED_BIG_SWORDFISH", "Stuffed big swordfish", "objtypes"),
            new GamevalEntry(7993, "BIG_SHARK", "Big shark", "objtypes"),
            new GamevalEntry(7994, "STUFFED_BIG_SHARK", "Stuffed big shark", "objtypes"),
            new GamevalEntry(7995, "ARTHUR_PORTRAIT", "Arthur portrait", "objtypes"),
            new GamevalEntry(7996, "ELENA_PORTRAIT", "Elena portrait", "objtypes"),
            new GamevalEntry(7997, "KELDAGRIM_PORTRAIT", "Keldagrim portrait", "objtypes"),
            new GamevalEntry(7998, "MISC_PORTRAIT", "Misc. portrait", "objtypes"),
            new GamevalEntry(7999, "DESERT_PAINTING", "Desert painting", "objtypes"),
            new GamevalEntry(8000, "ISAFDAR_PAINTING", "Isafdar painting", "objtypes"),
            new GamevalEntry(8001, "KARAMJA_PAINTING", "Karamja painting", "objtypes"),
            new GamevalEntry(8002, "LUMBRIDGE_PAINTING", "Lumbridge painting", "objtypes"),
            new GamevalEntry(8003, "MORYTANIA_PAINTING", "Morytania painting", "objtypes"),
            new GamevalEntry(8004, "SMALL_MAP", "Small map", "objtypes"),
            new GamevalEntry(8005, "MEDIUM_MAP", "Medium map", "objtypes"),
            new GamevalEntry(8006, "LARGE_MAP", "Large map", "objtypes"),
            new GamevalEntry(8007, "VARROCK_TELEPORT", "Varrock teleport", "objtypes"),
            new GamevalEntry(8008, "LUMBRIDGE_TELEPORT", "Lumbridge teleport", "objtypes"),
            new GamevalEntry(8009, "FALADOR_TELEPORT", "Falador teleport", "objtypes"),
            new GamevalEntry(8010, "CAMELOT_TELEPORT", "Camelot teleport", "objtypes"),
            new GamevalEntry(8011, "ARDOUGNE_TELEPORT", "Ardougne teleport", "objtypes"),
            new GamevalEntry(8012, "WATCHTOWER_TELEPORT", "Watchtower teleport", "objtypes"),
            new GamevalEntry(8013, "TELEPORT_TO_HOUSE", "Teleport to house", "objtypes"),
            new GamevalEntry(8014, "BONES_TO_BANANAS", "Bones to bananas", "objtypes"),
            new GamevalEntry(8015, "BONES_TO_PEACHES_8015", "Bones to peaches", "objtypes"),
            new GamevalEntry(8016, "ENCHANT_SAPPHIRE_OR_OPAL", "Enchant sapphire or opal", "objtypes"),
            new GamevalEntry(8017, "ENCHANT_EMERALD_OR_JADE", "Enchant emerald or jade", "objtypes"),
            new GamevalEntry(8018, "ENCHANT_RUBY_OR_TOPAZ", "Enchant ruby or topaz", "objtypes"),
            new GamevalEntry(8019, "ENCHANT_DIAMOND", "Enchant diamond", "objtypes"),
            new GamevalEntry(8020, "ENCHANT_DRAGONSTONE", "Enchant dragonstone", "objtypes"),
            new GamevalEntry(8021, "ENCHANT_ONYX", "Enchant onyx", "objtypes"),
            new GamevalEntry(8022, "TELEKINETIC_GRAB", "Telekinetic grab", "objtypes"),
            new GamevalEntry(8023, "BOXING_RING", "Boxing ring", "objtypes"),
            new GamevalEntry(8024, "FENCING_RING", "Fencing ring", "objtypes"),
            new GamevalEntry(8025, "COMBAT_RING", "Combat ring", "objtypes"),
            new GamevalEntry(8026, "RANGING_PEDESTALS", "Ranging pedestals", "objtypes"),
            new GamevalEntry(8027, "BALANCE_BEAM", "Balance beam", "objtypes"),
            new GamevalEntry(8028, "GLOVE_RACK", "Glove rack", "objtypes"),
            new GamevalEntry(8029, "WEAPONS_RACK", "Weapons rack", "objtypes"),
            new GamevalEntry(8030, "EXTRA_WEAPONS_RACK", "Extra weapons rack", "objtypes"),
            new GamevalEntry(8031, "WOODEN_BED", "Wooden bed", "objtypes"),
            new GamevalEntry(8032, "OAK_BED", "Oak bed", "objtypes"),
            new GamevalEntry(8033, "LARGE_OAK_BED", "Large oak bed", "objtypes"),
            new GamevalEntry(8034, "TEAK_BED", "Teak bed", "objtypes"),
            new GamevalEntry(8035, "LARGE_TEAK_BED", "Large teak bed", "objtypes"),
            new GamevalEntry(8036, "ID_8036_4_POSTER", "4-poster", "objtypes"),
            new GamevalEntry(8037, "GILDED_4_POSTER", "Gilded 4-poster", "objtypes"),
            new GamevalEntry(8038, "SHOE_BOX", "Shoe box", "objtypes"),
            new GamevalEntry(8039, "OAK_DRAWERS", "Oak drawers", "objtypes"),
            new GamevalEntry(8040, "OAK_WARDROBE", "Oak wardrobe", "objtypes"),
            new GamevalEntry(8041, "TEAK_DRAWERS", "Teak drawers", "objtypes"),
            new GamevalEntry(8042, "TEAK_WARDROBE", "Teak wardrobe", "objtypes"),
            new GamevalEntry(8043, "MAHOGANY_WARDROBE", "Mahogany wardrobe", "objtypes"),
            new GamevalEntry(8044, "GILDED_WARDROBE", "Gilded wardrobe", "objtypes"),
            new GamevalEntry(8045, "SHAVING_STAND", "Shaving stand", "objtypes"),
            new GamevalEntry(8046, "OAK_SHAVING_STAND", "Oak shaving stand", "objtypes"),
            new GamevalEntry(8047, "OAK_DRESSER", "Oak dresser", "objtypes"),
            new GamevalEntry(8048, "TEAK_DRESSER", "Teak dresser", "objtypes"),
            new GamevalEntry(8049, "FANCY_TEAK_DRESSER", "Fancy teak dresser", "objtypes"),
            new GamevalEntry(8050, "MAHOGANY_DRESSER", "Mahogany dresser", "objtypes"),
            new GamevalEntry(8051, "GILDED_DRESSER", "Gilded dresser", "objtypes"),
            new GamevalEntry(8052, "OAK_CLOCK", "Oak clock", "objtypes"),
            new GamevalEntry(8053, "TEAK_CLOCK", "Teak clock", "objtypes"),
            new GamevalEntry(8054, "GILDED_CLOCK", "Gilded clock", "objtypes"),
            new GamevalEntry(8055, "SARADOMIN_SYMBOL", "Saradomin symbol", "objtypes"),
            new GamevalEntry(8056, "ZAMORAK_SYMBOL", "Zamorak symbol", "objtypes"),
            new GamevalEntry(8057, "GUTHIX_SYMBOL", "Guthix symbol", "objtypes"),
            new GamevalEntry(8058, "SARADOMIN_ICON", "Saradomin icon", "objtypes"),
            new GamevalEntry(8059, "ZAMORAK_ICON", "Zamorak icon", "objtypes"),
            new GamevalEntry(8060, "GUTHIX_ICON", "Guthix icon", "objtypes"),
            new GamevalEntry(8061, "BOB_ICON", "Bob icon", "objtypes"),
            new GamevalEntry(8062, "OAK_ALTAR", "Oak altar", "objtypes"),
            new GamevalEntry(8063, "TEAK_ALTAR", "Teak altar", "objtypes"),
            new GamevalEntry(8064, "CLOTH_COVERED_ALTAR", "Cloth-covered altar", "objtypes"),
            new GamevalEntry(8065, "MAHOGANY_ALTAR", "Mahogany altar", "objtypes"),
            new GamevalEntry(8066, "LIMESTONE_ALTAR", "Limestone altar", "objtypes"),
            new GamevalEntry(8067, "MARBLE_ALTAR", "Marble altar", "objtypes"),
            new GamevalEntry(8068, "GILDED_ALTAR", "Gilded altar", "objtypes"),
            new GamevalEntry(8069, "WOODEN_TORCHES", "Wooden torches", "objtypes"),
            new GamevalEntry(8070, "STEEL_TORCHES", "Steel torches", "objtypes"),
            new GamevalEntry(8071, "STEEL_CANDLESTICKS", "Steel candlesticks", "objtypes"),
            new GamevalEntry(8072, "GOLD_CANDLESTICKS", "Gold candlesticks", "objtypes"),
            new GamevalEntry(8073, "INCENSE_BURNERS", "Incense burners", "objtypes"),
            new GamevalEntry(8074, "MAHOGANY_BURNERS", "Mahogany burners", "objtypes"),
            new GamevalEntry(8075, "MARBLE_BURNERS", "Marble burners", "objtypes"),
            new GamevalEntry(8076, "SHUTTERED_WINDOW", "Shuttered window", "objtypes"),
            new GamevalEntry(8077, "DECORATIVE_WINDOW", "& Decorative window", "objtypes"),
            new GamevalEntry(8078, "STAINED_GLASS", "Stained glass", "objtypes"),
            new GamevalEntry(8079, "WINDCHIMES", "Windchimes", "objtypes"),
            new GamevalEntry(8080, "BELLS", "Bells", "objtypes"),
            new GamevalEntry(8081, "ORGAN", "Organ", "objtypes"),
            new GamevalEntry(8082, "SMALL_STATUES", "Small statues", "objtypes"),
            new GamevalEntry(8083, "MEDIUM_STATUES", "Medium statues", "objtypes"),
            new GamevalEntry(8084, "LARGE_STATUES", "Large statues", "objtypes"),
            new GamevalEntry(8085, "SUIT_OF_ARMOUR", "Suit of armour", "objtypes"),
            new GamevalEntry(8086, "SMALL_PORTRAIT", "Small portrait", "objtypes"),
            new GamevalEntry(8087, "TEAK_MOUNTED_HEAD_DISPLAY", "Teak mounted head display", "objtypes"),
            new GamevalEntry(8088, "MAHOGANY_MOUNTED_HEAD_DISPLAY", "Mahogany mounted head display", "objtypes"),
            new GamevalEntry(8089, "GILDED_MOUNTED_HEAD_DISPLAY", "Gilded mounted head display", "objtypes"),
            new GamevalEntry(8090, "MOUNTED_SWORD", "Mounted sword", "objtypes"),
            new GamevalEntry(8091, "SMALL_LANDSCAPE", "Small landscape", "objtypes"),
            new GamevalEntry(8092, "ZTELEPORTS_YOU_TO_YOUR_RESPAWN_LOCATION", "ZTeleports you to your respawn location", "objtypes"),
            new GamevalEntry(8093, "LARGE_PORTRAIT", "Large portrait", "objtypes"),
            new GamevalEntry(8094, "LARGE_LANDSCAPE", "Large landscape", "objtypes"),
            new GamevalEntry(8095, "RUNE_DISPLAY_CASE", "Rune display case", "objtypes"),
            new GamevalEntry(8096, "LOW_LEVEL_PLANTS", "Low-level plants", "objtypes"),
            new GamevalEntry(8097, "MID_LEVEL_PLANTS", "Mid-level plants", "objtypes"),
            new GamevalEntry(8098, "HIGH_LEVEL_PLANTS", "High-level plants", "objtypes"),
            new GamevalEntry(8099, "ROPE_BELL_PULL", "Rope bell-pull", "objtypes"),
            new GamevalEntry(8100, "BELL_PULL", "Bell-pull", "objtypes"),
            new GamevalEntry(8101, "POSH_BELL_PULL", "Posh bell-pull", "objtypes"),
            new GamevalEntry(8102, "OAK_DECORATION", "Oak decoration", "objtypes"),
            new GamevalEntry(8103, "TEAK_DECORATION", "Teak decoration", "objtypes"),
            new GamevalEntry(8104, "GILDED_DECORATION", "Gilded decoration", "objtypes"),
            new GamevalEntry(8105, "ROUND_SHIELD", "Round shield", "objtypes"),
            new GamevalEntry(8106, "SQUARE_SHIELD", "Square shield", "objtypes"),
            new GamevalEntry(8107, "KITE_SHIELD", "Kite shield", "objtypes"),
            new GamevalEntry(8108, "WOODEN_BENCH", "Wooden bench", "objtypes"),
            new GamevalEntry(8109, "OAK_BENCH", "Oak bench", "objtypes"),
            new GamevalEntry(8110, "CARVED_OAK_BENCH", "Carved oak bench", "objtypes"),
            new GamevalEntry(8111, "TEAK_DINING_BENCH", "Teak dining bench", "objtypes"),
            new GamevalEntry(8112, "CARVED_TEAK_BENCH", "Carved teak bench", "objtypes"),
            new GamevalEntry(8113, "MAHOGANY_BENCH", "Mahogany bench", "objtypes"),
            new GamevalEntry(8114, "GILDED_BENCH", "Gilded bench", "objtypes"),
            new GamevalEntry(8115, "WOOD_DINING_TABLE", "Wood dining table", "objtypes"),
            new GamevalEntry(8116, "OAK_DINING_TABLE", "Oak dining table", "objtypes"),
            new GamevalEntry(8117, "CARVED_OAK_TABLE", "Carved oak table", "objtypes"),
            new GamevalEntry(8118, "TEAK_TABLE", "Teak table", "objtypes"),
            new GamevalEntry(8119, "CARVED_TEAK_TABLE", "Carved teak table", "objtypes"),
            new GamevalEntry(8120, "MAHOGANY_TABLE", "Mahogany table", "objtypes"),
            new GamevalEntry(8121, "OPULENT_TABLE", "Opulent table", "objtypes"),
            new GamevalEntry(8122, "OAK_DOOR", "Oak door", "objtypes"),
            new GamevalEntry(8123, "STEEL_PLATED_DOOR", "Steel-plated door", "objtypes"),
            new GamevalEntry(8124, "MARBLE_DOOR", "Marble door", "objtypes"),
            new GamevalEntry(8125, "DECORATIVE_BLOOD", "Decorative blood", "objtypes"),
            new GamevalEntry(8126, "DECORATIVE_PIPE", "Decorative pipe", "objtypes"),
            new GamevalEntry(8127, "HANGING_SKELETON", "Hanging skeleton", "objtypes"),
            new GamevalEntry(8128, "CANDLES", "Candles", "objtypes"),
            new GamevalEntry(8129, "TORCHES", "Torches", "objtypes"),
            new GamevalEntry(8130, "SKULL_TORCHES", "Skull torches", "objtypes"),
            new GamevalEntry(8131, "SKELETON_GUARD", "Skeleton guard", "objtypes"),
            new GamevalEntry(8132, "GUARD_DOG", "Guard dog", "objtypes"),
            new GamevalEntry(8133, "HOBGOBLIN_GUARD", "Hobgoblin guard", "objtypes"),
            new GamevalEntry(8134, "BABY_RED_DRAGON", "Baby red dragon", "objtypes"),
            new GamevalEntry(8135, "HUGE_SPIDER", "Huge spider", "objtypes"),
            new GamevalEntry(8136, "TROLL_GUARD", "Troll guard", "objtypes"),
            new GamevalEntry(8137, "HELLHOUND", "Hellhound", "objtypes"),
            new GamevalEntry(8138, "DEMON", "Demon", "objtypes"),
            new GamevalEntry(8139, "KALPHITE_SOLDIER", "Kalphite soldier", "objtypes"),
            new GamevalEntry(8140, "TOK_XIL", "Tok-xil", "objtypes"),
            new GamevalEntry(8141, "DAGANNOTH", "Dagannoth", "objtypes"),
            new GamevalEntry(8142, "STEEL_DRAGON", "Steel dragon", "objtypes"),
            new GamevalEntry(8143, "SPIKE_TRAP", "Spike trap", "objtypes"),
            new GamevalEntry(8144, "MAN_TRAP", "Man trap", "objtypes"),
            new GamevalEntry(8145, "TANGLE_VINE", "Tangle vine", "objtypes"),
            new GamevalEntry(8146, "MARBLE_TRAP", "Marble trap", "objtypes"),
            new GamevalEntry(8147, "TELEPORT_TRAP", "Teleport trap", "objtypes"),
            new GamevalEntry(8148, "WOODEN_CRATE", "Wooden crate", "objtypes"),
            new GamevalEntry(8149, "OAK_CHEST", "Oak chest", "objtypes"),
            new GamevalEntry(8150, "TEAK_CHEST", "Teak chest", "objtypes"),
            new GamevalEntry(8151, "MAHOGANY_CHEST", "Mahogany chest", "objtypes"),
            new GamevalEntry(8152, "MAGIC_CHEST", "Magic chest", "objtypes"),
            new GamevalEntry(8153, "CLAY_ATTACK_STONE", "Clay attack stone", "objtypes"),
            new GamevalEntry(8154, "ATTACK_STONE", "Attack stone", "objtypes"),
            new GamevalEntry(8155, "MARBLE_ATT_STONE", "Marble att. stone", "objtypes"),
            new GamevalEntry(8156, "MAGICAL_BALANCE_1", "Magical balance 1", "objtypes"),
            new GamevalEntry(8157, "MAGICAL_BALANCE_2", "Magical balance 2", "objtypes"),
            new GamevalEntry(8158, "MAGICAL_BALANCE_3", "Magical balance 3", "objtypes"),
            new GamevalEntry(8159, "JESTER", "Jester", "objtypes"),
            new GamevalEntry(8160, "TREASURE_HUNT", "Treasure hunt", "objtypes"),
            new GamevalEntry(8161, "HANGMAN_GAME", "Hangman game", "objtypes"),
            new GamevalEntry(8162, "HOOP_AND_STICK", "Hoop and stick", "objtypes"),
            new GamevalEntry(8163, "DARTBOARD", "Dartboard", "objtypes"),
            new GamevalEntry(8164, "ARCHERY_TARGET", "Archery target", "objtypes"),
            new GamevalEntry(8165, "OAK_PRIZE_CHEST", "Oak prize chest", "objtypes"),
            new GamevalEntry(8166, "TEAK_PRIZE_CHEST", "Teak prize chest", "objtypes"),
            new GamevalEntry(8167, "MAHOGANY_CHEST_8167", "Mahogany chest", "objtypes"),
            new GamevalEntry(8168, "EXIT_PORTAL", "Exit portal", "objtypes"),
            new GamevalEntry(8169, "DECORATIVE_ROCK", "Decorative rock", "objtypes"),
            new GamevalEntry(8170, "POND", "Pond", "objtypes"),
            new GamevalEntry(8171, "IMP_STATUE", "Imp statue", "objtypes"),
            new GamevalEntry(8172, "DUNGEON_ENTRANCE", "Dungeon entrance", "objtypes"),
            new GamevalEntry(8173, "TREE", "Tree", "objtypes"),
            new GamevalEntry(8174, "NICE_TREE", "Nice tree", "objtypes"),
            new GamevalEntry(8175, "OAK_TREE", "Oak tree", "objtypes"),
            new GamevalEntry(8176, "WILLOW_TREE", "Willow tree", "objtypes"),
            new GamevalEntry(8177, "MAPLE_TREE", "Maple tree", "objtypes"),
            new GamevalEntry(8178, "YEW_TREE", "Yew tree", "objtypes"),
            new GamevalEntry(8179, "MAGIC_TREE", "Magic tree", "objtypes"),
            new GamevalEntry(8180, "PLANT", "Plant", "objtypes"),
            new GamevalEntry(8181, "SMALL_FERN", "Small fern", "objtypes"),
            new GamevalEntry(8182, "FERN", "Fern", "objtypes"),
            new GamevalEntry(8183, "DOCK_LEAF", "Dock leaf", "objtypes"),
            new GamevalEntry(8184, "THISTLE", "Thistle", "objtypes"),
            new GamevalEntry(8185, "REEDS", "Reeds", "objtypes"),
            new GamevalEntry(8186, "FERN_8186", "Fern", "objtypes"),
            new GamevalEntry(8187, "BUSH", "Bush", "objtypes"),
            new GamevalEntry(8188, "TALL_PLANT", "Tall plant", "objtypes"),
            new GamevalEntry(8189, "SHORT_PLANT", "Short plant", "objtypes"),
            new GamevalEntry(8190, "LARGE_LEAF_PLANT", "Large-leaf plant", "objtypes"),
            new GamevalEntry(8191, "HUGE_PLANT", "Huge plant", "objtypes"),
        };
    }

    static Optional<GamevalEntry> byId(int id) {
        for (GamevalEntry entry : entries()) {
            if (entry.id() == id) return Optional.of(entry);
        }
        return Optional.empty();
    }

}
