package net.titan.gamevals.internal;

import java.util.Optional;

import net.titan.gamevals.GamevalEntry;
import net.titan.gamevals.QuestEntry;

final class ItemIDEntries_24 {
    private ItemIDEntries_24() {}

    static GamevalEntry[] entries() {
        return new GamevalEntry[] {
            new GamevalEntry(12288, "ID_12288", "", "objtypes"),
            new GamevalEntry(12289, "MITHRIL_PLATELEGS_T", "Mithril platelegs (t)", "objtypes"),
            new GamevalEntry(12290, "ID_12290", "", "objtypes"),
            new GamevalEntry(12291, "MITHRIL_KITESHIELD_T", "Mithril kiteshield (t)", "objtypes"),
            new GamevalEntry(12292, "ID_12292", "", "objtypes"),
            new GamevalEntry(12293, "MITHRIL_FULL_HELM_T", "Mithril full helm (t)", "objtypes"),
            new GamevalEntry(12294, "ID_12294", "", "objtypes"),
            new GamevalEntry(12295, "MITHRIL_PLATESKIRT_T", "Mithril plateskirt (t)", "objtypes"),
            new GamevalEntry(12296, "ID_12296", "", "objtypes"),
            new GamevalEntry(12297, "BLACK_PICKAXE", "Black pickaxe", "objtypes"),
            new GamevalEntry(12298, "ID_12298", "", "objtypes"),
            new GamevalEntry(12299, "WHITE_HEADBAND", "White headband", "objtypes"),
            new GamevalEntry(12300, "ID_12300", "", "objtypes"),
            new GamevalEntry(12301, "BLUE_HEADBAND", "Blue headband", "objtypes"),
            new GamevalEntry(12302, "ID_12302", "", "objtypes"),
            new GamevalEntry(12303, "GOLD_HEADBAND", "Gold headband", "objtypes"),
            new GamevalEntry(12304, "ID_12304", "", "objtypes"),
            new GamevalEntry(12305, "PINK_HEADBAND", "Pink headband", "objtypes"),
            new GamevalEntry(12306, "ID_12306", "", "objtypes"),
            new GamevalEntry(12307, "GREEN_HEADBAND", "Green headband", "objtypes"),
            new GamevalEntry(12308, "ID_12308", "", "objtypes"),
            new GamevalEntry(12309, "PINK_BOATER", "Pink boater", "objtypes"),
            new GamevalEntry(12310, "ID_12310", "", "objtypes"),
            new GamevalEntry(12311, "PURPLE_BOATER", "Purple boater", "objtypes"),
            new GamevalEntry(12312, "ID_12312", "", "objtypes"),
            new GamevalEntry(12313, "WHITE_BOATER", "White boater", "objtypes"),
            new GamevalEntry(12314, "ID_12314", "", "objtypes"),
            new GamevalEntry(12315, "PINK_ELEGANT_SHIRT", "Pink elegant shirt", "objtypes"),
            new GamevalEntry(12316, "ID_12316", "", "objtypes"),
            new GamevalEntry(12317, "PINK_ELEGANT_LEGS", "Pink elegant legs", "objtypes"),
            new GamevalEntry(12318, "ID_12318", "", "objtypes"),
            new GamevalEntry(12319, "CRIER_HAT", "Crier hat", "objtypes"),
            new GamevalEntry(12320, "ID_12320", "", "objtypes"),
            new GamevalEntry(12321, "WHITE_CAVALIER", "White cavalier", "objtypes"),
            new GamevalEntry(12322, "ID_12322", "", "objtypes"),
            new GamevalEntry(12323, "RED_CAVALIER", "Red cavalier", "objtypes"),
            new GamevalEntry(12324, "ID_12324", "", "objtypes"),
            new GamevalEntry(12325, "NAVY_CAVALIER", "Navy cavalier", "objtypes"),
            new GamevalEntry(12326, "ID_12326", "", "objtypes"),
            new GamevalEntry(12327, "RED_D_HIDE_BODY_G", "Red d'hide body (g)", "objtypes"),
            new GamevalEntry(12328, "ID_12328", "", "objtypes"),
            new GamevalEntry(12329, "RED_D_HIDE_CHAPS_G", "Red d'hide chaps (g)", "objtypes"),
            new GamevalEntry(12330, "ID_12330", "", "objtypes"),
            new GamevalEntry(12331, "RED_D_HIDE_BODY_T", "Red d'hide body (t)", "objtypes"),
            new GamevalEntry(12332, "ID_12332", "", "objtypes"),
            new GamevalEntry(12333, "RED_D_HIDE_CHAPS_T", "Red d'hide chaps (t)", "objtypes"),
            new GamevalEntry(12334, "ID_12334", "", "objtypes"),
            new GamevalEntry(12335, "BRIEFCASE", "Briefcase", "objtypes"),
            new GamevalEntry(12336, "ID_12336", "", "objtypes"),
            new GamevalEntry(12337, "SAGACIOUS_SPECTACLES", "Sagacious spectacles", "objtypes"),
            new GamevalEntry(12338, "ID_12338", "", "objtypes"),
            new GamevalEntry(12339, "PINK_ELEGANT_BLOUSE", "Pink elegant blouse", "objtypes"),
            new GamevalEntry(12340, "ID_12340", "", "objtypes"),
            new GamevalEntry(12341, "PINK_ELEGANT_SKIRT", "Pink elegant skirt", "objtypes"),
            new GamevalEntry(12342, "ID_12342", "", "objtypes"),
            new GamevalEntry(12343, "GOLD_ELEGANT_BLOUSE", "Gold elegant blouse", "objtypes"),
            new GamevalEntry(12344, "ID_12344", "", "objtypes"),
            new GamevalEntry(12345, "GOLD_ELEGANT_SKIRT", "Gold elegant skirt", "objtypes"),
            new GamevalEntry(12346, "ID_12346", "", "objtypes"),
            new GamevalEntry(12347, "GOLD_ELEGANT_SHIRT", "Gold elegant shirt", "objtypes"),
            new GamevalEntry(12348, "ID_12348", "", "objtypes"),
            new GamevalEntry(12349, "GOLD_ELEGANT_LEGS", "Gold elegant legs", "objtypes"),
            new GamevalEntry(12350, "ID_12350", "", "objtypes"),
            new GamevalEntry(12351, "MUSKETEER_HAT", "Musketeer hat", "objtypes"),
            new GamevalEntry(12352, "ID_12352", "", "objtypes"),
            new GamevalEntry(12353, "MONOCLE", "Monocle", "objtypes"),
            new GamevalEntry(12354, "ID_12354", "", "objtypes"),
            new GamevalEntry(12355, "BIG_PIRATE_HAT", "Big pirate hat", "objtypes"),
            new GamevalEntry(12356, "ID_12356", "", "objtypes"),
            new GamevalEntry(12357, "KATANA", "Katana", "objtypes"),
            new GamevalEntry(12358, "ID_12358", "", "objtypes"),
            new GamevalEntry(12359, "LEPRECHAUN_HAT", "Leprechaun hat", "objtypes"),
            new GamevalEntry(12360, "ID_12360", "", "objtypes"),
            new GamevalEntry(12361, "CAT_MASK", "Cat mask", "objtypes"),
            new GamevalEntry(12362, "ID_12362", "", "objtypes"),
            new GamevalEntry(12363, "BRONZE_DRAGON_MASK", "Bronze dragon mask", "objtypes"),
            new GamevalEntry(12364, "ID_12364", "", "objtypes"),
            new GamevalEntry(12365, "IRON_DRAGON_MASK", "Iron dragon mask", "objtypes"),
            new GamevalEntry(12366, "ID_12366", "", "objtypes"),
            new GamevalEntry(12367, "STEEL_DRAGON_MASK", "Steel dragon mask", "objtypes"),
            new GamevalEntry(12368, "ID_12368", "", "objtypes"),
            new GamevalEntry(12369, "MITHRIL_DRAGON_MASK", "Mithril dragon mask", "objtypes"),
            new GamevalEntry(12370, "ID_12370", "", "objtypes"),
            new GamevalEntry(12371, "LAVA_DRAGON_MASK", "Lava dragon mask", "objtypes"),
            new GamevalEntry(12372, "ID_12372", "", "objtypes"),
            new GamevalEntry(12373, "DRAGON_CANE", "Dragon cane", "objtypes"),
            new GamevalEntry(12374, "ID_12374", "", "objtypes"),
            new GamevalEntry(12375, "BLACK_CANE", "Black cane", "objtypes"),
            new GamevalEntry(12376, "ID_12376", "", "objtypes"),
            new GamevalEntry(12377, "ADAMANT_CANE", "Adamant cane", "objtypes"),
            new GamevalEntry(12378, "ID_12378", "", "objtypes"),
            new GamevalEntry(12379, "RUNE_CANE", "Rune cane", "objtypes"),
            new GamevalEntry(12380, "ID_12380", "", "objtypes"),
            new GamevalEntry(12381, "BLACK_D_HIDE_BODY_G", "Black d'hide body (g)", "objtypes"),
            new GamevalEntry(12382, "ID_12382", "", "objtypes"),
            new GamevalEntry(12383, "BLACK_D_HIDE_CHAPS_G", "Black d'hide chaps (g)", "objtypes"),
            new GamevalEntry(12384, "ID_12384", "", "objtypes"),
            new GamevalEntry(12385, "BLACK_D_HIDE_BODY_T", "Black d'hide body (t)", "objtypes"),
            new GamevalEntry(12386, "ID_12386", "", "objtypes"),
            new GamevalEntry(12387, "BLACK_D_HIDE_CHAPS_T", "Black d'hide chaps (t)", "objtypes"),
            new GamevalEntry(12388, "ID_12388", "", "objtypes"),
            new GamevalEntry(12389, "GILDED_SCIMITAR", "Gilded scimitar", "objtypes"),
            new GamevalEntry(12390, "ID_12390", "", "objtypes"),
            new GamevalEntry(12391, "GILDED_BOOTS", "Gilded boots", "objtypes"),
            new GamevalEntry(12392, "ID_12392", "", "objtypes"),
            new GamevalEntry(12393, "ROYAL_GOWN_TOP", "Royal gown top", "objtypes"),
            new GamevalEntry(12394, "ID_12394", "", "objtypes"),
            new GamevalEntry(12395, "ROYAL_GOWN_BOTTOM", "Royal gown bottom", "objtypes"),
            new GamevalEntry(12396, "ID_12396", "", "objtypes"),
            new GamevalEntry(12397, "ROYAL_CROWN", "Royal crown", "objtypes"),
            new GamevalEntry(12398, "ID_12398", "", "objtypes"),
            new GamevalEntry(12399, "PARTYHAT_SPECS", "Partyhat & specs", "objtypes"),
            new GamevalEntry(12400, "ID_12400", "", "objtypes"),
            new GamevalEntry(12401, "ID_12401", "", "objtypes"),
            new GamevalEntry(12402, "NARDAH_TELEPORT", "Nardah teleport", "objtypes"),
            new GamevalEntry(12403, "DIGSITE_TELEPORT", "Digsite teleport", "objtypes"),
            new GamevalEntry(12404, "FELDIP_HILLS_TELEPORT", "Feldip hills teleport", "objtypes"),
            new GamevalEntry(12405, "LUNAR_ISLE_TELEPORT", "Lunar isle teleport", "objtypes"),
            new GamevalEntry(12406, "MORT_TON_TELEPORT", "Mort'ton teleport", "objtypes"),
            new GamevalEntry(12407, "PEST_CONTROL_TELEPORT", "Pest control teleport", "objtypes"),
            new GamevalEntry(12408, "PISCATORIS_TELEPORT", "Piscatoris teleport", "objtypes"),
            new GamevalEntry(12409, "TAI_BWO_WANNAI_TELEPORT", "Tai bwo wannai teleport", "objtypes"),
            new GamevalEntry(12410, "IORWERTH_CAMP_TELEPORT", "Iorwerth camp teleport", "objtypes"),
            new GamevalEntry(12411, "MOS_LE_HARMLESS_TELEPORT", "Mos le'harmless teleport", "objtypes"),
            new GamevalEntry(12412, "PIRATE_HAT_PATCH", "Pirate hat & patch", "objtypes"),
            new GamevalEntry(12413, "ID_12413", "", "objtypes"),
            new GamevalEntry(12414, "DRAGON_CHAINBODY_G", "Dragon chainbody (g)", "objtypes"),
            new GamevalEntry(12415, "DRAGON_PLATELEGS_G", "Dragon platelegs (g)", "objtypes"),
            new GamevalEntry(12416, "DRAGON_PLATESKIRT_G", "Dragon plateskirt (g)", "objtypes"),
            new GamevalEntry(12417, "DRAGON_FULL_HELM_G", "Dragon full helm (g)", "objtypes"),
            new GamevalEntry(12418, "DRAGON_SQ_SHIELD_G", "Dragon sq shield (g)", "objtypes"),
            new GamevalEntry(12419, "LIGHT_INFINITY_HAT", "Light infinity hat", "objtypes"),
            new GamevalEntry(12420, "LIGHT_INFINITY_TOP", "Light infinity top", "objtypes"),
            new GamevalEntry(12421, "LIGHT_INFINITY_BOTTOMS", "Light infinity bottoms", "objtypes"),
            new GamevalEntry(12422, "I_A_3RD_AGE_WAND", "I? A 3rd age wand", "objtypes"),
            new GamevalEntry(12423, "ID_12423", "", "objtypes"),
            new GamevalEntry(12424, "I_A_3RD_AGE_BOW", "I? A 3rd age bow", "objtypes"),
            new GamevalEntry(12425, "ID_12425", "", "objtypes"),
            new GamevalEntry(12426, "I_A_3RD_AGE_LONGSWORD", "I? A 3rd age longsword", "objtypes"),
            new GamevalEntry(12427, "ID_12427", "", "objtypes"),
            new GamevalEntry(12428, "PENGUIN_MASK", "Penguin mask", "objtypes"),
            new GamevalEntry(12429, "ID_12429", "", "objtypes"),
            new GamevalEntry(12430, "AFRO", "Afro", "objtypes"),
            new GamevalEntry(12431, "ID_12431", "", "objtypes"),
            new GamevalEntry(12432, "TOP_HAT", "Top hat", "objtypes"),
            new GamevalEntry(12433, "ID_12433", "", "objtypes"),
            new GamevalEntry(12434, "TOP_HAT_MONOCLE", "Top hat & monocle", "objtypes"),
            new GamevalEntry(12435, "ID_12435", "", "objtypes"),
            new GamevalEntry(12436, "AMULET_OF_FURY_OR", "Amulet of fury (or)", "objtypes"),
            new GamevalEntry(12437, "ID_12437_3RD_AGE_CLOAK", "3rd age cloak", "objtypes"),
            new GamevalEntry(12438, "ID_12438", "", "objtypes"),
            new GamevalEntry(12439, "ROYAL_SCEPTRE", "Royal sceptre", "objtypes"),
            new GamevalEntry(12440, "ID_12440", "", "objtypes"),
            new GamevalEntry(12441, "MUSKETEER_TABARD", "Musketeer tabard", "objtypes"),
            new GamevalEntry(12442, "ID_12442", "", "objtypes"),
            new GamevalEntry(12443, "MUSKETEER_PANTS", "Musketeer pants", "objtypes"),
            new GamevalEntry(12444, "ID_12444", "", "objtypes"),
            new GamevalEntry(12445, "BLACK_SKIRT_G", "Black skirt (g)", "objtypes"),
            new GamevalEntry(12446, "ID_12446", "", "objtypes"),
            new GamevalEntry(12447, "BLACK_SKIRT_T", "Black skirt (t)", "objtypes"),
            new GamevalEntry(12448, "ID_12448", "", "objtypes"),
            new GamevalEntry(12449, "BLACK_WIZARD_ROBE_G", "Black wizard robe (g)", "objtypes"),
            new GamevalEntry(12450, "ID_12450", "", "objtypes"),
            new GamevalEntry(12451, "BLACK_WIZARD_ROBE_T", "Black wizard robe (t)", "objtypes"),
            new GamevalEntry(12452, "ID_12452", "", "objtypes"),
            new GamevalEntry(12453, "BLACK_WIZARD_HAT_G", "Black wizard hat (g)", "objtypes"),
            new GamevalEntry(12454, "ID_12454", "", "objtypes"),
            new GamevalEntry(12455, "BLACK_WIZARD_HAT_T", "Black wizard hat (t)", "objtypes"),
            new GamevalEntry(12456, "ID_12456", "", "objtypes"),
            new GamevalEntry(12457, "DARK_INFINITY_HAT", "Dark infinity hat", "objtypes"),
            new GamevalEntry(12458, "DARK_INFINITY_TOP", "Dark infinity top", "objtypes"),
            new GamevalEntry(12459, "DARK_INFINITY_BOTTOMS", "Dark infinity bottoms", "objtypes"),
            new GamevalEntry(12460, "ANCIENT_PLATEBODY", "Ancient platebody", "objtypes"),
            new GamevalEntry(12461, "ID_12461", "", "objtypes"),
            new GamevalEntry(12462, "ANCIENT_PLATELEGS", "Ancient platelegs", "objtypes"),
            new GamevalEntry(12463, "ID_12463", "", "objtypes"),
            new GamevalEntry(12464, "ANCIENT_PLATESKIRT", "Ancient plateskirt", "objtypes"),
            new GamevalEntry(12465, "ID_12465", "", "objtypes"),
            new GamevalEntry(12466, "ANCIENT_FULL_HELM", "Ancient full helm", "objtypes"),
            new GamevalEntry(12467, "ID_12467", "", "objtypes"),
            new GamevalEntry(12468, "ANCIENT_KITESHIELD", "Ancient kiteshield", "objtypes"),
            new GamevalEntry(12469, "ID_12469", "", "objtypes"),
            new GamevalEntry(12470, "ARMADYL_PLATEBODY", "Armadyl platebody", "objtypes"),
            new GamevalEntry(12471, "ID_12471", "", "objtypes"),
            new GamevalEntry(12472, "ARMADYL_PLATELEGS", "Armadyl platelegs", "objtypes"),
            new GamevalEntry(12473, "ID_12473", "", "objtypes"),
            new GamevalEntry(12474, "ARMADYL_PLATESKIRT", "Armadyl plateskirt", "objtypes"),
            new GamevalEntry(12475, "ID_12475", "", "objtypes"),
            new GamevalEntry(12476, "ARMADYL_FULL_HELM", "Armadyl full helm", "objtypes"),
            new GamevalEntry(12477, "ID_12477", "", "objtypes"),
            new GamevalEntry(12478, "ARMADYL_KITESHIELD", "Armadyl kiteshield", "objtypes"),
            new GamevalEntry(12479, "ID_12479", "", "objtypes"),
            new GamevalEntry(12480, "BANDOS_PLATEBODY", "Bandos platebody", "objtypes"),
            new GamevalEntry(12481, "ID_12481", "", "objtypes"),
            new GamevalEntry(12482, "BANDOS_PLATELEGS", "Bandos platelegs", "objtypes"),
            new GamevalEntry(12483, "ID_12483", "", "objtypes"),
            new GamevalEntry(12484, "BANDOS_PLATESKIRT", "Bandos plateskirt", "objtypes"),
            new GamevalEntry(12485, "ID_12485", "", "objtypes"),
            new GamevalEntry(12486, "BANDOS_FULL_HELM", "Bandos full helm", "objtypes"),
            new GamevalEntry(12487, "ID_12487", "", "objtypes"),
            new GamevalEntry(12488, "BANDOS_KITESHIELD", "Bandos kiteshield", "objtypes"),
            new GamevalEntry(12489, "ID_12489", "", "objtypes"),
            new GamevalEntry(12490, "ANCIENT_BRACERS", "Ancient bracers", "objtypes"),
            new GamevalEntry(12491, "ID_12491", "", "objtypes"),
            new GamevalEntry(12492, "ANCIENT_D_HIDE_BODY", "Ancient d'hide body", "objtypes"),
            new GamevalEntry(12493, "ID_12493", "", "objtypes"),
            new GamevalEntry(12494, "ANCIENT_CHAPS", "Ancient chaps", "objtypes"),
            new GamevalEntry(12495, "ID_12495", "", "objtypes"),
            new GamevalEntry(12496, "ANCIENT_COIF", "Ancient coif", "objtypes"),
            new GamevalEntry(12497, "ID_12497", "", "objtypes"),
            new GamevalEntry(12498, "BANDOS_BRACERS", "Bandos bracers", "objtypes"),
            new GamevalEntry(12499, "ID_12499", "", "objtypes"),
            new GamevalEntry(12500, "BANDOS_D_HIDE_BODY", "Bandos d'hide body", "objtypes"),
            new GamevalEntry(12501, "ID_12501", "", "objtypes"),
            new GamevalEntry(12502, "BANDOS_CHAPS", "Bandos chaps", "objtypes"),
            new GamevalEntry(12503, "ID_12503", "", "objtypes"),
            new GamevalEntry(12504, "BANDOS_COIF", "Bandos coif", "objtypes"),
            new GamevalEntry(12505, "ID_12505", "", "objtypes"),
            new GamevalEntry(12506, "ARMADYL_BRACERS", "Armadyl bracers", "objtypes"),
            new GamevalEntry(12507, "ID_12507", "", "objtypes"),
            new GamevalEntry(12508, "ARMADYL_D_HIDE_BODY", "Armadyl d'hide body", "objtypes"),
            new GamevalEntry(12509, "ID_12509", "", "objtypes"),
            new GamevalEntry(12510, "ARMADYL_CHAPS", "Armadyl chaps", "objtypes"),
            new GamevalEntry(12511, "ID_12511", "", "objtypes"),
            new GamevalEntry(12512, "ARMADYL_COIF", "Armadyl coif", "objtypes"),
            new GamevalEntry(12513, "ID_12513", "", "objtypes"),
            new GamevalEntry(12514, "EXPLORER_BACKPACK", "Explorer backpack", "objtypes"),
            new GamevalEntry(12515, "ID_12515", "", "objtypes"),
            new GamevalEntry(12516, "PITH_HELMET", "Pith helmet", "objtypes"),
            new GamevalEntry(12517, "ID_12517", "", "objtypes"),
            new GamevalEntry(12518, "GREEN_DRAGON_MASK", "Green dragon mask", "objtypes"),
            new GamevalEntry(12519, "ID_12519", "", "objtypes"),
            new GamevalEntry(12520, "BLUE_DRAGON_MASK", "Blue dragon mask", "objtypes"),
            new GamevalEntry(12521, "ID_12521", "", "objtypes"),
            new GamevalEntry(12522, "RED_DRAGON_MASK", "Red dragon mask", "objtypes"),
            new GamevalEntry(12523, "ID_12523", "", "objtypes"),
            new GamevalEntry(12524, "BLACK_DRAGON_MASK", "Black dragon mask", "objtypes"),
            new GamevalEntry(12525, "ID_12525", "", "objtypes"),
            new GamevalEntry(12526, "FURY_ORNAMENT_KIT", "Fury ornament kit", "objtypes"),
            new GamevalEntry(12527, "ID_12527", "", "objtypes"),
            new GamevalEntry(12528, "DARK_INFINITY_COLOUR_KIT", "Dark infinity colour kit", "objtypes"),
            new GamevalEntry(12529, "ID_12529", "", "objtypes"),
            new GamevalEntry(12530, "LIGHT_INFINITY_COLOUR_KIT", "Light infinity colour kit", "objtypes"),
            new GamevalEntry(12531, "ID_12531", "", "objtypes"),
            new GamevalEntry(12532, "DRAGON_SQ_SHIELD_ORNAMENT_KIT", "Dragon sq shield ornament kit", "objtypes"),
            new GamevalEntry(12533, "ID_12533", "", "objtypes"),
            new GamevalEntry(12534, "DRAGON_CHAINBODY_ORNAMENT_KIT", "Dragon chainbody ornament kit", "objtypes"),
            new GamevalEntry(12535, "ID_12535", "", "objtypes"),
            new GamevalEntry(12536, "DRAGON_LEGS_SKIRT_ORNAMENT_KIT", "Dragon legs/skirt ornament kit", "objtypes"),
            new GamevalEntry(12537, "ID_12537", "", "objtypes"),
            new GamevalEntry(12538, "DRAGON_FULL_HELM_ORNAMENT_KIT", "Dragon full helm ornament kit", "objtypes"),
            new GamevalEntry(12539, "ID_12539", "", "objtypes"),
            new GamevalEntry(12540, "DEERSTALKER", "Deerstalker", "objtypes"),
            new GamevalEntry(12541, "ID_12541", "", "objtypes"),
            new GamevalEntry(12542, "CLUE_SCROLL_HARD_12542", "Clue scroll (hard)", "objtypes"),
            new GamevalEntry(12543, "CASKET_HARD_12543", "Casket (hard)", "objtypes"),
            new GamevalEntry(12544, "CLUE_SCROLL_HARD_12544", "Clue scroll (hard)", "objtypes"),
            new GamevalEntry(12545, "CASKET_HARD_12545", "Casket (hard)", "objtypes"),
            new GamevalEntry(12546, "CLUE_SCROLL_HARD_12546", "Clue scroll (hard)", "objtypes"),
            new GamevalEntry(12547, "CASKET_HARD_12547", "Casket (hard)", "objtypes"),
            new GamevalEntry(12548, "CLUE_SCROLL_HARD_12548", "Clue scroll (hard)", "objtypes"),
            new GamevalEntry(12549, "CASKET_HARD_12549", "Casket (hard)", "objtypes"),
            new GamevalEntry(12550, "CLUE_SCROLL_HARD_12550", "Clue scroll (hard)", "objtypes"),
            new GamevalEntry(12551, "CASKET_HARD_12551", "Casket (hard)", "objtypes"),
            new GamevalEntry(12552, "CLUE_SCROLL_HARD_12552", "Clue scroll (hard)", "objtypes"),
            new GamevalEntry(12553, "CASKET_HARD_12553", "Casket (hard)", "objtypes"),
            new GamevalEntry(12554, "CLUE_SCROLL_HARD_12554", "Clue scroll (hard)", "objtypes"),
            new GamevalEntry(12555, "CASKET_HARD_12555", "Casket (hard)", "objtypes"),
            new GamevalEntry(12556, "CLUE_SCROLL_HARD_12556", "Clue scroll (hard)", "objtypes"),
            new GamevalEntry(12557, "CASKET_HARD_12557", "Casket (hard)", "objtypes"),
            new GamevalEntry(12558, "CLUE_SCROLL_HARD_12558", "Clue scroll (hard)", "objtypes"),
            new GamevalEntry(12559, "CASKET_HARD_12559", "Casket (hard)", "objtypes"),
            new GamevalEntry(12560, "CLUE_SCROLL_HARD_12560", "Clue scroll (hard)", "objtypes"),
            new GamevalEntry(12561, "CASKET_HARD_12561", "Casket (hard)", "objtypes"),
            new GamevalEntry(12562, "CLUE_SCROLL_HARD_12562", "Clue scroll (hard)", "objtypes"),
            new GamevalEntry(12563, "CASKET_HARD_12563", "Casket (hard)", "objtypes"),
            new GamevalEntry(12564, "CLUE_SCROLL_HARD_12564", "Clue scroll (hard)", "objtypes"),
            new GamevalEntry(12565, "CASKET_HARD_12565", "Casket (hard)", "objtypes"),
            new GamevalEntry(12566, "CLUE_SCROLL_HARD_12566", "Clue scroll (hard)", "objtypes"),
            new GamevalEntry(12567, "CHALLENGE_SCROLL_HARD_12567", "Challenge scroll (hard)", "objtypes"),
            new GamevalEntry(12568, "CLUE_SCROLL_HARD_12568", "Clue scroll (hard)", "objtypes"),
            new GamevalEntry(12569, "CHALLENGE_SCROLL_HARD_12569", "Challenge scroll (hard)", "objtypes"),
            new GamevalEntry(12570, "CLUE_SCROLL_HARD_12570", "Clue scroll (hard)", "objtypes"),
            new GamevalEntry(12571, "CHALLENGE_SCROLL_HARD_12571", "Challenge scroll (hard)", "objtypes"),
            new GamevalEntry(12572, "CLUE_SCROLL_HARD_12572", "Clue scroll (hard)", "objtypes"),
            new GamevalEntry(12573, "CHALLENGE_SCROLL_HARD_12573", "Challenge scroll (hard)", "objtypes"),
            new GamevalEntry(12574, "CLUE_SCROLL_HARD_12574", "Clue scroll (hard)", "objtypes"),
            new GamevalEntry(12575, "CHALLENGE_SCROLL_HARD_12575", "Challenge scroll (hard)", "objtypes"),
            new GamevalEntry(12576, "CLUE_SCROLL_HARD_12576", "Clue scroll (hard)", "objtypes"),
            new GamevalEntry(12577, "CHALLENGE_SCROLL_HARD_12577", "Challenge scroll (hard)", "objtypes"),
            new GamevalEntry(12578, "CLUE_SCROLL_HARD_12578", "Clue scroll (hard)", "objtypes"),
            new GamevalEntry(12579, "PUZZLE_BOX_HARD_12579", "Puzzle box (hard)", "objtypes"),
            new GamevalEntry(12580, "CASKET_HARD_12580", "Casket (hard)", "objtypes"),
            new GamevalEntry(12581, "CLUE_SCROLL_HARD_12581", "Clue scroll (hard)", "objtypes"),
            new GamevalEntry(12582, "PUZZLE_BOX_HARD_12582", "Puzzle box (hard)", "objtypes"),
            new GamevalEntry(12583, "CASKET_HARD_12583", "Casket (hard)", "objtypes"),
            new GamevalEntry(12584, "CLUE_SCROLL_HARD_12584", "Clue scroll (hard)", "objtypes"),
            new GamevalEntry(12585, "PUZZLE_BOX_HARD_12585", "Puzzle box (hard)", "objtypes"),
            new GamevalEntry(12586, "CASKET_HARD_12586", "Casket (hard)", "objtypes"),
            new GamevalEntry(12587, "CLUE_SCROLL_HARD_12587", "Clue scroll (hard)", "objtypes"),
            new GamevalEntry(12588, "PUZZLE_BOX_HARD_12588", "Puzzle box (hard)", "objtypes"),
            new GamevalEntry(12589, "CASKET_HARD_12589", "Casket (hard)", "objtypes"),
            new GamevalEntry(12590, "CLUE_SCROLL_HARD_12590", "Clue scroll (hard)", "objtypes"),
            new GamevalEntry(12591, "CASKET_HARD_12591", "Casket (hard)", "objtypes"),
            new GamevalEntry(12592, "BLACK_PICK_HEAD", "Black pick head", "objtypes"),
            new GamevalEntry(12593, "ID_12593", "", "objtypes"),
            new GamevalEntry(12594, "BROKEN_PICKAXE_12594", "Broken pickaxe", "objtypes"),
            new GamevalEntry(12595, "ID_12595", "", "objtypes"),
            new GamevalEntry(12596, "RANGERS_TUNIC", "Rangers' tunic", "objtypes"),
            new GamevalEntry(12597, "ID_12597", "", "objtypes"),
            new GamevalEntry(12598, "HOLY_SANDALS", "Holy sandals", "objtypes"),
            new GamevalEntry(12599, "ID_12599", "", "objtypes"),
            new GamevalEntry(12600, "DRUIDIC_WREATH", "Druidic wreath", "objtypes"),
            new GamevalEntry(12601, "RING_OF_THE_GODS", "Ring of the gods", "objtypes"),
            new GamevalEntry(12602, "ID_12602", "", "objtypes"),
            new GamevalEntry(12603, "TYRANNICAL_RING", "Tyrannical ring", "objtypes"),
            new GamevalEntry(12604, "ID_12604", "", "objtypes"),
            new GamevalEntry(12605, "TREASONOUS_RING", "Treasonous ring", "objtypes"),
            new GamevalEntry(12606, "ID_12606", "", "objtypes"),
            new GamevalEntry(12607, "DAMAGED_BOOK_12607", "Damaged book", "objtypes"),
            new GamevalEntry(12608, "BOOK_OF_WAR", "Book of war", "objtypes"),
            new GamevalEntry(12609, "DAMAGED_BOOK_12609", "Damaged book", "objtypes"),
            new GamevalEntry(12610, "BOOK_OF_LAW", "Book of law", "objtypes"),
            new GamevalEntry(12611, "DAMAGED_BOOK_12611", "Damaged book", "objtypes"),
            new GamevalEntry(12612, "BOOK_OF_DARKNESS", "Book of darkness", "objtypes"),
            new GamevalEntry(12613, "BANDOS_PAGE_1", "Bandos page 1", "objtypes"),
            new GamevalEntry(12614, "BANDOS_PAGE_2", "Bandos page 2", "objtypes"),
            new GamevalEntry(12615, "BANDOS_PAGE_3", "Bandos page 3", "objtypes"),
            new GamevalEntry(12616, "BANDOS_PAGE_4", "Bandos page 4", "objtypes"),
            new GamevalEntry(12617, "ARMADYL_PAGE_1", "Armadyl page 1", "objtypes"),
            new GamevalEntry(12618, "ARMADYL_PAGE_2", "Armadyl page 2", "objtypes"),
            new GamevalEntry(12619, "ARMADYL_PAGE_3", "Armadyl page 3", "objtypes"),
            new GamevalEntry(12620, "ARMADYL_PAGE_4", "Armadyl page 4", "objtypes"),
            new GamevalEntry(12621, "ANCIENT_PAGE_1", "Ancient page 1", "objtypes"),
            new GamevalEntry(12622, "ANCIENT_PAGE_2", "Ancient page 2", "objtypes"),
            new GamevalEntry(12623, "ANCIENT_PAGE_3", "Ancient page 3", "objtypes"),
            new GamevalEntry(12624, "ANCIENT_PAGE_4", "Ancient page 4", "objtypes"),
            new GamevalEntry(12625, "STAMINA_POTION_4", "Stamina potion(4)", "objtypes"),
            new GamevalEntry(12626, "ID_12626", "", "objtypes"),
            new GamevalEntry(12627, "STAMINA_POTION_3", "Stamina potion(3)", "objtypes"),
            new GamevalEntry(12628, "ID_12628", "", "objtypes"),
            new GamevalEntry(12629, "STAMINA_POTION_2", "Stamina potion(2)", "objtypes"),
            new GamevalEntry(12630, "ID_12630", "", "objtypes"),
            new GamevalEntry(12631, "STAMINA_POTION_1", "Stamina potion(1)", "objtypes"),
            new GamevalEntry(12632, "ID_12632", "", "objtypes"),
            new GamevalEntry(12633, "STAMINA_MIX_2", "Stamina mix(2)", "objtypes"),
            new GamevalEntry(12634, "ID_12634", "", "objtypes"),
            new GamevalEntry(12635, "STAMINA_MIX_1", "Stamina mix(1)", "objtypes"),
            new GamevalEntry(12636, "ID_12636", "", "objtypes"),
            new GamevalEntry(12637, "SARADOMIN_HALO", "Saradomin halo", "objtypes"),
            new GamevalEntry(12638, "ZAMORAK_HALO", "Zamorak halo", "objtypes"),
            new GamevalEntry(12639, "GUTHIX_HALO", "Guthix halo", "objtypes"),
            new GamevalEntry(12640, "AMYLASE_CRYSTAL", "Amylase crystal", "objtypes"),
            new GamevalEntry(12641, "AMYLASE_PACK", "Amylase pack", "objtypes"),
            new GamevalEntry(12642, "LUMBERYARD_TELEPORT", "Lumberyard teleport", "objtypes"),
            new GamevalEntry(12643, "PET_DAGANNOTH_SUPREME", "Pet dagannoth supreme", "objtypes"),
            new GamevalEntry(12644, "PET_DAGANNOTH_PRIME", "Pet dagannoth prime", "objtypes"),
            new GamevalEntry(12645, "PET_DAGANNOTH_REX", "Pet dagannoth rex", "objtypes"),
            new GamevalEntry(12646, "BABY_MOLE", "Baby mole", "objtypes"),
            new GamevalEntry(12647, "KALPHITE_PRINCESS", "Kalphite princess", "objtypes"),
            new GamevalEntry(12648, "PET_SMOKE_DEVIL", "Pet smoke devil", "objtypes"),
            new GamevalEntry(12649, "PET_KREE_ARRA", "Pet kree'arra", "objtypes"),
            new GamevalEntry(12650, "PET_GENERAL_GRAARDOR", "Pet general graardor", "objtypes"),
            new GamevalEntry(12651, "PET_ZILYANA", "Pet zilyana", "objtypes"),
            new GamevalEntry(12652, "PET_K_RIL_TSUTSAROTH", "Pet k'ril tsutsaroth", "objtypes"),
            new GamevalEntry(12653, "PRINCE_BLACK_DRAGON", "Prince black dragon", "objtypes"),
            new GamevalEntry(12654, "KALPHITE_PRINCESS_12654", "Kalphite princess", "objtypes"),
            new GamevalEntry(12655, "PET_KRAKEN", "Pet kraken", "objtypes"),
            new GamevalEntry(12656, "JUNK", "Junk", "objtypes"),
            new GamevalEntry(12657, "JUNK_12657", "Junk", "objtypes"),
            new GamevalEntry(12658, "IBAN_S_STAFF_U", "Iban's staff (u)", "objtypes"),
            new GamevalEntry(12659, "CLAN_WARS_CAPE", "Clan wars cape", "objtypes"),
            new GamevalEntry(12660, "CLAN_WARS_CAPE_12660", "Clan wars cape", "objtypes"),
            new GamevalEntry(12661, "CLAN_WARS_CAPE_12661", "Clan wars cape", "objtypes"),
            new GamevalEntry(12662, "CLAN_WARS_CAPE_12662", "Clan wars cape", "objtypes"),
            new GamevalEntry(12663, "CLAN_WARS_CAPE_12663", "Clan wars cape", "objtypes"),
            new GamevalEntry(12664, "CLAN_WARS_CAPE_12664", "Clan wars cape", "objtypes"),
            new GamevalEntry(12665, "CLAN_WARS_CAPE_12665", "Clan wars cape", "objtypes"),
            new GamevalEntry(12666, "CLAN_WARS_CAPE_12666", "Clan wars cape", "objtypes"),
            new GamevalEntry(12667, "CLAN_WARS_CAPE_12667", "Clan wars cape", "objtypes"),
            new GamevalEntry(12668, "CLAN_WARS_CAPE_12668", "Clan wars cape", "objtypes"),
            new GamevalEntry(12669, "CLAN_WARS_CAPE_12669", "Clan wars cape", "objtypes"),
            new GamevalEntry(12670, "CLAN_WARS_CAPE_12670", "Clan wars cape", "objtypes"),
            new GamevalEntry(12671, "CLAN_WARS_CAPE_12671", "Clan wars cape", "objtypes"),
            new GamevalEntry(12672, "CLAN_WARS_CAPE_12672", "Clan wars cape", "objtypes"),
            new GamevalEntry(12673, "CLAN_WARS_CAPE_12673", "Clan wars cape", "objtypes"),
            new GamevalEntry(12674, "CLAN_WARS_CAPE_12674", "Clan wars cape", "objtypes"),
            new GamevalEntry(12675, "CLAN_WARS_CAPE_12675", "Clan wars cape", "objtypes"),
            new GamevalEntry(12676, "CLAN_WARS_CAPE_12676", "Clan wars cape", "objtypes"),
            new GamevalEntry(12677, "CLAN_WARS_CAPE_12677", "Clan wars cape", "objtypes"),
            new GamevalEntry(12678, "CLAN_WARS_CAPE_12678", "Clan wars cape", "objtypes"),
            new GamevalEntry(12679, "CLAN_WARS_CAPE_12679", "Clan wars cape", "objtypes"),
            new GamevalEntry(12680, "CLAN_WARS_CAPE_12680", "Clan wars cape", "objtypes"),
            new GamevalEntry(12681, "CLAN_WARS_CAPE_12681", "Clan wars cape", "objtypes"),
            new GamevalEntry(12682, "CLAN_WARS_CAPE_12682", "Clan wars cape", "objtypes"),
            new GamevalEntry(12683, "CLAN_WARS_CAPE_12683", "Clan wars cape", "objtypes"),
            new GamevalEntry(12684, "CLAN_WARS_CAPE_12684", "Clan wars cape", "objtypes"),
            new GamevalEntry(12685, "CLAN_WARS_CAPE_12685", "Clan wars cape", "objtypes"),
            new GamevalEntry(12686, "CLAN_WARS_CAPE_12686", "Clan wars cape", "objtypes"),
            new GamevalEntry(12687, "CLAN_WARS_CAPE_12687", "Clan wars cape", "objtypes"),
            new GamevalEntry(12688, "CLAN_WARS_CAPE_12688", "Clan wars cape", "objtypes"),
            new GamevalEntry(12689, "CLAN_WARS_CAPE_12689", "Clan wars cape", "objtypes"),
            new GamevalEntry(12690, "CLAN_WARS_CAPE_12690", "Clan wars cape", "objtypes"),
            new GamevalEntry(12691, "TYRANNICAL_RING_I", "Tyrannical ring (i)", "objtypes"),
            new GamevalEntry(12692, "TREASONOUS_RING_I", "Treasonous ring (i)", "objtypes"),
            new GamevalEntry(12693, "KREE_ARRA", "Kree'arra", "objtypes"),
            new GamevalEntry(12694, "CHAOS_ELEMENTAL", "Chaos elemental", "objtypes"),
            new GamevalEntry(12695, "SUPER_COMBAT_POTION_4", "Super combat potion(4)", "objtypes"),
            new GamevalEntry(12696, "ID_12696", "", "objtypes"),
            new GamevalEntry(12697, "SUPER_COMBAT_POTION_3", "Super combat potion(3)", "objtypes"),
            new GamevalEntry(12698, "ID_12698", "", "objtypes"),
            new GamevalEntry(12699, "SUPER_COMBAT_POTION_2", "Super combat potion(2)", "objtypes"),
            new GamevalEntry(12700, "ID_12700", "", "objtypes"),
            new GamevalEntry(12701, "SUPER_COMBAT_POTION_1", "Super combat potion(1)", "objtypes"),
            new GamevalEntry(12702, "ID_12702", "", "objtypes"),
            new GamevalEntry(12703, "PET_PENANCE_QUEEN", "Pet penance queen", "objtypes"),
            new GamevalEntry(12704, "OAK_HOUSE", "Oak house", "objtypes"),
            new GamevalEntry(12705, "TEAK_HOUSE", "Teak house", "objtypes"),
            new GamevalEntry(12706, "MAHOGANY_HOUSE", "Mahogany house", "objtypes"),
            new GamevalEntry(12707, "CONSECRATED_HOUSE", "Consecrated house", "objtypes"),
            new GamevalEntry(12708, "DESECRATED_HOUSE", "Desecrated house", "objtypes"),
            new GamevalEntry(12709, "NATURE_HOUSE", "Nature house", "objtypes"),
            new GamevalEntry(12710, "GRASSLAND_HABITAT", "Grassland habitat", "objtypes"),
            new GamevalEntry(12711, "FOREST_HABITAT", "Forest habitat", "objtypes"),
            new GamevalEntry(12712, "DESERT_HABITAT", "Desert habitat", "objtypes"),
            new GamevalEntry(12713, "POLAR_HABITAT", "Polar habitat", "objtypes"),
            new GamevalEntry(12714, "VOLCANIC_HABITAT", "Volcanic habitat", "objtypes"),
            new GamevalEntry(12715, "OAK_SCRATCHING_POST", "Oak scratching post", "objtypes"),
            new GamevalEntry(12716, "TEAK_SCRATCHING_POST", "Teak scratching post", "objtypes"),
            new GamevalEntry(12717, "MAHOGANY_SCRATCHING_POST", "Mahogany scratching post", "objtypes"),
            new GamevalEntry(12718, "SIMPLE_ARENA", "Simple arena", "objtypes"),
            new GamevalEntry(12719, "ADVANCED_ARENA", "Advanced arena", "objtypes"),
            new GamevalEntry(12720, "GLORIOUS_ARENA", "Glorious arena", "objtypes"),
            new GamevalEntry(12721, "PET_LIST", "Pet list", "objtypes"),
            new GamevalEntry(12722, "OAK_FEEDER", "Oak feeder", "objtypes"),
            new GamevalEntry(12723, "TEAK_FEEDER", "Teak feeder", "objtypes"),
            new GamevalEntry(12724, "MAHOGANY_FEEDER", "Mahogany feeder", "objtypes"),
            new GamevalEntry(12725, "MENAGERIE", "Menagerie", "objtypes"),
            new GamevalEntry(12726, "MENAGERIE_12726", "Menagerie", "objtypes"),
            new GamevalEntry(12727, "GOBLIN_PAINT_CANNON", "Goblin paint cannon", "objtypes"),
            new GamevalEntry(12728, "AIR_RUNE_PACK", "Air rune pack", "objtypes"),
            new GamevalEntry(12729, "ID_12729", "", "objtypes"),
            new GamevalEntry(12730, "WATER_RUNE_PACK", "Water rune pack", "objtypes"),
            new GamevalEntry(12731, "ID_12731", "", "objtypes"),
            new GamevalEntry(12732, "EARTH_RUNE_PACK", "Earth rune pack", "objtypes"),
            new GamevalEntry(12733, "ID_12733", "", "objtypes"),
            new GamevalEntry(12734, "FIRE_RUNE_PACK", "Fire rune pack", "objtypes"),
            new GamevalEntry(12735, "ID_12735", "", "objtypes"),
            new GamevalEntry(12736, "MIND_RUNE_PACK", "Mind rune pack", "objtypes"),
            new GamevalEntry(12737, "ID_12737", "", "objtypes"),
            new GamevalEntry(12738, "CHAOS_RUNE_PACK", "Chaos rune pack", "objtypes"),
            new GamevalEntry(12739, "ID_12739", "", "objtypes"),
            new GamevalEntry(12740, "BIRD_SNARE_PACK", "Bird snare pack", "objtypes"),
            new GamevalEntry(12741, "ID_12741", "", "objtypes"),
            new GamevalEntry(12742, "BOX_TRAP_PACK", "Box trap pack", "objtypes"),
            new GamevalEntry(12743, "ID_12743", "", "objtypes"),
            new GamevalEntry(12744, "MAGIC_IMP_BOX_PACK", "Magic imp box pack", "objtypes"),
            new GamevalEntry(12745, "ID_12745", "", "objtypes"),
            new GamevalEntry(12746, "ARCHAIC_EMBLEM_TIER_1", "Archaic emblem (tier 1)", "objtypes"),
            new GamevalEntry(12747, "ARCHAIC_EMBLEM_TIER_1_12747", "Archaic emblem (tier 1)", "objtypes"),
            new GamevalEntry(12748, "ARCHAIC_EMBLEM_TIER_2", "Archaic emblem (tier 2)", "objtypes"),
            new GamevalEntry(12749, "ARCHAIC_EMBLEM_TIER_3", "Archaic emblem (tier 3)", "objtypes"),
            new GamevalEntry(12750, "ARCHAIC_EMBLEM_TIER_4", "Archaic emblem (tier 4)", "objtypes"),
            new GamevalEntry(12751, "ARCHAIC_EMBLEM_TIER_5", "Archaic emblem (tier 5)", "objtypes"),
            new GamevalEntry(12752, "ARCHAIC_EMBLEM_TIER_6", "Archaic emblem (tier 6)", "objtypes"),
            new GamevalEntry(12753, "ARCHAIC_EMBLEM_TIER_7", "Archaic emblem (tier 7)", "objtypes"),
            new GamevalEntry(12754, "ARCHAIC_EMBLEM_TIER_8", "Archaic emblem (tier 8)", "objtypes"),
            new GamevalEntry(12755, "ARCHAIC_EMBLEM_TIER_9", "Archaic emblem (tier 9)", "objtypes"),
            new GamevalEntry(12756, "ARCHAIC_EMBLEM_TIER_10", "Archaic emblem (tier 10)", "objtypes"),
            new GamevalEntry(12757, "BLUE_DARK_BOW_PAINT", "Blue dark bow paint", "objtypes"),
            new GamevalEntry(12758, "ID_12758", "", "objtypes"),
            new GamevalEntry(12759, "GREEN_DARK_BOW_PAINT", "Green dark bow paint", "objtypes"),
            new GamevalEntry(12760, "ID_12760", "", "objtypes"),
            new GamevalEntry(12761, "YELLOW_DARK_BOW_PAINT", "Yellow dark bow paint", "objtypes"),
            new GamevalEntry(12762, "ID_12762", "", "objtypes"),
            new GamevalEntry(12763, "WHITE_DARK_BOW_PAINT", "White dark bow paint", "objtypes"),
            new GamevalEntry(12764, "ID_12764", "", "objtypes"),
            new GamevalEntry(12765, "DARK_BOW", "Dark bow", "objtypes"),
            new GamevalEntry(12766, "DARK_BOW_12766", "Dark bow", "objtypes"),
            new GamevalEntry(12767, "DARK_BOW_12767", "Dark bow", "objtypes"),
            new GamevalEntry(12768, "DARK_BOW_12768", "Dark bow", "objtypes"),
            new GamevalEntry(12769, "FROZEN_WHIP_MIX", "Frozen whip mix", "objtypes"),
            new GamevalEntry(12770, "ID_12770", "", "objtypes"),
            new GamevalEntry(12771, "VOLCANIC_WHIP_MIX", "Volcanic whip mix", "objtypes"),
            new GamevalEntry(12772, "ID_12772", "", "objtypes"),
            new GamevalEntry(12773, "VOLCANIC_ABYSSAL_WHIP", "Volcanic abyssal whip", "objtypes"),
            new GamevalEntry(12774, "FROZEN_ABYSSAL_WHIP", "Frozen abyssal whip", "objtypes"),
            new GamevalEntry(12775, "ANNAKARL_TELEPORT", "Annakarl teleport", "objtypes"),
            new GamevalEntry(12776, "CARRALLANGER_TELEPORT", "Carrallanger teleport", "objtypes"),
            new GamevalEntry(12777, "DAREEYAK_TELEPORT", "Dareeyak teleport", "objtypes"),
            new GamevalEntry(12778, "GHORROCK_TELEPORT", "Ghorrock teleport", "objtypes"),
            new GamevalEntry(12779, "KHARYRLL_TELEPORT", "Kharyrll teleport", "objtypes"),
            new GamevalEntry(12780, "LASSAR_TELEPORT", "Lassar teleport", "objtypes"),
            new GamevalEntry(12781, "PADDEWWA_TELEPORT", "Paddewwa teleport", "objtypes"),
            new GamevalEntry(12782, "SENNTISTEN_TELEPORT", "Senntisten teleport", "objtypes"),
            new GamevalEntry(12783, "RING_OF_WEALTH_SCROLL", "Ring of wealth scroll", "objtypes"),
            new GamevalEntry(12784, "ID_12784", "", "objtypes"),
            new GamevalEntry(12785, "RING_OF_WEALTH_I", "Ring of wealth (i)", "objtypes"),
            new GamevalEntry(12786, "MAGIC_SHORTBOW_SCROLL", "Magic shortbow scroll", "objtypes"),
            new GamevalEntry(12787, "ID_12787", "", "objtypes"),
            new GamevalEntry(12788, "MAGIC_SHORTBOW_I", "Magic shortbow (i)", "objtypes"),
            new GamevalEntry(12789, "CLUE_BOX", "Clue box", "objtypes"),
            new GamevalEntry(12790, "ID_12790", "", "objtypes"),
            new GamevalEntry(12791, "RUNE_POUCH", "Rune pouch", "objtypes"),
            new GamevalEntry(12792, "NEST_BOX_EMPTY", "Nest box (empty)", "objtypes"),
            new GamevalEntry(12793, "NEST_BOX_SEEDS", "Nest box (seeds)", "objtypes"),
            new GamevalEntry(12794, "NEST_BOX_RING", "Nest box (ring)", "objtypes"),
            new GamevalEntry(12795, "STEAM_BATTLESTAFF_12795", "Steam battlestaff", "objtypes"),
            new GamevalEntry(12796, "MYSTIC_STEAM_STAFF_12796", "Mystic steam staff", "objtypes"),
            new GamevalEntry(12797, "DRAGON_PICKAXE_12797", "Dragon pickaxe", "objtypes"),
            new GamevalEntry(12798, "STEAM_STAFF_UPGRADE_KIT", "Steam staff upgrade kit", "objtypes"),
            new GamevalEntry(12799, "ID_12799", "", "objtypes"),
        };
    }

    static Optional<GamevalEntry> byId(int id) {
        for (GamevalEntry entry : entries()) {
            if (entry.id() == id) return Optional.of(entry);
        }
        return Optional.empty();
    }

}
