package net.titan.gamevals.internal;

import java.util.Optional;

import net.titan.gamevals.GamevalEntry;
import net.titan.gamevals.QuestEntry;

final class ItemIDEntries_65 {
    private ItemIDEntries_65() {}

    static GamevalEntry[] entries() {
        return new GamevalEntry[] {
            new GamevalEntry(33368, "DEMONIC_PACTS_DEMON_BUTLER_SCROLL", "Demonic pacts demon butler scroll", "objtypes"),
            new GamevalEntry(33369, "ID_33369", "", "objtypes"),
            new GamevalEntry(33370, "ID_33370", "", "objtypes"),
            new GamevalEntry(33371, "MARK_OF_GRACE_33371", "Mark of grace", "objtypes"),
            new GamevalEntry(33372, "ID_33372", "", "objtypes"),
            new GamevalEntry(33373, "DEMONIC_CONTRACTOR_THRONE", "Demonic contractor throne", "objtypes"),
            new GamevalEntry(33374, "ZA_SINGLE_TARGET_ICE_ATTACK_33374", "ZA single target ice attack", "objtypes"),
            new GamevalEntry(33375, "ZUPGRADES_UP_TO_10_RESOURCE_ITEMS_INTO_A_HIGHER_TIER", "ZUpgrades up to 10 resource items into a higher tier", "objtypes"),
            new GamevalEntry(33376, "ZDOWNGRADES_UP_TO_10_RESOURCE_ITEMS_INTO_A_LOWER_TIER", "ZDowngrades up to 10 resource items into a lower tier", "objtypes"),
            new GamevalEntry(33377, "ZDEVISTATING_FIRE_FROM_AN_INFERNAL_BEAST", "ZDevistating fire from an infernal beast.", "objtypes"),
            new GamevalEntry(33378, "INCOMING_DAMAGE_MODIFIER", "Incoming damage modifier", "objtypes"),
            new GamevalEntry(33379, "ID_33379", "", "objtypes"),
            new GamevalEntry(33380, "INCOMING_DAMAGE_CLAMPING", "Incoming damage clamping", "objtypes"),
            new GamevalEntry(33381, "ID_33381", "", "objtypes"),
            new GamevalEntry(33382, "IMMACULATE_MOLE_SKIN", "Immaculate mole skin", "objtypes"),
            new GamevalEntry(33383, "ID_33383", "", "objtypes"),
            new GamevalEntry(33384, "GEM_POUCH", "Gem pouch", "objtypes"),
            new GamevalEntry(33385, "ID_33385", "", "objtypes"),
            new GamevalEntry(33386, "OPEN_GEM_POUCH", "Open gem pouch", "objtypes"),
            new GamevalEntry(33387, "GEM_SATCHEL", "Gem satchel", "objtypes"),
            new GamevalEntry(33388, "ID_33388", "", "objtypes"),
            new GamevalEntry(33389, "OPEN_GEM_SATCHEL", "Open gem satchel", "objtypes"),
            new GamevalEntry(33390, "GEM_TOTE", "Gem tote", "objtypes"),
            new GamevalEntry(33391, "ID_33391", "", "objtypes"),
            new GamevalEntry(33392, "OPEN_GEM_TOTE", "Open gem tote", "objtypes"),
            new GamevalEntry(33393, "GEM_SACK", "Gem sack", "objtypes"),
            new GamevalEntry(33394, "ID_33394", "", "objtypes"),
            new GamevalEntry(33395, "OPEN_GEM_SACK", "Open gem sack", "objtypes"),
            new GamevalEntry(33396, "NULL__33396", "Null", "objtypes"),
            new GamevalEntry(33397, "ID_33397", "", "objtypes"),
            new GamevalEntry(33398, "ID_33398", "", "objtypes"),
            new GamevalEntry(33399, "ID_33399", "", "objtypes"),
            new GamevalEntry(33400, "ID_33400", "", "objtypes"),
            new GamevalEntry(33401, "ID_33401", "", "objtypes"),
            new GamevalEntry(33402, "ID_33402", "", "objtypes"),
            new GamevalEntry(33403, "ID_33403", "", "objtypes"),
            new GamevalEntry(33404, "GRANITE_CANNONBALL_33404", "Granite cannonball", "objtypes"),
            new GamevalEntry(33405, "ID_33405", "", "objtypes"),
            new GamevalEntry(33406, "ID_33406", "", "objtypes"),
            new GamevalEntry(33407, "ID_33407", "", "objtypes"),
            new GamevalEntry(33408, "ID_33408", "", "objtypes"),
            new GamevalEntry(33409, "ID_33409", "", "objtypes"),
            new GamevalEntry(33410, "ID_33410", "", "objtypes"),
            new GamevalEntry(33411, "ID_33411", "", "objtypes"),
            new GamevalEntry(33412, "ID_33412", "", "objtypes"),
            new GamevalEntry(33413, "ID_33413", "", "objtypes"),
            new GamevalEntry(33414, "ID_33414", "", "objtypes"),
            new GamevalEntry(33415, "ID_33415", "", "objtypes"),
            new GamevalEntry(33416, "ID_33416", "", "objtypes"),
            new GamevalEntry(33417, "ID_33417", "", "objtypes"),
            new GamevalEntry(33418, "ID_33418", "", "objtypes"),
            new GamevalEntry(33419, "ID_33419", "", "objtypes"),
            new GamevalEntry(33420, "BOSUN_S_WORKBENCH", "Bosun's workbench", "objtypes"),
            new GamevalEntry(33421, "RECOLOURED_SAIL", "Recoloured sail", "objtypes"),
            new GamevalEntry(33422, "DYES", "Dyes", "objtypes"),
            new GamevalEntry(33423, "BOSUN_S_WORKBENCH_SCHEMATIC", "Bosun's workbench schematic", "objtypes"),
            new GamevalEntry(33424, "MISSION_TOTEM", "Mission totem", "objtypes"),
            new GamevalEntry(33425, "ID_33425", "", "objtypes"),
            new GamevalEntry(33426, "ID_33426", "", "objtypes"),
            new GamevalEntry(33427, "SPECTATOR_OCULUS", "Spectator oculus", "objtypes"),
            new GamevalEntry(33428, "TRINKET_OF_VENGEANCE_2", "Trinket of vengeance (2)", "objtypes"),
            new GamevalEntry(33429, "ID_33429", "", "objtypes"),
            new GamevalEntry(33430, "ID_33430", "", "objtypes"),
            new GamevalEntry(33431, "TRINKET_OF_VENGEANCE_1", "Trinket of vengeance (1)", "objtypes"),
            new GamevalEntry(33432, "ID_33432", "", "objtypes"),
            new GamevalEntry(33433, "ID_33433", "", "objtypes"),
            new GamevalEntry(33434, "UNCHARGED_TRIDENT_O", "Uncharged trident (o)", "objtypes"),
            new GamevalEntry(33435, "NULL__33435", "Null", "objtypes"),
            new GamevalEntry(33436, "ID_33436", "", "objtypes"),
            new GamevalEntry(33437, "SULPHUROUS_FERTILISER_33437", "Sulphurous fertiliser", "objtypes"),
            new GamevalEntry(33438, "ID_33438", "", "objtypes"),
            new GamevalEntry(33439, "OATHPLATE_SLAYER_HELMET_I", "Oathplate slayer helmet (i)", "objtypes"),
            new GamevalEntry(33440, "ID_33440", "", "objtypes"),
            new GamevalEntry(33441, "OATHPLATE_SLAYER_HELMET_I_33441", "Oathplate slayer helmet (i)", "objtypes"),
            new GamevalEntry(33442, "ID_33442", "", "objtypes"),
            new GamevalEntry(33443, "OATHPLATE_SLAYER_HELMET_I_33443", "Oathplate slayer helmet (i)", "objtypes"),
            new GamevalEntry(33444, "ID_33444", "", "objtypes"),
            new GamevalEntry(33445, "RADIANT_SLAYER_HELMET_I", "Radiant slayer helmet (i)", "objtypes"),
            new GamevalEntry(33446, "ID_33446", "", "objtypes"),
            new GamevalEntry(33447, "RADIANT_SLAYER_HELMET_I_33447", "Radiant slayer helmet (i)", "objtypes"),
            new GamevalEntry(33448, "ID_33448", "", "objtypes"),
            new GamevalEntry(33449, "RADIANT_SLAYER_HELMET_I_33449", "Radiant slayer helmet (i)", "objtypes"),
            new GamevalEntry(33450, "ID_33450", "", "objtypes"),
            new GamevalEntry(33451, "DEMONIC_PACTS_RELIC_HUNTER_T1_ARMOUR_SET", "Demonic pacts relic hunter (t1) armour set", "objtypes"),
            new GamevalEntry(33452, "ID_33452", "", "objtypes"),
            new GamevalEntry(33453, "ID_33453", "", "objtypes"),
            new GamevalEntry(33454, "DEMONIC_PACTS_RELIC_HUNTER_T2_ARMOUR_SET", "Demonic pacts relic hunter (t2) armour set", "objtypes"),
            new GamevalEntry(33455, "ID_33455", "", "objtypes"),
            new GamevalEntry(33456, "ID_33456", "", "objtypes"),
            new GamevalEntry(33457, "DEMONIC_PACTS_RELIC_HUNTER_T3_ARMOUR_SET", "Demonic pacts relic hunter (t3) armour set", "objtypes"),
            new GamevalEntry(33458, "ID_33458", "", "objtypes"),
            new GamevalEntry(33459, "ID_33459", "", "objtypes"),
            new GamevalEntry(33460, "DRAGON_CROSSBOW_33460", "Dragon crossbow", "objtypes"),
            new GamevalEntry(33461, "ID_33461", "", "objtypes"),
            new GamevalEntry(33462, "OATHPLATE_HELM_33462", "Oathplate helm", "objtypes"),
            new GamevalEntry(33463, "ID_33463", "", "objtypes"),
            new GamevalEntry(33464, "VOID_MELEE_HELM_L_BROKEN", "Void melee helm (l) (broken)", "objtypes"),
            new GamevalEntry(33465, "ID_33465", "", "objtypes"),
            new GamevalEntry(33466, "VOID_MELEE_HELM_L_MANGLED", "Void melee helm (l) (mangled)", "objtypes"),
            new GamevalEntry(33467, "ID_33467", "", "objtypes"),
            new GamevalEntry(33468, "VOID_MAGE_HELM_L_BROKEN", "Void mage helm (l) (broken)", "objtypes"),
            new GamevalEntry(33469, "ID_33469", "", "objtypes"),
            new GamevalEntry(33470, "VOID_MAGE_HELM_L_MANGLED", "Void mage helm (l) (mangled)", "objtypes"),
            new GamevalEntry(33471, "ID_33471", "", "objtypes"),
            new GamevalEntry(33472, "VOID_RANGER_HELM_L_BROKEN", "Void ranger helm (l) (broken)", "objtypes"),
            new GamevalEntry(33473, "ID_33473", "", "objtypes"),
            new GamevalEntry(33474, "VOID_RANGER_HELM_L_MANGLED", "Void ranger helm (l) (mangled)", "objtypes"),
            new GamevalEntry(33475, "ID_33475", "", "objtypes"),
            new GamevalEntry(33476, "VOID_KNIGHT_TOP_L_BROKEN", "Void knight top (l) (broken)", "objtypes"),
            new GamevalEntry(33477, "ID_33477", "", "objtypes"),
            new GamevalEntry(33478, "VOID_KNIGHT_TOP_L_MANGLED", "Void knight top (l) (mangled)", "objtypes"),
            new GamevalEntry(33479, "ID_33479", "", "objtypes"),
            new GamevalEntry(33480, "ELITE_VOID_TOP_L_BROKEN", "Elite void top (l) (broken)", "objtypes"),
            new GamevalEntry(33481, "ID_33481", "", "objtypes"),
            new GamevalEntry(33482, "ELITE_VOID_TOP_L_MANGLED", "Elite void top (l) (mangled)", "objtypes"),
            new GamevalEntry(33483, "ID_33483", "", "objtypes"),
            new GamevalEntry(33484, "VOID_KNIGHT_ROBE_L_BROKEN", "Void knight robe (l) (broken)", "objtypes"),
            new GamevalEntry(33485, "ID_33485", "", "objtypes"),
            new GamevalEntry(33486, "VOID_KNIGHT_ROBE_L_MANGLED", "Void knight robe (l) (mangled)", "objtypes"),
            new GamevalEntry(33487, "ID_33487", "", "objtypes"),
            new GamevalEntry(33488, "ELITE_VOID_ROBE_L_BROKEN", "Elite void robe (l) (broken)", "objtypes"),
            new GamevalEntry(33489, "ID_33489", "", "objtypes"),
            new GamevalEntry(33490, "ELITE_VOID_ROBE_L_MANGLED", "Elite void robe (l) (mangled)", "objtypes"),
            new GamevalEntry(33491, "ID_33491", "", "objtypes"),
            new GamevalEntry(33492, "VOID_KNIGHT_GLOVES_L_BROKEN", "Void knight gloves (l) (broken)", "objtypes"),
            new GamevalEntry(33493, "ID_33493", "", "objtypes"),
            new GamevalEntry(33494, "VOID_KNIGHT_GLOVES_L_MANGLED", "Void knight gloves (l) (mangled)", "objtypes"),
            new GamevalEntry(33495, "ID_33495", "", "objtypes"),
            new GamevalEntry(33496, "INFERNAL_MAX_CAPE_L_BROKEN", "Infernal max cape (l) (broken)", "objtypes"),
            new GamevalEntry(33497, "ID_33497", "", "objtypes"),
            new GamevalEntry(33498, "INFERNAL_MAX_CAPE_L_MANGLED", "Infernal max cape (l) (mangled)", "objtypes"),
            new GamevalEntry(33499, "ID_33499", "", "objtypes"),
            new GamevalEntry(33500, "INFERNAL_CAPE_L_BROKEN", "Infernal cape (l) (broken)", "objtypes"),
            new GamevalEntry(33501, "ID_33501", "", "objtypes"),
            new GamevalEntry(33502, "INFERNAL_CAPE_L_MANGLED", "Infernal cape (l) (mangled)", "objtypes"),
            new GamevalEntry(33503, "ID_33503", "", "objtypes"),
            new GamevalEntry(33504, "BLOOD_ANCIENT_SCEPTRE_L_BROKEN", "- Blood ancient sceptre (l) (broken)", "objtypes"),
            new GamevalEntry(33505, "ID_33505", "", "objtypes"),
            new GamevalEntry(33506, "BLOOD_ANCIENT_SCEPTRE_L_MANGLED", "- Blood ancient sceptre (l) (mangled)", "objtypes"),
            new GamevalEntry(33507, "ID_33507", "", "objtypes"),
            new GamevalEntry(33508, "ICE_ANCIENT_SCEPTRE_L_BROKEN", "Ice ancient sceptre (l) (broken)", "objtypes"),
            new GamevalEntry(33509, "ID_33509", "", "objtypes"),
            new GamevalEntry(33510, "ICE_ANCIENT_SCEPTRE_L_MANGLED", "Ice ancient sceptre (l) (mangled)", "objtypes"),
            new GamevalEntry(33511, "ID_33511", "", "objtypes"),
            new GamevalEntry(33512, "SMOKE_ANCIENT_SCEPTRE_L_BROKEN", "Smoke ancient sceptre (l) (broken)", "objtypes"),
            new GamevalEntry(33513, "ID_33513", "", "objtypes"),
            new GamevalEntry(33514, "SMOKE_ANCIENT_SCEPTRE_L_MANGLED", "Smoke ancient sceptre (l) (mangled)", "objtypes"),
            new GamevalEntry(33515, "ID_33515", "", "objtypes"),
            new GamevalEntry(33516, "SHADOW_ANCIENT_SCEPTRE_L_BROKEN", "Shadow ancient sceptre (l) (broken)", "objtypes"),
            new GamevalEntry(33517, "ID_33517", "", "objtypes"),
            new GamevalEntry(33518, "SHADOW_ANCIENT_SCEPTRE_L_MANGLED", "Shadow ancient sceptre (l) (mangled)", "objtypes"),
            new GamevalEntry(33519, "ID_33519", "", "objtypes"),
            new GamevalEntry(33520, "FIGHTER_TORSO_L_BROKEN", "Fighter torso (l) (broken)", "objtypes"),
            new GamevalEntry(33521, "ID_33521", "", "objtypes"),
            new GamevalEntry(33522, "FIGHTER_TORSO_L_MANGLED", "Fighter torso (l) (mangled)", "objtypes"),
            new GamevalEntry(33523, "ID_33523", "", "objtypes"),
            new GamevalEntry(33524, "DIZANA_S_QUIVER_L_BROKEN", "Dizana's quiver (l) (broken)", "objtypes"),
            new GamevalEntry(33525, "ID_33525", "", "objtypes"),
            new GamevalEntry(33526, "DIZANA_S_QUIVER_L_MANGLED", "Dizana's quiver (l) (mangled)", "objtypes"),
            new GamevalEntry(33527, "ID_33527", "", "objtypes"),
            new GamevalEntry(33528, "BLESSED_DIZANA_S_QUIVER_L_BROKEN", "Blessed dizana's quiver (l) (broken)", "objtypes"),
            new GamevalEntry(33529, "ID_33529", "", "objtypes"),
            new GamevalEntry(33530, "BLESSED_DIZANA_S_QUIVER_L_MANGLED", "Blessed dizana's quiver (l) (mangled)", "objtypes"),
            new GamevalEntry(33531, "ID_33531", "", "objtypes"),
            new GamevalEntry(33532, "DIZANA_S_MAX_CAPE_L_BROKEN", "Dizana's max cape (l) (broken)", "objtypes"),
            new GamevalEntry(33533, "DIZANA_S_MAX_CAPE_L_MANGLED", "Dizana's max cape (l) (mangled)", "objtypes"),
        };
    }

    static Optional<GamevalEntry> byId(int id) {
        for (GamevalEntry entry : entries()) {
            if (entry.id() == id) return Optional.of(entry);
        }
        return Optional.empty();
    }

}
