package net.titan.gamevals.internal;

import java.util.Optional;

import net.titan.gamevals.GamevalEntry;
import net.titan.gamevals.QuestEntry;

final class ItemIDEntries_64 {
    private ItemIDEntries_64() {}

    static GamevalEntry[] entries() {
        return new GamevalEntry[] {
            new GamevalEntry(33338, "LEAGUE_6_SLAYER_HELM1", "Oathplate slayer helmet", "objtypes"),
            new GamevalEntry(33339, "PLACEHOLDER_LEAGUE_6_SLAYER_HELM1", "placeholder_league_6_slayer_helm1", "objtypes"),
            new GamevalEntry(33340, "LEAGUE_6_SLAYER_HELM2", "Radiant slayer helmet", "objtypes"),
            new GamevalEntry(33341, "PLACEHOLDER_LEAGUE_6_SLAYER_HELM2", "placeholder_league_6_slayer_helm2", "objtypes"),
            new GamevalEntry(33342, "LEAGUE_6_DEMONIC_QUILL", "Demonic quill", "objtypes"),
            new GamevalEntry(33343, "CERT_LEAGUE_6_DEMONIC_QUILL", "cert_league_6_demonic_quill", "objtypes"),
            new GamevalEntry(33344, "PLACEHOLDER_LEAGUE_6_DEMONIC_QUILL", "placeholder_league_6_demonic_quill", "objtypes"),
            new GamevalEntry(33345, "LEAGUE_6_DRAGON_TROPHY", "Demonic pacts dragon trophy", "objtypes"),
            new GamevalEntry(33346, "PLACEHOLDER_LEAGUE_6_DRAGON_TROPHY", "placeholder_league_6_dragon_trophy", "objtypes"),
            new GamevalEntry(33347, "LEAGUE_6_RUNE_TROPHY", "Demonic pacts rune trophy", "objtypes"),
            new GamevalEntry(33348, "PLACEHOLDER_LEAGUE_6_RUNE_TROPHY", "placeholder_league_6_rune_trophy", "objtypes"),
            new GamevalEntry(33349, "LEAGUE_6_ADAMANT_TROPHY", "Demonic pacts adamant trophy", "objtypes"),
            new GamevalEntry(33350, "PLACEHOLDER_LEAGUE_6_ADAMANT_TROPHY", "placeholder_league_6_adamant_trophy", "objtypes"),
            new GamevalEntry(33351, "LEAGUE_6_MITHRIL_TROPHY", "Demonic pacts mithril trophy", "objtypes"),
            new GamevalEntry(33352, "PLACEHOLDER_LEAGUE_6_MITHRIL_TROPHY", "placeholder_league_6_mithril_trophy", "objtypes"),
            new GamevalEntry(33353, "LEAGUE_6_STEEL_TROPHY", "Demonic pacts steel trophy", "objtypes"),
            new GamevalEntry(33354, "PLACEHOLDER_LEAGUE_6_STEEL_TROPHY", "placeholder_league_6_steel_trophy", "objtypes"),
            new GamevalEntry(33355, "LEAGUE_6_IRON_TROPHY", "Demonic pacts iron trophy", "objtypes"),
            new GamevalEntry(33356, "PLACEHOLDER_LEAGUE_6_IRON_TROPHY", "placeholder_league_6_iron_trophy", "objtypes"),
            new GamevalEntry(33357, "LEAGUE_6_BRONZE_TROPHY", "Demonic pacts bronze trophy", "objtypes"),
            new GamevalEntry(33358, "PLACEHOLDER_LEAGUE_6_BRONZE_TROPHY", "placeholder_league_6_bronze_trophy", "objtypes"),
            new GamevalEntry(33359, "LEAGUE_6_RITUAL_KIT", "Impish ritual scroll", "objtypes"),
            new GamevalEntry(33360, "CERT_LEAGUE_6_RITUAL_KIT", "cert_league_6_ritual_kit", "objtypes"),
            new GamevalEntry(33361, "PLACEHOLDER_LEAGUE_6_RITUAL_KIT", "placeholder_league_6_ritual_kit", "objtypes"),
            new GamevalEntry(33362, "LEAGUE_6_THRONE", "Demonic pacts throne scroll", "objtypes"),
            new GamevalEntry(33363, "CERT_LEAGUE_6_THRONE", "cert_league_6_throne", "objtypes"),
            new GamevalEntry(33364, "PLACEHOLDER_LEAGUE_6_THRONE", "placeholder_league_6_throne", "objtypes"),
            new GamevalEntry(33365, "LEAGUE_6_THRALL_CONTRACT", "Impish whistle", "objtypes"),
            new GamevalEntry(33366, "CERT_LEAGUE_6_THRALL_CONTRACT", "cert_league_6_thrall_contract", "objtypes"),
            new GamevalEntry(33367, "PLACEHOLDER_LEAGUE_6_THRALL_CONTRACT", "placeholder_league_6_thrall_contract", "objtypes"),
            new GamevalEntry(33368, "LEAGUE_6_BUTLER_SCROLL", "Demonic pacts demon butler scroll", "objtypes"),
            new GamevalEntry(33369, "CERT_LEAGUE_6_BUTLER_SCROLL", "cert_league_6_butler_scroll", "objtypes"),
            new GamevalEntry(33370, "PLACEHOLDER_LEAGUE_6_BUTLER_SCROLL", "placeholder_league_6_butler_scroll", "objtypes"),
            new GamevalEntry(33371, "GRACE_HOTFOOT", "Mark of grace", "objtypes"),
            new GamevalEntry(33372, "PLACEHOLDER_GRACE_HOTFOOT", "placeholder_grace_hotfoot", "objtypes"),
            new GamevalEntry(33373, "POH_THRONE_8", "Demonic contractor throne", "objtypes"),
            new GamevalEntry(33374, "KINGS_BARRAGE_ICE_ATTACK", "ZA single target ice attack", "objtypes"),
            new GamevalEntry(33375, "TRANSMUTE_UPGRADE", "ZUpgrades up to 10 resource items into a higher tier", "objtypes"),
            new GamevalEntry(33376, "TRANSMUTE_DOWNGRADE", "ZDowngrades up to 10 resource items into a lower tier", "objtypes"),
            new GamevalEntry(33377, "FANG_OF_THE_HOUND_FIRE", "ZDevistating fire from an infernal beast.", "objtypes"),
            new GamevalEntry(33378, "NOSAVE_WORLD_INCOMING_PRAYER_DAMAGE_MODIFIER", "Incoming damage modifier", "objtypes"),
            new GamevalEntry(33379, "PLACEHOLDER_NOSAVE_WORLD_INCOMING_PRAYER_DAMAGE_MODIFIER", "placeholder_nosave_world_incoming_prayer_damage_modifier", "objtypes"),
            new GamevalEntry(33380, "NOSAVE_WORLD_DAMAGE_CLAMPING", "Incoming damage clamping", "objtypes"),
            new GamevalEntry(33381, "PLACEHOLDER_NOSAVE_WORLD_DAMAGE_CLAMPING", "placeholder_nosave_world_damage_clamping", "objtypes"),
            new GamevalEntry(33382, "IMMACULATE_MOLE_SKIN", "Immaculate mole skin", "objtypes"),
            new GamevalEntry(33383, "PLACEHOLDER_IMMACULATE_MOLE_SKIN", "placeholder_immaculate_mole_skin", "objtypes"),
            new GamevalEntry(33384, "GEM_POUCH", "Gem pouch", "objtypes"),
            new GamevalEntry(33385, "PLACEHOLDER_GEM_POUCH", "placeholder_gem_pouch", "objtypes"),
            new GamevalEntry(33386, "GEM_POUCH_OPEN", "Open gem pouch", "objtypes"),
            new GamevalEntry(33387, "GEM_SATCHEL", "Gem satchel", "objtypes"),
            new GamevalEntry(33388, "PLACEHOLDER_GEM_SATCHEL", "placeholder_gem_satchel", "objtypes"),
            new GamevalEntry(33389, "GEM_SATCHEL_OPEN", "Open gem satchel", "objtypes"),
            new GamevalEntry(33390, "GEM_TOTE", "Gem tote", "objtypes"),
            new GamevalEntry(33391, "PLACEHOLDER_GEM_TOTE", "placeholder_gem_tote", "objtypes"),
            new GamevalEntry(33392, "GEM_TOTE_OPEN", "Open gem tote", "objtypes"),
            new GamevalEntry(33393, "GEM_SACK", "Gem sack", "objtypes"),
            new GamevalEntry(33394, "PLACEHOLDER_GEM_SACK", "placeholder_gem_sack", "objtypes"),
            new GamevalEntry(33395, "GEM_SACK_OPEN", "Open gem sack", "objtypes"),
            new GamevalEntry(33396, "INCENDIARY_DATA", "Null", "objtypes"),
            new GamevalEntry(33397, "BRONZE_CANNONBALL_SIDEPANEL", "bronze_cannonball_sidepanel", "objtypes"),
            new GamevalEntry(33398, "IRON_CANNONBALL_SIDEPANEL", "iron_cannonball_sidepanel", "objtypes"),
            new GamevalEntry(33399, "MCANNONBALL_SIDEPANEL", "mcannonball_sidepanel", "objtypes"),
            new GamevalEntry(33400, "MITHRIL_CANNONBALL_SIDEPANEL", "mithril_cannonball_sidepanel", "objtypes"),
            new GamevalEntry(33401, "ADAMANT_CANNONBALL_SIDEPANEL", "adamant_cannonball_sidepanel", "objtypes"),
            new GamevalEntry(33402, "RUNE_CANNONBALL_SIDEPANEL", "rune_cannonball_sidepanel", "objtypes"),
            new GamevalEntry(33403, "DRAGON_CANNONBALL_SIDEPANEL", "dragon_cannonball_sidepanel", "objtypes"),
            new GamevalEntry(33404, "GRANITE_CANNONBALL_SIDEPANEL", "Granite cannonball", "objtypes"),
            new GamevalEntry(33405, "PLACEHOLDER_GRANITE_CANNONBALL_SIDEPANEL", "placeholder_granite_cannonball_sidepanel", "objtypes"),
            new GamevalEntry(33406, "BRONZE_CHAINSHOT_CANNONBALL_SIDEPANEL", "bronze_chainshot_cannonball_sidepanel", "objtypes"),
            new GamevalEntry(33407, "IRON_CHAINSHOT_CANNONBALL_SIDEPANEL", "iron_chainshot_cannonball_sidepanel", "objtypes"),
            new GamevalEntry(33408, "STEEL_CHAINSHOT_CANNONBALL_SIDEPANEL", "steel_chainshot_cannonball_sidepanel", "objtypes"),
            new GamevalEntry(33409, "MITHRIL_CHAINSHOT_CANNONBALL_SIDEPANEL", "mithril_chainshot_cannonball_sidepanel", "objtypes"),
            new GamevalEntry(33410, "ADAMANT_CHAINSHOT_CANNONBALL_SIDEPANEL", "adamant_chainshot_cannonball_sidepanel", "objtypes"),
            new GamevalEntry(33411, "RUNE_CHAINSHOT_CANNONBALL_SIDEPANEL", "rune_chainshot_cannonball_sidepanel", "objtypes"),
            new GamevalEntry(33412, "DRAGON_CHAINSHOT_CANNONBALL_SIDEPANEL", "dragon_chainshot_cannonball_sidepanel", "objtypes"),
            new GamevalEntry(33413, "BRONZE_INCENDIARY_CANNONBALL_SIDEPANEL", "bronze_incendiary_cannonball_sidepanel", "objtypes"),
            new GamevalEntry(33414, "IRON_INCENDIARY_CANNONBALL_SIDEPANEL", "iron_incendiary_cannonball_sidepanel", "objtypes"),
            new GamevalEntry(33415, "STEEL_INCENDIARY_CANNONBALL_SIDEPANEL", "steel_incendiary_cannonball_sidepanel", "objtypes"),
            new GamevalEntry(33416, "MITHRIL_INCENDIARY_CANNONBALL_SIDEPANEL", "mithril_incendiary_cannonball_sidepanel", "objtypes"),
            new GamevalEntry(33417, "ADAMANT_INCENDIARY_CANNONBALL_SIDEPANEL", "adamant_incendiary_cannonball_sidepanel", "objtypes"),
            new GamevalEntry(33418, "RUNE_INCENDIARY_CANNONBALL_SIDEPANEL", "rune_incendiary_cannonball_sidepanel", "objtypes"),
            new GamevalEntry(33419, "DRAGON_INCENDIARY_CANNONBALL_SIDEPANEL", "dragon_incendiary_cannonball_sidepanel", "objtypes"),
            new GamevalEntry(33420, "SAILING_SKILLGUIDE_BOSUNS_WORKBENCH", "Bosun's workbench", "objtypes"),
            new GamevalEntry(33421, "SAILING_SKILLGUIDE_RECOLOURED_SAIL", "Recoloured sail", "objtypes"),
            new GamevalEntry(33422, "SAILING_SKILLGUIDE_MYSTERY_DYES", "Dyes", "objtypes"),
            new GamevalEntry(33423, "LOST_SCHEMATIC_BOSUNS_WORKBENCH", "Bosun's workbench schematic", "objtypes"),
            new GamevalEntry(33424, "DEADMAN_ALL_STAR_MISSION_TOTEM", "Mission totem", "objtypes"),
            new GamevalEntry(33425, "CERT_DEADMAN_ALL_STAR_MISSION_TOTEM", "cert_deadman_all_star_mission_totem", "objtypes"),
            new GamevalEntry(33426, "PLACEHOLDER_DEADMAN_ALL_STAR_MISSION_TOTEM", "placeholder_deadman_all_star_mission_totem", "objtypes"),
            new GamevalEntry(33427, "SPECTATOR_OCULUS", "Spectator oculus", "objtypes"),
            new GamevalEntry(33428, "MAGIC_ROCK_OF_VENGEANCE_2_USE", "Trinket of vengeance (2)", "objtypes"),
            new GamevalEntry(33429, "CERT_MAGIC_ROCK_OF_VENGEANCE_2_USE", "cert_magic_rock_of_vengeance_2_use", "objtypes"),
            new GamevalEntry(33430, "PLACEHOLDER_MAGIC_ROCK_OF_VENGEANCE_2_USE", "placeholder_magic_rock_of_vengeance_2_use", "objtypes"),
            new GamevalEntry(33431, "MAGIC_ROCK_OF_VENGEANCE_1_USE", "Trinket of vengeance (1)", "objtypes"),
            new GamevalEntry(33432, "CERT_MAGIC_ROCK_OF_VENGEANCE_1_USE", "cert_magic_rock_of_vengeance_1_use", "objtypes"),
            new GamevalEntry(33433, "PLACEHOLDER_MAGIC_ROCK_OF_VENGEANCE_1_USE", "placeholder_magic_rock_of_vengeance_1_use", "objtypes"),
            new GamevalEntry(33434, "TOTS_UNCHARGED_ORN", "Uncharged trident (o)", "objtypes"),
            new GamevalEntry(33435, "PLACEHOLDER_TOTS_UNCHARGED_ORN", "Null", "objtypes"),
            new GamevalEntry(33436, "POH_DUMMY_THRONE_8", "poh_dummy_throne_8", "objtypes"),
            new GamevalEntry(33437, "BUCKET_SULPHUROUS_FERTILISER", "Sulphurous fertiliser", "objtypes"),
            new GamevalEntry(33438, "PLACEHOLDER_BUCKET_SULPHUROUS_FERTILISER", "placeholder_bucket_sulphurous_fertiliser", "objtypes"),
            new GamevalEntry(33439, "LEAGUE_6_SLAYER_HELM1_I", "Oathplate slayer helmet (i)", "objtypes"),
            new GamevalEntry(33440, "PLACEHOLDER_LEAGUE_6_SLAYER_HELM1_I", "placeholder_league_6_slayer_helm1_i", "objtypes"),
            new GamevalEntry(33441, "SW_LEAGUE_6_SLAYER_HELM1_I", "Oathplate slayer helmet (i)", "objtypes"),
            new GamevalEntry(33442, "PLACEHOLDER_SW_LEAGUE_6_SLAYER_HELM1_I", "placeholder_sw_league_6_slayer_helm1_i", "objtypes"),
            new GamevalEntry(33443, "PVPA_LEAGUE_6_SLAYER_HELM1_I", "Oathplate slayer helmet (i)", "objtypes"),
            new GamevalEntry(33444, "PLACEHOLDER_PVPA_LEAGUE_6_SLAYER_HELM1_I", "placeholder_pvpa_league_6_slayer_helm1_i", "objtypes"),
            new GamevalEntry(33445, "LEAGUE_6_SLAYER_HELM2_I", "Radiant slayer helmet (i)", "objtypes"),
            new GamevalEntry(33446, "PLACEHOLDER_LEAGUE_6_SLAYER_HELM2_I", "placeholder_league_6_slayer_helm2_i", "objtypes"),
            new GamevalEntry(33447, "SW_LEAGUE_6_SLAYER_HELM2_I", "Radiant slayer helmet (i)", "objtypes"),
            new GamevalEntry(33448, "PLACEHOLDER_SW_LEAGUE_6_SLAYER_HELM2_I", "placeholder_sw_league_6_slayer_helm2_i", "objtypes"),
            new GamevalEntry(33449, "PVPA_LEAGUE_6_SLAYER_HELM2_I", "Radiant slayer helmet (i)", "objtypes"),
            new GamevalEntry(33450, "PLACEHOLDER_PVPA_LEAGUE_6_SLAYER_HELM2_I", "placeholder_pvpa_league_6_slayer_helm2_i", "objtypes"),
            new GamevalEntry(33451, "SET_LEAGUE_6_RELICHUNTER_T1", "Demonic pacts relic hunter (t1) armour set", "objtypes"),
            new GamevalEntry(33452, "CERT_SET_LEAGUE_6_RELICHUNTER_T1", "cert_set_league_6_relichunter_t1", "objtypes"),
            new GamevalEntry(33453, "PLACEHOLDER_SET_LEAGUE_6_RELICHUNTER_T1", "placeholder_set_league_6_relichunter_t1", "objtypes"),
            new GamevalEntry(33454, "SET_LEAGUE_6_RELICHUNTER_T2", "Demonic pacts relic hunter (t2) armour set", "objtypes"),
            new GamevalEntry(33455, "CERT_SET_LEAGUE_6_RELICHUNTER_T2", "cert_set_league_6_relichunter_t2", "objtypes"),
            new GamevalEntry(33456, "PLACEHOLDER_SET_LEAGUE_6_RELICHUNTER_T2", "placeholder_set_league_6_relichunter_t2", "objtypes"),
            new GamevalEntry(33457, "SET_LEAGUE_6_RELICHUNTER_T3", "Demonic pacts relic hunter (t3) armour set", "objtypes"),
            new GamevalEntry(33458, "CERT_SET_LEAGUE_6_RELICHUNTER_T3", "cert_set_league_6_relichunter_t3", "objtypes"),
            new GamevalEntry(33459, "PLACEHOLDER_SET_LEAGUE_6_RELICHUNTER_T3", "placeholder_set_league_6_relichunter_t3", "objtypes"),
            new GamevalEntry(33460, "BR_XBOWS_CROSSBOW_DRAGON", "Dragon crossbow", "objtypes"),
            new GamevalEntry(33461, "CERT_BR_XBOWS_CROSSBOW_DRAGON", "cert_br_xbows_crossbow_dragon", "objtypes"),
            new GamevalEntry(33462, "BR_OATHPLATE_HELM", "Oathplate helm", "objtypes"),
            new GamevalEntry(33463, "CERT_BR_OATHPLATE_HELM", "cert_br_oathplate_helm", "objtypes"),
            new GamevalEntry(33464, "GAME_PEST_MELEE_HELM_TROUVER_BROKEN", "Void melee helm (l) (broken)", "objtypes"),
            new GamevalEntry(33465, "PLACEHOLDER_GAME_PEST_MELEE_HELM_TROUVER_BROKEN", "placeholder_game_pest_melee_helm_trouver_broken", "objtypes"),
            new GamevalEntry(33466, "GAME_PEST_MELEE_HELM_TROUVER_MANGLED", "Void melee helm (l) (mangled)", "objtypes"),
            new GamevalEntry(33467, "PLACEHOLDER_GAME_PEST_MELEE_HELM_TROUVER_MANGLED", "placeholder_game_pest_melee_helm_trouver_mangled", "objtypes"),
            new GamevalEntry(33468, "GAME_PEST_MAGE_HELM_TROUVER_BROKEN", "Void mage helm (l) (broken)", "objtypes"),
            new GamevalEntry(33469, "PLACEHOLDER_GAME_PEST_MAGE_HELM_TROUVER_BROKEN", "placeholder_game_pest_mage_helm_trouver_broken", "objtypes"),
            new GamevalEntry(33470, "GAME_PEST_MAGE_HELM_TROUVER_MANGLED", "Void mage helm (l) (mangled)", "objtypes"),
            new GamevalEntry(33471, "PLACEHOLDER_GAME_PEST_MAGE_HELM_TROUVER_MANGLED", "placeholder_game_pest_mage_helm_trouver_mangled", "objtypes"),
            new GamevalEntry(33472, "GAME_PEST_ARCHER_HELM_TROUVER_BROKEN", "Void ranger helm (l) (broken)", "objtypes"),
            new GamevalEntry(33473, "PLACEHOLDER_GAME_PEST_ARCHER_HELM_TROUVER_BROKEN", "placeholder_game_pest_archer_helm_trouver_broken", "objtypes"),
            new GamevalEntry(33474, "GAME_PEST_ARCHER_HELM_TROUVER_MANGLED", "Void ranger helm (l) (mangled)", "objtypes"),
            new GamevalEntry(33475, "PLACEHOLDER_GAME_PEST_ARCHER_HELM_TROUVER_MANGLED", "placeholder_game_pest_archer_helm_trouver_mangled", "objtypes"),
            new GamevalEntry(33476, "PEST_VOID_KNIGHT_TOP_TROUVER_BROKEN", "Void knight top (l) (broken)", "objtypes"),
            new GamevalEntry(33477, "PLACEHOLDER_PEST_VOID_KNIGHT_TOP_TROUVER_BROKEN", "placeholder_pest_void_knight_top_trouver_broken", "objtypes"),
            new GamevalEntry(33478, "PEST_VOID_KNIGHT_TOP_TROUVER_MANGLED", "Void knight top (l) (mangled)", "objtypes"),
            new GamevalEntry(33479, "PLACEHOLDER_PEST_VOID_KNIGHT_TOP_TROUVER_MANGLED", "placeholder_pest_void_knight_top_trouver_mangled", "objtypes"),
            new GamevalEntry(33480, "ELITE_VOID_KNIGHT_TOP_TROUVER_BROKEN", "Elite void top (l) (broken)", "objtypes"),
            new GamevalEntry(33481, "PLACEHOLDER_ELITE_VOID_KNIGHT_TOP_TROUVER_BROKEN", "placeholder_elite_void_knight_top_trouver_broken", "objtypes"),
            new GamevalEntry(33482, "ELITE_VOID_KNIGHT_TOP_TROUVER_MANGLED", "Elite void top (l) (mangled)", "objtypes"),
            new GamevalEntry(33483, "PLACEHOLDER_ELITE_VOID_KNIGHT_TOP_TROUVER_MANGLED", "placeholder_elite_void_knight_top_trouver_mangled", "objtypes"),
            new GamevalEntry(33484, "PEST_VOID_KNIGHT_ROBES_TROUVER_BROKEN", "Void knight robe (l) (broken)", "objtypes"),
            new GamevalEntry(33485, "PLACEHOLDER_PEST_VOID_KNIGHT_ROBES_TROUVER_BROKEN", "placeholder_pest_void_knight_robes_trouver_broken", "objtypes"),
            new GamevalEntry(33486, "PEST_VOID_KNIGHT_ROBES_TROUVER_MANGLED", "Void knight robe (l) (mangled)", "objtypes"),
            new GamevalEntry(33487, "PLACEHOLDER_PEST_VOID_KNIGHT_ROBES_TROUVER_MANGLED", "placeholder_pest_void_knight_robes_trouver_mangled", "objtypes"),
            new GamevalEntry(33488, "ELITE_VOID_KNIGHT_ROBES_TROUVER_BROKEN", "Elite void robe (l) (broken)", "objtypes"),
            new GamevalEntry(33489, "PLACEHOLDER_ELITE_VOID_KNIGHT_ROBES_TROUVER_BROKEN", "placeholder_elite_void_knight_robes_trouver_broken", "objtypes"),
            new GamevalEntry(33490, "ELITE_VOID_KNIGHT_ROBES_TROUVER_MANGLED", "Elite void robe (l) (mangled)", "objtypes"),
            new GamevalEntry(33491, "PLACEHOLDER_ELITE_VOID_KNIGHT_ROBES_TROUVER_MANGLED", "placeholder_elite_void_knight_robes_trouver_mangled", "objtypes"),
            new GamevalEntry(33492, "PEST_VOID_KNIGHT_GLOVES_TROUVER_BROKEN", "Void knight gloves (l) (broken)", "objtypes"),
            new GamevalEntry(33493, "PLACEHOLDER_PEST_VOID_KNIGHT_GLOVES_TROUVER_BROKEN", "placeholder_pest_void_knight_gloves_trouver_broken", "objtypes"),
            new GamevalEntry(33494, "PEST_VOID_KNIGHT_GLOVES_TROUVER_MANGLED", "Void knight gloves (l) (mangled)", "objtypes"),
            new GamevalEntry(33495, "PLACEHOLDER_PEST_VOID_KNIGHT_GLOVES_TROUVER_MANGLED", "placeholder_pest_void_knight_gloves_trouver_mangled", "objtypes"),
            new GamevalEntry(33496, "SKILLCAPE_MAX_INFERNALCAPE_TROUVER_BROKEN", "Infernal max cape (l) (broken)", "objtypes"),
            new GamevalEntry(33497, "PLACEHOLDER_SKILLCAPE_MAX_INFERNALCAPE_TROUVER_BROKEN", "placeholder_skillcape_max_infernalcape_trouver_broken", "objtypes"),
            new GamevalEntry(33498, "SKILLCAPE_MAX_INFERNALCAPE_TROUVER_MANGLED", "Infernal max cape (l) (mangled)", "objtypes"),
            new GamevalEntry(33499, "PLACEHOLDER_SKILLCAPE_MAX_INFERNALCAPE_TROUVER_MANGLED", "placeholder_skillcape_max_infernalcape_trouver_mangled", "objtypes"),
            new GamevalEntry(33500, "INFERNAL_CAPE_TROUVER_BROKEN", "Infernal cape (l) (broken)", "objtypes"),
            new GamevalEntry(33501, "PLACEHOLDER_INFERNAL_CAPE_TROUVER_BROKEN", "placeholder_infernal_cape_trouver_broken", "objtypes"),
            new GamevalEntry(33502, "INFERNAL_CAPE_TROUVER_MANGLED", "Infernal cape (l) (mangled)", "objtypes"),
            new GamevalEntry(33503, "PLACEHOLDER_INFERNAL_CAPE_TROUVER_MANGLED", "placeholder_infernal_cape_trouver_mangled", "objtypes"),
            new GamevalEntry(33504, "ANCIENT_SCEPTRE_BLOOD_TROUVER_BROKEN", "- Blood ancient sceptre (l) (broken)", "objtypes"),
            new GamevalEntry(33505, "PLACEHOLDER_ANCIENT_SCEPTRE_BLOOD_TROUVER_BROKEN", "placeholder_ancient_sceptre_blood_trouver_broken", "objtypes"),
            new GamevalEntry(33506, "ANCIENT_SCEPTRE_BLOOD_TROUVER_MANGLED", "- Blood ancient sceptre (l) (mangled)", "objtypes"),
            new GamevalEntry(33507, "PLACEHOLDER_ANCIENT_SCEPTRE_BLOOD_TROUVER_MANGLED", "placeholder_ancient_sceptre_blood_trouver_mangled", "objtypes"),
            new GamevalEntry(33508, "ANCIENT_SCEPTRE_ICE_TROUVER_BROKEN", "Ice ancient sceptre (l) (broken)", "objtypes"),
            new GamevalEntry(33509, "PLACEHOLDER_ANCIENT_SCEPTRE_ICE_TROUVER_BROKEN", "placeholder_ancient_sceptre_ice_trouver_broken", "objtypes"),
            new GamevalEntry(33510, "ANCIENT_SCEPTRE_ICE_TROUVER_MANGLED", "Ice ancient sceptre (l) (mangled)", "objtypes"),
            new GamevalEntry(33511, "PLACEHOLDER_ANCIENT_SCEPTRE_ICE_TROUVER_MANGLED", "placeholder_ancient_sceptre_ice_trouver_mangled", "objtypes"),
            new GamevalEntry(33512, "ANCIENT_SCEPTRE_SMOKE_TROUVER_BROKEN", "Smoke ancient sceptre (l) (broken)", "objtypes"),
            new GamevalEntry(33513, "PLACEHOLDER_ANCIENT_SCEPTRE_SMOKE_TROUVER_BROKEN", "placeholder_ancient_sceptre_smoke_trouver_broken", "objtypes"),
            new GamevalEntry(33514, "ANCIENT_SCEPTRE_SMOKE_TROUVER_MANGLED", "Smoke ancient sceptre (l) (mangled)", "objtypes"),
            new GamevalEntry(33515, "PLACEHOLDER_ANCIENT_SCEPTRE_SMOKE_TROUVER_MANGLED", "placeholder_ancient_sceptre_smoke_trouver_mangled", "objtypes"),
            new GamevalEntry(33516, "ANCIENT_SCEPTRE_SHADOW_TROUVER_BROKEN", "Shadow ancient sceptre (l) (broken)", "objtypes"),
            new GamevalEntry(33517, "PLACEHOLDER_ANCIENT_SCEPTRE_SHADOW_TROUVER_BROKEN", "placeholder_ancient_sceptre_shadow_trouver_broken", "objtypes"),
            new GamevalEntry(33518, "ANCIENT_SCEPTRE_SHADOW_TROUVER_MANGLED", "Shadow ancient sceptre (l) (mangled)", "objtypes"),
            new GamevalEntry(33519, "PLACEHOLDER_ANCIENT_SCEPTRE_SHADOW_TROUVER_MANGLED", "placeholder_ancient_sceptre_shadow_trouver_mangled", "objtypes"),
            new GamevalEntry(33520, "BARBASSAULT_PENANCE_FIGHTER_TORSO_TROUVER_BROKEN", "Fighter torso (l) (broken)", "objtypes"),
            new GamevalEntry(33521, "PLACEHOLDER_BARBASSAULT_PENANCE_FIGHTER_TORSO_TROUVER_BROKEN", "placeholder_barbassault_penance_fighter_torso_trouver_broken", "objtypes"),
            new GamevalEntry(33522, "BARBASSAULT_PENANCE_FIGHTER_TORSO_TROUVER_MANGLED", "Fighter torso (l) (mangled)", "objtypes"),
            new GamevalEntry(33523, "PLACEHOLDER_BARBASSAULT_PENANCE_FIGHTER_TORSO_TROUVER_MANGLED", "placeholder_barbassault_penance_fighter_torso_trouver_mangled", "objtypes"),
            new GamevalEntry(33524, "DIZANAS_QUIVER_TROUVER_BROKEN", "Dizana's quiver (l) (broken)", "objtypes"),
            new GamevalEntry(33525, "PLACEHOLDER_DIZANAS_QUIVER_TROUVER_BROKEN", "placeholder_dizanas_quiver_trouver_broken", "objtypes"),
            new GamevalEntry(33526, "DIZANAS_QUIVER_TROUVER_MANGLED", "Dizana's quiver (l) (mangled)", "objtypes"),
            new GamevalEntry(33527, "PLACEHOLDER_DIZANAS_QUIVER_TROUVER_MANGLED", "placeholder_dizanas_quiver_trouver_mangled", "objtypes"),
            new GamevalEntry(33528, "DIZANAS_QUIVER_INFINITE_TROUVER_BROKEN", "Blessed dizana's quiver (l) (broken)", "objtypes"),
            new GamevalEntry(33529, "PLACEHOLDER_DIZANAS_QUIVER_INFINITE_TROUVER_BROKEN", "placeholder_dizanas_quiver_infinite_trouver_broken", "objtypes"),
            new GamevalEntry(33530, "DIZANAS_QUIVER_INFINITE_TROUVER_MANGLED", "Blessed dizana's quiver (l) (mangled)", "objtypes"),
            new GamevalEntry(33531, "PLACEHOLDER_DIZANAS_QUIVER_INFINITE_TROUVER_MANGLED", "placeholder_dizanas_quiver_infinite_trouver_mangled", "objtypes"),
            new GamevalEntry(33532, "SKILLCAPE_MAX_DIZANAS_TROUVER_BROKEN", "Dizana's max cape (l) (broken)", "objtypes"),
            new GamevalEntry(33533, "SKILLCAPE_MAX_DIZANAS_TROUVER_MANGLED", "Dizana's max cape (l) (mangled)", "objtypes"),
            new GamevalEntry(33534, "ETCHED_ARAXYTE_FANG", "Etched araxyte fang", "objtypes"),
            new GamevalEntry(33535, "CERT_ETCHED_ARAXYTE_FANG", "cert_etched_araxyte_fang", "objtypes"),
            new GamevalEntry(33536, "PLACEHOLDER_ETCHED_ARAXYTE_FANG", "placeholder_etched_araxyte_fang", "objtypes"),
            new GamevalEntry(33537, "GARLIC_COCKTAIL", "Garlic cocktail", "objtypes"),
            new GamevalEntry(33538, "PLACEHOLDER_GARLIC_COCKTAIL", "placeholder_garlic_cocktail", "objtypes"),
            new GamevalEntry(33539, "BUCKET_OF_BLOODWOOD_SAP", "Bucket of bloodwood sap", "objtypes"),
            new GamevalEntry(33540, "PLACEHOLDER_BUCKET_OF_BLOODWOOD_SAP", "placeholder_bucket_of_bloodwood_sap", "objtypes"),
            new GamevalEntry(33541, "SEEKING_ARROW_SHAFT", "Seeking arrow shaft", "objtypes"),
            new GamevalEntry(33542, "PLACEHOLDER_SEEKING_ARROW_SHAFT", "placeholder_seeking_arrow_shaft", "objtypes"),
            new GamevalEntry(33543, "SEEKING_ARROW_SHAFT_2", "seeking_arrow_shaft_2", "objtypes"),
            new GamevalEntry(33544, "SEEKING_ARROW_SHAFT_3", "seeking_arrow_shaft_3", "objtypes"),
            new GamevalEntry(33545, "SEEKING_ARROW_SHAFT_4", "seeking_arrow_shaft_4", "objtypes"),
            new GamevalEntry(33546, "SEEKING_ARROW_SHAFT_5", "seeking_arrow_shaft_5", "objtypes"),
            new GamevalEntry(33547, "SEEKING_HEADLESS_ARROW", "Seeking headless arrow", "objtypes"),
            new GamevalEntry(33548, "PLACEHOLDER_SEEKING_HEADLESS_ARROW", "placeholder_seeking_headless_arrow", "objtypes"),
            new GamevalEntry(33549, "SEEKING_HEADLESS_ARROW_2", "seeking_headless_arrow_2", "objtypes"),
            new GamevalEntry(33550, "SEEKING_HEADLESS_ARROW_3", "seeking_headless_arrow_3", "objtypes"),
            new GamevalEntry(33551, "SEEKING_HEADLESS_ARROW_4", "seeking_headless_arrow_4", "objtypes"),
            new GamevalEntry(33552, "SEEKING_HEADLESS_ARROW_5", "seeking_headless_arrow_5", "objtypes"),
            new GamevalEntry(33553, "SEEKING_BRONZE_ARROW", "Seeking bronze arrow", "objtypes"),
            new GamevalEntry(33554, "PLACEHOLDER_SEEKING_BRONZE_ARROW", "placeholder_seeking_bronze_arrow", "objtypes"),
            new GamevalEntry(33555, "SEEKING_BRONZE_ARROW_2", "seeking_bronze_arrow_2", "objtypes"),
            new GamevalEntry(33556, "SEEKING_BRONZE_ARROW_3", "seeking_bronze_arrow_3", "objtypes"),
            new GamevalEntry(33557, "SEEKING_BRONZE_ARROW_4", "seeking_bronze_arrow_4", "objtypes"),
            new GamevalEntry(33558, "SEEKING_BRONZE_ARROW_5", "seeking_bronze_arrow_5", "objtypes"),
            new GamevalEntry(33559, "SEEKING_IRON_ARROW", "Seeking iron arrow", "objtypes"),
            new GamevalEntry(33560, "PLACEHOLDER_SEEKING_IRON_ARROW", "placeholder_seeking_iron_arrow", "objtypes"),
            new GamevalEntry(33561, "SEEKING_IRON_ARROW_2", "seeking_iron_arrow_2", "objtypes"),
            new GamevalEntry(33562, "SEEKING_IRON_ARROW_3", "seeking_iron_arrow_3", "objtypes"),
            new GamevalEntry(33563, "SEEKING_IRON_ARROW_4", "seeking_iron_arrow_4", "objtypes"),
            new GamevalEntry(33564, "SEEKING_IRON_ARROW_5", "seeking_iron_arrow_5", "objtypes"),
            new GamevalEntry(33565, "SEEKING_STEEL_ARROW", "Seeking steel arrow", "objtypes"),
            new GamevalEntry(33566, "PLACEHOLDER_SEEKING_STEEL_ARROW", "placeholder_seeking_steel_arrow", "objtypes"),
            new GamevalEntry(33567, "SEEKING_STEEL_ARROW_2", "seeking_steel_arrow_2", "objtypes"),
            new GamevalEntry(33568, "SEEKING_STEEL_ARROW_3", "seeking_steel_arrow_3", "objtypes"),
            new GamevalEntry(33569, "SEEKING_STEEL_ARROW_4", "seeking_steel_arrow_4", "objtypes"),
            new GamevalEntry(33570, "SEEKING_STEEL_ARROW_5", "seeking_steel_arrow_5", "objtypes"),
            new GamevalEntry(33571, "SEEKING_MITHRIL_ARROW", "Seeking mithril arrow", "objtypes"),
            new GamevalEntry(33572, "PLACEHOLDER_SEEKING_MITHRIL_ARROW", "placeholder_seeking_mithril_arrow", "objtypes"),
            new GamevalEntry(33573, "SEEKING_MITHRIL_ARROW_2", "seeking_mithril_arrow_2", "objtypes"),
            new GamevalEntry(33574, "SEEKING_MITHRIL_ARROW_3", "seeking_mithril_arrow_3", "objtypes"),
            new GamevalEntry(33575, "SEEKING_MITHRIL_ARROW_4", "seeking_mithril_arrow_4", "objtypes"),
            new GamevalEntry(33576, "SEEKING_MITHRIL_ARROW_5", "seeking_mithril_arrow_5", "objtypes"),
            new GamevalEntry(33577, "SEEKING_ADAMANT_ARROW", "Seeking adamant arrow", "objtypes"),
            new GamevalEntry(33578, "PLACEHOLDER_SEEKING_ADAMANT_ARROW", "placeholder_seeking_adamant_arrow", "objtypes"),
            new GamevalEntry(33579, "SEEKING_ADAMANT_ARROW_2", "seeking_adamant_arrow_2", "objtypes"),
            new GamevalEntry(33580, "SEEKING_ADAMANT_ARROW_3", "seeking_adamant_arrow_3", "objtypes"),
            new GamevalEntry(33581, "SEEKING_ADAMANT_ARROW_4", "seeking_adamant_arrow_4", "objtypes"),
            new GamevalEntry(33582, "SEEKING_ADAMANT_ARROW_5", "seeking_adamant_arrow_5", "objtypes"),
            new GamevalEntry(33583, "SEEKING_RUNE_ARROW", "Seeking rune arrow", "objtypes"),
            new GamevalEntry(33584, "PLACEHOLDER_SEEKING_RUNE_ARROW", "placeholder_seeking_rune_arrow", "objtypes"),
            new GamevalEntry(33585, "SEEKING_RUNE_ARROW_2", "seeking_rune_arrow_2", "objtypes"),
            new GamevalEntry(33586, "SEEKING_RUNE_ARROW_3", "seeking_rune_arrow_3", "objtypes"),
            new GamevalEntry(33587, "SEEKING_RUNE_ARROW_4", "seeking_rune_arrow_4", "objtypes"),
            new GamevalEntry(33588, "SEEKING_RUNE_ARROW_5", "seeking_rune_arrow_5", "objtypes"),
            new GamevalEntry(33589, "SEEKING_AMETHYST_ARROW", "Seeking amethyst arrow", "objtypes"),
            new GamevalEntry(33590, "PLACEHOLDER_SEEKING_AMETHYST_ARROW", "placeholder_seeking_amethyst_arrow", "objtypes"),
            new GamevalEntry(33591, "SEEKING_AMETHYST_ARROW_2", "seeking_amethyst_arrow_2", "objtypes"),
            new GamevalEntry(33592, "SEEKING_AMETHYST_ARROW_3", "seeking_amethyst_arrow_3", "objtypes"),
            new GamevalEntry(33593, "SEEKING_AMETHYST_ARROW_4", "seeking_amethyst_arrow_4", "objtypes"),
            new GamevalEntry(33594, "SEEKING_AMETHYST_ARROW_5", "seeking_amethyst_arrow_5", "objtypes"),
            new GamevalEntry(33595, "SEEKING_DRAGON_ARROW", "Seeking dragon arrow", "objtypes"),
            new GamevalEntry(33596, "PLACEHOLDER_SEEKING_DRAGON_ARROW", "placeholder_seeking_dragon_arrow", "objtypes"),
            new GamevalEntry(33597, "SEEKING_DRAGON_ARROW2", "seeking_dragon_arrow2", "objtypes"),
            new GamevalEntry(33598, "SEEKING_DRAGON_ARROW3", "seeking_dragon_arrow3", "objtypes"),
            new GamevalEntry(33599, "SEEKING_DRAGON_ARROW4", "seeking_dragon_arrow4", "objtypes"),
            new GamevalEntry(33600, "SEEKING_DRAGON_ARROW5", "seeking_dragon_arrow5", "objtypes"),
            new GamevalEntry(33601, "SEEKING_SLAYER_BROAD_ARROWS", "Seeking broad arrows", "objtypes"),
            new GamevalEntry(33602, "PLACEHOLDER_SEEKING_SLAYER_BROAD_ARROWS", "placeholder_seeking_slayer_broad_arrows", "objtypes"),
            new GamevalEntry(33603, "SEEKING_SLAYER_BROAD_ARROWS_5", "seeking_slayer_broad_arrows_5", "objtypes"),
            new GamevalEntry(33604, "SEEKING_SLAYER_BROAD_ARROWS_4", "seeking_slayer_broad_arrows_4", "objtypes"),
            new GamevalEntry(33605, "SEEKING_SLAYER_BROAD_ARROWS_3", "seeking_slayer_broad_arrows_3", "objtypes"),
            new GamevalEntry(33606, "SEEKING_SLAYER_BROAD_ARROWS_2", "seeking_slayer_broad_arrows_2", "objtypes"),
            new GamevalEntry(33607, "SAP_TREATED_LOGS", "Sap-treated logs", "objtypes"),
            new GamevalEntry(33608, "PLACEHOLDER_SAP_TREATED_LOGS", "placeholder_sap_treated_logs", "objtypes"),
            new GamevalEntry(33609, "SAP_TREATED_MAGIC_LOGS", "Sap-treated magic logs", "objtypes"),
            new GamevalEntry(33610, "PLACEHOLDER_SAP_TREATED_MAGIC_LOGS", "placeholder_sap_treated_magic_logs", "objtypes"),
            new GamevalEntry(33611, "SAP_TREATED_YEW_LOGS", "Sap-treated yew logs", "objtypes"),
            new GamevalEntry(33612, "PLACEHOLDER_SAP_TREATED_YEW_LOGS", "placeholder_sap_treated_yew_logs", "objtypes"),
            new GamevalEntry(33613, "SAP_TREATED_MAPLE_LOGS", "Sap-treated maple logs", "objtypes"),
            new GamevalEntry(33614, "PLACEHOLDER_SAP_TREATED_MAPLE_LOGS", "placeholder_sap_treated_maple_logs", "objtypes"),
            new GamevalEntry(33615, "SAP_TREATED_WILLOW_LOGS", "Sap-treated willow logs", "objtypes"),
            new GamevalEntry(33616, "PLACEHOLDER_SAP_TREATED_WILLOW_LOGS", "placeholder_sap_treated_willow_logs", "objtypes"),
            new GamevalEntry(33617, "SAP_TREATED_OAK_LOGS", "Sap-treated oak logs", "objtypes"),
            new GamevalEntry(33618, "PLACEHOLDER_SAP_TREATED_OAK_LOGS", "placeholder_sap_treated_oak_logs", "objtypes"),
            new GamevalEntry(33619, "SAP_TREATED_REDWOOD_LOGS", "Sap-treated redwood logs", "objtypes"),
            new GamevalEntry(33620, "PLACEHOLDER_SAP_TREATED_REDWOOD_LOGS", "placeholder_sap_treated_redwood_logs", "objtypes"),
            new GamevalEntry(33621, "LEECHFIN", "Leechfin", "objtypes"),
            new GamevalEntry(33622, "PLACEHOLDER_LEECHFIN", "placeholder_leechfin", "objtypes"),
            new GamevalEntry(33623, "BLOOD_SAC", "Blood sac", "objtypes"),
            new GamevalEntry(33624, "PLACEHOLDER_BLOOD_SAC", "placeholder_blood_sac", "objtypes"),
            new GamevalEntry(33625, "LETVEK", "Letvek", "objtypes"),
            new GamevalEntry(33626, "PLACEHOLDER_LETVEK", "placeholder_letvek", "objtypes"),
            new GamevalEntry(33627, "DULL_ZAROSIAN_MEDAL", "Dull ancient medal", "objtypes"),
            new GamevalEntry(33628, "STYMPHIKE_TARTARE", "Stymphike tartare", "objtypes"),
            new GamevalEntry(33629, "ROTTEN_STYMPHIKE_TARTARE", "Rotten stymphike tartare", "objtypes"),
            new GamevalEntry(33630, "SUPPLY_DROP_DUMMY", "Supplies", "objtypes"),
            new GamevalEntry(33631, "CRIMSON_KISTEN", "Crimson kisten", "objtypes"),
            new GamevalEntry(33632, "CERT_CRIMSON_KISTEN", "cert_crimson_kisten", "objtypes"),
            new GamevalEntry(33633, "PLACEHOLDER_CRIMSON_KISTEN", "placeholder_crimson_kisten", "objtypes"),
            new GamevalEntry(33634, "ELDER_VENATOR_FANG", "Elder venator fang", "objtypes"),
            new GamevalEntry(33635, "PLACEHOLDER_ELDER_VENATOR_FANG", "placeholder_elder_venator_fang", "objtypes"),
            new GamevalEntry(33636, "ETCHED_ELDER_VENATOR_FANG", "Etched elder venator fang", "objtypes"),
            new GamevalEntry(33637, "CERT_ETCHED_ELDER_VENATOR_FANG", "cert_etched_elder_venator_fang", "objtypes"),
            new GamevalEntry(33638, "PLACEHOLDER_ETCHED_ELDER_VENATOR_FANG", "placeholder_etched_elder_venator_fang", "objtypes"),
            new GamevalEntry(33639, "NECKLACE_OF_RUPTURE", "Necklace of rupture", "objtypes"),
            new GamevalEntry(33640, "CERT_NECKLACE_OF_RUPTURE", "cert_necklace_of_rupture", "objtypes"),
            new GamevalEntry(33641, "PLACEHOLDER_NECKLACE_OF_RUPTURE", "placeholder_necklace_of_rupture", "objtypes"),
            new GamevalEntry(33642, "MAGGOTKINGPET", "Maggot marquess", "objtypes"),
            new GamevalEntry(33643, "PLACEHOLDER_MAGGOTKINGPET", "placeholder_maggotkingpet", "objtypes"),
            new GamevalEntry(33644, "DUMMY_STYMPHIKE_FEATHER01", "Dummy stymphike feather", "objtypes"),
            new GamevalEntry(33645, "CERT_DUMMY_STYMPHIKE_FEATHER01", "cert_dummy_stymphike_feather01", "objtypes"),
            new GamevalEntry(33646, "PLACEHOLDER_DUMMY_STYMPHIKE_FEATHER01", "placeholder_dummy_stymphike_feather01", "objtypes"),
            new GamevalEntry(33647, "RUPTURE_NECKLACE_FANG_DUMMY", "rupture_necklace_fang_dummy", "objtypes"),
            new GamevalEntry(33648, "RUPTURE_NECKLACE_ZENYTE_DUMMY", "rupture_necklace_zenyte_dummy", "objtypes"),
            new GamevalEntry(33649, "RUPTURE_NECKLACE_RUPTURE01_DUMMY", "rupture_necklace_rupture01_dummy", "objtypes"),
            new GamevalEntry(33650, "RUPTURE_NECKLACE_RUPTURE02_DUMMY", "rupture_necklace_rupture02_dummy", "objtypes"),
            new GamevalEntry(33651, "STYMPHIKE_FEATHER", "A Stymphike feather", "objtypes"),
            new GamevalEntry(33652, "PLACEHOLDER_STYMPHIKE_FEATHER", "placeholder_stymphike_feather", "objtypes"),
            new GamevalEntry(33653, "STYMPHIKE_CARCASS", "Stymphike carcass", "objtypes"),
            new GamevalEntry(33654, "PLACEHOLDER_STYMPHIKE_CARCASS", "placeholder_stymphike_carcass", "objtypes"),
            new GamevalEntry(33655, "HUNTING_STYMPHIKE_SPEAR", "Makeshift spear", "objtypes"),
            new GamevalEntry(33656, "PLACEHOLDER_HUNTING_STYMPHIKE_SPEAR", "placeholder_hunting_stymphike_spear", "objtypes"),
            new GamevalEntry(33657, "ORIKALKUM_GRAVEL", "Orikalkum gravel", "objtypes"),
            new GamevalEntry(33658, "PLACEHOLDER_ORIKALKUM_GRAVEL", "placeholder_orikalkum_gravel", "objtypes"),
            new GamevalEntry(33659, "GRAPEVINE", "Grapevine", "objtypes"),
            new GamevalEntry(33660, "PLACEHOLDER_GRAPEVINE", "placeholder_grapevine", "objtypes"),
            new GamevalEntry(33661, "VENATOR_FANG", "Venator fang", "objtypes"),
            new GamevalEntry(33662, "PLACEHOLDER_VENATOR_FANG", "placeholder_venator_fang", "objtypes"),
            new GamevalEntry(33663, "VENATOR_TOOTH", "Venator tooth", "objtypes"),
            new GamevalEntry(33664, "PLACEHOLDER_VENATOR_TOOTH", "placeholder_venator_tooth", "objtypes"),
            new GamevalEntry(33665, "MAGGOT_EGG", "Maggot egg", "objtypes"),
            new GamevalEntry(33666, "PLACEHOLDER_MAGGOT_EGG", "placeholder_maggot_egg", "objtypes"),
            new GamevalEntry(33667, "SICKLY_MAGGOT_EGG", "Maggot egg", "objtypes"),
            new GamevalEntry(33668, "PLACEHOLDER_SICKLY_MAGGOT_EGG", "placeholder_sickly_maggot_egg", "objtypes"),
            new GamevalEntry(33669, "WARM_MAGGOT_EGG", "Maggot egg", "objtypes"),
            new GamevalEntry(33670, "PLACEHOLDER_WARM_MAGGOT_EGG", "placeholder_warm_maggot_egg", "objtypes"),
            new GamevalEntry(33671, "PULSATING_MAGGOT_EGG", "Maggot egg", "objtypes"),
            new GamevalEntry(33672, "PLACEHOLDER_PULSATING_MAGGOT_EGG", "placeholder_pulsating_maggot_egg", "objtypes"),
            new GamevalEntry(33673, "WRIGGLING_MAGGOT_EGG", "Maggot egg", "objtypes"),
            new GamevalEntry(33674, "PLACEHOLDER_WRIGGLING_MAGGOT_EGG", "placeholder_wriggling_maggot_egg", "objtypes"),
            new GamevalEntry(33675, "WRITHING_MAGGOT_EGG", "Maggot egg", "objtypes"),
            new GamevalEntry(33676, "PLACEHOLDER_WRITHING_MAGGOT_EGG", "placeholder_writhing_maggot_egg", "objtypes"),
            new GamevalEntry(33677, "TARNISHED_LONGSWORD", "Tarnished longsword", "objtypes"),
            new GamevalEntry(33678, "PLACEHOLDER_TARNISHED_LONGSWORD", "placeholder_tarnished_longsword", "objtypes"),
            new GamevalEntry(33679, "TARNISHED_SPEAR", "Tarnished spear", "objtypes"),
            new GamevalEntry(33680, "PLACEHOLDER_TARNISHED_SPEAR", "placeholder_tarnished_spear", "objtypes"),
            new GamevalEntry(33681, "TARNISHED_2H_SWORD", "Tarnished 2h sword", "objtypes"),
            new GamevalEntry(33682, "PLACEHOLDER_TARNISHED_2H_SWORD", "placeholder_tarnished_2h_sword", "objtypes"),
            new GamevalEntry(33683, "TARNISHED_BATTLEAXE", "Tarnished battleaxe", "objtypes"),
            new GamevalEntry(33684, "PLACEHOLDER_TARNISHED_BATTLEAXE", "placeholder_tarnished_battleaxe", "objtypes"),
            new GamevalEntry(33685, "TARNISHED_HALBERD", "Tarnished halberd", "objtypes"),
            new GamevalEntry(33686, "PLACEHOLDER_TARNISHED_HALBERD", "placeholder_tarnished_halberd", "objtypes"),
            new GamevalEntry(33687, "TARNISHED_RING", "Tarnished ring", "objtypes"),
            new GamevalEntry(33688, "PLACEHOLDER_TARNISHED_RING", "placeholder_tarnished_ring", "objtypes"),
            new GamevalEntry(33689, "TARNISHED_BRACELET", "Tarnished bracelet", "objtypes"),
            new GamevalEntry(33690, "PLACEHOLDER_TARNISHED_BRACELET", "placeholder_tarnished_bracelet", "objtypes"),
            new GamevalEntry(33691, "TARNISHED_NECKLACE", "Tarnished necklace", "objtypes"),
            new GamevalEntry(33692, "PLACEHOLDER_TARNISHED_NECKLACE", "placeholder_tarnished_necklace", "objtypes"),
            new GamevalEntry(33693, "TARNISHED_AMULET", "Tarnished amulet", "objtypes"),
            new GamevalEntry(33694, "PLACEHOLDER_TARNISHED_AMULET", "placeholder_tarnished_amulet", "objtypes"),
            new GamevalEntry(33695, "VENATOR_HEART", "Venator heart", "objtypes"),
            new GamevalEntry(33696, "PLACEHOLDER_VENATOR_HEART", "placeholder_venator_heart", "objtypes"),
            new GamevalEntry(33697, "DRIED_OUT_VENATOR_HEART", "Dried out venator heart", "objtypes"),
            new GamevalEntry(33698, "PLACEHOLDER_DRIED_OUT_VENATOR_HEART", "placeholder_dried_out_venator_heart", "objtypes"),
            new GamevalEntry(33699, "BR_VIAL_EMPTY", "Vial", "objtypes"),
            new GamevalEntry(33700, "PLACEHOLDER_BR_VIAL_EMPTY", "placeholder_br_vial_empty", "objtypes"),
            new GamevalEntry(33701, "MYQ6_SQUIRE_JOURNAL", "Squire's journal", "objtypes"),
            new GamevalEntry(33702, "MYQ6_IRIANDUL_JOURNAL", "From Misthalin to Morytania", "objtypes"),
            new GamevalEntry(33703, "MYQ6_SARL_JOURNAL", "Sarl's journal", "objtypes"),
            new GamevalEntry(33704, "MYQ6_DERYGULL_JOURNAL", "Scruffy notebook", "objtypes"),
            new GamevalEntry(33705, "MYQ6_ERYSAIL_JOURNAL", "Pious proceedings", "objtypes"),
            new GamevalEntry(33706, "MYQ6_FRIAR_JOURNAL", "The Life of Friar", "objtypes"),
            new GamevalEntry(33707, "MYQ6_ESSIANDAR_JOURNAL", "Essiandar's notes", "objtypes"),
            new GamevalEntry(33708, "MYQ6_IVANDIS_WRITINGS", "Ivandis' writings", "objtypes"),
            new GamevalEntry(33709, "SILVER_SICKLE_DIAMOND", "Diamond sickle (b)", "objtypes"),
            new GamevalEntry(33710, "PLACEHOLDER_SILVER_SICKLE_DIAMOND", "placeholder_silver_sickle_diamond", "objtypes"),
            new GamevalEntry(33711, "SILVER_SICKLE_DIAMOND_ENCHANTED", "Enchanted diamond sickle (b)", "objtypes"),
            new GamevalEntry(33712, "PLACEHOLDER_SILVER_SICKLE_DIAMOND_ENCHANTED", "placeholder_silver_sickle_diamond_enchanted", "objtypes"),
            new GamevalEntry(33713, "BLISTERWOOD_SICKLE_ENHANCED", "Blisterwood sickle (e)", "objtypes"),
            new GamevalEntry(33714, "PLACEHOLDER_BLISTERWOOD_SICKLE_ENHANCED", "placeholder_blisterwood_sickle_enhanced", "objtypes"),
            new GamevalEntry(33715, "MYQ6_XP_TOME", "Tome of experience", "objtypes"),
            new GamevalEntry(33716, "BLISTERWOOD_STAKE", "Blisterwood stake", "objtypes"),
            new GamevalEntry(33717, "PLACEHOLDER_BLISTERWOOD_STAKE", "placeholder_blisterwood_stake", "objtypes"),
            new GamevalEntry(33718, "HALLOWED_FLAIL", "Hallowed flail", "objtypes"),
            new GamevalEntry(33719, "PLACEHOLDER_HALLOWED_FLAIL", "placeholder_hallowed_flail", "objtypes"),
            new GamevalEntry(33720, "MYQ6_IVAN_FOLLOWER_OBJ", "Ivan strom", "objtypes"),
            new GamevalEntry(33721, "MYQ6_VELIAF_FOLLOWER_OBJ", "Veliaf hurtz", "objtypes"),
            new GamevalEntry(33722, "SUNSPEAR", "Sunspear", "objtypes"),
            new GamevalEntry(33723, "PLACEHOLDER_SUNSPEAR", "placeholder_sunspear", "objtypes"),
            new GamevalEntry(33724, "CASTLE_DRAKAN_FULL_MOON_KEY", "Full moon key", "objtypes"),
            new GamevalEntry(33725, "CASTLE_DRAKAN_HALF_MOON_KEY", "Half moon key", "objtypes"),
            new GamevalEntry(33726, "CASTLE_DRAKAN_CRESCENT_MOON_KEY", "Crescent moon key", "objtypes"),
            new GamevalEntry(33727, "CASTLE_DRAKAN_GIBBOUS_MOON_KEY", "Gibbous moon key", "objtypes"),
            new GamevalEntry(33728, "CASTLE_DRAKAN_NEW_MOON_KEY", "New moon key", "objtypes"),
            new GamevalEntry(33729, "CASTLE_DRAKAN_GILDED_KEY", "Gilded key", "objtypes"),
            new GamevalEntry(33730, "CASTLE_DRAKAN_LAB_KEY", "Solid key", "objtypes"),
            new GamevalEntry(33731, "CASTLE_DRAKAN_DRAKAN_EMBLEM_1", "Drakan emblem", "objtypes"),
            new GamevalEntry(33732, "CASTLE_DRAKAN_DRAKAN_EMBLEM_2", "Drakan emblem", "objtypes"),
            new GamevalEntry(33733, "CASTLE_DRAKAN_DRAKAN_EMBLEM_3", "Drakan emblem", "objtypes"),
            new GamevalEntry(33734, "CASTLE_DRAKAN_LEFT_CREST_HALF", "Left crest half", "objtypes"),
            new GamevalEntry(33735, "CASTLE_DRAKAN_RIGHT_CREST_HALF", "Right crest half", "objtypes"),
            new GamevalEntry(33736, "CASTLE_DRAKAN_FULL_CREST", "Full crest", "objtypes"),
            new GamevalEntry(33737, "CASTLE_DRAKAN_ANCIENT_SYMBOL", "Ancient symbol", "objtypes"),
            new GamevalEntry(33738, "CASTLE_DRAKAN_ANCIENT_SHIELD", "Ancient shield", "objtypes"),
            new GamevalEntry(33739, "CASTLE_DRAKAN_SHIELD_WITH_SYMBOL", "Shield with symbol", "objtypes"),
            new GamevalEntry(33740, "CASTLE_DRAKAN_ORNATE_KNIFE", "Ornate knife", "objtypes"),
            new GamevalEntry(33741, "CASTLE_DRAKAN_ORNATE_SKULL", "Ornate skull", "objtypes"),
            new GamevalEntry(33742, "CASTLE_DRAKAN_ORNATE_HOURGLASS", "Ornate hourglass", "objtypes"),
            new GamevalEntry(33743, "CASTLE_DRAKAN_POTENT_BARREL", "Explosive barrel", "objtypes"),
            new GamevalEntry(33744, "CASTLE_DRAKAN_SMALL_CLOCK_HAND", "Small clock hand", "objtypes"),
            new GamevalEntry(33745, "CASTLE_DRAKAN_LARGE_CLOCK_HAND", "Large clock hand", "objtypes"),
            new GamevalEntry(33746, "CASTLE_DRAKAN_POEM_SCROLL", "Poem scroll", "objtypes"),
            new GamevalEntry(33747, "CASTLE_DRAKAN_SINK_PLUG", "Sink plug", "objtypes"),
            new GamevalEntry(33748, "CASTLE_DRAKAN_BROKEN_PIPE", "Broken pipe", "objtypes"),
            new GamevalEntry(33749, "CASTLE_DRAKAN_SHARP_KNIFE", "Sharp knife", "objtypes"),
            new GamevalEntry(33750, "CASTLE_DRAKAN_TONGS", "Tongs", "objtypes"),
            new GamevalEntry(33751, "CASTLE_DRAKAN_SYRINGE_NEEDLE", "Syringe needle", "objtypes"),
            new GamevalEntry(33752, "CASTLE_DRAKAN_SYRINGE_BARREL", "Syringe barrel", "objtypes"),
            new GamevalEntry(33753, "CASTLE_DRAKAN_SYRINGE_PLUNGER", "Syringe plunger", "objtypes"),
            new GamevalEntry(33754, "CASTLE_DRAKAN_EMPTY_SYRINGE", "Empty syringe", "objtypes"),
            new GamevalEntry(33755, "CASTLE_DRAKAN_FULL_SYRINGE", "Full syringe", "objtypes"),
            new GamevalEntry(33756, "CASTLE_DRAKAN_VENATOR_STOMACH", "Venator stomach", "objtypes"),
            new GamevalEntry(33757, "CASTLE_DRAKAN_OLD_SWORD", "Sword", "objtypes"),
            new GamevalEntry(33758, "CASTLE_DRAKAN_OLD_SPEAR", "Spear", "objtypes"),
            new GamevalEntry(33759, "CASTLE_DRAKAN_OLD_BATTLEAXE", "Battleaxe", "objtypes"),
            new GamevalEntry(33760, "CASTLE_DRAKAN_OLD_MACE", "Mace", "objtypes"),
            new GamevalEntry(33761, "CASTLE_DRAKAN_LOCKBOX", "Lockbox", "objtypes"),
            new GamevalEntry(33762, "CASTLE_DRAKAN_ANCESTRAL_DAGGER", "Ancestral dagger", "objtypes"),
            new GamevalEntry(33763, "CASTLE_DRAKAN_GRID_NOTE", "Grid note", "objtypes"),
            new GamevalEntry(33764, "CASTLE_DRAKAN_MYSTERIOUS_BOOK", "Mysterious book", "objtypes"),
            new GamevalEntry(33765, "CASTLE_DRAKAN_FANCY_GEM_1", "Fancy gem", "objtypes"),
            new GamevalEntry(33766, "CASTLE_DRAKAN_FANCY_GEM_2", "Fancy gem", "objtypes"),
            new GamevalEntry(33767, "CASTLE_DRAKAN_GILDED_BOOK", "Gilded book", "objtypes"),
            new GamevalEntry(33768, "CASTLE_DRAKAN_LANGUAGE_BOOK", "Vampyre book", "objtypes"),
            new GamevalEntry(33769, "CASTLE_DRAKAN_CLOUDY_GREY_POTION", "Cloudy grey potion", "objtypes"),
            new GamevalEntry(33770, "CASTLE_DRAKAN_WEIGHTLESS_BLACK_POTION", "Weightless black potion", "objtypes"),
            new GamevalEntry(33771, "CASTLE_DRAKAN_THICK_RED_POTION", "Thick red potion", "objtypes"),
            new GamevalEntry(33772, "CASTLE_DRAKAN_COLD_WHITE_POTION", "Cold bluish-white potion", "objtypes"),
            new GamevalEntry(33773, "CASTLE_DRAKAN_LAB_NOTES", "Lab notes", "objtypes"),
            new GamevalEntry(33774, "CASTLE_DRAKAN_VIAL_OF_WATER", "Vial of water", "objtypes"),
            new GamevalEntry(33775, "CASTLE_DRAKAN_VIAL_OF_BLOOD", "Vial of blood", "objtypes"),
            new GamevalEntry(33776, "CASTLE_DRAKAN_PURE_ESSENCE", "Pure essence", "objtypes"),
            new GamevalEntry(33777, "CASTLE_DRAKAN_DAEYALT_ORE", "Daeyalt ore", "objtypes"),
            new GamevalEntry(33778, "CASTLE_DRAKAN_CHEMICAL_VIAL", "Chemical vial", "objtypes"),
            new GamevalEntry(33779, "SANGVESTI_COG", "+K ?'Destroy", "objtypes"),
            new GamevalEntry(33780, "SANGVESTI_JOVKAI_KEY", "Jovkai key", "objtypes"),
            new GamevalEntry(33781, "SANGVESTI_MYRMEL_KEY_LOOP", "Loop half of key", "objtypes"),
            new GamevalEntry(33782, "SANGVESTI_MYRMEL_KEY_TOOTH", "Tooth half of key", "objtypes"),
            new GamevalEntry(33783, "SANGVESTI_MYRMEL_KEY", "Myrmel key", "objtypes"),
            new GamevalEntry(33784, "SANGVESTI_SHADUM_KEY", "Shadum key", "objtypes"),
            new GamevalEntry(33785, "SANGVESTI_VITUR_KEY", "Vitur key", "objtypes"),
            new GamevalEntry(33786, "SANGVESTI_TRAPDOOR_KEY", "Trapdoor key", "objtypes"),
            new GamevalEntry(33787, "SANGVESTI_BOLT_CUTTERS", "Bolt cutters", "objtypes"),
            new GamevalEntry(33788, "SANGVESTI_CRANK_WHEEL", "Crank wheel", "objtypes"),
            new GamevalEntry(33789, "SANGVESTI_VITUR_KEY_BOOK", "Dusty book", "objtypes"),
            new GamevalEntry(33790, "SOTFA_FOREST_TALON", "Spine", "objtypes"),
            new GamevalEntry(33791, "SOTFA_FOREST_DEAD_BLOOD_SERPENT", "Dead blood serpent", "objtypes"),
            new GamevalEntry(33792, "SOTFA_FOREST_ROPE", "Serpent rope", "objtypes"),
            new GamevalEntry(33793, "SOTFA_FOREST_TICK", "Tick", "objtypes"),
            new GamevalEntry(33794, "SOTFA_FOREST_JOURNAL", "Tattered journal", "objtypes"),
            new GamevalEntry(33795, "MYQ6_ROTTEN_DIARY", "Rotten diary", "objtypes"),
            new GamevalEntry(33796, "MYQ6_LEAVES", "Amitire leaves", "objtypes"),
            new GamevalEntry(33797, "MYQ6_STEW", "Amitire stew", "objtypes"),
            new GamevalEntry(33798, "MYQ6_HALLOWED_MARKS", "Hallowed marks", "objtypes"),
            new GamevalEntry(33799, "MYQ6_ENTRY_HALL_POTION", "Healing potion", "objtypes"),
            new GamevalEntry(33800, "MYQ6_BALLISTA", "Silvthrill ballista", "objtypes"),
            new GamevalEntry(33801, "MYQ6_JAVELIN", "Silvthrill javelin", "objtypes"),
            new GamevalEntry(33802, "VAMPYRIUM_MYSTERY_JERKY", "Mysterious jerky", "objtypes"),
            new GamevalEntry(33803, "VAMPYRIUM_STICKY_POTION_4", "Putrid sticky potion (4)", "objtypes"),
            new GamevalEntry(33804, "VAMPYRIUM_STICKY_POTION_3", "Putrid sticky potion (3)", "objtypes"),
            new GamevalEntry(33805, "VAMPYRIUM_STICKY_POTION_2", "Putrid sticky potion (2)", "objtypes"),
            new GamevalEntry(33806, "VAMPYRIUM_STICKY_POTION_1", "Putrid sticky potion (1)", "objtypes"),
            new GamevalEntry(33807, "VAMPYRIUM_CHUNKY_POTION_4", "Foul chunky potion (4)", "objtypes"),
            new GamevalEntry(33808, "VAMPYRIUM_CHUNKY_POTION_3", "Foul chunky potion (3)", "objtypes"),
            new GamevalEntry(33809, "VAMPYRIUM_CHUNKY_POTION_2", "Foul chunky potion (2)", "objtypes"),
            new GamevalEntry(33810, "VAMPYRIUM_CHUNKY_POTION_1", "Foul chunky potion (1)", "objtypes"),
            new GamevalEntry(33811, "VAMPYRIUM_SLIMY_POTION_4", "Rancid slimy potion (4)", "objtypes"),
            new GamevalEntry(33812, "VAMPYRIUM_SLIMY_POTION_3", "Rancid slimy potion (3)", "objtypes"),
            new GamevalEntry(33813, "VAMPYRIUM_SLIMY_POTION_2", "Rancid slimy potion (2)", "objtypes"),
            new GamevalEntry(33814, "VAMPYRIUM_SLIMY_POTION_1", "Rancid slimy potion (1)", "objtypes"),
            new GamevalEntry(33815, "VAMPYRIUM_FROTHY_POTION_4", "Rank frothy potion (4)", "objtypes"),
            new GamevalEntry(33816, "VAMPYRIUM_FROTHY_POTION_3", "Rank frothy potion (3)", "objtypes"),
            new GamevalEntry(33817, "VAMPYRIUM_FROTHY_POTION_2", "Rank frothy potion (2)", "objtypes"),
            new GamevalEntry(33818, "VAMPYRIUM_FROTHY_POTION_1", "Rank frothy potion (1)", "objtypes"),
            new GamevalEntry(33819, "VAMPYRIUM_CONGEALED_BLOOD", "Jar of congealed blood", "objtypes"),
            new GamevalEntry(33820, "VAMPYRIUM_MYSTERY_KEBAB", "Smelly kebab", "objtypes"),
            new GamevalEntry(33821, "RAW_IMPALER_MEAT", "Raw impaler meat", "objtypes"),
            new GamevalEntry(33822, "CERT_RAW_IMPALER_MEAT", "cert_raw_impaler_meat", "objtypes"),
            new GamevalEntry(33823, "PLACEHOLDER_RAW_IMPALER_MEAT", "placeholder_raw_impaler_meat", "objtypes"),
            new GamevalEntry(33824, "HUNTGUIDE_STYMPHIKE", "Stymphike", "objtypes"),
            new GamevalEntry(33825, "HUNTGUIDE_LETVEK", "Letvek", "objtypes"),
            new GamevalEntry(33826, "SLAYERGUIDE_VENATOR", "Venator", "objtypes"),
            new GamevalEntry(33827, "ANCIENT_SCEPTRE_TROUVER_BROKEN", "Ancient sceptre (l) (broken)", "objtypes"),
            new GamevalEntry(33828, "PLACEHOLDER_ANCIENT_SCEPTRE_TROUVER_BROKEN", "placeholder_ancient_sceptre_trouver_broken", "objtypes"),
            new GamevalEntry(33829, "ANCIENT_SCEPTRE_TROUVER_MANGLED", "Ancient sceptre (l) (mangled)", "objtypes"),
            new GamevalEntry(33830, "PLACEHOLDER_ANCIENT_SCEPTRE_TROUVER_MANGLED", "placeholder_ancient_sceptre_trouver_mangled", "objtypes"),
            new GamevalEntry(33831, "PLACEHOLDER_CERT_ALUFT_COCTAIL_GLASS_EMPTY", "placeholder_cert_aluft_coctail_glass_empty", "objtypes"),
            new GamevalEntry(33832, "PLACEHOLDER_CERT_ALUFT_COCTAIL_GLASS_EMPTY_DUMMY", "placeholder_cert_aluft_coctail_glass_empty_dummy", "objtypes"),
            new GamevalEntry(33833, "LETVEK_IN_A_BUCKET", "Letvek in a bucket", "objtypes"),
            new GamevalEntry(33834, "PLACEHOLDER_LETVEK_IN_A_BUCKET", "placeholder_letvek_in_a_bucket", "objtypes"),
        };
    }

    static Optional<GamevalEntry> byId(int id) {
        for (GamevalEntry entry : entries()) {
            if (entry.id() == id) return Optional.of(entry);
        }
        return Optional.empty();
    }

}
