package net.titan.gamevals.internal;

import java.util.Optional;

import net.titan.gamevals.GamevalEntry;
import net.titan.gamevals.QuestEntry;

final class ItemIDEntries_22 {
    private ItemIDEntries_22() {}

    static GamevalEntry[] entries() {
        return new GamevalEntry[] {
            new GamevalEntry(11500, "CERT_BRUTAL_1DOSE2DEFENSE", "cert_brutal_1dose2defense", "objtypes"),
            new GamevalEntry(11505, "BRUTAL_2DOSE1ANTIDRAGON", "Antifire mix(2)", "objtypes"),
            new GamevalEntry(11506, "CERT_BRUTAL_2DOSE1ANTIDRAGON", "cert_brutal_2dose1antidragon", "objtypes"),
            new GamevalEntry(11507, "BRUTAL_1DOSE1ANTIDRAGON", "Antifire mix(1)", "objtypes"),
            new GamevalEntry(11508, "CERT_BRUTAL_1DOSE1ANTIDRAGON", "cert_brutal_1dose1antidragon", "objtypes"),
            new GamevalEntry(11509, "BRUTAL_2DOSERANGERSPOTION", "Ranging mix(2)", "objtypes"),
            new GamevalEntry(11510, "CERT_BRUTAL_2DOSERANGERSPOTION", "cert_brutal_2doserangerspotion", "objtypes"),
            new GamevalEntry(11511, "BRUTAL_1DOSERANGERSPOTION", "Ranging mix(1)", "objtypes"),
            new GamevalEntry(11512, "CERT_BRUTAL_1DOSERANGERSPOTION", "cert_brutal_1doserangerspotion", "objtypes"),
            new GamevalEntry(11513, "BRUTAL_2DOSE1MAGIC", "Magic mix(2)", "objtypes"),
            new GamevalEntry(11514, "CERT_BRUTAL_2DOSE1MAGIC", "cert_brutal_2dose1magic", "objtypes"),
            new GamevalEntry(11515, "BRUTAL_1DOSE1MAGIC", "Magic mix(1)", "objtypes"),
            new GamevalEntry(11516, "CERT_BRUTAL_1DOSE1MAGIC", "cert_brutal_1dose1magic", "objtypes"),
            new GamevalEntry(11517, "BRUTAL_2DOSE1HUNTING", "Hunting mix(2)", "objtypes"),
            new GamevalEntry(11518, "CERT_BRUTAL_2DOSE1HUNTING", "cert_brutal_2dose1hunting", "objtypes"),
            new GamevalEntry(11519, "BRUTAL_1DOSE1HUNTING", "Hunting mix(1)", "objtypes"),
            new GamevalEntry(11520, "CERT_BRUTAL_1DOSE1HUNTING", "cert_brutal_1dose1hunting", "objtypes"),
            new GamevalEntry(11521, "BRUTAL_2DOSEPOTIONOFZAMORAK", "Zamorak mix(2)", "objtypes"),
            new GamevalEntry(11522, "CERT_BRUTAL_2DOSEPOTIONOFZAMORAK", "cert_brutal_2dosepotionofzamorak", "objtypes"),
            new GamevalEntry(11523, "BRUTAL_1DOSEPOTIONOFZAMORAK", "Zamorak mix(1)", "objtypes"),
            new GamevalEntry(11524, "CERT_BRUTAL_1DOSEPOTIONOFZAMORAK", "cert_brutal_1dosepotionofzamorak", "objtypes"),
            new GamevalEntry(11525, "HUNTING_WIMPY_FEATHER", "Feather", "objtypes"),
            new GamevalEntry(11526, "PATTERN_LIME_DUMMY", "pattern_lime_dummy", "objtypes"),
            new GamevalEntry(11527, "PATTERN_PINEAPPLE_CHUNKS_DUMMY", "Mausoleum bridge repair", "objtypes"),
            new GamevalEntry(11528, "PATTERN_BLACK_BATTLEAXE_DUMMY", "pattern_black_battleaxe_dummy", "objtypes"),
            new GamevalEntry(11529, "PATTERN_CHOCOLATE_CAKE_DUMMY", "pattern_chocolate_cake_dummy", "objtypes"),
            new GamevalEntry(11530, "PATTERN_SPADE_DUMMY", "pattern_spade_dummy", "objtypes"),
            new GamevalEntry(11531, "PATTERN_LEATHER_GLOVES_DUMMY", "pattern_leather_gloves_dummy", "objtypes"),
            new GamevalEntry(11532, "PATTERN_TROWEL_DUMMY", "pattern_trowel_dummy", "objtypes"),
            new GamevalEntry(11533, "PATTERN_AIRUNE_DUMMY", "pattern_airune_dummy", "objtypes"),
            new GamevalEntry(11534, "PATTERN_AIR_BATTLESTAFF_DUMMY", "pattern_air_battlestaff_dummy", "objtypes"),
            new GamevalEntry(11535, "PATTERN_OAK_LOGS_DUMMY", "pattern_oak_logs_dummy", "objtypes"),
            new GamevalEntry(11536, "PATTERN_RUNE_FULL_HELM_DUMMY", "pattern_rune_full_helm_dummy", "objtypes"),
            new GamevalEntry(11537, "PATTERN_RUNE_KITESHIELD_DUMMY", "pattern_rune_kiteshield_dummy", "objtypes"),
            new GamevalEntry(11538, "PATTERN_FIRERUNE_DUMMY", "pattern_firerune_dummy", "objtypes"),
            new GamevalEntry(11539, "PATTERN_SHORTBOW_DUMMY", "pattern_shortbow_dummy", "objtypes"),
            new GamevalEntry(11540, "PATTERN_ROBINHOODHAT_DUMMY", "pattern_robinhoodhat_dummy", "objtypes"),
            new GamevalEntry(11541, "PATTERN_LONGBOW_DUMMY", "pattern_longbow_dummy", "objtypes"),
            new GamevalEntry(11542, "PATTERN_CUP_OF_TEA_DUMMY", "pattern_cup_of_tea_dummy", "objtypes"),
            new GamevalEntry(11543, "PATTERN_BEER_DUMMY", "pattern_beer_dummy", "objtypes"),
            new GamevalEntry(11544, "PATTERN_GIN_DUMMY", "pattern_gin_dummy", "objtypes"),
            new GamevalEntry(11545, "PATTERN_REDBERRY_PIE_DUMMY", "pattern_redberry_pie_dummy", "objtypes"),
            new GamevalEntry(11546, "PATTERN_REGICIDE_CLOTH_DUMMY", "pattern_regicide_cloth_dummy", "objtypes"),
            new GamevalEntry(11547, "PATTERN_SACK_EMPTY_DUMMY", "Water pump", "objtypes"),
            new GamevalEntry(11548, "PATTERN_BASKET_EMPTY_DUMMY", "Cooking pot", "objtypes"),
            new GamevalEntry(11549, "PATTERN_STRAWBERRY_DUMMY", "Pottery wheel", "objtypes"),
            new GamevalEntry(11550, "PATTERN_REDBERRY_DUMMY", "Loom", "objtypes"),
            new GamevalEntry(11551, "PATTERN_TINDERBOX_DUMMY", "Pottery oven", "objtypes"),
            new GamevalEntry(11552, "PATTERN_CANDLE_LANTERN_UNLIT_DUMMY", "Rowboat", "objtypes"),
            new GamevalEntry(11553, "PATTERN_HAMMER_DUMMY", "Furnace", "objtypes"),
            new GamevalEntry(11554, "PATTERN_WATERING_CAN_0_DUMMY", "pattern_watering_can_0_dummy", "objtypes"),
            new GamevalEntry(11555, "PATTERN_WHITE_APRON_DUMMY", "pattern_white_apron_dummy", "objtypes"),
            new GamevalEntry(11556, "PATTERN_RAKE_DUMMY", "pattern_rake_dummy", "objtypes"),
            new GamevalEntry(11557, "PATTERN_HIGHWAYMANMASK_DUMMY", "pattern_highwaymanmask_dummy", "objtypes"),
            new GamevalEntry(11558, "PATTERN_PIRATEHAT_DUMMY", "pattern_piratehat_dummy", "objtypes"),
            new GamevalEntry(11559, "PATTERN_LOGS_DUMMY", "pattern_logs_dummy", "objtypes"),
            new GamevalEntry(11560, "PATTERN_CHEFSHAT_DUMMY", "pattern_chefshat_dummy", "objtypes"),
            new GamevalEntry(11561, "PATTERN_PIRATE_BOOTS_DUMMY", "pattern_pirate_boots_dummy", "objtypes"),
            new GamevalEntry(11562, "PATTERN_EARTHRUNE_DUMMY", "pattern_earthrune_dummy", "objtypes"),
            new GamevalEntry(11563, "PATTERN_BLANKRUNE_DUMMY", "pattern_blankrune_dummy", "objtypes"),
            new GamevalEntry(11564, "PATTERN_APPLE_PIE_DUMMY", "pattern_apple_pie_dummy", "objtypes"),
            new GamevalEntry(11565, "PATTERN_THREAD_DUMMY", "pattern_thread_dummy", "objtypes"),
            new GamevalEntry(11566, "PATTERN_RATS_TAIL_DUMMY", "pattern_rats_tail_dummy", "objtypes"),
            new GamevalEntry(11567, "PATTERN_EARTH_BATTLESTAFF_DUMMY", "pattern_earth_battlestaff_dummy", "objtypes"),
            new GamevalEntry(11568, "PATTERN_NEEDLE_DUMMY", "pattern_needle_dummy", "objtypes"),
            new GamevalEntry(11569, "PATTERN_REDDYE_DUMMY", "pattern_reddye_dummy", "objtypes"),
            new GamevalEntry(11570, "PATTERN_EYEPATCH_DUMMY", "pattern_eyepatch_dummy", "objtypes"),
            new GamevalEntry(11571, "PATTERN_SHEARS_DUMMY", "pattern_shears_dummy", "objtypes"),
            new GamevalEntry(11572, "PATTERN_EMERALD_NECKLACE_DUMMY", "pattern_emerald_necklace_dummy", "objtypes"),
            new GamevalEntry(11573, "PATTERN_ADAMANT_AXE_DUMMY", "pattern_adamant_axe_dummy", "objtypes"),
            new GamevalEntry(11574, "PATTERN_SALMON_DUMMY", "Mounted giant blue krill", "objtypes"),
            new GamevalEntry(11575, "PATTERN_CHEESE_DUMMY", "pattern_cheese_dummy", "objtypes"),
            new GamevalEntry(11576, "PATTERN_BLESSEDSTAR_DUMMY", "pattern_blessedstar_dummy", "objtypes"),
            new GamevalEntry(11577, "PATTERN_UNCUT_EMERALD_DUMMY", "pattern_uncut_emerald_dummy", "objtypes"),
            new GamevalEntry(11578, "PATTERN_HARPOON_DUMMY", "Mounted harpoonfish", "objtypes"),
            new GamevalEntry(11579, "PATTERN_IRON_MED_HELM_DUMMY", "pattern_iron_med_helm_dummy", "objtypes"),
            new GamevalEntry(11580, "PATTERN_TROUT_DUMMY", "Mounted golden haddock", "objtypes"),
            new GamevalEntry(11581, "PATTERN_PLANTPOT_EMPTY_DUMMY", "pattern_plantpot_empty_dummy", "objtypes"),
            new GamevalEntry(11582, "PATTERN_WATERRUNE_DUMMY", "pattern_waterrune_dummy", "objtypes"),
            new GamevalEntry(11583, "PATTERN_EMERALD_DUMMY", "pattern_emerald_dummy", "objtypes"),
            new GamevalEntry(11584, "PATTERN_YELLOWDYE_DUMMY", "pattern_yellowdye_dummy", "objtypes"),
            new GamevalEntry(11585, "PATTERN_ORANGEDYE_DUMMY", "pattern_orangedye_dummy", "objtypes"),
            new GamevalEntry(11586, "PATTERN_SECATEURS_DUMMY", "pattern_secateurs_dummy", "objtypes"),
            new GamevalEntry(11587, "PATTERN_IRON_ORE_DUMMY", "pattern_iron_ore_dummy", "objtypes"),
            new GamevalEntry(11588, "PATTERN_COPPER_ORE_DUMMY", "pattern_copper_ore_dummy", "objtypes"),
            new GamevalEntry(11589, "PATTERN_ELENAKEY_DUMMY", "pattern_elenakey_dummy", "objtypes"),
            new GamevalEntry(11590, "PATTERN_TURNIP_BOOK_DUMMY", "pattern_turnip_book_dummy", "objtypes"),
            new GamevalEntry(11591, "PATTERN_RUNE_SCIMITAR_DUMMY", "pattern_rune_scimitar_dummy", "objtypes"),
            new GamevalEntry(11592, "PATTERN_RUNE_BATTLEAXE_DUMMY", "pattern_rune_battleaxe_dummy", "objtypes"),
            new GamevalEntry(11593, "PATTERN_RUNE_MACE_DUMMY", "pattern_rune_mace_dummy", "objtypes"),
            new GamevalEntry(11594, "PATTERN_ADAMANT_PICKAXE_DUMMY", "pattern_adamant_pickaxe_dummy", "objtypes"),
            new GamevalEntry(11595, "PATTERN_RUNE_AXE_DUMMY", "pattern_rune_axe_dummy", "objtypes"),
            new GamevalEntry(11596, "PATTERN_BRONZE_PICKAXE_DUMMY", "pattern_bronze_pickaxe_dummy", "objtypes"),
            new GamevalEntry(11597, "PATTERN_RUNE_LONGSWORD_DUMMY", "pattern_rune_longsword_dummy", "objtypes"),
            new GamevalEntry(11598, "PATTERN_TIARA_DUMMY", "pattern_tiara_dummy", "objtypes"),
            new GamevalEntry(11599, "PATTERN_BASS_DUMMY", "Oak mounted fish display", "objtypes"),
            new GamevalEntry(11600, "PATTERN_PIKE_DUMMY", "Mounted orangefin", "objtypes"),
            new GamevalEntry(11601, "PATTERN_SHARK_DUMMY", "Mahogany mounted fish display", "objtypes"),
            new GamevalEntry(11602, "PATTERN_SHRIMP_DUMMY", "pattern_shrimp_dummy", "objtypes"),
            new GamevalEntry(11603, "PATTERN_SWORDFISH_DUMMY", "Teak mounted fish display", "objtypes"),
            new GamevalEntry(11604, "PATTERN_HERRING_DUMMY", "Mounted halibut", "objtypes"),
            new GamevalEntry(11605, "PATTERN_SARDINE_DUMMY", "Mounted purplefin", "objtypes"),
            new GamevalEntry(11606, "PATTERN_COD_DUMMY", "Mounted marlin", "objtypes"),
            new GamevalEntry(11607, "PATTERN_PINEAPPLE_DUMMY", "pattern_pineapple_dummy", "objtypes"),
            new GamevalEntry(11608, "PATTERN_JUG_DUMMY", "pattern_jug_dummy", "objtypes"),
            new GamevalEntry(11609, "PATTERN_BOWL_EMPTY_DUMMY", "pattern_bowl_empty_dummy", "objtypes"),
            new GamevalEntry(11610, "PATTERN_POT_EMPTY_DUMMY", "pattern_pot_empty_dummy", "objtypes"),
            new GamevalEntry(11611, "PATTERN_IRON_BAR_DUMMY", "pattern_iron_bar_dummy", "objtypes"),
            new GamevalEntry(11612, "PATTERN_BRONZE_BAR_DUMMY", "pattern_bronze_bar_dummy", "objtypes"),
            new GamevalEntry(11613, "PATTERN_GOLD_BAR_DUMMY", "pattern_gold_bar_dummy", "objtypes"),
            new GamevalEntry(11614, "PATTERN_STEEL_ARROW_3_DUMMY", "pattern_steel_arrow_3_dummy", "objtypes"),
            new GamevalEntry(11615, "PATTERN_BRONZE_ARROW_3_DUMMY", "pattern_bronze_arrow_3_dummy", "objtypes"),
            new GamevalEntry(11616, "PATTERN_CAKE_DUMMY", "pattern_cake_dummy", "objtypes"),
            new GamevalEntry(11617, "PATTERN_BONES_DUMMY", "pattern_bones_dummy", "objtypes"),
            new GamevalEntry(11618, "PATTERN_BOOTS_RANGER_DUMMY", "pattern_boots_ranger_dummy", "objtypes"),
            new GamevalEntry(11619, "PATTERN_MACRO_MIME_MASK_DUMMY", "pattern_macro_mime_mask_dummy", "objtypes"),
            new GamevalEntry(11620, "PATTERN_BREAD_DUMMY", "pattern_bread_dummy", "objtypes"),
            new GamevalEntry(11621, "PATTERN_PUMPKIN_DUMMY", "pattern_pumpkin_dummy", "objtypes"),
            new GamevalEntry(11622, "PATTERN_WATERMELON_SLICE_DUMMY", "pattern_watermelon_slice_dummy", "objtypes"),
            new GamevalEntry(11623, "PATTERN_ONION_DUMMY", "pattern_onion_dummy", "objtypes"),
            new GamevalEntry(11624, "PATTERN_HUNTING_DESERT_FEATHER_DUMMY", "pattern_hunting_desert_feather_dummy", "objtypes"),
            new GamevalEntry(11625, "PATTERN_TUNA_DUMMY", "pattern_tuna_dummy", "objtypes"),
            new GamevalEntry(11626, "PATTERN_PIRATEHOOK_DUMMY", "pattern_piratehook_dummy", "objtypes"),
            new GamevalEntry(11627, "PATTERN_CAPE_OF_LEGENDS_DUMMY", "pattern_cape_of_legends_dummy", "objtypes"),
            new GamevalEntry(11628, "PATTERN_PLAIN_PIZZA_DUMMY", "Ava's device", "objtypes"),
            new GamevalEntry(11629, "PATTERN_KNIFE_DUMMY", "pattern_knife_dummy", "objtypes"),
            new GamevalEntry(11630, "PATTERN_BROODOOMASK_POISON_DUMMY", "pattern_broodoomask_poison_dummy", "objtypes"),
            new GamevalEntry(11631, "PATTERN_ADAMANT_PLATELEGS_DUMMY", "pattern_adamant_platelegs_dummy", "objtypes"),
            new GamevalEntry(11632, "PATTERN_LADERHOSEN_HAT_DUMMY", "pattern_laderhosen_hat_dummy", "objtypes"),
            new GamevalEntry(11633, "PATTERN_XBOWS_CROSSBOW_ADAMANTITE_DUMMY", "pattern_xbows_crossbow_adamantite_dummy", "objtypes"),
            new GamevalEntry(11634, "PATTERN_BANNANA_DUMMY", "pattern_bannana_dummy", "objtypes"),
            new GamevalEntry(11635, "PATTERN_IRON_SQ_SHIELD_DUMMY", "pattern_iron_sq_shield_dummy", "objtypes"),
            new GamevalEntry(11636, "PATTERN_WOODEN_SHIELD_DUMMY", "pattern_wooden_shield_dummy", "objtypes"),
            new GamevalEntry(11637, "PATTERN_JESTER_HAT_DUMMY", "pattern_jester_hat_dummy", "objtypes"),
            new GamevalEntry(11638, "PATTERN_ANTIDRAGONBREATHSHIELD_CLEAN_DUMMY", "pattern_antidragonbreathshield_clean_dummy", "objtypes"),
            new GamevalEntry(11639, "PATTERN_HUNDRED_KNIFE_DUMMY", "pattern_hundred_knife_dummy", "objtypes"),
            new GamevalEntry(11640, "PATTERN_REWARD", "Book of knowledge", "objtypes"),
            new GamevalEntry(11641, "PATTERN_COCKTAIL_SHAKER_DUMMY", "pattern_cocktail_shaker_dummy", "objtypes"),
            new GamevalEntry(11642, "PATTERN_RUNE_PLATEBODY_DUMMY", "pattern_rune_platebody_dummy", "objtypes"),
            new GamevalEntry(11643, "PATTERN_MIND_TALISMAN_DUMMY", "pattern_mind_talisman_dummy", "objtypes"),
            new GamevalEntry(11644, "PATTERN_SGG_DUMMY", "pattern_sgg_dummy", "objtypes"),
            new GamevalEntry(11645, "PATTERN_ONION_SEED_4_DUMMY", "Spinning wheel", "objtypes"),
            new GamevalEntry(11646, "PATTERN_UNLIT_CANDLE_DUMMY", "Anvil", "objtypes"),
            new GamevalEntry(11647, "PATTERN_FRUIT_BLAST_DUMMY", "Bank chest", "objtypes"),
            new GamevalEntry(11648, "PATTERN_BRONZE_PLATEBODY_DUMMY", "pattern_bronze_platebody_dummy", "objtypes"),
            new GamevalEntry(11649, "PATTERN_LEMON_SLICES_DUMMY", "pattern_lemon_slices_dummy", "objtypes"),
            new GamevalEntry(11650, "PATTERN_SLAYER_BOOTS_DUMMY", "pattern_slayer_boots_dummy", "objtypes"),
            new GamevalEntry(11651, "PATTERN_SOS_BOOTS2_DUMMY", "pattern_sos_boots2_dummy", "objtypes"),
            new GamevalEntry(11652, "PATTERN_EMERALD_RING_DUMMY", "pattern_emerald_ring_dummy", "objtypes"),
            new GamevalEntry(11653, "PATTERN_EMPTY_VIAL_DUMMY", "pattern_empty_vial_dummy", "objtypes"),
            new GamevalEntry(11654, "PATTERN_MACRO_FROG_MASK_DUMMY", "pattern_macro_frog_mask_dummy", "objtypes"),
            new GamevalEntry(11655, "CERT_BOOK_OF_ASTROLOGY", "Xb", "objtypes"),
            new GamevalEntry(11656, "OBSERVATORY_GLASSBLOWING_BOOK", "Glassblowing book", "objtypes"),
            new GamevalEntry(11657, "CERT_OBSERVATORY_GLASSBLOWING_BOOK", "cert_observatory_glassblowing_book", "objtypes"),
            new GamevalEntry(11658, "QIP_OBS_TELE_BOOK", "qip_obs_tele_book", "objtypes"),
            new GamevalEntry(11659, "QIP_OBS_TELE_BOOK2", "qip_obs_tele_book2", "objtypes"),
            new GamevalEntry(11660, "QIP_OBS_TELE_BOOK3", "qip_obs_tele_book3", "objtypes"),
            new GamevalEntry(11661, "QIP_OBS_LENS_BOOK", "qip_obs_lens_book", "objtypes"),
            new GamevalEntry(11662, "QIP_OBS_STAR_BOOK", "qip_obs_star_book", "objtypes"),
            new GamevalEntry(11663, "GAME_PEST_MAGE_HELM", "Void mage helm", "objtypes"),
            new GamevalEntry(11664, "GAME_PEST_ARCHER_HELM", "Void ranger helm", "objtypes"),
            new GamevalEntry(11665, "GAME_PEST_MELEE_HELM", "Void melee helm", "objtypes"),
            new GamevalEntry(11666, "PEST_SEAL_8", "Void seal(8)", "objtypes"),
            new GamevalEntry(11667, "PEST_SEAL_7", "Void seal(7)", "objtypes"),
            new GamevalEntry(11668, "PEST_SEAL_6", "Void seal(6)", "objtypes"),
            new GamevalEntry(11669, "PEST_SEAL_5", "Void seal(5)", "objtypes"),
            new GamevalEntry(11670, "PEST_SEAL_4", "Void seal(4)", "objtypes"),
            new GamevalEntry(11671, "PEST_SEAL_3", "Void seal(3)", "objtypes"),
            new GamevalEntry(11672, "PEST_SEAL_2", "Void seal(2)", "objtypes"),
            new GamevalEntry(11673, "PEST_SEAL_1", "Void seal(1)", "objtypes"),
            new GamevalEntry(11674, "DUMMY_GAME_PEST_MAGE_HELM", "Null", "objtypes"),
            new GamevalEntry(11675, "DUMMY_GAME_PEST_ARCHER_HELM", "Null", "objtypes"),
            new GamevalEntry(11676, "DUMMY_GAME_PEST_MELEE_HELM", "Null", "objtypes"),
            new GamevalEntry(11677, "GODWARS_DWARVEN_BOOK", "Explorer's notes", "objtypes"),
            new GamevalEntry(11678, "KR_CLUE_ARMOUR", "Black knight helm", "objtypes"),
            new GamevalEntry(11679, "KR_REWARD_LAMP", "Antique lamp", "objtypes"),
            new GamevalEntry(11680, "KR_CLUE_FORM", "Address form", "objtypes"),
            new GamevalEntry(11681, "KR_CLUE_NOTE", "Scrap paper", "objtypes"),
            new GamevalEntry(11682, "KR_HAIRCLIP", "Hair clip", "objtypes"),
            new GamevalEntry(11683, "KR_LOCKPICK_BLUE", "kr_lockpick_blue", "objtypes"),
            new GamevalEntry(11684, "KR_LOCKPICK_RED", "kr_lockpick_red", "objtypes"),
            new GamevalEntry(11685, "KR_LOCKPICK_GREEN", "kr_lockpick_green", "objtypes"),
            new GamevalEntry(11686, "FAKE_FIRERUNE", "Fire rune", "objtypes"),
            new GamevalEntry(11687, "FAKE_WATERRUNE", "Water rune", "objtypes"),
            new GamevalEntry(11688, "FAKE_AIRRUNE", "Air rune", "objtypes"),
            new GamevalEntry(11689, "FAKE_EARTHRUNE", "Earth rune", "objtypes"),
            new GamevalEntry(11690, "FAKE_MINDRUNE", "Mind rune", "objtypes"),
            new GamevalEntry(11691, "FAKE_BODYRUNE", "Body rune", "objtypes"),
            new GamevalEntry(11692, "FAKE_DEATHRUNE", "Death rune", "objtypes"),
            new GamevalEntry(11693, "FAKE_NATURERUNE", "Nature rune", "objtypes"),
            new GamevalEntry(11694, "FAKE_CHAOSRUNE", "Chaos rune", "objtypes"),
            new GamevalEntry(11695, "FAKE_LAWRUNE", "Law rune", "objtypes"),
            new GamevalEntry(11696, "FAKE_COSMICRUNE", "Cosmic rune", "objtypes"),
            new GamevalEntry(11697, "FAKE_BLOODRUNE", "Blood rune", "objtypes"),
            new GamevalEntry(11698, "FAKE_SOULRUNE", "Soul rune", "objtypes"),
            new GamevalEntry(11699, "FAKE_ASTRALRUNE", "Astral rune", "objtypes"),
            new GamevalEntry(11700, "FAKE_BRONZE_ARROW", "Bronze arrow", "objtypes"),
            new GamevalEntry(11701, "FAKE_IRON_ARROW", "Iron arrow", "objtypes"),
            new GamevalEntry(11702, "FAKE_STEEL_ARROW", "Steel arrow", "objtypes"),
            new GamevalEntry(11703, "FAKE_MITHRIL_ARROW", "Mithril arrow", "objtypes"),
            new GamevalEntry(11704, "RAW_MACRO_PHEASANT", "Raw pheasant", "objtypes"),
            new GamevalEntry(11705, "BEACHPARTY_BOXINGGLOVES_YELLOW", "Beach boxing gloves", "objtypes"),
            new GamevalEntry(11706, "BEACHPARTY_BOXINGGLOVES_PURPLE", "Beach boxing gloves", "objtypes"),
            new GamevalEntry(11707, "GOBLINRAID_WARHAMMER", "Cursed goblin hammer", "objtypes"),
            new GamevalEntry(11708, "GOBLINRAID_BOW", "Cursed goblin bow", "objtypes"),
            new GamevalEntry(11709, "GOBLINRAID_STAFF", "Cursed goblin staff", "objtypes"),
            new GamevalEntry(11710, "NZONE_ANTIDRAGONSHIELD", "Anti-dragon shield (nz)", "objtypes"),
            new GamevalEntry(11711, "NZONE_FAIRYSECATEURS", "Magic secateurs (nz)", "objtypes"),
            new GamevalEntry(11712, "NZONE_CHAOSRUNE", "Chaos rune (nz)", "objtypes"),
            new GamevalEntry(11713, "NZONE_DEATHRUNE", "Death rune (nz)", "objtypes"),
            new GamevalEntry(11714, "NZONE_BLOODRUNE", "Blood rune (nz)", "objtypes"),
            new GamevalEntry(11715, "NZONE_AIRRUNE", "Air rune (nz)", "objtypes"),
            new GamevalEntry(11716, "NZONE_WATERRUNE", "Water rune (nz)", "objtypes"),
            new GamevalEntry(11717, "NZONE_EARTHRUNE", "Earth rune (nz)", "objtypes"),
            new GamevalEntry(11718, "NZONE_FIRERUNE", "Fire rune (nz)", "objtypes"),
            new GamevalEntry(11719, "NZONE_RUNE_PICKAXE", "Rune pickaxe (nz)", "objtypes"),
            new GamevalEntry(11720, "NZONE_MITHRIL_PICKAXE", "Mithril pickaxe (nz)", "objtypes"),
            new GamevalEntry(11721, "NZONE_IRON_PICKAXE", "Iron pickaxe (nz)", "objtypes"),
            new GamevalEntry(11722, "NZONE4DOSE2RANGERSPOTION", "Super ranging (4)", "objtypes"),
            new GamevalEntry(11723, "NZONE3DOSE2RANGERSPOTION", "Super ranging (3)", "objtypes"),
            new GamevalEntry(11724, "NZONE2DOSE2RANGERSPOTION", "Super ranging (2)", "objtypes"),
            new GamevalEntry(11725, "NZONE1DOSE2RANGERSPOTION", "Super ranging (1)", "objtypes"),
            new GamevalEntry(11726, "NZONE4DOSE2MAGICPOTION", "Super magic potion (4)", "objtypes"),
            new GamevalEntry(11727, "NZONE3DOSE2MAGICPOTION", "Super magic potion (3)", "objtypes"),
            new GamevalEntry(11728, "NZONE2DOSE2MAGICPOTION", "Super magic potion (2)", "objtypes"),
            new GamevalEntry(11729, "NZONE1DOSE2MAGICPOTION", "Super magic potion (1)", "objtypes"),
            new GamevalEntry(11730, "NZONE4DOSEOVERLOADPOTION", "Overload (4)", "objtypes"),
            new GamevalEntry(11731, "NZONE3DOSEOVERLOADPOTION", "Overload (3)", "objtypes"),
            new GamevalEntry(11732, "NZONE2DOSEOVERLOADPOTION", "Overload (2)", "objtypes"),
            new GamevalEntry(11733, "NZONE1DOSEOVERLOADPOTION", "Overload (1)", "objtypes"),
            new GamevalEntry(11734, "NZONE4DOSEABSORPTIONPOTION", "Absorption (4)", "objtypes"),
            new GamevalEntry(11735, "NZONE3DOSEABSORPTIONPOTION", "Absorption (3)", "objtypes"),
            new GamevalEntry(11736, "NZONE2DOSEABSORPTIONPOTION", "Absorption (2)", "objtypes"),
            new GamevalEntry(11737, "NZONE1DOSEABSORPTIONPOTION", "Absorption (1)", "objtypes"),
            new GamevalEntry(11738, "NZONE_HERBBOX", "Herb box", "objtypes"),
            new GamevalEntry(11739, "NZONE_HERBBOX_OPENED", "Open herb box", "objtypes"),
            new GamevalEntry(11740, "NZONE_REDIRECTION", "Scroll of redirection", "objtypes"),
            new GamevalEntry(11741, "NZONE_TELETAB_RIMMINGTON", "Rimmington teleport", "objtypes"),
            new GamevalEntry(11742, "NZONE_TELETAB_TAVERLEY", "Taverley teleport", "objtypes"),
            new GamevalEntry(11743, "NZONE_TELETAB_POLLNIVNEACH", "Pollnivneach teleport", "objtypes"),
            new GamevalEntry(11744, "NZONE_TELETAB_RELLEKKA", "Rellekka teleport", "objtypes"),
            new GamevalEntry(11745, "NZONE_TELETAB_BRIMHAVEN", "Brimhaven teleport", "objtypes"),
            new GamevalEntry(11746, "NZONE_TELETAB_YANILLE", "Yanille teleport", "objtypes"),
            new GamevalEntry(11747, "NZONE_TELETAB_TROLLHEIM", "Trollheim teleport", "objtypes"),
            new GamevalEntry(11748, "NZONE_CRYSTAL_BOW_NEW", "New crystal bow (i)", "objtypes"),
            new GamevalEntry(11749, "NZONE_CRYSTAL_BOW_1000", "Crystal bow full (i)", "objtypes"),
            new GamevalEntry(11750, "NZONE_CRYSTAL_BOW_900", "Crystal bow 9/10 (i)", "objtypes"),
            new GamevalEntry(11751, "NZONE_CRYSTAL_BOW_800", "Crystal bow 8/10 (i)", "objtypes"),
            new GamevalEntry(11752, "NZONE_CRYSTAL_BOW_700", "Crystal bow 7/10 (i)", "objtypes"),
            new GamevalEntry(11753, "NZONE_CRYSTAL_BOW_600", "Crystal bow 6/10 (i)", "objtypes"),
            new GamevalEntry(11754, "NZONE_CRYSTAL_BOW_500", "Crystal bow 5/10 (i)", "objtypes"),
            new GamevalEntry(11755, "NZONE_CRYSTAL_BOW_400", "Crystal bow 4/10 (i)", "objtypes"),
            new GamevalEntry(11756, "NZONE_CRYSTAL_BOW_300", "Crystal bow 3/10 (i)", "objtypes"),
            new GamevalEntry(11757, "NZONE_CRYSTAL_BOW_200", "Crystal bow 2/10 (i)", "objtypes"),
            new GamevalEntry(11758, "NZONE_CRYSTAL_BOW_100", "Crystal bow 1/10 (i)", "objtypes"),
            new GamevalEntry(11759, "NZONE_CRYSTAL_SHIELD_NEW", "New crystal shield (i)", "objtypes"),
            new GamevalEntry(11760, "NZONE_CRYSTAL_SHIELD_1000", "Crystal shield full (i)", "objtypes"),
            new GamevalEntry(11761, "NZONE_CRYSTAL_SHIELD_900", "Crystal shield 9/10 (i)", "objtypes"),
            new GamevalEntry(11762, "NZONE_CRYSTAL_SHIELD_800", "Crystal shield 8/10 (i)", "objtypes"),
            new GamevalEntry(11763, "NZONE_CRYSTAL_SHIELD_700", "Crystal shield 7/10 (i)", "objtypes"),
            new GamevalEntry(11764, "NZONE_CRYSTAL_SHIELD_600", "Crystal shield 6/10 (i)", "objtypes"),
            new GamevalEntry(11765, "NZONE_CRYSTAL_SHIELD_500", "Crystal shield 5/10 (i)", "objtypes"),
            new GamevalEntry(11766, "NZONE_CRYSTAL_SHIELD_400", "Crystal shield 4/10 (i)", "objtypes"),
            new GamevalEntry(11767, "NZONE_CRYSTAL_SHIELD_300", "Crystal shield 3/10 (i)", "objtypes"),
            new GamevalEntry(11768, "NZONE_CRYSTAL_SHIELD_200", "Crystal shield 2/10 (i)", "objtypes"),
            new GamevalEntry(11769, "NZONE_CRYSTAL_SHIELD_100", "Crystal shield 1/10 (i)", "objtypes"),
            new GamevalEntry(11770, "NZONE_SEER_RING", "l ? T Seers ring (i)", "objtypes"),
            new GamevalEntry(11771, "NZONE_RANGER_RING", "v p L Archers ring (i)", "objtypes"),
            new GamevalEntry(11772, "NZONE_WARRIOR_RING", "Warrior ring (i)", "objtypes"),
            new GamevalEntry(11773, "NZONE_BERZERKER_RING", "Berserker ring (i)", "objtypes"),
            new GamevalEntry(11774, "NZONE_BLACK_MASK_10", "Black mask (10) (i)", "objtypes"),
            new GamevalEntry(11775, "NZONE_BLACK_MASK_9", "Black mask (9) (i)", "objtypes"),
            new GamevalEntry(11776, "NZONE_BLACK_MASK_8", "Black mask (8) (i)", "objtypes"),
            new GamevalEntry(11777, "NZONE_BLACK_MASK_7", "Black mask (7) (i)", "objtypes"),
            new GamevalEntry(11778, "NZONE_BLACK_MASK_6", "Black mask (6) (i)", "objtypes"),
            new GamevalEntry(11779, "NZONE_BLACK_MASK_5", "Black mask (5) (i)", "objtypes"),
            new GamevalEntry(11780, "NZONE_BLACK_MASK_4", "Black mask (4) (i)", "objtypes"),
            new GamevalEntry(11781, "NZONE_BLACK_MASK_3", "Black mask (3) (i)", "objtypes"),
            new GamevalEntry(11782, "NZONE_BLACK_MASK_2", "Black mask (2) (i)", "objtypes"),
            new GamevalEntry(11783, "NZONE_BLACK_MASK_1", "Black mask (1) (i)", "objtypes"),
            new GamevalEntry(11784, "NZONE_BLACK_MASK", "Black mask (i)", "objtypes"),
            new GamevalEntry(11785, "ACB", "Armadyl crossbow", "objtypes"),
            new GamevalEntry(11786, "CERT_ACB", "cert_acb", "objtypes"),
            new GamevalEntry(11787, "STEAM_BATTLESTAFF", "Steam battlestaff", "objtypes"),
            new GamevalEntry(11788, "CERT_STEAM_BATTLESTAFF", "cert_steam_battlestaff", "objtypes"),
            new GamevalEntry(11789, "MYSTIC_STEAM_BATTLESTAFF", "Mystic steam staff", "objtypes"),
            new GamevalEntry(11790, "CERT_MYSTIC_STEAM_BATTLESTAFF", "cert_mystic_steam_battlestaff", "objtypes"),
            new GamevalEntry(11791, "SOTD", "Staff of the dead", "objtypes"),
            new GamevalEntry(11792, "CERT_SOTD", "cert_sotd", "objtypes"),
            new GamevalEntry(11793, "AGILITY_STRENGTH", "Agility strength", "objtypes"),
            new GamevalEntry(11802, "AGS", "Armadyl godsword", "objtypes"),
            new GamevalEntry(11803, "CERT_AGS", "cert_ags", "objtypes"),
            new GamevalEntry(11804, "BGS", "Bandos godsword", "objtypes"),
            new GamevalEntry(11805, "CERT_BGS", "cert_bgs", "objtypes"),
            new GamevalEntry(11806, "SGS", "Saradomin godsword", "objtypes"),
            new GamevalEntry(11807, "CERT_SGS", "cert_sgs", "objtypes"),
            new GamevalEntry(11808, "ZGS", "Zamorak godsword", "objtypes"),
            new GamevalEntry(11809, "CERT_ZGS", "cert_zgs", "objtypes"),
            new GamevalEntry(11810, "GODWARS_GODSWORD_HILT_ARMADYL", "Armadyl hilt", "objtypes"),
            new GamevalEntry(11811, "CERT_GODWARS_GODSWORD_HILT_ARMADYL", "cert_godwars_godsword_hilt_armadyl", "objtypes"),
            new GamevalEntry(11812, "GODWARS_GODSWORD_HILT_BANDOS", "Bandos hilt", "objtypes"),
            new GamevalEntry(11813, "CERT_GODWARS_GODSWORD_HILT_BANDOS", "cert_godwars_godsword_hilt_bandos", "objtypes"),
            new GamevalEntry(11814, "GODWARS_GODSWORD_HILT_SARADOMIN", "Saradomin hilt", "objtypes"),
            new GamevalEntry(11815, "CERT_GODWARS_GODSWORD_HILT_SARADOMIN", "cert_godwars_godsword_hilt_saradomin", "objtypes"),
            new GamevalEntry(11816, "GODWARS_GODSWORD_HILT_ZAMORAK", "Zamorak hilt", "objtypes"),
            new GamevalEntry(11817, "CERT_GODWARS_GODSWORD_HILT_ZAMORAK", "cert_godwars_godsword_hilt_zamorak", "objtypes"),
            new GamevalEntry(11818, "GODWARS_GODSWORD_BLADE1", "Godsword shard 1", "objtypes"),
            new GamevalEntry(11819, "CERT_GODWARS_GODSWORD_BLADE1", "cert_godwars_godsword_blade1", "objtypes"),
            new GamevalEntry(11820, "GODWARS_GODSWORD_BLADE2", "Godsword shard 2", "objtypes"),
            new GamevalEntry(11821, "CERT_GODWARS_GODSWORD_BLADE2", "cert_godwars_godsword_blade2", "objtypes"),
            new GamevalEntry(11822, "GODWARS_GODSWORD_BLADE3", "Godsword shard 3", "objtypes"),
            new GamevalEntry(11823, "CERT_GODWARS_GODSWORD_BLADE3", "cert_godwars_godsword_blade3", "objtypes"),
            new GamevalEntry(11824, "ZAMORAK_SPEAR", "Zamorakian spear", "objtypes"),
            new GamevalEntry(11825, "CERT_ZAMORAK_SPEAR", "cert_zamorak_spear", "objtypes"),
            new GamevalEntry(11826, "ARMADYL_HELMET", "A Armadyl helmet", "objtypes"),
            new GamevalEntry(11827, "CERT_ARMADYL_HELMET", "cert_armadyl_helmet", "objtypes"),
            new GamevalEntry(11828, "ARMADYL_CHESTPLATE", "Armadyl chestplate", "objtypes"),
            new GamevalEntry(11829, "CERT_ARMADYL_CHESTPLATE", "cert_armadyl_chestplate", "objtypes"),
            new GamevalEntry(11830, "ARMADYL_SKIRT", "Armadyl chainskirt", "objtypes"),
            new GamevalEntry(11831, "CERT_ARMADYL_SKIRT", "cert_armadyl_skirt", "objtypes"),
            new GamevalEntry(11832, "BANDOS_CHESTPLATE", "Bandos chestplate", "objtypes"),
            new GamevalEntry(11833, "CERT_BANDOS_CHESTPLATE", "cert_bandos_chestplate", "objtypes"),
            new GamevalEntry(11834, "BANDOS_SKIRT", "Bandos tassets", "objtypes"),
            new GamevalEntry(11835, "CERT_BANDOS_SKIRT", "cert_bandos_skirt", "objtypes"),
            new GamevalEntry(11836, "BANDOS_BOOTS", "Bandos boots", "objtypes"),
            new GamevalEntry(11837, "CERT_BANDOS_BOOTS", "cert_bandos_boots", "objtypes"),
            new GamevalEntry(11838, "SARADOMIN_SWORD", "Saradomin sword", "objtypes"),
            new GamevalEntry(11839, "CERT_SARADOMIN_SWORD", "cert_saradomin_sword", "objtypes"),
            new GamevalEntry(11840, "DRAGON_BOOTS", "Dragon boots", "objtypes"),
            new GamevalEntry(11841, "CERT_DRAGON_BOOTS", "cert_dragon_boots", "objtypes"),
            new GamevalEntry(11842, "GODWARS_KNIGHTS_SCROLL_CLOSED", "Knight's notes", "objtypes"),
            new GamevalEntry(11843, "GODWARS_KNIGHTS_SCROLL_OPEN", "Knight's notes", "objtypes"),
            new GamevalEntry(11844, "GODWARS_SPIRITUAL_MAGE_INV", "godwars_spiritual_mage_inv", "objtypes"),
            new GamevalEntry(11845, "GODWARS_SPIRITUAL_RANGER_INV", "godwars_spiritual_ranger_inv", "objtypes"),
            new GamevalEntry(11846, "GODWARS_SPIRITUAL_WARRIOR_INV", "godwars_spiritual_warrior_inv", "objtypes"),
            new GamevalEntry(11847, "HALLOWEENMASK_BLACK", "Black h'ween mask", "objtypes"),
            new GamevalEntry(11848, "THANKSGIVING_TURKEY", "Rancid turkey", "objtypes"),
            new GamevalEntry(11849, "GRACE", "Mark of grace", "objtypes"),
            new GamevalEntry(11850, "GRACEFUL_HOOD", "Graceful hood", "objtypes"),
            new GamevalEntry(11851, "GRACEFUL_HOOD_WORN", "Graceful hood", "objtypes"),
            new GamevalEntry(11852, "GRACEFUL_CAPE", "Graceful cape", "objtypes"),
            new GamevalEntry(11853, "GRACEFUL_CAPE_WORN", "Graceful cape", "objtypes"),
            new GamevalEntry(11854, "GRACEFUL_TOP", "Graceful top", "objtypes"),
            new GamevalEntry(11855, "GRACEFUL_TOP_WORN", "Graceful top", "objtypes"),
            new GamevalEntry(11856, "GRACEFUL_LEGS", "Graceful legs", "objtypes"),
            new GamevalEntry(11857, "GRACEFUL_LEGS_WORN", "Graceful legs", "objtypes"),
            new GamevalEntry(11858, "GRACEFUL_GLOVES", "Graceful gloves", "objtypes"),
            new GamevalEntry(11859, "GRACEFUL_GLOVES_WORN", "Graceful gloves", "objtypes"),
            new GamevalEntry(11860, "GRACEFUL_BOOTS", "Graceful boots", "objtypes"),
            new GamevalEntry(11861, "GRACEFUL_BOOTS_WORN", "Graceful boots", "objtypes"),
            new GamevalEntry(11862, "BLACK_PARTYHAT", "Black partyhat", "objtypes"),
            new GamevalEntry(11863, "RAINBOW_PARTYHAT", "Rainbow partyhat", "objtypes"),
            new GamevalEntry(11864, "SLAYER_HELM", "Slayer helmet", "objtypes"),
            new GamevalEntry(11865, "SLAYER_HELM_I", "Slayer helmet (i)", "objtypes"),
            new GamevalEntry(11866, "SLAYER_RING_8", "Slayer ring (8)", "objtypes"),
            new GamevalEntry(11867, "SLAYER_RING_7", "Slayer ring (7)", "objtypes"),
            new GamevalEntry(11868, "SLAYER_RING_6", "Slayer ring (6)", "objtypes"),
            new GamevalEntry(11869, "SLAYER_RING_5", "Slayer ring (5)", "objtypes"),
            new GamevalEntry(11870, "SLAYER_RING_4", "Slayer ring (4)", "objtypes"),
            new GamevalEntry(11871, "SLAYER_RING_3", "Slayer ring (3)", "objtypes"),
            new GamevalEntry(11872, "SLAYER_RING_2", "Slayer ring (2)", "objtypes"),
            new GamevalEntry(11873, "SLAYER_RING_1", "Slayer ring (1)", "objtypes"),
            new GamevalEntry(11874, "SLAYER_BROAD_ARROWHEAD", "Broad arrowheads", "objtypes"),
            new GamevalEntry(11875, "SLAYER_BROAD_BOLT", "Broad bolts", "objtypes"),
            new GamevalEntry(11876, "SLAYER_BROAD_BOLT_UNFINISHED", "Unfinished broad bolts", "objtypes"),
            new GamevalEntry(11877, "PACK_VIAL_EMPTY", "Empty vial pack", "objtypes"),
            new GamevalEntry(11878, "CERT_PACK_VIAL_EMPTY", "cert_pack_vial_empty", "objtypes"),
            new GamevalEntry(11879, "PACK_VIAL_WATER", "Water-filled vial pack", "objtypes"),
            new GamevalEntry(11880, "CERT_PACK_VIAL_WATER", "cert_pack_vial_water", "objtypes"),
            new GamevalEntry(11881, "PACK_FEATHER", "Feather pack", "objtypes"),
            new GamevalEntry(11882, "CERT_PACK_FEATHER", "cert_pack_feather", "objtypes"),
            new GamevalEntry(11883, "PACK_FISHING_BAIT", "Bait pack", "objtypes"),
            new GamevalEntry(11884, "CERT_PACK_FISHING_BAIT", "cert_pack_fishing_bait", "objtypes"),
            new GamevalEntry(11885, "PACK_SLAYER_BROAD_ARROWHEAD", "Broad arrowhead pack", "objtypes"),
            new GamevalEntry(11886, "CERT_PACK_SLAYER_BROAD_ARROWHEAD", "cert_pack_slayer_broad_arrowhead", "objtypes"),
            new GamevalEntry(11887, "PACK_SLAYER_BROAD_BOLT_UNFINISHED", "Unfinished broad bolt pack", "objtypes"),
            new GamevalEntry(11888, "CERT_PACK_SLAYER_BROAD_BOLT_UNFINISHED", "cert_pack_slayer_broad_bolt_unfinished", "objtypes"),
            new GamevalEntry(11889, "ZAMORAK_HASTA", "Zamorakian hasta", "objtypes"),
            new GamevalEntry(11890, "CERT_ZAMORAK_HASTA", "cert_zamorak_hasta", "objtypes"),
            new GamevalEntry(11891, "SARADOMIN_REWARD_BANNER", "Saradomin banner", "objtypes"),
            new GamevalEntry(11892, "ZAMORAK_REWARD_BANNER", "Zamorak banner", "objtypes"),
            new GamevalEntry(11893, "CASTLEWARS_ARMOUR_SKIRT", "Decorative armour", "objtypes"),
            new GamevalEntry(11894, "CASTLEWARS_ARMOUR_SKIRT_2", "Decorative armour", "objtypes"),
            new GamevalEntry(11895, "CASTLEWARS_ARMOUR_SKIRT_3", "Decorative armour", "objtypes"),
            new GamevalEntry(11896, "CASTLEWARS_MAGE_TOP", "Decorative armour", "objtypes"),
            new GamevalEntry(11897, "CASTLEWARS_MAGE_LEGS", "Decorative armour", "objtypes"),
            new GamevalEntry(11898, "CASTLEWARS_MAGE_HAT", "Decorative armour", "objtypes"),
            new GamevalEntry(11899, "CASTLEWARS_RANGE_TOP", "Decorative armour", "objtypes"),
            new GamevalEntry(11900, "CASTLEWARS_RANGE_LEGS", "Decorative armour", "objtypes"),
            new GamevalEntry(11901, "CASTLEWARS_RANGE_QUIVER", "Decorative armour", "objtypes"),
            new GamevalEntry(11902, "LEAFBLADED_SWORD", "Leaf-bladed sword", "objtypes"),
            new GamevalEntry(11903, "CERT_LEAFBLADED_SWORD", "cert_leafbladed_sword", "objtypes"),
            new GamevalEntry(11904, "SLAYER_CAVE_DIARY", "Entomologist's diary", "objtypes"),
            new GamevalEntry(11905, "TOTS", "Trident of the seas (full)", "objtypes"),
            new GamevalEntry(11906, "CERT_TOTS", "cert_tots", "objtypes"),
            new GamevalEntry(11907, "TOTS_CHARGED", "Trident of the seas", "objtypes"),
            new GamevalEntry(11908, "TOTS_UNCHARGED", "Uncharged trident", "objtypes"),
            new GamevalEntry(11909, "CERT_TOTS_UNCHARGED", "cert_tots_uncharged", "objtypes"),
            new GamevalEntry(11910, "CHOCOLATE_STRAWBERRY", "Chocolate strawberry", "objtypes"),
            new GamevalEntry(11911, "CERT_CHOCOLATE_STRAWBERRY", "cert_chocolate_strawberry", "objtypes"),
            new GamevalEntry(11912, "BOX_OF_CHOC_STRAWBERRIES", "Box of chocolate strawberries", "objtypes"),
            new GamevalEntry(11913, "CERT_BOX_OF_CHOC_STRAWBERRIES", "cert_box_of_choc_strawberries", "objtypes"),
            new GamevalEntry(11914, "BOX_OF_CHOC_STRAWBERRIES_OPEN", "Box of chocolate strawberries", "objtypes"),
            new GamevalEntry(11915, "CERT_BOX_OF_CHOC_STRAWBERRIES_OPEN", "cert_box_of_choc_strawberries_open", "objtypes"),
            new GamevalEntry(11916, "OS_BIRTHDAY_CAKE_SLICE", "Slice of birthday cake", "objtypes"),
            new GamevalEntry(11917, "CERT_OS_BIRTHDAY_CAKE_SLICE", "Slice of birthday cake", "objtypes"),
            new GamevalEntry(11918, "OS_BIRTHDAY_PRESENT", "Birthday present", "objtypes"),
            new GamevalEntry(11919, "COW_MASK", "Cow mask", "objtypes"),
            new GamevalEntry(11920, "DRAGON_PICKAXE", "Dragon pickaxe", "objtypes"),
            new GamevalEntry(11921, "CERT_DRAGON_PICKAXE", "cert_dragon_pickaxe", "objtypes"),
            new GamevalEntry(11922, "POT_BONEMEAL_LAVADRAGON", "Lava dragon bonemeal", "objtypes"),
            new GamevalEntry(11923, "MACRO_BROKEN_DRAGON_PICKAXE", "Broken pickaxe", "objtypes"),
            new GamevalEntry(11924, "MALEDICTION_WARD", "Malediction ward", "objtypes"),
            new GamevalEntry(11925, "CERT_MALEDICTION_WARD", "cert_malediction_ward", "objtypes"),
            new GamevalEntry(11926, "ODIUM_WARD", "Odium ward", "objtypes"),
            new GamevalEntry(11927, "CERT_ODIUM_WARD", "cert_odium_ward", "objtypes"),
            new GamevalEntry(11928, "ODIUM_SHARD1", "Odium shard 1", "objtypes"),
            new GamevalEntry(11929, "ODIUM_SHARD2", "Odium shard 2", "objtypes"),
            new GamevalEntry(11930, "ODIUM_SHARD3", "Odium shard 3", "objtypes"),
            new GamevalEntry(11931, "MALEDICTION_SHARD1", "Malediction shard 1", "objtypes"),
            new GamevalEntry(11932, "MALEDICTION_SHARD2", "Malediction shard 2", "objtypes"),
            new GamevalEntry(11933, "MALEDICTION_SHARD3", "Malediction shard 3", "objtypes"),
            new GamevalEntry(11934, "RAW_DARK_CRAB", "Raw dark crab", "objtypes"),
            new GamevalEntry(11935, "CERT_RAW_DARK_CRAB", "cert_raw_dark_crab", "objtypes"),
            new GamevalEntry(11936, "DARK_CRAB", "Dark crab", "objtypes"),
            new GamevalEntry(11937, "CERT_DARK_CRAB", "cert_dark_crab", "objtypes"),
            new GamevalEntry(11938, "BURNT_DARK_CRAB", "Burnt dark crab", "objtypes"),
            new GamevalEntry(11939, "CERT_BURNT_DARK_CRAB", "cert_burnt_dark_crab", "objtypes"),
            new GamevalEntry(11940, "WILDERNESS_FISHING_BAIT", "A( ?M) Dark fishing bait", "objtypes"),
            new GamevalEntry(11941, "LOOTING_BAG", "Looting bag", "objtypes"),
            new GamevalEntry(11942, "ECUMENICAL_KEY", "Ecumenical key", "objtypes"),
            new GamevalEntry(11943, "LAVA_DRAGON_BONES", "Lava dragon bones", "objtypes"),
            new GamevalEntry(11944, "CERT_LAVA_DRAGON_BONES", "cert_lava_dragon_bones", "objtypes"),
            new GamevalEntry(11945, "CERT_ODIUM_SHARD1", "cert_odium_shard1", "objtypes"),
            new GamevalEntry(11946, "CERT_ODIUM_SHARD2", "cert_odium_shard2", "objtypes"),
            new GamevalEntry(11947, "CERT_ODIUM_SHARD3", "cert_odium_shard3", "objtypes"),
            new GamevalEntry(11948, "CERT_MALEDICTION_SHARD1", "cert_malediction_shard1", "objtypes"),
            new GamevalEntry(11949, "CERT_MALEDICTION_SHARD2", "cert_malediction_shard2", "objtypes"),
            new GamevalEntry(11950, "CERT_MALEDICTION_SHARD3", "cert_malediction_shard3", "objtypes"),
            new GamevalEntry(11951, "_4DOSE2ANTIDRAGON", "Extended antifire(4)", "objtypes"),
            new GamevalEntry(11952, "CERT_4DOSE2ANTIDRAGON", "cert_4dose2antidragon", "objtypes"),
            new GamevalEntry(11953, "_3DOSE2ANTIDRAGON", "Extended antifire(3)", "objtypes"),
            new GamevalEntry(11954, "CERT_3DOSE2ANTIDRAGON", "cert_3dose2antidragon", "objtypes"),
            new GamevalEntry(11955, "_2DOSE2ANTIDRAGON", "Extended antifire(2)", "objtypes"),
            new GamevalEntry(11956, "CERT_2DOSE2ANTIDRAGON", "cert_2dose2antidragon", "objtypes"),
            new GamevalEntry(11957, "_1DOSE2ANTIDRAGON", "Extended antifire(1)", "objtypes"),
            new GamevalEntry(11958, "CERT_1DOSE2ANTIDRAGON", "cert_1dose2antidragon", "objtypes"),
            new GamevalEntry(11959, "CHINCHOMPA_BLACK", "Black chinchompa", "objtypes"),
            new GamevalEntry(11960, "BRUTAL_2DOSE2ANTIDRAGON", "Extended antifire mix(2)", "objtypes"),
            new GamevalEntry(11961, "CERT_BRUTAL_2DOSE2ANTIDRAGON", "cert_brutal_2dose2antidragon", "objtypes"),
            new GamevalEntry(11962, "BRUTAL_1DOSE2ANTIDRAGON", "Extended antifire mix(1)", "objtypes"),
            new GamevalEntry(11963, "CERT_BRUTAL_1DOSE2ANTIDRAGON", "cert_brutal_1dose2antidragon", "objtypes"),
            new GamevalEntry(11964, "TRAIL_AMULET_OF_GLORY_6", "Amulet of glory (t6)", "objtypes"),
            new GamevalEntry(11965, "CERT_TRAIL_AMULET_OF_GLORY_6", "cert_trail_amulet_of_glory_6", "objtypes"),
            new GamevalEntry(11966, "TRAIL_AMULET_OF_GLORY_5", "Amulet of glory (t5)", "objtypes"),
            new GamevalEntry(11967, "CERT_TRAIL_AMULET_OF_GLORY_5", "cert_trail_amulet_of_glory_5", "objtypes"),
            new GamevalEntry(11968, "JEWL_NECKLACE_OF_SKILLS_6", "Skills necklace(6)", "objtypes"),
            new GamevalEntry(11969, "CERT_JEWL_NECKLACE_OF_SKILLS_6", "cert_jewl_necklace_of_skills_6", "objtypes"),
            new GamevalEntry(11970, "JEWL_NECKLACE_OF_SKILLS_5", "Skills necklace(5)", "objtypes"),
            new GamevalEntry(11971, "CERT_JEWL_NECKLACE_OF_SKILLS_5", "cert_jewl_necklace_of_skills_5", "objtypes"),
            new GamevalEntry(11972, "JEWL_BRACELET_OF_COMBAT_6", "Combat bracelet(6)", "objtypes"),
            new GamevalEntry(11973, "CERT_JEWL_BRACELET_OF_COMBAT_6", "cert_jewl_bracelet_of_combat_6", "objtypes"),
            new GamevalEntry(11974, "JEWL_BRACELET_OF_COMBAT_5", "Combat bracelet(5)", "objtypes"),
            new GamevalEntry(11975, "CERT_JEWL_BRACELET_OF_COMBAT_5", "cert_jewl_bracelet_of_combat_5", "objtypes"),
            new GamevalEntry(11976, "AMULET_OF_GLORY_5", "Amulet of glory(5)", "objtypes"),
            new GamevalEntry(11977, "CERT_AMULET_OF_GLORY_5", "cert_amulet_of_glory_5", "objtypes"),
            new GamevalEntry(11978, "AMULET_OF_GLORY_6", "Amulet of glory(6)", "objtypes"),
            new GamevalEntry(11979, "CERT_AMULET_OF_GLORY_6", "cert_amulet_of_glory_6", "objtypes"),
            new GamevalEntry(11980, "RING_OF_WEALTH_5", "Coin Collection", "objtypes"),
            new GamevalEntry(11981, "CERT_RING_OF_WEALTH_5", "cert_ring_of_wealth_5", "objtypes"),
            new GamevalEntry(11982, "RING_OF_WEALTH_4", "Coin Collection", "objtypes"),
            new GamevalEntry(11983, "CERT_RING_OF_WEALTH_4", "cert_ring_of_wealth_4", "objtypes"),
            new GamevalEntry(11984, "RING_OF_WEALTH_3", "Coin Collection", "objtypes"),
            new GamevalEntry(11985, "CERT_RING_OF_WEALTH_3", "cert_ring_of_wealth_3", "objtypes"),
            new GamevalEntry(11986, "RING_OF_WEALTH_2", "Coin Collection", "objtypes"),
            new GamevalEntry(11987, "CERT_RING_OF_WEALTH_2", "cert_ring_of_wealth_2", "objtypes"),
            new GamevalEntry(11988, "RING_OF_WEALTH_1", "Coin Collection", "objtypes"),
            new GamevalEntry(11989, "CERT_RING_OF_WEALTH_1", "cert_ring_of_wealth_1", "objtypes"),
            new GamevalEntry(11990, "FEDORA", "Fedora", "objtypes"),
            new GamevalEntry(11991, "CERT_FEDORA", "cert_fedora", "objtypes"),
            new GamevalEntry(11992, "LAVA_SCALE", "Lava scale", "objtypes"),
            new GamevalEntry(11993, "CERT_LAVA_SCALE", "cert_lava_scale", "objtypes"),
            new GamevalEntry(11994, "LAVA_SHARD", "Lava scale shard", "objtypes"),
            new GamevalEntry(11995, "CHAOSELEPET", "Pet chaos elemental", "objtypes"),
            new GamevalEntry(11996, "TEAM_LEADER_HELPER", "Holiday tool", "objtypes"),
            new GamevalEntry(11997, "EASTER_HELPER", "ZReanimates a low levelled creature", "objtypes"),
            new GamevalEntry(11998, "SMOKE_BATTLESTAFF", "Smoke battlestaff", "objtypes"),
            new GamevalEntry(11999, "CERT_SMOKE_BATTLESTAFF", "cert_smoke_battlestaff", "objtypes"),
            new GamevalEntry(12000, "MYSTIC_SMOKE_BATTLESTAFF", "Mystic smoke staff", "objtypes"),
            new GamevalEntry(12001, "CERT_MYSTIC_SMOKE_BATTLESTAFF", "cert_mystic_smoke_battlestaff", "objtypes"),
            new GamevalEntry(12002, "OCCULT_NECKLACE", "Occult necklace", "objtypes"),
            new GamevalEntry(12003, "CERT_OCCULT_NECKLACE", "cert_occult_necklace", "objtypes"),
            new GamevalEntry(12004, "KRAKEN_TENTACLE", "Kraken tentacle", "objtypes"),
            new GamevalEntry(12005, "CERT_KRAKEN_TENTACLE", "cert_kraken_tentacle", "objtypes"),
            new GamevalEntry(12006, "ABYSSAL_TENTACLE", "Abyssal tentacle", "objtypes"),
            new GamevalEntry(12007, "JAR_OF_DIRT", "Jar of dirt", "objtypes"),
            new GamevalEntry(12008, "CERT_JAR_OF_DIRT", "cert_jar_of_dirt", "objtypes"),
            new GamevalEntry(12009, "PACK_SOFTCLAY", "Soft clay pack", "objtypes"),
            new GamevalEntry(12010, "CERT_PACK_SOFTCLAY", "Soft clay pack", "objtypes"),
            new GamevalEntry(12011, "PAYDIRT", "Pay-dirt", "objtypes"),
            new GamevalEntry(12012, "MOTHERLODE_NUGGET", "Golden nugget", "objtypes"),
            new GamevalEntry(12013, "MOTHERLODE_REWARD_HAT", "Prospector helmet", "objtypes"),
            new GamevalEntry(12014, "MOTHERLODE_REWARD_TOP", "Prospector jacket", "objtypes"),
            new GamevalEntry(12015, "MOTHERLODE_REWARD_LEGS", "Prospector legs", "objtypes"),
            new GamevalEntry(12016, "MOTHERLODE_REWARD_BOOTS", "Prospector boots", "objtypes"),
            new GamevalEntry(12017, "NZONE_SALVE_AMULET", "Salve amulet(i)", "objtypes"),
            new GamevalEntry(12018, "NZONE_SALVE_AMULET_E", "Salve amulet(ei)", "objtypes"),
            new GamevalEntry(12019, "COAL_BAG", "Coal bag", "objtypes"),
            new GamevalEntry(12020, "GEM_BAG", "Gem bag", "objtypes"),
            new GamevalEntry(12021, "TRAIL_MEDIUM_EMOTE_EXP1", "Clue scroll (medium)", "objtypes"),
            new GamevalEntry(12022, "TRAIL_MEDIUM_EMOTE_EXP1_CASKET", "Casket (medium)", "objtypes"),
            new GamevalEntry(12023, "TRAIL_MEDIUM_EMOTE_EXP2", "Clue scroll (medium)", "objtypes"),
        };
    }

    static Optional<GamevalEntry> byId(int id) {
        for (GamevalEntry entry : entries()) {
            if (entry.id() == id) return Optional.of(entry);
        }
        return Optional.empty();
    }

}
