package net.titan.gamevals.internal;

import java.util.Optional;

import net.titan.gamevals.GamevalEntry;
import net.titan.gamevals.QuestEntry;

final class ItemIDEntries_63 {
    private ItemIDEntries_63() {}

    static GamevalEntry[] entries() {
        return new GamevalEntry[] {
            new GamevalEntry(32338, "ID_32338", "", "objtypes"),
            new GamevalEntry(32339, "BURNT_HALIBUT", "Burnt halibut", "objtypes"),
            new GamevalEntry(32340, "ID_32340", "", "objtypes"),
            new GamevalEntry(32341, "RAW_BLUEFIN", "Raw bluefin", "objtypes"),
            new GamevalEntry(32342, "ID_32342", "", "objtypes"),
            new GamevalEntry(32343, "ID_32343", "", "objtypes"),
            new GamevalEntry(32344, "BLUEFIN", "Bluefin", "objtypes"),
            new GamevalEntry(32345, "ID_32345", "", "objtypes"),
            new GamevalEntry(32346, "ID_32346", "", "objtypes"),
            new GamevalEntry(32347, "BURNT_BLUEFIN", "Burnt bluefin", "objtypes"),
            new GamevalEntry(32348, "ID_32348", "", "objtypes"),
            new GamevalEntry(32349, "RAW_MARLIN", "Raw marlin", "objtypes"),
            new GamevalEntry(32350, "ID_32350", "", "objtypes"),
            new GamevalEntry(32351, "ID_32351", "", "objtypes"),
            new GamevalEntry(32352, "MARLIN", "Marlin", "objtypes"),
            new GamevalEntry(32353, "ID_32353", "", "objtypes"),
            new GamevalEntry(32354, "ID_32354", "", "objtypes"),
            new GamevalEntry(32355, "BURNT_MARLIN", "Burnt marlin", "objtypes"),
            new GamevalEntry(32356, "ID_32356", "", "objtypes"),
            new GamevalEntry(32357, "HADDOCK_EYE", "Haddock eye", "objtypes"),
            new GamevalEntry(32358, "ID_32358", "", "objtypes"),
            new GamevalEntry(32359, "ID_32359", "", "objtypes"),
            new GamevalEntry(32360, "YELLOW_FIN", "Yellow fin", "objtypes"),
            new GamevalEntry(32361, "ID_32361", "", "objtypes"),
            new GamevalEntry(32362, "MARLIN_SCALES", "Marlin scales", "objtypes"),
            new GamevalEntry(32363, "ID_32363", "", "objtypes"),
            new GamevalEntry(32364, "CAMPHOR_CRATE", "Camphor crate", "objtypes"),
            new GamevalEntry(32365, "ID_32365", "", "objtypes"),
            new GamevalEntry(32366, "FISH_CRATE_EMPTY", "Fish crate (empty)", "objtypes"),
            new GamevalEntry(32367, "ID_32367", "", "objtypes"),
            new GamevalEntry(32368, "FISH_CRATE_GIANT_KRILL", "Fish crate (giant krill)", "objtypes"),
            new GamevalEntry(32369, "ID_32369", "", "objtypes"),
            new GamevalEntry(32370, "FISH_CRATE_GIANT_KRILL_32370", "Fish crate (giant krill)", "objtypes"),
            new GamevalEntry(32371, "FISH_CRATE_HADDOCK", "Fish crate (haddock)", "objtypes"),
            new GamevalEntry(32372, "ID_32372", "", "objtypes"),
            new GamevalEntry(32373, "FISH_CRATE_HADDOCK_32373", "Fish crate (haddock)", "objtypes"),
            new GamevalEntry(32374, "FISH_CRATE_YELLOWFIN", "Fish crate (yellowfin)", "objtypes"),
            new GamevalEntry(32375, "ID_32375", "", "objtypes"),
            new GamevalEntry(32376, "FISH_CRATE_YELLOWFIN_32376", "Fish crate (yellowfin)", "objtypes"),
            new GamevalEntry(32377, "FISH_CRATE_HALIBUT", "Fish crate (halibut)", "objtypes"),
            new GamevalEntry(32378, "ID_32378", "", "objtypes"),
            new GamevalEntry(32379, "FISH_CRATE_HALIBUT_32379", "Fish crate (halibut)", "objtypes"),
            new GamevalEntry(32380, "FISH_CRATE_BLUEFIN", "Fish crate (bluefin)", "objtypes"),
            new GamevalEntry(32381, "ID_32381", "", "objtypes"),
            new GamevalEntry(32382, "FISH_CRATE_BLUEFIN_32382", "Fish crate (bluefin)", "objtypes"),
            new GamevalEntry(32383, "FISH_CRATE_MARLIN", "Fish crate (marlin)", "objtypes"),
            new GamevalEntry(32384, "ID_32384", "", "objtypes"),
            new GamevalEntry(32385, "FISH_CRATE_MARLIN_32385", "Fish crate (marlin)", "objtypes"),
            new GamevalEntry(32386, "MEDALLION_OF_THE_DEEP", "Medallion of the deep", "objtypes"),
            new GamevalEntry(32387, "ID_32387", "", "objtypes"),
            new GamevalEntry(32388, "MEDALLION_FRAGMENT", "Medallion fragment", "objtypes"),
            new GamevalEntry(32389, "MEDALLION_FRAGMENT_32389", "Medallion fragment", "objtypes"),
            new GamevalEntry(32390, "MEDALLION_FRAGMENT_32390", "Medallion fragment", "objtypes"),
            new GamevalEntry(32391, "MEDALLION_FRAGMENT_32391", "Medallion fragment", "objtypes"),
            new GamevalEntry(32392, "MEDALLION_FRAGMENT_32392", "Medallion fragment", "objtypes"),
            new GamevalEntry(32393, "MEDALLION_FRAGMENT_32393", "Medallion fragment", "objtypes"),
            new GamevalEntry(32394, "MEDALLION_FRAGMENT_32394", "Medallion fragment", "objtypes"),
            new GamevalEntry(32395, "MEDALLION_FRAGMENT_32395", "Medallion fragment", "objtypes"),
            new GamevalEntry(32396, "WATERLOGGED_JOURNAL", "Waterlogged journal", "objtypes"),
            new GamevalEntry(32397, "ID_32397", "", "objtypes"),
            new GamevalEntry(32398, "SAILORS_AMULET_INERT", "Sailors' amulet (inert)", "objtypes"),
            new GamevalEntry(32399, "THE_PANDEMONIUM_32399", "The Pandemonium", "objtypes"),
            new GamevalEntry(32400, "ID_32400", "", "objtypes"),
            new GamevalEntry(32401, "SALVAGING_STATION_SCHEMATIC", "Salvaging station schematic", "objtypes"),
            new GamevalEntry(32402, "GALE_CATCHER_SCHEMATIC", "Gale catcher schematic", "objtypes"),
            new GamevalEntry(32403, "ETERNAL_BRAZIER_SCHEMATIC", "Eternal brazier schematic", "objtypes"),
            new GamevalEntry(32404, "DRAGON_SALVAGING_HOOK_SCHEMATIC", "Dragon salvaging hook schematic", "objtypes"),
            new GamevalEntry(32405, "ROSEWOOD_CARGO_HOLD_SCHEMATIC", "Rosewood cargo hold schematic", "objtypes"),
            new GamevalEntry(32406, "DRAGON_CANNON_SCHEMATIC", "Dragon cannon schematic", "objtypes"),
            new GamevalEntry(32407, "ROSEWOOD_HULL_SCHEMATIC", "Rosewood hull schematic", "objtypes"),
            new GamevalEntry(32408, "ROSEWOOD_COTTON_SAILS_SCHEMATIC", "Rosewood & cotton sails schematic", "objtypes"),
            new GamevalEntry(32409, "DRAGON_HELM_SCHEMATIC", "Dragon helm schematic", "objtypes"),
            new GamevalEntry(32410, "DRAGON_KEEL_SCHEMATIC", "Dragon keel schematic", "objtypes"),
            new GamevalEntry(32411, "SMALL_KEY_THE_PANDEMONIUM", "Small key (the pandemonium)", "objtypes"),
            new GamevalEntry(32412, "SMALL_KEY_THE_ONYX_CREST", "Small key (the onyx crest)", "objtypes"),
            new GamevalEntry(32413, "SMALL_KEY_TEAR_OF_THE_SOUL", "Small key (tear of the soul)", "objtypes"),
            new GamevalEntry(32414, "SMALL_KEY_YNYSDAIL", "Small key (ynysdail)", "objtypes"),
            new GamevalEntry(32415, "SMALL_KEY_MINOTAURS_REST", "Small key (minotaurs' rest)", "objtypes"),
            new GamevalEntry(32416, "SMALL_KEY_BUCCANEERS_HAVEN", "Small key (buccaneers' haven)", "objtypes"),
            new GamevalEntry(32417, "SMALL_KEY_ISLE_OF_BONES", "Small key (isle of bones)", "objtypes"),
            new GamevalEntry(32418, "SMALL_KEY_CHARRED_ISLAND", "Small key (charred island)", "objtypes"),
            new GamevalEntry(32419, "SMALL_KEY_LAGUNA_AURORAE", "Small key (laguna aurorae)", "objtypes"),
            new GamevalEntry(32420, "SMALL_KEY_DRUMSTICK_ISLE", "Small key (drumstick isle)", "objtypes"),
            new GamevalEntry(32421, "LOCKBOX_DIRECTIONS_CHINCHOMPA_ISLAND", "Lockbox directions (chinchompa island)", "objtypes"),
            new GamevalEntry(32422, "LOCKBOX_DIRECTIONS_ANGLERS_RETREAT", "Lockbox directions (anglers' retreat)", "objtypes"),
            new GamevalEntry(32423, "LOCKBOX_DIRECTIONS_BUCCANEERS_HAVEN", "Lockbox directions (buccaneers' haven)", "objtypes"),
            new GamevalEntry(32424, "LOCKBOX_DIRECTIONS_LLEDRITH_ISLAND", "Lockbox directions (lledrith island)", "objtypes"),
            new GamevalEntry(32425, "LOCKBOX_DIRECTIONS_THE_CROWN_JEWEL", "Lockbox directions (the crown jewel)", "objtypes"),
            new GamevalEntry(32426, "LOCKBOX_DIRECTIONS_DEEPFIN_POINT", "Lockbox directions (deepfin point)", "objtypes"),
            new GamevalEntry(32427, "LOCKBOX_DIRECTIONS_SHIMMERING_ATOLL", "Lockbox directions (shimmering atoll)", "objtypes"),
            new GamevalEntry(32428, "LOCKBOX_DIRECTIONS_BRITTLE_ISLE", "Lockbox directions (brittle isle)", "objtypes"),
            new GamevalEntry(32429, "LOCKBOX_DIRECTIONS_SUNBLEAK_ISLAND", "Lockbox directions (sunbleak island)", "objtypes"),
            new GamevalEntry(32430, "LOCKBOX_DIRECTIONS_GRIMSTONE", "Lockbox directions (grimstone)", "objtypes"),
            new GamevalEntry(32431, "BOOK_ABOUT_LIGHTHOUSES", "Book about lighthouses", "objtypes"),
            new GamevalEntry(32432, "CHARRED_KEY", "Charred key", "objtypes"),
            new GamevalEntry(32433, "VOID_ORB", "Void orb", "objtypes"),
            new GamevalEntry(32434, "HOLY_SHEET", "Holy sheet", "objtypes"),
            new GamevalEntry(32435, "CRATE_OF_ADAMANTITE_ORE", "Crate of adamantite ore", "objtypes"),
            new GamevalEntry(32436, "CRATE_OF_CRAB_PASTE", "Crate of crab paste", "objtypes"),
            new GamevalEntry(32437, "CRATE_OF_CRYSTAL_SEEDS", "Crate of crystal seeds", "objtypes"),
            new GamevalEntry(32438, "CRATE_OF_DAGGERS", "Crate of daggers", "objtypes"),
            new GamevalEntry(32439, "CRATE_OF_DYES", "Crate of dyes", "objtypes"),
            new GamevalEntry(32440, "CRATE_OF_FURS", "Crate of furs", "objtypes"),
            new GamevalEntry(32441, "CRATE_OF_JEWELLERY", "Crate of jewellery", "objtypes"),
            new GamevalEntry(32442, "CRATE_OF_LEAD_ORE", "Crate of lead ore", "objtypes"),
            new GamevalEntry(32443, "CRATE_OF_MONKFISH", "Crate of monkfish", "objtypes"),
            new GamevalEntry(32444, "CRATE_OF_NICKEL_ORE", "Crate of nickel ore", "objtypes"),
            new GamevalEntry(32445, "CRATE_OF_PEST_REMAINS", "Crate of pest remains", "objtypes"),
            new GamevalEntry(32446, "CRATE_OF_PLATEBODIES", "Crate of platebodies", "objtypes"),
            new GamevalEntry(32447, "CRATE_OF_SPEARS", "Crate of spears", "objtypes"),
            new GamevalEntry(32448, "CRATE_OF_ARROWTIPS", "Crate of arrowtips", "objtypes"),
            new GamevalEntry(32449, "CRATE_OF_BANANAS", "Crate of bananas", "objtypes"),
            new GamevalEntry(32450, "CRATE_OF_CRYSTAL_SEEDS_32450", "Crate of crystal seeds", "objtypes"),
            new GamevalEntry(32451, "CRATE_OF_FISH", "Crate of fish", "objtypes"),
            new GamevalEntry(32452, "CRATE_OF_FURS_32452", "Crate of furs", "objtypes"),
            new GamevalEntry(32453, "CRATE_OF_GOLD_ORE", "Crate of gold ore", "objtypes"),
            new GamevalEntry(32454, "CRATE_OF_HALBERDS", "Crate of halberds", "objtypes"),
            new GamevalEntry(32455, "CRATE_OF_JEWELLERY_32455", "Crate of jewellery", "objtypes"),
            new GamevalEntry(32456, "CRATE_OF_POISON", "Crate of poison", "objtypes"),
            new GamevalEntry(32457, "CRATE_OF_RABBIT_MEAT", "Crate of rabbit meat", "objtypes"),
            new GamevalEntry(32458, "CRATE_OF_RED_CORAL", "Crate of red coral", "objtypes"),
            new GamevalEntry(32459, "CRATE_OF_RUNES", "Crate of runes", "objtypes"),
            new GamevalEntry(32460, "CRATE_OF_SALAMANDERS", "Crate of salamanders", "objtypes"),
            new GamevalEntry(32461, "CRATE_OF_SAND", "Crate of sand", "objtypes"),
            new GamevalEntry(32462, "CRATE_OF_SILK", "Crate of silk", "objtypes"),
            new GamevalEntry(32463, "CRATE_OF_SPICES", "Crate of spices", "objtypes"),
            new GamevalEntry(32464, "CRATE_OF_BEAR_MEAT", "Crate of bear meat", "objtypes"),
            new GamevalEntry(32465, "CRATE_OF_BEER", "Crate of beer", "objtypes"),
            new GamevalEntry(32466, "CRATE_OF_CACTI", "Crate of cacti", "objtypes"),
            new GamevalEntry(32467, "CRATE_OF_CAMPHOR_LOGS", "Crate of camphor logs", "objtypes"),
            new GamevalEntry(32468, "CRATE_OF_COMPOST", "Crate of compost", "objtypes"),
            new GamevalEntry(32469, "CRATE_OF_FISH_32469", "Crate of fish", "objtypes"),
            new GamevalEntry(32470, "CRATE_OF_GEMS", "Crate of gems", "objtypes"),
            new GamevalEntry(32471, "CRATE_OF_IRON_BARS", "Crate of iron bars", "objtypes"),
            new GamevalEntry(32472, "CRATE_OF_JEWELLERY_32472", "Crate of jewellery", "objtypes"),
            new GamevalEntry(32473, "CRATE_OF_MACHINERY_PARTS", "Crate of machinery parts", "objtypes"),
            new GamevalEntry(32474, "CRATE_OF_RUM", "Crate of rum", "objtypes"),
            new GamevalEntry(32475, "CRATE_OF_SANDSTONE", "Crate of sandstone", "objtypes"),
            new GamevalEntry(32476, "CRATE_OF_SILVER_ORE", "Crate of silver ore", "objtypes"),
            new GamevalEntry(32477, "CRATE_OF_SPICES_32477", "Crate of spices", "objtypes"),
            new GamevalEntry(32478, "CRATE_OF_VODKA", "Crate of vodka", "objtypes"),
            new GamevalEntry(32479, "CRATE_OF_WINE", "Crate of wine", "objtypes"),
            new GamevalEntry(32480, "CRATE_OF_GOLD_BARS", "Crate of gold bars", "objtypes"),
            new GamevalEntry(32481, "CRATE_OF_SECRET_STUFF", "Crate of secret stuff", "objtypes"),
            new GamevalEntry(32482, "CRATE_OF_ARROWTIPS_32482", "Crate of arrowtips", "objtypes"),
            new GamevalEntry(32483, "CRATE_OF_BAIT", "Crate of bait", "objtypes"),
            new GamevalEntry(32484, "CRATE_OF_FEATHERS", "Crate of feathers", "objtypes"),
            new GamevalEntry(32485, "CRATE_OF_BANANAS_32485", "Crate of bananas", "objtypes"),
            new GamevalEntry(32486, "CRATE_OF_COCONUTS", "Crate of coconuts", "objtypes"),
            new GamevalEntry(32487, "CRATE_OF_FURS_32487", "Crate of furs", "objtypes"),
            new GamevalEntry(32488, "CRATE_OF_GLASSMAKING_SUPPLIES", "Crate of glassmaking supplies", "objtypes"),
            new GamevalEntry(32489, "CRATE_OF_GOLD_ORE_32489", "Crate of gold ore", "objtypes"),
            new GamevalEntry(32490, "CRATE_OF_GROG", "Crate of grog", "objtypes"),
            new GamevalEntry(32491, "CRATE_OF_JAVELINS", "Crate of javelins", "objtypes"),
            new GamevalEntry(32492, "CRATE_OF_JEWELLERY_32492", "Crate of jewellery", "objtypes"),
            new GamevalEntry(32493, "CRATE_OF_KARAMBWANS", "Crate of karambwans", "objtypes"),
            new GamevalEntry(32494, "CRATE_OF_PINEAPPLES", "Crate of pineapples", "objtypes"),
            new GamevalEntry(32495, "CRATE_OF_POTATOES", "Crate of potatoes", "objtypes"),
            new GamevalEntry(32496, "CRATE_OF_SEEDS", "Crate of seeds", "objtypes"),
            new GamevalEntry(32497, "CRATE_OF_SILK_32497", "Crate of silk", "objtypes"),
            new GamevalEntry(32498, "CRATE_OF_SILVER_ORE_32498", "Crate of silver ore", "objtypes"),
            new GamevalEntry(32499, "CRATE_OF_VIALS", "Crate of vials", "objtypes"),
            new GamevalEntry(32500, "CRATE_OF_ASTRAL_RUNES", "Crate of astral runes", "objtypes"),
            new GamevalEntry(32501, "CRATE_OF_BOOKS", "Crate of books", "objtypes"),
            new GamevalEntry(32502, "CRATE_OF_CORAL", "Crate of coral", "objtypes"),
            new GamevalEntry(32503, "CRATE_OF_FISH_32503", "Crate of fish", "objtypes"),
            new GamevalEntry(32504, "CRATE_OF_FRUIT", "Crate of fruit", "objtypes"),
            new GamevalEntry(32505, "CRATE_OF_GEMS_32505", "Crate of gems", "objtypes"),
            new GamevalEntry(32506, "CRATE_OF_HISTORICAL_ARTEFACTS", "Crate of historical artefacts", "objtypes"),
            new GamevalEntry(32507, "CRATE_OF_NICKEL_ORE_32507", "Crate of nickel ore", "objtypes"),
            new GamevalEntry(32508, "CRATE_OF_ORANGES", "Crate of oranges", "objtypes"),
            new GamevalEntry(32509, "CRATE_OF_ORES", "Crate of ores", "objtypes"),
            new GamevalEntry(32510, "CRATE_OF_PINEAPPLES_32510", "Crate of pineapples", "objtypes"),
            new GamevalEntry(32511, "CRATE_OF_RED_CORAL_32511", "Crate of red coral", "objtypes"),
            new GamevalEntry(32512, "CRATE_OF_RUNES_32512", "Crate of runes", "objtypes"),
            new GamevalEntry(32513, "CRATE_OF_SEEDS_32513", "Crate of seeds", "objtypes"),
            new GamevalEntry(32514, "CRATE_OF_SHIP_PARTS", "Crate of ship parts", "objtypes"),
            new GamevalEntry(32515, "CRATE_OF_SPICES_32515", "Crate of spices", "objtypes"),
            new GamevalEntry(32516, "CRATE_OF_STAFFS", "Crate of staffs", "objtypes"),
            new GamevalEntry(32517, "CRATE_OF_TOKENS", "Crate of tokens", "objtypes"),
            new GamevalEntry(32518, "CRATE_OF_VEGETABLES", "Crate of vegetables", "objtypes"),
            new GamevalEntry(32519, "CRATE_OF_ARROWTIPS_32519", "Crate of arrowtips", "objtypes"),
            new GamevalEntry(32520, "CRATE_OF_BEAR_MEAT_32520", "Crate of bear meat", "objtypes"),
            new GamevalEntry(32521, "CRATE_OF_BEER_32521", "Crate of beer", "objtypes"),
            new GamevalEntry(32522, "CRATE_OF_DAGGERS_32522", "Crate of daggers", "objtypes"),
            new GamevalEntry(32523, "CRATE_OF_FISH_32523", "Crate of fish", "objtypes"),
            new GamevalEntry(32524, "CRATE_OF_GEMS_32524", "Crate of gems", "objtypes"),
            new GamevalEntry(32525, "CRATE_OF_KHALI_BREWS", "Crate of khali brews", "objtypes"),
            new GamevalEntry(32526, "CRATE_OF_PEG_LEGS", "Crate of peg legs", "objtypes"),
            new GamevalEntry(32527, "CRATE_OF_PLATEBODIES_32527", "Crate of platebodies", "objtypes"),
            new GamevalEntry(32528, "CRATE_OF_RUM_32528", "Crate of rum", "objtypes"),
            new GamevalEntry(32529, "CRATE_OF_SCIMITARS", "Crate of scimitars", "objtypes"),
            new GamevalEntry(32530, "CRATE_OF_SHIP_PARTS_32530", "Crate of ship parts", "objtypes"),
            new GamevalEntry(32531, "CRATE_OF_SWORDS", "Crate of swords", "objtypes"),
            new GamevalEntry(32532, "CRATE_OF_ALPACA_WOOL", "Crate of alpaca wool", "objtypes"),
            new GamevalEntry(32533, "CRATE_OF_CAMPHOR_LOGS_32533", "Crate of camphor logs", "objtypes"),
            new GamevalEntry(32534, "CRATE_OF_FABRICS", "Crate of fabrics", "objtypes"),
            new GamevalEntry(32535, "CRATE_OF_FRUIT_32535", "Crate of fruit", "objtypes"),
            new GamevalEntry(32536, "CRATE_OF_FURS_32536", "Crate of furs", "objtypes"),
            new GamevalEntry(32537, "CRATE_OF_GRANITE", "Crate of granite", "objtypes"),
            new GamevalEntry(32538, "CRATE_OF_JAVELINS_32538", "Crate of javelins", "objtypes"),
            new GamevalEntry(32539, "CRATE_OF_LOGS", "Crate of logs", "objtypes"),
            new GamevalEntry(32540, "CRATE_OF_MACHINERY_PARTS_32540", "Crate of machinery parts", "objtypes"),
            new GamevalEntry(32541, "CRATE_OF_MAHOGANY_LOGS", "Crate of mahogany logs", "objtypes"),
            new GamevalEntry(32542, "CRATE_OF_PEST_REMAINS_32542", "Crate of pest remains", "objtypes"),
            new GamevalEntry(32543, "CRATE_OF_PICKAXES", "Crate of pickaxes", "objtypes"),
            new GamevalEntry(32544, "CRATE_OF_PLANKS", "Crate of planks", "objtypes"),
            new GamevalEntry(32545, "CRATE_OF_SUQAH_HIDES", "Crate of suqah hides", "objtypes"),
            new GamevalEntry(32546, "CRATE_OF_WARHAMMERS", "Crate of warhammers", "objtypes"),
            new GamevalEntry(32547, "CRATE_OF_BANANAS_32547", "Crate of bananas", "objtypes"),
            new GamevalEntry(32548, "CRATE_OF_BARLEY", "Crate of barley", "objtypes"),
            new GamevalEntry(32549, "CRATE_OF_SAND_32549", "Crate of sand", "objtypes"),
            new GamevalEntry(32550, "CRATE_OF_ADAMANTITE_ORE_32550", "Crate of adamantite ore", "objtypes"),
            new GamevalEntry(32551, "CRATE_OF_FISH_32551", "Crate of fish", "objtypes"),
            new GamevalEntry(32552, "CRATE_OF_FRUIT_32552", "Crate of fruit", "objtypes"),
            new GamevalEntry(32553, "CRATE_OF_IRON_ORE", "Crate of iron ore", "objtypes"),
            new GamevalEntry(32554, "CRATE_OF_MONKFISH_32554", "Crate of monkfish", "objtypes"),
            new GamevalEntry(32555, "CRATE_OF_ONIONS", "Crate of onions", "objtypes"),
            new GamevalEntry(32556, "CRATE_OF_PLANKS_32556", "Crate of planks", "objtypes"),
            new GamevalEntry(32557, "CRATE_OF_SWORDS_32557", "Crate of swords", "objtypes"),
            new GamevalEntry(32558, "CRATE_OF_WARHAMMERS_32558", "Crate of warhammers", "objtypes"),
            new GamevalEntry(32559, "CRATE_OF_YAK_HAIR", "Crate of yak hair", "objtypes"),
            new GamevalEntry(32560, "CRATE_OF_FISH_32560", "Crate of fish", "objtypes"),
            new GamevalEntry(32561, "CRATE_OF_LEAD_ORE_32561", "Crate of lead ore", "objtypes"),
            new GamevalEntry(32562, "CRATE_OF_ROPE", "Crate of rope", "objtypes"),
            new GamevalEntry(32563, "CRATE_OF_XERICIAN_FABRICS", "Crate of xerician fabrics", "objtypes"),
            new GamevalEntry(32564, "CRATE_OF_FISH_32564", "Crate of fish", "objtypes"),
            new GamevalEntry(32565, "CRATE_OF_FLAX", "Crate of flax", "objtypes"),
            new GamevalEntry(32566, "CRATE_OF_LOGS_32566", "Crate of logs", "objtypes"),
            new GamevalEntry(32567, "CRATE_OF_BEAR_MEAT_32567", "Crate of bear meat", "objtypes"),
            new GamevalEntry(32568, "CRATE_OF_FISH_32568", "Crate of fish", "objtypes"),
            new GamevalEntry(32569, "CRATE_OF_FURS_32569", "Crate of furs", "objtypes"),
            new GamevalEntry(32570, "CRATE_OF_GEMS_32570", "Crate of gems", "objtypes"),
            new GamevalEntry(32571, "CRATE_OF_KEBBIT_FUR", "Crate of kebbit fur", "objtypes"),
            new GamevalEntry(32572, "CRATE_OF_MEAT", "Crate of meat", "objtypes"),
            new GamevalEntry(32573, "CRATE_OF_ORES_32573", "Crate of ores", "objtypes"),
            new GamevalEntry(32574, "CRATE_OF_SECRET_THINGS", "Crate of secret things", "objtypes"),
            new GamevalEntry(32575, "CRATE_OF_SWORDS_32575", "Crate of swords", "objtypes"),
            new GamevalEntry(32576, "CRATE_OF_VEGETABLES_32576", "Crate of vegetables", "objtypes"),
            new GamevalEntry(32577, "CRATE_OF_WINE_32577", "Crate of wine", "objtypes"),
            new GamevalEntry(32578, "CRATE_OF_ANTELOPE_FUR", "Crate of antelope fur", "objtypes"),
            new GamevalEntry(32579, "CRATE_OF_BERRIES", "Crate of berries", "objtypes"),
            new GamevalEntry(32580, "CRATE_OF_COAL", "Crate of coal", "objtypes"),
            new GamevalEntry(32581, "CRATE_OF_CRYSTAL_SEEDS_32581", "Crate of crystal seeds", "objtypes"),
            new GamevalEntry(32582, "CRATE_OF_FISH_32582", "Crate of fish", "objtypes"),
            new GamevalEntry(32583, "CRATE_OF_FURS_32583", "Crate of furs", "objtypes"),
            new GamevalEntry(32584, "CRATE_OF_KEBBIT_FUR_32584", "Crate of kebbit fur", "objtypes"),
            new GamevalEntry(32585, "CRATE_OF_LOGS_32585", "Crate of logs", "objtypes"),
            new GamevalEntry(32586, "CRATE_OF_POTIONS", "Crate of potions", "objtypes"),
            new GamevalEntry(32587, "CRATE_OF_RED_CORAL_32587", "Crate of red coral", "objtypes"),
            new GamevalEntry(32588, "CRATE_OF_BANANAS_32588", "Crate of bananas", "objtypes"),
            new GamevalEntry(32589, "CRATE_OF_BEER_GLASSES", "Crate of beer glasses", "objtypes"),
            new GamevalEntry(32590, "CRATE_OF_COCKTAILS", "Crate of cocktails", "objtypes"),
            new GamevalEntry(32591, "CRATE_OF_EYE_PATCHES", "Crate of eye patches", "objtypes"),
            new GamevalEntry(32592, "CRATE_OF_FISH_32592", "Crate of fish", "objtypes"),
            new GamevalEntry(32593, "CRATE_OF_HIGH_IMPORTANCE", "Crate of high importance", "objtypes"),
            new GamevalEntry(32594, "CRATE_OF_HONEY", "Crate of honey", "objtypes"),
            new GamevalEntry(32595, "CRATE_OF_LOBSTERS", "Crate of lobsters", "objtypes"),
            new GamevalEntry(32596, "CRATE_OF_LOGS_32596", "Crate of logs", "objtypes"),
            new GamevalEntry(32597, "CRATE_OF_MAHOGANY_LOGS_32597", "Crate of mahogany logs", "objtypes"),
            new GamevalEntry(32598, "CRATE_OF_MEAT_32598", "Crate of meat", "objtypes"),
            new GamevalEntry(32599, "CRATE_OF_ROTTEN_BANANAS", "Crate of rotten bananas", "objtypes"),
            new GamevalEntry(32600, "CRATE_OF_SECRET_STUFF_32600", "Crate of secret stuff", "objtypes"),
            new GamevalEntry(32601, "CRATE_OF_SHIP_PARTS_32601", "Crate of ship parts", "objtypes"),
            new GamevalEntry(32602, "CRATE_OF_SILK_32602", "Crate of silk", "objtypes"),
            new GamevalEntry(32603, "CRATE_OF_COAL_32603", "Crate of coal", "objtypes"),
            new GamevalEntry(32604, "CRATE_OF_MAHOGANY_LOGS_32604", "Crate of mahogany logs", "objtypes"),
            new GamevalEntry(32605, "CRATE_OF_SAND_32605", "Crate of sand", "objtypes"),
            new GamevalEntry(32606, "CRATE_OF_FABRICS_32606", "Crate of fabrics", "objtypes"),
            new GamevalEntry(32607, "CRATE_OF_FISH_32607", "Crate of fish", "objtypes"),
            new GamevalEntry(32608, "CRATE_OF_FLAX_32608", "Crate of flax", "objtypes"),
            new GamevalEntry(32609, "CRATE_OF_FURS_32609", "Crate of furs", "objtypes"),
            new GamevalEntry(32610, "CRATE_OF_POTIONS_32610", "Crate of potions", "objtypes"),
            new GamevalEntry(32611, "CRATE_OF_VODKA_32611", "Crate of vodka", "objtypes"),
            new GamevalEntry(32612, "CRATE_OF_ANGLER_OUTFIT_PIECES", "Crate of angler outfit pieces", "objtypes"),
            new GamevalEntry(32613, "CRATE_OF_ARROWTIPS_32613", "Crate of arrowtips", "objtypes"),
            new GamevalEntry(32614, "CRATE_OF_BOWS", "Crate of bows", "objtypes"),
            new GamevalEntry(32615, "CRATE_OF_BREAD", "Crate of bread", "objtypes"),
            new GamevalEntry(32616, "CRATE_OF_CHAINBODIES", "Crate of chainbodies", "objtypes"),
            new GamevalEntry(32617, "CRATE_OF_COAL_32617", "Crate of coal", "objtypes"),
            new GamevalEntry(32618, "CRATE_OF_CRAB_PASTE_32618", "Crate of crab paste", "objtypes"),
            new GamevalEntry(32619, "CRATE_OF_FRUIT_32619", "Crate of fruit", "objtypes"),
            new GamevalEntry(32620, "CRATE_OF_GUNPOWDER", "Crate of gunpowder", "objtypes"),
            new GamevalEntry(32621, "CRATE_OF_HERBS", "Crate of herbs", "objtypes"),
            new GamevalEntry(32622, "CRATE_OF_HUASCA", "Crate of huasca", "objtypes"),
            new GamevalEntry(32623, "CRATE_OF_KYATT_TEETH", "Crate of kyatt teeth", "objtypes"),
            new GamevalEntry(32624, "CRATE_OF_PLANKS_32624", "Crate of planks", "objtypes"),
            new GamevalEntry(32625, "CRATE_OF_PLATEBODIES_32625", "Crate of platebodies", "objtypes"),
            new GamevalEntry(32626, "CRATE_OF_RED_CORAL_32626", "Crate of red coral", "objtypes"),
            new GamevalEntry(32627, "CRATE_OF_SCIMITARS_32627", "Crate of scimitars", "objtypes"),
            new GamevalEntry(32628, "CRATE_OF_SECRET_STUFF_32628", "Crate of secret stuff", "objtypes"),
            new GamevalEntry(32629, "CRATE_OF_SPEARS_32629", "Crate of spears", "objtypes"),
            new GamevalEntry(32630, "CRATE_OF_SWAMP_PASTE", "Crate of swamp paste", "objtypes"),
            new GamevalEntry(32631, "CRATE_OF_VODKA_32631", "Crate of vodka", "objtypes"),
            new GamevalEntry(32632, "CRATE_OF_ANTELOPE_MEAT", "Crate of antelope meat", "objtypes"),
            new GamevalEntry(32633, "CRATE_OF_ASTRAL_RUNES_32633", "Crate of astral runes", "objtypes"),
            new GamevalEntry(32634, "CRATE_OF_BOOKS_32634", "Crate of books", "objtypes"),
            new GamevalEntry(32635, "CRATE_OF_CANNONBALLS", "Crate of cannonballs", "objtypes"),
            new GamevalEntry(32636, "CRATE_OF_COAL_32636", "Crate of coal", "objtypes"),
            new GamevalEntry(32637, "CRATE_OF_FABRICS_32637", "Crate of fabrics", "objtypes"),
            new GamevalEntry(32638, "CRATE_OF_FURS_32638", "Crate of furs", "objtypes"),
            new GamevalEntry(32639, "CRATE_OF_GEMS_32639", "Crate of gems", "objtypes"),
            new GamevalEntry(32640, "CRATE_OF_GIN", "Crate of gin", "objtypes"),
            new GamevalEntry(32641, "CRATE_OF_HONEY_32641", "Crate of honey", "objtypes"),
            new GamevalEntry(32642, "CRATE_OF_JEWELLERY_32642", "Crate of jewellery", "objtypes"),
            new GamevalEntry(32643, "CRATE_OF_KEBBIT_FUR_32643", "Crate of kebbit fur", "objtypes"),
            new GamevalEntry(32644, "CRATE_OF_MAHOGANY_LOGS_32644", "Crate of mahogany logs", "objtypes"),
            new GamevalEntry(32645, "CRATE_OF_PLANKS_32645", "Crate of planks", "objtypes"),
            new GamevalEntry(32646, "CRATE_OF_PLATEBODIES_32646", "Crate of platebodies", "objtypes"),
            new GamevalEntry(32647, "CRATE_OF_RED_CORAL_32647", "Crate of red coral", "objtypes"),
            new GamevalEntry(32648, "CRATE_OF_SEEDS_32648", "Crate of seeds", "objtypes"),
            new GamevalEntry(32649, "CRATE_OF_WINE_32649", "Crate of wine", "objtypes"),
            new GamevalEntry(32650, "CRATE_OF_ANTELOPE_FUR_32650", "Crate of antelope fur", "objtypes"),
            new GamevalEntry(32651, "CRATE_OF_BERRIES_32651", "Crate of berries", "objtypes"),
            new GamevalEntry(32652, "CRATE_OF_BOWS_32652", "Crate of bows", "objtypes"),
            new GamevalEntry(32653, "CRATE_OF_CORAL_32653", "Crate of coral", "objtypes"),
            new GamevalEntry(32654, "CRATE_OF_FABRICS_32654", "Crate of fabrics", "objtypes"),
            new GamevalEntry(32655, "CRATE_OF_FISH_32655", "Crate of fish", "objtypes"),
            new GamevalEntry(32656, "CRATE_OF_FLAX_32656", "Crate of flax", "objtypes"),
            new GamevalEntry(32657, "CRATE_OF_FURS_32657", "Crate of furs", "objtypes"),
            new GamevalEntry(32658, "CRATE_OF_GEMS_32658", "Crate of gems", "objtypes"),
            new GamevalEntry(32659, "CRATE_OF_HONEY_32659", "Crate of honey", "objtypes"),
            new GamevalEntry(32660, "CRATE_OF_JEWELLERY_32660", "Crate of jewellery", "objtypes"),
            new GamevalEntry(32661, "CRATE_OF_LOGS_32661", "Crate of logs", "objtypes"),
            new GamevalEntry(32662, "CRATE_OF_MEAT_32662", "Crate of meat", "objtypes"),
            new GamevalEntry(32663, "CRATE_OF_NICKEL_ORE_32663", "Crate of nickel ore", "objtypes"),
            new GamevalEntry(32664, "CRATE_OF_ORES_32664", "Crate of ores", "objtypes"),
            new GamevalEntry(32665, "CRATE_OF_RED_CORAL_32665", "Crate of red coral", "objtypes"),
            new GamevalEntry(32666, "CRATE_OF_RUNES_32666", "Crate of runes", "objtypes"),
            new GamevalEntry(32667, "CRATE_OF_SEEDS_32667", "Crate of seeds", "objtypes"),
            new GamevalEntry(32668, "CRATE_OF_SILK_32668", "Crate of silk", "objtypes"),
            new GamevalEntry(32669, "CRATE_OF_SILVER_ORE_32669", "Crate of silver ore", "objtypes"),
            new GamevalEntry(32670, "CRATE_OF_STAFFS_32670", "Crate of staffs", "objtypes"),
            new GamevalEntry(32671, "CRATE_OF_TEAK_LOGS", "Crate of teak logs", "objtypes"),
            new GamevalEntry(32672, "CRATE_OF_WINE_32672", "Crate of wine", "objtypes"),
            new GamevalEntry(32673, "CRATE_OF_AMULETS", "Crate of amulets", "objtypes"),
            new GamevalEntry(32674, "CRATE_OF_BEER_32674", "Crate of beer", "objtypes"),
            new GamevalEntry(32675, "CRATE_OF_BOOKS_32675", "Crate of books", "objtypes"),
            new GamevalEntry(32676, "CRATE_OF_CACTI_32676", "Crate of cacti", "objtypes"),
            new GamevalEntry(32677, "CRATE_OF_CAMPHOR_LOGS_32677", "Crate of camphor logs", "objtypes"),
            new GamevalEntry(32678, "CRATE_OF_COCONUTS_32678", "Crate of coconuts", "objtypes"),
            new GamevalEntry(32679, "CRATE_OF_FISH_32679", "Crate of fish", "objtypes"),
            new GamevalEntry(32680, "CRATE_OF_FLAX_32680", "Crate of flax", "objtypes"),
            new GamevalEntry(32681, "CRATE_OF_HONEY_32681", "Crate of honey", "objtypes"),
            new GamevalEntry(32682, "CRATE_OF_JEWELLERY_32682", "Crate of jewellery", "objtypes"),
            new GamevalEntry(32683, "CRATE_OF_KEBABS", "Crate of kebabs", "objtypes"),
            new GamevalEntry(32684, "CRATE_OF_LOGS_32684", "Crate of logs", "objtypes"),
            new GamevalEntry(32685, "CRATE_OF_NOTHING_SINISTER", "Crate of nothing sinister", "objtypes"),
            new GamevalEntry(32686, "CRATE_OF_PEST_REMAINS_32686", "Crate of pest remains", "objtypes"),
            new GamevalEntry(32687, "CRATE_OF_RED_CORAL_32687", "Crate of red coral", "objtypes"),
            new GamevalEntry(32688, "CRATE_OF_RUNES_32688", "Crate of runes", "objtypes"),
            new GamevalEntry(32689, "CRATE_OF_SEEDS_32689", "Crate of seeds", "objtypes"),
            new GamevalEntry(32690, "CRATE_OF_SPICES_32690", "Crate of spices", "objtypes"),
            new GamevalEntry(32691, "CRATE_OF_SUNBEAM_ALE", "Crate of sunbeam ale", "objtypes"),
            new GamevalEntry(32692, "CRATE_OF_SWORDS_32692", "Crate of swords", "objtypes"),
            new GamevalEntry(32693, "CRATE_OF_ARROWTIPS_32693", "Crate of arrowtips", "objtypes"),
            new GamevalEntry(32694, "CRATE_OF_CHINCHOMPAS", "Crate of chinchompas", "objtypes"),
            new GamevalEntry(32695, "CRATE_OF_COAL_32695", "Crate of coal", "objtypes"),
            new GamevalEntry(32696, "CRATE_OF_FABRICS_32696", "Crate of fabrics", "objtypes"),
            new GamevalEntry(32697, "CRATE_OF_FISH_32697", "Crate of fish", "objtypes"),
            new GamevalEntry(32698, "CRATE_OF_FRUIT_32698", "Crate of fruit", "objtypes"),
            new GamevalEntry(32699, "CRATE_OF_FURS_32699", "Crate of furs", "objtypes"),
            new GamevalEntry(32700, "CRATE_OF_HERBS_32700", "Crate of herbs", "objtypes"),
            new GamevalEntry(32701, "CRATE_OF_MITHRIL_ORE", "Crate of mithril ore", "objtypes"),
            new GamevalEntry(32702, "CRATE_OF_ORES_32702", "Crate of ores", "objtypes"),
            new GamevalEntry(32703, "CRATE_OF_PLATEBODIES_32703", "Crate of platebodies", "objtypes"),
            new GamevalEntry(32704, "CRATE_OF_SEEDS_32704", "Crate of seeds", "objtypes"),
            new GamevalEntry(32705, "CRATE_OF_SHIELDS", "Crate of shields", "objtypes"),
            new GamevalEntry(32706, "CRATE_OF_SNAKESKIN", "Crate of snakeskin", "objtypes"),
            new GamevalEntry(32707, "CRATE_OF_SWORDS_32707", "Crate of swords", "objtypes"),
            new GamevalEntry(32708, "CRATE_OF_VEGETABLES_32708", "Crate of vegetables", "objtypes"),
            new GamevalEntry(32709, "CRATE_OF_ASTRAL_RUNES_32709", "Crate of astral runes", "objtypes"),
            new GamevalEntry(32710, "CRATE_OF_BOOKS_32710", "Crate of books", "objtypes"),
            new GamevalEntry(32711, "CRATE_OF_CLOTHES", "Crate of clothes", "objtypes"),
            new GamevalEntry(32712, "CRATE_OF_FISH_32712", "Crate of fish", "objtypes"),
            new GamevalEntry(32713, "CRATE_OF_HALBERDS_32713", "Crate of halberds", "objtypes"),
            new GamevalEntry(32714, "CRATE_OF_HERBS_32714", "Crate of herbs", "objtypes"),
            new GamevalEntry(32715, "CRATE_OF_LOGS_32715", "Crate of logs", "objtypes"),
            new GamevalEntry(32716, "CRATE_OF_ORES_32716", "Crate of ores", "objtypes"),
            new GamevalEntry(32717, "CRATE_OF_POTIONS_32717", "Crate of potions", "objtypes"),
            new GamevalEntry(32718, "CRATE_OF_SILK_32718", "Crate of silk", "objtypes"),
            new GamevalEntry(32719, "CRATE_OF_SPICES_32719", "Crate of spices", "objtypes"),
            new GamevalEntry(32720, "CRATE_OF_XERICIAN_FABRICS_32720", "Crate of xerician fabrics", "objtypes"),
            new GamevalEntry(32721, "CRATE_OF_ASTRAL_RUNES_32721", "Crate of astral runes", "objtypes"),
            new GamevalEntry(32722, "CRATE_OF_BATTLEAXES", "Crate of battleaxes", "objtypes"),
            new GamevalEntry(32723, "CRATE_OF_COAL_32723", "Crate of coal", "objtypes"),
            new GamevalEntry(32724, "CRATE_OF_FISH_32724", "Crate of fish", "objtypes"),
            new GamevalEntry(32725, "CRATE_OF_FURS_32725", "Crate of furs", "objtypes"),
            new GamevalEntry(32726, "CRATE_OF_GRANITE_32726", "Crate of granite", "objtypes"),
            new GamevalEntry(32727, "CRATE_OF_HERBS_32727", "Crate of herbs", "objtypes"),
            new GamevalEntry(32728, "CRATE_OF_KARAMBWANS_32728", "Crate of karambwans", "objtypes"),
            new GamevalEntry(32729, "CRATE_OF_ORES_32729", "Crate of ores", "objtypes"),
            new GamevalEntry(32730, "CRATE_OF_PROTECTIVE_CLOTHING", "Crate of protective clothing", "objtypes"),
            new GamevalEntry(32731, "CRATE_OF_RUNES_32731", "Crate of runes", "objtypes"),
            new GamevalEntry(32732, "CRATE_OF_SHIP_PARTS_32732", "Crate of ship parts", "objtypes"),
            new GamevalEntry(32733, "CRATE_OF_SPICES_32733", "Crate of spices", "objtypes"),
            new GamevalEntry(32734, "CRATE_OF_ADAMANTITE_ORE_32734", "Crate of adamantite ore", "objtypes"),
            new GamevalEntry(32735, "CRATE_OF_BEER_32735", "Crate of beer", "objtypes"),
            new GamevalEntry(32736, "CRATE_OF_DRAGON_BITTER", "Crate of dragon bitter", "objtypes"),
            new GamevalEntry(32737, "CRATE_OF_FABRICS_32737", "Crate of fabrics", "objtypes"),
            new GamevalEntry(32738, "CRATE_OF_FISH_32738", "Crate of fish", "objtypes"),
            new GamevalEntry(32739, "CRATE_OF_HALBERDS_32739", "Crate of halberds", "objtypes"),
            new GamevalEntry(32740, "CRATE_OF_LEAD_ORE_32740", "Crate of lead ore", "objtypes"),
            new GamevalEntry(32741, "CRATE_OF_MONKFISH_32741", "Crate of monkfish", "objtypes"),
            new GamevalEntry(32742, "CRATE_OF_PIES", "Crate of pies", "objtypes"),
            new GamevalEntry(32743, "CRATE_OF_PLANKS_32743", "Crate of planks", "objtypes"),
            new GamevalEntry(32744, "CRATE_OF_REDWOOD_LOGS", "Crate of redwood logs", "objtypes"),
            new GamevalEntry(32745, "CRATE_OF_ROPE_32745", "Crate of rope", "objtypes"),
            new GamevalEntry(32746, "CRATE_OF_SHIP_PARTS_32746", "Crate of ship parts", "objtypes"),
            new GamevalEntry(32747, "CRATE_OF_TEAK_LOGS_32747", "Crate of teak logs", "objtypes"),
            new GamevalEntry(32748, "CRATE_OF_WINE_32748", "Crate of wine", "objtypes"),
            new GamevalEntry(32749, "CRATE_OF_CALQUAT", "Crate of calquat", "objtypes"),
            new GamevalEntry(32750, "CRATE_OF_COCKTAILS_32750", "Crate of cocktails", "objtypes"),
            new GamevalEntry(32751, "CRATE_OF_CORAL_32751", "Crate of coral", "objtypes"),
            new GamevalEntry(32752, "CRATE_OF_FISH_32752", "Crate of fish", "objtypes"),
            new GamevalEntry(32753, "CRATE_OF_FISHING_SUPPLIES", "Crate of fishing supplies", "objtypes"),
            new GamevalEntry(32754, "CRATE_OF_JAVELINS_32754", "Crate of javelins", "objtypes"),
            new GamevalEntry(32755, "CRATE_OF_PLANKS_32755", "Crate of planks", "objtypes"),
            new GamevalEntry(32756, "CRATE_OF_RUNES_32756", "Crate of runes", "objtypes"),
            new GamevalEntry(32757, "CRATE_OF_SHIP_PARTS_32757", "Crate of ship parts", "objtypes"),
            new GamevalEntry(32758, "CRATE_OF_BEER_32758", "Crate of beer", "objtypes"),
            new GamevalEntry(32759, "CRATE_OF_FABRICS_32759", "Crate of fabrics", "objtypes"),
            new GamevalEntry(32760, "CRATE_OF_FISH_32760", "Crate of fish", "objtypes"),
            new GamevalEntry(32761, "CRATE_OF_MACES", "Crate of maces", "objtypes"),
            new GamevalEntry(32762, "CRATE_OF_WARHAMMERS_32762", "Crate of warhammers", "objtypes"),
            new GamevalEntry(32763, "CRATE_OF_WINE_32763", "Crate of wine", "objtypes"),
            new GamevalEntry(32764, "CRATE_OF_ARROWTIPS_32764", "Crate of arrowtips", "objtypes"),
            new GamevalEntry(32765, "CRATE_OF_BANANAS_32765", "Crate of bananas", "objtypes"),
            new GamevalEntry(32766, "CRATE_OF_BATTLEAXES_32766", "Crate of battleaxes", "objtypes"),
            new GamevalEntry(32767, "CRATE_OF_CACTI_32767", "Crate of cacti", "objtypes"),
            new GamevalEntry(32768, "CRATE_OF_CORAL_32768", "Crate of coral", "objtypes"),
            new GamevalEntry(32769, "CRATE_OF_GOLD_BARS_32769", "Crate of gold bars", "objtypes"),
            new GamevalEntry(32770, "CRATE_OF_GRANITE_32770", "Crate of granite", "objtypes"),
            new GamevalEntry(32771, "CRATE_OF_MEAT_32771", "Crate of meat", "objtypes"),
            new GamevalEntry(32772, "CRATE_OF_PINEAPPLES_32772", "Crate of pineapples", "objtypes"),
            new GamevalEntry(32773, "CRATE_OF_PLATEBODIES_32773", "Crate of platebodies", "objtypes"),
            new GamevalEntry(32774, "CRATE_OF_RUM_32774", "Crate of rum", "objtypes"),
            new GamevalEntry(32775, "CRATE_OF_SEA_SHELLS", "Crate of sea shells", "objtypes"),
            new GamevalEntry(32776, "CRATE_OF_SPICES_32776", "Crate of spices", "objtypes"),
            new GamevalEntry(32777, "CRATE_OF_STEEL_BARS", "Crate of steel bars", "objtypes"),
            new GamevalEntry(32778, "CRATE_OF_SWAMP_PASTE_32778", "Crate of swamp paste", "objtypes"),
            new GamevalEntry(32779, "CRATE_OF_WAX", "Crate of wax", "objtypes"),
            new GamevalEntry(32780, "CRATE_OF_BANANAS_32780", "Crate of bananas", "objtypes"),
            new GamevalEntry(32781, "CRATE_OF_CACTI_32781", "Crate of cacti", "objtypes"),
            new GamevalEntry(32782, "CRATE_OF_GEMS_32782", "Crate of gems", "objtypes"),
            new GamevalEntry(32783, "CRATE_OF_JAVELINS_32783", "Crate of javelins", "objtypes"),
            new GamevalEntry(32784, "CRATE_OF_JEWELLERY_32784", "Crate of jewellery", "objtypes"),
            new GamevalEntry(32785, "CRATE_OF_LEATHER", "Crate of leather", "objtypes"),
            new GamevalEntry(32786, "CRATE_OF_MEAT_32786", "Crate of meat", "objtypes"),
            new GamevalEntry(32787, "CRATE_OF_NICKEL_ORE_32787", "Crate of nickel ore", "objtypes"),
            new GamevalEntry(32788, "CRATE_OF_PEST_REMAINS_32788", "Crate of pest remains", "objtypes"),
            new GamevalEntry(32789, "CRATE_OF_PINEAPPLES_32789", "Crate of pineapples", "objtypes"),
            new GamevalEntry(32790, "CRATE_OF_POTIONS_32790", "Crate of potions", "objtypes"),
            new GamevalEntry(32791, "CRATE_OF_ROPE_32791", "Crate of rope", "objtypes"),
            new GamevalEntry(32792, "CRATE_OF_SANDSTONE_32792", "Crate of sandstone", "objtypes"),
            new GamevalEntry(32793, "CRATE_OF_SHIELDS_32793", "Crate of shields", "objtypes"),
            new GamevalEntry(32794, "CRATE_OF_CORAL_32794", "Crate of coral", "objtypes"),
            new GamevalEntry(32795, "CRATE_OF_DRAGONHIDE", "Crate of dragonhide", "objtypes"),
            new GamevalEntry(32796, "CRATE_OF_GRANITE_32796", "Crate of granite", "objtypes"),
            new GamevalEntry(32797, "CRATE_OF_HERBS_32797", "Crate of herbs", "objtypes"),
            new GamevalEntry(32798, "CRATE_OF_LOGS_32798", "Crate of logs", "objtypes"),
            new GamevalEntry(32799, "CRATE_OF_MACES_32799", "Crate of maces", "objtypes"),
            new GamevalEntry(32800, "CRATE_OF_ORES_32800", "Crate of ores", "objtypes"),
            new GamevalEntry(32801, "CRATE_OF_PLATEBODIES_32801", "Crate of platebodies", "objtypes"),
            new GamevalEntry(32802, "CRATE_OF_POTIONS_32802", "Crate of potions", "objtypes"),
            new GamevalEntry(32803, "CRATE_OF_RUNES_32803", "Crate of runes", "objtypes"),
            new GamevalEntry(32804, "CRATE_OF_SEEDS_32804", "Crate of seeds", "objtypes"),
            new GamevalEntry(32805, "CRATE_OF_SPEARS_32805", "Crate of spears", "objtypes"),
            new GamevalEntry(32806, "CRATE_OF_WRATH_RUNES", "Crate of wrath runes", "objtypes"),
            new GamevalEntry(32807, "CRATE_OF_SHIP_PARTS_32807", "Crate of ship parts", "objtypes"),
            new GamevalEntry(32808, "CRATE_OF_LOOTY", "Crate of looty", "objtypes"),
            new GamevalEntry(32809, "BULL_SHARK_JAW", "Bull shark jaw", "objtypes"),
            new GamevalEntry(32810, "HAMMERHEAD_SHARK_JAW", "Hammerhead shark jaw", "objtypes"),
            new GamevalEntry(32811, "TIGER_SHARK_JAW", "Tiger shark jaw", "objtypes"),
            new GamevalEntry(32812, "GREAT_WHITE_SHARK_JAW", "Great white shark jaw", "objtypes"),
            new GamevalEntry(32813, "NARWHAL_BLUBBER", "Narwhal blubber", "objtypes"),
            new GamevalEntry(32814, "ORCA_BLUBBER", "Orca blubber", "objtypes"),
            new GamevalEntry(32815, "PYGMY_KRAKEN_TENTACLE", "Pygmy kraken tentacle", "objtypes"),
            new GamevalEntry(32816, "SPINED_KRAKEN_TENTACLE", "Spined kraken tentacle", "objtypes"),
            new GamevalEntry(32817, "ARMOURED_KRAKEN_TENTACLE", "Armoured kraken tentacle", "objtypes"),
            new GamevalEntry(32818, "VAMPYRE_KRAKEN_TENTACLE", "Vampyre kraken tentacle", "objtypes"),
            new GamevalEntry(32819, "EAGLE_RAY_FIN", "Eagle ray fin", "objtypes"),
            new GamevalEntry(32820, "BUTTERFLY_RAY_FIN", "Butterfly ray fin", "objtypes"),
            new GamevalEntry(32821, "STINGRAY_FIN", "Stingray fin", "objtypes"),
            new GamevalEntry(32822, "MANTA_RAY_FIN", "Manta ray fin", "objtypes"),
            new GamevalEntry(32823, "TERN_FEATHER", "Tern feather", "objtypes"),
            new GamevalEntry(32824, "OSPREY_FEATHER", "Osprey feather", "objtypes"),
            new GamevalEntry(32825, "FRIGATEBIRD_FEATHER", "Frigatebird feather", "objtypes"),
            new GamevalEntry(32826, "ALBATROSS_FEATHER", "Albatross feather", "objtypes"),
            new GamevalEntry(32827, "MOGRE_MACE", "Mogre mace", "objtypes"),
            new GamevalEntry(32828, "BULL_SHARK_LIVER", "Bull shark liver", "objtypes"),
            new GamevalEntry(32829, "HAMMERHEAD_SHARK_LIVER", "Hammerhead shark liver", "objtypes"),
            new GamevalEntry(32830, "TIGER_SHARK_LIVER", "Tiger shark liver", "objtypes"),
            new GamevalEntry(32831, "GREAT_WHITE_SHARK_LIVER", "Great white shark liver", "objtypes"),
            new GamevalEntry(32832, "NARWHAL_TUSK", "Narwhal tusk", "objtypes"),
            new GamevalEntry(32833, "ORCA_TEETH", "Orca teeth", "objtypes"),
            new GamevalEntry(32834, "PYGMY_KRAKEN_INK_SAC", "Pygmy kraken ink sac", "objtypes"),
            new GamevalEntry(32835, "SPINED_KRAKEN_INK_SAC", "Spined kraken ink sac", "objtypes"),
            new GamevalEntry(32836, "ARMOURED_KRAKEN_INK_SAC", "Armoured kraken ink sac", "objtypes"),
            new GamevalEntry(32837, "VAMPYRE_KRAKEN_INK_SAC", "Vampyre kraken ink sac", "objtypes"),
            new GamevalEntry(32838, "EAGLE_RAY_SKIN", "Eagle ray skin", "objtypes"),
            new GamevalEntry(32839, "BUTTERFLY_RAY_SKIN", "Butterfly ray skin", "objtypes"),
            new GamevalEntry(32840, "STINGRAY_SKIN", "Stingray skin", "objtypes"),
            new GamevalEntry(32841, "MANTA_RAY_SKIN", "Manta ray skin", "objtypes"),
            new GamevalEntry(32842, "TERN_BEAK", "Tern beak", "objtypes"),
            new GamevalEntry(32843, "OSPREY_BEAK", "Osprey beak", "objtypes"),
            new GamevalEntry(32844, "FRIGATEBIRD_BEAK", "Frigatebird beak", "objtypes"),
            new GamevalEntry(32845, "ALBATROSS_BEAK", "Albatross beak", "objtypes"),
            new GamevalEntry(32846, "MOGRE_HEAD", "Mogre head", "objtypes"),
            new GamevalEntry(32847, "SMALL_SALVAGE", "Small salvage", "objtypes"),
            new GamevalEntry(32848, "ID_32848", "", "objtypes"),
            new GamevalEntry(32849, "FISHY_SALVAGE", "Fishy salvage", "objtypes"),
        };
    }

    static Optional<GamevalEntry> byId(int id) {
        for (GamevalEntry entry : entries()) {
            if (entry.id() == id) return Optional.of(entry);
        }
        return Optional.empty();
    }

}
