package net.titan.gamevals.internal;

import java.util.Optional;

import net.titan.gamevals.GamevalEntry;
import net.titan.gamevals.QuestEntry;

final class ItemIDEntries_26 {
    private ItemIDEntries_26() {}

    static GamevalEntry[] entries() {
        return new GamevalEntry[] {
            new GamevalEntry(13312, "ID_13312", "", "objtypes"),
            new GamevalEntry(13313, "ID_13313", "", "objtypes"),
            new GamevalEntry(13314, "Y_S_U_13314", "?? ? ?", "objtypes"),
            new GamevalEntry(13315, "ID_13315", "", "objtypes"),
            new GamevalEntry(13316, "ID_13316", "", "objtypes"),
            new GamevalEntry(13317, "DEADMAN_S_CHEST", "Deadman's chest", "objtypes"),
            new GamevalEntry(13318, "DEADMAN_S_LEGS", "Deadman's legs", "objtypes"),
            new GamevalEntry(13319, "DEADMAN_S_CAPE", "Deadman's cape", "objtypes"),
            new GamevalEntry(13320, "HERON", "Heron", "objtypes"),
            new GamevalEntry(13321, "ROCK_GOLEM", "Rock golem", "objtypes"),
            new GamevalEntry(13322, "BEAVER", "Beaver", "objtypes"),
            new GamevalEntry(13323, "BABY_CHINCHOMPA", "Baby chinchompa", "objtypes"),
            new GamevalEntry(13324, "BABY_CHINCHOMPA_13324", "Baby chinchompa", "objtypes"),
            new GamevalEntry(13325, "BABY_CHINCHOMPA_13325", "Baby chinchompa", "objtypes"),
            new GamevalEntry(13326, "BABY_CHINCHOMPA_13326", "Baby chinchompa", "objtypes"),
            new GamevalEntry(13327, "ROTTEN_ONION", "Rotten onion", "objtypes"),
            new GamevalEntry(13328, "GREEN_BANNER", "Green banner", "objtypes"),
            new GamevalEntry(13329, "FIRE_MAX_CAPE", "Fire max cape", "objtypes"),
            new GamevalEntry(13330, "FIRE_MAX_HOOD", "Fire max hood", "objtypes"),
            new GamevalEntry(13331, "SARADOMIN_MAX_CAPE", "Saradomin max cape", "objtypes"),
            new GamevalEntry(13332, "SARADOMIN_MAX_HOOD", "Saradomin max hood", "objtypes"),
            new GamevalEntry(13333, "ZAMORAK_MAX_CAPE", "Zamorak max cape", "objtypes"),
            new GamevalEntry(13334, "ZAMORAK_MAX_HOOD", "Zamorak max hood", "objtypes"),
            new GamevalEntry(13335, "GUTHIX_MAX_CAPE", "Guthix max cape", "objtypes"),
            new GamevalEntry(13336, "GUTHIX_MAX_HOOD", "Guthix max hood", "objtypes"),
            new GamevalEntry(13337, "ACCUMULATOR_MAX_CAPE", "Accumulator max cape", "objtypes"),
            new GamevalEntry(13338, "ACCUMULATOR_MAX_HOOD", "Accumulator max hood", "objtypes"),
            new GamevalEntry(13339, "SACRED_EEL", "Sacred eel", "objtypes"),
            new GamevalEntry(13340, "AGILITY_CAPE_13340", "Agility cape", "objtypes"),
            new GamevalEntry(13341, "AGILITY_CAPE_T_13341", "Agility cape(t)", "objtypes"),
            new GamevalEntry(13342, "CRAFTING_GUILD", "?Crafting Guild", "objtypes"),
            new GamevalEntry(13343, "BLACK_SANTA_HAT", "Black santa hat", "objtypes"),
            new GamevalEntry(13344, "INVERTED_SANTA_HAT", "Inverted santa hat", "objtypes"),
            new GamevalEntry(13345, "ANTI_PRESENT", "Anti-present", "objtypes"),
            new GamevalEntry(13346, "PRESENT_13346", "Present", "objtypes"),
            new GamevalEntry(13347, "VIAL_OF_TEARS_EMPTY", "Vial of tears (empty)", "objtypes"),
            new GamevalEntry(13348, "VIAL_OF_TEARS_1", "Vial of tears (1)", "objtypes"),
            new GamevalEntry(13349, "VIAL_OF_TEARS_2", "Vial of tears (2)", "objtypes"),
            new GamevalEntry(13350, "VIAL_OF_TEARS_3", "Vial of tears (3)", "objtypes"),
            new GamevalEntry(13351, "VIAL_OF_TEARS_FULL", "Vial of tears (full)", "objtypes"),
            new GamevalEntry(13352, "VIAL_OF_SORROW", "Vial of sorrow", "objtypes"),
            new GamevalEntry(13353, "GRICOLLER_S_CAN", "Gricoller's can", "objtypes"),
            new GamevalEntry(13354, "LOVAKITE_BAR", "Lovakite bar", "objtypes"),
            new GamevalEntry(13355, "JUNIPER_LOGS", "Juniper logs", "objtypes"),
            new GamevalEntry(13356, "LOVAKITE_ORE", "Lovakite ore", "objtypes"),
            new GamevalEntry(13357, "SHAYZIEN_GLOVES_1", "Shayzien gloves (1)", "objtypes"),
            new GamevalEntry(13358, "SHAYZIEN_BOOTS_1", "Shayzien boots (1)", "objtypes"),
            new GamevalEntry(13359, "SHAYZIEN_HELM_1", "Shayzien helm (1)", "objtypes"),
            new GamevalEntry(13360, "SHAYZIEN_GREAVES_1", "Shayzien greaves (1)", "objtypes"),
            new GamevalEntry(13361, "SHAYZIEN_PLATEBODY_1", "Shayzien platebody (1)", "objtypes"),
            new GamevalEntry(13362, "SHAYZIEN_GLOVES_2", "Shayzien gloves (2)", "objtypes"),
            new GamevalEntry(13363, "SHAYZIEN_BOOTS_2", "Shayzien boots (2)", "objtypes"),
            new GamevalEntry(13364, "SHAYZIEN_HELM_2", "Shayzien helm (2)", "objtypes"),
            new GamevalEntry(13365, "SHAYZIEN_GREAVES_2", "Shayzien greaves (2)", "objtypes"),
            new GamevalEntry(13366, "SHAYZIEN_PLATEBODY_2", "Shayzien platebody (2)", "objtypes"),
            new GamevalEntry(13367, "SHAYZIEN_GLOVES_3", "Shayzien gloves (3)", "objtypes"),
            new GamevalEntry(13368, "SHAYZIEN_BOOTS_3", "Shayzien boots (3)", "objtypes"),
            new GamevalEntry(13369, "SHAYZIEN_HELM_3", "Shayzien helm (3)", "objtypes"),
            new GamevalEntry(13370, "SHAYZIEN_GREAVES_3", "Shayzien greaves (3)", "objtypes"),
            new GamevalEntry(13371, "SHAYZIEN_PLATEBODY_3", "Shayzien platebody (3)", "objtypes"),
            new GamevalEntry(13372, "SHAYZIEN_GLOVES_4", "Shayzien gloves (4)", "objtypes"),
            new GamevalEntry(13373, "SHAYZIEN_BOOTS_4", "Shayzien boots (4)", "objtypes"),
            new GamevalEntry(13374, "SHAYZIEN_HELM_4", "Shayzien helm (4)", "objtypes"),
            new GamevalEntry(13375, "SHAYZIEN_GREAVES_4", "Shayzien greaves (4)", "objtypes"),
            new GamevalEntry(13376, "SHAYZIEN_PLATEBODY_4", "Shayzien platebody (4)", "objtypes"),
            new GamevalEntry(13377, "SHAYZIEN_GLOVES_5", "Shayzien gloves (5)", "objtypes"),
            new GamevalEntry(13378, "SHAYZIEN_BOOTS_5", "Shayzien boots (5)", "objtypes"),
            new GamevalEntry(13379, "SHAYZIEN_HELM_5", "Shayzien helm (5)", "objtypes"),
            new GamevalEntry(13380, "SHAYZIEN_GREAVES_5", "Shayzien greaves (5)", "objtypes"),
            new GamevalEntry(13381, "SHAYZIEN_BODY_5", "Shayzien body (5)", "objtypes"),
            new GamevalEntry(13382, "SHAYZIEN_MEDPACK", "Shayzien medpack", "objtypes"),
            new GamevalEntry(13383, "XERICIAN_FABRIC", "Xerician fabric", "objtypes"),
            new GamevalEntry(13384, "ID_13384", "", "objtypes"),
            new GamevalEntry(13385, "XERICIAN_HAT", "Xerician hat", "objtypes"),
            new GamevalEntry(13386, "ID_13386", "", "objtypes"),
            new GamevalEntry(13387, "XERICIAN_TOP", "Xerician top", "objtypes"),
            new GamevalEntry(13388, "ID_13388", "", "objtypes"),
            new GamevalEntry(13389, "XERICIAN_ROBE", "Xerician robe", "objtypes"),
            new GamevalEntry(13390, "ID_13390", "", "objtypes"),
            new GamevalEntry(13391, "LIZARDMAN_FANG", "Lizardman fang", "objtypes"),
            new GamevalEntry(13392, "XERIC_S_TALISMAN_INERT", "Xeric's talisman (inert)", "objtypes"),
            new GamevalEntry(13393, "XERIC_S_TALISMAN", "Xeric's talisman", "objtypes"),
            new GamevalEntry(13394, "GANG_MEETING_INFO", "Gang meeting info", "objtypes"),
            new GamevalEntry(13395, "INTELLIGENCE", "Intelligence", "objtypes"),
            new GamevalEntry(13396, "TRAINING_MANUAL", "Training manual", "objtypes"),
            new GamevalEntry(13397, "SERVERY_FLOUR", "Servery flour", "objtypes"),
            new GamevalEntry(13398, "SERVERY_PASTRY_DOUGH", "Servery pastry dough", "objtypes"),
            new GamevalEntry(13399, "SERVERY_RAW_MEAT", "Servery raw meat", "objtypes"),
            new GamevalEntry(13400, "SERVERY_DISH", "Servery dish", "objtypes"),
            new GamevalEntry(13401, "SERVERY_PIE_SHELL", "Servery pie shell", "objtypes"),
            new GamevalEntry(13402, "SERVERY_UNCOOKED_PIE", "Servery uncooked pie", "objtypes"),
            new GamevalEntry(13403, "SERVERY_MEAT_PIE", "Servery meat pie", "objtypes"),
            new GamevalEntry(13404, "SERVERY_PIZZA_BASE", "Servery pizza base", "objtypes"),
            new GamevalEntry(13405, "SERVERY_TOMATO", "Servery tomato", "objtypes"),
            new GamevalEntry(13406, "SERVERY_INCOMPLETE_PIZZA", "Servery incomplete pizza", "objtypes"),
            new GamevalEntry(13407, "SERVERY_CHEESE", "Servery cheese", "objtypes"),
            new GamevalEntry(13408, "SERVERY_UNCOOKED_PIZZA", "Servery uncooked pizza", "objtypes"),
            new GamevalEntry(13409, "SERVERY_PLAIN_PIZZA", "Servery plain pizza", "objtypes"),
            new GamevalEntry(13410, "SERVERY_PINEAPPLE", "Servery pineapple", "objtypes"),
            new GamevalEntry(13411, "SERVERY_PINEAPPLE_CHUNKS", "Servery pineapple chunks", "objtypes"),
            new GamevalEntry(13412, "SERVERY_PINEAPPLE_PIZZA", "Servery pineapple pizza", "objtypes"),
            new GamevalEntry(13413, "SERVERY_COOKED_MEAT", "Servery cooked meat", "objtypes"),
            new GamevalEntry(13414, "X_SERVERY_POTATO", "X ( ? + Servery potato", "objtypes"),
            new GamevalEntry(13415, "SERVERY_INCOMPLETE_STEW", "Servery incomplete stew", "objtypes"),
            new GamevalEntry(13416, "SERVERY_INCOMPLETE_STEW_13416", "Servery incomplete stew", "objtypes"),
            new GamevalEntry(13417, "SERVERY_UNCOOKED_STEW", "Servery uncooked stew", "objtypes"),
            new GamevalEntry(13418, "SERVERY_STEW", "Servery stew", "objtypes"),
            new GamevalEntry(13419, "SULPHUROUS_FERTILISER", "Sulphurous fertiliser", "objtypes"),
            new GamevalEntry(13420, "GRICOLLER_S_FERTILISER", "Gricoller's fertiliser", "objtypes"),
            new GamevalEntry(13421, "SALTPETRE", "Saltpetre", "objtypes"),
            new GamevalEntry(13422, "ID_13422", "", "objtypes"),
            new GamevalEntry(13423, "GOLOVANOVA_SEED", "Golovanova seed", "objtypes"),
            new GamevalEntry(13424, "BOLOGANO_SEED", "Bologano seed", "objtypes"),
            new GamevalEntry(13425, "LOGAVANO_SEED", "Logavano seed", "objtypes"),
            new GamevalEntry(13426, "GOLOVANOVA_FRUIT", "Golovanova fruit", "objtypes"),
            new GamevalEntry(13427, "BOLOGANO_FRUIT", "Bologano fruit", "objtypes"),
            new GamevalEntry(13428, "LOGAVANO_FRUIT", "Logavano fruit", "objtypes"),
            new GamevalEntry(13429, "FRESH_FISH", "Fresh fish", "objtypes"),
            new GamevalEntry(13430, "BUCKET_OF_SANDWORMS", "Bucket of sandworms", "objtypes"),
            new GamevalEntry(13431, "SANDWORMS", "Sandworms", "objtypes"),
            new GamevalEntry(13432, "D_SANDWORMS_PACK", "D Sandworms pack", "objtypes"),
            new GamevalEntry(13433, "ID_13433", "", "objtypes"),
            new GamevalEntry(13434, "STOLEN_PENDANT", "Stolen pendant", "objtypes"),
            new GamevalEntry(13435, "STOLEN_GARNET_RING", "Stolen garnet ring", "objtypes"),
            new GamevalEntry(13436, "STOLEN_CIRCLET", "Stolen circlet", "objtypes"),
            new GamevalEntry(13437, "STOLEN_FAMILY_HEIRLOOM", "Stolen family heirloom", "objtypes"),
            new GamevalEntry(13438, "STOLEN_JEWELRY_BOX", "Stolen jewelry box", "objtypes"),
            new GamevalEntry(13439, "RAW_ANGLERFISH", "Raw anglerfish", "objtypes"),
            new GamevalEntry(13440, "ID_13440", "", "objtypes"),
            new GamevalEntry(13441, "ANGLERFISH", "Anglerfish", "objtypes"),
            new GamevalEntry(13442, "ID_13442", "", "objtypes"),
            new GamevalEntry(13443, "BURNT_ANGLERFISH", "Burnt anglerfish", "objtypes"),
            new GamevalEntry(13444, "ID_13444", "", "objtypes"),
            new GamevalEntry(13445, "DENSE_ESSENCE_BLOCK", "Dense essence block", "objtypes"),
            new GamevalEntry(13446, "DARK_ESSENCE_BLOCK", "Dark essence block", "objtypes"),
            new GamevalEntry(13447, "ENSOULED_GOBLIN_HEAD", "Ensouled goblin head", "objtypes"),
            new GamevalEntry(13448, "ENSOULED_GOBLIN_HEAD_13448", "Ensouled goblin head", "objtypes"),
            new GamevalEntry(13449, "ID_13449", "", "objtypes"),
            new GamevalEntry(13450, "ENSOULED_MONKEY_HEAD", "Ensouled monkey head", "objtypes"),
            new GamevalEntry(13451, "ENSOULED_MONKEY_HEAD_13451", "Ensouled monkey head", "objtypes"),
            new GamevalEntry(13452, "ID_13452", "", "objtypes"),
            new GamevalEntry(13453, "ENSOULED_IMP_HEAD", "Ensouled imp head", "objtypes"),
            new GamevalEntry(13454, "ENSOULED_IMP_HEAD_13454", "Ensouled imp head", "objtypes"),
            new GamevalEntry(13455, "ID_13455", "", "objtypes"),
            new GamevalEntry(13456, "ENSOULED_MINOTAUR_HEAD", "Ensouled minotaur head", "objtypes"),
            new GamevalEntry(13457, "ENSOULED_MINOTAUR_HEAD_13457", "Ensouled minotaur head", "objtypes"),
            new GamevalEntry(13458, "ID_13458", "", "objtypes"),
            new GamevalEntry(13459, "ENSOULED_SCORPION_HEAD", "Ensouled scorpion head", "objtypes"),
            new GamevalEntry(13460, "ENSOULED_SCORPION_HEAD_13460", "Ensouled scorpion head", "objtypes"),
            new GamevalEntry(13461, "ID_13461", "", "objtypes"),
            new GamevalEntry(13462, "ENSOULED_BEAR_HEAD", "Ensouled bear head", "objtypes"),
            new GamevalEntry(13463, "ENSOULED_BEAR_HEAD_13463", "Ensouled bear head", "objtypes"),
            new GamevalEntry(13464, "ID_13464", "", "objtypes"),
            new GamevalEntry(13465, "ENSOULED_UNICORN_HEAD", "Ensouled unicorn head", "objtypes"),
            new GamevalEntry(13466, "ENSOULED_UNICORN_HEAD_13466", "Ensouled unicorn head", "objtypes"),
            new GamevalEntry(13467, "ID_13467", "", "objtypes"),
            new GamevalEntry(13468, "ENSOULED_DOG_HEAD", "Ensouled dog head", "objtypes"),
            new GamevalEntry(13469, "ENSOULED_DOG_HEAD_13469", "Ensouled dog head", "objtypes"),
            new GamevalEntry(13470, "ID_13470", "", "objtypes"),
            new GamevalEntry(13471, "ENSOULED_CHAOS_DRUID_HEAD", "Ensouled chaos druid head", "objtypes"),
            new GamevalEntry(13472, "ENSOULED_CHAOS_DRUID_HEAD_13472", "Ensouled chaos druid head", "objtypes"),
            new GamevalEntry(13473, "ID_13473", "", "objtypes"),
            new GamevalEntry(13474, "ENSOULED_GIANT_HEAD", "Ensouled giant head", "objtypes"),
            new GamevalEntry(13475, "ENSOULED_GIANT_HEAD_13475", "Ensouled giant head", "objtypes"),
            new GamevalEntry(13476, "ID_13476", "", "objtypes"),
            new GamevalEntry(13477, "ENSOULED_OGRE_HEAD", "Ensouled ogre head", "objtypes"),
            new GamevalEntry(13478, "ENSOULED_OGRE_HEAD_13478", "Ensouled ogre head", "objtypes"),
            new GamevalEntry(13479, "ID_13479", "", "objtypes"),
            new GamevalEntry(13480, "ENSOULED_ELF_HEAD", "Ensouled elf head", "objtypes"),
            new GamevalEntry(13481, "ENSOULED_ELF_HEAD_13481", "Ensouled elf head", "objtypes"),
            new GamevalEntry(13482, "ID_13482", "", "objtypes"),
            new GamevalEntry(13483, "ENSOULED_TROLL_HEAD", "Ensouled troll head", "objtypes"),
            new GamevalEntry(13484, "ENSOULED_TROLL_HEAD_13484", "Ensouled troll head", "objtypes"),
            new GamevalEntry(13485, "ID_13485", "", "objtypes"),
            new GamevalEntry(13486, "ENSOULED_HORROR_HEAD", "Ensouled horror head", "objtypes"),
            new GamevalEntry(13487, "ENSOULED_HORROR_HEAD_13487", "Ensouled horror head", "objtypes"),
            new GamevalEntry(13488, "ID_13488", "", "objtypes"),
            new GamevalEntry(13489, "ENSOULED_KALPHITE_HEAD", "Ensouled kalphite head", "objtypes"),
            new GamevalEntry(13490, "ENSOULED_KALPHITE_HEAD_13490", "Ensouled kalphite head", "objtypes"),
            new GamevalEntry(13491, "ID_13491", "", "objtypes"),
            new GamevalEntry(13492, "ENSOULED_DAGANNOTH_HEAD", "Ensouled dagannoth head", "objtypes"),
            new GamevalEntry(13493, "ENSOULED_DAGANNOTH_HEAD_13493", "Ensouled dagannoth head", "objtypes"),
            new GamevalEntry(13494, "ID_13494", "", "objtypes"),
            new GamevalEntry(13495, "ENSOULED_BLOODVELD_HEAD", "Ensouled bloodveld head", "objtypes"),
            new GamevalEntry(13496, "ENSOULED_BLOODVELD_HEAD_13496", "Ensouled bloodveld head", "objtypes"),
            new GamevalEntry(13497, "ID_13497", "", "objtypes"),
            new GamevalEntry(13498, "ENSOULED_TZHAAR_HEAD", "Ensouled tzhaar head", "objtypes"),
            new GamevalEntry(13499, "ENSOULED_TZHAAR_HEAD_13499", "Ensouled tzhaar head", "objtypes"),
            new GamevalEntry(13500, "ID_13500", "", "objtypes"),
            new GamevalEntry(13501, "ENSOULED_DEMON_HEAD", "Ensouled demon head", "objtypes"),
            new GamevalEntry(13502, "A_ENSOULED_DEMON_HEAD", "A Ensouled demon head", "objtypes"),
            new GamevalEntry(13503, "ID_13503", "", "objtypes"),
            new GamevalEntry(13504, "ENSOULED_AVIANSIE_HEAD", ") Ensouled aviansie head", "objtypes"),
            new GamevalEntry(13505, "A_ENSOULED_AVIANSIE_HEAD", ") A Ensouled aviansie head", "objtypes"),
            new GamevalEntry(13506, "ID_13506", "", "objtypes"),
            new GamevalEntry(13507, "I_ENSOULED_ABYSSAL_HEAD", "I Ensouled abyssal head", "objtypes"),
            new GamevalEntry(13508, "I_A_ENSOULED_ABYSSAL_HEAD", "I A Ensouled abyssal head", "objtypes"),
            new GamevalEntry(13509, "ID_13509", "", "objtypes"),
            new GamevalEntry(13510, "ENSOULED_DRAGON_HEAD", "Ensouled dragon head", "objtypes"),
            new GamevalEntry(13511, "ENSOULED_DRAGON_HEAD_13511", "Ensouled dragon head", "objtypes"),
            new GamevalEntry(13512, "ID_13512", "", "objtypes"),
            new GamevalEntry(13513, "BOOK_OF_ARCANE_KNOWLEDGE", "Book of arcane knowledge", "objtypes"),
            new GamevalEntry(13514, "DARK_MANUSCRIPT", "Dark manuscript", "objtypes"),
            new GamevalEntry(13515, "DARK_MANUSCRIPT_13515", "Dark manuscript", "objtypes"),
            new GamevalEntry(13516, "DARK_MANUSCRIPT_13516", "Dark manuscript", "objtypes"),
            new GamevalEntry(13517, "DARK_MANUSCRIPT_13517", "Dark manuscript", "objtypes"),
            new GamevalEntry(13518, "DARK_MANUSCRIPT_13518", "Dark manuscript", "objtypes"),
            new GamevalEntry(13519, "DARK_MANUSCRIPT_13519", "Dark manuscript", "objtypes"),
            new GamevalEntry(13520, "DARK_MANUSCRIPT_13520", "Dark manuscript", "objtypes"),
            new GamevalEntry(13521, "DARK_MANUSCRIPT_13521", "Dark manuscript", "objtypes"),
            new GamevalEntry(13522, "DARK_MANUSCRIPT_13522", "Dark manuscript", "objtypes"),
            new GamevalEntry(13523, "DARK_MANUSCRIPT_13523", "Dark manuscript", "objtypes"),
            new GamevalEntry(13524, "RADA_S_CENSUS", "Rada's census", "objtypes"),
            new GamevalEntry(13525, "RICKTOR_S_DIARY_7", "Ricktor's diary (7)", "objtypes"),
            new GamevalEntry(13526, "EATHRAM_RADA_EXTRACT", "Eathram & rada extract", "objtypes"),
            new GamevalEntry(13527, "KILLING_OF_A_KING", "Killing of a king", "objtypes"),
            new GamevalEntry(13528, "HOSIDIUS_LETTER", "Hosidius letter", "objtypes"),
            new GamevalEntry(13529, "WINTERTODT_PARABLE", "Wintertodt parable", "objtypes"),
            new GamevalEntry(13530, "TWILL_ACCORD", "Twill accord", "objtypes"),
            new GamevalEntry(13531, "BYRNE_S_CORONATION_SPEECH", "Byrne's coronation speech", "objtypes"),
            new GamevalEntry(13532, "IDEOLOGY_OF_DARKNESS", "Ideology of darkness", "objtypes"),
            new GamevalEntry(13533, "RADA_S_JOURNEY", "Rada's journey", "objtypes"),
            new GamevalEntry(13534, "TRANSVERGENCE_THEORY", "Transvergence theory", "objtypes"),
            new GamevalEntry(13535, "TRISTESSA_S_TRAGEDY", "Tristessa's tragedy", "objtypes"),
            new GamevalEntry(13536, "TREACHERY_OF_ROYALTY", "Treachery of royalty", "objtypes"),
            new GamevalEntry(13537, "TRANSPORTATION_INCANTATIONS", "Transportation incantations", "objtypes"),
            new GamevalEntry(13538, "SHAYZIEN_SUPPLY_GLOVES_1", "Shayzien supply gloves (1)", "objtypes"),
            new GamevalEntry(13539, "SHAYZIEN_SUPPLY_BOOTS_1", "Shayzien supply boots (1)", "objtypes"),
            new GamevalEntry(13540, "SHAYZIEN_SUPPLY_HELM_1", "Shayzien supply helm (1)", "objtypes"),
            new GamevalEntry(13541, "SHAYZIEN_SUPPLY_GREAVES_1", "Shayzien supply greaves (1)", "objtypes"),
            new GamevalEntry(13542, "SHAYZIEN_SUPPLY_PLATEBODY_1", "Shayzien supply platebody (1)", "objtypes"),
            new GamevalEntry(13543, "SHAYZIEN_SUPPLY_GLOVES_2", "Shayzien supply gloves (2)", "objtypes"),
            new GamevalEntry(13544, "SHAYZIEN_SUPPLY_BOOTS_2", "Shayzien supply boots (2)", "objtypes"),
            new GamevalEntry(13545, "SHAYZIEN_SUPPLY_HELM_2", "Shayzien supply helm (2)", "objtypes"),
            new GamevalEntry(13546, "SHAYZIEN_SUPPLY_GREAVES_2", "Shayzien supply greaves (2)", "objtypes"),
            new GamevalEntry(13547, "SHAYZIEN_SUPPLY_PLATEBODY_2", "Shayzien supply platebody (2)", "objtypes"),
            new GamevalEntry(13548, "SHAYZIEN_SUPPLY_GLOVES_3", "Shayzien supply gloves (3)", "objtypes"),
            new GamevalEntry(13549, "SHAYZIEN_SUPPLY_BOOTS_3", "Shayzien supply boots (3)", "objtypes"),
            new GamevalEntry(13550, "SHAYZIEN_SUPPLY_HELM_3", "Shayzien supply helm (3)", "objtypes"),
            new GamevalEntry(13551, "SHAYZIEN_SUPPLY_GREAVES_3", "Shayzien supply greaves (3)", "objtypes"),
            new GamevalEntry(13552, "SHAYZIEN_SUPPLY_PLATEBODY_3", "Shayzien supply platebody (3)", "objtypes"),
            new GamevalEntry(13553, "SHAYZIEN_SUPPLY_GLOVES_4", "Shayzien supply gloves (4)", "objtypes"),
            new GamevalEntry(13554, "SHAYZIEN_SUPPLY_BOOTS_4", "Shayzien supply boots (4)", "objtypes"),
            new GamevalEntry(13555, "SHAYZIEN_SUPPLY_HELM_4", "Shayzien supply helm (4)", "objtypes"),
            new GamevalEntry(13556, "SHAYZIEN_SUPPLY_GREAVES_4", "Shayzien supply greaves (4)", "objtypes"),
            new GamevalEntry(13557, "SHAYZIEN_SUPPLY_PLATEBODY_4", "Shayzien supply platebody (4)", "objtypes"),
            new GamevalEntry(13558, "SHAYZIEN_SUPPLY_GLOVES_5", "Shayzien supply gloves (5)", "objtypes"),
            new GamevalEntry(13559, "SHAYZIEN_SUPPLY_BOOTS_5", "Shayzien supply boots (5)", "objtypes"),
            new GamevalEntry(13560, "SHAYZIEN_SUPPLY_HELM_5", "Shayzien supply helm (5)", "objtypes"),
            new GamevalEntry(13561, "SHAYZIEN_SUPPLY_GREAVES_5", "Shayzien supply greaves (5)", "objtypes"),
            new GamevalEntry(13562, "SHAYZIEN_SUPPLY_PLATEBODY_5", "Shayzien supply platebody (5)", "objtypes"),
            new GamevalEntry(13563, "SHAYZIEN_SUPPLY_CRATE", "Shayzien supply crate", "objtypes"),
            new GamevalEntry(13564, "SHAYZIEN_SUPPLY_CRATE_13564", "Shayzien supply crate", "objtypes"),
            new GamevalEntry(13565, "SHAYZIEN_SUPPLY_SET_1", "Shayzien supply set (1)", "objtypes"),
            new GamevalEntry(13566, "SHAYZIEN_SUPPLY_SET_2", "Shayzien supply set (2)", "objtypes"),
            new GamevalEntry(13567, "SHAYZIEN_SUPPLY_SET_3", "Shayzien supply set (3)", "objtypes"),
            new GamevalEntry(13568, "SHAYZIEN_SUPPLY_SET_4", "Shayzien supply set (4)", "objtypes"),
            new GamevalEntry(13569, "SHAYZIEN_SUPPLY_SET_5", "Shayzien supply set (5)", "objtypes"),
            new GamevalEntry(13570, "JUNIPER_CHARCOAL", "Juniper charcoal", "objtypes"),
            new GamevalEntry(13571, "VOLCANIC_SULPHUR", "Volcanic sulphur", "objtypes"),
            new GamevalEntry(13572, "DYNAMITE_POT", "Dynamite pot", "objtypes"),
            new GamevalEntry(13573, "DYNAMITE", "Dynamite", "objtypes"),
            new GamevalEntry(13574, "ID_13574", "", "objtypes"),
            new GamevalEntry(13575, "BLASTED_ORE", "Blasted ore", "objtypes"),
            new GamevalEntry(13576, "DRAGON_WARHAMMER", "Dragon warhammer", "objtypes"),
            new GamevalEntry(13577, "ID_13577", "", "objtypes"),
            new GamevalEntry(13578, "ID_13578", "", "objtypes"),
            new GamevalEntry(13579, "GRACEFUL_HOOD_13579", "Graceful hood", "objtypes"),
            new GamevalEntry(13580, "GRACEFUL_HOOD_13580", "Graceful hood", "objtypes"),
            new GamevalEntry(13581, "GRACEFUL_CAPE_13581", "Graceful cape", "objtypes"),
            new GamevalEntry(13582, "GRACEFUL_CAPE_13582", "Graceful cape", "objtypes"),
            new GamevalEntry(13583, "GRACEFUL_TOP_13583", "Graceful top", "objtypes"),
            new GamevalEntry(13584, "GRACEFUL_TOP_13584", "Graceful top", "objtypes"),
            new GamevalEntry(13585, "GRACEFUL_LEGS_13585", "Graceful legs", "objtypes"),
            new GamevalEntry(13586, "GRACEFUL_LEGS_13586", "Graceful legs", "objtypes"),
            new GamevalEntry(13587, "GRACEFUL_GLOVES_13587", "Graceful gloves", "objtypes"),
            new GamevalEntry(13588, "GRACEFUL_GLOVES_13588", "Graceful gloves", "objtypes"),
            new GamevalEntry(13589, "GRACEFUL_BOOTS_13589", "Graceful boots", "objtypes"),
            new GamevalEntry(13590, "GRACEFUL_BOOTS_13590", "Graceful boots", "objtypes"),
            new GamevalEntry(13591, "GRACEFUL_HOOD_13591", "Graceful hood", "objtypes"),
            new GamevalEntry(13592, "GRACEFUL_HOOD_13592", "Graceful hood", "objtypes"),
            new GamevalEntry(13593, "GRACEFUL_CAPE_13593", "Graceful cape", "objtypes"),
            new GamevalEntry(13594, "GRACEFUL_CAPE_13594", "Graceful cape", "objtypes"),
            new GamevalEntry(13595, "GRACEFUL_TOP_13595", "Graceful top", "objtypes"),
            new GamevalEntry(13596, "GRACEFUL_TOP_13596", "Graceful top", "objtypes"),
            new GamevalEntry(13597, "GRACEFUL_LEGS_13597", "Graceful legs", "objtypes"),
            new GamevalEntry(13598, "GRACEFUL_LEGS_13598", "Graceful legs", "objtypes"),
            new GamevalEntry(13599, "GRACEFUL_GLOVES_13599", "Graceful gloves", "objtypes"),
            new GamevalEntry(13600, "GRACEFUL_GLOVES_13600", "Graceful gloves", "objtypes"),
            new GamevalEntry(13601, "GRACEFUL_BOOTS_13601", "Graceful boots", "objtypes"),
            new GamevalEntry(13602, "GRACEFUL_BOOTS_13602", "Graceful boots", "objtypes"),
            new GamevalEntry(13603, "GRACEFUL_HOOD_13603", "Graceful hood", "objtypes"),
            new GamevalEntry(13604, "GRACEFUL_HOOD_13604", "Graceful hood", "objtypes"),
            new GamevalEntry(13605, "GRACEFUL_CAPE_13605", "Graceful cape", "objtypes"),
            new GamevalEntry(13606, "GRACEFUL_CAPE_13606", "Graceful cape", "objtypes"),
            new GamevalEntry(13607, "GRACEFUL_TOP_13607", "Graceful top", "objtypes"),
            new GamevalEntry(13608, "GRACEFUL_TOP_13608", "Graceful top", "objtypes"),
            new GamevalEntry(13609, "GRACEFUL_LEGS_13609", "Graceful legs", "objtypes"),
            new GamevalEntry(13610, "GRACEFUL_LEGS_13610", "Graceful legs", "objtypes"),
            new GamevalEntry(13611, "GRACEFUL_GLOVES_13611", "Graceful gloves", "objtypes"),
            new GamevalEntry(13612, "GRACEFUL_GLOVES_13612", "Graceful gloves", "objtypes"),
            new GamevalEntry(13613, "GRACEFUL_BOOTS_13613", "Graceful boots", "objtypes"),
            new GamevalEntry(13614, "GRACEFUL_BOOTS_13614", "Graceful boots", "objtypes"),
            new GamevalEntry(13615, "GRACEFUL_HOOD_13615", "Graceful hood", "objtypes"),
            new GamevalEntry(13616, "GRACEFUL_HOOD_13616", "Graceful hood", "objtypes"),
            new GamevalEntry(13617, "GRACEFUL_CAPE_13617", "Graceful cape", "objtypes"),
            new GamevalEntry(13618, "GRACEFUL_CAPE_13618", "Graceful cape", "objtypes"),
            new GamevalEntry(13619, "GRACEFUL_TOP_13619", "Graceful top", "objtypes"),
            new GamevalEntry(13620, "GRACEFUL_TOP_13620", "Graceful top", "objtypes"),
            new GamevalEntry(13621, "GRACEFUL_LEGS_13621", "Graceful legs", "objtypes"),
            new GamevalEntry(13622, "GRACEFUL_LEGS_13622", "Graceful legs", "objtypes"),
            new GamevalEntry(13623, "GRACEFUL_GLOVES_13623", "Graceful gloves", "objtypes"),
            new GamevalEntry(13624, "GRACEFUL_GLOVES_13624", "Graceful gloves", "objtypes"),
            new GamevalEntry(13625, "GRACEFUL_BOOTS_13625", "Graceful boots", "objtypes"),
            new GamevalEntry(13626, "GRACEFUL_BOOTS_13626", "Graceful boots", "objtypes"),
            new GamevalEntry(13627, "GRACEFUL_HOOD_13627", "Graceful hood", "objtypes"),
            new GamevalEntry(13628, "GRACEFUL_HOOD_13628", "Graceful hood", "objtypes"),
            new GamevalEntry(13629, "GRACEFUL_CAPE_13629", "Graceful cape", "objtypes"),
            new GamevalEntry(13630, "GRACEFUL_CAPE_13630", "Graceful cape", "objtypes"),
            new GamevalEntry(13631, "GRACEFUL_TOP_13631", "Graceful top", "objtypes"),
            new GamevalEntry(13632, "GRACEFUL_TOP_13632", "Graceful top", "objtypes"),
            new GamevalEntry(13633, "GRACEFUL_LEGS_13633", "Graceful legs", "objtypes"),
            new GamevalEntry(13634, "GRACEFUL_LEGS_13634", "Graceful legs", "objtypes"),
            new GamevalEntry(13635, "GRACEFUL_GLOVES_13635", "Graceful gloves", "objtypes"),
            new GamevalEntry(13636, "GRACEFUL_GLOVES_13636", "Graceful gloves", "objtypes"),
            new GamevalEntry(13637, "GRACEFUL_BOOTS_13637", "Graceful boots", "objtypes"),
            new GamevalEntry(13638, "GRACEFUL_BOOTS_13638", "Graceful boots", "objtypes"),
            new GamevalEntry(13639, "SEED_BOX", "Seed box", "objtypes"),
            new GamevalEntry(13640, "FARMER_S_BORO_TROUSERS", "Farmer's boro trousers", "objtypes"),
            new GamevalEntry(13641, "FARMER_S_BORO_TROUSERS_13641", "Farmer's boro trousers", "objtypes"),
            new GamevalEntry(13642, "FARMER_S_JACKET", "Farmer's jacket", "objtypes"),
            new GamevalEntry(13643, "FARMER_S_SHIRT", "Farmer's shirt", "objtypes"),
            new GamevalEntry(13644, "FARMER_S_BOOTS", "Farmer's boots", "objtypes"),
            new GamevalEntry(13645, "FARMER_S_BOOTS_13645", "Farmer's boots", "objtypes"),
            new GamevalEntry(13646, "FARMER_S_STRAWHAT", "Farmer's strawhat", "objtypes"),
            new GamevalEntry(13647, "FARMER_S_STRAWHAT_13647", "Farmer's strawhat", "objtypes"),
            new GamevalEntry(13648, "CLUE_BOTTLE_EASY", "Clue bottle (easy)", "objtypes"),
            new GamevalEntry(13649, "CLUE_BOTTLE_MEDIUM", "Clue bottle (medium)", "objtypes"),
            new GamevalEntry(13650, "CLUE_BOTTLE_HARD", "Clue bottle (hard)", "objtypes"),
            new GamevalEntry(13651, "CLUE_BOTTLE_ELITE", "Clue bottle (elite)", "objtypes"),
            new GamevalEntry(13652, "DRAGON_CLAWS", "Dragon claws", "objtypes"),
            new GamevalEntry(13653, "BIRD_NEST_13653", "Bird nest", "objtypes"),
            new GamevalEntry(13654, "NEST_BOX_SEEDS_13654", "Nest box (seeds)", "objtypes"),
            new GamevalEntry(13655, "GNOME_CHILD_HAT", "Gnome child hat", "objtypes"),
            new GamevalEntry(13656, "PRESENT_13656", "Present", "objtypes"),
            new GamevalEntry(13657, "GRAPE_SEED", "Grape seed", "objtypes"),
            new GamevalEntry(13658, "TELEPORT_CARD", "Teleport card", "objtypes"),
            new GamevalEntry(13659, "ID_13659", "", "objtypes"),
            new GamevalEntry(13660, "CHRONICLE", "Chronicle", "objtypes"),
            new GamevalEntry(13661, "NULL__13661", "Null", "objtypes"),
            new GamevalEntry(13662, "NULL__13662", "Null", "objtypes"),
            new GamevalEntry(13663, "BUNNY_TOP", "Bunny top", "objtypes"),
            new GamevalEntry(13664, "BUNNY_LEGS", "Bunny legs", "objtypes"),
            new GamevalEntry(13665, "BUNNY_PAWS", "Bunny paws", "objtypes"),
            new GamevalEntry(13666, "DEADMAN_TELEPORT_TABLET", "Deadman teleport tablet", "objtypes"),
            new GamevalEntry(13667, "GRACEFUL_HOOD_13667", "Graceful hood", "objtypes"),
            new GamevalEntry(13668, "GRACEFUL_HOOD_13668", "Graceful hood", "objtypes"),
            new GamevalEntry(13669, "GRACEFUL_CAPE_13669", "Graceful cape", "objtypes"),
            new GamevalEntry(13670, "GRACEFUL_CAPE_13670", "Graceful cape", "objtypes"),
            new GamevalEntry(13671, "GRACEFUL_TOP_13671", "Graceful top", "objtypes"),
            new GamevalEntry(13672, "GRACEFUL_TOP_13672", "Graceful top", "objtypes"),
            new GamevalEntry(13673, "GRACEFUL_LEGS_13673", "Graceful legs", "objtypes"),
            new GamevalEntry(13674, "GRACEFUL_LEGS_13674", "Graceful legs", "objtypes"),
            new GamevalEntry(13675, "GRACEFUL_GLOVES_13675", "Graceful gloves", "objtypes"),
            new GamevalEntry(13676, "GRACEFUL_GLOVES_13676", "Graceful gloves", "objtypes"),
            new GamevalEntry(13677, "GRACEFUL_BOOTS_13677", "Graceful boots", "objtypes"),
            new GamevalEntry(13678, "GRACEFUL_BOOTS_13678", "Graceful boots", "objtypes"),
            new GamevalEntry(13679, "CABBAGE_CAPE", "Cabbage cape", "objtypes"),
            new GamevalEntry(13680, "CABBAGE_RUNE", "Cabbage rune", "objtypes"),
            new GamevalEntry(13681, "CRUCIFEROUS_CODEX", "Cruciferous codex", "objtypes"),
            new GamevalEntry(13682, "ID_13682", "", "objtypes"),
            new GamevalEntry(13683, "ID_13683", "", "objtypes"),
            new GamevalEntry(13684, "ID_13684", "", "objtypes"),
            new GamevalEntry(13685, "ID_13685", "", "objtypes"),
            new GamevalEntry(13686, "ID_13686", "", "objtypes"),
            new GamevalEntry(13687, "ID_13687", "", "objtypes"),
            new GamevalEntry(13688, "ID_13688", "", "objtypes"),
            new GamevalEntry(13689, "ID_13689", "", "objtypes"),
            new GamevalEntry(13690, "ID_13690", "", "objtypes"),
            new GamevalEntry(13691, "ID_13691", "", "objtypes"),
            new GamevalEntry(13692, "ID_13692", "", "objtypes"),
            new GamevalEntry(13693, "ID_13693", "", "objtypes"),
            new GamevalEntry(13694, "ID_13694", "", "objtypes"),
            new GamevalEntry(13695, "ID_13695", "", "objtypes"),
            new GamevalEntry(13696, "ID_13696", "", "objtypes"),
            new GamevalEntry(13697, "ID_13697", "", "objtypes"),
            new GamevalEntry(13698, "ID_13698", "", "objtypes"),
            new GamevalEntry(13699, "ID_13699", "", "objtypes"),
            new GamevalEntry(13700, "ID_13700", "", "objtypes"),
            new GamevalEntry(13701, "ID_13701", "", "objtypes"),
            new GamevalEntry(13702, "ID_13702", "", "objtypes"),
            new GamevalEntry(13703, "ID_13703", "", "objtypes"),
            new GamevalEntry(13704, "ID_13704", "", "objtypes"),
            new GamevalEntry(13705, "ID_13705", "", "objtypes"),
            new GamevalEntry(13706, "ID_13706", "", "objtypes"),
            new GamevalEntry(13707, "ID_13707", "", "objtypes"),
            new GamevalEntry(13708, "ID_13708", "", "objtypes"),
            new GamevalEntry(13709, "ID_13709", "", "objtypes"),
            new GamevalEntry(13710, "ID_13710", "", "objtypes"),
            new GamevalEntry(13711, "ID_13711", "", "objtypes"),
            new GamevalEntry(13712, "A_8A", "A?8A", "objtypes"),
            new GamevalEntry(13713, "C_8A", "C?8A", "objtypes"),
            new GamevalEntry(13714, "E_8A", "E?8A", "objtypes"),
            new GamevalEntry(13715, "ID_13715", "", "objtypes"),
            new GamevalEntry(13716, "ID_13716", "", "objtypes"),
            new GamevalEntry(13717, "ID_13717", "", "objtypes"),
            new GamevalEntry(13718, "ID_13718", "", "objtypes"),
            new GamevalEntry(13719, "ID_13719", "", "objtypes"),
            new GamevalEntry(13720, "ID_13720", "", "objtypes"),
            new GamevalEntry(13721, "ID_13721", "", "objtypes"),
            new GamevalEntry(13722, "ID_13722", "", "objtypes"),
            new GamevalEntry(13723, "ID_13723", "", "objtypes"),
            new GamevalEntry(13724, "ID_13724", "", "objtypes"),
            new GamevalEntry(13725, "ID_13725", "", "objtypes"),
            new GamevalEntry(13726, "ID_13726", "", "objtypes"),
            new GamevalEntry(13727, "ID_13727", "", "objtypes"),
            new GamevalEntry(13728, "ID_13728", "", "objtypes"),
            new GamevalEntry(13729, "ID_13729", "", "objtypes"),
            new GamevalEntry(13730, "ID_13730", "", "objtypes"),
            new GamevalEntry(13731, "ID_13731", "", "objtypes"),
            new GamevalEntry(13732, "ID_13732", "", "objtypes"),
            new GamevalEntry(13733, "ID_13733", "", "objtypes"),
            new GamevalEntry(13734, "ID_13734", "", "objtypes"),
            new GamevalEntry(13735, "ID_13735", "", "objtypes"),
            new GamevalEntry(13736, "ID_13736", "", "objtypes"),
            new GamevalEntry(13737, "ID_13737", "", "objtypes"),
            new GamevalEntry(13738, "ID_13738", "", "objtypes"),
            new GamevalEntry(13739, "ID_13739", "", "objtypes"),
            new GamevalEntry(13740, "ID_13740", "", "objtypes"),
            new GamevalEntry(13741, "ID_13741", "", "objtypes"),
            new GamevalEntry(13742, "ID_13742", "", "objtypes"),
            new GamevalEntry(13743, "ID_13743", "", "objtypes"),
            new GamevalEntry(13744, "ID_13744", "", "objtypes"),
            new GamevalEntry(13745, "ID_13745", "", "objtypes"),
            new GamevalEntry(13746, "ID_13746", "", "objtypes"),
            new GamevalEntry(13747, "ID_13747", "", "objtypes"),
            new GamevalEntry(13748, "ID_13748", "", "objtypes"),
            new GamevalEntry(13749, "ID_13749", "", "objtypes"),
            new GamevalEntry(13750, "ID_13750", "", "objtypes"),
            new GamevalEntry(13751, "ID_13751", "", "objtypes"),
            new GamevalEntry(13752, "ID_13752", "", "objtypes"),
            new GamevalEntry(13753, "ID_13753", "", "objtypes"),
            new GamevalEntry(13754, "ID_13754", "", "objtypes"),
            new GamevalEntry(13755, "ID_13755", "", "objtypes"),
            new GamevalEntry(13756, "ID_13756", "", "objtypes"),
            new GamevalEntry(13757, "ID_13757", "", "objtypes"),
            new GamevalEntry(13758, "ID_13758", "", "objtypes"),
            new GamevalEntry(13759, "ID_13759", "", "objtypes"),
            new GamevalEntry(13760, "ID_13760", "", "objtypes"),
            new GamevalEntry(13761, "ID_13761", "", "objtypes"),
            new GamevalEntry(13762, "ID_13762", "", "objtypes"),
            new GamevalEntry(13763, "ID_13763", "", "objtypes"),
            new GamevalEntry(13764, "ID_13764", "", "objtypes"),
            new GamevalEntry(13765, "ID_13765", "", "objtypes"),
            new GamevalEntry(13766, "ID_13766", "", "objtypes"),
            new GamevalEntry(13767, "ID_13767", "", "objtypes"),
            new GamevalEntry(13768, "ID_13768", "", "objtypes"),
            new GamevalEntry(13769, "ID_13769", "", "objtypes"),
            new GamevalEntry(13770, "ID_13770", "", "objtypes"),
            new GamevalEntry(13771, "ID_13771", "", "objtypes"),
            new GamevalEntry(13772, "ID_13772", "", "objtypes"),
            new GamevalEntry(13773, "ID_13773", "", "objtypes"),
            new GamevalEntry(13774, "ID_13774", "", "objtypes"),
            new GamevalEntry(13775, "ID_13775", "", "objtypes"),
            new GamevalEntry(13776, "ID_13776", "", "objtypes"),
            new GamevalEntry(13777, "ID_13777", "", "objtypes"),
            new GamevalEntry(13778, "ID_13778", "", "objtypes"),
            new GamevalEntry(13779, "ID_13779", "", "objtypes"),
            new GamevalEntry(13780, "ID_13780", "", "objtypes"),
            new GamevalEntry(13781, "ID_13781", "", "objtypes"),
            new GamevalEntry(13782, "ID_13782", "", "objtypes"),
            new GamevalEntry(13783, "ID_13783", "", "objtypes"),
            new GamevalEntry(13784, "ID_13784", "", "objtypes"),
            new GamevalEntry(13785, "ID_13785", "", "objtypes"),
            new GamevalEntry(13786, "ID_13786", "", "objtypes"),
            new GamevalEntry(13787, "ID_13787", "", "objtypes"),
            new GamevalEntry(13788, "ID_13788", "", "objtypes"),
            new GamevalEntry(13789, "ID_13789", "", "objtypes"),
            new GamevalEntry(13790, "ID_13790", "", "objtypes"),
            new GamevalEntry(13791, "ID_13791", "", "objtypes"),
            new GamevalEntry(13792, "ID_13792", "", "objtypes"),
            new GamevalEntry(13793, "ID_13793", "", "objtypes"),
            new GamevalEntry(13794, "ID_13794", "", "objtypes"),
            new GamevalEntry(13795, "ID_13795", "", "objtypes"),
            new GamevalEntry(13796, "ID_13796", "", "objtypes"),
            new GamevalEntry(13797, "ID_13797", "", "objtypes"),
            new GamevalEntry(13798, "ID_13798", "", "objtypes"),
            new GamevalEntry(13799, "ID_13799", "", "objtypes"),
            new GamevalEntry(13800, "ID_13800", "", "objtypes"),
            new GamevalEntry(13801, "ID_13801", "", "objtypes"),
            new GamevalEntry(13802, "ID_13802", "", "objtypes"),
            new GamevalEntry(13803, "ID_13803", "", "objtypes"),
            new GamevalEntry(13804, "ID_13804", "", "objtypes"),
            new GamevalEntry(13805, "ID_13805", "", "objtypes"),
            new GamevalEntry(13806, "ID_13806", "", "objtypes"),
            new GamevalEntry(13807, "ID_13807", "", "objtypes"),
            new GamevalEntry(13808, "ID_13808", "", "objtypes"),
            new GamevalEntry(13809, "ID_13809", "", "objtypes"),
            new GamevalEntry(13810, "ID_13810", "", "objtypes"),
            new GamevalEntry(13811, "ID_13811", "", "objtypes"),
            new GamevalEntry(13812, "ID_13812", "", "objtypes"),
            new GamevalEntry(13813, "ID_13813", "", "objtypes"),
            new GamevalEntry(13814, "ID_13814", "", "objtypes"),
            new GamevalEntry(13815, "ID_13815", "", "objtypes"),
            new GamevalEntry(13816, "ID_13816", "", "objtypes"),
            new GamevalEntry(13817, "ID_13817", "", "objtypes"),
            new GamevalEntry(13818, "ID_13818", "", "objtypes"),
            new GamevalEntry(13819, "ID_13819", "", "objtypes"),
            new GamevalEntry(13820, "ID_13820", "", "objtypes"),
            new GamevalEntry(13821, "ID_13821", "", "objtypes"),
            new GamevalEntry(13822, "ID_13822", "", "objtypes"),
            new GamevalEntry(13823, "ID_13823", "", "objtypes"),
        };
    }

    static Optional<GamevalEntry> byId(int id) {
        for (GamevalEntry entry : entries()) {
            if (entry.id() == id) return Optional.of(entry);
        }
        return Optional.empty();
    }

}
