package net.titan.gamevals.internal;

import java.util.Optional;

import net.titan.gamevals.GamevalEntry;
import net.titan.gamevals.QuestEntry;

final class ItemIDEntries_19 {
    private ItemIDEntries_19() {}

    static GamevalEntry[] entries() {
        return new GamevalEntry[] {
            new GamevalEntry(9934, "ZEP_TEST_BALLOON", "Origami balloon", "objtypes"),
            new GamevalEntry(9935, "ZEP_TOY_BALLOON_YEL", "Yellow balloon", "objtypes"),
            new GamevalEntry(9936, "ZEP_TOY_BALLOON_BLUE", "Blue balloon", "objtypes"),
            new GamevalEntry(9937, "ZEP_TOY_BALLOON_RED", "Red balloon", "objtypes"),
            new GamevalEntry(9938, "ZEP_TOY_BALLOON_ORANGE", "Orange balloon", "objtypes"),
            new GamevalEntry(9939, "ZEP_TOY_BALLOON_GREEN", "Green balloon", "objtypes"),
            new GamevalEntry(9940, "ZEP_TOY_BALLOON_PURPLE", "Purple balloon", "objtypes"),
            new GamevalEntry(9941, "ZEP_TOY_BALLOON_PINK", "Pink balloon", "objtypes"),
            new GamevalEntry(9942, "ZEP_TOY_BALLOON_BLACK", "Black balloon", "objtypes"),
            new GamevalEntry(9943, "ZEP_SANDBAG", "Sandbag", "objtypes"),
            new GamevalEntry(9944, "ZEP_BOMBER_JACKET", "Bomber jacket", "objtypes"),
            new GamevalEntry(9945, "ZEP_BOMBER_CAP", "Bomber cap", "objtypes"),
            new GamevalEntry(9946, "ZEP_BOMBER_CAP_GOGGLES", "Cap and goggles", "objtypes"),
            new GamevalEntry(9947, "VIKING_RED_WOODEN_COIN_OLD", "Old red disk", "objtypes"),
            new GamevalEntry(9948, "SKILLCAPE_HUNTING", "Carnivorous Chinchompas", "objtypes"),
            new GamevalEntry(9949, "SKILLCAPE_HUNTING_TRIMMED", "Carnivorous Chinchompas", "objtypes"),
            new GamevalEntry(9950, "SKILLCAPE_HUNTING_HOOD", "Hunter hood", "objtypes"),
            new GamevalEntry(9951, "HUNTING_ICON", "Footprint", "objtypes"),
            new GamevalEntry(9952, "HUNTGUIDE_IMP", "Imp", "objtypes"),
            new GamevalEntry(9953, "HUNTGUIDE_POLAR_BEAST", "Kebbit", "objtypes"),
            new GamevalEntry(9954, "HUNTGUIDE_WOOD_BEAST", "Kebbit", "objtypes"),
            new GamevalEntry(9955, "HUNTGUIDE_JUNGLE_BEAST", "Kebbit", "objtypes"),
            new GamevalEntry(9956, "HUNTGUIDE_DESERT_BEAST", "Kebbit", "objtypes"),
            new GamevalEntry(9957, "HUNTGUIDE_RAZOR_BEAST", "Kebbit", "objtypes"),
            new GamevalEntry(9958, "HUNTGUIDE_BARBTAILED_BEAST", "Kebbit", "objtypes"),
            new GamevalEntry(9959, "HUNTGUIDE_SABRE_BEAST", "Kebbit", "objtypes"),
            new GamevalEntry(9960, "HUNTGUIDE_SPEEDY_BEAST", "Kebbit", "objtypes"),
            new GamevalEntry(9961, "HUNTGUIDE_RAZOR2_BEAST", "Kebbit", "objtypes"),
            new GamevalEntry(9962, "HUNTGUIDE_HUNTING_BEAST", "Kebbit", "objtypes"),
            new GamevalEntry(9963, "HUNTGUIDE_SILENT_BEAST", "Kebbit", "objtypes"),
            new GamevalEntry(9964, "HUNTGUIDE_SPEEDY2_BEAST", "Kebbit", "objtypes"),
            new GamevalEntry(9965, "HUNTGUIDE_JUNGLE_BIRD", "Crimson swift", "objtypes"),
            new GamevalEntry(9966, "HUNTGUIDE_WOOD_BIRD", "Copper longtail", "objtypes"),
            new GamevalEntry(9967, "HUNTGUIDE_POLAR_BIRD", "Cerulean twitch", "objtypes"),
            new GamevalEntry(9968, "HUNTGUIDE_DESERT_BIRD", "Golden warbler", "objtypes"),
            new GamevalEntry(9969, "HUNTGUIDE_COLOURED_BIRD", "Tropical wagtail", "objtypes"),
            new GamevalEntry(9970, "HUNTGUIDE_RED_BUTTERFLY", "Butterfly", "objtypes"),
            new GamevalEntry(9971, "HUNTGUIDE_BLUE_BUTTERFLY", "Butterfly", "objtypes"),
            new GamevalEntry(9972, "HUNTGUIDE_WHITE_BUTTERFLY", "Butterfly", "objtypes"),
            new GamevalEntry(9973, "HUNTGUIDE_BLACK_BUTTERFLY", "Butterfly", "objtypes"),
            new GamevalEntry(9974, "HUNTGUIDE_GIANT_EAGLE", "Giant eagle", "objtypes"),
            new GamevalEntry(9975, "HUNTGUIDE_RABBIT", "Rabbit", "objtypes"),
            new GamevalEntry(9976, "HUNTGUIDE_CHINCHOMPA_CAPTURED", "Chinchompa", "objtypes"),
            new GamevalEntry(9977, "HUNTGUIDE_CHINCHOMPA_BIG_CAPTURED", "Red chinchompa", "objtypes"),
            new GamevalEntry(9978, "SPIT_RAW_BIRD_MEAT", "Raw bird meat", "objtypes"),
            new GamevalEntry(9979, "CERT_SPIT_RAW_BIRD_MEAT", "cert_spit_raw_bird_meat", "objtypes"),
            new GamevalEntry(9980, "SPIT_ROASTED_BIRD_MEAT", "Roast bird meat", "objtypes"),
            new GamevalEntry(9981, "CERT_SPIT_ROASTED_BIRD_MEAT", "cert_spit_roasted_bird_meat", "objtypes"),
            new GamevalEntry(9982, "SPIT_BURNED_BIRD_MEAT", "Burnt bird meat", "objtypes"),
            new GamevalEntry(9983, "CERT_SPIT_BURNED_BIRD_MEAT", "cert_spit_burned_bird_meat", "objtypes"),
            new GamevalEntry(9984, "SPIT_SKEWERED_BIRD_MEAT", "Skewered bird meat", "objtypes"),
            new GamevalEntry(9985, "CERT_SPIT_SKEWERED_BIRD_MEAT", "cert_spit_skewered_bird_meat", "objtypes"),
            new GamevalEntry(9986, "SPIT_RAW_BEAST_MEAT", "Raw beast meat", "objtypes"),
            new GamevalEntry(9987, "CERT_SPIT_RAW_BEAST_MEAT", "cert_spit_raw_beast_meat", "objtypes"),
            new GamevalEntry(9988, "SPIT_ROASTED_BEAST_MEAT", "Roast beast meat", "objtypes"),
            new GamevalEntry(9989, "CERT_SPIT_ROASTED_BEAST_MEAT", "cert_spit_roasted_beast_meat", "objtypes"),
            new GamevalEntry(9990, "SPIT_BURNED_BEAST_MEAT", "Burnt beast meat", "objtypes"),
            new GamevalEntry(9991, "CERT_SPIT_BURNED_BEAST_MEAT", "cert_spit_burned_beast_meat", "objtypes"),
            new GamevalEntry(9992, "SPIT_SKEWERED_BEAST_MEAT", "Skewered beast", "objtypes"),
            new GamevalEntry(9993, "CERT_SPIT_SKEWERED_BEAST_MEAT", "cert_spit_skewered_beast_meat", "objtypes"),
            new GamevalEntry(9994, "BOWL_SPICYTOMATO", "Spicy tomato", "objtypes"),
            new GamevalEntry(9995, "CERT_BOWL_SPICYTOMATO", "cert_bowl_spicytomato", "objtypes"),
            new GamevalEntry(9996, "BOWL_SPICYMEAT", "Spicy minced meat", "objtypes"),
            new GamevalEntry(9997, "CERT_BOWL_SPICYMEAT", "cert_bowl_spicymeat", "objtypes"),
            new GamevalEntry(9998, "_4DOSEHUNTING", "Hunter potion(4)", "objtypes"),
            new GamevalEntry(9999, "CERT_4DOSEHUNTING", "cert_4dosehunting", "objtypes"),
            new GamevalEntry(10000, "_3DOSEHUNTING", "Hunter potion(3)", "objtypes"),
            new GamevalEntry(10001, "CERT_3DOSEHUNTING", "cert_3dosehunting", "objtypes"),
            new GamevalEntry(10002, "_2DOSEHUNTING", "Hunter potion(2)", "objtypes"),
            new GamevalEntry(10003, "CERT_2DOSEHUNTING", "cert_2dosehunting", "objtypes"),
            new GamevalEntry(10004, "_1DOSEHUNTING", "Hunter potion(1)", "objtypes"),
            new GamevalEntry(10005, "CERT_1DOSEHUNTING", "cert_1dosehunting", "objtypes"),
            new GamevalEntry(10006, "HUNTING_OJIBWAY_BIRD_SNARE", "Bird snare", "objtypes"),
            new GamevalEntry(10007, "CERT_HUNTING_OJIBWAY_BIRD_SNARE", "Null", "objtypes"),
            new GamevalEntry(10008, "HUNTING_BOX_TRAP", "Box trap", "objtypes"),
            new GamevalEntry(10009, "CERT_HUNTING_BOX_TRAP", "Null", "objtypes"),
            new GamevalEntry(10010, "HUNTING_BUTTERFLY_NET", "Butterfly net", "objtypes"),
            new GamevalEntry(10011, "CERT_HUNTING_BUTTERFLY_NET", "cert_hunting_butterfly_net", "objtypes"),
            new GamevalEntry(10012, "BUTTERFLY_JAR", "Butterfly jar", "objtypes"),
            new GamevalEntry(10013, "CERT_BUTTERFLY_JAR", "cert_butterfly_jar", "objtypes"),
            new GamevalEntry(10014, "BUTTERFLY_JAR_WARLOCK", "Black warlock", "objtypes"),
            new GamevalEntry(10015, "CERT_BUTTERFLY_JAR_WARLOCK", "cert_butterfly_jar_warlock", "objtypes"),
            new GamevalEntry(10016, "BUTTERFLY_JAR_SNOWY", "Snowy knight", "objtypes"),
            new GamevalEntry(10017, "CERT_BUTTERFLY_JAR_SNOWY", "cert_butterfly_jar_snowy", "objtypes"),
            new GamevalEntry(10018, "BUTTERFLY_JAR_GLACIALIS", "Sapphire glacialis", "objtypes"),
            new GamevalEntry(10019, "CERT_BUTTERFLY_JAR_GLACIALIS", "cert_butterfly_jar_glacialis", "objtypes"),
            new GamevalEntry(10020, "BUTTERFLY_JAR_RUBY", "Ruby harvest", "objtypes"),
            new GamevalEntry(10021, "CERT_BUTTERFLY_JAR_RUBY", "cert_butterfly_jar_ruby", "objtypes"),
            new GamevalEntry(10022, "BUTTERFLY_IN_JAR", "butterfly_in_jar", "objtypes"),
            new GamevalEntry(10023, "FALCON_GLOVES", "Falconer's glove", "objtypes"),
            new GamevalEntry(10024, "FALCON_ON_GLOVES", "Falconer's glove", "objtypes"),
            new GamevalEntry(10025, "MAGIC_IMP_BOX", "Magic box", "objtypes"),
            new GamevalEntry(10026, "CERT_MAGIC_IMP_BOX", "Null", "objtypes"),
            new GamevalEntry(10027, "MAGIC_IMP_BOX_FULL", "X Imp-in-a-box(2)", "objtypes"),
            new GamevalEntry(10028, "MAGIC_IMP_BOX_HALF", "X Imp-in-a-box(1)", "objtypes"),
            new GamevalEntry(10029, "HUNTING_TEASING_STICK", "Teasing stick", "objtypes"),
            new GamevalEntry(10030, "CERT_HUNTING_TEASING_STICK", "cert_hunting_teasing_stick", "objtypes"),
            new GamevalEntry(10031, "HUNTING_SNARE", "Rabbit snare", "objtypes"),
            new GamevalEntry(10032, "CERT_HUNTING_SNARE", "Null", "objtypes"),
            new GamevalEntry(10033, "CHINCHOMPA_CAPTURED", "Chinchompa", "objtypes"),
            new GamevalEntry(10034, "CHINCHOMPA_BIG_CAPTURED", "Red chinchompa", "objtypes"),
            new GamevalEntry(10035, "HUNTING_TROUSERS_TIGER", "Kyatt legs", "objtypes"),
            new GamevalEntry(10036, "CERT_HUNTING_TROUSERS_TIGER", "cert_hunting_trousers_tiger", "objtypes"),
            new GamevalEntry(10037, "HUNTING_TORSO_TIGER", "Kyatt top", "objtypes"),
            new GamevalEntry(10038, "CERT_HUNTING_TORSO_TIGER", "cert_hunting_torso_tiger", "objtypes"),
            new GamevalEntry(10039, "HUNTING_HAT_TIGER", "Kyatt hat", "objtypes"),
            new GamevalEntry(10040, "CERT_HUNTING_HAT_TIGER", "cert_hunting_hat_tiger", "objtypes"),
            new GamevalEntry(10041, "HUNTING_TROUSERS_JAGUAR", "Larupia legs", "objtypes"),
            new GamevalEntry(10042, "CERT_HUNTING_TROUSERS_JAGUAR", "cert_hunting_trousers_jaguar", "objtypes"),
            new GamevalEntry(10043, "HUNTING_TORSO_JAGUAR", "Larupia top", "objtypes"),
            new GamevalEntry(10044, "CERT_HUNTING_TORSO_JAGUAR", "cert_hunting_torso_jaguar", "objtypes"),
            new GamevalEntry(10045, "HUNTING_HAT_JAGUAR", "Larupia hat", "objtypes"),
            new GamevalEntry(10046, "CERT_HUNTING_HAT_JAGUAR", "cert_hunting_hat_jaguar", "objtypes"),
            new GamevalEntry(10047, "HUNTING_TROUSERS_LEOPARD", "Graahk legs", "objtypes"),
            new GamevalEntry(10048, "CERT_HUNTING_TROUSERS_LEOPARD", "cert_hunting_trousers_leopard", "objtypes"),
            new GamevalEntry(10049, "HUNTING_TORSO_LEOPARD", "Graahk top", "objtypes"),
            new GamevalEntry(10050, "CERT_HUNTING_TORSO_LEOPARD", "cert_hunting_torso_leopard", "objtypes"),
            new GamevalEntry(10051, "HUNTING_HAT_LEOPARD", "Graahk headdress", "objtypes"),
            new GamevalEntry(10052, "CERT_HUNTING_HAT_LEOPARD", "cert_hunting_hat_leopard", "objtypes"),
            new GamevalEntry(10053, "HUNTING_CAMOFLAUGE_ROBE_WOOD", "Wood camo top", "objtypes"),
            new GamevalEntry(10054, "CERT_HUNTING_CAMOFLAUGE_ROBE_WOOD", "cert_hunting_camoflauge_robe_wood", "objtypes"),
            new GamevalEntry(10055, "HUNTING_TROUSERS_WOOD", "Wood camo legs", "objtypes"),
            new GamevalEntry(10056, "CERT_HUNTING_TROUSERS_WOOD", "cert_hunting_trousers_wood", "objtypes"),
            new GamevalEntry(10057, "HUNTING_CAMOFLAUGE_ROBE_JUNGLE", "Jungle camo top", "objtypes"),
            new GamevalEntry(10058, "CERT_HUNTING_CAMOFLAUGE_ROBE_JUNGLE", "cert_hunting_camoflauge_robe_jungle", "objtypes"),
            new GamevalEntry(10059, "HUNTING_TROUSERS_JUNGLE", "Jungle camo legs", "objtypes"),
            new GamevalEntry(10060, "CERT_HUNTING_TROUSERS_JUNGLE", "cert_hunting_trousers_jungle", "objtypes"),
            new GamevalEntry(10061, "HUNTING_CAMOFLAUGE_ROBE_DESERT", "Desert camo top", "objtypes"),
            new GamevalEntry(10062, "CERT_HUNTING_CAMOFLAUGE_ROBE_DESERT", "cert_hunting_camoflauge_robe_desert", "objtypes"),
            new GamevalEntry(10063, "HUNTING_TROUSERS_DESERT", "Desert camo legs", "objtypes"),
            new GamevalEntry(10064, "CERT_HUNTING_TROUSERS_DESERT", "cert_hunting_trousers_desert", "objtypes"),
            new GamevalEntry(10065, "HUNTING_CAMOFLAUGE_ROBE_POLAR", "Polar camo top", "objtypes"),
            new GamevalEntry(10066, "CERT_HUNTING_CAMOFLAUGE_ROBE_POLAR", "cert_hunting_camoflauge_robe_polar", "objtypes"),
            new GamevalEntry(10067, "HUNTING_TROUSERS_POLAR", "Polar camo legs", "objtypes"),
            new GamevalEntry(10068, "CERT_HUNTING_TROUSERS_POLAR", "cert_hunting_trousers_polar", "objtypes"),
            new GamevalEntry(10069, "HUNTING_LIGHT_CAPE", "Spotted cape", "objtypes"),
            new GamevalEntry(10070, "CERT_HUNTING_LIGHT_CAPE", "cert_hunting_light_cape", "objtypes"),
            new GamevalEntry(10071, "HUNTING_LIGHTER_CAPE", "Spottier cape", "objtypes"),
            new GamevalEntry(10072, "CERT_HUNTING_LIGHTER_CAPE", "cert_hunting_lighter_cape", "objtypes"),
            new GamevalEntry(10073, "HUNTING_LIGHT_CAPE_WORN", "Spotted cape", "objtypes"),
            new GamevalEntry(10074, "HUNTING_LIGHTER_CAPE_WORN", "Spottier cape", "objtypes"),
            new GamevalEntry(10075, "HUNTING_SILENT_GLOVES", "Gloves of silence", "objtypes"),
            new GamevalEntry(10076, "CERT_HUNTING_SILENT_GLOVES", "cert_hunting_silent_gloves", "objtypes"),
            new GamevalEntry(10077, "SPIKED_VAMBRACES", "Spiky vambraces", "objtypes"),
            new GamevalEntry(10078, "CERT_SPIKED_VAMBRACES", "cert_spiked_vambraces", "objtypes"),
            new GamevalEntry(10079, "HUNTING_GREEN_SPIKED_VAMBRACES", "Green spiky vambraces", "objtypes"),
            new GamevalEntry(10080, "CERT_HUNTING_GREEN_SPIKED_VAMBRACES", "cert_hunting_green_spiked_vambraces", "objtypes"),
            new GamevalEntry(10081, "HUNTING_BLUE_SPIKED_VAMBRACES", "Blue spiky vambraces", "objtypes"),
            new GamevalEntry(10082, "CERT_HUNTING_BLUE_SPIKED_VAMBRACES", "cert_hunting_blue_spiked_vambraces", "objtypes"),
            new GamevalEntry(10083, "HUNTING_RED_SPIKED_VAMBRACES", "Red spiky vambraces", "objtypes"),
            new GamevalEntry(10084, "CERT_HUNTING_RED_SPIKED_VAMBRACES", "cert_hunting_red_spiked_vambraces", "objtypes"),
            new GamevalEntry(10085, "HUNTING_BLACK_SPIKED_VAMBRACES", "Black spiky vambraces", "objtypes"),
            new GamevalEntry(10086, "CERT_HUNTING_BLACK_SPIKED_VAMBRACES", "cert_hunting_black_spiked_vambraces", "objtypes"),
            new GamevalEntry(10087, "HUNTING_STRIPY_BIRD_FEATHER", "Stripy feather", "objtypes"),
            new GamevalEntry(10088, "HUNTING_JUNGLE_FEATHER", "Red feather", "objtypes"),
            new GamevalEntry(10089, "HUNTING_POLAR_FEATHER", "Blue feather", "objtypes"),
            new GamevalEntry(10090, "HUNTING_DESERT_FEATHER", "Yellow feather", "objtypes"),
            new GamevalEntry(10091, "HUNTING_WOODLAND_FEATHER", "Orange feather", "objtypes"),
            new GamevalEntry(10092, "HUNTING_FERRET", "Ferret", "objtypes"),
            new GamevalEntry(10093, "HUNTING_FUR_JAGUAR_SHABBY", "Tatty larupia fur", "objtypes"),
            new GamevalEntry(10094, "CERT_HUNTING_FUR_JAGUAR_SHABBY", "cert_hunting_fur_jaguar_shabby", "objtypes"),
            new GamevalEntry(10095, "HUNTING_FUR_JAGUAR_PERFECT", "Larupia fur", "objtypes"),
            new GamevalEntry(10096, "CERT_HUNTING_FUR_JAGUAR_PERFECT", "cert_hunting_fur_jaguar_perfect", "objtypes"),
            new GamevalEntry(10097, "HUNTING_FUR_LEOPARD_SHABBY", "Tatty graahk fur", "objtypes"),
            new GamevalEntry(10098, "CERT_HUNTING_FUR_LEOPARD_SHABBY", "cert_hunting_fur_leopard_shabby", "objtypes"),
            new GamevalEntry(10099, "HUNTING_FUR_LEOPARD_PERFECT", "Graahk fur", "objtypes"),
            new GamevalEntry(10100, "CERT_HUNTING_FUR_LEOPARD_PERFECT", "cert_hunting_fur_leopard_perfect", "objtypes"),
            new GamevalEntry(10101, "HUNTING_FUR_TIGER_SHABBY", "Tatty kyatt fur", "objtypes"),
            new GamevalEntry(10102, "CERT_HUNTING_FUR_TIGER_SHABBY", "cert_hunting_fur_tiger_shabby", "objtypes"),
            new GamevalEntry(10103, "HUNTING_FUR_TIGER_PERFECT", "Kyatt fur", "objtypes"),
            new GamevalEntry(10104, "CERT_HUNTING_FUR_TIGER_PERFECT", "cert_hunting_fur_tiger_perfect", "objtypes"),
            new GamevalEntry(10105, "HUNTINGBEAST_SPIKE", "Kebbit spike", "objtypes"),
            new GamevalEntry(10106, "CERT_HUNTINGBEAST_SPIKE", "cert_huntingbeast_spike", "objtypes"),
            new GamevalEntry(10107, "HUNTINGBEAST_BIGSPIKE", "Long kebbit spike", "objtypes"),
            new GamevalEntry(10108, "CERT_HUNTINGBEAST_BIGSPIKE", "cert_huntingbeast_bigspike", "objtypes"),
            new GamevalEntry(10109, "HUNTINGBEAST_SABRETEETH", "Kebbit teeth", "objtypes"),
            new GamevalEntry(10110, "CERT_HUNTINGBEAST_SABRETEETH", "cert_huntingbeast_sabreteeth", "objtypes"),
            new GamevalEntry(10111, "HUNTINGBEAST_SABRETEETH_DUST", "Kebbit teeth dust", "objtypes"),
            new GamevalEntry(10112, "CERT_HUNTINGBEAST_SABRETEETH_DUST", "cert_huntingbeast_sabreteeth_dust", "objtypes"),
            new GamevalEntry(10113, "HUNTINGBEAST_CLAWS", "Kebbit claws", "objtypes"),
            new GamevalEntry(10114, "CERT_HUNTINGBEAST_CLAWS", "cert_huntingbeast_claws", "objtypes"),
            new GamevalEntry(10115, "HUNTINGBEAST_SILENT_FUR", "Dark kebbit fur", "objtypes"),
            new GamevalEntry(10116, "CERT_HUNTINGBEAST_SILENT_FUR", "cert_huntingbeast_silent_fur", "objtypes"),
            new GamevalEntry(10117, "HUNTINGBEAST_POLAR_FUR", "Polar kebbit fur", "objtypes"),
            new GamevalEntry(10118, "CERT_HUNTINGBEAST_POLAR_FUR", "cert_huntingbeast_polar_fur", "objtypes"),
            new GamevalEntry(10119, "HUNTINGBEAST_JUNGLE_FUR", "Feldip weasel fur", "objtypes"),
            new GamevalEntry(10120, "CERT_HUNTINGBEAST_JUNGLE_FUR", "cert_huntingbeast_jungle_fur", "objtypes"),
            new GamevalEntry(10121, "HUNTINGBEAST_WOODLAND_FUR", "Common kebbit fur", "objtypes"),
            new GamevalEntry(10122, "CERT_HUNTINGBEAST_WOODLAND_FUR", "cert_huntingbeast_woodland_fur", "objtypes"),
            new GamevalEntry(10123, "HUNTINGBEAST_DESERT_FUR", "Desert devil fur", "objtypes"),
            new GamevalEntry(10124, "CERT_HUNTINGBEAST_DESERT_FUR", "cert_huntingbeast_desert_fur", "objtypes"),
            new GamevalEntry(10125, "HUNTINGBEAST_SPEEDY_FUR", "Spotted kebbit fur", "objtypes"),
            new GamevalEntry(10126, "CERT_HUNTINGBEAST_SPEEDY_FUR", "cert_huntingbeast_speedy_fur", "objtypes"),
            new GamevalEntry(10127, "HUNTINGBEAST_SPEEDY2_FUR", "Dashing kebbit fur", "objtypes"),
            new GamevalEntry(10128, "CERT_HUNTINGBEAST_SPEEDY2_FUR", "cert_huntingbeast_speedy2_fur", "objtypes"),
            new GamevalEntry(10129, "HUNTING_BARBED_HARPOON", "Barb-tail harpoon", "objtypes"),
            new GamevalEntry(10130, "CERT_HUNTING_BARBED_HARPOON", "cert_hunting_barbed_harpoon", "objtypes"),
            new GamevalEntry(10131, "HUNTING_BARBED_HARPOON_USING", "hunting_barbed_harpoon_using", "objtypes"),
            new GamevalEntry(10132, "HUNTING_STRUNG_RABBIT_FOOT", "Strung rabbit foot", "objtypes"),
            new GamevalEntry(10133, "CERT_HUNTING_STRUNG_RABBIT_FOOT", "cert_hunting_strung_rabbit_foot", "objtypes"),
            new GamevalEntry(10134, "HUNTING_RABBIT_FOOT", "Rabbit foot", "objtypes"),
            new GamevalEntry(10135, "CERT_HUNTING_RABBIT_FOOT", "cert_hunting_rabbit_foot", "objtypes"),
            new GamevalEntry(10136, "HUNTING_FISH_SPECIAL", "Rainbow fish", "objtypes"),
            new GamevalEntry(10137, "CERT_HUNTING_FISH_SPECIAL", "cert_hunting_fish_special", "objtypes"),
            new GamevalEntry(10138, "HUNTING_RAW_FISH_SPECIAL", "Raw rainbow fish", "objtypes"),
            new GamevalEntry(10139, "CERT_HUNTING_RAW_FISH_SPECIAL", "cert_hunting_raw_fish_special", "objtypes"),
            new GamevalEntry(10140, "HUNTING_RAW_FISH_SPECIAL_BURNT", "Burnt rainbow fish", "objtypes"),
            new GamevalEntry(10141, "CERT_HUNTING_RAW_FISH_SPECIAL_BURNT", "cert_hunting_raw_fish_special_burnt", "objtypes"),
            new GamevalEntry(10142, "SALAMANDER_TAR_GREEN", "Guam tar", "objtypes"),
            new GamevalEntry(10143, "SALAMANDER_TAR_ORANGE", "Marrentill tar", "objtypes"),
            new GamevalEntry(10144, "SALAMANDER_TAR_RED", "Tarromin tar", "objtypes"),
            new GamevalEntry(10145, "SALAMANDER_TAR_BLACK", "Harralander tar", "objtypes"),
            new GamevalEntry(10146, "ORANGE_SALAMANDER", "Orange salamander", "objtypes"),
            new GamevalEntry(10147, "RED_SALAMANDER", "Red salamander", "objtypes"),
            new GamevalEntry(10148, "BLACK_SALAMANDER", "Black salamander", "objtypes"),
            new GamevalEntry(10149, "GREEN_SALAMANDER", "Swamp lizard", "objtypes"),
            new GamevalEntry(10150, "NOOSE_WAND", "Noose wand", "objtypes"),
            new GamevalEntry(10151, "CERT_NOOSE_WAND", "cert_noose_wand", "objtypes"),
            new GamevalEntry(10152, "NOOSE_WAND_WOOD", "noose_wand_wood", "objtypes"),
            new GamevalEntry(10153, "NOOSE_WAND_POLAR", "noose_wand_polar", "objtypes"),
            new GamevalEntry(10154, "NOOSE_WAND_DESERT", "noose_wand_desert", "objtypes"),
            new GamevalEntry(10155, "NOOSE_WAND_JUNGLE", "noose_wand_jungle", "objtypes"),
            new GamevalEntry(10156, "HUNTING_CROSSBOW", "Hunters' crossbow", "objtypes"),
            new GamevalEntry(10157, "CERT_HUNTING_CROSSBOW", "cert_hunting_crossbow", "objtypes"),
            new GamevalEntry(10158, "HUNTINGBOW_BOLTS", "Kebbit bolts", "objtypes"),
            new GamevalEntry(10159, "HUNTINGBOW_BIGBOLTS", "Long kebbit bolts", "objtypes"),
            new GamevalEntry(10160, "CERT_ORANGE_SALAMANDER", "cert_orange_salamander", "objtypes"),
            new GamevalEntry(10161, "CERT_RED_SALAMANDER", "cert_red_salamander", "objtypes"),
            new GamevalEntry(10162, "CERT_BLACK_SALAMANDER", "cert_black_salamander", "objtypes"),
            new GamevalEntry(10163, "CERT_GREEN_SALAMANDER", "cert_green_salamander", "objtypes"),
            new GamevalEntry(10164, "HUNTING_LASSO", "hunting_lasso", "objtypes"),
            new GamevalEntry(10165, "POH_DUMMY_COSTUME_ROOM_MORE", "poh_dummy_costume_room_more", "objtypes"),
            new GamevalEntry(10166, "POH_DUMMY_COSTUME_ROOM_BACK", "poh_dummy_costume_room_back", "objtypes"),
            new GamevalEntry(10167, "HUNTING_EAGLE_FEATHER", "Eagle feather", "objtypes"),
            new GamevalEntry(10168, "HUNTING_EAGLE_FEATHERS2", "hunting_eagle_feathers2", "objtypes"),
            new GamevalEntry(10169, "HUNTING_EAGLE_FEATHERS3", "hunting_eagle_feathers3", "objtypes"),
            new GamevalEntry(10170, "HUNTING_EAGLE_FEATHERS4", "hunting_eagle_feathers4", "objtypes"),
            new GamevalEntry(10171, "HUNTING_EAGLE_CAPE", "Eagle cape", "objtypes"),
            new GamevalEntry(10172, "HUNTING_FAKE_BEAK", "Fake beak", "objtypes"),
            new GamevalEntry(10173, "HUNTING_BOOK_OF_BIRDS", "Bird book", "objtypes"),
            new GamevalEntry(10174, "EAGLEPEAK_METAL_FEATHER", "Metal feather", "objtypes"),
            new GamevalEntry(10175, "EAGLEPEAK_CRYSTAL_FEATHER1", "Golden feather", "objtypes"),
            new GamevalEntry(10176, "EAGLEPEAK_CRYSTAL_FEATHER2", "Silver feather", "objtypes"),
            new GamevalEntry(10177, "EAGLEPEAK_CRYSTAL_FEATHER3", "Bronze feather", "objtypes"),
            new GamevalEntry(10178, "EAGLEPEAK_BIRD_SEED", "Odd bird seed", "objtypes"),
            new GamevalEntry(10179, "EP_TRANSPORT_BOOK01", "Feathered journal", "objtypes"),
            new GamevalEntry(10180, "TRAIL_CLUE_EASY_EMOTE001", "Clue scroll (easy)", "objtypes"),
            new GamevalEntry(10181, "TRAIL_CLUE_EASY_EMOTE001_CASKET", "Casket (easy)", "objtypes"),
            new GamevalEntry(10182, "TRAIL_CLUE_EASY_EMOTE002", "Clue scroll (easy)", "objtypes"),
            new GamevalEntry(10183, "TRAIL_CLUE_EASY_EMOTE002_CASKET", "Casket (easy)", "objtypes"),
            new GamevalEntry(10184, "TRAIL_CLUE_EASY_EMOTE003", "Clue scroll (easy)", "objtypes"),
            new GamevalEntry(10185, "TRAIL_CLUE_EASY_EMOTE003_CASKET", "Casket (easy)", "objtypes"),
            new GamevalEntry(10186, "TRAIL_CLUE_EASY_EMOTE004", "Clue scroll (easy)", "objtypes"),
            new GamevalEntry(10187, "TRAIL_CLUE_EASY_EMOTE004_CASKET", "Casket (easy)", "objtypes"),
            new GamevalEntry(10188, "TRAIL_CLUE_EASY_EMOTE005", "Clue scroll (easy)", "objtypes"),
            new GamevalEntry(10189, "TRAIL_CLUE_EASY_EMOTE005_CASKET", "Casket (easy)", "objtypes"),
            new GamevalEntry(10190, "TRAIL_CLUE_EASY_EMOTE006", "Clue scroll (easy)", "objtypes"),
            new GamevalEntry(10191, "TRAIL_CLUE_EASY_EMOTE006_CASKET", "Casket (easy)", "objtypes"),
            new GamevalEntry(10192, "TRAIL_CLUE_EASY_EMOTE007", "Clue scroll (easy)", "objtypes"),
            new GamevalEntry(10193, "TRAIL_CLUE_EASY_EMOTE007_CASKET", "Casket (easy)", "objtypes"),
            new GamevalEntry(10194, "TRAIL_CLUE_EASY_EMOTE008", "Clue scroll (easy)", "objtypes"),
            new GamevalEntry(10195, "TRAIL_CLUE_EASY_EMOTE008_CASKET", "Casket (easy)", "objtypes"),
            new GamevalEntry(10196, "TRAIL_CLUE_EASY_EMOTE009", "Clue scroll (easy)", "objtypes"),
            new GamevalEntry(10197, "TRAIL_CLUE_EASY_EMOTE009_CASKET", "Casket (easy)", "objtypes"),
            new GamevalEntry(10198, "TRAIL_CLUE_EASY_EMOTE010", "Clue scroll (easy)", "objtypes"),
            new GamevalEntry(10199, "TRAIL_CLUE_EASY_EMOTE010_CASKET", "Casket (easy)", "objtypes"),
            new GamevalEntry(10200, "TRAIL_CLUE_EASY_EMOTE011", "Clue scroll (easy)", "objtypes"),
            new GamevalEntry(10201, "TRAIL_CLUE_EASY_EMOTE011_CASKET", "Casket (easy)", "objtypes"),
            new GamevalEntry(10202, "TRAIL_CLUE_EASY_EMOTE012", "Clue scroll (easy)", "objtypes"),
            new GamevalEntry(10203, "TRAIL_CLUE_EASY_EMOTE012_CASKET", "Casket (easy)", "objtypes"),
            new GamevalEntry(10204, "TRAIL_CLUE_EASY_EMOTE013", "Clue scroll (easy)", "objtypes"),
            new GamevalEntry(10205, "TRAIL_CLUE_EASY_EMOTE013_CASKET", "Casket (easy)", "objtypes"),
            new GamevalEntry(10206, "TRAIL_CLUE_EASY_EMOTE014", "Clue scroll (easy)", "objtypes"),
            new GamevalEntry(10207, "TRAIL_CLUE_EASY_EMOTE014_CASKET", "Casket (easy)", "objtypes"),
            new GamevalEntry(10208, "TRAIL_CLUE_EASY_EMOTE015", "Clue scroll (easy)", "objtypes"),
            new GamevalEntry(10209, "TRAIL_CLUE_EASY_EMOTE015_CASKET", "Casket (easy)", "objtypes"),
            new GamevalEntry(10210, "TRAIL_CLUE_EASY_EMOTE016", "Clue scroll (easy)", "objtypes"),
            new GamevalEntry(10211, "TRAIL_CLUE_EASY_EMOTE016_CASKET", "Casket (easy)", "objtypes"),
            new GamevalEntry(10212, "TRAIL_CLUE_EASY_EMOTE017", "Clue scroll (easy)", "objtypes"),
            new GamevalEntry(10213, "TRAIL_CLUE_EASY_EMOTE017_CASKET", "Casket (easy)", "objtypes"),
            new GamevalEntry(10214, "TRAIL_CLUE_EASY_EMOTE018", "Clue scroll (easy)", "objtypes"),
            new GamevalEntry(10215, "TRAIL_CLUE_EASY_EMOTE018_CASKET", "Casket (easy)", "objtypes"),
            new GamevalEntry(10216, "TRAIL_CLUE_EASY_EMOTE019", "Clue scroll (easy)", "objtypes"),
            new GamevalEntry(10217, "TRAIL_CLUE_EASY_EMOTE019_CASKET", "Casket (easy)", "objtypes"),
            new GamevalEntry(10218, "TRAIL_CLUE_EASY_EMOTE020", "Clue scroll (easy)", "objtypes"),
            new GamevalEntry(10219, "TRAIL_CLUE_EASY_EMOTE020_CASKET", "Casket (easy)", "objtypes"),
            new GamevalEntry(10220, "TRAIL_CLUE_EASY_EMOTE021", "Clue scroll (easy)", "objtypes"),
            new GamevalEntry(10221, "TRAIL_CLUE_EASY_EMOTE021_CASKET", "Casket (easy)", "objtypes"),
            new GamevalEntry(10222, "TRAIL_CLUE_EASY_EMOTE022", "Clue scroll (easy)", "objtypes"),
            new GamevalEntry(10223, "TRAIL_CLUE_EASY_EMOTE022_CASKET", "Casket (easy)", "objtypes"),
            new GamevalEntry(10224, "TRAIL_CLUE_EASY_EMOTE023", "Clue scroll (easy)", "objtypes"),
            new GamevalEntry(10225, "TRAIL_CLUE_EASY_EMOTE023_CASKET", "Casket (easy)", "objtypes"),
            new GamevalEntry(10226, "TRAIL_CLUE_EASY_EMOTE024", "Clue scroll (easy)", "objtypes"),
            new GamevalEntry(10227, "TRAIL_CLUE_EASY_EMOTE024_CASKET", "Casket (easy)", "objtypes"),
            new GamevalEntry(10228, "TRAIL_CLUE_EASY_EMOTE025", "Clue scroll (easy)", "objtypes"),
            new GamevalEntry(10229, "TRAIL_CLUE_EASY_EMOTE025_CASKET", "Casket (easy)", "objtypes"),
            new GamevalEntry(10230, "TRAIL_CLUE_EASY_EMOTE026", "Clue scroll (easy)", "objtypes"),
            new GamevalEntry(10231, "TRAIL_CLUE_EASY_EMOTE026_CASKET", "Casket (easy)", "objtypes"),
            new GamevalEntry(10232, "TRAIL_CLUE_EASY_EMOTE027", "Clue scroll (easy)", "objtypes"),
            new GamevalEntry(10233, "TRAIL_CLUE_EASY_EMOTE027_CASKET", "Casket (easy)", "objtypes"),
            new GamevalEntry(10234, "TRAIL_CLUE_HARD_EMOTE001", "Clue scroll (hard)", "objtypes"),
            new GamevalEntry(10235, "TRAIL_CLUE_HARD_EMOTE001_CASKET", "Casket (hard)", "objtypes"),
            new GamevalEntry(10236, "TRAIL_CLUE_HARD_EMOTE002", "Clue scroll (hard)", "objtypes"),
            new GamevalEntry(10237, "TRAIL_CLUE_HARD_EMOTE002_CASKET", "Casket (hard)", "objtypes"),
            new GamevalEntry(10238, "TRAIL_CLUE_HARD_EMOTE003", "Clue scroll (hard)", "objtypes"),
            new GamevalEntry(10239, "TRAIL_CLUE_HARD_EMOTE003_CASKET", "Casket (hard)", "objtypes"),
            new GamevalEntry(10240, "TRAIL_CLUE_HARD_EMOTE004", "Clue scroll (hard)", "objtypes"),
            new GamevalEntry(10241, "TRAIL_CLUE_HARD_EMOTE004_CASKET", "Casket (hard)", "objtypes"),
            new GamevalEntry(10242, "TRAIL_CLUE_HARD_EMOTE005", "Clue scroll (hard)", "objtypes"),
            new GamevalEntry(10243, "TRAIL_CLUE_HARD_EMOTE005_CASKET", "Casket (hard)", "objtypes"),
            new GamevalEntry(10244, "TRAIL_CLUE_HARD_EMOTE006", "Clue scroll (hard)", "objtypes"),
            new GamevalEntry(10245, "TRAIL_CLUE_HARD_EMOTE006_CASKET", "Casket (hard)", "objtypes"),
            new GamevalEntry(10246, "TRAIL_CLUE_HARD_EMOTE007", "Clue scroll (hard)", "objtypes"),
            new GamevalEntry(10247, "TRAIL_CLUE_HARD_EMOTE007_CASKET", "Casket (hard)", "objtypes"),
            new GamevalEntry(10248, "TRAIL_CLUE_HARD_EMOTE008", "Clue scroll (hard)", "objtypes"),
            new GamevalEntry(10249, "TRAIL_CLUE_HARD_EMOTE008_CASKET", "Casket (hard)", "objtypes"),
            new GamevalEntry(10250, "TRAIL_CLUE_HARD_EMOTE009", "Clue scroll (hard)", "objtypes"),
            new GamevalEntry(10251, "TRAIL_CLUE_HARD_EMOTE009_CASKET", "Casket (hard)", "objtypes"),
            new GamevalEntry(10252, "TRAIL_CLUE_HARD_EMOTE010", "Clue scroll (hard)", "objtypes"),
            new GamevalEntry(10253, "TRAIL_CLUE_HARD_EMOTE010_CASKET", "Casket (hard)", "objtypes"),
            new GamevalEntry(10254, "TRAIL_CLUE_MEDIUM_EMOTE001", "Clue scroll (medium)", "objtypes"),
            new GamevalEntry(10255, "TRAIL_CLUE_MEDIUM_EMOTE001_CASKET", "Casket (medium)", "objtypes"),
            new GamevalEntry(10256, "TRAIL_CLUE_MEDIUM_EMOTE002", "Clue scroll (medium)", "objtypes"),
            new GamevalEntry(10257, "TRAIL_CLUE_MEDIUM_EMOTE002_CASKET", "Casket (medium)", "objtypes"),
            new GamevalEntry(10258, "TRAIL_CLUE_MEDIUM_EMOTE003", "Clue scroll (medium)", "objtypes"),
            new GamevalEntry(10259, "TRAIL_CLUE_MEDIUM_EMOTE003_CASKET", "Casket (medium)", "objtypes"),
            new GamevalEntry(10260, "TRAIL_CLUE_MEDIUM_EMOTE004", "Clue scroll (medium)", "objtypes"),
            new GamevalEntry(10261, "TRAIL_CLUE_MEDIUM_EMOTE004_CASKET", "Casket (medium)", "objtypes"),
            new GamevalEntry(10262, "TRAIL_CLUE_MEDIUM_EMOTE005", "Clue scroll (medium)", "objtypes"),
            new GamevalEntry(10263, "TRAIL_CLUE_MEDIUM_EMOTE005_CASKET", "Casket (medium)", "objtypes"),
            new GamevalEntry(10264, "TRAIL_CLUE_MEDIUM_EMOTE006", "Clue scroll (medium)", "objtypes"),
            new GamevalEntry(10265, "TRAIL_CLUE_MEDIUM_EMOTE006_CASKET", "Casket (medium)", "objtypes"),
            new GamevalEntry(10266, "TRAIL_CLUE_MEDIUM_EMOTE007", "Clue scroll (medium)", "objtypes"),
            new GamevalEntry(10267, "TRAIL_CLUE_MEDIUM_EMOTE007_CASKET", "Casket (medium)", "objtypes"),
            new GamevalEntry(10268, "TRAIL_CLUE_MEDIUM_EMOTE008", "Clue scroll (medium)", "objtypes"),
            new GamevalEntry(10269, "TRAIL_CLUE_MEDIUM_EMOTE008_CASKET", "Casket (medium)", "objtypes"),
            new GamevalEntry(10270, "TRAIL_CLUE_MEDIUM_EMOTE009", "Clue scroll (medium)", "objtypes"),
            new GamevalEntry(10271, "TRAIL_CLUE_MEDIUM_EMOTE009_CASKET", "Casket (medium)", "objtypes"),
            new GamevalEntry(10272, "TRAIL_CLUE_MEDIUM_EMOTE010", "Clue scroll (medium)", "objtypes"),
            new GamevalEntry(10273, "TRAIL_CLUE_MEDIUM_EMOTE010_CASKET", "Casket (medium)", "objtypes"),
            new GamevalEntry(10274, "TRAIL_CLUE_MEDIUM_EMOTE011", "Clue scroll (medium)", "objtypes"),
            new GamevalEntry(10275, "TRAIL_CLUE_MEDIUM_EMOTE011_CASKET", "Casket (medium)", "objtypes"),
            new GamevalEntry(10276, "TRAIL_CLUE_MEDIUM_EMOTE012", "Clue scroll (medium)", "objtypes"),
            new GamevalEntry(10277, "TRAIL_CLUE_MEDIUM_EMOTE012_CASKET", "Casket (medium)", "objtypes"),
            new GamevalEntry(10278, "TRAIL_CLUE_MEDIUM_EMOTE013", "Clue scroll (medium)", "objtypes"),
            new GamevalEntry(10279, "TRAIL_CLUE_MEDIUM_EMOTE013_CASKET", "Casket (medium)", "objtypes"),
            new GamevalEntry(10280, "TRAIL_COMPOSITE_BOW_WILLOW", "Willow comp bow", "objtypes"),
            new GamevalEntry(10281, "CERT_TRAIL_COMPOSITE_BOW_WILLOW", "cert_trail_composite_bow_willow", "objtypes"),
            new GamevalEntry(10282, "TRAIL_COMPOSITE_BOW_YEW", "Yew comp bow", "objtypes"),
            new GamevalEntry(10283, "CERT_TRAIL_COMPOSITE_BOW_YEW", "cert_trail_composite_bow_yew", "objtypes"),
            new GamevalEntry(10284, "TRAIL_COMPOSITE_BOW_MAGIC", "Magic comp bow", "objtypes"),
            new GamevalEntry(10285, "CERT_TRAIL_COMPOSITE_BOW_MAGIC", "cert_trail_composite_bow_magic", "objtypes"),
            new GamevalEntry(10286, "TRAIL_HERALDIC_HELM_1_RUNE", "Rune helm (h1)", "objtypes"),
            new GamevalEntry(10287, "CERT_TRAIL_HERALDIC_HELM_1_RUNE", "cert_trail_heraldic_helm_1_rune", "objtypes"),
            new GamevalEntry(10288, "TRAIL_HERALDIC_HELM_2_RUNE", "Rune helm (h2)", "objtypes"),
            new GamevalEntry(10289, "CERT_TRAIL_HERALDIC_HELM_2_RUNE", "cert_trail_heraldic_helm_2_rune", "objtypes"),
            new GamevalEntry(10290, "TRAIL_HERALDIC_HELM_3_RUNE", "Rune helm (h3)", "objtypes"),
            new GamevalEntry(10291, "CERT_TRAIL_HERALDIC_HELM_3_RUNE", "cert_trail_heraldic_helm_3_rune", "objtypes"),
            new GamevalEntry(10292, "TRAIL_HERALDIC_HELM_4_RUNE", "Rune helm (h4)", "objtypes"),
            new GamevalEntry(10293, "CERT_TRAIL_HERALDIC_HELM_4_RUNE", "cert_trail_heraldic_helm_4_rune", "objtypes"),
            new GamevalEntry(10294, "TRAIL_HERALDIC_HELM_5_RUNE", "Rune helm (h5)", "objtypes"),
            new GamevalEntry(10295, "CERT_TRAIL_HERALDIC_HELM_5_RUNE", "cert_trail_heraldic_helm_5_rune", "objtypes"),
            new GamevalEntry(10296, "TRAIL_HERALDIC_HELM_1_ADAMANT", "Adamant helm (h1)", "objtypes"),
            new GamevalEntry(10297, "CERT_TRAIL_HERALDIC_HELM_1_ADAMANT", "cert_trail_heraldic_helm_1_adamant", "objtypes"),
            new GamevalEntry(10298, "TRAIL_HERALDIC_HELM_2_ADAMANT", "Adamant helm (h2)", "objtypes"),
            new GamevalEntry(10299, "CERT_TRAIL_HERALDIC_HELM_2_ADAMANT", "cert_trail_heraldic_helm_2_adamant", "objtypes"),
            new GamevalEntry(10300, "TRAIL_HERALDIC_HELM_3_ADAMANT", "Adamant helm (h3)", "objtypes"),
            new GamevalEntry(10301, "CERT_TRAIL_HERALDIC_HELM_3_ADAMANT", "cert_trail_heraldic_helm_3_adamant", "objtypes"),
            new GamevalEntry(10302, "TRAIL_HERALDIC_HELM_4_ADAMANT", "Adamant helm (h4)", "objtypes"),
            new GamevalEntry(10303, "CERT_TRAIL_HERALDIC_HELM_4_ADAMANT", "cert_trail_heraldic_helm_4_adamant", "objtypes"),
            new GamevalEntry(10304, "TRAIL_HERALDIC_HELM_5_ADAMANT", "Adamant helm (h5)", "objtypes"),
            new GamevalEntry(10305, "CERT_TRAIL_HERALDIC_HELM_5_ADAMANT", "cert_trail_heraldic_helm_5_adamant", "objtypes"),
            new GamevalEntry(10306, "TRAIL_HERALDIC_HELM_1_BLACK", "Black helm (h1)", "objtypes"),
            new GamevalEntry(10307, "CERT_TRAIL_HERALDIC_HELM_1_BLACK", "cert_trail_heraldic_helm_1_black", "objtypes"),
            new GamevalEntry(10308, "TRAIL_HERALDIC_HELM_2_BLACK", "Black helm (h2)", "objtypes"),
            new GamevalEntry(10309, "CERT_TRAIL_HERALDIC_HELM_2_BLACK", "cert_trail_heraldic_helm_2_black", "objtypes"),
            new GamevalEntry(10310, "TRAIL_HERALDIC_HELM_3_BLACK", "Black helm (h3)", "objtypes"),
            new GamevalEntry(10311, "CERT_TRAIL_HERALDIC_HELM_3_BLACK", "cert_trail_heraldic_helm_3_black", "objtypes"),
            new GamevalEntry(10312, "TRAIL_HERALDIC_HELM_4_BLACK", "Black helm (h4)", "objtypes"),
            new GamevalEntry(10313, "CERT_TRAIL_HERALDIC_HELM_4_BLACK", "cert_trail_heraldic_helm_4_black", "objtypes"),
            new GamevalEntry(10314, "TRAIL_HERALDIC_HELM_5_BLACK", "Black helm (h5)", "objtypes"),
            new GamevalEntry(10315, "CERT_TRAIL_HERALDIC_HELM_5_BLACK", "cert_trail_heraldic_helm_5_black", "objtypes"),
            new GamevalEntry(10316, "TRAIL_BOB_SHIRT_RED", "Bob's red shirt", "objtypes"),
            new GamevalEntry(10317, "CERT_TRAIL_BOB_SHIRT_RED", "cert_trail_bob_shirt_red", "objtypes"),
            new GamevalEntry(10318, "TRAIL_BOB_SHIRT_BLUE", "Bob's blue shirt", "objtypes"),
            new GamevalEntry(10319, "CERT_TRAIL_BOB_SHIRT_BLUE", "cert_trail_bob_shirt_blue", "objtypes"),
            new GamevalEntry(10320, "TRAIL_BOB_SHIRT_GREEN", "Bob's green shirt", "objtypes"),
            new GamevalEntry(10321, "CERT_TRAIL_BOB_SHIRT_GREEN", "cert_trail_bob_shirt_green", "objtypes"),
            new GamevalEntry(10322, "TRAIL_BOB_SHIRT_BLACK", "Bob's black shirt", "objtypes"),
            new GamevalEntry(10323, "CERT_TRAIL_BOB_SHIRT_BLACK", "cert_trail_bob_shirt_black", "objtypes"),
            new GamevalEntry(10324, "TRAIL_BOB_SHIRT_PURPLE", "Bob's purple shirt", "objtypes"),
            new GamevalEntry(10325, "CERT_TRAIL_BOB_SHIRT_PURPLE", "cert_trail_bob_shirt_purple", "objtypes"),
            new GamevalEntry(10326, "TRAIL_GNOMISH_FIRELIGHTER_PURPLE", "Purple firelighter", "objtypes"),
            new GamevalEntry(10327, "TRAIL_GNOMISH_FIRELIGHTER_WHITE", "White firelighter", "objtypes"),
            new GamevalEntry(10328, "TRAIL_LOGS_WHITE", "White logs", "objtypes"),
            new GamevalEntry(10329, "TRAIL_LOGS_PURPLE", "Purple logs", "objtypes"),
            new GamevalEntry(10330, "TRAIL_RANGER_TORSO", "3rd age range top", "objtypes"),
            new GamevalEntry(10331, "CERT_TRAIL_RANGER_TORSO", "cert_trail_ranger_torso", "objtypes"),
            new GamevalEntry(10332, "TRAIL_RANGER_LEGS", "3rd age range legs", "objtypes"),
            new GamevalEntry(10333, "CERT_TRAIL_RANGER_LEGS", "cert_trail_ranger_legs", "objtypes"),
            new GamevalEntry(10334, "TRAIL_RANGER_COIF", "3rd age range coif", "objtypes"),
            new GamevalEntry(10335, "CERT_TRAIL_RANGER_COIF", "cert_trail_ranger_coif", "objtypes"),
            new GamevalEntry(10336, "TRAIL_RANGER_VAMBRACES", "3rd age vambraces", "objtypes"),
            new GamevalEntry(10337, "CERT_TRAIL_RANGER_VAMBRACES", "cert_trail_ranger_vambraces", "objtypes"),
            new GamevalEntry(10338, "TRAIL_MAGE_TORSO", "3rd age robe top", "objtypes"),
            new GamevalEntry(10339, "CERT_TRAIL_MAGE_TORSO", "cert_trail_mage_torso", "objtypes"),
            new GamevalEntry(10340, "TRAIL_MAGE_LEGS", "3rd age robe", "objtypes"),
            new GamevalEntry(10341, "CERT_TRAIL_MAGE_LEGS", "cert_trail_mage_legs", "objtypes"),
            new GamevalEntry(10342, "TRAIL_MAGE_HAT", "3rd age mage hat", "objtypes"),
            new GamevalEntry(10343, "CERT_TRAIL_MAGE_HAT", "cert_trail_mage_hat", "objtypes"),
            new GamevalEntry(10344, "TRAIL_MAGE_AMULET", "3rd age amulet", "objtypes"),
            new GamevalEntry(10345, "CERT_TRAIL_MAGE_AMULET", "cert_trail_mage_amulet", "objtypes"),
            new GamevalEntry(10346, "TRAIL_SILVER_PLATE_LEGS", "3rd age platelegs", "objtypes"),
            new GamevalEntry(10347, "CERT_TRAIL_SILVER_PLATE_LEGS", "cert_trail_silver_plate_legs", "objtypes"),
            new GamevalEntry(10348, "TRAIL_SILVER_PLATE_CHEST", "3rd age platebody", "objtypes"),
            new GamevalEntry(10349, "CERT_TRAIL_SILVER_PLATE_CHEST", "cert_trail_silver_plate_chest", "objtypes"),
            new GamevalEntry(10350, "TRAIL_FIGHTER_HELM", "3rd age full helmet", "objtypes"),
            new GamevalEntry(10351, "CERT_TRAIL_FIGHTER_HELM", "cert_trail_fighter_helm", "objtypes"),
            new GamevalEntry(10352, "TRAIL_FIGHTER_SHIELD", "3rd age kiteshield", "objtypes"),
            new GamevalEntry(10353, "CERT_TRAIL_FIGHTER_SHIELD", "cert_trail_fighter_shield", "objtypes"),
            new GamevalEntry(10354, "TRAIL_AMULET_OF_GLORY_4", "Amulet of glory (t4)", "objtypes"),
            new GamevalEntry(10355, "CERT_TRAIL_AMULET_OF_GLORY_4", "cert_trail_amulet_of_glory_4", "objtypes"),
            new GamevalEntry(10356, "TRAIL_AMULET_OF_GLORY_3", "Amulet of glory (t3)", "objtypes"),
            new GamevalEntry(10357, "CERT_TRAIL_AMULET_OF_GLORY_3", "cert_trail_amulet_of_glory_3", "objtypes"),
            new GamevalEntry(10358, "TRAIL_AMULET_OF_GLORY_2", "Amulet of glory (t2)", "objtypes"),
            new GamevalEntry(10359, "CERT_TRAIL_AMULET_OF_GLORY_2", "cert_trail_amulet_of_glory_2", "objtypes"),
            new GamevalEntry(10360, "TRAIL_AMULET_OF_GLORY_1", "Amulet of glory (t1)", "objtypes"),
            new GamevalEntry(10361, "CERT_TRAIL_AMULET_OF_GLORY_1", "cert_trail_amulet_of_glory_1", "objtypes"),
            new GamevalEntry(10362, "TRAIL_AMULET_OF_GLORY", "Amulet of glory (t)", "objtypes"),
            new GamevalEntry(10363, "CERT_TRAIL_AMULET_OF_GLORY", "cert_trail_amulet_of_glory", "objtypes"),
            new GamevalEntry(10364, "TRAIL_AMULET_OF_STRENGTH", "Strength amulet (t)", "objtypes"),
            new GamevalEntry(10365, "CERT_TRAIL_AMULET_OF_STRENGTH", "cert_trail_amulet_of_strength", "objtypes"),
            new GamevalEntry(10366, "TRAIL_AMULET_OF_MAGIC", "Amulet of magic (t)", "objtypes"),
            new GamevalEntry(10367, "CERT_TRAIL_AMULET_OF_MAGIC", "cert_trail_amulet_of_magic", "objtypes"),
            new GamevalEntry(10368, "TRAIL_ZAMORAK_VAMBRACES", "Zamorak bracers", "objtypes"),
            new GamevalEntry(10369, "CERT_TRAIL_ZAMORAK_VAMBRACES", "cert_trail_zamorak_vambraces", "objtypes"),
            new GamevalEntry(10370, "TRAIL_ZAMORAK_CHEST", "Zamorak d'hide body", "objtypes"),
            new GamevalEntry(10371, "CERT_TRAIL_ZAMORAK_CHEST", "cert_trail_zamorak_chest", "objtypes"),
            new GamevalEntry(10372, "TRAIL_ZAMORAK_CHAPS", "Zamorak chaps", "objtypes"),
            new GamevalEntry(10373, "CERT_TRAIL_ZAMORAK_CHAPS", "cert_trail_zamorak_chaps", "objtypes"),
            new GamevalEntry(10374, "TRAIL_ZAMORAK_COIF", "Zamorak coif", "objtypes"),
            new GamevalEntry(10375, "CERT_TRAIL_ZAMORAK_COIF", "cert_trail_zamorak_coif", "objtypes"),
            new GamevalEntry(10376, "TRAIL_GUTHIX_VAMBRACES", "Guthix bracers", "objtypes"),
            new GamevalEntry(10377, "CERT_TRAIL_GUTHIX_VAMBRACES", "cert_trail_guthix_vambraces", "objtypes"),
            new GamevalEntry(10378, "TRAIL_GUTHIX_CHEST", "Guthix d'hide body", "objtypes"),
            new GamevalEntry(10379, "CERT_TRAIL_GUTHIX_CHEST", "cert_trail_guthix_chest", "objtypes"),
            new GamevalEntry(10380, "TRAIL_GUTHIX_CHAPS", "Guthix chaps", "objtypes"),
            new GamevalEntry(10381, "CERT_TRAIL_GUTHIX_CHAPS", "cert_trail_guthix_chaps", "objtypes"),
            new GamevalEntry(10382, "TRAIL_GUTHIX_COIF", "Guthix coif", "objtypes"),
            new GamevalEntry(10383, "CERT_TRAIL_GUTHIX_COIF", "cert_trail_guthix_coif", "objtypes"),
            new GamevalEntry(10384, "TRAIL_SARADOMIN_VAMBRACES", "Saradomin bracers", "objtypes"),
            new GamevalEntry(10385, "CERT_TRAIL_SARADOMIN_VAMBRACES", "cert_trail_saradomin_vambraces", "objtypes"),
            new GamevalEntry(10386, "TRAIL_SARADOMIN_CHEST", "Saradomin d'hide body", "objtypes"),
            new GamevalEntry(10387, "CERT_TRAIL_SARADOMIN_CHEST", "cert_trail_saradomin_chest", "objtypes"),
            new GamevalEntry(10388, "TRAIL_SARADOMIN_CHAPS", "Saradomin chaps", "objtypes"),
            new GamevalEntry(10389, "CERT_TRAIL_SARADOMIN_CHAPS", "cert_trail_saradomin_chaps", "objtypes"),
            new GamevalEntry(10390, "TRAIL_SARADOMIN_COIF", "Saradomin coif", "objtypes"),
            new GamevalEntry(10391, "CERT_TRAIL_SARADOMIN_COIF", "cert_trail_saradomin_coif", "objtypes"),
            new GamevalEntry(10392, "TRAIL_WIG", "A powdered wig", "objtypes"),
            new GamevalEntry(10393, "CERT_TRAIL_WIG", "cert_trail_wig", "objtypes"),
            new GamevalEntry(10394, "TRAIL_FLARED_PANTS", "Flared trousers", "objtypes"),
            new GamevalEntry(10395, "CERT_TRAIL_FLARED_PANTS", "cert_trail_flared_pants", "objtypes"),
            new GamevalEntry(10396, "TRAIL_PANTALOONS", "Pantaloons", "objtypes"),
            new GamevalEntry(10397, "CERT_TRAIL_PANTALOONS", "cert_trail_pantaloons", "objtypes"),
            new GamevalEntry(10398, "TRAIL_SLEEPING_CAP", "Sleeping cap", "objtypes"),
            new GamevalEntry(10399, "CERT_TRAIL_SLEEPING_CAP", "cert_trail_sleeping_cap", "objtypes"),
            new GamevalEntry(10400, "TRAIL_ELEGANT_SHIRT_MALE", "Black elegant shirt", "objtypes"),
            new GamevalEntry(10401, "CERT_TRAIL_ELEGANT_SHIRT_MALE", "cert_trail_elegant_shirt_male", "objtypes"),
            new GamevalEntry(10402, "TRAIL_ELEGANT_PANTS_MALE", "Black elegant legs", "objtypes"),
            new GamevalEntry(10403, "CERT_TRAIL_ELEGANT_PANTS_MALE", "cert_trail_elegant_pants_male", "objtypes"),
            new GamevalEntry(10404, "TRAIL_ELEGANT_SHIRT_MALE_R", "Red elegant shirt", "objtypes"),
            new GamevalEntry(10405, "CERT_TRAIL_ELEGANT_SHIRT_MALE_R", "cert_trail_elegant_shirt_male_r", "objtypes"),
            new GamevalEntry(10406, "TRAIL_ELEGANT_PANTS_MALE_R", "Red elegant legs", "objtypes"),
            new GamevalEntry(10407, "CERT_TRAIL_ELEGANT_PANTS_MALE_R", "cert_trail_elegant_pants_male_r", "objtypes"),
            new GamevalEntry(10408, "TRAIL_ELEGANT_SHIRT_MALE_B", "Blue elegant shirt", "objtypes"),
            new GamevalEntry(10409, "CERT_TRAIL_ELEGANT_SHIRT_MALE_B", "cert_trail_elegant_shirt_male_b", "objtypes"),
            new GamevalEntry(10410, "TRAIL_ELEGANT_PANTS_MALE_B", "Blue elegant legs", "objtypes"),
            new GamevalEntry(10411, "CERT_TRAIL_ELEGANT_PANTS_MALE_B", "cert_trail_elegant_pants_male_b", "objtypes"),
            new GamevalEntry(10412, "TRAIL_ELEGANT_SHIRT_MALE_G", "Green elegant shirt", "objtypes"),
            new GamevalEntry(10413, "CERT_TRAIL_ELEGANT_SHIRT_MALE_G", "cert_trail_elegant_shirt_male_g", "objtypes"),
            new GamevalEntry(10414, "TRAIL_ELEGANT_PANTS_MALE_G", "Green elegant legs", "objtypes"),
            new GamevalEntry(10415, "CERT_TRAIL_ELEGANT_PANTS_MALE_G", "cert_trail_elegant_pants_male_g", "objtypes"),
            new GamevalEntry(10416, "TRAIL_ELEGANT_SHIRT_MALE_P", "Purple elegant shirt", "objtypes"),
            new GamevalEntry(10417, "CERT_TRAIL_ELEGANT_SHIRT_MALE_P", "cert_trail_elegant_shirt_male_p", "objtypes"),
            new GamevalEntry(10418, "TRAIL_ELEGANT_PANTS_MALE_P", "Purple elegant legs", "objtypes"),
            new GamevalEntry(10419, "CERT_TRAIL_ELEGANT_PANTS_MALE_P", "cert_trail_elegant_pants_male_p", "objtypes"),
            new GamevalEntry(10420, "TRAIL_ELEGANT_SHIRT_FEMALE", "White elegant blouse", "objtypes"),
            new GamevalEntry(10421, "CERT_TRAIL_ELEGANT_SHIRT_FEMALE", "cert_trail_elegant_shirt_female", "objtypes"),
            new GamevalEntry(10422, "TRAIL_ELEGANT_PANTS_FEMALE", "White elegant skirt", "objtypes"),
            new GamevalEntry(10423, "CERT_TRAIL_ELEGANT_PANTS_FEMALE", "cert_trail_elegant_pants_female", "objtypes"),
            new GamevalEntry(10424, "TRAIL_ELEGANT_SHIRT_FEMALE_R", "Red elegant blouse", "objtypes"),
            new GamevalEntry(10425, "CERT_TRAIL_ELEGANT_SHIRT_FEMALE_R", "cert_trail_elegant_shirt_female_r", "objtypes"),
            new GamevalEntry(10426, "TRAIL_ELEGANT_PANTS_FEMALE_R", "Red elegant skirt", "objtypes"),
            new GamevalEntry(10427, "CERT_TRAIL_ELEGANT_PANTS_FEMALE_R", "cert_trail_elegant_pants_female_r", "objtypes"),
            new GamevalEntry(10428, "TRAIL_ELEGANT_SHIRT_FEMALE_B", "Blue elegant blouse", "objtypes"),
            new GamevalEntry(10429, "CERT_TRAIL_ELEGANT_SHIRT_FEMALE_B", "cert_trail_elegant_shirt_female_b", "objtypes"),
            new GamevalEntry(10430, "TRAIL_ELEGANT_PANTS_FEMALE_B", "Blue elegant skirt", "objtypes"),
            new GamevalEntry(10431, "CERT_TRAIL_ELEGANT_PANTS_FEMALE_B", "cert_trail_elegant_pants_female_b", "objtypes"),
            new GamevalEntry(10432, "TRAIL_ELEGANT_SHIRT_FEMALE_G", "Green elegant blouse", "objtypes"),
            new GamevalEntry(10433, "CERT_TRAIL_ELEGANT_SHIRT_FEMALE_G", "cert_trail_elegant_shirt_female_g", "objtypes"),
            new GamevalEntry(10434, "TRAIL_ELEGANT_PANTS_FEMALE_G", "Green elegant skirt", "objtypes"),
            new GamevalEntry(10435, "CERT_TRAIL_ELEGANT_PANTS_FEMALE_G", "cert_trail_elegant_pants_female_g", "objtypes"),
            new GamevalEntry(10436, "TRAIL_ELEGANT_SHIRT_FEMALE_P", "Purple elegant blouse", "objtypes"),
            new GamevalEntry(10437, "CERT_TRAIL_ELEGANT_SHIRT_FEMALE_P", "cert_trail_elegant_shirt_female_p", "objtypes"),
            new GamevalEntry(10438, "TRAIL_ELEGANT_PANTS_FEMALE_P", "Purple elegant skirt", "objtypes"),
            new GamevalEntry(10439, "CERT_TRAIL_ELEGANT_PANTS_FEMALE_P", "cert_trail_elegant_pants_female_p", "objtypes"),
            new GamevalEntry(10440, "TRAIL_SARADOMIN_STAFF", "Saradomin crozier", "objtypes"),
            new GamevalEntry(10441, "CERT_TRAIL_SARADOMIN_STAFF", "cert_trail_saradomin_staff", "objtypes"),
            new GamevalEntry(10442, "TRAIL_GUTHIX_STAFF", "Guthix crozier", "objtypes"),
            new GamevalEntry(10443, "CERT_TRAIL_GUTHIX_STAFF", "cert_trail_guthix_staff", "objtypes"),
            new GamevalEntry(10444, "TRAIL_ZAMORAK_STAFF", "Zamorak crozier", "objtypes"),
            new GamevalEntry(10445, "CERT_TRAIL_ZAMORAK_STAFF", "cert_trail_zamorak_staff", "objtypes"),
        };
    }

    static Optional<GamevalEntry> byId(int id) {
        for (GamevalEntry entry : entries()) {
            if (entry.id() == id) return Optional.of(entry);
        }
        return Optional.empty();
    }

}
