package net.titan.gamevals.internal;

import java.util.Optional;

import net.titan.gamevals.GamevalEntry;
import net.titan.gamevals.QuestEntry;

final class ItemIDEntries_53 {
    private ItemIDEntries_53() {}

    static GamevalEntry[] entries() {
        return new GamevalEntry[] {
            new GamevalEntry(27647, "CERT_SATURATED_HEART", "cert_saturated_heart", "objtypes"),
            new GamevalEntry(27648, "VENENATIS_PET_LEGACY", "Venenatis spiderling", "objtypes"),
            new GamevalEntry(27649, "CALLISTO_PET_LEGACY", "Callisto cub", "objtypes"),
            new GamevalEntry(27650, "VETION_PET_LEGACY", "Vet'ion jr.", "objtypes"),
            new GamevalEntry(27651, "VETION_PET2_LEGACY", "Vet'ion jr.", "objtypes"),
            new GamevalEntry(27652, "WILD_CAVE_WEBWEAVER_UNCHARGED", "Webweaver bow (u)", "objtypes"),
            new GamevalEntry(27653, "CERT_WILD_CAVE_WEBWEAVER_UNCHARGED", "cert_wild_cave_webweaver_uncharged", "objtypes"),
            new GamevalEntry(27654, "PLACEHOLDER_WILD_CAVE_WEBWEAVER_UNCHARGED", "placeholder_wild_cave_webweaver_uncharged", "objtypes"),
            new GamevalEntry(27655, "WILD_CAVE_WEBWEAVER_CHARGED", "Webweaver bow", "objtypes"),
            new GamevalEntry(27656, "PLACEHOLDER_WILD_CAVE_WEBWEAVER_CHARGED", "placeholder_wild_cave_webweaver_charged", "objtypes"),
            new GamevalEntry(27657, "WILD_CAVE_URSINE_UNCHARGED", "Ursine chainmace (u)", "objtypes"),
            new GamevalEntry(27658, "CERT_WILD_CAVE_URSINE_UNCHARGED", "cert_wild_cave_ursine_uncharged", "objtypes"),
            new GamevalEntry(27659, "PLACEHOLDER_WILD_CAVE_URSINE_UNCHARGED", "placeholder_wild_cave_ursine_uncharged", "objtypes"),
            new GamevalEntry(27660, "WILD_CAVE_URSINE_CHARGED", "Ursine chainmace", "objtypes"),
            new GamevalEntry(27661, "PLACEHOLDER_WILD_CAVE_URSINE_CHARGED", "placeholder_wild_cave_ursine_charged", "objtypes"),
            new GamevalEntry(27662, "WILD_CAVE_ACCURSED_UNCHARGED", "Accursed sceptre (u)", "objtypes"),
            new GamevalEntry(27663, "CERT_WILD_CAVE_ACCURSED_UNCHARGED", "cert_wild_cave_accursed_uncharged", "objtypes"),
            new GamevalEntry(27664, "PLACEHOLDER_WILD_CAVE_ACCURSED_UNCHARGED", "placeholder_wild_cave_accursed_uncharged", "objtypes"),
            new GamevalEntry(27665, "WILD_CAVE_ACCURSED_CHARGED", "Accursed sceptre", "objtypes"),
            new GamevalEntry(27666, "PLACEHOLDER_WILD_CAVE_ACCURSED_CHARGED", "placeholder_wild_cave_accursed_charged", "objtypes"),
            new GamevalEntry(27667, "WBR_CALLISTO_CLAWS", "Claws of callisto", "objtypes"),
            new GamevalEntry(27668, "CERT_WBR_CALLISTO_CLAWS", "cert_wbr_callisto_claws", "objtypes"),
            new GamevalEntry(27669, "PLACEHOLDER_WBR_CALLISTO_CLAWS", "placeholder_wbr_callisto_claws", "objtypes"),
            new GamevalEntry(27670, "WBR_VENENATIS_FANG", "Fangs of venenatis", "objtypes"),
            new GamevalEntry(27671, "CERT_WBR_VENENATIS_FANG", "cert_wbr_venenatis_fang", "objtypes"),
            new GamevalEntry(27672, "PLACEHOLDER_WBR_VENENATIS_FANG", "placeholder_wbr_venenatis_fang", "objtypes"),
            new GamevalEntry(27673, "WBR_VETION_SKULL", "Skull of vet'ion", "objtypes"),
            new GamevalEntry(27674, "CERT_WBR_VETION_SKULL", "cert_wbr_vetion_skull", "objtypes"),
            new GamevalEntry(27675, "PLACEHOLDER_WBR_VETION_SKULL", "placeholder_wbr_vetion_skull", "objtypes"),
            new GamevalEntry(27676, "WILD_CAVE_ACCURSED_UNCHARGED_RECOL", "Accursed sceptre (au)", "objtypes"),
            new GamevalEntry(27677, "CERT_WILD_CAVE_ACCURSED_UNCHARGED_RECOL", "cert_wild_cave_accursed_uncharged_recol", "objtypes"),
            new GamevalEntry(27678, "PLACEHOLDER_WILD_CAVE_ACCURSED_UNCHARGED_RECOL", "placeholder_wild_cave_accursed_uncharged_recol", "objtypes"),
            new GamevalEntry(27679, "WILD_CAVE_ACCURSED_CHARGED_RECOL", "Accursed sceptre (a)", "objtypes"),
            new GamevalEntry(27680, "PLACEHOLDER_WILD_CAVE_ACCURSED_CHARGED_RECOL", "placeholder_wild_cave_accursed_charged_recol", "objtypes"),
            new GamevalEntry(27681, "WBR_VOIDWAKER_HILT", "Voidwaker hilt", "objtypes"),
            new GamevalEntry(27682, "CERT_WBR_VOIDWAKER_HILT", "cert_wbr_voidwaker_hilt", "objtypes"),
            new GamevalEntry(27683, "PLACEHOLDER_WBR_VOIDWAKER_HILT", "placeholder_wbr_voidwaker_hilt", "objtypes"),
            new GamevalEntry(27684, "WBR_VOIDWAKER_BLADE", "Voidwaker blade", "objtypes"),
            new GamevalEntry(27685, "CERT_WBR_VOIDWAKER_BLADE", "cert_wbr_voidwaker_blade", "objtypes"),
            new GamevalEntry(27686, "PLACEHOLDER_WBR_VOIDWAKER_BLADE", "placeholder_wbr_voidwaker_blade", "objtypes"),
            new GamevalEntry(27687, "WBR_VOIDWAKER_GEM", "Voidwaker gem", "objtypes"),
            new GamevalEntry(27688, "CERT_WBR_VOIDWAKER_GEM", "cert_wbr_voidwaker_gem", "objtypes"),
            new GamevalEntry(27689, "PLACEHOLDER_WBR_VOIDWAKER_GEM", "placeholder_wbr_voidwaker_gem", "objtypes"),
            new GamevalEntry(27690, "VOIDWAKER", "Voidwaker", "objtypes"),
            new GamevalEntry(27691, "CERT_VOIDWAKER", "cert_voidwaker", "objtypes"),
            new GamevalEntry(27692, "PLACEHOLDER_VOIDWAKER", "placeholder_voidwaker", "objtypes"),
            new GamevalEntry(27693, "WBR_VM_OREPACK", "Ore pack", "objtypes"),
            new GamevalEntry(27694, "PLACEHOLDER_WBR_VM_OREPACK", "placeholder_wbr_vm_orepack", "objtypes"),
            new GamevalEntry(27695, "WBR_DRAGON_PICKAXE_BROKEN", "Dragon pickaxe (broken)", "objtypes"),
            new GamevalEntry(27696, "PLACEHOLDER_WBR_DRAGON_PICKAXE_BROKEN", "placeholder_wbr_dragon_pickaxe_broken", "objtypes"),
            new GamevalEntry(27697, "CRYSTAL_CHESTPLATE_HEFIN", "Crystal body", "objtypes"),
            new GamevalEntry(27698, "PLACEHOLDER_CRYSTAL_CHESTPLATE_HEFIN", "placeholder_crystal_chestplate_hefin", "objtypes"),
            new GamevalEntry(27699, "CRYSTAL_CHESTPLATE_INACTIVE_HEFIN", "Crystal body (inactive)", "objtypes"),
            new GamevalEntry(27700, "PLACEHOLDER_CRYSTAL_CHESTPLATE_INACTIVE_HEFIN", "placeholder_crystal_chestplate_inactive_hefin", "objtypes"),
            new GamevalEntry(27701, "CRYSTAL_PLATELEGS_HEFIN", "Crystal legs", "objtypes"),
            new GamevalEntry(27702, "PLACEHOLDER_CRYSTAL_PLATELEGS_HEFIN", "placeholder_crystal_platelegs_hefin", "objtypes"),
            new GamevalEntry(27703, "CRYSTAL_PLATELEGS_INACTIVE_HEFIN", "Crystal legs (inactive)", "objtypes"),
            new GamevalEntry(27704, "PLACEHOLDER_CRYSTAL_PLATELEGS_INACTIVE_HEFIN", "placeholder_crystal_platelegs_inactive_hefin", "objtypes"),
            new GamevalEntry(27705, "CRYSTAL_HELMET_HEFIN", "Crystal helm", "objtypes"),
            new GamevalEntry(27706, "PLACEHOLDER_CRYSTAL_HELMET_HEFIN", "placeholder_crystal_helmet_hefin", "objtypes"),
            new GamevalEntry(27707, "CRYSTAL_HELMET_INACTIVE_HEFIN", "Crystal helm (inactive)", "objtypes"),
            new GamevalEntry(27708, "PLACEHOLDER_CRYSTAL_HELMET_INACTIVE_HEFIN", "placeholder_crystal_helmet_inactive_hefin", "objtypes"),
            new GamevalEntry(27709, "CRYSTAL_CHESTPLATE_ITHELL", "Crystal body", "objtypes"),
            new GamevalEntry(27710, "PLACEHOLDER_CRYSTAL_CHESTPLATE_ITHELL", "placeholder_crystal_chestplate_ithell", "objtypes"),
            new GamevalEntry(27711, "CRYSTAL_CHESTPLATE_INACTIVE_ITHELL", "Crystal body (inactive)", "objtypes"),
            new GamevalEntry(27712, "PLACEHOLDER_CRYSTAL_CHESTPLATE_INACTIVE_ITHELL", "placeholder_crystal_chestplate_inactive_ithell", "objtypes"),
            new GamevalEntry(27713, "CRYSTAL_PLATELEGS_ITHELL", "Crystal legs", "objtypes"),
            new GamevalEntry(27714, "PLACEHOLDER_CRYSTAL_PLATELEGS_ITHELL", "placeholder_crystal_platelegs_ithell", "objtypes"),
            new GamevalEntry(27715, "CRYSTAL_PLATELEGS_INACTIVE_ITHELL", "Crystal legs (inactive)", "objtypes"),
            new GamevalEntry(27716, "PLACEHOLDER_CRYSTAL_PLATELEGS_INACTIVE_ITHELL", "placeholder_crystal_platelegs_inactive_ithell", "objtypes"),
            new GamevalEntry(27717, "CRYSTAL_HELMET_ITHELL", "Crystal helm", "objtypes"),
            new GamevalEntry(27718, "PLACEHOLDER_CRYSTAL_HELMET_ITHELL", "placeholder_crystal_helmet_ithell", "objtypes"),
            new GamevalEntry(27719, "CRYSTAL_HELMET_INACTIVE_ITHELL", "Crystal helm (inactive)", "objtypes"),
            new GamevalEntry(27720, "PLACEHOLDER_CRYSTAL_HELMET_INACTIVE_ITHELL", "placeholder_crystal_helmet_inactive_ithell", "objtypes"),
            new GamevalEntry(27721, "CRYSTAL_CHESTPLATE_IORWERTH", "Crystal body", "objtypes"),
            new GamevalEntry(27722, "PLACEHOLDER_CRYSTAL_CHESTPLATE_IORWERTH", "placeholder_crystal_chestplate_iorwerth", "objtypes"),
            new GamevalEntry(27723, "CRYSTAL_CHESTPLATE_INACTIVE_IORWERTH", "Crystal body (inactive)", "objtypes"),
            new GamevalEntry(27724, "PLACEHOLDER_CRYSTAL_CHESTPLATE_INACTIVE_IORWERTH", "placeholder_crystal_chestplate_inactive_iorwerth", "objtypes"),
            new GamevalEntry(27725, "CRYSTAL_PLATELEGS_IORWERTH", "Crystal legs", "objtypes"),
            new GamevalEntry(27726, "PLACEHOLDER_CRYSTAL_PLATELEGS_IORWERTH", "placeholder_crystal_platelegs_iorwerth", "objtypes"),
            new GamevalEntry(27727, "CRYSTAL_PLATELEGS_INACTIVE_IORWERTH", "Crystal legs (inactive)", "objtypes"),
            new GamevalEntry(27728, "PLACEHOLDER_CRYSTAL_PLATELEGS_INACTIVE_IORWERTH", "placeholder_crystal_platelegs_inactive_iorwerth", "objtypes"),
            new GamevalEntry(27729, "CRYSTAL_HELMET_IORWERTH", "Crystal helm", "objtypes"),
            new GamevalEntry(27730, "PLACEHOLDER_CRYSTAL_HELMET_IORWERTH", "placeholder_crystal_helmet_iorwerth", "objtypes"),
            new GamevalEntry(27731, "CRYSTAL_HELMET_INACTIVE_IORWERTH", "Crystal helm (inactive)", "objtypes"),
            new GamevalEntry(27732, "PLACEHOLDER_CRYSTAL_HELMET_INACTIVE_IORWERTH", "placeholder_crystal_helmet_inactive_iorwerth", "objtypes"),
            new GamevalEntry(27733, "CRYSTAL_CHESTPLATE_TRAHAEARN", "Crystal body", "objtypes"),
            new GamevalEntry(27734, "PLACEHOLDER_CRYSTAL_CHESTPLATE_TRAHAEARN", "placeholder_crystal_chestplate_trahaearn", "objtypes"),
            new GamevalEntry(27735, "CRYSTAL_CHESTPLATE_INACTIVE_TRAHAEARN", "Crystal body (inactive)", "objtypes"),
            new GamevalEntry(27736, "PLACEHOLDER_CRYSTAL_CHESTPLATE_INACTIVE_TRAHAEARN", "placeholder_crystal_chestplate_inactive_trahaearn", "objtypes"),
            new GamevalEntry(27737, "CRYSTAL_PLATELEGS_TRAHAEARN", "Crystal legs", "objtypes"),
            new GamevalEntry(27738, "PLACEHOLDER_CRYSTAL_PLATELEGS_TRAHAEARN", "placeholder_crystal_platelegs_trahaearn", "objtypes"),
            new GamevalEntry(27739, "CRYSTAL_PLATELEGS_INACTIVE_TRAHAEARN", "Crystal legs (inactive)", "objtypes"),
            new GamevalEntry(27740, "PLACEHOLDER_CRYSTAL_PLATELEGS_INACTIVE_TRAHAEARN", "placeholder_crystal_platelegs_inactive_trahaearn", "objtypes"),
            new GamevalEntry(27741, "CRYSTAL_HELMET_TRAHAEARN", "Crystal helm", "objtypes"),
            new GamevalEntry(27742, "PLACEHOLDER_CRYSTAL_HELMET_TRAHAEARN", "placeholder_crystal_helmet_trahaearn", "objtypes"),
            new GamevalEntry(27743, "CRYSTAL_HELMET_INACTIVE_TRAHAEARN", "Crystal helm (inactive)", "objtypes"),
            new GamevalEntry(27744, "PLACEHOLDER_CRYSTAL_HELMET_INACTIVE_TRAHAEARN", "placeholder_crystal_helmet_inactive_trahaearn", "objtypes"),
            new GamevalEntry(27745, "CRYSTAL_CHESTPLATE_CADARN", "Crystal body", "objtypes"),
            new GamevalEntry(27746, "PLACEHOLDER_CRYSTAL_CHESTPLATE_CADARN", "placeholder_crystal_chestplate_cadarn", "objtypes"),
            new GamevalEntry(27747, "CRYSTAL_CHESTPLATE_INACTIVE_CADARN", "Crystal body (inactive)", "objtypes"),
            new GamevalEntry(27748, "PLACEHOLDER_CRYSTAL_CHESTPLATE_INACTIVE_CADARN", "placeholder_crystal_chestplate_inactive_cadarn", "objtypes"),
            new GamevalEntry(27749, "CRYSTAL_PLATELEGS_CADARN", "Crystal legs", "objtypes"),
            new GamevalEntry(27750, "PLACEHOLDER_CRYSTAL_PLATELEGS_CADARN", "placeholder_crystal_platelegs_cadarn", "objtypes"),
            new GamevalEntry(27751, "CRYSTAL_PLATELEGS_INACTIVE_CADARN", "Crystal legs (inactive)", "objtypes"),
            new GamevalEntry(27752, "PLACEHOLDER_CRYSTAL_PLATELEGS_INACTIVE_CADARN", "placeholder_crystal_platelegs_inactive_cadarn", "objtypes"),
            new GamevalEntry(27753, "CRYSTAL_HELMET_CADARN", "Crystal helm", "objtypes"),
            new GamevalEntry(27754, "PLACEHOLDER_CRYSTAL_HELMET_CADARN", "placeholder_crystal_helmet_cadarn", "objtypes"),
            new GamevalEntry(27755, "CRYSTAL_HELMET_INACTIVE_CADARN", "Crystal helm (inactive)", "objtypes"),
            new GamevalEntry(27756, "PLACEHOLDER_CRYSTAL_HELMET_INACTIVE_CADARN", "placeholder_crystal_helmet_inactive_cadarn", "objtypes"),
            new GamevalEntry(27757, "CRYSTAL_CHESTPLATE_CRWYS", "Crystal body", "objtypes"),
            new GamevalEntry(27758, "PLACEHOLDER_CRYSTAL_CHESTPLATE_CRWYS", "placeholder_crystal_chestplate_crwys", "objtypes"),
            new GamevalEntry(27759, "CRYSTAL_CHESTPLATE_INACTIVE_CRWYS", "Crystal body (inactive)", "objtypes"),
            new GamevalEntry(27760, "PLACEHOLDER_CRYSTAL_CHESTPLATE_INACTIVE_CRWYS", "placeholder_crystal_chestplate_inactive_crwys", "objtypes"),
            new GamevalEntry(27761, "CRYSTAL_PLATELEGS_CRWYS", "Crystal legs", "objtypes"),
            new GamevalEntry(27762, "PLACEHOLDER_CRYSTAL_PLATELEGS_CRWYS", "placeholder_crystal_platelegs_crwys", "objtypes"),
            new GamevalEntry(27763, "CRYSTAL_PLATELEGS_INACTIVE_CRWYS", "Crystal legs (inactive)", "objtypes"),
            new GamevalEntry(27764, "PLACEHOLDER_CRYSTAL_PLATELEGS_INACTIVE_CRWYS", "placeholder_crystal_platelegs_inactive_crwys", "objtypes"),
            new GamevalEntry(27765, "CRYSTAL_HELMET_CRWYS", "Crystal helm", "objtypes"),
            new GamevalEntry(27766, "PLACEHOLDER_CRYSTAL_HELMET_CRWYS", "placeholder_crystal_helmet_crwys", "objtypes"),
            new GamevalEntry(27767, "CRYSTAL_HELMET_INACTIVE_CRWYS", "Crystal helm (inactive)", "objtypes"),
            new GamevalEntry(27768, "PLACEHOLDER_CRYSTAL_HELMET_INACTIVE_CRWYS", "placeholder_crystal_helmet_inactive_crwys", "objtypes"),
            new GamevalEntry(27769, "CRYSTAL_CHESTPLATE_AMLODD", "Crystal body", "objtypes"),
            new GamevalEntry(27770, "PLACEHOLDER_CRYSTAL_CHESTPLATE_AMLODD", "placeholder_crystal_chestplate_amlodd", "objtypes"),
            new GamevalEntry(27771, "CRYSTAL_CHESTPLATE_INACTIVE_AMLODD", "Crystal body (inactive)", "objtypes"),
            new GamevalEntry(27772, "PLACEHOLDER_CRYSTAL_CHESTPLATE_INACTIVE_AMLODD", "placeholder_crystal_chestplate_inactive_amlodd", "objtypes"),
            new GamevalEntry(27773, "CRYSTAL_PLATELEGS_AMLODD", "Crystal legs", "objtypes"),
            new GamevalEntry(27774, "PLACEHOLDER_CRYSTAL_PLATELEGS_AMLODD", "placeholder_crystal_platelegs_amlodd", "objtypes"),
            new GamevalEntry(27775, "CRYSTAL_PLATELEGS_INACTIVE_AMLODD", "Crystal legs (inactive)", "objtypes"),
            new GamevalEntry(27776, "PLACEHOLDER_CRYSTAL_PLATELEGS_INACTIVE_AMLODD", "placeholder_crystal_platelegs_inactive_amlodd", "objtypes"),
            new GamevalEntry(27777, "CRYSTAL_HELMET_AMLODD", "Crystal helm", "objtypes"),
            new GamevalEntry(27778, "PLACEHOLDER_CRYSTAL_HELMET_AMLODD", "placeholder_crystal_helmet_amlodd", "objtypes"),
            new GamevalEntry(27779, "CRYSTAL_HELMET_INACTIVE_AMLODD", "Crystal helm (inactive)", "objtypes"),
            new GamevalEntry(27780, "PLACEHOLDER_CRYSTAL_HELMET_INACTIVE_AMLODD", "placeholder_crystal_helmet_inactive_amlodd", "objtypes"),
            new GamevalEntry(27781, "SPEEDRUN_TROPHIES_DIAMOND", "Cabbage", "objtypes"),
            new GamevalEntry(27782, "BOUGHT_SPEEDRUN_TROPHIES_DIAMOND", "bought_speedrun_trophies_diamond", "objtypes"),
            new GamevalEntry(27783, "SPEEDRUN_TROPHY_DIAMOND", "Diamond speedrun trophy", "objtypes"),
            new GamevalEntry(27784, "PLACEHOLDER_SPEEDRUN_TROPHY_DIAMOND", "placeholder_speedrun_trophy_diamond", "objtypes"),
            new GamevalEntry(27785, "WILD_CAVE_SCEPTRE_UNCHARGED_RECOL", "Thammaron's sceptre (au)", "objtypes"),
            new GamevalEntry(27786, "CERT_WILD_CAVE_SCEPTRE_UNCHARGED_RECOL", "cert_wild_cave_sceptre_uncharged_recol", "objtypes"),
            new GamevalEntry(27787, "PLACEHOLDER_WILD_CAVE_SCEPTRE_UNCHARGED_RECOL", "placeholder_wild_cave_sceptre_uncharged_recol", "objtypes"),
            new GamevalEntry(27788, "WILD_CAVE_SCEPTRE_CHARGED_RECOL", "Thammaron's sceptre (a)", "objtypes"),
            new GamevalEntry(27789, "PLACEHOLDER_WILD_CAVE_SCEPTRE_CHARGED_RECOL", "placeholder_wild_cave_sceptre_charged_recol", "objtypes"),
            new GamevalEntry(27790, "STACKABLE_NIGHTSHADE", "Nightshade", "objtypes"),
            new GamevalEntry(27791, "PLACEHOLDER_STACKABLE_NIGHTSHADE", "placeholder_stackable_nightshade", "objtypes"),
            new GamevalEntry(27792, "STACKABLE_NIGHTSHADE_2", "stackable_nightshade_2", "objtypes"),
            new GamevalEntry(27793, "STACKABLE_NIGHTSHADE_3", "stackable_nightshade_3", "objtypes"),
            new GamevalEntry(27794, "OSB10_CRACKEDTIN", "Null", "objtypes"),
            new GamevalEntry(27795, "OSB10_CAKETIN", "Null", "objtypes"),
            new GamevalEntry(27796, "OSB10_PROMISENOTE", "Null", "objtypes"),
            new GamevalEntry(27797, "OSB10_SPECIALCAKE", "Null", "objtypes"),
            new GamevalEntry(27798, "OSB10_VARROCKCAKE", "Null", "objtypes"),
            new GamevalEntry(27799, "OSB10_GNOMECAKE", "Null", "objtypes"),
            new GamevalEntry(27800, "OSB10_GOBLINCAKE", "Null", "objtypes"),
            new GamevalEntry(27801, "OSB10_DWARFCAKE", "Null", "objtypes"),
            new GamevalEntry(27802, "OSB10_GNOMECHILD_BACKPACK", "Gnome child backpack", "objtypes"),
            new GamevalEntry(27803, "PLACEHOLDER_OSB10_GNOMECHILD_BACKPACK", "placeholder_osb10_gnomechild_backpack", "objtypes"),
            new GamevalEntry(27804, "OSB10_CAKE_HAT", "Cake hat", "objtypes"),
            new GamevalEntry(27805, "PLACEHOLDER_OSB10_CAKE_HAT", "placeholder_osb10_cake_hat", "objtypes"),
            new GamevalEntry(27806, "OSB10_BOB_SLIPPERS", "Bob the cat slippers", "objtypes"),
            new GamevalEntry(27807, "PLACEHOLDER_OSB10_BOB_SLIPPERS", "Null", "objtypes"),
            new GamevalEntry(27808, "OSB10_JAD_SLIPPERS", "Jad slippers", "objtypes"),
            new GamevalEntry(27809, "PLACEHOLDER_OSB10_JAD_SLIPPERS", "placeholder_osb10_jad_slippers", "objtypes"),
            new GamevalEntry(27810, "OSB10_DRAGON_CANDLE", "Dragon candle dagger", "objtypes"),
            new GamevalEntry(27811, "PLACEHOLDER_OSB10_DRAGON_CANDLE", "placeholder_osb10_dragon_candle", "objtypes"),
            new GamevalEntry(27812, "OSB10_CAPE", "10th birthday cape", "objtypes"),
            new GamevalEntry(27813, "PLACEHOLDER_OSB10_CAPE", "placeholder_osb10_cape", "objtypes"),
            new GamevalEntry(27814, "OSB10_PLUSH_JAD", "Jad plush", "objtypes"),
            new GamevalEntry(27815, "PLACEHOLDER_OSB10_PLUSH_JAD", "placeholder_osb10_plush_jad", "objtypes"),
            new GamevalEntry(27816, "OSB10_PLUSH_STRAYDOG", "Stray dog plush", "objtypes"),
            new GamevalEntry(27817, "PLACEHOLDER_OSB10_PLUSH_STRAYDOG", "Null", "objtypes"),
            new GamevalEntry(27818, "OSB10_PLUSH_GNOMECHILD", "Gnome child plush", "objtypes"),
            new GamevalEntry(27819, "PLACEHOLDER_OSB10_PLUSH_GNOMECHILD", "Null", "objtypes"),
            new GamevalEntry(27820, "OSB10_BALLOONS", "10th birthday balloons", "objtypes"),
            new GamevalEntry(27821, "PLACEHOLDER_OSB10_BALLOONS", "placeholder_osb10_balloons", "objtypes"),
            new GamevalEntry(27822, "OSB10_JUMPER_RED", "Oldschool jumper", "objtypes"),
            new GamevalEntry(27823, "OSB10_JUMPER_YELLOW", "Oldschool jumper", "objtypes"),
            new GamevalEntry(27824, "OSB10_JUMPER_BLUE", "Oldschool jumper", "objtypes"),
            new GamevalEntry(27825, "OSB10_JUMPER_PURPLE", "Oldschool jumper", "objtypes"),
            new GamevalEntry(27826, "OSB10_JUMPER_GREEN", "Oldschool jumper", "objtypes"),
            new GamevalEntry(27827, "OSB10_JUMPER_WHITE", "Oldschool jumper", "objtypes"),
            new GamevalEntry(27828, "OSB10_SILVER_PARTYHAT", "Silver partyhat", "objtypes"),
            new GamevalEntry(27829, "PLACEHOLDER_OSB10_SILVER_PARTYHAT", "placeholder_osb10_silver_partyhat", "objtypes"),
            new GamevalEntry(27830, "PLACEHOLDER_OSB10_JUMPER_RED", "placeholder_osb10_jumper_red", "objtypes"),
            new GamevalEntry(27831, "BH_VESTAS_CHAINBODY", "Vesta's chainbody (bh)", "objtypes"),
            new GamevalEntry(27832, "BH_VESTAS_PLATESKIRT", "Vesta's plateskirt (bh)", "objtypes"),
            new GamevalEntry(27833, "BH_STATIUS_FULL_HELM", "Statius's full helm (bh)", "objtypes"),
            new GamevalEntry(27834, "BH_STATIUS_PLATEBODY", "Statius's platebody (bh)", "objtypes"),
            new GamevalEntry(27835, "BH_STATIUS_PLATELEGS", "Statius's platelegs (bh)", "objtypes"),
            new GamevalEntry(27836, "BH_MORRIGANS_COIF", "Morrigan's coif (bh)", "objtypes"),
            new GamevalEntry(27837, "BH_MORRIGANS_LEATHER_BODY", "Morrigan's leather body (bh)", "objtypes"),
            new GamevalEntry(27838, "BH_MORRIGANS_LEATHER_CHAPS", "Morrigan's leather chaps (bh)", "objtypes"),
            new GamevalEntry(27839, "BH_ZURIELS_HOOD", "Zuriel's hood (bh)", "objtypes"),
            new GamevalEntry(27840, "BH_ZURIELS_ROBE_TOP", "Zuriel's robe top (bh)", "objtypes"),
            new GamevalEntry(27841, "BH_ZURIELS_ROBE_BOTTOM", "Zuriel's robe bottom (bh)", "objtypes"),
            new GamevalEntry(27842, "BH_VESTAS_CHAINBODY_CORRUPT", "Corrupted vesta's chainbody (bh)", "objtypes"),
            new GamevalEntry(27843, "BH_VESTAS_PLATESKIRT_CORRUPT", "Corrupted vesta's plateskirt (bh)", "objtypes"),
            new GamevalEntry(27844, "BH_STATIUS_FULL_HELM_CORRUPT", "Corrupted statius's full helm (bh)", "objtypes"),
            new GamevalEntry(27845, "BH_STATIUS_PLATEBODY_CORRUPT", "Corrupted statius's platebody (bh)", "objtypes"),
            new GamevalEntry(27846, "BH_STATIUS_PLATELEGS_CORRUPT", "Corrupted statius's platelegs (bh)", "objtypes"),
            new GamevalEntry(27847, "BH_MORRIGANS_COIF_CORRUPT", "Corrupted morrigan's coif (bh)", "objtypes"),
            new GamevalEntry(27848, "BH_MORRIGANS_LEATHER_BODY_CORRUPT", "Corrupted morrigan's leather body (bh)", "objtypes"),
            new GamevalEntry(27849, "BH_MORRIGANS_LEATHER_CHAPS_CORRUPT", "Corrupted morrigan's leather chaps (bh)", "objtypes"),
            new GamevalEntry(27850, "BH_ZURIELS_HOOD_CORRUPT", "Corrupted zuriel's hood (bh)", "objtypes"),
            new GamevalEntry(27851, "BH_ZURIELS_ROBE_TOP_CORRUPT", "Corrupted zuriel's robe top (bh)", "objtypes"),
            new GamevalEntry(27852, "BH_ZURIELS_ROBE_BOTTOM_CORRUPT", "Corrupted zuriel's robe bottom (bh)", "objtypes"),
            new GamevalEntry(27853, "BH_DARKBOW_IMBUE", "O Dark bow (bh)", "objtypes"),
            new GamevalEntry(27854, "PLACEHOLDER_BH_DARKBOW_IMBUE", "placeholder_bh_darkbow_imbue", "objtypes"),
            new GamevalEntry(27855, "BH_BRAIN_ANCHOR_IMBUE", "Barrelchest anchor (bh)", "objtypes"),
            new GamevalEntry(27856, "PLACEHOLDER_BH_BRAIN_ANCHOR_IMBUE", "placeholder_bh_brain_anchor_imbue", "objtypes"),
            new GamevalEntry(27857, "BH_DRAGON_MACE_IMBUE", "Dragon mace (bh)", "objtypes"),
            new GamevalEntry(27858, "PLACEHOLDER_BH_DRAGON_MACE_IMBUE", "placeholder_bh_dragon_mace_imbue", "objtypes"),
            new GamevalEntry(27859, "BH_DRAGON_LONGSWORD_IMBUE", "Dragon longsword (bh)", "objtypes"),
            new GamevalEntry(27860, "PLACEHOLDER_BH_DRAGON_LONGSWORD_IMBUE", "placeholder_bh_dragon_longsword_imbue", "objtypes"),
            new GamevalEntry(27861, "BH_ABYSSAL_DAGGER_IMBUE", "Abyssal dagger (bh)", "objtypes"),
            new GamevalEntry(27862, "PLACEHOLDER_BH_ABYSSAL_DAGGER_IMBUE", "placeholder_bh_abyssal_dagger_imbue", "objtypes"),
            new GamevalEntry(27863, "BH_ABYSSAL_DAGGER_P_IMBUE", "Abyssal dagger (bh)(p)", "objtypes"),
            new GamevalEntry(27864, "PLACEHOLDER_BH_ABYSSAL_DAGGER_P_IMBUE", "placeholder_bh_abyssal_dagger_p_imbue", "objtypes"),
            new GamevalEntry(27869, "BR_VOIDWAKER", "Voidwaker", "objtypes"),
            new GamevalEntry(27870, "BR_LIGHTBEARER", "Lightbearer", "objtypes"),
            new GamevalEntry(27871, "EASTER23_DAGGER", "Giant bronze dagger", "objtypes"),
            new GamevalEntry(27872, "PLACEHOLDER_EASTER23_DAGGER", "placeholder_easter23_dagger", "objtypes"),
            new GamevalEntry(27873, "EASTER23_SPADE", "Eastfloor spade", "objtypes"),
            new GamevalEntry(27874, "PLACEHOLDER_EASTER23_SPADE", "placeholder_easter23_spade", "objtypes"),
            new GamevalEntry(27875, "EASTER23_NEST_HAT_EGG", "Nest hat", "objtypes"),
            new GamevalEntry(27876, "PLACEHOLDER_EASTER23_NEST_HAT_EGG", "placeholder_easter23_nest_hat_egg", "objtypes"),
            new GamevalEntry(27877, "EASTER23_NEST_HAT_CHICK", "Nest hat", "objtypes"),
            new GamevalEntry(27878, "EASTER23_EGG", "Null", "objtypes"),
            new GamevalEntry(27879, "PLACEHOLDER_EASTER23_EGG", "placeholder_easter23_egg", "objtypes"),
            new GamevalEntry(27880, "EASTER23_EGG_HOT", "Null", "objtypes"),
            new GamevalEntry(27881, "PLACEHOLDER_EASTER23_EGG_HOT", "placeholder_easter23_egg_hot", "objtypes"),
            new GamevalEntry(27882, "EASTER23_EGG_HALF", "Null", "objtypes"),
            new GamevalEntry(27883, "PLACEHOLDER_EASTER23_EGG_HALF", "placeholder_easter23_egg_half", "objtypes"),
            new GamevalEntry(27884, "EASTER23_EGG_MOULD", "Null", "objtypes"),
            new GamevalEntry(27885, "PLACEHOLDER_EASTER23_EGG_MOULD", "placeholder_easter23_egg_mould", "objtypes"),
            new GamevalEntry(27886, "EASTER23_EGG_MOULD_DUSTED", "Null", "objtypes"),
            new GamevalEntry(27887, "PLACEHOLDER_EASTER23_EGG_MOULD_DUSTED", "placeholder_easter23_egg_mould_dusted", "objtypes"),
            new GamevalEntry(27888, "EASTER23_EGG_MOULD_COOKED", "Null", "objtypes"),
            new GamevalEntry(27889, "PLACEHOLDER_EASTER23_EGG_MOULD_COOKED", "placeholder_easter23_egg_mould_cooked", "objtypes"),
            new GamevalEntry(27890, "EASTER23_FROZEN_MILK", "Null", "objtypes"),
            new GamevalEntry(27891, "PLACEHOLDER_EASTER23_FROZEN_MILK", "placeholder_easter23_frozen_milk", "objtypes"),
            new GamevalEntry(27892, "EASTER23_CHOCOLATE_DUST", "Null", "objtypes"),
            new GamevalEntry(27893, "PLACEHOLDER_EASTER23_CHOCOLATE_DUST", "placeholder_easter23_chocolate_dust", "objtypes"),
            new GamevalEntry(27894, "CERT_VIRTUS_TOP", "cert_virtus_top", "objtypes"),
            new GamevalEntry(27895, "CERT_VIRTUS_LEGS", "cert_virtus_legs", "objtypes"),
            new GamevalEntry(27896, "CERT_VIRTUS_MASK", "cert_virtus_mask", "objtypes"),
            new GamevalEntry(27897, "SCALY_BLUEHIDE", "Scaly blue dragonhide", "objtypes"),
            new GamevalEntry(27898, "CERT_SCALY_BLUEHIDE", "cert_scaly_bluehide", "objtypes"),
            new GamevalEntry(27899, "PLACEHOLDER_SCALY_BLUEHIDE", "placeholder_scaly_bluehide", "objtypes"),
            new GamevalEntry(27900, "VESTAS_SPEAR_BH", "Vesta's spear (bh)", "objtypes"),
            new GamevalEntry(27901, "PLACEHOLDER_VESTAS_SPEAR_BH", "placeholder_vestas_spear_bh", "objtypes"),
            new GamevalEntry(27902, "VESTAS_SPEAR_BH_INACTIVE", "Vesta's spear (bh)(inactive)", "objtypes"),
            new GamevalEntry(27903, "PLACEHOLDER_VESTAS_SPEAR_BH_INACTIVE", "placeholder_vestas_spear_bh_inactive", "objtypes"),
            new GamevalEntry(27904, "VESTAS_LONGSWORD_BH", "Vesta's longsword (bh)", "objtypes"),
            new GamevalEntry(27905, "PLACEHOLDER_VESTAS_LONGSWORD_BH", "placeholder_vestas_longsword_bh", "objtypes"),
            new GamevalEntry(27906, "VESTAS_LONGSWORD_BH_INACTIVE", "Vesta's longsword (bh)(inactive)", "objtypes"),
            new GamevalEntry(27907, "PLACEHOLDER_VESTAS_LONGSWORD_BH_INACTIVE", "placeholder_vestas_longsword_bh_inactive", "objtypes"),
            new GamevalEntry(27908, "STATIUS_WARHAMMER_BH", "Statius's warhammer (bh)", "objtypes"),
            new GamevalEntry(27909, "PLACEHOLDER_STATIUS_WARHAMMER_BH", "placeholder_statius_warhammer_bh", "objtypes"),
            new GamevalEntry(27910, "STATIUS_WARHAMMER_BH_INACTIVE", "Statius's warhammer (bh)(inactive)", "objtypes"),
            new GamevalEntry(27911, "PLACEHOLDER_STATIUS_WARHAMMER_BH_INACTIVE", "placeholder_statius_warhammer_bh_inactive", "objtypes"),
            new GamevalEntry(27912, "MORRIGANS_THROWNAXE_BH", "Morrigan's throwing axe (bh)", "objtypes"),
            new GamevalEntry(27913, "PLACEHOLDER_MORRIGANS_THROWNAXE_BH", "placeholder_morrigans_thrownaxe_bh", "objtypes"),
            new GamevalEntry(27914, "MORRIGANS_THROWNAXE_BH_INACTIVE", "Morrigan's throwing axe (bh)(inactive)", "objtypes"),
            new GamevalEntry(27915, "PLACEHOLDER_MORRIGANS_THROWNAXE_BH_INACTIVE", "placeholder_morrigans_thrownaxe_bh_inactive", "objtypes"),
            new GamevalEntry(27916, "MORRIGANS_JAVELIN_BH", "Morrigan's javelin (bh)", "objtypes"),
            new GamevalEntry(27917, "PLACEHOLDER_MORRIGANS_JAVELIN_BH", "placeholder_morrigans_javelin_bh", "objtypes"),
            new GamevalEntry(27918, "MORRIGANS_JAVELIN_BH_INACTIVE", "Morrigan's javelin (bh)(inactive)", "objtypes"),
            new GamevalEntry(27919, "PLACEHOLDER_MORRIGANS_JAVELIN_BH_INACTIVE", "placeholder_morrigans_javelin_bh_inactive", "objtypes"),
            new GamevalEntry(27920, "ZURIELS_STAFF_BH", "Zuriel's staff (bh)", "objtypes"),
            new GamevalEntry(27921, "PLACEHOLDER_ZURIELS_STAFF_BH", "placeholder_zuriels_staff_bh", "objtypes"),
            new GamevalEntry(27922, "ZURIELS_STAFF_BH_INACTIVE", "Zuriel's staff (bh)(inactive)", "objtypes"),
            new GamevalEntry(27923, "PLACEHOLDER_ZURIELS_STAFF_BH_INACTIVE", "placeholder_zuriels_staff_bh_inactive", "objtypes"),
            new GamevalEntry(27924, "PLACEHOLDER_BH_VESTAS_CHAINBODY", "placeholder_bh_vestas_chainbody", "objtypes"),
            new GamevalEntry(27925, "BH_VESTAS_CHAINBODY_INACTIVE", "Vesta's chainbody (bh)(inactive)", "objtypes"),
            new GamevalEntry(27926, "PLACEHOLDER_BH_VESTAS_CHAINBODY_INACTIVE", "placeholder_bh_vestas_chainbody_inactive", "objtypes"),
            new GamevalEntry(27927, "PLACEHOLDER_BH_VESTAS_PLATESKIRT", "placeholder_bh_vestas_plateskirt", "objtypes"),
            new GamevalEntry(27928, "BH_VESTAS_PLATESKIRT_INACTIVE", "2 Vesta's plateskirt (bh)(inactive)", "objtypes"),
            new GamevalEntry(27929, "PLACEHOLDER_BH_VESTAS_PLATESKIRT_INACTIVE", "placeholder_bh_vestas_plateskirt_inactive", "objtypes"),
            new GamevalEntry(27930, "PLACEHOLDER_BH_STATIUS_FULL_HELM", "placeholder_bh_statius_full_helm", "objtypes"),
            new GamevalEntry(27931, "BH_STATIUS_FULL_HELM_INACTIVE", "Statius's full helm (bh)(inactive)", "objtypes"),
            new GamevalEntry(27932, "PLACEHOLDER_BH_STATIUS_FULL_HELM_INACTIVE", "placeholder_bh_statius_full_helm_inactive", "objtypes"),
            new GamevalEntry(27933, "PLACEHOLDER_BH_STATIUS_PLATEBODY", "placeholder_bh_statius_platebody", "objtypes"),
            new GamevalEntry(27934, "BH_STATIUS_PLATEBODY_INACTIVE", "Statius's platebody (bh)(inactive)", "objtypes"),
            new GamevalEntry(27935, "PLACEHOLDER_BH_STATIUS_PLATEBODY_INACTIVE", "placeholder_bh_statius_platebody_inactive", "objtypes"),
            new GamevalEntry(27936, "PLACEHOLDER_BH_STATIUS_PLATELEGS", "placeholder_bh_statius_platelegs", "objtypes"),
            new GamevalEntry(27937, "BH_STATIUS_PLATELEGS_INACTIVE", "Statius's platelegs (bh)(inactive)", "objtypes"),
            new GamevalEntry(27938, "PLACEHOLDER_BH_STATIUS_PLATELEGS_INACTIVE", "placeholder_bh_statius_platelegs_inactive", "objtypes"),
            new GamevalEntry(27939, "PLACEHOLDER_BH_MORRIGANS_COIF", "placeholder_bh_morrigans_coif", "objtypes"),
            new GamevalEntry(27940, "BH_MORRIGANS_COIF_INACTIVE", "Morrigan's coif (bh)(inactive)", "objtypes"),
            new GamevalEntry(27941, "PLACEHOLDER_BH_MORRIGANS_COIF_INACTIVE", "placeholder_bh_morrigans_coif_inactive", "objtypes"),
            new GamevalEntry(27942, "PLACEHOLDER_BH_MORRIGANS_LEATHER_BODY", "placeholder_bh_morrigans_leather_body", "objtypes"),
            new GamevalEntry(27943, "BH_MORRIGANS_LEATHER_BODY_INACTIVE", "Morrigan's leather body (bh)(inactive)", "objtypes"),
            new GamevalEntry(27944, "PLACEHOLDER_BH_MORRIGANS_LEATHER_BODY_INACTIVE", "placeholder_bh_morrigans_leather_body_inactive", "objtypes"),
            new GamevalEntry(27945, "PLACEHOLDER_BH_MORRIGANS_LEATHER_CHAPS", "placeholder_bh_morrigans_leather_chaps", "objtypes"),
            new GamevalEntry(27946, "BH_MORRIGANS_LEATHER_CHAPS_INACTIVE", "Morrigan's leather chaps (bh)(inactive)", "objtypes"),
            new GamevalEntry(27947, "PLACEHOLDER_BH_MORRIGANS_LEATHER_CHAPS_INACTIVE", "placeholder_bh_morrigans_leather_chaps_inactive", "objtypes"),
            new GamevalEntry(27948, "PLACEHOLDER_BH_ZURIELS_HOOD", "placeholder_bh_zuriels_hood", "objtypes"),
            new GamevalEntry(27949, "BH_ZURIELS_HOOD_INACTIVE", "Zuriel's hood (bh)(inactive)", "objtypes"),
            new GamevalEntry(27950, "PLACEHOLDER_BH_ZURIELS_HOOD_INACTIVE", "placeholder_bh_zuriels_hood_inactive", "objtypes"),
            new GamevalEntry(27951, "PLACEHOLDER_BH_ZURIELS_ROBE_TOP", "placeholder_bh_zuriels_robe_top", "objtypes"),
            new GamevalEntry(27952, "BH_ZURIELS_ROBE_TOP_INACTIVE", "Zuriel's robe top (bh)(inactive)", "objtypes"),
            new GamevalEntry(27953, "PLACEHOLDER_BH_ZURIELS_ROBE_TOP_INACTIVE", "placeholder_bh_zuriels_robe_top_inactive", "objtypes"),
            new GamevalEntry(27954, "PLACEHOLDER_BH_ZURIELS_ROBE_BOTTOM", "placeholder_bh_zuriels_robe_bottom", "objtypes"),
            new GamevalEntry(27955, "BH_ZURIELS_ROBE_BOTTOM_INACTIVE", "Zuriel's robe bottom (bh)(inactive)", "objtypes"),
            new GamevalEntry(27956, "PLACEHOLDER_BH_ZURIELS_ROBE_BOTTOM_INACTIVE", "placeholder_bh_zuriels_robe_bottom_inactive", "objtypes"),
            new GamevalEntry(27957, "BH_XP_ATTACK", "Attack xp", "objtypes"),
            new GamevalEntry(27958, "BH_XP_STRENGTH", "Strength xp", "objtypes"),
            new GamevalEntry(27959, "BH_XP_DEFENCE", "Defence xp", "objtypes"),
            new GamevalEntry(27960, "BH_XP_HITPOINTS", "Hitpoints xp", "objtypes"),
            new GamevalEntry(27961, "BH_XP_MAGIC", "Magic xp", "objtypes"),
            new GamevalEntry(27962, "BH_XP_RANGED", "Ranged xp", "objtypes"),
            new GamevalEntry(27963, "BH_XP_PRAYER", "Prayer xp", "objtypes"),
            new GamevalEntry(27964, "PLACEHOLDER_BH_VESTAS_CHAINBODY_CORRUPT", "placeholder_bh_vestas_chainbody_corrupt", "objtypes"),
            new GamevalEntry(27965, "BH_VESTAS_CHAINBODY_CORRUPT_INACTIVE", "Corrupted vesta's chainbody (bh)(inactive)", "objtypes"),
            new GamevalEntry(27966, "PLACEHOLDER_BH_VESTAS_CHAINBODY_CORRUPT_INACTIVE", "placeholder_bh_vestas_chainbody_corrupt_inactive", "objtypes"),
            new GamevalEntry(27967, "PLACEHOLDER_BH_VESTAS_PLATESKIRT_CORRUPT", "placeholder_bh_vestas_plateskirt_corrupt", "objtypes"),
            new GamevalEntry(27968, "BH_VESTAS_PLATESKIRT_CORRUPT_INACTIVE", "2 Corrupted vesta's plateskirt (bh)(inactive)", "objtypes"),
            new GamevalEntry(27969, "PLACEHOLDER_BH_VESTAS_PLATESKIRT_CORRUPT_INACTIVE", "placeholder_bh_vestas_plateskirt_corrupt_inactive", "objtypes"),
            new GamevalEntry(27970, "PLACEHOLDER_BH_STATIUS_FULL_HELM_CORRUPT", "placeholder_bh_statius_full_helm_corrupt", "objtypes"),
            new GamevalEntry(27971, "BH_STATIUS_FULL_HELM_CORRUPT_INACTIVE", "Corrupted statius's full helm (bh)(inactive)", "objtypes"),
            new GamevalEntry(27972, "PLACEHOLDER_BH_STATIUS_FULL_HELM_CORRUPT_INACTIVE", "placeholder_bh_statius_full_helm_corrupt_inactive", "objtypes"),
            new GamevalEntry(27973, "PLACEHOLDER_BH_STATIUS_PLATEBODY_CORRUPT", "placeholder_bh_statius_platebody_corrupt", "objtypes"),
            new GamevalEntry(27974, "BH_STATIUS_PLATEBODY_CORRUPT_INACTIVE", "Corrupted statius's platebody (bh)(inactive)", "objtypes"),
            new GamevalEntry(27975, "PLACEHOLDER_BH_STATIUS_PLATEBODY_CORRUPT_INACTIVE", "placeholder_bh_statius_platebody_corrupt_inactive", "objtypes"),
            new GamevalEntry(27976, "PLACEHOLDER_BH_STATIUS_PLATELEGS_CORRUPT", "placeholder_bh_statius_platelegs_corrupt", "objtypes"),
            new GamevalEntry(27977, "BH_STATIUS_PLATELEGS_CORRUPT_INACTIVE", "Corrupted statius's platelegs (bh)(inactive)", "objtypes"),
            new GamevalEntry(27978, "PLACEHOLDER_BH_STATIUS_PLATELEGS_CORRUPT_INACTIVE", "placeholder_bh_statius_platelegs_corrupt_inactive", "objtypes"),
            new GamevalEntry(27979, "PLACEHOLDER_BH_MORRIGANS_COIF_CORRUPT", "placeholder_bh_morrigans_coif_corrupt", "objtypes"),
            new GamevalEntry(27980, "BH_MORRIGANS_COIF_CORRUPT_INACTIVE", "Corrupted morrigan's coif (bh)(inactive)", "objtypes"),
            new GamevalEntry(27981, "PLACEHOLDER_BH_MORRIGANS_COIF_CORRUPT_INACTIVE", "placeholder_bh_morrigans_coif_corrupt_inactive", "objtypes"),
            new GamevalEntry(27982, "PLACEHOLDER_BH_MORRIGANS_LEATHER_BODY_CORRUPT", "placeholder_bh_morrigans_leather_body_corrupt", "objtypes"),
            new GamevalEntry(27983, "BH_MORRIGANS_LEATHER_BODY_CORRUPT_INACTIVE", "Corrupted morrigan's leather body (bh)(inactive)", "objtypes"),
            new GamevalEntry(27984, "PLACEHOLDER_BH_MORRIGANS_LEATHER_BODY_CORRUPT_INACTIVE", "placeholder_bh_morrigans_leather_body_corrupt_inactive", "objtypes"),
            new GamevalEntry(27985, "PLACEHOLDER_BH_MORRIGANS_LEATHER_CHAPS_CORRUPT", "placeholder_bh_morrigans_leather_chaps_corrupt", "objtypes"),
            new GamevalEntry(27986, "BH_MORRIGANS_LEATHER_CHAPS_CORRUPT_INACTIVE", "Corrupted morrigan's leather chaps (bh)(inactive)", "objtypes"),
            new GamevalEntry(27987, "PLACEHOLDER_BH_MORRIGANS_LEATHER_CHAPS_CORRUPT_INACTIVE", "placeholder_bh_morrigans_leather_chaps_corrupt_inactive", "objtypes"),
            new GamevalEntry(27988, "PLACEHOLDER_BH_ZURIELS_HOOD_CORRUPT", "placeholder_bh_zuriels_hood_corrupt", "objtypes"),
            new GamevalEntry(27989, "BH_ZURIELS_HOOD_CORRUPT_INACTIVE", "Corrupted zuriel's hood (bh)(inactive)", "objtypes"),
            new GamevalEntry(27990, "PLACEHOLDER_BH_ZURIELS_HOOD_CORRUPT_INACTIVE", "placeholder_bh_zuriels_hood_corrupt_inactive", "objtypes"),
            new GamevalEntry(27991, "PLACEHOLDER_BH_ZURIELS_ROBE_TOP_CORRUPT", "placeholder_bh_zuriels_robe_top_corrupt", "objtypes"),
            new GamevalEntry(27992, "BH_ZURIELS_ROBE_TOP_CORRUPT_INACTIVE", "Corrupted zuriel's robe top (bh)(inactive)", "objtypes"),
            new GamevalEntry(27993, "PLACEHOLDER_BH_ZURIELS_ROBE_TOP_CORRUPT_INACTIVE", "placeholder_bh_zuriels_robe_top_corrupt_inactive", "objtypes"),
            new GamevalEntry(27994, "PLACEHOLDER_BH_ZURIELS_ROBE_BOTTOM_CORRUPT", "placeholder_bh_zuriels_robe_bottom_corrupt", "objtypes"),
            new GamevalEntry(27995, "BH_ZURIELS_ROBE_BOTTOM_CORRUPT_INACTIVE", "Corrupted zuriel's robe bottom (bh)(inactive)", "objtypes"),
            new GamevalEntry(27996, "PLACEHOLDER_BH_ZURIELS_ROBE_BOTTOM_CORRUPT_INACTIVE", "placeholder_bh_zuriels_robe_bottom_corrupt_inactive", "objtypes"),
            new GamevalEntry(27997, "BH_2023_EMBLEM_1", "Esoteric emblem (tier 1)", "objtypes"),
            new GamevalEntry(27998, "PLACEHOLDER_BH_2023_EMBLEM_1", "placeholder_bh_2023_emblem_1", "objtypes"),
            new GamevalEntry(27999, "BH_2023_EMBLEM_2", "Esoteric emblem (tier 2)", "objtypes"),
            new GamevalEntry(28000, "PLACEHOLDER_BH_2023_EMBLEM_2", "placeholder_bh_2023_emblem_2", "objtypes"),
            new GamevalEntry(28001, "BH_2023_EMBLEM_3", "Esoteric emblem (tier 3)", "objtypes"),
            new GamevalEntry(28002, "PLACEHOLDER_BH_2023_EMBLEM_3", "placeholder_bh_2023_emblem_3", "objtypes"),
            new GamevalEntry(28003, "BH_2023_EMBLEM_4", "Esoteric emblem (tier 4)", "objtypes"),
            new GamevalEntry(28004, "PLACEHOLDER_BH_2023_EMBLEM_4", "placeholder_bh_2023_emblem_4", "objtypes"),
            new GamevalEntry(28005, "BH_2023_EMBLEM_5", "Esoteric emblem (tier 5)", "objtypes"),
            new GamevalEntry(28006, "PLACEHOLDER_BH_2023_EMBLEM_5", "placeholder_bh_2023_emblem_5", "objtypes"),
            new GamevalEntry(28007, "BH_2023_EMBLEM_6", "Esoteric emblem (tier 6)", "objtypes"),
            new GamevalEntry(28008, "PLACEHOLDER_BH_2023_EMBLEM_6", "placeholder_bh_2023_emblem_6", "objtypes"),
            new GamevalEntry(28009, "BH_2023_EMBLEM_7", "Esoteric emblem (tier 7)", "objtypes"),
            new GamevalEntry(28010, "PLACEHOLDER_BH_2023_EMBLEM_7", "placeholder_bh_2023_emblem_7", "objtypes"),
            new GamevalEntry(28011, "BH_2023_EMBLEM_8", "Esoteric emblem (tier 8)", "objtypes"),
            new GamevalEntry(28012, "PLACEHOLDER_BH_2023_EMBLEM_8", "placeholder_bh_2023_emblem_8", "objtypes"),
            new GamevalEntry(28013, "BH_2023_EMBLEM_9", "Esoteric emblem (tier 9)", "objtypes"),
            new GamevalEntry(28014, "PLACEHOLDER_BH_2023_EMBLEM_9", "placeholder_bh_2023_emblem_9", "objtypes"),
            new GamevalEntry(28015, "BH_2023_EMBLEM_10", "Esoteric emblem (tier 10)", "objtypes"),
            new GamevalEntry(28016, "PLACEHOLDER_BH_2023_EMBLEM_10", "placeholder_bh_2023_emblem_10", "objtypes"),
            new GamevalEntry(28017, "BH_ORNAMENT_KIT", "Bounty hunter ornament kit", "objtypes"),
            new GamevalEntry(28018, "PLACEHOLDER_BH_ORNAMENT_KIT", "placeholder_bh_ornament_kit", "objtypes"),
            new GamevalEntry(28019, "BH_DRAGON_DAGGER_CORRUPTED", "Dragon dagger (cr)", "objtypes"),
            new GamevalEntry(28020, "PLACEHOLDER_BH_DRAGON_DAGGER_CORRUPTED", "placeholder_bh_dragon_dagger_corrupted", "objtypes"),
            new GamevalEntry(28021, "BH_DRAGON_DAGGER_P_CORRUPTED", "Dragon dagger (p)(cr)", "objtypes"),
            new GamevalEntry(28022, "PLACEHOLDER_BH_DRAGON_DAGGER_P_CORRUPTED", "placeholder_bh_dragon_dagger_p_corrupted", "objtypes"),
            new GamevalEntry(28027, "BH_DRAGON_MACE_CORRUPTED", "Dragon mace (cr)", "objtypes"),
            new GamevalEntry(28028, "PLACEHOLDER_BH_DRAGON_MACE_CORRUPTED", "placeholder_bh_dragon_mace_corrupted", "objtypes"),
            new GamevalEntry(28029, "BH_DRAGON_SHORTSWORD_CORRUPTED", "Dragon sword (cr)", "objtypes"),
            new GamevalEntry(28030, "PLACEHOLDER_BH_DRAGON_SHORTSWORD_CORRUPTED", "placeholder_bh_dragon_shortsword_corrupted", "objtypes"),
            new GamevalEntry(28031, "BH_DRAGON_SCIMITAR_CORRUPTED", "Dragon scimitar (cr)", "objtypes"),
            new GamevalEntry(28032, "PLACEHOLDER_BH_DRAGON_SCIMITAR_CORRUPTED", "placeholder_bh_dragon_scimitar_corrupted", "objtypes"),
            new GamevalEntry(28033, "BH_DRAGON_LONGSWORD_CORRUPTED", "Dragon longsword (cr)", "objtypes"),
            new GamevalEntry(28034, "PLACEHOLDER_BH_DRAGON_LONGSWORD_CORRUPTED", "placeholder_bh_dragon_longsword_corrupted", "objtypes"),
            new GamevalEntry(28035, "BH_DRAGON_WARHAMMER_CORRUPTED", "Dragon warhammer (cr)", "objtypes"),
            new GamevalEntry(28036, "PLACEHOLDER_BH_DRAGON_WARHAMMER_CORRUPTED", "placeholder_bh_dragon_warhammer_corrupted", "objtypes"),
            new GamevalEntry(28037, "BH_DRAGON_BATTLEAXE_CORRUPTED", "Dragon battleaxe (cr)", "objtypes"),
            new GamevalEntry(28038, "PLACEHOLDER_BH_DRAGON_BATTLEAXE_CORRUPTED", "placeholder_bh_dragon_battleaxe_corrupted", "objtypes"),
            new GamevalEntry(28039, "BH_DRAGON_CLAWS_CORRUPTED", "Dragon claws (cr)", "objtypes"),
            new GamevalEntry(28040, "PLACEHOLDER_BH_DRAGON_CLAWS_CORRUPTED", "placeholder_bh_dragon_claws_corrupted", "objtypes"),
            new GamevalEntry(28041, "BH_DRAGON_SPEAR_CORRUPTED", "Dragon spear (cr)", "objtypes"),
            new GamevalEntry(28042, "PLACEHOLDER_BH_DRAGON_SPEAR_CORRUPTED", "placeholder_bh_dragon_spear_corrupted", "objtypes"),
            new GamevalEntry(28043, "BH_DRAGON_SPEAR_P_CORRUPTED", "Dragon spear (p)(cr)", "objtypes"),
            new GamevalEntry(28044, "PLACEHOLDER_BH_DRAGON_SPEAR_P_CORRUPTED", "placeholder_bh_dragon_spear_p_corrupted", "objtypes"),
            new GamevalEntry(28049, "BH_DRAGON_HALBERD_CORRUPTED", "Dragon halberd (cr)", "objtypes"),
            new GamevalEntry(28050, "PLACEHOLDER_BH_DRAGON_HALBERD_CORRUPTED", "placeholder_bh_dragon_halberd_corrupted", "objtypes"),
            new GamevalEntry(28051, "BH_DRAGON_2H_SWORD_CORRUPTED", "Dragon 2h sword (cr)", "objtypes"),
            new GamevalEntry(28052, "PLACEHOLDER_BH_DRAGON_2H_SWORD_CORRUPTED", "placeholder_bh_dragon_2h_sword_corrupted", "objtypes"),
            new GamevalEntry(28053, "BH_XBOWS_CROSSBOW_DRAGON_CORRUPTED", "Dragon crossbow (cr)", "objtypes"),
            new GamevalEntry(28054, "PLACEHOLDER_BH_XBOWS_CROSSBOW_DRAGON_CORRUPTED", "placeholder_bh_xbows_crossbow_dragon_corrupted", "objtypes"),
            new GamevalEntry(28055, "BH_DRAGON_BOOTS_CORRUPTED", "Dragon boots (cr)", "objtypes"),
            new GamevalEntry(28056, "PLACEHOLDER_BH_DRAGON_BOOTS_CORRUPTED", "placeholder_bh_dragon_boots_corrupted", "objtypes"),
            new GamevalEntry(28057, "BH_DRAGON_MED_HELM_CORRUPTED", "Dragon med helm (cr)", "objtypes"),
            new GamevalEntry(28058, "PLACEHOLDER_BH_DRAGON_MED_HELM_CORRUPTED", "placeholder_bh_dragon_med_helm_corrupted", "objtypes"),
            new GamevalEntry(28059, "BH_DRAGON_SQ_SHIELD_CORRUPTED", "Dragon sq shield (cr)", "objtypes"),
            new GamevalEntry(28060, "PLACEHOLDER_BH_DRAGON_SQ_SHIELD_CORRUPTED", "placeholder_bh_dragon_sq_shield_corrupted", "objtypes"),
            new GamevalEntry(28061, "BH_DRAGON_PLATELEGS_CORRUPTED", "Dragon platelegs (cr)", "objtypes"),
            new GamevalEntry(28062, "PLACEHOLDER_BH_DRAGON_PLATELEGS_CORRUPTED", "placeholder_bh_dragon_platelegs_corrupted", "objtypes"),
            new GamevalEntry(28063, "BH_DRAGON_PLATESKIRT_CORRUPTED", "Dragon plateskirt (cr)", "objtypes"),
            new GamevalEntry(28064, "PLACEHOLDER_BH_DRAGON_PLATESKIRT_CORRUPTED", "placeholder_bh_dragon_plateskirt_corrupted", "objtypes"),
            new GamevalEntry(28065, "BH_DRAGON_CHAINBODY_CORRUPTED", "Dragon chainbody (cr)", "objtypes"),
            new GamevalEntry(28066, "PLACEHOLDER_BH_DRAGON_CHAINBODY_CORRUPTED", "placeholder_bh_dragon_chainbody_corrupted", "objtypes"),
            new GamevalEntry(28067, "BH_BARBASSAULT_PENANCE_FIGHTER_TORSO_CORRUPTED", "Fighter torso (or)", "objtypes"),
            new GamevalEntry(28068, "PLACEHOLDER_BH_BARBASSAULT_PENANCE_FIGHTER_TORSO_CORRUPTED", "placeholder_bh_barbassault_penance_fighter_torso_corrupted", "objtypes"),
            new GamevalEntry(28069, "BH_BARBASSAULT_PENANCE_FIGHTER_TORSO_CORRUPTED_TROUVER", "Fighter torso (l)(or)", "objtypes"),
            new GamevalEntry(28070, "BH_FRIS_KINGLY_HELM_CORRUPTED", "Helm of neitiznot (or)", "objtypes"),
            new GamevalEntry(28071, "PLACEHOLDER_BH_FRIS_KINGLY_HELM_CORRUPTED", "placeholder_bh_fris_kingly_helm_corrupted", "objtypes"),
            new GamevalEntry(28072, "BH_DARKBOW_IMBUE_SCROLL", "Dark bow imbue scroll", "objtypes"),
            new GamevalEntry(28073, "PLACEHOLDER_BH_DARKBOW_IMBUE_SCROLL", "placeholder_bh_darkbow_imbue_scroll", "objtypes"),
            new GamevalEntry(28074, "BH_BRAIN_ANCHOR_IMBUE_SCROLL", "Barrelchest anchor imbue scroll", "objtypes"),
            new GamevalEntry(28075, "PLACEHOLDER_BH_BRAIN_ANCHOR_IMBUE_SCROLL", "placeholder_bh_brain_anchor_imbue_scroll", "objtypes"),
            new GamevalEntry(28076, "BH_DRAGON_MACE_IMBUE_SCROLL", "Dragon mace imbue scroll", "objtypes"),
            new GamevalEntry(28077, "PLACEHOLDER_BH_DRAGON_MACE_IMBUE_SCROLL", "placeholder_bh_dragon_mace_imbue_scroll", "objtypes"),
            new GamevalEntry(28078, "BH_DRAGON_LONGSWORD_IMBUE_SCROLL", "Dragon longsword imbue scroll", "objtypes"),
            new GamevalEntry(28079, "PLACEHOLDER_BH_DRAGON_LONGSWORD_IMBUE_SCROLL", "placeholder_bh_dragon_longsword_imbue_scroll", "objtypes"),
            new GamevalEntry(28080, "BH_ABYSSAL_DAGGER_IMBUE_SCROLL", "Abyssal dagger imbue scroll", "objtypes"),
            new GamevalEntry(28081, "PLACEHOLDER_BH_ABYSSAL_DAGGER_IMBUE_SCROLL", "placeholder_bh_abyssal_dagger_imbue_scroll", "objtypes"),
            new GamevalEntry(28082, "BH_EP_CRATE_2", "Bounty crate (tier 1)", "objtypes"),
            new GamevalEntry(28083, "PLACEHOLDER_BH_EP_CRATE_2", "placeholder_bh_ep_crate_2", "objtypes"),
            new GamevalEntry(28084, "BH_EP_CRATE_3", "' Bounty crate (tier 2)", "objtypes"),
            new GamevalEntry(28085, "PLACEHOLDER_BH_EP_CRATE_3", "placeholder_bh_ep_crate_3", "objtypes"),
            new GamevalEntry(28086, "BH_EP_CRATE_4", "' Bounty crate (tier 3)", "objtypes"),
            new GamevalEntry(28087, "PLACEHOLDER_BH_EP_CRATE_4", "placeholder_bh_ep_crate_4", "objtypes"),
            new GamevalEntry(28088, "BH_EP_CRATE_5", "Bounty crate (tier 4)", "objtypes"),
            new GamevalEntry(28089, "PLACEHOLDER_BH_EP_CRATE_5", "placeholder_bh_ep_crate_5", "objtypes"),
            new GamevalEntry(28090, "BH_EP_CRATE_6", "Bounty crate (tier 5)", "objtypes"),
            new GamevalEntry(28091, "PLACEHOLDER_BH_EP_CRATE_6", "placeholder_bh_ep_crate_6", "objtypes"),
            new GamevalEntry(28092, "BH_EP_CRATE_7", "Bounty crate (tier 6)", "objtypes"),
            new GamevalEntry(28093, "PLACEHOLDER_BH_EP_CRATE_7", "placeholder_bh_ep_crate_7", "objtypes"),
            new GamevalEntry(28094, "BH_EP_CRATE_8", "Bounty crate (tier 7)", "objtypes"),
            new GamevalEntry(28095, "PLACEHOLDER_BH_EP_CRATE_8", "placeholder_bh_ep_crate_8", "objtypes"),
            new GamevalEntry(28096, "BH_EP_CRATE_9", "Bounty crate (tier 8)", "objtypes"),
            new GamevalEntry(28097, "PLACEHOLDER_BH_EP_CRATE_9", "placeholder_bh_ep_crate_9", "objtypes"),
            new GamevalEntry(28098, "BH_EP_CRATE_10", "Bounty crate (tier 9)", "objtypes"),
            new GamevalEntry(28099, "PLACEHOLDER_BH_EP_CRATE_10", "placeholder_bh_ep_crate_10", "objtypes"),
            new GamevalEntry(28100, "PRIDE23_SCROLLQ", "Null", "objtypes"),
            new GamevalEntry(28101, "PRIDE23_SCROLLG", "Null", "objtypes"),
            new GamevalEntry(28102, "PRIDE23_SCROLLB", "Null", "objtypes"),
            new GamevalEntry(28103, "PRIDE23_SCROLLT", "Null", "objtypes"),
            new GamevalEntry(28104, "PRIDE23_SCROLLTH", "Null", "objtypes"),
            new GamevalEntry(28105, "PRIDE23_SCROLLGH", "Null", "objtypes"),
            new GamevalEntry(28106, "PRIDE23_SCROLLBH", "Null", "objtypes"),
            new GamevalEntry(28107, "PRIDE23_SCROLLQH", "Null", "objtypes"),
            new GamevalEntry(28108, "PRIDE23_SCARF_BISEXUAL", "Colourful scarf", "objtypes"),
            new GamevalEntry(28109, "PRIDE23_SCARF_ASEXUAL", "Colourful scarf", "objtypes"),
            new GamevalEntry(28110, "PRIDE23_SCARF_TRANSGENDER", "Colourful scarf", "objtypes"),
            new GamevalEntry(28111, "PRIDE23_SCARF_PANSEXUAL", "Colourful scarf", "objtypes"),
            new GamevalEntry(28112, "PRIDE23_SCARF_NONBINARY", "Colourful scarf", "objtypes"),
            new GamevalEntry(28113, "PRIDE23_SCARF_GENDERQUEER", "Colourful scarf", "objtypes"),
            new GamevalEntry(28114, "PRIDE23_SCARF_LESBIAN", "Colourful scarf", "objtypes"),
            new GamevalEntry(28115, "PRIDE23_SCARF_GAY", "Colourful scarf", "objtypes"),
            new GamevalEntry(28116, "PRIDE23_JUMPER", "Rainbow jumper", "objtypes"),
            new GamevalEntry(28117, "PLACEHOLDER_PRIDE23_JUMPER", "placeholder_pride23_jumper", "objtypes"),
            new GamevalEntry(28118, "PRIDE23_JUMPER_BISEXUAL", "Colourful jumper", "objtypes"),
            new GamevalEntry(28119, "PRIDE23_JUMPER_ASEXUAL", "Colourful jumper", "objtypes"),
            new GamevalEntry(28120, "PRIDE23_JUMPER_TRANSGENDER", "Colourful jumper", "objtypes"),
            new GamevalEntry(28121, "PRIDE23_JUMPER_PANSEXUAL", "Colourful jumper", "objtypes"),
            new GamevalEntry(28122, "PRIDE23_JUMPER_NONBINARY", "Colourful jumper", "objtypes"),
            new GamevalEntry(28123, "PRIDE23_JUMPER_GENDERQUEER", "Colourful jumper", "objtypes"),
            new GamevalEntry(28124, "PRIDE23_JUMPER_LESBIAN", "Colourful jumper", "objtypes"),
            new GamevalEntry(28125, "PRIDE23_JUMPER_GAY", "Colourful jumper", "objtypes"),
            new GamevalEntry(28126, "PRIDE23_POETS_JACKET", "Poet's jacket", "objtypes"),
            new GamevalEntry(28127, "PLACEHOLDER_PRIDE23_POETS_JACKET", "placeholder_pride23_poets_jacket", "objtypes"),
            new GamevalEntry(28128, "PRIDE23_CROSSBOW", "Love crossbow", "objtypes"),
            new GamevalEntry(28129, "PLACEHOLDER_PRIDE23_CROSSBOW", "placeholder_pride23_crossbow", "objtypes"),
            new GamevalEntry(28130, "BARROWS_ICON", "Strange icon", "objtypes"),
            new GamevalEntry(28131, "BARROWS_ICON_DUST", "barrows_icon_dust", "objtypes"),
            new GamevalEntry(28132, "HFS_REWARD_LAMP", "Dusty lamp", "objtypes"),
            new GamevalEntry(28133, "BARROWS_MAP", "Crypt map", "objtypes"),
            new GamevalEntry(28134, "FORESTRY_CURRENCY", "Anima-infused bark", "objtypes"),
            new GamevalEntry(28135, "PLACEHOLDER_FORESTRY_CURRENCY", "placeholder_forestry_currency", "objtypes"),
            new GamevalEntry(28136, "FORESTRY_KIT", "Forestry kit", "objtypes"),
            new GamevalEntry(28137, "PLACEHOLDER_FORESTRY_KIT", "placeholder_forestry_kit", "objtypes"),
            new GamevalEntry(28138, "FORESTRY_FUNKY_SHAPED_LOG", "Funky shaped log", "objtypes"),
            new GamevalEntry(28139, "PLACEHOLDER_FORESTRY_FUNKY_SHAPED_LOG", "placeholder_forestry_funky_shaped_log", "objtypes"),
            new GamevalEntry(28140, "LOG_BASKET_CLOSED", "Log basket", "objtypes"),
            new GamevalEntry(28141, "PLACEHOLDER_LOG_BASKET_CLOSED", "placeholder_log_basket_closed", "objtypes"),
            new GamevalEntry(28142, "LOG_BASKET_OPEN", "Open log basket", "objtypes"),
            new GamevalEntry(28143, "FORESTRY_BASKET_CLOSED", "Forestry basket", "objtypes"),
            new GamevalEntry(28144, "PLACEHOLDER_FORESTRY_BASKET_CLOSED", "placeholder_forestry_basket_closed", "objtypes"),
            new GamevalEntry(28145, "FORESTRY_BASKET_OPEN", "Open forestry basket", "objtypes"),
            new GamevalEntry(28146, "FORESTRY_LOG_BRACE", "Log brace", "objtypes"),
            new GamevalEntry(28147, "CERT_FORESTRY_LOG_BRACE", "cert_forestry_log_brace", "objtypes"),
            new GamevalEntry(28148, "PLACEHOLDER_FORESTRY_LOG_BRACE", "placeholder_forestry_log_brace", "objtypes"),
            new GamevalEntry(28149, "FORESTRY_STURDY_HARNESS", "Sturdy harness", "objtypes"),
            new GamevalEntry(28150, "CERT_FORESTRY_STURDY_HARNESS", "cert_forestry_sturdy_harness", "objtypes"),
            new GamevalEntry(28151, "PLACEHOLDER_FORESTRY_STURDY_HARNESS", "placeholder_forestry_sturdy_harness", "objtypes"),
            new GamevalEntry(28152, "NATURE_OFFERINGS", "Nature offerings", "objtypes"),
            new GamevalEntry(28153, "PLACEHOLDER_NATURE_OFFERINGS", "placeholder_nature_offerings", "objtypes"),
            new GamevalEntry(28154, "NATURE_OFFERINGS_COMPONENT", "Ritual mulch", "objtypes"),
            new GamevalEntry(28155, "CERT_NATURE_OFFERINGS_COMPONENT", "cert_nature_offerings_component", "objtypes"),
            new GamevalEntry(28156, "PLACEHOLDER_NATURE_OFFERINGS_COMPONENT", "placeholder_nature_offerings_component", "objtypes"),
            new GamevalEntry(28157, "FORESTRY_RATION", "Forester's ration", "objtypes"),
            new GamevalEntry(28158, "PLACEHOLDER_FORESTRY_RATION", "placeholder_forestry_ration", "objtypes"),
            new GamevalEntry(28159, "FORESTRY_SECATEURS_BLADE", "Secateurs blade", "objtypes"),
            new GamevalEntry(28160, "PLACEHOLDER_FORESTRY_SECATEURS_BLADE", "placeholder_forestry_secateurs_blade", "objtypes"),
            new GamevalEntry(28161, "FORESTRY_SECATEURS_ATTACHMENT", "Secateurs attachment", "objtypes"),
            new GamevalEntry(28162, "PLACEHOLDER_FORESTRY_SECATEURS_ATTACHMENT", "placeholder_forestry_secateurs_attachment", "objtypes"),
            new GamevalEntry(28163, "FORESTRY_CLOTHES_POUCH", "Clothes pouch", "objtypes"),
            new GamevalEntry(28164, "CERT_FORESTRY_CLOTHES_POUCH", "cert_forestry_clothes_pouch", "objtypes"),
            new GamevalEntry(28165, "PLACEHOLDER_FORESTRY_CLOTHES_POUCH", "placeholder_forestry_clothes_pouch", "objtypes"),
            new GamevalEntry(28166, "FORESTRY_CLOTHES_POUCH_BLUEPRINT", "Clothes pouch blueprint", "objtypes"),
            new GamevalEntry(28167, "CERT_FORESTRY_CLOTHES_POUCH_BLUEPRINT", "cert_forestry_clothes_pouch_blueprint", "objtypes"),
            new GamevalEntry(28168, "PLACEHOLDER_FORESTRY_CLOTHES_POUCH_BLUEPRINT", "placeholder_forestry_clothes_pouch_blueprint", "objtypes"),
            new GamevalEntry(28169, "FORESTRY_LUMBERJACK_TOP", "Forestry top", "objtypes"),
            new GamevalEntry(28170, "PLACEHOLDER_FORESTRY_LUMBERJACK_TOP", "placeholder_forestry_lumberjack_top", "objtypes"),
        };
    }

    static Optional<GamevalEntry> byId(int id) {
        for (GamevalEntry entry : entries()) {
            if (entry.id() == id) return Optional.of(entry);
        }
        return Optional.empty();
    }

}
