package net.titan.gamevals.internal;

import java.util.Optional;

import net.titan.gamevals.GamevalEntry;
import net.titan.gamevals.QuestEntry;

final class ItemIDEntries_17 {
    private ItemIDEntries_17() {}

    static GamevalEntry[] entries() {
        return new GamevalEntry[] {
            new GamevalEntry(8894, "MAGICTRAINING_COINS_5", "magictraining_coins_5", "objtypes"),
            new GamevalEntry(8895, "MAGICTRAINING_COINS_25", "magictraining_coins_25", "objtypes"),
            new GamevalEntry(8896, "MAGICTRAINING_COINS_100", "magictraining_coins_100", "objtypes"),
            new GamevalEntry(8897, "MAGICTRAINING_COINS_250", "?? ? ?", "objtypes"),
            new GamevalEntry(8898, "MAGICTRAINING_COINS_1000", "magictraining_coins_1000", "objtypes"),
            new GamevalEntry(8899, "MAGICTRAINING_COINS_10000", "magictraining_coins_10000", "objtypes"),
            new GamevalEntry(8900, "SLAYERGUIDE_HARMLESS_CAVE_HORROR", "Cave horror", "objtypes"),
            new GamevalEntry(8901, "HARMLESS_BLACK_MASK_10", "Black mask (10)", "objtypes"),
            new GamevalEntry(8902, "CERT_HARMLESS_BLACK_MASK_10", "cert_harmless_black_mask_10", "objtypes"),
            new GamevalEntry(8903, "HARMLESS_BLACK_MASK_9", "Black mask (9)", "objtypes"),
            new GamevalEntry(8904, "CERT_HARMLESS_BLACK_MASK_9", "cert_harmless_black_mask_9", "objtypes"),
            new GamevalEntry(8905, "HARMLESS_BLACK_MASK_8", "Black mask (8)", "objtypes"),
            new GamevalEntry(8906, "CERT_HARMLESS_BLACK_MASK_8", "cert_harmless_black_mask_8", "objtypes"),
            new GamevalEntry(8907, "HARMLESS_BLACK_MASK_7", "Black mask (7)", "objtypes"),
            new GamevalEntry(8908, "CERT_HARMLESS_BLACK_MASK_7", "cert_harmless_black_mask_7", "objtypes"),
            new GamevalEntry(8909, "HARMLESS_BLACK_MASK_6", "Black mask (6)", "objtypes"),
            new GamevalEntry(8910, "CERT_HARMLESS_BLACK_MASK_6", "cert_harmless_black_mask_6", "objtypes"),
            new GamevalEntry(8911, "HARMLESS_BLACK_MASK_5", "Black mask (5)", "objtypes"),
            new GamevalEntry(8912, "CERT_HARMLESS_BLACK_MASK_5", "cert_harmless_black_mask_5", "objtypes"),
            new GamevalEntry(8913, "HARMLESS_BLACK_MASK_4", "Black mask (4)", "objtypes"),
            new GamevalEntry(8914, "CERT_HARMLESS_BLACK_MASK_4", "cert_harmless_black_mask_4", "objtypes"),
            new GamevalEntry(8915, "HARMLESS_BLACK_MASK_3", "Black mask (3)", "objtypes"),
            new GamevalEntry(8916, "CERT_HARMLESS_BLACK_MASK_3", "cert_harmless_black_mask_3", "objtypes"),
            new GamevalEntry(8917, "HARMLESS_BLACK_MASK_2", "Black mask (2)", "objtypes"),
            new GamevalEntry(8918, "CERT_HARMLESS_BLACK_MASK_2", "cert_harmless_black_mask_2", "objtypes"),
            new GamevalEntry(8919, "HARMLESS_BLACK_MASK_1", "Black mask (1)", "objtypes"),
            new GamevalEntry(8920, "CERT_HARMLESS_BLACK_MASK_1", "cert_harmless_black_mask_1", "objtypes"),
            new GamevalEntry(8921, "HARMLESS_BLACK_MASK", "Black mask", "objtypes"),
            new GamevalEntry(8922, "CERT_HARMLESS_BLACK_MASK", "cert_harmless_black_mask", "objtypes"),
            new GamevalEntry(8923, "WITCHWOOD_ICON", "Witchwood icon", "objtypes"),
            new GamevalEntry(8924, "PIRATE_BANDANA_EYEPATCH", "Bandana eyepatch (white)", "objtypes"),
            new GamevalEntry(8925, "PIRATE_BANDANA_EYEPATCH_RED", "Bandana eyepatch (red)", "objtypes"),
            new GamevalEntry(8926, "PIRATE_BANDANA_EYEPATCH_BLUE", "Bandana eyepatch (blue)", "objtypes"),
            new GamevalEntry(8927, "PIRATE_BANDANA_EYEPATCH_BROWN", "Bandana eyepatch (brown)", "objtypes"),
            new GamevalEntry(8928, "PIRATE_HAT_EYEPATCH", "Hat eyepatch", "objtypes"),
            new GamevalEntry(8929, "PIRATE_CRABCLAW_HOOK", "Crabclaw hook", "objtypes"),
            new GamevalEntry(8930, "BREW_PIPE_SECTION", "Pipe section", "objtypes"),
            new GamevalEntry(8931, "CERT_BREW_PIPE_SECTION", "cert_brew_pipe_section", "objtypes"),
            new GamevalEntry(8932, "BREW_LUMBER_PATCH", "Lumber patch", "objtypes"),
            new GamevalEntry(8933, "CERT_BREW_LUMBER_PATCH", "cert_brew_lumber_patch", "objtypes"),
            new GamevalEntry(8934, "BREW_SCRAPEY_LOGS", "Scrapey tree logs", "objtypes"),
            new GamevalEntry(8935, "CERT_BREW_SCRAPEY_LOGS", "cert_brew_scrapey_logs", "objtypes"),
            new GamevalEntry(8936, "BREW_BLUE_FLOWER", "Blue flowers", "objtypes"),
            new GamevalEntry(8937, "CERT_BREW_BLUE_FLOWER", "cert_brew_blue_flower", "objtypes"),
            new GamevalEntry(8938, "BREW_RED_FLOWER", "Red flowers", "objtypes"),
            new GamevalEntry(8939, "CERT_BREW_RED_FLOWER", "cert_brew_red_flower", "objtypes"),
            new GamevalEntry(8940, "BREW_RED_RUM", "Rum", "objtypes"),
            new GamevalEntry(8941, "BREW_BLUE_RUM", "Rum", "objtypes"),
            new GamevalEntry(8942, "BREW_MONKEY", "Monkey", "objtypes"),
            new GamevalEntry(8943, "BREW_BLUE_MONKEY", "Blue monkey", "objtypes"),
            new GamevalEntry(8944, "BREW_CAREFUL_BLUE_MONKEY", "Blue monkey", "objtypes"),
            new GamevalEntry(8945, "BREW_ANGRY_BLUE_MONKEY", "Blue monkey", "objtypes"),
            new GamevalEntry(8946, "BREW_RED_MONKEY", "Red monkey", "objtypes"),
            new GamevalEntry(8947, "BREW_CAREFUL_RED_MONKEY", "Red monkey", "objtypes"),
            new GamevalEntry(8948, "BREW_ANGRY_RED_MONKEY", "Red monkey", "objtypes"),
            new GamevalEntry(8949, "BREW_BLUE_PIRATE_HAT", "Pirate bandana", "objtypes"),
            new GamevalEntry(8950, "BREW_RED_PIRATE_HAT", "Pirate hat", "objtypes"),
            new GamevalEntry(8951, "BREW_PIECE_OF_EIGHT", "Pieces of eight", "objtypes"),
            new GamevalEntry(8952, "BREW_UNIFORM_BLUE", "Blue naval shirt", "objtypes"),
            new GamevalEntry(8953, "BREW_UNIFORM_GREEN", "Green naval shirt", "objtypes"),
            new GamevalEntry(8954, "BREW_UNIFORM_RED", "Red naval shirt", "objtypes"),
            new GamevalEntry(8955, "BREW_UNIFORM_BROWN", "Brown naval shirt", "objtypes"),
            new GamevalEntry(8956, "BREW_UNIFORM_BLACK", "Black naval shirt", "objtypes"),
            new GamevalEntry(8957, "BREW_UNIFORM_PURPLE", "Purple naval shirt", "objtypes"),
            new GamevalEntry(8958, "BREW_UNIFORM_GREY", "Grey naval shirt", "objtypes"),
            new GamevalEntry(8959, "BREW_TRICORN_BLUE", "Blue tricorn hat", "objtypes"),
            new GamevalEntry(8960, "BREW_TRICORN_GREEN", "Green tricorn hat", "objtypes"),
            new GamevalEntry(8961, "BREW_TRICORN_RED", "Red tricorn hat", "objtypes"),
            new GamevalEntry(8962, "BREW_TRICORN_BROWN", "Brown tricorn hat", "objtypes"),
            new GamevalEntry(8963, "BREW_TRICORN_BLACK", "Black tricorn hat", "objtypes"),
            new GamevalEntry(8964, "BREW_TRICORN_PURPLE", "Purple tricorn hat", "objtypes"),
            new GamevalEntry(8965, "BREW_TRICORN_GREY", "Grey tricorn hat", "objtypes"),
            new GamevalEntry(8966, "BREW_FLAG_1", "Cutthroat flag", "objtypes"),
            new GamevalEntry(8967, "BREW_FLAG_2", "Gilded smile flag", "objtypes"),
            new GamevalEntry(8968, "BREW_FLAG_3", "Bronze fist flag", "objtypes"),
            new GamevalEntry(8969, "BREW_FLAG_4", "Lucky shot flag", "objtypes"),
            new GamevalEntry(8970, "BREW_FLAG_5", "Treasure flag", "objtypes"),
            new GamevalEntry(8971, "BREW_FLAG_6", "X Phasmatys flag", "objtypes"),
            new GamevalEntry(8972, "BREW_BOWL_RED", "Bowl of red water", "objtypes"),
            new GamevalEntry(8973, "CERT_BREW_BOWL_RED", "cert_brew_bowl_red", "objtypes"),
            new GamevalEntry(8974, "BREW_BOWL_BLUE", "Bowl of blue water", "objtypes"),
            new GamevalEntry(8975, "CERT_BREW_BOWL_BLUE", "cert_brew_bowl_blue", "objtypes"),
            new GamevalEntry(8976, "BREW_BITTERNUT", "Bitternut", "objtypes"),
            new GamevalEntry(8977, "BREW_SCRAPEY_BARK", "Scrapey bark", "objtypes"),
            new GamevalEntry(8978, "CERT_BREW_SCRAPEY_BARK", "cert_brew_scrapey_bark", "objtypes"),
            new GamevalEntry(8979, "BREW_BRIDGE_SECTION", "Bridge section", "objtypes"),
            new GamevalEntry(8980, "CERT_BREW_BRIDGE_SECTION", "cert_brew_bridge_section", "objtypes"),
            new GamevalEntry(8981, "BREW_SWEETGRUBS", "Sweetgrubs", "objtypes"),
            new GamevalEntry(8982, "CERT_BREW_SWEETGRUBS", "cert_brew_sweetgrubs", "objtypes"),
            new GamevalEntry(8983, "BREW_PIECE_O_EIGHT1", "SK", "objtypes"),
            new GamevalEntry(8984, "BREW_PIECE_O_EIGHT2", "7K", "objtypes"),
            new GamevalEntry(8985, "BREW_PIECE_O_EIGHT3", "nK", "objtypes"),
            new GamevalEntry(8986, "BREW_BUCKET_DUMMY", "Bucket", "objtypes"),
            new GamevalEntry(8987, "BREW_FLAMING_TORCH", "Torch", "objtypes"),
            new GamevalEntry(8988, "BREW_HYPER_YEAST", "The stuff", "objtypes"),
            new GamevalEntry(8989, "GAME_BREW_INSTRUCTION_BOOK", "Brewin' guide", "objtypes"),
            new GamevalEntry(8990, "GAME_BREW_INSTRUCTION_BOOK_DUMMY", "Brewin' guide", "objtypes"),
            new GamevalEntry(8991, "BREW_NAVY_SLACKS_BLUE", "Blue navy slacks", "objtypes"),
            new GamevalEntry(8992, "BREW_NAVY_SLACKS_GREEN", "Green navy slacks", "objtypes"),
            new GamevalEntry(8993, "BREW_NAVY_SLACKS_RED", "Red navy slacks", "objtypes"),
            new GamevalEntry(8994, "BREW_NAVY_SLACKS_BROWN", "Brown navy slacks", "objtypes"),
            new GamevalEntry(8995, "BREW_NAVY_SLACKS_BLACK", "Black navy slacks", "objtypes"),
            new GamevalEntry(8996, "BREW_NAVY_SLACKS_PURPLE", "Purple navy slacks", "objtypes"),
            new GamevalEntry(8997, "BREW_NAVY_SLACKS_GREY", "Grey navy slacks", "objtypes"),
            new GamevalEntry(8998, "CERT_PIRATE_BANDANA_EYEPATCH", "cert_pirate_bandana_eyepatch", "objtypes"),
            new GamevalEntry(8999, "CERT_PIRATE_BANDANA_EYEPATCH_RED", "cert_pirate_bandana_eyepatch_red", "objtypes"),
            new GamevalEntry(9000, "CERT_PIRATE_BANDANA_EYEPATCH_BLUE", "cert_pirate_bandana_eyepatch_blue", "objtypes"),
            new GamevalEntry(9001, "CERT_PIRATE_BANDANA_EYEPATCH_BROWN", "cert_pirate_bandana_eyepatch_brown", "objtypes"),
            new GamevalEntry(9002, "CERT_PIRATE_HAT_EYEPATCH", "cert_pirate_hat_eyepatch", "objtypes"),
            new GamevalEntry(9003, "SOS_SECURITY_BOOK", "Security book", "objtypes"),
            new GamevalEntry(9004, "SOS_STRONGHOLD_BOOK", "Stronghold notes", "objtypes"),
            new GamevalEntry(9005, "SOS_BOOTS", "Fancy boots", "objtypes"),
            new GamevalEntry(9006, "SOS_BOOTS2", "Fighting boots", "objtypes"),
            new GamevalEntry(9007, "SOS_HALF_SKULL1", "Right skull half", "objtypes"),
            new GamevalEntry(9008, "SOS_HALF_SKULL2", "Left skull half", "objtypes"),
            new GamevalEntry(9009, "SOS_SKULL", "Strange skull", "objtypes"),
            new GamevalEntry(9010, "SOS_HALF_SCEPTRE1", "Top of sceptre", "objtypes"),
            new GamevalEntry(9011, "SOS_HALF_SCEPTRE2", "HK Bottom of sceptre", "objtypes"),
            new GamevalEntry(9012, "SOS_SCEPTRE", "Runed sceptre", "objtypes"),
            new GamevalEntry(9013, "SOS_SKULL_SCEPTRE", "Skull sceptre", "objtypes"),
            new GamevalEntry(9014, "CERT_SOS_SECURITY_BOOK", "cert_sos_security_book", "objtypes"),
            new GamevalEntry(9015, "CERT_SOS_STRONGHOLD_BOOK", "cert_sos_stronghold_book", "objtypes"),
            new GamevalEntry(9016, "FAIRYTALE2_GORAK_CLAWS", "Gorak claws", "objtypes"),
            new GamevalEntry(9017, "FAIRYTALE2_FLOWER_HERBS", "Star flower", "objtypes"),
            new GamevalEntry(9018, "FAIRYTALE2_GROUND_GORAK_CLAWS", "Gorak claw powder", "objtypes"),
            new GamevalEntry(9019, "FAIRYTALE2_STARFLOWERVIAL", "Magic essence (unf)", "objtypes"),
            new GamevalEntry(9020, "FAIRY_QUEEN_SECATEURS2", "Queen's secateurs", "objtypes"),
            new GamevalEntry(9021, "_4DOSEMAGICESS", "Magic essence(4)", "objtypes"),
            new GamevalEntry(9022, "_3DOSEMAGICESS", "Magic essence(3)", "objtypes"),
            new GamevalEntry(9023, "_2DOSEMAGICESS", "Magic essence(2)", "objtypes"),
            new GamevalEntry(9024, "_1DOSEMAGICESS", "Magic essence(1)", "objtypes"),
            new GamevalEntry(9025, "FAIRYTALE2_NUFFS_CERTIFICATE", "Nuff's certificate", "objtypes"),
            new GamevalEntry(9026, "NTK_IVORY_COMB", "Ivory comb", "objtypes"),
            new GamevalEntry(9027, "CERT_NTK_IVORY_COMB", "cert_ntk_ivory_comb", "objtypes"),
            new GamevalEntry(9028, "NTK_SCARAB_GOLD", "Golden scarab", "objtypes"),
            new GamevalEntry(9029, "CERT_NTK_SCARAB_GOLD", "cert_ntk_scarab_gold", "objtypes"),
            new GamevalEntry(9030, "NTK_SCARAB_STONE", "Stone scarab", "objtypes"),
            new GamevalEntry(9031, "CERT_NTK_SCARAB_STONE", "cert_ntk_scarab_stone", "objtypes"),
            new GamevalEntry(9032, "NTK_SCARAB_POTTERY", "Pottery scarab", "objtypes"),
            new GamevalEntry(9033, "CERT_NTK_SCARAB_POTTERY", "cert_ntk_scarab_pottery", "objtypes"),
            new GamevalEntry(9034, "NTK_STATUETTE_GOLD", "Golden statuette", "objtypes"),
            new GamevalEntry(9035, "CERT_NTK_STATUETTE_GOLD", "cert_ntk_statuette_gold", "objtypes"),
            new GamevalEntry(9036, "NTK_STATUETTE_POTTERY", "Pottery statuette", "objtypes"),
            new GamevalEntry(9037, "CERT_NTK_STATUETTE_POTTERY", "cert_ntk_statuette_pottery", "objtypes"),
            new GamevalEntry(9038, "NTK_STATUETTE_STONE", "Stone statuette", "objtypes"),
            new GamevalEntry(9039, "CERT_NTK_STATUETTE_STONE", "cert_ntk_statuette_stone", "objtypes"),
            new GamevalEntry(9040, "NTK_SEAL_GOLD", "Gold seal", "objtypes"),
            new GamevalEntry(9041, "CERT_NTK_SEAL_GOLD", "cert_ntk_seal_gold", "objtypes"),
            new GamevalEntry(9042, "NTK_SEAL_STONE", "Stone seal", "objtypes"),
            new GamevalEntry(9043, "CERT_NTK_SEAL_STONE", "cert_ntk_seal_stone", "objtypes"),
            new GamevalEntry(9044, "NTK_JEWELLED_SCEPTRE_3", "Pharaoh's sceptre", "objtypes"),
            new GamevalEntry(9045, "CERT_NTK_JEWELLED_SCEPTRE_3", "Pharaoh's sceptre", "objtypes"),
            new GamevalEntry(9046, "NTK_JEWELLED_SCEPTRE_2", "Pharaoh's sceptre", "objtypes"),
            new GamevalEntry(9047, "CERT_NTK_JEWELLED_SCEPTRE_2", "Pharaoh's sceptre", "objtypes"),
            new GamevalEntry(9048, "NTK_JEWELLED_SCEPTRE_1", "Pharaoh's sceptre", "objtypes"),
            new GamevalEntry(9049, "CERT_NTK_JEWELLED_SCEPTRE_1", "Pharaoh's sceptre", "objtypes"),
            new GamevalEntry(9050, "NTK_JEWELLED_SCEPTRE_0", "Pharaoh's sceptre", "objtypes"),
            new GamevalEntry(9051, "CERT_NTK_JEWELLED_SCEPTRE_0", "Pharaoh's sceptre", "objtypes"),
            new GamevalEntry(9052, "LOCUST_MEAT", "Locust meat", "objtypes"),
            new GamevalEntry(9053, "CERT_LOCUST_MEAT", "cert_locust_meat", "objtypes"),
            new GamevalEntry(9054, "GOBLIN_ARMOUR_RED", "Red goblin mail", "objtypes"),
            new GamevalEntry(9055, "GOBLIN_ARMOUR_BLACK", "Black goblin mail", "objtypes"),
            new GamevalEntry(9056, "GOBLIN_ARMOUR_YELLOW", "Yellow goblin mail", "objtypes"),
            new GamevalEntry(9057, "GOBLIN_ARMOUR_GREEN", "Green goblin mail", "objtypes"),
            new GamevalEntry(9058, "GOBLIN_ARMOUR_PURPLE", "Purple goblin mail", "objtypes"),
            new GamevalEntry(9059, "GOBLIN_ARMOUR_PINK", "Pink goblin mail", "objtypes"),
            new GamevalEntry(9060, "DYE_LEFT_RED", "dye_left_red", "objtypes"),
            new GamevalEntry(9061, "DYE_LEFT_BLUE", "dye_left_blue", "objtypes"),
            new GamevalEntry(9062, "DYE_RIGHT_BLUE", "dye_right_blue", "objtypes"),
            new GamevalEntry(9063, "DYE_RIGHT_YELLOW", "dye_right_yellow", "objtypes"),
            new GamevalEntry(9064, "BULLSEYE_LANTERN_UNLIT_LUNAR_QUEST", "Emerald lantern", "objtypes"),
            new GamevalEntry(9065, "BULLSEYE_LANTERN_LIT_LUNAR_QUEST", "Emerald lantern", "objtypes"),
            new GamevalEntry(9066, "BULLSEYE_LANTERN_LENS_LUNAR_QUEST", "Emerald lens", "objtypes"),
            new GamevalEntry(9067, "LUNAR_DREAM_LOGS", "Dream log", "objtypes"),
            new GamevalEntry(9068, "LUNAR_MOONCLAN_HEADGEAR", "Moonclan helm", "objtypes"),
            new GamevalEntry(9069, "LUNAR_MOONCLAN_HAT", "Moonclan hat", "objtypes"),
            new GamevalEntry(9070, "LUNAR_MOONCLAN_TORSO", "Moonclan armour", "objtypes"),
            new GamevalEntry(9071, "LUNAR_MOONCLAN_SKIRT", "Moonclan skirt", "objtypes"),
            new GamevalEntry(9072, "LUNAR_MOONCLAN_GLOVES", "Moonclan gloves", "objtypes"),
            new GamevalEntry(9073, "LUNAR_MOONCLAN_BOOTS", "Moonclan boots", "objtypes"),
            new GamevalEntry(9074, "LUNAR_MOONCLAN_CAPE", "Moonclan cape", "objtypes"),
            new GamevalEntry(9075, "ASTRALRUNE", "Astral rune", "objtypes"),
            new GamevalEntry(9076, "QUEST_LUNAR_MAGIC_ORE", "Lunar ore", "objtypes"),
            new GamevalEntry(9077, "QUEST_LUNAR_MAGIC_BAR", "Lunar bar", "objtypes"),
            new GamevalEntry(9078, "LUNAR_BOOK", "3 Moonclan manual", "objtypes"),
            new GamevalEntry(9079, "SUQKA_TOOTH", "Suqah tooth", "objtypes"),
            new GamevalEntry(9080, "SUQKA_HIDE_UNTANNED", "Suqah hide", "objtypes"),
            new GamevalEntry(9081, "SUQKA_HIDE", "( (+( (/( ('( ( ( Suqah leather", "objtypes"),
            new GamevalEntry(9082, "LUNAR_GROUNDTOOTH", "Ground tooth", "objtypes"),
            new GamevalEntry(9083, "LUNAR_SEAL_OF_PASSAGE", "Seal of passage", "objtypes"),
            new GamevalEntry(9084, "LUNAR_MOONCLAN_LIMINAL_STAFF", "Lunar staff", "objtypes"),
            new GamevalEntry(9085, "LUNAR_MOONCLAN_LIMINAL_VIAL_EMPTY", "Empty vial", "objtypes"),
            new GamevalEntry(9086, "LUNAR_MOONCLAN_LIMINAL_VIAL_WATER", "Vial of water", "objtypes"),
            new GamevalEntry(9087, "LUNAR_MOONCLAN_LIMINAL_VIAL_FULL", "Waking sleep vial", "objtypes"),
            new GamevalEntry(9088, "LUNAR_MOONCLAN_LIMINAL_GUAM", "Guam vial", "objtypes"),
            new GamevalEntry(9089, "LUNAR_MOONCLAN_LIMINAL_MARR", "Marr vial", "objtypes"),
            new GamevalEntry(9090, "LUNAR_MOONCLAN_LIMINAL_GUAMMARR", "Guam-marr vial", "objtypes"),
            new GamevalEntry(9091, "DRAMEN_STAFF_AIR", "Lunar staff - pt1", "objtypes"),
            new GamevalEntry(9092, "DRAMEN_STAFF_FIRE", "Lunar staff - pt2", "objtypes"),
            new GamevalEntry(9093, "DRAMEN_STAFF_WATER", "Lunar staff - pt3", "objtypes"),
            new GamevalEntry(9094, "LUNAR_MOONCLAN_KINDLING", "CK ? Kindling", "objtypes"),
            new GamevalEntry(9095, "LUNAR_MOONCLAN_KINDLING_SOAKED", "CK ? Soaked kindling", "objtypes"),
            new GamevalEntry(9096, "LUNAR_HELMET", "Lunar helm", "objtypes"),
            new GamevalEntry(9097, "LUNAR_TORSO", "Lunar torso", "objtypes"),
            new GamevalEntry(9098, "LUNAR_LEGS", "Lunar legs", "objtypes"),
            new GamevalEntry(9099, "LUNAR_GLOVES", "Lunar gloves", "objtypes"),
            new GamevalEntry(9100, "LUNAR_BOOTS", "Lunar boots", "objtypes"),
            new GamevalEntry(9101, "LUNAR_CAPE", "Lunar cape", "objtypes"),
            new GamevalEntry(9102, "LUNAR_AMULET", "Lunar amulet", "objtypes"),
            new GamevalEntry(9103, "LUNAR_TIARA", "A special tiara", "objtypes"),
            new GamevalEntry(9104, "LUNAR_RING", "Lunar ring", "objtypes"),
            new GamevalEntry(9105, "SLAYERGUIDE_SUQAH_MONSTER", "Suqah monster", "objtypes"),
            new GamevalEntry(9106, "TIARA_ASTRAL", "Astral tiara", "objtypes"),
            new GamevalEntry(9107, "_65_BAKE_PIE", "ZBake pies without a stove", "objtypes"),
            new GamevalEntry(9108, "_66_CURE_PLANT", "ZCures disease on farming patch", "objtypes"),
            new GamevalEntry(9109, "_67_NPC_CONTACT", "ZContact various characters across long distances", "objtypes"),
            new GamevalEntry(9110, "_68_CURE_OTHER", "ZCure poisoned players", "objtypes"),
            new GamevalEntry(9111, "_69_TELE_MOONCLAN", "ZTeleports you to Moonclan Island", "objtypes"),
            new GamevalEntry(9112, "_70_TELE_MOONCLAN_GROUP", "ZTeleports players to Moonclan Island", "objtypes"),
            new GamevalEntry(9113, "_71_CURE_ME", "ZCure Poison", "objtypes"),
            new GamevalEntry(9114, "_72_TELE_WATERBIRTH", "ZTeleports you to Waterbirth Island", "objtypes"),
            new GamevalEntry(9115, "_73_TELE_WATERBIRTH_GROUP", "ZTeleports players to Waterbirth Island", "objtypes"),
            new GamevalEntry(9116, "_74_CURE_GROUP", "ZCure poison on players", "objtypes"),
            new GamevalEntry(9117, "_75_TELE_BARB_OUTPOST", "ZTeleports you to the Barbarian Outpost", "objtypes"),
            new GamevalEntry(9118, "_76_TELE_BARB_OUTPOST_GROUP", "ZTeleports players to the Barbarian Outpost", "objtypes"),
            new GamevalEntry(9119, "_77_SUPERGLASS", "ZMake glass without a furnace", "objtypes"),
            new GamevalEntry(9120, "_78_TELE_PORT_KHAZARD", "ZTeleports you to Port Khazard", "objtypes"),
            new GamevalEntry(9121, "_79_TELE_PORT_KHAZARD_GROUP", "ZTeleports players to Port Khazard", "objtypes"),
            new GamevalEntry(9122, "_80_STRING_JEWELRY", "ZString amulets without wool", "objtypes"),
            new GamevalEntry(9123, "_81_RES_POT_SHARE", "ZShares a potion with up to 4 nearby players", "objtypes"),
            new GamevalEntry(9124, "_82_MAGIC_IMBUE", "ZCombine runes without a talisman", "objtypes"),
            new GamevalEntry(9125, "_83_TREAT_SOIL", "ZFertilise a farming patch with super compost", "objtypes"),
            new GamevalEntry(9126, "_84_STATBOOST_POT_SHARE", "ZShares a potion with up to 4 nearby players", "objtypes"),
            new GamevalEntry(9127, "_85_TELE_FISH_GUILD", "ZTeleports you to the Fishing Guild", "objtypes"),
            new GamevalEntry(9128, "_86_TELE_FISH_GUILD_GROUP", "ZTeleports players to the Fishing Guild", "objtypes"),
            new GamevalEntry(9129, "_87_TELE_CATHERBY", "ZTeleports you to Catherby", "objtypes"),
            new GamevalEntry(9130, "_88_TELE_CATHERBY_GROUP", "ZTeleports players to Catherby", "objtypes"),
            new GamevalEntry(9131, "_89_TELE_GHORROCK", "ZTeleports you to Ice Plateau", "objtypes"),
            new GamevalEntry(9132, "_90_TELE_GHORROCK_GROUP", "ZTeleports players to Ice Plateau", "objtypes"),
            new GamevalEntry(9133, "_91_ENERGY_TRANSFER", "ZSpend Hitpoints and SA energy to give another SA and run energy", "objtypes"),
            new GamevalEntry(9134, "_92_HEAL_OTHER", "YHeal Other", "objtypes"),
            new GamevalEntry(9135, "_93_VENGEANCE_OTHER", "ZAllows another player to rebound damage to an opponent", "objtypes"),
            new GamevalEntry(9136, "_94_VENGEANCE", "ZRebound damage to an opponent", "objtypes"),
            new GamevalEntry(9137, "_95_HEAL_GROUP", "YHeal Group", "objtypes"),
            new GamevalEntry(9138, "OGRE_LOGS", "ogre_logs", "objtypes"),
            new GamevalEntry(9139, "XBOWS_CROSSBOW_BOLTS_BLURITE", "Blurite bolts", "objtypes"),
            new GamevalEntry(9140, "XBOWS_CROSSBOW_BOLTS_IRON", "Iron bolts", "objtypes"),
            new GamevalEntry(9141, "XBOWS_CROSSBOW_BOLTS_STEEL", "Steel bolts", "objtypes"),
            new GamevalEntry(9142, "XBOWS_CROSSBOW_BOLTS_MITHRIL", "Mithril bolts", "objtypes"),
            new GamevalEntry(9143, "XBOWS_CROSSBOW_BOLTS_ADAMANTITE", "Adamant bolts", "objtypes"),
            new GamevalEntry(9144, "XBOWS_CROSSBOW_BOLTS_RUNITE", "Runite bolts", "objtypes"),
            new GamevalEntry(9145, "XBOWS_CROSSBOW_BOLTS_SILVER", "Silver bolts", "objtypes"),
            new GamevalEntry(9146, "XBOWS_CROSSBOW_BOLTS_BLURITE_2", "xbows_crossbow_bolts_blurite_2", "objtypes"),
            new GamevalEntry(9147, "XBOWS_CROSSBOW_BOLTS_BLURITE_3", "xbows_crossbow_bolts_blurite_3", "objtypes"),
            new GamevalEntry(9148, "XBOWS_CROSSBOW_BOLTS_BLURITE_4", "xbows_crossbow_bolts_blurite_4", "objtypes"),
            new GamevalEntry(9149, "XBOWS_CROSSBOW_BOLTS_BLURITE_5", "xbows_crossbow_bolts_blurite_5", "objtypes"),
            new GamevalEntry(9150, "XBOWS_CROSSBOW_BOLTS_IRON_2", "xbows_crossbow_bolts_iron_2", "objtypes"),
            new GamevalEntry(9151, "XBOWS_CROSSBOW_BOLTS_IRON_3", "xbows_crossbow_bolts_iron_3", "objtypes"),
            new GamevalEntry(9152, "XBOWS_CROSSBOW_BOLTS_IRON_4", "xbows_crossbow_bolts_iron_4", "objtypes"),
            new GamevalEntry(9153, "XBOWS_CROSSBOW_BOLTS_IRON_5", "xbows_crossbow_bolts_iron_5", "objtypes"),
            new GamevalEntry(9154, "XBOWS_CROSSBOW_BOLTS_STEEL_2", "xbows_crossbow_bolts_steel_2", "objtypes"),
            new GamevalEntry(9155, "XBOWS_CROSSBOW_BOLTS_STEEL_3", "xbows_crossbow_bolts_steel_3", "objtypes"),
            new GamevalEntry(9156, "XBOWS_CROSSBOW_BOLTS_STEEL_4", "xbows_crossbow_bolts_steel_4", "objtypes"),
            new GamevalEntry(9157, "XBOWS_CROSSBOW_BOLTS_STEEL_5", "xbows_crossbow_bolts_steel_5", "objtypes"),
            new GamevalEntry(9158, "XBOWS_CROSSBOW_BOLTS_MITHRIL_2", "xbows_crossbow_bolts_mithril_2", "objtypes"),
            new GamevalEntry(9159, "XBOWS_CROSSBOW_BOLTS_MITHRIL_3", "xbows_crossbow_bolts_mithril_3", "objtypes"),
            new GamevalEntry(9160, "XBOWS_CROSSBOW_BOLTS_MITHRIL_4", "xbows_crossbow_bolts_mithril_4", "objtypes"),
            new GamevalEntry(9161, "XBOWS_CROSSBOW_BOLTS_MITHRIL_5", "xbows_crossbow_bolts_mithril_5", "objtypes"),
            new GamevalEntry(9162, "XBOWS_CROSSBOW_BOLTS_ADAMANTITE_2", "xbows_crossbow_bolts_adamantite_2", "objtypes"),
            new GamevalEntry(9163, "XBOWS_CROSSBOW_BOLTS_ADAMANTITE_3", "xbows_crossbow_bolts_adamantite_3", "objtypes"),
            new GamevalEntry(9164, "XBOWS_CROSSBOW_BOLTS_ADAMANTITE_4", "xbows_crossbow_bolts_adamantite_4", "objtypes"),
            new GamevalEntry(9165, "XBOWS_CROSSBOW_BOLTS_ADAMANTITE_5", "xbows_crossbow_bolts_adamantite_5", "objtypes"),
            new GamevalEntry(9166, "XBOWS_CROSSBOW_BOLTS_RUNITE_2", "xbows_crossbow_bolts_runite_2", "objtypes"),
            new GamevalEntry(9167, "XBOWS_CROSSBOW_BOLTS_RUNITE_3", "xbows_crossbow_bolts_runite_3", "objtypes"),
            new GamevalEntry(9168, "XBOWS_CROSSBOW_BOLTS_RUNITE_4", "xbows_crossbow_bolts_runite_4", "objtypes"),
            new GamevalEntry(9169, "XBOWS_CROSSBOW_BOLTS_RUNITE_5", "xbows_crossbow_bolts_runite_5", "objtypes"),
            new GamevalEntry(9170, "XBOWS_CROSSBOW_BOLTS_SILVER_2", "xbows_crossbow_bolts_silver_2", "objtypes"),
            new GamevalEntry(9171, "XBOWS_CROSSBOW_BOLTS_SILVER_3", "xbows_crossbow_bolts_silver_3", "objtypes"),
            new GamevalEntry(9172, "XBOWS_CROSSBOW_BOLTS_SILVER_4", "xbows_crossbow_bolts_silver_4", "objtypes"),
            new GamevalEntry(9173, "XBOWS_CROSSBOW_BOLTS_SILVER_5", "xbows_crossbow_bolts_silver_5", "objtypes"),
            new GamevalEntry(9174, "XBOWS_CROSSBOW_BRONZE", "Bronze crossbow", "objtypes"),
            new GamevalEntry(9175, "CERT_XBOWS_CROSSBOW_BRONZE", "cert_xbows_crossbow_bronze", "objtypes"),
            new GamevalEntry(9176, "XBOWS_CROSSBOW_BLURITE", "Blurite crossbow", "objtypes"),
            new GamevalEntry(9177, "XBOWS_CROSSBOW_IRON", "Iron crossbow", "objtypes"),
            new GamevalEntry(9178, "CERT_XBOWS_CROSSBOW_IRON", "cert_xbows_crossbow_iron", "objtypes"),
            new GamevalEntry(9179, "XBOWS_CROSSBOW_STEEL", "Steel crossbow", "objtypes"),
            new GamevalEntry(9180, "CERT_XBOWS_CROSSBOW_STEEL", "cert_xbows_crossbow_steel", "objtypes"),
            new GamevalEntry(9181, "XBOWS_CROSSBOW_MITHRIL", "Mithril crossbow", "objtypes"),
            new GamevalEntry(9182, "CERT_XBOWS_CROSSBOW_MITHRIL", "cert_xbows_crossbow_mithril", "objtypes"),
            new GamevalEntry(9183, "XBOWS_CROSSBOW_ADAMANTITE", "Adamant crossbow", "objtypes"),
            new GamevalEntry(9184, "CERT_XBOWS_CROSSBOW_ADAMANTITE", "cert_xbows_crossbow_adamantite", "objtypes"),
            new GamevalEntry(9185, "XBOWS_CROSSBOW_RUNITE", "Rune crossbow", "objtypes"),
            new GamevalEntry(9186, "CERT_XBOWS_CROSSBOW_RUNITE", "cert_xbows_crossbow_runite", "objtypes"),
            new GamevalEntry(9187, "XBOWS_BOLT_TIPS_JADE", "Jade bolt tips", "objtypes"),
            new GamevalEntry(9188, "XBOWS_BOLT_TIPS_REDTOPAZ", "Topaz bolt tips", "objtypes"),
            new GamevalEntry(9189, "XBOWS_BOLT_TIPS_SAPPHIRE", "Sapphire bolt tips", "objtypes"),
            new GamevalEntry(9190, "XBOWS_BOLT_TIPS_EMERALD", "Emerald bolt tips", "objtypes"),
            new GamevalEntry(9191, "XBOWS_BOLT_TIPS_RUBY", "A( (? 3 Ruby bolt tips", "objtypes"),
            new GamevalEntry(9192, "XBOWS_BOLT_TIPS_DIAMOND", "Diamond bolt tips", "objtypes"),
            new GamevalEntry(9193, "XBOWS_BOLT_TIPS_DRAGONSTONE", "Dragonstone bolt tips", "objtypes"),
            new GamevalEntry(9194, "XBOWS_BOLT_TIPS_ONYX", "Onyx bolt tips", "objtypes"),
            new GamevalEntry(9195, "XBOWS_BOLT_TIPS_JADE_2", "xbows_bolt_tips_jade_2", "objtypes"),
            new GamevalEntry(9196, "XBOWS_BOLT_TIPS_JADE_3", "xbows_bolt_tips_jade_3", "objtypes"),
            new GamevalEntry(9197, "XBOWS_BOLT_TIPS_JADE_4", "xbows_bolt_tips_jade_4", "objtypes"),
            new GamevalEntry(9198, "XBOWS_BOLT_TIPS_JADE_5", "xbows_bolt_tips_jade_5", "objtypes"),
            new GamevalEntry(9199, "XBOWS_BOLT_TIPS_OPAL_2", "xbows_bolt_tips_opal_2", "objtypes"),
            new GamevalEntry(9200, "XBOWS_BOLT_TIPS_OPAL_3", "xbows_bolt_tips_opal_3", "objtypes"),
            new GamevalEntry(9201, "XBOWS_BOLT_TIPS_OPAL_4", "xbows_bolt_tips_opal_4", "objtypes"),
            new GamevalEntry(9202, "XBOWS_BOLT_TIPS_OPAL_5", "xbows_bolt_tips_opal_5", "objtypes"),
            new GamevalEntry(9203, "XBOWS_BOLT_TIPS_PEARL_2", "xbows_bolt_tips_pearl_2", "objtypes"),
            new GamevalEntry(9204, "XBOWS_BOLT_TIPS_PEARL_3", "xbows_bolt_tips_pearl_3", "objtypes"),
            new GamevalEntry(9205, "XBOWS_BOLT_TIPS_PEARL_4", "xbows_bolt_tips_pearl_4", "objtypes"),
            new GamevalEntry(9206, "XBOWS_BOLT_TIPS_PEARL_5", "xbows_bolt_tips_pearl_5", "objtypes"),
            new GamevalEntry(9207, "XBOWS_BOLT_TIPS_REDTOPAZ_2", "xbows_bolt_tips_redtopaz_2", "objtypes"),
            new GamevalEntry(9208, "XBOWS_BOLT_TIPS_REDTOPAZ_3", "xbows_bolt_tips_redtopaz_3", "objtypes"),
            new GamevalEntry(9209, "XBOWS_BOLT_TIPS_REDTOPAZ_4", "xbows_bolt_tips_redtopaz_4", "objtypes"),
            new GamevalEntry(9210, "XBOWS_BOLT_TIPS_REDTOPAZ_5", "xbows_bolt_tips_redtopaz_5", "objtypes"),
            new GamevalEntry(9211, "XBOWS_BOLT_TIPS_SAPPHIRE_2", "xbows_bolt_tips_sapphire_2", "objtypes"),
            new GamevalEntry(9212, "XBOWS_BOLT_TIPS_SAPPHIRE_3", "xbows_bolt_tips_sapphire_3", "objtypes"),
            new GamevalEntry(9213, "XBOWS_BOLT_TIPS_SAPPHIRE_4", "xbows_bolt_tips_sapphire_4", "objtypes"),
            new GamevalEntry(9214, "XBOWS_BOLT_TIPS_SAPPHIRE_5", "xbows_bolt_tips_sapphire_5", "objtypes"),
            new GamevalEntry(9215, "XBOWS_BOLT_TIPS_EMERALD_2", "xbows_bolt_tips_emerald_2", "objtypes"),
            new GamevalEntry(9216, "XBOWS_BOLT_TIPS_EMERALD_3", "xbows_bolt_tips_emerald_3", "objtypes"),
            new GamevalEntry(9217, "XBOWS_BOLT_TIPS_EMERALD_4", "xbows_bolt_tips_emerald_4", "objtypes"),
            new GamevalEntry(9218, "XBOWS_BOLT_TIPS_EMERALD_5", "xbows_bolt_tips_emerald_5", "objtypes"),
            new GamevalEntry(9219, "XBOWS_BOLT_TIPS_RUBY_2", "xbows_bolt_tips_ruby_2", "objtypes"),
            new GamevalEntry(9220, "XBOWS_BOLT_TIPS_RUBY_3", "xbows_bolt_tips_ruby_3", "objtypes"),
            new GamevalEntry(9221, "XBOWS_BOLT_TIPS_RUBY_4", "xbows_bolt_tips_ruby_4", "objtypes"),
            new GamevalEntry(9222, "XBOWS_BOLT_TIPS_RUBY_5", "xbows_bolt_tips_ruby_5", "objtypes"),
            new GamevalEntry(9223, "XBOWS_BOLT_TIPS_DIAMOND_2", "xbows_bolt_tips_diamond_2", "objtypes"),
            new GamevalEntry(9224, "XBOWS_BOLT_TIPS_DIAMOND_3", "xbows_bolt_tips_diamond_3", "objtypes"),
            new GamevalEntry(9225, "XBOWS_BOLT_TIPS_DIAMOND_4", "xbows_bolt_tips_diamond_4", "objtypes"),
            new GamevalEntry(9226, "XBOWS_BOLT_TIPS_DIAMOND_5", "xbows_bolt_tips_diamond_5", "objtypes"),
            new GamevalEntry(9227, "XBOWS_BOLT_TIPS_DRAGONSTONE_2", "xbows_bolt_tips_dragonstone_2", "objtypes"),
            new GamevalEntry(9228, "XBOWS_BOLT_TIPS_DRAGONSTONE_3", "xbows_bolt_tips_dragonstone_3", "objtypes"),
            new GamevalEntry(9229, "XBOWS_BOLT_TIPS_DRAGONSTONE_4", "xbows_bolt_tips_dragonstone_4", "objtypes"),
            new GamevalEntry(9230, "XBOWS_BOLT_TIPS_DRAGONSTONE_5", "xbows_bolt_tips_dragonstone_5", "objtypes"),
            new GamevalEntry(9231, "XBOWS_BOLT_TIPS_ONYX_2", "xbows_bolt_tips_onyx_2", "objtypes"),
            new GamevalEntry(9232, "XBOWS_BOLT_TIPS_ONYX_3", "xbows_bolt_tips_onyx_3", "objtypes"),
            new GamevalEntry(9233, "XBOWS_BOLT_TIPS_ONYX_4", "xbows_bolt_tips_onyx_4", "objtypes"),
            new GamevalEntry(9234, "XBOWS_BOLT_TIPS_ONYX_5", "xbows_bolt_tips_onyx_5", "objtypes"),
            new GamevalEntry(9235, "XBOWS_BOLT_TIPS_INACTIVE", "xbows_bolt_tips_inactive", "objtypes"),
            new GamevalEntry(9236, "XBOWS_CROSSBOW_BOLTS_BRONZE_TIPPED_OPAL_ENCHANTED", "Opal bolts (e)", "objtypes"),
            new GamevalEntry(9237, "XBOWS_CROSSBOW_BOLTS_BLURITE_TIPPED_JADE_ENCHANTED", "Jade bolts (e)", "objtypes"),
            new GamevalEntry(9238, "XBOWS_CROSSBOW_BOLTS_IRON_TIPPED_PEARL_ENCHANTED", "Pearl bolts (e)", "objtypes"),
            new GamevalEntry(9239, "XBOWS_CROSSBOW_BOLTS_STEEL_TIPPED_REDTOPAZ_ENCHANTED", "Topaz bolts (e)", "objtypes"),
            new GamevalEntry(9240, "XBOWS_CROSSBOW_BOLTS_MITHRIL_TIPPED_SAPPHIRE_ENCHANTED", "Sapphire bolts (e)", "objtypes"),
            new GamevalEntry(9241, "XBOWS_CROSSBOW_BOLTS_MITHRIL_TIPPED_EMERALD_ENCHANTED", "Emerald bolts (e)", "objtypes"),
            new GamevalEntry(9242, "XBOWS_CROSSBOW_BOLTS_ADAMANTITE_TIPPED_RUBY_ENCHANTED", "3 Ruby bolts (e)", "objtypes"),
            new GamevalEntry(9243, "XBOWS_CROSSBOW_BOLTS_ADAMANTITE_TIPPED_DIAMOND_ENCHANTED", "Diamond bolts (e)", "objtypes"),
            new GamevalEntry(9244, "XBOWS_CROSSBOW_BOLTS_RUNITE_TIPPED_DRAGONSTONE_ENCHANTED", "Dragonstone bolts (e)", "objtypes"),
            new GamevalEntry(9245, "XBOWS_CROSSBOW_BOLTS_RUNITE_TIPPED_ONYX_ENCHANTED", "Onyx bolts (e)", "objtypes"),
            new GamevalEntry(9246, "XBOWS_CROSSBOW_BOLTS_BRONZE_TIPPED_OPAL_ENCHANTED_2", "xbows_crossbow_bolts_bronze_tipped_opal_enchanted_2", "objtypes"),
            new GamevalEntry(9247, "XBOWS_CROSSBOW_BOLTS_BRONZE_TIPPED_OPAL_ENCHANTED_3", "xbows_crossbow_bolts_bronze_tipped_opal_enchanted_3", "objtypes"),
            new GamevalEntry(9248, "XBOWS_CROSSBOW_BOLTS_BRONZE_TIPPED_OPAL_ENCHANTED_4", "xbows_crossbow_bolts_bronze_tipped_opal_enchanted_4", "objtypes"),
            new GamevalEntry(9249, "XBOWS_CROSSBOW_BOLTS_BRONZE_TIPPED_OPAL_ENCHANTED_5", "xbows_crossbow_bolts_bronze_tipped_opal_enchanted_5", "objtypes"),
            new GamevalEntry(9250, "XBOWS_CROSSBOW_BOLTS_IRON_TIPPED_PEARL_ENCHANTED_2", "xbows_crossbow_bolts_iron_tipped_pearl_enchanted_2", "objtypes"),
            new GamevalEntry(9251, "XBOWS_CROSSBOW_BOLTS_IRON_TIPPED_PEARL_ENCHANTED_3", "xbows_crossbow_bolts_iron_tipped_pearl_enchanted_3", "objtypes"),
            new GamevalEntry(9252, "XBOWS_CROSSBOW_BOLTS_IRON_TIPPED_PEARL_ENCHANTED_4", "xbows_crossbow_bolts_iron_tipped_pearl_enchanted_4", "objtypes"),
            new GamevalEntry(9253, "XBOWS_CROSSBOW_BOLTS_IRON_TIPPED_PEARL_ENCHANTED_5", "xbows_crossbow_bolts_iron_tipped_pearl_enchanted_5", "objtypes"),
            new GamevalEntry(9254, "XBOWS_CROSSBOW_BOLTS_BLURITE_TIPPED_JADE_ENCHANTED_2", "xbows_crossbow_bolts_blurite_tipped_jade_enchanted_2", "objtypes"),
            new GamevalEntry(9255, "XBOWS_CROSSBOW_BOLTS_BLURITE_TIPPED_JADE_ENCHANTED_3", "xbows_crossbow_bolts_blurite_tipped_jade_enchanted_3", "objtypes"),
            new GamevalEntry(9256, "XBOWS_CROSSBOW_BOLTS_BLURITE_TIPPED_JADE_ENCHANTED_4", "xbows_crossbow_bolts_blurite_tipped_jade_enchanted_4", "objtypes"),
            new GamevalEntry(9257, "XBOWS_CROSSBOW_BOLTS_BLURITE_TIPPED_JADE_ENCHANTED_5", "xbows_crossbow_bolts_blurite_tipped_jade_enchanted_5", "objtypes"),
            new GamevalEntry(9258, "XBOWS_CROSSBOW_BOLTS_STEEL_TIPPED_REDTOPAZ_ENCHANTED_2", "xbows_crossbow_bolts_steel_tipped_redtopaz_enchanted_2", "objtypes"),
            new GamevalEntry(9259, "XBOWS_CROSSBOW_BOLTS_STEEL_TIPPED_REDTOPAZ_ENCHANTED_3", "xbows_crossbow_bolts_steel_tipped_redtopaz_enchanted_3", "objtypes"),
            new GamevalEntry(9260, "XBOWS_CROSSBOW_BOLTS_STEEL_TIPPED_REDTOPAZ_ENCHANTED_4", "xbows_crossbow_bolts_steel_tipped_redtopaz_enchanted_4", "objtypes"),
            new GamevalEntry(9261, "XBOWS_CROSSBOW_BOLTS_STEEL_TIPPED_REDTOPAZ_ENCHANTED_5", "xbows_crossbow_bolts_steel_tipped_redtopaz_enchanted_5", "objtypes"),
            new GamevalEntry(9262, "XBOWS_CROSSBOW_BOLTS_MITHRIL_TIPPED_SAPPHIRE_ENCHANTED_2", "xbows_crossbow_bolts_mithril_tipped_sapphire_enchanted_2", "objtypes"),
            new GamevalEntry(9263, "XBOWS_CROSSBOW_BOLTS_MITHRIL_TIPPED_SAPPHIRE_ENCHANTED_3", "xbows_crossbow_bolts_mithril_tipped_sapphire_enchanted_3", "objtypes"),
            new GamevalEntry(9264, "XBOWS_CROSSBOW_BOLTS_MITHRIL_TIPPED_SAPPHIRE_ENCHANTED_4", "xbows_crossbow_bolts_mithril_tipped_sapphire_enchanted_4", "objtypes"),
            new GamevalEntry(9265, "XBOWS_CROSSBOW_BOLTS_MITHRIL_TIPPED_SAPPHIRE_ENCHANTED_5", "xbows_crossbow_bolts_mithril_tipped_sapphire_enchanted_5", "objtypes"),
            new GamevalEntry(9266, "XBOWS_CROSSBOW_BOLTS_MITHRIL_TIPPED_EMERALD_ENCHANTED_2", "xbows_crossbow_bolts_mithril_tipped_emerald_enchanted_2", "objtypes"),
            new GamevalEntry(9267, "XBOWS_CROSSBOW_BOLTS_MITHRIL_TIPPED_EMERALD_ENCHANTED_3", "xbows_crossbow_bolts_mithril_tipped_emerald_enchanted_3", "objtypes"),
            new GamevalEntry(9268, "XBOWS_CROSSBOW_BOLTS_MITHRIL_TIPPED_EMERALD_ENCHANTED_4", "xbows_crossbow_bolts_mithril_tipped_emerald_enchanted_4", "objtypes"),
            new GamevalEntry(9269, "XBOWS_CROSSBOW_BOLTS_MITHRIL_TIPPED_EMERALD_ENCHANTED_5", "xbows_crossbow_bolts_mithril_tipped_emerald_enchanted_5", "objtypes"),
            new GamevalEntry(9270, "XBOWS_CROSSBOW_BOLTS_ADAMANTITE_TIPPED_RUBY_ENCHANTED_2", "xbows_crossbow_bolts_adamantite_tipped_ruby_enchanted_2", "objtypes"),
            new GamevalEntry(9271, "XBOWS_CROSSBOW_BOLTS_ADAMANTITE_TIPPED_RUBY_ENCHANTED_3", "xbows_crossbow_bolts_adamantite_tipped_ruby_enchanted_3", "objtypes"),
            new GamevalEntry(9272, "XBOWS_CROSSBOW_BOLTS_ADAMANTITE_TIPPED_RUBY_ENCHANTED_4", "xbows_crossbow_bolts_adamantite_tipped_ruby_enchanted_4", "objtypes"),
            new GamevalEntry(9273, "XBOWS_CROSSBOW_BOLTS_ADAMANTITE_TIPPED_RUBY_ENCHANTED_5", "xbows_crossbow_bolts_adamantite_tipped_ruby_enchanted_5", "objtypes"),
            new GamevalEntry(9274, "XBOWS_CROSSBOW_BOLTS_ADAMANTITE_TIPPED_DIAMOND_ENCHANTED_2", "xbows_crossbow_bolts_adamantite_tipped_diamond_enchanted_2", "objtypes"),
            new GamevalEntry(9275, "XBOWS_CROSSBOW_BOLTS_ADAMANTITE_TIPPED_DIAMOND_ENCHANTED_3", "xbows_crossbow_bolts_adamantite_tipped_diamond_enchanted_3", "objtypes"),
            new GamevalEntry(9276, "XBOWS_CROSSBOW_BOLTS_ADAMANTITE_TIPPED_DIAMOND_ENCHANTED_4", "xbows_crossbow_bolts_adamantite_tipped_diamond_enchanted_4", "objtypes"),
            new GamevalEntry(9277, "XBOWS_CROSSBOW_BOLTS_ADAMANTITE_TIPPED_DIAMOND_ENCHANTED_5", "xbows_crossbow_bolts_adamantite_tipped_diamond_enchanted_5", "objtypes"),
            new GamevalEntry(9278, "XBOWS_CROSSBOW_BOLTS_RUNITE_TIPPED_DRAGONSTONE_ENCHANTED_2", "xbows_crossbow_bolts_runite_tipped_dragonstone_enchanted_2", "objtypes"),
            new GamevalEntry(9279, "XBOWS_CROSSBOW_BOLTS_RUNITE_TIPPED_DRAGONSTONE_ENCHANTED_3", "xbows_crossbow_bolts_runite_tipped_dragonstone_enchanted_3", "objtypes"),
            new GamevalEntry(9280, "XBOWS_CROSSBOW_BOLTS_RUNITE_TIPPED_DRAGONSTONE_ENCHANTED_4", "xbows_crossbow_bolts_runite_tipped_dragonstone_enchanted_4", "objtypes"),
            new GamevalEntry(9281, "XBOWS_CROSSBOW_BOLTS_RUNITE_TIPPED_DRAGONSTONE_ENCHANTED_5", "xbows_crossbow_bolts_runite_tipped_dragonstone_enchanted_5", "objtypes"),
            new GamevalEntry(9282, "XBOWS_CROSSBOW_BOLTS_RUNITE_TIPPED_ONYX_ENCHANTED_2", "xbows_crossbow_bolts_runite_tipped_onyx_enchanted_2", "objtypes"),
            new GamevalEntry(9283, "XBOWS_CROSSBOW_BOLTS_RUNITE_TIPPED_ONYX_ENCHANTED_3", "xbows_crossbow_bolts_runite_tipped_onyx_enchanted_3", "objtypes"),
            new GamevalEntry(9284, "XBOWS_CROSSBOW_BOLTS_RUNITE_TIPPED_ONYX_ENCHANTED_4", "xbows_crossbow_bolts_runite_tipped_onyx_enchanted_4", "objtypes"),
            new GamevalEntry(9285, "XBOWS_CROSSBOW_BOLTS_RUNITE_TIPPED_ONYX_ENCHANTED_5", "xbows_crossbow_bolts_runite_tipped_onyx_enchanted_5", "objtypes"),
            new GamevalEntry(9286, "XBOWS_CROSSBOW_BOLTS_BLURITE_POISONED", "Blurite bolts (p)", "objtypes"),
            new GamevalEntry(9287, "XBOWS_CROSSBOW_BOLTS_IRON_POISONED", "Iron bolts (p)", "objtypes"),
            new GamevalEntry(9288, "XBOWS_CROSSBOW_BOLTS_STEEL_POISONED", "Steel bolts (p)", "objtypes"),
            new GamevalEntry(9289, "XBOWS_CROSSBOW_BOLTS_MITHRIL_POISONED", "Mithril bolts (p)", "objtypes"),
            new GamevalEntry(9290, "XBOWS_CROSSBOW_BOLTS_ADAMANTITE_POISONED", "Adamant bolts (p)", "objtypes"),
            new GamevalEntry(9291, "XBOWS_CROSSBOW_BOLTS_RUNITE_POISONED", "Runite bolts (p)", "objtypes"),
            new GamevalEntry(9292, "XBOWS_CROSSBOW_BOLTS_SILVER_POISONED", "Silver bolts (p)", "objtypes"),
            new GamevalEntry(9307, "XBOWS_CROSSBOW_BOLTS_BLURITE_POISONED_2", "xbows_crossbow_bolts_blurite_poisoned_2", "objtypes"),
            new GamevalEntry(9308, "XBOWS_CROSSBOW_BOLTS_BLURITE_POISONED_3", "xbows_crossbow_bolts_blurite_poisoned_3", "objtypes"),
            new GamevalEntry(9309, "XBOWS_CROSSBOW_BOLTS_BLURITE_POISONED_4", "xbows_crossbow_bolts_blurite_poisoned_4", "objtypes"),
            new GamevalEntry(9310, "XBOWS_CROSSBOW_BOLTS_BLURITE_POISONED_5", "xbows_crossbow_bolts_blurite_poisoned_5", "objtypes"),
            new GamevalEntry(9311, "XBOWS_CROSSBOW_BOLTS_IRON_POISONED_2", "xbows_crossbow_bolts_iron_poisoned_2", "objtypes"),
            new GamevalEntry(9312, "XBOWS_CROSSBOW_BOLTS_IRON_POISONED_3", "xbows_crossbow_bolts_iron_poisoned_3", "objtypes"),
            new GamevalEntry(9313, "XBOWS_CROSSBOW_BOLTS_IRON_POISONED_4", "xbows_crossbow_bolts_iron_poisoned_4", "objtypes"),
            new GamevalEntry(9314, "XBOWS_CROSSBOW_BOLTS_IRON_POISONED_5", "xbows_crossbow_bolts_iron_poisoned_5", "objtypes"),
            new GamevalEntry(9315, "XBOWS_CROSSBOW_BOLTS_STEEL_POISONED_2", "xbows_crossbow_bolts_steel_poisoned_2", "objtypes"),
            new GamevalEntry(9316, "XBOWS_CROSSBOW_BOLTS_STEEL_POISONED_3", "xbows_crossbow_bolts_steel_poisoned_3", "objtypes"),
            new GamevalEntry(9317, "XBOWS_CROSSBOW_BOLTS_STEEL_POISONED_4", "xbows_crossbow_bolts_steel_poisoned_4", "objtypes"),
            new GamevalEntry(9318, "XBOWS_CROSSBOW_BOLTS_STEEL_POISONED_5", "xbows_crossbow_bolts_steel_poisoned_5", "objtypes"),
            new GamevalEntry(9319, "XBOWS_CROSSBOW_BOLTS_MITHRIL_POISONED_2", "xbows_crossbow_bolts_mithril_poisoned_2", "objtypes"),
            new GamevalEntry(9320, "XBOWS_CROSSBOW_BOLTS_MITHRIL_POISONED_3", "xbows_crossbow_bolts_mithril_poisoned_3", "objtypes"),
            new GamevalEntry(9321, "XBOWS_CROSSBOW_BOLTS_MITHRIL_POISONED_4", "xbows_crossbow_bolts_mithril_poisoned_4", "objtypes"),
            new GamevalEntry(9322, "XBOWS_CROSSBOW_BOLTS_MITHRIL_POISONED_5", "xbows_crossbow_bolts_mithril_poisoned_5", "objtypes"),
            new GamevalEntry(9323, "XBOWS_CROSSBOW_BOLTS_ADAMANTITE_POISONED_2", "xbows_crossbow_bolts_adamantite_poisoned_2", "objtypes"),
            new GamevalEntry(9324, "XBOWS_CROSSBOW_BOLTS_ADAMANTITE_POISONED_3", "xbows_crossbow_bolts_adamantite_poisoned_3", "objtypes"),
            new GamevalEntry(9325, "XBOWS_CROSSBOW_BOLTS_ADAMANTITE_POISONED_4", "xbows_crossbow_bolts_adamantite_poisoned_4", "objtypes"),
            new GamevalEntry(9326, "XBOWS_CROSSBOW_BOLTS_ADAMANTITE_POISONED_5", "xbows_crossbow_bolts_adamantite_poisoned_5", "objtypes"),
            new GamevalEntry(9327, "XBOWS_CROSSBOW_BOLTS_RUNITE_POISONED_2", "xbows_crossbow_bolts_runite_poisoned_2", "objtypes"),
            new GamevalEntry(9328, "XBOWS_CROSSBOW_BOLTS_RUNITE_POISONED_3", "xbows_crossbow_bolts_runite_poisoned_3", "objtypes"),
            new GamevalEntry(9329, "XBOWS_CROSSBOW_BOLTS_RUNITE_POISONED_4", "xbows_crossbow_bolts_runite_poisoned_4", "objtypes"),
            new GamevalEntry(9330, "XBOWS_CROSSBOW_BOLTS_RUNITE_POISONED_5", "xbows_crossbow_bolts_runite_poisoned_5", "objtypes"),
            new GamevalEntry(9331, "XBOWS_CROSSBOW_BOLTS_SILVER_POISONED_2", "xbows_crossbow_bolts_silver_poisoned_2", "objtypes"),
            new GamevalEntry(9332, "XBOWS_CROSSBOW_BOLTS_SILVER_POISONED_3", "xbows_crossbow_bolts_silver_poisoned_3", "objtypes"),
            new GamevalEntry(9333, "XBOWS_CROSSBOW_BOLTS_SILVER_POISONED_4", "xbows_crossbow_bolts_silver_poisoned_4", "objtypes"),
            new GamevalEntry(9334, "XBOWS_CROSSBOW_BOLTS_SILVER_POISONED_5", "xbows_crossbow_bolts_silver_poisoned_5", "objtypes"),
            new GamevalEntry(9335, "XBOWS_CROSSBOW_BOLTS_BLURITE_TIPPED_JADE", "Jade bolts", "objtypes"),
            new GamevalEntry(9336, "XBOWS_CROSSBOW_BOLTS_STEEL_TIPPED_REDTOPAZ", "Topaz bolts", "objtypes"),
            new GamevalEntry(9337, "XBOWS_CROSSBOW_BOLTS_MITHRIL_TIPPED_SAPPHIRE", "Sapphire bolts", "objtypes"),
            new GamevalEntry(9338, "XBOWS_CROSSBOW_BOLTS_MITHRIL_TIPPED_EMERALD", "Emerald bolts", "objtypes"),
            new GamevalEntry(9339, "XBOWS_CROSSBOW_BOLTS_ADAMANTITE_TIPPED_RUBY", "Ruby bolts", "objtypes"),
            new GamevalEntry(9340, "XBOWS_CROSSBOW_BOLTS_ADAMANTITE_TIPPED_DIAMOND", "Diamond bolts", "objtypes"),
            new GamevalEntry(9341, "XBOWS_CROSSBOW_BOLTS_RUNITE_TIPPED_DRAGONSTONE", "Dragonstone bolts", "objtypes"),
            new GamevalEntry(9342, "XBOWS_CROSSBOW_BOLTS_RUNITE_TIPPED_ONYX", "Onyx bolts", "objtypes"),
            new GamevalEntry(9343, "XBOWS_CROSSBOW_BOLTS_BLURITE_TIPPED_JADE_2", "xbows_crossbow_bolts_blurite_tipped_jade_2", "objtypes"),
            new GamevalEntry(9344, "XBOWS_CROSSBOW_BOLTS_BLURITE_TIPPED_JADE_3", "xbows_crossbow_bolts_blurite_tipped_jade_3", "objtypes"),
            new GamevalEntry(9345, "XBOWS_CROSSBOW_BOLTS_BLURITE_TIPPED_JADE_4", "xbows_crossbow_bolts_blurite_tipped_jade_4", "objtypes"),
            new GamevalEntry(9346, "XBOWS_CROSSBOW_BOLTS_BLURITE_TIPPED_JADE_5", "xbows_crossbow_bolts_blurite_tipped_jade_5", "objtypes"),
            new GamevalEntry(9347, "XBOWS_CROSSBOW_BOLTS_STEEL_TIPPED_REDTOPAZ_2", "xbows_crossbow_bolts_steel_tipped_redtopaz_2", "objtypes"),
            new GamevalEntry(9348, "XBOWS_CROSSBOW_BOLTS_STEEL_TIPPED_REDTOPAZ_3", "xbows_crossbow_bolts_steel_tipped_redtopaz_3", "objtypes"),
            new GamevalEntry(9349, "XBOWS_CROSSBOW_BOLTS_STEEL_TIPPED_REDTOPAZ_4", "xbows_crossbow_bolts_steel_tipped_redtopaz_4", "objtypes"),
            new GamevalEntry(9350, "XBOWS_CROSSBOW_BOLTS_STEEL_TIPPED_REDTOPAZ_5", "xbows_crossbow_bolts_steel_tipped_redtopaz_5", "objtypes"),
            new GamevalEntry(9351, "XBOWS_CROSSBOW_BOLTS_MITHRIL_TIPPED_SAPPHIRE_2", "xbows_crossbow_bolts_mithril_tipped_sapphire_2", "objtypes"),
            new GamevalEntry(9352, "XBOWS_CROSSBOW_BOLTS_MITHRIL_TIPPED_SAPPHIRE_3", "xbows_crossbow_bolts_mithril_tipped_sapphire_3", "objtypes"),
            new GamevalEntry(9353, "XBOWS_CROSSBOW_BOLTS_MITHRIL_TIPPED_SAPPHIRE_4", "xbows_crossbow_bolts_mithril_tipped_sapphire_4", "objtypes"),
            new GamevalEntry(9354, "XBOWS_CROSSBOW_BOLTS_MITHRIL_TIPPED_SAPPHIRE_5", "xbows_crossbow_bolts_mithril_tipped_sapphire_5", "objtypes"),
            new GamevalEntry(9355, "XBOWS_CROSSBOW_BOLTS_MITHRIL_TIPPED_EMERALD_2", "xbows_crossbow_bolts_mithril_tipped_emerald_2", "objtypes"),
            new GamevalEntry(9356, "XBOWS_CROSSBOW_BOLTS_MITHRIL_TIPPED_EMERALD_3", "xbows_crossbow_bolts_mithril_tipped_emerald_3", "objtypes"),
            new GamevalEntry(9357, "XBOWS_CROSSBOW_BOLTS_MITHRIL_TIPPED_EMERALD_4", "xbows_crossbow_bolts_mithril_tipped_emerald_4", "objtypes"),
            new GamevalEntry(9358, "XBOWS_CROSSBOW_BOLTS_MITHRIL_TIPPED_EMERALD_5", "xbows_crossbow_bolts_mithril_tipped_emerald_5", "objtypes"),
            new GamevalEntry(9359, "XBOWS_CROSSBOW_BOLTS_ADAMANTITE_TIPPED_RUBY_2", "xbows_crossbow_bolts_adamantite_tipped_ruby_2", "objtypes"),
            new GamevalEntry(9360, "XBOWS_CROSSBOW_BOLTS_ADAMANTITE_TIPPED_RUBY_3", "xbows_crossbow_bolts_adamantite_tipped_ruby_3", "objtypes"),
            new GamevalEntry(9361, "XBOWS_CROSSBOW_BOLTS_ADAMANTITE_TIPPED_RUBY_4", "xbows_crossbow_bolts_adamantite_tipped_ruby_4", "objtypes"),
            new GamevalEntry(9362, "XBOWS_CROSSBOW_BOLTS_ADAMANTITE_TIPPED_RUBY_5", "xbows_crossbow_bolts_adamantite_tipped_ruby_5", "objtypes"),
            new GamevalEntry(9363, "XBOWS_CROSSBOW_BOLTS_ADAMANTITE_TIPPED_DIAMOND_2", "xbows_crossbow_bolts_adamantite_tipped_diamond_2", "objtypes"),
            new GamevalEntry(9364, "XBOWS_CROSSBOW_BOLTS_ADAMANTITE_TIPPED_DIAMOND_3", "xbows_crossbow_bolts_adamantite_tipped_diamond_3", "objtypes"),
            new GamevalEntry(9365, "XBOWS_CROSSBOW_BOLTS_ADAMANTITE_TIPPED_DIAMOND_4", "xbows_crossbow_bolts_adamantite_tipped_diamond_4", "objtypes"),
            new GamevalEntry(9366, "XBOWS_CROSSBOW_BOLTS_ADAMANTITE_TIPPED_DIAMOND_5", "xbows_crossbow_bolts_adamantite_tipped_diamond_5", "objtypes"),
            new GamevalEntry(9367, "XBOWS_CROSSBOW_BOLTS_RUNITE_TIPPED_DRAGONSTONE_2", "xbows_crossbow_bolts_runite_tipped_dragonstone_2", "objtypes"),
            new GamevalEntry(9368, "XBOWS_CROSSBOW_BOLTS_RUNITE_TIPPED_DRAGONSTONE_3", "xbows_crossbow_bolts_runite_tipped_dragonstone_3", "objtypes"),
            new GamevalEntry(9369, "XBOWS_CROSSBOW_BOLTS_RUNITE_TIPPED_DRAGONSTONE_4", "xbows_crossbow_bolts_runite_tipped_dragonstone_4", "objtypes"),
            new GamevalEntry(9370, "XBOWS_CROSSBOW_BOLTS_RUNITE_TIPPED_DRAGONSTONE_5", "xbows_crossbow_bolts_runite_tipped_dragonstone_5", "objtypes"),
            new GamevalEntry(9371, "XBOWS_CROSSBOW_BOLTS_RUNITE_TIPPED_ONYX_2", "xbows_crossbow_bolts_runite_tipped_onyx_2", "objtypes"),
            new GamevalEntry(9372, "XBOWS_CROSSBOW_BOLTS_RUNITE_TIPPED_ONYX_3", "xbows_crossbow_bolts_runite_tipped_onyx_3", "objtypes"),
            new GamevalEntry(9373, "XBOWS_CROSSBOW_BOLTS_RUNITE_TIPPED_ONYX_4", "xbows_crossbow_bolts_runite_tipped_onyx_4", "objtypes"),
            new GamevalEntry(9374, "XBOWS_CROSSBOW_BOLTS_RUNITE_TIPPED_ONYX_5", "xbows_crossbow_bolts_runite_tipped_onyx_5", "objtypes"),
            new GamevalEntry(9375, "XBOWS_CROSSBOW_BOLTS_BRONZE_UNFEATHERED", "Bronze bolts (unf)", "objtypes"),
            new GamevalEntry(9376, "XBOWS_CROSSBOW_BOLTS_BLURITE_UNFEATHERED", "Blurite bolts (unf)", "objtypes"),
            new GamevalEntry(9377, "XBOWS_CROSSBOW_BOLTS_IRON_UNFEATHERED", "Iron bolts (unf)", "objtypes"),
            new GamevalEntry(9378, "XBOWS_CROSSBOW_BOLTS_STEEL_UNFEATHERED", "Steel bolts (unf)", "objtypes"),
            new GamevalEntry(9379, "XBOWS_CROSSBOW_BOLTS_MITHRIL_UNFEATHERED", "Mithril bolts (unf)", "objtypes"),
            new GamevalEntry(9380, "XBOWS_CROSSBOW_BOLTS_ADAMANTITE_UNFEATHERED", "Adamant bolts(unf)", "objtypes"),
            new GamevalEntry(9381, "XBOWS_CROSSBOW_BOLTS_RUNITE_UNFEATHERED", "Runite bolts (unf)", "objtypes"),
            new GamevalEntry(9382, "XBOWS_CROSSBOW_BOLTS_SILVER_UNFEATHERED", "Silver bolts (unf)", "objtypes"),
            new GamevalEntry(9383, "XBOWS_CROSSBOW_BOLTS_BRONZE_UNFEATHERED_2", "xbows_crossbow_bolts_bronze_unfeathered_2", "objtypes"),
            new GamevalEntry(9384, "XBOWS_CROSSBOW_BOLTS_BRONZE_UNFEATHERED_3", "xbows_crossbow_bolts_bronze_unfeathered_3", "objtypes"),
            new GamevalEntry(9385, "XBOWS_CROSSBOW_BOLTS_BRONZE_UNFEATHERED_4", "xbows_crossbow_bolts_bronze_unfeathered_4", "objtypes"),
            new GamevalEntry(9386, "XBOWS_CROSSBOW_BOLTS_BRONZE_UNFEATHERED_5", "xbows_crossbow_bolts_bronze_unfeathered_5", "objtypes"),
            new GamevalEntry(9387, "XBOWS_CROSSBOW_BOLTS_BLURITE_UNFEATHERED_2", "xbows_crossbow_bolts_blurite_unfeathered_2", "objtypes"),
            new GamevalEntry(9388, "XBOWS_CROSSBOW_BOLTS_BLURITE_UNFEATHERED_3", "xbows_crossbow_bolts_blurite_unfeathered_3", "objtypes"),
            new GamevalEntry(9389, "XBOWS_CROSSBOW_BOLTS_BLURITE_UNFEATHERED_4", "xbows_crossbow_bolts_blurite_unfeathered_4", "objtypes"),
            new GamevalEntry(9390, "XBOWS_CROSSBOW_BOLTS_BLURITE_UNFEATHERED_5", "xbows_crossbow_bolts_blurite_unfeathered_5", "objtypes"),
            new GamevalEntry(9391, "XBOWS_CROSSBOW_BOLTS_IRON_UNFEATHERED_2", "xbows_crossbow_bolts_iron_unfeathered_2", "objtypes"),
            new GamevalEntry(9392, "XBOWS_CROSSBOW_BOLTS_IRON_UNFEATHERED_3", "xbows_crossbow_bolts_iron_unfeathered_3", "objtypes"),
            new GamevalEntry(9393, "XBOWS_CROSSBOW_BOLTS_IRON_UNFEATHERED_4", "xbows_crossbow_bolts_iron_unfeathered_4", "objtypes"),
            new GamevalEntry(9394, "XBOWS_CROSSBOW_BOLTS_IRON_UNFEATHERED_5", "xbows_crossbow_bolts_iron_unfeathered_5", "objtypes"),
            new GamevalEntry(9395, "XBOWS_CROSSBOW_BOLTS_STEEL_UNFEATHERED_2", "xbows_crossbow_bolts_steel_unfeathered_2", "objtypes"),
            new GamevalEntry(9396, "XBOWS_CROSSBOW_BOLTS_STEEL_UNFEATHERED_3", "xbows_crossbow_bolts_steel_unfeathered_3", "objtypes"),
            new GamevalEntry(9397, "XBOWS_CROSSBOW_BOLTS_STEEL_UNFEATHERED_4", "xbows_crossbow_bolts_steel_unfeathered_4", "objtypes"),
            new GamevalEntry(9398, "XBOWS_CROSSBOW_BOLTS_STEEL_UNFEATHERED_5", "xbows_crossbow_bolts_steel_unfeathered_5", "objtypes"),
            new GamevalEntry(9399, "XBOWS_CROSSBOW_BOLTS_MITHRIL_UNFEATHERED_2", "xbows_crossbow_bolts_mithril_unfeathered_2", "objtypes"),
            new GamevalEntry(9400, "XBOWS_CROSSBOW_BOLTS_MITHRIL_UNFEATHERED_3", "xbows_crossbow_bolts_mithril_unfeathered_3", "objtypes"),
            new GamevalEntry(9401, "XBOWS_CROSSBOW_BOLTS_MITHRIL_UNFEATHERED_4", "xbows_crossbow_bolts_mithril_unfeathered_4", "objtypes"),
            new GamevalEntry(9402, "XBOWS_CROSSBOW_BOLTS_MITHRIL_UNFEATHERED_5", "xbows_crossbow_bolts_mithril_unfeathered_5", "objtypes"),
            new GamevalEntry(9403, "XBOWS_CROSSBOW_BOLTS_ADAMANTITE_UNFEATHERED_2", "xbows_crossbow_bolts_adamantite_unfeathered_2", "objtypes"),
            new GamevalEntry(9404, "XBOWS_CROSSBOW_BOLTS_ADAMANTITE_UNFEATHERED_3", "xbows_crossbow_bolts_adamantite_unfeathered_3", "objtypes"),
            new GamevalEntry(9405, "XBOWS_CROSSBOW_BOLTS_ADAMANTITE_UNFEATHERED_4", "xbows_crossbow_bolts_adamantite_unfeathered_4", "objtypes"),
            new GamevalEntry(9406, "XBOWS_CROSSBOW_BOLTS_ADAMANTITE_UNFEATHERED_5", "xbows_crossbow_bolts_adamantite_unfeathered_5", "objtypes"),
            new GamevalEntry(9407, "XBOWS_CROSSBOW_BOLTS_RUNITE_UNFEATHERED_2", "xbows_crossbow_bolts_runite_unfeathered_2", "objtypes"),
            new GamevalEntry(9408, "XBOWS_CROSSBOW_BOLTS_RUNITE_UNFEATHERED_3", "xbows_crossbow_bolts_runite_unfeathered_3", "objtypes"),
            new GamevalEntry(9409, "XBOWS_CROSSBOW_BOLTS_RUNITE_UNFEATHERED_4", "xbows_crossbow_bolts_runite_unfeathered_4", "objtypes"),
            new GamevalEntry(9410, "XBOWS_CROSSBOW_BOLTS_RUNITE_UNFEATHERED_5", "xbows_crossbow_bolts_runite_unfeathered_5", "objtypes"),
            new GamevalEntry(9411, "XBOWS_CROSSBOW_BOLTS_SILVER_UNFEATHERED_2", "xbows_crossbow_bolts_silver_unfeathered_2", "objtypes"),
            new GamevalEntry(9412, "XBOWS_CROSSBOW_BOLTS_SILVER_UNFEATHERED_3", "xbows_crossbow_bolts_silver_unfeathered_3", "objtypes"),
            new GamevalEntry(9413, "XBOWS_CROSSBOW_BOLTS_SILVER_UNFEATHERED_4", "xbows_crossbow_bolts_silver_unfeathered_4", "objtypes"),
            new GamevalEntry(9414, "XBOWS_CROSSBOW_BOLTS_SILVER_UNFEATHERED_5", "xbows_crossbow_bolts_silver_unfeathered_5", "objtypes"),
            new GamevalEntry(9415, "XBOWS_GRAPPLE_HOOK", "Grapple", "objtypes"),
            new GamevalEntry(9416, "XBOWS_GRAPPLE_TIP_MITHRIL", "Mith grapple tip", "objtypes"),
            new GamevalEntry(9417, "CERT_XBOWS_GRAPPLE_TIP_MITHRIL", "cert_xbows_grapple_tip_mithril", "objtypes"),
            new GamevalEntry(9418, "XBOWS_GRAPPLE_TIP_BOLT_MITHRIL", "Mith grapple", "objtypes"),
            new GamevalEntry(9419, "XBOWS_GRAPPLE_TIP_BOLT_MITHRIL_ROPE", "Mith grapple", "objtypes"),
        };
    }

    static Optional<GamevalEntry> byId(int id) {
        for (GamevalEntry entry : entries()) {
            if (entry.id() == id) return Optional.of(entry);
        }
        return Optional.empty();
    }

}
