package net.titan.gamevals.internal;

import java.util.Optional;

import net.titan.gamevals.GamevalEntry;
import net.titan.gamevals.QuestEntry;

final class ItemIDEntries_5 {
    private ItemIDEntries_5() {}

    static GamevalEntry[] entries() {
        return new GamevalEntry[] {
            new GamevalEntry(2566, "RING_OF_DUELING_1", "Ring of dueling(1)", "objtypes"),
            new GamevalEntry(2567, "CERT_RING_OF_DUELING_1", "cert_ring_of_dueling_1", "objtypes"),
            new GamevalEntry(2568, "RING_OF_FORGING", "Ring of forging", "objtypes"),
            new GamevalEntry(2569, "CERT_RING_OF_FORGING", "cert_ring_of_forging", "objtypes"),
            new GamevalEntry(2570, "RING_OF_LIFE", "Ring of life", "objtypes"),
            new GamevalEntry(2571, "CERT_RING_OF_LIFE", "cert_ring_of_life", "objtypes"),
            new GamevalEntry(2572, "RING_OF_WEALTH", "Coin Collection", "objtypes"),
            new GamevalEntry(2573, "CERT_RING_OF_WEALTH", "cert_ring_of_wealth", "objtypes"),
            new GamevalEntry(2574, "TRAIL_SEXTANT", "Sextant", "objtypes"),
            new GamevalEntry(2575, "TRAIL_WATCH", "Watch", "objtypes"),
            new GamevalEntry(2576, "TRAIL_CHART", "Chart", "objtypes"),
            new GamevalEntry(2577, "BOOTS_RANGER", "Ranger boots", "objtypes"),
            new GamevalEntry(2578, "CERT_BOOTS_RANGER", "cert_boots_ranger", "objtypes"),
            new GamevalEntry(2579, "BOOTS_WIZARD", "Wizard boots", "objtypes"),
            new GamevalEntry(2580, "CERT_BOOTS_WIZARD", "cert_boots_wizard", "objtypes"),
            new GamevalEntry(2581, "ROBINHOODHAT", "Robin hood hat", "objtypes"),
            new GamevalEntry(2582, "CERT_ROBINHOODHAT", "cert_robinhoodhat", "objtypes"),
            new GamevalEntry(2583, "BLACK_PLATEBODY_TRIM", "Black platebody (t)", "objtypes"),
            new GamevalEntry(2584, "CERT_BLACK_PLATEBODY_TRIM", "cert_black_platebody_trim", "objtypes"),
            new GamevalEntry(2585, "BLACK_PLATELEGS_TRIM", "Black platelegs (t)", "objtypes"),
            new GamevalEntry(2586, "CERT_BLACK_PLATELEGS_TRIM", "cert_black_platelegs_trim", "objtypes"),
            new GamevalEntry(2587, "BLACK_FULL_HELM_TRIM", "Black full helm (t)", "objtypes"),
            new GamevalEntry(2588, "CERT_BLACK_FULL_HELM_TRIM", "cert_black_full_helm_trim", "objtypes"),
            new GamevalEntry(2589, "BLACK_KITESHIELD_TRIM", "Black kiteshield (t)", "objtypes"),
            new GamevalEntry(2590, "CERT_BLACK_KITESHIELD_TRIM", "cert_black_kiteshield_trim", "objtypes"),
            new GamevalEntry(2591, "BLACK_PLATEBODY_GOLD", "Black platebody (g)", "objtypes"),
            new GamevalEntry(2592, "CERT_BLACK_PLATEBODY_GOLD", "cert_black_platebody_gold", "objtypes"),
            new GamevalEntry(2593, "BLACK_PLATELEGS_GOLD", "Black platelegs (g)", "objtypes"),
            new GamevalEntry(2594, "CERT_BLACK_PLATELEGS_GOLD", "cert_black_platelegs_gold", "objtypes"),
            new GamevalEntry(2595, "BLACK_FULL_HELM_GOLD", "Black full helm (g)", "objtypes"),
            new GamevalEntry(2596, "CERT_BLACK_FULL_HELM_GOLD", "cert_black_full_helm_gold", "objtypes"),
            new GamevalEntry(2597, "BLACK_KITESHIELD_GOLD", "Black kiteshield (g)", "objtypes"),
            new GamevalEntry(2598, "CERT_BLACK_KITESHIELD_GOLD", "cert_black_kiteshield_gold", "objtypes"),
            new GamevalEntry(2599, "ADAMANT_PLATEBODY_TRIM", "Adamant platebody (t)", "objtypes"),
            new GamevalEntry(2600, "CERT_ADAMANT_PLATEBODY_TRIM", "cert_adamant_platebody_trim", "objtypes"),
            new GamevalEntry(2601, "ADAMANT_PLATELEGS_TRIM", "Adamant platelegs (t)", "objtypes"),
            new GamevalEntry(2602, "CERT_ADAMANT_PLATELEGS_TRIM", "cert_adamant_platelegs_trim", "objtypes"),
            new GamevalEntry(2603, "ADAMANT_KITESHIELD_TRIM", "Adamant kiteshield (t)", "objtypes"),
            new GamevalEntry(2604, "CERT_ADAMANT_KITESHIELD_TRIM", "cert_adamant_kiteshield_trim", "objtypes"),
            new GamevalEntry(2605, "ADAMANT_FULL_HELM_TRIM", "Adamant full helm (t)", "objtypes"),
            new GamevalEntry(2606, "CERT_ADAMANT_FULL_HELM_TRIM", "cert_adamant_full_helm_trim", "objtypes"),
            new GamevalEntry(2607, "ADAMANT_PLATEBODY_GOLD", "Adamant platebody (g)", "objtypes"),
            new GamevalEntry(2608, "CERT_ADAMANT_PLATEBODY_GOLD", "cert_adamant_platebody_gold", "objtypes"),
            new GamevalEntry(2609, "ADAMANT_PLATELEGS_GOLD", "Adamant platelegs (g)", "objtypes"),
            new GamevalEntry(2610, "CERT_ADAMANT_PLATELEGS_GOLD", "cert_adamant_platelegs_gold", "objtypes"),
            new GamevalEntry(2611, "ADAMANT_KITESHIELD_GOLD", "Adamant kiteshield (g)", "objtypes"),
            new GamevalEntry(2612, "CERT_ADAMANT_KITESHIELD_GOLD", "cert_adamant_kiteshield_gold", "objtypes"),
            new GamevalEntry(2613, "ADAMANT_FULL_HELM_GOLD", "Adamant full helm (g)", "objtypes"),
            new GamevalEntry(2614, "CERT_ADAMANT_FULL_HELM_GOLD", "cert_adamant_full_helm_gold", "objtypes"),
            new GamevalEntry(2615, "RUNE_PLATEBODY_GOLD", "Rune platebody (g)", "objtypes"),
            new GamevalEntry(2616, "CERT_RUNE_PLATEBODY_GOLD", "cert_rune_platebody_gold", "objtypes"),
            new GamevalEntry(2617, "RUNE_PLATELEGS_GOLD", "Rune platelegs (g)", "objtypes"),
            new GamevalEntry(2618, "CERT_RUNE_PLATELEGS_GOLD", "cert_rune_platelegs_gold", "objtypes"),
            new GamevalEntry(2619, "RUNE_FULL_HELM_GOLD", "Rune full helm (g)", "objtypes"),
            new GamevalEntry(2620, "CERT_RUNE_FULL_HELM_GOLD", "cert_rune_full_helm_gold", "objtypes"),
            new GamevalEntry(2621, "RUNE_KITESHIELD_GOLD", "Rune kiteshield (g)", "objtypes"),
            new GamevalEntry(2622, "CERT_RUNE_KITESHIELD_GOLD", "cert_rune_kiteshield_gold", "objtypes"),
            new GamevalEntry(2623, "RUNE_PLATEBODY_TRIM", "Rune platebody (t)", "objtypes"),
            new GamevalEntry(2624, "CERT_RUNE_PLATEBODY_TRIM", "cert_rune_platebody_trim", "objtypes"),
            new GamevalEntry(2625, "RUNE_PLATELEGS_TRIM", "Rune platelegs (t)", "objtypes"),
            new GamevalEntry(2626, "CERT_RUNE_PLATELEGS_TRIM", "cert_rune_platelegs_trim", "objtypes"),
            new GamevalEntry(2627, "RUNE_FULL_HELM_TRIM", "Rune full helm (t)", "objtypes"),
            new GamevalEntry(2628, "CERT_RUNE_FULL_HELM_TRIM", "cert_rune_full_helm_trim", "objtypes"),
            new GamevalEntry(2629, "RUNE_KITESHIELD_TRIM", "Rune kiteshield (t)", "objtypes"),
            new GamevalEntry(2630, "CERT_RUNE_KITESHIELD_TRIM", "cert_rune_kiteshield_trim", "objtypes"),
            new GamevalEntry(2631, "HIGHWAYMANMASK", "Highwayman mask", "objtypes"),
            new GamevalEntry(2632, "CERT_HIGHWAYMANMASK", "cert_highwaymanmask", "objtypes"),
            new GamevalEntry(2633, "BERRET_BLUE", "Blue beret", "objtypes"),
            new GamevalEntry(2634, "CERT_BERRET_BLUE", "cert_berret_blue", "objtypes"),
            new GamevalEntry(2635, "BERRET_BLACK", "Black beret", "objtypes"),
            new GamevalEntry(2636, "CERT_BERRET_BLACK", "cert_berret_black", "objtypes"),
            new GamevalEntry(2637, "BERRET_WHITE", "White beret", "objtypes"),
            new GamevalEntry(2638, "CERT_BERRET_WHITE", "cert_berret_white", "objtypes"),
            new GamevalEntry(2639, "CAVALIER_BROWN", "Tan cavalier", "objtypes"),
            new GamevalEntry(2640, "CERT_CAVALIER_BROWN", "cert_cavalier_brown", "objtypes"),
            new GamevalEntry(2641, "CAVALIER_DARK", "Dark cavalier", "objtypes"),
            new GamevalEntry(2642, "CERT_CAVALIER_DARK", "cert_cavalier_dark", "objtypes"),
            new GamevalEntry(2643, "CAVALIER_BLACK", "Black cavalier", "objtypes"),
            new GamevalEntry(2644, "CERT_CAVALIER_BLACK", "cert_cavalier_black", "objtypes"),
            new GamevalEntry(2645, "HEADBAND_RED", "Red headband", "objtypes"),
            new GamevalEntry(2646, "CERT_HEADBAND_RED", "cert_headband_red", "objtypes"),
            new GamevalEntry(2647, "HEADBAND_BLACK", "Black headband", "objtypes"),
            new GamevalEntry(2648, "CERT_HEADBAND_BLACK", "cert_headband_black", "objtypes"),
            new GamevalEntry(2649, "HEADBAND_BROWN", "Brown headband", "objtypes"),
            new GamevalEntry(2650, "CERT_HEADBAND_BROWN", "cert_headband_brown", "objtypes"),
            new GamevalEntry(2651, "PIRATEHAT", "Pirate's hat", "objtypes"),
            new GamevalEntry(2652, "CERT_PIRATEHAT", "cert_piratehat", "objtypes"),
            new GamevalEntry(2653, "RUNE_PLATEBODY_ZAMORAK", "Zamorak platebody", "objtypes"),
            new GamevalEntry(2654, "CERT_RUNE_PLATEBODY_ZAMORAK", "cert_rune_platebody_zamorak", "objtypes"),
            new GamevalEntry(2655, "RUNE_PLATELEGS_ZAMORAK", "Zamorak platelegs", "objtypes"),
            new GamevalEntry(2656, "CERT_RUNE_PLATELEGS_ZAMORAK", "cert_rune_platelegs_zamorak", "objtypes"),
            new GamevalEntry(2657, "RUNE_FULL_HELM_ZAMORAK", "Zamorak full helm", "objtypes"),
            new GamevalEntry(2658, "CERT_RUNE_FULL_HELM_ZAMORAK", "cert_rune_full_helm_zamorak", "objtypes"),
            new GamevalEntry(2659, "RUNE_KITESHIELD_ZAMORAK", "Zamorak kiteshield", "objtypes"),
            new GamevalEntry(2660, "CERT_RUNE_KITESHIELD_ZAMORAK", "cert_rune_kiteshield_zamorak", "objtypes"),
            new GamevalEntry(2661, "RUNE_PLATEBODY_SARADOMIN", "Saradomin platebody", "objtypes"),
            new GamevalEntry(2662, "CERT_RUNE_PLATEBODY_SARADOMIN", "cert_rune_platebody_saradomin", "objtypes"),
            new GamevalEntry(2663, "RUNE_PLATELEGS_SARADOMIN", "Saradomin platelegs", "objtypes"),
            new GamevalEntry(2664, "CERT_RUNE_PLATELEGS_SARADOMIN", "cert_rune_platelegs_saradomin", "objtypes"),
            new GamevalEntry(2665, "RUNE_FULL_HELM_SARADOMIN", "Saradomin full helm", "objtypes"),
            new GamevalEntry(2666, "CERT_RUNE_FULL_HELM_SARADOMIN", "cert_rune_full_helm_saradomin", "objtypes"),
            new GamevalEntry(2667, "RUNE_KITESHIELD_SARADOMIN", "Saradomin kiteshield", "objtypes"),
            new GamevalEntry(2668, "CERT_RUNE_KITESHIELD_SARADOMIN", "cert_rune_kiteshield_saradomin", "objtypes"),
            new GamevalEntry(2669, "RUNE_PLATEBODY_GUTHIX", "Guthix platebody", "objtypes"),
            new GamevalEntry(2670, "CERT_RUNE_PLATEBODY_GUTHIX", "cert_rune_platebody_guthix", "objtypes"),
            new GamevalEntry(2671, "RUNE_PLATELEGS_GUTHIX", "Guthix platelegs", "objtypes"),
            new GamevalEntry(2672, "CERT_RUNE_PLATELEGS_GUTHIX", "cert_rune_platelegs_guthix", "objtypes"),
            new GamevalEntry(2673, "RUNE_FULL_HELM_GUTHIX", "Guthix full helm", "objtypes"),
            new GamevalEntry(2674, "CERT_RUNE_FULL_HELM_GUTHIX", "cert_rune_full_helm_guthix", "objtypes"),
            new GamevalEntry(2675, "RUNE_KITESHIELD_GUTHIX", "Guthix kiteshield", "objtypes"),
            new GamevalEntry(2676, "CERT_RUNE_KITESHIELD_GUTHIX", "cert_rune_kiteshield_guthix", "objtypes"),
            new GamevalEntry(2677, "TRAIL_CLUE_EASY_SIMPLE001", "Clue scroll (easy)", "objtypes"),
            new GamevalEntry(2678, "TRAIL_CLUE_EASY_SIMPLE002", "Clue scroll (easy)", "objtypes"),
            new GamevalEntry(2679, "TRAIL_CLUE_EASY_SIMPLE003", "Clue scroll (easy)", "objtypes"),
            new GamevalEntry(2680, "TRAIL_CLUE_EASY_SIMPLE004", "Clue scroll (easy)", "objtypes"),
            new GamevalEntry(2681, "TRAIL_CLUE_EASY_SIMPLE005", "Clue scroll (easy)", "objtypes"),
            new GamevalEntry(2682, "TRAIL_CLUE_EASY_SIMPLE006", "Clue scroll (easy)", "objtypes"),
            new GamevalEntry(2683, "TRAIL_CLUE_EASY_SIMPLE007", "Clue scroll (easy)", "objtypes"),
            new GamevalEntry(2684, "TRAIL_CLUE_EASY_SIMPLE008", "Clue scroll (easy)", "objtypes"),
            new GamevalEntry(2685, "TRAIL_CLUE_EASY_SIMPLE009", "Clue scroll (easy)", "objtypes"),
            new GamevalEntry(2686, "TRAIL_CLUE_EASY_SIMPLE010", "Clue scroll (easy)", "objtypes"),
            new GamevalEntry(2687, "TRAIL_CLUE_EASY_SIMPLE011", "Clue scroll (easy)", "objtypes"),
            new GamevalEntry(2688, "TRAIL_CLUE_EASY_SIMPLE012", "Clue scroll (easy)", "objtypes"),
            new GamevalEntry(2689, "TRAIL_CLUE_EASY_SIMPLE013", "Clue scroll (easy)", "objtypes"),
            new GamevalEntry(2690, "TRAIL_CLUE_EASY_SIMPLE014", "Clue scroll (easy)", "objtypes"),
            new GamevalEntry(2691, "TRAIL_CLUE_EASY_SIMPLE015", "Clue scroll (easy)", "objtypes"),
            new GamevalEntry(2692, "TRAIL_CLUE_EASY_SIMPLE016", "Clue scroll (easy)", "objtypes"),
            new GamevalEntry(2693, "TRAIL_CLUE_EASY_SIMPLE017", "Clue scroll (easy)", "objtypes"),
            new GamevalEntry(2694, "TRAIL_CLUE_EASY_SIMPLE018", "Clue scroll (easy)", "objtypes"),
            new GamevalEntry(2695, "TRAIL_CLUE_EASY_SIMPLE019", "Clue scroll (easy)", "objtypes"),
            new GamevalEntry(2696, "TRAIL_CLUE_EASY_SIMPLE020", "Clue scroll (easy)", "objtypes"),
            new GamevalEntry(2697, "TRAIL_CLUE_EASY_SIMPLE021", "Clue scroll (easy)", "objtypes"),
            new GamevalEntry(2698, "TRAIL_CLUE_EASY_SIMPLE022", "Clue scroll (easy)", "objtypes"),
            new GamevalEntry(2699, "TRAIL_CLUE_EASY_SIMPLE023", "Clue scroll (easy)", "objtypes"),
            new GamevalEntry(2700, "TRAIL_CLUE_EASY_SIMPLE024", "Clue scroll (easy)", "objtypes"),
            new GamevalEntry(2701, "TRAIL_CLUE_EASY_SIMPLE025", "Clue scroll (easy)", "objtypes"),
            new GamevalEntry(2702, "TRAIL_CLUE_EASY_SIMPLE026", "Clue scroll (easy)", "objtypes"),
            new GamevalEntry(2703, "TRAIL_CLUE_EASY_SIMPLE027", "Clue scroll (easy)", "objtypes"),
            new GamevalEntry(2704, "TRAIL_CLUE_EASY_SIMPLE028", "Clue scroll (easy)", "objtypes"),
            new GamevalEntry(2705, "TRAIL_CLUE_EASY_SIMPLE029", "Clue scroll (easy)", "objtypes"),
            new GamevalEntry(2706, "TRAIL_CLUE_EASY_SIMPLE030", "Clue scroll (easy)", "objtypes"),
            new GamevalEntry(2707, "TRAIL_CLUE_EASY_SIMPLE031", "Clue scroll (easy)", "objtypes"),
            new GamevalEntry(2708, "TRAIL_CLUE_EASY_VAGUE001", "Clue scroll (easy)", "objtypes"),
            new GamevalEntry(2709, "TRAIL_CLUE_EASY_VAGUE002", "Clue scroll (easy)", "objtypes"),
            new GamevalEntry(2710, "TRAIL_CLUE_EASY_VAGUE003", "Clue scroll (easy)", "objtypes"),
            new GamevalEntry(2711, "TRAIL_CLUE_EASY_VAGUE004", "Clue scroll (easy)", "objtypes"),
            new GamevalEntry(2712, "TRAIL_CLUE_EASY_VAGUE005", "Clue scroll (easy)", "objtypes"),
            new GamevalEntry(2713, "TRAIL_CLUE_EASY_MAP001", "Clue scroll (easy)", "objtypes"),
            new GamevalEntry(2714, "TRAIL_CLUE_EASY_MAP001_CASKET", "Casket (easy)", "objtypes"),
            new GamevalEntry(2715, "CERT_TRAIL_CLUE_EASY_MAP001_CASKET", "Casket (easy)", "objtypes"),
            new GamevalEntry(2716, "TRAIL_CLUE_EASY_MAP002", "Clue scroll (easy)", "objtypes"),
            new GamevalEntry(2717, "TRAIL_CLUE_EASY_MAP002_CASKET", "Casket (easy)", "objtypes"),
            new GamevalEntry(2718, "CERT_TRAIL_CLUE_EASY_MAP002_CASKET", "Casket (easy)", "objtypes"),
            new GamevalEntry(2719, "TRAIL_CLUE_EASY_MAP003", "Clue scroll (easy)", "objtypes"),
            new GamevalEntry(2720, "TRAIL_CLUE_EASY_MAP003_CASKET", "Casket (easy)", "objtypes"),
            new GamevalEntry(2721, "CERT_TRAIL_CLUE_EASY_MAP003_CASKET", "Casket (easy)", "objtypes"),
            new GamevalEntry(2722, "TRAIL_CLUE_HARD_MAP001", "Clue scroll (hard)", "objtypes"),
            new GamevalEntry(2723, "TRAIL_CLUE_HARD_SEXTANT001", "Clue scroll (hard)", "objtypes"),
            new GamevalEntry(2724, "TRAIL_CLUE_HARD_SEXTANT001_CASKET", "Casket (hard)", "objtypes"),
            new GamevalEntry(2725, "TRAIL_CLUE_HARD_SEXTANT002", "Clue scroll (hard)", "objtypes"),
            new GamevalEntry(2726, "TRAIL_CLUE_HARD_SEXTANT002_CASKET", "Casket (hard)", "objtypes"),
            new GamevalEntry(2727, "TRAIL_CLUE_HARD_SEXTANT003", "Clue scroll (hard)", "objtypes"),
            new GamevalEntry(2728, "TRAIL_CLUE_HARD_SEXTANT003_CASKET", "Casket (hard)", "objtypes"),
            new GamevalEntry(2729, "TRAIL_CLUE_HARD_SEXTANT004", "Clue scroll (hard)", "objtypes"),
            new GamevalEntry(2730, "TRAIL_CLUE_HARD_SEXTANT004_CASKET", "Casket (hard)", "objtypes"),
            new GamevalEntry(2731, "TRAIL_CLUE_HARD_SEXTANT005", "Clue scroll (hard)", "objtypes"),
            new GamevalEntry(2732, "TRAIL_CLUE_HARD_SEXTANT005_CASKET", "Casket (hard)", "objtypes"),
            new GamevalEntry(2733, "TRAIL_CLUE_HARD_SEXTANT006", "Clue scroll (hard)", "objtypes"),
            new GamevalEntry(2734, "TRAIL_CLUE_HARD_SEXTANT006_CASKET", "Casket (hard)", "objtypes"),
            new GamevalEntry(2735, "TRAIL_CLUE_HARD_SEXTANT007", "Clue scroll (hard)", "objtypes"),
            new GamevalEntry(2736, "TRAIL_CLUE_HARD_SEXTANT007_CASKET", "Casket (hard)", "objtypes"),
            new GamevalEntry(2737, "TRAIL_CLUE_HARD_SEXTANT008", "Clue scroll (hard)", "objtypes"),
            new GamevalEntry(2738, "TRAIL_CLUE_HARD_SEXTANT008_CASKET", "Casket (hard)", "objtypes"),
            new GamevalEntry(2739, "TRAIL_CLUE_HARD_SEXTANT009", "Clue scroll (hard)", "objtypes"),
            new GamevalEntry(2740, "TRAIL_CLUE_HARD_SEXTANT009_CASKET", "Casket (hard)", "objtypes"),
            new GamevalEntry(2741, "TRAIL_CLUE_HARD_SEXTANT010", "Clue scroll (hard)", "objtypes"),
            new GamevalEntry(2742, "TRAIL_CLUE_HARD_SEXTANT010_CASKET", "Casket (hard)", "objtypes"),
            new GamevalEntry(2743, "TRAIL_CLUE_HARD_SEXTANT011", "Clue scroll (hard)", "objtypes"),
            new GamevalEntry(2744, "TRAIL_CLUE_HARD_SEXTANT011_CASKET", "Casket (hard)", "objtypes"),
            new GamevalEntry(2745, "TRAIL_CLUE_HARD_SEXTANT012", "Clue scroll (hard)", "objtypes"),
            new GamevalEntry(2746, "TRAIL_CLUE_HARD_SEXTANT012_CASKET", "Casket (hard)", "objtypes"),
            new GamevalEntry(2747, "TRAIL_CLUE_HARD_SEXTANT013", "Clue scroll (hard)", "objtypes"),
            new GamevalEntry(2748, "TRAIL_CLUE_HARD_SEXTANT013_CASKET", "Casket (hard)", "objtypes"),
            new GamevalEntry(2749, "TRAIL_SLIDINGPUZZLEB01", "trail_slidingpuzzleb01", "objtypes"),
            new GamevalEntry(2750, "TRAIL_SLIDINGPUZZLEB02", "trail_slidingpuzzleb02", "objtypes"),
            new GamevalEntry(2751, "TRAIL_SLIDINGPUZZLEB03", "trail_slidingpuzzleb03", "objtypes"),
            new GamevalEntry(2752, "TRAIL_SLIDINGPUZZLEB04", "trail_slidingpuzzleb04", "objtypes"),
            new GamevalEntry(2753, "TRAIL_SLIDINGPUZZLEB05", "trail_slidingpuzzleb05", "objtypes"),
            new GamevalEntry(2754, "TRAIL_SLIDINGPUZZLEB06", "trail_slidingpuzzleb06", "objtypes"),
            new GamevalEntry(2755, "TRAIL_SLIDINGPUZZLEB07", "trail_slidingpuzzleb07", "objtypes"),
            new GamevalEntry(2756, "TRAIL_SLIDINGPUZZLEB08", "trail_slidingpuzzleb08", "objtypes"),
            new GamevalEntry(2757, "TRAIL_SLIDINGPUZZLEB09", "trail_slidingpuzzleb09", "objtypes"),
            new GamevalEntry(2758, "TRAIL_SLIDINGPUZZLEB10", "trail_slidingpuzzleb10", "objtypes"),
            new GamevalEntry(2759, "TRAIL_SLIDINGPUZZLEB11", "trail_slidingpuzzleb11", "objtypes"),
            new GamevalEntry(2760, "TRAIL_SLIDINGPUZZLEB12", "trail_slidingpuzzleb12", "objtypes"),
            new GamevalEntry(2761, "TRAIL_SLIDINGPUZZLEB13", "trail_slidingpuzzleb13", "objtypes"),
            new GamevalEntry(2762, "TRAIL_SLIDINGPUZZLEB14", "trail_slidingpuzzleb14", "objtypes"),
            new GamevalEntry(2763, "TRAIL_SLIDINGPUZZLEB15", "trail_slidingpuzzleb15", "objtypes"),
            new GamevalEntry(2764, "TRAIL_SLIDINGPUZZLEB16", "trail_slidingpuzzleb16", "objtypes"),
            new GamevalEntry(2765, "TRAIL_SLIDINGPUZZLEB17", "trail_slidingpuzzleb17", "objtypes"),
            new GamevalEntry(2766, "TRAIL_SLIDINGPUZZLEB18", "trail_slidingpuzzleb18", "objtypes"),
            new GamevalEntry(2767, "TRAIL_SLIDINGPUZZLEB19", "trail_slidingpuzzleb19", "objtypes"),
            new GamevalEntry(2768, "TRAIL_SLIDINGPUZZLEB20", "trail_slidingpuzzleb20", "objtypes"),
            new GamevalEntry(2769, "TRAIL_SLIDINGPUZZLEB21", "trail_slidingpuzzleb21", "objtypes"),
            new GamevalEntry(2770, "TRAIL_SLIDINGPUZZLEB22", "trail_slidingpuzzleb22", "objtypes"),
            new GamevalEntry(2771, "TRAIL_SLIDINGPUZZLEB23", "trail_slidingpuzzleb23", "objtypes"),
            new GamevalEntry(2772, "TRAIL_SLIDINGPUZZLEB24", "trail_slidingpuzzleb24", "objtypes"),
            new GamevalEntry(2773, "TRAIL_CLUE_HARD_RIDDLE001", "Clue scroll (hard)", "objtypes"),
            new GamevalEntry(2774, "TRAIL_CLUE_HARD_RIDDLE002", "Clue scroll (hard)", "objtypes"),
            new GamevalEntry(2775, "TRAIL_CLUE_HARD_RIDDLE002_CASKET", "Casket (hard)", "objtypes"),
            new GamevalEntry(2776, "TRAIL_CLUE_HARD_RIDDLE003", "Clue scroll (hard)", "objtypes"),
            new GamevalEntry(2777, "TRAIL_CLUE_HARD_RIDDLE003_CASKET", "Casket (hard)", "objtypes"),
            new GamevalEntry(2778, "TRAIL_CLUE_HARD_RIDDLE004", "Clue scroll (hard)", "objtypes"),
            new GamevalEntry(2779, "TRAIL_CLUE_HARD_RIDDLE004_CASKET", "Casket (hard)", "objtypes"),
            new GamevalEntry(2780, "TRAIL_CLUE_HARD_RIDDLE005", "Clue scroll (hard)", "objtypes"),
            new GamevalEntry(2781, "TRAIL_CLUE_HARD_RIDDLE005_CASKET", "Casket (hard)", "objtypes"),
            new GamevalEntry(2782, "TRAIL_CLUE_HARD_RIDDLE006", "Clue scroll (hard)", "objtypes"),
            new GamevalEntry(2783, "TRAIL_CLUE_HARD_RIDDLE007", "Clue scroll (hard)", "objtypes"),
            new GamevalEntry(2784, "TRAIL_CLUE_HARD_RIDDLE007_CASKET", "Casket (hard)", "objtypes"),
            new GamevalEntry(2785, "TRAIL_CLUE_HARD_RIDDLE008", "Clue scroll (hard)", "objtypes"),
            new GamevalEntry(2786, "TRAIL_CLUE_HARD_RIDDLE009", "Clue scroll (hard)", "objtypes"),
            new GamevalEntry(2787, "TRAIL_CLUE_HARD_RIDDLE009_CASKET", "Casket (hard)", "objtypes"),
            new GamevalEntry(2788, "TRAIL_CLUE_HARD_RIDDLE010", "Clue scroll (hard)", "objtypes"),
            new GamevalEntry(2789, "TRAIL_CLUE_HARD_RIDDLE010_CASKET", "Casket (hard)", "objtypes"),
            new GamevalEntry(2790, "TRAIL_CLUE_HARD_RIDDLE011", "Clue scroll (hard)", "objtypes"),
            new GamevalEntry(2791, "TRAIL_CLUE_HARD_RIDDLE011_CASKET", "Casket (hard)", "objtypes"),
            new GamevalEntry(2792, "TRAIL_CLUE_HARD_RIDDLE012", "Clue scroll (hard)", "objtypes"),
            new GamevalEntry(2793, "TRAIL_CLUE_HARD_RIDDLE013", "Clue scroll (hard)", "objtypes"),
            new GamevalEntry(2794, "TRAIL_CLUE_HARD_RIDDLE014", "Clue scroll (hard)", "objtypes"),
            new GamevalEntry(2795, "TRAIL_CLUE_HARD_RIDDLE014_PUZZLEBOX", "Puzzle box (hard)", "objtypes"),
            new GamevalEntry(2796, "TRAIL_CLUE_HARD_RIDDLE015", "Clue scroll (hard)", "objtypes"),
            new GamevalEntry(2797, "TRAIL_CLUE_HARD_RIDDLE016", "Clue scroll (hard)", "objtypes"),
            new GamevalEntry(2798, "TRAIL_CLUE_HARD_RIDDLE016_PUZZLEBOX", "Puzzle box (hard)", "objtypes"),
            new GamevalEntry(2799, "TRAIL_CLUE_HARD_RIDDLE017", "Clue scroll (hard)", "objtypes"),
            new GamevalEntry(2800, "TRAIL_CLUE_HARD_RIDDLE017_PUZZLEBOX", "Puzzle box (hard)", "objtypes"),
            new GamevalEntry(2801, "TRAIL_CLUE_MEDIUM_SEXTANT001", "Clue scroll (medium)", "objtypes"),
            new GamevalEntry(2802, "TRAIL_CLUE_MEDIUM_SEXTANT001_CASKET", "Casket (medium)", "objtypes"),
            new GamevalEntry(2803, "TRAIL_CLUE_MEDIUM_SEXTANT002", "Clue scroll (medium)", "objtypes"),
            new GamevalEntry(2804, "TRAIL_CLUE_MEDIUM_SEXTANT002_CASKET", "Casket (medium)", "objtypes"),
            new GamevalEntry(2805, "TRAIL_CLUE_MEDIUM_SEXTANT003", "Clue scroll (medium)", "objtypes"),
            new GamevalEntry(2806, "TRAIL_CLUE_MEDIUM_SEXTANT003_CASKET", "Casket (medium)", "objtypes"),
            new GamevalEntry(2807, "TRAIL_CLUE_MEDIUM_SEXTANT004", "Clue scroll (medium)", "objtypes"),
            new GamevalEntry(2808, "TRAIL_CLUE_MEDIUM_SEXTANT004_CASKET", "Casket (medium)", "objtypes"),
            new GamevalEntry(2809, "TRAIL_CLUE_MEDIUM_SEXTANT005", "Clue scroll (medium)", "objtypes"),
            new GamevalEntry(2810, "TRAIL_CLUE_MEDIUM_SEXTANT005_CASKET", "Casket (medium)", "objtypes"),
            new GamevalEntry(2811, "TRAIL_CLUE_MEDIUM_SEXTANT006", "Clue scroll (medium)", "objtypes"),
            new GamevalEntry(2812, "TRAIL_CLUE_MEDIUM_SEXTANT006_CASKET", "Casket (medium)", "objtypes"),
            new GamevalEntry(2813, "TRAIL_CLUE_MEDIUM_SEXTANT007", "Clue scroll (medium)", "objtypes"),
            new GamevalEntry(2814, "TRAIL_CLUE_MEDIUM_SEXTANT007_CASKET", "Casket (medium)", "objtypes"),
            new GamevalEntry(2815, "TRAIL_CLUE_MEDIUM_SEXTANT008", "Clue scroll (medium)", "objtypes"),
            new GamevalEntry(2816, "TRAIL_CLUE_MEDIUM_SEXTANT008_CASKET", "Casket (medium)", "objtypes"),
            new GamevalEntry(2817, "TRAIL_CLUE_MEDIUM_SEXTANT009", "Clue scroll (medium)", "objtypes"),
            new GamevalEntry(2818, "TRAIL_CLUE_MEDIUM_SEXTANT009_CASKET", "Casket (medium)", "objtypes"),
            new GamevalEntry(2819, "TRAIL_CLUE_MEDIUM_SEXTANT010", "Clue scroll (medium)", "objtypes"),
            new GamevalEntry(2820, "TRAIL_CLUE_MEDIUM_SEXTANT010_CASKET", "Casket (medium)", "objtypes"),
            new GamevalEntry(2821, "TRAIL_CLUE_MEDIUM_SEXTANT011", "Clue scroll (medium)", "objtypes"),
            new GamevalEntry(2822, "TRAIL_CLUE_MEDIUM_SEXTANT011_CASKET", "Casket (medium)", "objtypes"),
            new GamevalEntry(2823, "TRAIL_CLUE_MEDIUM_SEXTANT012", "Clue scroll (medium)", "objtypes"),
            new GamevalEntry(2824, "TRAIL_CLUE_MEDIUM_SEXTANT012_CASKET", "Casket (medium)", "objtypes"),
            new GamevalEntry(2825, "TRAIL_CLUE_MEDIUM_SEXTANT013", "Clue scroll (medium)", "objtypes"),
            new GamevalEntry(2826, "TRAIL_CLUE_MEDIUM_SEXTANT013_CASKET", "Casket (medium)", "objtypes"),
            new GamevalEntry(2827, "TRAIL_CLUE_MEDIUM_MAP001", "Clue scroll (medium)", "objtypes"),
            new GamevalEntry(2828, "TRAIL_CLUE_MEDIUM_MAP001_CASKET", "Casket (medium)", "objtypes"),
            new GamevalEntry(2829, "TRAIL_CLUE_MEDIUM_MAP002", "Clue scroll (medium)", "objtypes"),
            new GamevalEntry(2830, "TRAIL_CLUE_MEDIUM_MAP002_CASKET", "Casket (medium)", "objtypes"),
            new GamevalEntry(2831, "TRAIL_CLUE_MEDIUM_RIDDLE001", "Clue scroll (medium)", "objtypes"),
            new GamevalEntry(2832, "TRAIL_CLUE_MEDIUM_RIDDLE001_KEY", "Key (medium)", "objtypes"),
            new GamevalEntry(2833, "TRAIL_CLUE_MEDIUM_RIDDLE002", "Clue scroll (medium)", "objtypes"),
            new GamevalEntry(2834, "TRAIL_CLUE_MEDIUM_RIDDLE002_KEY", "Key (medium)", "objtypes"),
            new GamevalEntry(2835, "TRAIL_CLUE_MEDIUM_RIDDLE003", "Clue scroll (medium)", "objtypes"),
            new GamevalEntry(2836, "TRAIL_CLUE_MEDIUM_RIDDLE003_KEY", "Key (medium)", "objtypes"),
            new GamevalEntry(2837, "TRAIL_CLUE_MEDIUM_RIDDLE004", "Clue scroll (medium)", "objtypes"),
            new GamevalEntry(2838, "TRAIL_CLUE_MEDIUM_RIDDLE004_KEY", "Key (medium)", "objtypes"),
            new GamevalEntry(2839, "TRAIL_CLUE_MEDIUM_RIDDLE005", "Clue scroll (medium)", "objtypes"),
            new GamevalEntry(2840, "TRAIL_CLUE_MEDIUM_RIDDLE005_KEY", "Key (medium)", "objtypes"),
            new GamevalEntry(2841, "TRAIL_CLUE_MEDIUM_ANAGRAM001", "Clue scroll (medium)", "objtypes"),
            new GamevalEntry(2842, "TRAIL_CLUE_MEDIUM_ANAGRAM001_CHALLENGE", "Challenge scroll (medium)", "objtypes"),
            new GamevalEntry(2843, "TRAIL_CLUE_MEDIUM_ANAGRAM002", "Clue scroll (medium)", "objtypes"),
            new GamevalEntry(2844, "TRAIL_CLUE_MEDIUM_ANAGRAM002_CHALLENGE", "Challenge scroll (medium)", "objtypes"),
            new GamevalEntry(2845, "TRAIL_CLUE_MEDIUM_ANAGRAM003", "Clue scroll (medium)", "objtypes"),
            new GamevalEntry(2846, "TRAIL_CLUE_MEDIUM_ANAGRAM003_CHALLENGE", "Challenge scroll (medium)", "objtypes"),
            new GamevalEntry(2847, "TRAIL_CLUE_MEDIUM_ANAGRAM004", "Clue scroll (medium)", "objtypes"),
            new GamevalEntry(2848, "TRAIL_CLUE_MEDIUM_ANAGRAM005", "Clue scroll (medium)", "objtypes"),
            new GamevalEntry(2849, "TRAIL_CLUE_MEDIUM_ANAGRAM006", "Clue scroll (medium)", "objtypes"),
            new GamevalEntry(2850, "TRAIL_CLUE_MEDIUM_ANAGRAM006_CHALLENGE", "Challenge scroll (medium)", "objtypes"),
            new GamevalEntry(2851, "TRAIL_CLUE_MEDIUM_ANAGRAM007", "Clue scroll (medium)", "objtypes"),
            new GamevalEntry(2852, "TRAIL_CLUE_MEDIUM_ANAGRAM007_CHALLENGE", "Challenge scroll (medium)", "objtypes"),
            new GamevalEntry(2853, "TRAIL_CLUE_MEDIUM_ANAGRAM008", "Clue scroll (medium)", "objtypes"),
            new GamevalEntry(2854, "TRAIL_CLUE_MEDIUM_ANAGRAM008_CHALLENGE", "Challenge scroll (medium)", "objtypes"),
            new GamevalEntry(2855, "TRAIL_CLUE_MEDIUM_ANAGRAM009", "Clue scroll (medium)", "objtypes"),
            new GamevalEntry(2856, "TRAIL_CLUE_MEDIUM_ANAGRAM010", "Clue scroll (medium)", "objtypes"),
            new GamevalEntry(2857, "TRAIL_CLUE_MEDIUM_ANAGRAM011", "Clue scroll (medium)", "objtypes"),
            new GamevalEntry(2858, "TRAIL_CLUE_MEDIUM_ANAGRAM012", "Clue scroll (medium)", "objtypes"),
            new GamevalEntry(2859, "WOLF_BONES", "Wolf bones", "objtypes"),
            new GamevalEntry(2860, "CERT_WOLF_BONES", "cert_wolf_bones", "objtypes"),
            new GamevalEntry(2861, "WOLFBONE_ARROWHEADS", "Wolfbone arrowtips", "objtypes"),
            new GamevalEntry(2862, "ACHEY_TREE_LOGS", "Achey tree logs", "objtypes"),
            new GamevalEntry(2863, "CERT_ACHEY_TREE_LOGS", "cert_achey_tree_logs", "objtypes"),
            new GamevalEntry(2864, "OGRE_ARROW_SHAFT", "Ogre arrow shaft", "objtypes"),
            new GamevalEntry(2865, "OGRE_HEADLESS_ARROW", "Flighted ogre arrow", "objtypes"),
            new GamevalEntry(2866, "OGRE_ARROW", "Ogre arrow", "objtypes"),
            new GamevalEntry(2867, "OGRE_ARROW_5", "ogre_arrow_5", "objtypes"),
            new GamevalEntry(2868, "OGRE_ARROW_4", "ogre_arrow_4", "objtypes"),
            new GamevalEntry(2869, "OGRE_ARROW_3", "ogre_arrow_3", "objtypes"),
            new GamevalEntry(2870, "OGRE_ARROW_2", "ogre_arrow_2", "objtypes"),
            new GamevalEntry(2871, "EMPTY_OGRE_BELLOWS", "Ogre bellows", "objtypes"),
            new GamevalEntry(2872, "FILLED_OGRE_BELLOW3", "Ogre bellows (3)", "objtypes"),
            new GamevalEntry(2873, "FILLED_OGRE_BELLOW2", "Ogre bellows (2)", "objtypes"),
            new GamevalEntry(2874, "FILLED_OGRE_BELLOW1", "Ogre bellows (1)", "objtypes"),
            new GamevalEntry(2875, "BLOATED_TOAD", "Bloated toad", "objtypes"),
            new GamevalEntry(2876, "RAW_CHOMPY", "Raw chompy", "objtypes"),
            new GamevalEntry(2877, "CERT_RAW_CHOMPY", "cert_raw_chompy", "objtypes"),
            new GamevalEntry(2878, "COOKED_CHOMPY", "Cooked chompy", "objtypes"),
            new GamevalEntry(2879, "CERT_COOKED_CHOMPY", "cert_cooked_chompy", "objtypes"),
            new GamevalEntry(2880, "RUINED_CHOMPY", "Ruined chompy", "objtypes"),
            new GamevalEntry(2881, "CERT_RUINED_CHOMPY", "cert_ruined_chompy", "objtypes"),
            new GamevalEntry(2882, "COOKED_S_CHOMPY", "Seasoned chompy", "objtypes"),
            new GamevalEntry(2883, "OGRE_BOW", "Ogre bow", "objtypes"),
            new GamevalEntry(2884, "CHOMPY_BIRD_OBJ", "chompy_bird_obj", "objtypes"),
            new GamevalEntry(2885, "CERT_CHOMPY_BIRD_OBJ", "ZReanimates a medium levelled creature", "objtypes"),
            new GamevalEntry(2886, "ELEMENTAL_WORKSHOP_SHIELD_BOOK", "Battered book", "objtypes"),
            new GamevalEntry(2887, "ELEMENTAL_WORKSHOP_KEY", "Battered key", "objtypes"),
            new GamevalEntry(2888, "ELEMENTAL_WORKSHOP_LAVA_BOWL", "A stone bowl", "objtypes"),
            new GamevalEntry(2889, "ELEMENTAL_WORKSHOP_LAVA_BOWL_FULL", "A stone bowl", "objtypes"),
            new GamevalEntry(2890, "ELEMENTAL_SHIELD", "Elemental shield", "objtypes"),
            new GamevalEntry(2891, "CERT_ELEMENTAL_SHIELD", "cert_elemental_shield", "objtypes"),
            new GamevalEntry(2892, "ELEMENTAL_WORKSHOP_ORE", "Elemental ore", "objtypes"),
            new GamevalEntry(2893, "ELEMENTAL_WORKSHOP_BAR", "Elemental metal", "objtypes"),
            new GamevalEntry(2894, "WOLFENBOOTS_GREY", "Grey boots", "objtypes"),
            new GamevalEntry(2895, "CERT_WOLFENBOOTS_GREY", "cert_wolfenboots_grey", "objtypes"),
            new GamevalEntry(2896, "WOLFENROBETOP_GREY", "Grey robe top", "objtypes"),
            new GamevalEntry(2897, "CERT_WOLFENROBETOP_GREY", "cert_wolfenrobetop_grey", "objtypes"),
            new GamevalEntry(2898, "WOLFENROBEBOTTOM_GREY", "Grey robe bottoms", "objtypes"),
            new GamevalEntry(2899, "CERT_WOLFENROBEBOTTOM_GREY", "cert_wolfenrobebottom_grey", "objtypes"),
            new GamevalEntry(2900, "WOLFENHAT_GREY", "Grey hat", "objtypes"),
            new GamevalEntry(2901, "CERT_WOLFENHAT_GREY", "cert_wolfenhat_grey", "objtypes"),
            new GamevalEntry(2902, "WOLFENGLOVES_GREY", "Grey gloves", "objtypes"),
            new GamevalEntry(2903, "CERT_WOLFENGLOVES_GREY", "cert_wolfengloves_grey", "objtypes"),
            new GamevalEntry(2904, "WOLFENBOOTS_CRIMSON", "Red boots", "objtypes"),
            new GamevalEntry(2905, "CERT_WOLFENBOOTS_CRIMSON", "cert_wolfenboots_crimson", "objtypes"),
            new GamevalEntry(2906, "WOLFENROBETOP_CRIMSON", "Red robe top", "objtypes"),
            new GamevalEntry(2907, "CERT_WOLFENROBETOP_CRIMSON", "cert_wolfenrobetop_crimson", "objtypes"),
            new GamevalEntry(2908, "WOLFENROBEBOTTOM_CRIMSON", "Red robe bottoms", "objtypes"),
            new GamevalEntry(2909, "CERT_WOLFENROBEBOTTOM_CRIMSON", "cert_wolfenrobebottom_crimson", "objtypes"),
            new GamevalEntry(2910, "WOLFENHAT_CRIMSON", "Red hat", "objtypes"),
            new GamevalEntry(2911, "CERT_WOLFENHAT_CRIMSON", "cert_wolfenhat_crimson", "objtypes"),
            new GamevalEntry(2912, "WOLFENGLOVES_CRIMSON", "Red gloves", "objtypes"),
            new GamevalEntry(2913, "CERT_WOLFENGLOVES_CRIMSON", "cert_wolfengloves_crimson", "objtypes"),
            new GamevalEntry(2914, "WOLFENBOOTS_TANGERINE", "Yellow boots", "objtypes"),
            new GamevalEntry(2915, "CERT_WOLFENBOOTS_TANGERINE", "cert_wolfenboots_tangerine", "objtypes"),
            new GamevalEntry(2916, "WOLFENROBETOP_TANGERINE", "Yellow robe top", "objtypes"),
            new GamevalEntry(2917, "CERT_WOLFENROBETOP_TANGERINE", "cert_wolfenrobetop_tangerine", "objtypes"),
            new GamevalEntry(2918, "WOLFENROBEBOTTOM_TANGERINE", "Yellow robe bottoms", "objtypes"),
            new GamevalEntry(2919, "CERT_WOLFENROBEBOTTOM_TANGERINE", "cert_wolfenrobebottom_tangerine", "objtypes"),
            new GamevalEntry(2920, "WOLFENHAT_TANGERINE", "Yellow hat", "objtypes"),
            new GamevalEntry(2921, "CERT_WOLFENHAT_TANGERINE", "cert_wolfenhat_tangerine", "objtypes"),
            new GamevalEntry(2922, "WOLFENGLOVES_TANGERINE", "Yellow gloves", "objtypes"),
            new GamevalEntry(2923, "CERT_WOLFENGLOVES_TANGERINE", "cert_wolfengloves_tangerine", "objtypes"),
            new GamevalEntry(2924, "WOLFENBOOTS_OCEAN", "Teal boots", "objtypes"),
            new GamevalEntry(2925, "CERT_WOLFENBOOTS_OCEAN", "cert_wolfenboots_ocean", "objtypes"),
            new GamevalEntry(2926, "WOLFENROBETOP_OCEAN", "Teal robe top", "objtypes"),
            new GamevalEntry(2927, "CERT_WOLFENROBETOP_OCEAN", "cert_wolfenrobetop_ocean", "objtypes"),
            new GamevalEntry(2928, "WOLFENROBEBOTTOM_OCEAN", "Teal robe bottoms", "objtypes"),
            new GamevalEntry(2929, "CERT_WOLFENROBEBOTTOM_OCEAN", "cert_wolfenrobebottom_ocean", "objtypes"),
            new GamevalEntry(2930, "WOLFENHAT_OCEAN", "Teal hat", "objtypes"),
            new GamevalEntry(2931, "CERT_WOLFENHAT_OCEAN", "cert_wolfenhat_ocean", "objtypes"),
            new GamevalEntry(2932, "WOLFENGLOVES_OCEAN", "Teal gloves", "objtypes"),
            new GamevalEntry(2933, "CERT_WOLFENGLOVES_OCEAN", "cert_wolfengloves_ocean", "objtypes"),
            new GamevalEntry(2934, "WOLFENBOOTS_PURPLE", "Purple boots", "objtypes"),
            new GamevalEntry(2935, "CERT_WOLFENBOOTS_PURPLE", "cert_wolfenboots_purple", "objtypes"),
            new GamevalEntry(2936, "WOLFENROBETOP_PURPLE", "Purple robe top", "objtypes"),
            new GamevalEntry(2937, "CERT_WOLFENROBETOP_PURPLE", "cert_wolfenrobetop_purple", "objtypes"),
            new GamevalEntry(2938, "WOLFENROBEBOTTOM_PURPLE", "Purple robe bottoms", "objtypes"),
            new GamevalEntry(2939, "CERT_WOLFENROBEBOTTOM_PURPLE", "cert_wolfenrobebottom_purple", "objtypes"),
            new GamevalEntry(2940, "WOLFENHAT_PURPLE", "Purple hat", "objtypes"),
            new GamevalEntry(2941, "CERT_WOLFENHAT_PURPLE", "cert_wolfenhat_purple", "objtypes"),
            new GamevalEntry(2942, "WOLFENGLOVES_PURPLE", "Purple gloves", "objtypes"),
            new GamevalEntry(2943, "CERT_WOLFENGLOVES_PURPLE", "cert_wolfengloves_purple", "objtypes"),
            new GamevalEntry(2944, "PIPKEY_GOLD", "Golden key", "objtypes"),
            new GamevalEntry(2945, "PIPKEY_IRON", "Iron key", "objtypes"),
            new GamevalEntry(2946, "PIPTINDERBOX_GOLD", "Golden tinderbox", "objtypes"),
            new GamevalEntry(2947, "PIPCANDLE_GOLD", "Golden candle", "objtypes"),
            new GamevalEntry(2948, "PIPPOT_GOLD", "Golden pot", "objtypes"),
            new GamevalEntry(2949, "PIPHAMMER_GOLD", "Golden hammer", "objtypes"),
            new GamevalEntry(2950, "PIPFEATHER_GOLD", "Golden feather", "objtypes"),
            new GamevalEntry(2951, "PIPNEEDLE_GOLD", "Golden needle", "objtypes"),
            new GamevalEntry(2952, "DAGGER_WOLFBANE", "Wolfbane", "objtypes"),
            new GamevalEntry(2953, "BUCKET_MURKYWATER", "Murky water", "objtypes"),
            new GamevalEntry(2954, "BUCKET_BLESSEDWATER", "Blessed water", "objtypes"),
            new GamevalEntry(2955, "MOONLIGHT_MEAD", "& A( ?(T ?(X Moonlight mead", "objtypes"),
            new GamevalEntry(2956, "CERT_MOONLIGHT_MEAD", "cert_moonlight_mead", "objtypes"),
            new GamevalEntry(2957, "DRUID_POUCH_EMPTY", "Druid pouch", "objtypes"),
            new GamevalEntry(2958, "DRUID_POUCH", "Druid pouch", "objtypes"),
            new GamevalEntry(2959, "ROTTEN_FOOD", "Rotten food", "objtypes"),
            new GamevalEntry(2960, "CERT_ROTTEN_FOOD", "cert_rotten_food", "objtypes"),
            new GamevalEntry(2961, "SILVER_SICKLE", "Silver sickle", "objtypes"),
            new GamevalEntry(2962, "CERT_SILVER_SICKLE", "cert_silver_sickle", "objtypes"),
            new GamevalEntry(2963, "SILVER_SICKLE_BLESSED", "Silver sickle (b)", "objtypes"),
            new GamevalEntry(2964, "BOWL_EMPTY_FILLIMAN", "Washing bowl", "objtypes"),
            new GamevalEntry(2965, "CERT_BOWL_EMPTY_FILLIMAN", "cert_bowl_empty_filliman", "objtypes"),
            new GamevalEntry(2966, "MIRROR", "Mirror", "objtypes"),
            new GamevalEntry(2967, "FILLIMAN_JOURNAL", "Journal", "objtypes"),
            new GamevalEntry(2968, "BLOOM_SPELL", "Druidic spell", "objtypes"),
            new GamevalEntry(2969, "USED_BLOOM_SPELL", "A used spell", "objtypes"),
            new GamevalEntry(2970, "MORTMYREMUSHROOM", "Mort myre fungus", "objtypes"),
            new GamevalEntry(2971, "CERT_MORTMYREMUSHROOM", "cert_mortmyremushroom", "objtypes"),
            new GamevalEntry(2972, "MORTMYREBUDDINGSTEM", "Mort myre stem", "objtypes"),
            new GamevalEntry(2973, "CERT_MORTMYREBUDDINGSTEM", "cert_mortmyrebuddingstem", "objtypes"),
            new GamevalEntry(2974, "MORTMYREPEAR", "Mort myre pear", "objtypes"),
            new GamevalEntry(2975, "CERT_MORTMYREPEAR", "cert_mortmyrepear", "objtypes"),
            new GamevalEntry(2976, "SICKLE_MOULD", "Sickle mould", "objtypes"),
            new GamevalEntry(2977, "CERT_SICKLE_MOULD", "cert_sickle_mould", "objtypes"),
            new GamevalEntry(2978, "CBHAT1", "Chompy bird hat", "objtypes"),
            new GamevalEntry(2979, "CBHAT2", "Chompy bird hat", "objtypes"),
            new GamevalEntry(2980, "CBHAT3", "Chompy bird hat", "objtypes"),
            new GamevalEntry(2981, "CBHAT4", "Chompy bird hat", "objtypes"),
            new GamevalEntry(2982, "CBHAT5", "Chompy bird hat", "objtypes"),
            new GamevalEntry(2983, "CBHAT6", "Chompy bird hat", "objtypes"),
            new GamevalEntry(2984, "CBHAT7", "Chompy bird hat", "objtypes"),
            new GamevalEntry(2985, "CBHAT8", "Chompy bird hat", "objtypes"),
            new GamevalEntry(2986, "CBHAT9", "Chompy bird hat", "objtypes"),
            new GamevalEntry(2987, "CBHAT10", "Chompy bird hat", "objtypes"),
            new GamevalEntry(2988, "CBHAT11", "Chompy bird hat", "objtypes"),
            new GamevalEntry(2989, "CBHAT12", "Chompy bird hat", "objtypes"),
            new GamevalEntry(2990, "CBHAT13", "Chompy bird hat", "objtypes"),
            new GamevalEntry(2991, "CBHAT14", "Chompy bird hat", "objtypes"),
            new GamevalEntry(2992, "CBHAT15", "Chompy bird hat", "objtypes"),
            new GamevalEntry(2993, "CBHAT16", "Chompy bird hat", "objtypes"),
            new GamevalEntry(2994, "CBHAT17", "Chompy bird hat", "objtypes"),
            new GamevalEntry(2995, "CBHAT18", "Chompy bird hat", "objtypes"),
            new GamevalEntry(2996, "AGILITYARENA_TICKET", "Agility arena ticket", "objtypes"),
            new GamevalEntry(2997, "PIRATEHOOK", "Pirate's hook", "objtypes"),
            new GamevalEntry(2998, "TOADFLAX", "Toadflax", "objtypes"),
            new GamevalEntry(2999, "CERT_TOADFLAX", "cert_toadflax", "objtypes"),
            new GamevalEntry(3000, "SNAPDRAGON", "Snapdragon", "objtypes"),
            new GamevalEntry(3001, "CERT_SNAPDRAGON", "cert_snapdragon", "objtypes"),
            new GamevalEntry(3002, "TOADFLAXVIAL", "Toadflax potion (unf)", "objtypes"),
            new GamevalEntry(3003, "CERT_TOADFLAXVIAL", "cert_toadflaxvial", "objtypes"),
            new GamevalEntry(3004, "SNAPDRAGONVIAL", "Snapdragon potion (unf)", "objtypes"),
            new GamevalEntry(3005, "CERT_SNAPDRAGONVIAL", "cert_snapdragonvial", "objtypes"),
            new GamevalEntry(3006, "FIREWORK", "Firework", "objtypes"),
            new GamevalEntry(3007, "CERT_FIREWORK", "cert_firework", "objtypes"),
            new GamevalEntry(3008, "_4DOSE1ENERGY", "Energy potion(4)", "objtypes"),
            new GamevalEntry(3009, "CERT_4DOSE1ENERGY", "cert_4dose1energy", "objtypes"),
            new GamevalEntry(3010, "_3DOSE1ENERGY", "Energy potion(3)", "objtypes"),
            new GamevalEntry(3011, "CERT_3DOSE1ENERGY", "cert_3dose1energy", "objtypes"),
            new GamevalEntry(3012, "_2DOSE1ENERGY", "Energy potion(2)", "objtypes"),
            new GamevalEntry(3013, "CERT_2DOSE1ENERGY", "cert_2dose1energy", "objtypes"),
            new GamevalEntry(3014, "_1DOSE1ENERGY", "Energy potion(1)", "objtypes"),
            new GamevalEntry(3015, "CERT_1DOSE1ENERGY", "cert_1dose1energy", "objtypes"),
            new GamevalEntry(3016, "_4DOSE2ENERGY", "Super energy(4)", "objtypes"),
            new GamevalEntry(3017, "CERT_4DOSE2ENERGY", "cert_4dose2energy", "objtypes"),
            new GamevalEntry(3018, "_3DOSE2ENERGY", "Super energy(3)", "objtypes"),
            new GamevalEntry(3019, "CERT_3DOSE2ENERGY", "cert_3dose2energy", "objtypes"),
            new GamevalEntry(3020, "_2DOSE2ENERGY", "Super energy(2)", "objtypes"),
            new GamevalEntry(3021, "CERT_2DOSE2ENERGY", "cert_2dose2energy", "objtypes"),
            new GamevalEntry(3022, "_1DOSE2ENERGY", "Super energy(1)", "objtypes"),
            new GamevalEntry(3023, "CERT_1DOSE2ENERGY", "cert_1dose2energy", "objtypes"),
            new GamevalEntry(3024, "_4DOSE2RESTORE", "Super restore(4)", "objtypes"),
            new GamevalEntry(3025, "CERT_4DOSE2RESTORE", "cert_4dose2restore", "objtypes"),
            new GamevalEntry(3026, "_3DOSE2RESTORE", "Super restore(3)", "objtypes"),
            new GamevalEntry(3027, "CERT_3DOSE2RESTORE", "cert_3dose2restore", "objtypes"),
            new GamevalEntry(3028, "_2DOSE2RESTORE", "Super restore(2)", "objtypes"),
            new GamevalEntry(3029, "CERT_2DOSE2RESTORE", "cert_2dose2restore", "objtypes"),
            new GamevalEntry(3030, "_1DOSE2RESTORE", "Super restore(1)", "objtypes"),
            new GamevalEntry(3031, "CERT_1DOSE2RESTORE", "cert_1dose2restore", "objtypes"),
            new GamevalEntry(3032, "_4DOSE1AGILITY", "Agility potion(4)", "objtypes"),
            new GamevalEntry(3033, "CERT_4DOSE1AGILITY", "cert_4dose1agility", "objtypes"),
            new GamevalEntry(3034, "_3DOSE1AGILITY", "Agility potion(3)", "objtypes"),
            new GamevalEntry(3035, "CERT_3DOSE1AGILITY", "cert_3dose1agility", "objtypes"),
            new GamevalEntry(3036, "_2DOSE1AGILITY", "Agility potion(2)", "objtypes"),
            new GamevalEntry(3037, "CERT_2DOSE1AGILITY", "cert_2dose1agility", "objtypes"),
            new GamevalEntry(3038, "_1DOSE1AGILITY", "Agility potion(1)", "objtypes"),
            new GamevalEntry(3039, "CERT_1DOSE1AGILITY", "cert_1dose1agility", "objtypes"),
            new GamevalEntry(3040, "_4DOSE1MAGIC", "Magic potion(4)", "objtypes"),
            new GamevalEntry(3041, "CERT_4DOSE1MAGIC", "cert_4dose1magic", "objtypes"),
            new GamevalEntry(3042, "_3DOSE1MAGIC", "Magic potion(3)", "objtypes"),
            new GamevalEntry(3043, "CERT_3DOSE1MAGIC", "cert_3dose1magic", "objtypes"),
            new GamevalEntry(3044, "_2DOSE1MAGIC", "Magic potion(2)", "objtypes"),
            new GamevalEntry(3045, "CERT_2DOSE1MAGIC", "cert_2dose1magic", "objtypes"),
            new GamevalEntry(3046, "_1DOSE1MAGIC", "Magic potion(1)", "objtypes"),
            new GamevalEntry(3047, "CERT_1DOSE1MAGIC", "cert_1dose1magic", "objtypes"),
            new GamevalEntry(3048, "CERT_PIRATEHOOK", "cert_piratehook", "objtypes"),
            new GamevalEntry(3049, "UNIDENTIFIED_TOADFLAX", "Grimy toadflax", "objtypes"),
            new GamevalEntry(3050, "CERT_UNIDENTIFIED_TOADFLAX", "cert_unidentified_toadflax", "objtypes"),
            new GamevalEntry(3051, "UNIDENTIFIED_SNAPDRAGON", "Grimy snapdragon", "objtypes"),
            new GamevalEntry(3052, "CERT_UNIDENTIFIED_SNAPDRAGON", "cert_unidentified_snapdragon", "objtypes"),
            new GamevalEntry(3053, "LAVA_BATTLESTAFF", "Lava battlestaff", "objtypes"),
            new GamevalEntry(3054, "MYSTIC_LAVA_STAFF", "Mystic lava staff", "objtypes"),
            new GamevalEntry(3055, "CERT_LAVA_BATTLESTAFF", "cert_lava_battlestaff", "objtypes"),
            new GamevalEntry(3056, "CERT_MYSTIC_LAVA_STAFF", "cert_mystic_lava_staff", "objtypes"),
            new GamevalEntry(3057, "MACRO_MIME_MASK", "Mime mask", "objtypes"),
            new GamevalEntry(3058, "MACRO_MIME_TOP", "Mime top", "objtypes"),
            new GamevalEntry(3059, "MACRO_MIME_LEGS", "Mime legs", "objtypes"),
            new GamevalEntry(3060, "MACRO_MIME_GLOVES", "Mime gloves", "objtypes"),
            new GamevalEntry(3061, "MACRO_MIME_BOOTS", "Mime boots", "objtypes"),
            new GamevalEntry(3062, "MACRO_CUBE", "Strange box", "objtypes"),
            new GamevalEntry(3063, "MACRO_CUBE_REDTRIANGLE", "macro_cube_redtriangle", "objtypes"),
            new GamevalEntry(3064, "CERT_MACRO_CUBE_REDTRIANGLE", "cert_macro_cube_redtriangle", "objtypes"),
            new GamevalEntry(3065, "MACRO_CUBE_BLUETRIANGLE", "macro_cube_bluetriangle", "objtypes"),
            new GamevalEntry(3066, "CERT_MACRO_CUBE_BLUETRIANGLE", "cert_macro_cube_bluetriangle", "objtypes"),
            new GamevalEntry(3067, "MACRO_CUBE_YELLOWTRIANGLE", "macro_cube_yellowtriangle", "objtypes"),
            new GamevalEntry(3068, "CERT_MACRO_CUBE_YELLOWTRIANGLE", "cert_macro_cube_yellowtriangle", "objtypes"),
            new GamevalEntry(3069, "MACRO_CUBE_REDSQUARE", "macro_cube_redsquare", "objtypes"),
            new GamevalEntry(3070, "CERT_MACRO_CUBE_REDSQUARE", "cert_macro_cube_redsquare", "objtypes"),
            new GamevalEntry(3071, "MACRO_CUBE_BLUESQUARE", "macro_cube_bluesquare", "objtypes"),
            new GamevalEntry(3072, "CERT_MACRO_CUBE_BLUESQUARE", "cert_macro_cube_bluesquare", "objtypes"),
            new GamevalEntry(3073, "MACRO_CUBE_YELLOWSQUARE", "macro_cube_yellowsquare", "objtypes"),
            new GamevalEntry(3074, "CERT_MACRO_CUBE_YELLOWSQUARE", "cert_macro_cube_yellowsquare", "objtypes"),
            new GamevalEntry(3075, "MACRO_CUBE_REDCIRCLE", "macro_cube_redcircle", "objtypes"),
            new GamevalEntry(3076, "CERT_MACRO_CUBE_REDCIRCLE", "cert_macro_cube_redcircle", "objtypes"),
            new GamevalEntry(3077, "MACRO_CUBE_BLUECIRCLE", "macro_cube_bluecircle", "objtypes"),
        };
    }

    static Optional<GamevalEntry> byId(int id) {
        for (GamevalEntry entry : entries()) {
            if (entry.id() == id) return Optional.of(entry);
        }
        return Optional.empty();
    }

}
