package net.titan.gamevals.internal;

import java.util.Optional;

import net.titan.gamevals.GamevalEntry;
import net.titan.gamevals.QuestEntry;

final class ItemIDEntries_7 {
    private ItemIDEntries_7() {}

    static GamevalEntry[] entries() {
        return new GamevalEntry[] {
            new GamevalEntry(3598, "TRAIL_CLUE_MEDIUM_MAP004", "Clue scroll (medium)", "objtypes"),
            new GamevalEntry(3599, "TRAIL_CLUE_MEDIUM_MAP005", "Clue scroll (medium)", "objtypes"),
            new GamevalEntry(3600, "TRAIL_CLUE_MEDIUM_MAP005_CASKET", "Casket (medium)", "objtypes"),
            new GamevalEntry(3601, "TRAIL_CLUE_MEDIUM_MAP006", "Clue scroll (medium)", "objtypes"),
            new GamevalEntry(3602, "TRAIL_CLUE_MEDIUM_MAP007", "Clue scroll (medium)", "objtypes"),
            new GamevalEntry(3603, "TRAIL_CLUE_MEDIUM_MAP007_CASKET", "Casket (medium)", "objtypes"),
            new GamevalEntry(3604, "TRAIL_CLUE_MEDIUM_RIDDLE006", "Clue scroll (medium)", "objtypes"),
            new GamevalEntry(3605, "TRAIL_CLUE_MEDIUM_RIDDLE007", "Clue scroll (medium)", "objtypes"),
            new GamevalEntry(3606, "TRAIL_CLUE_MEDIUM_RIDDLE007_KEY", "Key (medium)", "objtypes"),
            new GamevalEntry(3607, "TRAIL_CLUE_MEDIUM_RIDDLE008", "Clue scroll (medium)", "objtypes"),
            new GamevalEntry(3608, "TRAIL_CLUE_MEDIUM_RIDDLE008_KEY", "Key (medium)", "objtypes"),
            new GamevalEntry(3609, "TRAIL_CLUE_MEDIUM_RIDDLE009", "Clue scroll (medium)", "objtypes"),
            new GamevalEntry(3610, "TRAIL_CLUE_MEDIUM_RIDDLE010", "Clue scroll (medium)", "objtypes"),
            new GamevalEntry(3611, "TRAIL_CLUE_MEDIUM_ANAGRAM013", "Clue scroll (medium)", "objtypes"),
            new GamevalEntry(3612, "TRAIL_CLUE_MEDIUM_ANAGRAM014", "Clue scroll (medium)", "objtypes"),
            new GamevalEntry(3613, "TRAIL_CLUE_MEDIUM_ANAGRAM015", "Clue scroll (medium)", "objtypes"),
            new GamevalEntry(3614, "TRAIL_CLUE_MEDIUM_ANAGRAM016", "Clue scroll (medium)", "objtypes"),
            new GamevalEntry(3615, "TRAIL_CLUE_MEDIUM_ANAGRAM017", "Clue scroll (medium)", "objtypes"),
            new GamevalEntry(3616, "TRAIL_CLUE_MEDIUM_ANAGRAM018", "Clue scroll (medium)", "objtypes"),
            new GamevalEntry(3617, "TRAIL_CLUE_MEDIUM_ANAGRAM019", "Clue scroll (medium)", "objtypes"),
            new GamevalEntry(3618, "TRAIL_CLUE_MEDIUM_ANAGRAM020", "Clue scroll (medium)", "objtypes"),
            new GamevalEntry(3619, "TRAIL_SLIDINGPUZZLEC01", "trail_slidingpuzzlec01", "objtypes"),
            new GamevalEntry(3620, "TRAIL_SLIDINGPUZZLEC02", "trail_slidingpuzzlec02", "objtypes"),
            new GamevalEntry(3621, "TRAIL_SLIDINGPUZZLEC03", "trail_slidingpuzzlec03", "objtypes"),
            new GamevalEntry(3622, "TRAIL_SLIDINGPUZZLEC04", "trail_slidingpuzzlec04", "objtypes"),
            new GamevalEntry(3623, "TRAIL_SLIDINGPUZZLEC05", "trail_slidingpuzzlec05", "objtypes"),
            new GamevalEntry(3624, "TRAIL_SLIDINGPUZZLEC06", "trail_slidingpuzzlec06", "objtypes"),
            new GamevalEntry(3625, "TRAIL_SLIDINGPUZZLEC07", "trail_slidingpuzzlec07", "objtypes"),
            new GamevalEntry(3626, "TRAIL_SLIDINGPUZZLEC08", "trail_slidingpuzzlec08", "objtypes"),
            new GamevalEntry(3627, "TRAIL_SLIDINGPUZZLEC09", "trail_slidingpuzzlec09", "objtypes"),
            new GamevalEntry(3628, "TRAIL_SLIDINGPUZZLEC10", "trail_slidingpuzzlec10", "objtypes"),
            new GamevalEntry(3629, "TRAIL_SLIDINGPUZZLEC11", "trail_slidingpuzzlec11", "objtypes"),
            new GamevalEntry(3630, "TRAIL_SLIDINGPUZZLEC12", "trail_slidingpuzzlec12", "objtypes"),
            new GamevalEntry(3631, "TRAIL_SLIDINGPUZZLEC13", "trail_slidingpuzzlec13", "objtypes"),
            new GamevalEntry(3632, "TRAIL_SLIDINGPUZZLEC14", "trail_slidingpuzzlec14", "objtypes"),
            new GamevalEntry(3633, "TRAIL_SLIDINGPUZZLEC15", "trail_slidingpuzzlec15", "objtypes"),
            new GamevalEntry(3634, "TRAIL_SLIDINGPUZZLEC16", "trail_slidingpuzzlec16", "objtypes"),
            new GamevalEntry(3635, "TRAIL_SLIDINGPUZZLEC17", "trail_slidingpuzzlec17", "objtypes"),
            new GamevalEntry(3636, "TRAIL_SLIDINGPUZZLEC18", "trail_slidingpuzzlec18", "objtypes"),
            new GamevalEntry(3637, "TRAIL_SLIDINGPUZZLEC19", "trail_slidingpuzzlec19", "objtypes"),
            new GamevalEntry(3638, "TRAIL_SLIDINGPUZZLEC20", "trail_slidingpuzzlec20", "objtypes"),
            new GamevalEntry(3639, "TRAIL_SLIDINGPUZZLEC21", "trail_slidingpuzzlec21", "objtypes"),
            new GamevalEntry(3640, "TRAIL_SLIDINGPUZZLEC22", "trail_slidingpuzzlec22", "objtypes"),
            new GamevalEntry(3641, "TRAIL_SLIDINGPUZZLEC23", "trail_slidingpuzzlec23", "objtypes"),
            new GamevalEntry(3642, "TRAIL_SLIDINGPUZZLEC24", "trail_slidingpuzzlec24", "objtypes"),
            new GamevalEntry(3643, "TRAIL_SLIDINGPUZZLED01", "trail_slidingpuzzled01", "objtypes"),
            new GamevalEntry(3644, "TRAIL_SLIDINGPUZZLED02", "trail_slidingpuzzled02", "objtypes"),
            new GamevalEntry(3645, "TRAIL_SLIDINGPUZZLED03", "trail_slidingpuzzled03", "objtypes"),
            new GamevalEntry(3646, "TRAIL_SLIDINGPUZZLED04", "trail_slidingpuzzled04", "objtypes"),
            new GamevalEntry(3647, "TRAIL_SLIDINGPUZZLED05", "trail_slidingpuzzled05", "objtypes"),
            new GamevalEntry(3648, "TRAIL_SLIDINGPUZZLED06", "trail_slidingpuzzled06", "objtypes"),
            new GamevalEntry(3649, "TRAIL_SLIDINGPUZZLED07", "trail_slidingpuzzled07", "objtypes"),
            new GamevalEntry(3650, "TRAIL_SLIDINGPUZZLED08", "trail_slidingpuzzled08", "objtypes"),
            new GamevalEntry(3651, "TRAIL_SLIDINGPUZZLED09", "trail_slidingpuzzled09", "objtypes"),
            new GamevalEntry(3652, "TRAIL_SLIDINGPUZZLED10", "trail_slidingpuzzled10", "objtypes"),
            new GamevalEntry(3653, "TRAIL_SLIDINGPUZZLED11", "trail_slidingpuzzled11", "objtypes"),
            new GamevalEntry(3654, "TRAIL_SLIDINGPUZZLED12", "trail_slidingpuzzled12", "objtypes"),
            new GamevalEntry(3655, "TRAIL_SLIDINGPUZZLED13", "trail_slidingpuzzled13", "objtypes"),
            new GamevalEntry(3656, "TRAIL_SLIDINGPUZZLED14", "trail_slidingpuzzled14", "objtypes"),
            new GamevalEntry(3657, "TRAIL_SLIDINGPUZZLED15", "trail_slidingpuzzled15", "objtypes"),
            new GamevalEntry(3658, "TRAIL_SLIDINGPUZZLED16", "trail_slidingpuzzled16", "objtypes"),
            new GamevalEntry(3659, "TRAIL_SLIDINGPUZZLED17", "trail_slidingpuzzled17", "objtypes"),
            new GamevalEntry(3660, "TRAIL_SLIDINGPUZZLED18", "trail_slidingpuzzled18", "objtypes"),
            new GamevalEntry(3661, "TRAIL_SLIDINGPUZZLED19", "trail_slidingpuzzled19", "objtypes"),
            new GamevalEntry(3662, "TRAIL_SLIDINGPUZZLED20", "trail_slidingpuzzled20", "objtypes"),
            new GamevalEntry(3663, "TRAIL_SLIDINGPUZZLED21", "trail_slidingpuzzled21", "objtypes"),
            new GamevalEntry(3664, "TRAIL_SLIDINGPUZZLED22", "trail_slidingpuzzled22", "objtypes"),
            new GamevalEntry(3665, "TRAIL_SLIDINGPUZZLED23", "trail_slidingpuzzled23", "objtypes"),
            new GamevalEntry(3666, "TRAIL_SLIDINGPUZZLED24", "trail_slidingpuzzled24", "objtypes"),
            new GamevalEntry(3667, "VIKING_TOYSHIP", "Boss helper tool", "objtypes"),
            new GamevalEntry(3668, "CERT_BLACK_PLATESKIRT_TRIM", "cert_black_plateskirt_trim", "objtypes"),
            new GamevalEntry(3669, "CERT_BLACK_PLATESKIRT_GOLD", "cert_black_plateskirt_gold", "objtypes"),
            new GamevalEntry(3670, "CERT_ADAMANT_PLATESKIRT_TRIM", "cert_adamant_plateskirt_trim", "objtypes"),
            new GamevalEntry(3671, "CERT_ADAMANT_PLATESKIRT_GOLD", "cert_adamant_plateskirt_gold", "objtypes"),
            new GamevalEntry(3672, "CERT_RUNE_PLATESKIRT_GOLD", "cert_rune_plateskirt_gold", "objtypes"),
            new GamevalEntry(3673, "CERT_RUNE_PLATESKIRT_TRIM", "cert_rune_plateskirt_trim", "objtypes"),
            new GamevalEntry(3674, "CERT_RUNE_PLATESKIRT_ZAMORAK", "cert_rune_plateskirt_zamorak", "objtypes"),
            new GamevalEntry(3675, "CERT_RUNE_PLATESKIRT_SARADOMIN", "cert_rune_plateskirt_saradomin", "objtypes"),
            new GamevalEntry(3676, "CERT_RUNE_PLATESKIRT_GUTHIX", "cert_rune_plateskirt_guthix", "objtypes"),
            new GamevalEntry(3677, "CERT_RUNE_PLATESKIRT_GOLDPLATE", "cert_rune_plateskirt_goldplate", "objtypes"),
            new GamevalEntry(3678, "FLAMTAER_HAMMER", "Flamtaer hammer", "objtypes"),
            new GamevalEntry(3679, "CERT_FLAMTAER_HAMMER", "cert_flamtaer_hammer", "objtypes"),
            new GamevalEntry(3680, "DUMMY_SHOE1", "Shoe", "objtypes"),
            new GamevalEntry(3681, "DUMMY_SHOE2", "Shoe", "objtypes"),
            new GamevalEntry(3682, "DUMMY_SHOE3", "Shoe", "objtypes"),
            new GamevalEntry(3683, "DUMMY_SHOE4", "Shoe", "objtypes"),
            new GamevalEntry(3684, "DUMMY_SHOE5", "Shoe", "objtypes"),
            new GamevalEntry(3685, "DUMMY_SHOE6", "Shoe", "objtypes"),
            new GamevalEntry(3686, "PICKPOCKET_GUIDE_FREMENNIK_CITIZEN", "Fremennik", "objtypes"),
            new GamevalEntry(3687, "CERT_PICKPOCKET_GUIDE_FREMENNIK_CITIZEN", "cert_pickpocket_guide_fremennik_citizen", "objtypes"),
            new GamevalEntry(3688, "VIKING_UNSTRUNG_LYRE", "Unstrung lyre", "objtypes"),
            new GamevalEntry(3689, "VIKING_STRUNG_LYRE", "Lyre", "objtypes"),
            new GamevalEntry(3690, "VIKING_ENCHANTED_STRUNG_LYRE", "Enchanted lyre", "objtypes"),
            new GamevalEntry(3691, "MAGIC_STRUNG_LYRE", "Waterbirth Island", "objtypes"),
            new GamevalEntry(3692, "VIKING_MUSICAL_TREE_BRANCH", "Branch", "objtypes"),
            new GamevalEntry(3693, "VIKING_GOLDEN_FLEECE", "Golden fleece", "objtypes"),
            new GamevalEntry(3694, "VIKING_GOLDEN_WOOL", "Golden wool", "objtypes"),
            new GamevalEntry(3695, "VT_USELESS_ROCK", "Pet rock", "objtypes"),
            new GamevalEntry(3696, "VIKING_DRAUGEN_TALISMAN", "Hunters' talisman", "objtypes"),
            new GamevalEntry(3697, "VIKING_DRAUGEN_TALISMAN_UNCHARGED", "Hunters' talisman", "objtypes"),
            new GamevalEntry(3698, "VIKING_RARE_FLOWER", "Exotic flower", "objtypes"),
            new GamevalEntry(3699, "VIKING_SONG", "Fremennik ballad", "objtypes"),
            new GamevalEntry(3700, "VIKING_NEW_BOOTS", "Sturdy boots", "objtypes"),
            new GamevalEntry(3701, "VIKING_MAP_TO_HUNTING_GROUNDS", "Tracking map", "objtypes"),
            new GamevalEntry(3702, "VIKING_BOWSTRING", "Custom bow string", "objtypes"),
            new GamevalEntry(3703, "VIKING_UNIQUE_FISH", "Unusual fish", "objtypes"),
            new GamevalEntry(3704, "VIKING_ANOTHER_MAP", "Sea fishing map", "objtypes"),
            new GamevalEntry(3705, "VIKING_WEATHER_FORECAST", "Weather forecast", "objtypes"),
            new GamevalEntry(3706, "VIKING_CHAMPION_TOKEN", "Champions token", "objtypes"),
            new GamevalEntry(3707, "VIKING_LEGENDARY_COCKTAIL", "Legendary cocktail", "objtypes"),
            new GamevalEntry(3708, "VIKING_PROMISSARY_NOTE", "Fiscal statement", "objtypes"),
            new GamevalEntry(3709, "VIKING_PROMISSARY_NOTE2", "Promissory note", "objtypes"),
            new GamevalEntry(3710, "VIKING_PROMISSARY_NOTE3", "Warriors' contract", "objtypes"),
            new GamevalEntry(3711, "VIKING_BEERKEG", "Keg of beer", "objtypes"),
            new GamevalEntry(3712, "VIKING_LOW_ALCAHOL_BEERKEG", "Low alcohol keg", "objtypes"),
            new GamevalEntry(3713, "VIKING_FIRECRACKER", "Strange object", "objtypes"),
            new GamevalEntry(3714, "VIKING_FIRECRACKER_LIT", "Lit strange object", "objtypes"),
            new GamevalEntry(3715, "VIKING_DUMMY_COIN", "Red disk", "objtypes"),
            new GamevalEntry(3716, "VIKING_DUMMY_COIN2", "Red disk", "objtypes"),
            new GamevalEntry(3717, "VIKING_DUMMY_LID", "viking_dummy_lid", "objtypes"),
            new GamevalEntry(3718, "VIKING_POINTLESS_MAGNET", "Magnet", "objtypes"),
            new GamevalEntry(3719, "VIKING_POINTLESS_THREAD", "Blue thread", "objtypes"),
            new GamevalEntry(3720, "VIKING_POINTLESS_PICK", "Small pick", "objtypes"),
            new GamevalEntry(3721, "VIKING_POINTLESS_SHIPTOY", "Toy ship", "objtypes"),
            new GamevalEntry(3722, "VIKING_BUCKET_5", "Full bucket", "objtypes"),
            new GamevalEntry(3723, "VIKING_BUCKET_4", "4/5ths full bucket", "objtypes"),
            new GamevalEntry(3724, "VIKING_BUCKET_3", "3/5ths full bucket", "objtypes"),
            new GamevalEntry(3725, "VIKING_BUCKET_2", "2/5ths full bucket", "objtypes"),
            new GamevalEntry(3726, "VIKING_BUCKET_1", "1/5ths full bucket", "objtypes"),
            new GamevalEntry(3727, "VIKING_BUCKET_EMPTY", "Empty bucket", "objtypes"),
            new GamevalEntry(3728, "VIKING_BUCKET_FROZEN", "Frozen bucket", "objtypes"),
            new GamevalEntry(3729, "VIKING_JUG_3", "Full jug", "objtypes"),
            new GamevalEntry(3730, "VIKING_JUG_2", "2/3rds full jug", "objtypes"),
            new GamevalEntry(3731, "VIKING_JUG_1", "1/3rds full jug", "objtypes"),
            new GamevalEntry(3732, "VIKING_JUG_EMPTY", "Empty jug", "objtypes"),
            new GamevalEntry(3733, "VIKING_JUG_FROZEN", "Frozen jug", "objtypes"),
            new GamevalEntry(3734, "VIKING_AIRTIGHT_VASE", "Vase", "objtypes"),
            new GamevalEntry(3735, "VIKING_AIRTIGHT_VASE_WATER", "Vase of water", "objtypes"),
            new GamevalEntry(3736, "VIKING_AIRTIGHT_VASE_FROZEN", "Frozen vase", "objtypes"),
            new GamevalEntry(3737, "VIKING_VASE_LID", "Vase lid", "objtypes"),
            new GamevalEntry(3738, "VIKING_AIRTIGHT_VASE_WITH_LID", "Sealed vase", "objtypes"),
            new GamevalEntry(3739, "VIKING_AIRTIGHT_VASE_WITH_LID_FROZEN", "Sealed vase", "objtypes"),
            new GamevalEntry(3740, "VIKING_AIRTIGHT_VASE_WITH_LID_WATER", "Sealed vase", "objtypes"),
            new GamevalEntry(3741, "VIKING_KEY_IN_ICE", "Frozen key", "objtypes"),
            new GamevalEntry(3742, "VIKING_RED_HERRING", "Red herring", "objtypes"),
            new GamevalEntry(3743, "VIKING_RED_WOODEN_COIN", "Red disk", "objtypes"),
            new GamevalEntry(3744, "VIKING_UNCOLOURED_WOODEN_COIN", "Wooden disk", "objtypes"),
            new GamevalEntry(3745, "VIKING_KEY", "Seer's key", "objtypes"),
            new GamevalEntry(3746, "VIKING_RED_SPLAT", "Sticky red goop", "objtypes"),
            new GamevalEntry(3747, "CERT_VIKING_RED_SPLAT", "cert_viking_red_splat", "objtypes"),
            new GamevalEntry(3748, "VIKING_HELMET", "Fremennik helm", "objtypes"),
            new GamevalEntry(3749, "VIKING_HELMET_RANGE", "Archer helm", "objtypes"),
            new GamevalEntry(3750, "CERT_VIKING_HELMET_RANGE", "cert_viking_helmet_range", "objtypes"),
            new GamevalEntry(3751, "VIKING_HELMET_CRUSH", "Berserker helm", "objtypes"),
            new GamevalEntry(3752, "CERT_VIKING_HELMET_CRUSH", "cert_viking_helmet_crush", "objtypes"),
            new GamevalEntry(3753, "VIKING_HELMET_SLASH", "Warrior helm", "objtypes"),
            new GamevalEntry(3754, "CERT_VIKING_HELMET_SLASH", "cert_viking_helmet_slash", "objtypes"),
            new GamevalEntry(3755, "VIKING_HELMET_MAGIC", "Farseer helm", "objtypes"),
            new GamevalEntry(3756, "CERT_VIKING_HELMET_MAGIC", "cert_viking_helmet_magic", "objtypes"),
            new GamevalEntry(3757, "VIKING_SWORD", "Fremennik blade", "objtypes"),
            new GamevalEntry(3758, "VIKING_SHIELD", "Fremennik shield", "objtypes"),
            new GamevalEntry(3759, "VIKING_CLOAK_GREEN", "Fremennik cyan cloak", "objtypes"),
            new GamevalEntry(3760, "CERT_VIKING_CLOAK_GREEN", "cert_viking_cloak_green", "objtypes"),
            new GamevalEntry(3761, "VIKING_CLOAK_DARKBROWN", "Fremennik brown cloak", "objtypes"),
            new GamevalEntry(3762, "CERT_VIKING_CLOAK_DARKBROWN", "cert_viking_cloak_darkbrown", "objtypes"),
            new GamevalEntry(3763, "VIKING_CLOAK_LIGHTBROWN", "Fremennik blue cloak", "objtypes"),
            new GamevalEntry(3764, "CERT_VIKING_CLOAK_LIGHTBROWN", "cert_viking_cloak_lightbrown", "objtypes"),
            new GamevalEntry(3765, "VIKING_CLOAK_BROWN", "Fremennik green cloak", "objtypes"),
            new GamevalEntry(3766, "CERT_VIKING_CLOAK_BROWN", "cert_viking_cloak_brown", "objtypes"),
            new GamevalEntry(3767, "VIKING_TOP_DARKBROWN", "Fremennik brown shirt", "objtypes"),
            new GamevalEntry(3768, "CERT_VIKING_TOP_DARKBROWN", "cert_viking_top_darkbrown", "objtypes"),
            new GamevalEntry(3769, "VIKING_TOP_GREEN", "Fremennik grey shirt", "objtypes"),
            new GamevalEntry(3770, "CERT_VIKING_TOP_GREEN", "cert_viking_top_green", "objtypes"),
            new GamevalEntry(3771, "VIKING_TOP_BEIGE", "Fremennik beige shirt", "objtypes"),
            new GamevalEntry(3772, "CERT_VIKING_TOP_BEIGE", "cert_viking_top_beige", "objtypes"),
            new GamevalEntry(3773, "VIKING_TOP_RED", "Fremennik red shirt", "objtypes"),
            new GamevalEntry(3774, "CERT_VIKING_TOP_RED", "cert_viking_top_red", "objtypes"),
            new GamevalEntry(3775, "VIKING_TOP_BLUE", "Fremennik blue shirt", "objtypes"),
            new GamevalEntry(3776, "CERT_VIKING_TOP_BLUE", "cert_viking_top_blue", "objtypes"),
            new GamevalEntry(3777, "VIKING_CLOAK_RED", "Fremennik red cloak", "objtypes"),
            new GamevalEntry(3778, "CERT_VIKING_CLOAK_RED", "cert_viking_cloak_red", "objtypes"),
            new GamevalEntry(3779, "VIKING_CLOAK_GREY", "Fremennik grey cloak", "objtypes"),
            new GamevalEntry(3780, "CERT_VIKING_CLOAK_GREY", "cert_viking_cloak_grey", "objtypes"),
            new GamevalEntry(3781, "VIKING_CLOAK_TANGERINE", "Fremennik yellow cloak", "objtypes"),
            new GamevalEntry(3782, "CERT_VIKING_CLOAK_TANGERINE", "cert_viking_cloak_tangerine", "objtypes"),
            new GamevalEntry(3783, "VIKING_CLOAK_OCEAN", "Fremennik teal cloak", "objtypes"),
            new GamevalEntry(3784, "CERT_VIKING_CLOAK_OCEAN", "cert_viking_cloak_ocean", "objtypes"),
            new GamevalEntry(3785, "VIKING_CLOAK_PURPLE", "Fremennik purple cloak", "objtypes"),
            new GamevalEntry(3786, "CERT_VIKING_CLOAK_PURPLE", "cert_viking_cloak_purple", "objtypes"),
            new GamevalEntry(3787, "VIKING_CLOAK_PINK", "Fremennik pink cloak", "objtypes"),
            new GamevalEntry(3788, "CERT_VIKING_CLOAK_PINK", "cert_viking_cloak_pink", "objtypes"),
            new GamevalEntry(3789, "VIKING_CLOAK_BLACK", "Fremennik black cloak", "objtypes"),
            new GamevalEntry(3790, "CERT_VIKING_CLOAK_BLACK", "cert_viking_cloak_black", "objtypes"),
            new GamevalEntry(3791, "VIKINGBOOTS", "Fremennik boots", "objtypes"),
            new GamevalEntry(3792, "CERT_VIKINGBOOTS", "cert_vikingboots", "objtypes"),
            new GamevalEntry(3793, "VIKINGROBETOP", "Fremennik robe", "objtypes"),
            new GamevalEntry(3794, "CERT_VIKINGROBETOP", "cert_vikingrobetop", "objtypes"),
            new GamevalEntry(3795, "VIKINGROBEBOTTOM", "Fremennik skirt", "objtypes"),
            new GamevalEntry(3796, "CERT_VIKINGROBEBOTTOM", "cert_vikingrobebottom", "objtypes"),
            new GamevalEntry(3797, "VIKINGHAT", "Fremennik hat", "objtypes"),
            new GamevalEntry(3798, "CERT_VIKINGHAT", "cert_vikinghat", "objtypes"),
            new GamevalEntry(3799, "VIKINGGLOVES", "Fremennik gloves", "objtypes"),
            new GamevalEntry(3800, "CERT_VIKINGGLOVES", "cert_vikinggloves", "objtypes"),
            new GamevalEntry(3801, "KEG_OF_BEER", "Keg of beer", "objtypes"),
            new GamevalEntry(3802, "CERT_KEG_OF_BEER", "cert_keg_of_beer", "objtypes"),
            new GamevalEntry(3803, "VIKING_TANKARD_FULL", "Beer tankard", "objtypes"),
            new GamevalEntry(3804, "CERT_VIKING_TANKARD_FULL", "cert_viking_tankard_full", "objtypes"),
            new GamevalEntry(3805, "VIKING_TANKARD_EMPTY", "Tankard", "objtypes"),
            new GamevalEntry(3806, "CERT_VIKING_TANKARD_EMPTY", "cert_viking_tankard_empty", "objtypes"),
            new GamevalEntry(3807, "BOLT2", "bolt2", "objtypes"),
            new GamevalEntry(3808, "BOLT3", "bolt3", "objtypes"),
            new GamevalEntry(3809, "BOLT4", "bolt4", "objtypes"),
            new GamevalEntry(3810, "BOLTS", "bolts", "objtypes"),
            new GamevalEntry(3811, "POISON_BOLT2", "poison_bolt2", "objtypes"),
            new GamevalEntry(3812, "POISON_BOLT3", "poison_bolt3", "objtypes"),
            new GamevalEntry(3813, "POISON_BOLT4", "poison_bolt4", "objtypes"),
            new GamevalEntry(3814, "POISON_BOLTS", "poison_bolts", "objtypes"),
            new GamevalEntry(3815, "OPAL_BOLT2", "opal_bolt2", "objtypes"),
            new GamevalEntry(3816, "OPAL_BOLT3", "opal_bolt3", "objtypes"),
            new GamevalEntry(3817, "OPAL_BOLT4", "opal_bolt4", "objtypes"),
            new GamevalEntry(3818, "OPAL_BOLTS", "opal_bolts", "objtypes"),
            new GamevalEntry(3819, "PEARL_BOLT2", "pearl_bolt2", "objtypes"),
            new GamevalEntry(3820, "PEARL_BOLT3", "pearl_bolt3", "objtypes"),
            new GamevalEntry(3821, "PEARL_BOLT4", "pearl_bolt4", "objtypes"),
            new GamevalEntry(3822, "PEARL_BOLTS", "pearl_bolts", "objtypes"),
            new GamevalEntry(3823, "BARBED_BOLT2", "barbed_bolt2", "objtypes"),
            new GamevalEntry(3824, "BARBED_BOLT3", "barbed_bolt3", "objtypes"),
            new GamevalEntry(3825, "BARBED_BOLT4", "barbed_bolt4", "objtypes"),
            new GamevalEntry(3826, "BARBED_BOLTS", "barbed_bolts", "objtypes"),
            new GamevalEntry(3827, "HOLY_BOOK_S_PAGE1", "Saradomin page 1", "objtypes"),
            new GamevalEntry(3828, "HOLY_BOOK_S_PAGE2", "Saradomin page 2", "objtypes"),
            new GamevalEntry(3829, "HOLY_BOOK_S_PAGE3", "Saradomin page 3", "objtypes"),
            new GamevalEntry(3830, "HOLY_BOOK_S_PAGE4", "Saradomin page 4", "objtypes"),
            new GamevalEntry(3831, "HOLY_BOOK_Z_PAGE1", "Zamorak page 1", "objtypes"),
            new GamevalEntry(3832, "HOLY_BOOK_Z_PAGE2", "Zamorak page 2", "objtypes"),
            new GamevalEntry(3833, "HOLY_BOOK_Z_PAGE3", "Zamorak page 3", "objtypes"),
            new GamevalEntry(3834, "HOLY_BOOK_Z_PAGE4", "Zamorak page 4", "objtypes"),
            new GamevalEntry(3835, "HOLY_BOOK_G_PAGE1", "Guthix page 1", "objtypes"),
            new GamevalEntry(3836, "HOLY_BOOK_G_PAGE2", "Guthix page 2", "objtypes"),
            new GamevalEntry(3837, "HOLY_BOOK_G_PAGE3", "Guthix page 3", "objtypes"),
            new GamevalEntry(3838, "HOLY_BOOK_G_PAGE4", "Guthix page 4", "objtypes"),
            new GamevalEntry(3839, "UNFINISHED_SARADOMINBOOK", "Damaged book", "objtypes"),
            new GamevalEntry(3840, "SARADOMINBOOK_COMPLETE", "Holy book", "objtypes"),
            new GamevalEntry(3841, "UNFINISHED_ZAMORAKBOOK", "Damaged book", "objtypes"),
            new GamevalEntry(3842, "ZAMORAKBOOK_COMPLETE", "Unholy book", "objtypes"),
            new GamevalEntry(3843, "UNFINISHED_GUTHIXBOOK", "Damaged book", "objtypes"),
            new GamevalEntry(3844, "GUTHIXBOOK_COMPLETE", "Book of balance", "objtypes"),
            new GamevalEntry(3845, "HORROR_DIARY1", "Journal", "objtypes"),
            new GamevalEntry(3846, "HORROR_DIARY2", "Diary", "objtypes"),
            new GamevalEntry(3847, "HORROR_DIARY3", "3 Manual", "objtypes"),
            new GamevalEntry(3848, "HORROR_KEY", "Lighthouse key", "objtypes"),
            new GamevalEntry(3849, "HORROR_CASKET", "Rusty casket", "objtypes"),
            new GamevalEntry(3850, "READBOOK_DUMMY", "readbook_dummy", "objtypes"),
            new GamevalEntry(3851, "CERT_READBOOK_DUMMY", "cert_readbook_dummy", "objtypes"),
            new GamevalEntry(3852, "CERT_BLESSEDSNAKE", "cert_blessedsnake", "objtypes"),
            new GamevalEntry(3853, "NECKLACE_OF_MINIGAMES_8", "Barbarian Outpost", "objtypes"),
            new GamevalEntry(3854, "CERT_NECKLACE_OF_MINIGAMES_8", "cert_necklace_of_minigames_8", "objtypes"),
            new GamevalEntry(3855, "NECKLACE_OF_MINIGAMES_7", "Barbarian Outpost", "objtypes"),
            new GamevalEntry(3856, "CERT_NECKLACE_OF_MINIGAMES_7", "cert_necklace_of_minigames_7", "objtypes"),
            new GamevalEntry(3857, "NECKLACE_OF_MINIGAMES_6", "Barbarian Outpost", "objtypes"),
            new GamevalEntry(3858, "CERT_NECKLACE_OF_MINIGAMES_6", "cert_necklace_of_minigames_6", "objtypes"),
            new GamevalEntry(3859, "NECKLACE_OF_MINIGAMES_5", "Barbarian Outpost", "objtypes"),
            new GamevalEntry(3860, "CERT_NECKLACE_OF_MINIGAMES_5", "cert_necklace_of_minigames_5", "objtypes"),
            new GamevalEntry(3861, "NECKLACE_OF_MINIGAMES_4", "Barbarian Outpost", "objtypes"),
            new GamevalEntry(3862, "CERT_NECKLACE_OF_MINIGAMES_4", "cert_necklace_of_minigames_4", "objtypes"),
            new GamevalEntry(3863, "NECKLACE_OF_MINIGAMES_3", "Barbarian Outpost", "objtypes"),
            new GamevalEntry(3864, "CERT_NECKLACE_OF_MINIGAMES_3", "cert_necklace_of_minigames_3", "objtypes"),
            new GamevalEntry(3865, "NECKLACE_OF_MINIGAMES_2", "Barbarian Outpost", "objtypes"),
            new GamevalEntry(3866, "CERT_NECKLACE_OF_MINIGAMES_2", "cert_necklace_of_minigames_2", "objtypes"),
            new GamevalEntry(3867, "NECKLACE_OF_MINIGAMES_1", "Barbarian Outpost", "objtypes"),
            new GamevalEntry(3868, "CERT_NECKLACE_OF_MINIGAMES_1", "cert_necklace_of_minigames_1", "objtypes"),
            new GamevalEntry(3869, "BOARDGAMES_DRAUGHTS_FIRERUNE_KING", "Board game piece", "objtypes"),
            new GamevalEntry(3870, "BOARDGAMES_DRAUGHTS_WATERRUNE_KING", "Board game piece", "objtypes"),
            new GamevalEntry(3871, "BOARDGAMES_DRAUGHTS_EARTHRUNE_KING", "Board game piece", "objtypes"),
            new GamevalEntry(3872, "BOARDGAMES_DRAUGHTS_AIRRUNE_KING", "Board game piece", "objtypes"),
            new GamevalEntry(3873, "BOARDGAMES_DRAUGHTS_MINDRUNE_KING", "Board game piece", "objtypes"),
            new GamevalEntry(3874, "BOARDGAMES_DRAUGHTS_BODYRUNE_KING", "Board game piece", "objtypes"),
            new GamevalEntry(3875, "BOARDGAMES_DRAUGHTS_NATURERUNE_KING", "Board game piece", "objtypes"),
            new GamevalEntry(3876, "BOARDGAMES_DRAUGHTS_CHAOSRUNE_KING", "Board game piece", "objtypes"),
            new GamevalEntry(3877, "BOARDGAMES_DRAUGHTS_LAWRUNE_KING", "Board game piece", "objtypes"),
            new GamevalEntry(3878, "BOARDGAMES_DRAUGHTS_COSMICRUNE_KING", "Board game piece", "objtypes"),
            new GamevalEntry(3879, "BOARDGAMES_DRAUGHTS_BLOODRUNE_KING", "Board game piece", "objtypes"),
            new GamevalEntry(3880, "BOARDGAMES_DRAUGHTS_SOULRUNE_KING", "Board game piece", "objtypes"),
            new GamevalEntry(3881, "BOARDGAMES_RUNELINK_FIRERUNE", "q Board game piece", "objtypes"),
            new GamevalEntry(3882, "BOARDGAMES_RUNELINK_WATERRUNE", "q Board game piece", "objtypes"),
            new GamevalEntry(3883, "BOARDGAMES_RUNELINK_EARTHRUNE", "q Board game piece", "objtypes"),
            new GamevalEntry(3884, "BOARDGAMES_RUNELINK_AIRRUNE", "q Board game piece", "objtypes"),
            new GamevalEntry(3885, "BOARDGAMES_RUNELINK_MINDRUNE", "q Board game piece", "objtypes"),
            new GamevalEntry(3886, "BOARDGAMES_RUNELINK_BODYRUNE", "q Board game piece", "objtypes"),
            new GamevalEntry(3887, "BOARDGAMES_RUNELINK_NATURERUNE", "q Board game piece", "objtypes"),
            new GamevalEntry(3888, "BOARDGAMES_RUNELINK_CHAOSRUNE", "q Board game piece", "objtypes"),
            new GamevalEntry(3889, "BOARDGAMES_RUNELINK_LAWRUNE", "q Board game piece", "objtypes"),
            new GamevalEntry(3890, "BOARDGAMES_RUNELINK_COSMICRUNE", "q Board game piece", "objtypes"),
            new GamevalEntry(3891, "BOARDGAMES_RUNELINK_BLOODRUNE", "q Board game piece", "objtypes"),
            new GamevalEntry(3892, "BOARDGAMES_RUNELINK_SOULRUNE", "q Board game piece", "objtypes"),
            new GamevalEntry(3893, "WEARABLE_STOOL_WHITE", "Stool", "objtypes"),
            new GamevalEntry(3894, "MISC_AWFUL_ANTHEM", "Awful anthem", "objtypes"),
            new GamevalEntry(3895, "MISC_GOOD_ANTHEM", "Good anthem", "objtypes"),
            new GamevalEntry(3896, "MISC_TREATY", "Treaty", "objtypes"),
            new GamevalEntry(3897, "MISC_GIANT_NIB", "Giant nib", "objtypes"),
            new GamevalEntry(3898, "MISC_GIANT_PEN", "Giant pen", "objtypes"),
            new GamevalEntry(3899, "IRON_SICKLE", "Iron sickle", "objtypes"),
            new GamevalEntry(3900, "CERT_IRON_SICKLE", "cert_iron_sickle", "objtypes"),
            new GamevalEntry(3901, "MISC_GHRIMBOOK", "Ghrim's book", "objtypes"),
            new GamevalEntry(3902, "REINIT", "reinit", "objtypes"),
            new GamevalEntry(3903, "CERT_REINIT", "cert_reinit", "objtypes"),
            new GamevalEntry(3904, "REINITIALISATION_01", "reinitialisation_01", "objtypes"),
            new GamevalEntry(3905, "CERT_REINITIALISATION_01", "cert_reinitialisation_01", "objtypes"),
            new GamevalEntry(3906, "REINITIALISATION_02", "reinitialisation_02", "objtypes"),
            new GamevalEntry(3907, "CERT_REINITIALISATION_02", "cert_reinitialisation_02", "objtypes"),
            new GamevalEntry(3908, "REINITIALISATION_03", "reinitialisation_03", "objtypes"),
            new GamevalEntry(3909, "CERT_REINITIALISATION_03", "cert_reinitialisation_03", "objtypes"),
            new GamevalEntry(3910, "REINITIALISATION_04", "reinitialisation_04", "objtypes"),
            new GamevalEntry(3911, "CERT_REINITIALISATION_04", "cert_reinitialisation_04", "objtypes"),
            new GamevalEntry(3912, "REINITIALISATION_05", "reinitialisation_05", "objtypes"),
            new GamevalEntry(3913, "CERT_REINITIALISATION_05", "cert_reinitialisation_05", "objtypes"),
            new GamevalEntry(3914, "REINITIALISATION_06", "reinitialisation_06", "objtypes"),
            new GamevalEntry(3915, "CERT_REINITIALISATION_06", "cert_reinitialisation_06", "objtypes"),
            new GamevalEntry(3916, "REINITIALISATION_07", "reinitialisation_07", "objtypes"),
            new GamevalEntry(3917, "CERT_REINITIALISATION_07", "cert_reinitialisation_07", "objtypes"),
            new GamevalEntry(3918, "REINITIALISATION_08", "reinitialisation_08", "objtypes"),
            new GamevalEntry(3919, "CERT_REINITIALISATION_08", "cert_reinitialisation_08", "objtypes"),
            new GamevalEntry(3920, "REINITIALISATION_09", "reinitialisation_09", "objtypes"),
            new GamevalEntry(3921, "CERT_REINITIALISATION_09", "cert_reinitialisation_09", "objtypes"),
            new GamevalEntry(3922, "REINITIALISATION_10", "reinitialisation_10", "objtypes"),
            new GamevalEntry(3923, "CERT_REINITIALISATION_10", "cert_reinitialisation_10", "objtypes"),
            new GamevalEntry(3924, "REINITIALISATION_11", "reinitialisation_11", "objtypes"),
            new GamevalEntry(3925, "CERT_REINITIALISATION_11", "cert_reinitialisation_11", "objtypes"),
            new GamevalEntry(3926, "REINITIALISATION_12", "reinitialisation_12", "objtypes"),
            new GamevalEntry(3927, "CERT_REINITIALISATION_12", "cert_reinitialisation_12", "objtypes"),
            new GamevalEntry(3928, "REINITIALISATION_13", "reinitialisation_13", "objtypes"),
            new GamevalEntry(3929, "CERT_REINITIALISATION_13", "cert_reinitialisation_13", "objtypes"),
            new GamevalEntry(3930, "REINITIALISATION_14", "reinitialisation_14", "objtypes"),
            new GamevalEntry(3931, "CERT_REINITIALISATION_14", "cert_reinitialisation_14", "objtypes"),
            new GamevalEntry(3932, "REINITIALISATION_15", "reinitialisation_15", "objtypes"),
            new GamevalEntry(3933, "CERT_REINITIALISATION_15", "cert_reinitialisation_15", "objtypes"),
            new GamevalEntry(3934, "REINITIALISATION_16", "reinitialisation_16", "objtypes"),
            new GamevalEntry(3935, "CERT_REINITIALISATION_16", "cert_reinitialisation_16", "objtypes"),
            new GamevalEntry(3936, "REINITIALISATION_17", "reinitialisation_17", "objtypes"),
            new GamevalEntry(3937, "CERT_REINITIALISATION_17", "cert_reinitialisation_17", "objtypes"),
            new GamevalEntry(3938, "REINITIALISATION_18", "reinitialisation_18", "objtypes"),
            new GamevalEntry(3939, "CERT_REINITIALISATION_18", "cert_reinitialisation_18", "objtypes"),
            new GamevalEntry(3940, "REINITIALISATION_19", "reinitialisation_19", "objtypes"),
            new GamevalEntry(3941, "CERT_REINITIALISATION_19", "cert_reinitialisation_19", "objtypes"),
            new GamevalEntry(3942, "REINITIALISATION_20", "reinitialisation_20", "objtypes"),
            new GamevalEntry(3943, "CERT_REINITIALISATION_20", "cert_reinitialisation_20", "objtypes"),
            new GamevalEntry(3944, "REINITIALISATION_21", "reinitialisation_21", "objtypes"),
            new GamevalEntry(3945, "CERT_REINITIALISATION_21", "cert_reinitialisation_21", "objtypes"),
            new GamevalEntry(3946, "REINITIALISATION_22", "reinitialisation_22", "objtypes"),
            new GamevalEntry(3947, "CERT_REINITIALISATION_22", "cert_reinitialisation_22", "objtypes"),
            new GamevalEntry(3948, "REINITIALISATION_23", "reinitialisation_23", "objtypes"),
            new GamevalEntry(3949, "CERT_REINITIALISATION_23", "cert_reinitialisation_23", "objtypes"),
            new GamevalEntry(3950, "REINITIALISATION_24", "reinitialisation_24", "objtypes"),
            new GamevalEntry(3951, "CERT_REINITIALISATION_24", "cert_reinitialisation_24", "objtypes"),
            new GamevalEntry(3952, "REINITIALISATION_01_INACTIVE", "reinitialisation_01_inactive", "objtypes"),
            new GamevalEntry(3953, "CERT_REINITIALISATION_01_INACTIVE", "cert_reinitialisation_01_inactive", "objtypes"),
            new GamevalEntry(3954, "REINITIALISATION_02_INACTIVE", "reinitialisation_02_inactive", "objtypes"),
            new GamevalEntry(3955, "CERT_REINITIALISATION_02_INACTIVE", "cert_reinitialisation_02_inactive", "objtypes"),
            new GamevalEntry(3956, "REINITIALISATION_03_INACTIVE", "reinitialisation_03_inactive", "objtypes"),
            new GamevalEntry(3957, "CERT_REINITIALISATION_03_INACTIVE", "cert_reinitialisation_03_inactive", "objtypes"),
            new GamevalEntry(3958, "REINITIALISATION_04_INACTIVE", "reinitialisation_04_inactive", "objtypes"),
            new GamevalEntry(3959, "CERT_REINITIALISATION_04_INACTIVE", "cert_reinitialisation_04_inactive", "objtypes"),
            new GamevalEntry(3960, "REINITIALISATION_05_INACTIVE", "reinitialisation_05_inactive", "objtypes"),
            new GamevalEntry(3961, "CERT_REINITIALISATION_05_INACTIVE", "cert_reinitialisation_05_inactive", "objtypes"),
            new GamevalEntry(3962, "REINITIALISATION_06_INACTIVE", "reinitialisation_06_inactive", "objtypes"),
            new GamevalEntry(3963, "CERT_REINITIALISATION_06_INACTIVE", "cert_reinitialisation_06_inactive", "objtypes"),
            new GamevalEntry(3964, "REINITIALISATION_07_INACTIVE", "reinitialisation_07_inactive", "objtypes"),
            new GamevalEntry(3965, "CERT_REINITIALISATION_07_INACTIVE", "cert_reinitialisation_07_inactive", "objtypes"),
            new GamevalEntry(3966, "REINITIALISATION_08_INACTIVE", "reinitialisation_08_inactive", "objtypes"),
            new GamevalEntry(3967, "CERT_REINITIALISATION_08_INACTIVE", "cert_reinitialisation_08_inactive", "objtypes"),
            new GamevalEntry(3968, "REINITIALISATION_09_INACTIVE", "reinitialisation_09_inactive", "objtypes"),
            new GamevalEntry(3969, "CERT_REINITIALISATION_09_INACTIVE", "X-", "objtypes"),
            new GamevalEntry(3970, "REINITIALISATION_10_INACTIVE", "reinitialisation_10_inactive", "objtypes"),
            new GamevalEntry(3971, "CERT_REINITIALISATION_10_INACTIVE", "X-", "objtypes"),
            new GamevalEntry(3972, "REINITIALISATION_11_INACTIVE", "reinitialisation_11_inactive", "objtypes"),
            new GamevalEntry(3973, "CERT_REINITIALISATION_11_INACTIVE", "cert_reinitialisation_11_inactive", "objtypes"),
            new GamevalEntry(3974, "REINITIALISATION_12_INACTIVE", "reinitialisation_12_inactive", "objtypes"),
            new GamevalEntry(3975, "CERT_REINITIALISATION_12_INACTIVE", "cert_reinitialisation_12_inactive", "objtypes"),
            new GamevalEntry(3976, "REINITIALISATION_13_INACTIVE", "reinitialisation_13_inactive", "objtypes"),
            new GamevalEntry(3977, "CERT_REINITIALISATION_13_INACTIVE", "cert_reinitialisation_13_inactive", "objtypes"),
            new GamevalEntry(3978, "REINITIALISATION_14_INACTIVE", "reinitialisation_14_inactive", "objtypes"),
            new GamevalEntry(3979, "CERT_REINITIALISATION_14_INACTIVE", "cert_reinitialisation_14_inactive", "objtypes"),
            new GamevalEntry(3980, "REINITIALISATION_15_INACTIVE", "reinitialisation_15_inactive", "objtypes"),
            new GamevalEntry(3981, "CERT_REINITIALISATION_15_INACTIVE", "Wilderness sword", "objtypes"),
            new GamevalEntry(3982, "REINITIALISATION_16_INACTIVE", "reinitialisation_16_inactive", "objtypes"),
            new GamevalEntry(3983, "CERT_REINITIALISATION_16_INACTIVE", "Western banner", "objtypes"),
            new GamevalEntry(3984, "REINITIALISATION_17_INACTIVE", "reinitialisation_17_inactive", "objtypes"),
            new GamevalEntry(3985, "CERT_REINITIALISATION_17_INACTIVE", "cert_reinitialisation_17_inactive", "objtypes"),
            new GamevalEntry(3986, "REINITIALISATION_18_INACTIVE", "reinitialisation_18_inactive", "objtypes"),
            new GamevalEntry(3987, "CERT_REINITIALISATION_18_INACTIVE", "cert_reinitialisation_18_inactive", "objtypes"),
            new GamevalEntry(3988, "REINITIALISATION_19_INACTIVE", "reinitialisation_19_inactive", "objtypes"),
            new GamevalEntry(3989, "CERT_REINITIALISATION_19_INACTIVE", "cert_reinitialisation_19_inactive", "objtypes"),
            new GamevalEntry(3990, "REINITIALISATION_20_INACTIVE", "reinitialisation_20_inactive", "objtypes"),
            new GamevalEntry(3991, "CERT_REINITIALISATION_20_INACTIVE", "cert_reinitialisation_20_inactive", "objtypes"),
            new GamevalEntry(3992, "REINITIALISATION_21_INACTIVE", "reinitialisation_21_inactive", "objtypes"),
            new GamevalEntry(3993, "CERT_REINITIALISATION_21_INACTIVE", "cert_reinitialisation_21_inactive", "objtypes"),
            new GamevalEntry(3994, "REINITIALISATION_22_INACTIVE", "reinitialisation_22_inactive", "objtypes"),
            new GamevalEntry(3995, "CERT_REINITIALISATION_22_INACTIVE", "cert_reinitialisation_22_inactive", "objtypes"),
            new GamevalEntry(3996, "REINITIALISATION_23_INACTIVE", "reinitialisation_23_inactive", "objtypes"),
            new GamevalEntry(3997, "CERT_REINITIALISATION_23_INACTIVE", "cert_reinitialisation_23_inactive", "objtypes"),
            new GamevalEntry(3998, "REINITIALISATION_24_INACTIVE", "reinitialisation_24_inactive", "objtypes"),
            new GamevalEntry(3999, "CERT_REINITIALISATION_24_INACTIVE", "cert_reinitialisation_24_inactive", "objtypes"),
            new GamevalEntry(4000, "MM_HELPER", "mm_helper", "objtypes"),
            new GamevalEntry(4001, "CERT_MM_HELPER", "Hardy gout tuber", "objtypes"),
            new GamevalEntry(4002, "MM_REINITIALISATION_HINT", "Spare controls", "objtypes"),
            new GamevalEntry(4003, "CERT_MM_REINITIALISATION_HINT", "cert_mm_reinitialisation_hint", "objtypes"),
            new GamevalEntry(4004, "MM_GNOME_ROYAL_SEAL", "Gnome royal seal", "objtypes"),
            new GamevalEntry(4005, "MM_NARNODE_ORDERS", "Narnode's orders", "objtypes"),
            new GamevalEntry(4006, "MM_MONKEY_DENTURES", "Monkey dentures", "objtypes"),
            new GamevalEntry(4007, "MM_ENCHANTED_GOLD_BAR", "Enchanted bar", "objtypes"),
            new GamevalEntry(4008, "MM_EYE_OF_GNOME", "Eye of gnome", "objtypes"),
            new GamevalEntry(4009, "CERT_MM_EYE_OF_GNOME", "Eye of gnome", "objtypes"),
            new GamevalEntry(4010, "MM_MONKEY_MAGIC", "Monkey magic", "objtypes"),
            new GamevalEntry(4011, "CERT_MM_MONKEY_MAGIC", "cert_mm_monkey_magic", "objtypes"),
            new GamevalEntry(4012, "MM_MONKEY_NUTS", "Monkey nuts", "objtypes"),
            new GamevalEntry(4013, "CERT_MM_MONKEY_NUTS", "cert_mm_monkey_nuts", "objtypes"),
            new GamevalEntry(4014, "MM_MONKEY_BAR", "Monkey bar", "objtypes"),
            new GamevalEntry(4015, "CERT_MM_MONKEY_BAR", "cert_mm_monkey_bar", "objtypes"),
            new GamevalEntry(4016, "MM_BANANA_STEW", "Banana stew", "objtypes"),
            new GamevalEntry(4017, "CERT_MM_BANANA_STEW", "cert_mm_banana_stew", "objtypes"),
            new GamevalEntry(4018, "MM_MONKEY_WRENCH", "Monkey wrench", "objtypes"),
            new GamevalEntry(4019, "CERT_MM_MONKEY_WRENCH", "cert_mm_monkey_wrench", "objtypes"),
            new GamevalEntry(4020, "MM_MONKEY_AMULET_MOULD", "M'amulet mould", "objtypes"),
            new GamevalEntry(4021, "MM_AMULET_OF_MONKEY_SPEAK", "M'speak amulet", "objtypes"),
            new GamevalEntry(4022, "MM_AMULET_OF_MONKEY_SPEAK_WITHOUT_STRING", "M'speak amulet", "objtypes"),
            new GamevalEntry(4023, "MM_MONKEY_TALISMAN", "Monkey talisman", "objtypes"),
            new GamevalEntry(4024, "MM_MONKEY_GREEGREE_FOR_SMALL_NINJA_MONKEY", "Ninja monkey greegree", "objtypes"),
            new GamevalEntry(4025, "MM_MONKEY_GREEGREE_FOR_MEDIUM_NINJA_MONKEY", "Ninja monkey greegree", "objtypes"),
            new GamevalEntry(4026, "MM_MONKEY_GREEGREE_FOR_NORMAL_GORILLA", "Gorilla greegree", "objtypes"),
            new GamevalEntry(4027, "MM_MONKEY_GREEGREE_FOR_BEARDED_GORILLA", "Bearded gorilla greegree", "objtypes"),
            new GamevalEntry(4028, "MM_MONKEY_GREEGREE_FOR_ANCIENT_MONKEY_SKULL", "Ancient gorilla greegree", "objtypes"),
            new GamevalEntry(4029, "MM_MONKEY_GREEGREE_FOR_SMALL_ZOMBIE_MONKEY", "Zombie monkey greegree", "objtypes"),
            new GamevalEntry(4030, "MM_MONKEY_GREEGREE_FOR_LARGE_ZOMBIE_MONKEY", "Zombie monkey greegree", "objtypes"),
            new GamevalEntry(4031, "MM_MONKEY_GREEGREE_FOR_NORMAL_MONKEY", "Karamjan monkey greegree", "objtypes"),
            new GamevalEntry(4032, "FADE_TO_BLACK_INV", "fade_to_black_inv", "objtypes"),
            new GamevalEntry(4033, "MM_MONKEY_IN_BACKPACK", "Monkey", "objtypes"),
            new GamevalEntry(4034, "MM_ANCIENT_MONKEY_SKULL", "Monkey skull", "objtypes"),
            new GamevalEntry(4035, "MM_SIGIL", "10th squad sigil", "objtypes"),
            new GamevalEntry(4036, "CERT_FADE_TO_BLACK_INV", "cert_fade_to_black_inv", "objtypes"),
            new GamevalEntry(4037, "CASTLEWARS_SARADOMIN_BANNER", "Saradomin banner", "objtypes"),
            new GamevalEntry(4038, "CERT_CASTLEWARS_SARADOMIN_BANNER", "cert_castlewars_saradomin_banner", "objtypes"),
            new GamevalEntry(4039, "CASTLEWARS_ZAMORAK_BANNER", "Zamorak banner", "objtypes"),
            new GamevalEntry(4040, "CERT_CASTLEWARS_ZAMORAK_BANNER", "cert_castlewars_zamorak_banner", "objtypes"),
            new GamevalEntry(4041, "CASTLEWARS_CLOAK_SARADOMIN", "Saradomin cloak", "objtypes"),
            new GamevalEntry(4042, "CASTLEWARS_CLOAK_ZAMORAK", "Zamorak cloak", "objtypes"),
            new GamevalEntry(4043, "CASTLEWARS_CATAPULT_ROCK", "Rock", "objtypes"),
            new GamevalEntry(4044, "CERT_CASTLEWARS_CATAPULT_ROCK", "cert_castlewars_catapult_rock", "objtypes"),
            new GamevalEntry(4045, "CASTLEWARS_EXPLOSIVES_POTION", "Explosive potion", "objtypes"),
            new GamevalEntry(4046, "CERT_CASTLEWARS_EXPLOSIVES_POTION", "cert_castlewars_explosives_potion", "objtypes"),
            new GamevalEntry(4047, "CASTLEWARS_CLIMBING_ROPE", "Climbing rope", "objtypes"),
            new GamevalEntry(4048, "CERT_CASTLEWARS_CLIMBING_ROPE", "cert_castlewars_climbing_rope", "objtypes"),
            new GamevalEntry(4049, "CASTLEWARS_BANDAGES", "Bandages", "objtypes"),
            new GamevalEntry(4050, "CERT_CASTLEWARS_BANDAGES", "cert_castlewars_bandages", "objtypes"),
            new GamevalEntry(4051, "CASTLEWARS_TOOLKIT", "Toolkit", "objtypes"),
            new GamevalEntry(4052, "CERT_CASTLEWARS_TOOLKIT", "cert_castlewars_toolkit", "objtypes"),
            new GamevalEntry(4053, "CASTLEWARS_BARRICADE", "Barricade", "objtypes"),
            new GamevalEntry(4054, "CERT_CASTLEWARS_BARRICADE", "cert_castlewars_barricade", "objtypes"),
            new GamevalEntry(4055, "CASTLEWARS_MANUAL", "Castlewars manual", "objtypes"),
            new GamevalEntry(4056, "CASTLEWARS_NO0", "castlewars_no0", "objtypes"),
            new GamevalEntry(4057, "CASTLEWARS_NO1", "castlewars_no1", "objtypes"),
            new GamevalEntry(4058, "CASTLEWARS_NO2", "castlewars_no2", "objtypes"),
            new GamevalEntry(4059, "CASTLEWARS_NO3", "castlewars_no3", "objtypes"),
            new GamevalEntry(4060, "CASTLEWARS_NO4", "castlewars_no4", "objtypes"),
            new GamevalEntry(4061, "CASTLEWARS_NO5", "castlewars_no5", "objtypes"),
            new GamevalEntry(4062, "CASTLEWARS_NO6", "castlewars_no6", "objtypes"),
            new GamevalEntry(4063, "CASTLEWARS_NO7", "castlewars_no7", "objtypes"),
            new GamevalEntry(4064, "CASTLEWARS_NO8", "castlewars_no8", "objtypes"),
            new GamevalEntry(4065, "CASTLEWARS_NO9", "castlewars_no9", "objtypes"),
            new GamevalEntry(4066, "CASTLEWARS_CATAPULT", "castlewars_catapult", "objtypes"),
            new GamevalEntry(4067, "CASTLEWARS_TICKET", "Castle wars ticket", "objtypes"),
            new GamevalEntry(4068, "CASTLEWARS_SWORD", "Decorative sword", "objtypes"),
            new GamevalEntry(4069, "CASTLEWARS_ARMOUR_BODY", "Decorative armour", "objtypes"),
            new GamevalEntry(4070, "CASTLEWARS_ARMOUR_LEGS", "Decorative armour", "objtypes"),
            new GamevalEntry(4071, "CASTLEWARS_MED_HELM", "Decorative helm", "objtypes"),
            new GamevalEntry(4072, "CASTLEWARS_SHIELD", "Decorative shield", "objtypes"),
            new GamevalEntry(4073, "DAMP_TINDERBOX", "Damp tinderbox", "objtypes"),
            new GamevalEntry(4074, "CERT_DAMP_TINDERBOX", "cert_damp_tinderbox", "objtypes"),
            new GamevalEntry(4075, "GLOWING_FUNGUS", "Glowing fungus", "objtypes"),
            new GamevalEntry(4076, "CRYSTALSHARD_DAGGER", "crystalshard_dagger", "objtypes"),
            new GamevalEntry(4077, "HAUNTEDMINE_REWARD_KEY", "Crystal-mine key", "objtypes"),
            new GamevalEntry(4078, "HAUNTEDMINE_LIFT_KEY", "Zealot's key", "objtypes"),
            new GamevalEntry(4079, "XMAS_YOYO", "Yo-yo", "objtypes"),
            new GamevalEntry(4080, "XMAS_YOYOWORN", "xmas_yoyoworn", "objtypes"),
            new GamevalEntry(4081, "CRYSTALSHARD_NECKLACE", "Salve amulet", "objtypes"),
            new GamevalEntry(4082, "CRYSTALSHARD_NECKLACE_UNSTRUNG", "Salve shard", "objtypes"),
            new GamevalEntry(4083, "TROLLROMANCE_TOBOGGON", "Sled", "objtypes"),
            new GamevalEntry(4084, "TROLLROMANCE_TOBOGGON_WAXED", "Sled", "objtypes"),
            new GamevalEntry(4085, "TROLLROMANCE_WAX", "Wax", "objtypes"),
            new GamevalEntry(4086, "TROLLROMANCE_RARE_FLOWER", "Trollweiss", "objtypes"),
            new GamevalEntry(4087, "DRAGON_PLATELEGS", "Dragon platelegs", "objtypes"),
            new GamevalEntry(4088, "CERT_DRAGON_PLATELEGS", "cert_dragon_platelegs", "objtypes"),
            new GamevalEntry(4089, "MYSTIC_HAT", "Mystic hat", "objtypes"),
            new GamevalEntry(4090, "CERT_MYSTIC_HAT", "cert_mystic_hat", "objtypes"),
            new GamevalEntry(4091, "MYSTIC_ROBE_TOP", "Mystic robe top", "objtypes"),
            new GamevalEntry(4092, "CERT_MYSTIC_ROBE_TOP", "cert_mystic_robe_top", "objtypes"),
            new GamevalEntry(4093, "MYSTIC_ROBE_BOTTOM", "Mystic robe bottom", "objtypes"),
            new GamevalEntry(4094, "CERT_MYSTIC_ROBE_BOTTOM", "cert_mystic_robe_bottom", "objtypes"),
            new GamevalEntry(4095, "MYSTIC_GLOVES", "Mystic gloves", "objtypes"),
            new GamevalEntry(4096, "CERT_MYSTIC_GLOVES", "cert_mystic_gloves", "objtypes"),
            new GamevalEntry(4097, "MYSTIC_BOOTS", "Mystic boots", "objtypes"),
            new GamevalEntry(4098, "CERT_MYSTIC_BOOTS", "cert_mystic_boots", "objtypes"),
            new GamevalEntry(4099, "MYSTIC_HAT_DARK", "Mystic hat (dark)", "objtypes"),
            new GamevalEntry(4100, "CERT_MYSTIC_HAT_DARK", "cert_mystic_hat_dark", "objtypes"),
            new GamevalEntry(4101, "MYSTIC_ROBE_TOP_DARK", "Mystic robe top (dark)", "objtypes"),
            new GamevalEntry(4102, "CERT_MYSTIC_ROBE_TOP_DARK", "cert_mystic_robe_top_dark", "objtypes"),
            new GamevalEntry(4103, "MYSTIC_ROBE_BOTTOM_DARK", "Mystic robe bottom (dark)", "objtypes"),
            new GamevalEntry(4104, "CERT_MYSTIC_ROBE_BOTTOM_DARK", "cert_mystic_robe_bottom_dark", "objtypes"),
            new GamevalEntry(4105, "MYSTIC_GLOVES_DARK", "Mystic gloves (dark)", "objtypes"),
            new GamevalEntry(4106, "CERT_MYSTIC_GLOVES_DARK", "cert_mystic_gloves_dark", "objtypes"),
            new GamevalEntry(4107, "MYSTIC_BOOTS_DARK", "Mystic boots (dark)", "objtypes"),
            new GamevalEntry(4108, "CERT_MYSTIC_BOOTS_DARK", "cert_mystic_boots_dark", "objtypes"),
            new GamevalEntry(4109, "MYSTIC_HAT_LIGHT", "Mystic hat (light)", "objtypes"),
        };
    }

    static Optional<GamevalEntry> byId(int id) {
        for (GamevalEntry entry : entries()) {
            if (entry.id() == id) return Optional.of(entry);
        }
        return Optional.empty();
    }

}
