package net.titan.gamevals.internal;

import java.util.Optional;

import net.titan.gamevals.GamevalEntry;
import net.titan.gamevals.QuestEntry;

final class ItemIDEntries_4 {
    private ItemIDEntries_4() {}

    static GamevalEntry[] entries() {
        return new GamevalEntry[] {
            new GamevalEntry(2048, "PINEAPPLE_PUNCH", "Pineapple punch", "objtypes"),
            new GamevalEntry(2049, "ID_2049", "", "objtypes"),
            new GamevalEntry(2050, "UNFINISHED_COCKTAIL_2050", "Unfinished cocktail", "objtypes"),
            new GamevalEntry(2051, "ID_2051", "", "objtypes"),
            new GamevalEntry(2052, "UNFINISHED_COCKTAIL_2052", "Unfinished cocktail", "objtypes"),
            new GamevalEntry(2053, "ID_2053", "", "objtypes"),
            new GamevalEntry(2054, "WIZARD_BLIZZARD", "Wizard blizzard", "objtypes"),
            new GamevalEntry(2055, "ID_2055", "", "objtypes"),
            new GamevalEntry(2056, "UNFINISHED_COCKTAIL_2056", "Unfinished cocktail", "objtypes"),
            new GamevalEntry(2057, "ID_2057", "", "objtypes"),
            new GamevalEntry(2058, "UNFINISHED_COCKTAIL_2058", "Unfinished cocktail", "objtypes"),
            new GamevalEntry(2059, "ID_2059", "", "objtypes"),
            new GamevalEntry(2060, "UNFINISHED_COCKTAIL_2060", "Unfinished cocktail", "objtypes"),
            new GamevalEntry(2061, "ID_2061", "", "objtypes"),
            new GamevalEntry(2062, "UNFINISHED_COCKTAIL_2062", "Unfinished cocktail", "objtypes"),
            new GamevalEntry(2063, "ID_2063", "", "objtypes"),
            new GamevalEntry(2064, "BLURBERRY_SPECIAL", "Blurberry special", "objtypes"),
            new GamevalEntry(2065, "ID_2065", "", "objtypes"),
            new GamevalEntry(2066, "UNFINISHED_COCKTAIL_2066", "Unfinished cocktail", "objtypes"),
            new GamevalEntry(2067, "ID_2067", "", "objtypes"),
            new GamevalEntry(2068, "UNFINISHED_COCKTAIL_2068", "Unfinished cocktail", "objtypes"),
            new GamevalEntry(2069, "ID_2069", "", "objtypes"),
            new GamevalEntry(2070, "UNFINISHED_COCKTAIL_2070", "Unfinished cocktail", "objtypes"),
            new GamevalEntry(2071, "ID_2071", "", "objtypes"),
            new GamevalEntry(2072, "UNFINISHED_COCKTAIL_2072", "Unfinished cocktail", "objtypes"),
            new GamevalEntry(2073, "ID_2073", "", "objtypes"),
            new GamevalEntry(2074, "CHOC_SATURDAY", "Choc saturday", "objtypes"),
            new GamevalEntry(2075, "ID_2075", "", "objtypes"),
            new GamevalEntry(2076, "UNFINISHED_COCKTAIL_2076", "Unfinished cocktail", "objtypes"),
            new GamevalEntry(2077, "ID_2077", "", "objtypes"),
            new GamevalEntry(2078, "UNFINISHED_COCKTAIL_2078", "Unfinished cocktail", "objtypes"),
            new GamevalEntry(2079, "ID_2079", "", "objtypes"),
            new GamevalEntry(2080, "SHORT_GREEN_GUY", "Short green guy", "objtypes"),
            new GamevalEntry(2081, "ID_2081", "", "objtypes"),
            new GamevalEntry(2082, "UNFINISHED_COCKTAIL_2082", "Unfinished cocktail", "objtypes"),
            new GamevalEntry(2083, "ID_2083", "", "objtypes"),
            new GamevalEntry(2084, "FRUIT_BLAST", "Fruit blast", "objtypes"),
            new GamevalEntry(2085, "ID_2085", "", "objtypes"),
            new GamevalEntry(2086, "UNFINISHED_COCKTAIL_2086", "Unfinished cocktail", "objtypes"),
            new GamevalEntry(2087, "ID_2087", "", "objtypes"),
            new GamevalEntry(2088, "UNFINISHED_COCKTAIL_2088", "Unfinished cocktail", "objtypes"),
            new GamevalEntry(2089, "ID_2089", "", "objtypes"),
            new GamevalEntry(2090, "UNFINISHED_COCKTAIL_2090", "Unfinished cocktail", "objtypes"),
            new GamevalEntry(2091, "ID_2091", "", "objtypes"),
            new GamevalEntry(2092, "DRUNK_DRAGON", "Drunk dragon", "objtypes"),
            new GamevalEntry(2093, "ID_2093", "", "objtypes"),
            new GamevalEntry(2094, "ODD_COCKTAIL", "Odd cocktail", "objtypes"),
            new GamevalEntry(2095, "ID_2095", "", "objtypes"),
            new GamevalEntry(2096, "ODD_COCKTAIL_2096", "Odd cocktail", "objtypes"),
            new GamevalEntry(2097, "ID_2097", "", "objtypes"),
            new GamevalEntry(2098, "ODD_COCKTAIL_2098", "Odd cocktail", "objtypes"),
            new GamevalEntry(2099, "ID_2099", "", "objtypes"),
            new GamevalEntry(2100, "ODD_COCKTAIL_2100", "Odd cocktail", "objtypes"),
            new GamevalEntry(2101, "ID_2101", "", "objtypes"),
            new GamevalEntry(2102, "LEMON", "Lemon", "objtypes"),
            new GamevalEntry(2103, "ID_2103", "", "objtypes"),
            new GamevalEntry(2104, "LEMON_CHUNKS", "Lemon chunks", "objtypes"),
            new GamevalEntry(2105, "ID_2105", "", "objtypes"),
            new GamevalEntry(2106, "LEMON_SLICES", "Lemon slices", "objtypes"),
            new GamevalEntry(2107, "ID_2107", "", "objtypes"),
            new GamevalEntry(2108, "ORANGE", "Orange", "objtypes"),
            new GamevalEntry(2109, "ID_2109", "", "objtypes"),
            new GamevalEntry(2110, "ORANGE_CHUNKS", "Orange chunks", "objtypes"),
            new GamevalEntry(2111, "ID_2111", "", "objtypes"),
            new GamevalEntry(2112, "ORANGE_SLICES", "Orange slices", "objtypes"),
            new GamevalEntry(2113, "ID_2113", "", "objtypes"),
            new GamevalEntry(2114, "PINEAPPLE", "Pineapple", "objtypes"),
            new GamevalEntry(2115, "ID_2115", "", "objtypes"),
            new GamevalEntry(2116, "PINEAPPLE_CHUNKS", "Pineapple chunks", "objtypes"),
            new GamevalEntry(2117, "ID_2117", "", "objtypes"),
            new GamevalEntry(2118, "PINEAPPLE_RING", "Pineapple ring", "objtypes"),
            new GamevalEntry(2119, "ID_2119", "", "objtypes"),
            new GamevalEntry(2120, "LIME", "Lime", "objtypes"),
            new GamevalEntry(2121, "ID_2121", "", "objtypes"),
            new GamevalEntry(2122, "LIME_CHUNKS", "Lime chunks", "objtypes"),
            new GamevalEntry(2123, "ID_2123", "", "objtypes"),
            new GamevalEntry(2124, "LIME_SLICES", "Lime slices", "objtypes"),
            new GamevalEntry(2125, "ID_2125", "", "objtypes"),
            new GamevalEntry(2126, "DWELLBERRIES", "Dwellberries", "objtypes"),
            new GamevalEntry(2127, "ID_2127", "", "objtypes"),
            new GamevalEntry(2128, "EQUA_LEAVES", "Equa leaves", "objtypes"),
            new GamevalEntry(2129, "ID_2129", "", "objtypes"),
            new GamevalEntry(2130, "POT_OF_CREAM", "Pot of cream", "objtypes"),
            new GamevalEntry(2131, "ID_2131", "", "objtypes"),
            new GamevalEntry(2132, "RAW_BEEF", "Raw beef", "objtypes"),
            new GamevalEntry(2133, "ID_2133", "", "objtypes"),
            new GamevalEntry(2134, "RAW_RAT_MEAT", "Raw rat meat", "objtypes"),
            new GamevalEntry(2135, "ID_2135", "", "objtypes"),
            new GamevalEntry(2136, "RAW_BEAR_MEAT", "Raw bear meat", "objtypes"),
            new GamevalEntry(2137, "ID_2137", "", "objtypes"),
            new GamevalEntry(2138, "RAW_CHICKEN", "Raw chicken", "objtypes"),
            new GamevalEntry(2139, "ID_2139", "", "objtypes"),
            new GamevalEntry(2140, "COOKED_CHICKEN", "Cooked chicken", "objtypes"),
            new GamevalEntry(2141, "ID_2141", "", "objtypes"),
            new GamevalEntry(2142, "COOKED_MEAT", "Cooked meat", "objtypes"),
            new GamevalEntry(2143, "ID_2143", "", "objtypes"),
            new GamevalEntry(2144, "BURNT_CHICKEN", "Burnt chicken", "objtypes"),
            new GamevalEntry(2145, "ID_2145", "", "objtypes"),
            new GamevalEntry(2146, "BURNT_MEAT", "Burnt meat", "objtypes"),
            new GamevalEntry(2147, "ID_2147", "", "objtypes"),
            new GamevalEntry(2148, "RAW_LAVA_EEL", "Raw lava eel", "objtypes"),
            new GamevalEntry(2149, "LAVA_EEL", "Lava eel", "objtypes"),
            new GamevalEntry(2150, "SWAMP_TOAD", "Swamp toad", "objtypes"),
            new GamevalEntry(2151, "ID_2151", "", "objtypes"),
            new GamevalEntry(2152, "TOAD_S_LEGS", "Toad's legs", "objtypes"),
            new GamevalEntry(2153, "ID_2153", "", "objtypes"),
            new GamevalEntry(2154, "EQUA_TOAD_S_LEGS", "Equa toad's legs", "objtypes"),
            new GamevalEntry(2155, "ID_2155", "", "objtypes"),
            new GamevalEntry(2156, "SPICY_TOAD_S_LEGS", "Spicy toad's legs", "objtypes"),
            new GamevalEntry(2157, "ID_2157", "", "objtypes"),
            new GamevalEntry(2158, "SEASONED_LEGS", "Seasoned legs", "objtypes"),
            new GamevalEntry(2159, "ID_2159", "", "objtypes"),
            new GamevalEntry(2160, "SPICY_WORM", "Spicy worm", "objtypes"),
            new GamevalEntry(2161, "ID_2161", "", "objtypes"),
            new GamevalEntry(2162, "KING_WORM", "King worm", "objtypes"),
            new GamevalEntry(2163, "ID_2163", "", "objtypes"),
            new GamevalEntry(2164, "BATTA_TIN", "Batta tin", "objtypes"),
            new GamevalEntry(2165, "CRUNCHY_TRAY", "Crunchy tray", "objtypes"),
            new GamevalEntry(2166, "GNOMEBOWL_MOULD", "Gnomebowl mould", "objtypes"),
            new GamevalEntry(2167, "GIANNE_S_COOK_BOOK", "Gianne's cook book", "objtypes"),
            new GamevalEntry(2168, "ID_2168", "", "objtypes"),
            new GamevalEntry(2169, "GNOME_SPICE", "Gnome spice", "objtypes"),
            new GamevalEntry(2170, "ID_2170", "", "objtypes"),
            new GamevalEntry(2171, "GIANNE_DOUGH", "Gianne dough", "objtypes"),
            new GamevalEntry(2172, "ID_2172", "", "objtypes"),
            new GamevalEntry(2173, "ODD_GNOMEBOWL", "Odd gnomebowl", "objtypes"),
            new GamevalEntry(2174, "ID_2174", "", "objtypes"),
            new GamevalEntry(2175, "BURNT_GNOMEBOWL", "Burnt gnomebowl", "objtypes"),
            new GamevalEntry(2176, "ID_2176", "", "objtypes"),
            new GamevalEntry(2177, "HALF_BAKED_BOWL", "Half baked bowl", "objtypes"),
            new GamevalEntry(2178, "RAW_GNOMEBOWL", "Raw gnomebowl", "objtypes"),
            new GamevalEntry(2179, "UNFINISHED_BOWL", "Unfinished bowl", "objtypes"),
            new GamevalEntry(2180, "ID_2180", "", "objtypes"),
            new GamevalEntry(2181, "UNFINISHED_BOWL_2181", "Unfinished bowl", "objtypes"),
            new GamevalEntry(2182, "ID_2182", "", "objtypes"),
            new GamevalEntry(2183, "UNFINISHED_BOWL_2183", "Unfinished bowl", "objtypes"),
            new GamevalEntry(2184, "ID_2184", "", "objtypes"),
            new GamevalEntry(2185, "CHOCOLATE_BOMB", "Chocolate bomb", "objtypes"),
            new GamevalEntry(2186, "ID_2186", "", "objtypes"),
            new GamevalEntry(2187, "TANGLED_TOAD_S_LEGS", "Tangled toad's legs", "objtypes"),
            new GamevalEntry(2188, "ID_2188", "", "objtypes"),
            new GamevalEntry(2189, "UNFINISHED_BOWL_2189", "Unfinished bowl", "objtypes"),
            new GamevalEntry(2190, "ID_2190", "", "objtypes"),
            new GamevalEntry(2191, "WORM_HOLE", "Worm hole", "objtypes"),
            new GamevalEntry(2192, "ID_2192", "", "objtypes"),
            new GamevalEntry(2193, "UNFINISHED_BOWL_2193", "Unfinished bowl", "objtypes"),
            new GamevalEntry(2194, "ID_2194", "", "objtypes"),
            new GamevalEntry(2195, "U2D_S2D_VEG_BALL", "(u2D(s2D Veg ball", "objtypes"),
            new GamevalEntry(2196, "ID_2196", "", "objtypes"),
            new GamevalEntry(2197, "ODD_CRUNCHIES", "Odd crunchies", "objtypes"),
            new GamevalEntry(2198, "ID_2198", "", "objtypes"),
            new GamevalEntry(2199, "BURNT_CRUNCHIES", "Burnt crunchies", "objtypes"),
            new GamevalEntry(2200, "ID_2200", "", "objtypes"),
            new GamevalEntry(2201, "HALF_BAKED_CRUNCHY", "Half baked crunchy", "objtypes"),
            new GamevalEntry(2202, "RAW_CRUNCHIES", "Raw crunchies", "objtypes"),
            new GamevalEntry(2203, "ROCK_CLIMBING_BOOTS", "Rock-climbing boots", "objtypes"),
            new GamevalEntry(2204, "ID_2204", "", "objtypes"),
            new GamevalEntry(2205, "WORM_CRUNCHIES", "Worm crunchies", "objtypes"),
            new GamevalEntry(2206, "ID_2206", "", "objtypes"),
            new GamevalEntry(2207, "UNFINISHED_CRUNCHY", "Unfinished crunchy", "objtypes"),
            new GamevalEntry(2208, "ID_2208", "", "objtypes"),
            new GamevalEntry(2209, "CHOCCHIP_CRUNCHIES", "Chocchip crunchies", "objtypes"),
            new GamevalEntry(2210, "ID_2210", "", "objtypes"),
            new GamevalEntry(2211, "UNFINISHED_CRUNCHY_2211", "Unfinished crunchy", "objtypes"),
            new GamevalEntry(2212, "ID_2212", "", "objtypes"),
            new GamevalEntry(2213, "SPICY_CRUNCHIES", "Spicy crunchies", "objtypes"),
            new GamevalEntry(2214, "ID_2214", "", "objtypes"),
            new GamevalEntry(2215, "UNFINISHED_CRUNCHY_2215", "Unfinished crunchy", "objtypes"),
            new GamevalEntry(2216, "ID_2216", "", "objtypes"),
            new GamevalEntry(2217, "TOAD_CRUNCHIES", "Toad crunchies", "objtypes"),
            new GamevalEntry(2218, "ID_2218", "", "objtypes"),
            new GamevalEntry(2219, "PREMADE_W_M_BATTA", "Premade w'm batta", "objtypes"),
            new GamevalEntry(2220, "ID_2220", "", "objtypes"),
            new GamevalEntry(2221, "PREMADE_T_D_BATTA", "Premade t'd batta", "objtypes"),
            new GamevalEntry(2222, "ID_2222", "", "objtypes"),
            new GamevalEntry(2223, "PREMADE_C_T_BATTA", "Premade c+t batta", "objtypes"),
            new GamevalEntry(2224, "ID_2224", "", "objtypes"),
            new GamevalEntry(2225, "PREMADE_FR_T_BATTA", "Premade fr't batta", "objtypes"),
            new GamevalEntry(2226, "ID_2226", "", "objtypes"),
            new GamevalEntry(2227, "PREMADE_VEG_BATTA", "Premade veg batta", "objtypes"),
            new GamevalEntry(2228, "ID_2228", "", "objtypes"),
            new GamevalEntry(2229, "PREMADE_CHOC_BOMB", "Premade choc bomb", "objtypes"),
            new GamevalEntry(2230, "ID_2230", "", "objtypes"),
            new GamevalEntry(2231, "PREMADE_TTL", "Premade ttl", "objtypes"),
            new GamevalEntry(2232, "ID_2232", "", "objtypes"),
            new GamevalEntry(2233, "PREMADE_WORM_HOLE", "Premade worm hole", "objtypes"),
            new GamevalEntry(2234, "ID_2234", "", "objtypes"),
            new GamevalEntry(2235, "PREMADE_VEG_BALL", "Premade veg ball", "objtypes"),
            new GamevalEntry(2236, "ID_2236", "", "objtypes"),
            new GamevalEntry(2237, "PREMADE_W_M_CRUN", "Premade w'm crun'", "objtypes"),
            new GamevalEntry(2238, "ID_2238", "", "objtypes"),
            new GamevalEntry(2239, "PREMADE_CH_CRUNCH", "Premade ch' crunch", "objtypes"),
            new GamevalEntry(2240, "ID_2240", "", "objtypes"),
            new GamevalEntry(2241, "PREMADE_S_Y_CRUNCH", "Premade s'y crunch", "objtypes"),
            new GamevalEntry(2242, "ID_2242", "", "objtypes"),
            new GamevalEntry(2243, "PREMADE_T_D_CRUNCH", "Premade t'd crunch", "objtypes"),
            new GamevalEntry(2244, "ID_2244", "", "objtypes"),
            new GamevalEntry(2245, "ODD_BATTA", "Odd batta", "objtypes"),
            new GamevalEntry(2246, "ID_2246", "", "objtypes"),
            new GamevalEntry(2247, "BURNT_BATTA", "Burnt batta", "objtypes"),
            new GamevalEntry(2248, "ID_2248", "", "objtypes"),
            new GamevalEntry(2249, "HALF_BAKED_BATTA", "Half baked batta", "objtypes"),
            new GamevalEntry(2250, "RAW_BATTA", "Raw batta", "objtypes"),
            new GamevalEntry(2251, "UNFINISHED_BATTA", "Unfinished batta", "objtypes"),
            new GamevalEntry(2252, "ID_2252", "", "objtypes"),
            new GamevalEntry(2253, "WORM_BATTA", "Worm batta", "objtypes"),
            new GamevalEntry(2254, "ID_2254", "", "objtypes"),
            new GamevalEntry(2255, "TOAD_BATTA", "Toad batta", "objtypes"),
            new GamevalEntry(2256, "ID_2256", "", "objtypes"),
            new GamevalEntry(2257, "UNFINISHED_BATTA_2257", "Unfinished batta", "objtypes"),
            new GamevalEntry(2258, "ID_2258", "", "objtypes"),
            new GamevalEntry(2259, "CHEESE_TOM_BATTA", "Cheese+tom batta", "objtypes"),
            new GamevalEntry(2260, "ID_2260", "", "objtypes"),
            new GamevalEntry(2261, "UNFINISHED_BATTA_2261", "Unfinished batta", "objtypes"),
            new GamevalEntry(2262, "ID_2262", "", "objtypes"),
            new GamevalEntry(2263, "UNFINISHED_BATTA_2263", "Unfinished batta", "objtypes"),
            new GamevalEntry(2264, "ID_2264", "", "objtypes"),
            new GamevalEntry(2265, "UNFINISHED_BATTA_2265", "Unfinished batta", "objtypes"),
            new GamevalEntry(2266, "ID_2266", "", "objtypes"),
            new GamevalEntry(2267, "UNFINISHED_BATTA_2267", "Unfinished batta", "objtypes"),
            new GamevalEntry(2268, "ID_2268", "", "objtypes"),
            new GamevalEntry(2269, "UNFINISHED_BATTA_2269", "Unfinished batta", "objtypes"),
            new GamevalEntry(2270, "ID_2270", "", "objtypes"),
            new GamevalEntry(2271, "UNFINISHED_BATTA_2271", "Unfinished batta", "objtypes"),
            new GamevalEntry(2272, "ID_2272", "", "objtypes"),
            new GamevalEntry(2273, "UNFINISHED_BATTA_2273", "Unfinished batta", "objtypes"),
            new GamevalEntry(2274, "ID_2274", "", "objtypes"),
            new GamevalEntry(2275, "UNFINISHED_BATTA_2275", "Unfinished batta", "objtypes"),
            new GamevalEntry(2276, "ID_2276", "", "objtypes"),
            new GamevalEntry(2277, "FRUIT_BATTA", "Fruit batta", "objtypes"),
            new GamevalEntry(2278, "ID_2278", "", "objtypes"),
            new GamevalEntry(2279, "UNFINISHED_BATTA_2279", "Unfinished batta", "objtypes"),
            new GamevalEntry(2280, "ID_2280", "", "objtypes"),
            new GamevalEntry(2281, "VEGETABLE_BATTA", "Vegetable batta", "objtypes"),
            new GamevalEntry(2282, "ID_2282", "", "objtypes"),
            new GamevalEntry(2283, "PIZZA_BASE", "Pizza base", "objtypes"),
            new GamevalEntry(2284, "ID_2284", "", "objtypes"),
            new GamevalEntry(2285, "INCOMPLETE_PIZZA", "Incomplete pizza", "objtypes"),
            new GamevalEntry(2286, "ID_2286", "", "objtypes"),
            new GamevalEntry(2287, "UNCOOKED_PIZZA", "Uncooked pizza", "objtypes"),
            new GamevalEntry(2288, "ID_2288", "", "objtypes"),
            new GamevalEntry(2289, "PLAIN_PIZZA", "Plain pizza", "objtypes"),
            new GamevalEntry(2290, "ID_2290", "", "objtypes"),
            new GamevalEntry(2291, "ID_2291_1_2_PLAIN_PIZZA", "1/2 plain pizza", "objtypes"),
            new GamevalEntry(2292, "ID_2292", "", "objtypes"),
            new GamevalEntry(2293, "MEAT_PIZZA", "Meat pizza", "objtypes"),
            new GamevalEntry(2294, "ID_2294", "", "objtypes"),
            new GamevalEntry(2295, "ID_2295_1_2_MEAT_PIZZA", "1/2 meat pizza", "objtypes"),
            new GamevalEntry(2296, "ID_2296", "", "objtypes"),
            new GamevalEntry(2297, "ANCHOVY_PIZZA", "Anchovy pizza", "objtypes"),
            new GamevalEntry(2298, "ID_2298", "", "objtypes"),
            new GamevalEntry(2299, "ID_2299_1_2_ANCHOVY_PIZZA", "1/2 anchovy pizza", "objtypes"),
            new GamevalEntry(2300, "ID_2300", "", "objtypes"),
            new GamevalEntry(2301, "PINEAPPLE_PIZZA", "Pineapple pizza", "objtypes"),
            new GamevalEntry(2302, "ID_2302", "", "objtypes"),
            new GamevalEntry(2303, "ID_2303_1_2_PINEAPPLE_PIZZA", "1/2 pineapple pizza", "objtypes"),
            new GamevalEntry(2304, "ID_2304", "", "objtypes"),
            new GamevalEntry(2305, "BURNT_PIZZA", "Burnt pizza", "objtypes"),
            new GamevalEntry(2306, "ID_2306", "", "objtypes"),
            new GamevalEntry(2307, "XA_BREAD_DOUGH", "XA Bread dough", "objtypes"),
            new GamevalEntry(2308, "ID_2308", "", "objtypes"),
            new GamevalEntry(2309, "BREAD", "Bread", "objtypes"),
            new GamevalEntry(2310, "ID_2310", "", "objtypes"),
            new GamevalEntry(2311, "BURNT_BREAD", "Burnt bread", "objtypes"),
            new GamevalEntry(2312, "ID_2312", "", "objtypes"),
            new GamevalEntry(2313, "PIE_DISH", "Pie dish", "objtypes"),
            new GamevalEntry(2314, "ID_2314", "", "objtypes"),
            new GamevalEntry(2315, "PIE_SHELL", "Pie shell", "objtypes"),
            new GamevalEntry(2316, "ID_2316", "", "objtypes"),
            new GamevalEntry(2317, "UNCOOKED_APPLE_PIE", "Uncooked apple pie", "objtypes"),
            new GamevalEntry(2318, "ID_2318", "", "objtypes"),
            new GamevalEntry(2319, "UNCOOKED_MEAT_PIE", "Uncooked meat pie", "objtypes"),
            new GamevalEntry(2320, "ID_2320", "", "objtypes"),
            new GamevalEntry(2321, "UNCOOKED_BERRY_PIE", "Uncooked berry pie", "objtypes"),
            new GamevalEntry(2322, "ID_2322", "", "objtypes"),
            new GamevalEntry(2323, "APPLE_PIE", "Apple pie", "objtypes"),
            new GamevalEntry(2324, "ID_2324", "", "objtypes"),
            new GamevalEntry(2325, "REDBERRY_PIE", "Redberry pie", "objtypes"),
            new GamevalEntry(2326, "ID_2326", "", "objtypes"),
            new GamevalEntry(2327, "MEAT_PIE", "Meat pie", "objtypes"),
            new GamevalEntry(2328, "ID_2328", "", "objtypes"),
            new GamevalEntry(2329, "BURNT_PIE", "Burnt pie", "objtypes"),
            new GamevalEntry(2330, "ID_2330", "", "objtypes"),
            new GamevalEntry(2331, "HALF_A_MEAT_PIE", "Half a meat pie", "objtypes"),
            new GamevalEntry(2332, "ID_2332", "", "objtypes"),
            new GamevalEntry(2333, "HALF_A_REDBERRY_PIE", "Half a redberry pie", "objtypes"),
            new GamevalEntry(2334, "ID_2334", "", "objtypes"),
            new GamevalEntry(2335, "HALF_AN_APPLE_PIE", "Half an apple pie", "objtypes"),
            new GamevalEntry(2336, "ID_2336", "", "objtypes"),
            new GamevalEntry(2337, "RAW_OOMLIE", "Raw oomlie", "objtypes"),
            new GamevalEntry(2338, "ID_2338", "", "objtypes"),
            new GamevalEntry(2339, "PALM_LEAF", "Palm leaf", "objtypes"),
            new GamevalEntry(2340, "PALM_LEAF_2340", "Palm leaf", "objtypes"),
            new GamevalEntry(2341, "WRAPPED_OOMLIE", "Wrapped oomlie", "objtypes"),
            new GamevalEntry(2342, "ID_2342", "", "objtypes"),
            new GamevalEntry(2343, "COOKED_OOMLIE_WRAP", "Cooked oomlie wrap", "objtypes"),
            new GamevalEntry(2344, "ID_2344", "", "objtypes"),
            new GamevalEntry(2345, "BURNT_OOMLIE_WRAP", "Burnt oomlie wrap", "objtypes"),
            new GamevalEntry(2346, "ID_2346", "", "objtypes"),
            new GamevalEntry(2347, "HAMMER", "Hammer", "objtypes"),
            new GamevalEntry(2348, "ID_2348", "", "objtypes"),
            new GamevalEntry(2349, "BRONZE_BAR", "Bronze bar", "objtypes"),
            new GamevalEntry(2350, "ID_2350", "", "objtypes"),
            new GamevalEntry(2351, "IRON_BAR", "Iron bar", "objtypes"),
            new GamevalEntry(2352, "ID_2352", "", "objtypes"),
            new GamevalEntry(2353, "STEEL_BAR", "Steel bar", "objtypes"),
            new GamevalEntry(2354, "ID_2354", "", "objtypes"),
            new GamevalEntry(2355, "SILVER_BAR", "Silver bar", "objtypes"),
            new GamevalEntry(2356, "ID_2356", "", "objtypes"),
            new GamevalEntry(2357, "GOLD_BAR", "Gold bar", "objtypes"),
            new GamevalEntry(2358, "ID_2358", "", "objtypes"),
            new GamevalEntry(2359, "MITHRIL_BAR", "Mithril bar", "objtypes"),
            new GamevalEntry(2360, "ID_2360", "", "objtypes"),
            new GamevalEntry(2361, "ADAMANTITE_BAR", "Adamantite bar", "objtypes"),
            new GamevalEntry(2362, "ID_2362", "", "objtypes"),
            new GamevalEntry(2363, "RUNITE_BAR", "Runite bar", "objtypes"),
            new GamevalEntry(2364, "ID_2364", "", "objtypes"),
            new GamevalEntry(2365, "PERFECT_GOLD_BAR", "'perfect' gold bar", "objtypes"),
            new GamevalEntry(2366, "SHIELD_LEFT_HALF", "Shield left half", "objtypes"),
            new GamevalEntry(2367, "ID_2367", "", "objtypes"),
            new GamevalEntry(2368, "SHIELD_RIGHT_HALF", "Shield right half", "objtypes"),
            new GamevalEntry(2369, "ID_2369", "", "objtypes"),
            new GamevalEntry(2370, "STEEL_STUDS", "Steel studs", "objtypes"),
            new GamevalEntry(2371, "ID_2371", "", "objtypes"),
            new GamevalEntry(2372, "OGRE_RELIC", "Ogre relic", "objtypes"),
            new GamevalEntry(2373, "RELIC_PART_1", "Relic part 1", "objtypes"),
            new GamevalEntry(2374, "RELIC_PART_2", "Relic part 2", "objtypes"),
            new GamevalEntry(2375, "RELIC_PART_3", "Relic part 3", "objtypes"),
            new GamevalEntry(2376, "SKAVID_MAP", "Skavid map", "objtypes"),
            new GamevalEntry(2377, "OGRE_TOOTH", "Ogre tooth", "objtypes"),
            new GamevalEntry(2378, "TOBAN_S_KEY", "Toban's key", "objtypes"),
            new GamevalEntry(2379, "ROCK_CAKE", "Rock cake", "objtypes"),
            new GamevalEntry(2380, "CRYSTAL", "Crystal", "objtypes"),
            new GamevalEntry(2381, "CRYSTAL_2381", "Crystal", "objtypes"),
            new GamevalEntry(2382, "CRYSTAL_2382", "Crystal", "objtypes"),
            new GamevalEntry(2383, "CRYSTAL_2383", "Crystal", "objtypes"),
            new GamevalEntry(2384, "FINGERNAILS", "Fingernails", "objtypes"),
            new GamevalEntry(2385, "K_OLD_ROBE", "K Old robe", "objtypes"),
            new GamevalEntry(2386, "UNUSUAL_ARMOUR", "Unusual armour", "objtypes"),
            new GamevalEntry(2387, "DAMAGED_DAGGER", "Damaged dagger", "objtypes"),
            new GamevalEntry(2388, "TATTERED_EYE_PATCH", "Tattered eye patch", "objtypes"),
            new GamevalEntry(2389, "VIAL", "Vial", "objtypes"),
            new GamevalEntry(2390, "VIAL_2390", "Vial", "objtypes"),
            new GamevalEntry(2391, "GROUND_BAT_BONES", "Ground bat bones", "objtypes"),
            new GamevalEntry(2392, "ID_2392", "", "objtypes"),
            new GamevalEntry(2393, "TOBAN_S_GOLD", "Toban's gold", "objtypes"),
            new GamevalEntry(2394, "POTION_2394", "Potion", "objtypes"),
            new GamevalEntry(2395, "MAGIC_OGRE_POTION", "Magic ogre potion", "objtypes"),
            new GamevalEntry(2396, "SPELL_SCROLL", "Spell scroll", "objtypes"),
            new GamevalEntry(2397, "SHAMAN_ROBE", "Shaman robe", "objtypes"),
            new GamevalEntry(2398, "CAVE_NIGHTSHADE", "Cave nightshade", "objtypes"),
            new GamevalEntry(2399, "SILVERLIGHT_KEY", "Silverlight key", "objtypes"),
            new GamevalEntry(2400, "SILVERLIGHT_KEY_2400", "Silverlight key", "objtypes"),
            new GamevalEntry(2401, "SILVERLIGHT_KEY_2401", "Silverlight key", "objtypes"),
            new GamevalEntry(2402, "SILVERLIGHT", "Silverlight", "objtypes"),
            new GamevalEntry(2403, "HAZEEL_SCROLL", "Hazeel scroll", "objtypes"),
            new GamevalEntry(2404, "CHEST_KEY_2404", "Chest key", "objtypes"),
            new GamevalEntry(2405, "CARNILLEAN_ARMOUR", "Carnillean armour", "objtypes"),
            new GamevalEntry(2406, "HAZEEL_S_MARK", "Hazeel's mark", "objtypes"),
            new GamevalEntry(2407, "BALL", "Ball", "objtypes"),
            new GamevalEntry(2408, "DIARY", "Diary", "objtypes"),
            new GamevalEntry(2409, "DOOR_KEY", "Door key", "objtypes"),
            new GamevalEntry(2410, "MAGNET", "Magnet", "objtypes"),
            new GamevalEntry(2411, "KEY_2411", "Key", "objtypes"),
            new GamevalEntry(2412, "SARADOMIN_CAPE", "Saradomin cape", "objtypes"),
            new GamevalEntry(2413, "GUTHIX_CAPE", "Guthix cape", "objtypes"),
            new GamevalEntry(2414, "ZAMORAK_CAPE", "Zamorak cape", "objtypes"),
            new GamevalEntry(2415, "SARADOMIN_STAFF", "Saradomin staff", "objtypes"),
            new GamevalEntry(2416, "GUTHIX_STAFF", "Guthix staff", "objtypes"),
            new GamevalEntry(2417, "ZAMORAK_STAFF", "Zamorak staff", "objtypes"),
            new GamevalEntry(2418, "BRONZE_KEY", "Bronze key", "objtypes"),
            new GamevalEntry(2419, "WIG", "Wig", "objtypes"),
            new GamevalEntry(2420, "ID_2420", "", "objtypes"),
            new GamevalEntry(2421, "WIG_2421", "Wig", "objtypes"),
            new GamevalEntry(2422, "BLUE_PARTYHAT_2422", "Blue partyhat", "objtypes"),
            new GamevalEntry(2423, "KEY_PRINT", "Key print", "objtypes"),
            new GamevalEntry(2424, "PASTE", "Paste", "objtypes"),
            new GamevalEntry(2425, "VORKATH_S_HEAD", "Vorkath's head", "objtypes"),
            new GamevalEntry(2426, "BURNT_OOMLIE", "Burnt oomlie", "objtypes"),
            new GamevalEntry(2427, "ID_2427", "", "objtypes"),
            new GamevalEntry(2428, "ATTACK_POTION_4", "Attack potion(4)", "objtypes"),
            new GamevalEntry(2429, "ID_2429", "", "objtypes"),
            new GamevalEntry(2430, "RESTORE_POTION_4", "Restore potion(4)", "objtypes"),
            new GamevalEntry(2431, "ID_2431", "", "objtypes"),
            new GamevalEntry(2432, "DEFENCE_POTION_4", "Defence potion(4)", "objtypes"),
            new GamevalEntry(2433, "ID_2433", "", "objtypes"),
            new GamevalEntry(2434, "PRAYER_POTION_4", "Prayer potion(4)", "objtypes"),
            new GamevalEntry(2435, "ID_2435", "", "objtypes"),
            new GamevalEntry(2436, "SUPER_ATTACK_4", "Super attack(4)", "objtypes"),
            new GamevalEntry(2437, "ID_2437", "", "objtypes"),
            new GamevalEntry(2438, "FISHING_POTION_4", "Fishing potion(4)", "objtypes"),
            new GamevalEntry(2439, "ID_2439", "", "objtypes"),
            new GamevalEntry(2440, "SUPER_STRENGTH_4", "Super strength(4)", "objtypes"),
            new GamevalEntry(2441, "ID_2441", "", "objtypes"),
            new GamevalEntry(2442, "SUPER_DEFENCE_4", "Super defence(4)", "objtypes"),
            new GamevalEntry(2443, "ID_2443", "", "objtypes"),
            new GamevalEntry(2444, "RANGING_POTION_4", "Ranging potion(4)", "objtypes"),
            new GamevalEntry(2445, "ID_2445", "", "objtypes"),
            new GamevalEntry(2446, "ANTIPOISON_4", "Antipoison(4)", "objtypes"),
            new GamevalEntry(2447, "ID_2447", "", "objtypes"),
            new GamevalEntry(2448, "SUPERANTIPOISON_4", "Superantipoison(4)", "objtypes"),
            new GamevalEntry(2449, "ID_2449", "", "objtypes"),
            new GamevalEntry(2450, "ZAMORAK_BREW_4", "Zamorak brew(4)", "objtypes"),
            new GamevalEntry(2451, "ID_2451", "", "objtypes"),
            new GamevalEntry(2452, "ANTIFIRE_POTION_4", "Antifire potion(4)", "objtypes"),
            new GamevalEntry(2453, "ID_2453", "", "objtypes"),
            new GamevalEntry(2454, "ANTIFIRE_POTION_3", "Antifire potion(3)", "objtypes"),
            new GamevalEntry(2455, "ID_2455", "", "objtypes"),
            new GamevalEntry(2456, "ANTIFIRE_POTION_2", "Antifire potion(2)", "objtypes"),
            new GamevalEntry(2457, "ID_2457", "", "objtypes"),
            new GamevalEntry(2458, "ANTIFIRE_POTION_1", "Antifire potion(1)", "objtypes"),
            new GamevalEntry(2459, "ID_2459", "", "objtypes"),
            new GamevalEntry(2460, "D_A_ASSORTED_FLOWERS", "d A Assorted flowers", "objtypes"),
            new GamevalEntry(2461, "ID_2461", "", "objtypes"),
            new GamevalEntry(2462, "RED_FLOWERS", "Red flowers", "objtypes"),
            new GamevalEntry(2463, "ID_2463", "", "objtypes"),
            new GamevalEntry(2464, "BLUE_FLOWERS", "Blue flowers", "objtypes"),
            new GamevalEntry(2465, "ID_2465", "", "objtypes"),
            new GamevalEntry(2466, "YELLOW_FLOWERS", "Yellow flowers", "objtypes"),
            new GamevalEntry(2467, "ID_2467", "", "objtypes"),
            new GamevalEntry(2468, "PURPLE_FLOWERS", "Purple flowers", "objtypes"),
            new GamevalEntry(2469, "ID_2469", "", "objtypes"),
            new GamevalEntry(2470, "ORANGE_FLOWERS", "Orange flowers", "objtypes"),
            new GamevalEntry(2471, "ID_2471", "", "objtypes"),
            new GamevalEntry(2472, "MIXED_FLOWERS", "Mixed flowers", "objtypes"),
            new GamevalEntry(2473, "ID_2473", "", "objtypes"),
            new GamevalEntry(2474, "WHITE_FLOWERS", "White flowers", "objtypes"),
            new GamevalEntry(2475, "ID_2475", "", "objtypes"),
            new GamevalEntry(2476, "BLACK_FLOWERS", "Black flowers", "objtypes"),
            new GamevalEntry(2477, "ID_2477", "", "objtypes"),
            new GamevalEntry(2478, "ID_2478", "", "objtypes"),
            new GamevalEntry(2479, "ID_2479", "", "objtypes"),
            new GamevalEntry(2480, "ID_2480", "", "objtypes"),
            new GamevalEntry(2481, "LANTADYME", "Lantadyme", "objtypes"),
            new GamevalEntry(2482, "ID_2482", "", "objtypes"),
            new GamevalEntry(2483, "LANTADYME_POTION_UNF", "Lantadyme potion (unf)", "objtypes"),
            new GamevalEntry(2484, "ID_2484", "", "objtypes"),
            new GamevalEntry(2485, "GRIMY_LANTADYME", "Grimy lantadyme", "objtypes"),
            new GamevalEntry(2486, "ID_2486", "", "objtypes"),
            new GamevalEntry(2487, "BLUE_D_HIDE_VAMBRACES", "Blue d'hide vambraces", "objtypes"),
            new GamevalEntry(2488, "ID_2488", "", "objtypes"),
            new GamevalEntry(2489, "RED_D_HIDE_VAMBRACES", "Red d'hide vambraces", "objtypes"),
            new GamevalEntry(2490, "ID_2490", "", "objtypes"),
            new GamevalEntry(2491, "BLACK_D_HIDE_VAMBRACES", "Black d'hide vambraces", "objtypes"),
            new GamevalEntry(2492, "ID_2492", "", "objtypes"),
            new GamevalEntry(2493, "BLUE_D_HIDE_CHAPS", "Blue d'hide chaps", "objtypes"),
            new GamevalEntry(2494, "ID_2494", "", "objtypes"),
            new GamevalEntry(2495, "RED_D_HIDE_CHAPS", "Red d'hide chaps", "objtypes"),
            new GamevalEntry(2496, "ID_2496", "", "objtypes"),
            new GamevalEntry(2497, "BLACK_D_HIDE_CHAPS", "Black d'hide chaps", "objtypes"),
            new GamevalEntry(2498, "ID_2498", "", "objtypes"),
            new GamevalEntry(2499, "BLUE_D_HIDE_BODY", "Blue d'hide body", "objtypes"),
            new GamevalEntry(2500, "ID_2500", "", "objtypes"),
            new GamevalEntry(2501, "RED_D_HIDE_BODY", "Red d'hide body", "objtypes"),
            new GamevalEntry(2502, "ID_2502", "", "objtypes"),
            new GamevalEntry(2503, "BLACK_D_HIDE_BODY", "Black d'hide body", "objtypes"),
            new GamevalEntry(2504, "ID_2504", "", "objtypes"),
            new GamevalEntry(2505, "BLUE_DRAGON_LEATHER", "Blue dragon leather", "objtypes"),
            new GamevalEntry(2506, "ID_2506", "", "objtypes"),
            new GamevalEntry(2507, "RED_DRAGON_LEATHER", "Red dragon leather", "objtypes"),
            new GamevalEntry(2508, "ID_2508", "", "objtypes"),
            new GamevalEntry(2509, "BLACK_DRAGON_LEATHER", "Black dragon leather", "objtypes"),
            new GamevalEntry(2510, "ID_2510", "", "objtypes"),
            new GamevalEntry(2511, "LOGS_2511", "Logs", "objtypes"),
            new GamevalEntry(2512, "ID_2512", "", "objtypes"),
            new GamevalEntry(2513, "DRAGON_CHAINBODY", "Dragon chainbody", "objtypes"),
            new GamevalEntry(2514, "RAW_SHRIMPS_2514", "Raw shrimps", "objtypes"),
            new GamevalEntry(2515, "ID_2515", "", "objtypes"),
            new GamevalEntry(2516, "POT_OF_FLOUR_2516", "Pot of flour", "objtypes"),
            new GamevalEntry(2517, "ID_2517", "", "objtypes"),
            new GamevalEntry(2518, "ROTTEN_TOMATO", "Rotten tomato", "objtypes"),
            new GamevalEntry(2519, "ID_2519", "", "objtypes"),
            new GamevalEntry(2520, "BROWN_TOY_HORSEY", "Brown toy horsey", "objtypes"),
            new GamevalEntry(2521, "ID_2521", "", "objtypes"),
            new GamevalEntry(2522, "WHITE_TOY_HORSEY", "White toy horsey", "objtypes"),
            new GamevalEntry(2523, "ID_2523", "", "objtypes"),
            new GamevalEntry(2524, "BLACK_TOY_HORSEY", "Black toy horsey", "objtypes"),
            new GamevalEntry(2525, "ID_2525", "", "objtypes"),
            new GamevalEntry(2526, "GREY_TOY_HORSEY", "Grey toy horsey", "objtypes"),
            new GamevalEntry(2527, "ID_2527", "", "objtypes"),
            new GamevalEntry(2528, "LAMP", "Lamp", "objtypes"),
            new GamevalEntry(2529, "DEAD_ORB", "Dead orb", "objtypes"),
            new GamevalEntry(2530, "BONES_2530", "Bones", "objtypes"),
            new GamevalEntry(2531, "ID_2531", "", "objtypes"),
            new GamevalEntry(2532, "IRON_FIRE_ARROW", "Iron fire arrow", "objtypes"),
            new GamevalEntry(2533, "IRON_FIRE_ARROW_LIT", "Iron fire arrow (lit)", "objtypes"),
            new GamevalEntry(2534, "STEEL_FIRE_ARROW", "Steel fire arrow", "objtypes"),
            new GamevalEntry(2535, "STEEL_FIRE_ARROW_LIT", "Steel fire arrow (lit)", "objtypes"),
            new GamevalEntry(2536, "MITHRIL_FIRE_ARROW", "Mithril fire arrow", "objtypes"),
            new GamevalEntry(2537, "MITHRIL_FIRE_ARROW_LIT", "Mithril fire arrow (lit)", "objtypes"),
            new GamevalEntry(2538, "ADAMANT_FIRE_ARROW", "Adamant fire arrow", "objtypes"),
            new GamevalEntry(2539, "ADAMANT_FIRE_ARROW_LIT", "Adamant fire arrow (lit)", "objtypes"),
            new GamevalEntry(2540, "RUNE_FIRE_ARROW", "Rune fire arrow", "objtypes"),
            new GamevalEntry(2541, "RUNE_FIRE_ARROW_LIT", "Rune fire arrow (lit)", "objtypes"),
            new GamevalEntry(2542, "ID_2542", "", "objtypes"),
            new GamevalEntry(2543, "ID_2543_8", "8", "objtypes"),
            new GamevalEntry(2544, "ID_2544", "", "objtypes"),
            new GamevalEntry(2545, "ID_2545", "", "objtypes"),
            new GamevalEntry(2546, "ID_2546", "", "objtypes"),
            new GamevalEntry(2547, "ID_2547", "", "objtypes"),
            new GamevalEntry(2548, "ID_2548", "", "objtypes"),
            new GamevalEntry(2549, "ID_2549", "", "objtypes"),
            new GamevalEntry(2550, "RING_OF_RECOIL", "Ring of recoil", "objtypes"),
            new GamevalEntry(2551, "ID_2551", "", "objtypes"),
            new GamevalEntry(2552, "RING_OF_DUELING_8", "Ring of dueling(8)", "objtypes"),
            new GamevalEntry(2553, "ID_2553", "", "objtypes"),
            new GamevalEntry(2554, "RING_OF_DUELING_7", "Ring of dueling(7)", "objtypes"),
            new GamevalEntry(2555, "ID_2555", "", "objtypes"),
            new GamevalEntry(2556, "RING_OF_DUELING_6", "Ring of dueling(6)", "objtypes"),
            new GamevalEntry(2557, "ID_2557", "", "objtypes"),
            new GamevalEntry(2558, "RING_OF_DUELING_5", "Ring of dueling(5)", "objtypes"),
            new GamevalEntry(2559, "ID_2559", "", "objtypes"),
        };
    }

    static Optional<GamevalEntry> byId(int id) {
        for (GamevalEntry entry : entries()) {
            if (entry.id() == id) return Optional.of(entry);
        }
        return Optional.empty();
    }

}
