package net.titan.gamevals.internal;

import java.util.Optional;

import net.titan.gamevals.GamevalEntry;
import net.titan.gamevals.QuestEntry;

final class NpcIDEntries_18 {
    private NpcIDEntries_18() {}

    static GamevalEntry[] entries() {
        return new GamevalEntry[] {
            new GamevalEntry(9216, "ID_9216", "", "npctypes"),
            new GamevalEntry(9217, "ID_9217", "", "npctypes"),
            new GamevalEntry(9218, "ID_9218", "", "npctypes"),
            new GamevalEntry(9219, "ID_9219", "", "npctypes"),
            new GamevalEntry(9220, "ID_9220", "", "npctypes"),
            new GamevalEntry(9221, "ID_9221_3_4_5_6_ZJ", "3 4 5 6 ZJ", "npctypes"),
            new GamevalEntry(9222, "ID_9222", "", "npctypes"),
            new GamevalEntry(9223, "ID_9223", "", "npctypes"),
            new GamevalEntry(9224, "ID_9224", "", "npctypes"),
            new GamevalEntry(9225, "ID_9225", "", "npctypes"),
            new GamevalEntry(9226, "ID_9226", "", "npctypes"),
            new GamevalEntry(9227, "ID_9227", "", "npctypes"),
            new GamevalEntry(9228, "ID_9228", "", "npctypes"),
            new GamevalEntry(9229, "ID_9229", "", "npctypes"),
            new GamevalEntry(9230, "ID_9230", "", "npctypes"),
            new GamevalEntry(9231, "ID_9231", "", "npctypes"),
            new GamevalEntry(9232, "ID_9232", "", "npctypes"),
            new GamevalEntry(9233, "ID_9233", "", "npctypes"),
            new GamevalEntry(9234, "ID_9234", "", "npctypes"),
            new GamevalEntry(9235, "ID_9235", "", "npctypes"),
            new GamevalEntry(9236, "ID_9236", "", "npctypes"),
            new GamevalEntry(9237, "ID_9237", "", "npctypes"),
            new GamevalEntry(9238, "ID_9238", "", "npctypes"),
            new GamevalEntry(9239, "ID_9239", "", "npctypes"),
            new GamevalEntry(9240, "ID_9240", "", "npctypes"),
            new GamevalEntry(9241, "ID_9241", "", "npctypes"),
            new GamevalEntry(9242, "ID_9242", "", "npctypes"),
            new GamevalEntry(9243, "ID_9243", "", "npctypes"),
            new GamevalEntry(9244, "ADVENTURER_JON_9244", "Adventurer Jon", "npctypes"),
            new GamevalEntry(9245, "ID_9245", "", "npctypes"),
            new GamevalEntry(9246, "ARIANWYN_HARD", "Arianwyn (hard)", "npctypes"),
            new GamevalEntry(9247, "ESSYLLT_HARD", "Essyllt (hard)", "npctypes"),
            new GamevalEntry(9248, "ARIANWYN_9248", "Arianwyn", "npctypes"),
            new GamevalEntry(9249, "ESSYLLT_9249", "Essyllt", "npctypes"),
            new GamevalEntry(9250, "CAPTAIN_BARNABY_9250", "Captain Barnaby", "npctypes"),
            new GamevalEntry(9251, "TOY_SOLDIER_9251", "Toy Soldier", "npctypes"),
            new GamevalEntry(9252, "TOY_DOLL", "Toy Doll", "npctypes"),
            new GamevalEntry(9253, "TOY_DOLL_9253", "Toy Doll", "npctypes"),
            new GamevalEntry(9254, "TOY_MOUSE", "Toy Mouse", "npctypes"),
            new GamevalEntry(9255, "TOY_MOUSE_9255", "Toy Mouse", "npctypes"),
            new GamevalEntry(9256, "ID_9256", "", "npctypes"),
            new GamevalEntry(9257, "PENGUIN_SUIT_9257", "Penguin suit", "npctypes"),
            new GamevalEntry(9258, "BASILISK_SENTINEL", "Basilisk Sentinel", "npctypes"),
            new GamevalEntry(9259, "OSPAK_9259", "Ospak", "npctypes"),
            new GamevalEntry(9260, "STYRMIR_9260", "Styrmir", "npctypes"),
            new GamevalEntry(9261, "TORBRUND_9261", "Torbrund", "npctypes"),
            new GamevalEntry(9262, "FRIDGEIR_9262", "Fridgeir", "npctypes"),
            new GamevalEntry(9263, "BRUNDT_THE_CHIEFTAIN_9263", "Brundt the Chieftain", "npctypes"),
            new GamevalEntry(9264, "THORA_THE_BARKEEP_9264", "Thora the Barkeep", "npctypes"),
            new GamevalEntry(9265, "BRUNDT_THE_CHIEFTAIN_9265", "Brundt the Chieftain", "npctypes"),
            new GamevalEntry(9266, "BRUNDT_THE_CHIEFTAIN_9266", "Brundt the Chieftain", "npctypes"),
            new GamevalEntry(9267, "BRUNDT_THE_CHIEFTAIN_9267", "Brundt the Chieftain", "npctypes"),
            new GamevalEntry(9268, "BRUNDT_THE_CHIEFTAIN_9268", "Brundt the Chieftain", "npctypes"),
            new GamevalEntry(9269, "ID_9269", "", "npctypes"),
            new GamevalEntry(9270, "HASKELL", "Haskell", "npctypes"),
            new GamevalEntry(9271, "HASKELL_9271", "Haskell", "npctypes"),
            new GamevalEntry(9272, "HASKELL_9272", "Haskell", "npctypes"),
            new GamevalEntry(9273, "AGNAR_9273", "Agnar", "npctypes"),
            new GamevalEntry(9274, "OLAF_THE_BARD_9274", "Olaf the Bard", "npctypes"),
            new GamevalEntry(9275, "MANNI_THE_REVELLER_9275", "Manni the Reveller", "npctypes"),
            new GamevalEntry(9276, "FREMENNIK_WARRIOR", "Fremennik Warrior", "npctypes"),
            new GamevalEntry(9277, "FREMENNIK_WARRIOR_9277", "Fremennik Warrior", "npctypes"),
            new GamevalEntry(9278, "BRUNDT_THE_CHIEFTAIN_9278", "Brundt the Chieftain", "npctypes"),
            new GamevalEntry(9279, "BRUNDT_THE_CHIEFTAIN_9279", "Brundt the Chieftain", "npctypes"),
            new GamevalEntry(9280, "THORVALD_THE_WARRIOR_9280", "Thorvald the Warrior", "npctypes"),
            new GamevalEntry(9281, "KOSCHEI_THE_DEATHLESS_9281", "Koschei the Deathless", "npctypes"),
            new GamevalEntry(9282, "BASILISK_YOUNGLING", "Basilisk Youngling", "npctypes"),
            new GamevalEntry(9283, "BASILISK_9283", "Basilisk", "npctypes"),
            new GamevalEntry(9284, "BASILISK_9284", "Basilisk", "npctypes"),
            new GamevalEntry(9285, "BASILISK_9285", "Basilisk", "npctypes"),
            new GamevalEntry(9286, "BASILISK_9286", "Basilisk", "npctypes"),
            new GamevalEntry(9287, "MONSTROUS_BASILISK_9287", "Monstrous Basilisk", "npctypes"),
            new GamevalEntry(9288, "MONSTROUS_BASILISK_9288", "Monstrous Basilisk", "npctypes"),
            new GamevalEntry(9289, "THE_JORMUNGAND", "The Jormungand", "npctypes"),
            new GamevalEntry(9290, "THE_JORMUNGAND_9290", "The Jormungand", "npctypes"),
            new GamevalEntry(9291, "THE_JORMUNGAND_9291", "The Jormungand", "npctypes"),
            new GamevalEntry(9292, "THE_JORMUNGAND_9292", "The Jormungand", "npctypes"),
            new GamevalEntry(9293, "BASILISK_KNIGHT", "Basilisk Knight", "npctypes"),
            new GamevalEntry(9294, "BAKUNA", "Bakuna", "npctypes"),
            new GamevalEntry(9295, "TYPHOR", "Typhor", "npctypes"),
            new GamevalEntry(9296, "TYPHOR_9296", "Typhor", "npctypes"),
            new GamevalEntry(9297, "VRITRA", "Vritra", "npctypes"),
            new GamevalEntry(9298, "MAZ", "Maz", "npctypes"),
            new GamevalEntry(9299, "TRADER_STAN", "Trader Stan", "npctypes"),
            new GamevalEntry(9300, "TRADER_STAN_9300", "Trader Stan", "npctypes"),
            new GamevalEntry(9301, "TRADER_STAN_9301", "Trader Stan", "npctypes"),
            new GamevalEntry(9302, "TRADER_STAN_9302", "Trader Stan", "npctypes"),
            new GamevalEntry(9303, "TRADER_STAN_9303", "Trader Stan", "npctypes"),
            new GamevalEntry(9304, "TRADER_STAN_9304", "Trader Stan", "npctypes"),
            new GamevalEntry(9305, "TRADER_STAN_9305", "Trader Stan", "npctypes"),
            new GamevalEntry(9306, "LOKAR_SEARUNNER_9306", "Lokar Searunner", "npctypes"),
            new GamevalEntry(9307, "TRADER_STAN_9307", "Trader Stan", "npctypes"),
            new GamevalEntry(9308, "TRADER_STAN_9308", "Trader Stan", "npctypes"),
            new GamevalEntry(9309, "TRADER_STAN_9309", "Trader Stan", "npctypes"),
            new GamevalEntry(9310, "TRADER_STAN_9310", "Trader Stan", "npctypes"),
            new GamevalEntry(9311, "TRADER_STAN_9311", "Trader Stan", "npctypes"),
            new GamevalEntry(9312, "TRADER_CREWMEMBER", "Trader Crewmember", "npctypes"),
            new GamevalEntry(9313, "TRADER_CREWMEMBER_9313", "Trader Crewmember", "npctypes"),
            new GamevalEntry(9314, "TRADER_CREWMEMBER_9314", "Trader Crewmember", "npctypes"),
            new GamevalEntry(9315, "TRADER_CREWMEMBER_9315", "Trader Crewmember", "npctypes"),
            new GamevalEntry(9316, "TRADER_CREWMEMBER_9316", "Trader Crewmember", "npctypes"),
            new GamevalEntry(9317, "TRADER_CREWMEMBER_9317", "Trader Crewmember", "npctypes"),
            new GamevalEntry(9318, "TRADER_CREWMEMBER_9318", "Trader Crewmember", "npctypes"),
            new GamevalEntry(9319, "TRADER_CREWMEMBER_9319", "Trader Crewmember", "npctypes"),
            new GamevalEntry(9320, "TRADER_CREWMEMBER_9320", "Trader Crewmember", "npctypes"),
            new GamevalEntry(9321, "TRADER_CREWMEMBER_9321", "Trader Crewmember", "npctypes"),
            new GamevalEntry(9322, "TRADER_CREWMEMBER_9322", "Trader Crewmember", "npctypes"),
            new GamevalEntry(9323, "TRADER_CREWMEMBER_9323", "Trader Crewmember", "npctypes"),
            new GamevalEntry(9324, "TRADER_CREWMEMBER_9324", "Trader Crewmember", "npctypes"),
            new GamevalEntry(9325, "TRADER_CREWMEMBER_9325", "Trader Crewmember", "npctypes"),
            new GamevalEntry(9326, "TRADER_CREWMEMBER_9326", "Trader Crewmember", "npctypes"),
            new GamevalEntry(9327, "TRADER_CREWMEMBER_9327", "Trader Crewmember", "npctypes"),
            new GamevalEntry(9328, "TRADER_CREWMEMBER_9328", "Trader Crewmember", "npctypes"),
            new GamevalEntry(9329, "TRADER_CREWMEMBER_9329", "Trader Crewmember", "npctypes"),
            new GamevalEntry(9330, "TRADER_CREWMEMBER_9330", "Trader Crewmember", "npctypes"),
            new GamevalEntry(9331, "TRADER_CREWMEMBER_9331", "Trader Crewmember", "npctypes"),
            new GamevalEntry(9332, "TRADER_CREWMEMBER_9332", "Trader Crewmember", "npctypes"),
            new GamevalEntry(9333, "TRADER_CREWMEMBER_9333", "Trader Crewmember", "npctypes"),
            new GamevalEntry(9334, "TRADER_CREWMEMBER_9334", "Trader Crewmember", "npctypes"),
            new GamevalEntry(9335, "TRADER_CREWMEMBER_9335", "Trader Crewmember", "npctypes"),
            new GamevalEntry(9336, "TRADER_CREWMEMBER_9336", "Trader Crewmember", "npctypes"),
            new GamevalEntry(9337, "TRADER_CREWMEMBER_9337", "Trader Crewmember", "npctypes"),
            new GamevalEntry(9338, "TRADER_CREWMEMBER_9338", "Trader Crewmember", "npctypes"),
            new GamevalEntry(9339, "TRADER_CREWMEMBER_9339", "Trader Crewmember", "npctypes"),
            new GamevalEntry(9340, "TRADER_CREWMEMBER_9340", "Trader Crewmember", "npctypes"),
            new GamevalEntry(9341, "TRADER_CREWMEMBER_9341", "Trader Crewmember", "npctypes"),
            new GamevalEntry(9342, "TRADER_CREWMEMBER_9342", "Trader Crewmember", "npctypes"),
            new GamevalEntry(9343, "TRADER_CREWMEMBER_9343", "Trader Crewmember", "npctypes"),
            new GamevalEntry(9344, "TRADER_CREWMEMBER_9344", "Trader Crewmember", "npctypes"),
            new GamevalEntry(9345, "TRADER_CREWMEMBER_9345", "Trader Crewmember", "npctypes"),
            new GamevalEntry(9346, "TRADER_CREWMEMBER_9346", "Trader Crewmember", "npctypes"),
            new GamevalEntry(9347, "TRADER_CREWMEMBER_9347", "Trader Crewmember", "npctypes"),
            new GamevalEntry(9348, "TRADER_CREWMEMBER_9348", "Trader Crewmember", "npctypes"),
            new GamevalEntry(9349, "TRADER_CREWMEMBER_9349", "Trader Crewmember", "npctypes"),
            new GamevalEntry(9350, "TRADER_CREWMEMBER_9350", "Trader Crewmember", "npctypes"),
            new GamevalEntry(9351, "TRADER_CREWMEMBER_9351", "Trader Crewmember", "npctypes"),
            new GamevalEntry(9352, "TRADER_CREWMEMBER_9352", "Trader Crewmember", "npctypes"),
            new GamevalEntry(9353, "TRADER_CREWMEMBER_9353", "Trader Crewmember", "npctypes"),
            new GamevalEntry(9354, "TRADER_CREWMEMBER_9354", "Trader Crewmember", "npctypes"),
            new GamevalEntry(9355, "TRADER_CREWMEMBER_9355", "Trader Crewmember", "npctypes"),
            new GamevalEntry(9356, "TRADER_CREWMEMBER_9356", "Trader Crewmember", "npctypes"),
            new GamevalEntry(9357, "TRADER_CREWMEMBER_9357", "Trader Crewmember", "npctypes"),
            new GamevalEntry(9358, "TRADER_CREWMEMBER_9358", "Trader Crewmember", "npctypes"),
            new GamevalEntry(9359, "TRADER_CREWMEMBER_9359", "Trader Crewmember", "npctypes"),
            new GamevalEntry(9360, "TRADER_CREWMEMBER_9360", "Trader Crewmember", "npctypes"),
            new GamevalEntry(9361, "TRADER_CREWMEMBER_9361", "Trader Crewmember", "npctypes"),
            new GamevalEntry(9362, "TRADER_CREWMEMBER_9362", "Trader Crewmember", "npctypes"),
            new GamevalEntry(9363, "TRADER_CREWMEMBER_9363", "Trader Crewmember", "npctypes"),
            new GamevalEntry(9364, "TRADER_CREWMEMBER_9364", "Trader Crewmember", "npctypes"),
            new GamevalEntry(9365, "TRADER_CREWMEMBER_9365", "Trader Crewmember", "npctypes"),
            new GamevalEntry(9366, "TRADER_CREWMEMBER_9366", "Trader Crewmember", "npctypes"),
            new GamevalEntry(9367, "TRADER_CREWMEMBER_9367", "Trader Crewmember", "npctypes"),
            new GamevalEntry(9368, "TRADER_CREWMEMBER_9368", "Trader Crewmember", "npctypes"),
            new GamevalEntry(9369, "TRADER_CREWMEMBER_9369", "Trader Crewmember", "npctypes"),
            new GamevalEntry(9370, "TRADER_CREWMEMBER_9370", "Trader Crewmember", "npctypes"),
            new GamevalEntry(9371, "TRADER_CREWMEMBER_9371", "Trader Crewmember", "npctypes"),
            new GamevalEntry(9372, "TRADER_CREWMEMBER_9372", "Trader Crewmember", "npctypes"),
            new GamevalEntry(9373, "TRADER_CREWMEMBER_9373", "Trader Crewmember", "npctypes"),
            new GamevalEntry(9374, "TRADER_CREWMEMBER_9374", "Trader Crewmember", "npctypes"),
            new GamevalEntry(9375, "TRADER_CREWMEMBER_9375", "Trader Crewmember", "npctypes"),
            new GamevalEntry(9376, "TRADER_CREWMEMBER_9376", "Trader Crewmember", "npctypes"),
            new GamevalEntry(9377, "TRADER_CREWMEMBER_9377", "Trader Crewmember", "npctypes"),
            new GamevalEntry(9378, "TRADER_CREWMEMBER_9378", "Trader Crewmember", "npctypes"),
            new GamevalEntry(9379, "TRADER_CREWMEMBER_9379", "Trader Crewmember", "npctypes"),
            new GamevalEntry(9380, "TRADER_CREWMEMBER_9380", "Trader Crewmember", "npctypes"),
            new GamevalEntry(9381, "TRADER_CREWMEMBER_9381", "Trader Crewmember", "npctypes"),
            new GamevalEntry(9382, "TRADER_CREWMEMBER_9382", "Trader Crewmember", "npctypes"),
            new GamevalEntry(9383, "TRADER_CREWMEMBER_9383", "Trader Crewmember", "npctypes"),
            new GamevalEntry(9384, "ID_9384", "", "npctypes"),
            new GamevalEntry(9385, "ID_9385", "", "npctypes"),
            new GamevalEntry(9386, "ID_9386", "", "npctypes"),
            new GamevalEntry(9387, "ID_9387", "", "npctypes"),
            new GamevalEntry(9388, "ID_9388", "", "npctypes"),
            new GamevalEntry(9389, "ID_9389", "", "npctypes"),
            new GamevalEntry(9390, "ID_9390", "", "npctypes"),
            new GamevalEntry(9391, "ID_9391", "", "npctypes"),
            new GamevalEntry(9392, "ID_9392", "", "npctypes"),
            new GamevalEntry(9393, "ID_9393", "", "npctypes"),
            new GamevalEntry(9394, "ID_9394", "", "npctypes"),
            new GamevalEntry(9395, "ID_9395", "", "npctypes"),
            new GamevalEntry(9396, "ID_9396", "", "npctypes"),
            new GamevalEntry(9397, "ID_9397", "", "npctypes"),
            new GamevalEntry(9398, "LITTLE_NIGHTMARE", "Little Nightmare", "npctypes"),
            new GamevalEntry(9399, "LITTLE_NIGHTMARE_9399", "Little Nightmare", "npctypes"),
            new GamevalEntry(9400, "OATH_LORD_D_ROWS", "Oath Lord D'rows", "npctypes"),
            new GamevalEntry(9401, "OATHBREAKER_M_ALS", "Oathbreaker M'als", "npctypes"),
            new GamevalEntry(9402, "OATHBREAKER_E_PIWS", "Oathbreaker E'piws", "npctypes"),
            new GamevalEntry(9403, "OATHBREAKER_B_ATS", "Oathbreaker B'ats", "npctypes"),
            new GamevalEntry(9404, "LITHIL", "Lithil", "npctypes"),
            new GamevalEntry(9405, "SISTER_ASERET", "Sister Aseret", "npctypes"),
            new GamevalEntry(9406, "SISTER_NAOJ", "Sister Naoj", "npctypes"),
            new GamevalEntry(9407, "SISTER_SALOHCIN", "Sister Salohcin", "npctypes"),
            new GamevalEntry(9408, "LUMIERE", "Lumiere", "npctypes"),
            new GamevalEntry(9409, "DAER_KRAND", "Daer Krand", "npctypes"),
            new GamevalEntry(9410, "STRONG_RONNY", "Strong Ronny", "npctypes"),
            new GamevalEntry(9411, "ID_9411", "", "npctypes"),
            new GamevalEntry(9412, "ID_9412", "", "npctypes"),
            new GamevalEntry(9413, "SHURA", "Shura", "npctypes"),
            new GamevalEntry(9414, "SHURA_9414", "Shura", "npctypes"),
            new GamevalEntry(9415, "ACORN", "Acorn", "npctypes"),
            new GamevalEntry(9416, "PHOSANI_S_NIGHTMARE_9416", "Phosani's Nightmare", "npctypes"),
            new GamevalEntry(9417, "PHOSANI_S_NIGHTMARE_9417", "Phosani's Nightmare", "npctypes"),
            new GamevalEntry(9418, "PHOSANI_S_NIGHTMARE_9418", "Phosani's Nightmare", "npctypes"),
            new GamevalEntry(9419, "PHOSANI_S_NIGHTMARE_9419", "Phosani's Nightmare", "npctypes"),
            new GamevalEntry(9420, "PHOSANI_S_NIGHTMARE_9420", "Phosani's Nightmare", "npctypes"),
            new GamevalEntry(9421, "PHOSANI_S_NIGHTMARE_9421", "Phosani's Nightmare", "npctypes"),
            new GamevalEntry(9422, "PHOSANI_S_NIGHTMARE_9422", "Phosani's Nightmare", "npctypes"),
            new GamevalEntry(9423, "PHOSANI_S_NIGHTMARE_9423", "Phosani's Nightmare", "npctypes"),
            new GamevalEntry(9424, "PHOSANI_S_NIGHTMARE_9424", "Phosani's Nightmare", "npctypes"),
            new GamevalEntry(9425, "THE_NIGHTMARE_9425", "The Nightmare", "npctypes"),
            new GamevalEntry(9426, "THE_NIGHTMARE_9426", "The Nightmare", "npctypes"),
            new GamevalEntry(9427, "THE_NIGHTMARE_9427", "The Nightmare", "npctypes"),
            new GamevalEntry(9428, "THE_NIGHTMARE_9428", "The Nightmare", "npctypes"),
            new GamevalEntry(9429, "THE_NIGHTMARE_9429", "The Nightmare", "npctypes"),
            new GamevalEntry(9430, "THE_NIGHTMARE_9430", "The Nightmare", "npctypes"),
            new GamevalEntry(9431, "THE_NIGHTMARE_9431", "The Nightmare", "npctypes"),
            new GamevalEntry(9432, "THE_NIGHTMARE_9432", "The Nightmare", "npctypes"),
            new GamevalEntry(9433, "THE_NIGHTMARE_9433", "The Nightmare", "npctypes"),
            new GamevalEntry(9434, "TOTEM", "Totem", "npctypes"),
            new GamevalEntry(9435, "TOTEM_9435", "Totem", "npctypes"),
            new GamevalEntry(9436, "TOTEM_9436", "Totem", "npctypes"),
            new GamevalEntry(9437, "TOTEM_9437", "Totem", "npctypes"),
            new GamevalEntry(9438, "TOTEM_9438", "Totem", "npctypes"),
            new GamevalEntry(9439, "TOTEM_9439", "Totem", "npctypes"),
            new GamevalEntry(9440, "TOTEM_9440", "Totem", "npctypes"),
            new GamevalEntry(9441, "TOTEM_9441", "Totem", "npctypes"),
            new GamevalEntry(9442, "TOTEM_9442", "Totem", "npctypes"),
            new GamevalEntry(9443, "TOTEM_9443", "Totem", "npctypes"),
            new GamevalEntry(9444, "TOTEM_9444", "Totem", "npctypes"),
            new GamevalEntry(9445, "TOTEM_9445", "Totem", "npctypes"),
            new GamevalEntry(9446, "SLEEPWALKER_9446", "Sleepwalker", "npctypes"),
            new GamevalEntry(9447, "SLEEPWALKER_9447", "Sleepwalker", "npctypes"),
            new GamevalEntry(9448, "SLEEPWALKER_9448", "Sleepwalker", "npctypes"),
            new GamevalEntry(9449, "SLEEPWALKER_9449", "Sleepwalker", "npctypes"),
            new GamevalEntry(9450, "SLEEPWALKER_9450", "Sleepwalker", "npctypes"),
            new GamevalEntry(9451, "SLEEPWALKER_9451", "Sleepwalker", "npctypes"),
            new GamevalEntry(9452, "PARASITE", "Parasite", "npctypes"),
            new GamevalEntry(9453, "PARASITE_9453", "Parasite", "npctypes"),
            new GamevalEntry(9454, "HUSK", "Husk", "npctypes"),
            new GamevalEntry(9455, "HUSK_9455", "Husk", "npctypes"),
            new GamevalEntry(9456, "ID_9456", "", "npctypes"),
            new GamevalEntry(9457, "ID_9457", "", "npctypes"),
            new GamevalEntry(9458, "ID_9458", "", "npctypes"),
            new GamevalEntry(9459, "ID_9459", "", "npctypes"),
            new GamevalEntry(9460, "THE_NIGHTMARE_9460", "The Nightmare", "npctypes"),
            new GamevalEntry(9461, "THE_NIGHTMARE_9461", "The Nightmare", "npctypes"),
            new GamevalEntry(9462, "THE_NIGHTMARE_9462", "The Nightmare", "npctypes"),
            new GamevalEntry(9463, "THE_NIGHTMARE_9463", "The Nightmare", "npctypes"),
            new GamevalEntry(9464, "THE_NIGHTMARE_9464", "The Nightmare", "npctypes"),
            new GamevalEntry(9465, "INFERNAL_PYRELORD", "Infernal pyrelord", "npctypes"),
            new GamevalEntry(9466, "HUSK_9466", "Husk", "npctypes"),
            new GamevalEntry(9467, "HUSK_9467", "Husk", "npctypes"),
            new GamevalEntry(9468, "PARASITE_9468", "Parasite", "npctypes"),
            new GamevalEntry(9469, "PARASITE_9469", "Parasite", "npctypes"),
            new GamevalEntry(9470, "SLEEPWALKER_9470", "Sleepwalker", "npctypes"),
            new GamevalEntry(9471, "SISTER_SENGA", "Sister Senga", "npctypes"),
            new GamevalEntry(9472, "SISTER_SENGA_9472", "Sister Senga", "npctypes"),
            new GamevalEntry(9473, "ID_9473", "", "npctypes"),
            new GamevalEntry(9474, "ENT_TRUNK", "Ent trunk", "npctypes"),
            new GamevalEntry(9475, "ID_9475", "", "npctypes"),
            new GamevalEntry(9476, "GIELINOR_GUIDE_9476", "Gielinor Guide", "npctypes"),
            new GamevalEntry(9477, "SURVIVAL_EXPERT_9477", "Survival Expert", "npctypes"),
            new GamevalEntry(9478, "FISHING_SPOT_9478", "Fishing spot", "npctypes"),
            new GamevalEntry(9479, "MASTER_NAVIGATOR", "Master Navigator", "npctypes"),
            new GamevalEntry(9480, "QUEST_GUIDE_9480", "Quest Guide", "npctypes"),
            new GamevalEntry(9481, "MINING_INSTRUCTOR_9481", "Mining Instructor", "npctypes"),
            new GamevalEntry(9482, "COMBAT_INSTRUCTOR_9482", "Combat Instructor", "npctypes"),
            new GamevalEntry(9483, "GIANT_RAT_9483", "Giant rat", "npctypes"),
            new GamevalEntry(9484, "BANKER_9484", "Banker", "npctypes"),
            new GamevalEntry(9485, "BROTHER_BRACE_9485", "Brother Brace", "npctypes"),
            new GamevalEntry(9486, "IRONMAN_TUTOR_9486", "Ironman tutor", "npctypes"),
            new GamevalEntry(9487, "MAGIC_INSTRUCTOR_9487", "Magic Instructor", "npctypes"),
            new GamevalEntry(9488, "CHICKEN_9488", "Chicken", "npctypes"),
            new GamevalEntry(9489, "VELIAF_HURTZ_9489", "Veliaf Hurtz", "npctypes"),
            new GamevalEntry(9490, "HAMELN_THE_JESTER", "Hameln the Jester", "npctypes"),
            new GamevalEntry(9491, "HANCHEN_THE_HOUND", "Hanchen the Hound", "npctypes"),
            new GamevalEntry(9492, "UD_TANGLEROOT", "?d Tangleroot", "npctypes"),
            new GamevalEntry(9493, "U_TANGLEROOT_9493", "? Tangleroot", "npctypes"),
            new GamevalEntry(9494, "U_TANGLEROOT_9494", "? Tangleroot", "npctypes"),
            new GamevalEntry(9495, "U_TANGLEROOT_9495", "? Tangleroot", "npctypes"),
            new GamevalEntry(9496, "U_TANGLEROOT_9496", "? Tangleroot", "npctypes"),
            new GamevalEntry(9497, "TANGLEROOT_9497", "Tangleroot", "npctypes"),
            new GamevalEntry(9498, "TANGLEROOT_9498", "Tangleroot", "npctypes"),
            new GamevalEntry(9499, "TANGLEROOT_9499", "Tangleroot", "npctypes"),
            new GamevalEntry(9500, "TANGLEROOT_9500", "Tangleroot", "npctypes"),
            new GamevalEntry(9501, "TANGLEROOT_9501", "Tangleroot", "npctypes"),
            new GamevalEntry(9502, "IORWERTH_WARRIOR_9502", "Iorwerth Warrior", "npctypes"),
            new GamevalEntry(9503, "IORWERTH_WARRIOR_9503", "Iorwerth Warrior", "npctypes"),
            new GamevalEntry(9504, "AGITATED_BEES", "Agitated bees", "npctypes"),
            new GamevalEntry(9505, "HAMELN_THE_JESTER_9505", "Hameln the Jester", "npctypes"),
            new GamevalEntry(9506, "HANCHEN_THE_HOUND_9506", "Hanchen the Hound", "npctypes"),
            new GamevalEntry(9507, "ID_9507", "", "npctypes"),
            new GamevalEntry(9508, "ID_9508", "", "npctypes"),
            new GamevalEntry(9509, "ID_9509", "", "npctypes"),
            new GamevalEntry(9510, "ID_9510", "", "npctypes"),
            new GamevalEntry(9511, "ENRAGED_TEKTINY", "Enraged Tektiny", "npctypes"),
            new GamevalEntry(9512, "FLYING_VESPINA", "Flying Vespina", "npctypes"),
            new GamevalEntry(9513, "ENRAGED_TEKTINY_9513", "Enraged Tektiny", "npctypes"),
            new GamevalEntry(9514, "FLYING_VESPINA_9514", "Flying Vespina", "npctypes"),
            new GamevalEntry(9515, "ID_9515", "", "npctypes"),
            new GamevalEntry(9516, "ID_9516", "", "npctypes"),
            new GamevalEntry(9517, "ID_9517", "", "npctypes"),
            new GamevalEntry(9518, "ID_9518", "", "npctypes"),
            new GamevalEntry(9519, "ID_9519", "", "npctypes"),
            new GamevalEntry(9520, "ID_9520", "", "npctypes"),
            new GamevalEntry(9521, "VELIAF_HURTZ_9521", "Veliaf Hurtz", "npctypes"),
            new GamevalEntry(9522, "VELIAF_HURTZ_9522", "Veliaf Hurtz", "npctypes"),
            new GamevalEntry(9523, "VELIAF_HURTZ_9523", "Veliaf Hurtz", "npctypes"),
            new GamevalEntry(9524, "VELIAF_HURTZ_9524", "Veliaf Hurtz", "npctypes"),
            new GamevalEntry(9525, "VELIAF_HURTZ_9525", "Veliaf Hurtz", "npctypes"),
            new GamevalEntry(9526, "VELIAF_HURTZ_9526", "Veliaf Hurtz", "npctypes"),
            new GamevalEntry(9527, "VELIAF_HURTZ_9527", "Veliaf Hurtz", "npctypes"),
            new GamevalEntry(9528, "VELIAF_HURTZ_9528", "Veliaf Hurtz", "npctypes"),
            new GamevalEntry(9529, "VELIAF_HURTZ_9529", "Veliaf Hurtz", "npctypes"),
            new GamevalEntry(9530, "IVAN_STROM_9530", "Ivan Strom", "npctypes"),
            new GamevalEntry(9531, "IVAN_STROM_9531", "Ivan Strom", "npctypes"),
            new GamevalEntry(9532, "IVAN_STROM_9532", "Ivan Strom", "npctypes"),
            new GamevalEntry(9533, "IVAN_STROM_9533", "Ivan Strom", "npctypes"),
            new GamevalEntry(9534, "IVAN_STROM_9534", "Ivan Strom", "npctypes"),
            new GamevalEntry(9535, "IVAN_STROM_9535", "Ivan Strom", "npctypes"),
            new GamevalEntry(9536, "IVAN_STROM_9536", "Ivan Strom", "npctypes"),
            new GamevalEntry(9537, "SAFALAAN_HALLOW_9537", "Safalaan Hallow", "npctypes"),
            new GamevalEntry(9538, "SAFALAAN_HALLOW_9538", "Safalaan Hallow", "npctypes"),
            new GamevalEntry(9539, "SAFALAAN_HALLOW_9539", "Safalaan Hallow", "npctypes"),
            new GamevalEntry(9540, "SAFALAAN_HALLOW_9540", "Safalaan Hallow", "npctypes"),
            new GamevalEntry(9541, "SAFALAAN_HALLOW_9541", "Safalaan Hallow", "npctypes"),
            new GamevalEntry(9542, "SAFALAAN_HALLOW_9542", "Safalaan Hallow", "npctypes"),
            new GamevalEntry(9543, "KAEL_FORSHAW_9543", "Kael Forshaw", "npctypes"),
            new GamevalEntry(9544, "KAEL_FORSHAW_9544", "Kael Forshaw", "npctypes"),
            new GamevalEntry(9545, "KAEL_FORSHAW_9545", "Kael Forshaw", "npctypes"),
            new GamevalEntry(9546, "KAEL_FORSHAW_9546", "Kael Forshaw", "npctypes"),
            new GamevalEntry(9547, "VERTIDA_SEFALATIS_9547", "Vertida Sefalatis", "npctypes"),
            new GamevalEntry(9548, "VERTIDA_SEFALATIS_9548", "Vertida Sefalatis", "npctypes"),
            new GamevalEntry(9549, "VERTIDA_SEFALATIS_9549", "Vertida Sefalatis", "npctypes"),
            new GamevalEntry(9550, "VERTIDA_SEFALATIS_9550", "Vertida Sefalatis", "npctypes"),
            new GamevalEntry(9551, "RADIGAD_PONFIT_9551", "Radigad Ponfit", "npctypes"),
            new GamevalEntry(9552, "RADIGAD_PONFIT_9552", "Radigad Ponfit", "npctypes"),
            new GamevalEntry(9553, "RADIGAD_PONFIT_9553", "Radigad Ponfit", "npctypes"),
            new GamevalEntry(9554, "POLMAFI_FERDYGRIS_9554", "Polmafi Ferdygris", "npctypes"),
            new GamevalEntry(9555, "POLMAFI_FERDYGRIS_9555", "Polmafi Ferdygris", "npctypes"),
            new GamevalEntry(9556, "POLMAFI_FERDYGRIS_9556", "Polmafi Ferdygris", "npctypes"),
            new GamevalEntry(9557, "CARL", "Carl", "npctypes"),
            new GamevalEntry(9558, "CARL_9558", "Carl", "npctypes"),
            new GamevalEntry(9559, "KROY", "Kroy", "npctypes"),
            new GamevalEntry(9560, "KROY_9560", "Kroy", "npctypes"),
            new GamevalEntry(9561, "DAMIEN_LEUCURTE", "Damien Leucurte", "npctypes"),
            new GamevalEntry(9562, "DAMIEN_LEUCURTE_9562", "Damien Leucurte", "npctypes"),
            new GamevalEntry(9563, "DAMIEN_LEUCURTE_9563", "Damien Leucurte", "npctypes"),
            new GamevalEntry(9564, "DAMIEN_LEUCURTE_9564", "Damien Leucurte", "npctypes"),
            new GamevalEntry(9565, "LORD_CROMBWICK", "Lord Crombwick", "npctypes"),
            new GamevalEntry(9566, "VANSTROM_KLAUSE_9566", "Vanstrom Klause", "npctypes"),
            new GamevalEntry(9567, "VANSTROM_KLAUSE_9567", "Vanstrom Klause", "npctypes"),
            new GamevalEntry(9568, "VANSTROM_KLAUSE_9568", "Vanstrom Klause", "npctypes"),
            new GamevalEntry(9569, "VANSTROM_KLAUSE_9569", "Vanstrom Klause", "npctypes"),
            new GamevalEntry(9570, "VANSTROM_KLAUSE_9570", "Vanstrom Klause", "npctypes"),
            new GamevalEntry(9571, "VANSTROM_KLAUSE_9571", "Vanstrom Klause", "npctypes"),
            new GamevalEntry(9572, "MIST_9572", "Mist", "npctypes"),
            new GamevalEntry(9573, "ACIDIC_BLOODVELD", "Acidic Bloodveld", "npctypes"),
            new GamevalEntry(9574, "VANESCULA_DRAKAN_9574", "Vanescula Drakan", "npctypes"),
            new GamevalEntry(9575, "VANESCULA_DRAKAN_9575", "Vanescula Drakan", "npctypes"),
            new GamevalEntry(9576, "VANESCULA_DRAKAN_9576", "Vanescula Drakan", "npctypes"),
            new GamevalEntry(9577, "VANESCULA_DRAKAN_9577", "Vanescula Drakan", "npctypes"),
            new GamevalEntry(9578, "LORD_ALEXEI_JOVKAI", "Lord Alexei Jovkai", "npctypes"),
            new GamevalEntry(9579, "LOWERNIEL_DRAKAN", "Lowerniel Drakan", "npctypes"),
            new GamevalEntry(9580, "WEREWOLF_9580", "Werewolf", "npctypes"),
            new GamevalEntry(9581, "WEREWOLF_9581", "Werewolf", "npctypes"),
            new GamevalEntry(9582, "WEREWOLF_9582", "Werewolf", "npctypes"),
            new GamevalEntry(9583, "PRISONER", "Prisoner", "npctypes"),
            new GamevalEntry(9584, "PRISONER_9584", "Prisoner", "npctypes"),
            new GamevalEntry(9585, "PRISONER_9585", "Prisoner", "npctypes"),
            new GamevalEntry(9586, "VAMPYRE_JUVINATE_9586", "+ Vampyre Juvinate", "npctypes"),
            new GamevalEntry(9587, "VAMPYRE_JUVINATE_9587", "+ Vampyre Juvinate", "npctypes"),
            new GamevalEntry(9588, "DESMODUS_LASIURUS", "Desmodus Lasiurus", "npctypes"),
            new GamevalEntry(9589, "MORDAN_NIKAZSI", "+ Mordan Nikazsi", "npctypes"),
            new GamevalEntry(9590, "VYREWATCH_9590", "Vyrewatch", "npctypes"),
            new GamevalEntry(9591, "VYREWATCH_9591", "Vyrewatch", "npctypes"),
            new GamevalEntry(9592, "PRISONER_9592", "Prisoner", "npctypes"),
            new GamevalEntry(9593, "PRISONER_9593", "Prisoner", "npctypes"),
            new GamevalEntry(9594, "MARIA_GADDERANKS", "Maria Gadderanks", "npctypes"),
            new GamevalEntry(9595, "MARIA_GADDERANKS_9595", "Maria Gadderanks", "npctypes"),
            new GamevalEntry(9596, "RON_GADDERANKS", "Ron Gadderanks", "npctypes"),
            new GamevalEntry(9597, "RON_GADDERANKS_9597", "Ron Gadderanks", "npctypes"),
            new GamevalEntry(9598, "SARIUS_GUILE_9598", "Sarius Guile", "npctypes"),
            new GamevalEntry(9599, "VYREWATCH_SENTINEL", "Vyrewatch Sentinel", "npctypes"),
            new GamevalEntry(9600, "VYREWATCH_SENTINEL_9600", "Vyrewatch Sentinel", "npctypes"),
            new GamevalEntry(9601, "VYREWATCH_SENTINEL_9601", "Vyrewatch Sentinel", "npctypes"),
            new GamevalEntry(9602, "VYREWATCH_SENTINEL_9602", "Vyrewatch Sentinel", "npctypes"),
            new GamevalEntry(9603, "VYREWATCH_SENTINEL_9603", "Vyrewatch Sentinel", "npctypes"),
            new GamevalEntry(9604, "VYREWATCH_SENTINEL_9604", "Vyrewatch Sentinel", "npctypes"),
            new GamevalEntry(9605, "VYREWATCH_9605", "Vyrewatch", "npctypes"),
            new GamevalEntry(9606, "VYREWATCH_9606", "Vyrewatch", "npctypes"),
            new GamevalEntry(9607, "VYREWATCH_9607", "Vyrewatch", "npctypes"),
            new GamevalEntry(9608, "VYREWATCH_9608", "Vyrewatch", "npctypes"),
            new GamevalEntry(9609, "SEAGULL_9609", "Seagull", "npctypes"),
            new GamevalEntry(9610, "ID_9610_16_353_MUTATED_BLOODVELD", "16! +? 353 Mutated Bloodveld", "npctypes"),
            new GamevalEntry(9611, "ID_9611_16_353_MUTATED_BLOODVELD", "16! +? 353 Mutated Bloodveld", "npctypes"),
            new GamevalEntry(9612, "NAIL_BEAST_9612", "Nail beast", "npctypes"),
            new GamevalEntry(9613, "NAIL_BEAST_9613", "Nail beast", "npctypes"),
            new GamevalEntry(9614, "VAMPYRE_JUVINATE_9614", "Vampyre Juvinate", "npctypes"),
            new GamevalEntry(9615, "VAMPYRE_JUVINATE_9615", "Vampyre Juvinate", "npctypes"),
            new GamevalEntry(9616, "VAMPYRE_JUVINATE_9616", "Vampyre Juvinate", "npctypes"),
            new GamevalEntry(9617, "VAMPYRE_JUVINATE_9617", "Vampyre Juvinate", "npctypes"),
            new GamevalEntry(9618, "ID_9618", "", "npctypes"),
            new GamevalEntry(9619, "CURPILE_FYOD", "Curpile Fyod", "npctypes"),
            new GamevalEntry(9620, "ID_9620", "", "npctypes"),
            new GamevalEntry(9621, "VELIAF_HURTZ_9621", "Veliaf Hurtz", "npctypes"),
            new GamevalEntry(9622, "SANI_PILIU", "Sani Piliu", "npctypes"),
            new GamevalEntry(9623, "SANI_PILIU_9623", "Sani Piliu", "npctypes"),
            new GamevalEntry(9624, "HAROLD_EVANS", "Harold Evans", "npctypes"),
            new GamevalEntry(9625, "HAROLD_EVANS_9625", "Harold Evans", "npctypes"),
            new GamevalEntry(9626, "ID_9626", "", "npctypes"),
            new GamevalEntry(9627, "RADIGAD_PONFIT_9627", "Radigad Ponfit", "npctypes"),
            new GamevalEntry(9628, "ID_9628", "", "npctypes"),
            new GamevalEntry(9629, "POLMAFI_FERDYGRIS_9629", "Polmafi Ferdygris", "npctypes"),
            new GamevalEntry(9630, "ID_9630", "", "npctypes"),
            new GamevalEntry(9631, "IVAN_STROM_9631", "Ivan Strom", "npctypes"),
            new GamevalEntry(9632, "VANSTROM_KLAUSE_9632", "Vanstrom Klause", "npctypes"),
            new GamevalEntry(9633, "VELIAF_HURTZ_9633", "Veliaf Hurtz", "npctypes"),
            new GamevalEntry(9634, "X_3_4_5_6", "X 3 4 5 6 ((", "npctypes"),
            new GamevalEntry(9635, "GADDERANKS_9635", "Gadderanks", "npctypes"),
            new GamevalEntry(9636, "DREZEL", "Drezel", "npctypes"),
            new GamevalEntry(9637, "DARK_SQUIRREL", "Dark Squirrel", "npctypes"),
            new GamevalEntry(9638, "DARK_SQUIRREL_9638", "Dark Squirrel", "npctypes"),
            new GamevalEntry(9639, "MYSTERIOUS_STRANGER_9639", "Mysterious Stranger", "npctypes"),
            new GamevalEntry(9640, "MYSTERIOUS_STRANGER_9640", "Mysterious Stranger", "npctypes"),
            new GamevalEntry(9641, "BAT_9641", "Bat", "npctypes"),
            new GamevalEntry(9642, "BAT_9642", "Bat", "npctypes"),
            new GamevalEntry(9643, "SPIDER_9643", "Spider", "npctypes"),
            new GamevalEntry(9644, "SPIDER_9644", "Spider", "npctypes"),
            new GamevalEntry(9645, "FISH_9645", "Fish", "npctypes"),
            new GamevalEntry(9646, "FISH_9646", "Fish", "npctypes"),
            new GamevalEntry(9647, "ID_9647", "", "npctypes"),
            new GamevalEntry(9648, "KNIGHT_OF_THE_OWL", "Knight of the Owl", "npctypes"),
            new GamevalEntry(9649, "ID_9649", "", "npctypes"),
            new GamevalEntry(9650, "KNIGHT_OF_THE_UNICORN", "Knight of the Unicorn", "npctypes"),
            new GamevalEntry(9651, "ID_9651", "", "npctypes"),
            new GamevalEntry(9652, "KNIGHT_OF_THE_WOLF", "Knight of the Wolf", "npctypes"),
            new GamevalEntry(9653, "ID_9653", "", "npctypes"),
            new GamevalEntry(9654, "KNIGHT_OF_THE_LION", "Knight of the Lion", "npctypes"),
            new GamevalEntry(9655, "ID_9655", "", "npctypes"),
            new GamevalEntry(9656, "ARCHPRIEST_OF_THE_UNICORN", "Archpriest of the Unicorn", "npctypes"),
            new GamevalEntry(9657, "DARKMEYER_SLAVE", "Darkmeyer Slave", "npctypes"),
            new GamevalEntry(9658, "DARKMEYER_SLAVE_9658", "Darkmeyer Slave", "npctypes"),
            new GamevalEntry(9659, "MAD_MELVIN96", "mad melvin96", "npctypes"),
            new GamevalEntry(9660, "R2T2PNSH0TY", "r2t2pnsh0Ty", "npctypes"),
            new GamevalEntry(9661, "JYN", "Jyn", "npctypes"),
            new GamevalEntry(9662, "C4SSI4N", "c4ssi4n", "npctypes"),
            new GamevalEntry(9663, "FISHRUNNER82", "fishrunner82", "npctypes"),
            new GamevalEntry(9664, "WEAST_SIDE49", "weast side49", "npctypes"),
            new GamevalEntry(9665, "C0LECT0R890", "c0lect0r890", "npctypes"),
            new GamevalEntry(9666, "GIANT_SQUIRREL_9666", "Giant Squirrel", "npctypes"),
            new GamevalEntry(9667, "OWL", "Owl", "npctypes"),
            new GamevalEntry(9668, "OWL_9668", "Owl", "npctypes"),
            new GamevalEntry(9669, "ID_9669", "", "npctypes"),
            new GamevalEntry(9670, "ID_9670", "", "npctypes"),
            new GamevalEntry(9671, "ID_9671", "", "npctypes"),
            new GamevalEntry(9672, "ID_9672", "", "npctypes"),
            new GamevalEntry(9673, "ID_9673", "", "npctypes"),
            new GamevalEntry(9674, "ID_9674", "", "npctypes"),
            new GamevalEntry(9675, "NORANNA_TYTANIN", "+ Noranna Tytanin", "npctypes"),
            new GamevalEntry(9676, "NORANNA_TYTANIN_9676", "+ Noranna Tytanin", "npctypes"),
            new GamevalEntry(9677, "SLAVE_9677", "Slave", "npctypes"),
            new GamevalEntry(9678, "SLAVE_9678", "Slave", "npctypes"),
            new GamevalEntry(9679, "SLAVE_9679", "Slave", "npctypes"),
            new GamevalEntry(9680, "SLAVE_9680", "Slave", "npctypes"),
            new GamevalEntry(9681, "SLAVE_9681", "Slave", "npctypes"),
            new GamevalEntry(9682, "SLAVE_9682", "Slave", "npctypes"),
            new GamevalEntry(9683, "TALK_TO_9683", "Talk-to", "npctypes"),
            new GamevalEntry(9684, "TALK_TO_9684", "Talk-to", "npctypes"),
            new GamevalEntry(9685, "VALENTIN_RASPUTIN", "Valentin Rasputin", "npctypes"),
            new GamevalEntry(9686, "VON_VAN_VON", "Von van Von", "npctypes"),
            new GamevalEntry(9687, "VLAD_BECHSTEIN", "Vlad Bechstein", "npctypes"),
            new GamevalEntry(9688, "DRACONIS_SANGUINE", "Draconis Sanguine", "npctypes"),
            new GamevalEntry(9689, "MORT_NIGHTSHADE", "Mort Nightshade", "npctypes"),
            new GamevalEntry(9690, "VAMPYRUS_DIAEMUS", "Vampyrus Diaemus", "npctypes"),
            new GamevalEntry(9691, "CARNIVUS_BELAMORTA", "Carnivus Belamorta", "npctypes"),
            new GamevalEntry(9692, "VORMAR_VAKAN", "Vormar Vakan", "npctypes"),
            new GamevalEntry(9693, "MISDRIEVUS_SHADUM", "Misdrievus Shadum", "npctypes"),
            new GamevalEntry(9694, "VLAD_DIAEMUS", "Vlad Diaemus", "npctypes"),
            new GamevalEntry(9695, "NOCTILLION_LUGOSI", "Noctillion Lugosi", "npctypes"),
            new GamevalEntry(9696, "ALEK_CONSTANTINE", "Alek Constantine", "npctypes"),
            new GamevalEntry(9697, "GRIGOR_RASPUTIN", "Grigor Rasputin", "npctypes"),
            new GamevalEntry(9698, "HAEMAS_LAMESCUS", "Haemas Lamescus", "npctypes"),
            new GamevalEntry(9699, "REMUS_KANINUS", "Remus Kaninus", "npctypes"),
            new GamevalEntry(9700, "VALLESSIA_DRACYULA", "Vallessia Dracyula", "npctypes"),
            new GamevalEntry(9701, "VIOLETTA_SANGUINE", "Violetta Sanguine", "npctypes"),
            new GamevalEntry(9702, "DIPHYLLA_BECHSTEIN", "Diphylla Bechstein", "npctypes"),
            new GamevalEntry(9703, "EPISCULA_HELSING", "Episcula Helsing", "npctypes"),
            new GamevalEntry(9704, "VAMPYRESSA_VAN_VON", "Vampyressa van Von", "npctypes"),
            new GamevalEntry(9705, "VALLESSIA_VON_PITT", "Vallessia von Pitt", "npctypes"),
            new GamevalEntry(9706, "VONNETTA_VARNIS", "Vonnetta Varnis", "npctypes"),
            new GamevalEntry(9707, "NATALIDAE_SHADUM", "Natalidae Shadum", "npctypes"),
            new GamevalEntry(9708, "MORTINA_DAUBENTON", "Mortina Daubenton", "npctypes"),
            new GamevalEntry(9709, "LASENNA_RASPUTIN", "Lasenna Rasputin", "npctypes"),
            new GamevalEntry(9710, "CANINELLE_DRAYNAR", "Caninelle Draynar", "npctypes"),
            new GamevalEntry(9711, "VALENTINA_DIAEMUS", "Valentina Diaemus", "npctypes"),
            new GamevalEntry(9712, "NAKASA_JOVKAI", "Nakasa Jovkai", "npctypes"),
            new GamevalEntry(9713, "CRIMSONETTE_VAN_MARR", "Crimsonette van Marr", "npctypes"),
            new GamevalEntry(9714, "PIPISTRELLE_DRAYNAR", "Pipistrelle Draynar", "npctypes"),
            new GamevalEntry(9715, "LADY_NADEZHDA_SHADUM", "Lady Nadezhda Shadum", "npctypes"),
            new GamevalEntry(9716, "LORD_MISCHA_MYRMEL", "Lord Mischa Myrmel", "npctypes"),
            new GamevalEntry(9717, "LORD_ALEXEI_JOVKAI_9717", "Lord Alexei Jovkai", "npctypes"),
            new GamevalEntry(9718, "BANKER_9718", "Banker", "npctypes"),
            new GamevalEntry(9719, "BANKER_9719", "Banker", "npctypes"),
            new GamevalEntry(9720, "GRINKA_KRAST", "Grinka Krast", "npctypes"),
            new GamevalEntry(9721, "DRASDAN_RANOR", "+ Drasdan Ranor", "npctypes"),
            new GamevalEntry(9722, "DESPOINA_CALLIDRA", "Despoina Callidra", "npctypes"),
            new GamevalEntry(9723, "LENYIG_KARNA", "Lenyig Karna", "npctypes"),
            new GamevalEntry(9724, "VARRIAN_SOBAK", "Varrian Sobak", "npctypes"),
            new GamevalEntry(9725, "SLAVE_9725", "Slave", "npctypes"),
            new GamevalEntry(9726, "SLAVE_9726", "Slave", "npctypes"),
            new GamevalEntry(9727, "VAMPYRE_JUVINATE_9727", "+ Vampyre Juvinate", "npctypes"),
        };
    }

    static Optional<GamevalEntry> byId(int id) {
        for (GamevalEntry entry : entries()) {
            if (entry.id() == id) return Optional.of(entry);
        }
        return Optional.empty();
    }

}
