package net.titan.gamevals.internal;

import java.util.Optional;

import net.titan.gamevals.GamevalEntry;
import net.titan.gamevals.QuestEntry;

final class NpcIDEntries_22 {
    private NpcIDEntries_22() {}

    static GamevalEntry[] entries() {
        return new GamevalEntry[] {
            new GamevalEntry(11266, "LOTG_OLDAK_YUBIUSK", "Oldak", "npctypes"),
            new GamevalEntry(11267, "LOTG_GOBLIN_HIGH_PRIEST", "High Priest Bighead", "npctypes"),
            new GamevalEntry(11268, "LOTG_GOBLIN_SKELETON", "Skoblin", "npctypes"),
            new GamevalEntry(11269, "LOTG_GOBLIN_SKELETON_HIGH_PRIEST1", "Snothead", "npctypes"),
            new GamevalEntry(11270, "LOTG_GOBLIN_SKELETON_HIGH_PRIEST2", "Snailfeet", "npctypes"),
            new GamevalEntry(11271, "LOTG_GOBLIN_SKELETON_HIGH_PRIEST3", "Mosschin", "npctypes"),
            new GamevalEntry(11272, "LOTG_GOBLIN_SKELETON_HIGH_PRIEST4", "Redeyes", "npctypes"),
            new GamevalEntry(11273, "LOTG_GOBLIN_SKELETON_HIGH_PRIEST5", "Strongbones", "npctypes"),
            new GamevalEntry(11274, "LOTG_GOBLIN_SKELETON_HIGH_PRIEST1_DEFEATED", "Snothead", "npctypes"),
            new GamevalEntry(11275, "LOTG_GOBLIN_SKELETON_HIGH_PRIEST2_DEFEATED", "Snailfeet", "npctypes"),
            new GamevalEntry(11276, "POH_NEX_PET", "Nexling", "npctypes"),
            new GamevalEntry(11277, "NEX_PET", "Nexling", "npctypes"),
            new GamevalEntry(11278, "NEX", "Nex", "npctypes"),
            new GamevalEntry(11279, "NEX_SPAWNING", "Nex", "npctypes"),
            new GamevalEntry(11280, "NEX_SOULSPLIT", "Nex", "npctypes"),
            new GamevalEntry(11281, "NEX_DEFLECT", "Nex", "npctypes"),
            new GamevalEntry(11282, "NEX_DYING", "Nex", "npctypes"),
            new GamevalEntry(11283, "NEX_SMOKEMAGE", "Fumus", "npctypes"),
            new GamevalEntry(11284, "NEX_SHADOWMAGE", "Umbra", "npctypes"),
            new GamevalEntry(11285, "NEX_BLOODMAGE", "Cruor", "npctypes"),
            new GamevalEntry(11286, "NEX_ICEMAGE", "Glacies", "npctypes"),
            new GamevalEntry(11287, "NEX_MESSENGER", "Messenger", "npctypes"),
            new GamevalEntry(11288, "NEX_STORY_NPC_1OP", "Ashuelot Reis", "npctypes"),
            new GamevalEntry(11289, "NEX_STORY_NPC_3OP", "Ashuelot Reis", "npctypes"),
            new GamevalEntry(11290, "NEX_PRISON_WARRIOR", "Spiritual Warrior", "npctypes"),
            new GamevalEntry(11291, "NEX_PRISON_RANGER", "Spiritual Ranger", "npctypes"),
            new GamevalEntry(11292, "NEX_PRISON_MAGE", "Spiritual Mage", "npctypes"),
            new GamevalEntry(11293, "NEX_PRISON_BLOOD_REAVER", "Blood Reaver", "npctypes"),
            new GamevalEntry(11294, "NEX_PRISON_BLOOD_REAVER_BOSS", "Blood Reaver", "npctypes"),
            new GamevalEntry(11295, "NEX_STORY_NPC_OUTER", "nex_story_npc_outer", "npctypes"),
            new GamevalEntry(11296, "NEX_STORY_NPC_INNER", "nex_story_npc_inner", "npctypes"),
            new GamevalEntry(11297, "SEAGULL", "Gull", "npctypes"),
            new GamevalEntry(11298, "LOTG_GOBLIN_SKELETON_HIGH_PRIEST3_DEFEATED", "Mosschin", "npctypes"),
            new GamevalEntry(11299, "LOTG_GOBLIN_SKELETON_HIGH_PRIEST4_DEFEATED", "Redeyes", "npctypes"),
            new GamevalEntry(11300, "LOTG_GOBLIN_SKELETON_HIGH_PRIEST5_DEFEATED", "Strongbones", "npctypes"),
            new GamevalEntry(11301, "LOTG_HOPESPEAR_THERE", "Ghost", "npctypes"),
            new GamevalEntry(11302, "LOTG_GOBLIN_PRIEST_BLUE_1OP", "Priest", "npctypes"),
            new GamevalEntry(11303, "LOTG_GOBLIN_PRIEST_BLUE_2OP", "Priest", "npctypes"),
            new GamevalEntry(11304, "LOTG_GOBLIN_PRIEST_ORANGE_1OP", "Priest", "npctypes"),
            new GamevalEntry(11305, "LOTG_GOBLIN_PRIEST_ORANGE_2OP", "Priest", "npctypes"),
            new GamevalEntry(11306, "LOTG_GOBLIN_PRIEST_BLACK_1OP", "Priest", "npctypes"),
            new GamevalEntry(11307, "LOTG_GOBLIN_PRIEST_BLACK_2OP", "Priest", "npctypes"),
            new GamevalEntry(11308, "LOTG_GOBLIN_PRIEST_WHITE_1OP", "Priest", "npctypes"),
            new GamevalEntry(11309, "LOTG_GOBLIN_PRIEST_WHITE_2OP", "Priest", "npctypes"),
            new GamevalEntry(11310, "LOTG_GOBLIN_PRIEST_PURPLE_1OP", "Priest", "npctypes"),
            new GamevalEntry(11311, "LOTG_GOBLIN_PRIEST_PURPLE_2OP", "Priest", "npctypes"),
            new GamevalEntry(11312, "LOTG_GOBLIN_PRIEST_YELLOW_1OP", "Priest", "npctypes"),
            new GamevalEntry(11313, "LOTG_GOBLIN_PRIEST_YELLOW_2OP", "Priest", "npctypes"),
            new GamevalEntry(11314, "LOTG_GOBLIN_GUARD1", "Goblin guard", "npctypes"),
            new GamevalEntry(11315, "LOTG_GOBLIN_GUARD2", "Goblin guard", "npctypes"),
            new GamevalEntry(11316, "LOTG_GOBLIN_GUARD_BLUE", "Guard", "npctypes"),
            new GamevalEntry(11317, "LOTG_GOBLIN_GUARD_ORANGE", "Guard", "npctypes"),
            new GamevalEntry(11318, "LOTG_GOBLIN_GUARD_BLACK", "Guard", "npctypes"),
            new GamevalEntry(11319, "LOTG_GOBLIN_GUARD_WHITE", "Guard", "npctypes"),
            new GamevalEntry(11320, "LOTG_GOBLIN_GUARD_PURPLE", "Guard", "npctypes"),
            new GamevalEntry(11321, "LOTG_GOBLIN_GUARD_YELLOW", "Guard", "npctypes"),
            new GamevalEntry(11322, "LOTG_GOBLIN_1_UNARMOURED", "Goblin", "npctypes"),
            new GamevalEntry(11323, "LOTG_GOBLIN_1_ARMOURED_RED", "Goblin", "npctypes"),
            new GamevalEntry(11324, "LOTG_GOBLIN_1_ARMOURED_PINK", "Goblin", "npctypes"),
            new GamevalEntry(11325, "LOTG_GOBLIN_1_ARMOURED_GREEN", "Goblin", "npctypes"),
            new GamevalEntry(11326, "LOTG_GOBLIN_1_ARMOURED_BLUE", "Goblin", "npctypes"),
            new GamevalEntry(11327, "LOTG_GOBLIN_1_ARMOURED_YELLOW", "Goblin", "npctypes"),
            new GamevalEntry(11328, "LOTG_GOBLIN_1_ARMOURED_ORANGE", "Goblin", "npctypes"),
            new GamevalEntry(11329, "LOTG_GOBLIN_1_ARMOURED_PURPLE", "Goblin", "npctypes"),
            new GamevalEntry(11330, "LOTG_GOBLIN_1_ARMOURED_BLACK", "Goblin", "npctypes"),
            new GamevalEntry(11331, "LOTG_GOBLIN_1_ARMOURED_WHITE", "Goblin", "npctypes"),
            new GamevalEntry(11332, "LOTG_GOBLIN_2_UNARMOURED", "Goblin", "npctypes"),
            new GamevalEntry(11333, "LOTG_GOBLIN_2_ARMOURED_RED", "Goblin", "npctypes"),
            new GamevalEntry(11334, "LOTG_GOBLIN_2_ARMOURED_PINK", "Goblin", "npctypes"),
            new GamevalEntry(11335, "LOTG_GOBLIN_2_ARMOURED_GREEN", "Goblin", "npctypes"),
            new GamevalEntry(11336, "LOTG_GOBLIN_2_ARMOURED_BLUE", "Goblin", "npctypes"),
            new GamevalEntry(11337, "LOTG_GOBLIN_2_ARMOURED_YELLOW", "Goblin", "npctypes"),
            new GamevalEntry(11338, "LOTG_GOBLIN_2_ARMOURED_ORANGE", "Goblin", "npctypes"),
            new GamevalEntry(11339, "LOTG_GOBLIN_2_ARMOURED_PURPLE", "Goblin", "npctypes"),
            new GamevalEntry(11340, "LOTG_GOBLIN_2_ARMOURED_BLACK", "Goblin", "npctypes"),
            new GamevalEntry(11341, "LOTG_GOBLIN_2_ARMOURED_WHITE", "Goblin", "npctypes"),
            new GamevalEntry(11342, "LOTG_GOBLIN_3_UNARMOURED", "Goblin", "npctypes"),
            new GamevalEntry(11343, "LOTG_GOBLIN_3_ARMOURED_RED", "Goblin", "npctypes"),
            new GamevalEntry(11344, "LOTG_GOBLIN_3_ARMOURED_PINK", "Goblin", "npctypes"),
            new GamevalEntry(11345, "LOTG_GOBLIN_3_ARMOURED_GREEN", "Goblin", "npctypes"),
            new GamevalEntry(11346, "LOTG_GOBLIN_3_ARMOURED_BLUE", "Goblin", "npctypes"),
            new GamevalEntry(11347, "LOTG_GOBLIN_3_ARMOURED_YELLOW", "Goblin", "npctypes"),
            new GamevalEntry(11348, "LOTG_GOBLIN_3_ARMOURED_ORANGE", "Goblin", "npctypes"),
            new GamevalEntry(11349, "LOTG_GOBLIN_3_ARMOURED_PURPLE", "Goblin", "npctypes"),
            new GamevalEntry(11350, "LOTG_GOBLIN_3_ARMOURED_BLACK", "Goblin", "npctypes"),
            new GamevalEntry(11351, "LOTG_GOBLIN_3_ARMOURED_WHITE", "Goblin", "npctypes"),
            new GamevalEntry(11352, "LOTG_GOBLIN_4_UNARMOURED", "Goblin", "npctypes"),
            new GamevalEntry(11353, "LOTG_GOBLIN_4_ARMOURED_RED", "Goblin", "npctypes"),
            new GamevalEntry(11354, "LOTG_GOBLIN_4_ARMOURED_PINK", "Goblin", "npctypes"),
            new GamevalEntry(11355, "LOTG_GOBLIN_4_ARMOURED_GREEN", "Goblin", "npctypes"),
            new GamevalEntry(11356, "LOTG_GOBLIN_4_ARMOURED_BLUE", "Goblin", "npctypes"),
            new GamevalEntry(11357, "LOTG_GOBLIN_4_ARMOURED_YELLOW", "Goblin", "npctypes"),
            new GamevalEntry(11358, "LOTG_GOBLIN_4_ARMOURED_ORANGE", "Goblin", "npctypes"),
            new GamevalEntry(11359, "LOTG_GOBLIN_4_ARMOURED_PURPLE", "Goblin", "npctypes"),
            new GamevalEntry(11360, "LOTG_GOBLIN_4_ARMOURED_BLACK", "Goblin", "npctypes"),
            new GamevalEntry(11361, "LOTG_GOBLIN_4_ARMOURED_WHITE", "Goblin", "npctypes"),
            new GamevalEntry(11362, "LOTG_GOBLIN_5_UNARMOURED", "Goblin", "npctypes"),
            new GamevalEntry(11363, "LOTG_GOBLIN_5_ARMOURED_RED", "Goblin", "npctypes"),
            new GamevalEntry(11364, "LOTG_GOBLIN_5_ARMOURED_PINK", "Goblin", "npctypes"),
            new GamevalEntry(11365, "LOTG_GOBLIN_5_ARMOURED_GREEN", "Goblin", "npctypes"),
            new GamevalEntry(11366, "LOTG_GOBLIN_5_ARMOURED_BLUE", "Goblin", "npctypes"),
            new GamevalEntry(11367, "LOTG_GOBLIN_5_ARMOURED_YELLOW", "Goblin", "npctypes"),
            new GamevalEntry(11368, "LOTG_GOBLIN_5_ARMOURED_ORANGE", "Goblin", "npctypes"),
            new GamevalEntry(11369, "LOTG_GOBLIN_5_ARMOURED_PURPLE", "Goblin", "npctypes"),
            new GamevalEntry(11370, "LOTG_GOBLIN_5_ARMOURED_BLACK", "Goblin", "npctypes"),
            new GamevalEntry(11371, "LOTG_GOBLIN_5_ARMOURED_WHITE", "Goblin", "npctypes"),
            new GamevalEntry(11372, "LOTG_GOBLIN_6_UNARMOURED", "Goblin", "npctypes"),
            new GamevalEntry(11373, "LOTG_GOBLIN_6_ARMOURED_RED", "Goblin", "npctypes"),
            new GamevalEntry(11374, "LOTG_GOBLIN_6_ARMOURED_PINK", "Goblin", "npctypes"),
            new GamevalEntry(11375, "LOTG_GOBLIN_6_ARMOURED_GREEN", "Goblin", "npctypes"),
            new GamevalEntry(11376, "LOTG_GOBLIN_6_ARMOURED_BLUE", "Goblin", "npctypes"),
            new GamevalEntry(11377, "LOTG_GOBLIN_6_ARMOURED_YELLOW", "Goblin", "npctypes"),
            new GamevalEntry(11378, "LOTG_GOBLIN_6_ARMOURED_ORANGE", "Goblin", "npctypes"),
            new GamevalEntry(11379, "LOTG_GOBLIN_6_ARMOURED_PURPLE", "Goblin", "npctypes"),
            new GamevalEntry(11380, "LOTG_GOBLIN_6_ARMOURED_BLACK", "Goblin", "npctypes"),
            new GamevalEntry(11381, "LOTG_GOBLIN_6_ARMOURED_WHITE", "Goblin", "npctypes"),
            new GamevalEntry(11382, "LOTG_GOBLIN_PREACHER", "Preacher", "npctypes"),
            new GamevalEntry(11383, "LOTG_DIPFLIP", "Dipflip", "npctypes"),
            new GamevalEntry(11384, "DORGESH_OLDAK_THERE", "Oldak", "npctypes"),
            new GamevalEntry(11385, "DORGESH_OLDAK_THERE_1OP", "Oldak", "npctypes"),
            new GamevalEntry(11386, "LOTG_ZANIK_IN_LAB", "lotg_zanik_in_lab", "npctypes"),
            new GamevalEntry(11387, "LOTG_ZANIK_OUTSIDE_TEMPLE", "lotg_zanik_outside_temple", "npctypes"),
            new GamevalEntry(11388, "LOTG_ZANIK_IN_PRISON", "lotg_zanik_in_prison", "npctypes"),
            new GamevalEntry(11389, "LOTG_ZANIK_FAIRYRING", "lotg_zanik_fairyring", "npctypes"),
            new GamevalEntry(11390, "LOTG_OLDAK_FAIRYRING", "lotg_oldak_fairyring", "npctypes"),
            new GamevalEntry(11391, "LOTG_HOPESPEAR", "lotg_hopespear", "npctypes"),
            new GamevalEntry(11392, "LOTG_GOBLIN_PRIEST_BLUE", "lotg_goblin_priest_blue", "npctypes"),
            new GamevalEntry(11393, "LOTG_GOBLIN_PRIEST_ORANGE", "lotg_goblin_priest_orange", "npctypes"),
            new GamevalEntry(11394, "LOTG_GOBLIN_PRIEST_BLACK", "lotg_goblin_priest_black", "npctypes"),
            new GamevalEntry(11395, "LOTG_GOBLIN_PRIEST_WHITE", "lotg_goblin_priest_white", "npctypes"),
            new GamevalEntry(11396, "LOTG_GOBLIN_PRIEST_PURPLE", "lotg_goblin_priest_purple", "npctypes"),
            new GamevalEntry(11397, "LOTG_GOBLIN_PRIEST_YELLOW", "lotg_goblin_priest_yellow", "npctypes"),
            new GamevalEntry(11398, "DORGESH_OLDAK", "dorgesh_oldak", "npctypes"),
            new GamevalEntry(11399, "GUILD_WIZARD_1OP", "Wizard Distentor", "npctypes"),
            new GamevalEntry(11400, "GUILD_WIZARD_2OP", "Wizard Distentor", "npctypes"),
            new GamevalEntry(11401, "POH_SKILLPET_RUNECRAFTING_GOTR", "Greatish guardian", "npctypes"),
            new GamevalEntry(11402, "POH_ABYSSAL_PET", "Abyssal protector", "npctypes"),
            new GamevalEntry(11403, "GOTR_GREAT_GUARDIAN", "The Great Guardian", "npctypes"),
            new GamevalEntry(11404, "GOTR_REWARD_TRADER", "Apprentice Felix", "npctypes"),
            new GamevalEntry(11405, "GOTR_ABYSSAL_PYRAMID", "Abyssal guardian", "npctypes"),
            new GamevalEntry(11406, "GOTR_ABYSSAL_WALKER", "Abyssal walker", "npctypes"),
            new GamevalEntry(11407, "GOTR_ABYSSAL_LEECH", "Abyssal leech", "npctypes"),
            new GamevalEntry(11408, "GOTR_GUARDIAN_MIND", "Weak catalytic guardian", "npctypes"),
            new GamevalEntry(11409, "TELECRYSTAL_WIZARD_NO_SHOP", "Rick", "npctypes"),
            new GamevalEntry(11410, "TELECRYSTAL_WIZARD_SHOP", "Rick", "npctypes"),
            new GamevalEntry(11411, "GOTR_GUARDIAN_CHAOS", "Medium catalytic guardian", "npctypes"),
            new GamevalEntry(11412, "GOTR_GUARDIAN_DEATH", "Strong catalytic guardian", "npctypes"),
            new GamevalEntry(11413, "GOTR_GUARDIAN_BLOOD", "Overcharged catalytic guardian", "npctypes"),
            new GamevalEntry(11414, "GOTR_GUARDIAN_AIR", "Weak elemental guardian", "npctypes"),
            new GamevalEntry(11415, "GOTR_GUARDIAN_WATER", "Medium elemental guardian", "npctypes"),
            new GamevalEntry(11416, "GOTR_GUARDIAN_EARTH", "Strong elemental guardian", "npctypes"),
            new GamevalEntry(11417, "GOTR_GUARDIAN_FIRE", "Overcharged elemental guardian", "npctypes"),
            new GamevalEntry(11418, "GOTR_BARRIER_NPC_TIER1", "gotr_barrier_npc_tier1", "npctypes"),
            new GamevalEntry(11419, "GOTR_BARRIER_NPC_TIER1_LARGE", "gotr_barrier_npc_tier1_large", "npctypes"),
            new GamevalEntry(11420, "GOTR_BARRIER_NPC_TIER2", "gotr_barrier_npc_tier2", "npctypes"),
            new GamevalEntry(11421, "GOTR_BARRIER_NPC_TIER2_LARGE", "gotr_barrier_npc_tier2_large", "npctypes"),
            new GamevalEntry(11422, "GOTR_BARRIER_NPC_TIER3", "gotr_barrier_npc_tier3", "npctypes"),
            new GamevalEntry(11423, "GOTR_BARRIER_NPC_TIER3_LARGE", "gotr_barrier_npc_tier3_large", "npctypes"),
            new GamevalEntry(11424, "GOTR_BARRIER_NPC_TIER4", "gotr_barrier_npc_tier4", "npctypes"),
            new GamevalEntry(11425, "GOTR_BARRIER_NPC_TIER4_LARGE", "gotr_barrier_npc_tier4_large", "npctypes"),
            new GamevalEntry(11426, "GOTR_TAMARA_PARENT", "gotr_tamara_parent", "npctypes"),
            new GamevalEntry(11427, "FORESTRY_FORESTER_NOSTORAGE", "Friendly Forester", "npctypes"),
            new GamevalEntry(11428, "SKILLPET_RUNECRAFTING_GOTR", "Greatish guardian", "npctypes"),
            new GamevalEntry(11429, "ABYSSAL_PET", "Abyssal protector", "npctypes"),
            new GamevalEntry(11430, "GNOME_BRIMSTAIL_1OP", "Brimstail", "npctypes"),
            new GamevalEntry(11431, "GNOME_BRIMSTAIL_2OP", "Brimstail", "npctypes"),
            new GamevalEntry(11432, "HEAD_WIZARD_1OP", "Archmage Sedridor", "npctypes"),
            new GamevalEntry(11433, "HEAD_WIZARD_2OP", "Archmage Sedridor", "npctypes"),
            new GamevalEntry(11434, "AUBURY_2OP", "Aubury", "npctypes"),
            new GamevalEntry(11435, "AUBURY_3OP", "Aubury", "npctypes"),
            new GamevalEntry(11436, "TOTE_PERSTEN_ALKHARID_CHILD", "Wizard Persten", "npctypes"),
            new GamevalEntry(11437, "TOTE_PERSTEN_TOWER_CHILD", "Wizard Persten", "npctypes"),
            new GamevalEntry(11438, "TOTE_PERSTEN_CUTSCENE", "Wizard Persten", "npctypes"),
            new GamevalEntry(11439, "TOTE_PERSTEN_TEMPLE", "Wizard Persten", "npctypes"),
            new GamevalEntry(11440, "TOTE_TAMARA_WIZARD_TOWER_CHILD", "Apprentice Tamara", "npctypes"),
            new GamevalEntry(11441, "TOTE_TAMARA_CUTSCENE", "Apprentice Tamara", "npctypes"),
            new GamevalEntry(11442, "TOTE_TAMARA_TEMPLE", "Apprentice Tamara", "npctypes"),
            new GamevalEntry(11443, "TOTE_CORDELIA_WIZARD_TOWER_CHILD", "Apprentice Cordelia", "npctypes"),
            new GamevalEntry(11444, "TOTE_CORDELIA_CUTSCENE", "Apprentice Cordelia", "npctypes"),
            new GamevalEntry(11445, "TOTE_CORDELIA_TEMPLE", "Apprentice Cordelia", "npctypes"),
            new GamevalEntry(11446, "TOTE_FELIX_WIZARD_TOWER_CHILD", "Apprentice Felix", "npctypes"),
            new GamevalEntry(11447, "TOTE_FELIX_CUTSCENE", "Apprentice Felix", "npctypes"),
            new GamevalEntry(11448, "TOTE_FELIX_TEMPLE", "Apprentice Felix", "npctypes"),
            new GamevalEntry(11449, "TOTE_TRAIBORN_CUTSCENE", "Wizard Traiborn", "npctypes"),
            new GamevalEntry(11450, "TOTE_SEDRIDOR_CUTSCENE", "Archmage Sedridor", "npctypes"),
            new GamevalEntry(11451, "TOTE_VOICE_1", "Mysterious Voice", "npctypes"),
            new GamevalEntry(11452, "TOTE_VOICE_2", "Mysterious Voice", "npctypes"),
            new GamevalEntry(11453, "TOTE_ABYSSAL_PYRAMID_CUTSCENE", "Abyssal guardian", "npctypes"),
            new GamevalEntry(11454, "TOTE_ABYSSAL_WALKER_CUTSCENE", "Abyssal walker", "npctypes"),
            new GamevalEntry(11455, "TOTE_GREAT_GUARDIAN_NOOP", "The Great Guardian", "npctypes"),
            new GamevalEntry(11456, "TOTE_GREAT_GUARDIAN", "The Great Guardian", "npctypes"),
            new GamevalEntry(11457, "TOTE_PERSTEN_ALKHARID_PARENT", "tote_persten_alkharid_parent", "npctypes"),
            new GamevalEntry(11458, "TOTE_PERSTEN_TOWER_PARENT", "tote_persten_tower_parent", "npctypes"),
            new GamevalEntry(11459, "TOTE_TAMARA_WIZARD_TOWER_PARENT", "tote_tamara_wizard_tower_parent", "npctypes"),
            new GamevalEntry(11460, "TOTE_CORDELIA_WIZARD_TOWER_PARENT", "tote_cordelia_wizard_tower_parent", "npctypes"),
            new GamevalEntry(11461, "TOTE_FELIX_WIZARD_TOWER_PARENT", "tote_felix_wizard_tower_parent", "npctypes"),
            new GamevalEntry(11462, "BCS_MENAPHITE_AKH_SHADOW", "Menaphite Shadow", "npctypes"),
            new GamevalEntry(11463, "ARCEUUS_REANIMATED_HELLHOUND", "Reanimated hellhound", "npctypes"),
            new GamevalEntry(11464, "GOTR_TAMARA_1OP", "Apprentice Tamara", "npctypes"),
            new GamevalEntry(11465, "GOTR_TAMARA_2OP", "Apprentice Tamara", "npctypes"),
            new GamevalEntry(11466, "BLAST_FURNACE_SMITHING_CATALYST", "Smithing catalyst", "npctypes"),
            new GamevalEntry(11467, "GIANTS_FOUNDRY_KOVAC_FAKE_ATTACK", "Hill Giant", "npctypes"),
            new GamevalEntry(11468, "GIANTS_FOUNDRY_KOVAC_QUEST", "Kovac", "npctypes"),
            new GamevalEntry(11469, "GIANTS_FOUNDRY_KOVAC_QUEST_CUTSCENE", "Kovac", "npctypes"),
            new GamevalEntry(11470, "GIANTS_FOUNDRY_KOVAC_1OP", "Kovac", "npctypes"),
            new GamevalEntry(11471, "EASTER22_REWARD_CRATE_NPC", "easter22_reward_crate_npc", "npctypes"),
            new GamevalEntry(11472, "GIANTS_FOUNDRY_KOVAC", "Kovac", "npctypes"),
            new GamevalEntry(11473, "NTK_TARIK_NOSPOTS", "Tarik", "npctypes"),
            new GamevalEntry(11474, "BCS_MAISA_VIS", "Maisa", "npctypes"),
            new GamevalEntry(11475, "BCS_MAISA_CUTSCENE", "Maisa", "npctypes"),
            new GamevalEntry(11476, "BCS_MAISA_CUTSCENE_ARMED", "Maisa", "npctypes"),
            new GamevalEntry(11477, "BCS_MAISA_COMBAT", "Maisa", "npctypes"),
            new GamevalEntry(11478, "BCS_MEHHAR_NONAME", "Spirit", "npctypes"),
            new GamevalEntry(11479, "BCS_MEHHAR_NAME", "Mehhar", "npctypes"),
            new GamevalEntry(11480, "BCS_SCABARAS_HIGH_PRIEST", "High Priest of Scabaras", "npctypes"),
            new GamevalEntry(11481, "BCS_SCABARAS_HIGH_PRIEST_CUTSCENE", "High Priest of Scabaras", "npctypes"),
            new GamevalEntry(11482, "BCS_CHAMPION_CUTSCENE", "Champion of Scabaras", "npctypes"),
            new GamevalEntry(11483, "BCS_CHAMPION_COMBAT", "XJ", "npctypes"),
            new GamevalEntry(11484, "BCS_CHAMPION_SCARAB_SWARM", "Scarab Swarm", "npctypes"),
            new GamevalEntry(11485, "BCS_CHAMPION_RIFT", "Shadow Rift", "npctypes"),
            new GamevalEntry(11486, "BCS_OSMAN_VIS", "Osman", "npctypes"),
            new GamevalEntry(11487, "BCS_OSMAN_CUTSCENE", "Osman", "npctypes"),
            new GamevalEntry(11488, "BCS_OSMAN_POSTFIGHT", "bcs_osman_postfight", "npctypes"),
            new GamevalEntry(11489, "BCS_SELIM_VIS", "Selim", "npctypes"),
            new GamevalEntry(11490, "BCS_MENAPHITE_AKH_CUTSCENE", "Menaphite Akh", "npctypes"),
            new GamevalEntry(11491, "BCS_MENAPHITE_AKH_CUTSCENE_SPAWNING", "Menaphite Akh", "npctypes"),
            new GamevalEntry(11492, "BCS_MENAPHITE_AKH_COMBAT", "Menaphite Akh", "npctypes"),
            new GamevalEntry(11493, "BCS_MENAPHITE_AKH_COMBAT_CHARGING", "Menaphite Akh", "npctypes"),
            new GamevalEntry(11494, "GIANTS_FOUNDRY_KOVAC_MULTI_OUTSIDE", "giants_foundry_kovac_multi_outside", "npctypes"),
            new GamevalEntry(11495, "BCS_MENAPHITE_AKH_1", "Menaphite Akh", "npctypes"),
            new GamevalEntry(11496, "BCS_MENAPHITE_AKH_2", "Menaphite Akh", "npctypes"),
            new GamevalEntry(11497, "BCS_MENAPHITE_AKH_3", "Menaphite Akh", "npctypes"),
            new GamevalEntry(11498, "BCS_MENAPHITE_AKH_4", "Menaphite Akh", "npctypes"),
            new GamevalEntry(11499, "BCS_COENUS_CUTSCENE", "Coenus", "npctypes"),
            new GamevalEntry(11500, "BCS_JABARI_CUTSCENE", "Jabari", "npctypes"),
            new GamevalEntry(11501, "BCS_KEMESIS_CUTSCENE", "Pharaoh Kemesis", "npctypes"),
            new GamevalEntry(11502, "BCS_HIGH_PRIEST_CUTSCENE", "High Priest", "npctypes"),
            new GamevalEntry(11503, "BCS_PRIEST_CUTSCENE", "Priest", "npctypes"),
            new GamevalEntry(11504, "BCS_MENAPHOS_GUARD_CUTSCENE_1", "Menaphite Guard", "npctypes"),
            new GamevalEntry(11505, "BCS_MENAPHOS_GUARD_CUTSCENE_2", "Menaphite Guard", "npctypes"),
            new GamevalEntry(11506, "BCS_MENAPHOS_GUARD_CUTSCENE_3", "Menaphite Guard", "npctypes"),
            new GamevalEntry(11507, "BCS_MENAPHOS_GUARD_CUTSCENE_4", "Menaphite Guard", "npctypes"),
            new GamevalEntry(11508, "BCS_SCARAB_MAGE", "Scarab Mage", "npctypes"),
            new GamevalEntry(11509, "BCS_SCARAB_SWARM", "Scarab Swarm", "npctypes"),
            new GamevalEntry(11510, "BCS_SCARAB_MAGE_FRIENDLY_N", "Scarab Mage", "npctypes"),
            new GamevalEntry(11511, "BCS_SCARAB_MAGE_FRIENDLY_S", "Scarab Mage", "npctypes"),
            new GamevalEntry(11512, "BCS_CROCODILE", "bcs_crocodile", "npctypes"),
            new GamevalEntry(11513, "BCS_CROCODILE_VIS", "Crocodile", "npctypes"),
            new GamevalEntry(11514, "BCS_CROCODILE_NAMED", "Roger", "npctypes"),
            new GamevalEntry(11515, "BCS_NECROPOLIS_GUARD_1_VIS", "Menaphite Guard", "npctypes"),
            new GamevalEntry(11516, "BCS_NECROPOLIS_GUARD_2_VIS", "Menaphite Guard", "npctypes"),
            new GamevalEntry(11517, "BCS_NECROPOLIS_GUARD_3_VIS", "Menaphite Guard", "npctypes"),
            new GamevalEntry(11518, "BCS_NECROPOLIS_GUARD_4_VIS", "Menaphite Guard", "npctypes"),
            new GamevalEntry(11519, "BCS_NECROPOLIS_GUARD_1_NOOP", "Menaphite Guard", "npctypes"),
            new GamevalEntry(11520, "BCS_NECROPOLIS_GUARD_2_NOOP", "Menaphite Guard", "npctypes"),
            new GamevalEntry(11521, "BCS_NECROPOLIS_GUARD_3_NOOP", "Menaphite Guard", "npctypes"),
            new GamevalEntry(11522, "BCS_NECROPOLIS_GUARD_4_NOOP", "Menaphite Guard", "npctypes"),
            new GamevalEntry(11523, "BCS_NECROPOLIS_GUARD_1_CUTSCENE", "Menaphite Guard", "npctypes"),
            new GamevalEntry(11524, "BCS_NECROPOLIS_GUARD_2_CUTSCENE", "Menaphite Guard", "npctypes"),
            new GamevalEntry(11525, "BCS_NECROPOLIS_GUARD_1_CUTSCENE_ALT", "Menaphite Guard", "npctypes"),
            new GamevalEntry(11526, "BCS_NECROPOLIS_GUARD_2_CUTSCENE_ALT", "Menaphite Guard", "npctypes"),
            new GamevalEntry(11527, "BCS_NECROPOLIS_GUARD_2_COMBAT", "Menaphite Guard", "npctypes"),
            new GamevalEntry(11528, "BCS_NECROPOLIS_HEADGUARD_CUTSCENE", "Head Menaphite Guard", "npctypes"),
            new GamevalEntry(11529, "BCS_NECROPOLIS_HEADGUARD_COMBAT", "Head Menaphite Guard", "npctypes"),
            new GamevalEntry(11530, "BCS_NECROPOLIS_HEADGUARD_DYING", "Head Menaphite Guard", "npctypes"),
            new GamevalEntry(11531, "BCS_NECROPOLIS_HEADGUARD_UNCONSCIOUS", "Head Menaphite Guard", "npctypes"),
            new GamevalEntry(11532, "BCS_NECROPOLIS_HEADGUARD_INJURED", "Head Menaphite Guard", "npctypes"),
            new GamevalEntry(11533, "BCS_NECROPOLIS_CITIZEN_1", "Citizen", "npctypes"),
            new GamevalEntry(11534, "BCS_NECROPOLIS_CITIZEN_2", "Citizen", "npctypes"),
            new GamevalEntry(11535, "BCS_NECROPOLIS_CITIZEN_3", "Citizen", "npctypes"),
            new GamevalEntry(11536, "BCS_NECROPOLIS_CITIZEN_4", "Citizen", "npctypes"),
            new GamevalEntry(11537, "BCS_NECROPOLIS_CITIZEN_5", "Citizen", "npctypes"),
            new GamevalEntry(11538, "BCS_NECROPOLIS_CITIZEN_6", "Citizen", "npctypes"),
            new GamevalEntry(11539, "BCS_NECROPOLIS_CITIZEN_7", "Citizen", "npctypes"),
            new GamevalEntry(11540, "BCS_NECROPOLIS_CITIZEN_8", "Citizen", "npctypes"),
            new GamevalEntry(11541, "BCS_NECROPOLIS_CITIZEN_1_NOOP", "Citizen", "npctypes"),
            new GamevalEntry(11542, "BCS_NECROPOLIS_CITIZEN_2_NOOP", "Citizen", "npctypes"),
            new GamevalEntry(11543, "BCS_NECROPOLIS_CITIZEN_3_NOOP", "Citizen", "npctypes"),
            new GamevalEntry(11544, "BCS_NECROPOLIS_CITIZEN_4_NOOP", "Citizen", "npctypes"),
            new GamevalEntry(11545, "BCS_NECROPOLIS_CITIZEN_5_NOOP", "Citizen", "npctypes"),
            new GamevalEntry(11546, "BCS_NECROPOLIS_CITIZEN_6_NOOP", "Citizen", "npctypes"),
            new GamevalEntry(11547, "BCS_NECROPOLIS_CITIZEN_7_NOOP", "Citizen", "npctypes"),
            new GamevalEntry(11548, "BCS_NECROPOLIS_CITIZEN_8_NOOP", "Citizen", "npctypes"),
            new GamevalEntry(11549, "BCS_NECROPOLIS_CITIZEN_1_CUTSCENE", "Citizen", "npctypes"),
            new GamevalEntry(11550, "BCS_NECROPOLIS_CITIZEN_2_CUTSCENE", "Citizen", "npctypes"),
            new GamevalEntry(11551, "BCS_NECROPOLIS_CITIZEN_3_CUTSCENE", "Citizen", "npctypes"),
            new GamevalEntry(11552, "BCS_NECROPOLIS_CITIZEN_4_CUTSCENE", "Citizen", "npctypes"),
            new GamevalEntry(11553, "BCS_NECROPOLIS_CITIZEN_5_CUTSCENE", "Citizen", "npctypes"),
            new GamevalEntry(11554, "BCS_NECROPOLIS_CITIZEN_6_CUTSCENE", "Citizen", "npctypes"),
            new GamevalEntry(11555, "BCS_NECROPOLIS_CITIZEN_7_CUTSCENE", "Citizen", "npctypes"),
            new GamevalEntry(11556, "BCS_NECROPOLIS_CITIZEN_8_CUTSCENE", "Citizen", "npctypes"),
            new GamevalEntry(11557, "BCS_NECROPOLIS_POSTQUEST_CITIZEN_1_VIS", "Citizen", "npctypes"),
            new GamevalEntry(11558, "BCS_NECROPOLIS_POSTQUEST_CITIZEN_2_VIS", "Citizen", "npctypes"),
            new GamevalEntry(11559, "BCS_BOLT_NPC", "bcs_bolt_npc", "npctypes"),
            new GamevalEntry(11560, "GIANTS_FOUNDRY_KOVAC_MULTI", "giants_foundry_kovac_multi", "npctypes"),
            new GamevalEntry(11561, "_100_SELIM", "Selim", "npctypes"),
            new GamevalEntry(11562, "CONTACT_JEX_CUTSCENE", "Jex", "npctypes"),
            new GamevalEntry(11563, "CONTACT_JEX_NOSPOTS", "Jex", "npctypes"),
            new GamevalEntry(11564, "CONTACT_MAISA_CUTSCENE", "Maisa", "npctypes"),
            new GamevalEntry(11565, "CONTACT_OSMAN_CUTSCENE", "Osman", "npctypes"),
            new GamevalEntry(11566, "CONTACT_OSMAN_CUTSCENE_2", "Osman", "npctypes"),
            new GamevalEntry(11567, "CONTACT_OSMAN_CAVE", "contact_osman_cave", "npctypes"),
            new GamevalEntry(11568, "CONTACT_OSMAN_CAVE_INSTANCE", "contact_osman_cave_instance", "npctypes"),
            new GamevalEntry(11569, "CONTACT_SCARAB_SWARM", "Scarab Swarm", "npctypes"),
            new GamevalEntry(11570, "CONTACT_MENAPHOS_GUARD_01_MASK", "Menaphite Guard", "npctypes"),
            new GamevalEntry(11571, "CONTACT_MENAPHOS_GUARD_01_NOMASK", "Menaphite Guard", "npctypes"),
            new GamevalEntry(11572, "CONTACT_MENAPHOS_GUARD_02_MASK", "Menaphite Guard", "npctypes"),
            new GamevalEntry(11573, "CONTACT_MENAPHOS_GUARD_02_NOMASK", "Menaphite Guard", "npctypes"),
            new GamevalEntry(11574, "CONTACT_MENAPHOS_GUARD_03_MASK", "Menaphite Guard", "npctypes"),
            new GamevalEntry(11575, "CONTACT_MENAPHOS_GUARD_03_NOMASK", "Menaphite Guard", "npctypes"),
            new GamevalEntry(11576, "CONTACT_MENAPHOS_GUARD_HEAD", "Coenus", "npctypes"),
            new GamevalEntry(11577, "JOE_VIS", "Joe", "npctypes"),
            new GamevalEntry(11578, "LADY_KELI_VIS", "Lady Keli", "npctypes"),
            new GamevalEntry(11579, "PRINCE_ALI_VIS_BLACKEYE", "Prince Ali", "npctypes"),
            new GamevalEntry(11580, "PRINCE_ALI_VIS", "Prince Ali", "npctypes"),
            new GamevalEntry(11581, "ICS_LITTLE_CROC_BLOCKED", "Crocodile", "npctypes"),
            new GamevalEntry(11582, "ICS_LITTLE_CROC_NORMAL", "Crocodile", "npctypes"),
            new GamevalEntry(11583, "ICS_LITTLE_JACKAL_ALT", "Jackal", "npctypes"),
            new GamevalEntry(11584, "ICS_LITTLE_LOCUST_VIS", "Locust", "npctypes"),
            new GamevalEntry(11585, "ULLEK_LOCUST", "Locust", "npctypes"),
            new GamevalEntry(11586, "ICS_LITTLE_PLAGUE_FROG_VIS", "Plague frog", "npctypes"),
            new GamevalEntry(11587, "ICS_LITTLE_PLAGUE_COW1_VIS", "Plague cow", "npctypes"),
            new GamevalEntry(11588, "ICS_LITTLE_PLAGUE_COW2_VIS", "Plague cow", "npctypes"),
            new GamevalEntry(11589, "ICS_LITTLE_PLAGUE_COW3_VIS", "Plague cow", "npctypes"),
            new GamevalEntry(11590, "ICS_LITTLE_REDHEADLADY_CEREMONY", "Wanderer", "npctypes"),
            new GamevalEntry(11591, "ICS_LITTLE_DEVOURER_CEREMONY", "Amascut", "npctypes"),
            new GamevalEntry(11592, "ICS_LITTLE_WORKER1", "Worker", "npctypes"),
            new GamevalEntry(11593, "ICS_LITTLE_WORKER1_NOSPOTS", "Worker", "npctypes"),
            new GamevalEntry(11594, "ICS_LITTLE_WORKER2", "Worker", "npctypes"),
            new GamevalEntry(11595, "ICS_LITTLE_WORKER2_NOSPOTS", "Worker", "npctypes"),
            new GamevalEntry(11596, "ICS_LITTLE_EMBALMER_NOSPOTS", "Embalmer", "npctypes"),
            new GamevalEntry(11597, "ICS_LITTLE_CARPENTER_NOSPOTS", "Carpenter", "npctypes"),
            new GamevalEntry(11598, "ICS_LITTLE_LINEN1_1OP", "Raetul", "npctypes"),
            new GamevalEntry(11599, "ICS_LITTLE_LINEN1_2OP", "Raetul", "npctypes"),
            new GamevalEntry(11600, "ICS_LITTLE_LINEN1_NOSPOTS", "Raetul", "npctypes"),
            new GamevalEntry(11601, "ICS_LITTLE_LINEN2_NOSPOTS", "Siamun", "npctypes"),
            new GamevalEntry(11602, "ICS_LITTLE_HIPRIEST_CEREMONY_NOOP", "High Priest", "npctypes"),
            new GamevalEntry(11603, "ICS_LITTLE_HIPRIEST_CEREMONY_OP", "High Priest", "npctypes"),
            new GamevalEntry(11604, "ICS_LITTLE_HIPRIEST_2_NOOP", "High Priest", "npctypes"),
            new GamevalEntry(11605, "ICS_LITTLE_HIPRIEST_NOSPOTS", "High Priest", "npctypes"),
            new GamevalEntry(11606, "ICS_LITTLE_PRIEST_CEREMONY", "Priest", "npctypes"),
            new GamevalEntry(11607, "ICS_LITTLE_PRIEST_NOSPOTS", "Priest", "npctypes"),
            new GamevalEntry(11608, "ICS_LITTLE_PRIEST_CEREMONY_POSSESSED", "Possessed Priest", "npctypes"),
            new GamevalEntry(11609, "ICS_LITTLE_PRIESTDOORMAN_ALT", "Priest", "npctypes"),
            new GamevalEntry(11610, "ICS_LITTLE_PRIESTDOORMAN_NOSPOTS", "Priest", "npctypes"),
            new GamevalEntry(11611, "BCS_NECROPOLIS_CITIZEN_S7", "bcs_necropolis_citizen_s7", "npctypes"),
            new GamevalEntry(11612, "BCS_NECROPOLIS_CITIZEN_S8", "bcs_necropolis_citizen_s8", "npctypes"),
            new GamevalEntry(11613, "BCS_NECROPOLIS_CITIZEN_N1", "bcs_necropolis_citizen_n1", "npctypes"),
            new GamevalEntry(11614, "BCS_NECROPOLIS_CITIZEN_N2", "bcs_necropolis_citizen_n2", "npctypes"),
            new GamevalEntry(11615, "BCS_NECROPOLIS_CITIZEN_N3", "bcs_necropolis_citizen_n3", "npctypes"),
            new GamevalEntry(11616, "BCS_NECROPOLIS_CITIZEN_N4", "bcs_necropolis_citizen_n4", "npctypes"),
            new GamevalEntry(11617, "BCS_NECROPOLIS_CITIZEN_N5", "bcs_necropolis_citizen_n5", "npctypes"),
            new GamevalEntry(11618, "BCS_NECROPOLIS_CITIZEN_N6", "bcs_necropolis_citizen_n6", "npctypes"),
            new GamevalEntry(11619, "BCS_NECROPOLIS_CITIZEN_N7", "bcs_necropolis_citizen_n7", "npctypes"),
            new GamevalEntry(11620, "BCS_NECROPOLIS_CITIZEN_N8", "bcs_necropolis_citizen_n8", "npctypes"),
            new GamevalEntry(11621, "BCS_NECROPOLIS_CITIZEN_E1", "bcs_necropolis_citizen_e1", "npctypes"),
            new GamevalEntry(11622, "BCS_NECROPOLIS_CITIZEN_E2", "bcs_necropolis_citizen_e2", "npctypes"),
            new GamevalEntry(11623, "BCS_NECROPOLIS_CITIZEN_E3", "bcs_necropolis_citizen_e3", "npctypes"),
            new GamevalEntry(11624, "BCS_NECROPOLIS_CITIZEN_E4", "bcs_necropolis_citizen_e4", "npctypes"),
            new GamevalEntry(11625, "BCS_NECROPOLIS_CITIZEN_E5", "bcs_necropolis_citizen_e5", "npctypes"),
            new GamevalEntry(11626, "BCS_NECROPOLIS_CITIZEN_E6", "bcs_necropolis_citizen_e6", "npctypes"),
            new GamevalEntry(11627, "BCS_NECROPOLIS_CITIZEN_E7", "bcs_necropolis_citizen_e7", "npctypes"),
            new GamevalEntry(11628, "BCS_NECROPOLIS_CITIZEN_E8", "bcs_necropolis_citizen_e8", "npctypes"),
            new GamevalEntry(11629, "BCS_NECROPOLIS_CITIZEN_W1", "bcs_necropolis_citizen_w1", "npctypes"),
            new GamevalEntry(11630, "BCS_NECROPOLIS_CITIZEN_W2", "bcs_necropolis_citizen_w2", "npctypes"),
            new GamevalEntry(11631, "BCS_NECROPOLIS_CITIZEN_W3", "bcs_necropolis_citizen_w3", "npctypes"),
            new GamevalEntry(11632, "BCS_NECROPOLIS_CITIZEN_W4", "bcs_necropolis_citizen_w4", "npctypes"),
            new GamevalEntry(11633, "BCS_NECROPOLIS_CITIZEN_W5", "bcs_necropolis_citizen_w5", "npctypes"),
            new GamevalEntry(11634, "BCS_NECROPOLIS_CITIZEN_W6", "bcs_necropolis_citizen_w6", "npctypes"),
            new GamevalEntry(11635, "BCS_NECROPOLIS_CITIZEN_W7", "bcs_necropolis_citizen_w7", "npctypes"),
            new GamevalEntry(11636, "BCS_NECROPOLIS_CITIZEN_W8", "bcs_necropolis_citizen_w8", "npctypes"),
            new GamevalEntry(11637, "BCS_NECROPOLIS_POSTQUEST_CITIZEN_1", "bcs_necropolis_postquest_citizen_1", "npctypes"),
            new GamevalEntry(11638, "BCS_NECROPOLIS_POSTQUEST_CITIZEN_2", "bcs_necropolis_postquest_citizen_2", "npctypes"),
            new GamevalEntry(11639, "CONTACT_MENAPHOS_GUARD_01", "contact_menaphos_guard_01", "npctypes"),
            new GamevalEntry(11640, "CONTACT_MENAPHOS_GUARD_02", "contact_menaphos_guard_02", "npctypes"),
            new GamevalEntry(11641, "CONTACT_MENAPHOS_GUARD_03", "contact_menaphos_guard_03", "npctypes"),
            new GamevalEntry(11642, "JOE", "joe", "npctypes"),
            new GamevalEntry(11643, "LADY_KELI", "lady_keli", "npctypes"),
            new GamevalEntry(11644, "PRINCE_ALI_PRISON", "prince_ali_prison", "npctypes"),
            new GamevalEntry(11645, "PRINCE_ALI_PALACE", "prince_ali_palace", "npctypes"),
            new GamevalEntry(11646, "ICS_LITTLE_PLAGUE_COW1", "ics_little_plague_cow1", "npctypes"),
            new GamevalEntry(11647, "ICS_LITTLE_PLAGUE_COW2", "ics_little_plague_cow2", "npctypes"),
            new GamevalEntry(11648, "ICS_LITTLE_PLAGUE_COW3", "ics_little_plague_cow3", "npctypes"),
            new GamevalEntry(11649, "ICS_LITTLE_HIPRIEST_CEREMONY", "ics_little_hipriest_ceremony", "npctypes"),
            new GamevalEntry(11650, "CASTLEWARS_JUDGE_MODEL", "Lanthus", "npctypes"),
            new GamevalEntry(11651, "CLAN_MEDIEVAL_STOOL_CAT", "Hannibal", "npctypes"),
            new GamevalEntry(11652, "POH_WARDEN_PET_TUMEKEN", "Tumeken's Guardian", "npctypes"),
            new GamevalEntry(11653, "POH_WARDEN_PET_ELIDINIS", "Elidinis' Guardian", "npctypes"),
            new GamevalEntry(11654, "TOA_APMEKEN_CAPTURED_VIS", "Apmeken", "npctypes"),
            new GamevalEntry(11655, "TOA_APMEKEN_FREED_VIS", "Apmeken", "npctypes"),
            new GamevalEntry(11656, "TOA_APMEKEN_NEXUS_VIS", "Apmeken", "npctypes"),
            new GamevalEntry(11657, "TOA_CRONDIS_CAPTURED_VIS", "Crondis", "npctypes"),
            new GamevalEntry(11658, "PRIDE22_GILBERT", "Gilbert", "npctypes"),
            new GamevalEntry(11659, "TOA_CRONDIS_FREED_VIS", "Crondis", "npctypes"),
            new GamevalEntry(11660, "TOA_CRONDIS_NEXUS_VIS", "Crondis", "npctypes"),
            new GamevalEntry(11661, "TOA_SCABARAS_CAPTURED_VIS", "Scabaras", "npctypes"),
            new GamevalEntry(11662, "TOA_SCABARAS_FREED_VIS", "Scabaras", "npctypes"),
            new GamevalEntry(11663, "TOA_SCABARAS_NEXUS_VIS", "Scabaras", "npctypes"),
            new GamevalEntry(11664, "PVPA_GUARD_1", "Arena Guard Fronk", "npctypes"),
            new GamevalEntry(11665, "PVPA_GUARD_4", "Arena Guard Nikkolas", "npctypes"),
            new GamevalEntry(11666, "PVPA_GUARD_5", "Arena Guard Fawry", "npctypes"),
            new GamevalEntry(11667, "PVPA_GUARD_6", "Arena Guard Yon", "npctypes"),
            new GamevalEntry(11668, "PVPA_GUARD_7", "Arena Guard Drakno", "npctypes"),
            new GamevalEntry(11669, "PVPA_GUARD_8", "Arena Guard Rachi", "npctypes"),
            new GamevalEntry(11670, "PVPA_GUARD_2_MODEL", "Arena Guard Joby", "npctypes"),
            new GamevalEntry(11671, "PVPA_GUARD_3_MODEL", "Arena Guard Beni", "npctypes"),
            new GamevalEntry(11672, "PVPA_1V1_GUIDE", "1v1 Tournament Guide", "npctypes"),
            new GamevalEntry(11673, "PVPA_DUEL_GUIDE", "Duel Guide", "npctypes"),
            new GamevalEntry(11674, "PVPA_REPAIRMAN", "Chris", "npctypes"),
            new GamevalEntry(11675, "PVPA_NPC_MAGIC1", "Fighter", "npctypes"),
            new GamevalEntry(11676, "PVPA_NPC_MAGIC2", "Fighter", "npctypes"),
            new GamevalEntry(11677, "PVPA_NPC_MAGIC3", "Fighter", "npctypes"),
            new GamevalEntry(11678, "PVPA_NPC_RANGED1", "Fighter", "npctypes"),
            new GamevalEntry(11679, "PVPA_NPC_RANGED2", "Fighter", "npctypes"),
            new GamevalEntry(11680, "PVPA_NPC_RANGED3", "Fighter", "npctypes"),
            new GamevalEntry(11681, "PVPA_NPC_MELEE1", "Fighter", "npctypes"),
            new GamevalEntry(11682, "PVPA_NPC_MELEE2", "Fighter", "npctypes"),
            new GamevalEntry(11683, "PVPA_NPC_MELEE3", "Fighter", "npctypes"),
            new GamevalEntry(11684, "PVPA_GUARD_2", "pvpa_guard_2", "npctypes"),
            new GamevalEntry(11685, "PVPA_GUARD_3", "pvpa_guard_3", "npctypes"),
            new GamevalEntry(11686, "TOA_HET_CAPTURED_VIS", "Het", "npctypes"),
            new GamevalEntry(11687, "TOA_HET_FREED_VIS", "Het", "npctypes"),
            new GamevalEntry(11688, "TOA_HET_NEXUS_VIS", "Het", "npctypes"),
            new GamevalEntry(11689, "TOA_OSMUMTEN_VIS", "Osmumten", "npctypes"),
            new GamevalEntry(11690, "TOA_OSMUMTEN_WARDENS_VIS", "Osmumten", "npctypes"),
            new GamevalEntry(11691, "TOA_OSMUMTEN_VAULT_VIS_0", "Spirit", "npctypes"),
            new GamevalEntry(11692, "TOA_OSMUMTEN_VAULT_VIS_1", "Osmumten", "npctypes"),
            new GamevalEntry(11693, "TOA_OSMUMTEN_VAULT_VIS_2", "Osmumten", "npctypes"),
            new GamevalEntry(11694, "TOA_MIDRAIDLOOT_TRADER", "Helpful Spirit", "npctypes"),
            new GamevalEntry(11695, "TOA_PLAYER_GHOST", "Ghost", "npctypes"),
            new GamevalEntry(11696, "TOA_AMASCUT_VIS", "Amascut", "npctypes"),
            new GamevalEntry(11697, "TOA_SCABARAS_SCARAB", "Scarab", "npctypes"),
            new GamevalEntry(11698, "TOA_SCABARAS_GUESSER_OBELISK", "Obelisk", "npctypes"),
            new GamevalEntry(11699, "TOA_SCABARAS_GUESSER_OBELISK_HIT", "Obelisk", "npctypes"),
            new GamevalEntry(11700, "TOA_CRONDIS_TREE_1", "Palm of Resourcefulness", "npctypes"),
            new GamevalEntry(11701, "TOA_CRONDIS_TREE_2", "Palm of Resourcefulness", "npctypes"),
            new GamevalEntry(11702, "TOA_CRONDIS_TREE_3", "Palm of Resourcefulness", "npctypes"),
            new GamevalEntry(11703, "TOA_CRONDIS_TREE_4", "Palm of Resourcefulness", "npctypes"),
            new GamevalEntry(11704, "TOA_CRONDIS_TREE_5", "Palm of Resourcefulness", "npctypes"),
            new GamevalEntry(11705, "TOA_CRONDIS_CROCODILE", "Crocodile", "npctypes"),
            new GamevalEntry(11706, "TOA_HET_GOAL", "Het's Seal (protected)", "npctypes"),
            new GamevalEntry(11707, "TOA_HET_GOAL_VULNERABLE", "Het's Seal (weakened)", "npctypes"),
            new GamevalEntry(11708, "TOA_HET_ORB", "Orb of Darkness", "npctypes"),
            new GamevalEntry(11709, "TOA_PATH_APMEKEN_BABOON_MELEE_1", "Baboon Brawler", "npctypes"),
            new GamevalEntry(11710, "TOA_PATH_APMEKEN_BABOON_RANGED_1", "Baboon Thrower", "npctypes"),
            new GamevalEntry(11711, "TOA_PATH_APMEKEN_BABOON_MAGIC_1", "Baboon Mage", "npctypes"),
            new GamevalEntry(11712, "TOA_PATH_APMEKEN_BABOON_MELEE_2", "Baboon Brawler", "npctypes"),
            new GamevalEntry(11713, "TOA_PATH_APMEKEN_BABOON_RANGED_2", "Baboon Thrower", "npctypes"),
            new GamevalEntry(11714, "TOA_PATH_APMEKEN_BABOON_MAGIC_2", "Baboon Mage", "npctypes"),
            new GamevalEntry(11715, "TOA_PATH_APMEKEN_BABOON_SHAMAN", "Baboon Shaman", "npctypes"),
            new GamevalEntry(11716, "TOA_PATH_APMEKEN_BABOON_ZOMBIE", "Volatile Baboon", "npctypes"),
            new GamevalEntry(11717, "TOA_PATH_APMEKEN_BABOON_CURSED", "Cursed Baboon", "npctypes"),
            new GamevalEntry(11718, "TOA_PATH_APMEKEN_BABOON_THRALL", "Baboon Thrall", "npctypes"),
            new GamevalEntry(11719, "TOA_KEPHRI_BOSS_SHIELDED", "Kephri", "npctypes"),
            new GamevalEntry(11720, "TOA_KEPHRI_BOSS_WEAK", "Kephri", "npctypes"),
            new GamevalEntry(11721, "TOA_KEPHRI_BOSS_ENRAGE", "Kephri", "npctypes"),
            new GamevalEntry(11722, "TOA_KEPHRI_BOSS_DEAD", "Kephri", "npctypes"),
            new GamevalEntry(11723, "TOA_KEPHRI_SHIELD_SCARAB", "Scarab Swarm", "npctypes"),
            new GamevalEntry(11724, "TOA_KEPHRI_GUARDIAN_MELEE", "Soldier Scarab", "npctypes"),
            new GamevalEntry(11725, "TOA_KEPHRI_GUARDIAN_RANGED", "Spitting Scarab", "npctypes"),
            new GamevalEntry(11726, "TOA_KEPHRI_GUARDIAN_MAGE", "Arcane Scarab", "npctypes"),
            new GamevalEntry(11727, "TOA_KEPHRI_SCARAB_RANGEKITE", "Agile Scarab", "npctypes"),
            new GamevalEntry(11728, "KEPHRI_EGG_EXPLODE", "Egg", "npctypes"),
            new GamevalEntry(11729, "KEPHRI_EGG_HATCH", "Egg", "npctypes"),
            new GamevalEntry(11730, "TOA_ZEBAK", "DJ", "npctypes"),
            new GamevalEntry(11731, "TOA_ZEBAK_TAIL", "Zebak's Tail", "npctypes"),
            new GamevalEntry(11732, "TOA_ZEBAK_ENRAGED", "DJ", "npctypes"),
            new GamevalEntry(11733, "TOA_ZEBAK_DEAD", "Zebak", "npctypes"),
            new GamevalEntry(11734, "TOA_ZEBAK_TAIL_DEAD", "Zebak's Tail", "npctypes"),
            new GamevalEntry(11735, "TOA_ZEBAK_JUG", "Jug", "npctypes"),
            new GamevalEntry(11736, "TOA_ZEBAK_JUG_ROLLING", "Jug", "npctypes"),
            new GamevalEntry(11737, "TOA_ZEBAK_SAFESPOT", "Boulder", "npctypes"),
            new GamevalEntry(11738, "TOA_ZEBAK_WAVE", "Wave", "npctypes"),
            new GamevalEntry(11739, "TOA_ZEBAK_WAVE_BLOODY", "Bloody Wave", "npctypes"),
            new GamevalEntry(11740, "TOA_ZEBAK_LANDCROC", "Crocodile", "npctypes"),
            new GamevalEntry(11741, "TOA_ZEBAK_WATERCROC", "Crocodile", "npctypes"),
            new GamevalEntry(11742, "TOA_ZEBAK_BLOOD_CLOUD", "Blood Cloud", "npctypes"),
            new GamevalEntry(11743, "TOA_ZEBAK_BLOOD_CLOUD_SMALL", "Blood Cloud", "npctypes"),
            new GamevalEntry(11744, "SPOTANIM_ZEBAK_RANGED01_NPC", "spotanim_zebak_ranged01_npc", "npctypes"),
            new GamevalEntry(11745, "SPOTANIM_ZEBAK_JUGBREAK_NPC", "spotanim_zebak_jugbreak_npc", "npctypes"),
            new GamevalEntry(11746, "TOA_WARDEN_ELIDINIS_PHASE1_INACTIVE", "Elidinis' Warden", "npctypes"),
            new GamevalEntry(11747, "TOA_WARDEN_TUMEKEN_PHASE1_INACTIVE", "Tumeken's Warden", "npctypes"),
            new GamevalEntry(11748, "TOA_WARDEN_ELIDINIS_PHASE1", "Elidinis' Warden", "npctypes"),
            new GamevalEntry(11749, "TOA_WARDEN_TUMEKEN_PHASE1", "Tumeken's Warden", "npctypes"),
            new GamevalEntry(11750, "TOA_WARDENS_P1_OBELISK_NPC_INACTIVE", "Obelisk", "npctypes"),
            new GamevalEntry(11751, "TOA_WARDENS_P1_OBELISK_NPC", "Obelisk", "npctypes"),
            new GamevalEntry(11752, "TOA_WARDENS_P2_OBELISK_NPC", "Obelisk", "npctypes"),
            new GamevalEntry(11753, "TOA_WARDEN_ELIDINIS_PHASE2_MAGE", "Elidinis' Warden", "npctypes"),
            new GamevalEntry(11754, "TOA_WARDEN_ELIDINIS_PHASE2_RANGE", "Elidinis' Warden", "npctypes"),
            new GamevalEntry(11755, "TOA_WARDEN_ELIDINIS_PHASE2_EXPOSED", "Elidinis' Warden", "npctypes"),
            new GamevalEntry(11756, "TOA_WARDEN_TUMEKEN_PHASE2_MAGE", "Tumeken's Warden", "npctypes"),
            new GamevalEntry(11757, "TOA_WARDEN_TUMEKEN_PHASE2_RANGE", "Tumeken's Warden", "npctypes"),
            new GamevalEntry(11758, "TOA_WARDEN_TUMEKEN_PHASE2_EXPOSED", "Tumeken's Warden", "npctypes"),
            new GamevalEntry(11759, "TOA_WARDEN_ELIDINIS_PHASE3_INACTIVE", "Elidinis' Warden", "npctypes"),
            new GamevalEntry(11760, "TOA_WARDEN_TUMEKEN_PHASE3_INACTIVE", "Tumeken's Warden", "npctypes"),
            new GamevalEntry(11761, "TOA_WARDEN_ELIDINIS_PHASE3", "Elidinis' Warden", "npctypes"),
            new GamevalEntry(11762, "TOA_WARDEN_TUMEKEN_PHASE3", "Tumeken's Warden", "npctypes"),
            new GamevalEntry(11763, "TOA_WARDEN_ELIDINIS_PHASE3_CHARGING", "Elidinis' Warden", "npctypes"),
            new GamevalEntry(11764, "TOA_WARDEN_TUMEKEN_PHASE3_CHARGING", "Tumeken's Warden", "npctypes"),
            new GamevalEntry(11765, "TOA_WARDEN_P3_DEATH_TUMEKEN", "toa_warden_p3_death_tumeken", "npctypes"),
            new GamevalEntry(11766, "TOA_WARDEN_P3_DEATH_ELIDINIS", "toa_warden_p3_death_elidinis", "npctypes"),
            new GamevalEntry(11767, "TOA_AMASCUT_P3", "Phantom", "npctypes"),
            new GamevalEntry(11768, "TOA_AMASCUT_P3_ENRAGE", "Phantom", "npctypes"),
            new GamevalEntry(11769, "TOA_WARDENS_ENERGY", "toa_wardens_energy", "npctypes"),
            new GamevalEntry(11770, "TOA_WARDEN_TUMEKEN_CORE", "Core", "npctypes"),
            new GamevalEntry(11771, "TOA_WARDEN_ELIDINIS_CORE", "Core", "npctypes"),
            new GamevalEntry(11772, "WARDENS_P3_ORB_BLUE", "Energy Siphon", "npctypes"),
            new GamevalEntry(11773, "WARDENS_P3_ORB_RED", "wardens_p3_orb_red", "npctypes"),
            new GamevalEntry(11774, "TOA_WARDENS_ZEBAK", "Zebak's Phantom", "npctypes"),
            new GamevalEntry(11775, "TOA_WARDENS_BABA", "Ba-Ba's Phantom", "npctypes"),
            new GamevalEntry(11776, "TOA_WARDENS_KEPHRI", "Kephri's Phantom", "npctypes"),
            new GamevalEntry(11777, "TOA_WARDENS_AKKHA", "Akkha's Phantom", "npctypes"),
        };
    }

    static Optional<GamevalEntry> byId(int id) {
        for (GamevalEntry entry : entries()) {
            if (entry.id() == id) return Optional.of(entry);
        }
        return Optional.empty();
    }

}
