package net.titan.gamevals.internal;

import java.util.Optional;

import net.titan.gamevals.GamevalEntry;
import net.titan.gamevals.QuestEntry;

final class NpcIDEntries_15 {
    private NpcIDEntries_15() {}

    static GamevalEntry[] entries() {
        return new GamevalEntry[] {
            new GamevalEntry(7682, "TZHAAR_HUR_CITY1", "TzHaar-Hur", "npctypes"),
            new GamevalEntry(7683, "TZHAAR_HUR_CITY2", "TzHaar-Hur", "npctypes"),
            new GamevalEntry(7684, "TZHAAR_HUR_CITY3", "TzHaar-Hur", "npctypes"),
            new GamevalEntry(7685, "TZHAAR_HUR_CITY4", "TzHaar-Hur", "npctypes"),
            new GamevalEntry(7686, "TZHAAR_HUR_CITY5", "TzHaar-Hur", "npctypes"),
            new GamevalEntry(7687, "TZHAAR_HUR_CITY6", "TzHaar-Hur", "npctypes"),
            new GamevalEntry(7688, "TZHAAR_MERCHANT_CITYEQUIPMENT", "TzHaar-Hur-Zal", "npctypes"),
            new GamevalEntry(7689, "TZHAAR_MERCHANT_CITYOREANDGEM", "TzHaar-Hur-Rin", "npctypes"),
            new GamevalEntry(7690, "INFERNO_MASTER", "inferno_master", "npctypes"),
            new GamevalEntry(7691, "INFERNO_NIBBLER", "Jal-Nib", "npctypes"),
            new GamevalEntry(7692, "INFERNO_CREATURE_HARPIE", "Jal-MejRah", "npctypes"),
            new GamevalEntry(7693, "INFERNO_CREATURE_SPLITTER", "Jal-Ak", "npctypes"),
            new GamevalEntry(7694, "INFERNO_CREATURE_SPLITTER_MAGE", "Jal-AkRek-Mej", "npctypes"),
            new GamevalEntry(7695, "INFERNO_CREATURE_SPLITTER_RANGE", "Jal-AkRek-Xil", "npctypes"),
            new GamevalEntry(7696, "INFERNO_CREATURE_SPLITTER_MELEE", "Jal-AkRek-Ket", "npctypes"),
            new GamevalEntry(7697, "INFERNO_CREATURE_MELEE", "Jal-ImKot", "npctypes"),
            new GamevalEntry(7698, "INFERNO_CREATURE_RANGER", "Jal-Xil", "npctypes"),
            new GamevalEntry(7699, "INFERNO_CREATURE_MAGER", "Jal-Zek", "npctypes"),
            new GamevalEntry(7700, "INFERNO_JAD", "JalTok-Jad", "npctypes"),
            new GamevalEntry(7701, "INFERNO_JAD_HEALER", "Yt-HurKot", "npctypes"),
            new GamevalEntry(7702, "INFERNO_RANGER_FINALWAVE", "Jal-Xil", "npctypes"),
            new GamevalEntry(7703, "INFERNO_MAGER_FINALWAVE", "Jal-Zek", "npctypes"),
            new GamevalEntry(7704, "INFERNO_JAD_FINALWAVE", "JalTok-Jad", "npctypes"),
            new GamevalEntry(7705, "INFERNO_JAD_HEALER_FINALWAVE", "Yt-HurKot", "npctypes"),
            new GamevalEntry(7706, "INFERNO_TZKALZUK_PLACEHOLDER", "XK TzKal-Zuk", "npctypes"),
            new GamevalEntry(7707, "INFERNO_MOVING_SAFESPOT", "Ancestral Glyph", "npctypes"),
            new GamevalEntry(7708, "INFERNO_ZUK_HEALER", "Jal-MejJak", "npctypes"),
            new GamevalEntry(7709, "INFERNO_INVISIBLE_3X3", "Rocky support", "npctypes"),
            new GamevalEntry(7710, "INFERNO_SAFESPOT_DYING", "Rocky support", "npctypes"),
            new GamevalEntry(7711, "SKILLPET_MINING_AMETHYST", "Rock Golem", "npctypes"),
            new GamevalEntry(7712, "MGUILD_DWARF1", "Dwarf", "npctypes"),
            new GamevalEntry(7713, "MGUILD_DWARF2", "Dwarf", "npctypes"),
            new GamevalEntry(7714, "MGUILD_GUARD1", "Dwarf", "npctypes"),
            new GamevalEntry(7715, "MGUILD_GUARD2", "Dwarf", "npctypes"),
            new GamevalEntry(7716, "MGUILD_CAPESELLER", "Gadrin", "npctypes"),
            new GamevalEntry(7717, "MGUILD_ORESELLER", "Hendor", "npctypes"),
            new GamevalEntry(7718, "MGUILD_PICKAXESELLER", "Yarsul", "npctypes"),
            new GamevalEntry(7719, "MGUILD_REWARDSELLER", "Belona", "npctypes"),
            new GamevalEntry(7720, "MGUILD_AMETHYSTMINER", "Utrec", "npctypes"),
            new GamevalEntry(7721, "MOTHERLODE_MGUILD_GUARD", "Dwarf", "npctypes"),
            new GamevalEntry(7722, "GOLEM_RUNE_ROCK_NO_ORE", "Rocks", "npctypes"),
            new GamevalEntry(7723, "GERTRUDE_POST", "Gertrude", "npctypes"),
            new GamevalEntry(7724, "BARBGUARD1_POSTCRAWL", "Barbarian guard", "npctypes"),
            new GamevalEntry(7725, "DWARF_CITY_BOATMAN_MINES_PREQUEST", "Dwarven Boatman", "npctypes"),
            new GamevalEntry(7726, "DWARF_CITY_BOATMAN_MINES_POSTQUEST", "Dwarven Boatman", "npctypes"),
            new GamevalEntry(7727, "MINNOW_FISHERMAN_LOCKED", "Kylie Minnow", "npctypes"),
            new GamevalEntry(7728, "MINNOW_FISHERMAN_UNLOCKED", "Kylie Minnow", "npctypes"),
            new GamevalEntry(7729, "DEADMAN_TOURNAMENT_INVISNPC_3", "deadman_tournament_invisnpc_3", "npctypes"),
            new GamevalEntry(7730, "MINNOW_FISHINGSPOT1", "Fishing spot", "npctypes"),
            new GamevalEntry(7731, "MINNOW_FISHINGSPOT2", "Fishing spot", "npctypes"),
            new GamevalEntry(7732, "MINNOW_FISHINGSPOT3", "Fishing spot", "npctypes"),
            new GamevalEntry(7733, "MINNOW_FISHINGSPOT4", "Fishing spot", "npctypes"),
            new GamevalEntry(7734, "WILDWARS_REDEEMER", "Recruiter", "npctypes"),
            new GamevalEntry(7735, "MINNOW_FISHERMAN_MULTI", "?c_", "npctypes"),
            new GamevalEntry(7736, "POH_SKILLPET_MINING_LOVAKITE", "Rock Golem", "npctypes"),
            new GamevalEntry(7737, "POH_SKILLPET_MINING_ELEMENTAL", "Rock Golem", "npctypes"),
            new GamevalEntry(7738, "POH_SKILLPET_MINING_DAEYALT", "Rock Golem", "npctypes"),
            new GamevalEntry(7739, "SKILLPET_MINING_LOVAKITE", "Rock Golem", "npctypes"),
            new GamevalEntry(7740, "SKILLPET_MINING_ELEMENTAL", "Rock Golem", "npctypes"),
            new GamevalEntry(7741, "SKILLPET_MINING_DAEYALT", "Rock Golem", "npctypes"),
            new GamevalEntry(7742, "LIZARDMAN_CAVE_GUARD", "Captain Cleive", "npctypes"),
            new GamevalEntry(7743, "LIZARDMAN_CAVE_SOLDIER", "Soldier", "npctypes"),
            new GamevalEntry(7744, "LIZARDMAN_CAVE_SHAMAN_1", "Lizardman shaman", "npctypes"),
            new GamevalEntry(7745, "LIZARDMAN_CAVE_SHAMAN_2", "Lizardman shaman", "npctypes"),
            new GamevalEntry(7746, "WIZARD_MIZGOG_QUEST", "Wizard Mizgog", "npctypes"),
            new GamevalEntry(7747, "WIZARD_MIZGOG_POST", "Wizard Mizgog", "npctypes"),
            new GamevalEntry(7748, "FAIRY_CHILD", "Fairy", "npctypes"),
            new GamevalEntry(7749, "WILDWARS_TIMER", "wildwars_timer", "npctypes"),
            new GamevalEntry(7750, "WILDWARS_BOSS_ARMOUR", "Armoured Foe", "npctypes"),
            new GamevalEntry(7751, "WILDWARS_BOSS_WEAPONS", "Well-armed Foe", "npctypes"),
            new GamevalEntry(7752, "UPASSMAGE_1OP", "Dark Mage", "npctypes"),
            new GamevalEntry(7753, "UPASSMAGE_2OPS", "Dark Mage", "npctypes"),
            new GamevalEntry(7754, "FOSSIL_SQUIRREL_GARDENER1", "Squirrel", "npctypes"),
            new GamevalEntry(7755, "FOSSIL_SQUIRREL_GARDENER2", "Squirrel", "npctypes"),
            new GamevalEntry(7756, "FOSSIL_SQUIRREL_GARDENER3", "Squirrel", "npctypes"),
            new GamevalEntry(7757, "FOSSIL_LEPRECHAUN_UNDERWATER", "Tool Leprechaun", "npctypes"),
            new GamevalEntry(7758, "FOSSIL_GARDENER_UNDERWATER", "Mernia", "npctypes"),
            new GamevalEntry(7759, "POH_HERBIBOAR_PET", "Herbi", "npctypes"),
            new GamevalEntry(7760, "HERBIBOAR_PET", "Herbi", "npctypes"),
            new GamevalEntry(7761, "FOSSILQUEST_LEAD_NAVIGATOR_QUEST", "Lead Navigator", "npctypes"),
            new GamevalEntry(7762, "FOSSILQUEST_LEAD_NAVIGATOR_POSTQUEST", "Lead Navigator", "npctypes"),
            new GamevalEntry(7763, "FOSSILQUEST_JR_NAVIGATOR_QUEST", "Junior Navigator", "npctypes"),
            new GamevalEntry(7764, "FOSSILQUEST_JR_NAVIGATOR_POSTQUEST", "Junior Navigator", "npctypes"),
            new GamevalEntry(7765, "FOSSILQUEST_JOHN_VIS", "John", "npctypes"),
            new GamevalEntry(7766, "FOSSILQUEST_DAVID_VIS", "David", "npctypes"),
            new GamevalEntry(7767, "FOSSILQUEST_BARGE_GUARD_PORT", "fossilquest_barge_guard_port", "npctypes"),
            new GamevalEntry(7768, "FOSSILQUEST_BARGE_GUARD_BARGE", "Barge guard", "npctypes"),
            new GamevalEntry(7769, "FOSSIL_GENERAL_STORE", "Shop keeper", "npctypes"),
            new GamevalEntry(7770, "FOSSIL_SHOPKEEPER", "Fossil Collector", "npctypes"),
            new GamevalEntry(7771, "FOSSIL_DOG_TRAY", "Dog", "npctypes"),
            new GamevalEntry(7772, "FOSSIL_PANNER", "Peter", "npctypes"),
            new GamevalEntry(7773, "FOSSIL_CHARLES", "Charles", "npctypes"),
            new GamevalEntry(7774, "FOSSIL_JOHN", "John", "npctypes"),
            new GamevalEntry(7775, "OSB5_IMP_GREEN", "Dunce", "npctypes"),
            new GamevalEntry(7776, "FOSSIL_MINEGUARD", "Petrified Pete", "npctypes"),
            new GamevalEntry(7777, "FOSSIL_SLAYERDUNGEONGUARD", "Weve", "npctypes"),
            new GamevalEntry(7778, "FOSSIL_CHEMIST", "Irene", "npctypes"),
            new GamevalEntry(7779, "FOSSIL_POOL_BOBBER", "Bobbing fossil", "npctypes"),
            new GamevalEntry(7780, "ROVING_ISLWYN_1OP", "Islwyn", "npctypes"),
            new GamevalEntry(7781, "FOSSIL_PUFFER_FISH_DEPUFFED", "Puffer Fish", "npctypes"),
            new GamevalEntry(7782, "FOSSIL_FISH_SHOAL", "Fish shoal", "npctypes"),
            new GamevalEntry(7783, "FOSSIL_MERMAID_FISHING", "Ceto", "npctypes"),
            new GamevalEntry(7784, "FOSSIL_MERMAID_DEEPWATER", "Mairin", "npctypes"),
            new GamevalEntry(7785, "FOSSIL_HERBIBOAR_VISIBLE", "Herbiboar", "npctypes"),
            new GamevalEntry(7786, "FOSSIL_HERBIBOAR_ANIM_VISIBLE", "Herbiboar", "npctypes"),
            new GamevalEntry(7787, "FOSSIL_TWITCHER", "Mattimeo", "npctypes"),
            new GamevalEntry(7788, "FOSSIL_SWAMP_CORRUPTED_ARCHAEOLOGIST", "Charles Charlington", "npctypes"),
            new GamevalEntry(7789, "HOLGARTLANDTRAVEL", "Holgart", "npctypes"),
            new GamevalEntry(7790, "FOSSIL_JOHN_CAMP", "John", "npctypes"),
            new GamevalEntry(7791, "FOSSIL_DAVID_CAMP", "David", "npctypes"),
            new GamevalEntry(7792, "WYVERN_LONG_TAILED", "Long-tailed Wyvern", "npctypes"),
            new GamevalEntry(7793, "WYVERN_TALONED", "Taloned Wyvern", "npctypes"),
            new GamevalEntry(7794, "WYVERN_SPITTING", "Spitting Wyvern", "npctypes"),
            new GamevalEntry(7795, "ANCIENT_WYVERN", "Ancient Wyvern", "npctypes"),
            new GamevalEntry(7796, "FOSSIL_LOBSTER", "Lobstrosity", "npctypes"),
            new GamevalEntry(7797, "FOSSIL_ZYGOMITE", "Ancient Zygomite", "npctypes"),
            new GamevalEntry(7798, "GAIUS", "Gaius", "npctypes"),
            new GamevalEntry(7799, "FOSSIL_AMMONITECRAB", "Ammonite Crab", "npctypes"),
            new GamevalEntry(7800, "FOSSIL_AMMONITECRAB_INACTIVE", "Fossil Rock", "npctypes"),
            new GamevalEntry(7801, "FOSSIL_TARMONSTER_BUBBLES", "Tar Bubbles", "npctypes"),
            new GamevalEntry(7802, "FOSSIL_HOOPSNAKE", "Hoop Snake", "npctypes"),
            new GamevalEntry(7803, "FOSSIL_HOOPSNAKE_STUNNED", "Stunned Hoop Snake", "npctypes"),
            new GamevalEntry(7804, "FOSSIL_TARMONSTER", "Tar Monster", "npctypes"),
            new GamevalEntry(7805, "FOSSIL_TARMONSTER_PASSIVE", "Passive Tar Monster", "npctypes"),
            new GamevalEntry(7806, "FOSSIL_CRAZY_ARCHAEOLOGIST", "Deranged archaeologist", "npctypes"),
            new GamevalEntry(7807, "FOSSIL_MINING_BOULDER_ATTACHED_BREAKING", "Giant boulder", "npctypes"),
            new GamevalEntry(7808, "FOSSIL_MINING_BOULDER_GIANT_FLOATING", "Giant boulder", "npctypes"),
            new GamevalEntry(7809, "FOSSIL_MINING_BOULDER_GIANT_BREAKING", "Giant boulder", "npctypes"),
            new GamevalEntry(7810, "FOSSIL_MINING_BOULDER_LARGE_FLOATING", "Large boulder", "npctypes"),
            new GamevalEntry(7811, "FOSSIL_MINING_BOULDER_LARGE_BREAKING", "Large boulder", "npctypes"),
            new GamevalEntry(7812, "FOSSIL_MINING_BOULDER_MEDIUM_FLOATING", "Medium boulder", "npctypes"),
            new GamevalEntry(7813, "FOSSIL_MINING_BOULDER_MEDIUM_BREAKING", "Medium boulder", "npctypes"),
            new GamevalEntry(7814, "FOSSIL_MINING_BOULDER_SMALL_FLOATING", "Small boulder", "npctypes"),
            new GamevalEntry(7815, "FOSSIL_MINING_BOULDER_SMALL_BREAKING", "Small boulder", "npctypes"),
            new GamevalEntry(7816, "FOSSIL_MINING_BOULDER_TINY_FLOATING", "Small boulder", "npctypes"),
            new GamevalEntry(7817, "FOSSIL_MINE_LAVABEAST", "Lava beast", "npctypes"),
            new GamevalEntry(7818, "VM_FOSSIL_EXPERT", "David", "npctypes"),
            new GamevalEntry(7819, "FOSSILQUEST_LEAD_NAVIGATOR", "fossilquest_lead_navigator", "npctypes"),
            new GamevalEntry(7820, "FOSSILQUEST_JR_NAVIGATOR", "fossilquest_jr_navigator", "npctypes"),
            new GamevalEntry(7821, "FOSSILQUEST_JOHN", "fossilquest_john", "npctypes"),
            new GamevalEntry(7822, "FOSSILQUEST_DAVID", "fossilquest_david", "npctypes"),
            new GamevalEntry(7823, "FOSSIL_POOL_BOBBER_1", "fossil_pool_bobber_1", "npctypes"),
            new GamevalEntry(7824, "FOSSIL_POOL_BOBBER_2", "fossil_pool_bobber_2", "npctypes"),
            new GamevalEntry(7825, "FOSSIL_POOL_BOBBER_3", "fossil_pool_bobber_3", "npctypes"),
            new GamevalEntry(7826, "FOSSIL_POOL_BOBBER_4", "fossil_pool_bobber_4", "npctypes"),
            new GamevalEntry(7827, "FOSSIL_POOL_BOBBER_5", "fossil_pool_bobber_5", "npctypes"),
            new GamevalEntry(7828, "FOSSIL_POOL_BOBBER_6", "fossil_pool_bobber_6", "npctypes"),
            new GamevalEntry(7829, "FOSSIL_POOL_BOBBER_7", "fossil_pool_bobber_7", "npctypes"),
            new GamevalEntry(7830, "FOSSIL_POOL_BOBBER_8", "fossil_pool_bobber_8", "npctypes"),
            new GamevalEntry(7831, "FOSSIL_HERBIBOAR_1", "fossil_herbiboar_1", "npctypes"),
            new GamevalEntry(7832, "FOSSIL_HERBIBOAR_2", "fossil_herbiboar_2", "npctypes"),
            new GamevalEntry(7833, "FOSSIL_HERBIBOAR_3", "fossil_herbiboar_3", "npctypes"),
            new GamevalEntry(7834, "FOSSIL_HERBIBOAR_4", "fossil_herbiboar_4", "npctypes"),
            new GamevalEntry(7835, "FOSSIL_HERBIBOAR_5", "fossil_herbiboar_5", "npctypes"),
            new GamevalEntry(7836, "FOSSIL_HERBIBOAR_6", "fossil_herbiboar_6", "npctypes"),
            new GamevalEntry(7837, "FOSSIL_HERBIBOAR_7", "fossil_herbiboar_7", "npctypes"),
            new GamevalEntry(7838, "FOSSIL_HERBIBOAR_8", "fossil_herbiboar_8", "npctypes"),
            new GamevalEntry(7839, "FOSSIL_HERBIBOAR_9", "fossil_herbiboar_9", "npctypes"),
            new GamevalEntry(7840, "FOSSIL_HERBIBOAR_ANIMATE_1", "fossil_herbiboar_animate_1", "npctypes"),
            new GamevalEntry(7841, "FOSSIL_HERBIBOAR_ANIMATE_2", "fossil_herbiboar_animate_2", "npctypes"),
            new GamevalEntry(7842, "FOSSIL_HERBIBOAR_ANIMATE_3", "fossil_herbiboar_animate_3", "npctypes"),
            new GamevalEntry(7843, "FOSSIL_HERBIBOAR_ANIMATE_4", "fossil_herbiboar_animate_4", "npctypes"),
            new GamevalEntry(7844, "FOSSIL_HERBIBOAR_ANIMATE_5", "fossil_herbiboar_animate_5", "npctypes"),
            new GamevalEntry(7845, "FOSSIL_HERBIBOAR_ANIMATE_6", "fossil_herbiboar_animate_6", "npctypes"),
            new GamevalEntry(7846, "FOSSIL_HERBIBOAR_ANIMATE_7", "fossil_herbiboar_animate_7", "npctypes"),
            new GamevalEntry(7847, "FOSSIL_HERBIBOAR_ANIMATE_8", "fossil_herbiboar_animate_8", "npctypes"),
            new GamevalEntry(7848, "FOSSIL_HERBIBOAR_ANIMATE_9", "fossil_herbiboar_animate_9", "npctypes"),
            new GamevalEntry(7849, "GARGBOSS_DUSK_SPAWN", "Dusk", "npctypes"),
            new GamevalEntry(7850, "GARGBOSS_DAWN_SPAWN", "Dawn", "npctypes"),
            new GamevalEntry(7851, "GARGBOSS_DUSK_PHASE1_DEFENSIVE", "Dusk", "npctypes"),
            new GamevalEntry(7852, "GARGBOSS_DAWN_PHASE1", "Dawn", "npctypes"),
            new GamevalEntry(7853, "GARGBOSS_DAWN_PHASE1_TRANSITION", "Dawn", "npctypes"),
            new GamevalEntry(7854, "GARGBOSS_DUSK_PHASE1_TRANSITION", "Dusk", "npctypes"),
            new GamevalEntry(7855, "GARGBOSS_DUSK_PHASE1_FLYTRANSITION", "Dusk", "npctypes"),
            new GamevalEntry(7856, "DEADMAN_FINAL_DARK_WARRIOR", "deadman_final_dark_warrior", "npctypes"),
            new GamevalEntry(7857, "DEADMAN_FINAL_SPOOPY_SKELETON", "deadman_final_spoopy_skeleton", "npctypes"),
            new GamevalEntry(7858, "MA2_BOSS_SARADOMIN", "Justiciar Zachariah", "npctypes"),
            new GamevalEntry(7859, "MA2_BOSS_GUTHIX", "Derwen", "npctypes"),
            new GamevalEntry(7860, "MA2_BOSS_ZAMORAK", "Porazdir", "npctypes"),
            new GamevalEntry(7861, "WILD_CAVE_BLACK_DRAGON", "Black dragon", "npctypes"),
            new GamevalEntry(7862, "WILD_CAVE_BLACK_DRAGON2", "Black dragon", "npctypes"),
            new GamevalEntry(7863, "WILD_CAVE_BLACK_DRAGON3", "Black dragon", "npctypes"),
            new GamevalEntry(7864, "WILD_CAVE_ANKOU", "Ankou", "npctypes"),
            new GamevalEntry(7865, "WILD_CAVE_LESSER_DEMON", "Lesser demon", "npctypes"),
            new GamevalEntry(7866, "WILD_CAVE_LESSER_DEMON2", "Lesser demon", "npctypes"),
            new GamevalEntry(7867, "WILD_CAVE_LESSER_DEMON3", "Lesser demon", "npctypes"),
            new GamevalEntry(7868, "WILD_CAVE_GREEN_DRAGON", "Green dragon", "npctypes"),
            new GamevalEntry(7869, "WILD_CAVE_GREEN_DRAGON2", "Green dragon", "npctypes"),
            new GamevalEntry(7870, "WILD_CAVE_GREEN_DRAGON3", "Green dragon", "npctypes"),
            new GamevalEntry(7871, "WILD_CAVE_GREATER_DEMON", "Greater demon", "npctypes"),
            new GamevalEntry(7872, "WILD_CAVE_GREATER_DEMON2", "Greater demon", "npctypes"),
            new GamevalEntry(7873, "WILD_CAVE_GREATER_DEMON3", "Greater demon", "npctypes"),
            new GamevalEntry(7874, "WILD_CAVE_BLACK_DEMON", "Black demon", "npctypes"),
            new GamevalEntry(7875, "WILD_CAVE_BLACK_DEMON2", "Black demon", "npctypes"),
            new GamevalEntry(7876, "WILD_CAVE_BLACK_DEMON3", "Black demon", "npctypes"),
            new GamevalEntry(7877, "WILD_CAVE_HELL_HOUND", "Hellhound", "npctypes"),
            new GamevalEntry(7878, "WILD_CAVE_ICEGIANT", "Ice giant", "npctypes"),
            new GamevalEntry(7879, "WILD_CAVE_ICEGIANT2", "Ice giant", "npctypes"),
            new GamevalEntry(7880, "WILD_CAVE_ICEGIANT3", "Ice giant", "npctypes"),
            new GamevalEntry(7881, "WILD_CAVE_IMP", "Revenant imp", "npctypes"),
            new GamevalEntry(7882, "GARGBOSS_DUSK_PHASE2_ATTACKING", "Dusk", "npctypes"),
            new GamevalEntry(7883, "GARGBOSS_DUSK_PHASE3_DEFENSIVE", "Dusk", "npctypes"),
            new GamevalEntry(7884, "GARGBOSS_DAWN_PHASE3", "Dawn", "npctypes"),
            new GamevalEntry(7885, "GARGBOSS_DAWN_DEATH", "Dawn", "npctypes"),
            new GamevalEntry(7886, "GARGBOSS_DUSK_PHASE3_TRANSITION", "Dusk", "npctypes"),
            new GamevalEntry(7887, "GARGBOSS_DUSK_PHASE4_SPAWN", "Dusk", "npctypes"),
            new GamevalEntry(7888, "GARGBOSS_DUSK_PHASE4", "Dusk", "npctypes"),
            new GamevalEntry(7889, "GARGBOSS_DUSK_DEATH", "Dusk", "npctypes"),
            new GamevalEntry(7890, "POH_DUSK_PET", "Midnight", "npctypes"),
            new GamevalEntry(7891, "POH_DAWN_PET", "Noon", "npctypes"),
            new GamevalEntry(7892, "DAWN_PET", "Noon", "npctypes"),
            new GamevalEntry(7893, "DUSK_PET", "Midnight", "npctypes"),
            new GamevalEntry(7894, "NZONE_HOSIDIUSQUEST_SNAKE_HARD", "Sand Snake (hard)", "npctypes"),
            new GamevalEntry(7895, "NZONE_HOSIDIUSQUEST_SNAKE_NORMAL", "Sand Snake", "npctypes"),
            new GamevalEntry(7896, "AKD_MARTIN_HOLT_SETTLEMENT_RUINS", "akd_martin_holt_settlement_ruins", "npctypes"),
            new GamevalEntry(7897, "AKD_MARTIN_HOLT_PISCARILIUS", "akd_martin_holt_piscarilius", "npctypes"),
            new GamevalEntry(7898, "HOSIDIUSQUEST_SON", "Artur Hosidius", "npctypes"),
            new GamevalEntry(7899, "HOSIDIUSQUEST_SON_CAVES", "Artur Hosidius", "npctypes"),
            new GamevalEntry(7900, "HOSIDIUSQUEST_BUTLER", "Butler Jarvis", "npctypes"),
            new GamevalEntry(7901, "HOSIDIUSQUEST_CHEF", "Chef Olivia", "npctypes"),
            new GamevalEntry(7902, "HOSIDIUSQUEST_LIBRARIAN", "Galana", "npctypes"),
            new GamevalEntry(7903, "HOSIDIUSQUEST_SNAKE", "Sand Snake", "npctypes"),
            new GamevalEntry(7904, "PISCQUEST_OFFICIAL_VISIBLE", "Tomas Lawry", "npctypes"),
            new GamevalEntry(7905, "PISCQUEST_CITIZEN", "Robert O'Reilly", "npctypes"),
            new GamevalEntry(7906, "PISCQUEST_THUG", "Devan Rutter", "npctypes"),
            new GamevalEntry(7907, "PISCQUEST_TARGET_ALIVE", "Conrad King", "npctypes"),
            new GamevalEntry(7908, "PISCQUEST_QUEEN_PREQUEST", "The Queen of Thieves", "npctypes"),
            new GamevalEntry(7909, "PISCQUEST_QUEEN_POSTQUEST", "Lady Shauna Piscarilius", "npctypes"),
            new GamevalEntry(7910, "PISCQUEST_COUNCILLOR_JAILED", "Sophia Hughes", "npctypes"),
            new GamevalEntry(7911, "WARRENS_BARMAN", "Bartender", "npctypes"),
            new GamevalEntry(7912, "WARRENS_FISHMONGER", "Fish monger", "npctypes"),
            new GamevalEntry(7913, "WARRENS_SHOPKEEPER", "Shop keeper", "npctypes"),
            new GamevalEntry(7914, "WARRENS_THIEF_1", "Thief", "npctypes"),
            new GamevalEntry(7915, "WARRENS_THIEF_2", "Thief", "npctypes"),
            new GamevalEntry(7916, "WARRENS_THIEF_STALL", "Thief", "npctypes"),
            new GamevalEntry(7917, "WARRENS_PIRATE_1", "Pirate", "npctypes"),
            new GamevalEntry(7918, "WARRENS_PIRATE_2", "Pirate", "npctypes"),
            new GamevalEntry(7919, "WARRENS_CITIZEN_1", "Man", "npctypes"),
            new GamevalEntry(7920, "WARRENS_CITIZEN_2", "Man", "npctypes"),
            new GamevalEntry(7921, "WARRENS_CITIZEN_3", "Woman", "npctypes"),
            new GamevalEntry(7922, "WARRENS_CITIZEN_4", "Woman", "npctypes"),
            new GamevalEntry(7923, "PISCARILIUS_POOR_CITIZEN_FEMALE_3", "Poor looking woman", "npctypes"),
            new GamevalEntry(7924, "ZEAH_HEAD_COUNCILLOR", "zeah_head_councillor", "npctypes"),
            new GamevalEntry(7925, "HOSIDIUSQUEST_SON_HOME", "hosidiusquest_son_home", "npctypes"),
            new GamevalEntry(7926, "PISCQUEST_OFFICIAL", "piscquest_official", "npctypes"),
            new GamevalEntry(7927, "PISCQUEST_OFFICIAL_CASTLE", "piscquest_official_castle", "npctypes"),
            new GamevalEntry(7928, "PISCQUEST_TARGET", "piscquest_target", "npctypes"),
            new GamevalEntry(7929, "PISCQUEST_QUEEN", "piscquest_queen", "npctypes"),
            new GamevalEntry(7930, "PISCQUEST_COUNCILLOR", "piscquest_councillor", "npctypes"),
            new GamevalEntry(7931, "WILD_CAVE_GOBLIN", "Revenant goblin", "npctypes"),
            new GamevalEntry(7932, "WILD_CAVE_PYREFIEND", "Revenant pyrefiend", "npctypes"),
            new GamevalEntry(7933, "WILD_CAVE_HOBGOBLIN", "Revenant hobgoblin", "npctypes"),
            new GamevalEntry(7934, "WILD_CAVE_CYCLOPS", "Revenant cyclops", "npctypes"),
            new GamevalEntry(7935, "WILD_CAVE_HELLHOUND", "Revenant hellhound", "npctypes"),
            new GamevalEntry(7936, "WILD_CAVE_DEMON", "Revenant demon", "npctypes"),
            new GamevalEntry(7937, "WILD_CAVE_ORK", "Revenant ork", "npctypes"),
            new GamevalEntry(7938, "WILD_CAVE_DARKBEAST", "Revenant dark beast", "npctypes"),
            new GamevalEntry(7939, "WILD_CAVE_KNIGHT", "Revenant knight", "npctypes"),
            new GamevalEntry(7940, "WILD_CAVE_DRAGON", "Revenant dragon", "npctypes"),
            new GamevalEntry(7941, "IRONMAN_TUTOR_2_VISIBLE", "Ironman tutor", "npctypes"),
            new GamevalEntry(7942, "IRONMAN_TUTOR_2", "ironman_tutor_2", "npctypes"),
            new GamevalEntry(7943, "WILD_CAVE_TRADER", "Emblem Trader", "npctypes"),
            new GamevalEntry(7944, "DEADMAN_FINAL_SPOOPY_BOI", "deadman_final_spoopy_boi", "npctypes"),
            new GamevalEntry(7945, "DEADMAN_BANKER_GNOME_NORTH", "deadman_banker_gnome_north", "npctypes"),
            new GamevalEntry(7946, "_0_38_45_RAREFISH", "Fishing spot", "npctypes"),
            new GamevalEntry(7947, "_0_39_44_SALTFISH", "Fishing spot", "npctypes"),
            new GamevalEntry(7948, "NZONE_CORSAIRCURSE_NAVIGATOR_HARD", "Corsair Traitor (hard)", "npctypes"),
            new GamevalEntry(7949, "NZONE_CORSAIRCURSE_NAVIGATOR_NORMAL", "Corsair Traitor", "npctypes"),
            new GamevalEntry(7950, "ALEC_KINCADE", "Alec Kincade", "npctypes"),
            new GamevalEntry(7951, "MYTHS_GUILD_DUNGEON_GUARD", "Ponts the Bridgemaster", "npctypes"),
            new GamevalEntry(7952, "MYTHS_GUILD_SMITH", "Erdan", "npctypes"),
            new GamevalEntry(7953, "MYTHS_GUILD_HERBALIST", "Primula", "npctypes"),
            new GamevalEntry(7954, "MYTHS_GUILD_HERO", "Mysterious Adventurer", "npctypes"),
            new GamevalEntry(7955, "BABY_BLACK_DRAGON_NOHUNT", "Baby black dragon", "npctypes"),
            new GamevalEntry(7956, "CORSAIR_CAPTAIN_1OP", "Captain Tock", "npctypes"),
            new GamevalEntry(7957, "CORSAIR_CAPTAIN_THRONE_CHILD", "Captain Tock", "npctypes"),
            new GamevalEntry(7958, "CORSAIR_CAPTAIN_2OPS", "Captain Tock", "npctypes"),
            new GamevalEntry(7959, "CORSAIR_CAPTAIN_CROSSROADS", "corsair_captain_crossroads", "npctypes"),
            new GamevalEntry(7960, "CORSAIR_CAPTAIN_THRONE", "corsair_captain_throne", "npctypes"),
            new GamevalEntry(7961, "CORSCURS_NAVIGATOR", "Ithoi the Navigator", "npctypes"),
            new GamevalEntry(7962, "CORSCURS_NAVIGATOR_SICK", "corscurs_navigator_sick", "npctypes"),
            new GamevalEntry(7963, "CORSCURS_NAVIGATOR_RUNNING", "Ithoi the Navigator", "npctypes"),
            new GamevalEntry(7964, "CORSCURS_NAVIGATOR_COMBAT", "Ithoi the Navigator", "npctypes"),
            new GamevalEntry(7965, "CORSCURS_CABINBOY", "Cabin Boy Colin", "npctypes"),
            new GamevalEntry(7966, "CORSCURS_CABINBOY_TELESCOPE", "Cabin Boy Colin", "npctypes"),
            new GamevalEntry(7967, "CORSCURS_CABINBOY_2OPS", "Cabin Boy Colin", "npctypes"),
            new GamevalEntry(7968, "CORSCURS_CABINBOY_SICK", "corscurs_cabinboy_sick", "npctypes"),
            new GamevalEntry(7969, "CORSCURS_OGRE", "Bugs", "npctypes"),
            new GamevalEntry(7970, "CORSCURS_COOK", "Gnocci the Cook", "npctypes"),
            new GamevalEntry(7971, "CORSCURS_COOK_FISHING", "Gnocci the Cook", "npctypes"),
            new GamevalEntry(7972, "CORSCURS_COOK_DIGGING", "Gnocci the Cook", "npctypes"),
            new GamevalEntry(7973, "CORSCURS_COOK_SICK", "corscurs_cook_sick", "npctypes"),
            new GamevalEntry(7974, "CORSCURS_COOK_POSTQUEST", "corscurs_cook_postquest", "npctypes"),
            new GamevalEntry(7975, "CORSCURS_DOLL", "Doll", "npctypes"),
            new GamevalEntry(7976, "CORSCURS_THIEF", "Arsen the Thief", "npctypes"),
            new GamevalEntry(7977, "CORSCURS_THIEF_SICK", "corscurs_thief_sick", "npctypes"),
            new GamevalEntry(7978, "CORSCURS_THIEF_POSTQUEST", "corscurs_thief_postquest", "npctypes"),
            new GamevalEntry(7979, "TRAIL_MIMIC_NONCOMBAT", "The Mimic", "npctypes"),
            new GamevalEntry(7980, "CORSAIR_FERRY_COVEDOCKS", "corsair_ferry_covedocks", "npctypes"),
            new GamevalEntry(7981, "CORSCURS_BANKER_1OP", "Yusuf", "npctypes"),
            new GamevalEntry(7982, "CORSCURS_BANKER_ALLOPS", "Yusuf", "npctypes"),
            new GamevalEntry(7983, "CORSCURS_DIGGING_THIEF", "Francois", "npctypes"),
            new GamevalEntry(7984, "CORSCURS_SPA_OWNER", "Madame Caldarium", "npctypes"),
            new GamevalEntry(7985, "CORSCURS_RESOURCE_GUARD", "Haris", "npctypes"),
            new GamevalEntry(7986, "CORSCURS_RESOURCE_MEDITATE", "Altarkiz", "npctypes"),
            new GamevalEntry(7987, "CORSCURS_LORD_MARSHAL", "Lord Marshal Brogan", "npctypes"),
            new GamevalEntry(7988, "OGRESS_TESS", "Chief Tess", "npctypes"),
            new GamevalEntry(7989, "OGRESS_WARRIOR1", "Ogress Warrior", "npctypes"),
            new GamevalEntry(7990, "OGRESS_WARRIOR2", "Ogress Warrior", "npctypes"),
            new GamevalEntry(7991, "OGRESS_SHAMAN1", "Ogress Shaman", "npctypes"),
            new GamevalEntry(7992, "OGRESS_SHAMAN2", "Ogress Shaman", "npctypes"),
            new GamevalEntry(7993, "CORSCURS_DOLL_MULTI", "corscurs_doll_multi", "npctypes"),
            new GamevalEntry(7994, "CORSCURS_BANKER_MULTI", "corscurs_banker_multi", "npctypes"),
            new GamevalEntry(7995, "WILD_CHAOS_UNCERTER", "Elder Chaos druid", "npctypes"),
            new GamevalEntry(7996, "NZONE_SHAYZIENQUEST_LIZARDMAN_HARD", "Corrupt Lizardman (hard)", "npctypes"),
            new GamevalEntry(7997, "NZONE_SHAYZIENQUEST_LIZARDMAN_NORMAL", "Corrupt Lizardman", "npctypes"),
            new GamevalEntry(7998, "AKD_MARTIN_HOLT_CASTLE", "akd_martin_holt_castle", "npctypes"),
            new GamevalEntry(7999, "PHILEAS_RIMOR_VISIBLE", "Phileas Rimor", "npctypes"),
            new GamevalEntry(8000, "SHAYZIENQUEST_LIZARDMAN_BOSS", "Corrupt Lizardman", "npctypes"),
            new GamevalEntry(8001, "OSB5_CRUNCHY", "Crunchy", "npctypes"),
            new GamevalEntry(8002, "OSB5_TIM", "Tim", "npctypes"),
            new GamevalEntry(8003, "OSB5_WORKMAN_SAWING", "Dave", "npctypes"),
            new GamevalEntry(8004, "OSB5_WORKMAN_SLEDGEHAMMERING", "Gene", "npctypes"),
            new GamevalEntry(8005, "VOSB5_WORKMAN_PAINTING_TAR", "Art", "npctypes"),
            new GamevalEntry(8006, "SHAYZIENQUEST_GNOSI", "Gnosi", "npctypes"),
            new GamevalEntry(8007, "SHAYZIENQUEST_DUFFY", "Historian Duffy", "npctypes"),
            new GamevalEntry(8008, "POH_CORPPET", "Corporeal Critter", "npctypes"),
            new GamevalEntry(8009, "POH_ZUK_PET", "TzRek-Zuk", "npctypes"),
            new GamevalEntry(8010, "CORP_PET", "Corporeal Critter", "npctypes"),
            new GamevalEntry(8011, "ZUK_PET", "TzRek-Zuk", "npctypes"),
            new GamevalEntry(8012, "FOSSILQUEST_BARGE_GUARD_PORT_POSTQUEST", "Barge guard", "npctypes"),
            new GamevalEntry(8013, "FOSSILQUEST_BARGE_GUARD_PORT_PREQUEST", "Barge guard", "npctypes"),
            new GamevalEntry(8014, "DEADMAN_FINAL_MOSS_WARRIOR", "deadman_final_moss_warrior", "npctypes"),
            new GamevalEntry(8015, "DEADMAN_FINAL_MOSSGIANT", ". 0J", "npctypes"),
            new GamevalEntry(8016, "DEADMAN_FINAL_MOSSGIANT2", ". 0J", "npctypes"),
            new GamevalEntry(8017, "DEADMAN_FINAL_MOSSGIANT3", ". 0J", "npctypes"),
            new GamevalEntry(8018, "DEADMAN_FINAL_MOSSGIANT4", "/ 0J", "npctypes"),
            new GamevalEntry(8019, "GRANDTREE_NARNODE_1OP", "King Narnode Shareen", "npctypes"),
            new GamevalEntry(8020, "GRANDTREE_NARNODE_2OPS", "King Narnode Shareen", "npctypes"),
            new GamevalEntry(8021, "SHAYZIENQUEST_HISTORIAN", "Natural Historian", "npctypes"),
            new GamevalEntry(8022, "SHAYZIENQUEST_GHOST", "Mysterious Voice", "npctypes"),
            new GamevalEntry(8023, "RAIDS_TEMPLE_GNOSI_VISIBLE", "Gnosi", "npctypes"),
            new GamevalEntry(8024, "POH_SKILLPET_RUNECRAFTING_WRATH", "Rift guardian", "npctypes"),
            new GamevalEntry(8025, "POH_VORKATH_PET", "Vorki", "npctypes"),
            new GamevalEntry(8026, "POH_MOUNTED_VORKATH", "Vorkath", "npctypes"),
            new GamevalEntry(8027, "POH_RUNE_DRAGON", "Rune dragon", "npctypes"),
            new GamevalEntry(8028, "SKILLPET_RUNECRAFTING_WRATH", "Rift guardian", "npctypes"),
            new GamevalEntry(8029, "VORKATH_PET", "Vorki", "npctypes"),
            new GamevalEntry(8030, "ADAMANT_DRAGON", "Adamant dragon", "npctypes"),
            new GamevalEntry(8031, "RUNE_DRAGON", "Rune dragon", "npctypes"),
            new GamevalEntry(8032, "RUNE_DRAGON_ELECTOVORTEX", "rune_dragon_electovortex", "npctypes"),
            new GamevalEntry(8033, "ELVARG_ALIVE", "Elvarg", "npctypes"),
            new GamevalEntry(8034, "DEATH_GROWNCAT_BLACK_VIS", "Bob", "npctypes"),
            new GamevalEntry(8035, "ICS_LITTLE_CAT_VISIBLE", "Neite", "npctypes"),
            new GamevalEntry(8036, "MYTHS_GUILD_WEAPON_SELLER", "Diana", "npctypes"),
            new GamevalEntry(8037, "MYTHS_GUILD_CAPE_SELLER", "Jack", "npctypes"),
            new GamevalEntry(8038, "MYTHS_GUILD_TRAINER", "Ellen", "npctypes"),
            new GamevalEntry(8039, "MYTHS_GUILD_FREM", "Freja", "npctypes"),
            new GamevalEntry(8040, "MYTHS_GUILD_LIBRARIAN", "Lutwidge", "npctypes"),
            new GamevalEntry(8041, "MYTHS_GUILD_DOG", "Dog", "npctypes"),
            new GamevalEntry(8042, "DS2_MEETING_KING_ROALD", "King Roald", "npctypes"),
            new GamevalEntry(8043, "DS2_MEETING_AEONISIG_RAISPHER", "Aeonisig Raispher", "npctypes"),
            new GamevalEntry(8044, "DS2_MEETING_SIR_AMIK_VARZE", "Sir Amik Varze", "npctypes"),
            new GamevalEntry(8045, "DS2_MEETING_SIR_TIFFY_CASHIEN", "Sir Tiffy Cashien", "npctypes"),
            new GamevalEntry(8046, "DS2_MEETING_KING_LATHAS", "King Lathas", "npctypes"),
            new GamevalEntry(8047, "DS2_MEETING_KING_ARTHUR", "King Arthur", "npctypes"),
            new GamevalEntry(8048, "DS2_MEETING_BRUNDT", "Brundt the Chieftain", "npctypes"),
            new GamevalEntry(8049, "DS2_MEETING_ONEIROMANCER", "Oneiromancer", "npctypes"),
            new GamevalEntry(8050, "DS2_MEETING_DENULTH", "Denulth", "npctypes"),
            new GamevalEntry(8051, "DS2_MEETING_DUKE_HORACIO", "Duke Horacio", "npctypes"),
            new GamevalEntry(8052, "DS2_MEETING_WOM", "Wise Old Man", "npctypes"),
            new GamevalEntry(8053, "DS2_MEETING_JARDRIC", "Jardric", "npctypes"),
            new GamevalEntry(8054, "DS2_MEETING_ACHIETTIES", "Achietties", "npctypes"),
            new GamevalEntry(8055, "DS2_MEETING_BOB", "Bob", "npctypes"),
            new GamevalEntry(8056, "STRANGE_SPAWN", "Spawn", "npctypes"),
            new GamevalEntry(8057, "DREAM_ROBERT_COMBAT", "Robert the Strong", "npctypes"),
            new GamevalEntry(8058, "VORKATH_SLEEPING_NOOP", "Vorkath", "npctypes"),
            new GamevalEntry(8059, "VORKATH_SLEEPING", "Vorkath", "npctypes"),
            new GamevalEntry(8060, "VORKATH_QUEST", "Vorkath", "npctypes"),
            new GamevalEntry(8061, "VORKATH", "Vorkath", "npctypes"),
            new GamevalEntry(8062, "VORKATH_SPAWN_QUEST", "Zombified Spawn", "npctypes"),
            new GamevalEntry(8063, "VORKATH_SPAWN", "Zombified Spawn", "npctypes"),
            new GamevalEntry(8064, "DS2_GOLEM_MELEE", "Stone Guardian", "npctypes"),
            new GamevalEntry(8065, "DS2_GOLEM_RANGED", "Stone Guardian", "npctypes"),
            new GamevalEntry(8066, "DS2_GOLEM_MAGIC", "Stone Guardian", "npctypes"),
            new GamevalEntry(8067, "DS2_ZOMBIE_MELEE", "Zombie", "npctypes"),
            new GamevalEntry(8068, "DS2_ZOMBIE_RANGED", "Zombie", "npctypes"),
            new GamevalEntry(8069, "DS2_ZOMBIE_MAGIC", "Zombie", "npctypes"),
            new GamevalEntry(8070, "DS2_SKELETON_MELEE", "Skeleton", "npctypes"),
            new GamevalEntry(8071, "DS2_SKELETON_RANGED", "Skeleton", "npctypes"),
            new GamevalEntry(8072, "DS2_SKELETON_MAGIC", "Skeleton", "npctypes"),
            new GamevalEntry(8073, "DS2_GREEN_DRAGON_FLYING", "Green dragon", "npctypes"),
            new GamevalEntry(8074, "DS2_BLUE_DRAGON_FLYING", "Blue dragon", "npctypes"),
            new GamevalEntry(8075, "DS2_RED_DRAGON_FLYING", "Red dragon", "npctypes"),
            new GamevalEntry(8076, "DS2_GREEN_DRAGON_CUTSCENE_FLYING", "Green dragon", "npctypes"),
            new GamevalEntry(8077, "DS2_BLUE_DRAGON_CUTSCENE_FLYING", "Blue dragon", "npctypes"),
            new GamevalEntry(8078, "DS2_RED_DRAGON_CUTSCENE_FLYING", "Red dragon", "npctypes"),
            new GamevalEntry(8079, "DS2_RED_DRAGON", "Red dragon", "npctypes"),
            new GamevalEntry(8080, "DS2_IRON_DRAGON", "Iron dragon", "npctypes"),
            new GamevalEntry(8081, "DS2_BRUT_GREEN_DRAGON", "Brutal green dragon", "npctypes"),
            new GamevalEntry(8082, "DS2_GREEN_DRAGON", "Green dragon", "npctypes"),
            new GamevalEntry(8083, "DS2_BLUE_DRAGON", "Blue dragon", "npctypes"),
            new GamevalEntry(8084, "DS2_BLACK_DRAGON_CUTSCENE", "Black dragon", "npctypes"),
            new GamevalEntry(8085, "DS2_BLACK_DRAGON", "Black dragon", "npctypes"),
            new GamevalEntry(8086, "DS2_STEEL_DRAGON", "Steel dragon", "npctypes"),
            new GamevalEntry(8087, "DS2_BRUT_RED_DRAGON", "Brutal red dragon", "npctypes"),
            new GamevalEntry(8088, "DS2_MITHRIL_DRAGON_CUTSCENE", "Mithril dragon", "npctypes"),
            new GamevalEntry(8089, "DS2_MITHRIL_DRAGON", "Mithril dragon", "npctypes"),
            new GamevalEntry(8090, "DS2_ADAMANT_DRAGON", "Adamant dragon", "npctypes"),
            new GamevalEntry(8091, "DS2_RUNE_DRAGON", "Rune dragon", "npctypes"),
            new GamevalEntry(8092, "DS2_BRUT_BLACK_DRAGON_CUTSCENE", "Brutal black dragon", "npctypes"),
            new GamevalEntry(8093, "DS2_BRUT_BLACK_DRAGON", "Brutal black dragon", "npctypes"),
            new GamevalEntry(8094, "GALVEK_WAVES", "Galvek", "npctypes"),
            new GamevalEntry(8095, "GALVEK_FIRE", "Galvek", "npctypes"),
            new GamevalEntry(8096, "GALVEK_WATER", "Galvek", "npctypes"),
            new GamevalEntry(8097, "GALVEK_WIND", "Galvek", "npctypes"),
            new GamevalEntry(8098, "GALVEK_EARTH", "Galvek", "npctypes"),
            new GamevalEntry(8099, "GALVEK_TSUNAMI", "Tsunami", "npctypes"),
            new GamevalEntry(8100, "DALLAS_JONES", "Dallas Jones", "npctypes"),
            new GamevalEntry(8101, "DALLAS_JONES_CAT", "Dallas Jones", "npctypes"),
            new GamevalEntry(8102, "DALLAS_JONES_VAULT", "Dallas Jones", "npctypes"),
            new GamevalEntry(8103, "DALLAS_JONES_VAULT_2", "Dallas Jones", "npctypes"),
            new GamevalEntry(8104, "DALLAS_JONES_CUTSCENE", "Dallas Jones", "npctypes"),
            new GamevalEntry(8105, "JARDRIC", "Jardric", "npctypes"),
            new GamevalEntry(8106, "JARDRIC_TRAVEL", "Jardric", "npctypes"),
            new GamevalEntry(8107, "JARDRIC_LITHKREN", "Jardric", "npctypes"),
            new GamevalEntry(8108, "DS2_JARDRIC_CROSSBOW", "Jardric", "npctypes"),
            new GamevalEntry(8109, "JARDRIC_DUNGEON", "jardric_dungeon", "npctypes"),
            new GamevalEntry(8110, "JARDRIC_VARROCK", "jardric_varrock", "npctypes"),
            new GamevalEntry(8111, "DEATH_GROWNCAT_BLACK_CHILD", "Bob", "npctypes"),
            new GamevalEntry(8112, "DEATH_GROWNCAT_BLACK_DREAM", "Bob", "npctypes"),
            new GamevalEntry(8113, "DEATH_GROWNCAT_BLACK_VAULT", "Bob", "npctypes"),
            new GamevalEntry(8114, "DEATH_GROWNCAT_BLACK_VAULT_2", "Bob", "npctypes"),
            new GamevalEntry(8115, "DEATH_GROWNCAT_BLACK_CUTSCENE", "Bob", "npctypes"),
            new GamevalEntry(8116, "NOT_BOB", "Not Bob", "npctypes"),
            new GamevalEntry(8117, "NOT_BOB_CUTSCENE", "Not Bob", "npctypes"),
            new GamevalEntry(8118, "DREAM_NEITE", "Neite", "npctypes"),
            new GamevalEntry(8119, "DREAM_UNFERTH", "Unferth", "npctypes"),
            new GamevalEntry(8120, "DREAM_DRAGONKIN", "Dragonkin", "npctypes"),
            new GamevalEntry(8121, "DREAM_CAMORRA", "Camorra", "npctypes"),
            new GamevalEntry(8122, "DREAM_TRISTAN", "Tristan", "npctypes"),
            new GamevalEntry(8123, "DREAM_AIVAS", "Aivas", "npctypes"),
            new GamevalEntry(8124, "DREAM_ROBERT", "Robert the Strong", "npctypes"),
            new GamevalEntry(8125, "FLASHBACK_DRAGONKIN", "Dragonkin", "npctypes"),
            new GamevalEntry(8126, "FLASHBACK_CAMORRA", "Camorra", "npctypes"),
            new GamevalEntry(8127, "FLASHBACK_TRISTAN", "Tristan", "npctypes"),
            new GamevalEntry(8128, "FLASHBACK_AIVAS", "Aivas", "npctypes"),
            new GamevalEntry(8129, "FLASHBACK_ROBERT", "Robert the Strong", "npctypes"),
            new GamevalEntry(8130, "FLASHBACK_ODYSSEUS", "Odysseus", "npctypes"),
            new GamevalEntry(8131, "TORFINN_NO_TRAVEL", "Torfinn", "npctypes"),
            new GamevalEntry(8132, "RC_ZMI_BANKER", "Eniola", "npctypes"),
            new GamevalEntry(8133, "LOTR_BANKER", "Odovacar", "npctypes"),
            new GamevalEntry(8134, "SARAH_CORVO", "Sarah", "npctypes"),
            new GamevalEntry(8135, "ZORGOTH_CUTSCENE", "Dragonkin", "npctypes"),
            new GamevalEntry(8136, "ZORGOTH_VAULT", "Zorgoth", "npctypes"),
            new GamevalEntry(8137, "LABORATORY_SPIDER", "Spider", "npctypes"),
            new GamevalEntry(8138, "LABORATORY_SPIDER_AGGRESSIVE", "Spider", "npctypes"),
            new GamevalEntry(8139, "WRATH_SKELETON", "Skeleton", "npctypes"),
            new GamevalEntry(8140, "WRATH_SKELETON_AXE", "Skeleton", "npctypes"),
            new GamevalEntry(8141, "NIETE_BURTHORPE", "niete_burthorpe", "npctypes"),
            new GamevalEntry(8142, "CRANDOR_LAB_EGG", "Strange Egg", "npctypes"),
            new GamevalEntry(8143, "DS2_DRAGON_HEAD_UNLIT", "Dragon head", "npctypes"),
            new GamevalEntry(8144, "DS2_DRAGON_HEAD_LIT", "Dragon head", "npctypes"),
            new GamevalEntry(8145, "DS2_FLEET_BRUNDT", "Brundt the Chieftain", "npctypes"),
            new GamevalEntry(8146, "DS2_FLEET_THORVALD", "Thorvald the Warrior", "npctypes"),
            new GamevalEntry(8147, "DS2_FLEET_PEER", "Peer the Seer", "npctypes"),
            new GamevalEntry(8148, "DS2_FLEET_SWENSEN", "Swensen the Navigator", "npctypes"),
            new GamevalEntry(8149, "DS2_WHITE_KNIGHT", "White Knight", "npctypes"),
            new GamevalEntry(8150, "DS2_PALADIN", "Paladin", "npctypes"),
            new GamevalEntry(8151, "DS2_FLEET_KOSCHEI", "Koschei the Deathless", "npctypes"),
            new GamevalEntry(8152, "DS2_FLEET_KOSCHEI_2", "Koschei the Deathless", "npctypes"),
            new GamevalEntry(8153, "DS2_BATTLE_BRUNDT", "Brundt the Chieftain", "npctypes"),
            new GamevalEntry(8154, "DS2_BATTLE_WOM", "Wise Old Man", "npctypes"),
            new GamevalEntry(8155, "DS2_BATTLE_JARDRIC", "Jardric", "npctypes"),
            new GamevalEntry(8156, "DS2_BATTLE_ACHIETTIES", "Achietties", "npctypes"),
            new GamevalEntry(8157, "DS2_BATTLE_SIR_TIFFY_CASHIEN", "Sir Tiffy Cashien", "npctypes"),
            new GamevalEntry(8158, "DS2_BATTLE_ONEIROMANCER", "Oneiromancer", "npctypes"),
            new GamevalEntry(8159, "DEATH_GROWNCAT_BLACK_FLEET", "Bob", "npctypes"),
            new GamevalEntry(8160, "DS2_BATTLE_SOLDIER", "Soldier", "npctypes"),
            new GamevalEntry(8161, "DS2_BATTLE_BRUNDT_FINAL", "Brundt the Chieftain", "npctypes"),
            new GamevalEntry(8162, "DS2_BATTLE_WOM_FINAL", "Wise Old Man", "npctypes"),
            new GamevalEntry(8163, "RAIDS_TEMPLE_DUFFY_VISIBLE", "Historian Duffy", "npctypes"),
            new GamevalEntry(8164, "DS2_BATTLE_ACHIETTIES_FINAL", "Achietties", "npctypes"),
            new GamevalEntry(8165, "DS2_BATTLE_SIR_TIFFY_CASHIEN_FINAL", "Sir Tiffy Cashien", "npctypes"),
            new GamevalEntry(8166, "DS2_BATTLE_ONEIROMANCER_FINAL", "Oneiromancer", "npctypes"),
            new GamevalEntry(8167, "ZORGOTH_FLEET", "Zorgoth", "npctypes"),
            new GamevalEntry(8168, "DS2_CUTSCENE_SOLDIER", "Soldier", "npctypes"),
            new GamevalEntry(8169, "DS2_CUTSCENE_BRUNDT", "Brundt the Chieftain", "npctypes"),
            new GamevalEntry(8170, "DS2_CUTSCENE_WOM", "Wise Old Man", "npctypes"),
            new GamevalEntry(8171, "DS2_CUTSCENE_JARDRIC", "Jardric", "npctypes"),
            new GamevalEntry(8172, "DS2_CUTSCENE_ACHIETTIES", "Achietties", "npctypes"),
            new GamevalEntry(8173, "DS2_CUTSCENE_SIR_TIFFY_CASHIEN", "Sir Tiffy Cashien", "npctypes"),
            new GamevalEntry(8174, "DS2_CUTSCENE_ONEIROMANCER", "Oneiromancer", "npctypes"),
            new GamevalEntry(8175, "ZORGOTH_FLEET_CUTSCENE", "Zorgoth", "npctypes"),
            new GamevalEntry(8176, "ZORGOTH_FLEET_CUTSCENE_LARGE", "Zorgoth", "npctypes"),
            new GamevalEntry(8177, "GALVEK_CUTSCENE", "Galvek", "npctypes"),
            new GamevalEntry(8178, "GALVEK_EARTH_CUTSCENE", "Galvek", "npctypes"),
            new GamevalEntry(8179, "GALVEK_EARTH_DEAD", "Galvek", "npctypes"),
            new GamevalEntry(8180, "SHAYZIEN_HISTORIAN", "Amelia", "npctypes"),
            new GamevalEntry(8181, "HOSIDIUS_HISTORIAN", "Jonathan", "npctypes"),
            new GamevalEntry(8182, "RAIDS_TEMPLE_HISTORIAN_VISIBLE", "Natural Historian", "npctypes"),
            new GamevalEntry(8183, "POH_NIGHTMARE_PET_PARASITE", "Little Parasite", "npctypes"),
            new GamevalEntry(8184, "KOUREND_PROTESTER", "kourend_protester", "npctypes"),
            new GamevalEntry(8185, "KOUREND_PROTESTER_2", "kourend_protester_2", "npctypes"),
            new GamevalEntry(8186, "KOUREND_PROTESTER_3", "kourend_protester_3", "npctypes"),
            new GamevalEntry(8187, "KOUREND_PROTESTER_4", "kourend_protester_4", "npctypes"),
            new GamevalEntry(8188, "SHAYZIENQUEST_BOULDER", "Boulder", "npctypes"),
            new GamevalEntry(8189, "SHAYZIENQUEST_GRAVEDIGGER", "Grave digger", "npctypes"),
            new GamevalEntry(8190, "RAIDS_TEMPLE_GNOSI", "raids_temple_gnosi", "npctypes"),
            new GamevalEntry(8191, "RAIDS_TEMPLE_DUFFY", "raids_temple_duffy", "npctypes"),
            new GamevalEntry(8192, "RAIDS_TEMPLE_HISTORIAN", "raids_temple_historian", "npctypes"),
            new GamevalEntry(8193, "BOND_JAMES_VISIBLE", "James", "npctypes"),
        };
    }

    static Optional<GamevalEntry> byId(int id) {
        for (GamevalEntry entry : entries()) {
            if (entry.id() == id) return Optional.of(entry);
        }
        return Optional.empty();
    }

}
