package net.titan.gamevals.internal;

import java.util.Optional;

import net.titan.gamevals.GamevalEntry;
import net.titan.gamevals.QuestEntry;

final class NpcIDEntries_8 {
    private NpcIDEntries_8() {}

    static GamevalEntry[] entries() {
        return new GamevalEntry[] {
            new GamevalEntry(4096, "ID_4096_3_4_5_6_A", "( 3 4 5 6 (a", "npctypes"),
            new GamevalEntry(4097, "ID_4097_3_4_5_6_A", "( 3 4 5 6 (a", "npctypes"),
            new GamevalEntry(4098, "ID_4098_3_4_5_6_A", "( 3 4 5 6 (a", "npctypes"),
            new GamevalEntry(4099, "ID_4099_3_4_5_6_A", "/ 3 4 5 6 (a", "npctypes"),
            new GamevalEntry(4100, "ID_4100_3_4_5_6_A", "/ 3 4 5 6 (a", "npctypes"),
            new GamevalEntry(4101, "HAROLD", "Harold", "npctypes"),
            new GamevalEntry(4102, "TOSTIG", "Tostig", "npctypes"),
            new GamevalEntry(4103, "EOHRIC", "Eohric", "npctypes"),
            new GamevalEntry(4104, "SERVANT_4104", "Servant", "npctypes"),
            new GamevalEntry(4105, "DUNSTAN", "Dunstan", "npctypes"),
            new GamevalEntry(4106, "WISTAN", "Wistan", "npctypes"),
            new GamevalEntry(4107, "ID_4107_4_3_4_5_6_TALK_TO", "4 3 4 5 6 ( Talk-to", "npctypes"),
            new GamevalEntry(4108, "ID_4108_4_3_4_5_6_TALK_TO", "4 3 4 5 6 ( Talk-to", "npctypes"),
            new GamevalEntry(4109, "ID_4109_4_3_4_5_6_TALK_TO", "4 3 4 5 6 ( Talk-to", "npctypes"),
            new GamevalEntry(4110, "ID_4110_5_3_4_5_6_TALK_TO", "5 3 4 5 6 ( Talk-to", "npctypes"),
            new GamevalEntry(4111, "ID_4111_5_3_4_5_6_TALK_TO", "5 3 4 5 6 ( Talk-to", "npctypes"),
            new GamevalEntry(4112, "ID_4112_5_3_4_5_6_TALK_TO", "5 3 4 5 6 ( Talk-to", "npctypes"),
            new GamevalEntry(4113, "ID_4113", "", "npctypes"),
            new GamevalEntry(4114, "WHITE_KNIGHT_4114", "White Knight", "npctypes"),
            new GamevalEntry(4115, "FAREED_HARD", "Fareed (hard)", "npctypes"),
            new GamevalEntry(4116, "BILLY", "Billy", "npctypes"),
            new GamevalEntry(4117, "MOUNTAIN_GOAT_4117", "Mountain goat", "npctypes"),
            new GamevalEntry(4118, "EADGAR", "Eadgar", "npctypes"),
            new GamevalEntry(4119, "GODRIC", "Godric", "npctypes"),
            new GamevalEntry(4120, "TROLL_GENERAL", "Troll general", "npctypes"),
            new GamevalEntry(4121, "TROLL_GENERAL_4121", "Troll general", "npctypes"),
            new GamevalEntry(4122, "TROLL_GENERAL_4122", "Troll general", "npctypes"),
            new GamevalEntry(4123, "TROLL_SPECTATOR", "Troll spectator", "npctypes"),
            new GamevalEntry(4124, "TROLL_SPECTATOR_4124", "Troll spectator", "npctypes"),
            new GamevalEntry(4125, "TROLL_SPECTATOR_4125", "Troll spectator", "npctypes"),
            new GamevalEntry(4126, "TROLL_SPECTATOR_4126", "Troll spectator", "npctypes"),
            new GamevalEntry(4127, "TROLL_SPECTATOR_4127", "Troll spectator", "npctypes"),
            new GamevalEntry(4128, "TROLL_SPECTATOR_4128", "Troll spectator", "npctypes"),
            new GamevalEntry(4129, "TROLL_SPECTATOR_4129", "Troll spectator", "npctypes"),
            new GamevalEntry(4130, "DAD", "Dad", "npctypes"),
            new GamevalEntry(4131, "ID_4131_6_A", "6 a", "npctypes"),
            new GamevalEntry(4132, "ID_4132_6_A", "6 a", "npctypes"),
            new GamevalEntry(4133, "TWIG", "Twig", "npctypes"),
            new GamevalEntry(4134, "BERRY", "Berry", "npctypes"),
            new GamevalEntry(4135, "ID_4135_9_A", "9 a", "npctypes"),
            new GamevalEntry(4136, "ID_4136_9_A", "9 a", "npctypes"),
            new GamevalEntry(4137, "ID_4137_9_A", "9 a", "npctypes"),
            new GamevalEntry(4138, "ID_4138_9_A", "9 a", "npctypes"),
            new GamevalEntry(4139, "ID_4139_9_A", "9 a", "npctypes"),
            new GamevalEntry(4140, "COOK_4140", "Cook", "npctypes"),
            new GamevalEntry(4141, "COOK_4141", "Cook", "npctypes"),
            new GamevalEntry(4142, "COOK_4142", "Cook", "npctypes"),
            new GamevalEntry(4143, "MOUNTAIN_TROLL_4143", "Mountain troll", "npctypes"),
            new GamevalEntry(4144, "MUSHROOM", "Mushroom", "npctypes"),
            new GamevalEntry(4145, "MOUNTAIN_GOAT_4145", "Mountain goat", "npctypes"),
            new GamevalEntry(4146, "MOUNTAIN_GOAT_4146", "Mountain goat", "npctypes"),
            new GamevalEntry(4147, "MOUNTAIN_GOAT_4147", "Mountain goat", "npctypes"),
            new GamevalEntry(4148, "GUARD_4148", "Guard", "npctypes"),
            new GamevalEntry(4149, "GUARD_4149", "Guard", "npctypes"),
            new GamevalEntry(4150, "GUARD_4150", "Guard", "npctypes"),
            new GamevalEntry(4151, "GUARD_4151", "Guard", "npctypes"),
            new GamevalEntry(4152, "GUARD_4152", "Guard", "npctypes"),
            new GamevalEntry(4153, "GUARD_4153", "Guard", "npctypes"),
            new GamevalEntry(4154, "GUARD_4154", "Guard", "npctypes"),
            new GamevalEntry(4155, "GUARD_4155", "Guard", "npctypes"),
            new GamevalEntry(4156, "GUARD_4156", "Guard", "npctypes"),
            new GamevalEntry(4157, "BURNTMEAT", "Burntmeat", "npctypes"),
            new GamevalEntry(4158, "RAT_BURGISS", "Rat Burgiss", "npctypes"),
            new GamevalEntry(4159, "SUROK_MAGIS_4159", "Surok Magis", "npctypes"),
            new GamevalEntry(4160, "SUROK_MAGIS_4160", "Surok Magis", "npctypes"),
            new GamevalEntry(4161, "ZAFF_4161", "Zaff", "npctypes"),
            new GamevalEntry(4162, "ANNA_JONES", "Anna Jones", "npctypes"),
            new GamevalEntry(4163, "KING_ROALD_4163", "King Roald", "npctypes"),
            new GamevalEntry(4164, "MISHKAL_UN_DORN", "Mishkal'un Dorn", "npctypes"),
            new GamevalEntry(4165, "DAKH_THOULAN_AEGIS", "Dakh'thoulan Aegis", "npctypes"),
            new GamevalEntry(4166, "SIL_AS_DAHCSNU", "Sil'as Dahcsnu", "npctypes"),
            new GamevalEntry(4167, "OUTLAW", "Outlaw", "npctypes"),
            new GamevalEntry(4168, "OUTLAW_4168", "Outlaw", "npctypes"),
            new GamevalEntry(4169, "OUTLAW_4169", "Outlaw", "npctypes"),
            new GamevalEntry(4170, "OUTLAW_4170", "Outlaw", "npctypes"),
            new GamevalEntry(4171, "OUTLAW_4171", "Outlaw", "npctypes"),
            new GamevalEntry(4172, "OUTLAW_4172", "Outlaw", "npctypes"),
            new GamevalEntry(4173, "OUTLAW_4173", "Outlaw", "npctypes"),
            new GamevalEntry(4174, "OUTLAW_4174", "Outlaw", "npctypes"),
            new GamevalEntry(4175, "OUTLAW_4175", "Outlaw", "npctypes"),
            new GamevalEntry(4176, "OUTLAW_4176", "Outlaw", "npctypes"),
            new GamevalEntry(4177, "MONKEY_4177", "Monkey", "npctypes"),
            new GamevalEntry(4178, "BENCH", "Bench", "npctypes"),
            new GamevalEntry(4179, "HADLEY", "Hadley", "npctypes"),
            new GamevalEntry(4180, "GERALD", "Gerald", "npctypes"),
            new GamevalEntry(4181, "ALMERA", "Almera", "npctypes"),
            new GamevalEntry(4182, "HUDON", "Hudon", "npctypes"),
            new GamevalEntry(4183, "GOLRIE_4183", "Golrie", "npctypes"),
            new GamevalEntry(4184, "CROCODILE", "Crocodile", "npctypes"),
            new GamevalEntry(4185, "JACKAL", "Jackal", "npctypes"),
            new GamevalEntry(4186, "ID_4186", "", "npctypes"),
            new GamevalEntry(4187, "ODDSKULL", "Oddskull", "npctypes"),
            new GamevalEntry(4188, "ID_4188", "", "npctypes"),
            new GamevalEntry(4189, "ID_4189", "", "npctypes"),
            new GamevalEntry(4190, "ID_4190", "", "npctypes"),
            new GamevalEntry(4191, "ID_4191", "", "npctypes"),
            new GamevalEntry(4192, "SCARAB_SWARM_4192", "Scarab Swarm", "npctypes"),
            new GamevalEntry(4193, "WANDERER", "Wanderer", "npctypes"),
            new GamevalEntry(4194, "WANDERER_4194", "Wanderer", "npctypes"),
            new GamevalEntry(4195, "LA", "La", "npctypes"),
            new GamevalEntry(4196, "LA_4196", "La", "npctypes"),
            new GamevalEntry(4197, "LA_4197", "La", "npctypes"),
            new GamevalEntry(4198, "LA_4198", "La", "npctypes"),
            new GamevalEntry(4199, "ICTHLARIN", "Icthlarin", "npctypes"),
            new GamevalEntry(4200, "ID_4200", "", "npctypes"),
            new GamevalEntry(4201, "ID_4201", "", "npctypes"),
            new GamevalEntry(4202, "EMBALMER", "Embalmer", "npctypes"),
            new GamevalEntry(4203, "CARPENTER", "Carpenter", "npctypes"),
            new GamevalEntry(4204, "ID_4204", "", "npctypes"),
            new GamevalEntry(4205, "SIAMUN", "Siamun", "npctypes"),
            new GamevalEntry(4206, "HIGH_PRIEST_4206", "High Priest", "npctypes"),
            new GamevalEntry(4207, "PRIEST_4207", "Priest", "npctypes"),
            new GamevalEntry(4208, "PRIEST_4208", "Priest", "npctypes"),
            new GamevalEntry(4209, "SPHINX_4209", "Sphinx", "npctypes"),
            new GamevalEntry(4210, "POSSESSED_PRIEST", "Possessed Priest", "npctypes"),
            new GamevalEntry(4211, "ID_4211", "", "npctypes"),
            new GamevalEntry(4212, "DONOVAN_THE_FAMILY_HANDYMAN", "Donovan the Family Handyman", "npctypes"),
            new GamevalEntry(4213, "PIERRE", "Pierre", "npctypes"),
            new GamevalEntry(4214, "HOBBES", "Hobbes", "npctypes"),
            new GamevalEntry(4215, "LOUISA", "Louisa", "npctypes"),
            new GamevalEntry(4216, "MARY", "Mary", "npctypes"),
            new GamevalEntry(4217, "STANFORD", "Stanford", "npctypes"),
            new GamevalEntry(4218, "GUARD_4218", "Guard", "npctypes"),
            new GamevalEntry(4219, "GOSSIP", "Gossip", "npctypes"),
            new GamevalEntry(4220, "ANNA_4220", "Anna", "npctypes"),
            new GamevalEntry(4221, "BOB_4221", "Bob", "npctypes"),
            new GamevalEntry(4222, "CAROL", "Carol", "npctypes"),
            new GamevalEntry(4223, "DAVID_4223", "David", "npctypes"),
            new GamevalEntry(4224, "ELIZABETH", "Elizabeth", "npctypes"),
            new GamevalEntry(4225, "FRANK", "Frank", "npctypes"),
            new GamevalEntry(4226, "SINCLAIR", "Sinclair", "npctypes"),
            new GamevalEntry(4227, "POISON_SALESMAN", "Poison Salesman", "npctypes"),
            new GamevalEntry(4228, "SINCLAIR_GUARD_DOG", "Sinclair Guard dog", "npctypes"),
            new GamevalEntry(4229, "LOVE_CATS_4229", "Love Cats", "npctypes"),
            new GamevalEntry(4230, "NEITE_4230", "Neite", "npctypes"),
            new GamevalEntry(4231, "BOB_4231", "Bob", "npctypes"),
            new GamevalEntry(4232, "BEITE", "Beite", "npctypes"),
            new GamevalEntry(4233, "GNOME", "Gnome", "npctypes"),
            new GamevalEntry(4234, "GNOME_4234", "Gnome", "npctypes"),
            new GamevalEntry(4235, "ODYSSEUS_4235", "Odysseus", "npctypes"),
            new GamevalEntry(4236, "NEITE_4236", "Neite", "npctypes"),
            new GamevalEntry(4237, "UNFERTH", "Unferth", "npctypes"),
            new GamevalEntry(4238, "UNFERTH_4238", "Unferth", "npctypes"),
            new GamevalEntry(4239, "UNFERTH_4239", "Unferth", "npctypes"),
            new GamevalEntry(4240, "UNFERTH_4240", "Unferth", "npctypes"),
            new GamevalEntry(4241, "UNFERTH_4241", "Unferth", "npctypes"),
            new GamevalEntry(4242, "RELDO", "Reldo", "npctypes"),
            new GamevalEntry(4243, "RELDO_4243", "Reldo", "npctypes"),
            new GamevalEntry(4244, "BROTHER_OMAD", "Brother Omad", "npctypes"),
            new GamevalEntry(4245, "BROTHER_CEDRIC", "Brother Cedric", "npctypes"),
            new GamevalEntry(4246, "MONK_4246", "Monk", "npctypes"),
            new GamevalEntry(4247, "ATTACK_4247", "Attack", "npctypes"),
            new GamevalEntry(4248, "HEAD_THIEF", "Head Thief", "npctypes"),
            new GamevalEntry(4249, "ALRENA", "Alrena", "npctypes"),
            new GamevalEntry(4250, "ALRENA_4250", "Alrena", "npctypes"),
            new GamevalEntry(4251, "ALRENA_4251", "Alrena", "npctypes"),
            new GamevalEntry(4252, "BRAVEK", "Bravek", "npctypes"),
            new GamevalEntry(4253, "BRAVEK_4253", "Bravek", "npctypes"),
            new GamevalEntry(4254, "ID_4254", "", "npctypes"),
            new GamevalEntry(4255, "CLERK", "Clerk", "npctypes"),
            new GamevalEntry(4256, "EDMOND_4256", "Edmond", "npctypes"),
            new GamevalEntry(4257, "ELENA_4257", "Elena", "npctypes"),
            new GamevalEntry(4258, "ID_4258", "", "npctypes"),
            new GamevalEntry(4259, "ID_4259", "", "npctypes"),
            new GamevalEntry(4260, "ID_4260", "", "npctypes"),
            new GamevalEntry(4261, "ID_4261", "", "npctypes"),
            new GamevalEntry(4262, "ID_4262", "", "npctypes"),
            new GamevalEntry(4263, "TED_REHNISON", "Ted Rehnison", "npctypes"),
            new GamevalEntry(4264, "MARTHA_REHNISON", "Martha Rehnison", "npctypes"),
            new GamevalEntry(4265, "BILLY_REHNISON", "Billy Rehnison", "npctypes"),
            new GamevalEntry(4266, "MILLI_REHNISON", "Milli Rehnison", "npctypes"),
            new GamevalEntry(4267, "ID_4267", "", "npctypes"),
            new GamevalEntry(4268, "MAN_4268", "Man", "npctypes"),
            new GamevalEntry(4269, "MAN_4269", "Man", "npctypes"),
            new GamevalEntry(4270, "MAN_4270", "Man", "npctypes"),
            new GamevalEntry(4271, "MAN_4271", "Man", "npctypes"),
            new GamevalEntry(4272, "MAN_4272", "Man", "npctypes"),
            new GamevalEntry(4273, "ID_4273", "", "npctypes"),
            new GamevalEntry(4274, "LEELA", "Leela", "npctypes"),
            new GamevalEntry(4275, "ID_4275", "", "npctypes"),
            new GamevalEntry(4276, "JAIL_GUARD", "Jail guard", "npctypes"),
            new GamevalEntry(4277, "JAIL_GUARD_4277", "Jail guard", "npctypes"),
            new GamevalEntry(4278, "JAIL_GUARD_4278", "Jail guard", "npctypes"),
            new GamevalEntry(4279, "JAIL_GUARD_4279", "Jail guard", "npctypes"),
            new GamevalEntry(4280, "NED", "Ned", "npctypes"),
            new GamevalEntry(4281, "ID_4281", "", "npctypes"),
            new GamevalEntry(4282, "ID_4282", "", "npctypes"),
            new GamevalEntry(4283, "ID_4283", "", "npctypes"),
            new GamevalEntry(4284, "ID_4284", "", "npctypes"),
            new GamevalEntry(4285, "CHANCELLOR_HASSAN", "Chancellor Hassan", "npctypes"),
            new GamevalEntry(4286, "OSMAN_4286", "Osman", "npctypes"),
            new GamevalEntry(4287, "BORDER_GUARD", "Border Guard", "npctypes"),
            new GamevalEntry(4288, "BORDER_GUARD_4288", "Border Guard", "npctypes"),
            new GamevalEntry(4289, "JOE_4289", "Joe", "npctypes"),
            new GamevalEntry(4290, "CAT_4290", "Cat", "npctypes"),
            new GamevalEntry(4291, "HERMAN_CARANOS", "Herman Caranos", "npctypes"),
            new GamevalEntry(4292, "FRANKLIN_CARANOS", "Franklin Caranos", "npctypes"),
            new GamevalEntry(4293, "ARNOLD_LYDSPOR", "Arnold Lydspor", "npctypes"),
            new GamevalEntry(4294, "DEVIN_MENDELBERG", "Devin Mendelberg", "npctypes"),
            new GamevalEntry(4295, "GEORGE_LAXMEISTER", "George Laxmeister", "npctypes"),
            new GamevalEntry(4296, "RAMARA_DU_CROISSANT", "Ramara du Croissant", "npctypes"),
            new GamevalEntry(4297, "ID_4297", "", "npctypes"),
            new GamevalEntry(4298, "KATHY_CORKAT", "Kathy Corkat", "npctypes"),
            new GamevalEntry(4299, "KATHY_CORKAT_4299", "Kathy Corkat", "npctypes"),
            new GamevalEntry(4300, "ID_4300", "", "npctypes"),
            new GamevalEntry(4301, "ELEMENTAL_BALANCE_4301", "Elemental balance", "npctypes"),
            new GamevalEntry(4302, "ELEMENTAL_BALANCE_4302", "Elemental balance", "npctypes"),
            new GamevalEntry(4303, "KALPHITE_QUEEN_4303", "Kalphite Queen", "npctypes"),
            new GamevalEntry(4304, "KALPHITE_QUEEN_4304", "Kalphite Queen", "npctypes"),
            new GamevalEntry(4305, "DRUNKEN_DWARF_4305", "Drunken Dwarf", "npctypes"),
            new GamevalEntry(4306, "WISE_OLD_MAN_4306", "Wise Old Man", "npctypes"),
            new GamevalEntry(4307, "WISE_OLD_MAN_4307", "Wise Old Man", "npctypes"),
            new GamevalEntry(4308, "SEA_TROLL", "Sea troll", "npctypes"),
            new GamevalEntry(4309, "SEA_TROLL_4309", "Sea troll", "npctypes"),
            new GamevalEntry(4310, "SEA_TROLL_4310", "Sea troll", "npctypes"),
            new GamevalEntry(4311, "SEA_TROLL_4311", "Sea troll", "npctypes"),
            new GamevalEntry(4312, "SKELETON_MAGE_4312", "Skeleton Mage", "npctypes"),
            new GamevalEntry(4313, "SEA_TROLL_4313", "Sea troll", "npctypes"),
            new GamevalEntry(4314, "SEA_TROLL_GENERAL", "Sea Troll General", "npctypes"),
            new GamevalEntry(4315, "SEA_TROLL_QUEEN", "Sea Troll Queen", "npctypes"),
            new GamevalEntry(4316, "N_FISHING_SPOT", "N Fishing spot", "npctypes"),
            new GamevalEntry(4317, "CALEB", "Caleb", "npctypes"),
            new GamevalEntry(4318, "SKELETON_MAGE_4318", "Skeleton Mage", "npctypes"),
            new GamevalEntry(4319, "SKELETON_MAGE_4319", "Skeleton Mage", "npctypes"),
            new GamevalEntry(4320, "MORGAN_LE_FAYE_4320", "Morgan Le Faye", "npctypes"),
            new GamevalEntry(4321, "RENEGADE_KNIGHT_4321", "Renegade knight", "npctypes"),
            new GamevalEntry(4322, "ZANIK_4322", "Zanik", "npctypes"),
            new GamevalEntry(4323, "ZANIK_4323", "Zanik", "npctypes"),
            new GamevalEntry(4324, "ZANIK_4324", "Zanik", "npctypes"),
            new GamevalEntry(4325, "LIGHT_CREATURE", "Light creature", "npctypes"),
            new GamevalEntry(4326, "ZANIK_4326", "Zanik", "npctypes"),
            new GamevalEntry(4327, "HAM_MEMBER", "HAM member", "npctypes"),
            new GamevalEntry(4328, "SIGMUND_4328", "Sigmund", "npctypes"),
            new GamevalEntry(4329, "H_A_M_DEACON_4329", "H.A.M. Deacon", "npctypes"),
            new GamevalEntry(4330, "JOHANHUS_ULSBRECHT_4330", "Johanhus Ulsbrecht", "npctypes"),
            new GamevalEntry(4331, "BLACK_KNIGHT_4331", "Black Knight", "npctypes"),
            new GamevalEntry(4332, "GUARD_4332", "Guard", "npctypes"),
            new GamevalEntry(4333, "COURT_JUDGE", "Court judge", "npctypes"),
            new GamevalEntry(4334, "JURY", "Jury", "npctypes"),
            new GamevalEntry(4335, "GUARD_4335", "Guard", "npctypes"),
            new GamevalEntry(4336, "GUARD_4336", "Guard", "npctypes"),
            new GamevalEntry(4337, "PROSECUTOR", "Prosecutor", "npctypes"),
            new GamevalEntry(4338, "ID_4338", "", "npctypes"),
            new GamevalEntry(4339, "ID_4339", "", "npctypes"),
            new GamevalEntry(4340, "ARTHUR", "Arthur", "npctypes"),
            new GamevalEntry(4341, "ID_4341", "", "npctypes"),
            new GamevalEntry(4342, "SIR_LUCAN_4342", "Sir Lucan", "npctypes"),
            new GamevalEntry(4343, "SIR_PALOMEDES_4343", "Sir Palomedes", "npctypes"),
            new GamevalEntry(4344, "SIR_LANCELOT_4344", "Sir Lancelot", "npctypes"),
            new GamevalEntry(4345, "X_Z_X_SIR_BEDIVERE", ")(X ?(X Sir Bedivere", "npctypes"),
            new GamevalEntry(4346, "SIR_TRISTRAM_4346", "Sir Tristram", "npctypes"),
            new GamevalEntry(4347, "ID_4347_1_Z_1_SIR_PELLEAS", ") 1 ? 1 Sir Pelleas", "npctypes"),
            new GamevalEntry(4348, "SIR_GAWAIN_4348", "Sir Gawain", "npctypes"),
            new GamevalEntry(4349, "SIR_KAY_4349", "Sir Kay", "npctypes"),
            new GamevalEntry(4350, "ID_4350_1_Z_1_SIR_PELLEAS", ") 1 ? 1 Sir Pelleas", "npctypes"),
            new GamevalEntry(4351, "SIR_GAWAIN_4351", "Sir Gawain", "npctypes"),
            new GamevalEntry(4352, "SIR_KAY_4352", "Sir Kay", "npctypes"),
            new GamevalEntry(4353, "SQUIRE_4353", "Squire", "npctypes"),
            new GamevalEntry(4354, "SIR_LANCELOT_4354", "Sir Lancelot", "npctypes"),
            new GamevalEntry(4355, "SIR_KAY_4355", "Sir Kay", "npctypes"),
            new GamevalEntry(4356, "SIR_GAWAIN_4356", "Sir Gawain", "npctypes"),
            new GamevalEntry(4357, "SIR_LUCAN_4357", "Sir Lucan", "npctypes"),
            new GamevalEntry(4358, "SIR_PALOMEDES_4358", "Sir Palomedes", "npctypes"),
            new GamevalEntry(4359, "SIR_TRISTRAM_4359", "Sir Tristram", "npctypes"),
            new GamevalEntry(4360, "ID_4360_1_Z_1_SIR_PELLEAS", ") 1 ? 1 Sir Pelleas", "npctypes"),
            new GamevalEntry(4361, "SIR_BEDIVERE_4361", "Sir Bedivere", "npctypes"),
            new GamevalEntry(4362, "OGRE_CHIEFTAIN", "Ogre chieftain", "npctypes"),
            new GamevalEntry(4363, "OGRE_CHIEFTAIN_4363", "Ogre chieftain", "npctypes"),
            new GamevalEntry(4364, "F_E_TALK_TO", "f e Talk-to", "npctypes"),
            new GamevalEntry(4365, "F_E_TALK_TO_4365", "f e Talk-to", "npctypes"),
            new GamevalEntry(4366, "F_E_TALK_TO_4366", "f e Talk-to", "npctypes"),
            new GamevalEntry(4367, "F_E_TALK_TO_4367", "f e Talk-to", "npctypes"),
            new GamevalEntry(4368, "OGRE_GUARD_4368", "Ogre guard", "npctypes"),
            new GamevalEntry(4369, "OGRE_GUARD_4369", "Ogre guard", "npctypes"),
            new GamevalEntry(4370, "OGRE_GUARD_4370", "Ogre guard", "npctypes"),
            new GamevalEntry(4371, "OGRE_GUARD_4371", "Ogre guard", "npctypes"),
            new GamevalEntry(4372, "OGRE_GUARD_4372", "Ogre guard", "npctypes"),
            new GamevalEntry(4373, "CITY_GUARD", "City guard", "npctypes"),
            new GamevalEntry(4374, "SCARED_SKAVID", "Scared skavid", "npctypes"),
            new GamevalEntry(4375, "MAD_SKAVID", "Mad skavid", "npctypes"),
            new GamevalEntry(4376, "SKAVID_4376", "Skavid", "npctypes"),
            new GamevalEntry(4377, "SKAVID_4377", "Skavid", "npctypes"),
            new GamevalEntry(4378, "SKAVID_4378", "Skavid", "npctypes"),
            new GamevalEntry(4379, "SKAVID_4379", "Skavid", "npctypes"),
            new GamevalEntry(4380, "SKAVID_4380", "Skavid", "npctypes"),
            new GamevalEntry(4381, "ENCLAVE_GUARD", "Enclave guard", "npctypes"),
            new GamevalEntry(4382, "OGRE_SHAMAN_4382", "Ogre shaman", "npctypes"),
            new GamevalEntry(4383, "OGRE_SHAMAN_4383", "Ogre shaman", "npctypes"),
            new GamevalEntry(4384, "OGRE_SHAMAN_4384", "Ogre shaman", "npctypes"),
            new GamevalEntry(4385, "BLUE_DRAGON_4385", "Blue dragon", "npctypes"),
            new GamevalEntry(4386, "OGRE_SHAMAN_4386", "Ogre shaman", "npctypes"),
            new GamevalEntry(4387, "OGRE_SHAMAN_4387", "Ogre shaman", "npctypes"),
            new GamevalEntry(4388, "OGRE_SHAMAN_4388", "Ogre shaman", "npctypes"),
            new GamevalEntry(4389, "OGRE_SHAMAN_4389", "Ogre shaman", "npctypes"),
            new GamevalEntry(4390, "OGRE_SHAMAN_4390", "Ogre shaman", "npctypes"),
            new GamevalEntry(4391, "OGRE_SHAMAN_4391", "Ogre shaman", "npctypes"),
            new GamevalEntry(4392, "OGRE_SHAMAN_4392", "Ogre shaman", "npctypes"),
            new GamevalEntry(4393, "OGRE_SHAMAN_4393", "Ogre shaman", "npctypes"),
            new GamevalEntry(4394, "OGRE_SHAMAN_4394", "Ogre shaman", "npctypes"),
            new GamevalEntry(4395, "OGRE_SHAMAN_4395", "Ogre shaman", "npctypes"),
            new GamevalEntry(4396, "OGRE_SHAMAN_4396", "Ogre shaman", "npctypes"),
            new GamevalEntry(4397, "WATCHTOWER_WIZARD", "Watchtower Wizard", "npctypes"),
            new GamevalEntry(4398, "WIZARD_4398", "Wizard", "npctypes"),
            new GamevalEntry(4399, "WIZARD_4399", "Wizard", "npctypes"),
            new GamevalEntry(4400, "WIZARD_4400", "Wizard", "npctypes"),
            new GamevalEntry(4401, "OGRE_TRADER", "Ogre trader", "npctypes"),
            new GamevalEntry(4402, "OGRE_MERCHANT", "Ogre merchant", "npctypes"),
            new GamevalEntry(4403, "OGRE_TRADER_4403", "Ogre trader", "npctypes"),
            new GamevalEntry(4404, "OGRE_TRADER_4404", "Ogre trader", "npctypes"),
            new GamevalEntry(4405, "TOWER_GUARD", "Tower guard", "npctypes"),
            new GamevalEntry(4406, "COLONEL_RADICK", "Colonel Radick", "npctypes"),
            new GamevalEntry(4407, "AVA", "Ava", "npctypes"),
            new GamevalEntry(4408, "ID_4408", "", "npctypes"),
            new GamevalEntry(4409, "WITCH_4409", "Witch", "npctypes"),
            new GamevalEntry(4410, "ID_4410", "", "npctypes"),
            new GamevalEntry(4411, "MALCOLM", "Malcolm", "npctypes"),
            new GamevalEntry(4412, "MALCOLM_4412", "Malcolm", "npctypes"),
            new GamevalEntry(4413, "MALCOLM_4413", "Malcolm", "npctypes"),
            new GamevalEntry(4414, "MALCOLM_4414", "Malcolm", "npctypes"),
            new GamevalEntry(4415, "ID_4415", "", "npctypes"),
            new GamevalEntry(4416, "TREE_4416", "Tree", "npctypes"),
            new GamevalEntry(4417, "UNDEAD_TREE", "Undead tree", "npctypes"),
            new GamevalEntry(4418, "ID_4418", "", "npctypes"),
            new GamevalEntry(4419, "SNEAKY_UNDEAD_FOWL", "Sneaky undead fowl", "npctypes"),
            new GamevalEntry(4420, "COW31337KILLER", "Cow31337Killer", "npctypes"),
            new GamevalEntry(4421, "UNDEAD_COW_4421", "Undead cow", "npctypes"),
            new GamevalEntry(4422, "ALICE_4422", "Alice", "npctypes"),
            new GamevalEntry(4423, "JOSSIK", "Jossik", "npctypes"),
            new GamevalEntry(4424, "JOSSIK_4424", "Jossik", "npctypes"),
            new GamevalEntry(4425, "LARRISSA", "Larrissa", "npctypes"),
            new GamevalEntry(4426, "LARRISSA_4426", "Larrissa", "npctypes"),
            new GamevalEntry(4427, "VAMPYRE_JUVINATE_4427", "Vampyre Juvinate", "npctypes"),
            new GamevalEntry(4428, "VAMPYRE_JUVINATE_4428", "Vampyre Juvinate", "npctypes"),
            new GamevalEntry(4429, "VAMPYRE_JUVINATE_4429", "Vampyre Juvinate", "npctypes"),
            new GamevalEntry(4430, "VAMPYRE_JUVINATE_4430", "Vampyre Juvinate", "npctypes"),
            new GamevalEntry(4431, "FERAL_VAMPYRE_4431", "Feral Vampyre", "npctypes"),
            new GamevalEntry(4432, "VAMPYRE_JUVINATE_4432", "Vampyre Juvinate", "npctypes"),
            new GamevalEntry(4433, "VAMPYRE_JUVINATE_4433", "Vampyre Juvinate", "npctypes"),
            new GamevalEntry(4434, "VAMPYRE_JUVINATE_4434", "Vampyre Juvinate", "npctypes"),
            new GamevalEntry(4435, "MIST_4435", "Mist", "npctypes"),
            new GamevalEntry(4436, "VAMPYRE_JUVENILE_4436", "Vampyre Juvenile", "npctypes"),
            new GamevalEntry(4437, "VAMPYRE_JUVENILE_4437", "Vampyre Juvenile", "npctypes"),
            new GamevalEntry(4438, "VAMPYRE_JUVENILE_4438", "Vampyre Juvenile", "npctypes"),
            new GamevalEntry(4439, "VAMPYRE_JUVENILE_4439", "Vampyre Juvenile", "npctypes"),
            new GamevalEntry(4440, "IVAN_STROM", "Ivan Strom", "npctypes"),
            new GamevalEntry(4441, "IVAN_STROM_4441", "Ivan Strom", "npctypes"),
            new GamevalEntry(4442, "VAMPYRE_JUVINATE_4442", "Vampyre Juvinate", "npctypes"),
            new GamevalEntry(4443, "VAMPYRE_JUVINATE_4443", "Vampyre Juvinate", "npctypes"),
            new GamevalEntry(4444, "XA", "Xa", "npctypes"),
            new GamevalEntry(4445, "X_TALK_TO", "X Talk-to", "npctypes"),
            new GamevalEntry(4446, "XJ", "XJ", "npctypes"),
            new GamevalEntry(4447, "LUSCION", "Luscion", "npctypes"),
            new GamevalEntry(4448, "SERGIU", "Sergiu", "npctypes"),
            new GamevalEntry(4449, "RADU", "Radu", "npctypes"),
            new GamevalEntry(4450, "GRIGORE", "Grigore", "npctypes"),
            new GamevalEntry(4451, "ILEANA", "Ileana", "npctypes"),
            new GamevalEntry(4452, "VALERIA", "Valeria", "npctypes"),
            new GamevalEntry(4453, "EMILIA", "Emilia", "npctypes"),
            new GamevalEntry(4454, "FLORIN", "Florin", "npctypes"),
            new GamevalEntry(4455, "CATALINA", "Catalina", "npctypes"),
            new GamevalEntry(4456, "IVAN", "Ivan", "npctypes"),
            new GamevalEntry(4457, "VICTOR", "Victor", "npctypes"),
            new GamevalEntry(4458, "HELENA", "Helena", "npctypes"),
            new GamevalEntry(4459, "X_TALK_TO_4459", "X Talk-to", "npctypes"),
            new GamevalEntry(4460, "XG", "Xg", "npctypes"),
            new GamevalEntry(4461, "GABRIELA", "Gabriela", "npctypes"),
            new GamevalEntry(4463, "CALIN", "Calin", "npctypes"),
            new GamevalEntry(4464, "MIHAIL", "Mihail", "npctypes"),
            new GamevalEntry(4465, "NICOLETA", "Nicoleta", "npctypes"),
            new GamevalEntry(4466, "SIMONA", "Simona", "npctypes"),
            new GamevalEntry(4467, "ID_4467", "", "npctypes"),
            new GamevalEntry(4468, "RAZVAN", "Razvan", "npctypes"),
            new GamevalEntry(4469, "LUMINATA", "Luminata", "npctypes"),
            new GamevalEntry(4470, "CORNELIUS", "Cornelius", "npctypes"),
            new GamevalEntry(4471, "CORNELIUS_4471", "Cornelius", "npctypes"),
            new GamevalEntry(4472, "BENJAMIN_4472", "Benjamin", "npctypes"),
            new GamevalEntry(4473, "LIAM_4473", "Liam", "npctypes"),
            new GamevalEntry(4474, "MIALA_4474", "Miala", "npctypes"),
            new GamevalEntry(4475, "VERAK_4475", "Verak", "npctypes"),
            new GamevalEntry(4476, "FISHING_SPOT_4476", "Fishing spot", "npctypes"),
            new GamevalEntry(4477, "FISHING_SPOT_4477", "Fishing spot", "npctypes"),
            new GamevalEntry(4478, "XJ_4478", "XJ", "npctypes"),
            new GamevalEntry(4479, "ID_4479", "", "npctypes"),
            new GamevalEntry(4480, "WISKIT", "Wiskit", "npctypes"),
            new GamevalEntry(4481, "VAMPYRE_JUVINATE_4481", "Vampyre Juvinate", "npctypes"),
            new GamevalEntry(4482, "VAMPYRE_JUVINATE_4482", "Vampyre Juvinate", "npctypes"),
            new GamevalEntry(4483, "GADDERANKS", "Gadderanks", "npctypes"),
            new GamevalEntry(4484, "GADDERANKS_4484", "Gadderanks", "npctypes"),
            new GamevalEntry(4485, "GADDERANKS_4485", "Gadderanks", "npctypes"),
            new GamevalEntry(4486, "VAMPYRE_JUVINATE_4486", "Vampyre Juvinate", "npctypes"),
            new GamevalEntry(4487, "VAMPYRE_JUVINATE_4487", "Vampyre Juvinate", "npctypes"),
            new GamevalEntry(4488, "OLAF_HRADSON", "Olaf Hradson", "npctypes"),
            new GamevalEntry(4489, "VOLF_OLAFSON", "Volf Olafson", "npctypes"),
            new GamevalEntry(4490, "INGRID_HRADSON", "Ingrid Hradson", "npctypes"),
            new GamevalEntry(4491, "SKELETON_FREMENNIK", "Skeleton fremennik", "npctypes"),
            new GamevalEntry(4492, "SKELETON_FREMENNIK_4492", "Skeleton fremennik", "npctypes"),
            new GamevalEntry(4493, "SKELETON_FREMENNIK_4493", "Skeleton fremennik", "npctypes"),
            new GamevalEntry(4494, "SKELETON_FREMENNIK_4494", "Skeleton fremennik", "npctypes"),
            new GamevalEntry(4495, "SKELETON_FREMENNIK_4495", "Skeleton fremennik", "npctypes"),
            new GamevalEntry(4496, "SKELETON_FREMENNIK_4496", "Skeleton fremennik", "npctypes"),
            new GamevalEntry(4497, "SKELETON_FREMENNIK_4497", "Skeleton fremennik", "npctypes"),
            new GamevalEntry(4498, "SKELETON_FREMENNIK_4498", "Skeleton fremennik", "npctypes"),
            new GamevalEntry(4499, "SKELETON_FREMENNIK_4499", "Skeleton fremennik", "npctypes"),
            new GamevalEntry(4500, "ULFRIC", "Ulfric", "npctypes"),
            new GamevalEntry(4501, "BRINE_RAT", "Brine rat", "npctypes"),
            new GamevalEntry(4502, "BOULDER_4502", "Boulder", "npctypes"),
            new GamevalEntry(4503, "BOULDER_4503", "Boulder", "npctypes"),
            new GamevalEntry(4504, "GIANT_BAT_4504", "Giant bat", "npctypes"),
            new GamevalEntry(4505, "ULFRIC_4505", "Ulfric", "npctypes"),
            new GamevalEntry(4506, "ZANIK_4506", "Zanik", "npctypes"),
            new GamevalEntry(4507, "ID_4507", "", "npctypes"),
            new GamevalEntry(4508, "ZANIK_4508", "Zanik", "npctypes"),
            new GamevalEntry(4509, "ZANIK_4509", "Zanik", "npctypes"),
            new GamevalEntry(4510, "ZANIK_4510", "Zanik", "npctypes"),
            new GamevalEntry(4511, "FZCN", "fzcN", "npctypes"),
            new GamevalEntry(4512, "DWARF_4512", "Dwarf", "npctypes"),
            new GamevalEntry(4513, "H_A_M_MEMBER_4513", "H.A.M. Member", "npctypes"),
            new GamevalEntry(4514, "H_A_M_MEMBER_4514", "H.A.M. Member", "npctypes"),
            new GamevalEntry(4515, "I", "i_", "npctypes"),
            new GamevalEntry(4516, "GUARD_4516", "Guard", "npctypes"),
            new GamevalEntry(4517, "GUARD_4517", "Guard", "npctypes"),
            new GamevalEntry(4518, "GUARD_4518", "Guard", "npctypes"),
            new GamevalEntry(4519, "GUARD_4519", "Guard", "npctypes"),
            new GamevalEntry(4520, "GUARD_4520", "Guard", "npctypes"),
            new GamevalEntry(4521, "GUARD_4521", "Guard", "npctypes"),
            new GamevalEntry(4522, "GUARD_4522", "Guard", "npctypes"),
            new GamevalEntry(4523, "GUARD_4523", "Guard", "npctypes"),
            new GamevalEntry(4524, "GUARD_4524", "Guard", "npctypes"),
            new GamevalEntry(4525, "GUARD_4525", "Guard", "npctypes"),
            new GamevalEntry(4526, "GUARD_4526", "Guard", "npctypes"),
            new GamevalEntry(4527, "CHADWELL", "Chadwell", "npctypes"),
            new GamevalEntry(4528, "ID_4528", "", "npctypes"),
            new GamevalEntry(4529, "ID_4529", "", "npctypes"),
            new GamevalEntry(4530, "ID_4530", "", "npctypes"),
            new GamevalEntry(4531, "ID_4531", "", "npctypes"),
            new GamevalEntry(4532, "ID_4532", "", "npctypes"),
            new GamevalEntry(4533, "BLESSED_SPIDER", "Blessed spider", "npctypes"),
            new GamevalEntry(4534, "BLESSED_GIANT_RAT", "Blessed giant rat", "npctypes"),
            new GamevalEntry(4535, "BLESSED_GIANT_RAT_4535", "Blessed giant rat", "npctypes"),
            new GamevalEntry(4536, "ID_4536", "", "npctypes"),
            new GamevalEntry(4537, "ID_4537", "", "npctypes"),
            new GamevalEntry(4538, "ID_4538", "", "npctypes"),
            new GamevalEntry(4539, "ID_4539", "", "npctypes"),
            new GamevalEntry(4540, "ID_4540", "", "npctypes"),
            new GamevalEntry(4541, "ID_4541", "", "npctypes"),
            new GamevalEntry(4542, "ID_4542", "", "npctypes"),
            new GamevalEntry(4543, "BOULDER_4543", "Boulder", "npctypes"),
            new GamevalEntry(4544, "ID_4544", "", "npctypes"),
            new GamevalEntry(4545, "ID_4545", "", "npctypes"),
            new GamevalEntry(4546, "ID_4546", "", "npctypes"),
            new GamevalEntry(4547, "ID_4547", "", "npctypes"),
            new GamevalEntry(4548, "ID_4548", "", "npctypes"),
            new GamevalEntry(4549, "ID_4549", "", "npctypes"),
            new GamevalEntry(4550, "ID_4550", "", "npctypes"),
            new GamevalEntry(4551, "NILOOF", "Niloof", "npctypes"),
            new GamevalEntry(4552, "KLANK", "Klank", "npctypes"),
            new GamevalEntry(4553, "KAMEN", "Kamen", "npctypes"),
            new GamevalEntry(4554, "ID_4554", "", "npctypes"),
            new GamevalEntry(4555, "ID_4555", "", "npctypes"),
            new GamevalEntry(4556, "ID_4556", "", "npctypes"),
            new GamevalEntry(4557, "ID_4557", "", "npctypes"),
            new GamevalEntry(4558, "ID_4558", "", "npctypes"),
            new GamevalEntry(4559, "ID_4559", "", "npctypes"),
            new GamevalEntry(4560, "ID_4560", "", "npctypes"),
            new GamevalEntry(4561, "ATTACK_4561", "Attack", "npctypes"),
            new GamevalEntry(4562, "GIANT_BAT_4562", "Giant bat", "npctypes"),
            new GamevalEntry(4563, "MONK_4563", "Monk", "npctypes"),
            new GamevalEntry(4564, "DEAD_MONK", "Dead Monk", "npctypes"),
            new GamevalEntry(4565, "HIGH_PRIEST_4565", "High Priest", "npctypes"),
            new GamevalEntry(4566, "MONK_4566", "Monk", "npctypes"),
            new GamevalEntry(4567, "MONK_4567", "Monk", "npctypes"),
            new GamevalEntry(4568, "ASSASSIN", "Assassin", "npctypes"),
            new GamevalEntry(4569, "RED_AXE_HENCHMAN_4569", "Red Axe Henchman", "npctypes"),
            new GamevalEntry(4570, "RED_AXE_HENCHMAN_4570", "Red Axe Henchman", "npctypes"),
            new GamevalEntry(4571, "OGRE_SHAMAN_4571", "Ogre shaman", "npctypes"),
            new GamevalEntry(4572, "L_A_4572", "l a", "npctypes"),
            new GamevalEntry(4573, "L_A_4573", "l a", "npctypes"),
            new GamevalEntry(4574, "L_A_4574", "l a", "npctypes"),
            new GamevalEntry(4575, "L_A_4575", "l a", "npctypes"),
            new GamevalEntry(4576, "L_A_4576", "l a", "npctypes"),
            new GamevalEntry(4577, "ID_4577", "", "npctypes"),
            new GamevalEntry(4578, "COUNCILLOR_HALGRIVE", "Councillor Halgrive", "npctypes"),
            new GamevalEntry(4579, "SPICE_SELLER_4579", "Spice seller", "npctypes"),
            new GamevalEntry(4580, "FUR_TRADER_4580", "Fur trader", "npctypes"),
            new GamevalEntry(4581, "GEM_MERCHANT_4581", "Gem merchant", "npctypes"),
            new GamevalEntry(4582, "SILVER_MERCHANT", "Silver merchant", "npctypes"),
            new GamevalEntry(4583, "SILK_MERCHANT_4583", "Silk merchant", "npctypes"),
            new GamevalEntry(4584, "ZENESHA", "Zenesha", "npctypes"),
            new GamevalEntry(4585, "ALI_MORRISANE_4585", "Ali Morrisane", "npctypes"),
            new GamevalEntry(4586, "GRIMESQUIT", "Grimesquit", "npctypes"),
            new GamevalEntry(4587, "PHINGSPET", "Phingspet", "npctypes"),
            new GamevalEntry(4588, "HOOKNOSED_JACK", "Hooknosed Jack", "npctypes"),
            new GamevalEntry(4589, "JIMMY_DAZZLER", "Jimmy Dazzler", "npctypes"),
            new GamevalEntry(4590, "THE_FACE", "The Face", "npctypes"),
            new GamevalEntry(4591, "FELKRASH", "Felkrash", "npctypes"),
            new GamevalEntry(4592, "SMOKIN_JOE", "Smokin' Joe", "npctypes"),
            new GamevalEntry(4593, "RAT_4593", "Rat", "npctypes"),
            new GamevalEntry(4594, "RAT_4594", "Rat", "npctypes"),
            new GamevalEntry(4595, "KING_RAT", "King rat", "npctypes"),
            new GamevalEntry(4596, "TURBOGROOMER", "Turbogroomer", "npctypes"),
            new GamevalEntry(4597, "PUSSKINS", "Pusskins", "npctypes"),
            new GamevalEntry(4598, "LOKI", "Loki", "npctypes"),
            new GamevalEntry(4599, "CAPTAIN_TOM", "Captain Tom", "npctypes"),
            new GamevalEntry(4600, "TREACLE", "Treacle", "npctypes"),
            new GamevalEntry(4601, "MITTENS", "Mittens", "npctypes"),
            new GamevalEntry(4602, "CLAUDE", "Claude", "npctypes"),
            new GamevalEntry(4603, "TOPSY", "Topsy", "npctypes"),
            new GamevalEntry(4604, "RAUBORN", "Rauborn", "npctypes"),
            new GamevalEntry(4605, "VAERINGK", "Vaeringk", "npctypes"),
            new GamevalEntry(4606, "OXI", "Oxi", "npctypes"),
            new GamevalEntry(4607, "FIOR", "Fior", "npctypes"),
            new GamevalEntry(4608, "SAGIRA", "Sagira", "npctypes"),
        };
    }

    static Optional<GamevalEntry> byId(int id) {
        for (GamevalEntry entry : entries()) {
            if (entry.id() == id) return Optional.of(entry);
        }
        return Optional.empty();
    }

}
