package net.titan.gamevals.internal;

import java.util.Optional;

import net.titan.gamevals.GamevalEntry;
import net.titan.gamevals.QuestEntry;

final class NpcIDEntries_24 {
    private NpcIDEntries_24() {}

    static GamevalEntry[] entries() {
        return new GamevalEntry[] {
            new GamevalEntry(12290, "DT2_STRANGLED_LYNX", "Strangled Lynx", "npctypes"),
            new GamevalEntry(12291, "DT2_ASGARNIA_SMITH_VIS", "Asgarnia Smith", "npctypes"),
            new GamevalEntry(12292, "DT2_ASGARNIA_SMITH_CUTSCENE", "Asgarnia Smith", "npctypes"),
            new GamevalEntry(12293, "DT2_BANIKAN_VIS", "Dr Banikan", "npctypes"),
            new GamevalEntry(12294, "DT2_BANIKAN_CUTSCENE", "Dr Banikan", "npctypes"),
            new GamevalEntry(12295, "DT2_BANIKAN_CUTSCENE_HIDDEN", "Mysterious Voice", "npctypes"),
            new GamevalEntry(12296, "DT2_BANIKAN_FOLLOWER", "dt2_banikan_follower", "npctypes"),
            new GamevalEntry(12297, "DT2_PURSUER_VIS", "Mysterious Figure", "npctypes"),
            new GamevalEntry(12298, "DT2_PURSUER_CUTSCENE", "Mysterious Figure", "npctypes"),
            new GamevalEntry(12299, "DT2_PURSUER_DISGUISED", "Sandwich lady", "npctypes"),
            new GamevalEntry(12300, "DT2_PURSUER_OVERWORLD_COMBAT", "Mysterious Figure", "npctypes"),
            new GamevalEntry(12301, "DT2_PURSUER_HIDEOUT_COMBAT", "Mysterious Figure", "npctypes"),
            new GamevalEntry(12302, "DT2_HAZEEL_VIS", "Hazeel", "npctypes"),
            new GamevalEntry(12303, "DT2_HAZEEL_CUTSCENE", "Hazeel", "npctypes"),
            new GamevalEntry(12304, "DT2_HAZEEL_COMBAT", "Hazeel", "npctypes"),
            new GamevalEntry(12305, "DT2_AZZANADRA_VIS", "Azzanadra", "npctypes"),
            new GamevalEntry(12306, "DT2_AZZANADRA_CUTSCENE", "Azzanadra", "npctypes"),
            new GamevalEntry(12307, "DT2_AZZANADRA_CUTSCENE_3", "Azzanadra", "npctypes"),
            new GamevalEntry(12308, "DT2_AZZANADRA_COMBAT", "Azzanadra", "npctypes"),
            new GamevalEntry(12309, "DT2_ENAKHRA_CUTSCENE", "Enakhra", "npctypes"),
            new GamevalEntry(12310, "DT2_ENAKHRA_COMBAT", "Enakhra", "npctypes"),
            new GamevalEntry(12311, "DT2_AKTHANAKOS_CUTSCENE", "Akthanakos", "npctypes"),
            new GamevalEntry(12312, "DT2_AKTHANAKOS_COMBAT", "Akthanakos", "npctypes"),
            new GamevalEntry(12313, "DT2_AKTHANAKOS_CAMEL", "Akthanakos", "npctypes"),
            new GamevalEntry(12314, "DT2_SLISKE_CUTSCENE", "Sliske", "npctypes"),
            new GamevalEntry(12315, "DT2_SLISKE_CUTSCENE_TELEPORTING", "Sliske", "npctypes"),
            new GamevalEntry(12316, "DT2_AHRIM_CUTSCENE", "Ahrim the Blighted", "npctypes"),
            new GamevalEntry(12317, "DT2_DHAROK_CUTSCENE", "Dharok the Wretched", "npctypes"),
            new GamevalEntry(12318, "DT2_GUTHAN_CUTSCENE", "Guthan the Infested", "npctypes"),
            new GamevalEntry(12319, "DT2_KARIL_CUTSCENE", "Karil the Tainted", "npctypes"),
            new GamevalEntry(12320, "DT2_TORAG_CUTSCENE", "Torag the Corrupted", "npctypes"),
            new GamevalEntry(12321, "DT2_VERAC_CUTSCENE", "Verac the Defiled", "npctypes"),
            new GamevalEntry(12322, "DT2_AHRIM_COMBAT", "Ahrim the Blighted", "npctypes"),
            new GamevalEntry(12323, "DT2_DHAROK_COMBAT", "Dharok the Wretched", "npctypes"),
            new GamevalEntry(12324, "DT2_GUTHAN_COMBAT", "Guthan the Infested", "npctypes"),
            new GamevalEntry(12325, "DT2_KARIL_COMBAT", "Karil the Tainted", "npctypes"),
            new GamevalEntry(12326, "DT2_TORAG_COMBAT", "Torag the Corrupted", "npctypes"),
            new GamevalEntry(12327, "DT2_VERAC_COMBAT", "Verac the Defiled", "npctypes"),
            new GamevalEntry(12328, "DT2_ASSASSIN_WIGHT_COMBAT", "The Forsaken Assassin", "npctypes"),
            new GamevalEntry(12329, "DT2_KETLA_WIGHT_COMBAT", "Ketla the Unworthy", "npctypes"),
            new GamevalEntry(12330, "DT2_KETLA_WIGHT_COMBAT_CLONE", "Ketla the Unworthy", "npctypes"),
            new GamevalEntry(12331, "DT2_KASONDE_WIGHT_COMBAT", "Kasonde the Craven", "npctypes"),
            new GamevalEntry(12332, "DT2_KASONDE_WIGHT_COMBAT_OPBREAK", "Kasonde the Craven", "npctypes"),
            new GamevalEntry(12333, "DT2_PERSTEN_WIGHT_COMBAT", "Persten the Deceitful", "npctypes"),
            new GamevalEntry(12334, "DT2_WIGHT_PERSTEN_PORTAL", "Portal", "npctypes"),
            new GamevalEntry(12335, "DT2_WIGHT_PERSTEN_NPC", "Wighted Leech", "npctypes"),
            new GamevalEntry(12336, "DT2_ANCIENT_GUARDIAN", "Ancient Guardian", "npctypes"),
            new GamevalEntry(12337, "DT2_ANCIENT_GUARDIAN_SHIELD", "Ancient Guardian", "npctypes"),
            new GamevalEntry(12338, "DT2_WARMIND", "Golem", "npctypes"),
            new GamevalEntry(12339, "DT2_WAR_ROOM_SMOKE_TOTEM_INACTIVE", "Smoke Totem", "npctypes"),
            new GamevalEntry(12340, "DT2_WAR_ROOM_SMOKE_TOTEM_ACTIVE", "Smoke Totem", "npctypes"),
            new GamevalEntry(12341, "DT2_WAR_ROOM_SHADOW_TOTEM_INACTIVE", "Shadow Totem", "npctypes"),
            new GamevalEntry(12342, "DT2_WAR_ROOM_SHADOW_TOTEM_ACTIVE", "Shadow Totem", "npctypes"),
            new GamevalEntry(12343, "DT2_WAR_ROOM_BLOOD_TOTEM_INACTIVE", "Blood Totem", "npctypes"),
            new GamevalEntry(12344, "DT2_WAR_ROOM_BLOOD_TOTEM_ACTIVE", "Blood Totem", "npctypes"),
            new GamevalEntry(12345, "DT2_WAR_ROOM_ICE_TOTEM_INACTIVE", "Ice Totem", "npctypes"),
            new GamevalEntry(12346, "DT2_WAR_ROOM_ICE_TOTEM_ACTIVE", "Ice Totem", "npctypes"),
            new GamevalEntry(12347, "DT2_VAULT_BANDIT_VIS", "Mysterious Bandit", "npctypes"),
            new GamevalEntry(12348, "DT2_ASSASSIN_GHORROCK_INSTANCE", "Assassin", "npctypes"),
            new GamevalEntry(12349, "DT2_ASSASSIN_GHORROCK_VIS", "Assassin", "npctypes"),
            new GamevalEntry(12350, "DT2_ASSASSIN_CUTSCENE", "Assassin", "npctypes"),
            new GamevalEntry(12351, "DT2_ASSASSIN_CUTSCENE_3", "Assassin", "npctypes"),
            new GamevalEntry(12352, "DT2_ASSASSIN_ANON", "Mysterious Voice", "npctypes"),
            new GamevalEntry(12353, "DT2_JHALLAN_CHASE", "Jhallan", "npctypes"),
            new GamevalEntry(12354, "DT2_JHALLAN_COMBAT", "Jhallan", "npctypes"),
            new GamevalEntry(12355, "DT2_JHALLAN_CUTSCENE", "Jhallan", "npctypes"),
            new GamevalEntry(12356, "DT2_SCAR_MAZE_1_ELECTRIC_NPC", "Cerebral pathfinder", "npctypes"),
            new GamevalEntry(12357, "DT2_SCAR_MAZE_1_ELECTRIC_NPC_REVERSE", "Cerebral pathbreaker", "npctypes"),
            new GamevalEntry(12358, "DT2_SCAR_MAZE_1_RITUAL_NPC", "dt2_scar_maze_1_ritual_npc", "npctypes"),
            new GamevalEntry(12359, "DT2_SCAR_MAZE_1_RITUAL_CATALYST", "Catalyst", "npctypes"),
            new GamevalEntry(12360, "DT2_SCAR_MAZE_MAGE_DEMON", "Scarred lesser demon", "npctypes"),
            new GamevalEntry(12361, "DT2_SCAR_MAZE_MAGE_DEMON_NORMAL", "Lesser demon", "npctypes"),
            new GamevalEntry(12362, "DT2_SCAR_MAZE_MELEE_DEMON", "Scarred lesser demon", "npctypes"),
            new GamevalEntry(12363, "DT2_SCAR_MAZE_MELEE_DEMON_NORMAL", "Lesser demon", "npctypes"),
            new GamevalEntry(12364, "DT2_SCAR_MAZE_RANGED_DEMON", "Scarred lesser demon", "npctypes"),
            new GamevalEntry(12365, "DT2_SCAR_MAZE_RANGED_DEMON_NORMAL", "Lesser demon", "npctypes"),
            new GamevalEntry(12366, "DT2_SCAR_MAZE_LEECH", "Abyssal leech", "npctypes"),
            new GamevalEntry(12367, "DT2_SCAR_MAZE_LIGHT_LEECH", "Light leech", "npctypes"),
            new GamevalEntry(12368, "DT2_SCAR_MAZE_LIGHT_LEECH_AGGRESSIVE", "Light leech", "npctypes"),
            new GamevalEntry(12369, "DT2_SCAR_MAZE_2_BLOOD_CELL_RED", "Crimson sanguisphera", "npctypes"),
            new GamevalEntry(12370, "DT2_SCAR_MAZE_2_BLOOD_CELL_WHITE", "Radiant sanguisphera", "npctypes"),
            new GamevalEntry(12371, "DT2_SCAR_MAZE_2_PILLAR", "Brain Pillar", "npctypes"),
            new GamevalEntry(12372, "DT2_SCAR_MAZE_2_PILLAR_REPAIRER", "Abyssal antibody", "npctypes"),
            new GamevalEntry(12373, "DT2_SCAR_MAZE_2_PILLAR_ATTACKER", "Scarred greater demon", "npctypes"),
            new GamevalEntry(12374, "DT2_SCAR_MAZE_2_PILLAR_ATTACKER_DOG", "Scarred hellhound", "npctypes"),
            new GamevalEntry(12375, "DT2_SCAR_MAZE_3_PATHING_NPC", "Abyssal axon", "npctypes"),
            new GamevalEntry(12376, "DT2_SCAR_MAZE_3_LINK_CHANTER", "Lesser demon", "npctypes"),
            new GamevalEntry(12377, "DT2_SCAR_MAZE_3_LINK_NPC", "Scarred imp", "npctypes"),
            new GamevalEntry(12378, "DT2_SCAR_MAZE_3_LINK_ATTACKER", "Scarred lesser demon", "npctypes"),
            new GamevalEntry(12379, "DT2_SCAR_MAZE_3_LINK_ATTACKER_DOG", "Scarred hellhound", "npctypes"),
            new GamevalEntry(12380, "DT2_PERSTEN_SCAR_VIS", "Wizard Persten", "npctypes"),
            new GamevalEntry(12381, "DT2_PERSTEN_CUTSCENE", "Wizard Persten", "npctypes"),
            new GamevalEntry(12382, "DT2_PERSTEN_CUTSCENE_NOSTAFF", "Wizard Persten", "npctypes"),
            new GamevalEntry(12383, "DT2_CATALYTIC_GUARDIAN_1OP", "Catalytic Guardian", "npctypes"),
            new GamevalEntry(12384, "DT2_CATALYTIC_GUARDIAN_2OPS", "Catalytic Guardian", "npctypes"),
            new GamevalEntry(12385, "DT2_SCAR_BLACK_DEMON_1", "Black demon", "npctypes"),
            new GamevalEntry(12386, "DT2_SCAR_BLACK_DEMON_2", "Scarred black demon", "npctypes"),
            new GamevalEntry(12387, "DT2_SCAR_GREATER_DEMON_1", "Greater demon", "npctypes"),
            new GamevalEntry(12388, "DT2_SCAR_GREATER_DEMON_2", "Scarred greater demon", "npctypes"),
            new GamevalEntry(12389, "DT2_SCAR_LESSER_DEMON_1", "Lesser demon", "npctypes"),
            new GamevalEntry(12390, "DT2_SCAR_LESSER_DEMON_2", "Scarred lesser demon", "npctypes"),
            new GamevalEntry(12391, "DT2_SCAR_ABYSSAL_LEECH", "Abyssal leech", "npctypes"),
            new GamevalEntry(12392, "DT2_SCAR_ABYSSAL_WALKER", "Abyssal walker", "npctypes"),
            new GamevalEntry(12393, "DT2_SCAR_LEECH", "Abyssal leech", "npctypes"),
            new GamevalEntry(12394, "DT2_SCAR_WALKER", "Abyssal walker", "npctypes"),
            new GamevalEntry(12395, "ENAKH_ENAKHRA_HOODED_CUTSCENE", "Enakhra", "npctypes"),
            new GamevalEntry(12396, "ENAKH_AKTHANAKOS_BONEGUARD_MULTINPC", "enakh_akthanakos_boneguard_multinpc", "npctypes"),
            new GamevalEntry(12397, "ENAKH_AKTHANAKOS_FREED_CUTSCENE", "Akthanakos", "npctypes"),
            new GamevalEntry(12398, "ENAKH_AKTHANAKOS_MAHJARRAT_CUTSCENE", "Akthanakos", "npctypes"),
            new GamevalEntry(12399, "DT2_KETLA_WORKSHOP", "dt2_ketla_workshop", "npctypes"),
            new GamevalEntry(12400, "DT2_KASONDE_HIDEOUT", "dt2_kasonde_hideout", "npctypes"),
            new GamevalEntry(12401, "DT2_ASGARNIA_SMITH_VAULT_INITIAL", "dt2_asgarnia_smith_vault_initial", "npctypes"),
            new GamevalEntry(12402, "DT2_ASGARNIA_SMITH_VAULT", "dt2_asgarnia_smith_vault", "npctypes"),
            new GamevalEntry(12403, "DT2_BANIKAN_DIGSITE", "dt2_banikan_digsite", "npctypes"),
            new GamevalEntry(12404, "DT2_BANIKAN_WAR_ROOM", "dt2_banikan_war_room", "npctypes"),
            new GamevalEntry(12405, "DT2_PURSUER_VAULT", "dt2_pursuer_vault", "npctypes"),
            new GamevalEntry(12406, "DT2_HAZEEL_VAULT", "dt2_hazeel_vault", "npctypes"),
            new GamevalEntry(12407, "DT2_AZZANADRA_VAULT", "dt2_azzanadra_vault", "npctypes"),
            new GamevalEntry(12408, "DT2_WAR_ROOM_SMOKE_TOTEM", "dt2_war_room_smoke_totem", "npctypes"),
            new GamevalEntry(12409, "DT2_WAR_ROOM_SHADOW_TOTEM", "dt2_war_room_shadow_totem", "npctypes"),
            new GamevalEntry(12410, "DT2_WAR_ROOM_BLOOD_TOTEM", "dt2_war_room_blood_totem", "npctypes"),
            new GamevalEntry(12411, "DT2_WAR_ROOM_ICE_TOTEM", "dt2_war_room_ice_totem", "npctypes"),
            new GamevalEntry(12412, "DT2_VAULT_BANDIT", "dt2_vault_bandit", "npctypes"),
            new GamevalEntry(12413, "DT2_ASSASSIN_GHORROCK_CAMP", "dt2_assassin_ghorrock_camp", "npctypes"),
            new GamevalEntry(12414, "DT2_ASSASSIN_GHORROCK_ASYLUM", "dt2_assassin_ghorrock_asylum", "npctypes"),
            new GamevalEntry(12415, "DT2_PERSTEN_SCAR", "dt2_persten_scar", "npctypes"),
            new GamevalEntry(12416, "DT2_PERSTEN_SCAR_ISLAND", "dt2_persten_scar_island", "npctypes"),
            new GamevalEntry(12417, "DT2_CATALYTIC_GUARDIAN", "dt2_catalytic_guardian", "npctypes"),
            new GamevalEntry(12418, "DT2_KETLA_CUTSCENE_INACTIVE", "dt2_ketla_cutscene_inactive", "npctypes"),
            new GamevalEntry(12419, "DT2_KASONDE_CUTSCENE_3_INACTIVE", "dt2_kasonde_cutscene_3_inactive", "npctypes"),
            new GamevalEntry(12420, "DT2_AZZANADRA_CUTSCENE_3_INACTIVE", "dt2_azzanadra_cutscene_3_inactive", "npctypes"),
            new GamevalEntry(12421, "DT2_SLISKE_CUTSCENE_INACTIVE", "dt2_sliske_cutscene_inactive", "npctypes"),
            new GamevalEntry(12422, "DT2_ASSASSIN_CUTSCENE_3_INACTIVE", "dt2_assassin_cutscene_3_inactive", "npctypes"),
            new GamevalEntry(12423, "DT2_PERSTEN_CUTSCENE_NOSTAFF_INACTIVE", "? J ?", "npctypes"),
            new GamevalEntry(12424, "VARDORVIS_BASE_ANON", "Strangled", "npctypes"),
            new GamevalEntry(12425, "VARDORVIS_BASE_QUEST", "Vardorvis", "npctypes"),
            new GamevalEntry(12426, "VARDORVIS_BASE_POSTQUEST", "Vardorvis", "npctypes"),
            new GamevalEntry(12427, "VARDORVIS_BASE", "vardorvis_base", "npctypes"),
            new GamevalEntry(12428, "RAIDS_MOUNTAINGUIDE_SOUTH_MULTI", "raids_mountainguide_south_multi", "npctypes"),
            new GamevalEntry(12429, "DT2_STRANGLED_BASE_T1_1", "Strangled", "npctypes"),
            new GamevalEntry(12430, "DT2_STRANGLED_BASE_T1_2", "Strangled", "npctypes"),
            new GamevalEntry(12431, "DT2_STRANGLED_BASE_T1_3", "Strangled", "npctypes"),
            new GamevalEntry(12432, "DT2_STRANGLED_BASE_T1_4", "Strangled", "npctypes"),
            new GamevalEntry(12433, "DT2_STRANGLED_BASE_T2_1", "Strangled", "npctypes"),
            new GamevalEntry(12434, "DT2_STRANGLED_BASE_T2_2", "Strangled", "npctypes"),
            new GamevalEntry(12435, "DT2_STRANGLED_BASE_T2_3", "Strangled", "npctypes"),
            new GamevalEntry(12436, "LEVIATHAN_TAIL_RING_1_BASE", "Tail", "npctypes"),
            new GamevalEntry(12437, "LEVIATHAN_TAIL_RING_2_BASE", "Tail", "npctypes"),
            new GamevalEntry(12438, "LEVIATHAN_TAIL_RING_3_BASE", "Tail", "npctypes"),
            new GamevalEntry(12439, "DEADMAN_BREACH_DKS_MELEE", "Dagannoth Rex", "npctypes"),
            new GamevalEntry(12440, "DEADMAN_BREACH_KING_BLACK_DRAGON", "King Black Dragon", "npctypes"),
            new GamevalEntry(12441, "DEADMAN_BREACH_DKS_RANGE", "Dagannoth Supreme", "npctypes"),
            new GamevalEntry(12442, "DEADMAN_BREACH_DKS_MAGIC", "Dagannoth Prime", "npctypes"),
            new GamevalEntry(12443, "DEADMAN_BREACH_GODWARS_ARMADYL", "D Kree'arra", "npctypes"),
            new GamevalEntry(12444, "DEADMAN_BREACH_GODWARS_BANDOS", "p General Graardor", "npctypes"),
            new GamevalEntry(12445, "DEADMAN_BREACH_GODWARS_SARADOMIN", "T Commander Zilyana", "npctypes"),
            new GamevalEntry(12446, "DEADMAN_BREACH_GODWARS_ZAMORAK", "K'ril Tsutsaroth", "npctypes"),
            new GamevalEntry(12447, "DEADMAN_BREACH_BARROWS_DHAROK", "Dharok the Wretched", "npctypes"),
            new GamevalEntry(12448, "DEADMAN_BREACH_MA2_ZAMORAK", "Porazdir", "npctypes"),
            new GamevalEntry(12449, "DEADMAN_BREACH_MA2_SARADOMIN", "Justiciar Zachariah", "npctypes"),
            new GamevalEntry(12450, "DEADMAN_BREACH_MA2_GUTHIX", "Derwen", "npctypes"),
            new GamevalEntry(12451, "DEADMAN_BREACH_SUPERIOR_ABYSSAL_DEMON", "Greater abyssal demon", "npctypes"),
            new GamevalEntry(12452, "DEADMAN_BREACH_GIANT_GOBLIN", "Giant goblin", "npctypes"),
            new GamevalEntry(12453, "DEADMAN_BREACH_SUPERIOR_PYREFIEND", "Flaming pyrelord", "npctypes"),
            new GamevalEntry(12454, "DEADMAN_BREACH_SUPERIOR_CAVE_HORROR", "Cave abomination", "npctypes"),
            new GamevalEntry(12455, "DEADMAN_BREACH_INFERNO_MELEE", "Jal-ImKot", "npctypes"),
            new GamevalEntry(12456, "DEADMAN_BREACH_SUPERIOR_INFERNAL_MAGE", "Malevolent Mage", "npctypes"),
            new GamevalEntry(12457, "DEADMAN_BREACH_SUPERIOR_KOUREND_JELLY", "Vitreous warped Jelly", "npctypes"),
            new GamevalEntry(12458, "DEADMAN_BREACH_SULPHUR_LIZARD", "Sulphur Lizard", "npctypes"),
            new GamevalEntry(12459, "DEADMAN_BREACH_SUPERIOR_DARK_BEAST", "Night beast", "npctypes"),
            new GamevalEntry(12460, "DEADMAN_GUARD_WARGUILD_VIS", "Guard", "npctypes"),
            new GamevalEntry(12461, "DEADMAN_GUARD_WARGUILD_RANGE_VIS", "Guard", "npctypes"),
            new GamevalEntry(12462, "DEADMAN_GUARD_WARGUILD", "deadman_guard_warguild", "npctypes"),
            new GamevalEntry(12463, "DEADMAN_GUARD_WARGUILD_RANGE", "deadman_guard_warguild_range", "npctypes"),
            new GamevalEntry(12464, "SUPERIOR_WARPED_TERRORBIRD", "Mutated Terrorbird", "npctypes"),
            new GamevalEntry(12465, "SUPERIOR_WARPED_TORTOISE", "Mutated Tortoise", "npctypes"),
            new GamevalEntry(12466, "POG_GNOME_LONGRAMBLE_VIS", "Longramble", "npctypes"),
            new GamevalEntry(12467, "POG_GAS_JET_TIMER", "pog_gas_jet_timer", "npctypes"),
            new GamevalEntry(12468, "POG_SPIRIT_TREE_WARPED_DUMMY", "Spirit tree", "npctypes"),
            new GamevalEntry(12469, "POG_SPIRIT_TREE_HEALTHY_DUMMY", "Spirit tree", "npctypes"),
            new GamevalEntry(12470, "POG_YEWNOCK", "Yewnock the Engineer", "npctypes"),
            new GamevalEntry(12471, "POG_BOLRIE", "King Bolrie", "npctypes"),
            new GamevalEntry(12472, "POG_BOLRIE_NOKING", "Bolrie", "npctypes"),
            new GamevalEntry(12473, "POG_CUTSCENE_HAZELMERE", "Hazelmere", "npctypes"),
            new GamevalEntry(12474, "POG_ADVISOR", "Advisor", "npctypes"),
            new GamevalEntry(12475, "POG_ARGENTHORG", "Argenthorg", "npctypes"),
            new GamevalEntry(12476, "POG_FLUFFIE_CUTE_1", "Cute Creature", "npctypes"),
            new GamevalEntry(12477, "POG_FLUFFIE_EVIL_1", "Evil Creature", "npctypes"),
            new GamevalEntry(12478, "POG_FLUFFIE_CUTE_CUTSCENE", "Cute Creature", "npctypes"),
            new GamevalEntry(12479, "POG_FLUFFIE_EVIL_CUTSCENE", "Evil Creature", "npctypes"),
            new GamevalEntry(12480, "POG_ENGINEERED_TERROR_BIRD_GUARD_1_VIS", "Terrorbird Guard 21", "npctypes"),
            new GamevalEntry(12481, "POG_ENGINEERED_TERROR_BIRD_GUARD_2_VIS", "Terrorbird Guard 72", "npctypes"),
            new GamevalEntry(12482, "POG_ENGINEERED_TERROR_BIRD_GUARD_1_CUTSCENE", "Terrorbird Guard 21", "npctypes"),
            new GamevalEntry(12483, "POG_ENGINEERED_TERROR_BIRD_GUARD_2_CUTSCENE", "Terrorbird Guard 72", "npctypes"),
            new GamevalEntry(12484, "POG_ENGINEERED_TERROR_BIRD_GUARD_1_CUTSCENE_PANIC", "Terrorbird Guard 21", "npctypes"),
            new GamevalEntry(12485, "POG_ENGINEERED_TERROR_BIRD_GUARD_2_CUTSCENE_PANIC", "Terrorbird Guard 72", "npctypes"),
            new GamevalEntry(12486, "POG_GOLRIE_CRATE_2X2", "Big Monolith", "npctypes"),
            new GamevalEntry(12487, "POG_GOLRIE_CRATE_1X1", "Small Monolith", "npctypes"),
            new GamevalEntry(12488, "POG_GOLRIE_CRATE_2X2_NOOP", "Big Monolith", "npctypes"),
            new GamevalEntry(12489, "POG_GOLRIE_CRATE_1X1_NOOP", "Small Monolith", "npctypes"),
            new GamevalEntry(12490, "POG_MUTATED_TORTOISE", "Warped Tortoise", "npctypes"),
            new GamevalEntry(12491, "POG_MUTATED_TERRORBIRD_1", "Warped Terrorbird", "npctypes"),
            new GamevalEntry(12492, "POG_MUTATED_TERRORBIRD_2", "Warped Terrorbird", "npctypes"),
            new GamevalEntry(12493, "POG_MUTATED_TERRORBIRD_3", "Warped Terrorbird", "npctypes"),
            new GamevalEntry(12494, "POG_MUTATED_TERRORBIRD_4", "Warped Terrorbird", "npctypes"),
            new GamevalEntry(12495, "POG_MUTATED_TERRORBIRD_5", "Warped Terrorbird", "npctypes"),
            new GamevalEntry(12496, "POG_MUTATED_TERRORBIRD_6", "Warped Terrorbird", "npctypes"),
            new GamevalEntry(12497, "POG_MUTATED_TERRORBIRD_7", "Warped Terrorbird", "npctypes"),
            new GamevalEntry(12498, "POG_MUTATED_TERRORBIRD_8", "Warped Terrorbird", "npctypes"),
            new GamevalEntry(12499, "POG_MUTATED_TERRORBIRD_BOSS_1", "Warped Terrorbird", "npctypes"),
            new GamevalEntry(12500, "POG_MUTATED_TERRORBIRD_BOSS_2", "Warped Terrorbird", "npctypes"),
            new GamevalEntry(12501, "POG_MUTATED_TERRORBIRD_BOSS_3", "Warped Terrorbird", "npctypes"),
            new GamevalEntry(12502, "POG_MUTATED_TERRORBIRD_BOSS_1_BACKGROUND_VIS", "Warped Terrorbird", "npctypes"),
            new GamevalEntry(12503, "POG_MUTATED_TERRORBIRD_BOSS_2_BACKGROUND_VIS", "Warped Terrorbird", "npctypes"),
            new GamevalEntry(12504, "POG_MUTATED_TERRORBIRD_BOSS_3_BACKGROUND_VIS", "Warped Terrorbird", "npctypes"),
            new GamevalEntry(12505, "POG_GNOME_LONGRAMBLE", "pog_gnome_longramble", "npctypes"),
            new GamevalEntry(12506, "POG_WATCHER", "pog_watcher", "npctypes"),
            new GamevalEntry(12507, "POG_ENGINEERED_TERROR_BIRD_GUARD_1", "pog_engineered_terror_bird_guard_1", "npctypes"),
            new GamevalEntry(12508, "POG_ENGINEERED_TERROR_BIRD_GUARD_2", "pog_engineered_terror_bird_guard_2", "npctypes"),
            new GamevalEntry(12509, "POG_MUTATED_TERRORBIRD_BOSS_1_BACKGROUND", "pog_mutated_terrorbird_boss_1_background", "npctypes"),
            new GamevalEntry(12510, "POG_MUTATED_TERRORBIRD_BOSS_2_BACKGROUND", "pog_mutated_terrorbird_boss_2_background", "npctypes"),
            new GamevalEntry(12511, "POG_MUTATED_TERRORBIRD_BOSS_3_BACKGROUND", "pog_mutated_terrorbird_boss_3_background", "npctypes"),
            new GamevalEntry(12512, "HAGUS", "Hagus", "npctypes"),
            new GamevalEntry(12513, "HW23_STRAY_DOG", "Spidey dog", "npctypes"),
            new GamevalEntry(12514, "GATHERING_EVENT_BEES_BEEKEEPER", "Bee keeper", "npctypes"),
            new GamevalEntry(12515, "GATHERING_EVENT_BEES_BEEBOX_1", "Unfinished Beehive", "npctypes"),
            new GamevalEntry(12516, "GATHERING_EVENT_BEES_BEEBOX_2", "Unfinished Beehive", "npctypes"),
            new GamevalEntry(12517, "GATHERING_EVENT_BEES_BEEBOX_3", "Complete Beehive", "npctypes"),
            new GamevalEntry(12518, "GATHERING_EVENT_BEES_BEEBOX_4", "Wild Beehive", "npctypes"),
            new GamevalEntry(12519, "GATHERING_EVENT_ENCHANTED_RITUAL_DRYAD", "Dryad", "npctypes"),
            new GamevalEntry(12520, "GATHERING_EVENT_ENCHANTED_RITUAL_A_1", "Ritual circle (green)", "npctypes"),
            new GamevalEntry(12521, "GATHERING_EVENT_ENCHANTED_RITUAL_A_2", "A?&'M?!Z Ritual circle (yellow)", "npctypes"),
            new GamevalEntry(12522, "GATHERING_EVENT_ENCHANTED_RITUAL_A_3", "Ritual circle (blue)", "npctypes"),
            new GamevalEntry(12523, "GATHERING_EVENT_ENCHANTED_RITUAL_A_4", "Ritual circle (red)", "npctypes"),
            new GamevalEntry(12524, "GATHERING_EVENT_ENCHANTED_RITUAL_B_1", "Ritual circle (green)", "npctypes"),
            new GamevalEntry(12525, "GATHERING_EVENT_ENCHANTED_RITUAL_B_2", "A?&'M?!Z Ritual circle (yellow)", "npctypes"),
            new GamevalEntry(12526, "GATHERING_EVENT_ENCHANTED_RITUAL_B_3", "Ritual circle (blue)", "npctypes"),
            new GamevalEntry(12527, "GATHERING_EVENT_ENCHANTED_RITUAL_B_4", "Ritual circle (red)", "npctypes"),
            new GamevalEntry(12528, "GATHERING_EVENT_ENCHANTED_RITUAL_C_1", "Ritual circle (green)", "npctypes"),
            new GamevalEntry(12529, "GATHERING_EVENT_ENCHANTED_RITUAL_C_2", "A?&'M?!Z Ritual circle (yellow)", "npctypes"),
            new GamevalEntry(12530, "GATHERING_EVENT_ENCHANTED_RITUAL_C_3", "Ritual circle (blue)", "npctypes"),
            new GamevalEntry(12531, "GATHERING_EVENT_ENCHANTED_RITUAL_C_4", "Ritual circle (red)", "npctypes"),
            new GamevalEntry(12532, "GATHERING_EVENT_ENCHANTED_RITUAL_D_1", "Ritual circle (green)", "npctypes"),
            new GamevalEntry(12533, "GATHERING_EVENT_ENCHANTED_RITUAL_D_2", "A?&'M?!Z Ritual circle (yellow)", "npctypes"),
            new GamevalEntry(12534, "GATHERING_EVENT_ENCHANTED_RITUAL_D_3", "Ritual circle (blue)", "npctypes"),
            new GamevalEntry(12535, "GATHERING_EVENT_ENCHANTED_RITUAL_D_4", "Ritual circle (red)", "npctypes"),
            new GamevalEntry(12536, "GATHERING_EVENT_PHEASANT_FORESTER", "Freaky Forester", "npctypes"),
            new GamevalEntry(12537, "GATHERING_EVENT_PHEASANT", "Pheasant", "npctypes"),
            new GamevalEntry(12538, "LEAGUE_SUPERIOR_CRAWLING_HAND", "Bloodthirsty hand", "npctypes"),
            new GamevalEntry(12539, "LEAGUE_SUPERIOR_CAVE_CRAWLER", "Bloodthirsty Crawler", "npctypes"),
            new GamevalEntry(12540, "LEAGUE_SUPERIOR_BANSHEE", "Bloodthirsty banshee", "npctypes"),
            new GamevalEntry(12541, "GATHERING_EVENT_POACHERS_TRAP", "Fox trap", "npctypes"),
            new GamevalEntry(12542, "LEAGUE_SUPERIOR_KOUREND_BANSHEE", "Bloodthirsty twisted banshee", "npctypes"),
            new GamevalEntry(12543, "GATHERING_EVENT_ENTLINGS_NPC_01", "Entling", "npctypes"),
            new GamevalEntry(12544, "GATHERING_EVENT_ENTLINGS_NPC_01_PRUNED", "Pruned Entling", "npctypes"),
            new GamevalEntry(12545, "GATHERING_EVENT_ENT_STUMP_01", "Friendly Ent", "npctypes"),
            new GamevalEntry(12546, "GATHERING_EVENT_ENT_STUMP_02", "Friendly Ent", "npctypes"),
            new GamevalEntry(12547, "POH_SKILLPET_WC_PHEASANT", "Pheasant", "npctypes"),
            new GamevalEntry(12548, "POH_SKILLPET_WC_FOX", "? Fox", "npctypes"),
            new GamevalEntry(12549, "SKILLPET_WC_PHEASANT", "Pheasant", "npctypes"),
            new GamevalEntry(12550, "SKILLPET_WC_FOX", "Fox", "npctypes"),
            new GamevalEntry(12551, "MACRO_COUNTCHECK_SURFACE", "Count Check", "npctypes"),
            new GamevalEntry(12552, "MACRO_COUNTCHECK_UNDERWATER", "Count Check", "npctypes"),
            new GamevalEntry(12553, "GATHERING_EVENT_POACHERS_POACHER01_OUTDOORS", "Poacher", "npctypes"),
            new GamevalEntry(12554, "GATHERING_EVENT_POACHERS_POACHER02_OUTDOORS", "Poacher", "npctypes"),
            new GamevalEntry(12555, "GATHERING_EVENT_POACHERS_POACHER03_OUTDOORS", "Poacher", "npctypes"),
            new GamevalEntry(12556, "GATHERING_EVENT_POACHERS_POACHER01_INDOORS", "Poacher", "npctypes"),
            new GamevalEntry(12557, "GATHERING_EVENT_POACHERS_POACHER02_INDOORS", "Poacher", "npctypes"),
            new GamevalEntry(12558, "GATHERING_EVENT_POACHERS_POACHER03_INDOORS", "Poacher", "npctypes"),
            new GamevalEntry(12559, "GATHERING_EVENT_POACHERS_FOX_OUTDOORS", "Frightened Fox", "npctypes"),
            new GamevalEntry(12560, "GATHERING_EVENT_POACHERS_FOX_INDOORS", "Frightened Fox", "npctypes"),
            new GamevalEntry(12561, "LEAGUE_SUPERIOR_ROCKSLUG", "Bloodthirst rockslug", "npctypes"),
            new GamevalEntry(12562, "LEAGUE_SUPERIOR_COCKATRICE", "Bloodthirsty Cockathrice", "npctypes"),
            new GamevalEntry(12563, "LEAGUE_SUPERIOR_PYREFIEND", "Bloodthirsty pyrelord", "npctypes"),
            new GamevalEntry(12564, "LEAGUE_SUPERIOR_PYRELORD", "Bloodthirsty Infernal pyrelord", "npctypes"),
            new GamevalEntry(12565, "LEAGUE_SUPERIOR_BASILISK", "Bloodthirsty basilisk", "npctypes"),
            new GamevalEntry(12566, "LEAGUE_SUPERIOR_BASILISK_KNIGHT", "Bloodthirsty Basilisk Sentinel", "npctypes"),
            new GamevalEntry(12567, "LEAGUE_SUPERIOR_INFERNAL_MAGE", "Bloodthirsty Mage", "npctypes"),
            new GamevalEntry(12568, "LEAGUE_SUPERIOR_BLOODVELD", "Bloodthirsty Bloodveld", "npctypes"),
            new GamevalEntry(12569, "LEAGUE_SUPERIOR_KOUREND_BLOODVELD", "Bloodthirsty mutated Bloodveld", "npctypes"),
            new GamevalEntry(12570, "LEAGUE_SUPERIOR_JELLY", "Bloodthirsty Jelly", "npctypes"),
            new GamevalEntry(12571, "LEAGUE_SUPERIOR_KOUREND_JELLY", "Bloodthirsty Warped Jelly", "npctypes"),
            new GamevalEntry(12572, "LEAGUE_SUPERIOR_CAVE_HORROR", "Bloodthirsty abomination", "npctypes"),
            new GamevalEntry(12573, "LEAGUE_SUPERIOR_ABBERANT_SPECTRE", "Bloodthirsty spectre", "npctypes"),
            new GamevalEntry(12574, "LEAGUE_SUPERIOR_KOUREND_SPECTRE", "Bloodthirsty Repugnant spectre", "npctypes"),
            new GamevalEntry(12575, "LEAGUE_SUPERIOR_DUSTDEVIL", "Bloodthirsty choke devil", "npctypes"),
            new GamevalEntry(12576, "LEAGUE_SUPERIOR_KURASK", "Bloodthirsty kurask", "npctypes"),
            new GamevalEntry(12577, "LEAGUE_SUPERIOR_SMOKE_DEVIL", "Bloodthirsty smoke devil", "npctypes"),
            new GamevalEntry(12578, "LEAGUE_SUPERIOR_GARGOYLE", "Bloodthirsty gargoyle", "npctypes"),
            new GamevalEntry(12579, "LEAGUE_SUPERIOR_GARGOYLE_DEAD", "Bloodthirsty gargoyle", "npctypes"),
            new GamevalEntry(12580, "LEAGUE_SUPERIOR_DARK_BEAST", "&J K", "npctypes"),
            new GamevalEntry(12581, "LEAGUE_SUPERIOR_ABYSSAL_DEMON", "Bloodthirsty abyssal demon", "npctypes"),
            new GamevalEntry(12582, "LEAGUE_SUPERIOR_NECHRYAEL", "Bloodthirsty Nechryarch", "npctypes"),
            new GamevalEntry(12583, "LEAGUE_SUPERIOR_TUROTH", "Bloodthirsty Turoth", "npctypes"),
            new GamevalEntry(12584, "LEAGUE_SUPERIOR_WYRM_DARK", "Bloodthirsty Shadow Wyrm", "npctypes"),
            new GamevalEntry(12585, "LEAGUE_SUPERIOR_WYRM_LIGHT", "Bloodthirsty Shadow Wyrm", "npctypes"),
            new GamevalEntry(12586, "LEAGUE_SUPERIOR_DRAKE", "Bloodthirsty Drake", "npctypes"),
            new GamevalEntry(12587, "LEAGUE_SUPERIOR_DRAKE_DEATH", "Bloodthirsty Drake", "npctypes"),
            new GamevalEntry(12588, "LEAGUE_SUPERIOR_HYDRA", "Bloodthirsty Hydra", "npctypes"),
            new GamevalEntry(12589, "LEAGUE_GUARDIAN", "league_guardian", "npctypes"),
            new GamevalEntry(12590, "MUSPAH_TRANSMOG", "Muspah", "npctypes"),
            new GamevalEntry(12591, "LEVIATHAN_TRANSMOG", "The Leviathan", "npctypes"),
            new GamevalEntry(12592, "POH_RTELDRIC_PET", "Ric", "npctypes"),
            new GamevalEntry(12593, "RTBRANDA_PET", "Bran", "npctypes"),
            new GamevalEntry(12594, "INFERNO_CREATURE_MELEE_SMALL", "Jal-ImKot", "npctypes"),
            new GamevalEntry(12595, "RTELDRIC_PET", "Ric", "npctypes"),
            new GamevalEntry(12596, "RT_FIRE_QUEEN", "Branda the Fire Queen", "npctypes"),
            new GamevalEntry(12597, "GOOSE_TRANSMOG", "Goose", "npctypes"),
            new GamevalEntry(12598, "ANTI_SANTA_TRANSMOG", "Anti-Santa", "npctypes"),
            new GamevalEntry(12599, "KEEPER_OF_KEYS", "Key Master", "npctypes"),
            new GamevalEntry(12600, "GUSS_MISTLETOAD_TRANSMOG", "Guss Mistletoad", "npctypes"),
            new GamevalEntry(12601, "SANTAS_SCRIBE_TRANSMOG", "Santa's scribe", "npctypes"),
            new GamevalEntry(12602, "SANTA_TRANSMOG", "Santa Claus", "npctypes"),
            new GamevalEntry(12603, "BARBARIAN_BARTENDER_TRANSMOG", "Barbarian bartender", "npctypes"),
            new GamevalEntry(12604, "XMAS_WAITRESS_TRANSMOG", "Waitress", "npctypes"),
            new GamevalEntry(12605, "XMAS22_GOOSE", "Goose", "npctypes"),
            new GamevalEntry(12606, "RAT_BOSS_BIOLOGIST", "rat_boss_biologist", "npctypes"),
            new GamevalEntry(12607, "LAVA_DRAGON2", "Lava dragon", "npctypes"),
            new GamevalEntry(12608, "LAVA_DRAGON3", "Lava dragon", "npctypes"),
            new GamevalEntry(12609, "HALLOWED_GRAPPLE_HELPER_F2", "hallowed_grapple_helper_f2", "npctypes"),
            new GamevalEntry(12610, "ELIAS_WHITE_VIS", "Elias White", "npctypes"),
            new GamevalEntry(12611, "ELIAS_WHITE_CUTSCENE", "Elias White", "npctypes"),
            new GamevalEntry(12612, "DOV_ARRAV_CUTSCENE", "Arrav", "npctypes"),
            new GamevalEntry(12613, "DOV_ARRAV_COMBAT", "Arrav", "npctypes"),
            new GamevalEntry(12614, "DOV_ZEMOUREGAL_CUTSCENE", "Zemouregal", "npctypes"),
            new GamevalEntry(12615, "DOV_ZEMOUREGAL_CUTSCENE_3", "Zemouregal", "npctypes"),
            new GamevalEntry(12616, "DOV_ZEMOUREGAL_CUTSCENE_3_INACTIVE", "dov_zemouregal_cutscene_3_inactive", "npctypes"),
            new GamevalEntry(12617, "DOV_SHARATHTEERK_CUTSCENE", "Sharathteerk", "npctypes"),
            new GamevalEntry(12618, "DOV_CHAOSMONK", "Monk of Zamorak", "npctypes"),
            new GamevalEntry(12619, "DOV_CHAOSMONK_CUTSCENE", "Monk of Zamorak", "npctypes"),
            new GamevalEntry(12620, "DOV_AEONISIG", "Aeonisig Raispher", "npctypes"),
            new GamevalEntry(12621, "DOV_ROALD", "King Roald", "npctypes"),
            new GamevalEntry(12622, "DOV_PRYSIN", "Sir Prysin", "npctypes"),
            new GamevalEntry(12623, "DOV_FERRNOOK", "Ambassador Ferrnook", "npctypes"),
            new GamevalEntry(12624, "DOV_ELLAMARIA", "Queen Ellamaria", "npctypes"),
            new GamevalEntry(12625, "DOV_ELLAMARIA_CUTSCENE", "Queen Ellamaria", "npctypes"),
            new GamevalEntry(12626, "DOV_RELDO", "Reldo", "npctypes"),
            new GamevalEntry(12627, "DOV_ROVIN", "Captain Rovin", "npctypes"),
            new GamevalEntry(12628, "DOV_TREZNOR", "Treznor", "npctypes"),
            new GamevalEntry(12629, "DOV_DIMINTHEIS_CUTSCENE", "Dimintheis", "npctypes"),
            new GamevalEntry(12630, "SAILING_TRANSPORT_TRADER_STAN_PISCARILIUS", "Trader Stan", "npctypes"),
            new GamevalEntry(12631, "SAILING_TRANSPORT_TRADER_STAN_LANDSEND", "Trader Stan", "npctypes"),
            new GamevalEntry(12632, "SAILING_TRANSPORT_TRADER_STAN_CREW_MAN1_PISCARILIUS", "Trader Crewmember", "npctypes"),
            new GamevalEntry(12633, "SAILING_TRANSPORT_TRADER_STAN_CREW_MAN1_LANDSEND", "Trader Crewmember", "npctypes"),
            new GamevalEntry(12634, "SAILING_TRANSPORT_TRADER_STAN_CREW_MAN2_PISCARILIUS", "Trader Crewmember", "npctypes"),
            new GamevalEntry(12635, "SAILING_TRANSPORT_TRADER_STAN_CREW_MAN2_LANDSEND", "Trader Crewmember", "npctypes"),
            new GamevalEntry(12636, "SAILING_TRANSPORT_TRADER_STAN_CREW_MAN3_PISCARILIUS", "Trader Crewmember", "npctypes"),
            new GamevalEntry(12637, "SAILING_TRANSPORT_TRADER_STAN_CREW_MAN3_LANDSEND", "Trader Crewmember", "npctypes"),
            new GamevalEntry(12638, "SAILING_TRANSPORT_TRADER_STAN_CREW_WOMAN1_PISCARILIUS", "Trader Crewmember", "npctypes"),
            new GamevalEntry(12639, "SAILING_TRANSPORT_TRADER_STAN_CREW_WOMAN1_LANDSEND", "Trader Crewmember", "npctypes"),
            new GamevalEntry(12640, "SAILING_TRANSPORT_TRADER_STAN_CREW_WOMAN2_PISCARILIUS", "Trader Crewmember", "npctypes"),
            new GamevalEntry(12641, "SAILING_TRANSPORT_TRADER_STAN_CREW_WOMAN2_LANDSEND", "Trader Crewmember", "npctypes"),
            new GamevalEntry(12642, "SAILING_TRANSPORT_TRADER_STAN_CREW_WOMAN3_PISCARILIUS", "Trader Crewmember", "npctypes"),
            new GamevalEntry(12643, "SAILING_TRANSPORT_TRADER_STAN_CREW_WOMAN3_LANDSEND", "Trader Crewmember", "npctypes"),
            new GamevalEntry(12644, "VMQ1_ALINA_VIS", "Alina", "npctypes"),
            new GamevalEntry(12645, "VMQ1_ALINA_CUTSCENE", "Alina", "npctypes"),
            new GamevalEntry(12646, "VMQ1_NOAH_VIS", "Noah", "npctypes"),
            new GamevalEntry(12647, "VMQ1_NOAH_CUTSCENE", "Noah", "npctypes"),
            new GamevalEntry(12648, "VMQ1_GUARD_SERGEANT_VIS", "Sergeant Tobyn", "npctypes"),
            new GamevalEntry(12649, "VMQ1_GUARD_SERGEANT_CUTSCENE", "Sergeant Tobyn", "npctypes"),
            new GamevalEntry(12650, "VMQ1_ITZLA_VIS", "Prince Itzla Arkan", "npctypes"),
            new GamevalEntry(12651, "VMQ1_ITZLA_CUTSCENE", "Prince Itzla Arkan", "npctypes"),
            new GamevalEntry(12652, "VMQ1_SERVIUS_CUTSCENE", "Servius, Teokan of Ralos", "npctypes"),
            new GamevalEntry(12653, "VMQ1_FURIA_CUTSCENE", "Furia Tullus", "npctypes"),
            new GamevalEntry(12654, "VMQ1_ENNIUS_CUTSCENE", "Ennius Tullus", "npctypes"),
            new GamevalEntry(12655, "VMQ1_KNIGHT_1", "Knight of Varlamore", "npctypes"),
            new GamevalEntry(12656, "VMQ1_KNIGHT_2", "Knight of Varlamore", "npctypes"),
            new GamevalEntry(12657, "VMQ1_KNIGHT_3", "Knight of Varlamore", "npctypes"),
            new GamevalEntry(12658, "VMQ1_KNIGHT_4", "Knight of Varlamore", "npctypes"),
            new GamevalEntry(12659, "VMQ1_KNIGHT_5", "Knight of Varlamore", "npctypes"),
            new GamevalEntry(12660, "VMQ1_KNIGHT_6", "Knight of Varlamore", "npctypes"),
            new GamevalEntry(12661, "VMQ1_BAG_GUARD", "Guard", "npctypes"),
            new GamevalEntry(12662, "VMQ1_BAG_GUARD_VIS", "Guard", "npctypes"),
            new GamevalEntry(12663, "VMQ1_BANDIT_1_VIS", "Bandit", "npctypes"),
            new GamevalEntry(12664, "VMQ1_BANDIT_2_VIS", "Bandit", "npctypes"),
            new GamevalEntry(12665, "VMQ1_BANDIT_3_VIS", "Bandit", "npctypes"),
            new GamevalEntry(12666, "VMQ1_BANDIT_4_VIS", "Bandit", "npctypes"),
            new GamevalEntry(12667, "VMQ1_BANDIT_4_CUTSCENE", "Bandit", "npctypes"),
            new GamevalEntry(12668, "VMQ1_GUARD_1_UNMARKED", "Guard", "npctypes"),
            new GamevalEntry(12669, "VMQ1_GUARD_1_MARKED", "Guard", "npctypes"),
            new GamevalEntry(12670, "VMQ1_GUARD_1_NOOP", "Guard", "npctypes"),
            new GamevalEntry(12671, "VMQ1_GUARD_2_UNMARKED", "Guard", "npctypes"),
            new GamevalEntry(12672, "VMQ1_GUARD_2_MARKED", "Guard", "npctypes"),
            new GamevalEntry(12673, "VMQ1_GUARD_2_NOOP", "Guard", "npctypes"),
            new GamevalEntry(12674, "VMQ1_GUARD_3_UNMARKED", "Guard", "npctypes"),
            new GamevalEntry(12675, "VMQ1_GUARD_3_MARKED", "Guard", "npctypes"),
            new GamevalEntry(12676, "VMQ1_GUARD_3_NOOP", "Guard", "npctypes"),
            new GamevalEntry(12677, "VMQ1_GUARD_4_UNMARKED", "Guard", "npctypes"),
            new GamevalEntry(12678, "VMQ1_GUARD_4_MARKED", "Guard", "npctypes"),
            new GamevalEntry(12679, "VMQ1_GUARD_4_NOOP", "Guard", "npctypes"),
            new GamevalEntry(12680, "VMQ1_GUARD_5_UNMARKED", "Guard", "npctypes"),
            new GamevalEntry(12681, "VMQ1_GUARD_5_MARKED", "Guard", "npctypes"),
            new GamevalEntry(12682, "VMQ1_GUARD_5_NOOP", "Guard", "npctypes"),
            new GamevalEntry(12683, "VMQ1_GUARD_6_UNMARKED", "Guard", "npctypes"),
            new GamevalEntry(12684, "VMQ1_GUARD_6_MARKED", "Guard", "npctypes"),
            new GamevalEntry(12685, "VMQ1_GUARD_6_NOOP", "Guard", "npctypes"),
            new GamevalEntry(12686, "VMQ1_GUARD_7_UNMARKED", "Guard", "npctypes"),
            new GamevalEntry(12687, "VMQ1_GUARD_7_MARKED", "Guard", "npctypes"),
            new GamevalEntry(12688, "VMQ1_GUARD_7_NOOP", "Guard", "npctypes"),
            new GamevalEntry(12689, "VMQ1_GUARD_8_UNMARKED", "Guard", "npctypes"),
            new GamevalEntry(12690, "VMQ1_GUARD_8_MARKED", "Guard", "npctypes"),
            new GamevalEntry(12691, "VMQ1_GUARD_8_NOOP", "Guard", "npctypes"),
            new GamevalEntry(12692, "VMQ1_GUARD_9_UNMARKED", "Guard", "npctypes"),
            new GamevalEntry(12693, "VMQ1_GUARD_9_MARKED", "Guard", "npctypes"),
            new GamevalEntry(12694, "VMQ1_GUARD_9_NOOP", "Guard", "npctypes"),
            new GamevalEntry(12695, "VMQ1_GUARD_10_UNMARKED", "Guard", "npctypes"),
            new GamevalEntry(12696, "VMQ1_GUARD_10_MARKED", "Guard", "npctypes"),
            new GamevalEntry(12697, "VMQ1_GUARD_10_NOOP", "Guard", "npctypes"),
            new GamevalEntry(12698, "VMQ1_KING_ROALD_CUTSCENE", "King Roald", "npctypes"),
            new GamevalEntry(12699, "VMQ1_AEONISIG_RAISPHER_CUTSCENE", "Aeonisig Raispher", "npctypes"),
            new GamevalEntry(12700, "KOUREND_STATUE_ARCHITECT", "Hosa", "npctypes"),
            new GamevalEntry(12701, "LOVAKENGJ_ARCHITECT", "Lovada", "npctypes"),
            new GamevalEntry(12702, "LOVAKENGJ_MINECART_FARMING_GUILD", "Ferain", "npctypes"),
            new GamevalEntry(12703, "LOVAKENGJ_MINECART_TITHE_FARM", "Elnes", "npctypes"),
            new GamevalEntry(12704, "LOVAKENGJ_MINECART_KINGSTOWN", "Hordal", "npctypes"),
            new GamevalEntry(12705, "LOVAKENGJ_MINECART_KOUREND_WOODLAND", "Buneir", "npctypes"),
            new GamevalEntry(12706, "LOVAKENGJ_MINECART_NORTHERN_TUNDRAS", "Lassin", "npctypes"),
            new GamevalEntry(12707, "LOVAKENGJ_MINECART_SHAYZIEN_WALL", "Hatna", "npctypes"),
            new GamevalEntry(12708, "LOVAKENGJ_CITIZEN_1", "Dwarf", "npctypes"),
            new GamevalEntry(12709, "LOVAKENGJ_CITIZEN_2", "Dwarf", "npctypes"),
            new GamevalEntry(12710, "LOVAKENGJ_CITIZEN_3", "Dwarf", "npctypes"),
            new GamevalEntry(12711, "LOVAKENGJ_CITIZEN_4", "Dwarf", "npctypes"),
            new GamevalEntry(12712, "LOVAKENGJ_CITIZEN_5", "Dwarf", "npctypes"),
            new GamevalEntry(12713, "DOV_VARROCK_GUARD_M_1", "Guard", "npctypes"),
            new GamevalEntry(12714, "DOV_VARROCK_GUARD_M_2", "Guard", "npctypes"),
            new GamevalEntry(12715, "DOV_VARROCK_GUARD_M_3", "Guard", "npctypes"),
            new GamevalEntry(12716, "DOV_VARROCK_GUARD_F_1", "Guard", "npctypes"),
            new GamevalEntry(12717, "DOV_VARROCK_GUARD_F_2", "Guard", "npctypes"),
            new GamevalEntry(12718, "DOV_VARROCK_GUARD_F_3", "Guard", "npctypes"),
            new GamevalEntry(12719, "DOV_VARROCK_GUARD_CAPTAIN", "Guard", "npctypes"),
            new GamevalEntry(12720, "DOV_ARMOURED_ZOMBIE_MELEE_1", "Armoured zombie", "npctypes"),
            new GamevalEntry(12721, "DOV_ARMOURED_ZOMBIE_MELEE_2", "Armoured zombie", "npctypes"),
            new GamevalEntry(12722, "DOV_ARMOURED_ZOMBIE_MELEE_3", "Armoured zombie", "npctypes"),
            new GamevalEntry(12723, "DOV_ARMOURED_ZOMBIE_MELEE_4", "Armoured zombie", "npctypes"),
            new GamevalEntry(12724, "DOV_ARMOURED_ZOMBIE_MELEE_5", "Armoured zombie", "npctypes"),
            new GamevalEntry(12725, "DOV_ARMOURED_ZOMBIE_RANGED_1", "Armoured zombie", "npctypes"),
            new GamevalEntry(12726, "DOV_ARMOURED_ZOMBIE_RANGED_2", "Armoured zombie", "npctypes"),
            new GamevalEntry(12727, "DOV_ARMOURED_ZOMBIE_RANGED_3", "Armoured zombie", "npctypes"),
            new GamevalEntry(12728, "DOV_ARMOURED_ZOMBIE_RANGED_4", "Armoured zombie", "npctypes"),
            new GamevalEntry(12729, "DOV_ARMOURED_ZOMBIE_RANGED_5", "Armoured zombie", "npctypes"),
            new GamevalEntry(12730, "DOV_ARMOURED_ZOMBIE_VARROCK_MELEE_1", "Armoured zombie", "npctypes"),
            new GamevalEntry(12731, "DOV_ARMOURED_ZOMBIE_VARROCK_MELEE_2", "Armoured zombie", "npctypes"),
            new GamevalEntry(12732, "DOV_ARMOURED_ZOMBIE_VARROCK_MELEE_3", "Armoured zombie", "npctypes"),
            new GamevalEntry(12733, "DOV_ARMOURED_ZOMBIE_VARROCK_MELEE_4", "Armoured zombie", "npctypes"),
            new GamevalEntry(12734, "DOV_ARMOURED_ZOMBIE_VARROCK_MELEE_5", "Armoured zombie", "npctypes"),
            new GamevalEntry(12735, "DOV_ARMOURED_ZOMBIE_VARROCK_RANGED_1", "Armoured zombie", "npctypes"),
            new GamevalEntry(12736, "DOV_ARMOURED_ZOMBIE_VARROCK_RANGED_2", "Armoured zombie", "npctypes"),
            new GamevalEntry(12737, "DOV_ARMOURED_ZOMBIE_VARROCK_RANGED_3", "Armoured zombie", "npctypes"),
            new GamevalEntry(12738, "DOV_ARMOURED_ZOMBIE_VARROCK_RANGED_4", "Armoured zombie", "npctypes"),
            new GamevalEntry(12739, "DOV_ARMOURED_ZOMBIE_VARROCK_RANGED_5", "Armoured zombie", "npctypes"),
            new GamevalEntry(12740, "DOV_ARMOURED_ZOMBIE_INACTIVE_MELEE_1", "Armoured zombie", "npctypes"),
            new GamevalEntry(12741, "DOV_ARMOURED_ZOMBIE_INACTIVE_MELEE_2", "Armoured zombie", "npctypes"),
            new GamevalEntry(12742, "DOV_ARMOURED_ZOMBIE_INACTIVE_MELEE_3", "Armoured zombie", "npctypes"),
            new GamevalEntry(12743, "DOV_ARMOURED_ZOMBIE_INACTIVE_MELEE_4", "Armoured zombie", "npctypes"),
            new GamevalEntry(12744, "DOV_ARMOURED_ZOMBIE_INACTIVE_MELEE_5", "Armoured zombie", "npctypes"),
            new GamevalEntry(12745, "DOV_ARMOURED_ZOMBIE_INACTIVE_RANGED_1", "Armoured zombie", "npctypes"),
            new GamevalEntry(12746, "DOV_ARMOURED_ZOMBIE_INACTIVE_RANGED_2", "Armoured zombie", "npctypes"),
            new GamevalEntry(12747, "DOV_ARMOURED_ZOMBIE_INACTIVE_RANGED_3", "Armoured zombie", "npctypes"),
            new GamevalEntry(12748, "DOV_ARMOURED_ZOMBIE_INACTIVE_RANGED_4", "Armoured zombie", "npctypes"),
            new GamevalEntry(12749, "DOV_ARMOURED_ZOMBIE_INACTIVE_RANGED_5", "Armoured zombie", "npctypes"),
            new GamevalEntry(12750, "ELIAS_WHITE_BASE", "elias_white_base", "npctypes"),
            new GamevalEntry(12751, "ELIAS_WHITE_PALACE_DOWNSTAIRS", "elias_white_palace_downstairs", "npctypes"),
            new GamevalEntry(12752, "ELIAS_WHITE_PALACE_UPSTAIRS", "elias_white_palace_upstairs", "npctypes"),
            new GamevalEntry(12753, "ELIAS_WHITE_PALACE_ATTACKED", "elias_white_palace_attacked", "npctypes"),
            new GamevalEntry(12754, "DOV_ELIAS_WHITE_FOLLOWER", "dov_elias_white_follower", "npctypes"),
            new GamevalEntry(12755, "DOV_ARMOURED_ZOMBIE_VARROCK_MELEE_1_HUNTPLAYER", "Armoured zombie", "npctypes"),
            new GamevalEntry(12756, "DOV_ARMOURED_ZOMBIE_VARROCK_MELEE_2_HUNTPLAYER", "Armoured zombie", "npctypes"),
            new GamevalEntry(12757, "DOV_ARMOURED_ZOMBIE_VARROCK_MELEE_3_HUNTPLAYER", "Armoured zombie", "npctypes"),
            new GamevalEntry(12758, "DOV_ARMOURED_ZOMBIE_VARROCK_MELEE_4_HUNTPLAYER", "Armoured zombie", "npctypes"),
            new GamevalEntry(12759, "DOV_ARMOURED_ZOMBIE_VARROCK_MELEE_5_HUNTPLAYER", "Armoured zombie", "npctypes"),
            new GamevalEntry(12760, "DOV_ARMOURED_ZOMBIE_VARROCK_RANGED_1_HUNTPLAYER", "Armoured zombie", "npctypes"),
            new GamevalEntry(12761, "DOV_ARMOURED_ZOMBIE_VARROCK_RANGED_2_HUNTPLAYER", "Armoured zombie", "npctypes"),
            new GamevalEntry(12762, "DOV_ARMOURED_ZOMBIE_VARROCK_RANGED_3_HUNTPLAYER", "Armoured zombie", "npctypes"),
            new GamevalEntry(12763, "DOV_ARMOURED_ZOMBIE_VARROCK_RANGED_4_HUNTPLAYER", "Armoured zombie", "npctypes"),
            new GamevalEntry(12764, "DOV_ARMOURED_ZOMBIE_VARROCK_RANGED_5_HUNTPLAYER", "Armoured zombie", "npctypes"),
            new GamevalEntry(12765, "FARMING_TOOLS_LEPRECHAUN_VARLAMORE", "Tool Leprechaun", "npctypes"),
            new GamevalEntry(12766, "FORTIS_GARDENER", "Harminia", "npctypes"),
            new GamevalEntry(12767, "POH_SOLHEREDIT_PET", "?d e Smol Heredit", "npctypes"),
            new GamevalEntry(12768, "POH_QUETZAL_PET", "Quetzin", "npctypes"),
            new GamevalEntry(12769, "SALAMANDER_MOUNTAIN", "Tecu salamander", "npctypes"),
            new GamevalEntry(12770, "MOTH_SUNLIGHT", "Sunlight Moth", "npctypes"),
            new GamevalEntry(12771, "MOTH_MOONLIGHT", "Moonlight moth", "npctypes"),
            new GamevalEntry(12772, "MOTH_MOONLIGHT_LOW_WANDER", "Moonlight moth", "npctypes"),
            new GamevalEntry(12773, "MOTH_MOONLIGHT_NOCLICK", "Moonlight moth", "npctypes"),
            new GamevalEntry(12774, "_0_24_49_FRESHFISH", "Rod Fishing spot", "npctypes"),
            new GamevalEntry(12775, "_0_24_46_MEMBERFISH", "Fishing spot", "npctypes"),
            new GamevalEntry(12776, "_0_27_46_MEMBERFISH", "Fishing spot", "npctypes"),
            new GamevalEntry(12777, "_0_24_46_RAREFISH", "Fishing spot", "npctypes"),
            new GamevalEntry(12778, "_0_27_46_SALTFISH", "Fishing spot", "npctypes"),
            new GamevalEntry(12779, "SAILING_TRANSPORT_TRADER_STAN_FORTIS", "Trader Stan", "npctypes"),
            new GamevalEntry(12780, "SAILING_TRANSPORT_TRADER_STAN_ALDARIN", "Trader Stan", "npctypes"),
            new GamevalEntry(12781, "SAILING_TRANSPORT_TRADER_STAN_SUNSETCOAST", "Trader Stan", "npctypes"),
            new GamevalEntry(12782, "SAILING_TRANSPORT_TRADER_STAN_TEMPESTUS", "Trader Stan", "npctypes"),
            new GamevalEntry(12783, "SAILING_TRANSPORT_TRADER_STAN_CREW_MAN1_FORTIS", "Trader Crewmember", "npctypes"),
            new GamevalEntry(12784, "SAILING_TRANSPORT_TRADER_STAN_CREW_MAN1_ALDARIN", "Trader Crewmember", "npctypes"),
            new GamevalEntry(12785, "SAILING_TRANSPORT_TRADER_STAN_CREW_MAN1_SUNSETCOAST", "Trader Crewmember", "npctypes"),
            new GamevalEntry(12786, "SAILING_TRANSPORT_TRADER_STAN_CREW_MAN1_TEMPESTUS", "Trader Crewmember", "npctypes"),
            new GamevalEntry(12787, "SAILING_TRANSPORT_TRADER_STAN_CREW_MAN2_FORTIS", "Trader Crewmember", "npctypes"),
            new GamevalEntry(12788, "SAILING_TRANSPORT_TRADER_STAN_CREW_MAN2_ALDARIN", "Trader Crewmember", "npctypes"),
            new GamevalEntry(12789, "SAILING_TRANSPORT_TRADER_STAN_CREW_MAN2_SUNSETCOAST", "Trader Crewmember", "npctypes"),
            new GamevalEntry(12790, "SAILING_TRANSPORT_TRADER_STAN_CREW_MAN2_TEMPESTUS", "Trader Crewmember", "npctypes"),
            new GamevalEntry(12791, "SAILING_TRANSPORT_TRADER_STAN_CREW_MAN3_FORTIS", "Trader Crewmember", "npctypes"),
            new GamevalEntry(12792, "SAILING_TRANSPORT_TRADER_STAN_CREW_MAN3_ALDARIN", "Trader Crewmember", "npctypes"),
            new GamevalEntry(12793, "SAILING_TRANSPORT_TRADER_STAN_CREW_MAN3_SUNSETCOAST", "Trader Crewmember", "npctypes"),
            new GamevalEntry(12794, "SAILING_TRANSPORT_TRADER_STAN_CREW_MAN3_TEMPESTUS", "Trader Crewmember", "npctypes"),
            new GamevalEntry(12795, "SAILING_TRANSPORT_TRADER_STAN_CREW_WOMAN1_FORTIS", "Trader Crewmember", "npctypes"),
            new GamevalEntry(12796, "SAILING_TRANSPORT_TRADER_STAN_CREW_WOMAN1_ALDARIN", "Trader Crewmember", "npctypes"),
            new GamevalEntry(12797, "SAILING_TRANSPORT_TRADER_STAN_CREW_WOMAN1_SUNSETCOAST", "Trader Crewmember", "npctypes"),
            new GamevalEntry(12798, "SAILING_TRANSPORT_TRADER_STAN_CREW_WOMAN1_TEMPESTUS", "Trader Crewmember", "npctypes"),
            new GamevalEntry(12799, "SAILING_TRANSPORT_TRADER_STAN_CREW_WOMAN2_FORTIS", "Trader Crewmember", "npctypes"),
            new GamevalEntry(12800, "SAILING_TRANSPORT_TRADER_STAN_CREW_WOMAN2_ALDARIN", "Trader Crewmember", "npctypes"),
            new GamevalEntry(12801, "SAILING_TRANSPORT_TRADER_STAN_CREW_WOMAN2_SUNSETCOAST", "Trader Crewmember", "npctypes"),
        };
    }

    static Optional<GamevalEntry> byId(int id) {
        for (GamevalEntry entry : entries()) {
            if (entry.id() == id) return Optional.of(entry);
        }
        return Optional.empty();
    }

}
