package net.titan.gamevals.internal;

import java.util.Optional;

import net.titan.gamevals.GamevalEntry;
import net.titan.gamevals.QuestEntry;

final class ObjectIDEntries_74 {
    private ObjectIDEntries_74() {}

    static GamevalEntry[] entries() {
        return new GamevalEntry[] {
            new GamevalEntry(37956, "TUT2_BANK_LADDER", "Ladder", "loctypes"),
            new GamevalEntry(37957, "TOURNAMENT_CLANWARS_TEMPPORTAL_HUB", "Handy portal", "loctypes"),
            new GamevalEntry(37958, "PRIF_IORWERTH_DUNGEON_CAMP_TENT", "prif_iorwerth_dungeon_camp_tent", "loctypes"),
            new GamevalEntry(37959, "TUT2_BANKBOOTH", "Bank booth", "loctypes"),
            new GamevalEntry(37960, "TUT2_BANK_DOOR_OPEN", "tut2_bank_door_open", "loctypes"),
            new GamevalEntry(37961, "TUT2_BANK_EXIT", "Door", "loctypes"),
            new GamevalEntry(37962, "TUT2_PRAYER_DOOR", "tut2_prayer_door", "loctypes"),
            new GamevalEntry(37963, "TUT2_PRAYER_EXIT_L", "Door", "loctypes"),
            new GamevalEntry(37964, "TUT2_PRAYER_EXIT_R", "Door", "loctypes"),
            new GamevalEntry(37965, "TUT2_TREE", "Tree", "loctypes"),
            new GamevalEntry(37966, "TUT2_TREE_NOOP", "Tree", "loctypes"),
            new GamevalEntry(37967, "TUT2_TREE2", "Tree", "loctypes"),
            new GamevalEntry(37968, "TUT2_TREE2_NOOP", "Tree", "loctypes"),
            new GamevalEntry(37969, "TUT2_OAK", "Oak tree", "loctypes"),
            new GamevalEntry(37970, "TUT2_OAK_NOOP", "Oak tree", "loctypes"),
            new GamevalEntry(37971, "TUT2_DEAD_TREE", "Tree", "loctypes"),
            new GamevalEntry(37972, "TUT2_DEAD_TREE_NOOP", "Tree", "loctypes"),
            new GamevalEntry(37973, "TUT2_DEAD_TREE2", "Tree", "loctypes"),
            new GamevalEntry(37974, "TUT2_DEAD_TREE2_NOOP", "Tree", "loctypes"),
            new GamevalEntry(37975, "PRIF_TREE_NORMAL_2_NOCHOP", "Tree", "loctypes"),
            new GamevalEntry(37976, "RAIDS_REWARD_LOOTBEAM_KIT", "raids_reward_lootbeam_kit", "loctypes"),
            new GamevalEntry(37977, "RAIDS_REWARD_LOOTBEAM_DUST", "raids_reward_lootbeam_dust", "loctypes"),
            new GamevalEntry(37978, "RAIDS_STORAGE_4", "Massive storage unit", "loctypes"),
            new GamevalEntry(37979, "MYQ5_BARREL_NOOP", "Barrel", "loctypes"),
            new GamevalEntry(37980, "MYQ5_BARREL_OP", "Barrel", "loctypes"),
            new GamevalEntry(37981, "SLP_CHURCH_CRYPT_SOUTH_LADDER_DOWN_MYQ5", "Climb-down", "loctypes"),
            new GamevalEntry(37982, "MYQ5_KROY_TABLE_NOOP", "Lab table", "loctypes"),
            new GamevalEntry(37983, "MYQ5_KROY_TABLE_OP", "Lab table", "loctypes"),
            new GamevalEntry(37984, "MYQ5_KROY_TABLE_BROKEN", "Broken table", "loctypes"),
            new GamevalEntry(37985, "SLEPE_BODY_VIS", "Skeleton", "loctypes"),
            new GamevalEntry(37986, "MYQ5_DISGUISE_CHEST_CLOSED", "Closed Chest", "loctypes"),
            new GamevalEntry(37987, "MYQ5_DISGUISE_CHEST_OPEN", "Open Chest", "loctypes"),
            new GamevalEntry(37988, "MYQ5_DISGUISE_CHEST_CLOSED_NOOP", "Closed Chest", "loctypes"),
            new GamevalEntry(37989, "BLISTERWOOD_TREE", "Blisterwood tree", "loctypes"),
            new GamevalEntry(37990, "MYQ5_BLOOD_POOL", "Strange pool", "loctypes"),
            new GamevalEntry(37991, "MYQ5_ACID_POOL", "Acid pool", "loctypes"),
            new GamevalEntry(37992, "MYQ5_SLEPE_DOOR_ESCAPE", "Gate", "loctypes"),
            new GamevalEntry(37993, "MYQ5_SLEPE_DOOR_LEAVE", "Gate", "loctypes"),
            new GamevalEntry(37994, "MYQ5_DAMIEN_FIRE_NOOP", "Magical Fire", "loctypes"),
            new GamevalEntry(37995, "MYQ5_DAMIEN_FIRE", "Magical Fire", "loctypes"),
            new GamevalEntry(37996, "MYQ5_DAMIEN_FIRE_SMALL", "Magical Fire", "loctypes"),
            new GamevalEntry(37997, "MYQ5_VALVE_NORTH", "Valve", "loctypes"),
            new GamevalEntry(37998, "MYQ5_VALVE_SOUTH", "Valve", "loctypes"),
            new GamevalEntry(37999, "MYQ5_ARBORETUM_SHELVES", "Shelves", "loctypes"),
            new GamevalEntry(38000, "MYQ5_VANSTROM_BARRIER", "Energy Barrier", "loctypes"),
            new GamevalEntry(38001, "MYQ5_VANSTROM_BARRIER_BIG", "Energy Barrier", "loctypes"),
            new GamevalEntry(38002, "MYQ5_VANSTROM_BARRIER_NOOP", "Energy Barrier", "loctypes"),
            new GamevalEntry(38003, "MYQ5_VANSTROM_BARRIER_BIG_NOOP", "Energy Barrier", "loctypes"),
            new GamevalEntry(38004, "MYQ5_SWAMPTREE_BRANCH", "Swamp tree branch", "loctypes"),
            new GamevalEntry(38005, "MYQ5_SWAMPTREE_BRANCH_VINE", "Swamp tree branch", "loctypes"),
            new GamevalEntry(38006, "MYQ5_SWAMP_FAIL_PATH", "Path", "loctypes"),
            new GamevalEntry(38007, "MYQ5_SWAMP_FAIL_PATH_QUICK", "Path", "loctypes"),
            new GamevalEntry(38008, "MYQ5_SWAMP_SUCCESS_PATH_1", "Path", "loctypes"),
            new GamevalEntry(38009, "MYQ5_SWAMP_SUCCESS_PATH_2", "Path", "loctypes"),
            new GamevalEntry(38010, "MYQ5_SWAMP_SUCCESS_PATH_3", "Path", "loctypes"),
            new GamevalEntry(38011, "MYQ5_SWAMP_SUCCESS_PATH_4", "Path", "loctypes"),
            new GamevalEntry(38012, "MYQ5_PRISONER_DOOR", "Cell door", "loctypes"),
            new GamevalEntry(38013, "MYQ5_PRISONER_DOOR_2", "Cell door", "loctypes"),
            new GamevalEntry(38014, "MYQ5_PRISONER_DOOR_NOOP", "Cell door", "loctypes"),
            new GamevalEntry(38015, "MYQ5_VANSTROM_ORB", "Blood Orb", "loctypes"),
            new GamevalEntry(38016, "MYQ5_WALL_CAVE_EXIT", "Cave", "loctypes"),
            new GamevalEntry(38017, "MYQ5_LAB_SHELF", "Bookshelf", "loctypes"),
            new GamevalEntry(38018, "MYQ5_LAB_SHELF_FAKE", "Bookshelf", "loctypes"),
            new GamevalEntry(38019, "MYQ5_LAB_SHELF_FAKE_2", "Bookshelf", "loctypes"),
            new GamevalEntry(38020, "MYQ5_WALL_JOIN_R", "myq5_wall_join_r", "loctypes"),
            new GamevalEntry(38021, "MYQ5_WALL_JOIN_L", "myq5_wall_join_l", "loctypes"),
            new GamevalEntry(38022, "MYQ5_WALL_CAVE", "myq5_wall_cave", "loctypes"),
            new GamevalEntry(38023, "MYQ5_WALL_CAVE_SUPPORT_RIGHT", "myq5_wall_cave_support_right", "loctypes"),
            new GamevalEntry(38024, "MYQ5_WALL_CAVE_SUPPORT_LEFT", "myq5_wall_cave_support_left", "loctypes"),
            new GamevalEntry(38025, "MYQ5_WALL_CAVE_SUPPORT_MID", "myq5_wall_cave_support_mid", "loctypes"),
            new GamevalEntry(38026, "MYQ5_WALL_CAVE_SUPPORT_MID_POST", "myq5_wall_cave_support_mid_post", "loctypes"),
            new GamevalEntry(38027, "MYQ5_TORCH", "myq5_torch", "loctypes"),
            new GamevalEntry(38028, "MYQ5_LAB_CRUMBLED_WALL", "myq5_lab_crumbled_wall", "loctypes"),
            new GamevalEntry(38029, "MYQ5_LAB_CAGE_SMALL", "Cage", "loctypes"),
            new GamevalEntry(38030, "MYQ5_LAB_CAGE_SMALL_BROKEN", "Cage", "loctypes"),
            new GamevalEntry(38031, "MYQ5_LAB_CAGE_TALL", "Cage", "loctypes"),
            new GamevalEntry(38032, "MYQ5_LAB_CAGE_TALL_BROKEN", "Cage", "loctypes"),
            new GamevalEntry(38033, "MYQ5_LAB_BROKEN_BARS", "myq5_lab_broken_bars", "loctypes"),
            new GamevalEntry(38034, "MYQ5_LAB_TABLE_RESTRAINT", "Restraining Table", "loctypes"),
            new GamevalEntry(38035, "MYQ5_LAB_TABLE_RESTRAINT_SKELETON", "Restraint Table", "loctypes"),
            new GamevalEntry(38036, "MYQ5_LAB_TABLE_TOOLS", "Equipment table", "loctypes"),
            new GamevalEntry(38037, "MYQ5_LAB_TABLE_TOOLS_BROKEN", "Broken equipment table", "loctypes"),
            new GamevalEntry(38038, "MYQ5_LAB_BROKEN_RANGE", "Broken range", "loctypes"),
            new GamevalEntry(38039, "MYQ5_LAB_COFFIN1_OPEN", "Coffin", "loctypes"),
            new GamevalEntry(38040, "MYQ5_LAB_COFFIN2_OPEN", "Coffin", "loctypes"),
            new GamevalEntry(38041, "MYQ5_LAB_COFFIN_RAISED", "Raised coffin", "loctypes"),
            new GamevalEntry(38042, "MYQ5_LAB_GRAVESTONE1", "Gravestone", "loctypes"),
            new GamevalEntry(38043, "MYQ5_LAB_GRAVESTONE2", "Gravestone", "loctypes"),
            new GamevalEntry(38044, "GOTR_AGILITY_PORTAL_BOTTOM_PARENT", "gotr_agility_portal_bottom_parent", "loctypes"),
            new GamevalEntry(38045, "MYQ5_LAB_WALL_TOP_JOIN", "myq5_lab_wall_top_join", "loctypes"),
            new GamevalEntry(38046, "MYQ5_LAB_WALL_TOP_JOIN_DIAG", "myq5_lab_wall_top_join_diag", "loctypes"),
            new GamevalEntry(38047, "MYQ5_LAB_WALL_TOP_JOIN_DIAG_INNER", "myq5_lab_wall_top_join_diag_inner", "loctypes"),
            new GamevalEntry(38048, "IG_FENCE", "ig_fence", "loctypes"),
            new GamevalEntry(38049, "IG_GRAVEBED", "Grave", "loctypes"),
            new GamevalEntry(38050, "IG_GRAVESTONE_01", "Gravestone", "loctypes"),
            new GamevalEntry(38051, "IG_GRAVESTONE_02", "Gravestone", "loctypes"),
            new GamevalEntry(38052, "IG_GRAVESTONE_03", "Gravestone", "loctypes"),
            new GamevalEntry(38053, "IG_GRAVESTONE_04", "Gravestone", "loctypes"),
            new GamevalEntry(38054, "IG_GRAVESTONE_05", "Gravestone", "loctypes"),
            new GamevalEntry(38055, "IG_GRAVESTONE_06", "Gravestone", "loctypes"),
            new GamevalEntry(38056, "IG_GRAVESTONE_07", "Gravestone", "loctypes"),
            new GamevalEntry(38057, "IG_MAUSOLEUM_WALL", "ig_mausoleum_wall", "loctypes"),
            new GamevalEntry(38058, "IG_MAUSOLEUM_WALL_CORNER", "ig_mausoleum_wall_corner", "loctypes"),
            new GamevalEntry(38059, "IG_MAUSOLEUM_WALL_EDGE_R", "ig_mausoleum_wall_edge_r", "loctypes"),
            new GamevalEntry(38060, "IG_MAUSOLEUM_WALL_EDGE_L", "ig_mausoleum_wall_edge_l", "loctypes"),
            new GamevalEntry(38061, "IG_MAUSOLEUM_DOOR_ARCH", "ig_mausoleum_door_arch", "loctypes"),
            new GamevalEntry(38062, "IG_MAUSOLEUM_DOOR_SMALL", "Mausoleum door", "loctypes"),
            new GamevalEntry(38063, "IG_MAUSOLEUM_ROOF_ARCH", "ig_mausoleum_roof_arch", "loctypes"),
            new GamevalEntry(38064, "IG_MAUSOLEUM_ROOF_CENTER", "ig_mausoleum_roof_center", "loctypes"),
            new GamevalEntry(38065, "IG_MAUSOLEUM_ROOF_CORNER", "ig_mausoleum_roof_corner", "loctypes"),
            new GamevalEntry(38066, "IG_MAUSOLEUM_ROOF_EDGE", "ig_mausoleum_roof_edge", "loctypes"),
            new GamevalEntry(38067, "IG_MAUSOLEUM_STATUE", "ig_mausoleum_statue", "loctypes"),
            new GamevalEntry(38068, "IG_MAUSOLEUM_POOL", "ig_mausoleum_pool", "loctypes"),
            new GamevalEntry(38069, "IG_MAUSOLEUM_DOOR_NOOP", "Mausoleum door", "loctypes"),
            new GamevalEntry(38070, "IG_MAUSOLEUM_DOOR_UNLOCK", "Mausoleum door", "loctypes"),
            new GamevalEntry(38071, "IG_MAUSOLEUM_DOOR_OPEN", "Mausoleum door", "loctypes"),
            new GamevalEntry(38072, "IG_MAUSOLEUM_DOOR_UNLOCKED", "Mausoleum door", "loctypes"),
            new GamevalEntry(38073, "IG_MAUSOLEUM_COFFIN", "Coffin", "loctypes"),
            new GamevalEntry(38074, "IG_TALL_GRASS_WALL", "ig_tall_grass_wall", "loctypes"),
            new GamevalEntry(38075, "IG_IVY_TALL", "ig_ivy_tall", "loctypes"),
            new GamevalEntry(38076, "IG_IVY_SHORT", "ig_ivy_short", "loctypes"),
            new GamevalEntry(38077, "IG_IVY_TALL_M", "ig_ivy_tall_m", "loctypes"),
            new GamevalEntry(38078, "IG_IVY_SHORT_M", "ig_ivy_short_m", "loctypes"),
            new GamevalEntry(38079, "IG_IVY_TALL_UPPER", "ig_ivy_tall_upper", "loctypes"),
            new GamevalEntry(38080, "IG_IVY_SHORT_UPPER", "ig_ivy_short_upper", "loctypes"),
            new GamevalEntry(38081, "IG_IVY_TALL_UPPER_M", "ig_ivy_tall_upper_m", "loctypes"),
            new GamevalEntry(38082, "IG_IVY_SHORT_UPPER_M", "ig_ivy_short_upper_m", "loctypes"),
            new GamevalEntry(38083, "IG_PLANT_FLAT", "Plant", "loctypes"),
            new GamevalEntry(38084, "IG_PLANT_MORTMYRE_LEAVES_EDGE", "ig_plant_mortmyre_leaves_edge", "loctypes"),
            new GamevalEntry(38085, "IG_PLANT_MORTMYRE_LEAVES_CORNER", "ig_plant_mortmyre_leaves_corner", "loctypes"),
            new GamevalEntry(38086, "IG_PLANT_MORTMYRE_LEAVES", "ig_plant_mortmyre_leaves", "loctypes"),
            new GamevalEntry(38087, "IG_PLANT_MORTMYRE_THINNER", "ig_plant_mortmyre_thinner", "loctypes"),
            new GamevalEntry(38088, "IG_BIG_BUSH", "Plant", "loctypes"),
            new GamevalEntry(38089, "MYQ5_BOAT_VIS", "Boat", "loctypes"),
            new GamevalEntry(38090, "IG_SEA_RUIN_01", "ig_sea_ruin_01", "loctypes"),
            new GamevalEntry(38091, "BLOOD_ALTAR_SKELETON", "Skeleton", "loctypes"),
            new GamevalEntry(38092, "IG_MUD_PATCH", "Mud mound", "loctypes"),
            new GamevalEntry(38093, "ROUTE_CAVEWALLTUNNEL_NOOP", "Cave entrance", "loctypes"),
            new GamevalEntry(38094, "ROUTE_CAVEWALLTUNNEL_ESCAPE", "Cave entrance", "loctypes"),
            new GamevalEntry(38095, "MYQ4_SICKLE_CRATE_NOOP", "Crate", "loctypes"),
            new GamevalEntry(38096, "MYQ4_CHAIN_CRATE_NOOP", "Crate", "loctypes"),
            new GamevalEntry(38097, "MYQ4_HIDEOUT_EXIT_NOOP", "Ladder", "loctypes"),
            new GamevalEntry(38098, "MYQ3_LAB_DOOR_LOCKED_L_OPEN", "myq3_lab_door_locked_l_open", "loctypes"),
            new GamevalEntry(38099, "MYQ3_LAB_DOOR_LOCKED_R_OPEN", "myq3_lab_door_locked_r_open", "loctypes"),
            new GamevalEntry(38100, "MINING_SITE_ICON_MORY_ESSENCE_SOUNDS", "mining_site_icon_mory_essence_sounds", "loctypes"),
            new GamevalEntry(38101, "POLLBOOTH_SANGUINE_DARKM", "?M ??? \" #", "loctypes"),
            new GamevalEntry(38102, "HS_LOBBY_STAR_CENTER", "hs_lobby_star_center", "loctypes"),
            new GamevalEntry(38103, "HS_LOBBY_STAR_EDGE", "hs_lobby_star_edge", "loctypes"),
            new GamevalEntry(38104, "HS_LOBBY_STAR_CORNER", "hs_lobby_star_corner", "loctypes"),
            new GamevalEntry(38105, "HS_LOBBY_STAR_INNER", "hs_lobby_star_inner", "loctypes"),
            new GamevalEntry(38106, "HS_LOBBY_STAR_EDGE_HALF", "hs_lobby_star_edge_half", "loctypes"),
            new GamevalEntry(38107, "HS_LOBBY_STAR_EDGE_HALF_M", "hs_lobby_star_edge_half_m", "loctypes"),
            new GamevalEntry(38108, "HS_LOBBY_STAR_CORNER_INNER", "hs_lobby_star_corner_inner", "loctypes"),
            new GamevalEntry(38109, "HS_LOBBY_PLAIN_01", "hs_lobby_plain_01", "loctypes"),
            new GamevalEntry(38110, "HS_LOBBY_DIRT_01", "hs_lobby_dirt_01", "loctypes"),
            new GamevalEntry(38111, "HS_LOBBY_SHADE_CORNER_01", "hs_lobby_shade_corner_01", "loctypes"),
            new GamevalEntry(38112, "HS_LOBBY_SHADE_CORNER_02", "hs_lobby_shade_corner_02", "loctypes"),
            new GamevalEntry(38113, "HS_LOBBY_SHADE_EDGE_01", "hs_lobby_shade_edge_01", "loctypes"),
            new GamevalEntry(38114, "HS_LOBBY_SHADE_EDGE_02", "hs_lobby_shade_edge_02", "loctypes"),
            new GamevalEntry(38115, "HS_LOBBY_SHADE_JOIN_01", "hs_lobby_shade_join_01", "loctypes"),
            new GamevalEntry(38116, "HS_LOBBY_SHADE_JOIN_02", "hs_lobby_shade_join_02", "loctypes"),
            new GamevalEntry(38117, "HS_LOBBY_SHADE_THICK_01", "hs_lobby_shade_thick_01", "loctypes"),
            new GamevalEntry(38118, "HS_LOBBY_SHADE_THICK_02", "hs_lobby_shade_thick_02", "loctypes"),
            new GamevalEntry(38119, "HS_LOBBY_SHADE_INCORN_01", "hs_lobby_shade_incorn_01", "loctypes"),
            new GamevalEntry(38120, "HS_LOBBY_SHADE_FULL_01", "hs_lobby_shade_full_01", "loctypes"),
            new GamevalEntry(38121, "HS_LOBBY_PANEL_01", "hs_lobby_panel_01", "loctypes"),
            new GamevalEntry(38122, "HS_LOBBY_PANEL_02", "hs_lobby_panel_02", "loctypes"),
            new GamevalEntry(38123, "HS_LOBBY_PANEL_03", "hs_lobby_panel_03", "loctypes"),
            new GamevalEntry(38124, "HS_LOBBY_PANEL_04", "hs_lobby_panel_04", "loctypes"),
            new GamevalEntry(38125, "HS_LOBBY_STONES_01", "hs_lobby_stones_01", "loctypes"),
            new GamevalEntry(38126, "HS_LOBBY_STONES_02", "hs_lobby_stones_02", "loctypes"),
            new GamevalEntry(38127, "HS_LOBBY_STONES_03", "hs_lobby_stones_03", "loctypes"),
            new GamevalEntry(38128, "HS_LOBBY_STONES_04", "hs_lobby_stones_04", "loctypes"),
            new GamevalEntry(38129, "HS_NPT1_PLAIN_F2_01", "hs_npt1_plain_f2_01", "loctypes"),
            new GamevalEntry(38130, "HS_NPT1_DIRT_F2_01", "hs_npt1_dirt_f2_01", "loctypes"),
            new GamevalEntry(38131, "HS_NPT1_SHADE_CORNER_F2_01", "hs_npt1_shade_corner_f2_01", "loctypes"),
            new GamevalEntry(38132, "HS_NPT1_SHADE_CORNER_F2_02", "hs_npt1_shade_corner_f2_02", "loctypes"),
            new GamevalEntry(38133, "HS_NPT1_SHADE_EDGE_F2_01", "hs_npt1_shade_edge_f2_01", "loctypes"),
            new GamevalEntry(38134, "HS_NPT1_SHADE_EDGE_F2_02", "hs_npt1_shade_edge_f2_02", "loctypes"),
            new GamevalEntry(38135, "HS_NPT1_SHADE_JOIN_F2_01", "hs_npt1_shade_join_f2_01", "loctypes"),
            new GamevalEntry(38136, "HS_NPT1_SHADE_JOIN_F2_02", "hs_npt1_shade_join_f2_02", "loctypes"),
            new GamevalEntry(38137, "HS_NPT1_SHADE_THICK_F2_01", "hs_npt1_shade_thick_f2_01", "loctypes"),
            new GamevalEntry(38138, "HS_NPT1_SHADE_THICK_F2_02", "hs_npt1_shade_thick_f2_02", "loctypes"),
            new GamevalEntry(38139, "HS_NPT1_SHADE_INCORN_F2_01", "hs_npt1_shade_incorn_f2_01", "loctypes"),
            new GamevalEntry(38140, "HS_NPT1_SHADE_FULL_F2_01", "hs_npt1_shade_full_f2_01", "loctypes"),
            new GamevalEntry(38141, "HS_NPT1_PANEL_F2_01", "hs_npt1_panel_f2_01", "loctypes"),
            new GamevalEntry(38142, "HS_NPT1_PANEL_F2_02", "hs_npt1_panel_f2_02", "loctypes"),
            new GamevalEntry(38143, "HS_NPT1_PANEL_F2_03", "hs_npt1_panel_f2_03", "loctypes"),
            new GamevalEntry(38144, "HS_NPT1_PANEL_F2_04", "hs_npt1_panel_f2_04", "loctypes"),
            new GamevalEntry(38145, "HS_NPT1_STONES_F2_01", "hs_npt1_stones_f2_01", "loctypes"),
            new GamevalEntry(38146, "HS_NPT1_STONES_F2_02", "hs_npt1_stones_f2_02", "loctypes"),
            new GamevalEntry(38147, "HS_NPT1_STONES_F2_03", "hs_npt1_stones_f2_03", "loctypes"),
            new GamevalEntry(38148, "HS_NPT1_STONES_F2_04", "hs_npt1_stones_f2_04", "loctypes"),
            new GamevalEntry(38149, "HS_NPT1_BOLTS_F2_01", "hs_npt1_bolts_f2_01", "loctypes"),
            new GamevalEntry(38150, "HS_NPT1_BOLTS_F2_02", "hs_npt1_bolts_f2_02", "loctypes"),
            new GamevalEntry(38151, "HS_NPT1_F1_01", "hs_npt1_f1_01", "loctypes"),
            new GamevalEntry(38152, "HS_NPT1_DIRT_F1_01", "hs_npt1_dirt_f1_01", "loctypes"),
            new GamevalEntry(38153, "HS_NPT1_SHADE_CORNER_F1_01", "hs_npt1_shade_corner_f1_01", "loctypes"),
            new GamevalEntry(38154, "HS_NPT1_SHADE_CORNER_F1_02", "hs_npt1_shade_corner_f1_02", "loctypes"),
            new GamevalEntry(38155, "HS_NPT1_SHADE_EDGE_F1_01", "hs_npt1_shade_edge_f1_01", "loctypes"),
            new GamevalEntry(38156, "HS_NPT1_SHADE_EDGE_F1_02", "hs_npt1_shade_edge_f1_02", "loctypes"),
            new GamevalEntry(38157, "HS_NPT1_SHADE_JOIN_F1_01", "hs_npt1_shade_join_f1_01", "loctypes"),
            new GamevalEntry(38158, "HS_NPT1_SHADE_JOIN_F1_02", "hs_npt1_shade_join_f1_02", "loctypes"),
            new GamevalEntry(38159, "HS_NPT1_SHADE_THICK_F1_01", "hs_npt1_shade_thick_f1_01", "loctypes"),
            new GamevalEntry(38160, "HS_NPT1_SHADE_THICK_F1_02", "hs_npt1_shade_thick_f1_02", "loctypes"),
            new GamevalEntry(38161, "HS_NPT1_SHADE_INCORN_F1_01", "hs_npt1_shade_incorn_f1_01", "loctypes"),
            new GamevalEntry(38162, "HS_NPT1_SHADE_FULL_F1_01", "hs_npt1_shade_full_f1_01", "loctypes"),
            new GamevalEntry(38163, "HS_NPT1_PANEL_F1_01", "hs_npt1_panel_f1_01", "loctypes"),
            new GamevalEntry(38164, "HS_NPT1_PANEL_F1_02", "hs_npt1_panel_f1_02", "loctypes"),
            new GamevalEntry(38165, "HS_NPT1_PANEL_F1_03", "hs_npt1_panel_f1_03", "loctypes"),
            new GamevalEntry(38166, "HS_NPT1_PANEL_F1_04", "hs_npt1_panel_f1_04", "loctypes"),
            new GamevalEntry(38167, "HS_NPT1_STONES_F1_01", "hs_npt1_stones_f1_01", "loctypes"),
            new GamevalEntry(38168, "HS_NPT1_STONES_F1_02", "hs_npt1_stones_f1_02", "loctypes"),
            new GamevalEntry(38169, "HS_NPT1_STONES_F1_03", "hs_npt1_stones_f1_03", "loctypes"),
            new GamevalEntry(38170, "HS_NPT1_STONES_F1_04", "hs_npt1_stones_f1_04", "loctypes"),
            new GamevalEntry(38171, "HS_NPT1_BOLTS_F1_01", "hs_npt1_bolts_f1_01", "loctypes"),
            new GamevalEntry(38172, "HS_NPT1_BOLTS_F1_02", "hs_npt1_bolts_f1_02", "loctypes"),
            new GamevalEntry(38173, "HS_NPT1_FALLOFF_F1_01", "hs_npt1_falloff_f1_01", "loctypes"),
            new GamevalEntry(38174, "HS_NPT1_FALLOFF_F1_02", "hs_npt1_falloff_f1_02", "loctypes"),
            new GamevalEntry(38175, "HS_NPT1_FALLOFF_F1_03", "hs_npt1_falloff_f1_03", "loctypes"),
            new GamevalEntry(38176, "HS_NPT1_FALLOFF_F2_01", "hs_npt1_falloff_f2_01", "loctypes"),
            new GamevalEntry(38177, "HS_NPT1_FALLOFF_F2_02", "hs_npt1_falloff_f2_02", "loctypes"),
            new GamevalEntry(38178, "HS_NPT1_FALLOFF_F2_03", "hs_npt1_falloff_f2_03", "loctypes"),
            new GamevalEntry(38179, "HS_NPT1_BRIDGE_EDGE_F1_01", "hs_npt1_bridge_edge_f1_01", "loctypes"),
            new GamevalEntry(38180, "HS_NPT1_BRIDGE_EDGE_F1_01_M", "hs_npt1_bridge_edge_f1_01_m", "loctypes"),
            new GamevalEntry(38181, "HS_NPT1_BRIDGE_EDGE_F2_01", "hs_npt1_bridge_edge_f2_01", "loctypes"),
            new GamevalEntry(38182, "HS_NPT1_BRIDGE_EDGE_F2_01_M", "hs_npt1_bridge_edge_f2_01_m", "loctypes"),
            new GamevalEntry(38183, "HS_NPT1_BRIDGE_EDGE_F2_02", "hs_npt1_bridge_edge_f2_02", "loctypes"),
            new GamevalEntry(38184, "HS_NPT1_BRIDGE_EDGE_F2_02_M", "hs_npt1_bridge_edge_f2_02_m", "loctypes"),
            new GamevalEntry(38185, "HS_NPT2_PLAIN_F2_01", "hs_npt2_plain_f2_01", "loctypes"),
            new GamevalEntry(38186, "HS_NPT2_DIRT_F2_01", "hs_npt2_dirt_f2_01", "loctypes"),
            new GamevalEntry(38187, "HS_NPT2_SHADE_CORNER_F2_01", "hs_npt2_shade_corner_f2_01", "loctypes"),
            new GamevalEntry(38188, "HS_NPT2_SHADE_CORNER_F2_02", "hs_npt2_shade_corner_f2_02", "loctypes"),
            new GamevalEntry(38189, "HS_NPT2_SHADE_EDGE_F2_01", "hs_npt2_shade_edge_f2_01", "loctypes"),
            new GamevalEntry(38190, "HS_NPT2_SHADE_EDGE_F2_02", "hs_npt2_shade_edge_f2_02", "loctypes"),
            new GamevalEntry(38191, "HS_NPT2_SHADE_JOIN_F2_01", "hs_npt2_shade_join_f2_01", "loctypes"),
            new GamevalEntry(38192, "HS_NPT2_SHADE_JOIN_F2_02", "hs_npt2_shade_join_f2_02", "loctypes"),
            new GamevalEntry(38193, "HS_NPT2_SHADE_THICK_01", "hs_npt2_shade_thick_01", "loctypes"),
            new GamevalEntry(38194, "HS_NPT2_SHADE_THICK_F2_02", "hs_npt2_shade_thick_f2_02", "loctypes"),
            new GamevalEntry(38195, "HS_NPT2_SHADE_INCORN_F2_01", "hs_npt2_shade_incorn_f2_01", "loctypes"),
            new GamevalEntry(38196, "HS_NPT2_SHADE_FULL_F2_01", "hs_npt2_shade_full_f2_01", "loctypes"),
            new GamevalEntry(38197, "HS_NPT2_PANEL_F2_01", "hs_npt2_panel_f2_01", "loctypes"),
            new GamevalEntry(38198, "HS_NPT2_PANEL_F2_02", "hs_npt2_panel_f2_02", "loctypes"),
            new GamevalEntry(38199, "HS_NPT2_PANEL_F2_03", "hs_npt2_panel_f2_03", "loctypes"),
            new GamevalEntry(38200, "HS_NPT2_PANEL_F2_04", "hs_npt2_panel_f2_04", "loctypes"),
            new GamevalEntry(38201, "HS_NPT2_STONES_F2_01", "hs_npt2_stones_f2_01", "loctypes"),
            new GamevalEntry(38202, "HS_NPT2_STONES_F2_02", "hs_npt2_stones_f2_02", "loctypes"),
            new GamevalEntry(38203, "HS_NPT2_STONES_F2_03", "hs_npt2_stones_f2_03", "loctypes"),
            new GamevalEntry(38204, "HS_NPT2_STONES_F2_04", "hs_npt2_stones_f2_04", "loctypes"),
            new GamevalEntry(38205, "HS_NPT2_BOLTS_F2_01", "hs_npt2_bolts_f2_01", "loctypes"),
            new GamevalEntry(38206, "HS_NPT2_BOLTS_F2_02", "hs_npt2_bolts_f2_02", "loctypes"),
            new GamevalEntry(38207, "HS_NPT2_CRACK_F2_01", "hs_npt2_crack_f2_01", "loctypes"),
            new GamevalEntry(38208, "HS_NPT2_CRACK_F2_02", "hs_npt2_crack_f2_02", "loctypes"),
            new GamevalEntry(38209, "HS_NPT2_F1_01", "hs_npt2_f1_01", "loctypes"),
            new GamevalEntry(38210, "HS_NPT2_DIRT_F1_01", "hs_npt2_dirt_f1_01", "loctypes"),
            new GamevalEntry(38211, "HS_NPT2_SHADE_CORNER_F1_01", "hs_npt2_shade_corner_f1_01", "loctypes"),
            new GamevalEntry(38212, "HS_NPT2_SHADE_CORNER_F1_02", "hs_npt2_shade_corner_f1_02", "loctypes"),
            new GamevalEntry(38213, "HS_NPT2_SHADE_EDGE_F1_01", "hs_npt2_shade_edge_f1_01", "loctypes"),
            new GamevalEntry(38214, "HS_NPT2_SHADE_EDGE_F1_02", "hs_npt2_shade_edge_f1_02", "loctypes"),
            new GamevalEntry(38215, "HS_NPT2_SHADE_JOIN_F1_01", "hs_npt2_shade_join_f1_01", "loctypes"),
            new GamevalEntry(38216, "HS_NPT2_SHADE_JOIN_F1_02", "hs_npt2_shade_join_f1_02", "loctypes"),
            new GamevalEntry(38217, "HS_NPT2_SHADE_THICK_F1_01", "hs_npt2_shade_thick_f1_01", "loctypes"),
            new GamevalEntry(38218, "HS_NPT2_SHADE_THICK_F1_02", "hs_npt2_shade_thick_f1_02", "loctypes"),
            new GamevalEntry(38219, "HS_NPT2_SHADE_INCORN_F1_01", "hs_npt2_shade_incorn_f1_01", "loctypes"),
            new GamevalEntry(38220, "HS_NPT2_SHADE_FULL_F1_01", "hs_npt2_shade_full_f1_01", "loctypes"),
            new GamevalEntry(38221, "HS_NPT2_PANEL_F1_01", "hs_npt2_panel_f1_01", "loctypes"),
            new GamevalEntry(38222, "HS_NPT2_PANEL_F1_02", "hs_npt2_panel_f1_02", "loctypes"),
            new GamevalEntry(38223, "HS_NPT2_PANEL_F1_03", "hs_npt2_panel_f1_03", "loctypes"),
            new GamevalEntry(38224, "HS_NPT2_PANEL_F1_04", "hs_npt2_panel_f1_04", "loctypes"),
            new GamevalEntry(38225, "HS_NPT2_STONES_F1_01", "hs_npt2_stones_f1_01", "loctypes"),
            new GamevalEntry(38226, "HS_NPT2_STONES_F1_02", "hs_npt2_stones_f1_02", "loctypes"),
            new GamevalEntry(38227, "HS_NPT2_STONES_F1_03", "hs_npt2_stones_f1_03", "loctypes"),
            new GamevalEntry(38228, "HS_NPT2_STONES_F1_04", "hs_npt2_stones_f1_04", "loctypes"),
            new GamevalEntry(38229, "HS_NPT2_BOLTS_F1_01", "hs_npt2_bolts_f1_01", "loctypes"),
            new GamevalEntry(38230, "HS_NPT2_BOLTS_F1_02", "hs_npt2_bolts_f1_02", "loctypes"),
            new GamevalEntry(38231, "HS_NPT2_CRACK_F1_01", "hs_npt2_crack_f1_01", "loctypes"),
            new GamevalEntry(38232, "HS_NPT2_CRACK_F1_02", "hs_npt2_crack_f1_02", "loctypes"),
            new GamevalEntry(38233, "HS_NPT2_RUG_F1_CORNER_01", "hs_npt2_rug_f1_corner_01", "loctypes"),
            new GamevalEntry(38234, "HS_NPT2_RUG_F1_CORNER_02", "hs_npt2_rug_f1_corner_02", "loctypes"),
            new GamevalEntry(38235, "HS_NPT2_RUG_F1_EDGE_END_01", "hs_npt2_rug_f1_edge_end_01", "loctypes"),
            new GamevalEntry(38236, "HS_NPT2_RUG_F1_EDGE_SIDE_01", "hs_npt2_rug_f1_edge_side_01", "loctypes"),
            new GamevalEntry(38237, "HS_NPT2_RUG_F1_EDGE_SIDE_02", "hs_npt2_rug_f1_edge_side_02", "loctypes"),
            new GamevalEntry(38238, "HS_NPT2_RUG_F1_EDGE_SIDE_03", "hs_npt2_rug_f1_edge_side_03", "loctypes"),
            new GamevalEntry(38239, "HS_NPT2_RUG_F1_EDGE_SIDE_04", "hs_npt2_rug_f1_edge_side_04", "loctypes"),
            new GamevalEntry(38240, "HS_NPT2_RUG_F1_MIDDLE_01", "hs_npt2_rug_f1_middle_01", "loctypes"),
            new GamevalEntry(38241, "HS_NPT2_RUG_F1_MIDDLE_02", "hs_npt2_rug_f1_middle_02", "loctypes"),
            new GamevalEntry(38242, "HS_NPT2_RUG_F1_MIDDLE_03", "hs_npt2_rug_f1_middle_03", "loctypes"),
            new GamevalEntry(38243, "HS_NPT2_RUG_F1_MIDDLE_04", "hs_npt2_rug_f1_middle_04", "loctypes"),
            new GamevalEntry(38244, "HS_NPT2_RUG_F2_CORNER_01", "hs_npt2_rug_f2_corner_01", "loctypes"),
            new GamevalEntry(38245, "HS_NPT2_RUG_F2_CORNER_02", "hs_npt2_rug_f2_corner_02", "loctypes"),
            new GamevalEntry(38246, "HS_NPT2_RUG_F2_EDGE_END_01", "hs_npt2_rug_f2_edge_end_01", "loctypes"),
            new GamevalEntry(38247, "HS_NPT2_RUG_F2_EDGE_SIDE_01", "hs_npt2_rug_f2_edge_side_01", "loctypes"),
            new GamevalEntry(38248, "HS_NPT2_RUG_F2_EDGE_SIDE_02", "hs_npt2_rug_f2_edge_side_02", "loctypes"),
            new GamevalEntry(38249, "HS_NPT2_RUG_F2_EDGE_SIDE_03", "hs_npt2_rug_f2_edge_side_03", "loctypes"),
            new GamevalEntry(38250, "HS_NPT2_RUG_F2_EDGE_SIDE_04", "hs_npt2_rug_f2_edge_side_04", "loctypes"),
            new GamevalEntry(38251, "HS_NPT2_RUG_F2_MIDDLE_01", "hs_npt2_rug_f2_middle_01", "loctypes"),
            new GamevalEntry(38252, "HS_NPT2_RUG_F2_MIDDLE_02", "hs_npt2_rug_f2_middle_02", "loctypes"),
            new GamevalEntry(38253, "HS_NPT2_RUG_F2_MIDDLE_03", "hs_npt2_rug_f2_middle_03", "loctypes"),
            new GamevalEntry(38254, "HS_NPT2_RUG_F2_MIDDLE_04", "hs_npt2_rug_f2_middle_04", "loctypes"),
            new GamevalEntry(38255, "HS_NPT2_FALLOFF_F1_01", "hs_npt2_falloff_f1_01", "loctypes"),
            new GamevalEntry(38256, "HS_NPT2_FALLOFF_F1_02", "hs_npt2_falloff_f1_02", "loctypes"),
            new GamevalEntry(38257, "HS_NPT2_FALLOFF_F1_03", "hs_npt2_falloff_f1_03", "loctypes"),
            new GamevalEntry(38258, "HS_NPT2_FALLOFF_F1_04", "hs_npt2_falloff_f1_04", "loctypes"),
            new GamevalEntry(38259, "HS_NPT2_FALLOFF_F1_04_CORNER", "hs_npt2_falloff_f1_04_corner", "loctypes"),
            new GamevalEntry(38260, "HS_NPT2_FALLOFF_F1_04_CORNER_OUT", "hs_npt2_falloff_f1_04_corner_out", "loctypes"),
            new GamevalEntry(38261, "HS_NPT2_FALLOFF_F1_05", "hs_npt2_falloff_f1_05", "loctypes"),
            new GamevalEntry(38262, "HS_NPT2_FALLOFF_F2_01", "hs_npt2_falloff_f2_01", "loctypes"),
            new GamevalEntry(38263, "HS_NPT2_FALLOFF_F2_02", "hs_npt2_falloff_f2_02", "loctypes"),
            new GamevalEntry(38264, "HS_NPT2_FALLOFF_F2_03", "hs_npt2_falloff_f2_03", "loctypes"),
            new GamevalEntry(38265, "HS_NPT2_FALLOFF_F2_04", "hs_npt2_falloff_f2_04", "loctypes"),
            new GamevalEntry(38266, "HS_NPT2_FALLOFF_F2_04_CORNER", "hs_npt2_falloff_f2_04_corner", "loctypes"),
            new GamevalEntry(38267, "HS_NPT2_FALLOFF_F2_04_CORNER_OUT", "hs_npt2_falloff_f2_04_corner_out", "loctypes"),
            new GamevalEntry(38268, "HS_NPT2_FALLOFF_F2_05", "hs_npt2_falloff_f2_05", "loctypes"),
            new GamevalEntry(38269, "HS_NPT2_FALLOFF_OWLS_F1_01", "hs_npt2_falloff_owls_f1_01", "loctypes"),
            new GamevalEntry(38270, "HS_NPT2_FALLOFF_OWLS_F1_02", "hs_npt2_falloff_owls_f1_02", "loctypes"),
            new GamevalEntry(38271, "HS_NPT2_FALLOFF_OWLS_F1_03", "hs_npt2_falloff_owls_f1_03", "loctypes"),
            new GamevalEntry(38272, "HS_NPT2_FALLOFF_OWLS_F1_04", "hs_npt2_falloff_owls_f1_04", "loctypes"),
            new GamevalEntry(38273, "HS_NPT2_FALLOFF_OWLS_F2_01", "hs_npt2_falloff_owls_f2_01", "loctypes"),
            new GamevalEntry(38274, "HS_NPT2_FALLOFF_OWLS_F2_02", "hs_npt2_falloff_owls_f2_02", "loctypes"),
            new GamevalEntry(38275, "HS_NPT2_FALLOFF_OWLS_F2_03", "hs_npt2_falloff_owls_f2_03", "loctypes"),
            new GamevalEntry(38276, "HS_NPT2_FALLOFF_OWLS_F2_04", "hs_npt2_falloff_owls_f2_04", "loctypes"),
            new GamevalEntry(38277, "HS_NPT2_BRIDGE_EDGE_F1_01", "hs_npt2_bridge_edge_f1_01", "loctypes"),
            new GamevalEntry(38278, "HS_NPT2_BRIDGE_EDGE_F1_01_M", "hs_npt2_bridge_edge_f1_01_m", "loctypes"),
            new GamevalEntry(38279, "HS_NPT2_BRIDGE_EDGE_F2_01", "hs_npt2_bridge_edge_f2_01", "loctypes"),
            new GamevalEntry(38280, "HS_NPT2_BRIDGE_EDGE_F2_01_M", "hs_npt2_bridge_edge_f2_01_m", "loctypes"),
            new GamevalEntry(38281, "HS_NPT2_BRIDGE_EDGE_F2_02", "hs_npt2_bridge_edge_f2_02", "loctypes"),
            new GamevalEntry(38282, "HS_NPT2_BRIDGE_EDGE_F2_02_M", "hs_npt2_bridge_edge_f2_02_m", "loctypes"),
            new GamevalEntry(38283, "HS_NPT3_PLAIN_F2_01", "hs_npt3_plain_f2_01", "loctypes"),
            new GamevalEntry(38284, "HS_NPT3_DIRT_F2_01", "hs_npt3_dirt_f2_01", "loctypes"),
            new GamevalEntry(38285, "HS_NPT3_SHADE_CORNER_F2_01", "hs_npt3_shade_corner_f2_01", "loctypes"),
            new GamevalEntry(38286, "HS_NPT3_SHADE_CORNER_F2_02", "hs_npt3_shade_corner_f2_02", "loctypes"),
            new GamevalEntry(38287, "HS_NPT3_SHADE_EDGE_F2_01", "hs_npt3_shade_edge_f2_01", "loctypes"),
            new GamevalEntry(38288, "HS_NPT3_SHADE_EDGE_F2_02", "hs_npt3_shade_edge_f2_02", "loctypes"),
            new GamevalEntry(38289, "HS_NPT3_SHADE_JOIN_F2_01", "hs_npt3_shade_join_f2_01", "loctypes"),
            new GamevalEntry(38290, "HS_NPT3_SHADE_JOIN_F2_02", "hs_npt3_shade_join_f2_02", "loctypes"),
            new GamevalEntry(38291, "HS_NPT3_SHADE_THICK_F2_01", "hs_npt3_shade_thick_f2_01", "loctypes"),
            new GamevalEntry(38292, "HS_NPT3_SHADE_THICK_F2_02", "hs_npt3_shade_thick_f2_02", "loctypes"),
            new GamevalEntry(38293, "HS_NPT3_SHADE_INCORN_F2_01", "hs_npt3_shade_incorn_f2_01", "loctypes"),
            new GamevalEntry(38294, "HS_NPT3_SHADE_FULL_F2_01", "hs_npt3_shade_full_f2_01", "loctypes"),
            new GamevalEntry(38295, "HS_NPT3_PANEL_F2_01", "hs_npt3_panel_f2_01", "loctypes"),
            new GamevalEntry(38296, "HS_NPT3_PANEL_F2_02", "hs_npt3_panel_f2_02", "loctypes"),
            new GamevalEntry(38297, "HS_NPT3_PANEL_F2_03", "hs_npt3_panel_f2_03", "loctypes"),
            new GamevalEntry(38298, "HS_NPT3_PANEL_F2_04", "hs_npt3_panel_f2_04", "loctypes"),
            new GamevalEntry(38299, "HS_NPT3_STONES_F2_01", "hs_npt3_stones_f2_01", "loctypes"),
            new GamevalEntry(38300, "HS_NPT3_STONES_F2_02", "hs_npt3_stones_f2_02", "loctypes"),
            new GamevalEntry(38301, "HS_NPT3_STONES_F2_03", "hs_npt3_stones_f2_03", "loctypes"),
            new GamevalEntry(38302, "HS_NPT3_STONES_F2_04", "hs_npt3_stones_f2_04", "loctypes"),
            new GamevalEntry(38303, "HS_NPT3_BOLTS_F2_01", "hs_npt3_bolts_f2_01", "loctypes"),
            new GamevalEntry(38304, "HS_NPT3_BOLTS_F2_02", "hs_npt3_bolts_f2_02", "loctypes"),
            new GamevalEntry(38305, "HS_NPT3_CRACK_F2_01", "hs_npt3_crack_f2_01", "loctypes"),
            new GamevalEntry(38306, "HS_NPT3_CRACK_F2_02", "hs_npt3_crack_f2_02", "loctypes"),
            new GamevalEntry(38307, "HS_NPT3_F1_01", "hs_npt3_f1_01", "loctypes"),
            new GamevalEntry(38308, "HS_NPT3_DIRT_F1_01", "hs_npt3_dirt_f1_01", "loctypes"),
            new GamevalEntry(38309, "HS_NPT3_SHADE_CORNER_F1_01", "hs_npt3_shade_corner_f1_01", "loctypes"),
            new GamevalEntry(38310, "HS_NPT3_SHADE_CORNER_F1_02", "hs_npt3_shade_corner_f1_02", "loctypes"),
            new GamevalEntry(38311, "HS_NPT3_SHADE_EDGE_F1_01", "hs_npt3_shade_edge_f1_01", "loctypes"),
            new GamevalEntry(38312, "HS_NPT3_SHADE_EDGE_F1_02", "hs_npt3_shade_edge_f1_02", "loctypes"),
            new GamevalEntry(38313, "HS_NPT3_SHADE_JOIN_F1_01", "hs_npt3_shade_join_f1_01", "loctypes"),
            new GamevalEntry(38314, "HS_NPT3_SHADE_JOIN_F1_02", "hs_npt3_shade_join_f1_02", "loctypes"),
            new GamevalEntry(38315, "HS_NPT3_SHADE_THICK_F1_01", "hs_npt3_shade_thick_f1_01", "loctypes"),
            new GamevalEntry(38316, "HS_NPT3_SHADE_THICK_F1_02", "hs_npt3_shade_thick_f1_02", "loctypes"),
            new GamevalEntry(38317, "HS_NPT3_SHADE_INCORN_F1_01", "hs_npt3_shade_incorn_f1_01", "loctypes"),
            new GamevalEntry(38318, "HS_NPT3_SHADE_FULL_F1_01", "hs_npt3_shade_full_f1_01", "loctypes"),
            new GamevalEntry(38319, "HS_NPT3_PANEL_F1_01", "hs_npt3_panel_f1_01", "loctypes"),
            new GamevalEntry(38320, "HS_NPT3_PANEL_F1_02", "hs_npt3_panel_f1_02", "loctypes"),
            new GamevalEntry(38321, "HS_NPT3_PANEL_F1_03", "hs_npt3_panel_f1_03", "loctypes"),
            new GamevalEntry(38322, "HS_NPT3_PANEL_F1_04", "hs_npt3_panel_f1_04", "loctypes"),
            new GamevalEntry(38323, "HS_NPT3_STONES_F1_01", "hs_npt3_stones_f1_01", "loctypes"),
            new GamevalEntry(38324, "HS_NPT3_STONES_F1_02", "hs_npt3_stones_f1_02", "loctypes"),
            new GamevalEntry(38325, "HS_NPT3_STONES_F1_03", "hs_npt3_stones_f1_03", "loctypes"),
            new GamevalEntry(38326, "HS_NPT3_STONES_F1_04", "hs_npt3_stones_f1_04", "loctypes"),
            new GamevalEntry(38327, "HS_NPT3_BOLTS_F1_01", "hs_npt3_bolts_f1_01", "loctypes"),
            new GamevalEntry(38328, "HS_NPT3_BOLTS_F1_02", "hs_npt3_bolts_f1_02", "loctypes"),
            new GamevalEntry(38329, "HS_NPT3_CRACK_F1_01", "hs_npt3_crack_f1_01", "loctypes"),
            new GamevalEntry(38330, "HS_NPT3_CRACK_F1_02", "hs_npt3_crack_f1_02", "loctypes"),
            new GamevalEntry(38331, "HS_NPT3_F0_01", "hs_npt3_f0_01", "loctypes"),
            new GamevalEntry(38332, "HS_NPT3_DIRT_F0_01", "hs_npt3_dirt_f0_01", "loctypes"),
            new GamevalEntry(38333, "HS_NPT3_SHADE_CORNER_F0_01", "hs_npt3_shade_corner_f0_01", "loctypes"),
            new GamevalEntry(38334, "HS_NPT3_SHADE_CORNER_F0_02", "hs_npt3_shade_corner_f0_02", "loctypes"),
            new GamevalEntry(38335, "HS_NPT3_SHADE_EDGE_F0_01", "hs_npt3_shade_edge_f0_01", "loctypes"),
            new GamevalEntry(38336, "HS_NPT3_SHADE_EDGE_F0_02", "hs_npt3_shade_edge_f0_02", "loctypes"),
            new GamevalEntry(38337, "HS_NPT3_SHADE_JOIN_F0_01", "hs_npt3_shade_join_f0_01", "loctypes"),
            new GamevalEntry(38338, "HS_NPT3_SHADE_JOIN_F0_02", "hs_npt3_shade_join_f0_02", "loctypes"),
            new GamevalEntry(38339, "HS_NPT3_SHADE_THICK_F0_01", "hs_npt3_shade_thick_f0_01", "loctypes"),
            new GamevalEntry(38340, "HS_NPT3_SHADE_THICK_F0_02", "hs_npt3_shade_thick_f0_02", "loctypes"),
            new GamevalEntry(38341, "HS_NPT3_SHADE_INCORN_F0_01", "hs_npt3_shade_incorn_f0_01", "loctypes"),
            new GamevalEntry(38342, "HS_NPT3_SHADE_FULL_F0_01", "hs_npt3_shade_full_f0_01", "loctypes"),
            new GamevalEntry(38343, "HS_NPT3_PANEL_F0_01", "hs_npt3_panel_f0_01", "loctypes"),
            new GamevalEntry(38344, "HS_NPT3_PANEL_F0_02", "hs_npt3_panel_f0_02", "loctypes"),
            new GamevalEntry(38345, "HS_NPT3_PANEL_F0_03", "hs_npt3_panel_f0_03", "loctypes"),
            new GamevalEntry(38346, "HS_NPT3_STONES_F0_01", "hs_npt3_stones_f0_01", "loctypes"),
            new GamevalEntry(38347, "HS_NPT3_STONES_F0_02", "hs_npt3_stones_f0_02", "loctypes"),
            new GamevalEntry(38348, "HS_NPT3_STONES_F0_03", "hs_npt3_stones_f0_03", "loctypes"),
            new GamevalEntry(38349, "HS_NPT3_STONES_F0_04", "hs_npt3_stones_f0_04", "loctypes"),
            new GamevalEntry(38350, "HS_NPT3_BOLTS_F0_01", "hs_npt3_bolts_f0_01", "loctypes"),
            new GamevalEntry(38351, "HS_NPT3_BOLTS_F0_02", "hs_npt3_bolts_f0_02", "loctypes"),
            new GamevalEntry(38352, "HS_NPT3_CRACK_F0_01", "hs_npt3_crack_f0_01", "loctypes"),
            new GamevalEntry(38353, "HS_NPT3_CRACK_F0_02", "hs_npt3_crack_f0_02", "loctypes"),
            new GamevalEntry(38354, "HS_NPT3_FALLOFF_F0_01", "hs_npt3_falloff_f0_01", "loctypes"),
            new GamevalEntry(38355, "HS_NPT3_FALLOFF_F1_01", "hs_npt3_falloff_f1_01", "loctypes"),
            new GamevalEntry(38356, "HS_NPT3_FALLOFF_F1_02", "hs_npt3_falloff_f1_02", "loctypes"),
            new GamevalEntry(38357, "HS_NPT3_FALLOFF_F1_04", "hs_npt3_falloff_f1_04", "loctypes"),
            new GamevalEntry(38358, "HS_NPT3_FALLOFF_F1_04_CORNER", "hs_npt3_falloff_f1_04_corner", "loctypes"),
            new GamevalEntry(38359, "HS_NPT3_FALLOFF_F1_04_CORNER_OUT", "hs_npt3_falloff_f1_04_corner_out", "loctypes"),
            new GamevalEntry(38360, "HS_NPT3_FALLOFF_F1_05", "hs_npt3_falloff_f1_05", "loctypes"),
            new GamevalEntry(38361, "HS_NPT3_FALLOFF_F2_01", "hs_npt3_falloff_f2_01", "loctypes"),
            new GamevalEntry(38362, "HS_NPT3_FALLOFF_F2_02", "hs_npt3_falloff_f2_02", "loctypes"),
            new GamevalEntry(38363, "HS_NPT3_FALLOFF_F2_05", "hs_npt3_falloff_f2_05", "loctypes"),
            new GamevalEntry(38364, "HS_NPT3_BRIDGE_EDGE_F0_01", "hs_npt3_bridge_edge_f0_01", "loctypes"),
            new GamevalEntry(38365, "HS_NPT3_BRIDGE_EDGE_F0_01_M", "hs_npt3_bridge_edge_f0_01_m", "loctypes"),
            new GamevalEntry(38366, "HS_NPT3_BRIDGE_EDGE_F1_01", "hs_npt3_bridge_edge_f1_01", "loctypes"),
            new GamevalEntry(38367, "HS_NPT3_BRIDGE_EDGE_F1_01_M", "hs_npt3_bridge_edge_f1_01_m", "loctypes"),
            new GamevalEntry(38368, "HS_NPT3_BRIDGE_EDGE_F2_01", "hs_npt3_bridge_edge_f2_01", "loctypes"),
            new GamevalEntry(38369, "HS_NPT3_BRIDGE_EDGE_F2_01_M", "hs_npt3_bridge_edge_f2_01_m", "loctypes"),
            new GamevalEntry(38370, "HS_NPT3_BRIDGE_EDGE_F2_02", "hs_npt3_bridge_edge_f2_02", "loctypes"),
            new GamevalEntry(38371, "HS_NPT3_BRIDGE_EDGE_F2_02_M", "hs_npt3_bridge_edge_f2_02_m", "loctypes"),
            new GamevalEntry(38372, "HS_NPT3_POOL_ALL", "hs_npt3_pool_all", "loctypes"),
            new GamevalEntry(38373, "HS_NPT3_POOL_CORNER", "hs_npt3_pool_corner", "loctypes"),
            new GamevalEntry(38374, "HS_NPT3_POOL_CORNER_FOLIAGE", "hs_npt3_pool_corner_foliage", "loctypes"),
            new GamevalEntry(38375, "HS_NPT3_POOL_CORNER_OUT", "hs_npt3_pool_corner_out", "loctypes"),
            new GamevalEntry(38376, "HS_NPT3_POOL_CORNER_OUT_FOLIAGE", "hs_npt3_pool_corner_out_foliage", "loctypes"),
            new GamevalEntry(38377, "HS_NPT3_POOL_EDGE", "hs_npt3_pool_edge", "loctypes"),
            new GamevalEntry(38378, "HS_NPT3_POOL_EDGE_FOLIAGE", "hs_npt3_pool_edge_foliage", "loctypes"),
            new GamevalEntry(38379, "HS_NPT3_POOL_END", "hs_npt3_pool_end", "loctypes"),
            new GamevalEntry(38380, "HS_NPT3_POOL_NONE", "hs_npt3_pool_none", "loctypes"),
            new GamevalEntry(38381, "HS_NPT3_POOL_FISH", "Fish", "loctypes"),
            new GamevalEntry(38382, "HS_NPT3_POOL_TUBE", "hs_npt3_pool_tube", "loctypes"),
            new GamevalEntry(38383, "HS_NPT3_SKEWSTEPS", "hs_npt3_skewsteps", "loctypes"),
            new GamevalEntry(38384, "HS_NPT3_SKEWSTEPS_CORNER", "hs_npt3_skewsteps_corner", "loctypes"),
            new GamevalEntry(38385, "HS_NPT3_SKEWSTEPS_CORNER2", "hs_npt3_skewsteps_corner2", "loctypes"),
            new GamevalEntry(38386, "HS_NPT1_BURNT_F1_01", "hs_npt1_burnt_f1_01", "loctypes"),
            new GamevalEntry(38387, "HS_NPT1_BURNT_F1_02", "hs_npt1_burnt_f1_02", "loctypes"),
            new GamevalEntry(38388, "HS_NPT1_BURNT_F1_03", "hs_npt1_burnt_f1_03", "loctypes"),
            new GamevalEntry(38389, "HS_NPT1_BURNT_F2_01", "hs_npt1_burnt_f2_01", "loctypes"),
            new GamevalEntry(38390, "HS_NPT1_BURNT_F2_02", "hs_npt1_burnt_f2_02", "loctypes"),
            new GamevalEntry(38391, "HS_NPT1_BURNT_F2_03", "hs_npt1_burnt_f2_03", "loctypes"),
            new GamevalEntry(38392, "HS_NPT2_BURNT_F1_01", "hs_npt2_burnt_f1_01", "loctypes"),
            new GamevalEntry(38393, "HS_NPT2_BURNT_F1_02", "hs_npt2_burnt_f1_02", "loctypes"),
            new GamevalEntry(38394, "HS_NPT2_BURNT_F1_03", "hs_npt2_burnt_f1_03", "loctypes"),
            new GamevalEntry(38395, "HS_NPT2_BURNT_F2_01", "hs_npt2_burnt_f2_01", "loctypes"),
            new GamevalEntry(38396, "HS_NPT2_BURNT_F2_02", "hs_npt2_burnt_f2_02", "loctypes"),
            new GamevalEntry(38397, "HS_NPT2_BURNT_F2_03", "hs_npt2_burnt_f2_03", "loctypes"),
            new GamevalEntry(38398, "HS_NPT3_BURNT_F0_01", "hs_npt3_burnt_f0_01", "loctypes"),
            new GamevalEntry(38399, "HS_NPT3_BURNT_F0_02", "hs_npt3_burnt_f0_02", "loctypes"),
            new GamevalEntry(38400, "HS_NPT3_BURNT_F0_03", "hs_npt3_burnt_f0_03", "loctypes"),
            new GamevalEntry(38401, "HS_NPT3_BURNT_F0_04", "hs_npt3_burnt_f0_04", "loctypes"),
            new GamevalEntry(38402, "HS_NPT3_BURNT_F1_01", "hs_npt3_burnt_f1_01", "loctypes"),
            new GamevalEntry(38403, "HS_NPT3_BURNT_F1_02", "hs_npt3_burnt_f1_02", "loctypes"),
            new GamevalEntry(38404, "HS_NPT3_BURNT_F1_03", "hs_npt3_burnt_f1_03", "loctypes"),
            new GamevalEntry(38405, "HS_NPT3_BURNT_F2_01", "hs_npt3_burnt_f2_01", "loctypes"),
            new GamevalEntry(38406, "HS_NPT3_BURNT_F2_02", "hs_npt3_burnt_f2_02", "loctypes"),
            new GamevalEntry(38407, "HS_NPT3_BURNT_F2_03", "hs_npt3_burnt_f2_03", "loctypes"),
            new GamevalEntry(38408, "HALLOWED_INVISIBLE_NPC", "hallowed_invisible_npc", "loctypes"),
            new GamevalEntry(38409, "HALLOWED_FIRE_TRAP", "Wizard Statue", "loctypes"),
            new GamevalEntry(38410, "HALLOWED_FIRE_TRAP_V2", "Wizard Statue", "loctypes"),
            new GamevalEntry(38411, "HALLOWED_FIRE_TRAP_V3", "Wizard Statue", "loctypes"),
            new GamevalEntry(38412, "HALLOWED_FIRE_TRAP_V4", "Wizard Statue", "loctypes"),
            new GamevalEntry(38413, "HALLOWED_FIRE_TRAP_V5", "Wizard Statue", "loctypes"),
            new GamevalEntry(38414, "HALLOWED_FIRE_TRAP_V6", "Wizard Statue", "loctypes"),
            new GamevalEntry(38415, "HALLOWED_FIRE_TRAP_V7", "Wizard Statue", "loctypes"),
            new GamevalEntry(38416, "HALLOWED_FIRE_TRAP_T2", "Wizard Statue", "loctypes"),
            new GamevalEntry(38417, "HALLOWED_FIRE_TRAP_T2_V2", "Wizard Statue", "loctypes"),
            new GamevalEntry(38418, "HALLOWED_FIRE_TRAP_T2_V3", "Wizard Statue", "loctypes"),
            new GamevalEntry(38419, "HALLOWED_FIRE_TRAP_T2_V4", "Wizard Statue", "loctypes"),
            new GamevalEntry(38420, "HALLOWED_FIRE_TRAP_T2_V5", "Wizard Statue", "loctypes"),
            new GamevalEntry(38421, "HALLOWED_FIRE_TRAP_T3", "Wizard Statue", "loctypes"),
            new GamevalEntry(38422, "HALLOWED_FIRE_TRAP_T3_V2", "Wizard Statue", "loctypes"),
            new GamevalEntry(38423, "HALLOWED_FIRE_TRAP_T3_V3", "Wizard Statue", "loctypes"),
            new GamevalEntry(38424, "HALLOWED_FIRE_TRAP_T3_V4", "Wizard Statue", "loctypes"),
            new GamevalEntry(38425, "HALLOWED_FIRE_TRAP_T3_V5", "Wizard Statue", "loctypes"),
            new GamevalEntry(38426, "DEATH_OFFICE_ACCESS_GRAVE", "Death's Domain", "loctypes"),
            new GamevalEntry(38427, "HALLOWED_FIRE_TRAP_ANIMATIONS", "Fire", "loctypes"),
            new GamevalEntry(38428, "HALLOWED_SWORD_TRAP", "Knight Statue", "loctypes"),
            new GamevalEntry(38429, "HALLOWED_SWORD_TRAP_OWL", "Knight Statue", "loctypes"),
            new GamevalEntry(38430, "HALLOWED_SWORD_TRAP_LION", "Knight Statue", "loctypes"),
            new GamevalEntry(38431, "HALLOWED_SWORD_TRAP_UNICORN", "Knight Statue", "loctypes"),
            new GamevalEntry(38432, "HALLOWED_SWORD_TRAP_T2", "Knight Statue", "loctypes"),
            new GamevalEntry(38433, "HALLOWED_SWORD_TRAP_T2_LION", "Knight Statue", "loctypes"),
            new GamevalEntry(38434, "HALLOWED_SWORD_TRAP_T3", "Knight Statue", "loctypes"),
            new GamevalEntry(38435, "HALLOWED_SWORD_TRAP_T3_LION", "Knight Statue", "loctypes"),
            new GamevalEntry(38436, "HALLOWED_SWORD_TRAP_THROWN", "Knight Statue", "loctypes"),
            new GamevalEntry(38437, "HALLOWED_SWORD_TRAP_OWL_THROWN", "Knight Statue", "loctypes"),
            new GamevalEntry(38438, "HALLOWED_SWORD_TRAP_LION_THROWN", "Knight Statue", "loctypes"),
            new GamevalEntry(38439, "HALLOWED_SWORD_TRAP_UNICORN_THROWN", "Knight Statue", "loctypes"),
            new GamevalEntry(38440, "HALLOWED_SWORD_TRAP_T2_THROWN", "Knight Statue", "loctypes"),
            new GamevalEntry(38441, "HALLOWED_SWORD_TRAP_T2_LION_THROWN", "Knight Statue", "loctypes"),
            new GamevalEntry(38442, "HALLOWED_SWORD_TRAP_T3_THROWN", "Knight Statue", "loctypes"),
            new GamevalEntry(38443, "HALLOWED_SWORD_TRAP_T3_LION_THROWN", "Knight Statue", "loctypes"),
            new GamevalEntry(38444, "HALLOWED_PROJECTILE_TRAP", "Crossbowman Statue", "loctypes"),
            new GamevalEntry(38445, "HALLOWED_PROJECTILE_TRAP_T2", "Crossbowman Statue", "loctypes"),
            new GamevalEntry(38446, "HALLOWED_PROJECTILE_TRAP_T3", "Crossbowman Statue", "loctypes"),
            new GamevalEntry(38447, "HALLOWED_TELEPORT_TRAP", "Strange Tile", "loctypes"),
            new GamevalEntry(38448, "HALLOWED_TELEPORT_TRAP_FORWARD", "Strange Tile", "loctypes"),
            new GamevalEntry(38449, "HALLOWED_LIGHTNING_TRAP_T2", "Priest Statue", "loctypes"),
            new GamevalEntry(38450, "HALLOWED_LIGHTNING_TRAP_T3", "Priest Statue", "loctypes"),
            new GamevalEntry(38451, "HALLOWED_EXIT", "Magical Obelisk", "loctypes"),
            new GamevalEntry(38452, "HALLOWED_MINIGAME_START", "Stairs", "loctypes"),
            new GamevalEntry(38453, "HALLOWED_PROGRESS_STAIRS", "Stairs", "loctypes"),
            new GamevalEntry(38454, "HALLOWED_LOCKED_STAIRS", "Stairs", "loctypes"),
            new GamevalEntry(38455, "HALLOWED_PATH_END_JUMPOVER_01_NORTH", "Platform", "loctypes"),
            new GamevalEntry(38456, "HALLOWED_PATH_END_JUMPOVER_01_EAST", "Platform", "loctypes"),
            new GamevalEntry(38457, "HALLOWED_PATH_END_JUMPOVER_01_SOUTH", "Platform", "loctypes"),
            new GamevalEntry(38458, "HALLOWED_PATH_END_JUMPOVER_01_WEST", "Platform", "loctypes"),
            new GamevalEntry(38459, "HALLOWED_PATH_END_JUMPOVER_02", "Platform", "loctypes"),
            new GamevalEntry(38460, "HALLOWED_PATH_END_GATE", "Gate", "loctypes"),
            new GamevalEntry(38461, "HALLOWED_STAIRS_RETURN", "Stairs", "loctypes"),
            new GamevalEntry(38462, "HALLOWED_FLOOR_1_NORTHPATH_DROP", "Stairs", "loctypes"),
            new GamevalEntry(38463, "HALLOWED_FLOOR_1_EASTPATH_STAIRS", "Stairs", "loctypes"),
            new GamevalEntry(38464, "HALLOWED_FLOOR_1_SOUTHPATH_STAIRS", "Stairs", "loctypes"),
            new GamevalEntry(38465, "HALLOWED_FLOOR_1_WESTPATH_DROP", "Stairs", "loctypes"),
            new GamevalEntry(38466, "HALLOWED_FLOOR_2_NORTHPATH_STAIRS", "Stairs", "loctypes"),
            new GamevalEntry(38467, "HALLOWED_FLOOR_2_EASTPATH_STAIRS", "Stairs", "loctypes"),
        };
    }

    static Optional<GamevalEntry> byId(int id) {
        for (GamevalEntry entry : entries()) {
            if (entry.id() == id) return Optional.of(entry);
        }
        return Optional.empty();
    }

}
