package net.titan.gamevals.internal;

import java.util.Optional;

import net.titan.gamevals.GamevalEntry;
import net.titan.gamevals.QuestEntry;

final class ObjectIDEntries_92 {
    private ObjectIDEntries_92() {}

    static GamevalEntry[] entries() {
        return new GamevalEntry[] {
            new GamevalEntry(47104, "WILD_CALLISTO_BONES04", "wild_callisto_bones04", "loctypes"),
            new GamevalEntry(47105, "WILD_CALLISTO_BONES05", "wild_callisto_bones05", "loctypes"),
            new GamevalEntry(47106, "WILD_CALLISTO_DUGUPSOIL01_GREY", "wild_callisto_dugupsoil01_grey", "loctypes"),
            new GamevalEntry(47107, "WILD_CALLISTO_DUGUPSOIL02_GREY", "wild_callisto_dugupsoil02_grey", "loctypes"),
            new GamevalEntry(47108, "WILD_CALLISTO_DUGUPSOIL03_GREY", "wild_callisto_dugupsoil03_grey", "loctypes"),
            new GamevalEntry(47109, "WILD_CALLISTO_DUGUPSOIL01_RED", "wild_callisto_dugupsoil01_red", "loctypes"),
            new GamevalEntry(47110, "WILD_CALLISTO_DUGUPSOIL02_RED", "wild_callisto_dugupsoil02_red", "loctypes"),
            new GamevalEntry(47111, "WILD_CALLISTO_DUGUPSOIL03_RED", "wild_callisto_dugupsoil03_red", "loctypes"),
            new GamevalEntry(47112, "WILD_CALLISTO_TWIG01", "wild_callisto_twig01", "loctypes"),
            new GamevalEntry(47113, "WILD_CALLISTO_TWIG02", "wild_callisto_twig02", "loctypes"),
            new GamevalEntry(47114, "WILD_CALLISTO_TWIG03", "wild_callisto_twig03", "loctypes"),
            new GamevalEntry(47115, "WILD_CALLISTO_TWIG04", "wild_callisto_twig04", "loctypes"),
            new GamevalEntry(47116, "CAVEKIT_ROCK02_LOW01", "cavekit_rock02_low01", "loctypes"),
            new GamevalEntry(47117, "CAVEKIT_ROCK02_LOW02", "cavekit_rock02_low02", "loctypes"),
            new GamevalEntry(47118, "CAVEKIT_ROCK02_LOW03", "cavekit_rock02_low03", "loctypes"),
            new GamevalEntry(47119, "CAVEKIT_ROCK02_LOW04", "cavekit_rock02_low04", "loctypes"),
            new GamevalEntry(47120, "CAVEKIT_ROCK02_LOW05", "cavekit_rock02_low05", "loctypes"),
            new GamevalEntry(47121, "CAVEKIT_ROCK02_LOW06", "cavekit_rock02_low06", "loctypes"),
            new GamevalEntry(47122, "WILD_CALLISTO_EXIT01", "Exit", "loctypes"),
            new GamevalEntry(47123, "WILD_CALLISTO_FOG_1X1", "wild_callisto_fog_1x1", "loctypes"),
            new GamevalEntry(47124, "WILD_CALLISTO_FOG_2X2", "wild_callisto_fog_2x2", "loctypes"),
            new GamevalEntry(47125, "WILD_CALLISTO_FOG_3X3", "wild_callisto_fog_3x3", "loctypes"),
            new GamevalEntry(47126, "WILD_CALLISTO_FOG_1X1_DARK", "wild_callisto_fog_1x1_dark", "loctypes"),
            new GamevalEntry(47127, "WILD_CALLISTO_FOG_2X2_DARK", "wild_callisto_fog_2x2_dark", "loctypes"),
            new GamevalEntry(47128, "WILD_CALLISTO_FOG_3X3_DARK", "wild_callisto_fog_3x3_dark", "loctypes"),
            new GamevalEntry(47129, "WILD_CALLISTO_BLOODSPLATTER01", "Bloodsplatter", "loctypes"),
            new GamevalEntry(47130, "WILD_CALLISTO_BLOODSPLATTER02", "Bloodsplatter", "loctypes"),
            new GamevalEntry(47131, "WILD_CALLISTO_BLOODSPLATTER03", "Bloodsplatter", "loctypes"),
            new GamevalEntry(47132, "WILD_CALLISTO_EXPLORER01", "Dead Explorer", "loctypes"),
            new GamevalEntry(47133, "WILD_CALLISTO_STALAGTITE01", "wild_callisto_stalagtite01", "loctypes"),
            new GamevalEntry(47134, "WILD_CALLISTO_STALAGTITE02", "wild_callisto_stalagtite02", "loctypes"),
            new GamevalEntry(47135, "WILD_CALLISTO_ROCKS01", "wild_callisto_rocks01", "loctypes"),
            new GamevalEntry(47136, "WILD_CALLISTO_ROCKS02", "wild_callisto_rocks02", "loctypes"),
            new GamevalEntry(47137, "WILD_CALLISTO_ROCKS03", "wild_callisto_rocks03", "loctypes"),
            new GamevalEntry(47138, "WILD_CALLISTO_ROCKS04", "wild_callisto_rocks04", "loctypes"),
            new GamevalEntry(47139, "WILD_CALLISTO_ROCKS05", "wild_callisto_rocks05", "loctypes"),
            new GamevalEntry(47140, "WILD_CALLISTO_ENTRANCE01", "Cave Entrance", "loctypes"),
            new GamevalEntry(47141, "WILD_CALLISTO_SINGLES_ENTRANCE01", "Cave Entrance", "loctypes"),
            new GamevalEntry(47142, "WILD_CALLISTO_ROCKS02_DARK", "wild_callisto_rocks02_dark", "loctypes"),
            new GamevalEntry(47143, "WILD_CALLISTO_ROCKS04_DARK", "wild_callisto_rocks04_dark", "loctypes"),
            new GamevalEntry(47144, "WILD_CALLISTO_ROCKS03_DARK", "wild_callisto_rocks03_dark", "loctypes"),
            new GamevalEntry(47145, "WILD_CALLISTO_SIGN01", "Signpost", "loctypes"),
            new GamevalEntry(47146, "CALLISTO_TRAP_LOC", "callisto_trap_loc", "loctypes"),
            new GamevalEntry(47147, "WILD_BOSS_ESCAPE_CAVE_EXIT01", "Exit", "loctypes"),
            new GamevalEntry(47148, "WILD_BOSS_ESCAPE_CAVE_EXIT02", "Exit", "loctypes"),
            new GamevalEntry(47149, "WILD_BOSS_ESCAPE_CAVE_EXIT03", "Exit", "loctypes"),
            new GamevalEntry(47150, "WILD_BOSS_ESCAPE_CAVE_EXIT03_OVERHEAD", "wild_boss_escape_cave_exit03_overhead", "loctypes"),
            new GamevalEntry(47151, "WILD_BOSS_ESCAPE_CAVE_EXIT_NOOP", "wild_boss_escape_cave_exit_noop", "loctypes"),
            new GamevalEntry(47152, "WILD_BOSS_ESCAPE_CAVE_CALLISTO", "wild_boss_escape_cave_callisto", "loctypes"),
            new GamevalEntry(47153, "WILD_BOSS_ESCAPE_CAVE_CALLISTO_SIDE_LEFT", "wild_boss_escape_cave_callisto_side_left", "loctypes"),
            new GamevalEntry(47154, "WILD_BOSS_ESCAPE_CAVE_CALLISTO_SIDE_RIGHT", "wild_boss_escape_cave_callisto_side_right", "loctypes"),
            new GamevalEntry(47155, "WILD_BOSS_ESCAPE_CAVE_EXIT_VENENATIS", "wild_boss_escape_cave_exit_venenatis", "loctypes"),
            new GamevalEntry(47156, "WILD_BOSS_ESCAPE_CAVE_EXIT_VETION", "wild_boss_escape_cave_exit_vetion", "loctypes"),
            new GamevalEntry(47157, "WILD_ESCAPECAVE_STALAGMITE01", "wild_escapecave_stalagmite01", "loctypes"),
            new GamevalEntry(47158, "WILD_ESCAPECAVE_STALAGMITE02", "wild_escapecave_stalagmite02", "loctypes"),
            new GamevalEntry(47159, "WILD_ESCAPECAVE_FLOOR_SCRATCH_RIGHT", "wild_escapecave_floor_scratch_right", "loctypes"),
            new GamevalEntry(47160, "WILD_ESCAPECAVE_FLOOR_SCRATCH_LEFT", "wild_escapecave_floor_scratch_left", "loctypes"),
            new GamevalEntry(47161, "WILD_ESCAPECAVE_ROCKSLIDE1", "wild_escapecave_rockslide1", "loctypes"),
            new GamevalEntry(47162, "WILD_ESCAPECAVE_ROCKSLIDE2", "wild_escapecave_rockslide2", "loctypes"),
            new GamevalEntry(47163, "WILD_ESCAPECAVE_ROCKSLIDE3", "wild_escapecave_rockslide3", "loctypes"),
            new GamevalEntry(47164, "WILD_ESCAPECAVE_ROCKSLIDE4", "wild_escapecave_rockslide4", "loctypes"),
            new GamevalEntry(47165, "WILD_ESCAPECAVE_ROCKSLIDE5", "wild_escapecave_rockslide5", "loctypes"),
            new GamevalEntry(47166, "WILD_ESCAPECAVE_ROCKSLIDE6", "wild_escapecave_rockslide6", "loctypes"),
            new GamevalEntry(47167, "CAVEKIT_WEB02_DEFAULT01", "cavekit_web02_default01", "loctypes"),
            new GamevalEntry(47168, "CAVEKIT_WEB02_DEFAULT02", "cavekit_web02_default02", "loctypes"),
            new GamevalEntry(47169, "CAVEKIT_WEB02_DEFAULT02_MIRROR", "cavekit_web02_default02_mirror", "loctypes"),
            new GamevalEntry(47170, "WILD_ESCAPECAVE_DUGUPSOIL_1", "wild_escapecave_dugupsoil_1", "loctypes"),
            new GamevalEntry(47171, "WILD_ESCAPECAVE_DUGUPSOIL_2", "wild_escapecave_dugupsoil_2", "loctypes"),
            new GamevalEntry(47172, "WILD_ESCAPECAVE_DUGUPSOIL_3", "wild_escapecave_dugupsoil_3", "loctypes"),
            new GamevalEntry(47173, "WILD_ESCAPECAVE_VETION_PILLAR01", "wild_escapecave_vetion_pillar01", "loctypes"),
            new GamevalEntry(47174, "WILD_VETION_ENTER_ARENA", "Rubble", "loctypes"),
            new GamevalEntry(47175, "WILD_CAVE_EXIT01", "Cave", "loctypes"),
            new GamevalEntry(47176, "GREYBOX_TOMB_WALL02_DARK01", "greybox_tomb_wall02_dark01", "loctypes"),
            new GamevalEntry(47177, "GREYBOX_TOMB_WALL02_DARK02", "greybox_tomb_wall02_dark02", "loctypes"),
            new GamevalEntry(47178, "HOSDUN_SARACHNIS_ENTRANCE_INSTANCE", "Thick Web", "loctypes"),
            new GamevalEntry(47179, "OSB10_TABLE", "osb10_table", "loctypes"),
            new GamevalEntry(47180, "OSB10_WARMFIRE", "Warmhandz' Fire", "loctypes"),
            new GamevalEntry(47181, "SAILING_BOAT_HULL_GUNPORTS_KANDARIN_3X8_PORT_STERN_UP_WOOD", "sailing_boat_hull_gunports_kandarin_3x8_port_stern_up_wood", "loctypes"),
            new GamevalEntry(47182, "SAILING_BOAT_HULL_GUNPORTS_KANDARIN_3X8_STARBOARD_MIDSHIPS_DOWN_WOOD", "sailing_boat_hull_gunports_kandarin_3x8_starboard_midships_down_wood", "loctypes"),
            new GamevalEntry(47183, "SAILING_BOAT_HULL_GUNPORTS_KANDARIN_3X8_STARBOARD_MIDSHIPS_UP_WOOD", "sailing_boat_hull_gunports_kandarin_3x8_starboard_midships_up_wood", "loctypes"),
            new GamevalEntry(47184, "SAILING_BOAT_HULL_GUNPORTS_KANDARIN_3X8_STARBOARD_STERN_DOWN_WOOD", "sailing_boat_hull_gunports_kandarin_3x8_starboard_stern_down_wood", "loctypes"),
            new GamevalEntry(47185, "SAILING_BOAT_HULL_GUNPORTS_KANDARIN_3X8_STARBOARD_STERN_UP_WOOD", "sailing_boat_hull_gunports_kandarin_3x8_starboard_stern_up_wood", "loctypes"),
            new GamevalEntry(47186, "OSB10_BANNER01_YEAR10", "osb10_banner01_year10", "loctypes"),
            new GamevalEntry(47187, "OSB10_BANNER01_YEAR10_RAISED01", "osb10_banner01_year10_raised01", "loctypes"),
            new GamevalEntry(47188, "OSB10_BALLOONS01_YEAR10", "Birthday Balloons", "loctypes"),
            new GamevalEntry(47189, "OSB10_TOYS01_MIXED10", "Birthday plushies", "loctypes"),
            new GamevalEntry(47190, "OSB10_TOYS01_JAD10", "Birthday plushies", "loctypes"),
            new GamevalEntry(47191, "OSB10_TOYS01_JAD10_SOLO01", "Birthday plushies", "loctypes"),
            new GamevalEntry(47192, "OSB10_TOYS01_STRAYDOG10", "Birthday plushies", "loctypes"),
            new GamevalEntry(47193, "OSB10_TOYS01_STRAYDOG10_SOLO01", "Birthday plushies", "loctypes"),
            new GamevalEntry(47194, "OSB10_TOYS01_GNOMECHILD10", "Birthday plushies", "loctypes"),
            new GamevalEntry(47195, "OSB10_TOYS01_GNOMECHILD10_SOLO01", "Birthday plushies", "loctypes"),
            new GamevalEntry(47196, "SAILING_BOAT_HULL_GUNPORTS_KANDARIN_3X8_PORT_MIDSHIPS_DOWN_OAK", "sailing_boat_hull_gunports_kandarin_3x8_port_midships_down_oak", "loctypes"),
            new GamevalEntry(47197, "SAILING_BOAT_HULL_GUNPORTS_KANDARIN_3X8_PORT_MIDSHIPS_UP_OAK", "sailing_boat_hull_gunports_kandarin_3x8_port_midships_up_oak", "loctypes"),
            new GamevalEntry(47198, "SAILING_BOAT_HULL_GUNPORTS_KANDARIN_3X8_PORT_STERN_DOWN_OAK", "sailing_boat_hull_gunports_kandarin_3x8_port_stern_down_oak", "loctypes"),
            new GamevalEntry(47199, "SAILING_BOAT_HULL_GUNPORTS_KANDARIN_3X8_PORT_STERN_UP_OAK", "sailing_boat_hull_gunports_kandarin_3x8_port_stern_up_oak", "loctypes"),
            new GamevalEntry(47200, "SAILING_BOAT_HULL_GUNPORTS_KANDARIN_3X8_STARBOARD_MIDSHIPS_DOWN_OAK", "sailing_boat_hull_gunports_kandarin_3x8_starboard_midships_down_oak", "loctypes"),
            new GamevalEntry(47201, "SAILING_BOAT_HULL_GUNPORTS_KANDARIN_3X8_STARBOARD_MIDSHIPS_UP_OAK", "sailing_boat_hull_gunports_kandarin_3x8_starboard_midships_up_oak", "loctypes"),
            new GamevalEntry(47202, "OSB10_PARTYROOM_DOORL_NOOP", "osb10_partyroom_doorl_noop", "loctypes"),
            new GamevalEntry(47203, "OSB10_PARTYROOM_DOORR_NOOP", "osb10_partyroom_doorr_noop", "loctypes"),
            new GamevalEntry(47204, "OSB10_CLICKZONE_CTC2", "Crack the Clue II Display", "loctypes"),
            new GamevalEntry(47205, "OSB10_CLICKZONE_MIMIC", "Mimic Display", "loctypes"),
            new GamevalEntry(47206, "OSB10_CLICKZONE_HOSIDIUS", "Hosidius Rework Display", "loctypes"),
            new GamevalEntry(47207, "OSB10_CLICKZONE_FORTHOS", "Forthos Dungeon Display", "loctypes"),
            new GamevalEntry(47208, "OSB10_CLICKZONE_LMS", "LMS Rework Display", "loctypes"),
            new GamevalEntry(47209, "OSB10_FIGURE07_LMS01", "osb10_figure07_lms01", "loctypes"),
            new GamevalEntry(47210, "OSB10_FIGURE07_LMS02", "osb10_figure07_lms02", "loctypes"),
            new GamevalEntry(47211, "OSB10_CLICKZONE_EXILES", "Jormungand Display", "loctypes"),
            new GamevalEntry(47212, "OSB10_CLICKZONE_TWISTEDLEAGUE", "Twisted League Display", "loctypes"),
            new GamevalEntry(47213, "OSB10_FIGURE07_LEAGUE01_TIER01", "osb10_figure07_league01_tier01", "loctypes"),
            new GamevalEntry(47214, "OSB10_FIGURE07_LEAGUE01_TIER02", "osb10_figure07_league01_tier02", "loctypes"),
            new GamevalEntry(47215, "OSB10_FIGURE07_LEAGUE01_TIER03", "osb10_figure07_league01_tier03", "loctypes"),
            new GamevalEntry(47216, "OSB10_FIGURE07_LEAGUE01_TROPHY01", "osb10_figure07_league01_trophy01", "loctypes"),
            new GamevalEntry(47217, "OSB10_CLICKZONE_NIGHTMARE", "The Nightmare of Ashihama Display", "loctypes"),
            new GamevalEntry(47218, "OSB10_NIGHTMARE_PILLAR01", "osb10_nightmare_pillar01", "loctypes"),
            new GamevalEntry(47219, "OSB10_CLICKZONE_PRIFF", "Prifddinas Display", "loctypes"),
            new GamevalEntry(47220, "OSB10_STATUE07_ZALCANO01", "osb10_statue07_zalcano01", "loctypes"),
            new GamevalEntry(47221, "OSB10_STATUE07_HUNLLEF01", "osb10_statue07_hunllef01", "loctypes"),
            new GamevalEntry(47222, "OSB10_FIGURE07_PRIFDDINAS01", "osb10_figure07_prifddinas01", "loctypes"),
            new GamevalEntry(47223, "OSB10_FIGURE07_PRIFDDINAS02", "osb10_figure07_prifddinas02", "loctypes"),
            new GamevalEntry(47224, "OSB10_CLICKZONE_DEATH", "Death Rework Display", "loctypes"),
            new GamevalEntry(47225, "OSB10_CLICKZONE_MAHOGANYHOMES", "Mahogany Homes Display", "loctypes"),
            new GamevalEntry(47226, "OSB10_CLICKZONE_FEROX", "Ferox Enclave Display", "loctypes"),
            new GamevalEntry(47227, "OSB10_CLICKZONE_PORCINE", "Porcine of Interest Display", "loctypes"),
            new GamevalEntry(47228, "OSB10_CLICKZONE_SOULWARS", "Soul Wars Display", "loctypes"),
            new GamevalEntry(47229, "OSB10_STATUE08_SOULWARS01", "osb10_statue08_soulwars01", "loctypes"),
            new GamevalEntry(47230, "OSB10_STATUE08_SOULWARS02", "osb10_statue08_soulwars02", "loctypes"),
            new GamevalEntry(47231, "OSB10_STATUE08_TREE01", "osb10_statue08_tree01", "loctypes"),
            new GamevalEntry(47232, "OSB10_CLICKZONE_DARKMEYER", "Darkmeyer Display", "loctypes"),
            new GamevalEntry(47233, "OSB10_STATUE08_BLISTERWOOD", "osb10_statue08_blisterwood", "loctypes"),
            new GamevalEntry(47234, "OSB10_CLICKZONE_SHADES", "Shades of Mort'ton Rework Display", "loctypes"),
            new GamevalEntry(47235, "OSB10_CLICKZONE_TRAILBLAZERLEAGUE", "Trailblazer League Display", "loctypes"),
            new GamevalEntry(47236, "OSB10_FIGURE07_LEAGUE02_TIER01", "osb10_figure07_league02_tier01", "loctypes"),
            new GamevalEntry(47237, "OSB10_FIGURE07_LEAGUE02_TIER02", "osb10_figure07_league02_tier02", "loctypes"),
            new GamevalEntry(47238, "OSB10_FIGURE07_LEAGUE02_TIER03", "osb10_figure07_league02_tier03", "loctypes"),
            new GamevalEntry(47239, "OSB10_FIGURE07_LEAGUE02_TROPHY01", "osb10_figure07_league02_trophy01", "loctypes"),
            new GamevalEntry(47240, "OSB10_FIGURE07_LEAGUE02_GATEWAY01", "Archway", "loctypes"),
            new GamevalEntry(47241, "OSB10_CLICKZONE_TZHAARKETRAK", "Tzhaar-Ket-Rak Display", "loctypes"),
            new GamevalEntry(47242, "OSB10_CLICKZONE_SHOOTINGSTARS", "Shooting Star Display", "loctypes"),
            new GamevalEntry(47243, "OSB10_CLICKZONE_TEMPOROSS", "Tempoross Display", "loctypes"),
            new GamevalEntry(47244, "OSB10_CLICKZONE_BIM", "Below Ice Mountain Display", "loctypes"),
            new GamevalEntry(47245, "OSB10_CLICKZONE_COMBATACHIEVEMENTS", "Combat Achievements Display", "loctypes"),
            new GamevalEntry(47246, "OSB10_CLICKZONE_KINGDOMDIVIDED", "A Kingdom Divided Display", "loctypes"),
            new GamevalEntry(47247, "OSB10_STATUE09_XAMPHUR01", "osb10_statue09_xamphur01", "loctypes"),
            new GamevalEntry(47248, "OSB10_STATUE09_JOY01", "osb10_statue09_joy01", "loctypes"),
            new GamevalEntry(47249, "OSB10_FIGURE09_WARRIOR01", "osb10_figure09_warrior01", "loctypes"),
            new GamevalEntry(47250, "OSB10_FIGURE09_WIZARD01", "osb10_figure09_wizard01", "loctypes"),
            new GamevalEntry(47251, "OSB10_CLICKZONE_DEADMANREBORN", "Deadman: Reborn Display", "loctypes"),
            new GamevalEntry(47252, "OSB10_FIGURE09_DEADMAN01", "osb10_figure09_deadman01", "loctypes"),
            new GamevalEntry(47253, "OSB10_FIGURE09_DEADMAN02", "osb10_figure09_deadman02", "loctypes"),
            new GamevalEntry(47254, "OSB10_CLICKZONE_GIM", "Group Ironman Display", "loctypes"),
            new GamevalEntry(47255, "OSB10_CLICKZONE_NEX", "Nex Display", "loctypes"),
            new GamevalEntry(47256, "OSB10_NEX_BACKGROUND", "osb10_nex_background", "loctypes"),
            new GamevalEntry(47257, "OSB10_CLICKZONE_SHATTEREDLEAGUE", "Shattered League Display", "loctypes"),
            new GamevalEntry(47258, "OSB10_FIGURE07_LEAGUE03_TIER01", "osb10_figure07_league03_tier01", "loctypes"),
            new GamevalEntry(47259, "OSB10_FIGURE07_LEAGUE03_TIER02", "osb10_figure07_league03_tier02", "loctypes"),
            new GamevalEntry(47260, "OSB10_FIGURE07_LEAGUE03_SAGE01", "osb10_figure07_league03_sage01", "loctypes"),
            new GamevalEntry(47261, "OSB10_FIGURE07_LEAGUE03_TROPHY01", "osb10_figure07_league03_trophy01", "loctypes"),
            new GamevalEntry(47262, "OSB10_FIGURE09_GOBLIN01", "A Goblin", "loctypes"),
            new GamevalEntry(47263, "OSB10_FIGURE09_GOBLIN02", "A Goblin", "loctypes"),
            new GamevalEntry(47264, "OSB10_FIGURE09_GOBLIN03", "A Goblin", "loctypes"),
            new GamevalEntry(47265, "OSB10_CLICKZONE_PHOSANI", "Phosani's Nightmare Display", "loctypes"),
            new GamevalEntry(47266, "OSB10_CLICKZONE_MALEDICTUS", "Revenant Maledictus Display", "loctypes"),
            new GamevalEntry(47267, "OSB10_CLICKZONE_GOTR", "Guardians of the Rift Display", "loctypes"),
            new GamevalEntry(47268, "OSB10_CLICKZONE_GIANTSFOUNDRY", "Giants' Foundry Display", "loctypes"),
            new GamevalEntry(47269, "OSB10_CLICKZONE_EMIRSARENA", "Emir's Arena Display", "loctypes"),
            new GamevalEntry(47270, "OSB10_FIGURE10_PVP01", "osb10_figure10_pvp01", "loctypes"),
            new GamevalEntry(47271, "OSB10_FIGURE10_PVP02", "osb10_figure10_pvp02", "loctypes"),
            new GamevalEntry(47272, "OSB10_CLICKZONE_UNRANKEDGIM", "Unranked Group Ironman Display", "loctypes"),
            new GamevalEntry(47273, "OSB10_CLICKZONE_MUSPAH", "Phantom Muspah Display", "loctypes"),
            new GamevalEntry(47274, "OSB10_CLICKZONE_QUESTSPEEDRUNNING", "Quest Speedrunning Display", "loctypes"),
            new GamevalEntry(47275, "OSB10_FIGURE10_QUESTSPEEDRUNNING01", "osb10_figure10_questspeedrunning01", "loctypes"),
            new GamevalEntry(47276, "OSB10_FIGURE10_QUESTSPEEDRUNNING02", "osb10_figure10_questspeedrunning02", "loctypes"),
            new GamevalEntry(47277, "OSB10_FIGURE10_QUESTSPEEDRUNNING03", "osb10_figure10_questspeedrunning03", "loctypes"),
            new GamevalEntry(47278, "OSB10_CLICKZONE_WBR", "Wilderness Boss Display", "loctypes"),
            new GamevalEntry(47279, "OSB10_STATUE10_CALLISTO01", "osb10_statue10_callisto01", "loctypes"),
            new GamevalEntry(47280, "OSB10_STATUE10_VETION01", "osb10_statue10_vetion01", "loctypes"),
            new GamevalEntry(47281, "OSB10_STATUE10_VENENATIS01", "osb10_statue10_venenatis01", "loctypes"),
            new GamevalEntry(47282, "OSB10_CLICKZONE_TOA", "Tombs of Amascut Display", "loctypes"),
            new GamevalEntry(47283, "OSB10_STATUE10_AMASCUT01", "osb10_statue10_amascut01", "loctypes"),
            new GamevalEntry(47284, "OSB10_STATUE10_WARDEN01", "osb10_statue10_warden01", "loctypes"),
            new GamevalEntry(47285, "OSB10_STATUE10_WARDEN02", "osb10_statue10_warden02", "loctypes"),
            new GamevalEntry(47286, "OSB10_STATUE10_AKKHA01", "osb10_statue10_akkha01", "loctypes"),
            new GamevalEntry(47287, "OSB10_STATUE10_BABA01", "osb10_statue10_baba01", "loctypes"),
            new GamevalEntry(47288, "OSB10_STATUE10_KEPHRI01", "osb10_statue10_kephri01", "loctypes"),
            new GamevalEntry(47289, "OSB10_STATUE10_ZEBAK01", "osb10_statue10_zebak01", "loctypes"),
            new GamevalEntry(47290, "WALLKIT_MUSEUM01_DEFAULT01", "wallkit_museum01_default01", "loctypes"),
            new GamevalEntry(47291, "WALLKIT_MUSEUM01_DEFAULT01_DARK01", "wallkit_museum01_default01_dark01", "loctypes"),
            new GamevalEntry(47292, "WALLKIT_MUSEUM01_TRANSITION01_WHITE_LEFT", "wallkit_museum01_transition01_white_left", "loctypes"),
            new GamevalEntry(47293, "WALLKIT_MUSEUM01_TRANSITION01_WHITE_RIGHT", "wallkit_museum01_transition01_white_right", "loctypes"),
            new GamevalEntry(47294, "WALLKIT_MUSEUM01_PLAIN01_WHITE_MIDDLE", "wallkit_museum01_plain01_white_middle", "loctypes"),
            new GamevalEntry(47295, "WALLKIT_MUSEUM01_TRANSITION01_BLACK01_LEFT", "wallkit_museum01_transition01_black01_left", "loctypes"),
            new GamevalEntry(47296, "WALLKIT_MUSEUM01_TRANSITION01_BLACK01_RIGHT", "wallkit_museum01_transition01_black01_right", "loctypes"),
            new GamevalEntry(47297, "WALLKIT_MUSEUM01_PLAIN01_BLACK01_MIDDLE", "wallkit_museum01_plain01_black01_middle", "loctypes"),
            new GamevalEntry(47298, "WALLKIT_MUSEUM01_TRANSITION01_BLACK02_LEFT", "wallkit_museum01_transition01_black02_left", "loctypes"),
            new GamevalEntry(47299, "WALLKIT_MUSEUM01_TRANSITION01_BLACK02_RIGHT", "wallkit_museum01_transition01_black02_right", "loctypes"),
            new GamevalEntry(47300, "WALLKIT_MUSEUM01_PLAIN01_BLACK02_MIDDLE", "wallkit_museum01_plain01_black02_middle", "loctypes"),
            new GamevalEntry(47301, "WALLKIT_MUSEUM01_UPPER01", "wallkit_museum01_upper01", "loctypes"),
            new GamevalEntry(47302, "WALLKIT_MUSEUM01_UPPER01_DARK01", "wallkit_museum01_upper01_dark01", "loctypes"),
            new GamevalEntry(47303, "WALLKIT_MUSEUM01_TRANSITION02_WHITE_LEFT", "wallkit_museum01_transition02_white_left", "loctypes"),
            new GamevalEntry(47304, "WALLKIT_MUSEUM01_TRANSITION02_WHITE_RIGHT", "wallkit_museum01_transition02_white_right", "loctypes"),
            new GamevalEntry(47305, "WALLKIT_MUSEUM01_PLAIN02_WHITE_MIDDLE", "wallkit_museum01_plain02_white_middle", "loctypes"),
            new GamevalEntry(47306, "WALLKIT_MUSEUM01_TRANSITION02_BLACK01_LEFT", "wallkit_museum01_transition02_black01_left", "loctypes"),
            new GamevalEntry(47307, "WALLKIT_MUSEUM01_TRANSITION02_BLACK01_RIGHT", "wallkit_museum01_transition02_black01_right", "loctypes"),
            new GamevalEntry(47308, "WALLKIT_MUSEUM01_PLAIN02_BLACK01_MIDDLE", "wallkit_museum01_plain02_black01_middle", "loctypes"),
            new GamevalEntry(47309, "WALLKIT_MUSEUM01_TRANSITION02_BLACK02_LEFT", "wallkit_museum01_transition02_black02_left", "loctypes"),
            new GamevalEntry(47310, "WALLKIT_MUSEUM01_TRANSITION02_BLACK02_RIGHT", "wallkit_museum01_transition02_black02_right", "loctypes"),
            new GamevalEntry(47311, "WALLKIT_MUSEUM01_PLAIN02_BLACK02_MIDDLE", "wallkit_museum01_plain02_black02_middle", "loctypes"),
            new GamevalEntry(47312, "WALLKIT_MUSEUM01_TOP01", "wallkit_museum01_top01", "loctypes"),
            new GamevalEntry(47313, "WALLKIT_MUSEUM01_PILLAR01", "wallkit_museum01_pillar01", "loctypes"),
            new GamevalEntry(47314, "OSB10_SPIRAL_STAIRS_B1", "Climb-down", "loctypes"),
            new GamevalEntry(47315, "OSB10_SPIRAL_STAIRS_B2", "Staircase", "loctypes"),
            new GamevalEntry(47316, "OSB5_PASSAGEWAY_NOOP", "Old passageway", "loctypes"),
            new GamevalEntry(47317, "SEATING_BENCH01_MUSEUM01", "Bench", "loctypes"),
            new GamevalEntry(47318, "SEATING_BENCH01_MUSEUM02", "Bench", "loctypes"),
            new GamevalEntry(47319, "SPOTLIGHT_MUSEUM01_ORANGE01", "Spotlight", "loctypes"),
            new GamevalEntry(47320, "BANNER_BIRTHDAY01_DEFAULT01", "Banner", "loctypes"),
            new GamevalEntry(47321, "BANNER_BIRTHDAY01_DEFAULT02", "Banner", "loctypes"),
            new GamevalEntry(47322, "PILLAR_MUSEUM01_TALL01", "pillar_museum01_tall01", "loctypes"),
            new GamevalEntry(47323, "SAILING_BOAT_HULL_GUNPORTS_KANDARIN_3X8_STARBOARD_STERN_DOWN_OAK", "sailing_boat_hull_gunports_kandarin_3x8_starboard_stern_down_oak", "loctypes"),
            new GamevalEntry(47324, "UNGAEL_CRATER_ENTRANCE_INSTANCE_LEAVE", "Ice chunks", "loctypes"),
            new GamevalEntry(47325, "UNGAEL_CRATER_EXIT_INSTANCE_LEAVE", "ungael_crater_exit_instance_leave", "loctypes"),
            new GamevalEntry(47326, "DS2_LITHKREN_DUNGEON_STAIRS_LOWER_NOOP", "Staircase", "loctypes"),
            new GamevalEntry(47327, "DS2_LITHKREN_DUNGEON_VAULT_DOOR_KEYLESS_NOOP", "Ancient Doors", "loctypes"),
            new GamevalEntry(47328, "DS2_LITHKREN_DUNGEON_VAULT_DOOR_COMPLETE_NOOP", "Ancient Doors", "loctypes"),
            new GamevalEntry(47329, "DS2_LITHKREN_DUNGEON_VAULT_DOOR_BROKEN_NOOP", "Broken Doors", "loctypes"),
            new GamevalEntry(47330, "DS2_LITHKREN_VAULT_DOOR_FIXED_NOOP", "Ancient Doors", "loctypes"),
            new GamevalEntry(47331, "DS2_VIKING_SHIP_HAMMERS_NOOP", "Hammers", "loctypes"),
            new GamevalEntry(47332, "DS2_VIKING_SHIP_WATER_NOOP", "Water containers", "loctypes"),
            new GamevalEntry(47333, "DS2_VIKING_SHIP_PASTE_NOOP", "Swamp paste", "loctypes"),
            new GamevalEntry(47334, "DS2_VIKING_SHIP_POTIONS_NOOP", "Potions", "loctypes"),
            new GamevalEntry(47335, "SHIPRAIL_BROKEN", "shiprail_broken", "loctypes"),
            new GamevalEntry(47336, "TOB_WALKWAY_VERZIK_BARRIER_OP", "Barrier", "loctypes"),
            new GamevalEntry(47337, "TOA_DUMMY_LOOT_LOC_FOR_LOOTTRACKER", "Tombs of Amascut", "loctypes"),
            new GamevalEntry(47338, "TOB_LOOTTRACKER_DUMMY_LOC", "Theatre of Blood", "loctypes"),
            new GamevalEntry(47339, "YOMMITREE_DUMMY_FOR_LOOTTRACKER", "Yommi tree", "loctypes"),
            new GamevalEntry(47340, "BH_ARENA_ENTRANCE", "2'7 Enter", "loctypes"),
            new GamevalEntry(47341, "BH_ARENA_ENTRANCE_BOTTOM01", "Arena", "loctypes"),
            new GamevalEntry(47342, "BH_ARENA_ENTRANCE_MIDDLE01", "Arena", "loctypes"),
            new GamevalEntry(47343, "BH_ARENA_ENTRANCE_TOP01", "Arena", "loctypes"),
            new GamevalEntry(47344, "BH_ARENA_EXIT", "Arena", "loctypes"),
            new GamevalEntry(47345, "BH_BANKCHEST", "Bank chest", "loctypes"),
            new GamevalEntry(47346, "BH_PORTAL_ENTER", "Bounty Hunter portal", "loctypes"),
            new GamevalEntry(47347, "BH_PORTAL_EXIT", "Bounty Hunter portal", "loctypes"),
            new GamevalEntry(47348, "INVISIBLE_TYPE8_BLOCKING_SIZE2", "invisible_type8_blocking_size2", "loctypes"),
            new GamevalEntry(47349, "INVISIBLE_TYPE8_BLOCKING_SIZE2_ACTIVE", "T Nothing", "loctypes"),
            new GamevalEntry(47350, "HORROR_LIGHTHOUSE_SPIRALSTAIRS_MIDDLE_INACTIVE", "horror_lighthouse_spiralstairs_middle_inactive", "loctypes"),
            new GamevalEntry(47351, "CONTACT_CHAIR4_BIG", "Chair", "loctypes"),
            new GamevalEntry(47352, "CONTACT_BOOK_TABLE", "Table", "loctypes"),
            new GamevalEntry(47353, "QUEST_START_ICON_DESERTTREASURE2", "quest_start_icon_deserttreasure2", "loctypes"),
            new GamevalEntry(47354, "PRISON_BUCKET_NOOP_ALT", "Bucket", "loctypes"),
            new GamevalEntry(47355, "CAVE_MOUNTAIN01_DEFAULT01", "Cave", "loctypes"),
            new GamevalEntry(47356, "CAVE_MOUNTAIN01_DEFAULT02", "Cave", "loctypes"),
            new GamevalEntry(47357, "CAVE_MOUNTAIN01_WATER01", "Cave", "loctypes"),
            new GamevalEntry(47358, "CAVE_MOUNTAIN01_WATER02", "Cave", "loctypes"),
            new GamevalEntry(47359, "ROCKSLIDE_CLIFF02_LARGE01", "Rockslide", "loctypes"),
            new GamevalEntry(47360, "ROCKSLIDE_CLIFF02_LARGE02", "Rockslide", "loctypes"),
            new GamevalEntry(47361, "ROCKSLIDE_CLIFF02_SMALL01", "Rockslide", "loctypes"),
            new GamevalEntry(47362, "ROCKSLIDE_CLIFF02_SMALL02", "Rockslide", "loctypes"),
            new GamevalEntry(47363, "ROCKSLIDE_CLIFF02_SOIL01", "rockslide_cliff02_soil01", "loctypes"),
            new GamevalEntry(47364, "ROCKSLIDE_CLIFF02_SOIL02", "rockslide_cliff02_soil02", "loctypes"),
            new GamevalEntry(47365, "ROCKSLIDE_CLIFF02_SOIL03", "rockslide_cliff02_soil03", "loctypes"),
            new GamevalEntry(47366, "ROCKSLIDE_SNOW01_LARGE01", "Rockslide", "loctypes"),
            new GamevalEntry(47367, "ROCKSLIDE_SNOW01_LARGE02", "Rockslide", "loctypes"),
            new GamevalEntry(47368, "ROCKSLIDE_SNOW01_SMALL01", "Rockslide", "loctypes"),
            new GamevalEntry(47369, "ROCKSLIDE_SNOW01_SMALL02", "Rockslide", "loctypes"),
            new GamevalEntry(47370, "GROUNDCOVER_PLANT5_WITHERED", "Plant", "loctypes"),
            new GamevalEntry(47371, "GROUNDCOVER_PLANT5_ROTTEN", "Plant", "loctypes"),
            new GamevalEntry(47372, "TREE_REDWOOD_DEFAULT01", "Redwood tree", "loctypes"),
            new GamevalEntry(47373, "TREE_REDWOOD_DEFAULT02", "Redwood tree", "loctypes"),
            new GamevalEntry(47374, "TREE_REDWOOD_DEFAULT03", "Redwood tree", "loctypes"),
            new GamevalEntry(47375, "TREE_REDWOOD_ICON01", "tree_redwood_icon01", "loctypes"),
            new GamevalEntry(47376, "TREE_REDWOOD_ICON02", "tree_redwood_icon02", "loctypes"),
            new GamevalEntry(47377, "TREE_REDWOOD_ICON03", "tree_redwood_icon03", "loctypes"),
            new GamevalEntry(47378, "TREE_REDWOOD_ICON04", "tree_redwood_icon04", "loctypes"),
            new GamevalEntry(47379, "GREYBOX_SEATING_CHAIR01", "Chair", "loctypes"),
            new GamevalEntry(47380, "GREYBOX_SEATING_STOOL01", "Stool", "loctypes"),
            new GamevalEntry(47381, "GREYBOX_SEATING_THRONE01", "Throne", "loctypes"),
            new GamevalEntry(47382, "GREYBOX_STORAGE_CUPBOARD01", "Cupboard", "loctypes"),
            new GamevalEntry(47383, "GREYBOX_STORAGE_CUPBOARD02", "Cupboard", "loctypes"),
            new GamevalEntry(47384, "GREYBOX_STORAGE_SHELVES01", "Shelves", "loctypes"),
            new GamevalEntry(47385, "GREYBOX_STORAGE_RACK01", "Hat stand", "loctypes"),
            new GamevalEntry(47386, "GREYBOX_STORAGE_RACK02", "Rack", "loctypes"),
            new GamevalEntry(47387, "GREYBOX_STORAGE_BARREL01", "Barrel", "loctypes"),
            new GamevalEntry(47388, "GREYBOX_STORAGE_CABINET01", "Cabinet", "loctypes"),
            new GamevalEntry(47389, "GREYBOX_STORAGE_CABINET02", "Cabinet", "loctypes"),
            new GamevalEntry(47390, "GREYBOX_STORAGE_VIAL01", "Giant vial", "loctypes"),
            new GamevalEntry(47391, "GREYBOX_STORAGE_BOOKS01", "Books", "loctypes"),
            new GamevalEntry(47392, "GREYBOX_UTILITY_STOVE01", "Range", "loctypes"),
            new GamevalEntry(47393, "GREYBOX_UTILITY_SINK01", "Sink", "loctypes"),
            new GamevalEntry(47394, "GREYBOX_UTILITY_HEARTH01", "Fireplace", "loctypes"),
            new GamevalEntry(47395, "GREYBOX_FURNITURE_BED01", "Bed", "loctypes"),
            new GamevalEntry(47396, "GREYBOX_FURNITURE_BED02", "Bed", "loctypes"),
            new GamevalEntry(47397, "FAI_VARROCK_SHELF_HAIRDRESSER01", "Shelves", "loctypes"),
            new GamevalEntry(47398, "FAI_VARROCK_SHELF_HAIRDRESSER02", "Shelves", "loctypes"),
            new GamevalEntry(47399, "FAI_VARROCK_WALLSHELF_HAIRDRESSER01", "fai_varrock_wallshelf_hairdresser01", "loctypes"),
            new GamevalEntry(47400, "FAI_VARROCK_WALLSHELF_HAIRDRESSER02", "Shelf", "loctypes"),
            new GamevalEntry(47401, "FAI_VARROCK_WOODEN_TABLE_HAIRDRESSER01", "Table", "loctypes"),
            new GamevalEntry(47402, "FAI_VARROCK_FABRIC_RACK_HAIRDRESSER01", "Fabric rolls", "loctypes"),
            new GamevalEntry(47403, "FAI_VARROCK_FLOOR_CLOTH_HAIRDRESSER01", "Cloth", "loctypes"),
            new GamevalEntry(47404, "FAI_VARROCK_HAIRCLIPPINGS01", "fai_varrock_hairclippings01", "loctypes"),
            new GamevalEntry(47405, "FAI_VARROCK_HAIRCLIPPINGS02", "fai_varrock_hairclippings02", "loctypes"),
            new GamevalEntry(47406, "FAI_VARROCK_WOODEN_TABLE_HAIRDRESSER02", "Table", "loctypes"),
            new GamevalEntry(47407, "FAI_VARROCK_POSTER_HAIRDRESSER02", "Hairstyles Poster", "loctypes"),
            new GamevalEntry(47408, "FAI_VARROCK_POSTER_HAIRDRESSER01", "Hairstyles Poster", "loctypes"),
            new GamevalEntry(47409, "FAI_CAGE_PARROT01_DEFAULT01", "Rio the Parrot", "loctypes"),
            new GamevalEntry(47410, "FAI_VARROCK_PORTRAIT_HAIRDRESSER01", "Portraits", "loctypes"),
            new GamevalEntry(47411, "FAI_VARROCK_PORTRAIT_HAIRDRESSER02", "Portraits", "loctypes"),
            new GamevalEntry(47412, "FAI_VARROCK_HAIRDRESSER_SIGN", "fai_varrock_hairdresser_sign", "loctypes"),
            new GamevalEntry(47413, "FAI_VARROCK_HAIRDRESSER_WELCOME_MAT", "fai_varrock_hairdresser_welcome_mat", "loctypes"),
            new GamevalEntry(47414, "FAI_VARROCK_SEPIA_PAINTING1_DARK", "Painting", "loctypes"),
            new GamevalEntry(47415, "FAI_VARROCK_TABLE_HAIRDRESSER01", "Vanity dresser", "loctypes"),
            new GamevalEntry(47416, "FAI_VARROCK_TABLE_HAIRDRESSER02", "Vanity dresser", "loctypes"),
            new GamevalEntry(47417, "FAI_VARROCK_CHAIR_HAIRDRESSER01", "Chair", "loctypes"),
            new GamevalEntry(47418, "FAI_VARROCK_SINGLE_BED_ORANGE02", "Bed", "loctypes"),
            new GamevalEntry(47419, "RAIDS_BANK_CHEST_LOBBY", "Bank chest", "loctypes"),
            new GamevalEntry(47420, "RAIDS_BANK_CHEST_LOBBY_WORKING", "Bank chest", "loctypes"),
            new GamevalEntry(47421, "BH_PORTAL_FLOOR", "bh_portal_floor", "loctypes"),
            new GamevalEntry(47422, "BH_PORTAL_STAIRS", "bh_portal_stairs", "loctypes"),
            new GamevalEntry(47423, "BH_PORTAL_STAIRS_TRIM", "bh_portal_stairs_trim", "loctypes"),
            new GamevalEntry(47424, "BH_PORTAL_SKULLS01", "bh_portal_skulls01", "loctypes"),
            new GamevalEntry(47425, "BH_PORTAL_SKULLS02", "bh_portal_skulls02", "loctypes"),
            new GamevalEntry(47426, "BH_PORTAL_FLOATING_SKULL01", "Bounty Hunter portal", "loctypes"),
            new GamevalEntry(47427, "BH_PORTAL_FLOATING_SKULL02", "Bounty Hunter portal", "loctypes"),
            new GamevalEntry(47428, "BH_PORTAL_FLOATING_SKULL03", "Bounty Hunter portal", "loctypes"),
            new GamevalEntry(47429, "BH_PORTAL_FLOATING_SKULL04", "Bounty Hunter portal", "loctypes"),
            new GamevalEntry(47430, "BH_FALLOFF1", "bh_falloff1", "loctypes"),
            new GamevalEntry(47431, "BH_FALLOFF5", "bh_falloff5", "loctypes"),
            new GamevalEntry(47432, "BH_FALLOFF13", "bh_falloff13", "loctypes"),
            new GamevalEntry(47433, "BH_FALLOFF14", "bh_falloff14", "loctypes"),
            new GamevalEntry(47434, "BH_FALLOFF_11", "bh_falloff_11", "loctypes"),
            new GamevalEntry(47435, "BH_FALLOFF_12", "bh_falloff_12", "loctypes"),
            new GamevalEntry(47436, "FLOORKIT_SUMMONING01_NORTHEAST01", "floorkit_summoning01_northeast01", "loctypes"),
            new GamevalEntry(47437, "FLOORKIT_SUMMONING01_NORTHWEST01", "floorkit_summoning01_northwest01", "loctypes"),
            new GamevalEntry(47438, "FLOORKIT_SUMMONING01_SOUTHEAST01", "floorkit_summoning01_southeast01", "loctypes"),
            new GamevalEntry(47439, "FLOORKIT_SUMMONING01_SOUTHWEST01", "floorkit_summoning01_southwest01", "loctypes"),
            new GamevalEntry(47440, "FLOORKIT_SUMMONING01_NORTH01", "floorkit_summoning01_north01", "loctypes"),
            new GamevalEntry(47441, "FLOORKIT_SUMMONING01_NORTHEAST02", "floorkit_summoning01_northeast02", "loctypes"),
            new GamevalEntry(47442, "FLOORKIT_SUMMONING01_NORTHWEST02", "floorkit_summoning01_northwest02", "loctypes"),
            new GamevalEntry(47443, "FLOORKIT_SUMMONING01_SOUTH01", "floorkit_summoning01_south01", "loctypes"),
            new GamevalEntry(47444, "FLOORKIT_SUMMONING01_SOUTHEAST02", "floorkit_summoning01_southeast02", "loctypes"),
            new GamevalEntry(47445, "FLOORKIT_SUMMONING01_SOUTHWEST02", "floorkit_summoning01_southwest02", "loctypes"),
            new GamevalEntry(47446, "DECO_CANDLES01_RED", "Candles", "loctypes"),
            new GamevalEntry(47447, "DECO_CANDLES02_RED", "Candles", "loctypes"),
            new GamevalEntry(47448, "DECO_CANDLES03_RED", "Candles", "loctypes"),
            new GamevalEntry(47449, "BH_BARREL_EXPLODED", "Barrel", "loctypes"),
            new GamevalEntry(47450, "BH_CRANE", "Crane", "loctypes"),
            new GamevalEntry(47451, "BH_PORTCULLIS", "Portcullis", "loctypes"),
            new GamevalEntry(47452, "BH_CURTAINS", "Drapes", "loctypes"),
            new GamevalEntry(47453, "BH_PRISON_DOOR_INACTIVE", "bh_prison_door_inactive", "loctypes"),
            new GamevalEntry(47454, "BH_BASALT_ICON", "bh_basalt_icon", "loctypes"),
            new GamevalEntry(47455, "BH_ICESLIDE1", "Ice chunks", "loctypes"),
            new GamevalEntry(47456, "BH_ICESLIDE2", "Ice chunks", "loctypes"),
            new GamevalEntry(47457, "BH_ICESLIDE3", "Ice chunks", "loctypes"),
            new GamevalEntry(47458, "BH_ICESLIDE4", "Ice chunks", "loctypes"),
            new GamevalEntry(47459, "BH_ICESLIDE5", "Ice chunks", "loctypes"),
            new GamevalEntry(47460, "BH_ICESLIDE6", "Ice chunks", "loctypes"),
            new GamevalEntry(47461, "BH_COFFER_CHEST", "Coffer", "loctypes"),
            new GamevalEntry(47462, "WILD_VETION_FLAG02", "wild_vetion_flag02", "loctypes"),
            new GamevalEntry(47463, "WILD_VETION_FLAG03", "wild_vetion_flag03", "loctypes"),
            new GamevalEntry(47464, "WILDY_HUB_WALL_ARCH", "wildy_hub_wall_arch", "loctypes"),
            new GamevalEntry(47465, "WILDY_HUB_WALL_ARCH_MIRROR", "wildy_hub_wall_arch_mirror", "loctypes"),
            new GamevalEntry(47466, "WILDY_HUB_WALL_HILLFILL_01", "wildy_hub_wall_hillfill_01", "loctypes"),
            new GamevalEntry(47467, "WILDY_HUB_WALL_HILLFILL_01_M", "wildy_hub_wall_hillfill_01_m", "loctypes"),
            new GamevalEntry(47468, "WILDY_HUB_WALL_HILLFILL_02", "wildy_hub_wall_hillfill_02", "loctypes"),
            new GamevalEntry(47469, "WILDY_HUB_WALL_HILLFILL_02_M", "wildy_hub_wall_hillfill_02_m", "loctypes"),
            new GamevalEntry(47470, "PRIDE23_FLOWERS_FULL01", "Flowerbed", "loctypes"),
            new GamevalEntry(47471, "PRIDE23_FLOWERS_EDGE01", "Flowerbed", "loctypes"),
            new GamevalEntry(47472, "PRIDE23_FLOWERS_CORNER01", "Flowerbed", "loctypes"),
            new GamevalEntry(47473, "PRIDE23_FLOWERS_SCATTER01", "Flowerbed", "loctypes"),
            new GamevalEntry(47474, "PRIDE23_FLOWERS_SCATTER02", "Flowerbed", "loctypes"),
            new GamevalEntry(47475, "PRIDE23_FLOWERS_PETALS01", "pride23_flowers_petals01", "loctypes"),
            new GamevalEntry(47476, "PRIDE23_FLOWERS_PETALS02", "pride23_flowers_petals02", "loctypes"),
            new GamevalEntry(47477, "PRIDE23_FLOWERS_PETALS03", "pride23_flowers_petals03", "loctypes"),
            new GamevalEntry(47478, "PRIDE23_FLOWERS_PETALS04", "pride23_flowers_petals04", "loctypes"),
            new GamevalEntry(47479, "PRIDE23_TABLE_MESSY01", "Table", "loctypes"),
            new GamevalEntry(47480, "PRIDE23_TABLE_MESSY02", "Table", "loctypes"),
            new GamevalEntry(47481, "FORESTRY_POH_BEEHIVE01_ROT2", "Beehive", "loctypes"),
            new GamevalEntry(47482, "GATHERING_EVENT_RISING_ROOTS", "Tree roots", "loctypes"),
            new GamevalEntry(47483, "GATHERING_EVENT_RISING_ROOTS_SPECIAL", "Anima-infused Tree roots", "loctypes"),
            new GamevalEntry(47484, "GATHERING_EVENT_SAPLING_1X1", "Struggling sapling", "loctypes"),
            new GamevalEntry(47485, "GATHERING_EVENT_SAPLING_WITHERING_1X1", "Struggling sapling", "loctypes"),
            new GamevalEntry(47486, "GATHERING_EVENT_SAPLING_SAVED_1X1", "Thriving sapling", "loctypes"),
            new GamevalEntry(47487, "GATHERING_EVENT_SAPLING_2X2", "Struggling sapling", "loctypes"),
            new GamevalEntry(47488, "GATHERING_EVENT_SAPLING_WITHERING_2X2", "Struggling sapling", "loctypes"),
            new GamevalEntry(47489, "GATHERING_EVENT_SAPLING_SAVED_2X2", "Thriving sapling", "loctypes"),
            new GamevalEntry(47490, "GATHERING_EVENT_SAPLING_3X3", "Struggling sapling", "loctypes"),
            new GamevalEntry(47491, "GATHERING_EVENT_SAPLING_WITHERING_3X3", "Struggling sapling", "loctypes"),
            new GamevalEntry(47492, "GATHERING_EVENT_SAPLING_SAVED_3X3", "Thriving sapling", "loctypes"),
            new GamevalEntry(47493, "GATHERING_EVENT_SAPLING_INGREDIENT_1", "Rotting leaves", "loctypes"),
            new GamevalEntry(47494, "GATHERING_EVENT_SAPLING_INGREDIENT_2", "Green leaves", "loctypes"),
            new GamevalEntry(47495, "GATHERING_EVENT_SAPLING_INGREDIENT_3", "Droppings", "loctypes"),
            new GamevalEntry(47496, "GATHERING_EVENT_SAPLING_INGREDIENT_4A", "Wild mushrooms", "loctypes"),
            new GamevalEntry(47497, "GATHERING_EVENT_SAPLING_INGREDIENT_4B", "Wild mushrooms", "loctypes"),
            new GamevalEntry(47498, "GATHERING_EVENT_SAPLING_INGREDIENT_4C", "Wild mushrooms", "loctypes"),
            new GamevalEntry(47499, "GATHERING_EVENT_SAPLING_INGREDIENT_5", "Splintered bark", "loctypes"),
            new GamevalEntry(47500, "FORESTRY_SHOP_ICON", "forestry_shop_icon", "loctypes"),
            new GamevalEntry(47501, "CHISEL", "Chisel", "loctypes"),
            new GamevalEntry(47502, "BARREL_TAP", "Barrel", "loctypes"),
            new GamevalEntry(47503, "CAVEKIT_WEB01_FLOOR02_LOW", "cavekit_web01_floor02_low", "loctypes"),
            new GamevalEntry(47504, "SLUG2_ROWBOAT_BROKEN_ONLAND2_INACTIVE", "slug2_rowboat_broken_onland2_inactive", "loctypes"),
            new GamevalEntry(47505, "SOTN_ASSASSIN_SMOKE_DANGEROUS", "Smoke Cloud", "loctypes"),
            new GamevalEntry(47506, "GHORROCK_STONE01_DARKER", "ghorrock_stone01_darker", "loctypes"),
            new GamevalEntry(47507, "GHORROCK_STONE01_SNOW01_HOLE_1", "ghorrock_stone01_snow01_hole_1", "loctypes"),
            new GamevalEntry(47508, "GHORROCK_STONE01_SNOW01_HOLE_2", "ghorrock_stone01_snow01_hole_2", "loctypes"),
            new GamevalEntry(47509, "GHORROCK_STONE01_SNOW01_DARKER", "ghorrock_stone01_snow01_darker", "loctypes"),
            new GamevalEntry(47510, "GHORROCK_STONE01_PILLAR03", "Pillar", "loctypes"),
            new GamevalEntry(47511, "GHORROCK_STONE01_PILLAR04", "ghorrock_stone01_pillar04", "loctypes"),
            new GamevalEntry(47512, "GHORROCK_STONE01_PILLAR05", "ghorrock_stone01_pillar05", "loctypes"),
            new GamevalEntry(47513, "GHORROCK_STONE01_PILLAR06", "ghorrock_stone01_pillar06", "loctypes"),
            new GamevalEntry(47514, "GHORROCK_STONE01_PILLAR05_MIRROR", "ghorrock_stone01_pillar05_mirror", "loctypes"),
            new GamevalEntry(47515, "GHORROCK_STONE01_SNOW01_FALLOFF_STRAIGHT_DARKER", "ghorrock_stone01_snow01_falloff_straight_darker", "loctypes"),
            new GamevalEntry(47516, "GHORROCK_STONE01_SNOW01_FALLOFF_STRAIGHT_END_DARKER", "ghorrock_stone01_snow01_falloff_straight_end_darker", "loctypes"),
            new GamevalEntry(47517, "GHORROCK_STONE01_SNOW01_FALLOFF_STRAIGHT_END_MIRROR_DARKER", "ghorrock_stone01_snow01_falloff_straight_end_mirror_darker", "loctypes"),
            new GamevalEntry(47518, "GHORROCK_STONE01_SNOW01_FALLOFF_OUTSIDE_CORNER_DARKER", "ghorrock_stone01_snow01_falloff_outside_corner_darker", "loctypes"),
            new GamevalEntry(47519, "GHORROCK_STONE01_SNOW01_FALLOFF_INSIDE_CORNER_DARKER", "ghorrock_stone01_snow01_falloff_inside_corner_darker", "loctypes"),
            new GamevalEntry(47520, "GHORROCK_SNOW4", "ghorrock_snow4", "loctypes"),
            new GamevalEntry(47521, "GHORROCK_METAL_GATE", "ghorrock_metal_gate", "loctypes"),
            new GamevalEntry(47522, "DUKE_SUCELLUS_SALT", "Salt Deposit", "loctypes"),
            new GamevalEntry(47523, "DUKE_SUCELLUS_SALT_NOOP", "Salt Deposit", "loctypes"),
            new GamevalEntry(47524, "DUKE_SUCELLUS_MUSHROOMS_1", "Musca mushrooms", "loctypes"),
            new GamevalEntry(47525, "DUKE_SUCELLUS_MUSHROOMS_1_DEPLETED", "duke_sucellus_mushrooms_1_depleted", "loctypes"),
            new GamevalEntry(47526, "DUKE_SUCELLUS_MUSHROOMS_2", "Holos mushrooms", "loctypes"),
            new GamevalEntry(47527, "DUKE_SUCELLUS_MUSHROOMS_2_DEPLETED", "duke_sucellus_mushrooms_2_depleted", "loctypes"),
            new GamevalEntry(47528, "DUKE_SUCELLUS_MUSHROOMS_3", "Arder mushrooms", "loctypes"),
            new GamevalEntry(47529, "DUKE_SUCELLUS_MUSHROOMS_3_DEPLETED", "duke_sucellus_mushrooms_3_depleted", "loctypes"),
            new GamevalEntry(47530, "DUKE_SUCELLUS_MUSHROOMS_4", "Resper mushrooms", "loctypes"),
            new GamevalEntry(47531, "DUKE_SUCELLUS_MUSHROOMS_4_DEPLETED", "duke_sucellus_mushrooms_4_depleted", "loctypes"),
            new GamevalEntry(47532, "DUKE_SUCELLUS_MUSHROOMS_1_NOOP", "Musca mushrooms", "loctypes"),
            new GamevalEntry(47533, "DUKE_SUCELLUS_MUSHROOMS_2_NOOP", "Holos mushrooms", "loctypes"),
            new GamevalEntry(47534, "DUKE_SUCELLUS_MUSHROOMS_3_NOOP", "Arder mushrooms", "loctypes"),
            new GamevalEntry(47535, "DUKE_SUCELLUS_MUSHROOMS_4_NOOP", "Resper mushrooms", "loctypes"),
            new GamevalEntry(47536, "DUKE_SUCELLUS_VAT_CHECK", "Fermentation Vat", "loctypes"),
            new GamevalEntry(47537, "DUKE_SUCELLUS_VAT_NOOP", "Fermentation Vat", "loctypes"),
            new GamevalEntry(47538, "DUKE_SUCELLUS_VAT_COLLECT_1_2", "Fermentation Vat", "loctypes"),
            new GamevalEntry(47539, "DUKE_SUCELLUS_VAT_COLLECT_1_3", "Fermentation Vat", "loctypes"),
            new GamevalEntry(47540, "DUKE_SUCELLUS_VAT_COLLECT_1_4", "Fermentation Vat", "loctypes"),
            new GamevalEntry(47541, "DUKE_SUCELLUS_VAT_COLLECT_2_3", "Fermentation Vat", "loctypes"),
            new GamevalEntry(47542, "DUKE_SUCELLUS_VAT_COLLECT_2_4", "Fermentation Vat", "loctypes"),
            new GamevalEntry(47543, "DUKE_SUCELLUS_VAT_COLLECT_3_4", "Fermentation Vat", "loctypes"),
            new GamevalEntry(47544, "DT2_DUKE_PRISONDOOR_EYE01", "Extremity", "loctypes"),
            new GamevalEntry(47545, "DT2_DUKE_PRISONDOOR_EYE02", "Extremity", "loctypes"),
            new GamevalEntry(47546, "DT2_DUKE_PRISONDOOR_EYE03", "Extremity", "loctypes"),
            new GamevalEntry(47547, "DT2_DUKE_PRISONDOOR_EYE01_AWAKE", "Extremity", "loctypes"),
            new GamevalEntry(47548, "DT2_DUKE_PRISONDOOR_EYE02_AWAKE", "Extremity", "loctypes"),
            new GamevalEntry(47549, "DT2_DUKE_PRISONDOOR_EYE03_AWAKE", "Extremity", "loctypes"),
            new GamevalEntry(47550, "DT2_DUKE_PRISONDOOR_EYE01_DEAD", "Extremity", "loctypes"),
            new GamevalEntry(47551, "DT2_DUKE_PRISONDOOR_EYE02_DEAD", "Extremity", "loctypes"),
            new GamevalEntry(47552, "DT2_DUKE_PRISONDOOR_EYE03_DEAD", "Extremity", "loctypes"),
            new GamevalEntry(47553, "DT2_DUKE_PRISONDOOR_DEBRIS01", "dt2_duke_prisondoor_debris01", "loctypes"),
            new GamevalEntry(47554, "DT2_DUKE_PRISONDOOR_DEBRIS02", "dt2_duke_prisondoor_debris02", "loctypes"),
            new GamevalEntry(47555, "DT2_DUKE_FLOOR_VENT_MIDDLE", "dt2_duke_floor_vent_middle", "loctypes"),
            new GamevalEntry(47556, "DT2_DUKE_FLOOR_VENT_SIDE", "dt2_duke_floor_vent_side", "loctypes"),
            new GamevalEntry(47557, "DT2_DUKE_FLOOR_VENT_CORNER", "dt2_duke_floor_vent_corner", "loctypes"),
            new GamevalEntry(47558, "DT2_DUKE_FLOOR_VENT_SIDE_SNOW", "dt2_duke_floor_vent_side_snow", "loctypes"),
            new GamevalEntry(47559, "DT2_DUKE_FLOOR_VENT_CORNER_SNOW", "dt2_duke_floor_vent_corner_snow", "loctypes"),
            new GamevalEntry(47560, "DUKE_SUCELLUS_PESTLE_MORTAR", "Pestle and mortar", "loctypes"),
            new GamevalEntry(47561, "DUKE_SUCELLUS_PICKAXE", "Pickaxe", "loctypes"),
            new GamevalEntry(47562, "DUKE_SUCELLUS_SCOREBOARD_NOOP", "Scoreboard", "loctypes"),
            new GamevalEntry(47563, "DUKE_SUCELLUS_SCOREBOARD_OP", "Scoreboard", "loctypes"),
            new GamevalEntry(47564, "DUKE_SUCELLUS_SCOREBOARD_OP_AWAKENED", "Scoreboard", "loctypes"),
            new GamevalEntry(47565, "DUKE_SUCELLUS_ESCAPE", "Gate", "loctypes"),
            new GamevalEntry(47566, "DUKE_SUCELLUS_EXIT", "Gate", "loctypes"),
            new GamevalEntry(47567, "DUKE_SUCELLUS_PESTLE_MORTAR_NOOP", "Pestle and mortar", "loctypes"),
            new GamevalEntry(47568, "DUKE_SUCELLUS_PICKAXE_NOOP", "Pickaxe", "loctypes"),
            new GamevalEntry(47569, "DT2_GHORROCK_ASYLUM_SKELETON", "Skeleton", "loctypes"),
            new GamevalEntry(47570, "ICE_MOUNTAIN_SHORTCUT_TOP", "Rocks", "loctypes"),
            new GamevalEntry(47571, "ICE_MOUNTAIN_SHORTCUT_BOTTOM", "Rocks", "loctypes"),
            new GamevalEntry(47572, "ICE_MOUNTAIN_SHORTCUT_MIDDLE", "ice_mountain_shortcut_middle", "loctypes"),
            new GamevalEntry(47573, "WHISPERER_SEED_SHADOW_REALM_WEAK", "Corrupted seed", "loctypes"),
            new GamevalEntry(47574, "WHISPERER_SEED_SHADOW_REALM_DANGER", "Corrupted seed", "loctypes"),
            new GamevalEntry(47575, "WHISPERER_SEED_REGULAR_REALM_WEAK", "Corrupted seed", "loctypes"),
            new GamevalEntry(47576, "WHISPERER_SCREECH_SAFESPOT_FULL", "Floating Column", "loctypes"),
            new GamevalEntry(47577, "WHISPERER_SCREECH_SAFESPOT", "whisperer_screech_safespot", "loctypes"),
            new GamevalEntry(47578, "WHISPERER_MEDALLION_LOC", "whisperer_medallion_loc", "loctypes"),
            new GamevalEntry(47579, "WHISPERER_MEDALLION_LOC_INACTIVE", "whisperer_medallion_loc_inactive", "loctypes"),
            new GamevalEntry(47580, "WHISPERER_SCOREBOARD_SHADOW_VIS", "Scoreboard", "loctypes"),
            new GamevalEntry(47581, "WHISPERER_SCOREBOARD_SHADOW_VIS_AWAKENED", "Scoreboard", "loctypes"),
            new GamevalEntry(47582, "WHISPERER_SCOREBOARD_VIS", "Scoreboard", "loctypes"),
            new GamevalEntry(47583, "WHISPERER_SCOREBOARD_VIS_AWAKENED", "Scoreboard", "loctypes"),
            new GamevalEntry(47584, "WHISPERER_ESCAPE", "Tentacle", "loctypes"),
            new GamevalEntry(47585, "WHISPERER_ESCAPE_SHADOW", "Tentacle", "loctypes"),
            new GamevalEntry(47586, "WHISPERER_EXIT", "Tentacle", "loctypes"),
            new GamevalEntry(47587, "LEVIATHAN_SCOREBOARD_NOOP", "Broken Pillar", "loctypes"),
            new GamevalEntry(47588, "LEVIATHAN_SCOREBOARD_OP", "Scoreboard", "loctypes"),
            new GamevalEntry(47589, "LEVIATHAN_SCOREBOARD_OP_AWAKENED", "Scoreboard", "loctypes"),
            new GamevalEntry(47590, "LEVIATHAN_RUBBLE", "leviathan_rubble", "loctypes"),
            new GamevalEntry(47591, "LEVIATHAN_BOAT_END", "leviathan_boat_end", "loctypes"),
            new GamevalEntry(47592, "LEVIATHAN_WALL_CLIMB", "Handholds", "loctypes"),
            new GamevalEntry(47593, "LEVIATHAN_WALL_CLIMB_QUEST", "Handholds", "loctypes"),
            new GamevalEntry(47594, "LEVIATHAN_WALL_CLIMB_QUEST_EXIT", "Handholds", "loctypes"),
            new GamevalEntry(47595, "LEVIATHAN_WALL_CLIMB_NOOP", "Handholds", "loctypes"),
            new GamevalEntry(47596, "VARDORVIS_SCOREBOARD_VIS_NOOP", "Ancient Tablet", "loctypes"),
            new GamevalEntry(47597, "VARDORVIS_SCOREBOARD_VIS", "Ancient Tablet", "loctypes"),
            new GamevalEntry(47598, "VARDORVIS_SCOREBOARD_VIS_AWAKENED", "Ancient Tablet", "loctypes"),
            new GamevalEntry(47599, "VARDORVIS_ESCAPE_1", "Tendril", "loctypes"),
            new GamevalEntry(47600, "VARDORVIS_ESCAPE_2", "Tendril", "loctypes"),
            new GamevalEntry(47601, "VARDORVIS_ESCAPE_3", "Tendril", "loctypes"),
            new GamevalEntry(47602, "VARDORVIS_ESCAPE_ANIM", "Tendril", "loctypes"),
            new GamevalEntry(47603, "VARDORVIS_EXIT", "Rocks", "loctypes"),
            new GamevalEntry(47604, "VARDORVIS_EXIT_NOOP", "Rocks", "loctypes"),
            new GamevalEntry(47605, "WALLKIT_LASSAR01_MIDDLE01", "wallkit_lassar01_middle01", "loctypes"),
            new GamevalEntry(47606, "WALLKIT_LASSAR01_MIDDLE02", "wallkit_lassar01_middle02", "loctypes"),
            new GamevalEntry(47607, "WALLKIT_LASSAR02_MIDDLE01", "wallkit_lassar02_middle01", "loctypes"),
            new GamevalEntry(47608, "WALLKIT_LASSAR01_FRAME01", "wallkit_lassar01_frame01", "loctypes"),
            new GamevalEntry(47609, "WALLKIT_LASSAR01_DAMAGE01", "wallkit_lassar01_damage01", "loctypes"),
            new GamevalEntry(47610, "WALLKIT_LASSAR01_END01_RIGHT", "wallkit_lassar01_end01_right", "loctypes"),
            new GamevalEntry(47611, "WALLKIT_LASSAR01_END01_LEFT", "wallkit_lassar01_end01_left", "loctypes"),
            new GamevalEntry(47612, "WALLKIT_LASSAR02_END01_RIGHT", "wallkit_lassar02_end01_right", "loctypes"),
            new GamevalEntry(47613, "WALLKIT_LASSAR02_END01_LEFT", "wallkit_lassar02_end01_left", "loctypes"),
            new GamevalEntry(47614, "WALLKIT_LASSAR01_INNER01", "wallkit_lassar01_inner01", "loctypes"),
            new GamevalEntry(47615, "WALLKIT_LASSAR01_SCONCE01", "wallkit_lassar01_sconce01", "loctypes"),
        };
    }

    static Optional<GamevalEntry> byId(int id) {
        for (GamevalEntry entry : entries()) {
            if (entry.id() == id) return Optional.of(entry);
        }
        return Optional.empty();
    }

}
