package net.titan.gamevals.internal;

import java.util.Optional;

import net.titan.gamevals.GamevalEntry;
import net.titan.gamevals.QuestEntry;

final class ObjectIDEntries_88 {
    private ObjectIDEntries_88() {}

    static GamevalEntry[] entries() {
        return new GamevalEntry[] {
            new GamevalEntry(45056, "TOA_WALL_BASIC01C", "toa_wall_basic01c", "loctypes"),
            new GamevalEntry(45057, "TOA_WALL_BASIC02A", "toa_wall_basic02a", "loctypes"),
            new GamevalEntry(45058, "TOA_WALL_BASIC02B", "toa_wall_basic02b", "loctypes"),
            new GamevalEntry(45059, "TOA_WALL_BASIC02C", "toa_wall_basic02c", "loctypes"),
            new GamevalEntry(45060, "TOA_WALL_BASIC02D", "toa_wall_basic02d", "loctypes"),
            new GamevalEntry(45061, "TOA_WALL_BASIC02D_DAMAGED01", "toa_wall_basic02d_damaged01", "loctypes"),
            new GamevalEntry(45062, "TOA_WALL_BASIC03A", "toa_wall_basic03a", "loctypes"),
            new GamevalEntry(45063, "TOA_WALL_MID01A", "toa_wall_mid01a", "loctypes"),
            new GamevalEntry(45064, "TOA_WALL_MID01A_DARK1", "toa_wall_mid01a_dark1", "loctypes"),
            new GamevalEntry(45065, "TOA_WALL_MID01B", "toa_wall_mid01b", "loctypes"),
            new GamevalEntry(45066, "TOA_WALL_MID02A", "toa_wall_mid02a", "loctypes"),
            new GamevalEntry(45067, "TOA_WALL_MID02B", "toa_wall_mid02b", "loctypes"),
            new GamevalEntry(45068, "TOA_WALL_MID03A", "toa_wall_mid03a", "loctypes"),
            new GamevalEntry(45069, "TOA_WALL_MID03B", "toa_wall_mid03b", "loctypes"),
            new GamevalEntry(45070, "TOA_WALL_HIGH01A", "toa_wall_high01a", "loctypes"),
            new GamevalEntry(45071, "TOA_WALL_HIGH01B", "toa_wall_high01b", "loctypes"),
            new GamevalEntry(45072, "TOA_WALL_HIGH02A", "toa_wall_high02a", "loctypes"),
            new GamevalEntry(45073, "TOA_WALL_HIGH02B", "toa_wall_high02b", "loctypes"),
            new GamevalEntry(45074, "TOA_WALL_HIGH02B_MIRROR", "toa_wall_high02b_mirror", "loctypes"),
            new GamevalEntry(45075, "TOA_WALL_HIGH02C", "toa_wall_high02c", "loctypes"),
            new GamevalEntry(45076, "TOA_WALL_HIGH03A", "toa_wall_high03a", "loctypes"),
            new GamevalEntry(45077, "TOA_WALL_HIGH03B", "toa_wall_high03b", "loctypes"),
            new GamevalEntry(45078, "TOA_WALL_HIGH03B_MIRROR", "toa_wall_high03b_mirror", "loctypes"),
            new GamevalEntry(45079, "TOA_WALL_HIGH03C", "toa_wall_high03c", "loctypes"),
            new GamevalEntry(45080, "TOA_WALL_HIGH03C_MIRROR", "toa_wall_high03c_mirror", "loctypes"),
            new GamevalEntry(45081, "TOA_WALL_HIGH03D", "toa_wall_high03d", "loctypes"),
            new GamevalEntry(45082, "TOA_WALL_HIGH03D_MIRROR", "toa_wall_high03d_mirror", "loctypes"),
            new GamevalEntry(45083, "TOA_WALL_HIGH03E", "toa_wall_high03e", "loctypes"),
            new GamevalEntry(45084, "TOA_WALL_HIGH04A", "toa_wall_high04a", "loctypes"),
            new GamevalEntry(45085, "TOA_WALL_HIGH04B", "toa_wall_high04b", "loctypes"),
            new GamevalEntry(45086, "TOA_WALL_DOOR01_OPEN", "toa_wall_door01_open", "loctypes"),
            new GamevalEntry(45087, "TOA_WALL_SCROLLS01", "toa_wall_scrolls01", "loctypes"),
            new GamevalEntry(45088, "TOA_WALL_SCROLLS01_R", "toa_wall_scrolls01_r", "loctypes"),
            new GamevalEntry(45089, "TOA_WALL_SCROLLS01_L", "toa_wall_scrolls01_l", "loctypes"),
            new GamevalEntry(45090, "TOA_WALL_SCROLLS02", "toa_wall_scrolls02", "loctypes"),
            new GamevalEntry(45091, "TOA_WALL_SCROLLS2X4", "toa_wall_scrolls2x4", "loctypes"),
            new GamevalEntry(45092, "TOA_WALL_SCROLLS2X4_M", "toa_wall_scrolls2x4_m", "loctypes"),
            new GamevalEntry(45093, "TOA_WALL_SCROLLS02_R", "toa_wall_scrolls02_r", "loctypes"),
            new GamevalEntry(45094, "TOA_WALL_SCROLLS02_L", "toa_wall_scrolls02_l", "loctypes"),
            new GamevalEntry(45095, "TOA_WALL_SCROLLS03", "toa_wall_scrolls03", "loctypes"),
            new GamevalEntry(45096, "TOA_WALL_PILLAR01", "toa_wall_pillar01", "loctypes"),
            new GamevalEntry(45097, "TOA_WALL_PILLAR02", "toa_wall_pillar02", "loctypes"),
            new GamevalEntry(45098, "TOA_WALL_PILLAR03", "toa_wall_pillar03", "loctypes"),
            new GamevalEntry(45099, "TOA_WALL_SCARAB01", "toa_wall_scarab01", "loctypes"),
            new GamevalEntry(45100, "TOA_WALL_SCARAB02", "toa_wall_scarab02", "loctypes"),
            new GamevalEntry(45101, "TOA_WALL_SCARAB03", "toa_wall_scarab03", "loctypes"),
            new GamevalEntry(45102, "TOA_WALL_RETAINING01", "toa_wall_retaining01", "loctypes"),
            new GamevalEntry(45103, "TOA_WALL_RETAINING02", "toa_wall_retaining02", "loctypes"),
            new GamevalEntry(45104, "TOA_WALL_RETAINING01_CAP01", "toa_wall_retaining01_cap01", "loctypes"),
            new GamevalEntry(45105, "TOA_WALL_RETAINING01_CAP02", "toa_wall_retaining01_cap02", "loctypes"),
            new GamevalEntry(45106, "TOA_WALL_RETAINING01_CAP01_MIRROR", "toa_wall_retaining01_cap01_mirror", "loctypes"),
            new GamevalEntry(45107, "TOA_WALL_SUPPORT03", "toa_wall_support03", "loctypes"),
            new GamevalEntry(45108, "TOA_WALL_SUPPORT04", "toa_wall_support04", "loctypes"),
            new GamevalEntry(45109, "TOA_WALL_SUPPORT05", "toa_wall_support05", "loctypes"),
            new GamevalEntry(45110, "TOA_WALL_SUPPORT06", "toa_wall_support06", "loctypes"),
            new GamevalEntry(45111, "TOA_WALL_SUPPORT07", "toa_wall_support07", "loctypes"),
            new GamevalEntry(45112, "TOA_WALL_KEPHRI01", "toa_wall_kephri01", "loctypes"),
            new GamevalEntry(45113, "TOA_WALL_LOW01", "toa_wall_low01", "loctypes"),
            new GamevalEntry(45114, "TOA_WALL_LOW01_DARK01", "toa_wall_low01_dark01", "loctypes"),
            new GamevalEntry(45115, "TOA_WALL_LOW01_DARK02", "toa_wall_low01_dark02", "loctypes"),
            new GamevalEntry(45116, "TOA_WALL_LOW01_DARK03", "toa_wall_low01_dark03", "loctypes"),
            new GamevalEntry(45117, "TOA_WALL_LOW01_DARK04", "toa_wall_low01_dark04", "loctypes"),
            new GamevalEntry(45118, "TOA_WALL_FENCE01", "toa_wall_fence01", "loctypes"),
            new GamevalEntry(45119, "TOA_WALL_MID03TUNNEL", "Hole", "loctypes"),
            new GamevalEntry(45120, "TOA_WALL_WARDEN_01", "toa_wall_warden_01", "loctypes"),
            new GamevalEntry(45121, "TOA_WALL_WARDEN_02", "toa_wall_warden_02", "loctypes"),
            new GamevalEntry(45122, "TOA_WALL_WARDEN_02_MIRROR", "toa_wall_warden_02_mirror", "loctypes"),
            new GamevalEntry(45123, "TOA_WALL_WARDEN_03", "toa_wall_warden_03", "loctypes"),
            new GamevalEntry(45124, "TOA_WALL_WARDEN_01_ALT01", "toa_wall_warden_01_alt01", "loctypes"),
            new GamevalEntry(45125, "TOA_WALL_WARDEN_02_ALT01", "toa_wall_warden_02_alt01", "loctypes"),
            new GamevalEntry(45126, "TOA_WALL_WARDEN_02_MIRROR_ALT01", "toa_wall_warden_02_mirror_alt01", "loctypes"),
            new GamevalEntry(45127, "TOA_WALL_WARDEN_03_ALT01", "toa_wall_warden_03_alt01", "loctypes"),
            new GamevalEntry(45128, "TOA_DOOR_EXIT", "Exit", "loctypes"),
            new GamevalEntry(45129, "TOA_DOOR_EXIT_WARDENS", "I Leave", "loctypes"),
            new GamevalEntry(45130, "TOA_DOOR_EXIT_SMALL", "Exit", "loctypes"),
            new GamevalEntry(45131, "TOA_DOOR_CONTINUE", "Entry", "loctypes"),
            new GamevalEntry(45132, "TOA_DOOR_TOP", "toa_door_top", "loctypes"),
            new GamevalEntry(45133, "TOA_DOOR_TOP02", "toa_door_top02", "loctypes"),
            new GamevalEntry(45134, "TOA_DOOR_TOP02_NEXUS", "toa_door_top02_nexus", "loctypes"),
            new GamevalEntry(45135, "TOA_PATH_BARRIER", "Barrier", "loctypes"),
            new GamevalEntry(45136, "TOA_WARDENS_BARRIER", "Barrier", "loctypes"),
            new GamevalEntry(45137, "TOA_TELEPORT_CRYSTAL_CONTINUE", "Teleport crystal", "loctypes"),
            new GamevalEntry(45138, "TOA_TELEPORT_CRYSTAL_CONTINUE_WARDENS", "Teleport crystal", "loctypes"),
            new GamevalEntry(45139, "TOA_SCABARAS_HINTS01", "Strange panels", "loctypes"),
            new GamevalEntry(45140, "TOA_SCABARAS_HINTS02", "Strange panels", "loctypes"),
            new GamevalEntry(45141, "TOA_DUGUPSOIL_SAND_1", "toa_dugupsoil_sand_1", "loctypes"),
            new GamevalEntry(45142, "TOA_DUGUPSOIL_SAND_2", "toa_dugupsoil_sand_2", "loctypes"),
            new GamevalEntry(45143, "TOA_DUGUPSOIL_SAND_3", "toa_dugupsoil_sand_3", "loctypes"),
            new GamevalEntry(45144, "TOA_ENTRANCE_KEPHRI_MAIN", "Exit", "loctypes"),
            new GamevalEntry(45145, "TOA_ENTRANCE_KEPHRI01", "toa_entrance_kephri01", "loctypes"),
            new GamevalEntry(45146, "TOA_ENTRANCE_KEPHRI02", "toa_entrance_kephri02", "loctypes"),
            new GamevalEntry(45147, "TOA_ENTRANCE_KEPHRI03", "toa_entrance_kephri03", "loctypes"),
            new GamevalEntry(45148, "TOA_ENTRANCE_KEPHRI04", "toa_entrance_kephri04", "loctypes"),
            new GamevalEntry(45149, "TOA_KEPHRI_DUNG01", "toa_kephri_dung01", "loctypes"),
            new GamevalEntry(45150, "TOA_KEPHRI_DUNG02", "toa_kephri_dung02", "loctypes"),
            new GamevalEntry(45151, "TOA_KEPHRI_DUNG03", "toa_kephri_dung03", "loctypes"),
            new GamevalEntry(45152, "TOA_STEPS_LIGHT01", "toa_steps_light01", "loctypes"),
            new GamevalEntry(45153, "TOA_STEPS_DARK01", "toa_steps_dark01", "loctypes"),
            new GamevalEntry(45154, "TOA_STEPS_DARK02", "toa_steps_dark02", "loctypes"),
            new GamevalEntry(45155, "TOA_STEPS_DARK03", "toa_steps_dark03", "loctypes"),
            new GamevalEntry(45156, "TOA_STEPS_CORNER01_DARK01", "toa_steps_corner01_dark01", "loctypes"),
            new GamevalEntry(45157, "TOA_STEPS_CORNER02_DARK01", "toa_steps_corner02_dark01", "loctypes"),
            new GamevalEntry(45158, "TOA_STEPS_CORNER03_LIGHT01", "toa_steps_corner03_light01", "loctypes"),
            new GamevalEntry(45159, "TOA_STEPS_STONE01", "toa_steps_stone01", "loctypes"),
            new GamevalEntry(45160, "TOA_TOMB04_TILE01_FULL01_RED01", "toa_tomb04_tile01_full01_red01", "loctypes"),
            new GamevalEntry(45161, "TOA_TOMB04_TILE01_FULL01_YELLOW01", "toa_tomb04_tile01_full01_yellow01", "loctypes"),
            new GamevalEntry(45162, "TOA_TOMB04_TILE01_HALF01_GREEN01", "1B1B1919", "loctypes"),
            new GamevalEntry(45163, "TOA_TOMB04_TILE01_HALF01_RED01", "toa_tomb04_tile01_half01_red01", "loctypes"),
            new GamevalEntry(45164, "TOA_TOMB04_TILE01_HALF02_GREEN01", "1B1B1919", "loctypes"),
            new GamevalEntry(45165, "TOA_TOMB04_TILE01_HALF02_RED01", "toa_tomb04_tile01_half02_red01", "loctypes"),
            new GamevalEntry(45166, "TOA_TOMB04_TILE01_EDGE01_RED01", "toa_tomb04_tile01_edge01_red01", "loctypes"),
            new GamevalEntry(45167, "TOA_TOMB04_TILE01_EDGE01_RED01_M", "toa_tomb04_tile01_edge01_red01_m", "loctypes"),
            new GamevalEntry(45168, "TOA_TOMB04_TILE01_EDGE01_WHITE01", "toa_tomb04_tile01_edge01_white01", "loctypes"),
            new GamevalEntry(45169, "TOA_TOMB04_TILE01_EDGE01_WHITE01_M", "toa_tomb04_tile01_edge01_white01_m", "loctypes"),
            new GamevalEntry(45170, "TOA_TOMB04_TILE01_EDGE02_RED01", "toa_tomb04_tile01_edge02_red01", "loctypes"),
            new GamevalEntry(45171, "TOA_TOMB04_TILE01_EDGE02_WHITE01", "toa_tomb04_tile01_edge02_white01", "loctypes"),
            new GamevalEntry(45172, "TOA_TOMB04_TILE01_EDGE02_YELLOW01", "toa_tomb04_tile01_edge02_yellow01", "loctypes"),
            new GamevalEntry(45173, "TOA_TOMB04_TILE01_EDGE02_YELLOW02", "toa_tomb04_tile01_edge02_yellow02", "loctypes"),
            new GamevalEntry(45174, "TOA_TOMB04_TILE01_EDGE03_RED01", "toa_tomb04_tile01_edge03_red01", "loctypes"),
            new GamevalEntry(45175, "TOA_TOMB04_TILE01_EDGE03_RED01_M", "toa_tomb04_tile01_edge03_red01_m", "loctypes"),
            new GamevalEntry(45176, "TOA_TOMB04_TILE01_CORNER01_WHITE01", "toa_tomb04_tile01_corner01_white01", "loctypes"),
            new GamevalEntry(45177, "TOA_TOMB04_TILE01_CORNER02_YELLOW01", "toa_tomb04_tile01_corner02_yellow01", "loctypes"),
            new GamevalEntry(45178, "TOA_TOMB04_TILE01_CORNER02_RED01", "toa_tomb04_tile01_corner02_red01", "loctypes"),
            new GamevalEntry(45179, "TOA_TOMB04_TILE01_CENTER01_YELLOW01", "toa_tomb04_tile01_center01_yellow01", "loctypes"),
            new GamevalEntry(45180, "TOA_TOMB04_TILE01_CENTER01_YELLOW01_M", "toa_tomb04_tile01_center01_yellow01_m", "loctypes"),
            new GamevalEntry(45181, "TOA_TOMB04_TILE01_CENTER02_YELLOW01", "toa_tomb04_tile01_center02_yellow01", "loctypes"),
            new GamevalEntry(45182, "TOA_TOMB04_TILE01_CENTER03_YELLOW01", "toa_tomb04_tile01_center03_yellow01", "loctypes"),
            new GamevalEntry(45183, "TOA_MURAL_KEPHRI01", "Mural", "loctypes"),
            new GamevalEntry(45184, "TOA_WALL_BASIC01_STONETOP01", "toa_wall_basic01_stonetop01", "loctypes"),
            new GamevalEntry(45185, "TOA_WALL_BASIC01_STONETOP02", "toa_wall_basic01_stonetop02", "loctypes"),
            new GamevalEntry(45186, "TOA_WALL_BASIC01_STONETOP03", "toa_wall_basic01_stonetop03", "loctypes"),
            new GamevalEntry(45187, "TOA_WALL_BASIC01_STONETOP01_GROUND", "toa_wall_basic01_stonetop01_ground", "loctypes"),
            new GamevalEntry(45188, "TOA_WALL_BASIC01_STONETOP02_GROUND", "toa_wall_basic01_stonetop02_ground", "loctypes"),
            new GamevalEntry(45189, "TOA_WALL_BASIC01_STONETOP03_GROUND", "toa_wall_basic01_stonetop03_ground", "loctypes"),
            new GamevalEntry(45190, "SKEWKIT_STONE01_STRAIGHT01", "skewkit_stone01_straight01", "loctypes"),
            new GamevalEntry(45191, "SKEWKIT_STONE01_CORNER01", "skewkit_stone01_corner01", "loctypes"),
            new GamevalEntry(45192, "SKEWKIT_STONE02_STRAIGHT01", "skewkit_stone02_straight01", "loctypes"),
            new GamevalEntry(45193, "SKEWKIT_STONE02_CORNER01", "skewkit_stone02_corner01", "loctypes"),
            new GamevalEntry(45194, "TOA_WALL_BASIC01_AKKHA01", "toa_wall_basic01_akkha01", "loctypes"),
            new GamevalEntry(45195, "TOA_FLOORKIT_AKKHA01_EDGE01", "toa_floorkit_akkha01_edge01", "loctypes"),
            new GamevalEntry(45196, "TOA_FLOORKIT_AKKHA01_EDGE02", "toa_floorkit_akkha01_edge02", "loctypes"),
            new GamevalEntry(45197, "TOA_FLOORKIT_AKKHA01_EDGE03", "toa_floorkit_akkha01_edge03", "loctypes"),
            new GamevalEntry(45198, "TOA_FLOORKIT_AKKHA01_CHUNK01", "toa_floorkit_akkha01_chunk01", "loctypes"),
            new GamevalEntry(45199, "TOA_FLOORKIT_AKKHA01_EDGE01_MIRROR", "toa_floorkit_akkha01_edge01_mirror", "loctypes"),
            new GamevalEntry(45200, "TOA_FLOORKIT_AKKHA01_EDGE02_MIRROR", "toa_floorkit_akkha01_edge02_mirror", "loctypes"),
            new GamevalEntry(45201, "TOA_FLOORKIT_AKKHA01_EDGE03_MIRROR", "toa_floorkit_akkha01_edge03_mirror", "loctypes"),
            new GamevalEntry(45202, "TOA_FLOORKIT_AKKHA01_CHUNK01_MIRROR", "toa_floorkit_akkha01_chunk01_mirror", "loctypes"),
            new GamevalEntry(45203, "TOA_AKKHA01_PILLAR01", "Pillar", "loctypes"),
            new GamevalEntry(45204, "TOA_BRAZIER01_2X2", "Gilded stand", "loctypes"),
            new GamevalEntry(45205, "TOA_SCABARAS_STATUE01_3X3", "Statue", "loctypes"),
            new GamevalEntry(45206, "TOA_CRONDIS_STATUE01_3X3", "Statue", "loctypes"),
            new GamevalEntry(45207, "FX_FOG01_SOULSTORMGROUND01", "fx_fog01_soulstormground01", "loctypes"),
            new GamevalEntry(45208, "FX_FOG01_SOULSTORMGROUND03", "fx_fog01_soulstormground03", "loctypes"),
            new GamevalEntry(45209, "FX_FOG01_SOULSTORMGROUND04", "fx_fog01_soulstormground04", "loctypes"),
            new GamevalEntry(45210, "FX_FOG01_SOULSTORM01", "Fog", "loctypes"),
            new GamevalEntry(45211, "FX_FOG01_SOULSTORM02", "Fog", "loctypes"),
            new GamevalEntry(45212, "FX_FOG01_SOULSTORM03", "Fog", "loctypes"),
            new GamevalEntry(45213, "FX_FOG01_SOULSTORM04", "Fog", "loctypes"),
            new GamevalEntry(45214, "FX_FOG02_SOULSTORM01", "Fog", "loctypes"),
            new GamevalEntry(45215, "FX_FOG02_SOULSTORM02", "Fog", "loctypes"),
            new GamevalEntry(45216, "FX_FOG02_SOULSTORM03", "Fog", "loctypes"),
            new GamevalEntry(45217, "FX_FOG02_SOULSTORM04", "Fog", "loctypes"),
            new GamevalEntry(45218, "FX_FOG03_SOULSTORM01", "Fog", "loctypes"),
            new GamevalEntry(45219, "FX_FOG03_SOULSTORM02", "Fog", "loctypes"),
            new GamevalEntry(45220, "FX_FOG03_SOULSTORM03", "Fog", "loctypes"),
            new GamevalEntry(45221, "FX_FOG03_SOULSTORM04", "Fog", "loctypes"),
            new GamevalEntry(45222, "DECOKIT_TOMB01_CORNER01", "decokit_tomb01_corner01", "loctypes"),
            new GamevalEntry(45223, "DECOKIT_TOMB01_CORNER02", "decokit_tomb01_corner02", "loctypes"),
            new GamevalEntry(45224, "DECOKIT_TOMB01_EDGE01", "decokit_tomb01_edge01", "loctypes"),
            new GamevalEntry(45225, "DECOKIT_TOMB01_EDGE02", "decokit_tomb01_edge02", "loctypes"),
            new GamevalEntry(45226, "DECOKIT_TOMB01_EDGE03", "decokit_tomb01_edge03", "loctypes"),
            new GamevalEntry(45227, "DECOKIT_TOMB01_EDGE04", "decokit_tomb01_edge04", "loctypes"),
            new GamevalEntry(45228, "DECOKIT_TOMB01_MIDDLE01", "decokit_tomb01_middle01", "loctypes"),
            new GamevalEntry(45229, "DECOKIT_TOMB01_MIDDLE02", "decokit_tomb01_middle02", "loctypes"),
            new GamevalEntry(45230, "DECOKIT_TOMB02_CORNER01", "decokit_tomb02_corner01", "loctypes"),
            new GamevalEntry(45231, "DECOKIT_TOMB02_CORNER02", "decokit_tomb02_corner02", "loctypes"),
            new GamevalEntry(45232, "DECOKIT_TOMB02_CORNER03", "decokit_tomb02_corner03", "loctypes"),
            new GamevalEntry(45233, "DECOKIT_TOMB02_CORNER041", "decokit_tomb02_corner041", "loctypes"),
            new GamevalEntry(45234, "DECOKIT_TOMB02_EDGE01", "decokit_tomb02_edge01", "loctypes"),
            new GamevalEntry(45235, "DECOKIT_TOMB02_EDGE02", "decokit_tomb02_edge02", "loctypes"),
            new GamevalEntry(45236, "DECOKIT_TOMB02_EDGE03", "decokit_tomb02_edge03", "loctypes"),
            new GamevalEntry(45237, "DECOKIT_TOMB02_EDGE04", "decokit_tomb02_edge04", "loctypes"),
            new GamevalEntry(45238, "DECOKIT_TOMB02_MIDDLE01", "decokit_tomb02_middle01", "loctypes"),
            new GamevalEntry(45239, "DECOKIT_TOMB02_MIDDLE02", "decokit_tomb02_middle02", "loctypes"),
            new GamevalEntry(45240, "DECOKIT_TOMB03_CORNER01", "decokit_tomb03_corner01", "loctypes"),
            new GamevalEntry(45241, "DECOKIT_TOMB03_CORNER02", "decokit_tomb03_corner02", "loctypes"),
            new GamevalEntry(45242, "DECOKIT_TOMB03_EDGE01", "decokit_tomb03_edge01", "loctypes"),
            new GamevalEntry(45243, "DECOKIT_TOMB03_MIDDLE01", "decokit_tomb03_middle01", "loctypes"),
            new GamevalEntry(45244, "BRAZIER_TOMB02_BROKEN01", "Brazier", "loctypes"),
            new GamevalEntry(45245, "BRAZIER_TOMB02_DEFAULT01", "Brazier", "loctypes"),
            new GamevalEntry(45246, "BRAZIER_TOMB03_DEFAULT01", "Brazier", "loctypes"),
            new GamevalEntry(45247, "BRAZIER_TOMB03_ORNATE01", "Brazier", "loctypes"),
            new GamevalEntry(45248, "BRAZIER_TOMB03_ORNATE02", "Brazier", "loctypes"),
            new GamevalEntry(45249, "POTTERY_TOMB01_BROKEN01", "Pot", "loctypes"),
            new GamevalEntry(45250, "POTTERY_TOMB01_DEFAULT01", "Pot", "loctypes"),
            new GamevalEntry(45251, "POTTERY_TOMB02_BROKEN01", "Pot", "loctypes"),
            new GamevalEntry(45252, "POTTERY_TOMB02_DEFAULT01", "Pot", "loctypes"),
            new GamevalEntry(45253, "POTTERY_TOMB03_BROKEN01", "Pot", "loctypes"),
            new GamevalEntry(45254, "POTTERY_TOMB03_DEFAULT01", "Pot", "loctypes"),
            new GamevalEntry(45255, "POTTERY_TOMB04_BROKEN01", "Pot", "loctypes"),
            new GamevalEntry(45256, "POTTERY_TOMB04_DEFAULT01", "Pot", "loctypes"),
            new GamevalEntry(45257, "POTTERY_TOMB05_BROKEN01", "Pot", "loctypes"),
            new GamevalEntry(45258, "POTTERY_TOMB05_DEFAULT01", "Pot", "loctypes"),
            new GamevalEntry(45259, "POTTERY_TOMB06_BROKEN01", "Pot", "loctypes"),
            new GamevalEntry(45260, "POTTERY_TOMB06_DEFAULT01", "Pot", "loctypes"),
            new GamevalEntry(45261, "POTTERY_TOMB07_BROKEN01", "Pot", "loctypes"),
            new GamevalEntry(45262, "POTTERY_TOMB07_DEFAULT01", "Pot", "loctypes"),
            new GamevalEntry(45263, "POTTERY_TOMB08_DEFAULT01", "Pot", "loctypes"),
            new GamevalEntry(45264, "POTTERY_TOMB08_SUNKEN01", "Pot", "loctypes"),
            new GamevalEntry(45265, "POTTERY_TOMB08_BROKEN01", "Pot", "loctypes"),
            new GamevalEntry(45266, "POTTERY_TOMB08_BROKEN02", "Pot", "loctypes"),
            new GamevalEntry(45267, "TOA_POTTERY_GROUP01_DEFAULT01", "Pots", "loctypes"),
            new GamevalEntry(45268, "TOA_POTTERY_GROUP01_SCABARAS01", "Pots", "loctypes"),
            new GamevalEntry(45269, "TOA_POTTERY_GROUP02_DEFAULT01", "Pots", "loctypes"),
            new GamevalEntry(45270, "TOA_POTTERY_GROUP02_SCABARAS01", "Pots", "loctypes"),
            new GamevalEntry(45271, "TOA_POTTERY_GROUP02_HET01", "Pots", "loctypes"),
            new GamevalEntry(45272, "TOA_POTTERY_GROUP03_DEFAULT01", "Pots", "loctypes"),
            new GamevalEntry(45273, "TOA_POTTERY_GROUP03_SCABARAS01", "Pots", "loctypes"),
            new GamevalEntry(45274, "TOA_POTTERY_GROUP03_HET01", "Pots", "loctypes"),
            new GamevalEntry(45275, "TOA_POTTERY_GROUP04_DEFAULT01", "Pots", "loctypes"),
            new GamevalEntry(45276, "TOA_POTTERY_GROUP05_DEFAULT01", "Pots", "loctypes"),
            new GamevalEntry(45277, "TOA_POTTERY_GROUP06_DEFAULT01", "Pots", "loctypes"),
            new GamevalEntry(45278, "TOA_POTTERY_GROUP07_DEFAULT01", "Pots", "loctypes"),
            new GamevalEntry(45279, "TOA_POTTERY_SINGLE01_DEFAULT01", "Pot", "loctypes"),
            new GamevalEntry(45280, "TOA_POTTERY_SINGLE01_SCABARAS01", "Pot", "loctypes"),
            new GamevalEntry(45281, "TOA_POTTERY_SINGLE01_SCABARAS02", "Pot", "loctypes"),
            new GamevalEntry(45282, "TOA_POTTERY_SINGLE01_HET01", "Pot", "loctypes"),
            new GamevalEntry(45283, "TOA_POTTERY_SINGLE01_HET02", "Pot", "loctypes"),
            new GamevalEntry(45284, "TOA_POTTERY_SINGLE02_DEFAULT01", "Pot", "loctypes"),
            new GamevalEntry(45285, "TOA_POTTERY_SINGLE03_DEFAULT01", "Pot", "loctypes"),
            new GamevalEntry(45286, "TOA_POTTERY_SINGLE04_DEFAULT01", "Pot", "loctypes"),
            new GamevalEntry(45287, "TOA_POTTERY_SINGLE05_DEFAULT01", "Pot", "loctypes"),
            new GamevalEntry(45288, "TOA_POTTERY_SINGLE06_DEFAULT01", "Pot", "loctypes"),
            new GamevalEntry(45289, "TOA_POTTERY_SINGLE01_BROKEN01", "Broken Pot", "loctypes"),
            new GamevalEntry(45290, "TOA_POTTERY_SINGLE01_BROKEN02", "Broken Pot", "loctypes"),
            new GamevalEntry(45291, "TOA_POTTERY_SINGLE01_BROKEN01_SCABARAS01", "Broken Pot", "loctypes"),
            new GamevalEntry(45292, "TOA_POTTERY_SINGLE01_BROKEN02_SCABARAS01", "Broken Pot", "loctypes"),
            new GamevalEntry(45293, "TOA_POTTERY_SINGLE01_BROKEN01_HET01", "Broken Pot", "loctypes"),
            new GamevalEntry(45294, "TOA_POTTERY_SINGLE01_BROKEN02_HET01", "Broken Pot", "loctypes"),
            new GamevalEntry(45295, "TOA_POTTERY_SINGLE02_BROKEN01", "Broken Pot", "loctypes"),
            new GamevalEntry(45296, "TOA_POTTERY_SINGLE02_BROKEN02", "Broken Pot", "loctypes"),
            new GamevalEntry(45297, "TOA_POTTERY_SINGLE03_BROKEN01", "Broken Pot", "loctypes"),
            new GamevalEntry(45298, "PILLAR_TOMB02_BROKEN01", "pillar_tomb02_broken01", "loctypes"),
            new GamevalEntry(45299, "PILLAR_TOMB02_DEFAULT01", "pillar_tomb02_default01", "loctypes"),
            new GamevalEntry(45300, "PILLAR_TOMB02_ORNATE01", "pillar_tomb02_ornate01", "loctypes"),
            new GamevalEntry(45301, "PILLAR_TOMB03_BROKEN01", "pillar_tomb03_broken01", "loctypes"),
            new GamevalEntry(45302, "PILLAR_TOMB03_DEFAULT01", "?'", "loctypes"),
            new GamevalEntry(45303, "PILLAR_TOMB03_ORNATE01", "pillar_tomb03_ornate01", "loctypes"),
            new GamevalEntry(45304, "PILLAR_TOMB04_BROKEN01", "pillar_tomb04_broken01", "loctypes"),
            new GamevalEntry(45305, "PILLAR_TOMB04_DEFAULT01", "pillar_tomb04_default01", "loctypes"),
            new GamevalEntry(45306, "PILLAR_TOMB04_ORNATE01", "pillar_tomb04_ornate01", "loctypes"),
            new GamevalEntry(45307, "PILLAR_TOMB05_BROKEN01", "pillar_tomb05_broken01", "loctypes"),
            new GamevalEntry(45308, "PILLAR_TOMB05_DEFAULT01", "pillar_tomb05_default01", "loctypes"),
            new GamevalEntry(45309, "PILLAR_TOMB05_ORNATE01", "pillar_tomb05_ornate01", "loctypes"),
            new GamevalEntry(45310, "TOA_PILLAR01_ORNATE01_SHADOW01", "toa_pillar01_ornate01_shadow01", "loctypes"),
            new GamevalEntry(45311, "TOA_PILLAR01_ORNATE01_SHADOW02", "toa_pillar01_ornate01_shadow02", "loctypes"),
            new GamevalEntry(45312, "TOA_PILLAR01_ORNATE01_SHADOW03", "toa_pillar01_ornate01_shadow03", "loctypes"),
            new GamevalEntry(45313, "TOA_PILLAR01_ORNATE01_SHADOW04", "toa_pillar01_ornate01_shadow04", "loctypes"),
            new GamevalEntry(45314, "TOA_CHASM_TOMB01", "toa_chasm_tomb01", "loctypes"),
            new GamevalEntry(45315, "TOA_CHASM_TOMB01_NOBLOCK", "toa_chasm_tomb01_noblock", "loctypes"),
            new GamevalEntry(45316, "TOA_CHASM_TOMB01_END01", "toa_chasm_tomb01_end01", "loctypes"),
            new GamevalEntry(45317, "TOA_CHASM_TOMB01_DOUBLE01", "toa_chasm_tomb01_double01", "loctypes"),
            new GamevalEntry(45318, "TOA_CHASM_TOMB01_CORNJOIN01", "toa_chasm_tomb01_cornjoin01", "loctypes"),
            new GamevalEntry(45319, "TOA_CHASM_TOMB01_CORNJOIN01_M", "toa_chasm_tomb01_cornjoin01_m", "loctypes"),
            new GamevalEntry(45320, "DEBRIS_TOMB_STONE01", "Debris", "loctypes"),
            new GamevalEntry(45321, "DEBRIS_TOMB_STONE02", "Debris", "loctypes"),
            new GamevalEntry(45322, "TOA_BONES01_SKELETON01", "Skeleton", "loctypes"),
            new GamevalEntry(45323, "TOA_BONES01_SKELETON02", "Skeleton", "loctypes"),
            new GamevalEntry(45324, "TOA_BONES01_SKELETON03", "Skeleton", "loctypes"),
            new GamevalEntry(45325, "TOA_BONES01_DEFAULT01", "toa_bones01_default01", "loctypes"),
            new GamevalEntry(45326, "TOA_BONES01_DEFAULT02", "toa_bones01_default02", "loctypes"),
            new GamevalEntry(45327, "TOA_BONES01_DEFAULT03", "toa_bones01_default03", "loctypes"),
            new GamevalEntry(45328, "TOA_BONES02_SKELETON01", "Skeleton", "loctypes"),
            new GamevalEntry(45329, "TOA_BONES02_SKELETON02", "Skeleton", "loctypes"),
            new GamevalEntry(45330, "TOA_BONES02_SKELETON03", "Skeleton", "loctypes"),
            new GamevalEntry(45331, "TOA_BONES02_DEFAULT01", "toa_bones02_default01", "loctypes"),
            new GamevalEntry(45332, "TOA_BONES02_DEFAULT02", "toa_bones02_default02", "loctypes"),
            new GamevalEntry(45333, "TOA_BONES02_DEFAULT03", "toa_bones02_default03", "loctypes"),
            new GamevalEntry(45334, "TOA_FX_FIRE01_SMALL01", "Fire", "loctypes"),
            new GamevalEntry(45335, "TOA_SCABARAS_BARRIER", "toa_scabaras_barrier", "loctypes"),
            new GamevalEntry(45336, "TOA_SCABARAS_BARRIER_ACTIVE", "Barrier", "loctypes"),
            new GamevalEntry(45337, "TOA_SCABARAS_CONTINUE", "Entry", "loctypes"),
            new GamevalEntry(45338, "TOA_SCABARAS_SIMONSAYS_BUTTON", "Ancient button", "loctypes"),
            new GamevalEntry(45339, "TOA_SCABARAS_TOTALTILES_TABLET", "Ancient tablet", "loctypes"),
            new GamevalEntry(45340, "TOA_SCABARAS_SIMONSAYS_TILE_UP", "Pressure plate", "loctypes"),
            new GamevalEntry(45341, "TOA_SCABARAS_SIMONSAYS_TILE_DOWN", "Pressure plate", "loctypes"),
            new GamevalEntry(45342, "TOA_SCABARAS_SIMONSAYS_TILE_DOWN_PLAYER", "Pressure plate", "loctypes"),
            new GamevalEntry(45343, "TOA_SCABARAS_SPAWN_HOLE", "Passage", "loctypes"),
            new GamevalEntry(45344, "TOA_SCABARAS_LIGHTSOUT_TILE_OFF", "Pressure plate", "loctypes"),
            new GamevalEntry(45345, "TOA_SCABARAS_TOTALTILES_TILE1", "Pressure plate", "loctypes"),
            new GamevalEntry(45346, "TOA_SCABARAS_TOTALTILES_TILE2", "Pressure plate", "loctypes"),
            new GamevalEntry(45347, "TOA_SCABARAS_TOTALTILES_TILE3", "Pressure plate", "loctypes"),
            new GamevalEntry(45348, "TOA_SCABARAS_TOTALTILES_TILE4", "Pressure plate", "loctypes"),
            new GamevalEntry(45349, "TOA_SCABARAS_TOTALTILES_TILE5", "Pressure plate", "loctypes"),
            new GamevalEntry(45350, "TOA_SCABARAS_TOTALTILES_TILE6", "Pressure plate", "loctypes"),
            new GamevalEntry(45351, "TOA_SCABARAS_TOTALTILES_TILE7", "Pressure plate", "loctypes"),
            new GamevalEntry(45352, "TOA_SCABARAS_TOTALTILES_TILE8", "Pressure plate", "loctypes"),
            new GamevalEntry(45353, "TOA_SCABARAS_TOTALTILES_TILE9", "Pressure plate", "loctypes"),
            new GamevalEntry(45354, "TOA_SCABARAS_SWARM", "toa_scabaras_swarm", "loctypes"),
            new GamevalEntry(45355, "TOA_SCABARAS_FINAL_BUTTON", "Ancient button", "loctypes"),
            new GamevalEntry(45356, "TOA_SCABARAS_MEMORYGAME_BUTTON1", "Tile", "loctypes"),
            new GamevalEntry(45357, "TOA_SCABARAS_MEMORYGAME_BUTTON2", "Tile", "loctypes"),
            new GamevalEntry(45358, "TOA_SCABARAS_MEMORYGAME_BUTTON3", "Tile", "loctypes"),
            new GamevalEntry(45359, "TOA_SCABARAS_MEMORYGAME_BUTTON4", "Tile", "loctypes"),
            new GamevalEntry(45360, "TOA_SCABARAS_MEMORYGAME_BUTTON5", "Tile", "loctypes"),
            new GamevalEntry(45361, "TOA_SCABARAS_MEMORYGAME_BUTTON6", "Tile", "loctypes"),
            new GamevalEntry(45362, "TOA_SCABARAS_MEMORYGAME_BUTTON7", "Tile", "loctypes"),
            new GamevalEntry(45363, "TOA_SCABARAS_MEMORYGAME_BUTTON8", "Tile", "loctypes"),
            new GamevalEntry(45364, "TOA_SCABARAS_MEMORYGAME_BUTTON9", "Tile", "loctypes"),
            new GamevalEntry(45365, "TOA_SCABARAS_MEMORYGAME_TILE1", "Symbol", "loctypes"),
            new GamevalEntry(45366, "TOA_SCABARAS_MEMORYGAME_TILE2", "Symbol", "loctypes"),
            new GamevalEntry(45367, "TOA_SCABARAS_MEMORYGAME_TILE3", "Symbol", "loctypes"),
            new GamevalEntry(45368, "TOA_SCABARAS_MEMORYGAME_TILE4", "Symbol", "loctypes"),
            new GamevalEntry(45369, "TOA_SCABARAS_MEMORYGAME_TILE5", "Symbol", "loctypes"),
            new GamevalEntry(45370, "TOA_SCABARAS_MEMORYGAME_TILE6", "Symbol", "loctypes"),
            new GamevalEntry(45371, "TOA_SCABARAS_MEMORYGAME_TILE7", "Symbol", "loctypes"),
            new GamevalEntry(45372, "TOA_SCABARAS_MEMORYGAME_TILE8", "Symbol", "loctypes"),
            new GamevalEntry(45373, "TOA_SCABARAS_MEMORYGAME_TILE9", "Symbol", "loctypes"),
            new GamevalEntry(45374, "TOA_SCABARAS_DIVIDER", "toa_scabaras_divider", "loctypes"),
            new GamevalEntry(45375, "GATEWAY_TOMB01_LEFT01", "gateway_tomb01_left01", "loctypes"),
            new GamevalEntry(45376, "GATEWAY_TOMB01_RIGHT01", "gateway_tomb01_right01", "loctypes"),
            new GamevalEntry(45377, "GATEWAY_TOMB01_TOP01", "gateway_tomb01_top01", "loctypes"),
            new GamevalEntry(45378, "BRAZIER_TOMB01_LEFT01", "brazier_tomb01_left01", "loctypes"),
            new GamevalEntry(45379, "BRAZIER_TOMB01_RIGHT01", "brazier_tomb01_right01", "loctypes"),
            new GamevalEntry(45380, "FLOORKIT_TOMB_BASIC01", "floorkit_tomb_basic01", "loctypes"),
            new GamevalEntry(45381, "FLOORKIT_TOMB_DAMAGED01", "floorkit_tomb_damaged01", "loctypes"),
            new GamevalEntry(45382, "TOA_TOMB_TILES01_SCABARAS", "toa_tomb_tiles01_scabaras", "loctypes"),
            new GamevalEntry(45383, "TOA_TOMB_TILES02_SCABARAS", "toa_tomb_tiles02_scabaras", "loctypes"),
            new GamevalEntry(45384, "TOA_SCABARAS_FX01", "toa_scabaras_fx01", "loctypes"),
            new GamevalEntry(45385, "TOA_SCABARAS_FX02", "toa_scabaras_fx02", "loctypes"),
            new GamevalEntry(45386, "TOA_SCABARAS_FX03", "toa_scabaras_fx03", "loctypes"),
            new GamevalEntry(45387, "TOA_SCABARAS_FX04", "toa_scabaras_fx04", "loctypes"),
            new GamevalEntry(45388, "TOA_SCABARAS_FX05", "toa_scabaras_fx05", "loctypes"),
            new GamevalEntry(45389, "TOA_SCABARAS_FX06", "toa_scabaras_fx06", "loctypes"),
            new GamevalEntry(45390, "TOA_SCABARAS_FX07", "toa_scabaras_fx07", "loctypes"),
            new GamevalEntry(45391, "TOA_SCABARAS_FX08", "toa_scabaras_fx08", "loctypes"),
            new GamevalEntry(45392, "TOA_SCABARAS_FX09", "toa_scabaras_fx09", "loctypes"),
            new GamevalEntry(45393, "TOA_SCABARAS_FX10", "toa_scabaras_fx10", "loctypes"),
            new GamevalEntry(45394, "TOA_SCABARAS_FX11", "toa_scabaras_fx11", "loctypes"),
            new GamevalEntry(45395, "TOA_SCABARAS_FX12", "toa_scabaras_fx12", "loctypes"),
            new GamevalEntry(45396, "TOA_SCABARAS_STEPPING_STONE", "Platform", "loctypes"),
            new GamevalEntry(45397, "TOA_PATH_CRONDIS_CONTINUE", "Entry", "loctypes"),
            new GamevalEntry(45398, "TOA_CRONDIS_WATER_SOURCE", "Waterfall", "loctypes"),
            new GamevalEntry(45399, "TOA_CRONDIS_WATER_SOURCE_EMPTY", "Waterfall (dry)", "loctypes"),
            new GamevalEntry(45400, "TOA_CRONDIS_WATERFALL_FLOOR_01", "toa_crondis_waterfall_floor_01", "loctypes"),
            new GamevalEntry(45401, "TOA_CRONDIS_WATERFALL_FLOOR_01_MIRROR", "toa_crondis_waterfall_floor_01_mirror", "loctypes"),
            new GamevalEntry(45402, "TOA_CRONDIS_WATERFALL_FLOOR_02", "toa_crondis_waterfall_floor_02", "loctypes"),
            new GamevalEntry(45403, "TOA_CRONDIS_ORB", "Acid Orb", "loctypes"),
            new GamevalEntry(45404, "TOA_CRONDIS_BUSH_01", "Bushes", "loctypes"),
            new GamevalEntry(45405, "TOA_CRONDIS_BUSH_01_RECOL", "Bushes", "loctypes"),
            new GamevalEntry(45406, "TOA_CRONDIS_BUSH_02", "Bushes", "loctypes"),
            new GamevalEntry(45407, "TOA_CRONDIS_BUSH_02_RECOL", "Bushes", "loctypes"),
            new GamevalEntry(45408, "TOA_CRONDIS_BUSH_03", "Bushes", "loctypes"),
            new GamevalEntry(45409, "TOA_CRONDIS_BUSH_03_RECOL", "Bushes", "loctypes"),
            new GamevalEntry(45410, "TOA_CRONDIS_BUSH_04", "toa_crondis_bush_04", "loctypes"),
            new GamevalEntry(45411, "TOA_CRONDIS_BUSH_04_RECOL", "toa_crondis_bush_04_recol", "loctypes"),
            new GamevalEntry(45412, "TOA_CRONDIS_BUSH_05", "toa_crondis_bush_05", "loctypes"),
            new GamevalEntry(45413, "TOA_CRONDIS_BUSH_06", "toa_crondis_bush_06", "loctypes"),
            new GamevalEntry(45414, "TOA_CRONDIS_COLUMN_TRAP", "Statue", "loctypes"),
            new GamevalEntry(45415, "TOA_CRONDIS_ROW_TRAP", "Statue", "loctypes"),
            new GamevalEntry(45416, "TOA_CRONDIS_ROW_TRAP_FIRE", "Spear", "loctypes"),
            new GamevalEntry(45417, "TOA_WALL_CRONDIS01", "toa_wall_crondis01", "loctypes"),
            new GamevalEntry(45418, "TOA_CRONDIS_POISON_TILE", "toa_crondis_poison_tile", "loctypes"),
            new GamevalEntry(45419, "TOA_CRONDIS_POISON_TILE_RECOL01", "toa_crondis_poison_tile_recol01", "loctypes"),
            new GamevalEntry(45420, "TOA_CRONDIS_POISON_TILE_RECOL02", "toa_crondis_poison_tile_recol02", "loctypes"),
            new GamevalEntry(45421, "TOA_CRONDIS_POISON_TILE_INACTIVE", "Vines", "loctypes"),
            new GamevalEntry(45422, "TOA_CRONDIS_POISON_TILE_EDGE01", "toa_crondis_poison_tile_edge01", "loctypes"),
            new GamevalEntry(45423, "TOA_CRONDIS_POISON_TILE_EDGE01_MIRROR", "toa_crondis_poison_tile_edge01_mirror", "loctypes"),
            new GamevalEntry(45424, "TOA_CRONDIS_POISON_TILE_EDGE01_RECOL", "toa_crondis_poison_tile_edge01_recol", "loctypes"),
            new GamevalEntry(45425, "TOA_CRONDIS_POISON_TILE_EDGE02", "toa_crondis_poison_tile_edge02", "loctypes"),
            new GamevalEntry(45426, "TOA_CRONDIS_SKEWSTEPS_PLAIN", "toa_crondis_skewsteps_plain", "loctypes"),
            new GamevalEntry(45427, "TOA_CRONDIS_SKEWSTEPS_LIGHT", "toa_crondis_skewsteps_light", "loctypes"),
            new GamevalEntry(45428, "TOA_CRONDIS_SKEWSTEPS_CORNER", "toa_crondis_skewsteps_corner", "loctypes"),
            new GamevalEntry(45429, "TOA_CRONDIS_SKEWSTEPS_CORNER_LIGHT", "toa_crondis_skewsteps_corner_light", "loctypes"),
            new GamevalEntry(45430, "TOA_CRONDIS_DIRTPATCH", "toa_crondis_dirtpatch", "loctypes"),
            new GamevalEntry(45431, "TOA_WALL02_CROCODILES01", "toa_wall02_crocodiles01", "loctypes"),
            new GamevalEntry(45432, "TOA_WALL02_CROCODILES02", "toa_wall02_crocodiles02", "loctypes"),
            new GamevalEntry(45433, "TOA_WALL02_CROCODILES03", "toa_wall02_crocodiles03", "loctypes"),
            new GamevalEntry(45434, "TOA_WALL02_CROCODILES04", "toa_wall02_crocodiles04", "loctypes"),
            new GamevalEntry(45435, "TOA_WALL02_CROCODILES05", "toa_wall02_crocodiles05", "loctypes"),
            new GamevalEntry(45436, "TOA_WALL02_CROCODILES06", "toa_wall02_crocodiles06", "loctypes"),
            new GamevalEntry(45437, "TOA_CRONDIS_PATCH01_EDGE01", "toa_crondis_patch01_edge01", "loctypes"),
            new GamevalEntry(45438, "TOA_CRONDIS_PATCH01_EDGE02", "toa_crondis_patch01_edge02", "loctypes"),
            new GamevalEntry(45439, "TOA_CRONDIS_PATCH01_EDGE03", "toa_crondis_patch01_edge03", "loctypes"),
            new GamevalEntry(45440, "TOA_CRONDIS_PATCH01_CORNER01", "toa_crondis_patch01_corner01", "loctypes"),
            new GamevalEntry(45441, "TOA_CRONDIS_PATCH01_CORNER02", "toa_crondis_patch01_corner02", "loctypes"),
            new GamevalEntry(45442, "TOA_CRONDIS_DUGUPSOIL01", "toa_crondis_dugupsoil01", "loctypes"),
            new GamevalEntry(45443, "TOA_CRONDIS_DUGUPSOIL02", "toa_crondis_dugupsoil02", "loctypes"),
            new GamevalEntry(45444, "TOA_CRONDIS_DUGUPSOIL03", "toa_crondis_dugupsoil03", "loctypes"),
            new GamevalEntry(45445, "DECAL_SAND05_FLOOR01", "decal_sand05_floor01", "loctypes"),
            new GamevalEntry(45446, "DECAL_SAND05_FLOOR02", "decal_sand05_floor02", "loctypes"),
            new GamevalEntry(45447, "DECAL_SAND05_FLOOR03", "decal_sand05_floor03", "loctypes"),
            new GamevalEntry(45448, "DECAL_SAND05_FLOOR03_MIRROR", "decal_sand05_floor03_mirror", "loctypes"),
            new GamevalEntry(45449, "DECAL_SAND05_FLOOR04", "decal_sand05_floor04", "loctypes"),
            new GamevalEntry(45450, "DECAL_SAND05_FLOOR04_MIRROR", "decal_sand05_floor04_mirror", "loctypes"),
            new GamevalEntry(45451, "DECAL_SAND05_FLOOR05", "decal_sand05_floor05", "loctypes"),
            new GamevalEntry(45452, "DECAL_SAND05_FLOOR06", "decal_sand05_floor06", "loctypes"),
            new GamevalEntry(45453, "TOA_CRONDIS_EXIT", "I Leave", "loctypes"),
            new GamevalEntry(45454, "TOA_CRONDIS_EXIT_TOP", "toa_crondis_exit_top", "loctypes"),
            new GamevalEntry(45455, "TOA_HET_MIRROR", "Mirror", "loctypes"),
            new GamevalEntry(45456, "TOA_HET_MIRROR_FIXED", "Mirror", "loctypes"),
            new GamevalEntry(45457, "TOA_HET_MIRROR_DIRTY", "Mirror (dirty)", "loctypes"),
            new GamevalEntry(45458, "TOA_HET_BARRIER_INTERNAL", "Barrier", "loctypes"),
            new GamevalEntry(45459, "TOA_HET_BARRIER_INTERNAL_RISING", "toa_het_barrier_internal_rising", "loctypes"),
            new GamevalEntry(45460, "TOA_HET_BARRIER_END", "Barrier", "loctypes"),
            new GamevalEntry(45461, "TOA_HET_BARRIER_END_RISING", "toa_het_barrier_end_rising", "loctypes"),
            new GamevalEntry(45462, "TOA_HET_BARRIER_DESTRUCTABLE_INTERNAL", "Barrier", "loctypes"),
            new GamevalEntry(45463, "TOA_HET_BARRIER_DESTRUCTABLE_INTERNAL_RISING", "toa_het_barrier_destructable_internal_rising", "loctypes"),
            new GamevalEntry(45464, "TOA_HET_BARRIER_DESTRUCTABLE_END", "Barrier", "loctypes"),
            new GamevalEntry(45465, "TOA_HET_BARRIER_DESTRUCTABLE_END_RISING", "toa_het_barrier_destructable_end_rising", "loctypes"),
            new GamevalEntry(45466, "TOA_HET_BARRIER_DESTROYED", "toa_het_barrier_destroyed", "loctypes"),
            new GamevalEntry(45467, "TOA_HET_MIRROR_DESTROYED", "toa_het_mirror_destroyed", "loctypes"),
            new GamevalEntry(45468, "TOA_HET_STATUE_PARENT", "toa_het_statue_parent", "loctypes"),
            new GamevalEntry(45469, "TOA_HET_STATUE_PICKAXE_EMPTY01", "Statue", "loctypes"),
            new GamevalEntry(45470, "TOA_HET_STATUE_PICKAXE_BRONZE01", "Statue", "loctypes"),
            new GamevalEntry(45471, "TOA_HET_STATUE_PICKAXE_IRON01", "Statue", "loctypes"),
            new GamevalEntry(45472, "TOA_HET_STATUE_PICKAXE_STEEL01", "Statue", "loctypes"),
            new GamevalEntry(45473, "TOA_HET_STATUE_PICKAXE_BLACK01", "Statue", "loctypes"),
            new GamevalEntry(45474, "TOA_HET_STATUE_PICKAXE_MITHRIL01", "Statue", "loctypes"),
            new GamevalEntry(45475, "TOA_HET_STATUE_PICKAXE_ADAMANT01", "Statue", "loctypes"),
            new GamevalEntry(45476, "TOA_HET_STATUE_PICKAXE_RUNE01", "Statue", "loctypes"),
            new GamevalEntry(45477, "TOA_HET_STATUE_PICKAXE_GILDED01", "Statue", "loctypes"),
            new GamevalEntry(45478, "TOA_HET_STATUE_PICKAXE_DRAGON01", "Statue", "loctypes"),
            new GamevalEntry(45479, "TOA_HET_STATUE_PICKAXE_DRAGON02", "Statue", "loctypes"),
            new GamevalEntry(45480, "TOA_HET_STATUE_PICKAXE_DRAGON03", "Statue", "loctypes"),
            new GamevalEntry(45481, "TOA_HET_STATUE_PICKAXE_3RDAGE01", "Statue", "loctypes"),
            new GamevalEntry(45482, "TOA_HET_STATUE_PICKAXE_INFERNAL01", "Statue", "loctypes"),
            new GamevalEntry(45483, "TOA_HET_STATUE_PICKAXE_CRYSTAL01", "Statue", "loctypes"),
            new GamevalEntry(45484, "TOA_HET_STATUE_PICKAXE_TRAILBLAZER01", "Statue", "loctypes"),
            new GamevalEntry(45485, "TOA_HET_TARGET", "Shielded statue", "loctypes"),
            new GamevalEntry(45486, "TOA_HET_SOURCE", "Caster statue", "loctypes"),
            new GamevalEntry(45487, "TOA_HET_BARRIER_MOUND", "Nothing", "loctypes"),
            new GamevalEntry(45488, "TOA_HET_GOAL_BOX", "toa_het_goal_box", "loctypes"),
            new GamevalEntry(45489, "TOA_HET_GOAL_DEAD", "Broken seal", "loctypes"),
            new GamevalEntry(45490, "TOA_HET_GOAL", "toa_het_goal", "loctypes"),
            new GamevalEntry(45491, "TOA_HET_RUBBLE", "Broken seal", "loctypes"),
            new GamevalEntry(45492, "TOA_HET_PILLAR01", "toa_het_pillar01", "loctypes"),
            new GamevalEntry(45493, "TOA_PATH_APMEKEN_VENOM_POOL", "Venom pool", "loctypes"),
            new GamevalEntry(45494, "TOA_PATH_APMEKEN_PILLAR", "Roof support", "loctypes"),
            new GamevalEntry(45495, "TOA_PATH_APMEKEN_PILLAR_SHAKING", "Roof support", "loctypes"),
            new GamevalEntry(45496, "TOA_PATH_APMEKEN_PILLAR_NO_REPAIR", "Statue", "loctypes"),
            new GamevalEntry(45497, "TOA_PATH_APMEKEN_HAMMERS", "Hammers", "loctypes"),
            new GamevalEntry(45498, "TOA_PATH_APMEKEN_POTIONS", "Potions", "loctypes"),
            new GamevalEntry(45499, "TOA_PATH_APMEKEN_VENT", "toa_path_apmeken_vent", "loctypes"),
            new GamevalEntry(45500, "TOA_PATH_APMEKEN_CONTINUE", "Entry", "loctypes"),
            new GamevalEntry(45501, "TOA_PATH_APMEKEN_TRANSITION", "toa_path_apmeken_transition", "loctypes"),
            new GamevalEntry(45502, "TOA_PATH_APMEKEN_TRANSITION_M", "toa_path_apmeken_transition_m", "loctypes"),
            new GamevalEntry(45503, "KEPHRI_DOOR", "Tomb Door", "loctypes"),
            new GamevalEntry(45504, "KEPHRI_DUNG", "Dung", "loctypes"),
            new GamevalEntry(45505, "KEPHRI_TELEPORT", "Teleport crystal", "loctypes"),
            new GamevalEntry(45506, "ZEBAK_TELEPORT", "Teleport crystal", "loctypes"),
            new GamevalEntry(45507, "TOA_ZEBAK_BUBBLES", "Bubbles", "loctypes"),
            new GamevalEntry(45508, "TOA_ZEBAK_WATER", "toa_zebak_water", "loctypes"),
            new GamevalEntry(45509, "TOA_ZEBAK_CLIMBING_ROCK", "Rock steps", "loctypes"),
            new GamevalEntry(45510, "TOA_ZEBAK_DEBRIS01", "Debris", "loctypes"),
            new GamevalEntry(45511, "TOA_ZEBAK_DEBRIS01_MIRROR", "Debris", "loctypes"),
            new GamevalEntry(45512, "TOA_ZEBAK_DEBRIS02", "Debris", "loctypes"),
            new GamevalEntry(45513, "TOA_ZEBAK_DEBRIS02_MIRROR", "Debris", "loctypes"),
            new GamevalEntry(45514, "TOA_ZEBAK_DEBRIS03", "Debris", "loctypes"),
            new GamevalEntry(45515, "TOA_ZEBAK_DEBRIS03_MIRROR", "Debris", "loctypes"),
            new GamevalEntry(45516, "TOA_ZEBAK_PILLAR01", "Debris", "loctypes"),
            new GamevalEntry(45517, "TOA_ZEBAK_PILLAR02", "Debris", "loctypes"),
            new GamevalEntry(45518, "TOA_ZEBAK_RIBCAGE01", "Debris", "loctypes"),
            new GamevalEntry(45519, "TOA_ZEBAK_WALL01_BASIC01C", "toa_zebak_wall01_basic01c", "loctypes"),
            new GamevalEntry(45520, "TOA_ZEBAK_WALL01_BASIC01B", "toa_zebak_wall01_basic01b", "loctypes"),
            new GamevalEntry(45521, "TOA_ZEBAK_WALL01_BASIC01D", "toa_zebak_wall01_basic01d", "loctypes"),
            new GamevalEntry(45522, "TOA_WALL_CROCODILES01", "toa_wall_crocodiles01", "loctypes"),
            new GamevalEntry(45523, "TOA_WALL_CROCODILES02", "toa_wall_crocodiles02", "loctypes"),
            new GamevalEntry(45524, "TOA_WALL_CROCODILES03", "toa_wall_crocodiles03", "loctypes"),
            new GamevalEntry(45525, "TOA_WALL_CROCODILES04", "toa_wall_crocodiles04", "loctypes"),
            new GamevalEntry(45526, "TOA_ZEBAK_POTTERY01_DEFAULT01", "Pot", "loctypes"),
            new GamevalEntry(45527, "TOA_ZEBAK_POTTERY08_SUNKEN01", "Floating pot", "loctypes"),
            new GamevalEntry(45528, "TOA_ZEBAK_POTTERY08_BROKEN01", "Pot", "loctypes"),
            new GamevalEntry(45529, "TOA_ZEBAK_POTTERY08_BROKEN02", "Pot", "loctypes"),
            new GamevalEntry(45530, "TOA_ZEBAK_PILLAR04_DEFAULT01", "Pillar", "loctypes"),
            new GamevalEntry(45531, "TOA_ZEBAK_PILLAR04_SHAKE01", "Damaged pillar", "loctypes"),
            new GamevalEntry(45532, "TOA_ZEBAK_CROCODILE01_SUNKEN01", "Crocodile", "loctypes"),
            new GamevalEntry(45533, "TOA_ZEBAK_BUSH_01", "Bushes", "loctypes"),
            new GamevalEntry(45534, "TOA_ZEBAK_BUSH_02", "Bushes", "loctypes"),
            new GamevalEntry(45535, "TOA_ZEBAK_BUSH_03", "Bushes", "loctypes"),
            new GamevalEntry(45536, "TOA_ZEBAK_BUSH_04", "toa_zebak_bush_04", "loctypes"),
            new GamevalEntry(45537, "TOA_ZEBAK_BUSH_05", "Bushes", "loctypes"),
            new GamevalEntry(45538, "TOA_ZEBAK_RIPPLE01", "toa_zebak_ripple01", "loctypes"),
            new GamevalEntry(45539, "TOA_ZEBAK_RIPPLE02", "toa_zebak_ripple02", "loctypes"),
            new GamevalEntry(45540, "TOA_ZEBAK_DEBRIS_STONE", "Debris", "loctypes"),
            new GamevalEntry(45541, "TOA_ZEBAK_DEBRIS_STONE02", "Debris", "loctypes"),
            new GamevalEntry(45542, "TOA_ZEBAK_DEBRIS_STONE03", "Debris", "loctypes"),
            new GamevalEntry(45543, "TOA_ZEBAK_EXIT", "Exit", "loctypes"),
            new GamevalEntry(45544, "TOA_ZEBAK_DOOR_TOP", "toa_zebak_door_top", "loctypes"),
            new GamevalEntry(45545, "TOA_ZEBAK_ROCKS01", "toa_zebak_rocks01", "loctypes"),
            new GamevalEntry(45546, "TOA_ZEBAK_ROCKS02", "toa_zebak_rocks02", "loctypes"),
            new GamevalEntry(45547, "TOA_ZEBAK_ROCKS03", "toa_zebak_rocks03", "loctypes"),
            new GamevalEntry(45548, "TOA_ZEBAK_ROCKS04", "toa_zebak_rocks04", "loctypes"),
            new GamevalEntry(45549, "TOA_ZEBAK_ROCKS05", "toa_zebak_rocks05", "loctypes"),
            new GamevalEntry(45550, "TOA_ZEBAK_DUGUPSOIL01", "toa_zebak_dugupsoil01", "loctypes"),
            new GamevalEntry(45551, "TOA_ZEBAK_DUGUPSOIL02", "toa_zebak_dugupsoil02", "loctypes"),
            new GamevalEntry(45552, "WALLKIT_TOMB01_SMASHED01", "wallkit_tomb01_smashed01", "loctypes"),
            new GamevalEntry(45553, "WALLKIT_TOMB01_SMASHED02", "wallkit_tomb01_smashed02", "loctypes"),
            new GamevalEntry(45554, "WALLKIT_TOMB01_SMASHED03", "wallkit_tomb01_smashed03", "loctypes"),
            new GamevalEntry(45555, "WALLKIT_TOMB01_SMASHED04", "wallkit_tomb01_smashed04", "loctypes"),
            new GamevalEntry(45556, "WALLKIT_TOMB01_SMASHED05", "wallkit_tomb01_smashed05", "loctypes"),
            new GamevalEntry(45557, "WALLKIT_TOMB01_SMASHED06", "wallkit_tomb01_smashed06", "loctypes"),
            new GamevalEntry(45558, "WALLKIT_TOMB01_SMASHED07", "wallkit_tomb01_smashed07", "loctypes"),
            new GamevalEntry(45559, "WALLKIT_TOMB01_SMASHED01_MIRROR", "wallkit_tomb01_smashed01_mirror", "loctypes"),
            new GamevalEntry(45560, "WALLKIT_TOMB01_SMASHED02_MIRROR", "wallkit_tomb01_smashed02_mirror", "loctypes"),
            new GamevalEntry(45561, "WALLKIT_TOMB01_SMASHED03_MIRROR", "wallkit_tomb01_smashed03_mirror", "loctypes"),
            new GamevalEntry(45562, "WALLKIT_TOMB01_SMASHED04_MIRROR", "wallkit_tomb01_smashed04_mirror", "loctypes"),
            new GamevalEntry(45563, "WALLKIT_TOMB01_SMASHED05_MIRROR", "wallkit_tomb01_smashed05_mirror", "loctypes"),
            new GamevalEntry(45564, "WALLKIT_TOMB01_SMASHED06_MIRROR", "wallkit_tomb01_smashed06_mirror", "loctypes"),
            new GamevalEntry(45565, "WALLKIT_TOMB01_SMASHED07_MIRROR", "wallkit_tomb01_smashed07_mirror", "loctypes"),
            new GamevalEntry(45566, "WALLKIT_TOMB01_SMASHED08", "wallkit_tomb01_smashed08", "loctypes"),
            new GamevalEntry(45567, "WALLKIT_TOMB01_SMASHED09", "wallkit_tomb01_smashed09", "loctypes"),
        };
    }

    static Optional<GamevalEntry> byId(int id) {
        for (GamevalEntry entry : entries()) {
            if (entry.id() == id) return Optional.of(entry);
        }
        return Optional.empty();
    }

}
