package net.titan.gamevals.internal;

import java.util.Optional;

import net.titan.gamevals.GamevalEntry;
import net.titan.gamevals.QuestEntry;

final class ObjectIDEntries_117 {
    private ObjectIDEntries_117() {}

    static GamevalEntry[] entries() {
        return new GamevalEntry[] {
            new GamevalEntry(59978, "BOATKIT_DECK_STRAIGHT03_PIRATE", "boatkit_deck_straight03_pirate", "loctypes"),
            new GamevalEntry(59979, "BOATKIT_DECK_DIAGONAL01_PIRATE", "boatkit_deck_diagonal01_pirate", "loctypes"),
            new GamevalEntry(59980, "BOATKIT_DECK_DIAGONAL01_MIRROR_PIRATE", "boatkit_deck_diagonal01_mirror_pirate", "loctypes"),
            new GamevalEntry(59981, "BOATKIT_HELM01_PIRATE", "Ship's wheel", "loctypes"),
            new GamevalEntry(59982, "MOTD_CRATE", "Crate", "loctypes"),
            new GamevalEntry(59983, "MOTD_CORAL", "Coral Reef", "loctypes"),
            new GamevalEntry(59984, "MOTD_CAULDRON", "Cauldron", "loctypes"),
            new GamevalEntry(59985, "SAILORS_MARKER_ROBERTS", "Sailors' Marker", "loctypes"),
            new GamevalEntry(59986, "SAILORS_MARKER_REDROCK", "Sailors' Marker", "loctypes"),
            new GamevalEntry(59987, "SAILORS_MARKER_BARRACUDA", "Sailors' Marker", "loctypes"),
            new GamevalEntry(59988, "SAILORS_MARKER_DEEPFIN", "Sailors' Marker", "loctypes"),
            new GamevalEntry(59989, "LOST_SCHEMATIC_BOX_CHINCHOMPA_CLOSED", "Lockbox", "loctypes"),
            new GamevalEntry(59990, "LOST_SCHEMATIC_BOX_CHINCHOMPA_OPEN", "Lockbox", "loctypes"),
            new GamevalEntry(59991, "LOST_SCHEMATIC_BOX_ANGLERS_CLOSED", "Lockbox", "loctypes"),
            new GamevalEntry(59992, "LOST_SCHEMATIC_BOX_ANGLERS_OPEN", "Lockbox", "loctypes"),
            new GamevalEntry(59993, "LOST_SCHEMATIC_BOX_BUCCANEERS_CLOSED", "Lockbox", "loctypes"),
            new GamevalEntry(59994, "LOST_SCHEMATIC_BOX_BUCCANEERS_OPEN", "Lockbox", "loctypes"),
            new GamevalEntry(59995, "LOST_SCHEMATIC_BOX_LLEDRITH_CLOSED", "Lockbox", "loctypes"),
            new GamevalEntry(59996, "LOST_SCHEMATIC_BOX_LLEDRITH_OPEN", "Lockbox", "loctypes"),
            new GamevalEntry(59997, "LOST_SCHEMATIC_BOX_CROWNJEWEL_CLOSED", "Lockbox", "loctypes"),
            new GamevalEntry(59998, "LOST_SCHEMATIC_BOX_CROWNJEWEL_OPEN", "Lockbox", "loctypes"),
            new GamevalEntry(59999, "LOST_SCHEMATIC_BOX_DEEPFIN_CLOSED", "Lockbox", "loctypes"),
            new GamevalEntry(60000, "LOST_SCHEMATIC_BOX_DEEPFIN_OPEN", "Lockbox", "loctypes"),
            new GamevalEntry(60001, "LOST_SCHEMATIC_BOX_SHIMMERING_CLOSED", "Lockbox", "loctypes"),
            new GamevalEntry(60002, "LOST_SCHEMATIC_BOX_SHIMMERING_OPEN", "Lockbox", "loctypes"),
            new GamevalEntry(60003, "LOST_SCHEMATIC_BOX_BRITTLE_CLOSED", "Lockbox", "loctypes"),
            new GamevalEntry(60004, "LOST_SCHEMATIC_BOX_BRITTLE_OPEN", "Lockbox", "loctypes"),
            new GamevalEntry(60005, "LOST_SCHEMATIC_BOX_SUNBLEAK_CLOSED", "Lockbox", "loctypes"),
            new GamevalEntry(60006, "LOST_SCHEMATIC_BOX_SUNBLEAK_OPEN", "Lockbox", "loctypes"),
            new GamevalEntry(60007, "LOST_SCHEMATIC_BOX_GRIMSTONE_CLOSED", "Lockbox", "loctypes"),
            new GamevalEntry(60008, "LOST_SCHEMATIC_BOX_GRIMSTONE_OPEN", "Lockbox", "loctypes"),
            new GamevalEntry(60009, "GERARDUS_CHARRED_CHEST_CLOSED", "Old chest", "loctypes"),
            new GamevalEntry(60010, "GERARDUS_CHARRED_CHEST_OPEN", "Old chest", "loctypes"),
            new GamevalEntry(60011, "BRITTLE_ISLE_CAVE", "Cave", "loctypes"),
            new GamevalEntry(60012, "CHINCHOMPA_ISLAND_CAULDRON", "Cauldron", "loctypes"),
            new GamevalEntry(60013, "CHINCHOMPA_ISLAND_CUSHION", "Cushion", "loctypes"),
            new GamevalEntry(60014, "WRECKED_BOAT", "Wrecked boat", "loctypes"),
            new GamevalEntry(60015, "CROWN_JEWEL_CAVE_ENTRANCE", "Cave", "loctypes"),
            new GamevalEntry(60016, "CROWN_JEWEL_CAVE_ENTRANCE_CLOSED", "Cave", "loctypes"),
            new GamevalEntry(60017, "LAST_LIGHT_LIGHTHOUSE_COG", "Lighting mechanism", "loctypes"),
            new GamevalEntry(60018, "LAST_LIGHT_DOORWAY", "Door", "loctypes"),
            new GamevalEntry(60019, "LAST_LIGHT_DOORWAY_INACTIVE", "last_light_doorway_inactive", "loctypes"),
            new GamevalEntry(60020, "LAST_LIGHT_SPIRALSTAIRS_BASE", "Staircase", "loctypes"),
            new GamevalEntry(60021, "LAST_LIGHT_SPIRALSTAIRS_MIDDLE", "Staircase", "loctypes"),
            new GamevalEntry(60022, "LAST_LIGHT_SPIRALSTAIRS_MIDDLE_INACTIVE", "last_light_spiralstairs_middle_inactive", "loctypes"),
            new GamevalEntry(60023, "LAST_LIGHT_SPIRALSTAIRS_TOP", "Staircase", "loctypes"),
            new GamevalEntry(60024, "SAILING_WALL_POSTER_GENERIC01", "sailing_wall_poster_generic01", "loctypes"),
            new GamevalEntry(60025, "SAILING_WALL_POSTER_GENERIC02", "sailing_wall_poster_generic02", "loctypes"),
            new GamevalEntry(60026, "SAILING_WALL_POSTER_GENERIC03", "sailing_wall_poster_generic03", "loctypes"),
            new GamevalEntry(60027, "SAILING_WALL_POSTER_GENERIC04", "sailing_wall_poster_generic04", "loctypes"),
            new GamevalEntry(60028, "SAILING_SHODDY_BENCH", "Bench", "loctypes"),
            new GamevalEntry(60029, "SAILING_TABLE_1_NOOP", "Table", "loctypes"),
            new GamevalEntry(60030, "SAILING_WALL_CRUMBLY_LEFT", "sailing_wall_crumbly_left", "loctypes"),
            new GamevalEntry(60031, "SAILING_WALL_CRUMBLY_RIGHT", "sailing_wall_crumbly_right", "loctypes"),
            new GamevalEntry(60032, "SAILING_WALL_CRUMBLY2_LEFT", "sailing_wall_crumbly2_left", "loctypes"),
            new GamevalEntry(60033, "SAILING_WALL_CRUMBLY2_RIGHT", "sailing_wall_crumbly2_right", "loctypes"),
            new GamevalEntry(60034, "SAILING_WALL_CRUMBLY2_RIGHT_MIRRORED", "sailing_wall_crumbly2_right_mirrored", "loctypes"),
            new GamevalEntry(60035, "SAILING_WALL_CRUMBLY_RIGHT_MIRRORED", "sailing_wall_crumbly_right_mirrored", "loctypes"),
            new GamevalEntry(60036, "SAILING_WALL_DAMAGED", "sailing_wall_damaged", "loctypes"),
            new GamevalEntry(60037, "SAILING_WALL_DAMAGED2", "sailing_wall_damaged2", "loctypes"),
            new GamevalEntry(60038, "SAILING_WALL_DAMAGED3", "sailing_wall_damaged3", "loctypes"),
            new GamevalEntry(60039, "SAILING_WALL_CRUMBLY_DAMAGED_LEFT", "sailing_wall_crumbly_damaged_left", "loctypes"),
            new GamevalEntry(60040, "SAILING_WALL_CRUMBLY_DAMAGED_RIGHT", "sailing_wall_crumbly_damaged_right", "loctypes"),
            new GamevalEntry(60041, "FAI_LIGHTHOUSE_PLANKS1", "fai_lighthouse_planks1", "loctypes"),
            new GamevalEntry(60042, "FAI_LIGHTHOUSE_PLANKS2", "fai_lighthouse_planks2", "loctypes"),
            new GamevalEntry(60043, "DT2_LIGHTHOUSE_SPIDERWEB01", "dt2_lighthouse_spiderweb01", "loctypes"),
            new GamevalEntry(60044, "DT2_LIGHTHOUSE_SPIDERWEB02", "dt2_lighthouse_spiderweb02", "loctypes"),
            new GamevalEntry(60045, "DECOKIT_LIGHTHOUSE_WEB01_STRAIGHT04", "decokit_lighthouse_web01_straight04", "loctypes"),
            new GamevalEntry(60046, "DECOKIT_LIGHTHOUSE_WEB01_STRAIGHT05", "decokit_lighthouse_web01_straight05", "loctypes"),
            new GamevalEntry(60047, "SLUG2_LIGHTHOUSE_CRATE_STACK", "Stacked crates", "loctypes"),
            new GamevalEntry(60048, "ELEM_LIGHTHOUSE_CRATE_3", "Crates", "loctypes"),
            new GamevalEntry(60049, "PIRATE_LIGHTHOUSE_BARRELS", "Barrels", "loctypes"),
            new GamevalEntry(60050, "LUNAR_LIGHTHOUSE_LOW_TABLE", "Table", "loctypes"),
            new GamevalEntry(60051, "LUNAR_LIGHTHOUSE_LOW_TABLE_NO_OFFSET", "Table", "loctypes"),
            new GamevalEntry(60052, "PIRATE_FISH_TABLE", "Table", "loctypes"),
            new GamevalEntry(60053, "PIRATE_FISH_TABLE_OFFSET", "Table", "loctypes"),
            new GamevalEntry(60054, "PIRATE_CRATE_1", "Crate", "loctypes"),
            new GamevalEntry(60055, "PIRATE_SEA_GRAVE", "Grave", "loctypes"),
            new GamevalEntry(60056, "PIRATE_SACKS_KNIFE", "Sacks", "loctypes"),
            new GamevalEntry(60057, "PIRATE_SACKS", "Sacks", "loctypes"),
            new GamevalEntry(60058, "PIRATE_SACKS_2", "Sacks", "loctypes"),
            new GamevalEntry(60059, "PIRATE_BARREL", "Barrel", "loctypes"),
            new GamevalEntry(60060, "PIRATE_CRATE_EMPTY", "Crate", "loctypes"),
            new GamevalEntry(60061, "PIRATE_TORTURE_TABLE", "Table", "loctypes"),
            new GamevalEntry(60062, "PIRATE_CHAIN", "Chain", "loctypes"),
            new GamevalEntry(60063, "DWARF_LIGHTHOUSE_METAL_CRATE_WITHPAPERS", "Crate", "loctypes"),
            new GamevalEntry(60064, "DWARF_LIGHTHOUSE_METAL_CRATES", "Crates", "loctypes"),
            new GamevalEntry(60065, "LIGHTHOUSE_IVY01_LARGE01", "lighthouse_ivy01_large01", "loctypes"),
            new GamevalEntry(60066, "LIGHTHOUSE_IVY01_MEDIUM01", "lighthouse_ivy01_medium01", "loctypes"),
            new GamevalEntry(60067, "LIGHTHOUSE_IVY01_SMALL02", "lighthouse_ivy01_small02", "loctypes"),
            new GamevalEntry(60068, "AREA_LIGHTHOUSE_GHETTO_SHELF5", "area_lighthouse_ghetto_shelf5", "loctypes"),
            new GamevalEntry(60069, "LIGHTHOUSE_WALL_POSTER_GENERIC01_SLOPED", "lighthouse_wall_poster_generic01_sloped", "loctypes"),
            new GamevalEntry(60070, "LIGHTHOUSE_WALL_POSTER_GENERIC02_SLOPED", "lighthouse_wall_poster_generic02_sloped", "loctypes"),
            new GamevalEntry(60071, "LIGHTHOUSE_WALL_POSTER_GENERIC03_SLOPED", "lighthouse_wall_poster_generic03_sloped", "loctypes"),
            new GamevalEntry(60072, "LIGHTHOUSE_WALL_POSTER_GENERIC04_SLOPED", "lighthouse_wall_poster_generic04_sloped", "loctypes"),
            new GamevalEntry(60073, "SAILING_ISLANDS_DRAGON_ISLAND_DUNGEON_ENTRANCE_MULTILOC", "sailing_islands_dragon_island_dungeon_entrance_multiloc", "loctypes"),
            new GamevalEntry(60074, "SAILING_ISLANDS_DRAGON_ISLAND_DUNGEON_ENTRANCE_NO_ROPE", "Dark hole", "loctypes"),
            new GamevalEntry(60075, "SAILING_ISLANDS_DRAGON_ISLAND_DUNGEON_ENTRANCE_ROPED", "Dark hole", "loctypes"),
            new GamevalEntry(60076, "SAILING_ISLANDS_DRAGON_ISLAND_DUNGEON_EXIT", "Climb-up", "loctypes"),
            new GamevalEntry(60077, "CAVEKIT_ROCK01_DEFAULT05", "cavekit_rock01_default05", "loctypes"),
            new GamevalEntry(60078, "CAVEKIT_ROCK01_DEFAULT05_WALLTOP", "cavekit_rock01_default05_walltop", "loctypes"),
            new GamevalEntry(60079, "CAVEKIT_ROCK01_DEFAULT05_STALAGMITES", "cavekit_rock01_default05_stalagmites", "loctypes"),
            new GamevalEntry(60080, "CAVEKIT_ROCK01_DEFAULT05_STALAGMITES_LARGE", "cavekit_rock01_default05_stalagmites_large", "loctypes"),
            new GamevalEntry(60081, "CAVEKIT_ROCK01_DEFAULT05_STALAGMITES_TWIN", "cavekit_rock01_default05_stalagmites_twin", "loctypes"),
            new GamevalEntry(60082, "CAVEKIT_ROCK01_DEFAULT05_STALAGMITES_FALLOFF", "cavekit_rock01_default05_stalagmites_falloff", "loctypes"),
            new GamevalEntry(60083, "CAVEKIT_ROCK01_DEFAULT05_STALAGMITES_TALL", "cavekit_rock01_default05_stalagmites_tall", "loctypes"),
            new GamevalEntry(60084, "CAVEKIT_ROCK01_DEFAULT05_STALAGMITES_LARGE_TALL", "cavekit_rock01_default05_stalagmites_large_tall", "loctypes"),
            new GamevalEntry(60085, "CAVEKIT_ROCK01_DEFAULT05_STALAGMITES_TWIN_TALL", "cavekit_rock01_default05_stalagmites_twin_tall", "loctypes"),
            new GamevalEntry(60086, "CAVEKIT_ROCK01_DEFAULT05_STALAGMITES_FALLOFF_TALL", "cavekit_rock01_default05_stalagmites_falloff_tall", "loctypes"),
            new GamevalEntry(60087, "CAVEKIT_ROCK01_DEFAULT05_STALAGMITES_LARGE_BIG", "cavekit_rock01_default05_stalagmites_large_big", "loctypes"),
            new GamevalEntry(60088, "CAVEKIT_ROCK01_DEFAULT05_STALAGMITES_TWIN_BIG", "cavekit_rock01_default05_stalagmites_twin_big", "loctypes"),
            new GamevalEntry(60089, "SAILING_ISLANDS_DRAGON_ISLAND_DUNGEON_CHEST_CLOSED", "Chest", "loctypes"),
            new GamevalEntry(60090, "SAILING_ISLANDS_DRAGON_ISLAND_DUNGEON_CHEST_OPEN", "Chest", "loctypes"),
            new GamevalEntry(60091, "TREE_PINE_LIGHTFROST01", "Pine tree", "loctypes"),
            new GamevalEntry(60092, "TREE_PINE_LIGHTFROST01_NOFERN", "Pine tree", "loctypes"),
            new GamevalEntry(60093, "HAVEN_BASEMENT_TRAPDOOR", "Ladder", "loctypes"),
            new GamevalEntry(60094, "HAVEN_TOWER_BASEMENT_LADDER", "Ladder", "loctypes"),
            new GamevalEntry(60095, "HAVEN_TOWER_BASEMENT_WALL_STONE", "haven_tower_basement_wall_stone", "loctypes"),
            new GamevalEntry(60096, "HAVEN_TOWER_BASEMENT_WALL_STONE_CAVE_JOIN", "haven_tower_basement_wall_stone_cave_join", "loctypes"),
            new GamevalEntry(60097, "HAVEN_TOWER_BASEMENT_WALL_STONE_CAVE_JOIN_MIRROR", "haven_tower_basement_wall_stone_cave_join_mirror", "loctypes"),
            new GamevalEntry(60098, "HAVEN_TOWER_BASEMENT_WALL_STONE_CAVE_MID", "haven_tower_basement_wall_stone_cave_mid", "loctypes"),
            new GamevalEntry(60099, "HAVEN_TOWER_BASEMENT_WALL_STONE_CAVE_SUPPORT_RIGHT", "haven_tower_basement_wall_stone_cave_support_right", "loctypes"),
            new GamevalEntry(60100, "HAVEN_TOWER_BASEMENT_WALL_STONE_CAVE_SUPPORT_LEFT", "haven_tower_basement_wall_stone_cave_support_left", "loctypes"),
            new GamevalEntry(60101, "HAVEN_TOWER_BASEMENT_WALL_STONE_CAVE_SUPPORT_MID", "haven_tower_basement_wall_stone_cave_support_mid", "loctypes"),
            new GamevalEntry(60102, "HAVEN_TOWER_BASEMENT_WALL_STONE_CAVE_SUPPORT_MID_POST", "haven_tower_basement_wall_stone_cave_support_mid_post", "loctypes"),
            new GamevalEntry(60103, "HAVEN_TOWER_BASEMENT_CAGE_SMALL", "Cage", "loctypes"),
            new GamevalEntry(60104, "HAVEN_TOWER_BASEMENT_CAGE_SMALL_BROKEN", "Cage", "loctypes"),
            new GamevalEntry(60105, "HAVEN_TOWER_BASEMENT_CAGE_TALL", "Cage", "loctypes"),
            new GamevalEntry(60106, "HAVEN_TOWER_BASEMENT_CAGE_TALL_BROKEN", "Cage", "loctypes"),
            new GamevalEntry(60107, "HAVEN_TOWER_BASEMENT_TABLE_TOOLS", "Equipment table", "loctypes"),
            new GamevalEntry(60108, "HAVEN_TOWER_BASEMENT_TABLE_TOOLS_BROKEN", "Broken equipment table", "loctypes"),
            new GamevalEntry(60109, "HAVEN_TOWER_BASEMENT_TABLE_RESTRAINT", "Restraining table", "loctypes"),
            new GamevalEntry(60110, "HAVEN_TOWER_BASEMENT_TABLE_RESTRAINT_SKELETON", "Restraint table", "loctypes"),
            new GamevalEntry(60111, "GRIMSTONE_FURNACE", "Ancient Furnace", "loctypes"),
            new GamevalEntry(60112, "GRIMSTONE_CANNONBALLS_NOOP", "Cannonballs", "loctypes"),
            new GamevalEntry(60113, "GRIMSTONE_CANNONBALL_MOULD", "Cannonball mould", "loctypes"),
            new GamevalEntry(60114, "GRIMSTONE_ANCIENT_MOULD", "Ancient mould", "loctypes"),
            new GamevalEntry(60115, "GRIMSTONE_SHADOW_HANDS", "grimstone_shadow_hands", "loctypes"),
            new GamevalEntry(60116, "GRIMSTONE_SHADOW_HANDS_VIS", "grimstone_shadow_hands_vis", "loctypes"),
            new GamevalEntry(60117, "GRIMSTONE_CAVE_ENTRANCE", "Cave entrance", "loctypes"),
            new GamevalEntry(60118, "GRIMSTONE_CAVE_EXIT", "Cave exit", "loctypes"),
            new GamevalEntry(60119, "GRIMSTONE_SHORTCUT_NORTH", "Large stone ledges", "loctypes"),
            new GamevalEntry(60120, "GRIMSTONE_SHORTCUT_SOUTH", "Uneven stone ledges", "loctypes"),
            new GamevalEntry(60121, "GRIMSTONE_SKELETON", "Skeleton", "loctypes"),
            new GamevalEntry(60122, "GRIMSTONE_PLINTH", "Plinth", "loctypes"),
            new GamevalEntry(60123, "GRIMSTONE_CAVE_WALL_UPPER", "grimstone_cave_wall_upper", "loctypes"),
            new GamevalEntry(60124, "GRIMSTONE_SPEARWALL", "grimstone_spearwall", "loctypes"),
            new GamevalEntry(60125, "GRIMSTONE_SPEARWALL2", "grimstone_spearwall2", "loctypes"),
            new GamevalEntry(60126, "ANGLERS_RETREAT_SHORTCUT", "Rocky outcrop", "loctypes"),
            new GamevalEntry(60127, "LAGUNA_AURORAE_SHORTCUT_1", "Rocky outcrop", "loctypes"),
            new GamevalEntry(60128, "LAGUNA_AURORAE_SHORTCUT_2", "Rocky outcrop", "loctypes"),
            new GamevalEntry(60129, "SUNBLEAK_CAVE_ENTRANCE", "Cave entrance", "loctypes"),
            new GamevalEntry(60130, "SUNBLEAK_SEAGULL_NEST", "Seagull nest", "loctypes"),
            new GamevalEntry(60131, "SUNBLEAK_SPADE_BROWN", "sunbleak_spade_brown", "loctypes"),
            new GamevalEntry(60132, "SUNBLEAK_MINING_STONE_PICK_NOOP", "Rock", "loctypes"),
            new GamevalEntry(60133, "SUNBLEAK_CAVE_ROCKS_1", "sunbleak_cave_rocks_1", "loctypes"),
            new GamevalEntry(60134, "SUNBLEAK_CAVE_ROCKS_2", "sunbleak_cave_rocks_2", "loctypes"),
            new GamevalEntry(60135, "SUNBLEAK_CAVE_ROCKS_3", "sunbleak_cave_rocks_3", "loctypes"),
            new GamevalEntry(60136, "SUNBLEAK_CAVE_ROCKS_2X2_1", "sunbleak_cave_rocks_2x2_1", "loctypes"),
            new GamevalEntry(60137, "SUNBLEAK_CAVE_ROCKS_2X2_2", "sunbleak_cave_rocks_2x2_2", "loctypes"),
            new GamevalEntry(60138, "SUNBLEAK_CAVE_ROCKS_2X2_3", "sunbleak_cave_rocks_2x2_3", "loctypes"),
            new GamevalEntry(60139, "SUNBLEAK_CAVE_STALAGMITE_1", "sunbleak_cave_stalagmite_1", "loctypes"),
            new GamevalEntry(60140, "SUNBLEAK_CAVE_STALAGMITE_2", "sunbleak_cave_stalagmite_2", "loctypes"),
            new GamevalEntry(60141, "SUNBLEAK_CAVE_WALL_OUTER", "sunbleak_cave_wall_outer", "loctypes"),
            new GamevalEntry(60142, "SUNBLEAK_CAVE_WALL_UPPER", "sunbleak_cave_wall_upper", "loctypes"),
            new GamevalEntry(60143, "SUNBLEAK_CAVE_WALL_UPPER_ACTIVE", "Wall", "loctypes"),
            new GamevalEntry(60144, "SUNBLEAK_DUNGEON_EXIT", "Opening", "loctypes"),
            new GamevalEntry(60145, "DEEPFIN_FURNACE", "Furnace", "loctypes"),
            new GamevalEntry(60146, "DEEPFIN_CAVE_SHORTCUT", "Crevice", "loctypes"),
            new GamevalEntry(60147, "DEEPFIN_BUNKBED", "Bunkbed", "loctypes"),
            new GamevalEntry(60148, "DEEPFIN_MINING_MACHINE", "Machinery", "loctypes"),
            new GamevalEntry(60149, "DEEPFIN_MINING_BUOY", "Buoy", "loctypes"),
            new GamevalEntry(60150, "DEEPFIN_TRACKBUFFER", "Buffers", "loctypes"),
            new GamevalEntry(60151, "DEEPFIN_TRACKSTRAIGHT_GDECOR", "deepfin_trackstraight_gdecor", "loctypes"),
            new GamevalEntry(60152, "DEEPFIN_TRACK_CURVE_A", "deepfin_track_curve_a", "loctypes"),
            new GamevalEntry(60153, "DEEPFIN_TRACK_CURVE_B", "deepfin_track_curve_b", "loctypes"),
            new GamevalEntry(60154, "DEEPFIN_TRACK_CURVE_C", "deepfin_track_curve_c", "loctypes"),
            new GamevalEntry(60155, "DEEPFIN_TRACK_CURVE_D", "deepfin_track_curve_d", "loctypes"),
            new GamevalEntry(60156, "DEEPFIN_TRACK_POINTS_A", "deepfin_track_points_a", "loctypes"),
            new GamevalEntry(60157, "DEEPFIN_TRACK_POINTS_B", "deepfin_track_points_b", "loctypes"),
            new GamevalEntry(60158, "DEEPFIN_TRACK_POINTS_C", "deepfin_track_points_c", "loctypes"),
            new GamevalEntry(60159, "DEEPFIN_TRACK_POINTS_D", "deepfin_track_points_d", "loctypes"),
            new GamevalEntry(60160, "DEEPFIN_TRACK_POINTS_A_MIRRORED", "deepfin_track_points_a_mirrored", "loctypes"),
            new GamevalEntry(60161, "DEEPFIN_TRACK_POINTS_B_MIRRORED", "deepfin_track_points_b_mirrored", "loctypes"),
            new GamevalEntry(60162, "DEEPFIN_TRACK_POINTS_C_MIRRORED", "deepfin_track_points_c_mirrored", "loctypes"),
            new GamevalEntry(60163, "DEEPFIN_TRACK_POINTS_D_MIRRORED", "deepfin_track_points_d_mirrored", "loctypes"),
            new GamevalEntry(60164, "DEEPFIN_MINECART_FULL", "Mine cart", "loctypes"),
            new GamevalEntry(60165, "DEEPFIN_MINECART_EMPTY", "Mine cart", "loctypes"),
            new GamevalEntry(60166, "DEEPFIN_CAVE_ENTRANCE", "Cave", "loctypes"),
            new GamevalEntry(60167, "DEEPFIN_CAVE_EXIT", "Exit", "loctypes"),
            new GamevalEntry(60168, "YNYSDAIL_CAVE_WALL_LOWER", "ynysdail_cave_wall_lower", "loctypes"),
            new GamevalEntry(60169, "YNYSDAIL_CAVE_ENTRANCE", "Cave entrance", "loctypes"),
            new GamevalEntry(60170, "YNYSDAIL_CAVE_EXIT", "Cave exit", "loctypes"),
            new GamevalEntry(60171, "YNYSDAIL_STALAGTITE_01", "ynysdail_stalagtite_01", "loctypes"),
            new GamevalEntry(60172, "YNYSDAIL_STALAGTITE_02", "ynysdail_stalagtite_02", "loctypes"),
            new GamevalEntry(60173, "MINOTAURS_REST_CAVE_ENTRANCE", "Cave entrance", "loctypes"),
            new GamevalEntry(60174, "MINOTAURS_REST_CAVE_EXIT", "Opening", "loctypes"),
            new GamevalEntry(60175, "MINOTAURS_REST_CAVE_WALL_LOWER", "minotaurs_rest_cave_wall_lower", "loctypes"),
            new GamevalEntry(60176, "MINOTAURS_REST_CAVE_WALL_UPPER", "minotaurs_rest_cave_wall_upper", "loctypes"),
            new GamevalEntry(60177, "MINOTAURS_REST_CAVE_WALL_UPPER_ACTIVE", "minotaurs_rest_cave_wall_upper_active", "loctypes"),
            new GamevalEntry(60178, "MINOTAURS_REST_CAVE_WALL_TOP", "minotaurs_rest_cave_wall_top", "loctypes"),
            new GamevalEntry(60179, "MINOTAURS_REST_CAMPFIRE", "Fire", "loctypes"),
            new GamevalEntry(60180, "MINOTAURS_REST_COOKING_TABLE", "Table", "loctypes"),
            new GamevalEntry(60181, "MINOTAURS_REST_BED", "Bed", "loctypes"),
            new GamevalEntry(60182, "WALLKIT_HIDEOUT01_DEFAULT01", "wallkit_hideout01_default01", "loctypes"),
            new GamevalEntry(60183, "WALLKIT_HIDEOUT01_DAMAGED01", "wallkit_hideout01_damaged01", "loctypes"),
            new GamevalEntry(60184, "WALLKIT_HIDEOUT01_DAMAGED02", "wallkit_hideout01_damaged02", "loctypes"),
            new GamevalEntry(60185, "WALLKIT_HIDEOUT01_WINDOW01", "wallkit_hideout01_window01", "loctypes"),
            new GamevalEntry(60186, "WALLKIT_HIDEOUT01_DOOR01", "Door", "loctypes"),
            new GamevalEntry(60187, "PLANT_WATER_LILYPAD04", "plant_water_lilypad04", "loctypes"),
            new GamevalEntry(60188, "PLANT_WATER_LILYPAD05", "plant_water_lilypad05", "loctypes"),
            new GamevalEntry(60189, "PLANT_WATER_LILYPAD06", "plant_water_lilypad06", "loctypes"),
            new GamevalEntry(60190, "HIDEOUT_LANTERN01_DEFAULT01", "hideout_lantern01_default01", "loctypes"),
            new GamevalEntry(60191, "HIDEOUT_SKULL_DEFAULT01", "Skull", "loctypes"),
            new GamevalEntry(60192, "LAGUNA_ROCKSLIDE_MUDDY01", "Rockslide", "loctypes"),
            new GamevalEntry(60193, "LAGUNA_ROCKSLIDE_MUDDY02", "Rockslide", "loctypes"),
            new GamevalEntry(60194, "LAGUNA_ROCKSLIDE_MUDDY03", "Rockslide", "loctypes"),
            new GamevalEntry(60195, "LAGUNA_ROCKSLIDE_MUDDY04", "Rockslide", "loctypes"),
            new GamevalEntry(60196, "LAGUNA_DUGUPSOIL01_MUD01", "laguna_dugupsoil01_mud01", "loctypes"),
            new GamevalEntry(60197, "LAGUNA_DUGUPSOIL02_MUD01", "laguna_dugupsoil02_mud01", "loctypes"),
            new GamevalEntry(60198, "LAGUNA_DUGUPSOIL03_MUD01", "laguna_dugupsoil03_mud01", "loctypes"),
            new GamevalEntry(60199, "LAGUNA_DUGUPSOIL01_SAND01", "laguna_dugupsoil01_sand01", "loctypes"),
            new GamevalEntry(60200, "LAGUNA_DUGUPSOIL02_SAND01", "laguna_dugupsoil02_sand01", "loctypes"),
            new GamevalEntry(60201, "LAGUNA_DUGUPSOIL03_SAND01", "laguna_dugupsoil03_sand01", "loctypes"),
            new GamevalEntry(60202, "LAGUNA_CAVE_ENTRANCE", "Cave entrance", "loctypes"),
            new GamevalEntry(60203, "LAGUNA_CAVE_EXIT", "Cave exit", "loctypes"),
            new GamevalEntry(60204, "RED_ROCK_TABLE01_1X1", "Table of coral", "loctypes"),
            new GamevalEntry(60205, "RED_ROCK_TABLE01_1X2", "Table", "loctypes"),
            new GamevalEntry(60206, "RED_ROCK_TABLE01_1X3", "Table of coral", "loctypes"),
            new GamevalEntry(60207, "RED_ROCK_TABLE01_2X3", "Table of coral", "loctypes"),
            new GamevalEntry(60208, "RED_ROCK_CRATE01_SINGLE01", "Crate", "loctypes"),
            new GamevalEntry(60209, "RED_ROCK_CRATE01_STACKED01", "Crates", "loctypes"),
            new GamevalEntry(60210, "RED_ROCK_CRATE02", "Crate", "loctypes"),
            new GamevalEntry(60211, "RED_ROCK_CRATE02_WIDE", "Crate", "loctypes"),
            new GamevalEntry(60212, "RED_ROCK_CRATE03", "Crate", "loctypes"),
            new GamevalEntry(60213, "RED_ROCK_PALLET01_BAG01", "Pallets", "loctypes"),
            new GamevalEntry(60214, "RED_ROCK_PALLET02_BAG01", "Pallets", "loctypes"),
            new GamevalEntry(60215, "RED_ROCK_PALLET02_LEANING01", "Pallets", "loctypes"),
            new GamevalEntry(60216, "RED_ROCK_PALLET02_LEANING01_OFFSET_X", "Pallets", "loctypes"),
            new GamevalEntry(60217, "RED_ROCK_PALLET02_LEANING01_OFFSET_Z", "Pallets", "loctypes"),
            new GamevalEntry(60218, "RED_ROCK_RUBBISH01", "red_rock_rubbish01", "loctypes"),
            new GamevalEntry(60219, "RED_ROCK_RUBBISH02", "red_rock_rubbish02", "loctypes"),
            new GamevalEntry(60220, "RED_ROCK_FLOOR_CLOTH01", "Cloth", "loctypes"),
            new GamevalEntry(60221, "WALLKIT_RED_ROCK_DOOR01_CLOSED_R", "Door", "loctypes"),
            new GamevalEntry(60222, "WALLKIT_RED_ROCK_DOOR01_CLOSED_L", "Door", "loctypes"),
            new GamevalEntry(60223, "WALLKIT_RED_ROCK_DOOR01_OPEN_R", "Door", "loctypes"),
            new GamevalEntry(60224, "WALLKIT_RED_ROCK_DOOR01_OPEN_L", "Door", "loctypes"),
            new GamevalEntry(60225, "WALLKIT_RED_ROCK_DOOR01_OPEN_NOOP", "Door", "loctypes"),
            new GamevalEntry(60226, "WALLKIT_RED_ROCK_DOOR01_OPEN_R_NOOP", "Door", "loctypes"),
            new GamevalEntry(60227, "WALLKIT_RED_ROCK_DOOR01_OPEN_L_NOOP", "Door", "loctypes"),
            new GamevalEntry(60228, "WALLKIT_RED_ROCK_DOOR01_LOCKED", "Door", "loctypes"),
            new GamevalEntry(60229, "WALLKIT_RED_ROCK_WALL01", "wallkit_red_rock_wall01", "loctypes"),
            new GamevalEntry(60230, "WALLKIT_RED_ROCK_WALL01_RESIZE01", "wallkit_red_rock_wall01_resize01", "loctypes"),
            new GamevalEntry(60231, "WALLKIT_RED_ROCK_INTERNAL01_WALL01", "wallkit_red_rock_internal01_wall01", "loctypes"),
            new GamevalEntry(60232, "WALLKIT_RED_ROCK_WINDOW01", "wallkit_red_rock_window01", "loctypes"),
            new GamevalEntry(60233, "WALLKIT_RED_ROCK_PULLEY01", "wallkit_red_rock_pulley01", "loctypes"),
            new GamevalEntry(60234, "SKEWSTEPS_WOOD01_REDROCK01", "skewsteps_wood01_redrock01", "loctypes"),
            new GamevalEntry(60235, "LAGUNA_STALAGMITE_CAVE01", "laguna_stalagmite_cave01", "loctypes"),
            new GamevalEntry(60236, "LAGUNA_STALAGMITE_CAVE02", "laguna_stalagmite_cave02", "loctypes"),
            new GamevalEntry(60237, "LAGUNA_STALAGMITE_FALLOFF01", "laguna_stalagmite_falloff01", "loctypes"),
            new GamevalEntry(60238, "LAGUNA_PLANT_SWAMP01", "laguna_plant_swamp01", "loctypes"),
            new GamevalEntry(60239, "LAGUNA_PLANT_SWAMP02", "laguna_plant_swamp02", "loctypes"),
            new GamevalEntry(60240, "SAILING_NPC_BOAT_BASIC_CANNON", "Iron cannon", "loctypes"),
            new GamevalEntry(60241, "SAILING_NPC_BOAT_BASIC_SMALL_HELM", "Helm", "loctypes"),
            new GamevalEntry(60242, "SAILING_NPC_BOAT_BASIC_MEDIUM_HELM", "Helm", "loctypes"),
            new GamevalEntry(60243, "SAILING_NPC_BOAT_BASIC_SMALL_SAIL", "Sails", "loctypes"),
            new GamevalEntry(60244, "SAILING_NPC_BOAT_BASIC_MEDIUM_SAIL", "sailing_npc_boat_basic_medium_sail", "loctypes"),
            new GamevalEntry(60245, "SAILING_BOAT_CARGO_HOLD_REGULAR_RAFT", "sailing_boat_cargo_hold_regular_raft", "loctypes"),
            new GamevalEntry(60246, "DEADMAN_RARE_CHEST_SPAWN", "Deadman's chest", "loctypes"),
            new GamevalEntry(60247, "SAILING_BOAT_CARGO_HOLD_OAK_RAFT", "sailing_boat_cargo_hold_oak_raft", "loctypes"),
            new GamevalEntry(60248, "DEADMAN_RARE_CHEST_IDLE", "Deadman's chest", "loctypes"),
            new GamevalEntry(60249, "SAILING_BOAT_CARGO_HOLD_TEAK_RAFT", "sailing_boat_cargo_hold_teak_raft", "loctypes"),
            new GamevalEntry(60250, "DEADMAN_RARE_CHEST_OPENED", "Deadman's chest", "loctypes"),
            new GamevalEntry(60251, "SAILING_BOAT_CARGO_HOLD_MAHOGANY_RAFT", "sailing_boat_cargo_hold_mahogany_raft", "loctypes"),
            new GamevalEntry(60252, "DEADMAN_POH_WALL", "deadman_poh_wall", "loctypes"),
            new GamevalEntry(60253, "SAILING_BOAT_CARGO_HOLD_CAMPHOR_RAFT", "sailing_boat_cargo_hold_camphor_raft", "loctypes"),
            new GamevalEntry(60254, "DEADMAN_POH_WINDOW", "deadman_poh_window", "loctypes"),
            new GamevalEntry(60255, "SAILING_BOAT_CARGO_HOLD_IRONWOOD_RAFT", "sailing_boat_cargo_hold_ironwood_raft", "loctypes"),
            new GamevalEntry(60256, "DEADMAN_POH_WALL_CRUMBLY01_L", "deadman_poh_wall_crumbly01_l", "loctypes"),
            new GamevalEntry(60257, "SAILING_BOAT_CARGO_HOLD_ROSEWOOD_RAFT", "sailing_boat_cargo_hold_rosewood_raft", "loctypes"),
            new GamevalEntry(60258, "DEADMAN_POH_WALL_CRUMBLY01_R", "deadman_poh_wall_crumbly01_r", "loctypes"),
            new GamevalEntry(60259, "SAILING_BOAT_CARGO_HOLD_REGULAR_2X5", "sailing_boat_cargo_hold_regular_2x5", "loctypes"),
            new GamevalEntry(60260, "DEADMAN_POH_WALL_CRUMBLY02_L", "deadman_poh_wall_crumbly02_l", "loctypes"),
            new GamevalEntry(60261, "SAILING_BOAT_CARGO_HOLD_OAK_2X5", "sailing_boat_cargo_hold_oak_2x5", "loctypes"),
            new GamevalEntry(60262, "DEADMAN_POH_WALL_CRUMBLY02_R", "deadman_poh_wall_crumbly02_r", "loctypes"),
            new GamevalEntry(60263, "SAILING_BOAT_CARGO_HOLD_TEAK_2X5", "sailing_boat_cargo_hold_teak_2x5", "loctypes"),
            new GamevalEntry(60264, "DEADMAN_POH_WALL_CRUMBLY03_L", "deadman_poh_wall_crumbly03_l", "loctypes"),
            new GamevalEntry(60265, "SAILING_BOAT_CARGO_HOLD_MAHOGANY_2X5", "sailing_boat_cargo_hold_mahogany_2x5", "loctypes"),
            new GamevalEntry(60266, "DEADMAN_POH_WALL_CRUMBLY03_R", "deadman_poh_wall_crumbly03_r", "loctypes"),
            new GamevalEntry(60267, "SAILING_BOAT_CARGO_HOLD_CAMPHOR_2X5", "sailing_boat_cargo_hold_camphor_2x5", "loctypes"),
            new GamevalEntry(60268, "DEADMAN_RUBBLE01", "deadman_rubble01", "loctypes"),
            new GamevalEntry(60269, "SAILING_BOAT_CARGO_HOLD_IRONWOOD_2X5", "sailing_boat_cargo_hold_ironwood_2x5", "loctypes"),
            new GamevalEntry(60270, "DEADMAN_RUBBLE02", "deadman_rubble02", "loctypes"),
            new GamevalEntry(60271, "SAILING_BOAT_CARGO_HOLD_ROSEWOOD_2X5", "sailing_boat_cargo_hold_rosewood_2x5", "loctypes"),
            new GamevalEntry(60272, "POH_FLOORDECOR_DEADMAN", "poh_floordecor_deadman", "loctypes"),
            new GamevalEntry(60273, "SAILING_BOAT_CARGO_HOLD_REGULAR_LARGE", "sailing_boat_cargo_hold_regular_large", "loctypes"),
            new GamevalEntry(60274, "DEADMAN_DUNGEON_INSIDEWALL_CORNER", "deadman_dungeon_insidewall_corner", "loctypes"),
            new GamevalEntry(60275, "SAILING_BOAT_CARGO_HOLD_OAK_LARGE", "sailing_boat_cargo_hold_oak_large", "loctypes"),
            new GamevalEntry(60276, "DEADMAN_DUNGEON_OUTSIDEWALL_CORNER", "deadman_dungeon_outsidewall_corner", "loctypes"),
            new GamevalEntry(60277, "SAILING_BOAT_CARGO_HOLD_TEAK_LARGE", "sailing_boat_cargo_hold_teak_large", "loctypes"),
            new GamevalEntry(60278, "DEADMAN_DUNGEON_OUTSIDEWALL_LCORNER", "deadman_dungeon_outsidewall_lcorner", "loctypes"),
            new GamevalEntry(60279, "SAILING_BOAT_CARGO_HOLD_MAHOGANY_LARGE", "sailing_boat_cargo_hold_mahogany_large", "loctypes"),
            new GamevalEntry(60280, "DEADMAN_DUNGEON_OUTSIDEWALL_RCORNER", "deadman_dungeon_outsidewall_rcorner", "loctypes"),
            new GamevalEntry(60281, "SAILING_BOAT_CARGO_HOLD_CAMPHOR_LARGE", "sailing_boat_cargo_hold_camphor_large", "loctypes"),
            new GamevalEntry(60282, "DEADMAN_DUNGEON_WALLTOP", "deadman_dungeon_walltop", "loctypes"),
            new GamevalEntry(60283, "SAILING_BOAT_CARGO_HOLD_IRONWOOD_LARGE", "sailing_boat_cargo_hold_ironwood_large", "loctypes"),
            new GamevalEntry(60284, "DEADMAN_DUNGEON_OUTSIDEWALL", "deadman_dungeon_outsidewall", "loctypes"),
            new GamevalEntry(60285, "SAILING_BOAT_CARGO_HOLD_ROSEWOOD_LARGE", "sailing_boat_cargo_hold_rosewood_large", "loctypes"),
            new GamevalEntry(60286, "DEADMAN_DUNGEON_INSIDEWALL", "deadman_dungeon_insidewall", "loctypes"),
            new GamevalEntry(60287, "PORT_TASK_BOARD_PORT_SARIM", "Notice board", "loctypes"),
            new GamevalEntry(60288, "PORT_TASK_BOARD_PANDEMONIUM", "Notice board", "loctypes"),
            new GamevalEntry(60289, "PORT_TASK_BOARD_CATHERBY", "Notice board", "loctypes"),
            new GamevalEntry(60290, "PORT_TASK_BOARD_PORT_KHAZARD", "Notice board", "loctypes"),
            new GamevalEntry(60291, "PORT_TASK_BOARD_RUINS_OF_UNKAH", "Notice board", "loctypes"),
            new GamevalEntry(60292, "PORT_TASK_BOARD_RELLEKKA", "Notice board", "loctypes"),
            new GamevalEntry(60293, "PORT_TASK_BOARD_PORT_PISCARILIUS", "Notice board", "loctypes"),
            new GamevalEntry(60294, "PORT_TASK_BOARD_CIVITAS_ILLA_FORTIS", "Notice board", "loctypes"),
            new GamevalEntry(60295, "PORT_TASK_BOARD_LANDS_END", "Notice board", "loctypes"),
            new GamevalEntry(60296, "PORT_TASK_BOARD_MUSA_POINT", "Notice board", "loctypes"),
            new GamevalEntry(60297, "PORT_TASK_BOARD_ARDOUGNE", "Notice board", "loctypes"),
            new GamevalEntry(60298, "PORT_TASK_BOARD_BRIMHAVEN", "Notice board", "loctypes"),
            new GamevalEntry(60299, "PORT_TASK_BOARD_CORSAIR_COVE", "Notice board", "loctypes"),
            new GamevalEntry(60300, "PORT_TASK_BOARD_THE_SUMMER_SHORE", "Notice board", "loctypes"),
            new GamevalEntry(60301, "PORT_TASK_BOARD_ALDARIN", "Notice board", "loctypes"),
            new GamevalEntry(60302, "PORT_TASK_BOARD_VOID_KNIGHTS_OUTPOST", "Notice board", "loctypes"),
            new GamevalEntry(60303, "PORT_TASK_BOARD_PORT_ROBERTS", "Notice board", "loctypes"),
            new GamevalEntry(60304, "PORT_TASK_BOARD_RED_ROCK", "Notice board", "loctypes"),
            new GamevalEntry(60305, "PORT_TASK_BOARD_ETCETERIA", "Notice board", "loctypes"),
            new GamevalEntry(60306, "PORT_TASK_BOARD_PORT_TYRAS", "Notice board", "loctypes"),
            new GamevalEntry(60307, "PORT_TASK_BOARD_DEEPFIN_POINT", "Notice board", "loctypes"),
            new GamevalEntry(60308, "PORT_TASK_BOARD_PRIFDDINAS", "Notice board", "loctypes"),
            new GamevalEntry(60309, "PORT_TASK_BOARD_LUNAR_ISLE", "Notice board", "loctypes"),
            new GamevalEntry(60310, "DOCK_LOADING_BAY_CRANE_CRATE01", "Crane", "loctypes"),
            new GamevalEntry(60311, "DOCK_CLEAT01", "dock_cleat01", "loctypes"),
            new GamevalEntry(60312, "DOCK_LOADING_BAY_LEDGER_TABLE", "Ledger table", "loctypes"),
            new GamevalEntry(60313, "DOCK_LOADING_BAY_CRATE_BARS_MITHRIL", "Crate", "loctypes"),
            new GamevalEntry(60314, "DOCK_LOADING_BAY_CRATE", "Crate", "loctypes"),
            new GamevalEntry(60315, "DOCK_LOADING_BAY_CRATE_CANONBALLS", "Crate", "loctypes"),
            new GamevalEntry(60316, "DOCK_LOADING_BAY_CRATE_SEEDS", "Crate", "loctypes"),
            new GamevalEntry(60317, "DOCK_LOADING_BAY_CRATE_COAL", "Crate", "loctypes"),
            new GamevalEntry(60318, "DOCK_LOADING_BAY_BARREL_FISH", "Barrel of fish", "loctypes"),
            new GamevalEntry(60319, "DOCK_LOADING_BAY_BARREL_LIQUID", "Barrel of liquid", "loctypes"),
            new GamevalEntry(60320, "DOCK_LOADING_BAY_LEDGER_TABLE_WITHDRAW", "Ledger table", "loctypes"),
            new GamevalEntry(60321, "DOCK_LOADING_BAY_LEDGER_TABLE_DEPOSIT", "Ledger table", "loctypes"),
            new GamevalEntry(60322, "DOCK_LOADING_BAY_LEDGER_TABLE_PORT_SARIM", "dock_loading_bay_ledger_table_port_sarim", "loctypes"),
            new GamevalEntry(60323, "DOCK_LOADING_BAY_LEDGER_TABLE_MUSA_POINT", "dock_loading_bay_ledger_table_musa_point", "loctypes"),
            new GamevalEntry(60324, "DOCK_LOADING_BAY_LEDGER_TABLE_PANDEMONIUM", "dock_loading_bay_ledger_table_pandemonium", "loctypes"),
            new GamevalEntry(60325, "DOCK_LOADING_BAY_LEDGER_TABLE_CATHERBY", "dock_loading_bay_ledger_table_catherby", "loctypes"),
            new GamevalEntry(60326, "DOCK_LOADING_BAY_LEDGER_TABLE_ENTRANA", "dock_loading_bay_ledger_table_entrana", "loctypes"),
            new GamevalEntry(60327, "DOCK_LOADING_BAY_LEDGER_TABLE_ARDOUGNE", "dock_loading_bay_ledger_table_ardougne", "loctypes"),
            new GamevalEntry(60328, "DOCK_LOADING_BAY_LEDGER_TABLE_BRIMHAVEN", "dock_loading_bay_ledger_table_brimhaven", "loctypes"),
            new GamevalEntry(60329, "DOCK_LOADING_BAY_LEDGER_TABLE_PORT_KHAZARD", "dock_loading_bay_ledger_table_port_khazard", "loctypes"),
            new GamevalEntry(60330, "DOCK_LOADING_BAY_LEDGER_TABLE_CORSAIR_COVE", "dock_loading_bay_ledger_table_corsair_cove", "loctypes"),
            new GamevalEntry(60331, "DOCK_LOADING_BAY_LEDGER_TABLE_RUINS_OF_UNKAH", "dock_loading_bay_ledger_table_ruins_of_unkah", "loctypes"),
            new GamevalEntry(60332, "DOCK_LOADING_BAY_LEDGER_TABLE_PORT_PISCARILIUS", "dock_loading_bay_ledger_table_port_piscarilius", "loctypes"),
            new GamevalEntry(60333, "DOCK_LOADING_BAY_LEDGER_TABLE_CIVITAS_ILLA_FORTIS", "dock_loading_bay_ledger_table_civitas_illa_fortis", "loctypes"),
            new GamevalEntry(60334, "DOCK_LOADING_BAY_LEDGER_TABLE_RELLEKKA", "dock_loading_bay_ledger_table_rellekka", "loctypes"),
            new GamevalEntry(60335, "DOCK_LOADING_BAY_LEDGER_TABLE_LANDS_END", "dock_loading_bay_ledger_table_lands_end", "loctypes"),
            new GamevalEntry(60336, "DOCK_LOADING_BAY_LEDGER_TABLE_HOSIDIUS", "dock_loading_bay_ledger_table_hosidius", "loctypes"),
            new GamevalEntry(60337, "DOCK_LOADING_BAY_LEDGER_TABLE_CAIRN_ISLE", "dock_loading_bay_ledger_table_cairn_isle", "loctypes"),
            new GamevalEntry(60338, "DOCK_LOADING_BAY_LEDGER_TABLE_SUNSET_COAST", "dock_loading_bay_ledger_table_sunset_coast", "loctypes"),
            new GamevalEntry(60339, "DOCK_LOADING_BAY_LEDGER_TABLE_THE_SUMMER_SHORE", "dock_loading_bay_ledger_table_the_summer_shore", "loctypes"),
            new GamevalEntry(60340, "DOCK_LOADING_BAY_LEDGER_TABLE_ALDARIN", "dock_loading_bay_ledger_table_aldarin", "loctypes"),
            new GamevalEntry(60341, "DOCK_LOADING_BAY_LEDGER_TABLE_VOID_KNIGHTS_OUTPOST", "dock_loading_bay_ledger_table_void_knights_outpost", "loctypes"),
            new GamevalEntry(60342, "DOCK_LOADING_BAY_LEDGER_TABLE_PORT_ROBERTS", "dock_loading_bay_ledger_table_port_roberts", "loctypes"),
            new GamevalEntry(60343, "DOCK_LOADING_BAY_LEDGER_TABLE_RED_ROCK", "dock_loading_bay_ledger_table_red_rock", "loctypes"),
            new GamevalEntry(60344, "DOCK_LOADING_BAY_LEDGER_TABLE_ETCETERIA", "dock_loading_bay_ledger_table_etceteria", "loctypes"),
            new GamevalEntry(60345, "DOCK_LOADING_BAY_LEDGER_TABLE_NEITIZNOT", "dock_loading_bay_ledger_table_neitiznot", "loctypes"),
            new GamevalEntry(60346, "DOCK_LOADING_BAY_LEDGER_TABLE_JATIZSO", "dock_loading_bay_ledger_table_jatizso", "loctypes"),
            new GamevalEntry(60347, "DOCK_LOADING_BAY_LEDGER_TABLE_PORT_TYRAS", "dock_loading_bay_ledger_table_port_tyras", "loctypes"),
            new GamevalEntry(60348, "DOCK_LOADING_BAY_LEDGER_TABLE_DEEPFIN_POINT", "dock_loading_bay_ledger_table_deepfin_point", "loctypes"),
            new GamevalEntry(60349, "DOCK_LOADING_BAY_LEDGER_TABLE_PRIFDDINAS", "dock_loading_bay_ledger_table_prifddinas", "loctypes"),
            new GamevalEntry(60350, "DOCK_LOADING_BAY_LEDGER_TABLE_PISCATORIS", "dock_loading_bay_ledger_table_piscatoris", "loctypes"),
            new GamevalEntry(60351, "DOCK_LOADING_BAY_LEDGER_TABLE_LUNAR_ISLE", "dock_loading_bay_ledger_table_lunar_isle", "loctypes"),
            new GamevalEntry(60352, "SAILING_RAPIDS", "Gentle rapids", "loctypes"),
            new GamevalEntry(60353, "SAILING_RAPIDS_STRONG", "Strong rapids", "loctypes"),
            new GamevalEntry(60354, "SAILING_RAPIDS_POWERFUL", "Powerful rapids", "loctypes"),
            new GamevalEntry(60355, "SAILING_RAPIDS_DEADLY", "Deadly rapids", "loctypes"),
            new GamevalEntry(60356, "SAILING_HAZARD_FETID_WATERS_AMBIENT_3X3_FAST", "sailing_hazard_fetid_waters_ambient_3x3_fast", "loctypes"),
            new GamevalEntry(60357, "SAILING_HAZARD_FETID_WATERS_AMBIENT_3X3_SLOW", "sailing_hazard_fetid_waters_ambient_3x3_slow", "loctypes"),
            new GamevalEntry(60358, "SAILING_HAZARD_FETID_WATERS_AMBIENT_1X1", "sailing_hazard_fetid_waters_ambient_1x1", "loctypes"),
            new GamevalEntry(60359, "SAILING_FETID_POOL", "sailing_fetid_pool", "loctypes"),
            new GamevalEntry(60360, "SAILING_FETID_POOL_2X2", "sailing_fetid_pool_2x2", "loctypes"),
            new GamevalEntry(60361, "SAILING_FETID_POOL_3X3A", "sailing_fetid_pool_3x3a", "loctypes"),
            new GamevalEntry(60362, "SAILING_FETID_POOL_3X3B", "sailing_fetid_pool_3x3b", "loctypes"),
            new GamevalEntry(60363, "SAILING_FETID_POOL_3X3C", "sailing_fetid_pool_3x3c", "loctypes"),
            new GamevalEntry(60364, "SAILING_HAZARD_PROFANE_SPLASH", "sailing_hazard_profane_splash", "loctypes"),
            new GamevalEntry(60365, "SAILING_HAZARD_PROFANE_CURSE", "sailing_hazard_profane_curse", "loctypes"),
            new GamevalEntry(60366, "SAILING_HAZARD_PROFANE_ORB", "sailing_hazard_profane_orb", "loctypes"),
            new GamevalEntry(60367, "SAILING_HAZARDOUS_WATER_PROFANE", "sailing_hazardous_water_profane", "loctypes"),
            new GamevalEntry(60368, "HAZARDOUS_WATER_PROFANE_2X2_01", "hazardous_water_profane_2x2_01", "loctypes"),
            new GamevalEntry(60369, "HAZARDOUS_WATER_PROFANE_2X2_02", "hazardous_water_profane_2x2_02", "loctypes"),
            new GamevalEntry(60370, "HAZARDOUS_WATER_PROFANE_2X2_03", "hazardous_water_profane_2x2_03", "loctypes"),
            new GamevalEntry(60371, "HAZARDOUS_WATER_PROFANE_1X1_01", "hazardous_water_profane_1x1_01", "loctypes"),
            new GamevalEntry(60372, "HAZARDOUS_WATER_PROFANE_1X1_02", "hazardous_water_profane_1x1_02", "loctypes"),
            new GamevalEntry(60373, "HAZARDOUS_WATER_PROFANE_1X1_03", "hazardous_water_profane_1x1_03", "loctypes"),
            new GamevalEntry(60374, "HAZARDOUS_WATER_PROFANE_1X1_04", "hazardous_water_profane_1x1_04", "loctypes"),
            new GamevalEntry(60375, "HAZARDOUS_WATER_PROFANE_1X1_05", "hazardous_water_profane_1x1_05", "loctypes"),
            new GamevalEntry(60376, "HAZARDOUS_WATER_PROFANE_1X1_06", "hazardous_water_profane_1x1_06", "loctypes"),
            new GamevalEntry(60377, "SAILING_HAZARDOUS_SUNBAKED_3X3_01", "sailing_hazardous_sunbaked_3x3_01", "loctypes"),
            new GamevalEntry(60378, "SAILING_HAZARDOUS_SUNBAKED_2X2_01", "sailing_hazardous_sunbaked_2x2_01", "loctypes"),
            new GamevalEntry(60379, "SAILING_HAZARDOUS_SUNBAKED_2X2_02", "sailing_hazardous_sunbaked_2x2_02", "loctypes"),
            new GamevalEntry(60380, "SAILING_HAZARDOUS_SUNBAKED_1X1_01", "sailing_hazardous_sunbaked_1x1_01", "loctypes"),
            new GamevalEntry(60381, "SAILING_HAZARDOUS_SUNBAKED_1X1_02", "sailing_hazardous_sunbaked_1x1_02", "loctypes"),
            new GamevalEntry(60382, "SAILING_HAZARDOUS_SUNBAKED_1X1_03", "sailing_hazardous_sunbaked_1x1_03", "loctypes"),
            new GamevalEntry(60383, "SAILING_HAZARDOUS_WATER_CURSED_6X3_01", "sailing_hazardous_water_cursed_6x3_01", "loctypes"),
            new GamevalEntry(60384, "SAILING_HAZARDOUS_WATER_CURSED_3X3_01", "sailing_hazardous_water_cursed_3x3_01", "loctypes"),
            new GamevalEntry(60385, "SAILING_HAZARDOUS_WATER_CURSED_3X3_02", "sailing_hazardous_water_cursed_3x3_02", "loctypes"),
            new GamevalEntry(60386, "SAILING_HAZARDOUS_WATER_CURSED_2X2_01", "sailing_hazardous_water_cursed_2x2_01", "loctypes"),
            new GamevalEntry(60387, "SAILING_HAZARDOUS_WATER_CURSED_2X2_02", "sailing_hazardous_water_cursed_2x2_02", "loctypes"),
            new GamevalEntry(60388, "SAILING_HAZARDOUS_WATER_CURSED_1X1_01", "sailing_hazardous_water_cursed_1x1_01", "loctypes"),
            new GamevalEntry(60389, "SAILING_HAZARDOUS_WATER_CURSED_1X1_02", "sailing_hazardous_water_cursed_1x1_02", "loctypes"),
            new GamevalEntry(60390, "SAILING_HAZARDOUS_WATER_ICY_3X3_01", "sailing_hazardous_water_icy_3x3_01", "loctypes"),
            new GamevalEntry(60391, "SAILING_HAZARDOUS_WATER_ICY_2X2_01", "sailing_hazardous_water_icy_2x2_01", "loctypes"),
            new GamevalEntry(60392, "SAILING_HAZARDOUS_WATER_ICY_2X2_02", "sailing_hazardous_water_icy_2x2_02", "loctypes"),
            new GamevalEntry(60393, "SAILING_HAZARDOUS_WATER_ICY_2X2_03", "sailing_hazardous_water_icy_2x2_03", "loctypes"),
            new GamevalEntry(60394, "SAILING_HAZARDOUS_WATER_ICY_2X1_01", "sailing_hazardous_water_icy_2x1_01", "loctypes"),
            new GamevalEntry(60395, "SAILING_HAZARDOUS_WATER_ICY_2X1_02", "sailing_hazardous_water_icy_2x1_02", "loctypes"),
            new GamevalEntry(60396, "SAILING_HAZARDOUS_WATER_ICY_2X1_03", "sailing_hazardous_water_icy_2x1_03", "loctypes"),
            new GamevalEntry(60397, "SAILING_HAZARDOUS_WATER_ICY_1X1_01", "sailing_hazardous_water_icy_1x1_01", "loctypes"),
            new GamevalEntry(60398, "SAILING_HAZARDOUS_WATER_ICY_1X1_02", "sailing_hazardous_water_icy_1x1_02", "loctypes"),
            new GamevalEntry(60399, "SAILING_HAZARDOUS_WATER_ICY_1X1_03", "sailing_hazardous_water_icy_1x1_03", "loctypes"),
            new GamevalEntry(60400, "SAILING_HAZARDOUS_WATER_ICY_1X1_04", "sailing_hazardous_water_icy_1x1_04", "loctypes"),
            new GamevalEntry(60401, "SAILING_HAZARDOUS_WATER_ENDLESS_3X3_01", "sailing_hazardous_water_endless_3x3_01", "loctypes"),
            new GamevalEntry(60402, "SAILING_HAZARDOUS_WATER_ENDLESS_2X2_01", "sailing_hazardous_water_endless_2x2_01", "loctypes"),
            new GamevalEntry(60403, "SAILING_HAZARDOUS_WATER_ENDLESS_2X2_02", "sailing_hazardous_water_endless_2x2_02", "loctypes"),
            new GamevalEntry(60404, "SAILING_HAZARDOUS_WATER_ENDLESS_2X2_03", "sailing_hazardous_water_endless_2x2_03", "loctypes"),
            new GamevalEntry(60405, "SAILING_HAZARDOUS_WATER_ENDLESS_2X2_04", "sailing_hazardous_water_endless_2x2_04", "loctypes"),
            new GamevalEntry(60406, "SAILING_HAZARDOUS_WATER_ENDLESS_1X1_01", "sailing_hazardous_water_endless_1x1_01", "loctypes"),
            new GamevalEntry(60407, "SAILING_HAZARDOUS_WATER_ENDLESS_1X1_02", "sailing_hazardous_water_endless_1x1_02", "loctypes"),
            new GamevalEntry(60408, "SAILING_HAZARDOUS_WATER_ENDLESS_1X1_03", "sailing_hazardous_water_endless_1x1_03", "loctypes"),
            new GamevalEntry(60409, "SAILING_HAZARDOUS_WATER_BOILING_3X3_01", "sailing_hazardous_water_boiling_3x3_01", "loctypes"),
            new GamevalEntry(60410, "SAILING_HAZARDOUS_WATER_BOILING_2X2_01", "sailing_hazardous_water_boiling_2x2_01", "loctypes"),
            new GamevalEntry(60411, "SAILING_HAZARDOUS_WATER_BOILING_1X1_01", "sailing_hazardous_water_boiling_1x1_01", "loctypes"),
            new GamevalEntry(60412, "SAILING_HAZARDOUS_WATER_BOILING_1X1_02", "sailing_hazardous_water_boiling_1x1_02", "loctypes"),
            new GamevalEntry(60413, "SAILING_HAZARDOUS_WATER_BOILING_1X1_03", "sailing_hazardous_water_boiling_1x1_03", "loctypes"),
            new GamevalEntry(60414, "SAILING_HAZARDOUS_WATER_BOILING_1X1_04", "sailing_hazardous_water_boiling_1x1_04", "loctypes"),
            new GamevalEntry(60415, "ROCK_CRYSTAL02_FLECKED01", "rock_crystal02_flecked01", "loctypes"),
            new GamevalEntry(60416, "ROCK_CRYSTAL01_FLECKED01", "rock_crystal01_flecked01", "loctypes"),
            new GamevalEntry(60417, "ROCK_CRYSTAL01_FLECKED02", "rock_crystal01_flecked02", "loctypes"),
            new GamevalEntry(60418, "ROCK_CRYSTAL01_FLECKED03", "rock_crystal01_flecked03", "loctypes"),
            new GamevalEntry(60419, "ROCK_CRYSTAL01_FLECKED04", "rock_crystal01_flecked04", "loctypes"),
            new GamevalEntry(60420, "ROCK_CRYSTAL01_FLECKED05", "rock_crystal01_flecked05", "loctypes"),
            new GamevalEntry(60421, "FX_CRYSTAL01_DISCHARGE01", "fx_crystal01_discharge01", "loctypes"),
            new GamevalEntry(60422, "FX_CRYSTAL01_DISCHARGE01_OFFSET01", "fx_crystal01_discharge01_offset01", "loctypes"),
            new GamevalEntry(60423, "FX_CRYSTAL01_DISCHARGE01_OFFSET02", "fx_crystal01_discharge01_offset02", "loctypes"),
            new GamevalEntry(60424, "SAILING_HAZARD_FOG", "sailing_hazard_fog", "loctypes"),
            new GamevalEntry(60425, "SAILING_HAZARD_FOG_STRAIGHT", "sailing_hazard_fog_straight", "loctypes"),
            new GamevalEntry(60426, "OCEAN_HAZARD_STORMY_WAVE01", "ocean_hazard_stormy_wave01", "loctypes"),
            new GamevalEntry(60427, "OCEAN_HAZARD_STORMY_WAVE02", "ocean_hazard_stormy_wave02", "loctypes"),
            new GamevalEntry(60428, "OCEAN_HAZARD_STORMY_WAVE03", "ocean_hazard_stormy_wave03", "loctypes"),
            new GamevalEntry(60429, "OCEAN_HAZARD_STORMY_CLOUD01", "ocean_hazard_stormy_cloud01", "loctypes"),
            new GamevalEntry(60430, "OCEAN_HAZARD_STORMY_WHIRL01", "ocean_hazard_stormy_whirl01", "loctypes"),
            new GamevalEntry(60431, "SAILING_BANK_BOAT_HULL01", "sailing_bank_boat_hull01", "loctypes"),
            new GamevalEntry(60432, "SAILING_BANK_BOAT_SAIL01", "sailing_bank_boat_sail01", "loctypes"),
            new GamevalEntry(60433, "SAILING_BANK_BOAT_HELM01", "sailing_bank_boat_helm01", "loctypes"),
            new GamevalEntry(60434, "SAILING_BANK_BOAT_CLICKBOX", "Bank boat", "loctypes"),
            new GamevalEntry(60435, "SAILING_BANK_BOAT_BANK_CRAB", "Bank Crab", "loctypes"),
            new GamevalEntry(60436, "OCEAN_OUTCROP_ROCK01", "ocean_outcrop_rock01", "loctypes"),
            new GamevalEntry(60437, "OCEAN_OUTCROP_ROCK02", "ocean_outcrop_rock02", "loctypes"),
            new GamevalEntry(60438, "OCEAN_OUTCROP_ROCK03", "ocean_outcrop_rock03", "loctypes"),
            new GamevalEntry(60439, "OCEAN_OUTCROP_ROCK04", "ocean_outcrop_rock04", "loctypes"),
            new GamevalEntry(60440, "OCEAN_OUTCROP_ROCK05", "ocean_outcrop_rock05", "loctypes"),
            new GamevalEntry(60441, "OCEAN_OUTCROP_ROCK06", "ocean_outcrop_rock06", "loctypes"),
            new GamevalEntry(60442, "OCEAN_OUTCROP_ROCK07", "ocean_outcrop_rock07", "loctypes"),
            new GamevalEntry(60443, "OCEAN_OUTCROP_ROCK08", "ocean_outcrop_rock08", "loctypes"),
            new GamevalEntry(60444, "OCEAN_OUTCROP_ROCK09", "ocean_outcrop_rock09", "loctypes"),
            new GamevalEntry(60445, "OCEAN_OUTCROP_JAGGED01", "ocean_outcrop_jagged01", "loctypes"),
            new GamevalEntry(60446, "OCEAN_OUTCROP_JAGGED02", "ocean_outcrop_jagged02", "loctypes"),
            new GamevalEntry(60447, "OCEAN_OUTCROP_JAGGED03", "ocean_outcrop_jagged03", "loctypes"),
            new GamevalEntry(60448, "OCEAN_OUTCROP_JAGGED04", "ocean_outcrop_jagged04", "loctypes"),
            new GamevalEntry(60449, "OCEAN_OUTCROP_JAGGED05", "ocean_outcrop_jagged05", "loctypes"),
            new GamevalEntry(60450, "OCEAN_OUTCROP_JAGGED06", "ocean_outcrop_jagged06", "loctypes"),
            new GamevalEntry(60451, "OCEAN_OUTCROP_JAGGED07", "ocean_outcrop_jagged07", "loctypes"),
            new GamevalEntry(60452, "OCEAN_OUTCROP_SEAWEED01", "ocean_outcrop_seaweed01", "loctypes"),
            new GamevalEntry(60453, "OCEAN_OUTCROP_SEAWEED02", "ocean_outcrop_seaweed02", "loctypes"),
            new GamevalEntry(60454, "OCEAN_OUTCROP_SEAWEED03", "ocean_outcrop_seaweed03", "loctypes"),
            new GamevalEntry(60455, "OCEAN_BUBBLES", "ocean_bubbles", "loctypes"),
            new GamevalEntry(60456, "OCEAN_PLANT_KELP01", "M-1-I!9'", "loctypes"),
            new GamevalEntry(60457, "OCEAN_PLANT_KELP02", "M-1-I!9'", "loctypes"),
            new GamevalEntry(60458, "OCEAN_PLANT_KELP03", "M-1-I!9'", "loctypes"),
            new GamevalEntry(60459, "OCEAN_PLANT_KELP04", "M-1-I!9'", "loctypes"),
            new GamevalEntry(60460, "OCEAN_PLANT_KELP05", "M-1-I!9'", "loctypes"),
            new GamevalEntry(60461, "BUOY_DOCK_DEFAULT01", "Dock buoy", "loctypes"),
            new GamevalEntry(60462, "SAILING_PORT_SALVAGING_STATION_PORT_SARIM", "Salvaging station", "loctypes"),
            new GamevalEntry(60463, "SAILING_PORT_SALVAGING_STATION", "Salvaging station", "loctypes"),
            new GamevalEntry(60464, "SAILING_SMALL_SHIPWRECK", "Small shipwreck", "loctypes"),
            new GamevalEntry(60465, "SAILING_SMALL_SHIPWRECK_STUMP", "Small shipwreck", "loctypes"),
            new GamevalEntry(60466, "SAILING_FISHERMAN_SHIPWRECK", "Fisherman's shipwreck", "loctypes"),
            new GamevalEntry(60467, "SAILING_FISHERMAN_SHIPWRECK_STUMP", "Fisherman's shipwreck", "loctypes"),
            new GamevalEntry(60468, "SAILING_BARRACUDA_SHIPWRECK", "Barracuda shipwreck", "loctypes"),
            new GamevalEntry(60469, "SAILING_BARRACUDA_SHIPWRECK_STUMP", "Barracuda shipwreck", "loctypes"),
            new GamevalEntry(60470, "SAILING_LARGE_SHIPWRECK", "Large shipwreck", "loctypes"),
            new GamevalEntry(60471, "SAILING_LARGE_SHIPWRECK_STUMP", "Large shipwreck", "loctypes"),
            new GamevalEntry(60472, "SAILING_PIRATE_SHIPWRECK", "Pirate shipwreck", "loctypes"),
            new GamevalEntry(60473, "SAILING_PIRATE_SHIPWRECK_STUMP", "Pirate shipwreck", "loctypes"),
            new GamevalEntry(60474, "SAILING_MERCENARY_SHIPWRECK", "Mercenary shipwreck", "loctypes"),
            new GamevalEntry(60475, "SAILING_MERCENARY_SHIPWRECK_STUMP", "Mercenary shipwreck", "loctypes"),
            new GamevalEntry(60476, "SAILING_FREMENNIK_SHIPWRECK", "Fremennik shipwreck", "loctypes"),
            new GamevalEntry(60477, "SAILING_FREMENNIK_SHIPWRECK_STUMP", "Fremennik shipwreck", "loctypes"),
            new GamevalEntry(60478, "SAILING_MERCHANT_SHIPWRECK", "Merchant shipwreck", "loctypes"),
            new GamevalEntry(60479, "SAILING_MERCHANT_SHIPWRECK_STUMP", "Merchant shipwreck", "loctypes"),
            new GamevalEntry(60480, "SAILING_INTRO_SALVAGING_HOOK", "sailing_intro_salvaging_hook", "loctypes"),
            new GamevalEntry(60481, "SAILING_INTRO_SALVAGING_HOOK_NOOPS", "Salvaging hook", "loctypes"),
            new GamevalEntry(60482, "SAILING_INTRO_SALVAGING_HOOK_OPS", "Salvaging hook", "loctypes"),
            new GamevalEntry(60483, "SALVAGING_HOOK_RAFT_BRONZE", "Bronze salvaging hook", "loctypes"),
            new GamevalEntry(60484, "SALVAGING_HOOK_RAFT_IRON", "Iron salvaging hook", "loctypes"),
            new GamevalEntry(60485, "SALVAGING_HOOK_RAFT_STEEL", "Steel salvaging hook", "loctypes"),
            new GamevalEntry(60486, "SALVAGING_HOOK_RAFT_MITHRIL", "Mithril salvaging hook", "loctypes"),
            new GamevalEntry(60487, "SALVAGING_HOOK_RAFT_ADAMANT", "Adamant salvaging hook", "loctypes"),
            new GamevalEntry(60488, "SALVAGING_HOOK_RAFT_RUNE", "Rune salvaging hook", "loctypes"),
            new GamevalEntry(60489, "SALVAGING_HOOK_RAFT_DRAGON", "Dragon salvaging hook", "loctypes"),
        };
    }

    static Optional<GamevalEntry> byId(int id) {
        for (GamevalEntry entry : entries()) {
            if (entry.id() == id) return Optional.of(entry);
        }
        return Optional.empty();
    }

}
