package net.titan.gamevals.internal;

import java.util.Optional;

import net.titan.gamevals.GamevalEntry;
import net.titan.gamevals.QuestEntry;

final class ObjectIDEntries_91 {
    private ObjectIDEntries_91() {}

    static GamevalEntry[] entries() {
        return new GamevalEntry[] {
            new GamevalEntry(46592, "SOTN_HIDDEN_CHEST_CLOSED_PICKLOCK", "Chest", "loctypes"),
            new GamevalEntry(46593, "SOTN_HIDDEN_CHEST_CLOSED_SEARCH", "Chest", "loctypes"),
            new GamevalEntry(46594, "SOTN_HIDDEN_CHEST_CLOSED_NOOP", "Chest", "loctypes"),
            new GamevalEntry(46595, "SOTN_HIDDEN_CHEST_OPEN", "Chest", "loctypes"),
            new GamevalEntry(46596, "GHORROCK_DUNGEON_EXIT", "Crevice", "loctypes"),
            new GamevalEntry(46597, "GHORROCK_DUNGEON_CAVE_ENTRY", "Crevice", "loctypes"),
            new GamevalEntry(46598, "GHORROCK_DUNGEON_CAVE_EXIT", "Crevice", "loctypes"),
            new GamevalEntry(46599, "SOTN_MUSPAH_ESCAPE", "Crevice", "loctypes"),
            new GamevalEntry(46600, "SOTN_ASSASSIN_ESCAPE", "Gate", "loctypes"),
            new GamevalEntry(46601, "SOTN_GHORROCK_GATE_1", "Gate", "loctypes"),
            new GamevalEntry(46602, "SOTN_GHORROCK_GATE_2", "Gate", "loctypes"),
            new GamevalEntry(46603, "SOTN_GHORROCK_GATE_3", "Gate", "loctypes"),
            new GamevalEntry(46604, "SOTN_GHORROCK_GATE_OPEN", "Gate", "loctypes"),
            new GamevalEntry(46605, "SOTN_GHORROCK_TABLE_1", "Damaged Table", "loctypes"),
            new GamevalEntry(46606, "SOTN_GHORROCK_TABLE_2", "Damaged Table", "loctypes"),
            new GamevalEntry(46607, "SOTN_GHORROCK_CRATE_1", "Crate", "loctypes"),
            new GamevalEntry(46608, "SOTN_GHORROCK_CRATE_2", "Crate", "loctypes"),
            new GamevalEntry(46609, "SOTN_GHORROCK_WEAPON_BARREL", "Barrel", "loctypes"),
            new GamevalEntry(46610, "SOTN_GHORROCK_LEVER_MISSING", "Lever Mechanism", "loctypes"),
            new GamevalEntry(46611, "SOTN_GHORROCK_LEVER_UP", "Lever", "loctypes"),
            new GamevalEntry(46612, "SOTN_GHORROCK_LEVER_DOWN", "Lever", "loctypes"),
            new GamevalEntry(46613, "SOTN_GHORROCK_PILLAR", "Pillar", "loctypes"),
            new GamevalEntry(46614, "SOTN_GHORROCK_BRAZIER_UNLIT", "Brazier", "loctypes"),
            new GamevalEntry(46615, "SOTN_GHORROCK_BRAZIER_LIT", "Brazier", "loctypes"),
            new GamevalEntry(46616, "SOTN_GHORROCK_CHEST_1", "Chest", "loctypes"),
            new GamevalEntry(46617, "SOTN_GHORROCK_CHEST_2", "Chest", "loctypes"),
            new GamevalEntry(46618, "SOTN_GHORROCK_CHEST_3", "Chest", "loctypes"),
            new GamevalEntry(46619, "SOTN_GHORROCK_CHEST_4", "Chest", "loctypes"),
            new GamevalEntry(46620, "SOTN_GHORROCK_CHEST_EMPTY", "Chest", "loctypes"),
            new GamevalEntry(46621, "SOTN_GHORROCK_CHEST_OPEN", "Chest", "loctypes"),
            new GamevalEntry(46622, "SOTN_ASSASSIN_SMOKE", "Smoke Cloud", "loctypes"),
            new GamevalEntry(46623, "GHORROCK_STONE01", "ghorrock_stone01", "loctypes"),
            new GamevalEntry(46624, "GHORROCK_STONE01_SNOW01", "ghorrock_stone01_snow01", "loctypes"),
            new GamevalEntry(46625, "GHORROCK_STONE01_SNOW01_TRANSITION", "ghorrock_stone01_snow01_transition", "loctypes"),
            new GamevalEntry(46626, "GHORROCK_STONE01_SNOW01_TRANSITION_MIRROR", "ghorrock_stone01_snow01_transition_mirror", "loctypes"),
            new GamevalEntry(46627, "GHORROCK_STONE01_SNOW01_PILLAR", "ghorrock_stone01_snow01_pillar", "loctypes"),
            new GamevalEntry(46628, "GHORROCK_STONE01_PILLAR01", "Pillar", "loctypes"),
            new GamevalEntry(46629, "GHORROCK_STONE01_PILLAR02", "Pillar", "loctypes"),
            new GamevalEntry(46630, "GHORROCK_STONE01_DECORATIVE01", "ghorrock_stone01_decorative01", "loctypes"),
            new GamevalEntry(46631, "GHORROCK_STONE01_ALCOVE01", "ghorrock_stone01_alcove01", "loctypes"),
            new GamevalEntry(46632, "GHORROCK_STONE01_ALCOVE02_STAIRS", "ghorrock_stone01_alcove02_stairs", "loctypes"),
            new GamevalEntry(46633, "GHORROCK_STONE01_ALCOVE02_BLANK", "ghorrock_stone01_alcove02_blank", "loctypes"),
            new GamevalEntry(46634, "GHORROCK_STONE01_ALCOVE02_CAGE", "Cage", "loctypes"),
            new GamevalEntry(46635, "GHORROCK_STONE01_ALCOVE02_DOOR", "ghorrock_stone01_alcove02_door", "loctypes"),
            new GamevalEntry(46636, "GHORROCK_STONE01_ALCOVE02_PLAQUE", "ghorrock_stone01_alcove02_plaque", "loctypes"),
            new GamevalEntry(46637, "GHORROCK_SNOW_BLOCKAGE", "ghorrock_snow_blockage", "loctypes"),
            new GamevalEntry(46638, "GHORROCK_STONE01_ENTRANCE", "Crevice", "loctypes"),
            new GamevalEntry(46639, "GHORROCK_STONE01_SNOW01_FALLOFF_STRAIGHT", "ghorrock_stone01_snow01_falloff_straight", "loctypes"),
            new GamevalEntry(46640, "GHORROCK_STONE01_SNOW01_FALLOFF_STRAIGHT_END", "ghorrock_stone01_snow01_falloff_straight_end", "loctypes"),
            new GamevalEntry(46641, "GHORROCK_STONE01_SNOW01_FALLOFF_STRAIGHT_END_MIRROR", "ghorrock_stone01_snow01_falloff_straight_end_mirror", "loctypes"),
            new GamevalEntry(46642, "GHORROCK_STONE01_SNOW01_FALLOFF_OUTSIDE_CORNER", "ghorrock_stone01_snow01_falloff_outside_corner", "loctypes"),
            new GamevalEntry(46643, "GHORROCK_STONE01_SNOW01_FALLOFF_INSIDE_CORNER", "ghorrock_stone01_snow01_falloff_inside_corner", "loctypes"),
            new GamevalEntry(46644, "GHORROCK_SNOW1", "ghorrock_snow1", "loctypes"),
            new GamevalEntry(46645, "GHORROCK_SNOW2", "ghorrock_snow2", "loctypes"),
            new GamevalEntry(46646, "GHORROCK_SNOW3", "ghorrock_snow3", "loctypes"),
            new GamevalEntry(46647, "GHORROCK_WALL_CANDLE01", "ghorrock_wall_candle01", "loctypes"),
            new GamevalEntry(46648, "GHORROCK_WALLTOP_SNOW_FILLER", "ghorrock_walltop_snow_filler", "loctypes"),
            new GamevalEntry(46649, "GHORROCK_WALLTOP_SNOW_BLACK", "ghorrock_walltop_snow_black", "loctypes"),
            new GamevalEntry(46650, "GHORROCK_WALLTOP_SNOW_STRAIGHT", "ghorrock_walltop_snow_straight", "loctypes"),
            new GamevalEntry(46651, "GHORROCK_WALLTOP_SNOW_OUTSIDE_CORNER", "ghorrock_walltop_snow_outside_corner", "loctypes"),
            new GamevalEntry(46652, "GHORROCK_WALLTOP_SNOW_INSIDE_CORNER", "ghorrock_walltop_snow_inside_corner", "loctypes"),
            new GamevalEntry(46653, "GHORROCK_GATEWAY01_LEFT_LVL0", "ghorrock_gateway01_left_lvl0", "loctypes"),
            new GamevalEntry(46654, "GHORROCK_GATEWAY01_RIGHT_LVL0", "ghorrock_gateway01_right_lvl0", "loctypes"),
            new GamevalEntry(46655, "GHORROCK_GATEWAY01_LEFT_LVL1", "ghorrock_gateway01_left_lvl1", "loctypes"),
            new GamevalEntry(46656, "GHORROCK_GATEWAY01_RIGHT_LVL1", "ghorrock_gateway01_right_lvl1", "loctypes"),
            new GamevalEntry(46657, "GHORROCK_GATEWAY01_MIDDLE_LVL1", "ghorrock_gateway01_middle_lvl1", "loctypes"),
            new GamevalEntry(46658, "GHORROCK_METAL_GATE_CLOSED", "Gate", "loctypes"),
            new GamevalEntry(46659, "GHORROCK_METAL_GATE_OPEN", "Gate", "loctypes"),
            new GamevalEntry(46660, "GHORROCK_METAL_GATE_PADLOCK_CLOSED", "Gate", "loctypes"),
            new GamevalEntry(46661, "GHORROCK_METAL_GATE_PADLOCK_OPEN", "Gate", "loctypes"),
            new GamevalEntry(46662, "GHORROCK_ICE01", "ghorrock_ice01", "loctypes"),
            new GamevalEntry(46663, "GHORROCK_ICE02", "ghorrock_ice02", "loctypes"),
            new GamevalEntry(46664, "GHORROCK_ICE03", "ghorrock_ice03", "loctypes"),
            new GamevalEntry(46665, "GHORROCK_ICE_BLOCKAGE", "Blockage", "loctypes"),
            new GamevalEntry(46666, "GHORROCK_SNOW01_ICE01_TRANS", "ghorrock_snow01_ice01_trans", "loctypes"),
            new GamevalEntry(46667, "GHORROCK_SNOW01_ICE01_TRANS_MIRROR", "ghorrock_snow01_ice01_trans_mirror", "loctypes"),
            new GamevalEntry(46668, "GHORROCK_ICE_FORMATION01", "ghorrock_ice_formation01", "loctypes"),
            new GamevalEntry(46669, "GHORROCK_ICE_FORMATION02", "ghorrock_ice_formation02", "loctypes"),
            new GamevalEntry(46670, "GHORROCK_ICE_FORMATION03", "ghorrock_ice_formation03", "loctypes"),
            new GamevalEntry(46671, "GHORROCK_ICE_FORMATION04", "ghorrock_ice_formation04", "loctypes"),
            new GamevalEntry(46672, "GHORROCK_ICE_FORMATION05", "ghorrock_ice_formation05", "loctypes"),
            new GamevalEntry(46673, "GHORROCK_PRISON_DOOR", "Heavy Door", "loctypes"),
            new GamevalEntry(46674, "GHORROCK_SNOW01_BROKENTABLE01", "Damaged Table", "loctypes"),
            new GamevalEntry(46675, "GHORROCK_SNOW01_BROKENTABLE02", "Damaged Table", "loctypes"),
            new GamevalEntry(46676, "GHORROCK_SNOW01_SMASHEDCHAIR01", "Smashed Chair", "loctypes"),
            new GamevalEntry(46677, "GHORROCK_SNOW01_SMASHEDCHAIR02", "Chair", "loctypes"),
            new GamevalEntry(46678, "GHORROCK_SNOW01_CHEST_CLOSED", "Chest", "loctypes"),
            new GamevalEntry(46679, "GHORROCK_SNOW01_CHEST_OPEN", "Chest", "loctypes"),
            new GamevalEntry(46680, "GHORROCK_SNOW01_CHEST_CLOSED_NOOP", "Chest", "loctypes"),
            new GamevalEntry(46681, "GHORROCK_RUBBLE01", "ghorrock_rubble01", "loctypes"),
            new GamevalEntry(46682, "GHORROCK_RUBBLE02", "ghorrock_rubble02", "loctypes"),
            new GamevalEntry(46683, "GHORROCK_RUBBLE03", "ghorrock_rubble03", "loctypes"),
            new GamevalEntry(46684, "GHORROCK_RUBBLE04", "ghorrock_rubble04", "loctypes"),
            new GamevalEntry(46685, "GHORROCK_RUBBLE05", "ghorrock_rubble05", "loctypes"),
            new GamevalEntry(46686, "GHORROCK_LEVER_UP", "Lever", "loctypes"),
            new GamevalEntry(46687, "GHORROCK_LEVER_DOWN", "Lever", "loctypes"),
            new GamevalEntry(46688, "GHORROCK_CRATE_SINGLE", "Crate", "loctypes"),
            new GamevalEntry(46689, "GHORROCK_CRATE_DOUBLE", "Crates", "loctypes"),
            new GamevalEntry(46690, "GHORROCK_WEAPON_BARREL", "Barrel", "loctypes"),
            new GamevalEntry(46691, "GHORROCK_BRAZIER", "Brazier", "loctypes"),
            new GamevalEntry(46692, "GHORROCK_DOOR_SHIELD01", "Strange Barrier", "loctypes"),
            new GamevalEntry(46693, "MUSPAH_SPIKE_PRE", "Spike", "loctypes"),
            new GamevalEntry(46694, "MUSPAH_SPIKE_POST", "Spike", "loctypes"),
            new GamevalEntry(46695, "MUSPAH_SPIKE", "Spike", "loctypes"),
            new GamevalEntry(46696, "MUSPAH_SPIKE_SURROUNDED", "Spike", "loctypes"),
            new GamevalEntry(46697, "MUSPAH_SPIKE_FOLLOW", "Spike", "loctypes"),
            new GamevalEntry(46698, "MUSPAH_SPIKE_INVISIBLE", "muspah_spike_invisible", "loctypes"),
            new GamevalEntry(46699, "MUSPAH_SPIKE_SURROUNDED_INVISIBLE", "muspah_spike_surrounded_invisible", "loctypes"),
            new GamevalEntry(46700, "MUSPAH_SCOREBOARD", "Scoreboard", "loctypes"),
            new GamevalEntry(46701, "ANCIENT_ESSENCE_ROCK_ACTIVE", "Ancient essence crystals", "loctypes"),
            new GamevalEntry(46702, "ANCIENT_ESSENCE_ROCK_EMPTY", "Wall", "loctypes"),
            new GamevalEntry(46703, "ANCIENT_ESSENCE_ROCK_INACTIVE", "ancient_essence_rock_inactive", "loctypes"),
            new GamevalEntry(46704, "CARNILLEAN_STAIRS", "Staircase", "loctypes"),
            new GamevalEntry(46705, "CARNILLEAN_STAIRSTOP", "Climb-down", "loctypes"),
            new GamevalEntry(46706, "HAZEELCBOPEN_NOOP", "Cupboard", "loctypes"),
            new GamevalEntry(46707, "CARNILLEANBOOKCASE_KNOCK", "Wall", "loctypes"),
            new GamevalEntry(46708, "CARNILLEANBOOKCASE_PUSH", "Wall", "loctypes"),
            new GamevalEntry(46709, "CARNILLEANBOOKCASE_NOOP", "Wall", "loctypes"),
            new GamevalEntry(46710, "CARNILLEANSHUTCHEST_NORMAL", "Chest", "loctypes"),
            new GamevalEntry(46711, "CARNILLEANSHUTCHEST_BROKEN", "Chest", "loctypes"),
            new GamevalEntry(46712, "CARNILLEANOPENCHEST_NORMAL", "Chest", "loctypes"),
            new GamevalEntry(46713, "HAZEEL_CHEST_CLOSED", "Chest", "loctypes"),
            new GamevalEntry(46714, "HAZEEL_CHEST_OPEN", "Chest", "loctypes"),
            new GamevalEntry(46715, "HAZEEL_CHEST_CLOSED_NOOP", "Chest", "loctypes"),
            new GamevalEntry(46716, "CARNILLEAN_LADDER_UP", "Ladder", "loctypes"),
            new GamevalEntry(46717, "CARNILLEAN_LADDER_DOWN", "Ladder", "loctypes"),
            new GamevalEntry(46718, "CARNILLEAN_DOG_GRAVE_VIS", "Scruffy's Grave", "loctypes"),
            new GamevalEntry(46719, "CARNILLEAN_DOG_GRAVE_NOVIS", "Potted flower", "loctypes"),
            new GamevalEntry(46720, "DT2_DESERT_VAULT_WALL01_STRAIGHT01", "dt2_desert_vault_wall01_straight01", "loctypes"),
            new GamevalEntry(46721, "DT2_DESERT_VAULT_WALL01_STRAIGHT02", "dt2_desert_vault_wall01_straight02", "loctypes"),
            new GamevalEntry(46722, "DT2_DESERT_VAULT_WALL01_OUTSIDE_CORNER", "dt2_desert_vault_wall01_outside_corner", "loctypes"),
            new GamevalEntry(46723, "DT2_DESERT_VAULT_WALL01_END_CAP01", "dt2_desert_vault_wall01_end_cap01", "loctypes"),
            new GamevalEntry(46724, "DT2_DESERT_VAULT_WALL01_END_CAP02", "dt2_desert_vault_wall01_end_cap02", "loctypes"),
            new GamevalEntry(46725, "DT2_DESERT_VAULT_WALLTOP01", "dt2_desert_vault_walltop01", "loctypes"),
            new GamevalEntry(46726, "DT2_DESERT_VAULT_STEPS1_01", "dt2_desert_vault_steps1_01", "loctypes"),
            new GamevalEntry(46727, "DT2_DESERT_VAULT_STEPS1_02", "dt2_desert_vault_steps1_02", "loctypes"),
            new GamevalEntry(46728, "DT2_DESERT_VAULT_STEPS1_03", "dt2_desert_vault_steps1_03", "loctypes"),
            new GamevalEntry(46729, "DT2_DESERT_VAULT_STEPS2_01", "dt2_desert_vault_steps2_01", "loctypes"),
            new GamevalEntry(46730, "DT2_DESERT_VAULT_STEPS2_01B", "dt2_desert_vault_steps2_01b", "loctypes"),
            new GamevalEntry(46731, "DT2_DESERT_VAULT_STEPS3_01", "dt2_desert_vault_steps3_01", "loctypes"),
            new GamevalEntry(46732, "DT2_DESERT_VAULT_STEPS3_01B", "dt2_desert_vault_steps3_01b", "loctypes"),
            new GamevalEntry(46733, "DT2_DESERT_VAULT_STEPS4_01", "dt2_desert_vault_steps4_01", "loctypes"),
            new GamevalEntry(46734, "DT2_DESERT_VAULT_STEPS4_01B", "dt2_desert_vault_steps4_01b", "loctypes"),
            new GamevalEntry(46735, "DT2_DESERT_VAULT_WALL02_STRAIGHT01", "dt2_desert_vault_wall02_straight01", "loctypes"),
            new GamevalEntry(46736, "DT2_DESERT_VAULT_WALL02_STRAIGHT02", "dt2_desert_vault_wall02_straight02", "loctypes"),
            new GamevalEntry(46737, "DT2_DESERT_VAULT_WALL02_OUTSIDE_CORNER", "dt2_desert_vault_wall02_outside_corner", "loctypes"),
            new GamevalEntry(46738, "DT2_DESERT_VAULT_WALL02_INSIDE_CURVE", "dt2_desert_vault_wall02_inside_curve", "loctypes"),
            new GamevalEntry(46739, "DT2_DESERT_VAULT_ROOF01", "dt2_desert_vault_roof01", "loctypes"),
            new GamevalEntry(46740, "DT2_DESERT_VAULT_ROOF02", "dt2_desert_vault_roof02", "loctypes"),
            new GamevalEntry(46741, "DT2_DESERT_VAULT_ROOF03", "dt2_desert_vault_roof03", "loctypes"),
            new GamevalEntry(46742, "DT2_DESERT_VAULT_ROOF04", "dt2_desert_vault_roof04", "loctypes"),
            new GamevalEntry(46743, "DT2_DESERT_VAULT_DOOR", "Vault Door", "loctypes"),
            new GamevalEntry(46744, "DT2_DESERT_VAULT_PILLAR01", "dt2_desert_vault_pillar01", "loctypes"),
            new GamevalEntry(46745, "DT2_DESERT_VAULT_PILLAR02", "dt2_desert_vault_pillar02", "loctypes"),
            new GamevalEntry(46746, "DT2_DESERT_VAULT_PILLAR03", "dt2_desert_vault_pillar03", "loctypes"),
            new GamevalEntry(46747, "DT2_DESERT_VAULT_PILLAR04", "dt2_desert_vault_pillar04", "loctypes"),
            new GamevalEntry(46748, "DT2_DESERT_VAULT_PILLAR05", "dt2_desert_vault_pillar05", "loctypes"),
            new GamevalEntry(46749, "DT2_DESERT_VAULT_PILLAR06", "dt2_desert_vault_pillar06", "loctypes"),
            new GamevalEntry(46750, "DT2_DESERT_VAULT_PILLAR07", "dt2_desert_vault_pillar07", "loctypes"),
            new GamevalEntry(46751, "DT2_DESERT_VAULT_PILLAR08", "dt2_desert_vault_pillar08", "loctypes"),
            new GamevalEntry(46752, "DT2_DESERT_VAULT_BRAZIER01", "Brazier", "loctypes"),
            new GamevalEntry(46753, "DT2_DESERT_ROCK01", "dt2_desert_rock01", "loctypes"),
            new GamevalEntry(46754, "DT2_DESERT_ROCK02", "dt2_desert_rock02", "loctypes"),
            new GamevalEntry(46755, "DT2_DESERT_ROCK03", "dt2_desert_rock03", "loctypes"),
            new GamevalEntry(46756, "DT2_DESERT_ROCK04", "dt2_desert_rock04", "loctypes"),
            new GamevalEntry(46757, "DT2_DESERT_ROCK05", "dt2_desert_rock05", "loctypes"),
            new GamevalEntry(46758, "DT2_DESERT_ROCK06", "dt2_desert_rock06", "loctypes"),
            new GamevalEntry(46759, "DT2_DESERT_ROCK07", "dt2_desert_rock07", "loctypes"),
            new GamevalEntry(46760, "DT2_DESERT_ROCK08", "dt2_desert_rock08", "loctypes"),
            new GamevalEntry(46761, "DUGUPSOIL_DESERT_VAULT_1", "dugupsoil_desert_vault_1", "loctypes"),
            new GamevalEntry(46762, "DUGUPSOIL_DESERT_VAULT_2", "dugupsoil_desert_vault_2", "loctypes"),
            new GamevalEntry(46763, "DUGUPSOIL_DESERT_VAULT_3", "dugupsoil_desert_vault_3", "loctypes"),
            new GamevalEntry(46764, "DT2_DESERT_VAULT_FLOOR_SYMBOL_01", "dt2_desert_vault_floor_symbol_01", "loctypes"),
            new GamevalEntry(46765, "DT2_DESERT_VAULT_FLOOR_SYMBOL_02", "dt2_desert_vault_floor_symbol_02", "loctypes"),
            new GamevalEntry(46766, "DT2_DESERT_VAULT_FLOOR_SYMBOL_03", "dt2_desert_vault_floor_symbol_03", "loctypes"),
            new GamevalEntry(46767, "DT2_DESERT_VAULT_FLOOR_SYMBOL_04", "dt2_desert_vault_floor_symbol_04", "loctypes"),
            new GamevalEntry(46768, "DT2_DESERT_VAULT_FLOOR_SYMBOL_05", "dt2_desert_vault_floor_symbol_05", "loctypes"),
            new GamevalEntry(46769, "DT2_DESERT_VAULT_FLOOR_SYMBOL_06", "dt2_desert_vault_floor_symbol_06", "loctypes"),
            new GamevalEntry(46770, "DT2_DESERT_VAULT_FLOOR_SYMBOL_07", "dt2_desert_vault_floor_symbol_07", "loctypes"),
            new GamevalEntry(46771, "DT2_DESERT_VAULT_FLOOR_SYMBOL_08", "dt2_desert_vault_floor_symbol_08", "loctypes"),
            new GamevalEntry(46772, "DT2_DESERT_VAULT_FLOOR_SYMBOL_09", "dt2_desert_vault_floor_symbol_09", "loctypes"),
            new GamevalEntry(46773, "WALLKIT_MASTABA01_DEFAULT01_OASIS", "wallkit_mastaba01_default01_oasis", "loctypes"),
            new GamevalEntry(46774, "WALLKIT_MASTABA01_DEFAULT02_OASIS", "wallkit_mastaba01_default02_oasis", "loctypes"),
            new GamevalEntry(46775, "WALLKIT_MASTABA01_DAMAGED01_OASIS", "wallkit_mastaba01_damaged01_oasis", "loctypes"),
            new GamevalEntry(46776, "WALLKIT_MASTABA01_DAMAGED02_OASIS", "wallkit_mastaba01_damaged02_oasis", "loctypes"),
            new GamevalEntry(46777, "WALLKIT_MASTABA01_DAMAGED03_OASIS", "wallkit_mastaba01_damaged03_oasis", "loctypes"),
            new GamevalEntry(46778, "WALLKIT_MASTABA01_DAMAGED04_OASIS", "wallkit_mastaba01_damaged04_oasis", "loctypes"),
            new GamevalEntry(46779, "WALLKIT_MASTABA01_ROOF01_OASIS", "wallkit_mastaba01_roof01_oasis", "loctypes"),
            new GamevalEntry(46780, "WALLKIT_MASTABA01_ROOF02_OASIS", "wallkit_mastaba01_roof02_oasis", "loctypes"),
            new GamevalEntry(46781, "WALLKIT_MASTABA01_ROOF03_OASIS", "wallkit_mastaba01_roof03_oasis", "loctypes"),
            new GamevalEntry(46782, "WALLKIT_MASTABA01_CORNER01_OASIS", "wallkit_mastaba01_corner01_oasis", "loctypes"),
            new GamevalEntry(46783, "WALLKIT_MASTABA01_DOORWAY01_OASIS", "Entry", "loctypes"),
            new GamevalEntry(46784, "WALLKIT_MASTABA01_WALL01_OASIS", "wallkit_mastaba01_wall01_oasis", "loctypes"),
            new GamevalEntry(46785, "WALLKIT_MASTABA02_DAMAGED01_OASIS", "wallkit_mastaba02_damaged01_oasis", "loctypes"),
            new GamevalEntry(46786, "WALLKIT_MASTABA02_CORNER01_OASIS", "wallkit_mastaba02_corner01_oasis", "loctypes"),
            new GamevalEntry(46787, "WALLKIT_MASTABA02_ROOF01_OASIS", "wallkit_mastaba02_roof01_oasis", "loctypes"),
            new GamevalEntry(46788, "WALLKIT_MASTABA02_ROOF02_OASIS", "wallkit_mastaba02_roof02_oasis", "loctypes"),
            new GamevalEntry(46789, "WALLKIT_MASTABA02_ROOF03_OASIS", "wallkit_mastaba02_roof03_oasis", "loctypes"),
            new GamevalEntry(46790, "WALLKIT_MASTABA02_ROOF04_OASIS", "wallkit_mastaba02_roof04_oasis", "loctypes"),
            new GamevalEntry(46791, "WALLKIT_MASTABA_DEBRIS01_OASIS", "wallkit_mastaba_debris01_oasis", "loctypes"),
            new GamevalEntry(46792, "WALLKIT_MASTABA_DEBRIS02_OASIS", "wallkit_mastaba_debris02_oasis", "loctypes"),
            new GamevalEntry(46793, "ROCKSLIDE1_OASIS", "Rockslide", "loctypes"),
            new GamevalEntry(46794, "ROCKSLIDE2_OASIS", "Rockslide", "loctypes"),
            new GamevalEntry(46795, "ROCKSLIDE3_OASIS", "Rockslide", "loctypes"),
            new GamevalEntry(46796, "ROCKSLIDE4_OASIS", "Rockslide", "loctypes"),
            new GamevalEntry(46797, "ROCKSLIDE5_OASIS", "rockslide5_oasis", "loctypes"),
            new GamevalEntry(46798, "ROCKSLIDE6_OASIS", "rockslide6_oasis", "loctypes"),
            new GamevalEntry(46799, "DUGUPSOIL_OASIS_1", "dugupsoil_oasis_1", "loctypes"),
            new GamevalEntry(46800, "DUGUPSOIL_OASIS_2", "dugupsoil_oasis_2", "loctypes"),
            new GamevalEntry(46801, "DUGUPSOIL_OASIS_3", "dugupsoil_oasis_3", "loctypes"),
            new GamevalEntry(46802, "OASIS_WOODEN_TABLE_TEA", "Table", "loctypes"),
            new GamevalEntry(46803, "SKEWSTEPS_WOOD01_OASIS", "skewsteps_wood01_oasis", "loctypes"),
            new GamevalEntry(46804, "OASIS_SUPPORT_OUTDOORS", "oasis_support_outdoors", "loctypes"),
            new GamevalEntry(46805, "WELL_OASIS", "Well", "loctypes"),
            new GamevalEntry(46806, "DRESSING_SCREEN_OASIS", "dressing_screen_oasis", "loctypes"),
            new GamevalEntry(46807, "TENT_OASIS", "Tent", "loctypes"),
            new GamevalEntry(46808, "CAMPING_EQUIPMENT_OASIS", "Camping Equipment", "loctypes"),
            new GamevalEntry(46809, "CAMPFIRE_OASIS", "Campfire", "loctypes"),
            new GamevalEntry(46810, "ELID_CRATES_2", "Crates", "loctypes"),
            new GamevalEntry(46811, "ELID_LADDER_BOTTOM", "Ladder", "loctypes"),
            new GamevalEntry(46812, "ELID_LADDER_TOP", "Ladder", "loctypes"),
            new GamevalEntry(46813, "ELID_INCENSE_BURNER", "Incense burner", "loctypes"),
            new GamevalEntry(46814, "QUEST_START_ICON_SECRETSOFTHENORTH", "quest_start_icon_secretsofthenorth", "loctypes"),
            new GamevalEntry(46815, "MY2ARM_TOWN_FENCE_BROKEN_SHORTCUT_MULTI", "my2arm_town_fence_broken_shortcut_multi", "loctypes"),
            new GamevalEntry(46816, "MY2ARM_TOWN_FENCE_ACTIVE", "Fence", "loctypes"),
            new GamevalEntry(46817, "MY2ARM_TOWN_FENCE_BROKEN_SHORTCUT", "Broken fence", "loctypes"),
            new GamevalEntry(46818, "MY2ARM_CAVE_ROCKS_SMALL_01", "my2arm_cave_rocks_small_01", "loctypes"),
            new GamevalEntry(46819, "MY2ARM_CAVE_ROCKS_SMALL_02", "my2arm_cave_rocks_small_02", "loctypes"),
            new GamevalEntry(46820, "MY2ARM_CAVE_ROCKS_SMALL_03", "my2arm_cave_rocks_small_03", "loctypes"),
            new GamevalEntry(46821, "MY2ARM_CAVE_ROCKS01", "my2arm_cave_rocks01", "loctypes"),
            new GamevalEntry(46822, "MY2ARM_CAVE_ROCKS02", "my2arm_cave_rocks02", "loctypes"),
            new GamevalEntry(46823, "MY2ARM_CAVE_ROCKS03", "my2arm_cave_rocks03", "loctypes"),
            new GamevalEntry(46824, "MY2ARM_CAVE_FENCE", "my2arm_cave_fence", "loctypes"),
            new GamevalEntry(46825, "MY2ARM_MINE_WALL", "my2arm_mine_wall", "loctypes"),
            new GamevalEntry(46826, "MY2ARM_MINE_WALL_SNOWTOP", "my2arm_mine_wall_snowtop", "loctypes"),
            new GamevalEntry(46827, "MY2ARM_MINE_WALL_SNOWTOP_TRANSITION", "my2arm_mine_wall_snowtop_transition", "loctypes"),
            new GamevalEntry(46828, "MY2ARM_MINE_WALL_SNOWTOP_TRANSITION_MIRROR", "my2arm_mine_wall_snowtop_transition_mirror", "loctypes"),
            new GamevalEntry(46829, "MY2ARM_MINE_WALL_TOP", "my2arm_mine_wall_top", "loctypes"),
            new GamevalEntry(46830, "MY2ARM_MINE_WALL_TOP_SNOW01", "my2arm_mine_wall_top_snow01", "loctypes"),
            new GamevalEntry(46831, "MY2ARM_MINE_WALL_TOP_BLANK", "my2arm_mine_wall_top_blank", "loctypes"),
            new GamevalEntry(46832, "MY2ARM_MINE_WALL_TOP_FALLOFF_STRAIGHT", "my2arm_mine_wall_top_falloff_straight", "loctypes"),
            new GamevalEntry(46833, "MY2ARM_MINE_WALL_TOP_FALLOFF_STRAIGHT_SNOW", "my2arm_mine_wall_top_falloff_straight_snow", "loctypes"),
            new GamevalEntry(46834, "MY2ARM_MINE_WALL_TOP_FALLOFF_INSIDE_CORNER", "my2arm_mine_wall_top_falloff_inside_corner", "loctypes"),
            new GamevalEntry(46835, "MY2ARM_MINE_WALL_TOP_FALLOFF_INSIDE_CORNER_SNOW", "my2arm_mine_wall_top_falloff_inside_corner_snow", "loctypes"),
            new GamevalEntry(46836, "MY2ARM_MINE_WALL_TOP_FALLOFF_OUTSIDE_CORNER", "my2arm_mine_wall_top_falloff_outside_corner", "loctypes"),
            new GamevalEntry(46837, "MY2ARM_MINE_WALL_TOP_FALLOFF_OUTSIDE_CORNER_SNOW", "my2arm_mine_wall_top_falloff_outside_corner_snow", "loctypes"),
            new GamevalEntry(46838, "MY2ARM_MINE_WALL_TOP_SOLID", "my2arm_mine_wall_top_solid", "loctypes"),
            new GamevalEntry(46839, "MY2ARM_MINE_WALL_CAVE_EXIT_02_VIS", "Cave", "loctypes"),
            new GamevalEntry(46840, "MY2ARM_MINE_WALL_3WIDE", "Wall", "loctypes"),
            new GamevalEntry(46841, "MY2ARM_BED", "Bed", "loctypes"),
            new GamevalEntry(46842, "DEVIOUS_ALTAR_POUCH_NOOP", "Altar", "loctypes"),
            new GamevalEntry(46843, "DEVIOUS_ALTAR_SCORCHED_NOOP", "Altar", "loctypes"),
            new GamevalEntry(46844, "KARUULM_HYDRA_ROOM_FLOOR_VENT_MIDDLE_BLANK", "karuulm_hydra_room_floor_vent_middle_blank", "loctypes"),
            new GamevalEntry(46845, "SHAYZIEN_PILLOW", "Pillow", "loctypes"),
            new GamevalEntry(46846, "NECROPOLIS_TENT_DEFAULT02_CROC", "Tent", "loctypes"),
            new GamevalEntry(46847, "NOTICEBOARD_ALT", "Noticeboard", "loctypes"),
            new GamevalEntry(46848, "DRAWERS2_NOOP", "Drawers", "loctypes"),
            new GamevalEntry(46849, "BOOKCASE2_NOOP", "Bookcase", "loctypes"),
            new GamevalEntry(46850, "DRESSING_SCREEN_INACTIVE", "dressing_screen_inactive", "loctypes"),
            new GamevalEntry(46851, "ALTAR_NOOP", "Altar", "loctypes"),
            new GamevalEntry(46852, "COOKINGSHELVES_SEARCH", "Cooking shelves", "loctypes"),
            new GamevalEntry(46853, "BASIC_WALL_HIDDEN_DOOR", "basic_wall_hidden_door", "loctypes"),
            new GamevalEntry(46854, "BASIC_WALL_HIDDEN_DOOR_NO_PADLOCK", "basic_wall_hidden_door_no_padlock", "loctypes"),
            new GamevalEntry(46855, "BASIC_WALL_HIDDEN_DOOR_MOSSY", "basic_wall_hidden_door_mossy", "loctypes"),
            new GamevalEntry(46856, "BASIC_WALL_HIDDEN_DOOR_MOSSY_NO_PADLOCK", "basic_wall_hidden_door_mossy_no_padlock", "loctypes"),
            new GamevalEntry(46857, "BASIC_WALL_HIDDEN_DOOR_OLD", "basic_wall_hidden_door_old", "loctypes"),
            new GamevalEntry(46858, "BASIC_WALL_HIDDEN_DOOR_OLD_NO_PADLOCK", "basic_wall_hidden_door_old_no_padlock", "loctypes"),
            new GamevalEntry(46859, "STAIRSTOP_NOOP", "Staircase", "loctypes"),
            new GamevalEntry(46860, "CASTLEDOUBLEDOORL_NOOP", "Large door", "loctypes"),
            new GamevalEntry(46861, "CASTLEDOUBLEDOORR_NOOP", "Large door", "loctypes"),
            new GamevalEntry(46862, "POSHDOOR_NOOP", "Door", "loctypes"),
            new GamevalEntry(46863, "POSHDOOR_REVERSE", "Door", "loctypes"),
            new GamevalEntry(46864, "POSHDOOROPEN_REVERSE", "Door", "loctypes"),
            new GamevalEntry(46865, "TRAPDOOR_LOCKED_NOOP", "Trapdoor", "loctypes"),
            new GamevalEntry(46866, "BGSOUND_FIRE_SMALL_5", "bgsound_fire_small_5", "loctypes"),
            new GamevalEntry(46867, "BGSOUND_TOTE_MAGIC_HUM_5", "bgsound_tote_magic_hum_5", "loctypes"),
            new GamevalEntry(46868, "BGSOUND_SOTN_ICE_WIND_LOOP", "bgsound_sotn_ice_wind_loop", "loctypes"),
            new GamevalEntry(46869, "RANDOMSOUND_SOTN_ICE_GAP", "randomsound_sotn_ice_gap", "loctypes"),
            new GamevalEntry(46870, "RANDOMSOUND_SOTN_DUNGEON_AMBIENCE", "randomsound_sotn_dungeon_ambience", "loctypes"),
            new GamevalEntry(46871, "SOTN_BROKEN_GLASS", "sotn_broken_glass", "loctypes"),
            new GamevalEntry(46872, "SOTN_ROWBOAT", "sotn_rowboat", "loctypes"),
            new GamevalEntry(46873, "SOTN_HUNTING_BARREL", "sotn_hunting_barrel", "loctypes"),
            new GamevalEntry(46874, "SOTN_HUNTING_BOULDER1", "sotn_hunting_boulder1", "loctypes"),
            new GamevalEntry(46875, "SOTN_HUNTING_BOULDER2", "sotn_hunting_boulder2", "loctypes"),
            new GamevalEntry(46876, "SOTN_HUNTING_FALLEN_TREE", "sotn_hunting_fallen_tree", "loctypes"),
            new GamevalEntry(46877, "SOTN_HUNTING_TREESTUMP", "sotn_hunting_treestump", "loctypes"),
            new GamevalEntry(46878, "SOTN_HUNTING_BUSH", "sotn_hunting_bush", "loctypes"),
            new GamevalEntry(46879, "SOTN_HUNTING_TRAIL_1", "sotn_hunting_trail_1", "loctypes"),
            new GamevalEntry(46880, "SOTN_HUNTING_TRAIL_1_CORNER", "sotn_hunting_trail_1_corner", "loctypes"),
            new GamevalEntry(46881, "SOTN_HUNTING_TRAIL_1_CORNER_MIRROR", "sotn_hunting_trail_1_corner_mirror", "loctypes"),
            new GamevalEntry(46882, "SOTN_HUNTING_TRAIL_2", "sotn_hunting_trail_2", "loctypes"),
            new GamevalEntry(46883, "SOTN_HUNTING_TRAIL_2_CORNER", "sotn_hunting_trail_2_corner", "loctypes"),
            new GamevalEntry(46884, "SOTN_HUNTING_TRAIL_2_CORNER_MIRROR", "sotn_hunting_trail_2_corner_mirror", "loctypes"),
            new GamevalEntry(46885, "SOTN_HUNTING_TRAIL_3", "sotn_hunting_trail_3", "loctypes"),
            new GamevalEntry(46886, "SOTN_HUNTING_TRAIL_3_CORNER", "sotn_hunting_trail_3_corner", "loctypes"),
            new GamevalEntry(46887, "SOTN_HUNTING_TRAIL_3_CORNER_MIRROR", "sotn_hunting_trail_3_corner_mirror", "loctypes"),
            new GamevalEntry(46888, "SOTN_HUNTING_TRAIL_4", "sotn_hunting_trail_4", "loctypes"),
            new GamevalEntry(46889, "SOTN_HUNTING_TRAIL_4_CORNER", "sotn_hunting_trail_4_corner", "loctypes"),
            new GamevalEntry(46890, "SOTN_HUNTING_TRAIL_4_CORNER_MIRROR", "sotn_hunting_trail_4_corner_mirror", "loctypes"),
            new GamevalEntry(46891, "SOTN_HUNTING_TRAIL_5", "sotn_hunting_trail_5", "loctypes"),
            new GamevalEntry(46892, "SOTN_HUNTING_TRAIL_5_CORNER", "sotn_hunting_trail_5_corner", "loctypes"),
            new GamevalEntry(46893, "SOTN_HUNTING_TRAIL_5_CORNER_MIRROR", "sotn_hunting_trail_5_corner_mirror", "loctypes"),
            new GamevalEntry(46894, "SOTN_HUNTING_TRAIL_6", "sotn_hunting_trail_6", "loctypes"),
            new GamevalEntry(46895, "SOTN_HUNTING_TRAIL_6_CORNER", "sotn_hunting_trail_6_corner", "loctypes"),
            new GamevalEntry(46896, "SOTN_HUNTING_TRAIL_6_CORNER_MIRROR", "sotn_hunting_trail_6_corner_mirror", "loctypes"),
            new GamevalEntry(46897, "SOTN_HIDDEN_DOOR_1", "sotn_hidden_door_1", "loctypes"),
            new GamevalEntry(46898, "SOTN_HIDDEN_DOOR_2", "sotn_hidden_door_2", "loctypes"),
            new GamevalEntry(46899, "SOTN_HIDDEN_CHEST_CLOSED", "sotn_hidden_chest_closed", "loctypes"),
            new GamevalEntry(46900, "SOTN_GHORROCK_LEVER", "sotn_ghorrock_lever", "loctypes"),
            new GamevalEntry(46901, "MUSPAH_SCOREBOARD_MULTI", "muspah_scoreboard_multi", "loctypes"),
            new GamevalEntry(46902, "CARNILLEANBOOKCASE", "carnilleanbookcase", "loctypes"),
            new GamevalEntry(46903, "CARNILLEANSHUTCHEST", "carnilleanshutchest", "loctypes"),
            new GamevalEntry(46904, "CARNILLEAN_DOG_GRAVE", "carnillean_dog_grave", "loctypes"),
            new GamevalEntry(46905, "MY2ARM_MINE_WALL_CAVE_EXIT_02", "my2arm_mine_wall_cave_exit_02", "loctypes"),
            new GamevalEntry(46906, "DEVIOUS_ALTAR_NOOP", "devious_altar_noop", "loctypes"),
            new GamevalEntry(46907, "RAT_BOSS_WATERFALL01", "rat_boss_waterfall01", "loctypes"),
            new GamevalEntry(46908, "RAT_BOSS_WATERFALL_FOAM01", "rat_boss_waterfall_foam01", "loctypes"),
            new GamevalEntry(46909, "LOTG_WIRED_MUSHROOM_RING_MIDDLE_THERE", "lotg_wired_mushroom_ring_middle_there", "loctypes"),
            new GamevalEntry(46910, "WILD_VETION_COFFIN02", "Desecrated Tomb", "loctypes"),
            new GamevalEntry(46911, "WILD_VETION_COFFIN03", "Desecrated Tomb", "loctypes"),
            new GamevalEntry(46912, "WILD_VETION_ROCKS01", "wild_vetion_rocks01", "loctypes"),
            new GamevalEntry(46913, "WILD_VETION_ROCKS02", "wild_vetion_rocks02", "loctypes"),
            new GamevalEntry(46914, "CAVEKIT_ROCK03_HIGH01", "cavekit_rock03_high01", "loctypes"),
            new GamevalEntry(46915, "CAVEKIT_ROCK03_HIGH01_NOSHADOW", "cavekit_rock03_high01_noshadow", "loctypes"),
            new GamevalEntry(46916, "CAVEKIT_ROCK03_HIGH02", "cavekit_rock03_high02", "loctypes"),
            new GamevalEntry(46917, "CAVEKIT_ROCK03_HIGH01_DARK", "cavekit_rock03_high01_dark", "loctypes"),
            new GamevalEntry(46918, "CAVEKIT_ROCK03_HIGH02_DARK", "cavekit_rock03_high02_dark", "loctypes"),
            new GamevalEntry(46919, "CAVEKIT_ROCK03_LOW01", "cavekit_rock03_low01", "loctypes"),
            new GamevalEntry(46920, "CAVEKIT_ROCK03_LOW02", "cavekit_rock03_low02", "loctypes"),
            new GamevalEntry(46921, "CAVEKIT_ROCK03_ARCH01", "cavekit_rock03_arch01", "loctypes"),
            new GamevalEntry(46922, "CAVEKIT_ROCK03_ARCH01_MIRROR", "cavekit_rock03_arch01_mirror", "loctypes"),
            new GamevalEntry(46923, "CAVEKIT_ROCK03_ARCH02", "cavekit_rock03_arch02", "loctypes"),
            new GamevalEntry(46924, "CAVEKIT_ROCK03_ARCH02_MIRROR", "cavekit_rock03_arch02_mirror", "loctypes"),
            new GamevalEntry(46925, "WILD_VETION_EXIT01", "Cave", "loctypes"),
            new GamevalEntry(46926, "CAVEKIT_ROCK03_PILLAR01_LOWER01", "cavekit_rock03_pillar01_lower01", "loctypes"),
            new GamevalEntry(46927, "CAVEKIT_ROCK03_PILLAR01_UPPER01", "cavekit_rock03_pillar01_upper01", "loctypes"),
            new GamevalEntry(46928, "CAVEKIT_ROCK03_PILLAR01_LOWER01_MIRROR", "cavekit_rock03_pillar01_lower01_mirror", "loctypes"),
            new GamevalEntry(46929, "CAVEKIT_ROCK03_PILLAR01_LOWER02", "cavekit_rock03_pillar01_lower02", "loctypes"),
            new GamevalEntry(46930, "CAVEKIT_ROCK03_PILLAR01_LOWER02_MIRROR", "cavekit_rock03_pillar01_lower02_mirror", "loctypes"),
            new GamevalEntry(46931, "CAVEKIT_ROCK03_PILLAR01_UPPER02", "cavekit_rock03_pillar01_upper02", "loctypes"),
            new GamevalEntry(46932, "CAVEKIT_ROCK03_PILLAR01_UPPER02_MIRROR", "cavekit_rock03_pillar01_upper02_mirror", "loctypes"),
            new GamevalEntry(46933, "CAVEKIT_ROCK03_FLAG01", "cavekit_rock03_flag01", "loctypes"),
            new GamevalEntry(46934, "CAVEKIT_ROCK03_FLAG01_MIRROR", "cavekit_rock03_flag01_mirror", "loctypes"),
            new GamevalEntry(46935, "WILD_VETION_GRATE01_DEFAULT01", "wild_vetion_grate01_default01", "loctypes"),
            new GamevalEntry(46936, "WILD_VETION_GRATE01_EDGE01", "wild_vetion_grate01_edge01", "loctypes"),
            new GamevalEntry(46937, "WILD_VETION_GRATE01_EDGE01_MIRROR", "wild_vetion_grate01_edge01_mirror", "loctypes"),
            new GamevalEntry(46938, "WILD_VETION_GRATE01_EDGE02", "wild_vetion_grate01_edge02", "loctypes"),
            new GamevalEntry(46939, "WILD_VETION_GRATE01_EDGE02_MIRROR", "wild_vetion_grate01_edge02_mirror", "loctypes"),
            new GamevalEntry(46940, "WILD_VETION_GRATE01_CORNER01", "wild_vetion_grate01_corner01", "loctypes"),
            new GamevalEntry(46941, "WILD_VETION_GRATE01_CORNER01_MIRROR", "wild_vetion_grate01_corner01_mirror", "loctypes"),
            new GamevalEntry(46942, "WILD_VETION_GRATE01_CORNER02", "wild_vetion_grate01_corner02", "loctypes"),
            new GamevalEntry(46943, "WILD_VETION_GRATE01_CORNER02_MIRROR", "wild_vetion_grate01_corner02_mirror", "loctypes"),
            new GamevalEntry(46944, "WILD_VETION_DRIP01", "wild_vetion_drip01", "loctypes"),
            new GamevalEntry(46945, "WILD_VETION_RIPPLE01", "wild_vetion_ripple01", "loctypes"),
            new GamevalEntry(46946, "WILD_VETION_RIPPLE02", "wild_vetion_ripple02", "loctypes"),
            new GamevalEntry(46947, "WILD_VETION_RIPPLE03", "wild_vetion_ripple03", "loctypes"),
            new GamevalEntry(46948, "WILD_VETION_RUBBLE01", "wild_vetion_rubble01", "loctypes"),
            new GamevalEntry(46949, "LIGHT_GODRAY02_LARGE01", "light_godray02_large01", "loctypes"),
            new GamevalEntry(46950, "TILEKIT_BRICK01_DEFAULT01", "tilekit_brick01_default01", "loctypes"),
            new GamevalEntry(46951, "TILEKIT_BRICK01_DEFAULT02", "tilekit_brick01_default02", "loctypes"),
            new GamevalEntry(46952, "TILEKIT_BRICK01_DEFAULT03", "tilekit_brick01_default03", "loctypes"),
            new GamevalEntry(46953, "TILEKIT_BRICK01_BROKEN01", "tilekit_brick01_broken01", "loctypes"),
            new GamevalEntry(46954, "TILEKIT_BRICK01_BROKEN01_LIGHT", "tilekit_brick01_broken01_light", "loctypes"),
            new GamevalEntry(46955, "TILEKIT_BRICK01_BROKEN02", "tilekit_brick01_broken02", "loctypes"),
            new GamevalEntry(46956, "TILEKIT_BRICK01_BROKEN02_LIGHT", "tilekit_brick01_broken02_light", "loctypes"),
            new GamevalEntry(46957, "TILEKIT_BRICK01_BROKEN03", "tilekit_brick01_broken03", "loctypes"),
            new GamevalEntry(46958, "TILEKIT_BRICK01_BROKEN03_LIGHT", "tilekit_brick01_broken03_light", "loctypes"),
            new GamevalEntry(46959, "TILEKIT_BRICK01_BROKEN04", "tilekit_brick01_broken04", "loctypes"),
            new GamevalEntry(46960, "TILEKIT_BRICK01_BROKEN04_LIGHT", "tilekit_brick01_broken04_light", "loctypes"),
            new GamevalEntry(46961, "TILEKIT_BRICK01_BROKEN05", "tilekit_brick01_broken05", "loctypes"),
            new GamevalEntry(46962, "TILEKIT_BRICK01_BROKEN05_LIGHT", "tilekit_brick01_broken05_light", "loctypes"),
            new GamevalEntry(46963, "TILEKIT_BRICK01_BROKEN06", "tilekit_brick01_broken06", "loctypes"),
            new GamevalEntry(46964, "TILEKIT_BRICK01_BROKEN06_LIGHT", "tilekit_brick01_broken06_light", "loctypes"),
            new GamevalEntry(46965, "TILEKIT_BRICK01_BROKEN07", "tilekit_brick01_broken07", "loctypes"),
            new GamevalEntry(46966, "TILEKIT_BRICK01_BROKEN07_LIGHT", "tilekit_brick01_broken07_light", "loctypes"),
            new GamevalEntry(46967, "TILEKIT_BRICK01_BROKEN08", "tilekit_brick01_broken08", "loctypes"),
            new GamevalEntry(46968, "TILEKIT_BRICK01_BROKEN08_LIGHT", "tilekit_brick01_broken08_light", "loctypes"),
            new GamevalEntry(46969, "TILEKIT_BRICK01_BROKEN09", "tilekit_brick01_broken09", "loctypes"),
            new GamevalEntry(46970, "TILEKIT_BRICK01_BROKEN09_LIGHT", "tilekit_brick01_broken09_light", "loctypes"),
            new GamevalEntry(46971, "TILEKIT_BRICK01_BROKEN10", "tilekit_brick01_broken10", "loctypes"),
            new GamevalEntry(46972, "TILEKIT_BRICK01_BROKEN10_LIGHT", "tilekit_brick01_broken10_light", "loctypes"),
            new GamevalEntry(46973, "TILEKIT_BRICK01_BROKEN11", "tilekit_brick01_broken11", "loctypes"),
            new GamevalEntry(46974, "TILEKIT_BRICK01_BROKEN12", "tilekit_brick01_broken12", "loctypes"),
            new GamevalEntry(46975, "TILEKIT_BRICK01_BROKEN13", "tilekit_brick01_broken13", "loctypes"),
            new GamevalEntry(46976, "TILEKIT_BRICK01_BROKEN14", "tilekit_brick01_broken14", "loctypes"),
            new GamevalEntry(46977, "TILEKIT_BRICK01_BROKEN15", "tilekit_brick01_broken15", "loctypes"),
            new GamevalEntry(46978, "TILEKIT_BRICK01_BROKEN16", "tilekit_brick01_broken16", "loctypes"),
            new GamevalEntry(46979, "TILEKIT_BRICK01_BROKEN17", "tilekit_brick01_broken17", "loctypes"),
            new GamevalEntry(46980, "TILEKIT_BRICK01_BROKEN18", "tilekit_brick01_broken18", "loctypes"),
            new GamevalEntry(46981, "TILEKIT_BRICK01_WATER01", "tilekit_brick01_water01", "loctypes"),
            new GamevalEntry(46982, "TILEKIT_BRICK01_CARPET01", "tilekit_brick01_carpet01", "loctypes"),
            new GamevalEntry(46983, "TILEKIT_BRICK01_CARPET02", "( +", "loctypes"),
            new GamevalEntry(46984, "TILEKIT_BRICK01_CARPET03", "tilekit_brick01_carpet03", "loctypes"),
            new GamevalEntry(46985, "TILEKIT_BRICK01_CARPET04", "tilekit_brick01_carpet04", "loctypes"),
            new GamevalEntry(46986, "TILEKIT_BRICK01_CARPET05", "tilekit_brick01_carpet05", "loctypes"),
            new GamevalEntry(46987, "TILEKIT_BRICK01_FABRIC01", "tilekit_brick01_fabric01", "loctypes"),
            new GamevalEntry(46988, "TILEKIT_BRICK01_FABRIC02", "tilekit_brick01_fabric02", "loctypes"),
            new GamevalEntry(46989, "TILEKIT_BRICK01_FABRIC03", "tilekit_brick01_fabric03", "loctypes"),
            new GamevalEntry(46990, "TILEKIT_BRICK01_FABRIC04", "tilekit_brick01_fabric04", "loctypes"),
            new GamevalEntry(46991, "WILD_VETION_FLAG01", "wild_vetion_flag01", "loctypes"),
            new GamevalEntry(46992, "WILD_VETION_SIGN01", "Signpost", "loctypes"),
            new GamevalEntry(46993, "WILD_VETION_CANDLES01", "Candles", "loctypes"),
            new GamevalEntry(46994, "WILD_VETION_CANDLES02", "Candles", "loctypes"),
            new GamevalEntry(46995, "WILD_VETION_ENTRANCE01", "Jump-Down", "loctypes"),
            new GamevalEntry(46996, "WILD_VETION_SINGLES_ENTRANCE01", "Memorial", "loctypes"),
            new GamevalEntry(46997, "WILD_VETION_BRICKS01", "wild_vetion_bricks01", "loctypes"),
            new GamevalEntry(46998, "WILD_VETION_BRICKS02", "wild_vetion_bricks02", "loctypes"),
            new GamevalEntry(46999, "WILD_VENANATIS_EXIT_NOOP", "wild_venanatis_exit_noop", "loctypes"),
            new GamevalEntry(47000, "WILD_VENANATIS_EXIT", "Cave", "loctypes"),
            new GamevalEntry(47001, "WILD_VENANATIS_CAVEWALLA", "wild_venanatis_cavewalla", "loctypes"),
            new GamevalEntry(47002, "WILD_VENANATIS_CAVEWALLB", "wild_venanatis_cavewallb", "loctypes"),
            new GamevalEntry(47003, "WILD_VENANATIS_CAVEWALLC", "wild_venanatis_cavewallc", "loctypes"),
            new GamevalEntry(47004, "WILD_VENANATIS_FALLOFF", "wild_venanatis_falloff", "loctypes"),
            new GamevalEntry(47005, "WILD_VENANATIS_EDGE_HALF1", "wild_venanatis_edge_half1", "loctypes"),
            new GamevalEntry(47006, "WILD_VENANATIS_EDGE_HALF2", "wild_venanatis_edge_half2", "loctypes"),
            new GamevalEntry(47007, "WILD_VENANATIS_EDGE_FULL1", "wild_venanatis_edge_full1", "loctypes"),
            new GamevalEntry(47008, "WILD_VENANATIS_EDGE_FULL2", "wild_venanatis_edge_full2", "loctypes"),
            new GamevalEntry(47009, "WILD_VENANATIS_EDGE_JOIN1", "wild_venanatis_edge_join1", "loctypes"),
            new GamevalEntry(47010, "WILD_VENANATIS_EDGE_JOIN2", "wild_venanatis_edge_join2", "loctypes"),
            new GamevalEntry(47011, "WILD_VENANATIS_CORNER_SMALL", "wild_venanatis_corner_small", "loctypes"),
            new GamevalEntry(47012, "WILD_VENANATIS_CORNER_INNER", "wild_venanatis_corner_inner", "loctypes"),
            new GamevalEntry(47013, "WILD_VENANATIS_CORNER", "wild_venanatis_corner", "loctypes"),
            new GamevalEntry(47014, "WILD_VENANATIS_PLANE", "wild_venanatis_plane", "loctypes"),
            new GamevalEntry(47015, "WILD_VENANATIS_PLANE_SB", "wild_venanatis_plane_sb", "loctypes"),
            new GamevalEntry(47016, "WILD_VENANATIS_CAVETOP", "wild_venanatis_cavetop", "loctypes"),
            new GamevalEntry(47017, "WILD_VENANATIS_CAVETOP_WALLTOP01", "wild_venanatis_cavetop_walltop01", "loctypes"),
            new GamevalEntry(47018, "WILD_VENANATIS_CAVETOP_WALLTOP02", "wild_venanatis_cavetop_walltop02", "loctypes"),
            new GamevalEntry(47019, "WILD_VENANATIS_CAVETOP_WALLTOP03", "wild_venanatis_cavetop_walltop03", "loctypes"),
            new GamevalEntry(47020, "WILD_VENANATIS_CAVETOP_WALLTOP04", "wild_venanatis_cavetop_walltop04", "loctypes"),
            new GamevalEntry(47021, "WILD_VENANATIS_STALAGMITE_WEBBED_LARGE", "wild_venanatis_stalagmite_webbed_large", "loctypes"),
            new GamevalEntry(47022, "WILD_VENANATIS_STALAGMITE_WEBBED_SMALL", "wild_venanatis_stalagmite_webbed_small", "loctypes"),
            new GamevalEntry(47023, "WILD_VENANATIS_STALAGMITE_WEBBED_CORNER", "wild_venanatis_stalagmite_webbed_corner", "loctypes"),
            new GamevalEntry(47024, "WILD_VENANATIS_DUGUPSOIL_1", "wild_venanatis_dugupsoil_1", "loctypes"),
            new GamevalEntry(47025, "WILD_VENANATIS_DUGUPSOIL_2", "wild_venanatis_dugupsoil_2", "loctypes"),
            new GamevalEntry(47026, "WILD_VENANATIS_DUGUPSOIL_3", "wild_venanatis_dugupsoil_3", "loctypes"),
            new GamevalEntry(47027, "WILD_VENANATIS_WEB01_FLOOR02", "wild_venanatis_web01_floor02", "loctypes"),
            new GamevalEntry(47028, "WILD_VENANATIS_ANCHOR01", "wild_venanatis_anchor01", "loctypes"),
            new GamevalEntry(47029, "WILD_VENANATIS_ANCHOR02", "wild_venanatis_anchor02", "loctypes"),
            new GamevalEntry(47030, "WILD_VENANATIS_ANCHOR03", "wild_venanatis_anchor03", "loctypes"),
            new GamevalEntry(47031, "WILD_VENANATIS_ANCHOR04", "wild_venanatis_anchor04", "loctypes"),
            new GamevalEntry(47032, "WILD_VENANATIS_ANCHOR05", "'2( u?u7", "loctypes"),
            new GamevalEntry(47033, "WILD_VENANATIS_ANCHOR06", "'2( u?u7", "loctypes"),
            new GamevalEntry(47034, "WILD_VENANATIS_ANCHOR07", "'2( u?u7", "loctypes"),
            new GamevalEntry(47035, "WILD_VENANATIS_ANCHOR08", "wild_venanatis_anchor08", "loctypes"),
            new GamevalEntry(47036, "WILD_VENANATIS_ANCHOR09", "'2( u?u7", "loctypes"),
            new GamevalEntry(47037, "WILD_VENANATIS_ANCHOR10", "wild_venanatis_anchor10", "loctypes"),
            new GamevalEntry(47038, "WILD_VENANATIS_PLATFORM01", "wild_venanatis_platform01", "loctypes"),
            new GamevalEntry(47039, "WILD_VENANATIS_PLATFORM02", "wild_venanatis_platform02", "loctypes"),
            new GamevalEntry(47040, "WILD_VENANATIS_PLATFORM03", "wild_venanatis_platform03", "loctypes"),
            new GamevalEntry(47041, "WILD_VENANATIS_PLATFORM04", "wild_venanatis_platform04", "loctypes"),
            new GamevalEntry(47042, "WILD_VENANATIS_PLATFORM05", "wild_venanatis_platform05", "loctypes"),
            new GamevalEntry(47043, "WILD_VENANATIS_PLATFORM06", "wild_venanatis_platform06", "loctypes"),
            new GamevalEntry(47044, "WILD_VENANATIS_PLATFORM07", "wild_venanatis_platform07", "loctypes"),
            new GamevalEntry(47045, "WILD_VENANATIS_PLATFORM08", "wild_venanatis_platform08", "loctypes"),
            new GamevalEntry(47046, "WILD_VENANATIS_PLATFORM09", "wild_venanatis_platform09", "loctypes"),
            new GamevalEntry(47047, "WILD_VENANATIS_PLATFORM10", "wild_venanatis_platform10", "loctypes"),
            new GamevalEntry(47048, "WILD_VENANATIS_PLATFORM11", "wild_venanatis_platform11", "loctypes"),
            new GamevalEntry(47049, "WILD_VENANATIS_PLATFORM12", "wild_venanatis_platform12", "loctypes"),
            new GamevalEntry(47050, "WILD_VENANATIS_PLATFORM13", "wild_venanatis_platform13", "loctypes"),
            new GamevalEntry(47051, "WILD_VENANATIS_PLATFORM14", "wild_venanatis_platform14", "loctypes"),
            new GamevalEntry(47052, "WILD_VENANATIS_PLATFORM15", "wild_venanatis_platform15", "loctypes"),
            new GamevalEntry(47053, "WILD_VENANATIS_PLATFORM16", "wild_venanatis_platform16", "loctypes"),
            new GamevalEntry(47054, "WILD_VENANATIS_PLATFORM17", "wild_venanatis_platform17", "loctypes"),
            new GamevalEntry(47055, "WILD_VENANATIS_PLATFORM18", "wild_venanatis_platform18", "loctypes"),
            new GamevalEntry(47056, "WILD_VENANATIS_PLATFORM19", "wild_venanatis_platform19", "loctypes"),
            new GamevalEntry(47057, "WILD_VENANATIS_PLATFORM20", "wild_venanatis_platform20", "loctypes"),
            new GamevalEntry(47058, "WILD_VENANATIS_PLATFORM21", "wild_venanatis_platform21", "loctypes"),
            new GamevalEntry(47059, "WILD_VENANATIS_PLATFORM22", "'2( u?u7", "loctypes"),
            new GamevalEntry(47060, "WILD_VENANATIS_PLATFORM23", "'2( u?u7", "loctypes"),
            new GamevalEntry(47061, "WILD_VENANATIS_PLATFORM24", "wild_venanatis_platform24", "loctypes"),
            new GamevalEntry(47062, "WILD_VENANATIS_PLATFORM25", "wild_venanatis_platform25", "loctypes"),
            new GamevalEntry(47063, "WILD_VENANATIS_PLATFORM26", "wild_venanatis_platform26", "loctypes"),
            new GamevalEntry(47064, "WILD_VENANATIS_PLATFORM27", "wild_venanatis_platform27", "loctypes"),
            new GamevalEntry(47065, "WILD_VENANATIS_PLATFORM28", "wild_venanatis_platform28", "loctypes"),
            new GamevalEntry(47066, "WILD_VENANATIS_PLATFORM29", "wild_venanatis_platform29", "loctypes"),
            new GamevalEntry(47067, "WILD_VENANATIS_PLATFORM30", "'2( u?u7", "loctypes"),
            new GamevalEntry(47068, "WILD_VENANATIS_WEBSACK_LAYING01", "Web sack", "loctypes"),
            new GamevalEntry(47069, "WILD_VENANATIS_WEBSACK_LAYING02", "Web sack", "loctypes"),
            new GamevalEntry(47070, "WILD_VENANATIS_WEBSACK_HANGING01", "Web sack", "loctypes"),
            new GamevalEntry(47071, "WILD_VENANATIS_WEBSACK_HANGING02", "Web sack", "loctypes"),
            new GamevalEntry(47072, "WILD_VENANATIS_WEB_CEILING01", "wild_venanatis_web_ceiling01", "loctypes"),
            new GamevalEntry(47073, "WILD_VENANATIS_WEB_CEILING02", "wild_venanatis_web_ceiling02", "loctypes"),
            new GamevalEntry(47074, "WILD_VENANATIS_WEB_FLOOR01", "wild_venanatis_web_floor01", "loctypes"),
            new GamevalEntry(47075, "WILD_VENANATIS_WEB_FLOOR02", "wild_venanatis_web_floor02", "loctypes"),
            new GamevalEntry(47076, "WILD_VENANATIS_WEB_FLOOR07", "wild_venanatis_web_floor07", "loctypes"),
            new GamevalEntry(47077, "WILD_VENANATIS_ENTRANCE01", "Cave Entrance", "loctypes"),
            new GamevalEntry(47078, "WILD_VENENATIS_SINGLES_ENTRANCE01", "Cave Entrance", "loctypes"),
            new GamevalEntry(47079, "WILD_VENANATIS_DUGUPSOIL_1_LIGHT", "wild_venanatis_dugupsoil_1_light", "loctypes"),
            new GamevalEntry(47080, "WILD_VENANATIS_DUGUPSOIL_2_LIGHT", "wild_venanatis_dugupsoil_2_light", "loctypes"),
            new GamevalEntry(47081, "WILD_VENANATIS_DUGUPSOIL_3_LIGHT", "wild_venanatis_dugupsoil_3_light", "loctypes"),
            new GamevalEntry(47082, "WILD_VENANATIS_GRASS01", "wild_venanatis_grass01", "loctypes"),
            new GamevalEntry(47083, "WILD_VENANATIS_SIGN01", "Signpost", "loctypes"),
            new GamevalEntry(47084, "WBR_VENENATIS_WEB_CENTRE", "wbr_venenatis_web_centre", "loctypes"),
            new GamevalEntry(47085, "WBR_VENENATIS_WEB_EDGE", "wbr_venenatis_web_edge", "loctypes"),
            new GamevalEntry(47086, "WBR_VENENATIS_WEB_CORNER", "wbr_venenatis_web_corner", "loctypes"),
            new GamevalEntry(47087, "TREE_PETRIFIED01_DEFAULT01", "tree_petrified01_default01", "loctypes"),
            new GamevalEntry(47088, "TREE_PETRIFIED01_DEFAULT02", "tree_petrified01_default02", "loctypes"),
            new GamevalEntry(47089, "TREE_PETRIFIED01_DEFAULT03", "tree_petrified01_default03", "loctypes"),
            new GamevalEntry(47090, "TREE_PETRIFIED01_DEFAULT04", "tree_petrified01_default04", "loctypes"),
            new GamevalEntry(47091, "TREE_PETRIFIED01_STUMP01", "tree_petrified01_stump01", "loctypes"),
            new GamevalEntry(47092, "TREE_PETRIFIED01_ROOT01", "tree_petrified01_root01", "loctypes"),
            new GamevalEntry(47093, "TREE_PETRIFIED01_ROOT01_DARK", "tree_petrified01_root01_dark", "loctypes"),
            new GamevalEntry(47094, "TREE_PETRIFIED01_ROOT02", "tree_petrified01_root02", "loctypes"),
            new GamevalEntry(47095, "TREE_PETRIFIED01_ROOT02_DARK", "tree_petrified01_root02_dark", "loctypes"),
            new GamevalEntry(47096, "TREE_PETRIFIED01_ROOT02_LIGHT", "tree_petrified01_root02_light", "loctypes"),
            new GamevalEntry(47097, "TREE_PETRIFIED01_ROOT03", "tree_petrified01_root03", "loctypes"),
            new GamevalEntry(47098, "TREE_PETRIFIED01_ROOT03_DARK", "tree_petrified01_root03_dark", "loctypes"),
            new GamevalEntry(47099, "TREE_PETRIFIED01_ROOT04", "tree_petrified01_root04", "loctypes"),
            new GamevalEntry(47100, "WILD_CALLISTO_SKULL01", "wild_callisto_skull01", "loctypes"),
            new GamevalEntry(47101, "WILD_CALLISTO_BONES01", "wild_callisto_bones01", "loctypes"),
            new GamevalEntry(47102, "WILD_CALLISTO_BONES02", "wild_callisto_bones02", "loctypes"),
            new GamevalEntry(47103, "WILD_CALLISTO_BONES03", "wild_callisto_bones03", "loctypes"),
        };
    }

    static Optional<GamevalEntry> byId(int id) {
        for (GamevalEntry entry : entries()) {
            if (entry.id() == id) return Optional.of(entry);
        }
        return Optional.empty();
    }

}
