package net.titan.gamevals.internal;

import java.util.Optional;

import net.titan.gamevals.GamevalEntry;
import net.titan.gamevals.QuestEntry;

final class ObjectIDEntries_30 {
    private ObjectIDEntries_30() {}

    static GamevalEntry[] entries() {
        return new GamevalEntry[] {
            new GamevalEntry(15420, "POH_STUDY_1", "Lectern space", "loctypes"),
            new GamevalEntry(15421, "POH_STUDY_2", "Globe space", "loctypes"),
            new GamevalEntry(15422, "POH_STUDY_4", "Crystal ball space", "loctypes"),
            new GamevalEntry(15423, "POH_STUDY_5", "Wall chart space", "loctypes"),
            new GamevalEntry(15424, "POH_STUDY_6", "Telescope space", "loctypes"),
            new GamevalEntry(15425, "POH_STUDY_7", "Bookcase space", "loctypes"),
            new GamevalEntry(15426, "POH_THRONE_ROOM_1", "Throne space", "loctypes"),
            new GamevalEntry(15427, "POH_THRONE_ROOM_3_RIMMINGTON", "Floor space", "loctypes"),
            new GamevalEntry(15428, "POH_THRONE_ROOM_3_LUMBRIDGE", "Floor space", "loctypes"),
            new GamevalEntry(15429, "POH_THRONE_ROOM_3_POLLNIVNEACH", "Floor space", "loctypes"),
            new GamevalEntry(15430, "POH_THRONE_ROOM_3_RELLEKKA", "Floor space", "loctypes"),
            new GamevalEntry(15431, "POH_THRONE_ROOM_3_BRIMHAVEN", "Floor space", "loctypes"),
            new GamevalEntry(15432, "POH_THRONE_ROOM_3_YANILLE", "Floor space", "loctypes"),
            new GamevalEntry(15433, "POH_THRONE_ROOM_3", "Decoration space", "loctypes"),
            new GamevalEntry(15434, "POH_THRONE_ROOM_3_Q", "Decoration space", "loctypes"),
            new GamevalEntry(15435, "POH_THRONE_ROOM_4", "Lever space", "loctypes"),
            new GamevalEntry(15436, "POH_THRONE_ROOM_5", "Seating space", "loctypes"),
            new GamevalEntry(15437, "POH_THRONE_ROOM_6", "Seating space", "loctypes"),
            new GamevalEntry(15438, "POH_THRONE_ROOM_7", "Trapdoor space", "loctypes"),
            new GamevalEntry(15439, "POH_WORKSHOP_1", "Workbench space", "loctypes"),
            new GamevalEntry(15440, "POH_WORKSHOP_1_STOOL", "T Nothing", "loctypes"),
            new GamevalEntry(15441, "POH_WORKSHOP_2", "Clockmaking space", "loctypes"),
            new GamevalEntry(15442, "POH_WORKSHOP_2_STOOL", "T Nothing", "loctypes"),
            new GamevalEntry(15443, "POH_WORKSHOP_3A", "Tool space", "loctypes"),
            new GamevalEntry(15444, "POH_WORKSHOP_3B", "Tool space", "loctypes"),
            new GamevalEntry(15445, "POH_WORKSHOP_3C", "Tool space", "loctypes"),
            new GamevalEntry(15446, "POH_WORKSHOP_3D", "Tool space", "loctypes"),
            new GamevalEntry(15447, "POH_WORKSHOP_3E", "Tool space", "loctypes"),
            new GamevalEntry(15448, "POH_WORKSHOP_4", "Repair space", "loctypes"),
            new GamevalEntry(15449, "POH_WORKSHOP_4_STOOL", "T Nothing", "loctypes"),
            new GamevalEntry(15450, "POH_WORKSHOP_5", "Heraldry space", "loctypes"),
            new GamevalEntry(15451, "WINT_FLOOR_B", "wint_floor_b", "loctypes"),
            new GamevalEntry(15452, "POH_PREVIEW_WALL", "Door", "loctypes"),
            new GamevalEntry(15453, "LUMBRIDGE_POH_ROOF_1_01", "lumbridge_poh_roof_1_01", "loctypes"),
            new GamevalEntry(15454, "LUMBRIDGE_POH_ROOF_1_02", "lumbridge_poh_roof_1_02", "loctypes"),
            new GamevalEntry(15455, "LUMBRIDGE_POH_ROOF_1_03", "lumbridge_poh_roof_1_03", "loctypes"),
            new GamevalEntry(15456, "LUMBRIDGE_POH_ROOF_1_04", "lumbridge_poh_roof_1_04", "loctypes"),
            new GamevalEntry(15457, "LUMBRIDGE_POH_ROOF_2_01", "lumbridge_poh_roof_2_01", "loctypes"),
            new GamevalEntry(15458, "LUMBRIDGE_POH_ROOF_2_02", "lumbridge_poh_roof_2_02", "loctypes"),
            new GamevalEntry(15459, "LUMBRIDGE_POH_ROOF_2_03", "lumbridge_poh_roof_2_03", "loctypes"),
            new GamevalEntry(15460, "LUMBRIDGE_POH_ROOF_2_04", "lumbridge_poh_roof_2_04", "loctypes"),
            new GamevalEntry(15461, "BOOKCASE_MAHOGANY", "Bookcase", "loctypes"),
            new GamevalEntry(15462, "POSH_CHAIR_MAHOGANY", "Chair", "loctypes"),
            new GamevalEntry(15463, "HATSTAND_MAHOGANY", "Hat stand", "loctypes"),
            new GamevalEntry(15464, "POH_ESTATE_AGENTS_WALL_PIECE", "Picture", "loctypes"),
            new GamevalEntry(15465, "POH_ESTATE_AGENTS_LOC_ITEM", "Display board", "loctypes"),
            new GamevalEntry(15466, "POH_STONEMASONS_LOC_ITEM", "Stone crusher", "loctypes"),
            new GamevalEntry(15467, "POH_SERVANT_LOC_ITEM", "Cleaning supplies", "loctypes"),
            new GamevalEntry(15468, "POH_SAWMILL_LOC_ITEM", "Power saw", "loctypes"),
            new GamevalEntry(15469, "POH_TAXIDERMIST_LOC_ITEM", "Embalming tube", "loctypes"),
            new GamevalEntry(15470, "POH_TAXIDERMIST_SHEEP_RUG", "poh_taxidermist_sheep_rug", "loctypes"),
            new GamevalEntry(15471, "POH_TAXIDERMISTS_TABLE_ITEM", "Fish bowl", "loctypes"),
            new GamevalEntry(15472, "POH_SERVANTS_GUILD_TABLE_ITEM", "Gloves and duster", "loctypes"),
            new GamevalEntry(15473, "POH_SERVENTS_GUILD_DININGTABLE", "Mahogany table", "loctypes"),
            new GamevalEntry(15474, "POH_SERVANTS_GUILD_WALL_PIECE", "poh_servants_guild_wall_piece", "loctypes"),
            new GamevalEntry(15475, "POH_STONEMASONS_WALL_PIECE", "poh_stonemasons_wall_piece", "loctypes"),
            new GamevalEntry(15476, "POH_TAXIDERMISTS_WALL_PIECE", "poh_taxidermists_wall_piece", "loctypes"),
            new GamevalEntry(15477, "POH_TAVERLY_PORTAL", "Portal", "loctypes"),
            new GamevalEntry(15478, "POH_RIMMINGTON_PORTAL", "Portal", "loctypes"),
            new GamevalEntry(15479, "POH_POLLNIVNEACH_PORTAL", "Portal", "loctypes"),
            new GamevalEntry(15480, "POH_RELLEKKA_PORTAL", "Portal", "loctypes"),
            new GamevalEntry(15481, "POH_BRIMHAVEN_PORTAL", "Portal", "loctypes"),
            new GamevalEntry(15482, "POH_YANILLE_PORTAL", "poh_yanille_portal", "loctypes"),
            new GamevalEntry(15483, "TOA_VAULT_ENTRY", "Entry", "loctypes"),
            new GamevalEntry(15484, "VM_DIGSITE_FINDS_COIN_SARANTHIUM", "? Study", "loctypes"),
            new GamevalEntry(15485, "VM_TIMELINE_RUNESTONE_ROCK_MODEL", "vm_timeline_runestone_rock_model", "loctypes"),
            new GamevalEntry(15486, "_100_ILM_CLIFF_CLIMB_2", "100_ilm_cliff_climb_2", "loctypes"),
            new GamevalEntry(15487, "_100_ILM_ROPE_SWING", "Rope", "loctypes"),
            new GamevalEntry(15488, "_100_ILM_LEANING_TREE", "Tropical tree", "loctypes"),
            new GamevalEntry(15489, "_100_ILM_LEANING_TREE_TOP", "Tropical tree", "loctypes"),
            new GamevalEntry(15490, "VM_NAT_HIS_KALPHITE_QUEEN", "Kalphite Queen", "loctypes"),
            new GamevalEntry(15491, "_100_ILM_VINE_HOLE", "Hole", "loctypes"),
            new GamevalEntry(15492, "_100_ILM_SNAKE_WALL_BASIC", "100_ilm_snake_wall_basic", "loctypes"),
            new GamevalEntry(15493, "_100_ILM_SNAKE_WALL_LOWHOLE", "100_ilm_snake_wall_lowhole", "loctypes"),
            new GamevalEntry(15494, "FAI_VARROCK_UNDERGROUND", "fai_varrock_underground", "loctypes"),
            new GamevalEntry(15495, "FAI_VARROCK_UNDERGROUND_JOIN", "fai_varrock_underground_join", "loctypes"),
            new GamevalEntry(15496, "FAI_VARROCK_UNDERGROUND_JOIN_MIRROR", "fai_varrock_underground_join_mirror", "loctypes"),
            new GamevalEntry(15497, "FAI_VARROCK_UNDERGROUND_DOUBLE", "fai_varrock_underground_double", "loctypes"),
            new GamevalEntry(15498, "FAI_VARROCK_UNDERGROUND_DOUBLE_TERM_L", "fai_varrock_underground_double_term_l", "loctypes"),
            new GamevalEntry(15499, "FAI_VARROCK_UNDERGROUND_DOUBLE_TERM_R", "fai_varrock_underground_double_term_r", "loctypes"),
            new GamevalEntry(15500, "FAI_VARROCK_UNDERGROUND_SUPPORT", "fai_varrock_underground_support", "loctypes"),
            new GamevalEntry(15501, "FAI_VARROCK_UNDERGROUND_SUPPORT2", "fai_varrock_underground_support2", "loctypes"),
            new GamevalEntry(15502, "_100_ILM_SNAKE_WALL_HIGHHOLE", "100_ilm_snake_wall_highhole", "loctypes"),
            new GamevalEntry(15503, "_100_ILM_SNAKE_WALL_MIDHOLE", "100_ilm_snake_wall_midhole", "loctypes"),
            new GamevalEntry(15504, "_100_ILM_SNAKE_WALL_2HOLES", "100_ilm_snake_wall_2holes", "loctypes"),
            new GamevalEntry(15505, "_100_ILM_SNAKE_WALLROCKS", "100_ilm_snake_wallrocks", "loctypes"),
            new GamevalEntry(15506, "FAI_VARROCK_WHEAT", "Wheat", "loctypes"),
            new GamevalEntry(15507, "FAI_VARROCK_WHEAT_CORNER", "Wheat", "loctypes"),
            new GamevalEntry(15508, "FAI_VARROCK_WHEAT_SMALL", "Wheat", "loctypes"),
            new GamevalEntry(15509, "II_FENCING", "ii_fencing", "loctypes"),
            new GamevalEntry(15510, "II_FENCEGATE_L", "Gate", "loctypes"),
            new GamevalEntry(15511, "II_FENCEGATE_LC", "Gate", "loctypes"),
            new GamevalEntry(15512, "II_FENCEGATE_R", "Gate", "loctypes"),
            new GamevalEntry(15513, "II_FENCEGATE_RC", "Gate", "loctypes"),
            new GamevalEntry(15514, "FAI_VARROCK_GATE_L", "Gate", "loctypes"),
            new GamevalEntry(15515, "FAI_VARROCK_GATE_LC", "Gate", "loctypes"),
            new GamevalEntry(15516, "FAI_VARROCK_GATE_R", "Gate", "loctypes"),
            new GamevalEntry(15517, "FAI_VARROCK_GATE_RC", "Gate", "loctypes"),
            new GamevalEntry(15518, "WH_WITCHMOUSEHOLE", "Mouse hole", "loctypes"),
            new GamevalEntry(15519, "GRIM_WITCHMOUSEHOLE", "Mouse hole", "loctypes"),
            new GamevalEntry(15520, "GRIM_RANDOMSOUND_WOLF", "grim_randomsound_wolf", "loctypes"),
            new GamevalEntry(15521, "GRIM_GRANDPIANO_STOOL", "Piano stool", "loctypes"),
            new GamevalEntry(15522, "GRIM_SIGNPOST", "Signpost", "loctypes"),
            new GamevalEntry(15523, "GRIM_TRAPDOOR_CLOSED", "Trapdoor", "loctypes"),
            new GamevalEntry(15524, "GRIM_WATCHTOWER_BARREL", "Barrel", "loctypes"),
            new GamevalEntry(15525, "GRIM_MOUSE_HOLE_WALL_TOP", "grim_mouse_hole_wall_top", "loctypes"),
            new GamevalEntry(15526, "GRIM_MOUSE_HOLE_WALL_TOP5", "grim_mouse_hole_wall_top5", "loctypes"),
            new GamevalEntry(15527, "GRIM_MOUSE_FLOOR_01", "grim_mouse_floor_01", "loctypes"),
            new GamevalEntry(15528, "GRIM_MOUSE_FLOOR_02", "grim_mouse_floor_02", "loctypes"),
            new GamevalEntry(15529, "GRIM_MOUSE_FLOOR_03", "grim_mouse_floor_03", "loctypes"),
            new GamevalEntry(15530, "GRIM_MOUSE_FLOOR_04", "grim_mouse_floor_04", "loctypes"),
            new GamevalEntry(15531, "POH_PORTAL_ICON", "poh_portal_icon", "loctypes"),
            new GamevalEntry(15532, "POH_ESTATEAGENT_ICON", "poh_estateagent_icon", "loctypes"),
            new GamevalEntry(15533, "POH_SAWMILL_ICON", "poh_sawmill_icon", "loctypes"),
            new GamevalEntry(15534, "POH_STONEMASON_ICON", "poh_stonemason_icon", "loctypes"),
            new GamevalEntry(15535, "_100_ILM_SNAKE_WALLROCKS_MIRROR", "100_ilm_snake_wallrocks_mirror", "loctypes"),
            new GamevalEntry(15536, "_100_ILM_SNAKE_ROCKS", "Rock", "loctypes"),
            new GamevalEntry(15537, "_100_ILM_SNAKE_ROCKS2", "Rock", "loctypes"),
            new GamevalEntry(15538, "_100_ILM_SNAKE_HOLE", "100_ilm_snake_hole", "loctypes"),
            new GamevalEntry(15539, "_100_ILM_SNAKE_HIGHWALL_BASIC", "100_ilm_snake_highwall_basic", "loctypes"),
            new GamevalEntry(15540, "_100_ILM_SNAKE_HIGHWALL_HOLE", "100_ilm_snake_highwall_hole", "loctypes"),
            new GamevalEntry(15541, "_100_ILM_SNAKE_LOW", "Snake", "loctypes"),
            new GamevalEntry(15542, "_100_ILM_SNAKE_UPPER_WALL", "Snake", "loctypes"),
            new GamevalEntry(15543, "_100_ILM_SNAKE_MID", "Snake", "loctypes"),
            new GamevalEntry(15544, "_100_ILM_SNAKE_HIGH", "Hole", "loctypes"),
            new GamevalEntry(15545, "_100_ILM_SNAKE_GROUND", "Snake", "loctypes"),
            new GamevalEntry(15546, "_100_ILM_SNAKE_OUT_THEN_IN", "Snake", "loctypes"),
            new GamevalEntry(15547, "LOTR_ARMOUR_GROUND", "Armour", "loctypes"),
            new GamevalEntry(15548, "LOTR_ARMOUR_GROUND_REFORM", "Armour", "loctypes"),
            new GamevalEntry(15549, "LOTR_SKELETON_01_GROUND", "Skeleton", "loctypes"),
            new GamevalEntry(15550, "LOTR_SKELETON_01_GROUND_REFORM", "Skeleton", "loctypes"),
            new GamevalEntry(15551, "LOTR_SKELETON_02_GROUND", "Skeleton", "loctypes"),
            new GamevalEntry(15552, "FAI_VARROCK_ROOFKIT_SLATE", "fai_varrock_roofkit_slate", "loctypes"),
            new GamevalEntry(15553, "FAI_VARROCK_ROOFKIT_SLATE_CUT", "fai_varrock_roofkit_slate_cut", "loctypes"),
            new GamevalEntry(15554, "FAI_VARROCK_ROOFKIT_SLATE_CUT_MIRROR", "fai_varrock_roofkit_slate_cut_mirror", "loctypes"),
            new GamevalEntry(15555, "FAI_VARROCK_ROOFKIT_SLATE_CUT_CORNER", "fai_varrock_roofkit_slate_cut_corner", "loctypes"),
            new GamevalEntry(15556, "FAI_VARROCK_ROOFKIT_SLATE_CUT_CORNER_MIRROR", "fai_varrock_roofkit_slate_cut_corner_mirror", "loctypes"),
            new GamevalEntry(15557, "FAI_VARROCK_ROOFKIT_SLATE_WALL", "fai_varrock_roofkit_slate_wall", "loctypes"),
            new GamevalEntry(15558, "FAI_VARROCK_ROOFKIT_SLATE_WALL_CUT", "fai_varrock_roofkit_slate_wall_cut", "loctypes"),
            new GamevalEntry(15559, "LOTR_SKELETON_02_GROUND_REFORM", "Skeleton", "loctypes"),
            new GamevalEntry(15560, "LOTR_LIVING_AREA_LOCKER", "Locker", "loctypes"),
            new GamevalEntry(15561, "DRAGONMOUNTEDHEAD_OFFSET", "Dragon's head", "loctypes"),
            new GamevalEntry(15562, "DRAGONMOUNTEDHEAD2", "Dragon's head", "loctypes"),
            new GamevalEntry(15563, "DRAGONMOUNTEDHEAD2_OFFSET", "Dragon's head", "loctypes"),
            new GamevalEntry(15564, "DRAGONMOUNTEDHEAD3", "Dragon's head", "loctypes"),
            new GamevalEntry(15565, "DRAGONMOUNTEDHEAD3_OFFSET", "Dragon's head", "loctypes"),
            new GamevalEntry(15566, "GOBLIN_CAVES_WARNINGSIGN", "Warning sign", "loctypes"),
            new GamevalEntry(15567, "LOTR_LIVING_AREA_STOOL", "Stool", "loctypes"),
            new GamevalEntry(15568, "LOTR_LIVING_AREA_SMALL_TABLE", "Small table", "loctypes"),
            new GamevalEntry(15569, "LOTR_LIVING_AREA_BOOKCASE", "Bookcase", "loctypes"),
            new GamevalEntry(15570, "_100_ILM_SNAKE_OUT_THEN_IN8", "Snake", "loctypes"),
            new GamevalEntry(15571, "_100_ILM_LIGHT_STREAMING_WITH_ROPE", "Rope", "loctypes"),
            new GamevalEntry(15572, "_100_ILM_SNAKEPIT_ENTRANCE", "Enter", "loctypes"),
            new GamevalEntry(15573, "_100_ILM_TCHIKI_NUT_BUSH", "Tchiki Monkey Nut Bush", "loctypes"),
            new GamevalEntry(15574, "_100_ILM_RED_BANANA_TREE", "Strange banana tree", "loctypes"),
            new GamevalEntry(15575, "_100_ILM_LIGHT_STREAMING_WITH_VINE", "Light", "loctypes"),
            new GamevalEntry(15576, "_100_ILM_BANANA_TREE_SUPER_BEFORE", "Banana tree", "loctypes"),
            new GamevalEntry(15577, "_100_ILM_BANANA_TREE_BEFORE", "Banana tree", "loctypes"),
            new GamevalEntry(15578, "_100_ILM_BANANA_TREE_DURING", "Red Banana Tree", "loctypes"),
            new GamevalEntry(15579, "_100_ILM_BANANA_TREE_AFTER", "Red Banana Tree", "loctypes"),
            new GamevalEntry(15580, "_100_ILM_BANANA_TREE_MULTILOC", "100_ilm_banana_tree_multiloc", "loctypes"),
            new GamevalEntry(15581, "_100_ILM_HOTCOAL_01", "100_ilm_hotcoal_01", "loctypes"),
            new GamevalEntry(15582, "_100_ILM_HOTCOAL_03", "100_ilm_hotcoal_03", "loctypes"),
            new GamevalEntry(15583, "_100_ILM_HOTCOAL_06", "100_ilm_hotcoal_06", "loctypes"),
            new GamevalEntry(15584, "_100_ILM_HOTCOAL_07", "100_ilm_hotcoal_07", "loctypes"),
            new GamevalEntry(15585, "LUNAR_DREAM_LOGNPC_MULTI", "lunar_dream_lognpc_multi", "loctypes"),
            new GamevalEntry(15586, "LUNAR_DREAM_LOGPLAY_MULTI", "lunar_dream_logplay_multi", "loctypes"),
            new GamevalEntry(15587, "QUEST_LUNAR_SUPPORT_SYMBOL_MULTI", "B7B8B7", "loctypes"),
            new GamevalEntry(15588, "PLAGUESHEEP_GATEL_OPEN", "plaguesheep_gatel_open", "loctypes"),
            new GamevalEntry(15589, "PLAGUESHEEP_GATER_OPEN", "plaguesheep_gater_open", "loctypes"),
            new GamevalEntry(15590, "MCANNON_RAILING1_MULTILOC", "mcannon_railing1_multiloc", "loctypes"),
            new GamevalEntry(15591, "MCANNON_RAILING2_MULTILOC", "mcannon_railing2_multiloc", "loctypes"),
            new GamevalEntry(15592, "MCANNON_RAILING3_MULTILOC", "mcannon_railing3_multiloc", "loctypes"),
            new GamevalEntry(15593, "MCANNON_RAILING4_MULTILOC", "mcannon_railing4_multiloc", "loctypes"),
            new GamevalEntry(15594, "MCANNON_RAILING5_MULTILOC", "mcannon_railing5_multiloc", "loctypes"),
            new GamevalEntry(15595, "MCANNON_RAILING6_MULTILOC", "mcannon_railing6_multiloc", "loctypes"),
            new GamevalEntry(15596, "MCANNONREMAINS_LOCATION", "Dwarf remains", "loctypes"),
            new GamevalEntry(15597, "MCANNON_CANNON_MULTILOC", "mcannon_cannon_multiloc", "loctypes"),
            new GamevalEntry(15598, "MCANNON_CRATES", "Boxes", "loctypes"),
            new GamevalEntry(15599, "MCANNON_CRATES2", "Crate", "loctypes"),
            new GamevalEntry(15600, "MCANNON_CRATES3", "Crates", "loctypes"),
            new GamevalEntry(15601, "MCANNON_DWARF_RAILING_FIXED", "Railing", "loctypes"),
            new GamevalEntry(15602, "MCANNON_DWARF_RAILING_END", "Railing", "loctypes"),
            new GamevalEntry(15603, "MCANNON_DWARF_RAILING_END_MIR", "Railing", "loctypes"),
            new GamevalEntry(15604, "MCANNON_DWARF_RAILING_GATE", "Gate", "loctypes"),
            new GamevalEntry(15605, "MCANNON_DWARF_RAILING_GATE_MIR", "Gate", "loctypes"),
            new GamevalEntry(15606, "MCANNON_DWARF_RAILING_GATE_MIR_INACT", "mcannon_dwarf_railing_gate_mir_inact", "loctypes"),
            new GamevalEntry(15607, "MCANNON_DWARF_RAILING_GATE_INACT", "mcannon_dwarf_railing_gate_inact", "loctypes"),
            new GamevalEntry(15608, "ROOFTOPS_ARDY_WALLCLIMB", "Wooden Beams", "loctypes"),
            new GamevalEntry(15609, "ROOFTOPS_ARDY_JUMP", "Gap", "loctypes"),
            new GamevalEntry(15610, "ROOFTOPS_ARDY_JUMP_2", "Gap", "loctypes"),
            new GamevalEntry(15611, "ROOFTOPS_ARDY_JUMP_3", "Gap", "loctypes"),
            new GamevalEntry(15612, "ROOFTOPS_ARDY_JUMP_4", "Gap", "loctypes"),
            new GamevalEntry(15613, "MM2_LAB_ROOF_13", "mm2_lab_roof_13", "loctypes"),
            new GamevalEntry(15614, "MM2_LAB_ROOF_14", "mm2_lab_roof_14", "loctypes"),
            new GamevalEntry(15615, "GUBLINCH_SNOW_SMALL_1", "Snow", "loctypes"),
            new GamevalEntry(15616, "GUBLINCH_SNOW_SMALL_2", "Snow", "loctypes"),
            new GamevalEntry(15617, "GUBLINCH_SNOW_SMALL_3", "Snow", "loctypes"),
            new GamevalEntry(15618, "GODSORB", "godsorb", "loctypes"),
            new GamevalEntry(15619, "MACRO_THEATREWALL", "macro_theatrewall", "loctypes"),
            new GamevalEntry(15620, "MACRO_THEATRE_CURTAINS_RIGHT", "macro_theatre_curtains_right", "loctypes"),
            new GamevalEntry(15621, "MACRO_THEATRE_CURTAINS_LEFT", "macro_theatre_curtains_left", "loctypes"),
            new GamevalEntry(15622, "MACRO_THEATRE_CURTAINS_SIDE", "macro_theatre_curtains_side", "loctypes"),
            new GamevalEntry(15623, "MACRO_THEATRE_CURTAINS_CORNER_LEFT", "macro_theatre_curtains_corner_left", "loctypes"),
            new GamevalEntry(15624, "MACRO_THEATRE_CURTAINS_CORNER_RIGHT", "macro_theatre_curtains_corner_right", "loctypes"),
            new GamevalEntry(15625, "MACRO_SPOTLIGHT", "Spotlight", "loctypes"),
            new GamevalEntry(15626, "MACRO_EXITSIGN", "macro_exitsign", "loctypes"),
            new GamevalEntry(15627, "MACRO_THEATRE_FLOOR", "macro_theatre_floor", "loctypes"),
            new GamevalEntry(15628, "MACRO_THEATRE_CHAIR", "macro_theatre_chair", "loctypes"),
            new GamevalEntry(15629, "DUGUPSOIL1_MACROMAZE", "dugupsoil1_macromaze", "loctypes"),
            new GamevalEntry(15630, "DUGUPSOIL2_MACROMAZE", "dugupsoil2_macromaze", "loctypes"),
            new GamevalEntry(15631, "DUGUPSOIL3_MACROMAZE", "dugupsoil3_macromaze", "loctypes"),
            new GamevalEntry(15632, "MACRO_SIMPLEWALL_THEATRE", "macro_simplewall_theatre", "loctypes"),
            new GamevalEntry(15633, "MACRO_DARK_FADE", "macro_dark_fade", "loctypes"),
            new GamevalEntry(15634, "BRIDGELUM_DUGUPSOIL_1", "bridgelum_dugupsoil_1", "loctypes"),
            new GamevalEntry(15635, "BRIDGELUM_DUGUPSOIL_2", "bridgelum_dugupsoil_2", "loctypes"),
            new GamevalEntry(15636, "BRIDGELUM_DUGUPSOIL_3", "bridgelum_dugupsoil_3", "loctypes"),
            new GamevalEntry(15637, "BRIDGELUM_DUGUPSOIL_DARK_1", "bridgelum_dugupsoil_dark_1", "loctypes"),
            new GamevalEntry(15638, "MM2_LAB_INCUBATOR_HEALTHY", "Incubation chamber", "loctypes"),
            new GamevalEntry(15639, "BRIDGELUM_DUGUPSOIL_DARK_2", "bridgelum_dugupsoil_dark_2", "loctypes"),
            new GamevalEntry(15640, "BRIDGELUM_DUGUPSOIL_DARK_3", "bridgelum_dugupsoil_dark_3", "loctypes"),
            new GamevalEntry(15641, "BRIDGELUM_SHORT_GRASS_1", "bridgelum_short_grass_1", "loctypes"),
            new GamevalEntry(15642, "BRIDGELUM_SHORT_GRASS_2", "bridgelum_short_grass_2", "loctypes"),
            new GamevalEntry(15643, "BRIDGELUM_SHORT_GRASS_3", "bridgelum_short_grass_3", "loctypes"),
            new GamevalEntry(15644, "BRIDGELUM_SHORT_GRASS_4", "bridgelum_short_grass_4", "loctypes"),
            new GamevalEntry(15645, "STAIRS", "Staircase", "loctypes"),
            new GamevalEntry(15646, "STAIRS_YANILLE_FIX", "Staircase", "loctypes"),
            new GamevalEntry(15647, "STAIRS_HIGHER", "Staircase", "loctypes"),
            new GamevalEntry(15648, "STAIRSTOP", "Climb-down", "loctypes"),
            new GamevalEntry(15649, "STAIRS_SHALLOW_BASE", "Staircase", "loctypes"),
            new GamevalEntry(15650, "STAIRS_SHALLOW_TOP", "Climb-down", "loctypes"),
            new GamevalEntry(15651, "STAIRSTOP_HIGHER", "Climb-down", "loctypes"),
            new GamevalEntry(15652, "STAIRSDOWN", "Climb-down", "loctypes"),
            new GamevalEntry(15653, "WOODENSTAIRS", "Staircase", "loctypes"),
            new GamevalEntry(15654, "WOODENSTAIRSTOP", "Climb-down", "loctypes"),
            new GamevalEntry(15655, "WOODENSTAIRSDOWN", "Climb-down", "loctypes"),
            new GamevalEntry(15656, "YANILLESTAIRSDOWN", "Climb-down", "loctypes"),
            new GamevalEntry(15657, "YANILLESTAIRSUP", "Staircase", "loctypes"),
            new GamevalEntry(15658, "WAR_STRENGTH_DOOR", "Heavy door", "loctypes"),
            new GamevalEntry(15659, "WAR_STRENGTH_DOOR_O", "Heavy door", "loctypes"),
            new GamevalEntry(15660, "WAR_STRENGTH_DOOR_M", "Heavy door", "loctypes"),
            new GamevalEntry(15661, "WAR_STRENGTH_DOOR_OM", "Heavy door", "loctypes"),
            new GamevalEntry(15662, "WAR_STRENGTH_KEGSIDE", "Keg", "loctypes"),
            new GamevalEntry(15663, "WAR_STRENGTH_KEGTWO", "Keg", "loctypes"),
            new GamevalEntry(15664, "WAR_STRENGTH_SHOT18", "Shot", "loctypes"),
            new GamevalEntry(15665, "WAR_STRENGTH_SHOT22", "Shot", "loctypes"),
            new GamevalEntry(15666, "WAR_STRENGTH_NET", "war_strength_net", "loctypes"),
            new GamevalEntry(15667, "WAR_FLOOR_LINE", "war_floor_line", "loctypes"),
            new GamevalEntry(15668, "WAR_STRENGTH_KEG_ACTIVE", "Keg", "loctypes"),
            new GamevalEntry(15669, "WAR_STRENGTH_KEG2", "war_strength_keg2", "loctypes"),
            new GamevalEntry(15670, "WAR_STRENGTH_KEG3", "war_strength_keg3", "loctypes"),
            new GamevalEntry(15671, "WAR_STRENGTH_KEG4", "war_strength_keg4", "loctypes"),
            new GamevalEntry(15672, "WAR_STRENGTH_KEG5", "war_strength_keg5", "loctypes"),
            new GamevalEntry(15673, "WAR_STRENGTH_KEG1", "war_strength_keg1", "loctypes"),
            new GamevalEntry(15674, "AIDE_BARREL", "Barrel", "loctypes"),
            new GamevalEntry(15675, "AIDE_BARREL_FISH", "Barrel", "loctypes"),
            new GamevalEntry(15676, "AIDE_BARREL_TAP", "Barrel", "loctypes"),
            new GamevalEntry(15677, "AIDE_BANKTABLE", "Bank table", "loctypes"),
            new GamevalEntry(15678, "AIDE_SINK", "Sink", "loctypes"),
            new GamevalEntry(15679, "AIDE_STOOL", "Stool", "loctypes"),
            new GamevalEntry(15680, "AIDE_TABLE_SMALL", "Table", "loctypes"),
            new GamevalEntry(15681, "AIDE_ROCKINGCHAIR", "aide_rockingchair", "loctypes"),
            new GamevalEntry(15682, "AIDE_CHAIR", "aide_chair", "loctypes"),
            new GamevalEntry(15683, "AIDE_NORMAL_BED", "Bed", "loctypes"),
            new GamevalEntry(15684, "AIDE_WOODEN_TABLE", "Table", "loctypes"),
            new GamevalEntry(15685, "AIDE_COOKINGSHELVES", "Cooking shelves", "loctypes"),
            new GamevalEntry(15686, "AIDE_COOKINGSHELVES_EMPTY", "Cooking shelves", "loctypes"),
            new GamevalEntry(15687, "AIDE_POORRUG_CORNER", "aide_poorrug_corner", "loctypes"),
            new GamevalEntry(15688, "AIDE_POORRUG_SIDE", "aide_poorrug_side", "loctypes"),
            new GamevalEntry(15689, "AIDE_TORCH", "aide_torch", "loctypes"),
            new GamevalEntry(15690, "AIDE_PAINTING_KING", "Portrait", "loctypes"),
            new GamevalEntry(15691, "AIDE_PAINTING_ELF", "Painting", "loctypes"),
            new GamevalEntry(15692, "AIDE_CRATES_STACKED", "Crates", "loctypes"),
            new GamevalEntry(15693, "AIDE_SMALL_CRATES", "Crates", "loctypes"),
            new GamevalEntry(15694, "AIDE_LANTERN", "aide_lantern", "loctypes"),
            new GamevalEntry(15695, "DTTD_MACHINE_PARTS_CRATE_SMALL_FULL", "Crate", "loctypes"),
            new GamevalEntry(15696, "DTTD_MACHINE_PARTS_CRATE_SMALL_EMPTY", "Crate", "loctypes"),
            new GamevalEntry(15697, "DTTD_MACHINE_PARTS_CRATE_BIG_FULL", "Crate", "loctypes"),
            new GamevalEntry(15698, "DTTD_MACHINE_PARTS_CRATE_BIG_EMPTY", "Crate", "loctypes"),
            new GamevalEntry(15699, "DTTD_BOX_KART", "Box cart", "loctypes"),
            new GamevalEntry(15700, "DTTD_KART_EMPTY", "Box cart", "loctypes"),
            new GamevalEntry(15701, "DTTD_MACHINE_PARTS_CRATE_SMALL_FULL_MULTI", "dttd_machine_parts_crate_small_full_multi", "loctypes"),
            new GamevalEntry(15702, "DTTD_MACHINE_PARTS_CRATE_BIG_FULL_MULTI", "dttd_machine_parts_crate_big_full_multi", "loctypes"),
            new GamevalEntry(15703, "DTTD_BOX_KART_MULTI", "dttd_box_kart_multi", "loctypes"),
            new GamevalEntry(15704, "DTTD_MACHINE_CRATE_OPEN_WITH_LID", "Crate", "loctypes"),
            new GamevalEntry(15705, "DTTD_MACHINE_CRATE_OPEN_WITH_LID_NOBLOCKWALK", "Crate", "loctypes"),
            new GamevalEntry(15706, "DTTD_MACHINE_CRATE_OPEN_WITHOUT_LID", "Crate", "loctypes"),
            new GamevalEntry(15707, "DTTD_MACHINE_CRATE_CLOSED", "Crate", "loctypes"),
            new GamevalEntry(15708, "DTTD_BONE_DEALER_SALE_ITEMS", "dttd_bone_dealer_sale_items", "loctypes"),
            new GamevalEntry(15709, "DTTD_ZANIK_REVIVAL", "Zanik", "loctypes"),
            new GamevalEntry(15710, "DTTD_ZANIK_CORPSE_JUNA", "dttd_zanik_corpse_juna", "loctypes"),
            new GamevalEntry(15711, "DTTD_ZANIK_DEAD_BODY", "Inspect", "loctypes"),
            new GamevalEntry(15712, "DTTD_ZANIK_CORPSE", "dttd_zanik_corpse", "loctypes"),
            new GamevalEntry(15713, "DTTD_DRILLING_MACHINE", "Drilling machine", "loctypes"),
            new GamevalEntry(15714, "DTTD_ANIM_DRILL_MACHINE_BEING_BROKEN", "Drilling machine", "loctypes"),
            new GamevalEntry(15715, "DTTD_DRILLING_MACHINE_BROKEN", "Broken drilling machine", "loctypes"),
            new GamevalEntry(15716, "DTTD_MACHINE_BROKEN_PARTS_1", "dttd_machine_broken_parts_1", "loctypes"),
            new GamevalEntry(15717, "DTTD_MACHINE_BROKEN_PARTS_2", "dttd_machine_broken_parts_2", "loctypes"),
            new GamevalEntry(15718, "DTTD_MACHINE_BROKEN_PARTS_3", "dttd_machine_broken_parts_3", "loctypes"),
            new GamevalEntry(15719, "DTTD_DOUBLE_TABLE", "Table", "loctypes"),
            new GamevalEntry(15720, "DTTD_CRATE", "Crate", "loctypes"),
            new GamevalEntry(15721, "DTTD_CRATE_CLOSED", "Crate", "loctypes"),
            new GamevalEntry(15722, "DTTD_HAM_CHEST_1", "Small chest", "loctypes"),
            new GamevalEntry(15723, "DTTD_HAM_CHEST_2", "Small chest", "loctypes"),
            new GamevalEntry(15724, "DTTD_HAM_CHEST_3", "Small chest", "loctypes"),
            new GamevalEntry(15725, "DTTD_HAM_CHEST_OPEN", "Small chest", "loctypes"),
            new GamevalEntry(15726, "DTTD_HAM_CHEST_4", "Small chest", "loctypes"),
            new GamevalEntry(15727, "DTTD_SMALL_DRIP", "Drip", "loctypes"),
            new GamevalEntry(15728, "DTTD_SMALL_DRIPS", "Drips", "loctypes"),
            new GamevalEntry(15729, "DTTD_CAVE_WALLS", "dttd_cave_walls", "loctypes"),
            new GamevalEntry(15730, "DTTD_CAVE_WALLS_PITTED", "dttd_cave_walls_pitted", "loctypes"),
            new GamevalEntry(15731, "DTTD_CAVE_WALLS_CRACKED", "Crack", "loctypes"),
            new GamevalEntry(15732, "DTTD_CAVE_WALLS_SPECIAL_T_PIECE", "Wall", "loctypes"),
            new GamevalEntry(15733, "DTTD_CAVE_WALLS_SPECIAL_T_PIECE_MIRROR", "Wall", "loctypes"),
            new GamevalEntry(15734, "DTTD_BASEMENT_WALLS", "dttd_basement_walls", "loctypes"),
            new GamevalEntry(15735, "DTTD_LINKING_WALL", "dttd_linking_wall", "loctypes"),
            new GamevalEntry(15736, "DTTD_LINKING_WALL_MIRROR", "dttd_linking_wall_mirror", "loctypes"),
            new GamevalEntry(15737, "DTTD_WALL_TOP_OUTER", "dttd_wall_top_outer", "loctypes"),
            new GamevalEntry(15738, "DTTD_WALL_TOP5_OUTER", "dttd_wall_top5_outer", "loctypes"),
            new GamevalEntry(15739, "DTTD_WALL_TOP5_OUTER2", "dttd_wall_top5_outer2", "loctypes"),
            new GamevalEntry(15740, "DTTD_WALL_TOP_LINKING", "dttd_wall_top_linking", "loctypes"),
            new GamevalEntry(15741, "DTTD_WALL_TOP_LINKING_MIRROR", "dttd_wall_top_linking_mirror", "loctypes"),
            new GamevalEntry(15742, "DTTD_WALL_HAM_TOP_OUTER", "dttd_wall_ham_top_outer", "loctypes"),
            new GamevalEntry(15743, "DTTD_WALL_HAM_TOP5_OUTER", "dttd_wall_ham_top5_outer", "loctypes"),
            new GamevalEntry(15744, "DTTD_WALL_HAM_TOP5_OUTER2", "dttd_wall_ham_top5_outer2", "loctypes"),
            new GamevalEntry(15745, "DTTD_CAVEWALL_TOP", "dttd_cavewall_top", "loctypes"),
            new GamevalEntry(15746, "DTTD_LADDER_UP_OUT_OF_MILL_BASEMENT", "Ladder", "loctypes"),
            new GamevalEntry(15747, "DTTD_LADDER_UP_OUT_OF_HAM_STOREROOMS", "Ladder", "loctypes"),
            new GamevalEntry(15748, "DTTD_CAVE_ENTRANCE_HAMSIDE_OPEN", "Tunnel", "loctypes"),
            new GamevalEntry(15749, "DTTD_CAVE_ENTRANCE_HAMSIDE_BLOCKED", "Tunnel", "loctypes"),
            new GamevalEntry(15750, "DTTD_CAVE_ENTRANCE_MILLSIDE_OPEN", "Tunnel", "loctypes"),
            new GamevalEntry(15751, "DTTD_CAVE_ENTRANCE_MILLSIDE_BLOCKED", "Tunnel", "loctypes"),
            new GamevalEntry(15752, "DTTD_MILL_TRAPDOOR_CLOSED", "Trapdoor", "loctypes"),
            new GamevalEntry(15753, "DTTD_MILL_TRAPDOOR_OPEN", "Trapdoor", "loctypes"),
            new GamevalEntry(15754, "DTTD_HAM_TRAPDOOR_HIDDEN", "Rubble", "loctypes"),
            new GamevalEntry(15755, "DTTD_HAM_TRAPDOOR_CLOSED", "Hidden trapdoor", "loctypes"),
            new GamevalEntry(15756, "DTTD_HAM_TRAPDOOR_OPEN", "Trapdoor", "loctypes"),
            new GamevalEntry(15757, "DTTD_DOORL_LISTENAT", "Large door", "loctypes"),
            new GamevalEntry(15758, "DTTD_DOORR_LISTENAT", "Large door", "loctypes"),
            new GamevalEntry(15759, "DTTD_HAM_DOOR", "Door", "loctypes"),
            new GamevalEntry(15760, "DTTD_SACK_EMPTY", "Sack", "loctypes"),
            new GamevalEntry(15761, "DTTD_SACK_PILE_LARGE", "Sack Pile", "loctypes"),
            new GamevalEntry(15762, "DTTD_SACK_PILE_KNIFE", "Sacks", "loctypes"),
            new GamevalEntry(15763, "DTTD_TUNNEL_MINESIDE", "dttd_tunnel_mineside", "loctypes"),
            new GamevalEntry(15764, "DTTD_TUNNEL_MILLSIDE", "dttd_tunnel_millside", "loctypes"),
            new GamevalEntry(15765, "DTTD_MILL_TRAPDOOR", "dttd_mill_trapdoor", "loctypes"),
            new GamevalEntry(15766, "DTTD_HAM_TRAPDOOR", "dttd_ham_trapdoor", "loctypes"),
            new GamevalEntry(15767, "LOTR_LIVING_AREA_BED", "Bed", "loctypes"),
            new GamevalEntry(15768, "LOTR_LIVING_AREA_CRATE", "Crate", "loctypes"),
            new GamevalEntry(15769, "LOTR_LIVING_AREA_CRATES_STACKED", "Crate", "loctypes"),
            new GamevalEntry(15770, "LOTR_RUINS_DOOR_BOSS_EXIT", "Passageway", "loctypes"),
            new GamevalEntry(15771, "LOTR_RUINS_DOOR_BOSS_EXIT_2", "Passageway", "loctypes"),
            new GamevalEntry(15772, "LOTR_RUINS_TRAN_DOOR_CLOSED", "Passageway", "loctypes"),
            new GamevalEntry(15773, "LOTR_RUINS_TRAN_DOOR_OPENING", "Passageway", "loctypes"),
            new GamevalEntry(15774, "LOTR_RUINS_TRAN_DOOR_OPEN", "Passageway", "loctypes"),
            new GamevalEntry(15775, "LOTR_MINE_PIPE_WALL_01", "lotr_mine_pipe_wall_01", "loctypes"),
            new GamevalEntry(15776, "LOTR_MINE_PIPE_WALL_02", "lotr_mine_pipe_wall_02", "loctypes"),
            new GamevalEntry(15777, "LOTR_MINE_PIPE_WALL_03", "lotr_mine_pipe_wall_03", "loctypes"),
            new GamevalEntry(15778, "LOTR_MINE_PIPE_WALL_04", "lotr_mine_pipe_wall_04", "loctypes"),
            new GamevalEntry(15779, "LOTR_MINE_PIPE_WALL_05", "lotr_mine_pipe_wall_05", "loctypes"),
            new GamevalEntry(15780, "LOTR_MINE_PIPE_WALL_06", "lotr_mine_pipe_wall_06", "loctypes"),
            new GamevalEntry(15781, "LOTR_MINE_PIPE_WALL_07", "lotr_mine_pipe_wall_07", "loctypes"),
            new GamevalEntry(15782, "LOTR_MINE_PIPE_WALL_08", "lotr_mine_pipe_wall_08", "loctypes"),
            new GamevalEntry(15783, "LOTR_MINE_PIPE_WALL_09", "lotr_mine_pipe_wall_09", "loctypes"),
            new GamevalEntry(15784, "LOTR_MINE_WALL_BLEND_01", "lotr_mine_wall_blend_01", "loctypes"),
            new GamevalEntry(15785, "LOTR_MINE_WALL_BLEND_02", "lotr_mine_wall_blend_02", "loctypes"),
            new GamevalEntry(15786, "LOTR_MINE_WALL_BLEND_03", "lotr_mine_wall_blend_03", "loctypes"),
            new GamevalEntry(15787, "LOTR_MINE_WALL_BLEND_04", "lotr_mine_wall_blend_04", "loctypes"),
            new GamevalEntry(15788, "LOTR_MINE_WALL_BLEND_05", "lotr_mine_wall_blend_05", "loctypes"),
            new GamevalEntry(15789, "LOTR_MINE_WALL", "lotr_mine_wall", "loctypes"),
            new GamevalEntry(15790, "LOTR_MINE_WALL_ROCKY", "lotr_mine_wall_rocky", "loctypes"),
            new GamevalEntry(15791, "LOTR_MINE_WALL_SUPPORT", "lotr_mine_wall_support", "loctypes"),
            new GamevalEntry(15792, "LOTR_MINE_WALL_SUPPORT_LEFT", "lotr_mine_wall_support_left", "loctypes"),
            new GamevalEntry(15793, "LOTR_MINE_WALL_SUPPORT_RIGHT", "lotr_mine_wall_support_right", "loctypes"),
            new GamevalEntry(15794, "LOTR_MINE_WALL_SUPPORT_MID", "lotr_mine_wall_support_mid", "loctypes"),
            new GamevalEntry(15795, "LOTR_MINE_WALL_FOR_MINING", "lotr_mine_wall_for_mining", "loctypes"),
            new GamevalEntry(15796, "LOTR_MINE_WALL_LAMP", "lotr_mine_wall_lamp", "loctypes"),
            new GamevalEntry(15797, "LOTR_MINE_DUGUPSOIL_01", "lotr_mine_dugupsoil_01", "loctypes"),
            new GamevalEntry(15798, "LOTR_MINE_DUGUPSOIL_02", "lotr_mine_dugupsoil_02", "loctypes"),
            new GamevalEntry(15799, "LOTR_MINE_DUGUPSOIL_03", "lotr_mine_dugupsoil_03", "loctypes"),
            new GamevalEntry(15800, "LOTR_MINE_DUGUPSOIL_04", "lotr_mine_dugupsoil_04", "loctypes"),
            new GamevalEntry(15801, "LOTR_MINE_DUGUPSOIL_05", "lotr_mine_dugupsoil_05", "loctypes"),
            new GamevalEntry(15802, "LOTR_MINE_DUGUPSOIL_06", "lotr_mine_dugupsoil_06", "loctypes"),
            new GamevalEntry(15803, "LOTR_MINE_DUGUPSOIL_07", "lotr_mine_dugupsoil_07", "loctypes"),
            new GamevalEntry(15804, "LOTR_MINE_WALL_TOP", "lotr_mine_wall_top", "loctypes"),
            new GamevalEntry(15805, "LOTR_MINE_WALL_TOP5", "lotr_mine_wall_top5", "loctypes"),
            new GamevalEntry(15806, "LOTR_MINE_ROCKS_BIG_01", "lotr_mine_rocks_big_01", "loctypes"),
            new GamevalEntry(15807, "LOTR_MINE_ROCKS_BIG_02", "lotr_mine_rocks_big_02", "loctypes"),
            new GamevalEntry(15808, "LOTR_MINE_ROCKS_BIG_03", "lotr_mine_rocks_big_03", "loctypes"),
            new GamevalEntry(15809, "LOTR_MINE_ROCKS_SMALL_01", "lotr_mine_rocks_small_01", "loctypes"),
            new GamevalEntry(15810, "EXCHANGE_FLOOR_VAR02_1X1", "exchange_floor_var02_1x1", "loctypes"),
            new GamevalEntry(15811, "LOTR_MINE_ROCKS_SMALL_02", "lotr_mine_rocks_small_02", "loctypes"),
            new GamevalEntry(15812, "LOTR_MINE_ROCKS_SMALL_03", "lotr_mine_rocks_small_03", "loctypes"),
            new GamevalEntry(15813, "LOTR_MINE_STALAGTITE_01", "lotr_mine_stalagtite_01", "loctypes"),
            new GamevalEntry(15814, "LOTR_MINE_STALAGTITE_02", "lotr_mine_stalagtite_02", "loctypes"),
            new GamevalEntry(15815, "LOTR_MINE_STALAGTITE_FALLOFF", "lotr_mine_stalagtite_falloff", "loctypes"),
            new GamevalEntry(15816, "LOTR_MINE_CRATE_IN_WATER", "Crate", "loctypes"),
            new GamevalEntry(15817, "LOTR_MINE_BARREL_IN_WATER", "Barrel", "loctypes"),
            new GamevalEntry(15818, "LOTR_TRACKSTRAIGHT", "lotr_trackstraight", "loctypes"),
            new GamevalEntry(15819, "LOTR_TRACKSTRAIGHT_BROKEN", "lotr_trackstraight_broken", "loctypes"),
            new GamevalEntry(15820, "LOTR_TRACKSTRAIGHT_BROKEN2", "lotr_trackstraight_broken2", "loctypes"),
            new GamevalEntry(15821, "LOTR_TRACKCURVE_A", "lotr_trackcurve_a", "loctypes"),
            new GamevalEntry(15822, "LOTR_TRACKCURVE_B", "lotr_trackcurve_b", "loctypes"),
            new GamevalEntry(15823, "LOTR_TRACKCURVE_C", "lotr_trackcurve_c", "loctypes"),
            new GamevalEntry(15824, "LOTR_TRACKCURVE_D", "lotr_trackcurve_d", "loctypes"),
            new GamevalEntry(15825, "LOTR_TRACKBUFFER", "Buffers", "loctypes"),
            new GamevalEntry(15826, "LOTR_TRACK_POINTS_A", "lotr_track_points_a", "loctypes"),
            new GamevalEntry(15827, "LOTR_TRACK_POINTS_B", "lotr_track_points_b", "loctypes"),
            new GamevalEntry(15828, "LOTR_TRACK_POINTS_C", "lotr_track_points_c", "loctypes"),
            new GamevalEntry(15829, "LOTR_TRACK_POINTS_D", "lotr_track_points_d", "loctypes"),
            new GamevalEntry(15830, "LOTR_BACK_ENTRANCE1_INSIDE", "Cart tunnel", "loctypes"),
            new GamevalEntry(15831, "LOTR_SECONDARY_ENTRANCE_INSIDE", "Cart tunnel", "loctypes"),
            new GamevalEntry(15832, "LOTR_MINE_SUPPORT_WALL", "Wall support", "loctypes"),
            new GamevalEntry(15833, "LOTR_ENTRANCE_DOOR_UNBLOCKED", "Entrance", "loctypes"),
            new GamevalEntry(15834, "LOTR_ENTRANCE_DOOR_BLOCKED", "Entrance", "loctypes"),
            new GamevalEntry(15835, "LOTR_ENTRANCE_SIDE_01", "lotr_entrance_side_01", "loctypes"),
            new GamevalEntry(15836, "LOTR_ENTRANCE_SIDE_02", "lotr_entrance_side_02", "loctypes"),
            new GamevalEntry(15837, "BREW_PIPES_RED", "Bamboo Pipes", "loctypes"),
            new GamevalEntry(15838, "BREW_PIPES_RED_BURNING_1", "Bamboo Pipes", "loctypes"),
            new GamevalEntry(15839, "BREW_PIPES_RED_BURNING_2", "Bamboo Pipes", "loctypes"),
            new GamevalEntry(15840, "BREW_PIPES_RED_DAMAGED_1", "Bamboo Pipes", "loctypes"),
            new GamevalEntry(15841, "BREW_PIPES_RED_DAMAGED_2", "Bamboo Pipes", "loctypes"),
            new GamevalEntry(15842, "BREW_PIPES_RED_WET_1", "Bamboo Pipes", "loctypes"),
            new GamevalEntry(15843, "BREW_PIPES_RED_WET_2", "Bamboo Pipes", "loctypes"),
            new GamevalEntry(15844, "BREW_PIPES_RED_DESTROYED", "Bamboo Pipes", "loctypes"),
            new GamevalEntry(15845, "BREW_CRATE_RED", "Rum Crate", "loctypes"),
            new GamevalEntry(15846, "BREW_RED_FLOWERS", "Red flowers", "loctypes"),
            new GamevalEntry(15847, "BREW_HOPPER_RED", "Hopper", "loctypes"),
            new GamevalEntry(15848, "BREW_HOPPER_RED_BURNING_1", "Hopper", "loctypes"),
            new GamevalEntry(15849, "BREW_HOPPER_RED_BURNING_2", "Hopper", "loctypes"),
            new GamevalEntry(15850, "BREW_HOPPER_RED_DAMAGED_1", "Hopper", "loctypes"),
            new GamevalEntry(15851, "BREW_HOPPER_RED_DAMAGED_2", "Hopper", "loctypes"),
            new GamevalEntry(15852, "BREW_HOPPER_RED_WET_1", "Hopper", "loctypes"),
            new GamevalEntry(15853, "BREW_HOPPER_RED_WET_2", "Hopper", "loctypes"),
            new GamevalEntry(15854, "BREW_HOPPER_RED_DESTROYED", "Hopper", "loctypes"),
            new GamevalEntry(15855, "BREW_BRIDGE_RED", "Bridge", "loctypes"),
            new GamevalEntry(15856, "BREW_BRIDGE_RED_BURNING_1", "Bridge", "loctypes"),
            new GamevalEntry(15857, "BREW_BRIDGE_RED_BURNING_2", "Bridge", "loctypes"),
            new GamevalEntry(15858, "BREW_BRIDGE_RED_DAMAGED_1", "Bridge", "loctypes"),
            new GamevalEntry(15859, "BREW_BRIDGE_RED_DAMAGED_2", "Bridge", "loctypes"),
            new GamevalEntry(15860, "BREW_BRIDGE_RED_WET_1", "Bridge", "loctypes"),
            new GamevalEntry(15861, "BREW_BRIDGE_RED_WET_2", "Bridge", "loctypes"),
            new GamevalEntry(15862, "BREW_BRIDGE_RED_DESTROYED", "Bridge", "loctypes"),
            new GamevalEntry(15863, "BREW_PIPES_BLUE", "Bamboo Pipes", "loctypes"),
            new GamevalEntry(15864, "BREW_PIPES_BLUE_BURNING_1", "Bamboo Pipes", "loctypes"),
            new GamevalEntry(15865, "BREW_PIPES_BLUE_BURNING_2", "Bamboo Pipes", "loctypes"),
            new GamevalEntry(15866, "BREW_PIPES_BLUE_DAMAGED_1", "Bamboo Pipes", "loctypes"),
            new GamevalEntry(15867, "BREW_PIPES_BLUE_DAMAGED_2", "Bamboo Pipes", "loctypes"),
            new GamevalEntry(15868, "BREW_PIPES_BLUE_WET_1", "Bamboo Pipes", "loctypes"),
            new GamevalEntry(15869, "BREW_PIPES_BLUE_WET_2", "Bamboo Pipes", "loctypes"),
            new GamevalEntry(15870, "BREW_PIPES_BLUE_DESTROYED", "Bamboo Pipes", "loctypes"),
            new GamevalEntry(15871, "BREW_CRATE_BLUE", "Rum Crate", "loctypes"),
            new GamevalEntry(15872, "BREW_BLUE_FLOWERS", "Blue flowers", "loctypes"),
            new GamevalEntry(15873, "BREW_HOPPER_BLUE", "Hopper", "loctypes"),
            new GamevalEntry(15874, "BREW_HOPPER_BLUE_BURNING_1", "Hopper", "loctypes"),
            new GamevalEntry(15875, "BREW_HOPPER_BLUE_BURNING_2", "Hopper", "loctypes"),
            new GamevalEntry(15876, "BREW_HOPPER_BLUE_DAMAGED_1", "Hopper", "loctypes"),
            new GamevalEntry(15877, "BREW_HOPPER_BLUE_DAMAGED_2", "Hopper", "loctypes"),
            new GamevalEntry(15878, "BREW_HOPPER_BLUE_WET_1", "Hopper", "loctypes"),
            new GamevalEntry(15879, "BREW_HOPPER_BLUE_WET_2", "Hopper", "loctypes"),
            new GamevalEntry(15880, "BREW_HOPPER_BLUE_DESTROYED", "Hopper", "loctypes"),
            new GamevalEntry(15881, "BREW_BRIDGE_BLUE", "Bridge", "loctypes"),
            new GamevalEntry(15882, "BREW_BRIDGE_BLUE_BURNING_1", "Bridge", "loctypes"),
            new GamevalEntry(15883, "BREW_BRIDGE_BLUE_BURNING_2", "Bridge", "loctypes"),
            new GamevalEntry(15884, "BREW_BRIDGE_BLUE_DAMAGED_1", "Bridge", "loctypes"),
            new GamevalEntry(15885, "BREW_BRIDGE_BLUE_DAMAGED_2", "Bridge", "loctypes"),
            new GamevalEntry(15886, "BREW_BRIDGE_BLUE_WET_1", "Bridge", "loctypes"),
            new GamevalEntry(15887, "BREW_BRIDGE_BLUE_WET_2", "Bridge", "loctypes"),
            new GamevalEntry(15888, "BREW_BRIDGE_BLUE_DESTROYED", "Bridge", "loctypes"),
            new GamevalEntry(15889, "BREW_BAMBOO_UPPER_WALL", "brew_bamboo_upper_wall", "loctypes"),
            new GamevalEntry(15890, "BREW_BAMBOO_LADDER_1", "Bamboo Ladder", "loctypes"),
            new GamevalEntry(15891, "BREW_BAMBOO_LADDER_2", "Bamboo Ladder", "loctypes"),
            new GamevalEntry(15892, "BREW_BAMBOO_LADDER_TOP", "Bamboo Ladder", "loctypes"),
            new GamevalEntry(15893, "BREW_BAMBOO_LADDER_1_REVERSE", "Bamboo Ladder", "loctypes"),
            new GamevalEntry(15894, "BREW_BAMBOO_LADDER_2_REVERSE", "Bamboo Ladder", "loctypes"),
            new GamevalEntry(15895, "BREW_BAMBOO_LADDER_TOP_REVERSE", "Bamboo Ladder", "loctypes"),
            new GamevalEntry(15896, "BREW_COPPER_LADDER_1", "Copper Ladder", "loctypes"),
            new GamevalEntry(15897, "BREW_COPPER_LADDER_2", "Copper Ladder", "loctypes"),
            new GamevalEntry(15898, "BREW_COPPER_LADDER_TOP", "Copper Ladder", "loctypes"),
            new GamevalEntry(15899, "BREW_COPPER_LADDER_1_REVERSE", "Copper Ladder", "loctypes"),
            new GamevalEntry(15900, "BREW_COPPER_LADDER_2_REVERSE", "Copper Ladder", "loctypes"),
            new GamevalEntry(15901, "BREW_COPPER_LADDER_TOP_REVERSE", "Copper Ladder", "loctypes"),
            new GamevalEntry(15902, "BREW_END_POST", "Posts", "loctypes"),
            new GamevalEntry(15903, "BREW_STILL_BOILER", "Boiler", "loctypes"),
            new GamevalEntry(15904, "BREW_STILL_BOILER_LOGS", "Boiler", "loctypes"),
            new GamevalEntry(15905, "BREW_STILL_BOILER_FIRE", "Boiler", "loctypes"),
            new GamevalEntry(15906, "BREW_STILL_BOILER_MIRROR", "Boiler", "loctypes"),
            new GamevalEntry(15907, "BREW_STILL_BOILER_LOGS_MIRROR", "Boiler", "loctypes"),
            new GamevalEntry(15908, "BREW_STILL_BOILER_FIRE_MIRROR", "Boiler", "loctypes"),
            new GamevalEntry(15909, "BREW_STILL_BOILER_CORNER", "Boiler", "loctypes"),
            new GamevalEntry(15910, "BREW_STILL_BOILER_CORNER_LOGS", "Boiler", "loctypes"),
            new GamevalEntry(15911, "BREW_STILL_BOILER_CORNER_FIRE", "Boiler", "loctypes"),
            new GamevalEntry(15912, "BREW_STILL_BOILER_CORNER_MIRROR", "Boiler", "loctypes"),
            new GamevalEntry(15913, "BREW_STILL_BOILER_CORNER_LOGS_MIRROR", "Boiler", "loctypes"),
            new GamevalEntry(15914, "BREW_STILL_BOILER_CORNER_FIRE_MIRROR", "Boiler", "loctypes"),
            new GamevalEntry(15915, "GRILLE", "grille", "loctypes"),
            new GamevalEntry(15916, "BREW_KETTLE_MIDDLE_SECTION_1", "middle section", "loctypes"),
            new GamevalEntry(15917, "BREW_KETTLE_MIDDLE_SECTION_1_MIRROR", "middle section", "loctypes"),
            new GamevalEntry(15918, "BREW_KETTLE_MIDDLE_SECTION_2", "middle section", "loctypes"),
            new GamevalEntry(15919, "BREW_KETTLE_MIDDLE_SECTION_2_MIRROR", "middle section", "loctypes"),
            new GamevalEntry(15920, "BREW_KETTLE_MIDDLE_SECTION_PIPE", "middle section", "loctypes"),
            new GamevalEntry(15921, "BREW_KETTLE_MIDDLE_SECTION_PIPE_MIRROR", "middle section", "loctypes"),
            new GamevalEntry(15922, "BREW_BOTTLE_MACHINE", "Bottle Machine", "loctypes"),
            new GamevalEntry(15923, "GAME_BREW_BOTTLE_MACHINE_SHAKE", "Bottle machine", "loctypes"),
            new GamevalEntry(15924, "BREW_CONVEYER_BELT", "Conveyor Belt", "loctypes"),
            new GamevalEntry(15925, "BREW_CONVEYER_BELT_BOTTLE_ANIM", "Conveyor Belt", "loctypes"),
            new GamevalEntry(15926, "BREW_CONVEYER_BELT_BOTTLE", "Conveyor Belt", "loctypes"),
            new GamevalEntry(15927, "BREW_CONVEYER_BELT_BOTTLE_BREAK", "Conveyor Belt", "loctypes"),
            new GamevalEntry(15928, "BREW_STEAM_PUMP", "Steam Pump", "loctypes"),
            new GamevalEntry(15929, "STEAM_PUMP_ANIM1", "Steam Pump", "loctypes"),
            new GamevalEntry(15930, "BREW_STEAM_PUMP_ACTIVE", "brew_steam_pump_active", "loctypes"),
            new GamevalEntry(15931, "BREW_LOG_STORE", "Log Store", "loctypes"),
        };
    }

    static Optional<GamevalEntry> byId(int id) {
        for (GamevalEntry entry : entries()) {
            if (entry.id() == id) return Optional.of(entry);
        }
        return Optional.empty();
    }

}
