package net.titan.gamevals.internal;

import java.util.Optional;

import net.titan.gamevals.GamevalEntry;
import net.titan.gamevals.QuestEntry;

final class ObjectIDEntries_24 {
    private ObjectIDEntries_24() {}

    static GamevalEntry[] entries() {
        return new GamevalEntry[] {
            new GamevalEntry(12334, "HUNDRED_GOBLIN2_BASE", "General Wartface", "loctypes"),
            new GamevalEntry(12335, "HUNDRED_GOBLIN_CHAIR", "hundred_goblin_chair", "loctypes"),
            new GamevalEntry(12336, "HUNDRED_PIRATE_MULTI", "hundred_pirate_multi", "loctypes"),
            new GamevalEntry(12337, "HUNDRED_PIRATE_BASE", "Pirate Pete", "loctypes"),
            new GamevalEntry(12338, "HUNDRED_GUIDE_MULTI", "hundred_guide_multi", "loctypes"),
            new GamevalEntry(12339, "HUNDRED_GUIDE_BASE", "Lumbridge Guide", "loctypes"),
            new GamevalEntry(12340, "HUNDRED_DAVE_MULTI", "hundred_dave_multi", "loctypes"),
            new GamevalEntry(12341, "HUNDRED_DAVE_BASE", "Evil Dave", "loctypes"),
            new GamevalEntry(12342, "HUNDRED_OGRE_MULTI", "hundred_ogre_multi", "loctypes"),
            new GamevalEntry(12343, "HUNDRED_OGRE_BASE", "Skrach Uglogwee", "loctypes"),
            new GamevalEntry(12344, "HUNDRED_VARZE_MULTI", "hundred_varze_multi", "loctypes"),
            new GamevalEntry(12345, "HUNDRED_VARZE_BASE", "Sir Amik Varze", "loctypes"),
            new GamevalEntry(12346, "HUNDRED_MONKEY_MULTI", "hundred_monkey_multi", "loctypes"),
            new GamevalEntry(12347, "HUNDRED_MONKEY_BASE", "Awowogei", "loctypes"),
            new GamevalEntry(12348, "HUNDRED_LUMBRIDGE_DOOR", "Door", "loctypes"),
            new GamevalEntry(12349, "HUNDRED_LUMBRIDGE_DOUBLEDOORL", "Large door", "loctypes"),
            new GamevalEntry(12350, "HUNDRED_LUMBRIDGE_DOUBLEDOORR", "Large door", "loctypes"),
            new GamevalEntry(12351, "HUNDRED_PORTAL_DOOR1", "Barrier", "loctypes"),
            new GamevalEntry(12352, "HUNDRED_PORTAL_DOOR2", "Barrier", "loctypes"),
            new GamevalEntry(12353, "HUNDRED_PORTAL_DOOR3", "Barrier", "loctypes"),
            new GamevalEntry(12354, "HUNDRED_PORTAL_MULTI", "hundred_portal_multi", "loctypes"),
            new GamevalEntry(12355, "HUNDRED_PORTAL_ACTIVE", "Portal", "loctypes"),
            new GamevalEntry(12356, "HUNDRED_EXIT_PORTAL", "Portal", "loctypes"),
            new GamevalEntry(12357, "_100_BUBBLE", "100_bubble", "loctypes"),
            new GamevalEntry(12358, "_100_BUBBLE1", "100_bubble1", "loctypes"),
            new GamevalEntry(12359, "_100_BUBBLE2", "100_bubble2", "loctypes"),
            new GamevalEntry(12360, "_100_BUBBLE3", "100_bubble3", "loctypes"),
            new GamevalEntry(12361, "_100_BUBBLEB", "100_bubbleb", "loctypes"),
            new GamevalEntry(12362, "_100_BUBBLEB1", "100_bubbleb1", "loctypes"),
            new GamevalEntry(12363, "_100_BUBBLEB2", "100_bubbleb2", "loctypes"),
            new GamevalEntry(12364, "_100_BUBBLEB3", "100_bubbleb3", "loctypes"),
            new GamevalEntry(12365, "_100_RINGS_FROZE", "100_rings_froze", "loctypes"),
            new GamevalEntry(12366, "_100_TILE", "100_tile", "loctypes"),
            new GamevalEntry(12367, "_100_TILE_LOW", "100_tile_low", "loctypes"),
            new GamevalEntry(12368, "_100_TILE_LOW2", "100_tile_low2", "loctypes"),
            new GamevalEntry(12369, "_100_GOBLIN_ROOF1", "100_goblin_roof1", "loctypes"),
            new GamevalEntry(12370, "_100_GOBLIN_ROOF2", "100_goblin_roof2", "loctypes"),
            new GamevalEntry(12371, "_100_GOBLIN_ROOF_MID2", "100_goblin_roof_mid2", "loctypes"),
            new GamevalEntry(12372, "_100_GOBLIN_ROOF", "100_goblin_roof", "loctypes"),
            new GamevalEntry(12373, "_100_GOBLIN_ROOF_END", "100_goblin_roof_end", "loctypes"),
            new GamevalEntry(12374, "_100_GOBLIN_ROOF_TOP", "100_goblin_roof_top", "loctypes"),
            new GamevalEntry(12375, "_100_GOBLIN_ROOF_END_MIRROR", "100_goblin_roof_end_mirror", "loctypes"),
            new GamevalEntry(12376, "_100_GOBLIN_ROOF_END2", "100_goblin_roof_end2", "loctypes"),
            new GamevalEntry(12377, "_100_GOBLIN_ROOF_END2_MIRROR", "100_goblin_roof_end2_mirror", "loctypes"),
            new GamevalEntry(12378, "_100_GOBLIN_ROOF_BEFORE_EX", "100_goblin_roof_before_ex", "loctypes"),
            new GamevalEntry(12379, "_100_GOBLIN_ROOF_AFTER_EX", "100_goblin_roof_after_ex", "loctypes"),
            new GamevalEntry(12380, "_100_GOBLIN_ROOF_BLAST", "100_goblin_roof_blast", "loctypes"),
            new GamevalEntry(12381, "_100_GOBLIN_KITCHEN_WALL", "100_goblin_kitchen_wall", "loctypes"),
            new GamevalEntry(12382, "_100_GOBLIN_KITCHEN_WALL2", "100_goblin_kitchen_wall2", "loctypes"),
            new GamevalEntry(12383, "_100_GOBLIN_KITCHEN_SOOTY_WALL", "100_goblin_kitchen_sooty_wall", "loctypes"),
            new GamevalEntry(12384, "_100_GOBLIN_KITCHEN_SOOTY_WALL2", "100_goblin_kitchen_sooty_wall2", "loctypes"),
            new GamevalEntry(12385, "_100_GOBLIN_KITCHEN_SOOTY_OUTLINE", "100_goblin_kitchen_sooty_outline", "loctypes"),
            new GamevalEntry(12386, "_100_GOBLIN_LARGE_TABLE", "Table", "loctypes"),
            new GamevalEntry(12387, "_100_GOBLIN_LARGE_TABLE_BLASTED", "Table", "loctypes"),
            new GamevalEntry(12388, "_100_GOBLIN_LARGE_TABLE_CHARRED", "Table", "loctypes"),
            new GamevalEntry(12389, "_100_GOBLIN_LADDER_DOWN", "Ladder", "loctypes"),
            new GamevalEntry(12390, "_100_GOBLIN_LADDER_UP", "Ladder", "loctypes"),
            new GamevalEntry(12391, "_100_GOBLIN_LADDER_UP_CHARRED", "Ladder", "loctypes"),
            new GamevalEntry(12392, "_100_GOBLIN_SACK_PILE_KNIFE", "Sacks", "loctypes"),
            new GamevalEntry(12393, "_100_GOBLIN_SACK_PILE_KNIFE_CHARRED", "Sacks", "loctypes"),
            new GamevalEntry(12394, "_100_GOBLIN_SACK_PILE_LARGE", "Sack Pile", "loctypes"),
            new GamevalEntry(12395, "_100_GOBLIN_SACK_PILE_LARGE_CHARRED", "Sack Pile", "loctypes"),
            new GamevalEntry(12396, "_100_GOBLIN_SACK_EMPTY", "Sack", "loctypes"),
            new GamevalEntry(12397, "_100_GOBLIN_FOOD_SPLAT", "100_goblin_food_splat", "loctypes"),
            new GamevalEntry(12398, "_100_GOBLIN_FOOD_SPLAT_GREEN", "100_goblin_food_splat_green", "loctypes"),
            new GamevalEntry(12399, "_100_GOBLIN_SACK_EMPTY_CHARRED", "Sack", "loctypes"),
            new GamevalEntry(12400, "_100_GOBLIN_CAULDREN_STILL", "Cauldron", "loctypes"),
            new GamevalEntry(12401, "_100_GOBLIN_CAULDREN_SHAKE", "Cauldron", "loctypes"),
            new GamevalEntry(12402, "_100_GOBLIN_CAULDREN_BLAST", "Explosion", "loctypes"),
            new GamevalEntry(12403, "_100_GOBLIN_SHORT_SHELVES", "Shelves", "loctypes"),
            new GamevalEntry(12404, "_100_GOBLIN_SHORT_SHELVES_BLASTED", "Shelves", "loctypes"),
            new GamevalEntry(12405, "_100_GOBLIN_TALL_CUPBOARD", "Cupboard", "loctypes"),
            new GamevalEntry(12406, "_100_GOBLIN_TALL_CUPBOARD_BLASTED", "Cupboard", "loctypes"),
            new GamevalEntry(12407, "_100_GOBLIN_STUBBY_STOOL", "Stool", "loctypes"),
            new GamevalEntry(12408, "_100_GOBLIN_STUBBY_STOOL_BLASTED", "Stool", "loctypes"),
            new GamevalEntry(12409, "_100_GOBLIN_STUBBY_STOOL_BLASTED_SIDE", "Stool", "loctypes"),
            new GamevalEntry(12410, "_100_GOBLIN_SAUCEPAN", "Saucepan", "loctypes"),
            new GamevalEntry(12411, "_100_GOBLIN_SAUCEPAN_BLASTED", "Saucepan", "loctypes"),
            new GamevalEntry(12412, "_100_GOBLIN_ROLLING_PIN", "Rolling pin", "loctypes"),
            new GamevalEntry(12413, "_100_GOBLIN_ROLLING_PIN_BLASTED", "Rolling pin", "loctypes"),
            new GamevalEntry(12414, "_100_GOBLIN_BIG_SPORK", "Spork", "loctypes"),
            new GamevalEntry(12415, "_100_GOBLIN_BIG_SPORK_BLASTED", "Spork", "loctypes"),
            new GamevalEntry(12416, "_100_GOBLIN_LARGE_TABLE_MULTI", "0b0c0c", "loctypes"),
            new GamevalEntry(12417, "_100_GOBLIN_ROOF_MULTI", "100_goblin_roof_multi", "loctypes"),
            new GamevalEntry(12418, "GOBLIN_OUTPOST_WALL", "goblin_outpost_wall", "loctypes"),
            new GamevalEntry(12419, "GOBLIN_OUTPOST_FORT_WALL", "goblin_outpost_fort_wall", "loctypes"),
            new GamevalEntry(12420, "GOBLIN_OUTPOST_TALL_WALL", "goblin_outpost_tall_wall", "loctypes"),
            new GamevalEntry(12421, "GOBLIN_OUTPOST_BROKEN_WALL", "goblin_outpost_broken_wall", "loctypes"),
            new GamevalEntry(12422, "GOBLIN_OUTPOST_WALL_SUPPORT", "goblin_outpost_wall_support", "loctypes"),
            new GamevalEntry(12423, "GOBLIN_OUTPOST_WALL_WINDOW", "goblin_outpost_wall_window", "loctypes"),
            new GamevalEntry(12424, "GOBLIN_OUTPOST_TALL_WALL_FORT", "goblin_outpost_tall_wall_fort", "loctypes"),
            new GamevalEntry(12425, "GOBLIN_OUTPOST_GATE_LEFT", "goblin_outpost_gate_left", "loctypes"),
            new GamevalEntry(12426, "GOBLIN_OUTPOST_GATE_RIGHT", "goblin_outpost_gate_right", "loctypes"),
            new GamevalEntry(12427, "GOBLIN_OUTPOST_GATE_RIGHT_CAP", "goblin_outpost_gate_right_cap", "loctypes"),
            new GamevalEntry(12428, "GOBLIN_OUTPOST_GATE_LEFT_CAP", "goblin_outpost_gate_left_cap", "loctypes"),
            new GamevalEntry(12429, "GOBLIN_OUTPOST_PIER_SUPPORT", "goblin_outpost_pier_support", "loctypes"),
            new GamevalEntry(12430, "GOBLIN_OUTPOST_PIER_RAIL", "goblin_outpost_pier_rail", "loctypes"),
            new GamevalEntry(12431, "GOBLIN_OUTPOST_PIER_RAIL_BROKE", "goblin_outpost_pier_rail_broke", "loctypes"),
            new GamevalEntry(12432, "GOBLIN_OUTPOST_PIER_EDGE", "goblin_outpost_pier_edge", "loctypes"),
            new GamevalEntry(12433, "GOBLIN_OUTPOST_PIER_EDGE_FRONT", "goblin_outpost_pier_edge_front", "loctypes"),
            new GamevalEntry(12434, "GOBLIN_OUTPOST_BARREL_WITH_TAP", "Barrel", "loctypes"),
            new GamevalEntry(12435, "GOBLIN_OUTPOST_BARREL", "Barrel", "loctypes"),
            new GamevalEntry(12436, "GOBLIN_OUTPOST_PIER_BROKEN", "goblin_outpost_pier_broken", "loctypes"),
            new GamevalEntry(12437, "GOBLIN_OUTPOST_PIER", "goblin_outpost_pier", "loctypes"),
            new GamevalEntry(12438, "GOBLIN_OUTPOST_SCAFOLD", "goblin_outpost_scafold", "loctypes"),
            new GamevalEntry(12439, "GOBLIN_OUTPOST_SCAFOLD_TALL", "goblin_outpost_scafold_tall", "loctypes"),
            new GamevalEntry(12440, "GOBLIN_OUTPOST_STOOL", "Stool", "loctypes"),
            new GamevalEntry(12441, "GOBLIN_OUTPOST_SCAFOLD_EDGE", "goblin_outpost_scafold_edge", "loctypes"),
            new GamevalEntry(12442, "GOBLIN_OUTPOST_LARGE_CRATE", "Crate", "loctypes"),
            new GamevalEntry(12443, "GOBLIN_OUTPOST_LARGE_CRATES", "Crate", "loctypes"),
            new GamevalEntry(12444, "GOBLIN_OUTPOST_POORDOOR", "Door", "loctypes"),
            new GamevalEntry(12445, "GOBLIN_OUTPOST_OPENPOORDOOR", "Door", "loctypes"),
            new GamevalEntry(12446, "GOBLIN_OUTPOST_POORDOOR_DOUBLE_INNER", "Large door", "loctypes"),
            new GamevalEntry(12447, "GOBLIN_OUTPOST_OPENPOORDOOR_DOUBLE_INNER", "Large door", "loctypes"),
            new GamevalEntry(12448, "GOBLIN_OUTPOST_POORDOOR_DOUBLER_INNER", "Large door", "loctypes"),
            new GamevalEntry(12449, "GOBLIN_OUTPOST_OPENPOORDOOR_DOUBLER_INNER", "Large door", "loctypes"),
            new GamevalEntry(12450, "GOBLIN_OUTPOST_BIG_TABLE", "Table", "loctypes"),
            new GamevalEntry(12451, "GOBLIN_OUTPOST_CHEST_CLOSED", "Chest", "loctypes"),
            new GamevalEntry(12452, "GOBLIN_OUTPOST_CHEST_OPEN", "Chest", "loctypes"),
            new GamevalEntry(12453, "GOBLIN_OUTPOST_SKULL_PILE", "Skulls", "loctypes"),
            new GamevalEntry(12454, "SEABED_CAVEWALL_FACE1", "seabed_cavewall_face1", "loctypes"),
            new GamevalEntry(12455, "SEABED_CAVEWALL_TOP", "seabed_cavewall_top", "loctypes"),
            new GamevalEntry(12456, "SEABED2_CAVEWALL_FACE1", "seabed2_cavewall_face1", "loctypes"),
            new GamevalEntry(12457, "SEABED2_CAVEWALL_TOP", "seabed2_cavewall_top", "loctypes"),
            new GamevalEntry(12458, "SEABED3_CAVEWALL_FACE1", "seabed3_cavewall_face1", "loctypes"),
            new GamevalEntry(12459, "SEABED3_CAVEWALL_TOP", "seabed3_cavewall_top", "loctypes"),
            new GamevalEntry(12460, "SEABED2_CAVEWALL_MUDSKIPPER_CAVEENTRANCEL", "Underwater Cavern Entrance", "loctypes"),
            new GamevalEntry(12461, "SEABED2_CAVEWALL_MUDSKIPPER_CAVEENTRANCER", "Underwater Cavern Entrance", "loctypes"),
            new GamevalEntry(12462, "SEABED2_CAVEWALL_MUDSKIPPER_CAVEEXITL", "Underwater Cavern Entrance", "loctypes"),
            new GamevalEntry(12463, "SEABED2_CAVEWALL_MUDSKIPPER_CAVEEXITR", "Underwater Cavern Entrance", "loctypes"),
            new GamevalEntry(12464, "SEABED3_CAVEWALL_ABOVE_CAVEENTRANCEL", "seabed3_cavewall_above_caveentrancel", "loctypes"),
            new GamevalEntry(12465, "SEABED3_CAVEWALL_ABOVE_CAVEENTRANCER", "seabed3_cavewall_above_caveentrancer", "loctypes"),
            new GamevalEntry(12466, "PEN_WALL", "pen_wall", "loctypes"),
            new GamevalEntry(12467, "PEN_WALL_DOORL", "Pen Door", "loctypes"),
            new GamevalEntry(12468, "PEN_WALL_DOORR", "Pen Door", "loctypes"),
            new GamevalEntry(12469, "PEN_WALL_DOORL_OPEN", "pen_wall_doorl_open", "loctypes"),
            new GamevalEntry(12470, "PEN_WALL_DOORR_OPEN", "pen_wall_doorr_open", "loctypes"),
            new GamevalEntry(12471, "PEN_WALLL", "pen_walll", "loctypes"),
            new GamevalEntry(12472, "PEN_WALLR", "pen_wallr", "loctypes"),
            new GamevalEntry(12473, "PEN_WALL_BROKEN", "pen_wall_broken", "loctypes"),
            new GamevalEntry(12474, "ANCHOR_BOTTOM", "Anchor", "loctypes"),
            new GamevalEntry(12475, "ANCHOR_MIDDLE", "Anchor", "loctypes"),
            new GamevalEntry(12476, "ANCHOR_MIDDLE2", "Anchor", "loctypes"),
            new GamevalEntry(12477, "KELP", "Kelp", "loctypes"),
            new GamevalEntry(12478, "KELP_PICKINGPOINT", "Kelp", "loctypes"),
            new GamevalEntry(12479, "_100_CORAL_PLAIN_SIDE1", "Coral Reef", "loctypes"),
            new GamevalEntry(12480, "_100_CORAL_PLAIN_SIDE2", "Coral", "loctypes"),
            new GamevalEntry(12481, "_100_CORAL_PLAIN_CORNER1", "Coral", "loctypes"),
            new GamevalEntry(12482, "_100_CORAL_PLAIN_CORNER2", "Coral", "loctypes"),
            new GamevalEntry(12483, "_100_CORAL_PLAIN_INVERSE", "Coral", "loctypes"),
            new GamevalEntry(12484, "_100_CORAL_PLAIN_TOP1", "Coral", "loctypes"),
            new GamevalEntry(12485, "_100_CORAL_PLAIN_TOP2", "Coral", "loctypes"),
            new GamevalEntry(12486, "_100_CORAL_PLAIN_TOP3", "Coral", "loctypes"),
            new GamevalEntry(12487, "_100_CORAL_PLAIN_ROCK1", "Coral", "loctypes"),
            new GamevalEntry(12488, "_100_CORAL_PLAIN_ROCK2", "Coral", "loctypes"),
            new GamevalEntry(12489, "_100_CORAL_ELK_SIDE1", "Coral", "loctypes"),
            new GamevalEntry(12490, "_100_CORAL_ELK_SIDE2", "Coral", "loctypes"),
            new GamevalEntry(12491, "_100_CORAL_ELK_CORNER1", "Coral", "loctypes"),
            new GamevalEntry(12492, "_100_CORAL_ELK_CORNER2", "Coral", "loctypes"),
            new GamevalEntry(12493, "_100_CORAL_ELK_INVERSE", "Coral", "loctypes"),
            new GamevalEntry(12494, "_100_CORAL_ELK_TOP1", "Coral", "loctypes"),
            new GamevalEntry(12495, "_100_CORAL_ELK_TOP2", "Coral", "loctypes"),
            new GamevalEntry(12496, "_100_CORAL_ELK_TOP3", "Coral", "loctypes"),
            new GamevalEntry(12497, "_100_CORAL_ELK_ROCK1", "Coral", "loctypes"),
            new GamevalEntry(12498, "_100_CORAL_ELK_ROCK2", "Coral", "loctypes"),
            new GamevalEntry(12499, "_100_CORAL_LACE_SIDE1", "Coral Reef", "loctypes"),
            new GamevalEntry(12500, "_100_CORAL_LACE_SIDE2", "Coral", "loctypes"),
            new GamevalEntry(12501, "_100_CORAL_LACE_CORNER1", "Coral", "loctypes"),
            new GamevalEntry(12502, "_100_CORAL_LACE_CORNER2", "Coral", "loctypes"),
            new GamevalEntry(12503, "_100_CORAL_LACE_INVERSE", "Coral", "loctypes"),
            new GamevalEntry(12504, "_100_CORAL_LACE_TOP1", "Coral", "loctypes"),
            new GamevalEntry(12505, "_100_CORAL_LACE_TOP2", "Coral", "loctypes"),
            new GamevalEntry(12506, "_100_CORAL_LACE_TOP3", "Coral", "loctypes"),
            new GamevalEntry(12507, "_100_CORAL_LACE_ROCK1", "Coral", "loctypes"),
            new GamevalEntry(12508, "_100_CORAL_LACE_ROCK2", "Coral", "loctypes"),
            new GamevalEntry(12509, "_100_CORAL_DISC_SIDE1", "Coral Reef", "loctypes"),
            new GamevalEntry(12510, "_100_CORAL_DISC_SIDE2", "Coral", "loctypes"),
            new GamevalEntry(12511, "_100_CORAL_DISC_CORNER1", "Coral", "loctypes"),
            new GamevalEntry(12512, "_100_CORAL_DISC_CORNER2", "Coral", "loctypes"),
            new GamevalEntry(12513, "_100_CORAL_DISC_INVERSE", "Coral", "loctypes"),
            new GamevalEntry(12514, "_100_CORAL_DISC_TOP1", "Coral", "loctypes"),
            new GamevalEntry(12515, "_100_CORAL_DISC_TOP2", "Coral", "loctypes"),
            new GamevalEntry(12516, "_100_CORAL_DISC_TOP3", "Coral", "loctypes"),
            new GamevalEntry(12517, "_100_CORAL_DISC_ROCK1", "Coral", "loctypes"),
            new GamevalEntry(12518, "_100_CORAL_DISC_ROCK2", "Coral", "loctypes"),
            new GamevalEntry(12519, "_100_CORAL_FLOWER_ROCK", "Coral", "loctypes"),
            new GamevalEntry(12520, "_100_CORAL_TUBE_SIDE1", "Coral Reef", "loctypes"),
            new GamevalEntry(12521, "_100_CORAL_TUBE_SIDE2", "Coral", "loctypes"),
            new GamevalEntry(12522, "_100_CORAL_TUBE_CORNER1", "Coral", "loctypes"),
            new GamevalEntry(12523, "_100_CORAL_TUBE_CORNER2", "Coral", "loctypes"),
            new GamevalEntry(12524, "_100_CORAL_TUBE_INVERSE", "Coral", "loctypes"),
            new GamevalEntry(12525, "_100_CORAL_TUBE_TOP1", "Coral", "loctypes"),
            new GamevalEntry(12526, "_100_CORAL_TUBE_TOP2", "Coral", "loctypes"),
            new GamevalEntry(12527, "_100_CORAL_TUBE_TOP3", "Coral", "loctypes"),
            new GamevalEntry(12528, "_100_CORAL_TUBE_ROCK1", "Coral", "loctypes"),
            new GamevalEntry(12529, "_100_CORAL_TUBE_ROCK2", "Coral", "loctypes"),
            new GamevalEntry(12530, "_100_CORAL_ANCHOR_TOP", "Anchor", "loctypes"),
            new GamevalEntry(12531, "_100_PIRATE_BUBBLES", "Bubbles", "loctypes"),
            new GamevalEntry(12532, "_100GUIDE_SPOTLIGHT", "100guide_spotlight", "loctypes"),
            new GamevalEntry(12533, "_100GUIDE_SPOT_CENTRE", "100guide_spot_centre", "loctypes"),
            new GamevalEntry(12534, "_100GUIDE_SPOT_EDGE", "100guide_spot_edge", "loctypes"),
            new GamevalEntry(12535, "_100GUIDE_SPOT_CORNER", "100guide_spot_corner", "loctypes"),
            new GamevalEntry(12536, "FAI_WIZTOWER_SPIRALSTAIRS", "Staircase", "loctypes"),
            new GamevalEntry(12537, "FAI_WIZTOWER_SPIRALSTAIRS_MIDDLE", "Staircase", "loctypes"),
            new GamevalEntry(12538, "FAI_WIZTOWER_SPIRALSTAIRSTOP", "Staircase", "loctypes"),
            new GamevalEntry(12539, "FAI_WIZTOWER_BOOKCASE", "Bookcase", "loctypes"),
            new GamevalEntry(12540, "FAI_WIZTOWER_BOOKCASE_WALL", "Bookcase", "loctypes"),
            new GamevalEntry(12541, "FAI_WIZTOWER_TABLE", "Table", "loctypes"),
            new GamevalEntry(12542, "FAI_WIZTOWER_LANTERN", "fai_wiztower_lantern", "loctypes"),
            new GamevalEntry(12543, "FAI_WIZTOWER_BIG_WOODEN_TABLE", "Large table", "loctypes"),
            new GamevalEntry(12544, "FAI_WIZTOWER_WOODEN_TABLE_SMALL", "Table", "loctypes"),
            new GamevalEntry(12545, "FAI_WIZTOWER_BOXES", "Boxes", "loctypes"),
            new GamevalEntry(12546, "FAI_WIZTOWER_CRATE", "Crate", "loctypes"),
            new GamevalEntry(12547, "FAI_WIZTOWER_CRATE2", "Crate", "loctypes"),
            new GamevalEntry(12548, "FAI_WIZTOWER_CRATE3", "Crates", "loctypes"),
            new GamevalEntry(12549, "_100_JUBBLY_MULTI_PUSH_TREE", "100_jubbly_multi_push_tree", "loctypes"),
            new GamevalEntry(12550, "_100_JUBBLY_TREE_STAGE1", "Old tree", "loctypes"),
            new GamevalEntry(12551, "_100_JUBBLY_TREE_STAGE2", "Old tree", "loctypes"),
            new GamevalEntry(12552, "_100_JUBBLY_TREE_STAGE3", "Old tree", "loctypes"),
            new GamevalEntry(12553, "_100_JUBBLY_TREE_STAGE4", "Old tree", "loctypes"),
            new GamevalEntry(12554, "_100_JUBBLY_TREE_STAGE5", "Crude boat", "loctypes"),
            new GamevalEntry(12555, "_100_JUBBLY_TREE_STAGE6", "Roots", "loctypes"),
            new GamevalEntry(12556, "_100_JUBBLY_ROCK_AND_STRING_BROWN", "Rock and string", "loctypes"),
            new GamevalEntry(12557, "_100_JUBBLY_ROCK_AND_STRING_WHITE", "Rock and string", "loctypes"),
            new GamevalEntry(12558, "_100_JUBBLY_MULTI_ARROW_TREE", "100_jubbly_multi_arrow_tree", "loctypes"),
            new GamevalEntry(12559, "_100_JUBBLY_ARROW_TREE_STAGE1", "Tree", "loctypes"),
            new GamevalEntry(12560, "_100_JUBBLY_ARROW_TREE_STAGE2", "Tree", "loctypes"),
            new GamevalEntry(12561, "_100_JUBBLY_SPITROAST", "Ogre spit-roast", "loctypes"),
            new GamevalEntry(12562, "_100_JUBBLY_SPITROAST_COOKED", "Ogre spit-roast", "loctypes"),
            new GamevalEntry(12563, "_100_JUBBLY_SPITROAST_RUINED", "Ogre spit-roast", "loctypes"),
            new GamevalEntry(12564, "SWAMP_ROCK1", "Pile of Rock", "loctypes"),
            new GamevalEntry(12565, "SWAMP_ROCK2", "Pile of Rock", "loctypes"),
            new GamevalEntry(12566, "SWAMP_ROCK3", "Pile of Rock", "loctypes"),
            new GamevalEntry(12567, "SWAMP_ROCK_NOORE", "Pile of Rock", "loctypes"),
            new GamevalEntry(12568, "STAGAMITE_SMALL_GREY", "Stalagmite", "loctypes"),
            new GamevalEntry(12569, "BOULDER3_GDECOR", "boulder3_gdecor", "loctypes"),
            new GamevalEntry(12570, "BOULDER4_GDECOR", "boulder4_gdecor", "loctypes"),
            new GamevalEntry(12571, "BOULDER3_GDECOR_SKEW", "boulder3_gdecor_skew", "loctypes"),
            new GamevalEntry(12572, "BOULDER4_GDECOR_SKEW", "boulder4_gdecor_skew", "loctypes"),
            new GamevalEntry(12573, "STAGATITE_DRIPPING", "Stalactite", "loctypes"),
            new GamevalEntry(12574, "STAGATITE_DRIPPINGFLOOR", "stagatite_drippingfloor", "loctypes"),
            new GamevalEntry(12575, "STAGAMITE_LARGE", "Stalagmite", "loctypes"),
            new GamevalEntry(12576, "STAGAMITE_SMALL", "Stalagmite", "loctypes"),
            new GamevalEntry(12577, "STAGATITE_LARGE", "Stalactite", "loctypes"),
            new GamevalEntry(12578, "STALAGMITES", "Stalagmite", "loctypes"),
            new GamevalEntry(12579, "CAVE_BOLDER1", "Boulder", "loctypes"),
            new GamevalEntry(12580, "CAVETEMPLEDOOR_STATUE", "Eerie statue", "loctypes"),
            new GamevalEntry(12581, "CAVETEMPLEDOOR_STATUE_RIGHT", "cavetempledoor_statue_right", "loctypes"),
            new GamevalEntry(12582, "ROCKSLIDE1_UPASS", "Rockslide", "loctypes"),
            new GamevalEntry(12583, "ROCKSLIDE2_UPASS", "Rockslide", "loctypes"),
            new GamevalEntry(12584, "ROCKSLIDE3_UPASS", "Rockslide", "loctypes"),
            new GamevalEntry(12585, "ROCKSLIDE4_UPASS", "Rockslide", "loctypes"),
            new GamevalEntry(12586, "ROCKSLIDE5_UPASS", "rockslide5_upass", "loctypes"),
            new GamevalEntry(12587, "ROCKSLIDE6_UPASS", "rockslide6_upass", "loctypes"),
            new GamevalEntry(12588, "SANDY_ROCK_POOL", "Rock", "loctypes"),
            new GamevalEntry(12589, "SANDY_ROCK_POOL_SMALL", "Rock", "loctypes"),
            new GamevalEntry(12590, "SANDY_ROCK_POOL_BITS", "Rocks", "loctypes"),
            new GamevalEntry(12591, "ROCKSLIDE_MIDGREY1", "Rockslide", "loctypes"),
            new GamevalEntry(12592, "ROCKSLIDE_MIDGREY2", "Rockslide", "loctypes"),
            new GamevalEntry(12593, "ROCKSLIDE_MIDGREY3", "Rockslide", "loctypes"),
            new GamevalEntry(12594, "ROCKSLIDE_MIDGREY4", "Rockslide", "loctypes"),
            new GamevalEntry(12595, "DUGUPSOIL_MIDGREY1", "dugupsoil_midgrey1", "loctypes"),
            new GamevalEntry(12596, "DUGUPSOIL_MIDGREY2", "dugupsoil_midgrey2", "loctypes"),
            new GamevalEntry(12597, "DUGUPSOIL_MIDGREY3", "dugupsoil_midgrey3", "loctypes"),
            new GamevalEntry(12598, "GRAPEVINE_PATCH_CLICKZONE_10", "grapevine_patch_clickzone_10", "loctypes"),
            new GamevalEntry(12599, "GRAPEVINE_PATCH_CLICKZONE_11", "grapevine_patch_clickzone_11", "loctypes"),
            new GamevalEntry(12600, "GRAPEVINE_PATCH_CLICKZONE_12", "grapevine_patch_clickzone_12", "loctypes"),
            new GamevalEntry(12601, "_100_OSMAN_WALLBACK_WINTER", "100_osman_wallback_winter", "loctypes"),
            new GamevalEntry(12602, "_100_OSMAN_GATEHOUSE_WINTER", "100_osman_gatehouse_winter", "loctypes"),
            new GamevalEntry(12603, "_100_OSMAN_GATEHOUSE_WINTER_TOP", "100_osman_gatehouse_winter_top", "loctypes"),
            new GamevalEntry(12604, "SWANSONG_HATCHET", "Bronze axe", "loctypes"),
            new GamevalEntry(12605, "GRAPEVINE_PATCH_01", "grapevine_patch_01", "loctypes"),
            new GamevalEntry(12606, "GRAPEVINE_PATCH_02", "grapevine_patch_02", "loctypes"),
            new GamevalEntry(12607, "GRAPEVINE_PATCH_03", "grapevine_patch_03", "loctypes"),
            new GamevalEntry(12608, "GRAPEVINE_PATCH_04", "grapevine_patch_04", "loctypes"),
            new GamevalEntry(12609, "SWAN_SINK1", "Sink", "loctypes"),
            new GamevalEntry(12610, "SWAN_SINK2", "Washbasin", "loctypes"),
            new GamevalEntry(12611, "SWAN_STOVE", "Range", "loctypes"),
            new GamevalEntry(12612, "SWAN_TABLE", "Table", "loctypes"),
            new GamevalEntry(12613, "_100_OSMAN_PILLAR_WINTER", "100_osman_pillar_winter", "loctypes"),
            new GamevalEntry(12614, "_100_OSMAN_PILLAR_ARCH_WINTER", "100_osman_pillar_arch_winter", "loctypes"),
            new GamevalEntry(12615, "_100_OSMAN_ARCH_WINTER", "100_osman_arch_winter", "loctypes"),
            new GamevalEntry(12616, "_100_OSMAN_GATETOP_WINTER", "100_osman_gatetop_winter", "loctypes"),
            new GamevalEntry(12617, "_100_OSMAN_DOOR_WINTER", "Gate", "loctypes"),
            new GamevalEntry(12618, "_100_OSMAN_DOOR_WINTER_OPEN", "100_osman_door_winter_open", "loctypes"),
            new GamevalEntry(12619, "_100_OSMAN_TRELLIS_WINTER", "100_osman_trellis_winter", "loctypes"),
            new GamevalEntry(12620, "_100_OSMAN_TRELLIS_WINTER_SINGLE", "100_osman_trellis_winter_single", "loctypes"),
            new GamevalEntry(12621, "_100_OSMAN_TRELLIS_WINTER_CORNER", "100_osman_trellis_winter_corner", "loctypes"),
            new GamevalEntry(12622, "_100_OSMAN_TRELLIS_WINTER_END", "100_osman_trellis_winter_end", "loctypes"),
            new GamevalEntry(12623, "_100_OSMAN_TRELLIS_WINTER_T", "100_osman_trellis_winter_t", "loctypes"),
            new GamevalEntry(12624, "_100_OSMAN_TRELLIS_WINTER_X", "100_osman_trellis_winter_x", "loctypes"),
            new GamevalEntry(12625, "_100_OSMAN_BUSH_WINTER", "100_osman_bush_winter", "loctypes"),
            new GamevalEntry(12626, "_100_OSMAN_PLANTER_WINTER", "100_osman_planter_winter", "loctypes"),
            new GamevalEntry(12627, "_100_OSMAN_BASKET_WINTER", "100_osman_basket_winter", "loctypes"),
            new GamevalEntry(12628, "_100_OSMAN_WALLTOP_AUTUMN_L", "100_osman_walltop_autumn_l", "loctypes"),
            new GamevalEntry(12629, "_100_OSMAN_WALLTOP_AUTUMN_R", "100_osman_walltop_autumn_r", "loctypes"),
            new GamevalEntry(12630, "_100_OSMAN_WALL_AUTUMN_L", "100_osman_wall_autumn_l", "loctypes"),
            new GamevalEntry(12631, "_100_OSMAN_WALL_AUTUMN_R", "100_osman_wall_autumn_r", "loctypes"),
            new GamevalEntry(12632, "_100_OSMAN_WALLBACK_AUTUMN", "100_osman_wallback_autumn", "loctypes"),
            new GamevalEntry(12633, "_100_OSMAN_GATEHOUSE_AUTUMN", "100_osman_gatehouse_autumn", "loctypes"),
            new GamevalEntry(12634, "_100_OSMAN_GATEHOUSE_AUTUMN_TOP", "100_osman_gatehouse_autumn_top", "loctypes"),
            new GamevalEntry(12635, "_100_OSMAN_PILLAR_AUTUMN", "100_osman_pillar_autumn", "loctypes"),
            new GamevalEntry(12636, "_100_OSMAN_PILLAR_ARCH_AUTUMN", "100_osman_pillar_arch_autumn", "loctypes"),
            new GamevalEntry(12637, "_100_OSMAN_ARCH_AUTUMN", "100_osman_arch_autumn", "loctypes"),
            new GamevalEntry(12638, "_100_OSMAN_GATETOP_AUTUMN", "100_osman_gatetop_autumn", "loctypes"),
            new GamevalEntry(12639, "_100_OSMAN_DOOR_AUTUMN", "Gate", "loctypes"),
            new GamevalEntry(12640, "_100_OSMAN_DOOR_AUTUMN_OPEN", "100_osman_door_autumn_open", "loctypes"),
            new GamevalEntry(12641, "_100_OSMAN_TRELLIS_AUTUMN", "100_osman_trellis_autumn", "loctypes"),
            new GamevalEntry(12642, "_100_OSMAN_TRELLIS_AUTUMN_SINGLE", "100_osman_trellis_autumn_single", "loctypes"),
            new GamevalEntry(12643, "_100_OSMAN_TRELLIS_AUTUMN_SINGLE_SHORT", "100_osman_trellis_autumn_single_short", "loctypes"),
            new GamevalEntry(12644, "_100_OSMAN_TRELLIS_AUTUMN_CORNER", "100_osman_trellis_autumn_corner", "loctypes"),
            new GamevalEntry(12645, "_100_OSMAN_TRELLIS_AUTUMN_END", "100_osman_trellis_autumn_end", "loctypes"),
            new GamevalEntry(12646, "_100_OSMAN_TRELLIS_AUTUMN_CURVED_END", "100_osman_trellis_autumn_curved_end", "loctypes"),
            new GamevalEntry(12647, "_100_OSMAN_TRELLIS_AUTUMN_T", "100_osman_trellis_autumn_t", "loctypes"),
            new GamevalEntry(12648, "_100_OSMAN_TRELLIS_AUTUMN_X", "100_osman_trellis_autumn_x", "loctypes"),
            new GamevalEntry(12649, "_100_OSMAN_BUSH_AUTUMN", "100_osman_bush_autumn", "loctypes"),
            new GamevalEntry(12650, "_100_OSMAN_PLANTER_AUTUMN", "100_osman_planter_autumn", "loctypes"),
            new GamevalEntry(12651, "_100_OSMAN_BASKET_AUTUMN", "100_osman_basket_autumn", "loctypes"),
            new GamevalEntry(12652, "_100_OSMAN_WALLTOP_SPRING_L", "100_osman_walltop_spring_l", "loctypes"),
            new GamevalEntry(12653, "_100_OSMAN_WALLTOP_SPRING_R", "100_osman_walltop_spring_r", "loctypes"),
            new GamevalEntry(12654, "_100_OSMAN_WALL_SPRING_L", "100_osman_wall_spring_l", "loctypes"),
            new GamevalEntry(12655, "SWAN_FURNACE", "Small furnace", "loctypes"),
            new GamevalEntry(12656, "SWAN_HOLE", "Hole", "loctypes"),
            new GamevalEntry(12657, "SWAN_BUILDING_DOOR", "Door", "loctypes"),
            new GamevalEntry(12658, "SWAN_BUILDING_DOOR_OPEN", "Door", "loctypes"),
            new GamevalEntry(12659, "SWAN_FENCE1", "swan_fence1", "loctypes"),
            new GamevalEntry(12660, "SWAN_FENCE2", "swan_fence2", "loctypes"),
            new GamevalEntry(12661, "SWAN_FENCE3", "swan_fence3", "loctypes"),
            new GamevalEntry(12662, "FAI_WIZTOWER_WALLS", "fai_wiztower_walls", "loctypes"),
            new GamevalEntry(12663, "FAI_WIZTOWER_WALLS_TERMINATOR_LEFT", "fai_wiztower_walls_terminator_left", "loctypes"),
            new GamevalEntry(12664, "FAI_WIZTOWER_WALLS_TERMINATOR_RIGHT", "fai_wiztower_walls_terminator_right", "loctypes"),
            new GamevalEntry(12665, "FAI_WIZTOWER_WALLS_L2_5_TERMINATOR_RHT", "fai_wiztower_walls_l2_5_terminator_rht", "loctypes"),
            new GamevalEntry(12666, "FAI_WIZTOWER_WALLS_L2_5_TERMINATOR_LFT", "fai_wiztower_walls_l2_5_terminator_lft", "loctypes"),
            new GamevalEntry(12667, "FAI_WIZTOWER_WALLS_3_TERMINATOR", "fai_wiztower_walls_3_terminator", "loctypes"),
            new GamevalEntry(12668, "FAI_WIZTOWER_WALLS_L2", "fai_wiztower_walls_l2", "loctypes"),
            new GamevalEntry(12669, "FAI_WIZTOWER_WALLS_WINDOW", "fai_wiztower_walls_window", "loctypes"),
            new GamevalEntry(12670, "FAI_WIZTOWER_WALLS_L2_WINDOW", "fai_wiztower_walls_l2_window", "loctypes"),
            new GamevalEntry(12671, "FAI_WIZTOWER_BATTLEMENTS", "fai_wiztower_battlements", "loctypes"),
            new GamevalEntry(12672, "FAI_WIZTOWER_WALL_BATTLEMENTS", "fai_wiztower_wall_battlements", "loctypes"),
            new GamevalEntry(12673, "FAI_WIZTOWER_WALL_BATTLEMENTS2", "fai_wiztower_wall_battlements2", "loctypes"),
            new GamevalEntry(12674, "FAI_WIZTOWER_UPPER_WALLS", "fai_wiztower_upper_walls", "loctypes"),
            new GamevalEntry(12675, "FAI_WIZTOWER_UPPER_WALLS_TERMINATOR_LEFT", "fai_wiztower_upper_walls_terminator_left", "loctypes"),
            new GamevalEntry(12676, "FAI_WIZTOWER_UPPER_WALLS_TERMINATOR_RIGHT", "fai_wiztower_upper_walls_terminator_right", "loctypes"),
            new GamevalEntry(12677, "FAI_WIZTOWER_UPPER_WALLS_L2_5_TERMINATOR_RHT", "fai_wiztower_upper_walls_l2_5_terminator_rht", "loctypes"),
            new GamevalEntry(12678, "FAI_WIZTOWER_UPPER_WALLS_L2_5_TERMINATOR_LFT", "fai_wiztower_upper_walls_l2_5_terminator_lft", "loctypes"),
            new GamevalEntry(12679, "FAI_WIZTOWER_UPPER_WALLS_3_TERMINATOR", "fai_wiztower_upper_walls_3_terminator", "loctypes"),
            new GamevalEntry(12680, "FAI_WIZTOWER_UPPER_WALLS_WINDOW", "fai_wiztower_upper_walls_window", "loctypes"),
            new GamevalEntry(12681, "FAI_WIZTOWER_UPPER_WALLS_L2_WINDOW", "fai_wiztower_upper_walls_l2_window", "loctypes"),
            new GamevalEntry(12682, "FAI_WIZTOWER_BRIDGESUPPORT", "fai_wiztower_bridgesupport", "loctypes"),
            new GamevalEntry(12683, "FAI_WIZTOWER_BRIDGE_LINK_UNDER_POLE", "Bridge", "loctypes"),
            new GamevalEntry(12684, "FAI_WIZTOWER_BRIDGE_LINK_UNDER_POLE_MIRROR", "Bridge", "loctypes"),
            new GamevalEntry(12685, "FAI_WIZTOWER_BRIDGE_LINK_INNER", "fai_wiztower_bridge_link_inner", "loctypes"),
            new GamevalEntry(12686, "FAI_WIZTOWER_BRIDGE_LINK_INNER_MIRROR", "fai_wiztower_bridge_link_inner_mirror", "loctypes"),
            new GamevalEntry(12687, "FAI_WIZTOWER_BRIDGE_BASIC_FLOOR", "fai_wiztower_bridge_basic_floor", "loctypes"),
            new GamevalEntry(12688, "FAI_WIZTOWER_BRIDGE_CUT_CORNER_FLOOR", "fai_wiztower_bridge_cut_corner_floor", "loctypes"),
            new GamevalEntry(12689, "FAI_WIZTOWER_BRIDGE_CUT_CORNER_FLOOR_MIRROR", "fai_wiztower_bridge_cut_corner_floor_mirror", "loctypes"),
            new GamevalEntry(12690, "FAI_WIZTOWER_BRIDGE_FLOOR_WALL_CORNER", "fai_wiztower_bridge_floor_wall_corner", "loctypes"),
            new GamevalEntry(12691, "FAI_WIZTOWER_BRIDGE_FLOOR_WALL_CORNER_MIRROR", "fai_wiztower_bridge_floor_wall_corner_mirror", "loctypes"),
            new GamevalEntry(12692, "FAI_WIZTOWER_BRIDGE_EDGE_FLOOR", "fai_wiztower_bridge_edge_floor", "loctypes"),
            new GamevalEntry(12693, "FAI_WIZTOWER_BRIDGE_CORNER_FLOOR", "fai_wiztower_bridge_corner_floor", "loctypes"),
            new GamevalEntry(12694, "FAI_WIZTOWER_BRIDGE_CORNER_FLOOR_MIRROR", "fai_wiztower_bridge_corner_floor_mirror", "loctypes"),
            new GamevalEntry(12695, "FAI_WIZTOWER_INTERNAL_WALLS", "fai_wiztower_internal_walls", "loctypes"),
            new GamevalEntry(12696, "FAI_WIZTOWER_BRIDGE_WALLS", "fai_wiztower_bridge_walls", "loctypes"),
            new GamevalEntry(12697, "FAI_WIZTOWER_FLOOR_BASIC", "fai_wiztower_floor_basic", "loctypes"),
            new GamevalEntry(12698, "FAI_WIZTOWER_FLOOR_DIAGONAL", "fai_wiztower_floor_diagonal", "loctypes"),
            new GamevalEntry(12699, "FAI_WIZTOWER_FLOOR_RECESSED", "fai_wiztower_floor_recessed", "loctypes"),
            new GamevalEntry(12700, "WIZ_TOWER_TEXTURE_WALL_TEST", "wiz_tower_texture_wall_test", "loctypes"),
            new GamevalEntry(12701, "LUNAR_DREAM_POINT_LIGHT1", "lunar_dream_point_light1", "loctypes"),
            new GamevalEntry(12702, "LUNAR_DREAM_POINT_LIGHT2", "lunar_dream_point_light2", "loctypes"),
            new GamevalEntry(12703, "LUNAR_DREAM_POINT_LIGHT3", "lunar_dream_point_light3", "loctypes"),
            new GamevalEntry(12704, "LUNAR_DREAM_POINT_LIGHT2X2", "lunar_dream_point_light2x2", "loctypes"),
            new GamevalEntry(12705, "_100_GOBLINDUGUPSOIL2_SOOT", "100_goblindugupsoil2_soot", "loctypes"),
            new GamevalEntry(12706, "_100_GOBLINDUGUPSOIL3_SOOT", "100_goblindugupsoil3_soot", "loctypes"),
            new GamevalEntry(12707, "_100_GOBLINDUGUPSOIL1_GREY", "100_goblindugupsoil1_grey", "loctypes"),
            new GamevalEntry(12708, "_100_GOBLINDUGUPSOIL3_GREY", "100_goblindugupsoil3_grey", "loctypes"),
            new GamevalEntry(12709, "_100_GOBLINDUGUPSOIL2_UPASS", "100_goblindugupsoil2_upass", "loctypes"),
            new GamevalEntry(12710, "_100_GOBLINDUGUPSOIL3_UPASS", "100_goblindugupsoil3_upass", "loctypes"),
            new GamevalEntry(12711, "_100_OSMAN_WALL_SPRING_R", "100_osman_wall_spring_r", "loctypes"),
            new GamevalEntry(12712, "_100_OSMAN_WALLBACK_SPRING", "100_osman_wallback_spring", "loctypes"),
            new GamevalEntry(12713, "_100_OSMAN_GATEHOUSE_SPRING", "100_osman_gatehouse_spring", "loctypes"),
            new GamevalEntry(12714, "_100_OSMAN_GATEHOUSE_SPRING_TOP", "100_osman_gatehouse_spring_top", "loctypes"),
            new GamevalEntry(12715, "_100_OSMAN_PILLAR_SPRING", "100_osman_pillar_spring", "loctypes"),
            new GamevalEntry(12716, "_100_OSMAN_PILLAR_ARCH_SPRING", "100_osman_pillar_arch_spring", "loctypes"),
            new GamevalEntry(12717, "_100_OSMAN_ARCH_SPRING", "100_osman_arch_spring", "loctypes"),
            new GamevalEntry(12718, "_100_OSMAN_GATETOP_SPRING", "100_osman_gatetop_spring", "loctypes"),
            new GamevalEntry(12719, "_100_OSMAN_DOOR_SPRING", "Gate", "loctypes"),
            new GamevalEntry(12720, "_100_OSMAN_DOOR_SPRING_OPEN", "100_osman_door_spring_open", "loctypes"),
            new GamevalEntry(12721, "_100_OSMAN_TRELLIS_SPRING", "100_osman_trellis_spring", "loctypes"),
            new GamevalEntry(12722, "SWAN_FENCE4", "swan_fence4", "loctypes"),
            new GamevalEntry(12723, "SWAN_DOOR_L", "Colony gate", "loctypes"),
            new GamevalEntry(12724, "SWAN_OPENDOOR_L", "swan_opendoor_l", "loctypes"),
            new GamevalEntry(12725, "SWAN_DOOR_R", "Colony gate", "loctypes"),
            new GamevalEntry(12726, "_100_OSMAN_TRELLIS_SPRING_SINGLE", "100_osman_trellis_spring_single", "loctypes"),
            new GamevalEntry(12727, "_100_OSMAN_TRELLIS_SPRING_CORNER", "100_osman_trellis_spring_corner", "loctypes"),
            new GamevalEntry(12728, "_100_OSMAN_TRELLIS_SPRING_END", "100_osman_trellis_spring_end", "loctypes"),
            new GamevalEntry(12729, "_100_OSMAN_TRELLIS_SPRING_T", "100_osman_trellis_spring_t", "loctypes"),
            new GamevalEntry(12730, "_100_OSMAN_TRELLIS_SPRING_X", "100_osman_trellis_spring_x", "loctypes"),
            new GamevalEntry(12731, "_100_OSMAN_BUSH_SPRING", "100_osman_bush_spring", "loctypes"),
            new GamevalEntry(12732, "_100_OSMAN_PLANTER_SPRING", "100_osman_planter_spring", "loctypes"),
            new GamevalEntry(12733, "_100_OSMAN_BASKET_SPRING", "100_osman_basket_spring", "loctypes"),
            new GamevalEntry(12734, "BURGH_QUEST_FOOD_TABLE", "Table", "loctypes"),
            new GamevalEntry(12735, "BURGH_QUEST_FOOD_CHEST_CLOSED", "Closed chest", "loctypes"),
            new GamevalEntry(12736, "BURGH_QUEST_FOOD_CHEST_OPEN", "Open chest", "loctypes"),
            new GamevalEntry(12737, "BURGH_INN_CLIMB_OVER", "Broken wall", "loctypes"),
            new GamevalEntry(12738, "BURGH_INN_COLAPSED_WALL_MULTILOC", "burgh_inn_colapsed_wall_multiloc", "loctypes"),
            new GamevalEntry(12739, "BURGH_INN_RUBBLE_BLOCKED", "Rubble", "loctypes"),
            new GamevalEntry(12740, "BURGH_INN_RUBBLE_CLEARED", "Rubble", "loctypes"),
            new GamevalEntry(12741, "BURGH_INN_CRUMBLE_WALL", "Fallen Wall", "loctypes"),
            new GamevalEntry(12742, "BURGH_INN_CRUMBLE_WALL_RUBBLE", "Rubble", "loctypes"),
            new GamevalEntry(12743, "BURGH_INN_TRAPDOOR_MULTILOC", "burgh_inn_trapdoor_multiloc", "loctypes"),
            new GamevalEntry(12744, "BURGH_INN_TRAPDOOR_CLOSED", "Trapdoor", "loctypes"),
            new GamevalEntry(12745, "BURGH_INN_TRAPDOOR_OPEN", "Trapdoor", "loctypes"),
            new GamevalEntry(12746, "BURGH_INN_RUBBLE_ROCK", "Rubble", "loctypes"),
            new GamevalEntry(12747, "BURGH_INN_RUBBLE_PILE", "Pile of rubble.", "loctypes"),
            new GamevalEntry(12748, "BURGH_INN_BASEMENT_LADDER", "Ladder", "loctypes"),
            new GamevalEntry(12749, "BURGH_OUTSIDE_RUBBLE_PILE", "Rubble Pile", "loctypes"),
            new GamevalEntry(12750, "BURGH_INN_WALL_PLAQUE", "Plaque", "loctypes"),
            new GamevalEntry(12751, "BURGH_GENERAL_STORE_ROOF_MULTILOC", "burgh_general_store_roof_multiloc", "loctypes"),
            new GamevalEntry(12752, "BURGH_GENERAL_STORE_WALL_MULTILOC", "burgh_general_store_wall_multiloc", "loctypes"),
            new GamevalEntry(12753, "BURGH_GENERAL_STORE_TINDERBOX_CRATE", "burgh_general_store_tinderbox_crate", "loctypes"),
            new GamevalEntry(12754, "BURGH_GENERAL_STORE_AXES_CRATE", "burgh_general_store_axes_crate", "loctypes"),
            new GamevalEntry(12755, "BURGH_GENERAL_STORE_SNAILS_CRATE", "burgh_general_store_snails_crate", "loctypes"),
            new GamevalEntry(12756, "BURGH_GENERAL_STORE_TINDERBOX_SHELVES", "burgh_general_store_tinderbox_shelves", "loctypes"),
            new GamevalEntry(12757, "BURGH_GENERAL_STORE_AXES_SHELVES", "burgh_general_store_axes_shelves", "loctypes"),
            new GamevalEntry(12758, "BURGH_GENERAL_STORE_TINDERBOX_SNAILS", "burgh_general_store_tinderbox_snails", "loctypes"),
            new GamevalEntry(12759, "BURGH_BANK_BOOTH_MULTILOC", "burgh_bank_booth_multiloc", "loctypes"),
            new GamevalEntry(12760, "BURGH_BANK_WALL_MULTILOC", "burgh_bank_wall_multiloc", "loctypes"),
            new GamevalEntry(12761, "BURGH_VILLAGE_DOOR", "Door", "loctypes"),
            new GamevalEntry(12762, "BURGH_TEMPLE_TRAPDOOR_MULTILOC", "burgh_temple_trapdoor_multiloc", "loctypes"),
            new GamevalEntry(12763, "BURGH_TEMPLE_LIBRARY_TRAPDOOR_OPEN", "Trapdoor", "loctypes"),
            new GamevalEntry(12764, "BURGH_TEMPLE_LIBRARY_LADDER_UP", "Ladder", "loctypes"),
            new GamevalEntry(12765, "BURGH_LIBRARY_KEYHOLE", "Keyhole", "loctypes"),
            new GamevalEntry(12766, "BURGH_LIBRARY_BOOKCASE_HISTORY", "Bookcase", "loctypes"),
            new GamevalEntry(12767, "BURGH_LIBRARY_BOOKCASE_IVANDIS", "Bookcase", "loctypes"),
            new GamevalEntry(12768, "BURGH_CHEST_CLOSED", "Closed chest", "loctypes"),
            new GamevalEntry(12769, "BURGH_CHEST_OPEN", "Open chest", "loctypes"),
            new GamevalEntry(12770, "BURGH_IVANDIS_TOMB_ENTRANCE", "Cave entrance", "loctypes"),
            new GamevalEntry(12771, "BURGH_IVANDIS_TOMB_EXIT", "Cave entrance", "loctypes"),
            new GamevalEntry(12772, "BURGH_IVANDIS_TOMBDOOR_BOARD_MULTILOC", "burgh_ivandis_tombdoor_board_multiloc", "loctypes"),
            new GamevalEntry(12773, "BURGH_IVANDIS_BOARDEDUPDOOR", "Wooden boards", "loctypes"),
            new GamevalEntry(12774, "MYQ2_FISHTESTROCK", "Rock", "loctypes"),
            new GamevalEntry(12775, "BURGH_BED_MAN", "Talk-to", "loctypes"),
            new GamevalEntry(12776, "BURGH_AGILITY_SHORTCUT_FENCE", "Low fence", "loctypes"),
            new GamevalEntry(12777, "BURGH_TRAPDOOR_CLOSED", "Trapdoor", "loctypes"),
            new GamevalEntry(12778, "BURGH_TRAPDOOR_OPEN", "Trapdoor", "loctypes"),
            new GamevalEntry(12779, "BURGH_INN_BASEMENT_LADDERUP", "Ladder", "loctypes"),
            new GamevalEntry(12780, "BURGH_LADDER_GENERALSTORE_UP", "Ladder", "loctypes"),
            new GamevalEntry(12781, "BURGH_LADDER_GENERALSTORE_DOWN", "Ladder", "loctypes"),
            new GamevalEntry(12782, "BURGH_STORE_ROOF_BROKEN", "Broken Roof", "loctypes"),
            new GamevalEntry(12783, "BURGH_STORE_ROOF_FIXED", "Repaired Roof", "loctypes"),
            new GamevalEntry(12784, "BURGH_ROOF_LEAK_BUCKET_EMPTY", "Bucket", "loctypes"),
            new GamevalEntry(12785, "BURGH_ROOF_LEAK_BUCKET", "Bucket", "loctypes"),
            new GamevalEntry(12786, "BURGH_BOARED_UP_WALL", "Repaired wall", "loctypes"),
            new GamevalEntry(12787, "BURGH_BOARED_UP_WALL_CLICKZONE", "Damaged wall", "loctypes"),
            new GamevalEntry(12788, "BURGH_EMPTY_CRATE", "burgh_empty_crate", "loctypes"),
            new GamevalEntry(12789, "BURGH_CRATE_TINDERBOXES", "burgh_crate_tinderboxes", "loctypes"),
            new GamevalEntry(12790, "BURGH_CRATE_AXES", "burgh_crate_axes", "loctypes"),
            new GamevalEntry(12791, "BURGH_CRATE_SNAILS", "burgh_crate_snails", "loctypes"),
            new GamevalEntry(12792, "BURGH_SHELVES_STOCKED_TINDERBOXES", "burgh_shelves_stocked_tinderboxes", "loctypes"),
            new GamevalEntry(12793, "BURGH_SHELVES_STOCKED_AXES", "burgh_shelves_stocked_axes", "loctypes"),
            new GamevalEntry(12794, "BURGH_SHELVES_STOCKED_SNAILS", "burgh_shelves_stocked_snails", "loctypes"),
            new GamevalEntry(12795, "BURGH_FIRES_MULTILOC", "burgh_fires_multiloc", "loctypes"),
            new GamevalEntry(12796, "BURGH_VILLAGE_FIRE", "Fire", "loctypes"),
            new GamevalEntry(12797, "BURGH_VILLAGE_FIRE_BASE", "burgh_village_fire_base", "loctypes"),
            new GamevalEntry(12798, "BURGH_BANKBOOTH_REPAIRED", "Bank Booth", "loctypes"),
            new GamevalEntry(12799, "BURGH_BANKBOOTH_DAMAGED", "Bank Booth", "loctypes"),
            new GamevalEntry(12800, "BURGH_BANKBOOTH_TOO_DAMAGED", "Bank Booth", "loctypes"),
            new GamevalEntry(12801, "BURGH_BANKBOOTH_TOO_DAMAGED2", "Bank Booth", "loctypes"),
            new GamevalEntry(12802, "BURGH_ANCIENT_COFFIN", "Inspect", "loctypes"),
            new GamevalEntry(12803, "BURGH_BLOOD_BARREL_MULTILOC", "burgh_blood_barrel_multiloc", "loctypes"),
            new GamevalEntry(12804, "BURGH_BLOOD_BARREL", "Barrel", "loctypes"),
            new GamevalEntry(12805, "BURGH_FURNACE_MULTILOC", "burgh_furnace_multiloc", "loctypes"),
            new GamevalEntry(12806, "BURGH_FURNACE_BROKEN", "Broken furnace", "loctypes"),
            new GamevalEntry(12807, "BURGH_FURNACE_REPAIRED", "Repaired furnace", "loctypes"),
            new GamevalEntry(12808, "BURGH_FURNACE_COAL_LOADED", "Repaired furnace", "loctypes"),
            new GamevalEntry(12809, "BURGH_FURNACE_FIRED", "Furnace", "loctypes"),
            new GamevalEntry(12810, "BURGH_FURNACE_SMOKE_MULTILOC", "burgh_furnace_smoke_multiloc", "loctypes"),
            new GamevalEntry(12811, "BURGH_FURNACE_SMOKE", "burgh_furnace_smoke", "loctypes"),
            new GamevalEntry(12812, "BURGH_RUBBLE_A_1", "Rubble", "loctypes"),
            new GamevalEntry(12813, "BURGH_RUBBLE_A_2", "Rubble", "loctypes"),
            new GamevalEntry(12814, "BURGH_RUBBLE_A_3", "Rubble", "loctypes"),
            new GamevalEntry(12815, "BURGH_RUBBLE_A_4", "Rubble", "loctypes"),
            new GamevalEntry(12816, "BURGH_FENCEGATE_L", "Gate", "loctypes"),
            new GamevalEntry(12817, "BURGH_FENCEGATE_R", "Gate", "loctypes"),
            new GamevalEntry(12818, "BURGH_OPENFENCEGATE_L", "Gate", "loctypes"),
            new GamevalEntry(12819, "BURGH_OPENFENCEGATE_R", "burgh_openfencegate_r", "loctypes"),
            new GamevalEntry(12820, "BURGH_SWAMP_EXIT_PATH", "Exit path", "loctypes"),
            new GamevalEntry(12821, "BURGH_ABODE_WALL", "burgh_abode_wall", "loctypes"),
            new GamevalEntry(12822, "BURGH_ABODE_WALL_WINDOW", "burgh_abode_wall_window", "loctypes"),
            new GamevalEntry(12823, "BURGH_ABODE_WALL_CRUMBLY_LEFT", "burgh_abode_wall_crumbly_left", "loctypes"),
            new GamevalEntry(12824, "BURGH_ABODE_WALL_CRUMBLY_RIGHT", "burgh_abode_wall_crumbly_right", "loctypes"),
            new GamevalEntry(12825, "BURGH_ABODE_WALL_CRUMBLY2_LEFT", "burgh_abode_wall_crumbly2_left", "loctypes"),
            new GamevalEntry(12826, "BURGH_ABODE_WALL_CRUMBLY2_RIGHT", "burgh_abode_wall_crumbly2_right", "loctypes"),
            new GamevalEntry(12827, "BURGH_ABODE_WALL_CRUMBLY2_RIGHT_MIRRORED", "burgh_abode_wall_crumbly2_right_mirrored", "loctypes"),
            new GamevalEntry(12828, "BURGH_ABODE_WALL_CRUMBLY_RIGHT_MIRRORED", "burgh_abode_wall_crumbly_right_mirrored", "loctypes"),
            new GamevalEntry(12829, "BURGH_ABODE_WALL_DAMAGED", "burgh_abode_wall_damaged", "loctypes"),
            new GamevalEntry(12830, "BURGH_ABODE_WALL_DAMAGED2", "burgh_abode_wall_damaged2", "loctypes"),
            new GamevalEntry(12831, "BURGH_ABODE_WALL_DAMAGED3", "burgh_abode_wall_damaged3", "loctypes"),
            new GamevalEntry(12832, "BURGH_ABODE_WALL_CRUMBLY_DAMAGED_LEFT", "burgh_abode_wall_crumbly_damaged_left", "loctypes"),
            new GamevalEntry(12833, "BURGH_ABODE_WALL_CRUMBLY_DAMAGED_RIGHT", "burgh_abode_wall_crumbly_damaged_right", "loctypes"),
            new GamevalEntry(12834, "BURGH_STONE", "burgh_stone", "loctypes"),
            new GamevalEntry(12835, "BURGH_STONE_VARI", "burgh_stone_vari", "loctypes"),
            new GamevalEntry(12836, "BURGH_STONE_CRUMBLY_RIGHT", "burgh_stone_crumbly_right", "loctypes"),
            new GamevalEntry(12837, "BURGH_STONE_CRUMBLY_LEFT", "burgh_stone_crumbly_left", "loctypes"),
            new GamevalEntry(12838, "BURGH_STONE_CRUMBLY_HALF_RIGHT", "burgh_stone_crumbly_half_right", "loctypes"),
            new GamevalEntry(12839, "BURGH_STONE_CRUMBLY_HALF_LEFT", "burgh_stone_crumbly_half_left", "loctypes"),
            new GamevalEntry(12840, "BURGH_STONE_CRUMBLY_LOW_LEFT", "burgh_stone_crumbly_low_left", "loctypes"),
            new GamevalEntry(12841, "BURGH_STONE_CRUMBLY_LOW_RIGHT", "burgh_stone_crumbly_low_right", "loctypes"),
            new GamevalEntry(12842, "BURGH_STONE_CRUMBLY_LOW2_LEFT", "burgh_stone_crumbly_low2_left", "loctypes"),
            new GamevalEntry(12843, "BURGH_STONE_WINDOW", "burgh_stone_window", "loctypes"),
            new GamevalEntry(12844, "BURGH_STONE_PILE_OF_BICKS", "Pile of bricks", "loctypes"),
            new GamevalEntry(12845, "BURGH_DUNGEON", "burgh_dungeon", "loctypes"),
        };
    }

    static Optional<GamevalEntry> byId(int id) {
        for (GamevalEntry entry : entries()) {
            if (entry.id() == id) return Optional.of(entry);
        }
        return Optional.empty();
    }

}
