package net.titan.gamevals.internal;

import java.util.Optional;

import net.titan.gamevals.GamevalEntry;
import net.titan.gamevals.QuestEntry;

final class ObjectIDEntries_113 {
    private ObjectIDEntries_113() {}

    static GamevalEntry[] entries() {
        return new GamevalEntry[] {
            new GamevalEntry(57923, "GRYPHON_BOSS_WHIRLWIND_INITIAL_4", "Whirlwind", "loctypes"),
            new GamevalEntry(57924, "GRYPHON_BOSS_WHIRLWIND_ACTIVE_4", "Whirlwind", "loctypes"),
            new GamevalEntry(57925, "GRYPHON_BOSS_WHIRLWIND_INITIAL_5", "Whirlwind", "loctypes"),
            new GamevalEntry(57926, "GRYPHON_BOSS_WHIRLWIND_ACTIVE_5", "Whirlwind", "loctypes"),
            new GamevalEntry(57927, "GREAT_CONCH_CLIFF_SHORTCUT_TOWN_TOP", "Rocks", "loctypes"),
            new GamevalEntry(57928, "GREAT_CONCH_CLIFF_SHORTCUT_TOWN_BOTTOM", "Rocks", "loctypes"),
            new GamevalEntry(57929, "GREAT_CONCH_CLIFF_SHORTCUT_SOUTHEAST_TOP", "Rocks", "loctypes"),
            new GamevalEntry(57930, "GREAT_CONCH_CLIFF_SHORTCUT_SOUTHEAST_BOTTOM", "Rocks", "loctypes"),
            new GamevalEntry(57931, "GREAT_CONCH_CLIFF_SHORTCUT_EAST_1_TOP", "Rocks", "loctypes"),
            new GamevalEntry(57932, "GREAT_CONCH_CLIFF_SHORTCUT_EAST_1_BOTTOM", "Rocks", "loctypes"),
            new GamevalEntry(57933, "GREAT_CONCH_CLIFF_SHORTCUT_EAST_2_TOP", "Rocks", "loctypes"),
            new GamevalEntry(57934, "GREAT_CONCH_CLIFF_SHORTCUT_EAST_2_BOTTOM", "Rocks", "loctypes"),
            new GamevalEntry(57935, "GREAT_CONCH_CLIFF_SHORTCUT_MIDDLE", "great_conch_cliff_shortcut_middle", "loctypes"),
            new GamevalEntry(57936, "GREAT_CONCH_STEPPING_STONE", "Stepping stone", "loctypes"),
            new GamevalEntry(57937, "GREAT_CONCH_STEPPING_STONE_NOOP", "Stepping stone", "loctypes"),
            new GamevalEntry(57938, "GREAT_CONCH_SHRINE", "Shrine", "loctypes"),
            new GamevalEntry(57939, "TORTUGAN_STALL_EMPTY", "Market stall", "loctypes"),
            new GamevalEntry(57940, "TORTUGAN_STALL_VEG", "Vegetable stall", "loctypes"),
            new GamevalEntry(57941, "TORTUGAN_STALL_FRUIT", "Fruit stall", "loctypes"),
            new GamevalEntry(57942, "TORTUGAN_STALL_SEED", "Farming stall", "loctypes"),
            new GamevalEntry(57943, "TORTUGAN_STALL_FISH", "Fish stall", "loctypes"),
            new GamevalEntry(57944, "TORTUGAN_STALL_SILVER", "Silver stall", "loctypes"),
            new GamevalEntry(57945, "TORTUGAN_STALL_ORE", "Ore stall", "loctypes"),
            new GamevalEntry(57946, "TORTUGAN_STALL_HUNTING", "Hunting stall", "loctypes"),
            new GamevalEntry(57947, "TORTUGAN_STALL_CRAFTING", "Crafting stall", "loctypes"),
            new GamevalEntry(57948, "TORTUGAN_STALL_HERBALIST", "Herbalist stall", "loctypes"),
            new GamevalEntry(57949, "TORTUGAN_STALL_WEAPONS", "Weapon stall", "loctypes"),
            new GamevalEntry(57950, "CONCH_ROWBOAT_NORTH", "Rowboat", "loctypes"),
            new GamevalEntry(57951, "CONCH_ROWBOAT_EAST", "Rowboat", "loctypes"),
            new GamevalEntry(57952, "CONCH_ROWBOAT_SOUTH", "Rowboat", "loctypes"),
            new GamevalEntry(57953, "TORGAN_WORKBENCH", "Workbench", "loctypes"),
            new GamevalEntry(57954, "TORTUGAN_MENAPHITE_URN", "Urn", "loctypes"),
            new GamevalEntry(57955, "TORTUGAN_TELESCOPE", "Telescope", "loctypes"),
            new GamevalEntry(57956, "TORTUGAN_CHEST01_WOOD01_OPEN01", "Open chest", "loctypes"),
            new GamevalEntry(57957, "TORTUGAN_CHEST01_WOOD01_CLOSED01", "Open chest", "loctypes"),
            new GamevalEntry(57958, "TORTUGAN_CHEST01_BANK01_OPEN01", "Bank chest", "loctypes"),
            new GamevalEntry(57959, "TORTUGAN_CHEST01_BANK01_CLOSED01", "Bank chest", "loctypes"),
            new GamevalEntry(57960, "CONCH_GRYPHON_DROPPINGS01", "Gryphon droppings", "loctypes"),
            new GamevalEntry(57961, "CONCH_GRYPHON_DROPPINGS02", "Gryphon droppings", "loctypes"),
            new GamevalEntry(57962, "CONCH_GRYPHON_DROPPINGS03", "Gryphon droppings", "loctypes"),
            new GamevalEntry(57963, "CONCH_GRYPHON_DROPPINGS04", "Gryphon droppings", "loctypes"),
            new GamevalEntry(57964, "CONCH_GRYPHON_FEATHERS01", "Gryphon feathers", "loctypes"),
            new GamevalEntry(57965, "CONCH_GRYPHON_FEATHERS02", "Gryphon feathers", "loctypes"),
            new GamevalEntry(57966, "CONCH_GRYPHON_FEATHERS03", "Gryphon feathers", "loctypes"),
            new GamevalEntry(57967, "CONCH_GRYPHON_FEATHERS04", "Gryphon feathers", "loctypes"),
            new GamevalEntry(57968, "CONCH_GRYPHON_FEATHERS05", "Gryphon feathers", "loctypes"),
            new GamevalEntry(57969, "CONCH_GRYPHON_FEATHERS06", "Gryphon feathers", "loctypes"),
            new GamevalEntry(57970, "CONCH_GRYPHON_FEATHERS07", "Gryphon feathers", "loctypes"),
            new GamevalEntry(57971, "CONCH_GRYPHON_FEATHERS08", "Gryphon feathers", "loctypes"),
            new GamevalEntry(57972, "CONCH_GRYPHON_FEATHERS09", "Gryphon feathers", "loctypes"),
            new GamevalEntry(57973, "CONCH_GRYPHON_FEATHERS10", "Gryphon feathers", "loctypes"),
            new GamevalEntry(57974, "CONCH_GRYPHON_FEATHERS11", "Gryphon feathers", "loctypes"),
            new GamevalEntry(57975, "CONCH_GRYPHON_FEATHERS12", "Gryphon feathers", "loctypes"),
            new GamevalEntry(57976, "CONCH_TORTUGAN_SHELL_CRACKED01", "Cracked shells", "loctypes"),
            new GamevalEntry(57977, "CONCH_TORTUGAN_SHELL_CRACKED02", "Cracked shells", "loctypes"),
            new GamevalEntry(57978, "CONCH_TORTUGAN_SHELL_CRACKED03", "Cracked shells", "loctypes"),
            new GamevalEntry(57979, "CONCH_TORTUGAN_SHELL_CRACKED04", "Cracked shells", "loctypes"),
            new GamevalEntry(57980, "CONCH_TORTUGAN_SHELL_CRACKED05", "Cracked shells", "loctypes"),
            new GamevalEntry(57981, "CONCH_TORTUGAN_SHELL_CRACKED05_2X2", "Cracked shells", "loctypes"),
            new GamevalEntry(57982, "CONCH_TORTUGAN_SHELL_CRACKED06", "Cracked shells", "loctypes"),
            new GamevalEntry(57983, "CONCH_TORTUGAN_SHELL_CRACKED07", "Cracked shells", "loctypes"),
            new GamevalEntry(57984, "CONCH_TORTUGAN_SKELETON_SHELL01", "Skeleton", "loctypes"),
            new GamevalEntry(57985, "CONCH_TORTUGAN_SKELETON_SHELL02", "Skeleton", "loctypes"),
            new GamevalEntry(57986, "CONCH_TORTUGAN_SKELETON_SKULL01", "Skeleton", "loctypes"),
            new GamevalEntry(57987, "CONCH_TORTUGAN_SKELETON_SKULL02", "Skeleton", "loctypes"),
            new GamevalEntry(57988, "CONCH_TORTUGAN_SKELETON_SKULL03", "Skeleton", "loctypes"),
            new GamevalEntry(57989, "CONCH_TORTUGAN_SKELETON_CLAW01", "Skeleton", "loctypes"),
            new GamevalEntry(57990, "CONCH_TORTUGAN_SKELETON_LEG01", "Skeleton", "loctypes"),
            new GamevalEntry(57991, "CONCH_TORTUGAN_SKELETON_COMPLETE01", "Skeleton", "loctypes"),
            new GamevalEntry(57992, "CONCH_GRYPHON_BLOODSPLATTER01", "Bloodsplatter", "loctypes"),
            new GamevalEntry(57993, "CONCH_GRYPHON_BLOODSPLATTER02", "Bloodsplatter", "loctypes"),
            new GamevalEntry(57994, "CONCH_GRYPHON_BLOODSPLATTER03", "Bloodsplatter", "loctypes"),
            new GamevalEntry(57995, "CONCH_GRYPHON_BELLE", "Belle's remains", "loctypes"),
            new GamevalEntry(57996, "CONCH_GROVE_BANK_DEPOSIT_BOX", "Bank Deposit Box", "loctypes"),
            new GamevalEntry(57997, "PISCARILIUS_FLOOR_TILE_01_SHIPWRIGHT", "piscarilius_floor_tile_01_shipwright", "loctypes"),
            new GamevalEntry(57998, "PISCARILIUS_FLOOR_TILE_01_BANK", "piscarilius_floor_tile_01_bank", "loctypes"),
            new GamevalEntry(57999, "PISCARILIUS_FLOOR_TILE_01_PUB", "piscarilius_floor_tile_01_pub", "loctypes"),
            new GamevalEntry(58000, "PISCARILIUS_FLOOR_TILE_01_GENERAL_STORE", "piscarilius_floor_tile_01_general_store", "loctypes"),
            new GamevalEntry(58001, "PISCARILIUS_FLOOR_TILE_01_FUR_TRADER_ICON", "piscarilius_floor_tile_01_fur_trader_icon", "loctypes"),
            new GamevalEntry(58002, "PISCARILIUS_FLOOR_TILE_01_VEGETABLE_STORE_ICON", "piscarilius_floor_tile_01_vegetable_store_icon", "loctypes"),
            new GamevalEntry(58003, "PISCARILIUS_FLOOR_TILE_01_MINING_SHOP_ICON", "piscarilius_floor_tile_01_mining_shop_icon", "loctypes"),
            new GamevalEntry(58004, "PISCARILIUS_FLOOR_TILE_02_LEDGER_TABLE", "piscarilius_floor_tile_02_ledger_table", "loctypes"),
            new GamevalEntry(58005, "PISCARILIUS_FLOOR_TILE_02_PORT_TASK_BOARD", "piscarilius_floor_tile_02_port_task_board", "loctypes"),
            new GamevalEntry(58006, "PISCARILIUS_FLOOR_TILE_02_SPICE_SHOP_ICON", "piscarilius_floor_tile_02_spice_shop_icon", "loctypes"),
            new GamevalEntry(58007, "PISCARILIUS_FLOOR_TILE_02_GEM_SHOP_ICON", "piscarilius_floor_tile_02_gem_shop_icon", "loctypes"),
            new GamevalEntry(58008, "PISCARILIUS_FLOOR_TILE_02_SILK_TRADER_ICON", "piscarilius_floor_tile_02_silk_trader_icon", "loctypes"),
            new GamevalEntry(58009, "PISCARILIUS_FLOOR_TILE_02_ARCHERY_SHOP_ICON", "piscarilius_floor_tile_02_archery_shop_icon", "loctypes"),
            new GamevalEntry(58010, "PISCARILIUS_FLOOR_TILE_02_FISHING_SHOP_ICON", "piscarilius_floor_tile_02_fishing_shop_icon", "loctypes"),
            new GamevalEntry(58011, "PISCARILIUS_FLOOR_TILE_02_THIEVING_ICON", "piscarilius_floor_tile_02_thieving_icon", "loctypes"),
            new GamevalEntry(58012, "PISCARILIUS_FLOOR_TILE_02_REGISTRAR_ICON", "piscarilius_floor_tile_02_registrar_icon", "loctypes"),
            new GamevalEntry(58013, "PISCARILIUS_FLOOR_TILE_04_SILVER_SHOP_ICON", "piscarilius_floor_tile_04_silver_shop_icon", "loctypes"),
            new GamevalEntry(58014, "PISCARILIUS_PIER_SIDE_04_SALVAGING_STATION", "piscarilius_pier_side_04_salvaging_station", "loctypes"),
            new GamevalEntry(58015, "SALVAGING_STATION_ICON_PISCARILIUS", "salvaging_station_icon_piscarilius", "loctypes"),
            new GamevalEntry(58016, "PORT_TASK_BOARD_ICON_PISCARILIUS", "port_task_board_icon_piscarilius", "loctypes"),
            new GamevalEntry(58017, "LEDGER_TABLE_ICON_PISCARILIUS", "ledger_table_icon_piscarilius", "loctypes"),
            new GamevalEntry(58018, "SHIPWRIGHT_ICON_PISCARILIUS", "shipwright_icon_piscarilius", "loctypes"),
            new GamevalEntry(58019, "PISCARILIUS_BED_WOODEN_DOUBLE_LARGE_01", "Bed", "loctypes"),
            new GamevalEntry(58020, "PISCARILIUS_BED_WOODEN_DOUBLE_LARGE_02", "Bed", "loctypes"),
            new GamevalEntry(58021, "PISCARILIUS_BED_WOODEN_DOUBLE_LARGE_03", "Bed", "loctypes"),
            new GamevalEntry(58022, "CAVEKIT_ROCK01_DEFAULT02B", "cavekit_rock01_default02b", "loctypes"),
            new GamevalEntry(58023, "BRUT_PIER_BROKEN", "brut_pier_broken", "loctypes"),
            new GamevalEntry(58024, "PANDEMONIUM_WATER_PUMP", "Water pump", "loctypes"),
            new GamevalEntry(58025, "PANDEMONIUM_COOKING_POT", "Cooking pot", "loctypes"),
            new GamevalEntry(58026, "PANDEMONIUM_FISHING_STALL", "Fish stall", "loctypes"),
            new GamevalEntry(58027, "PANDEMONIUM_LADDER_UP", "Ladder", "loctypes"),
            new GamevalEntry(58028, "PANDEMONIUM_LADDER_UP_INACTIVE", "pandemonium_ladder_up_inactive", "loctypes"),
            new GamevalEntry(58029, "PANDEMONIUM_LADDER_DOWN", "Ladder", "loctypes"),
            new GamevalEntry(58030, "PANDEMONIUM_PIER", "pandemonium_pier", "loctypes"),
            new GamevalEntry(58031, "PANDEMONIUM_PIER_SHIPWRIGHT_ICON", "pandemonium_pier_shipwright_icon", "loctypes"),
            new GamevalEntry(58032, "PANDEMONIUM_PIER_BANK_ICON", "pandemonium_pier_bank_icon", "loctypes"),
            new GamevalEntry(58033, "PANDEMONIUM_PIER_ANVIL_ICON", "pandemonium_pier_anvil_icon", "loctypes"),
            new GamevalEntry(58034, "PANDEMONIUM_PIER_FURNACE_ICON", "pandemonium_pier_furnace_icon", "loctypes"),
            new GamevalEntry(58035, "PANDEMONIUM_PIER_MINING_SHOP_ICON", "pandemonium_pier_mining_shop_icon", "loctypes"),
            new GamevalEntry(58036, "PANDEMONIUM_PIER_PUB_ICON", "pandemonium_pier_pub_icon", "loctypes"),
            new GamevalEntry(58037, "PANDEMONIUM_PIER_RANGE_ICON", "pandemonium_pier_range_icon", "loctypes"),
            new GamevalEntry(58038, "PANDEMONIUM_CHEST_CLOSED", "Closed chest", "loctypes"),
            new GamevalEntry(58039, "PANDEMONIUM_CHEST_OPEN", "Open chest", "loctypes"),
            new GamevalEntry(58040, "PANDEMONIUM_BEER_STORE_ICON", "pandemonium_beer_store_icon", "loctypes"),
            new GamevalEntry(58041, "PANDEMONIUM_FISHING_STORE_ICON", "pandemonium_fishing_store_icon", "loctypes"),
            new GamevalEntry(58042, "PANDEMONIUM_WATER_SOURCE_ICON", "pandemonium_water_source_icon", "loctypes"),
            new GamevalEntry(58043, "PANDEMONIUM_DUNGEONENTRANCE_ICON_CLICKABLE", "pandemonium_dungeonentrance_icon_clickable", "loctypes"),
            new GamevalEntry(58044, "PANDEMONIUM_PORT_TASK_BOARD_ICON", "pandemonium_port_task_board_icon", "loctypes"),
            new GamevalEntry(58045, "PANDEMONIUM_SALVAGING_STATION_ICON", "pandemonium_salvaging_station_icon", "loctypes"),
            new GamevalEntry(58046, "PANDEMONIUM_LEDGER_TABLE_ICON", "pandemonium_ledger_table_icon", "loctypes"),
            new GamevalEntry(58047, "PANDEMONIUM_SHIPWRIGHT_ICON", "pandemonium_shipwright_icon", "loctypes"),
            new GamevalEntry(58048, "PANDEMONIUM_REGISTRAR_ICON", "pandemonium_registrar_icon", "loctypes"),
            new GamevalEntry(58049, "FENCE_WOOD_BASIC01", "fence_wood_basic01", "loctypes"),
            new GamevalEntry(58050, "FENCE_WOOD_BASIC01_MIRROR", "fence_wood_basic01_mirror", "loctypes"),
            new GamevalEntry(58051, "BOATKIT_MAST_FRONTMAST_HOISTED_PANDEMONIUM01", "Hoisted sail", "loctypes"),
            new GamevalEntry(58052, "BOATKIT_MAST_FRONTMAST_HOISTED_PANDEMONIUM02", "Hoisted sail", "loctypes"),
            new GamevalEntry(58053, "PANDEMONIUM_BAR_01A", "pandemonium_bar_01a", "loctypes"),
            new GamevalEntry(58054, "PANDEMONIUM_BAR_01A_SHIPHULL", "pandemonium_bar_01a_shiphull", "loctypes"),
            new GamevalEntry(58055, "PANDEMONIUM_BAR_01A_SHIPHULL_MIRROR", "pandemonium_bar_01a_shiphull_mirror", "loctypes"),
            new GamevalEntry(58056, "PANDEMONIUM_BAR_01A_WINDOW", "pandemonium_bar_01a_window", "loctypes"),
            new GamevalEntry(58057, "PANDEMONIUM_BAR_01B", "pandemonium_bar_01b", "loctypes"),
            new GamevalEntry(58058, "PANDEMONIUM_BAR_01C", "pandemonium_bar_01c", "loctypes"),
            new GamevalEntry(58059, "PANDEMONIUM_BAR_01D", "pandemonium_bar_01d", "loctypes"),
            new GamevalEntry(58060, "PANDEMONIUM_BAR_01E", "pandemonium_bar_01e", "loctypes"),
            new GamevalEntry(58061, "PANDEMONIUM_BAR_WINDOW_LONG", "pandemonium_bar_window_long", "loctypes"),
            new GamevalEntry(58062, "PANDEMONIUM_DOOR", "Door", "loctypes"),
            new GamevalEntry(58063, "PANDEMONIUM_DOOR_OPEN", "Door", "loctypes"),
            new GamevalEntry(58064, "PANDEMONIUM_DOOR_REVERSE", "Door", "loctypes"),
            new GamevalEntry(58065, "PANDEMONIUM_DOOR_REVERSE_OPEN", "Door", "loctypes"),
            new GamevalEntry(58066, "PANDEMONIUM_DOOR_DOUBLE_L_OPEN_NOOP", "Door", "loctypes"),
            new GamevalEntry(58067, "PANDEMONIUM_DOOR_DOUBLE_R_OPEN_NOOP", "Door", "loctypes"),
            new GamevalEntry(58068, "PANDEMONIUM_DOOR_DOUBLE_L_OPEN_NOOP_ALT", "Door", "loctypes"),
            new GamevalEntry(58069, "PANDEMONIUM_DOOR_DOUBLE_R_OPEN_NOOP_ALT", "Door", "loctypes"),
            new GamevalEntry(58070, "PANDEMONIUM_DOOR_OPEN_NOOP", "Door", "loctypes"),
            new GamevalEntry(58071, "PANDEMONIUM_BAR_FLOOR_BROKEN01", "pandemonium_bar_floor_broken01", "loctypes"),
            new GamevalEntry(58072, "PANDEMONIUM_BAR_FLOOR_RUG01", "pandemonium_bar_floor_rug01", "loctypes"),
            new GamevalEntry(58073, "PANDEMONIUM_BAR_STOOL01", "pandemonium_bar_stool01", "loctypes"),
            new GamevalEntry(58074, "PANDEMONIUM_BAR_STOOL02", "pandemonium_bar_stool02", "loctypes"),
            new GamevalEntry(58075, "PANDEMONIUM_BAR_STOOL03", "pandemonium_bar_stool03", "loctypes"),
            new GamevalEntry(58076, "PANDEMONIUM_BAR_STOOL04", "pandemonium_bar_stool04", "loctypes"),
            new GamevalEntry(58077, "PANDEMONIUM_BAR_STOOL05", "pandemonium_bar_stool05", "loctypes"),
            new GamevalEntry(58078, "PANDEMONIUM_DRAWERS01", "Drawers", "loctypes"),
            new GamevalEntry(58079, "PANDEMONIUM_CABINET_SHARK", "pandemonium_cabinet_shark", "loctypes"),
            new GamevalEntry(58080, "PANDEMONIUM_BAR_PUMPS01", "Bar pumps", "loctypes"),
            new GamevalEntry(58081, "PANDEMONIUM_BARSHELF_EMPTY", "Shelves", "loctypes"),
            new GamevalEntry(58082, "PANDEMONIUM_BARSHELF_FULL1", "Shelves", "loctypes"),
            new GamevalEntry(58083, "PANDEMONIUM_BARSHELF_FULL2", "Shelves", "loctypes"),
            new GamevalEntry(58084, "PANDEMONIUM_TABLE_PARROT01", "Table", "loctypes"),
            new GamevalEntry(58085, "PANDEMONIUM_BAR_ROOF", "pandemonium_bar_roof", "loctypes"),
            new GamevalEntry(58086, "PANDEMONIUM_BAR_ROOF_SUPPORT01", "pandemonium_bar_roof_support01", "loctypes"),
            new GamevalEntry(58087, "PANDEMONIUM_BAR_ROOF_SUPPORT02", "pandemonium_bar_roof_support02", "loctypes"),
            new GamevalEntry(58088, "PANDEMONIUM_PIER_SUPPORT_PILLAR", "pandemonium_pier_support_pillar", "loctypes"),
            new GamevalEntry(58089, "PANDEMONIUM_PIER_SUPPORT_STRAIGHT01", "pandemonium_pier_support_straight01", "loctypes"),
            new GamevalEntry(58090, "PANDEMONIUM_PIER_SUPPORT_STRAIGHT02", "pandemonium_pier_support_straight02", "loctypes"),
            new GamevalEntry(58091, "PANDEMONIUM_PIER_SUPPORT_CORNER_OUTSIDE", "pandemonium_pier_support_corner_outside", "loctypes"),
            new GamevalEntry(58092, "PANDEMONIUM_CAVE_ENTRANCE", "Cave entrance", "loctypes"),
            new GamevalEntry(58093, "PANDEMONIUM_CAVE_EXIT", "Opening", "loctypes"),
            new GamevalEntry(58094, "PANDEMONIUM_BANK_CRAB", "Bank Crab", "loctypes"),
            new GamevalEntry(58095, "PORT_ROBERTS_CELL_DOOR", "port_roberts_cell_door", "loctypes"),
            new GamevalEntry(58096, "PORT_ROBERTS_CELL_DOOR_IN", "Cell door", "loctypes"),
            new GamevalEntry(58097, "PORT_ROBERTS_CELL_DOOR_OUT", "Cell door", "loctypes"),
            new GamevalEntry(58098, "PORT_ROBERTS_CELL_DOOR_INACTIVE", "Cell door", "loctypes"),
            new GamevalEntry(58099, "PORT_ROBERTS_MARKET_STALL", "Market stall", "loctypes"),
            new GamevalEntry(58100, "PORT_ROBERTS_MARKET_STALL_VEG", "Steal-from", "loctypes"),
            new GamevalEntry(58101, "PORT_ROBERTS_MARKET_STALL_SILK", "Steal-from", "loctypes"),
            new GamevalEntry(58102, "PORT_ROBERTS_MARKET_STALL_FUR", "Steal-from", "loctypes"),
            new GamevalEntry(58103, "PORT_ROBERTS_MARKET_STALL_FISH", "Steal-from", "loctypes"),
            new GamevalEntry(58104, "PORT_ROBERTS_MARKET_STALL_SILVER", "Silver stall", "loctypes"),
            new GamevalEntry(58105, "PORT_ROBERTS_MARKET_STALL_SPICE", "Spice stall", "loctypes"),
            new GamevalEntry(58106, "PORT_ROBERTS_MARKET_STALL_GEMS", "Steal-from", "loctypes"),
            new GamevalEntry(58107, "PORT_ROBERTS_MARKET_STALL_ORE", "Steal-from", "loctypes"),
            new GamevalEntry(58108, "PORT_ROBERTS_MARKET_STALL_CBALL", "Cannonball stall", "loctypes"),
            new GamevalEntry(58109, "PRIF_AMLODD_WOODEN_DECKING_PORT_TASK_BOARD_ICON", "prif_amlodd_wooden_decking_port_task_board_icon", "loctypes"),
            new GamevalEntry(58110, "ALDARIN_STAIRS_1X2_SINGLE", "aldarin_stairs_1x2_single", "loctypes"),
            new GamevalEntry(58111, "ALDARIN_PIER_RAISED_PORT_TASK_BOARD_ICON", "aldarin_pier_raised_port_task_board_icon", "loctypes"),
            new GamevalEntry(58112, "ALDARIN_PIER_RAISED_SALVAGING_STATION_ICON", "aldarin_pier_raised_salvaging_station_icon", "loctypes"),
            new GamevalEntry(58113, "ALDARIN_PIER_RAISED_LEDGER_TABLE_ICON", "aldarin_pier_raised_ledger_table_icon", "loctypes"),
            new GamevalEntry(58114, "ALDARIN_PIER_RAISED_SHIPWRIGHT_ICON", "aldarin_pier_raised_shipwright_icon", "loctypes"),
            new GamevalEntry(58115, "WALLKIT_WOODEN01_DEFAULT01_UPPER", "wallkit_wooden01_default01_upper", "loctypes"),
            new GamevalEntry(58116, "WALLKIT_WOODEN01_DEFAULT01_DOOR", "Door", "loctypes"),
            new GamevalEntry(58117, "WALLKIT_WOODEN01_DEFAULT01_DOOR_OPEN", "Door", "loctypes"),
            new GamevalEntry(58118, "WALLKIT_WOODEN01_DEFAULT01_DOOR_OPEN_NOOP", "Door", "loctypes"),
            new GamevalEntry(58119, "WALLKIT_WOODEN01_DEFAULT03", "wallkit_wooden01_default03", "loctypes"),
            new GamevalEntry(58120, "WALLKIT_WOODEN01_WINDOW03", "wallkit_wooden01_window03", "loctypes"),
            new GamevalEntry(58121, "FLOORKIT_WOODEN01_DEFAULT01_SALVAGING_STATION", "floorkit_wooden01_default01_salvaging_station", "loctypes"),
            new GamevalEntry(58122, "FLOORKIT_WOODEN01_DEFAULT01_LEDGER_TABLE", "floorkit_wooden01_default01_ledger_table", "loctypes"),
            new GamevalEntry(58123, "FORTIS_RUGMIDDLE_SHIPWRIGHT_ICON", "fortis_rugmiddle_shipwright_icon", "loctypes"),
            new GamevalEntry(58124, "FLOORKIT_WOOD01_STRAIGHT01_PORT_TASK_BOARD_ICON", "floorkit_wood01_straight01_port_task_board_icon", "loctypes"),
            new GamevalEntry(58125, "FLOORKIT_WOOD01_STRAIGHT01_SALVAGING_STATION_ICON", "floorkit_wood01_straight01_salvaging_station_icon", "loctypes"),
            new GamevalEntry(58126, "FLOORKIT_WOOD01_STRAIGHT02_SHIPWRIGHT_ICON", "floorkit_wood01_straight02_shipwright_icon", "loctypes"),
            new GamevalEntry(58127, "FLOORKIT_WOOD01_STRAIGHT03_LEDGER_TABLE_ICON", "floorkit_wood01_straight03_ledger_table_icon", "loctypes"),
            new GamevalEntry(58128, "BANK_CHEST", "Bank chest", "loctypes"),
            new GamevalEntry(58129, "BANK_CHEST_SMALL", "Bank chest", "loctypes"),
            new GamevalEntry(58130, "HH_EASY_SAIL", "hh_easy_sail", "loctypes"),
            new GamevalEntry(58131, "HH_ELITE_SAIL", "hh_elite_sail", "loctypes"),
            new GamevalEntry(58132, "HH_MASTER_SAIL", "hh_master_sail", "loctypes"),
            new GamevalEntry(58133, "FISHING_SHOAL_ICON", "fishing_shoal_icon", "loctypes"),
            new GamevalEntry(58134, "DOCKING_ICON", "docking_icon", "loctypes"),
            new GamevalEntry(58135, "BARRACUDA_TRIAL", "barracuda_trial", "loctypes"),
            new GamevalEntry(58136, "SALVAGE_SPOT_ICON", "salvage_spot_icon", "loctypes"),
            new GamevalEntry(58137, "PORT_TASK_BOARD_ICON", "port_task_board_icon", "loctypes"),
            new GamevalEntry(58138, "SALVAGING_STATION_ICON", "salvaging_station_icon", "loctypes"),
            new GamevalEntry(58139, "LEDGER_TABLE_ICON", "ledger_table_icon", "loctypes"),
            new GamevalEntry(58140, "SHIPWRIGHT_ICON", "shipwright_icon", "loctypes"),
            new GamevalEntry(58141, "REGISTRAR_ICON", "registrar_icon", "loctypes"),
            new GamevalEntry(58142, "TRAWLER_UPDATE_NET_RAISED", "Trawler net", "loctypes"),
            new GamevalEntry(58143, "TRAWLER_UPDATE_HULLWALL01", "trawler_update_hullwall01", "loctypes"),
            new GamevalEntry(58144, "TRAWLER_UPDATE_HULLWALL01_MIRROR", "trawler_update_hullwall01_mirror", "loctypes"),
            new GamevalEntry(58145, "TRAWLER_UPDATE_HULLWALL02", "trawler_update_hullwall02", "loctypes"),
            new GamevalEntry(58146, "PEST_SERIM_PIER_JOIN_CORNER_MIRROR_LEDGER_TABLE_ICON", "pest_serim_pier_join_corner_mirror_ledger_table_icon", "loctypes"),
            new GamevalEntry(58147, "SNP_RUIN_WINDOW1_LIGHTBROWN01", "snp_ruin_window1_lightbrown01", "loctypes"),
            new GamevalEntry(58148, "SNP_RUIN_WINDOW2_LIGHTBROWN01", "snp_ruin_window2_lightbrown01", "loctypes"),
            new GamevalEntry(58149, "SNP_RUIN_SMALL_WALL1_LIGHTBROWN01", "snp_ruin_small_wall1_lightbrown01", "loctypes"),
            new GamevalEntry(58150, "SNP_RUIN_SMALL_WALL2_LIGHTBROWN01", "snp_ruin_small_wall2_lightbrown01", "loctypes"),
            new GamevalEntry(58151, "SNP_RUINS_LARGE_WALL1_LIGHTBROWN01", "snp_ruins_large_wall1_lightbrown01", "loctypes"),
            new GamevalEntry(58152, "SNP_RUINS_LARGE_WALL2_LIGHTBROWN01", "snp_ruins_large_wall2_lightbrown01", "loctypes"),
            new GamevalEntry(58153, "SNP_RUIN_WINDOW1_MIRROR_LIGHTBROWN01", "snp_ruin_window1_mirror_lightbrown01", "loctypes"),
            new GamevalEntry(58154, "SNP_RUIN_WINDOW2_MIRROR_LIGHTBROWN01", "snp_ruin_window2_mirror_lightbrown01", "loctypes"),
            new GamevalEntry(58155, "SNP_RUIN_SMALL_WALL1_MIRROR_LIGHTBROWN01", "snp_ruin_small_wall1_mirror_lightbrown01", "loctypes"),
            new GamevalEntry(58156, "SNP_RUIN_SMALL_WALL2_MIRROR_LIGHTBROWN01", "snp_ruin_small_wall2_mirror_lightbrown01", "loctypes"),
            new GamevalEntry(58157, "SNP_RUINS_LARGE_WALL1_MIRROR_LIGHTBROWN01", "snp_ruins_large_wall1_mirror_lightbrown01", "loctypes"),
            new GamevalEntry(58158, "SNP_RUINS_LARGE_WALL2_MIRROR_LIGHTBROWN01", "snp_ruins_large_wall2_mirror_lightbrown01", "loctypes"),
            new GamevalEntry(58159, "SNP_RUINS_RUBBLE1_LIGHTBROWN01", "snp_ruins_rubble1_lightbrown01", "loctypes"),
            new GamevalEntry(58160, "SNP_RUINS_RUBBLE2_LIGHTBROWN01", "snp_ruins_rubble2_lightbrown01", "loctypes"),
            new GamevalEntry(58161, "QUEST_START_ICON_CURRENTAFFAIRS", "quest_start_icon_currentaffairs", "loctypes"),
            new GamevalEntry(58162, "QUEST_START_ICON_PRYINGTIMES", "quest_start_icon_pryingtimes", "loctypes"),
            new GamevalEntry(58163, "QUEST_START_ICON_TROUBLEDTORTUGANS", "quest_start_icon_troubledtortugans", "loctypes"),
            new GamevalEntry(58164, "QUEST_START_ICON_PANDEMONIUM", "quest_start_icon_pandemonium", "loctypes"),
            new GamevalEntry(58165, "QUEST_START_ICON_REDREEF", "quest_start_icon_redreef", "loctypes"),
            new GamevalEntry(58166, "QUEST_START_ICON_BURIALATSEA", "quest_start_icon_burialatsea", "loctypes"),
            new GamevalEntry(58167, "BAS_LAB_ENTRY", "bas_lab_entry", "loctypes"),
            new GamevalEntry(58168, "BAS_LAB_ENTRY_CLOSED", "Door", "loctypes"),
            new GamevalEntry(58169, "BAS_LAB_ENTRY_OPEN", "Door", "loctypes"),
            new GamevalEntry(58170, "BAS_LAB_EXIT", "Door", "loctypes"),
            new GamevalEntry(58171, "BAS_LAB_EXIT_ESCAPE", "Door", "loctypes"),
            new GamevalEntry(58172, "BAS_PUZZLE_PLINTH", "bas_puzzle_plinth", "loctypes"),
            new GamevalEntry(58173, "BAS_PUZZLE_PLINTH_OP", "Plinth", "loctypes"),
            new GamevalEntry(58174, "BAS_PUZZLE_PLINTH_NOOP", "Plinth", "loctypes"),
            new GamevalEntry(58175, "BAS_PLINTH_SMOKE", "bas_plinth_smoke", "loctypes"),
            new GamevalEntry(58176, "BAS_PLINTH_SMOKE_INACTIVE", "Plinth", "loctypes"),
            new GamevalEntry(58177, "BAS_PLINTH_SMOKE_ACTIVE", "Plinth", "loctypes"),
            new GamevalEntry(58178, "BAS_PLINTH_SMOKE_EMPOWERED", "Plinth", "loctypes"),
            new GamevalEntry(58179, "BAS_PLINTH_SHADOW", "bas_plinth_shadow", "loctypes"),
            new GamevalEntry(58180, "BAS_PLINTH_SHADOW_INACTIVE", "Plinth", "loctypes"),
            new GamevalEntry(58181, "BAS_PLINTH_SHADOW_ACTIVE", "Plinth", "loctypes"),
            new GamevalEntry(58182, "BAS_PLINTH_SHADOW_EMPOWERED", "Plinth", "loctypes"),
            new GamevalEntry(58183, "BAS_PLINTH_BLOOD", "bas_plinth_blood", "loctypes"),
            new GamevalEntry(58184, "BAS_PLINTH_BLOOD_INACTIVE", "Plinth", "loctypes"),
            new GamevalEntry(58185, "BAS_PLINTH_BLOOD_ACTIVE", "Plinth", "loctypes"),
            new GamevalEntry(58186, "BAS_PLINTH_BLOOD_EMPOWERED", "Plinth", "loctypes"),
            new GamevalEntry(58187, "BAS_PLINTH_ICE", "bas_plinth_ice", "loctypes"),
            new GamevalEntry(58188, "BAS_PLINTH_ICE_INACTIVE", "Plinth", "loctypes"),
            new GamevalEntry(58189, "BAS_PLINTH_ICE_ACTIVE", "Plinth", "loctypes"),
            new GamevalEntry(58190, "BAS_PLINTH_ICE_EMPOWERED", "Plinth", "loctypes"),
            new GamevalEntry(58191, "BAS_LAB_RIFT", "Shadowy Rift", "loctypes"),
            new GamevalEntry(58192, "CURRENT_AFFAIRS_DESK", "Desk", "loctypes"),
            new GamevalEntry(58193, "CURRENT_AFFAIRS_CABINET", "Cabinet", "loctypes"),
            new GamevalEntry(58194, "BCS_TOMB_WALL01_DARKTOP", "bcs_tomb_wall01_darktop", "loctypes"),
            new GamevalEntry(58195, "BCS_TOMB_WALL01_DARKER", "bcs_tomb_wall01_darker", "loctypes"),
            new GamevalEntry(58196, "REGICIDE_DENSE_TREES", "Trees", "loctypes"),
            new GamevalEntry(58197, "REGICIDE_DENSE_TREES2", "Trees", "loctypes"),
            new GamevalEntry(58198, "REGICIDE_DENSE_TREES3", "Trees", "loctypes"),
            new GamevalEntry(58199, "FAIRY2_PINE_TREE_SMALL", "Tree", "loctypes"),
            new GamevalEntry(58200, "VIKING_PIER_PORT_TASK_BOARD_ICON", "( )", "loctypes"),
            new GamevalEntry(58201, "VIKING_PIER_SALVAGING_STATION_ICON", "( )", "loctypes"),
            new GamevalEntry(58202, "VIKING_PIER_LEDGER_TABLE_ICON", "( )", "loctypes"),
            new GamevalEntry(58203, "HORROR_LIGHTHOUSE_COG_BROKEN_NOOP", "Lighting mechanism", "loctypes"),
            new GamevalEntry(58204, "PIRATE_LEANING_ANCHOR", "Anchor", "loctypes"),
            new GamevalEntry(58205, "QUEST_LUNAR_PIER1_LOW_LEDGER_TABLE_ICON", "quest_lunar_pier1_low_ledger_table_icon", "loctypes"),
            new GamevalEntry(58206, "QUEST_LUNAR_PIER1_LOW_PORT_TASK_BOARD_ICON", "quest_lunar_pier1_low_port_task_board_icon", "loctypes"),
            new GamevalEntry(58207, "QUEST_LUNAR_PIER1_LOW_SALVAGING_STATION_ICON", "quest_lunar_pier1_low_salvaging_station_icon", "loctypes"),
            new GamevalEntry(58208, "SAILING_INTRO_WRECK", "Wreck", "loctypes"),
            new GamevalEntry(58209, "BRAIN_BOAT_MAST_01_BOTTOM_GALLEON", "brain_boat_mast_01_bottom_galleon", "loctypes"),
            new GamevalEntry(58210, "BRAIN_BOAT_MAST_01_TOP_GALLEON", "brain_boat_mast_01_top_galleon", "loctypes"),
            new GamevalEntry(58211, "ROCKO_MULTI_TAPPING_PIPE", "Pipes", "loctypes"),
            new GamevalEntry(58212, "ROCKO_TAPPING_PIPE", "Pipes", "loctypes"),
            new GamevalEntry(58213, "ROCKO_BROKEN_PIPE", "Pipes", "loctypes"),
            new GamevalEntry(58214, "ROCKO_MULTI_PERCH_ROCK", "Perch rock", "loctypes"),
            new GamevalEntry(58215, "ROCKO_CUTSCENE_DEAD_GUY", "Dead guy", "loctypes"),
            new GamevalEntry(58216, "ROCKO_CUSTOMS_OFFICE_LOCKER", "Locker", "loctypes"),
            new GamevalEntry(58217, "ROCKO_CUSTOMS_OFFICE_POSTER1", "rocko_customs_office_poster1", "loctypes"),
            new GamevalEntry(58218, "ROCKO_PRISON_WALL_STANDARD01", "rocko_prison_wall_standard01", "loctypes"),
            new GamevalEntry(58219, "ROCKO_PRISON_WALL_STANDARD01_EXTERIOR", "rocko_prison_wall_standard01_exterior", "loctypes"),
            new GamevalEntry(58220, "ROCKO_PRISON_WALL_STANDARD02", "rocko_prison_wall_standard02", "loctypes"),
            new GamevalEntry(58221, "ROCKO_PRISON_WALL_STANDARD01_L63", "rocko_prison_wall_standard01_l63", "loctypes"),
            new GamevalEntry(58222, "ROCKO_PRISON_WALL_STANDARD02_L63", "rocko_prison_wall_standard02_l63", "loctypes"),
            new GamevalEntry(58223, "ROCKO_PRISON_WALL_STANDARD01_R63", "rocko_prison_wall_standard01_r63", "loctypes"),
            new GamevalEntry(58224, "ROCKO_PRISON_WALL_STANDARD02_R63", "rocko_prison_wall_standard02_r63", "loctypes"),
            new GamevalEntry(58225, "ROCKO_PRISON_WALL_STANDARD01_L64", "rocko_prison_wall_standard01_l64", "loctypes"),
            new GamevalEntry(58226, "ROCKO_PRISON_WALL_STANDARD02_L64", "rocko_prison_wall_standard02_l64", "loctypes"),
            new GamevalEntry(58227, "ROCKO_PRISON_WALL_STANDARD01_R64", "rocko_prison_wall_standard01_r64", "loctypes"),
            new GamevalEntry(58228, "ROCKO_PRISON_WALL_STANDARD02_R64", "rocko_prison_wall_standard02_r64", "loctypes"),
            new GamevalEntry(58229, "ROCKO_PRISON_WALL_STANDARD01_66", "rocko_prison_wall_standard01_66", "loctypes"),
            new GamevalEntry(58230, "ROCKO_PRISON_WALL_STANDARD02_66", "rocko_prison_wall_standard02_66", "loctypes"),
            new GamevalEntry(58231, "ROCKO_PRISON_WALL_STANDARD01_67", "rocko_prison_wall_standard01_67", "loctypes"),
            new GamevalEntry(58232, "ROCKO_PRISON_WALL_STANDARD02_67", "rocko_prison_wall_standard02_67", "loctypes"),
            new GamevalEntry(58233, "ROCKO_PRISON_WALL_STANDARD01_R69", "rocko_prison_wall_standard01_r69", "loctypes"),
            new GamevalEntry(58234, "ROCKO_PRISON_WALL_STANDARD02_R69", "rocko_prison_wall_standard02_r69", "loctypes"),
            new GamevalEntry(58235, "ROCKO_PRISON_WALL_STANDARD01_R70", "rocko_prison_wall_standard01_r70", "loctypes"),
            new GamevalEntry(58236, "ROCKO_PRISON_WALL_STANDARD02_R70", "rocko_prison_wall_standard02_r70", "loctypes"),
            new GamevalEntry(58237, "ROCKO_PRISON_WALL_END01", "rocko_prison_wall_end01", "loctypes"),
            new GamevalEntry(58238, "ROCKO_PRISON_WALL_END02", "rocko_prison_wall_end02", "loctypes"),
            new GamevalEntry(58239, "ROCKO_PRISON_WALL_END02_EXTERIOR", "rocko_prison_wall_end02_exterior", "loctypes"),
            new GamevalEntry(58240, "ROCKO_PRISON_WALL_END04_MIRROR", "rocko_prison_wall_end04_mirror", "loctypes"),
            new GamevalEntry(58241, "ROCKO_PRISON_WALL_WELD01_EXTERIOR", "rocko_prison_wall_weld01_exterior", "loctypes"),
            new GamevalEntry(58242, "ROCKO_PRISON_WALL_WELD_END01_EXTERIOR", "rocko_prison_wall_weld_end01_exterior", "loctypes"),
            new GamevalEntry(58243, "ROCKO_PRISON_WALL_WELD03", "rocko_prison_wall_weld03", "loctypes"),
            new GamevalEntry(58244, "ROCKO_PRISON_WALL_WELD01_MIRROR", "rocko_prison_wall_weld01_mirror", "loctypes"),
            new GamevalEntry(58245, "ROCKO_PRISON_WALL_WELD01_MIRROR_EXTERIOR", "rocko_prison_wall_weld01_mirror_exterior", "loctypes"),
            new GamevalEntry(58246, "ROCKO_PRISON_WALL_WELD02_MIRROR", "rocko_prison_wall_weld02_mirror", "loctypes"),
            new GamevalEntry(58247, "ROCKO_PRISON_WALL_WELD03_MIRROR", "rocko_prison_wall_weld03_mirror", "loctypes"),
            new GamevalEntry(58248, "ROCKO_PRISON_WALL_WINDOW01", "rocko_prison_wall_window01", "loctypes"),
            new GamevalEntry(58249, "ROCKO_PRISON_WALL_WINDOW01_EXTERIOR", "rocko_prison_wall_window01_exterior", "loctypes"),
            new GamevalEntry(58250, "ROCKO_PRISON_WALL_CUSTOM", "Barred window", "loctypes"),
            new GamevalEntry(58251, "ROCKO_PRISON_WALL_BARS01", "Cell door", "loctypes"),
            new GamevalEntry(58252, "ROCKO_PRISON_WALL_BUSTED01", "rocko_prison_wall_busted01", "loctypes"),
            new GamevalEntry(58253, "ROCKO_PRISON_WALL_BUSTED01_MIRROR", "rocko_prison_wall_busted01_mirror", "loctypes"),
            new GamevalEntry(58254, "ROCKO_PRISON_RANDOM_FILES01", "rocko_prison_random_files01", "loctypes"),
            new GamevalEntry(58255, "ROCKO_PRISON_GROUND_ROCKS01", "rocko_prison_ground_rocks01", "loctypes"),
            new GamevalEntry(58256, "ROCKO_PRISON_GROUND_ROCKS02", "rocko_prison_ground_rocks02", "loctypes"),
            new GamevalEntry(58257, "ROCKO_PRISON_GROUND_ROCKS03", "rocko_prison_ground_rocks03", "loctypes"),
            new GamevalEntry(58258, "ROCKO_ROCK_KIT_1X1_01", "rocko_rock_kit_1x1_01", "loctypes"),
            new GamevalEntry(58259, "ROCKO_ROCK_KIT_1X1_01_ICON", "rocko_rock_kit_1x1_01_icon", "loctypes"),
            new GamevalEntry(58260, "ROCKO_ROCK_KIT_1X1_02", "rocko_rock_kit_1x1_02", "loctypes"),
            new GamevalEntry(58261, "ROCKO_ROCK_KIT_1X1_02_ICON", "rocko_rock_kit_1x1_02_icon", "loctypes"),
            new GamevalEntry(58262, "ROCKO_ROCK_KIT_1X1_03", "rocko_rock_kit_1x1_03", "loctypes"),
            new GamevalEntry(58263, "ROCKO_ROCK_KIT_1X1_03_ICON", "rocko_rock_kit_1x1_03_icon", "loctypes"),
            new GamevalEntry(58264, "ROCKO_ROCK_KIT_3X3_A_01", "rocko_rock_kit_3x3_a_01", "loctypes"),
            new GamevalEntry(58265, "ROCKO_ROCK_KIT_3X3_A_02", "rocko_rock_kit_3x3_a_02", "loctypes"),
            new GamevalEntry(58266, "ROCKO_ROCK_KIT_3X3_A_03", "rocko_rock_kit_3x3_a_03", "loctypes"),
            new GamevalEntry(58267, "ROCKO_ROCK_KIT_3X3_A_04", "rocko_rock_kit_3x3_a_04", "loctypes"),
            new GamevalEntry(58268, "ROCKO_ROCK_KIT_3X3_A_05", "rocko_rock_kit_3x3_a_05", "loctypes"),
            new GamevalEntry(58269, "ROCKO_ROCK_KIT_3X3_A_06", "rocko_rock_kit_3x3_a_06", "loctypes"),
            new GamevalEntry(58270, "ROCKO_ROCK_KIT_3X3_A_07", "rocko_rock_kit_3x3_a_07", "loctypes"),
            new GamevalEntry(58271, "ROCKO_ROCK_KIT_3X3_A_08", "rocko_rock_kit_3x3_a_08", "loctypes"),
            new GamevalEntry(58272, "ROCKO_PRISON_DESK01", "Desk", "loctypes"),
            new GamevalEntry(58273, "ROCKO_PRISON_STAIRS01", "Stairs", "loctypes"),
            new GamevalEntry(58274, "ROCKO_PRISON_STAIRS02", "Stairs", "loctypes"),
            new GamevalEntry(58275, "ROCKO_PRISON_DOOR01", "Door", "loctypes"),
            new GamevalEntry(58276, "ROCKO_PRISON_DOOR_CUSTOM", "Door", "loctypes"),
            new GamevalEntry(58277, "ROCKO_PRISON_DOOR01_OPEN", "Door", "loctypes"),
            new GamevalEntry(58278, "ROCKO_PRISON_REGULAR_PIPES01", "Pipes", "loctypes"),
            new GamevalEntry(58279, "ROCKO_PRISON_REGULAR_PIPES02", "Pipes", "loctypes"),
            new GamevalEntry(58280, "ROCKO_PRISON_DOOR02", "Door", "loctypes"),
            new GamevalEntry(58281, "ROCKO_PRISON_DOOR02_OPEN", "Door", "loctypes"),
            new GamevalEntry(58282, "ROCKO_PRISON_SHARP_ROCK01", "Sharp rock", "loctypes"),
            new GamevalEntry(58283, "ROCKO_PRISON_FILE_CABINET01", "Cabinet", "loctypes"),
            new GamevalEntry(58284, "ROCKO_PRISON_FILE_CABINET_CLOSED01", "Cabinet", "loctypes"),
            new GamevalEntry(58285, "ROCKO_PRISON_RUBBLE01", "Rubble", "loctypes"),
            new GamevalEntry(58286, "ROCKO_PRISON_RUBBLE02", "Rubble", "loctypes"),
            new GamevalEntry(58287, "ROCKO_PRISON_SPOIL_HEAP01", "Rubble", "loctypes"),
            new GamevalEntry(58288, "ROCKO_PRISON_BED01", "Bed", "loctypes"),
            new GamevalEntry(58289, "ROCKO_PRISON_BED02", "rocko_prison_bed02", "loctypes"),
            new GamevalEntry(58290, "ROCKO_PRISON_BUNK_BED", "Bed", "loctypes"),
            new GamevalEntry(58291, "ROCKO_PRISON_BUNK_BED2", "Bed", "loctypes"),
            new GamevalEntry(58292, "ROCKO_PRISON_TABLE", "Desk", "loctypes"),
            new GamevalEntry(58293, "ROCKO_PRISON_BOOKCASE", "Bookcase", "loctypes"),
            new GamevalEntry(58294, "ROCKO_PRISON_OFFICE_LOCKER", "Locker", "loctypes"),
            new GamevalEntry(58295, "ROCKO_CAVEWALL_TOP", "rocko_cavewall_top", "loctypes"),
            new GamevalEntry(58296, "ROCKO_CAVEWALL_FACE1", "rocko_cavewall_face1", "loctypes"),
            new GamevalEntry(58297, "ROCKO_SEAGULL_MULTI_EMPTY_ROCK", "Perch rock", "loctypes"),
            new GamevalEntry(58298, "ROCKO_SEAGULL_MULTI_FISHY_ROCK", "Perch rock", "loctypes"),
            new GamevalEntry(58299, "ROCKO_SEAGULL_MULTI_FISHY_SEAGULL_LANDS_ROCK", "Perch rock", "loctypes"),
            new GamevalEntry(58300, "ROCKO_SEAGULL_MULTI_FISHY_SEAGULL_ROCK", "Perch rock", "loctypes"),
            new GamevalEntry(58301, "ROCKO_SEAGULL_MULTI_SUCKED_SEAGULL_ROCK", "Perch rock", "loctypes"),
            new GamevalEntry(58302, "ROCKO_ANCHOR_BOTTOM", "Anchor", "loctypes"),
            new GamevalEntry(58303, "ROCKO_ANCHOR_MIDDLE", "Anchor", "loctypes"),
            new GamevalEntry(58304, "ROCKO_ANCHOR_MIDDLE2", "Anchor", "loctypes"),
            new GamevalEntry(58305, "ROCKO_BUBBLES", "rocko_bubbles", "loctypes"),
            new GamevalEntry(58306, "ROCKO_WATER_ROCK_KIT_2X2_A_01", "rocko_water_rock_kit_2x2_a_01", "loctypes"),
            new GamevalEntry(58307, "ROCKO_WATER_ROCK_KIT_2X2_A_02", "rocko_water_rock_kit_2x2_a_02", "loctypes"),
            new GamevalEntry(58308, "ROCKO_WATER_ROCK_KIT_2X2_A_03", "rocko_water_rock_kit_2x2_a_03", "loctypes"),
            new GamevalEntry(58309, "ROCKO_WATER_ROCK_KIT_2X2_A_04", "rocko_water_rock_kit_2x2_a_04", "loctypes"),
            new GamevalEntry(58310, "ROCKO_WATER_ROCK_KIT_1X1_01", "rocko_water_rock_kit_1x1_01", "loctypes"),
            new GamevalEntry(58311, "ROCKO_WATER_ROCK_KIT_1X1_02", "rocko_water_rock_kit_1x1_02", "loctypes"),
            new GamevalEntry(58312, "ROCKO_WATER_ROCK_KIT_1X1_03", "rocko_water_rock_kit_1x1_03", "loctypes"),
            new GamevalEntry(58313, "ROCKO_WATER_ROCK_KIT_3X3_B_01", "rocko_water_rock_kit_3x3_b_01", "loctypes"),
            new GamevalEntry(58314, "ROCKO_WATER_ROCK_KIT_3X3_B_02", "rocko_water_rock_kit_3x3_b_02", "loctypes"),
            new GamevalEntry(58315, "ROCKO_WATER_ROCK_KIT_3X3_B_03", "rocko_water_rock_kit_3x3_b_03", "loctypes"),
            new GamevalEntry(58316, "ROCKO_WATER_ROCK_KIT_3X3_B_04", "rocko_water_rock_kit_3x3_b_04", "loctypes"),
            new GamevalEntry(58317, "ROCKO_WATER_ROCK_KIT_3X3_B_05", "rocko_water_rock_kit_3x3_b_05", "loctypes"),
            new GamevalEntry(58318, "ROCKO_WATER_ROCK_KIT_3X3_B_06", "rocko_water_rock_kit_3x3_b_06", "loctypes"),
            new GamevalEntry(58319, "ROCKO_WATER_ROCK_KIT_3X3_B_07", "rocko_water_rock_kit_3x3_b_07", "loctypes"),
            new GamevalEntry(58320, "ROCKO_WATER_ROCK_KIT_3X3_B_08", "rocko_water_rock_kit_3x3_b_08", "loctypes"),
            new GamevalEntry(58321, "ROCKO_WATER_ROCK_KIT_3X3_B_09", "rocko_water_rock_kit_3x3_b_09", "loctypes"),
            new GamevalEntry(58322, "ROCKO_BOAT_HULL_FLOOR_EDGE", "rocko_boat_hull_floor_edge", "loctypes"),
            new GamevalEntry(58323, "ROCKO_BOAT_HULL_FLOOR_EDGE_MIRROR", "rocko_boat_hull_floor_edge_mirror", "loctypes"),
            new GamevalEntry(58324, "ROCKO_IDOL_COVERED_BOARDS", "Mess", "loctypes"),
            new GamevalEntry(58325, "ROCKO_IDOL_COVERED_SAND", "Mess", "loctypes"),
            new GamevalEntry(58326, "ROCKO_IDOL_UNCOVERED", "Idol", "loctypes"),
            new GamevalEntry(58327, "ROCKO_PRISON_EVIDENCE_SHELF01", "Shelf", "loctypes"),
            new GamevalEntry(58328, "ROCKO_PRISON_EVIDENCE_SHELF02", "Shelf", "loctypes"),
            new GamevalEntry(58329, "ROCKO_PRISON_EVIDENCE_SHELF03", "Shelf", "loctypes"),
            new GamevalEntry(58330, "ROCKO_KELP", "rocko_kelp", "loctypes"),
            new GamevalEntry(58331, "ROCKO_CORAL_PLAIN_SIDE1", "rocko_coral_plain_side1", "loctypes"),
            new GamevalEntry(58332, "ROCKO_CORAL_PLAIN_SIDE2", "rocko_coral_plain_side2", "loctypes"),
            new GamevalEntry(58333, "ROCKO_CORAL_PLAIN_CORNER1", "rocko_coral_plain_corner1", "loctypes"),
            new GamevalEntry(58334, "ROCKO_CORAL_PLAIN_CORNER2", "rocko_coral_plain_corner2", "loctypes"),
            new GamevalEntry(58335, "ROCKO_CORAL_PLAIN_INVERSE", "rocko_coral_plain_inverse", "loctypes"),
            new GamevalEntry(58336, "ROCKO_CORAL_PLAIN_TOP3", "rocko_coral_plain_top3", "loctypes"),
            new GamevalEntry(58337, "ROCKO_CORAL_PLAIN_ROCK1", "rocko_coral_plain_rock1", "loctypes"),
            new GamevalEntry(58338, "ROCKO_CORAL_PLAIN_ROCK2", "rocko_coral_plain_rock2", "loctypes"),
            new GamevalEntry(58339, "ROCKO_CORAL_ELK_SIDE1", "rocko_coral_elk_side1", "loctypes"),
            new GamevalEntry(58340, "ROCKO_CORAL_ELK_SIDE2", "rocko_coral_elk_side2", "loctypes"),
            new GamevalEntry(58341, "ROCKO_CORAL_ELK_CORNER1", "rocko_coral_elk_corner1", "loctypes"),
            new GamevalEntry(58342, "ROCKO_CORAL_ELK_CORNER2", "rocko_coral_elk_corner2", "loctypes"),
            new GamevalEntry(58343, "ROCKO_CORAL_ELK_INVERSE", "rocko_coral_elk_inverse", "loctypes"),
            new GamevalEntry(58344, "ROCKO_CORAL_ELK_ROCK1", "rocko_coral_elk_rock1", "loctypes"),
            new GamevalEntry(58345, "ROCKO_CORAL_ELK_ROCK2", "rocko_coral_elk_rock2", "loctypes"),
            new GamevalEntry(58346, "ROCKO_CORAL_LACE_SIDE1", "rocko_coral_lace_side1", "loctypes"),
            new GamevalEntry(58347, "ROCKO_CORAL_LACE_SIDE2", "rocko_coral_lace_side2", "loctypes"),
            new GamevalEntry(58348, "ROCKO_CORAL_LACE_CORNER1", "rocko_coral_lace_corner1", "loctypes"),
            new GamevalEntry(58349, "ROCKO_CORAL_LACE_CORNER2", "rocko_coral_lace_corner2", "loctypes"),
            new GamevalEntry(58350, "ROCKO_CORAL_LACE_INVERSE", "rocko_coral_lace_inverse", "loctypes"),
            new GamevalEntry(58351, "ROCKO_CORAL_LACE_TOP2", "rocko_coral_lace_top2", "loctypes"),
            new GamevalEntry(58352, "ROCKO_CORAL_LACE_TOP3", "rocko_coral_lace_top3", "loctypes"),
            new GamevalEntry(58353, "ROCKO_CORAL_LACE_ROCK1", "rocko_coral_lace_rock1", "loctypes"),
            new GamevalEntry(58354, "ROCKO_CORAL_LACE_ROCK2", "rocko_coral_lace_rock2", "loctypes"),
            new GamevalEntry(58355, "ROCKO_CORAL_DISC_SIDE1", "rocko_coral_disc_side1", "loctypes"),
            new GamevalEntry(58356, "ROCKO_CORAL_DISC_SIDE2", "rocko_coral_disc_side2", "loctypes"),
            new GamevalEntry(58357, "ROCKO_CORAL_DISC_CORNER1", "rocko_coral_disc_corner1", "loctypes"),
            new GamevalEntry(58358, "ROCKO_CORAL_DISC_CORNER2", "rocko_coral_disc_corner2", "loctypes"),
            new GamevalEntry(58359, "ROCKO_CORAL_DISC_INVERSE", "rocko_coral_disc_inverse", "loctypes"),
            new GamevalEntry(58360, "ROCKO_CORAL_DISC_TOP1", "rocko_coral_disc_top1", "loctypes"),
            new GamevalEntry(58361, "ROCKO_CORAL_DISC_TOP3", "rocko_coral_disc_top3", "loctypes"),
            new GamevalEntry(58362, "ROCKO_CORAL_DISC_ROCK1", "rocko_coral_disc_rock1", "loctypes"),
            new GamevalEntry(58363, "ROCKO_CORAL_DISC_ROCK2", "rocko_coral_disc_rock2", "loctypes"),
            new GamevalEntry(58364, "ROCKO_CORAL_TUBE_SIDE1", "rocko_coral_tube_side1", "loctypes"),
            new GamevalEntry(58365, "ROCKO_CORAL_TUBE_SIDE2", "rocko_coral_tube_side2", "loctypes"),
            new GamevalEntry(58366, "ROCKO_CORAL_TUBE_CORNER1", "rocko_coral_tube_corner1", "loctypes"),
            new GamevalEntry(58367, "ROCKO_CORAL_TUBE_CORNER2", "rocko_coral_tube_corner2", "loctypes"),
            new GamevalEntry(58368, "ROCKO_CORAL_TUBE_INVERSE", "rocko_coral_tube_inverse", "loctypes"),
            new GamevalEntry(58369, "ROCKO_CORAL_TUBE_ROCK1", "rocko_coral_tube_rock1", "loctypes"),
            new GamevalEntry(58370, "ROCKO_CORAL_TUBE_ROCK2", "rocko_coral_tube_rock2", "loctypes"),
            new GamevalEntry(58371, "ROCKO_RIMMINGTON_NOTICE_BOARD", "Notices", "loctypes"),
            new GamevalEntry(58372, "ROCKO_PRISON_PIER", "rocko_prison_pier", "loctypes"),
            new GamevalEntry(58373, "ROCKO_PRISON_PIER_DIVE", "Pier", "loctypes"),
            new GamevalEntry(58374, "ROCKO_DRAGONTOOTH_DIVING_POINT", "Chain", "loctypes"),
            new GamevalEntry(58375, "ROCKO_TREASURE_CHEST", "Chest", "loctypes"),
            new GamevalEntry(58376, "ROCKO_CUTSCENE_SHIP_FLOOR01", "rocko_cutscene_ship_floor01", "loctypes"),
            new GamevalEntry(58377, "ROCKO_TREASURE_OPENCHEST", "Chest", "loctypes"),
            new GamevalEntry(58378, "ROCKO_CUTSCENE_SHIP_FLOOR04", "rocko_cutscene_ship_floor04", "loctypes"),
            new GamevalEntry(58379, "ROCKO_CUTSCENE_SHIP_FLOOR05", "rocko_cutscene_ship_floor05", "loctypes"),
            new GamevalEntry(58380, "ROCKO_CUTSCENE_SHIP_FLOOR06", "rocko_cutscene_ship_floor06", "loctypes"),
            new GamevalEntry(58381, "ROCKO_CUTSCENE_SHIP_FLOOR07", "rocko_cutscene_ship_floor07", "loctypes"),
            new GamevalEntry(58382, "ROCKO_CUTSCENE_SHIP_FLOOR07_MIRROR", "rocko_cutscene_ship_floor07_mirror", "loctypes"),
            new GamevalEntry(58383, "ROCKO_CUTSCENE_SHIP_RAILING01", "rocko_cutscene_ship_railing01", "loctypes"),
            new GamevalEntry(58384, "ROCKO_CUTSCENE_SHIP_FLOOR08", "rocko_cutscene_ship_floor08", "loctypes"),
            new GamevalEntry(58385, "ROCKO_CUTSCENE_SHIP_FLOOR10", "rocko_cutscene_ship_floor10", "loctypes"),
            new GamevalEntry(58386, "ROCKO_CUTSCENE_SHIP_RAILING02", "rocko_cutscene_ship_railing02", "loctypes"),
            new GamevalEntry(58387, "ROCKO_CUTSCENE_SHIP_RAILING05", "rocko_cutscene_ship_railing05", "loctypes"),
            new GamevalEntry(58388, "ROCKO_CUTSCENE_SHIP_MAST01", "rocko_cutscene_ship_mast01", "loctypes"),
            new GamevalEntry(58389, "ROCKO_CUTSCENE_SHIP_STEERING01", "rocko_cutscene_ship_steering01", "loctypes"),
            new GamevalEntry(58390, "ROCKO_CUTSCENE_SHIP_STAIRS01", "rocko_cutscene_ship_stairs01", "loctypes"),
            new GamevalEntry(58391, "ROCKO_CUTSCENE_SHIP_WALL01", "rocko_cutscene_ship_wall01", "loctypes"),
            new GamevalEntry(58392, "ROCKO_CUTSCENE_SHIP_SKYBOX01", "rocko_cutscene_ship_skybox01", "loctypes"),
            new GamevalEntry(58393, "ROCKO_CUTSCENE_SHIP_SKYBOX02", "rocko_cutscene_ship_skybox02", "loctypes"),
            new GamevalEntry(58394, "ROCKO_CUTSCENE_SHIP_SKYBOX03", "rocko_cutscene_ship_skybox03", "loctypes"),
            new GamevalEntry(58395, "ROCKO_CUTSCENE_SHIP_SKYBOX04", "rocko_cutscene_ship_skybox04", "loctypes"),
            new GamevalEntry(58396, "ROCKO_CUTSCENE_SHIP_SEABOX01", "rocko_cutscene_ship_seabox01", "loctypes"),
            new GamevalEntry(58397, "ROCKO_CUTSCENE_SHIP_SKYBOX_ULTRA", "rocko_cutscene_ship_skybox_ultra", "loctypes"),
            new GamevalEntry(58398, "ROCKO_CUTSCENE_SHIP_BOTTOM02", "rocko_cutscene_ship_bottom02", "loctypes"),
            new GamevalEntry(58399, "ROCKO_CUTSCENE_SHIP_BOTTOM03", "rocko_cutscene_ship_bottom03", "loctypes"),
            new GamevalEntry(58400, "ROCKO_CUTSCENE_SHIP_TREASURE_CHEST01", "rocko_cutscene_ship_treasure_chest01", "loctypes"),
            new GamevalEntry(58401, "ROCKO_CUTSCENE_SHIP_ARROWS01", "rocko_cutscene_ship_arrows01", "loctypes"),
            new GamevalEntry(58402, "ROCKO_CUTSCENE_SHIP_ARROWS02", "rocko_cutscene_ship_arrows02", "loctypes"),
            new GamevalEntry(58403, "PRY_CRATE_MULTI", "pry_crate_multi", "loctypes"),
            new GamevalEntry(58404, "PRY_SACKS", "Sacks", "loctypes"),
            new GamevalEntry(58405, "PRY_CRATE_SEALED", "Sealed crate", "loctypes"),
            new GamevalEntry(58406, "PRY_CRATE_OPEN", "Crate of crowbars", "loctypes"),
            new GamevalEntry(58407, "TEMPLE_PYRE_CAMPHOR", "Camphor Pyre", "loctypes"),
            new GamevalEntry(58408, "TEMPLE_PYRE_IRONWOOD", "Ironwood Pyre", "loctypes"),
            new GamevalEntry(58409, "TEMPLE_PYRE_ROSEWOOD", "Rosewood Pyre", "loctypes"),
            new GamevalEntry(58410, "TEMPLE_PYRE_BONES_CAMPHOR", "Camphor Pyre", "loctypes"),
            new GamevalEntry(58411, "TEMPLE_PYRE_BONES_IRONWOOD", "Ironwood Pyre", "loctypes"),
            new GamevalEntry(58412, "TEMPLE_PYRE_BONES_ROSEWOOD", "Rosewood Pyre", "loctypes"),
            new GamevalEntry(58413, "ROWBOAT_2", "Rowboat", "loctypes"),
            new GamevalEntry(58414, "SLUG2_BARREL_RODS_ACTIVE", "Barrel", "loctypes"),
            new GamevalEntry(58415, "TT_PALM_1", "Palm", "loctypes"),
            new GamevalEntry(58416, "TT_PALM_2", "Palm", "loctypes"),
            new GamevalEntry(58417, "TT_PALM_3", "Palm", "loctypes"),
            new GamevalEntry(58418, "TORTUGAN_EGGS", "Eggs", "loctypes"),
            new GamevalEntry(58419, "TORTUGAN_EGGS02", "Eggs", "loctypes"),
            new GamevalEntry(58420, "TT_REPAIR_KRILL_STALL", "tt_repair_krill_stall", "loctypes"),
            new GamevalEntry(58421, "TT_REPAIR_COCO_STALL", "tt_repair_coco_stall", "loctypes"),
            new GamevalEntry(58422, "TT_REPAIR_STROM_CRATES", "tt_repair_strom_crates", "loctypes"),
            new GamevalEntry(58423, "TT_REPAIR_COCO_CRATES", "tt_repair_coco_crates", "loctypes"),
            new GamevalEntry(58424, "TT_REPAIR_KRILL_WALL", "tt_repair_krill_wall", "loctypes"),
            new GamevalEntry(58425, "TT_REPAIR_STROM_WALL", "tt_repair_strom_wall", "loctypes"),
            new GamevalEntry(58426, "TT_REPAIR_STALL_COCO_BROKEN_NOOP", "Broken crafting stall", "loctypes"),
            new GamevalEntry(58427, "TT_REPAIR_STALL_COCO_BROKEN", "Broken crafting stall", "loctypes"),
            new GamevalEntry(58428, "TT_REPAIR_STALL_KRILL_BROKEN_NOOP", "Broken fish stall", "loctypes"),
            new GamevalEntry(58429, "TT_REPAIR_STALL_KRILL_BROKEN", "Broken fish stall", "loctypes"),
            new GamevalEntry(58430, "TT_REPAIR_CRATES_BROKEN_NOOP", "Broken crate", "loctypes"),
            new GamevalEntry(58431, "TT_REPAIR_CRATES_BROKEN", "Broken crate", "loctypes"),
            new GamevalEntry(58432, "TT_REPAIR_CRATES_FIXED", "Crate", "loctypes"),
            new GamevalEntry(58433, "TT_REPAIR_CRATES_COCO_BROKEN_NOOP", "Broken coconut crate", "loctypes"),
            new GamevalEntry(58434, "TT_REPAIR_CRATES_COCO_BROKEN", "Broken coconut crate", "loctypes"),
        };
    }

    static Optional<GamevalEntry> byId(int id) {
        for (GamevalEntry entry : entries()) {
            if (entry.id() == id) return Optional.of(entry);
        }
        return Optional.empty();
    }

}
