package net.titan.gamevals.internal;

import java.util.Optional;

import net.titan.gamevals.GamevalEntry;
import net.titan.gamevals.QuestEntry;

final class ObjectIDEntries_56 {
    private ObjectIDEntries_56() {}

    static GamevalEntry[] entries() {
        return new GamevalEntry[] {
            new GamevalEntry(28738, "MM2_CAVE_SECRET_BUNKER_LEV0_HOLD", "mm2_cave_secret_bunker_lev0_hold", "loctypes"),
            new GamevalEntry(28739, "MM2_CAVE_SECRET_BUNKER_TOP", "mm2_cave_secret_bunker_top", "loctypes"),
            new GamevalEntry(28740, "MM2_CAVE_SECRET_BUNKER_TOP5", "mm2_cave_secret_bunker_top5", "loctypes"),
            new GamevalEntry(28741, "MM2_CAVE_SECRET_BUNKER_LEV1_01", "mm2_cave_secret_bunker_lev1_01", "loctypes"),
            new GamevalEntry(28742, "MM2_CAVE_SECRET_BUNKER_LEV1_HOLD", "mm2_cave_secret_bunker_lev1_hold", "loctypes"),
            new GamevalEntry(28743, "MM2_CAVE_SECRET_BUNKER_LEV1_02", "mm2_cave_secret_bunker_lev1_02", "loctypes"),
            new GamevalEntry(28744, "MM2_CAVE_SECRET_BUNKER_LEV1_HOLD_UPPER", "mm2_cave_secret_bunker_lev1_hold_upper", "loctypes"),
            new GamevalEntry(28745, "MM2_CAVE_SECRET_BUNKER_LEV1_JOIN01", "mm2_cave_secret_bunker_lev1_join01", "loctypes"),
            new GamevalEntry(28746, "MM2_CAVE_SECRET_BUNKER_LEV1_JOIN02", "mm2_cave_secret_bunker_lev1_join02", "loctypes"),
            new GamevalEntry(28747, "MM2_CAVE_SECRET_BUNKER_LEV1_TOP", "mm2_cave_secret_bunker_lev1_top", "loctypes"),
            new GamevalEntry(28748, "MM2_CAVE_SECRET_BUNKER_LEV2_STRAIGHT", "mm2_cave_secret_bunker_lev2_straight", "loctypes"),
            new GamevalEntry(28749, "MM2_CAVE_SECRET_BUNKER_LEV2_CORNER_01", "mm2_cave_secret_bunker_lev2_corner_01", "loctypes"),
            new GamevalEntry(28750, "MM2_CAVE_SECRET_BUNKER_LEV2_CORNER_02", "mm2_cave_secret_bunker_lev2_corner_02", "loctypes"),
            new GamevalEntry(28751, "MM2_CAVE_SECRET_BUNKER_LEV2_TOP", "mm2_cave_secret_bunker_lev2_top", "loctypes"),
            new GamevalEntry(28752, "MM2_CAVE_SECRET_BUNKER_STEP_ROCKS", "Rocks", "loctypes"),
            new GamevalEntry(28753, "MM2_STEP_ROCKS_TOP", "Rocks", "loctypes"),
            new GamevalEntry(28754, "MM2_VINE_SWING", "Vine", "loctypes"),
            new GamevalEntry(28755, "MM2_VINE_WALK", "Vine", "loctypes"),
            new GamevalEntry(28756, "MM2_LEDGE_HANG", "Wall support", "loctypes"),
            new GamevalEntry(28757, "MM2_LEDGE_WALK", "Rocky ledge", "loctypes"),
            new GamevalEntry(28758, "MM2_ROCK_FALL", "Pressure pad", "loctypes"),
            new GamevalEntry(28759, "MM2_PILLAR_JUMP", "Pillar", "loctypes"),
            new GamevalEntry(28760, "MM2_PILLAR_BASE_01", "mm2_pillar_base_01", "loctypes"),
            new GamevalEntry(28761, "MM2_PILLAR_BASE_02", "mm2_pillar_base_02", "loctypes"),
            new GamevalEntry(28762, "MM2_PILLAR_BASE_03", "mm2_pillar_base_03", "loctypes"),
            new GamevalEntry(28763, "MM2_LOG_WALK", "Log balance", "loctypes"),
            new GamevalEntry(28764, "MM2_CRACK_PASS", "Hole", "loctypes"),
            new GamevalEntry(28765, "MM2_GAP_JUMP", "Gap", "loctypes"),
            new GamevalEntry(28766, "MM2_GAP_JUMP_8", "Gap", "loctypes"),
            new GamevalEntry(28767, "MM2_TILE_WALK", "Dodgy ground", "loctypes"),
            new GamevalEntry(28768, "MM2_TILE_BROKEN", "Dodgy ground", "loctypes"),
            new GamevalEntry(28769, "MM2_TILE_BROKEN_ANIM", "Broken ground", "loctypes"),
            new GamevalEntry(28770, "MM2_TILE_BLEND_EDGE", "mm2_tile_blend_edge", "loctypes"),
            new GamevalEntry(28771, "MM2_TILE_BLEND_CORNER", "mm2_tile_blend_corner", "loctypes"),
            new GamevalEntry(28772, "MM2_MAZE_EXIT_HOLE", "Hole", "loctypes"),
            new GamevalEntry(28773, "MM2_MAZE_EXIT_HOLE_SIDE", "mm2_maze_exit_hole_side", "loctypes"),
            new GamevalEntry(28774, "MM2_MAZE_EXIT_HOLE_CORNER", "mm2_maze_exit_hole_corner", "loctypes"),
            new GamevalEntry(28775, "MM2_MAZE_EXIT_ROPE", "Rope", "loctypes"),
            new GamevalEntry(28776, "MM2_TRAP_TRIPWIRE", "Tripwire", "loctypes"),
            new GamevalEntry(28777, "MM2_TRAP_SPIKES", "Floor spikes", "loctypes"),
            new GamevalEntry(28778, "MM2_TRAP_DARTS", "Dart trap", "loctypes"),
            new GamevalEntry(28779, "MM2_TRAP_SAW", "Blade", "loctypes"),
            new GamevalEntry(28780, "MM2_TRAP_SAW_FLOOR", "Blade", "loctypes"),
            new GamevalEntry(28781, "MM2_TRAP_SAW_FLOOR2", "Blade", "loctypes"),
            new GamevalEntry(28782, "MM2_TRAP_AXES", "Spinning blades", "loctypes"),
            new GamevalEntry(28783, "MM2_THIEVING_DOOR", "Door", "loctypes"),
            new GamevalEntry(28784, "MM2_THIEVING_DOOR_INACTIVE", "mm2_thieving_door_inactive", "loctypes"),
            new GamevalEntry(28785, "MM2_CHEST_CLOSED", "Locked chest", "loctypes"),
            new GamevalEntry(28786, "MM2_ROCKS_BREAKABLE", "Rockfall", "loctypes"),
            new GamevalEntry(28787, "MM2_ROCKS_RUBBLE", "mm2_rocks_rubble", "loctypes"),
            new GamevalEntry(28788, "MM2_ROCKS_UNBREAKABLE", "Rockslide", "loctypes"),
            new GamevalEntry(28789, "MM2_WEB", "Web", "loctypes"),
            new GamevalEntry(28790, "MM2_SLICED_WEB", "Sliced web", "loctypes"),
            new GamevalEntry(28791, "MM2_MONKEY_FIRE", "Fire", "loctypes"),
            new GamevalEntry(28792, "MM2_AGILITY_CHEST_CLOSED", "Chest", "loctypes"),
            new GamevalEntry(28793, "MM2_AGILITY_CHEST_OPEN", "Chest", "loctypes"),
            new GamevalEntry(28794, "MM2_AGILITY_DOOR", "Bronze Door", "loctypes"),
            new GamevalEntry(28795, "MM2_AGILITY_DOOR_INACTIVE", "mm2_agility_door_inactive", "loctypes"),
            new GamevalEntry(28796, "MM2_THIEVING_CHEST_CLOSED", "Chest", "loctypes"),
            new GamevalEntry(28797, "MM2_THIEVING_CHEST_OPEN", "Chest", "loctypes"),
            new GamevalEntry(28798, "MM2_MAZE_RETURN_HIDDEN", "Wall", "loctypes"),
            new GamevalEntry(28799, "MM2_MAZE_RETURN_OPEN", "Passage", "loctypes"),
            new GamevalEntry(28800, "MM2_GLOUGH_BRANCH_DOWN_MULTI", "mm2_glough_branch_down_multi", "loctypes"),
            new GamevalEntry(28801, "MM2_DOWNTREE_SEARCHABLE", "Tree", "loctypes"),
            new GamevalEntry(28802, "ARCEUUS_LECTERN", "Lectern", "loctypes"),
            new GamevalEntry(28803, "MM_BANKDESK", "mm_bankdesk", "loctypes"),
            new GamevalEntry(28804, "MM_JUNGLEPLANT_FAT", "Jungle Plant", "loctypes"),
            new GamevalEntry(28805, "MM2_LAB_INCUBATOR_MULTI", "M ???s????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????= ????????= ????????= ????????= ????????@S????????@S????????@S????????@S", "loctypes"),
            new GamevalEntry(28806, "MM2_LAB_LEVER_MULTI", "mm2_lab_lever_multi", "loctypes"),
            new GamevalEntry(28807, "MM2_STRONGHOLD_FENCE_MULTI", "mm2_stronghold_fence_multi", "loctypes"),
            new GamevalEntry(28808, "MM2_KRUKS_TRACKS_MULTI", "mm2_kruks_tracks_multi", "loctypes"),
            new GamevalEntry(28809, "MM2_OTHER_TRACKS_MULTI", "mm2_other_tracks_multi", "loctypes"),
            new GamevalEntry(28810, "MM2_SECRET_ENTRANCE_MULTI", "mm2_secret_entrance_multi", "loctypes"),
            new GamevalEntry(28811, "MM2_KRUKS_REMAINS_MULTI", "mm2_kruks_remains_multi", "loctypes"),
            new GamevalEntry(28812, "MM2_MONKEY_BOAT_POST_MULTI", "mm2_monkey_boat_post_multi", "loctypes"),
            new GamevalEntry(28813, "MM2_SECRET_LAB_ENTRANCE_MULTI", "mm2_secret_lab_entrance_multi", "loctypes"),
            new GamevalEntry(28814, "MM2_MAZE_RETURN_MULTI", "mm2_maze_return_multi", "loctypes"),
            new GamevalEntry(28815, "MM2_CAVE_BOSS_RAMP", "mm2_cave_boss_ramp", "loctypes"),
            new GamevalEntry(28816, "MM_DESK_BANKCHEST", "Bank chest", "loctypes"),
            new GamevalEntry(28817, "MM2_POSTQUEST_BRAZIER", "Brazier", "loctypes"),
            new GamevalEntry(28818, "MM2_POSTQUEST_BRAZIER_LIT", "Burning brazier", "loctypes"),
            new GamevalEntry(28819, "MM2_POSTQUEST_BRAZIER_MULTI", "mm2_postquest_brazier_multi", "loctypes"),
            new GamevalEntry(28820, "MM2_CAVE_BOSS_WATERFALL_LARGE_03", "Ruptured cavern", "loctypes"),
            new GamevalEntry(28821, "MM2_CAVE_BOSS_WATERFALL_SMALL_03", "Ruptured cavern", "loctypes"),
            new GamevalEntry(28822, "POH_KOUREND_PORTAL", "Portal", "loctypes"),
            new GamevalEntry(28823, "HOS_FRUIT_STALL_02", "Steal-from", "loctypes"),
            new GamevalEntry(28824, "HUNTING_MONKEYTRAP_UNSET", "Large boulder", "loctypes"),
            new GamevalEntry(28825, "HUNTING_MONKEYTRAP_SETTING", "Large boulder", "loctypes"),
            new GamevalEntry(28826, "HUNTING_MONKEYTRAP_UNSETTING", "Large boulder", "loctypes"),
            new GamevalEntry(28827, "HUNTING_MONKEYTRAP_SET", "Monkey trap", "loctypes"),
            new GamevalEntry(28828, "HUNTING_MONKEYTRAP_TRAPPING_0", "Monkey trap", "loctypes"),
            new GamevalEntry(28829, "HUNTING_MONKEYTRAP_TRAPPING_1", "Monkey trap", "loctypes"),
            new GamevalEntry(28830, "HUNTING_MONKEYTRAP_FULL_0", "Large boulder", "loctypes"),
            new GamevalEntry(28831, "HUNTING_MONKEYTRAP_FULL_1", "Large boulder", "loctypes"),
            new GamevalEntry(28832, "HUNTING_MONKEYTRAP_CHECKING_0", "Monkey trap", "loctypes"),
            new GamevalEntry(28833, "HUNTING_MONKEYTRAP_CHECKING_1", "Monkey trap", "loctypes"),
            new GamevalEntry(28834, "HUNTING_MONKEYTRAP_FAILING", "Monkey trap", "loctypes"),
            new GamevalEntry(28835, "LOVAKENGJ_MINECART", "Minecart", "loctypes"),
            new GamevalEntry(28836, "DUNGEONKIT_WALLTOP01_SEWERS01", "dungeonkit_walltop01_sewers01", "loctypes"),
            new GamevalEntry(28837, "LOVAKENGJ_MINECART_CONTROLS", "Control panel", "loctypes"),
            new GamevalEntry(28838, "LOVAKENGJ_MINECART_TUNNEL_DARKGREY", "lovakengj_minecart_tunnel_darkgrey", "loctypes"),
            new GamevalEntry(28839, "LOVAKENGJ_MINECART_TUNNEL_LIGHTGREY", "lovakengj_minecart_tunnel_lightgrey", "loctypes"),
            new GamevalEntry(28840, "LOVAKENGJ_MINECART_SIDE_L_LIGHTGREY", "lovakengj_minecart_side_l_lightgrey", "loctypes"),
            new GamevalEntry(28841, "LOVAKENGJ_MINECART_SIDE_R_LIGHTGREY", "lovakengj_minecart_side_r_lightgrey", "loctypes"),
            new GamevalEntry(28842, "LOVAKENGJ_MINECART_TUNNEL_DARKBROWN", "lovakengj_minecart_tunnel_darkbrown", "loctypes"),
            new GamevalEntry(28843, "LOVAKENGJ_MINECART_SIDE_L_DARKBROWN", "lovakengj_minecart_side_l_darkbrown", "loctypes"),
            new GamevalEntry(28844, "LOVAKENGJ_MINECART_SIDE_R_DARKBROWN", "lovakengj_minecart_side_r_darkbrown", "loctypes"),
            new GamevalEntry(28845, "LOVAKENGJ_MINECART_TUNNEL_GREEN", "lovakengj_minecart_tunnel_green", "loctypes"),
            new GamevalEntry(28846, "LOVAKENGJ_MINECART_SIDE_L_GREEN", "lovakengj_minecart_side_l_green", "loctypes"),
            new GamevalEntry(28847, "LOVAKENGJ_MINECART_SIDE_R_GREEN", "lovakengj_minecart_side_r_green", "loctypes"),
            new GamevalEntry(28848, "RAIDS_REWARD_LOOTBEAM", "raids_reward_lootbeam", "loctypes"),
            new GamevalEntry(28849, "DEEPDUNGEONLOOSERAILING", "Loose Railing", "loctypes"),
            new GamevalEntry(28850, "DEADMAN_SAFEZONE_INDICATOR_MULTI", "deadman_safezone_indicator_multi", "loctypes"),
            new GamevalEntry(28851, "WCGUILD_GATEL", "Gate", "loctypes"),
            new GamevalEntry(28852, "WCGUILD_GATER", "Gate", "loctypes"),
            new GamevalEntry(28853, "WCGUILD_GATEL_OPEN", "wcguild_gatel_open", "loctypes"),
            new GamevalEntry(28854, "WCGUILD_GATER_OPEN", "wcguild_gater_open", "loctypes"),
            new GamevalEntry(28855, "WCGUILD_CAVE", "Cave", "loctypes"),
            new GamevalEntry(28856, "WCGUILD_CAVE_EXIT", "Vine", "loctypes"),
            new GamevalEntry(28857, "WCGUILD_REDWOOD_ROPEBOTTOM", "Rope ladder", "loctypes"),
            new GamevalEntry(28858, "WCGUILD_REDWOOD_ROPETOP", "Rope ladder", "loctypes"),
            new GamevalEntry(28859, "POH_SERVANT_MONEYBAG", "Servant's money bag", "loctypes"),
            new GamevalEntry(28860, "COFFIN_OPEN_INACTIVE", "coffin_open_inactive", "loctypes"),
            new GamevalEntry(28861, "WCGUILD_BANKCHEST", "Bank chest", "loctypes"),
            new GamevalEntry(28862, "WCGUILD_TABLE", "Table", "loctypes"),
            new GamevalEntry(28863, "WCGUILD_TABLE_SMALL", "Table", "loctypes"),
            new GamevalEntry(28864, "WCGUILD_COUNTER", "Counter", "loctypes"),
            new GamevalEntry(28865, "TEMPLE_PYRE_REDWOOD", "Redwood Pyre", "loctypes"),
            new GamevalEntry(28866, "TEMPLE_PYRE_BONES_REDWOOD", "Redwood Pyre", "loctypes"),
            new GamevalEntry(28867, "ZEAH_CATA_WALL_01", "zeah_cata_wall_01", "loctypes"),
            new GamevalEntry(28868, "ZEAH_CATA_WALL_02", "zeah_cata_wall_02", "loctypes"),
            new GamevalEntry(28869, "ZEAH_CATA_WALL_03", "zeah_cata_wall_03", "loctypes"),
            new GamevalEntry(28870, "ZEAH_CATA_WALL_04", "zeah_cata_wall_04", "loctypes"),
            new GamevalEntry(28871, "ZEAH_CATA_OVERPASS_01", "zeah_cata_overpass_01", "loctypes"),
            new GamevalEntry(28872, "ZEAH_CATA_OVERPASS_02", "zeah_cata_overpass_02", "loctypes"),
            new GamevalEntry(28873, "ZEAH_CATA_OVERPASS_SIDE_01", "zeah_cata_overpass_side_01", "loctypes"),
            new GamevalEntry(28874, "ZEAH_CATA_OVERPASS_SIDE_02", "zeah_cata_overpass_side_02", "loctypes"),
            new GamevalEntry(28875, "ZEAH_CATA_OVERPASS_WALL_01", "zeah_cata_overpass_wall_01", "loctypes"),
            new GamevalEntry(28876, "ZEAH_CATA_STAIRS_01", "zeah_cata_stairs_01", "loctypes"),
            new GamevalEntry(28877, "ZEAH_CATA_FLOOR_01", "zeah_cata_floor_01", "loctypes"),
            new GamevalEntry(28878, "ZEAH_CATA_FLOOR_02", "zeah_cata_floor_02", "loctypes"),
            new GamevalEntry(28879, "ZEAH_CATA_FLOOR_03", "zeah_cata_floor_03", "loctypes"),
            new GamevalEntry(28880, "ZEAH_CATA_FLOOR_04", "zeah_cata_floor_04", "loctypes"),
            new GamevalEntry(28881, "ZEAH_CATA_FLOOR_05", "zeah_cata_floor_05", "loctypes"),
            new GamevalEntry(28882, "ZEAH_CATA_FLOOR_06", "zeah_cata_floor_06", "loctypes"),
            new GamevalEntry(28883, "ZEAH_CATA_FLOOR_07", "zeah_cata_floor_07", "loctypes"),
            new GamevalEntry(28884, "ZEAH_CATA_FLOOR_08", "zeah_cata_floor_08", "loctypes"),
            new GamevalEntry(28885, "ZEAH_CATA_FLOOR_09", "zeah_cata_floor_09", "loctypes"),
            new GamevalEntry(28886, "ZEAH_CATA_FLOOR_10", "zeah_cata_floor_10", "loctypes"),
            new GamevalEntry(28887, "ZEAH_CATA_FLOOR_11", "zeah_cata_floor_11", "loctypes"),
            new GamevalEntry(28888, "ZEAH_CATA_FLOOR_12", "zeah_cata_floor_12", "loctypes"),
            new GamevalEntry(28889, "ZEAH_CATA_FLOOR_13", "zeah_cata_floor_13", "loctypes"),
            new GamevalEntry(28890, "ZEAH_CATA_ROCK_MINE", "Rocks", "loctypes"),
            new GamevalEntry(28891, "ZEAH_CATA_ROCK_RUBBLE", "zeah_cata_rock_rubble", "loctypes"),
            new GamevalEntry(28892, "ZEAH_CATA_CRACK", "Crack", "loctypes"),
            new GamevalEntry(28893, "ZEAH_CATA_STEPSTONE", "Stone", "loctypes"),
            new GamevalEntry(28894, "CATA_EXIT", "Vine ladder", "loctypes"),
            new GamevalEntry(28895, "ZEAH_CATA_EXIT_01", "Vine", "loctypes"),
            new GamevalEntry(28896, "ZEAH_CATA_EXIT_02", "Vine", "loctypes"),
            new GamevalEntry(28897, "ZEAH_CATA_EXIT_03", "Vine", "loctypes"),
            new GamevalEntry(28898, "ZEAH_CATA_EXIT_04", "Vine", "loctypes"),
            new GamevalEntry(28899, "ZEAH_CATA_EXIT_TOP", "zeah_cata_exit_top", "loctypes"),
            new GamevalEntry(28900, "CATA_ALTAR", "Teleport", "loctypes"),
            new GamevalEntry(28901, "CATA_GRASS_ACTIVE1", "Boulder", "loctypes"),
            new GamevalEntry(28902, "CATA_HOLE1_SIDE_MULTI", "cata_hole1_side_multi", "loctypes"),
            new GamevalEntry(28903, "CATA_HOLE1_CORNER_MULTI", "cata_hole1_corner_multi", "loctypes"),
            new GamevalEntry(28904, "CATA_GRASS_ACTIVE2", "Boulder", "loctypes"),
            new GamevalEntry(28905, "CATA_HOLE2_SIDE_MULTI", "cata_hole2_side_multi", "loctypes"),
            new GamevalEntry(28906, "CATA_HOLE2_CORNER_MULTI", "cata_hole2_corner_multi", "loctypes"),
            new GamevalEntry(28907, "CATA_HOLE3_SIDE_MULTI", "cata_hole3_side_multi", "loctypes"),
            new GamevalEntry(28908, "CATA_HOLE3_CORNER_MULTI", "cata_hole3_corner_multi", "loctypes"),
            new GamevalEntry(28909, "ROOFTOPS_ARDY_PLANK_MIDDLE", "rooftops_ardy_plank_middle", "loctypes"),
            new GamevalEntry(28910, "CATA_HOLE4_SIDE_MULTI", "cata_hole4_side_multi", "loctypes"),
            new GamevalEntry(28911, "CATA_HOLE4_CORNER_MULTI", "cata_hole4_corner_multi", "loctypes"),
            new GamevalEntry(28912, "ROOFTOPS_ARDY_WALLCROSSING", "Steep roof", "loctypes"),
            new GamevalEntry(28913, "ROOFTOPS_ARDY_LEAPDOWN", "Gap", "loctypes"),
            new GamevalEntry(28914, "AIRTEMPLE_RUINED_OLD", "Mysterious ruins", "loctypes"),
            new GamevalEntry(28915, "CATA_HOLE", "Hole", "loctypes"),
            new GamevalEntry(28916, "CATA_HOLE_SIDE", "cata_hole_side", "loctypes"),
            new GamevalEntry(28917, "CATA_HOLE_CORNER", "cata_hole_corner", "loctypes"),
            new GamevalEntry(28918, "CATA_HOLE1_MULTI", "M ??? ?-?,", "loctypes"),
            new GamevalEntry(28919, "CATA_HOLE2_MULTI", "cata_hole2_multi", "loctypes"),
            new GamevalEntry(28920, "CATA_HOLE3_MULTI", "cata_hole3_multi", "loctypes"),
            new GamevalEntry(28921, "CATA_HOLE4_MULTI", "cata_hole4_multi", "loctypes"),
            new GamevalEntry(28922, "CATA_BOSS_LOOT", "Inanimate Altar", "loctypes"),
            new GamevalEntry(28923, "CATA_BOSS_ALTAR_OPEN", "Awakened Altar", "loctypes"),
            new GamevalEntry(28924, "CATA_BOSS_ALTAR_CLOSED", "Altar", "loctypes"),
            new GamevalEntry(28925, "CATA_BOSS_EXIT_PORTAL", "Portal", "loctypes"),
            new GamevalEntry(28926, "ZEAH_CATA_FLOOR_14", "zeah_cata_floor_14", "loctypes"),
            new GamevalEntry(28927, "ZEAH_CATA_FLOOR_15", "zeah_cata_floor_15", "loctypes"),
            new GamevalEntry(28928, "TOG_JUNA_1OP", "Talk-to", "loctypes"),
            new GamevalEntry(28929, "TOG_JUNA_2OPS", "Talk-to", "loctypes"),
            new GamevalEntry(28930, "SHILO_BROKENCART_ORIGINAL", "Broken cart", "loctypes"),
            new GamevalEntry(28931, "SHILO_BROKENCART_POSTQUEST", "Broken cart", "loctypes"),
            new GamevalEntry(28932, "HOS_BARREL_ASGARNIAN_ALE", "Asgarnian Ale", "loctypes"),
            new GamevalEntry(28933, "HIDEY_CRATE_MEDIUM", "STASH (medium)", "loctypes"),
            new GamevalEntry(28934, "HIDEY_UNBUILT_BUSH_HARD", "Inconspicuous bush (hard)", "loctypes"),
            new GamevalEntry(28935, "HIDEY_BUSH_HARD", "STASH (hard)", "loctypes"),
            new GamevalEntry(28936, "HIDEY_UNBUILT_HOLE_HARD", "Inconspicuous hole (hard)", "loctypes"),
            new GamevalEntry(28937, "HIDEY_HOLE_HARD", "STASH (hard)", "loctypes"),
            new GamevalEntry(28938, "HIDEY_UNBUILT_ROCK_HARD", "Inconspicuous rocks (hard)", "loctypes"),
            new GamevalEntry(28939, "HIDEY_ROCK_HARD", "STASH (hard)", "loctypes"),
            new GamevalEntry(28940, "HIDEY_UNBUILT_CRATE_HARD", "Inconspicuous crate (hard)", "loctypes"),
            new GamevalEntry(28941, "HIDEY_CRATE_HARD", "STASH (hard)", "loctypes"),
            new GamevalEntry(28942, "HIDEY_UNBUILT_BUSH_ELITE", "Inconspicuous bush (elite)", "loctypes"),
            new GamevalEntry(28943, "HIDEY_BUSH_ELITE", "STASH (elite)", "loctypes"),
            new GamevalEntry(28944, "HIDEY_UNBUILT_HOLE_ELITE", "Inconspicuous hole (elite)", "loctypes"),
            new GamevalEntry(28945, "HIDEY_HOLE_ELITE", "STASH (elite)", "loctypes"),
            new GamevalEntry(28946, "HIDEY_UNBUILT_ROCK_ELITE", "Inconspicuous rocks (elite)", "loctypes"),
            new GamevalEntry(28947, "HIDEY_ROCK_ELITE", "STASH (elite)", "loctypes"),
            new GamevalEntry(28948, "HIDEY_UNBUILT_CRATE_ELITE", "Inconspicuous crate (elite)", "loctypes"),
            new GamevalEntry(28949, "HIDEY_CRATE_ELITE", "STASH (elite)", "loctypes"),
            new GamevalEntry(28950, "HIDEY_UNBUILT_BUSH_MASTER", "Inconspicuous bush (master)", "loctypes"),
            new GamevalEntry(28951, "HIDEY_BUSH_MASTER", "STASH (master)", "loctypes"),
            new GamevalEntry(28952, "HIDEY_UNBUILT_HOLE_MASTER", "Inconspicuous hole (master)", "loctypes"),
            new GamevalEntry(28953, "HIDEY_HOLE_MASTER", "STASH (master)", "loctypes"),
            new GamevalEntry(28954, "HIDEY_UNBUILT_ROCK_MASTER", "Inconspicuous rocks (master)", "loctypes"),
            new GamevalEntry(28955, "HIDEY_ROCK_MASTER", "STASH (master)", "loctypes"),
            new GamevalEntry(28956, "HIDEY_UNBUILT_CRATE_MASTER", "Inconspicuous crate (master)", "loctypes"),
            new GamevalEntry(28957, "HIDEY_CRATE_MASTER", "STASH (master)", "loctypes"),
            new GamevalEntry(28958, "HH_EASY001", "hh_easy001", "loctypes"),
            new GamevalEntry(28959, "HH_EASY002", "hh_easy002", "loctypes"),
            new GamevalEntry(28960, "HH_EASY003", "hh_easy003", "loctypes"),
            new GamevalEntry(28961, "HH_EASY004", "hh_easy004", "loctypes"),
            new GamevalEntry(28962, "HH_EASY005", "hh_easy005", "loctypes"),
            new GamevalEntry(28963, "HH_EASY006", "hh_easy006", "loctypes"),
            new GamevalEntry(28964, "HH_EASY007", "hh_easy007", "loctypes"),
            new GamevalEntry(28965, "HH_EASY008", "hh_easy008", "loctypes"),
            new GamevalEntry(28966, "HH_EASY009", "hh_easy009", "loctypes"),
            new GamevalEntry(28967, "HH_EASY010", "hh_easy010", "loctypes"),
            new GamevalEntry(28968, "HH_EASY011", "hh_easy011", "loctypes"),
            new GamevalEntry(28969, "HH_EASY012", "hh_easy012", "loctypes"),
            new GamevalEntry(28970, "HH_EASY013", "hh_easy013", "loctypes"),
            new GamevalEntry(28971, "HH_EASY014", "hh_easy014", "loctypes"),
            new GamevalEntry(28972, "HH_EASY015", "hh_easy015", "loctypes"),
            new GamevalEntry(28973, "HH_EASY016", "hh_easy016", "loctypes"),
            new GamevalEntry(28974, "HH_EASY018", "hh_easy018", "loctypes"),
            new GamevalEntry(28975, "HH_EASY019", "hh_easy019", "loctypes"),
            new GamevalEntry(28976, "HH_EASY020", "hh_easy020", "loctypes"),
            new GamevalEntry(28977, "HH_EASY021", "hh_easy021", "loctypes"),
            new GamevalEntry(28978, "HH_EASY022", "hh_easy022", "loctypes"),
            new GamevalEntry(28979, "HH_EASY024", "hh_easy024", "loctypes"),
            new GamevalEntry(28980, "HH_EASY025", "hh_easy025", "loctypes"),
            new GamevalEntry(28981, "HH_EASY026", "hh_easy026", "loctypes"),
            new GamevalEntry(28982, "HH_EASY027", "hh_easy027", "loctypes"),
            new GamevalEntry(28983, "HH_EASY_EXP1", "hh_easy_exp1", "loctypes"),
            new GamevalEntry(28984, "HH_EASY_EXP2", "hh_easy_exp2", "loctypes"),
            new GamevalEntry(28985, "HH_EASY_EXP3", "hh_easy_exp3", "loctypes"),
            new GamevalEntry(28986, "HH_EASY_EXP4", "hh_easy_exp4", "loctypes"),
            new GamevalEntry(28987, "HH_MEDIUM001", "hh_medium001", "loctypes"),
            new GamevalEntry(28988, "HH_MEDIUM002", "hh_medium002", "loctypes"),
            new GamevalEntry(28989, "HH_MEDIUM003", "hh_medium003", "loctypes"),
            new GamevalEntry(28990, "HH_MEDIUM004", "hh_medium004", "loctypes"),
            new GamevalEntry(28991, "HH_MEDIUM005", "hh_medium005", "loctypes"),
            new GamevalEntry(28992, "HH_MEDIUM006", "hh_medium006", "loctypes"),
            new GamevalEntry(28993, "HH_MEDIUM007", "hh_medium007", "loctypes"),
            new GamevalEntry(28994, "HH_MEDIUM008", "hh_medium008", "loctypes"),
            new GamevalEntry(28995, "HH_MEDIUM009", "hh_medium009", "loctypes"),
            new GamevalEntry(28996, "HH_MEDIUM010", "hh_medium010", "loctypes"),
            new GamevalEntry(28997, "HH_MEDIUM011", "hh_medium011", "loctypes"),
            new GamevalEntry(28998, "HH_MEDIUM012", "hh_medium012", "loctypes"),
            new GamevalEntry(28999, "HH_MEDIUM013", "hh_medium013", "loctypes"),
            new GamevalEntry(29000, "HH_MEDIUM_EXP1", "hh_medium_exp1", "loctypes"),
            new GamevalEntry(29001, "HH_MEDIUM_EXP2", "hh_medium_exp2", "loctypes"),
            new GamevalEntry(29002, "HH_MEDIUM_EXP3", "hh_medium_exp3", "loctypes"),
            new GamevalEntry(29003, "HH_MEDIUM_EXP4", "hh_medium_exp4", "loctypes"),
            new GamevalEntry(29004, "HH_MEDIUM_EXP5", "hh_medium_exp5", "loctypes"),
            new GamevalEntry(29005, "HH_MEDIUM_EXP6", "hh_medium_exp6", "loctypes"),
            new GamevalEntry(29006, "HH_MEDIUM_EXP7", "hh_medium_exp7", "loctypes"),
            new GamevalEntry(29007, "HH_MEDIUM_EXP8", "hh_medium_exp8", "loctypes"),
            new GamevalEntry(29008, "HH_MEDIUM_EXP9", "hh_medium_exp9", "loctypes"),
            new GamevalEntry(29009, "HH_HARD001", "hh_hard001", "loctypes"),
            new GamevalEntry(29010, "HH_HARD002", "hh_hard002", "loctypes"),
            new GamevalEntry(29011, "HH_HARD003", "hh_hard003", "loctypes"),
            new GamevalEntry(29012, "HH_HARD005", "hh_hard005", "loctypes"),
            new GamevalEntry(29013, "HH_HARD006", "hh_hard006", "loctypes"),
            new GamevalEntry(29014, "HH_HARD007", "hh_hard007", "loctypes"),
            new GamevalEntry(29015, "HH_HARD008", "hh_hard008", "loctypes"),
            new GamevalEntry(29016, "HH_HARD009", "hh_hard009", "loctypes"),
            new GamevalEntry(29017, "HH_HARD010", "hh_hard010", "loctypes"),
            new GamevalEntry(29018, "HH_HARD_EXP1", "hh_hard_exp1", "loctypes"),
            new GamevalEntry(29019, "HH_HARD_EXP2", "hh_hard_exp2", "loctypes"),
            new GamevalEntry(29020, "HH_HARD_EXP3", "hh_hard_exp3", "loctypes"),
            new GamevalEntry(29021, "HH_HARD_EXP4", "hh_hard_exp4", "loctypes"),
            new GamevalEntry(29022, "HH_HARD_EXP5", "hh_hard_exp5", "loctypes"),
            new GamevalEntry(29023, "HH_HARD_EXP6", "hh_hard_exp6", "loctypes"),
            new GamevalEntry(29024, "HH_ELITE_EXP1", "hh_elite_exp1", "loctypes"),
            new GamevalEntry(29025, "HH_ELITE_EXP2", "hh_elite_exp2", "loctypes"),
            new GamevalEntry(29026, "HH_ELITE_EXP3", "hh_elite_exp3", "loctypes"),
            new GamevalEntry(29027, "HH_ELITE_EXP4", "hh_elite_exp4", "loctypes"),
            new GamevalEntry(29028, "HH_ELITE_EXP5", "hh_elite_exp5", "loctypes"),
            new GamevalEntry(29029, "HH_ELITE_EXP6", "hh_elite_exp6", "loctypes"),
            new GamevalEntry(29030, "HH_ELITE_EXP7", "hh_elite_exp7", "loctypes"),
            new GamevalEntry(29031, "HH_ELITE_EXP8", "hh_elite_exp8", "loctypes"),
            new GamevalEntry(29032, "HH_ELITE_EXP9", "hh_elite_exp9", "loctypes"),
            new GamevalEntry(29033, "HH_ELITE_EXP10", "hh_elite_exp10", "loctypes"),
            new GamevalEntry(29034, "HH_ELITE_EXP11", "hh_elite_exp11", "loctypes"),
            new GamevalEntry(29035, "HH_ELITE_EXP12", "hh_elite_exp12", "loctypes"),
            new GamevalEntry(29036, "HH_ELITE_EXP13", "hh_elite_exp13", "loctypes"),
            new GamevalEntry(29037, "HH_ELITE_EXP14", "hh_elite_exp14", "loctypes"),
            new GamevalEntry(29038, "HH_ELITE_EXP15", "hh_elite_exp15", "loctypes"),
            new GamevalEntry(29039, "HH_ELITE_EXP16", "hh_elite_exp16", "loctypes"),
            new GamevalEntry(29040, "HH_MASTER001", "hh_master001", "loctypes"),
            new GamevalEntry(29041, "HH_MASTER002", "hh_master002", "loctypes"),
            new GamevalEntry(29042, "HH_MASTER003", "hh_master003", "loctypes"),
            new GamevalEntry(29043, "HH_MASTER004", "hh_master004", "loctypes"),
            new GamevalEntry(29044, "HH_MASTER005", "hh_master005", "loctypes"),
            new GamevalEntry(29045, "HH_MASTER006", "hh_master006", "loctypes"),
            new GamevalEntry(29046, "HH_MASTER007", "hh_master007", "loctypes"),
            new GamevalEntry(29047, "HH_MASTER008", "hh_master008", "loctypes"),
            new GamevalEntry(29048, "HH_MASTER009", "hh_master009", "loctypes"),
            new GamevalEntry(29049, "HH_MASTER010", "hh_master010", "loctypes"),
            new GamevalEntry(29050, "HH_MASTER011", "hh_master011", "loctypes"),
            new GamevalEntry(29051, "HH_MASTER012", "hh_master012", "loctypes"),
            new GamevalEntry(29052, "HH_MASTER013", "hh_master013", "loctypes"),
            new GamevalEntry(29053, "HH_MASTER014", "hh_master014", "loctypes"),
            new GamevalEntry(29054, "HH_MASTER015", "hh_master015", "loctypes"),
            new GamevalEntry(29055, "HH_MASTER016", "hh_master016", "loctypes"),
            new GamevalEntry(29056, "HH_MASTER017", "hh_master017", "loctypes"),
            new GamevalEntry(29057, "HH_MASTER018", "hh_master018", "loctypes"),
            new GamevalEntry(29058, "HH_MASTER019", "hh_master019", "loctypes"),
            new GamevalEntry(29059, "HH_MASTER020", "hh_master020", "loctypes"),
            new GamevalEntry(29060, "HH_MASTER021", "hh_master021", "loctypes"),
            new GamevalEntry(29061, "FOSSIL_WYVERN_TASK_STAIRS_1A", "Stairs", "loctypes"),
            new GamevalEntry(29062, "BR_LADDER", "Ladder", "loctypes"),
            new GamevalEntry(29063, "BR_REWARD_CHEST", "Reward chest", "loctypes"),
            new GamevalEntry(29064, "BR_SCOREBOARD", "Scoreboard", "loctypes"),
            new GamevalEntry(29065, "BR_PLINTH", "br_plinth", "loctypes"),
            new GamevalEntry(29066, "BR_DOOR_LOCKED", "Door", "loctypes"),
            new GamevalEntry(29067, "BR_DOOR_FORFEIT", "Door", "loctypes"),
            new GamevalEntry(29068, "BR_LOADOUT_CUSTOMISER", "br_loadout_customiser", "loctypes"),
            new GamevalEntry(29069, "BR_LOOT_CHEST_CLOSED", "Chest", "loctypes"),
            new GamevalEntry(29070, "BR_LOOT_CHEST_OPEN", "Chest", "loctypes"),
            new GamevalEntry(29071, "BR_LOOT_CHEST_LOOTED_CLOSED", "Chest", "loctypes"),
            new GamevalEntry(29072, "BR_LOOT_CHEST_LOOTED_OPEN", "Chest", "loctypes"),
            new GamevalEntry(29073, "BR_LOOT_DRAWER_CLOSED", "Drawers", "loctypes"),
            new GamevalEntry(29074, "BR_LOOT_DRAWER_OPEN", "Drawers", "loctypes"),
            new GamevalEntry(29075, "BR_LOOT_DRAWER_LOOTED_CLOSED", "Drawers", "loctypes"),
            new GamevalEntry(29076, "BR_LOOT_DRAWER_LOOTED_OPEN", "Drawers", "loctypes"),
            new GamevalEntry(29077, "BR_LOOT_CUPBOARD_CLOSED", "Cupboard", "loctypes"),
            new GamevalEntry(29078, "BR_LOOT_CUPBOARD_OPEN", "Cupboard", "loctypes"),
            new GamevalEntry(29079, "BR_LOOT_CUPBOARD_LOOTED_CLOSED", "Cupboard", "loctypes"),
            new GamevalEntry(29080, "BR_LOOT_CUPBOARD_LOOTED_OPEN", "Cupboard", "loctypes"),
            new GamevalEntry(29081, "BR_LOOTCRATE", "Crate", "loctypes"),
            new GamevalEntry(29082, "BR_BOAT_FORFEIT", "Rowboat", "loctypes"),
            new GamevalEntry(29083, "BR_STEPPING_STONE", "Stepping stone", "loctypes"),
            new GamevalEntry(29084, "BR_CAMPFIRE", "br_campfire", "loctypes"),
            new GamevalEntry(29085, "BR_CAMPFIRE_FIRE", "Campfire", "loctypes"),
            new GamevalEntry(29086, "JOGRE_STEPS_MODEL", "jogre_steps_model", "loctypes"),
            new GamevalEntry(29087, "BR_COFFER", "Coffer", "loctypes"),
            new GamevalEntry(29088, "WCGUILD_SHRINE", "Shrine", "loctypes"),
            new GamevalEntry(29089, "BR_LADDER_TOP", "Ladder", "loctypes"),
            new GamevalEntry(29090, "AIRTEMPLE_RUINED_NEW", "Mysterious ruins", "loctypes"),
            new GamevalEntry(29091, "POH_BOARD_RIMMINGTON", "House Advertisement", "loctypes"),
            new GamevalEntry(29092, "BR_WATCHTOWER_LADDER", "Ladder", "loctypes"),
            new GamevalEntry(29093, "BR_WATCHTOWER_LADDER_TOP", "br_watchtower_ladder_top", "loctypes"),
            new GamevalEntry(29094, "MINDTEMPLE_RUINED_OLD", "Mysterious ruins", "loctypes"),
            new GamevalEntry(29095, "MINDTEMPLE_RUINED_NEW", "Mysterious ruins", "loctypes"),
            new GamevalEntry(29096, "WATERTEMPLE_RUINED_OLD", "Mysterious ruins", "loctypes"),
            new GamevalEntry(29097, "WATERTEMPLE_RUINED_NEW", "Mysterious ruins", "loctypes"),
            new GamevalEntry(29098, "EARTHTEMPLE_RUINED_OLD", "Mysterious ruins", "loctypes"),
            new GamevalEntry(29099, "EARTHTEMPLE_RUINED_NEW", "Mysterious ruins", "loctypes"),
            new GamevalEntry(29100, "GNOME_WELL", "Well", "loctypes"),
            new GamevalEntry(29101, "GNOME_WATERBARREL", "Barrel", "loctypes"),
            new GamevalEntry(29102, "BR_CROSSING_ROCK", "Rock", "loctypes"),
            new GamevalEntry(29103, "DIARY_GUILD_DEPOSIT_BOX", "Bank Deposit Box", "loctypes"),
            new GamevalEntry(29104, "SWAN_BANK_DEPOSIT_BOX", "Bank Deposit Box", "loctypes"),
            new GamevalEntry(29105, "BURGH_BANK_DEPOSIT_BOX", "Bank deposit box", "loctypes"),
            new GamevalEntry(29106, "AHOY_BANK_DEPOSIT_BOX", "Bank deposit box", "loctypes"),
            new GamevalEntry(29107, "MM_INACTIVE_DEPOSIT_BOX", "Pot", "loctypes"),
            new GamevalEntry(29108, "MM_ACTIVE_DEPOSIT_BOX", "Bank Deposit Pot", "loctypes"),
            new GamevalEntry(29109, "MM_DEPOSIT_BOX", "mm_deposit_box", "loctypes"),
            new GamevalEntry(29110, "BR_LOBBY_RAIL", "br_lobby_rail", "loctypes"),
            new GamevalEntry(29111, "POH_INVISIBLE_GARDEN_BENCH_TEAK_LEFT", "T Teak bench", "loctypes"),
            new GamevalEntry(29112, "POH_INVISIBLE_GARDEN_BENCH_TEAK_RIGHT", "T Teak bench", "loctypes"),
            new GamevalEntry(29113, "POH_INVISIBLE_GARDEN_BENCH_GNOME_LEFT", "T Gnome bench", "loctypes"),
            new GamevalEntry(29114, "POH_INVISIBLE_GARDEN_BENCH_GNOME_RIGHT", "T Gnome bench", "loctypes"),
            new GamevalEntry(29115, "POH_INVISIBLE_GARDEN_BENCH_MARBLE_LEFT", "T Marble bench", "loctypes"),
            new GamevalEntry(29116, "POH_INVISIBLE_GARDEN_BENCH_MARBLE_RIGHT", "T Marble bench", "loctypes"),
            new GamevalEntry(29117, "POH_INVISIBLE_GARDEN_BENCH_OBSIDIAN_LEFT", "T Obsidian bench", "loctypes"),
            new GamevalEntry(29118, "POH_INVISIBLE_GARDEN_BENCH_OBSIDIAN_RIGHT", "T Obsidian bench", "loctypes"),
            new GamevalEntry(29119, "POH_GARDEN_8", "Tip jar space", "loctypes"),
            new GamevalEntry(29120, "POH_SUPERIOR_GARDEN_HOTSPOT_TREERING", "Teleport space", "loctypes"),
            new GamevalEntry(29121, "POH_SUPERIOR_GARDEN_HOTSPOT_TOPIARY", "Topiary space", "loctypes"),
            new GamevalEntry(29122, "POH_SUPERIOR_GARDEN_HOTSPOT_POOL", "Pool space", "loctypes"),
            new GamevalEntry(29123, "POH_SUPERIOR_GARDEN_HOTSPOT_THEME_OUTERCORNER", "Theme space", "loctypes"),
            new GamevalEntry(29124, "POH_SUPERIOR_GARDEN_HOTSPOT_THEME_INNERCORNER", "Theme space", "loctypes"),
            new GamevalEntry(29125, "POH_SUPERIOR_GARDEN_HOTSPOT_THEME_EDGE", "Theme space", "loctypes"),
            new GamevalEntry(29126, "POH_SUPERIOR_GARDEN_HOTSPOT_THEME_PATH_1", "Theme space", "loctypes"),
            new GamevalEntry(29127, "POH_SUPERIOR_GARDEN_HOTSPOT_THEME_PATH_2", "Theme space", "loctypes"),
            new GamevalEntry(29128, "POH_SUPERIOR_GARDEN_HOTSPOT_THEME_PATH_3", "Theme space", "loctypes"),
            new GamevalEntry(29129, "POH_SUPERIOR_GARDEN_HOTSPOT_THEME_PATHCORNER", "Theme space", "loctypes"),
            new GamevalEntry(29130, "POH_SUPERIOR_GARDEN_HOTSPOT_THEME_FEATURE", "Theme space", "loctypes"),
            new GamevalEntry(29131, "POH_SUPERIOR_GARDEN_HOTSPOT_FENCE_MIDDLE", "Fence space", "loctypes"),
            new GamevalEntry(29132, "POH_SUPERIOR_GARDEN_HOTSPOT_FENCE_POST", "Fence space", "loctypes"),
            new GamevalEntry(29133, "POH_SUPERIOR_GARDEN_HOTSPOT_FENCE_POST_M", "Fence space", "loctypes"),
            new GamevalEntry(29134, "WINT_FLOOR_C", "wint_floor_c", "loctypes"),
            new GamevalEntry(29135, "WINT_FLOOR_D", "wint_floor_d", "loctypes"),
            new GamevalEntry(29136, "POH_SUPERIOR_GARDEN_HOTSPOT_SEATING_A_LEFT", "Seating space", "loctypes"),
            new GamevalEntry(29137, "POH_SUPERIOR_GARDEN_HOTSPOT_SEATING_A_RIGHT", "Seating space", "loctypes"),
            new GamevalEntry(29138, "POH_SUPERIOR_GARDEN_HOTSPOT_SEATING_B_LEFT", "Seating space", "loctypes"),
            new GamevalEntry(29139, "POH_SUPERIOR_GARDEN_HOTSPOT_SEATING_B_RIGHT", "Seating space", "loctypes"),
            new GamevalEntry(29140, "POH_ACHIEVEMENT_HOTSPOT_ALTAR", "Altar space", "loctypes"),
            new GamevalEntry(29141, "POH_ACHIEVEMENT_HOTSPOT_LOG", "Adventure log space", "loctypes"),
            new GamevalEntry(29142, "POH_ACHIEVEMENT_HOTSPOT_JEWELLERYBOX", "Jewellery box space", "loctypes"),
            new GamevalEntry(29143, "POH_ACHIEVEMENT_HOTSPOT_LAIR", "Boss lair space", "loctypes"),
            new GamevalEntry(29144, "POH_ACHIEVEMENT_HOTSPOT_DISPLAY", "Display space", "loctypes"),
            new GamevalEntry(29145, "POH_ACHIEVEMENT_HOTSPOT_QUESTLIST", "Quest list space", "loctypes"),
            new GamevalEntry(29146, "POH_TIPJAR", "Tip jar", "loctypes"),
            new GamevalEntry(29147, "POH_ALTAR_ANCIENT", "Ancient Altar", "loctypes"),
            new GamevalEntry(29148, "POH_ALTAR_LUNAR", "Lunar Altar", "loctypes"),
            new GamevalEntry(29149, "POH_ALTAR_DARK", "Dark Altar", "loctypes"),
            new GamevalEntry(29150, "POH_ALTAR_OCCULT", "poh_altar_occult", "loctypes"),
            new GamevalEntry(29151, "POH_ADVENTURE_LOG_1", "Mahogany Adventure Log", "loctypes"),
            new GamevalEntry(29152, "POH_ADVENTURE_LOG_2", "Gilded Adventure Log", "loctypes"),
            new GamevalEntry(29153, "POH_ADVENTURE_LOG_3", "Marble adventure log", "loctypes"),
            new GamevalEntry(29154, "POH_JEWELLERY_BOX_1", "poh_jewellery_box_1", "loctypes"),
            new GamevalEntry(29155, "POH_JEWELLERY_BOX_2", "poh_jewellery_box_2", "loctypes"),
            new GamevalEntry(29156, "POH_JEWELLERY_BOX_3", "poh_jewellery_box_3", "loctypes"),
            new GamevalEntry(29157, "POH_DISPLAY_BLANK", "Boss lair display", "loctypes"),
            new GamevalEntry(29158, "POH_DISPLAY_KRAKEN", "Kraken display", "loctypes"),
            new GamevalEntry(29159, "POH_DISPLAY_ZULRAH", "Zulrah display", "loctypes"),
            new GamevalEntry(29160, "POH_DISPLAY_KQ", "Kalphite Queen display", "loctypes"),
            new GamevalEntry(29161, "POH_DISPLAY_CERBERUS", "Cerberus display", "loctypes"),
            new GamevalEntry(29162, "POH_DISPLAY_SIRE", "Abyssal Sire display", "loctypes"),
            new GamevalEntry(29163, "POH_DISPLAY_SKOTIZO", "Skotizo display", "loctypes"),
            new GamevalEntry(29164, "POH_MOUNTED_EMBLEM", "Mounted Emblem", "loctypes"),
            new GamevalEntry(29165, "POH_MOUNTED_COINS", "Mounted Coins", "loctypes"),
            new GamevalEntry(29166, "POH_MOUNTED_CAPESTAND_BLANK", "Cape hanger", "loctypes"),
            new GamevalEntry(29167, "POH_MOUNTED_DIARY_CAPE", "Mounted Achievement Diary Cape", "loctypes"),
            new GamevalEntry(29168, "POH_MOUNTED_DIARY_CAPE_TRIM", "Mounted Achievement Diary Cape", "loctypes"),
            new GamevalEntry(29169, "POH_MOUNTED_FIRE_CAPE", "Mounted Fire Cape", "loctypes"),
            new GamevalEntry(29170, "POH_MOUNTED_MAX_CAPE", "Mounted Max Cape", "loctypes"),
            new GamevalEntry(29171, "POH_MOUNTED_MAX_CAPE_FIRE", "Mounted Max Cape", "loctypes"),
            new GamevalEntry(29172, "POH_MOUNTED_MAX_CAPE_SARADOMIN", "Mounted Max Cape", "loctypes"),
            new GamevalEntry(29173, "POH_MOUNTED_MAX_CAPE_ZAMORAK", "Mounted Max Cape", "loctypes"),
            new GamevalEntry(29174, "POH_MOUNTED_MAX_CAPE_GUTHIX", "Mounted Max Cape", "loctypes"),
            new GamevalEntry(29175, "POH_MOUNTED_MAX_CAPE_AVA", "Mounted Max Cape", "loctypes"),
            new GamevalEntry(29176, "POH_MOUNTED_MUSIC_CAPE", "Mounted Music Cape", "loctypes"),
            new GamevalEntry(29177, "POH_MOUNTED_MUSIC_CAPE_TRIM", "Mounted Music Cape", "loctypes"),
            new GamevalEntry(29178, "POH_MOUNTED_QUEST_CAPE", "Mounted Quest Cape", "loctypes"),
            new GamevalEntry(29179, "POH_MOUNTED_QUEST_CAPE_TRIM", "Mounted Quest Cape", "loctypes"),
            new GamevalEntry(29180, "POH_MOUNTED_AGILITY_CAPE", "Mounted Agility Cape", "loctypes"),
            new GamevalEntry(29181, "POH_MOUNTED_AGILITY_CAPE_TRIM", "Mounted Agility Cape (t)", "loctypes"),
            new GamevalEntry(29182, "POH_MOUNTED_ATTACK_CAPE", "Mounted Attack Cape", "loctypes"),
            new GamevalEntry(29183, "POH_MOUNTED_ATTACK_CAPE_TRIM", "Mounted Attack Cape (t)", "loctypes"),
            new GamevalEntry(29184, "POH_MOUNTED_CONSTRUCTION_CAPE", "Mounted Construction Cape", "loctypes"),
            new GamevalEntry(29185, "POH_MOUNTED_CONSTRUCTION_CAPE_TRIM", "Mounted Construction Cape (t)", "loctypes"),
            new GamevalEntry(29186, "POH_MOUNTED_COOKING_CAPE", "Mounted Cooking Cape", "loctypes"),
            new GamevalEntry(29187, "POH_MOUNTED_COOKING_CAPE_TRIM", "Mounted Cooking Cape (t)", "loctypes"),
            new GamevalEntry(29188, "POH_MOUNTED_CRAFTING_CAPE", "Mounted Crafting Cape", "loctypes"),
            new GamevalEntry(29189, "POH_MOUNTED_CRAFTING_CAPE_TRIM", "Mounted Crafting Cape (t)", "loctypes"),
            new GamevalEntry(29190, "POH_MOUNTED_DEFENCE_CAPE", "Mounted Defence Cape", "loctypes"),
            new GamevalEntry(29191, "POH_MOUNTED_DEFENCE_CAPE_TRIM", "Mounted Defence Cape (t)", "loctypes"),
            new GamevalEntry(29192, "POH_MOUNTED_FARMING_CAPE", "Mounted Farming Cape", "loctypes"),
            new GamevalEntry(29193, "POH_MOUNTED_FARMING_CAPE_TRIM", "Mounted Farming Cape (t)", "loctypes"),
            new GamevalEntry(29194, "POH_MOUNTED_FIREMAKING_CAPE", "Mounted Firemaking Cape", "loctypes"),
            new GamevalEntry(29195, "POH_MOUNTED_FIREMAKING_CAPE_TRIM", "Mounted Firemaking Cape (t)", "loctypes"),
            new GamevalEntry(29196, "POH_MOUNTED_FISHING_CAPE", "Mounted Fishing Cape", "loctypes"),
            new GamevalEntry(29197, "POH_MOUNTED_FISHING_CAPE_TRIM", "Mounted Fishing Cape (t)", "loctypes"),
            new GamevalEntry(29198, "POH_MOUNTED_FLETCHING_CAPE", "Mounted Fletching Cape", "loctypes"),
            new GamevalEntry(29199, "POH_MOUNTED_FLETCHING_CAPE_TRIM", "Mounted Fletching Cape (t)", "loctypes"),
            new GamevalEntry(29200, "POH_MOUNTED_HERBLORE_CAPE", "Mounted Herblore Cape", "loctypes"),
            new GamevalEntry(29201, "POH_MOUNTED_HERBLORE_CAPE_TRIM", "Mounted Herblore Cape (t)", "loctypes"),
            new GamevalEntry(29202, "POH_MOUNTED_HITPOINTS_CAPE", "Mounted Hitpoints Cape", "loctypes"),
            new GamevalEntry(29203, "POH_MOUNTED_HITPOINTS_CAPE_TRIM", "Mounted Hitpoints Cape (t)", "loctypes"),
            new GamevalEntry(29204, "POH_MOUNTED_HUNTING_CAPE", "Mounted Hunting Cape", "loctypes"),
            new GamevalEntry(29205, "POH_MOUNTED_HUNTING_CAPE_TRIM", "Mounted Hunting Cape (t)", "loctypes"),
            new GamevalEntry(29206, "POH_MOUNTED_MAGIC_CAPE", "Mounted Magic Cape", "loctypes"),
            new GamevalEntry(29207, "POH_MOUNTED_MAGIC_CAPE_TRIM", "Mounted Magic Cape (t)", "loctypes"),
            new GamevalEntry(29208, "POH_MOUNTED_MINING_CAPE", "Mounted Mining Cape", "loctypes"),
            new GamevalEntry(29209, "POH_MOUNTED_MINING_CAPE_TRIM", "Mounted Mining Cape (t)", "loctypes"),
            new GamevalEntry(29210, "POH_MOUNTED_PRAYER_CAPE", "Mounted Prayer Cape", "loctypes"),
            new GamevalEntry(29211, "POH_MOUNTED_PRAYER_CAPE_TRIM", "Mounted Prayer Cape (t)", "loctypes"),
            new GamevalEntry(29212, "POH_MOUNTED_RANGED_CAPE", "Mounted Ranged Cape", "loctypes"),
            new GamevalEntry(29213, "POH_MOUNTED_RANGED_CAPE_TRIM", "Mounted Ranged Cape (t)", "loctypes"),
            new GamevalEntry(29214, "POH_MOUNTED_RUNECRAFTING_CAPE", "Mounted Runecrafting Cape", "loctypes"),
            new GamevalEntry(29215, "POH_MOUNTED_RUNECRAFTING_CAPE_TRIM", "Mounted Runecrafting Cape (t)", "loctypes"),
            new GamevalEntry(29216, "POH_MOUNTED_SLAYER_CAPE", "Mounted Slayer Cape", "loctypes"),
            new GamevalEntry(29217, "POH_MOUNTED_SLAYER_CAPE_TRIM", "Mounted Slayer Cape (t)", "loctypes"),
            new GamevalEntry(29218, "POH_MOUNTED_SMITHING_CAPE", "Mounted Smithing Cape", "loctypes"),
            new GamevalEntry(29219, "POH_MOUNTED_SMITHING_CAPE_TRIM", "Mounted Smithing Cape (t)", "loctypes"),
            new GamevalEntry(29220, "POH_MOUNTED_STRENGTH_CAPE", "Mounted Strength Cape", "loctypes"),
            new GamevalEntry(29221, "POH_MOUNTED_STRENGTH_CAPE_TRIM", "Mounted Strength Cape (t)", "loctypes"),
            new GamevalEntry(29222, "POH_MOUNTED_THIEVING_CAPE", "Mounted Thieving Cape", "loctypes"),
            new GamevalEntry(29223, "POH_MOUNTED_THIEVING_CAPE_TRIM", "Mounted Thieving Cape (t)", "loctypes"),
            new GamevalEntry(29224, "POH_MOUNTED_WOODCUTTING_CAPE", "Mounted Woodcutting Cape", "loctypes"),
            new GamevalEntry(29225, "POH_MOUNTED_WOODCUTTING_CAPE_TRIM", "Mounted Woodcutting Cape (t)", "loctypes"),
            new GamevalEntry(29226, "POH_QUEST_LIST", "Quest List", "loctypes"),
            new GamevalEntry(29227, "POH_SPIRIT_TREE", "Gnome Stronghold", "loctypes"),
            new GamevalEntry(29228, "POH_FAIRY_RING", "Favourite 2", "loctypes"),
            new GamevalEntry(29229, "POH_SPIRIT_RING", "Spiritual Fairy Tree", "loctypes"),
            new GamevalEntry(29230, "POH_TOPIARY_NULL", "Topiary bush", "loctypes"),
            new GamevalEntry(29231, "POH_TOPIARY_KRAKEN", "Kraken Topiary", "loctypes"),
            new GamevalEntry(29232, "POH_TOPIARY_ZULRAH", "Zulrah Topiary", "loctypes"),
            new GamevalEntry(29233, "POH_TOPIARY_KQ", "Kalphite Queen Topiary", "loctypes"),
            new GamevalEntry(29234, "POH_TOPIARY_CERB", "Cerberus Topiary", "loctypes"),
            new GamevalEntry(29235, "POH_TOPIARY_SIRE", "Abyssal Sire Topiary", "loctypes"),
            new GamevalEntry(29236, "POH_TOPIARY_SKOTIZO", "Skotizo Topiary", "loctypes"),
            new GamevalEntry(29237, "POH_POOL_RESTORATION", "Pool of Restoration", "loctypes"),
            new GamevalEntry(29238, "POH_POOL_REVITALISATION", "Pool of Revitalisation", "loctypes"),
            new GamevalEntry(29239, "POH_POOL_REJUVENATION", "Pool of Rejuvenation", "loctypes"),
            new GamevalEntry(29240, "POH_POOL_RECOVERY", "Fancy pool of Rejuvenation", "loctypes"),
            new GamevalEntry(29241, "POH_POOL_REGENERATION", "Ornate pool of Rejuvenation", "loctypes"),
            new GamevalEntry(29242, "POH_THEME_ZEN_PATH", "Zen garden", "loctypes"),
            new GamevalEntry(29243, "POH_THEME_ZEN_PATH_CORNER", "Zen garden", "loctypes"),
            new GamevalEntry(29244, "POH_THEME_ZEN_EDGE", "Zen garden", "loctypes"),
            new GamevalEntry(29245, "POH_THEME_ZEN_INNER_CORNER", "Zen garden", "loctypes"),
            new GamevalEntry(29246, "POH_THEME_ZEN_OUTER_CORNER", "Zen garden", "loctypes"),
            new GamevalEntry(29247, "POH_THEME_ZEN_HERO", "Zen theme", "loctypes"),
            new GamevalEntry(29248, "POH_THEME_ZANARIS_PATH", "Otherworldly garden", "loctypes"),
            new GamevalEntry(29249, "POH_THEME_ZANARIS_PATH_CORNER", "Otherworldly garden", "loctypes"),
        };
    }

    static Optional<GamevalEntry> byId(int id) {
        for (GamevalEntry entry : entries()) {
            if (entry.id() == id) return Optional.of(entry);
        }
        return Optional.empty();
    }

}
