package net.titan.gamevals.internal;

import java.util.Optional;

import net.titan.gamevals.GamevalEntry;
import net.titan.gamevals.QuestEntry;

final class ObjectIDEntries_96 {
    private ObjectIDEntries_96() {}

    static GamevalEntry[] entries() {
        return new GamevalEntry[] {
            new GamevalEntry(49219, "DT2_SCAR_DEBRIS_OP", "Debris", "loctypes"),
            new GamevalEntry(49220, "DT2_SCAR_DEBRIS_NOOP", "Debris", "loctypes"),
            new GamevalEntry(49221, "DT2_SCAR_TENT_OP", "Tent", "loctypes"),
            new GamevalEntry(49222, "DT2_SCAR_TENT_NOOP", "Tent", "loctypes"),
            new GamevalEntry(49223, "DT2_SCAR_WALLKIT01", "dt2_scar_wallkit01", "loctypes"),
            new GamevalEntry(49224, "DT2_SCAR_WALLKIT01_SHORT", "dt2_scar_wallkit01_short", "loctypes"),
            new GamevalEntry(49225, "DT2_SCAR_WALLTOP_SHORT_01", "dt2_scar_walltop_short_01", "loctypes"),
            new GamevalEntry(49226, "DT2_SCAR_WALLTOP_SHORT_02", "dt2_scar_walltop_short_02", "loctypes"),
            new GamevalEntry(49227, "DT2_SCAR_WALLTOP_SHORT_03", "dt2_scar_walltop_short_03", "loctypes"),
            new GamevalEntry(49228, "DT2_SCAR_WALLKIT01_LIGHTNING", "dt2_scar_wallkit01_lightning", "loctypes"),
            new GamevalEntry(49229, "DT2_SCAR_WALLKIT01_ALCOVE_LEFT", "dt2_scar_wallkit01_alcove_left", "loctypes"),
            new GamevalEntry(49230, "DT2_SCAR_WALLKIT01_ALCOVE_MID", "dt2_scar_wallkit01_alcove_mid", "loctypes"),
            new GamevalEntry(49231, "DT2_SCAR_WALLKIT01_ALCOVE_RIGHT", "dt2_scar_wallkit01_alcove_right", "loctypes"),
            new GamevalEntry(49232, "DT2_SCAR_WALLTOP", "dt2_scar_walltop", "loctypes"),
            new GamevalEntry(49233, "DT2_SCAR_WALLTOP02", "dt2_scar_walltop02", "loctypes"),
            new GamevalEntry(49234, "DT2_SCAR_WALLTOP03", "dt2_scar_walltop03", "loctypes"),
            new GamevalEntry(49235, "DT2_SCAR_WALLTOP04", "dt2_scar_walltop04", "loctypes"),
            new GamevalEntry(49236, "DT2_SCAR_WALLTOP05", "dt2_scar_walltop05", "loctypes"),
            new GamevalEntry(49237, "DT2_SCAR_WALLKIT_1_2X1", "dt2_scar_wallkit_1_2x1", "loctypes"),
            new GamevalEntry(49238, "DT2_SCAR_PILLAR_BROKEN01", "Broken Pillar", "loctypes"),
            new GamevalEntry(49239, "DT2_SCAR_PILLAR_BROKEN02", "Broken Pillar", "loctypes"),
            new GamevalEntry(49240, "DT2_SCAR_PILLAR_BROKEN03", "Broken Pillar", "loctypes"),
            new GamevalEntry(49241, "DT2_SCAR_PILLAR_BROKEN04", "Broken Pillar", "loctypes"),
            new GamevalEntry(49242, "DT2_PORTALS_ABYSSAL01_DEFAULT01", "Abyssal Portal", "loctypes"),
            new GamevalEntry(49243, "DT2_PORTALS_ABYSSAL01_DEFAULT02", "Abyssal Portal", "loctypes"),
            new GamevalEntry(49244, "DT2_SCAR_BROKEN_BOAT01", "Broken Boat", "loctypes"),
            new GamevalEntry(49245, "DT2_SCAR_BROKEN_BOAT02", "Broken Boat", "loctypes"),
            new GamevalEntry(49246, "DT2_SCAR_BROKEN_BOAT03", "Broken Boat", "loctypes"),
            new GamevalEntry(49247, "DT2_SCAR_FLOOR_BRAIN01", "dt2_scar_floor_brain01", "loctypes"),
            new GamevalEntry(49248, "DT2_SCAR_FLOOR_BRAIN02", "dt2_scar_floor_brain02", "loctypes"),
            new GamevalEntry(49249, "DT2_SCAR_FLOOR_BRAIN03", "dt2_scar_floor_brain03", "loctypes"),
            new GamevalEntry(49250, "DT2_SCAR_FLOOR_BRAIN04", "dt2_scar_floor_brain04", "loctypes"),
            new GamevalEntry(49251, "DT2_SCAR_FLOOR_BRAIN05", "dt2_scar_floor_brain05", "loctypes"),
            new GamevalEntry(49252, "DT2_SCAR_FLOOR_BRAIN06", "dt2_scar_floor_brain06", "loctypes"),
            new GamevalEntry(49253, "DT2_SCAR_FLOOR_BRAIN07", "dt2_scar_floor_brain07", "loctypes"),
            new GamevalEntry(49254, "DT2_SCAR_FLOOR_BRAIN08", "dt2_scar_floor_brain08", "loctypes"),
            new GamevalEntry(49255, "DT2_SCAR_FLOOR_BRAIN09", "dt2_scar_floor_brain09", "loctypes"),
            new GamevalEntry(49256, "DT2_SCAR_FLOOR_BRAIN10", "dt2_scar_floor_brain10", "loctypes"),
            new GamevalEntry(49257, "DT2_SCAR_FLOOR_BRAIN11", "dt2_scar_floor_brain11", "loctypes"),
            new GamevalEntry(49258, "DT2_SCAR_FLOOR_BRAIN12", "dt2_scar_floor_brain12", "loctypes"),
            new GamevalEntry(49259, "DT2_SCAR_FLOOR_BRAIN13", "dt2_scar_floor_brain13", "loctypes"),
            new GamevalEntry(49260, "DT2_SCAR_FLOOR_BRAIN14", "dt2_scar_floor_brain14", "loctypes"),
            new GamevalEntry(49261, "DT2_SCAR_FLOOR_BRAIN15", "dt2_scar_floor_brain15", "loctypes"),
            new GamevalEntry(49262, "DT2_SCAR_FLOOR_BRAIN16", "dt2_scar_floor_brain16", "loctypes"),
            new GamevalEntry(49263, "DT2_SCAR_FLOOR_BRAIN17", "dt2_scar_floor_brain17", "loctypes"),
            new GamevalEntry(49264, "DT2_SCAR_FLOOR_BRAIN18", "dt2_scar_floor_brain18", "loctypes"),
            new GamevalEntry(49265, "DT2_SCAR_FLOOR_BRAIN19", "dt2_scar_floor_brain19", "loctypes"),
            new GamevalEntry(49266, "DT2_SCAR_FLOOR_BRAIN20", "dt2_scar_floor_brain20", "loctypes"),
            new GamevalEntry(49267, "DT2_SCAR_FLOOR_BRAIN21", "dt2_scar_floor_brain21", "loctypes"),
            new GamevalEntry(49268, "DT2_SCAR_FLOOR_BRAIN22", "dt2_scar_floor_brain22", "loctypes"),
            new GamevalEntry(49269, "DT2_SCAR_FLOOR_BRAIN23", "dt2_scar_floor_brain23", "loctypes"),
            new GamevalEntry(49270, "DT2_SCAR_FLOOR_BRAIN24", "dt2_scar_floor_brain24", "loctypes"),
            new GamevalEntry(49271, "DT2_SCAR_FLOOR_BRAIN25", "dt2_scar_floor_brain25", "loctypes"),
            new GamevalEntry(49272, "DT2_SCAR_FLOOR_BRAIN26", "dt2_scar_floor_brain26", "loctypes"),
            new GamevalEntry(49273, "DT2_SCAR_FLOOR_BRAIN27", "dt2_scar_floor_brain27", "loctypes"),
            new GamevalEntry(49274, "DT2_SCAR_FLOOR_BRAIN28", "dt2_scar_floor_brain28", "loctypes"),
            new GamevalEntry(49275, "DT2_SCAR_FLOOR_BRAIN29", "dt2_scar_floor_brain29", "loctypes"),
            new GamevalEntry(49276, "DT2_SCAR_FLOOR_BRAIN30", "dt2_scar_floor_brain30", "loctypes"),
            new GamevalEntry(49277, "DT2_SCAR_FLOOR_BRAIN31", "dt2_scar_floor_brain31", "loctypes"),
            new GamevalEntry(49278, "DT2_SCAR_FLOOR_BRAIN32", "dt2_scar_floor_brain32", "loctypes"),
            new GamevalEntry(49279, "DT2_SCAR_FLOOR_BRAIN33", "dt2_scar_floor_brain33", "loctypes"),
            new GamevalEntry(49280, "DT2_SCAR_FLOOR_BRAIN34", "dt2_scar_floor_brain34", "loctypes"),
            new GamevalEntry(49281, "DT2_SCAR_FLOOR_BRAIN35", "dt2_scar_floor_brain35", "loctypes"),
            new GamevalEntry(49282, "DT2_SCAR_FLOOR_BRAIN36", "dt2_scar_floor_brain36", "loctypes"),
            new GamevalEntry(49283, "DT2_SCAR_FLOOR_LIGHTNING_BRAIN01", "dt2_scar_floor_lightning_brain01", "loctypes"),
            new GamevalEntry(49284, "DT2_SCAR_FLOOR_LIGHTNING_BRAIN02", "dt2_scar_floor_lightning_brain02", "loctypes"),
            new GamevalEntry(49285, "DT2_SCAR_FLOOR_LIGHTNING_BRAIN03", "dt2_scar_floor_lightning_brain03", "loctypes"),
            new GamevalEntry(49286, "DT2_SCAR_FLOOR_LIGHTNING_BRAIN04", "dt2_scar_floor_lightning_brain04", "loctypes"),
            new GamevalEntry(49287, "DT2_SCAR_FLOOR_LIGHTNING_BRAIN05", "dt2_scar_floor_lightning_brain05", "loctypes"),
            new GamevalEntry(49288, "DT2_SCAR_FLOOR_LIGHTNING_BRAIN06", "dt2_scar_floor_lightning_brain06", "loctypes"),
            new GamevalEntry(49289, "DT2_SCAR_FLOOR_LIGHTNING_BRAIN07", "dt2_scar_floor_lightning_brain07", "loctypes"),
            new GamevalEntry(49290, "DT2_SCAR_FLOOR_LIGHTNING_BRAIN08", "dt2_scar_floor_lightning_brain08", "loctypes"),
            new GamevalEntry(49291, "DT2_SCAR_FLOOR_LIGHTNING_BRAIN09", "dt2_scar_floor_lightning_brain09", "loctypes"),
            new GamevalEntry(49292, "DT2_SCAR_FLOOR_LIGHTNING_BRAIN10", "dt2_scar_floor_lightning_brain10", "loctypes"),
            new GamevalEntry(49293, "DT2_SCAR_FLOOR_LIGHTNING_BRAIN11", "dt2_scar_floor_lightning_brain11", "loctypes"),
            new GamevalEntry(49294, "DT2_SCAR_FLOOR_LIGHTNING_BRAIN12", "dt2_scar_floor_lightning_brain12", "loctypes"),
            new GamevalEntry(49295, "DT2_SCAR_FLOOR_LIGHTNING_BRAIN13", "dt2_scar_floor_lightning_brain13", "loctypes"),
            new GamevalEntry(49296, "DT2_SCAR_FLOOR_LIGHTNING_BRAIN14", "dt2_scar_floor_lightning_brain14", "loctypes"),
            new GamevalEntry(49297, "DT2_SCAR_FLOOR_LIGHTNING_BRAIN15", "dt2_scar_floor_lightning_brain15", "loctypes"),
            new GamevalEntry(49298, "DT2_SCAR_FLOOR_LIGHTNING_BRAIN16", "dt2_scar_floor_lightning_brain16", "loctypes"),
            new GamevalEntry(49299, "DT2_SCAR_FLOOR_LIGHTNING_BRAIN17", "dt2_scar_floor_lightning_brain17", "loctypes"),
            new GamevalEntry(49300, "DT2_SCAR_FLOOR_LIGHTNING_BRAIN18", "dt2_scar_floor_lightning_brain18", "loctypes"),
            new GamevalEntry(49301, "DT2_SCAR_FLOOR_LIGHTNING_BRAIN19", "dt2_scar_floor_lightning_brain19", "loctypes"),
            new GamevalEntry(49302, "DT2_SCAR_FLOOR_LIGHTNING_BRAIN20", "dt2_scar_floor_lightning_brain20", "loctypes"),
            new GamevalEntry(49303, "DT2_SCAR_FLOOR_LIGHTNING_BRAIN21", "dt2_scar_floor_lightning_brain21", "loctypes"),
            new GamevalEntry(49304, "DT2_SCAR_FLOOR_LIGHTNING_BRAIN22", "dt2_scar_floor_lightning_brain22", "loctypes"),
            new GamevalEntry(49305, "DT2_SCAR_FLOOR_LIGHTNING_BRAIN23", "dt2_scar_floor_lightning_brain23", "loctypes"),
            new GamevalEntry(49306, "DT2_SCAR_FLOOR_LIGHTNING_BRAIN24", "dt2_scar_floor_lightning_brain24", "loctypes"),
            new GamevalEntry(49307, "DT2_SCAR_FLOOR_LIGHTNING_BRAIN25", "dt2_scar_floor_lightning_brain25", "loctypes"),
            new GamevalEntry(49308, "DT2_SCAR_FLOOR_LIGHTNING_BRAIN26", "dt2_scar_floor_lightning_brain26", "loctypes"),
            new GamevalEntry(49309, "DT2_SCAR_FLOOR_LIGHTNING_BRAIN27", "dt2_scar_floor_lightning_brain27", "loctypes"),
            new GamevalEntry(49310, "DT2_SCAR_FLOOR_LIGHTNING_BRAIN28", "dt2_scar_floor_lightning_brain28", "loctypes"),
            new GamevalEntry(49311, "DT2_SCAR_FLOOR_LIGHTNING_BRAIN29", "dt2_scar_floor_lightning_brain29", "loctypes"),
            new GamevalEntry(49312, "DT2_SCAR_FLOOR_LIGHTNING_BRAIN30", "dt2_scar_floor_lightning_brain30", "loctypes"),
            new GamevalEntry(49313, "DT2_SCAR_FLOOR_LIGHTNING_BRAIN31", "dt2_scar_floor_lightning_brain31", "loctypes"),
            new GamevalEntry(49314, "DT2_SCAR_FLOOR_LIGHTNING_BRAIN32", "dt2_scar_floor_lightning_brain32", "loctypes"),
            new GamevalEntry(49315, "DT2_SCAR_FLOOR_LIGHTNING_BRAIN33", "dt2_scar_floor_lightning_brain33", "loctypes"),
            new GamevalEntry(49316, "DT2_SCAR_FLOOR_LIGHTNING_BRAIN34", "dt2_scar_floor_lightning_brain34", "loctypes"),
            new GamevalEntry(49317, "DT2_SCAR_FLOOR_LIGHTNING_BRAIN35", "dt2_scar_floor_lightning_brain35", "loctypes"),
            new GamevalEntry(49318, "DT2_SCAR_FLOOR_LIGHTNING_BRAIN36", "dt2_scar_floor_lightning_brain36", "loctypes"),
            new GamevalEntry(49319, "DT2_SCAR_FLOOR_RITUAL_CIRCLE01", "dt2_scar_floor_ritual_circle01", "loctypes"),
            new GamevalEntry(49320, "DT2_SCAR_FLOOR_RITUAL_CIRCLE02", "dt2_scar_floor_ritual_circle02", "loctypes"),
            new GamevalEntry(49321, "DT2_SCAR_FLOOR_RITUAL_CIRCLE03", "dt2_scar_floor_ritual_circle03", "loctypes"),
            new GamevalEntry(49322, "DT2_SCAR_FLOOR_RITUAL_CIRCLE01_M", "dt2_scar_floor_ritual_circle01_m", "loctypes"),
            new GamevalEntry(49323, "DT2_SCAR_FLOOR_RITUAL_CIRCLE02_M", "dt2_scar_floor_ritual_circle02_m", "loctypes"),
            new GamevalEntry(49324, "DT2_SCAR_FLOOR_RITUAL_CIRCLE03_M", "dt2_scar_floor_ritual_circle03_m", "loctypes"),
            new GamevalEntry(49325, "DT2_SCAR_FLOOR_RITUAL_CIRCLE04", "dt2_scar_floor_ritual_circle04", "loctypes"),
            new GamevalEntry(49326, "DT2_SCAR_FLOOR_RITUAL_CIRCLE04_M", "dt2_scar_floor_ritual_circle04_m", "loctypes"),
            new GamevalEntry(49327, "DT2_SCAR_FLOOR_RITUAL_CIRCLE05", "dt2_scar_floor_ritual_circle05", "loctypes"),
            new GamevalEntry(49328, "DT2_SCAR_FLOOR_RITUAL_CIRCLE05_M", "dt2_scar_floor_ritual_circle05_m", "loctypes"),
            new GamevalEntry(49329, "DT2_SCAR_FLOOR_RITUAL_CIRCLE06", "dt2_scar_floor_ritual_circle06", "loctypes"),
            new GamevalEntry(49330, "DT2_SCAR_FLOOR_RITUAL_CIRCLE06_M", "dt2_scar_floor_ritual_circle06_m", "loctypes"),
            new GamevalEntry(49331, "DT2_SCAR_CRATE01", "Crate", "loctypes"),
            new GamevalEntry(49332, "DT2_SCAR_CRATE01_NOOP", "Crate", "loctypes"),
            new GamevalEntry(49333, "DT2_SCAR_FIRE01", "dt2_scar_fire01", "loctypes"),
            new GamevalEntry(49334, "DT2_SCAR_FIRE02", "dt2_scar_fire02", "loctypes"),
            new GamevalEntry(49335, "DT2_SCAR_FIRE03", "dt2_scar_fire03", "loctypes"),
            new GamevalEntry(49336, "DT2_SCAR_FIRE04", "dt2_scar_fire04", "loctypes"),
            new GamevalEntry(49337, "DT2_SCAR_FIRE01_OFFSET01", "dt2_scar_fire01_offset01", "loctypes"),
            new GamevalEntry(49338, "DT2_SCAR_FIRE01_OFFSET02", "dt2_scar_fire01_offset02", "loctypes"),
            new GamevalEntry(49339, "DT2_SCAR_BOAT_LARGE_DESTROYED01", "dt2_scar_boat_large_destroyed01", "loctypes"),
            new GamevalEntry(49340, "DT2_SCAR_BOAT_LARGE_DESTROYED02", "dt2_scar_boat_large_destroyed02", "loctypes"),
            new GamevalEntry(49341, "DT2_SCAR_BOAT_LARGE_DESTROYED03", "dt2_scar_boat_large_destroyed03", "loctypes"),
            new GamevalEntry(49342, "DT2_SCAR_PERSTENCAMP_FIRE01", "Fire", "loctypes"),
            new GamevalEntry(49343, "DT2_SCAR_PILLAR_BROKEN05", "Broken Pillar", "loctypes"),
            new GamevalEntry(49344, "DT2_SCAR_PILLAR_BROKEN06", "Broken Pillar", "loctypes"),
            new GamevalEntry(49345, "DT2_SCAR_FLOOR_BRAIN17_PUDDLE", "dt2_scar_floor_brain17_puddle", "loctypes"),
            new GamevalEntry(49346, "DT2_SCAR_FLOOR_BRAIN23_PUDDLE", "dt2_scar_floor_brain23_puddle", "loctypes"),
            new GamevalEntry(49347, "DT2_SCAR_PERSTENCAMP_SKULL01", "dt2_scar_perstencamp_skull01", "loctypes"),
            new GamevalEntry(49348, "DT2_SCAR_PERSTENCAMP_SKULL02", "dt2_scar_perstencamp_skull02", "loctypes"),
            new GamevalEntry(49349, "DT2_SCAR_PERSTENCAMP_SKULL03", "dt2_scar_perstencamp_skull03", "loctypes"),
            new GamevalEntry(49350, "DT2_SCAR_FOLIAGE_PLANT01", "dt2_scar_foliage_plant01", "loctypes"),
            new GamevalEntry(49351, "DT2_SCAR_FOLIAGE_GRASS01", "dt2_scar_foliage_grass01", "loctypes"),
            new GamevalEntry(49352, "DT2_SCAR_FOLIAGE_GRASS02", "dt2_scar_foliage_grass02", "loctypes"),
            new GamevalEntry(49353, "DT2_SCAR_FOLIAGE_GRASS03", "dt2_scar_foliage_grass03", "loctypes"),
            new GamevalEntry(49354, "DT2_SCAR_FOLIAGE_CORAL01", "Brain matter", "loctypes"),
            new GamevalEntry(49355, "DT2_SCAR_FOLIAGE_CORAL02", "Brain matter", "loctypes"),
            new GamevalEntry(49356, "DT2_SCAR_FOLIAGE_CORAL03", "Brain matter", "loctypes"),
            new GamevalEntry(49357, "DT2_SCAR_FOLIAGE_SMALL01", "Nerve", "loctypes"),
            new GamevalEntry(49358, "DT2_SCAR_FOLIAGE_SMALL02", "Nerve", "loctypes"),
            new GamevalEntry(49359, "DT2_SCAR_FOLIAGE_MEDIUM01", "Nerve", "loctypes"),
            new GamevalEntry(49360, "DT2_SCAR_FOLIAGE_MEDIUM02", "Nerves", "loctypes"),
            new GamevalEntry(49361, "DT2_SCAR_FOLIAGE_MEDIUM03", "Nerve", "loctypes"),
            new GamevalEntry(49362, "DT2_SCAR_FOLIAGE_MEDIUM04", "Nerve", "loctypes"),
            new GamevalEntry(49363, "DT2_SCAR_FOLIAGE_LARGE01", "Nerves", "loctypes"),
            new GamevalEntry(49364, "DT2_SCAR_FOLIAGE_LARGE02", "Nerves", "loctypes"),
            new GamevalEntry(49365, "DT2_SCAR_FOLIAGE_LARGE03", "Nerves", "loctypes"),
            new GamevalEntry(49366, "DT2_SCAR_FOLIAGE_TREE01", "Nerve formation", "loctypes"),
            new GamevalEntry(49367, "DT2_SCAR_FOLIAGE_TREE02", "Nerve formation", "loctypes"),
            new GamevalEntry(49368, "DT2_SCAR_FOLIAGE_TREE03", "Nerve formation", "loctypes"),
            new GamevalEntry(49369, "SCAR_DUGUPSOIL01", "scar_dugupsoil01", "loctypes"),
            new GamevalEntry(49370, "SCAR_DUGUPSOIL02", "scar_dugupsoil02", "loctypes"),
            new GamevalEntry(49371, "SCAR_DUGUPSOIL03", "scar_dugupsoil03", "loctypes"),
            new GamevalEntry(49372, "SCAR_DUGUPSOIL04", "scar_dugupsoil04", "loctypes"),
            new GamevalEntry(49373, "DT2_SCAR_NERVE_NOOP01", "dt2_scar_nerve_noop01", "loctypes"),
            new GamevalEntry(49374, "DT2_SCAR_NERVE_NOOP02", "dt2_scar_nerve_noop02", "loctypes"),
            new GamevalEntry(49375, "DT2_SCAR_NERVE_NOOP03", "dt2_scar_nerve_noop03", "loctypes"),
            new GamevalEntry(49376, "DT2_SCAR_FALLOFF1", "dt2_scar_falloff1", "loctypes"),
            new GamevalEntry(49377, "DT2_SCAR_FALLOFF2", "dt2_scar_falloff2", "loctypes"),
            new GamevalEntry(49378, "DT2_SCAR_FALLOFF3", "dt2_scar_falloff3", "loctypes"),
            new GamevalEntry(49379, "DT2_SCAR_FALLOFF4", "dt2_scar_falloff4", "loctypes"),
            new GamevalEntry(49380, "DT2_SCAR_FALLOFF5", "dt2_scar_falloff5", "loctypes"),
            new GamevalEntry(49381, "DT2_SCAR_FALLOFF6", "dt2_scar_falloff6", "loctypes"),
            new GamevalEntry(49382, "DT2_SCAR_FALLOFF7", "dt2_scar_falloff7", "loctypes"),
            new GamevalEntry(49383, "DT2_SCAR_FALLOFF8", "dt2_scar_falloff8", "loctypes"),
            new GamevalEntry(49384, "DT2_SCAR_FALLOFF9", "dt2_scar_falloff9", "loctypes"),
            new GamevalEntry(49385, "DT2_SCAR_FALLOFF_10", "dt2_scar_falloff_10", "loctypes"),
            new GamevalEntry(49386, "DT2_SCAR_FALLOFF_11", "dt2_scar_falloff_11", "loctypes"),
            new GamevalEntry(49387, "DT2_SCAR_SMOKE01", "dt2_scar_smoke01", "loctypes"),
            new GamevalEntry(49388, "DT2_SCAR_VENT01", "Vent", "loctypes"),
            new GamevalEntry(49389, "DT2_SCAR_MAZE_2_AIR_BUBBLE", "Air Bubble", "loctypes"),
            new GamevalEntry(49390, "DT2_SCAR_MAZE_2_PROP_BUBBLES", "dt2_scar_maze_2_prop_bubbles", "loctypes"),
            new GamevalEntry(49391, "DT2_SCAR_MAZE_2_SEQUENCE_GROWTH", "Abyssal Growth", "loctypes"),
            new GamevalEntry(49392, "DT2_SCAR_MAZE_2_SEQUENCE_GROWTH_LIT", "Abyssal Growth", "loctypes"),
            new GamevalEntry(49393, "DT2_SCAR_MAZE_2_SEQUENCE_GROWTH_BROKEN", "Abyssal Growth", "loctypes"),
            new GamevalEntry(49394, "DT2_SCAR_MAZE_2_SEQUENCE_GROWTH_TRIGGER", "Abyssal Stem", "loctypes"),
            new GamevalEntry(49395, "DT2_SCAR_MAZE_2_BLOOD_WHITE_HIDDEN", "Radiant Vein", "loctypes"),
            new GamevalEntry(49396, "DT2_SCAR_MAZE_2_BLOOD_WHITE_REPAIRABLE", "Radiant Vein", "loctypes"),
            new GamevalEntry(49397, "DT2_SCAR_MAZE_2_BLOOD_RED_HIDDEN", "Crimson Vein", "loctypes"),
            new GamevalEntry(49398, "DT2_SCAR_MAZE_2_BLOOD_RED_REPAIRABLE", "Crimson Vein", "loctypes"),
            new GamevalEntry(49399, "DT2_SCAR_MAZE_2_BLOOD_RED_FIXED", "Crimson Vein", "loctypes"),
            new GamevalEntry(49400, "DT2_SCAR_MAZE_2_BLOOD_WHITE_FIXED", "Radiant Vein", "loctypes"),
            new GamevalEntry(49401, "DT2_SCAR_MAZE_2_BLOOD_RED_CORNER", "Crimson Vein", "loctypes"),
            new GamevalEntry(49402, "DT2_SCAR_MAZE_2_BLOOD_RED_CORNER_MIRROR", "Crimson Vein", "loctypes"),
            new GamevalEntry(49403, "DT2_SCAR_MAZE_2_BLOOD_WHITE_CORNER", "Radiant Vein", "loctypes"),
            new GamevalEntry(49404, "DT2_SCAR_MAZE_2_BLOOD_WHITE_CORNER_MIRROR", "Radiant Vein", "loctypes"),
            new GamevalEntry(49405, "DT2_SCAR_MAZE_2_PILLAR_LOC", "dt2_scar_maze_2_pillar_loc", "loctypes"),
            new GamevalEntry(49406, "DT2_SCAR_MAZE_2_PILLAR_LOC_ACTIVE", "Fleshy Pillar", "loctypes"),
            new GamevalEntry(49407, "DT2_SCAR_MAZE_2_PILLAR_ATTACKER_SPAWN", "Neural Gateway", "loctypes"),
            new GamevalEntry(49408, "DT2_SCAR_MAZE_EXIT", "Passage", "loctypes"),
            new GamevalEntry(49409, "DT2_SCAR_MAZE_EXIT_CLIMB", "Fleshy Strand", "loctypes"),
            new GamevalEntry(49410, "DT2_SCAR_MAZE_CHALLENGE_DOOR_1", "Passage", "loctypes"),
            new GamevalEntry(49411, "DT2_SCAR_MAZE_CHALLENGE_DOOR_2", "Passage", "loctypes"),
            new GamevalEntry(49412, "DT2_SCAR_MAZE_CHALLENGE_DOOR_3", "Passage", "loctypes"),
            new GamevalEntry(49413, "DT2_SCAR_MAZE_TELEPORTER_1_1", "Neural Teleporter", "loctypes"),
            new GamevalEntry(49414, "DT2_SCAR_MAZE_TELEPORTER_1_2", "Neural Teleporter", "loctypes"),
            new GamevalEntry(49415, "DT2_SCAR_MAZE_TELEPORTER_2_1", "Neural Teleporter", "loctypes"),
            new GamevalEntry(49416, "DT2_SCAR_MAZE_TELEPORTER_2_2", "Neural Teleporter", "loctypes"),
            new GamevalEntry(49417, "DT2_SCAR_MAZE_DOORWAY_WALL_NOOP", "Passage", "loctypes"),
            new GamevalEntry(49418, "DT2_SCAR_MAZE_BOAT_ENTRANCE", "Passage", "loctypes"),
            new GamevalEntry(49419, "DT2_SCAR_MAZE_DOOR_CLOSED", "Passage", "loctypes"),
            new GamevalEntry(49420, "DT2_SCAR_MAZE_BOAT_CHEST_CLOSED", "Chest", "loctypes"),
            new GamevalEntry(49421, "DT2_SCAR_MAZE_BOAT_CHEST_CLOSED_DECOY", "Chest", "loctypes"),
            new GamevalEntry(49422, "DT2_SCAR_MAZE_BOAT_CHEST_OPEN", "Chest", "loctypes"),
            new GamevalEntry(49423, "DT2_SCAR_MAZE_BOAT", "Shipwreck", "loctypes"),
            new GamevalEntry(49424, "DT2_SCAR_MAZE_GUNPOWDER", "Gunpowder", "loctypes"),
            new GamevalEntry(49425, "DT2_SCAR_MAZE_TINDERBOXES", "Crate", "loctypes"),
            new GamevalEntry(49426, "DT2_SCAR_MAZE_BOAT_SKELETON_1", "Skeleton", "loctypes"),
            new GamevalEntry(49427, "DT2_SCAR_MAZE_BOAT_SKELETON_2", "Skeleton", "loctypes"),
            new GamevalEntry(49428, "DT2_SCAR_MAZE_BOAT_SKELETON_3", "Skeleton", "loctypes"),
            new GamevalEntry(49429, "DT2_SCAR_MAZE_BOAT_SKELETON_DECOY", "Skeleton", "loctypes"),
            new GamevalEntry(49430, "DT2_SCAR_MAZE_BOAT_SKELETON_NOTE", "Skeleton", "loctypes"),
            new GamevalEntry(49431, "DT2_SCAR_MAZE_BOAT_SKELETON_NOTE_NOOP", "Skeleton", "loctypes"),
            new GamevalEntry(49432, "DT2_SCAR_MAZE_BOAT_SKELETON_NOOP", "Skeleton", "loctypes"),
            new GamevalEntry(49433, "DT2_SCAR_MAZE_CHEST_CLOSED", "Chest", "loctypes"),
            new GamevalEntry(49434, "DT2_SCAR_MAZE_CHEST_OPEN", "Chest", "loctypes"),
            new GamevalEntry(49435, "DT2_SCAR_MAZE_CHEST_OPEN_NOOP", "Chest", "loctypes"),
            new GamevalEntry(49436, "DT2_SCAR_MAZE_LIGHT_EMPTY", "Damaged Growth", "loctypes"),
            new GamevalEntry(49437, "DT2_SCAR_MAZE_LIGHT_FILLED", "Luminescent Growth", "loctypes"),
            new GamevalEntry(49438, "DT2_SCAR_MAZE_LORE_SEARCHABLE_1", "Crate", "loctypes"),
            new GamevalEntry(49439, "DT2_SCAR_MAZE_LORE_SEARCHABLE_2", "Fleshy growth", "loctypes"),
            new GamevalEntry(49440, "DT2_SCAR_MAZE_3_PATHING_WATER", "Water Axon Terminal", "loctypes"),
            new GamevalEntry(49441, "DT2_SCAR_MAZE_3_PATHING_FIRE", "Fire Axon Terminal", "loctypes"),
            new GamevalEntry(49442, "DT2_SCAR_MAZE_3_PATHING_NATURE", "Nature Axon Terminal", "loctypes"),
            new GamevalEntry(49443, "DT2_SCAR_MAZE_3_PATHING_COSMIC", "Cosmic Axon Terminal", "loctypes"),
            new GamevalEntry(49444, "DT2_SCAR_MAZE_3_PATHING_INACTIVE_TERMINAL", "Triggered Axon Terminal", "loctypes"),
            new GamevalEntry(49445, "DT2_SCAR_MAZE_3_COMBINATION_ENDING_SMOKE", "Smoke Nerve Ending (Broken)", "loctypes"),
            new GamevalEntry(49446, "DT2_SCAR_MAZE_3_COMBINATION_ENDING_STEAM", "Steam Nerve Ending (Broken)", "loctypes"),
            new GamevalEntry(49447, "DT2_SCAR_MAZE_3_COMBINATION_ENDING_DUST", "Dust Nerve Ending (Broken)", "loctypes"),
            new GamevalEntry(49448, "DT2_SCAR_MAZE_3_COMBINATION_ENDING_LAVA", "Lava Nerve Ending (Broken)", "loctypes"),
            new GamevalEntry(49449, "DT2_SCAR_MAZE_3_COMBINATION_ENDING_FIXED", "Pulsing Nerve Ending", "loctypes"),
            new GamevalEntry(49450, "DT2_SCAR_MAZE_3_LINK_RITUAL_CIRCLE", "Summoning Circle", "loctypes"),
            new GamevalEntry(49451, "DT2_SCAR_MAZE_3_LINK_RITUAL_CIRCLE_INACTIVE", "Summoning Circle", "loctypes"),
            new GamevalEntry(49452, "MYQ5_LAB_CAGE_SMALL_BROKEN_ALT", "Cage", "loctypes"),
            new GamevalEntry(49453, "MYQ5_LAB_CAGE_TALL_BROKEN_ALT", "Cage", "loctypes"),
            new GamevalEntry(49454, "INVISABLE_BLOCKING_WALL_NOSHADOW", "invisable_blocking_wall_noshadow", "loctypes"),
            new GamevalEntry(49455, "CAMDOZAAL_VAULT_CHEST_EMPTY_SMALL", "Empty pedestal", "loctypes"),
            new GamevalEntry(49456, "PLANT_FERN01_CAVE01_HILLSKEW", "Fern", "loctypes"),
            new GamevalEntry(49457, "PLANT_FERN01_CAVE02_HILLSKEW", "Fern", "loctypes"),
            new GamevalEntry(49458, "PLANT_FERN01_CAVE03_HILLSKEW", "Fern", "loctypes"),
            new GamevalEntry(49459, "PLANT_FERN01_CAVE04_HILLSKEW", "Fern", "loctypes"),
            new GamevalEntry(49460, "SHAYZIEN_BARRICADE_2", "Barricade", "loctypes"),
            new GamevalEntry(49461, "SHAYZIEN_TABLE_4X2_ALT", "Table", "loctypes"),
            new GamevalEntry(49462, "ARCHEEUS_BARREL_BROKEN_ALT", "Barrel", "loctypes"),
            new GamevalEntry(49463, "FIRE_REMAINS_OLD", "Fire remains", "loctypes"),
            new GamevalEntry(49464, "BGSOUND_RUNE_ALTAR_AMBIENCE_3", "bgsound_rune_altar_ambience_3", "loctypes"),
            new GamevalEntry(49465, "BGSOUND_RUNE_ALTAR_AMBIENCE_2", "bgsound_rune_altar_ambience_2", "loctypes"),
            new GamevalEntry(49466, "DRAIN_LOOP_3", "drain_loop_3", "loctypes"),
            new GamevalEntry(49467, "DRAIN_LOOP_4", "drain_loop_4", "loctypes"),
            new GamevalEntry(49468, "DRAIN_LOOP_5", "drain_loop_5", "loctypes"),
            new GamevalEntry(49469, "RANDOMSOUND_UNDERGROUND_LAKE", "randomsound_underground_lake", "loctypes"),
            new GamevalEntry(49470, "RANDOMSOUND_STRANGLEWOOD_AMBIENCE", "randomsound_stranglewood_ambience", "loctypes"),
            new GamevalEntry(49471, "FAI_VARROCK_APOTHECARY_CABINET_ALT", "Cabinet", "loctypes"),
            new GamevalEntry(49472, "FAI_VARROCK_APOTHECARY_CABINET_TWO_ALT", "Cabinet", "loctypes"),
            new GamevalEntry(49473, "DEBUG_CUBE", "Debug Block", "loctypes"),
            new GamevalEntry(49474, "WHISPERER_SCOREBOARD_SHADOW", "whisperer_scoreboard_shadow", "loctypes"),
            new GamevalEntry(49475, "LEVIATHAN_SCOREBOARD", "\\;G???? ??????", "loctypes"),
            new GamevalEntry(49476, "VARDORVIS_SCOREBOARD", "vardorvis_scoreboard", "loctypes"),
            new GamevalEntry(49477, "DT2_LASSAR_ENTRY_ROCK", "dt2_lassar_entry_rock", "loctypes"),
            new GamevalEntry(49478, "DT2_LASSAR_SHADOW_PUDDLE", "\\; ???G ?H?H?H?H?H?H?H?H?H?H?H?H?H?H?H", "loctypes"),
            new GamevalEntry(49479, "DT2_LASSAR_TELEPORTER_PALACE", "dt2_lassar_teleporter_palace", "loctypes"),
            new GamevalEntry(49480, "DT2_LASSAR_TELEPORTER_PLAZA", "dt2_lassar_teleporter_plaza", "loctypes"),
            new GamevalEntry(49481, "DT2_LASSAR_TELEPORTER_CATHEDRAL", "dt2_lassar_teleporter_cathedral", "loctypes"),
            new GamevalEntry(49482, "DT2_LASSAR_TELEPORTER_SCIENCE_NORTH", "dt2_lassar_teleporter_science_north", "loctypes"),
            new GamevalEntry(49483, "DT2_LASSAR_TELEPORTER_SCIENCE_SOUTH", "dt2_lassar_teleporter_science_south", "loctypes"),
            new GamevalEntry(49484, "DT2_LASSAR_TELEPORTER_RESIDENTIAL_WEST", "dt2_lassar_teleporter_residential_west", "loctypes"),
            new GamevalEntry(49485, "DT2_LASSAR_TELEPORTER_RESIDENTIAL_EAST", "dt2_lassar_teleporter_residential_east", "loctypes"),
            new GamevalEntry(49486, "DT2_LASSAR_KETLA_WORKBENCH", "dt2_lassar_ketla_workbench", "loctypes"),
            new GamevalEntry(49487, "DT2_LASSAR_KETLA_WORKBENCH_SHADOW", "dt2_lassar_ketla_workbench_shadow", "loctypes"),
            new GamevalEntry(49488, "DT2_LASSAR_CHURCH_ENTRY", "dt2_lassar_church_entry", "loctypes"),
            new GamevalEntry(49489, "DT2_LASSAR_CHURCH_ENTRY_SHADOW", "dt2_lassar_church_entry_shadow", "loctypes"),
            new GamevalEntry(49490, "DT2_KASONDE_DESK", "dt2_kasonde_desk", "loctypes"),
            new GamevalEntry(49491, "DT2_STRANGLEWOOD_BOAT_IN", "dt2_stranglewood_boat_in", "loctypes"),
            new GamevalEntry(49492, "DT2_STRANGLEWOOD_BARRICADE", "dt2_stranglewood_barricade", "loctypes"),
            new GamevalEntry(49493, "DT2_STRANGLEWOOD_BUSH", "dt2_stranglewood_bush", "loctypes"),
            new GamevalEntry(49494, "DT2_STRANGLEWOOD_HERBS", "dt2_stranglewood_herbs", "loctypes"),
            new GamevalEntry(49495, "DT2_STRANGLEWOOD_BOSS_ENTRY", "dt2_stranglewood_boss_entry", "loctypes"),
            new GamevalEntry(49496, "DT2_STRANGLEWOOD_MEDALLION_CHEST", "dt2_stranglewood_medallion_chest", "loctypes"),
            new GamevalEntry(49497, "DT2_HIDEOUT_ENTRY", "dt2_hideout_entry", "loctypes"),
            new GamevalEntry(49498, "DT2_HIDEOUT_ALTAR", "dt2_hideout_altar", "loctypes"),
            new GamevalEntry(49499, "DT2_VAULT_VARDORVIS_STATUE", "dt2_vault_vardorvis_statue", "loctypes"),
            new GamevalEntry(49500, "DT2_VAULT_VARDORVIS_STATUE_NOOP", "dt2_vault_vardorvis_statue_noop", "loctypes"),
            new GamevalEntry(49501, "DT2_VAULT_WHISPERER_STATUE", "dt2_vault_whisperer_statue", "loctypes"),
            new GamevalEntry(49502, "DT2_VAULT_WHISPERER_STATUE_NOOP", "dt2_vault_whisperer_statue_noop", "loctypes"),
            new GamevalEntry(49503, "DT2_VAULT_SUCELLUS_STATUE", "dt2_vault_sucellus_statue", "loctypes"),
            new GamevalEntry(49504, "DT2_VAULT_SUCELLUS_STATUE_NOOP", "dt2_vault_sucellus_statue_noop", "loctypes"),
            new GamevalEntry(49505, "DT2_VAULT_PERSERIYA_STATUE", "dt2_vault_perseriya_statue", "loctypes"),
            new GamevalEntry(49506, "DT2_VAULT_PERSERIYA_STATUE_NOOP", "dt2_vault_perseriya_statue_noop", "loctypes"),
            new GamevalEntry(49507, "DT2_VAULT_DOOR_ENTRANCE", "dt2_vault_door_entrance", "loctypes"),
            new GamevalEntry(49508, "DT2_VAULT_DOOR_EXIT", "dt2_vault_door_exit", "loctypes"),
            new GamevalEntry(49509, "DT2_ELDER_HORN", "dt2_elder_horn", "loctypes"),
            new GamevalEntry(49510, "DT2_DIGSITE_CREVICE", "dt2_digsite_crevice", "loctypes"),
            new GamevalEntry(49511, "DT2_WAR_ROOM_WARMIND", "dt2_war_room_warmind", "loctypes"),
            new GamevalEntry(49512, "DT2_WAR_ROOM_ALTAR", "dt2_war_room_altar", "loctypes"),
            new GamevalEntry(49513, "DT2_GHORROCK_ENTRY", "dt2_ghorrock_entry", "loctypes"),
            new GamevalEntry(49514, "DT2_GHORROCK_CELL_BED", "dt2_ghorrock_cell_bed", "loctypes"),
            new GamevalEntry(49515, "DT2_GHORROCK_FIRECRACKER_PACK", "dt2_ghorrock_firecracker_pack", "loctypes"),
            new GamevalEntry(49516, "DT2_GHORROCK_SHORTCUT_1_ENTRY", "dt2_ghorrock_shortcut_1_entry", "loctypes"),
            new GamevalEntry(49517, "DT2_GHORROCK_SHORTCUT_2_ENTRY", "dt2_ghorrock_shortcut_2_entry", "loctypes"),
            new GamevalEntry(49518, "DT2_GHORROCK_RATION_CRATE", "dt2_ghorrock_ration_crate", "loctypes"),
            new GamevalEntry(49519, "DT2_JHALLAN_FROZEN", "dt2_jhallan_frozen", "loctypes"),
            new GamevalEntry(49520, "DT2_SCAR_MAZE_1_RIFT_EARTH", "dt2_scar_maze_1_rift_earth", "loctypes"),
            new GamevalEntry(49521, "DT2_SCAR_MAZE_1_RIFT_COSMIC", "dt2_scar_maze_1_rift_cosmic", "loctypes"),
            new GamevalEntry(49522, "DT2_SCAR_MAZE_1_RIFT_DEATH", "dt2_scar_maze_1_rift_death", "loctypes"),
            new GamevalEntry(49523, "DT2_SCAR_MAZE_1_RIFT_NATURE", "dt2_scar_maze_1_rift_nature", "loctypes"),
            new GamevalEntry(49524, "DT2_SCAR_MAZE_1_RIFT_LAW", "dt2_scar_maze_1_rift_law", "loctypes"),
            new GamevalEntry(49525, "DT2_SCAR_MAZE_1_RIFT_FIRE", "dt2_scar_maze_1_rift_fire", "loctypes"),
            new GamevalEntry(49526, "DT2_SCAR_MAZE_1_ENTRY", "\\; ???6 ?6?6?6?6?6?6?6?6?6?6?5?5?5?5?5?5?5?5?5", "loctypes"),
            new GamevalEntry(49527, "DT2_SCAR_MAZE_2_ENTRY", "\\; ???6 ?6?6?6?6?6?6?6?6?6?6?6?6?6?6?6?6?6?6?6?6?7?7?7?7?7?7?7", "loctypes"),
            new GamevalEntry(49528, "DT2_SCAR_MAZE_3_ENTRY", "\\; ???6\"?6?6?6?6?6?6?6?6?6?6?6?6?6?6?6?6?6?6?6?6?6?6?6?6?6?6?6?6?8?8?8?8?8?8?8", "loctypes"),
            new GamevalEntry(49529, "DT2_SCAR_STEPPING_STONE", "dt2_scar_stepping_stone", "loctypes"),
            new GamevalEntry(49530, "DT2_SCAR_PERSTEN_BOAT_CAMP", "dt2_scar_persten_boat_camp", "loctypes"),
            new GamevalEntry(49531, "DT2_SCAR_PERSTEN_BOAT_ISLAND", "dt2_scar_persten_boat_island", "loctypes"),
            new GamevalEntry(49532, "DT2_SCAR_TENT", "dt2_scar_tent", "loctypes"),
            new GamevalEntry(49533, "DT2_SCAR_SMOKE_STEP_1", "dt2_scar_smoke_step_1", "loctypes"),
            new GamevalEntry(49534, "DT2_SCAR_SMOKE_STEP_2", "dt2_scar_smoke_step_2", "loctypes"),
            new GamevalEntry(49535, "DT2_SCAR_SMOKE_STEP_3", "dt2_scar_smoke_step_3", "loctypes"),
            new GamevalEntry(49536, "DT2_SCAR_MAZE_2_BLOOD_WHITE", "dt2_scar_maze_2_blood_white", "loctypes"),
            new GamevalEntry(49537, "DT2_SCAR_MAZE_2_BLOOD_RED", "dt2_scar_maze_2_blood_red", "loctypes"),
            new GamevalEntry(49538, "DT2_SCAR_MAZE_2_BLOOD_RED_NO_REPAIR", "dt2_scar_maze_2_blood_red_no_repair", "loctypes"),
            new GamevalEntry(49539, "DT2_SCAR_MAZE_2_BLOOD_WHITE_NO_REPAIR", "dt2_scar_maze_2_blood_white_no_repair", "loctypes"),
            new GamevalEntry(49540, "DT2_SCAR_MAZE_2_BLOOD_RED_CORNER_NO_REPAIR", "dt2_scar_maze_2_blood_red_corner_no_repair", "loctypes"),
            new GamevalEntry(49541, "DT2_SCAR_MAZE_2_BLOOD_RED_CORNER_NO_REPAIR_MIRROR", "dt2_scar_maze_2_blood_red_corner_no_repair_mirror", "loctypes"),
            new GamevalEntry(49542, "DT2_SCAR_MAZE_2_BLOOD_WHITE_CORNER_NO_REPAIR", "dt2_scar_maze_2_blood_white_corner_no_repair", "loctypes"),
            new GamevalEntry(49543, "DT2_SCAR_MAZE_2_BLOOD_WHITE_CORNER_NO_REPAIR_MIRROR", "dt2_scar_maze_2_blood_white_corner_no_repair_mirror", "loctypes"),
            new GamevalEntry(49544, "DT2_LASSAR_STAMINA_POOL_OP", "Strange Pool", "loctypes"),
            new GamevalEntry(49545, "DT2_LASSAR_STAMINA_POOL_NOOP", "Strange Pool", "loctypes"),
            new GamevalEntry(49546, "DT2_LASSAR_STAMINA_POOL_SHADOW_OP", "Strange Pool", "loctypes"),
            new GamevalEntry(49547, "DT2_LASSAR_STAMINA_POOL_SHADOW_NOOP", "Strange Pool", "loctypes"),
            new GamevalEntry(49548, "DT2_STRANGLEWOOD_STAMINA_PLANT_OP", "Strange shrine", "loctypes"),
            new GamevalEntry(49549, "DT2_STRANGLEWOOD_STAMINA_PLANT_NOOP", "Strange shrine", "loctypes"),
            new GamevalEntry(49550, "DT2_STRANGLEWOOD_STINKBOMB_CHEST", "Stone chest", "loctypes"),
            new GamevalEntry(49551, "DT2_LASSAR_STAMINA_POOL", "dt2_lassar_stamina_pool", "loctypes"),
            new GamevalEntry(49552, "DT2_LASSAR_STAMINA_POOL_SHADOW", "dt2_lassar_stamina_pool_shadow", "loctypes"),
            new GamevalEntry(49553, "DT2_STRANGLEWOOD_STAMINA_PLANT", "dt2_stranglewood_stamina_plant", "loctypes"),
            new GamevalEntry(49554, "DT2_STRANGLEWOOD_STAMINA_PLANT_CUTSCENE", "Strange shrine", "loctypes"),
            new GamevalEntry(49555, "WHISPERER_MEDALLION_LOC_OP", "Entrails", "loctypes"),
            new GamevalEntry(49556, "WHISPERER_MEDALLION_LOC_NOOP", "Entrails", "loctypes"),
            new GamevalEntry(49557, "DT2_VAULT_QUARTZ_CHEST_MULTI", "dt2_vault_quartz_chest_multi", "loctypes"),
            new GamevalEntry(49558, "DT2_VAULT_QUARTZ_CHEST_MULTI_NOOP", "Chest", "loctypes"),
            new GamevalEntry(49559, "DT2_VAULT_QUARTZ_CHEST_MULTI_OP", "Chest", "loctypes"),
            new GamevalEntry(49560, "DT2_VAULT_QUARTZ_CHEST_OPEN", "Chest", "loctypes"),
            new GamevalEntry(49561, "DEADMAN_BREACH_SPAWN_LOC", "Breach", "loctypes"),
            new GamevalEntry(49562, "DEADMAN_BREACH_DESPAWN_LOC", "deadman_breach_despawn_loc", "loctypes"),
            new GamevalEntry(49563, "DEADMAN_BOSS_SPAWN_LOC", "Boss Spawn", "loctypes"),
            new GamevalEntry(49564, "DEADMAN_BLIGHTED_WEAPONS_LOOT_CYCLE", "Loot!", "loctypes"),
            new GamevalEntry(49565, "DEADMAN_BLIGHTED_WEAPONS_LOOT_CHOSEN_WEAPON", "Loot!", "loctypes"),
            new GamevalEntry(49566, "TOA_LOBBY_WALL02_CAVITY_PARENT", "toa_lobby_wall02_cavity_parent", "loctypes"),
            new GamevalEntry(49567, "TOA_LOBBY_WALL02_CAVITY_01", "toa_lobby_wall02_cavity_01", "loctypes"),
            new GamevalEntry(49568, "TOA_LOBBY_WALL02_CAVITY_PICKAXE_EMPTY01", "Cavity", "loctypes"),
            new GamevalEntry(49569, "TOA_LOBBY_WALL02_CAVITY_PICKAXE_IRON01", "Cavity", "loctypes"),
            new GamevalEntry(49570, "TOA_LOBBY_WALL02_CAVITY_PICKAXE_STEEL01", "Cavity", "loctypes"),
            new GamevalEntry(49571, "TOA_LOBBY_WALL02_CAVITY_PICKAXE_BLACK01", "Cavity", "loctypes"),
            new GamevalEntry(49572, "TOA_LOBBY_WALL02_CAVITY_PICKAXE_MITHRIL01", "Cavity", "loctypes"),
            new GamevalEntry(49573, "TOA_LOBBY_WALL02_CAVITY_PICKAXE_ADAMANT01", "Cavity", "loctypes"),
            new GamevalEntry(49574, "TOA_LOBBY_WALL02_CAVITY_PICKAXE_RUNE01", "Cavity", "loctypes"),
            new GamevalEntry(49575, "TOA_LOBBY_WALL02_CAVITY_PICKAXE_GILDED01", "Cavity", "loctypes"),
            new GamevalEntry(49576, "TOA_LOBBY_WALL02_CAVITY_PICKAXE_DRAGON01", "Cavity", "loctypes"),
            new GamevalEntry(49577, "TOA_LOBBY_WALL02_CAVITY_PICKAXE_DRAGON02", "Cavity", "loctypes"),
            new GamevalEntry(49578, "TOA_LOBBY_WALL02_CAVITY_PICKAXE_DRAGON03", "Cavity", "loctypes"),
            new GamevalEntry(49579, "TOA_LOBBY_WALL02_CAVITY_PICKAXE_3RDAGE01", "Cavity", "loctypes"),
            new GamevalEntry(49580, "TOA_LOBBY_WALL02_CAVITY_PICKAXE_INFERNAL01", "Cavity", "loctypes"),
            new GamevalEntry(49581, "TOA_LOBBY_WALL02_CAVITY_PICKAXE_CRYSTAL01", "Cavity", "loctypes"),
            new GamevalEntry(49582, "TOA_LOBBY_WALL02_CAVITY_PICKAXE_TRAILBLAZER01", "Cavity", "loctypes"),
            new GamevalEntry(49583, "TOA_POTTERY_BANKDEPOSIT", "Deposit pot", "loctypes"),
            new GamevalEntry(49584, "POG_2X2_BLOCKING", "pog_2x2_blocking", "loctypes"),
            new GamevalEntry(49585, "POG_2X2_NONBLOCKING", "pog_2x2_nonblocking", "loctypes"),
            new GamevalEntry(49586, "POG_1X1_BLOCKING", "pog_1x1_blocking", "loctypes"),
            new GamevalEntry(49587, "POG_1X1_NONBLOCKING", "pog_1x1_nonblocking", "loctypes"),
            new GamevalEntry(49588, "POG_FLUFFY_REVEAL_ANIM", "Cute Creature", "loctypes"),
            new GamevalEntry(49589, "POG_GRAPPLE_TREE", "Tree", "loctypes"),
            new GamevalEntry(49590, "POG_GRAPPLE_TREE_BASE_OP", "Tree", "loctypes"),
            new GamevalEntry(49591, "POG_GRAPPLE_TREE_BASE_NOOP", "Tree", "loctypes"),
            new GamevalEntry(49592, "POG_SPIRIT_TREE_DEAD", "Spirit Tree", "loctypes"),
            new GamevalEntry(49593, "POG_SPIRIT_TREE_DEAD_NOOP", "Spirit Tree", "loctypes"),
            new GamevalEntry(49594, "POG_SPIRIT_TREE_ALIVE_INITIAL", "Spirit Tree", "loctypes"),
            new GamevalEntry(49595, "POG_SPIRIT_TREE_ALIVE_STATIC", "Gnome Stronghold", "loctypes"),
            new GamevalEntry(49596, "POG_SPIRIT_TREE_ALIVE_NOOP", "Spirit Tree", "loctypes"),
            new GamevalEntry(49597, "POG_SPIRIT_TREE_ANIM", "Spirit Tree", "loctypes"),
            new GamevalEntry(49598, "POG_SPIRIT_TREE_MULTI", "pog_spirit_tree_multi", "loctypes"),
            new GamevalEntry(49599, "POG_HATCH_CLOSED_DOOR", "Heavy door", "loctypes"),
            new GamevalEntry(49600, "POG_HATCH_OPEN_DOOR", "Heavy door", "loctypes"),
            new GamevalEntry(49601, "POG_HATCH_OPEN_DOOR_NOOP", "Heavy door", "loctypes"),
            new GamevalEntry(49602, "POG_HUMAN_FOOD_SHANKS", "Human food", "loctypes"),
            new GamevalEntry(49603, "POG_HUMAN_FOOD_FRUIT_1", "Human food", "loctypes"),
            new GamevalEntry(49604, "POG_HUMAN_FOOD_FRUIT_2", "Human food", "loctypes"),
            new GamevalEntry(49605, "POG_HUMAN_FOOD_SHANKS_ALT", "Human food", "loctypes"),
            new GamevalEntry(49606, "POG_HUMAN_FOOD_FRUIT_1_ALT", "Human food", "loctypes"),
            new GamevalEntry(49607, "POG_HUMAN_FOOD_FRUIT_2_ALT", "Human food", "loctypes"),
            new GamevalEntry(49608, "POG_BOLRIES_ADVISOR_FADE_REVEAL", "Advisor", "loctypes"),
            new GamevalEntry(49609, "POG_ALARM_BUTTON", "Alarm button", "loctypes"),
            new GamevalEntry(49610, "POG_SINGING_BOWL_INSPECT", "Singing bowl", "loctypes"),
            new GamevalEntry(49611, "POG_SINGING_BOWL_SING", "Singing bowl", "loctypes"),
            new GamevalEntry(49612, "POG_GOLRIE_BIG_CHEST", "Chest", "loctypes"),
            new GamevalEntry(49613, "POG_GOLRIE_BIG_OPENCHEST", "Chest", "loctypes"),
            new GamevalEntry(49614, "POG_GOLRIE_SMALL_CHEST_PICKLOCK", "Chest", "loctypes"),
            new GamevalEntry(49615, "POG_GOLRIE_SMALL_CHEST_NORMAL", "Chest", "loctypes"),
            new GamevalEntry(49616, "POG_GOLRIE_SMALL_OPENCHEST", "Chest", "loctypes"),
            new GamevalEntry(49617, "POG_CHEST_CLOSED", "Chest", "loctypes"),
            new GamevalEntry(49618, "POG_CHEST_OPEN", "Chest", "loctypes"),
            new GamevalEntry(49619, "POG_CAVE_WALL_ENTRANCE_GOLRIE_WATERFALL", "Tunnel", "loctypes"),
            new GamevalEntry(49620, "POG_CAVE_WALL_ENTRANCE_GOLRIE_ROVING", "Tunnel", "loctypes"),
            new GamevalEntry(49621, "BGSOUND_POG_CAVE_WIND", "bgsound_pog_cave_wind", "loctypes"),
            new GamevalEntry(49622, "POG_CAVE_WALL", "pog_cave_wall", "loctypes"),
            new GamevalEntry(49623, "POG_CAVE_WALL_ENTRANCE", "Tunnel", "loctypes"),
            new GamevalEntry(49624, "POG_CAVE_WALL_ROCKY", "pog_cave_wall_rocky", "loctypes"),
            new GamevalEntry(49625, "POG_CAVE_WALL_SUPPORT_LEFT", "pog_cave_wall_support_left", "loctypes"),
            new GamevalEntry(49626, "POG_CAVE_WALL_SUPPORT_RIGHT", "pog_cave_wall_support_right", "loctypes"),
            new GamevalEntry(49627, "POG_CAVE_WALL_SUPPORT_MID", "pog_cave_wall_support_mid", "loctypes"),
            new GamevalEntry(49628, "POG_CAVE_MINE_WALL_LAMP", "pog_cave_mine_wall_lamp", "loctypes"),
            new GamevalEntry(49629, "POG_CAVE_WALL_TOP", "pog_cave_wall_top", "loctypes"),
            new GamevalEntry(49630, "POG_CAVE_WALL_TOP_BLACK", "pog_cave_wall_top_black", "loctypes"),
            new GamevalEntry(49631, "POG_CAVE_WALL_TOP5", "pog_cave_wall_top5", "loctypes"),
            new GamevalEntry(49632, "POG_CAVE_ROCKS_1X1_01", "Rock", "loctypes"),
            new GamevalEntry(49633, "POG_CAVE_ROCKS_1X1_02", "Rock", "loctypes"),
            new GamevalEntry(49634, "POG_CAVE_ROCKS_1X1_03", "Rock", "loctypes"),
            new GamevalEntry(49635, "POG_CAVE_ROCKS_1X3_01", "Rock", "loctypes"),
            new GamevalEntry(49636, "POG_GNOME_BARREL", "Gnome barrel", "loctypes"),
            new GamevalEntry(49637, "POG_GNOME_BARRELS", "Gnome barrels", "loctypes"),
            new GamevalEntry(49638, "POG_GNOME_CRATES", "Gnome crates", "loctypes"),
            new GamevalEntry(49639, "POG_GNOME_CRATE_SINGLE", "Gnome crate", "loctypes"),
            new GamevalEntry(49640, "POG_BARREL", "Barrel", "loctypes"),
            new GamevalEntry(49641, "POG_CRATE", "Crate", "loctypes"),
            new GamevalEntry(49642, "POG_CRATES_STACKED", "Crates", "loctypes"),
            new GamevalEntry(49643, "POG_CRATES_STACKED_ENTRANCE", "Crates", "loctypes"),
            new GamevalEntry(49644, "POG_DUGUPSOIL_01", "pog_dugupsoil_01", "loctypes"),
            new GamevalEntry(49645, "POG_DUGUPSOIL_02", "pog_dugupsoil_02", "loctypes"),
            new GamevalEntry(49646, "POG_DUGUPSOIL_03", "pog_dugupsoil_03", "loctypes"),
            new GamevalEntry(49647, "POG_DUGUPSOIL_04", "pog_dugupsoil_04", "loctypes"),
            new GamevalEntry(49648, "POG_DUGUPSOIL_05", "pog_dugupsoil_05", "loctypes"),
            new GamevalEntry(49649, "POG_DUGUPSOIL_06", "pog_dugupsoil_06", "loctypes"),
            new GamevalEntry(49650, "POG_DUGUPSOIL_07", "pog_dugupsoil_07", "loctypes"),
            new GamevalEntry(49651, "POG_CAVE_DOOR_SUPPORT", "pog_cave_door_support", "loctypes"),
            new GamevalEntry(49652, "POG_CAVE_DOOR_SUPPORT_M", "pog_cave_door_support_m", "loctypes"),
            new GamevalEntry(49653, "POG_WOODEN_TABLE", "Table", "loctypes"),
            new GamevalEntry(49654, "POG_STOOL", "Stool", "loctypes"),
            new GamevalEntry(49655, "POG_SMASHEDCHAIR", "Smashed chair", "loctypes"),
            new GamevalEntry(49656, "POG_WOOD", "pog_wood", "loctypes"),
            new GamevalEntry(49657, "POG_GATE_DOOR", "Gate", "loctypes"),
            new GamevalEntry(49658, "POG_GATE_DOOR_OPEN", "Gate", "loctypes"),
            new GamevalEntry(49659, "POG_GNOME_MACHINE_01", "Yewnock's machine", "loctypes"),
            new GamevalEntry(49660, "POG_GNOME_MACHINE_01_COGS", "Cogs", "loctypes"),
            new GamevalEntry(49661, "POG_GNOME_MACHINE_01_PIPE", "pog_gnome_machine_01_pipe", "loctypes"),
            new GamevalEntry(49662, "POG_GNOME_MACHINE_02", "Yewnock's machine", "loctypes"),
            new GamevalEntry(49663, "POG_GNOME_MACHINE_03", "Yewnock's exchanger", "loctypes"),
            new GamevalEntry(49664, "POG_MACHINE_PLATFORM_PART1", "pog_machine_platform_part1", "loctypes"),
            new GamevalEntry(49665, "POG_MACHINE_PLATFORM_PART2", "pog_machine_platform_part2", "loctypes"),
            new GamevalEntry(49666, "POG_MACHINE_PLATFORM_PART3", "pog_machine_platform_part3", "loctypes"),
            new GamevalEntry(49667, "POG_MACHINE_PLATFORM_PART4", "pog_machine_platform_part4", "loctypes"),
            new GamevalEntry(49668, "POG_MACHINE_PLATFORM_PART5", "pog_machine_platform_part5", "loctypes"),
            new GamevalEntry(49669, "POG_MACHINE_PLATFORM_PART6", "pog_machine_platform_part6", "loctypes"),
            new GamevalEntry(49670, "POG_DITCH_LIP01", "pog_ditch_lip01", "loctypes"),
            new GamevalEntry(49671, "POG_DITCH_LIP02", "pog_ditch_lip02", "loctypes"),
            new GamevalEntry(49672, "POG_DITCH_LIP03", "pog_ditch_lip03", "loctypes"),
            new GamevalEntry(49673, "POG_LECTURN", "Lectern", "loctypes"),
            new GamevalEntry(49674, "POG_SEWER_BRICK_WALL_FOR_PIPE", "pog_sewer_brick_wall_for_pipe", "loctypes"),
            new GamevalEntry(49675, "POG_BRICK_WALL_PIPE", "pog_brick_wall_pipe", "loctypes"),
            new GamevalEntry(49676, "POG_BRICK_WALL_PIPE_NO_TAR", "pog_brick_wall_pipe_no_tar", "loctypes"),
            new GamevalEntry(49677, "POG_SEWER_BRICK_WALL_FOR_JETS", "pog_sewer_brick_wall_for_jets", "loctypes"),
            new GamevalEntry(49678, "POG_SEWER_BRICK_WALL_FOR_DARTS", "pog_sewer_brick_wall_for_darts", "loctypes"),
            new GamevalEntry(49679, "POG_SHIELD", "pog_shield", "loctypes"),
            new GamevalEntry(49680, "POG_GAS_CLOUD", "pog_gas_cloud", "loctypes"),
            new GamevalEntry(49681, "POG_CAVE_GROUND_FALLOFF_1", "pog_cave_ground_falloff_1", "loctypes"),
            new GamevalEntry(49682, "POG_CAVE_GROUND_FALLOFF_2", "pog_cave_ground_falloff_2", "loctypes"),
            new GamevalEntry(49683, "POG_CAVE_GROUND_FALLOFF_3", "pog_cave_ground_falloff_3", "loctypes"),
            new GamevalEntry(49684, "POG_CAVE_GROUND_FALLOFF_4", "pog_cave_ground_falloff_4", "loctypes"),
            new GamevalEntry(49685, "POG_CAVE_GROUND_FALLOFF_5", "pog_cave_ground_falloff_5", "loctypes"),
            new GamevalEntry(49686, "POG_CAVE_GROUND_FALLOFF_6", "pog_cave_ground_falloff_6", "loctypes"),
            new GamevalEntry(49687, "POG_CAVE_GROUND_FALLOFF_7", "pog_cave_ground_falloff_7", "loctypes"),
            new GamevalEntry(49688, "POG_CAVE_GROUND_FALLOFF_8", "pog_cave_ground_falloff_8", "loctypes"),
            new GamevalEntry(49689, "POG_CAVE_GROUND_FALLOFF_9", "pog_cave_ground_falloff_9", "loctypes"),
            new GamevalEntry(49690, "POG_CAVE_GROUND_FALLOFF_10", "pog_cave_ground_falloff_10", "loctypes"),
            new GamevalEntry(49691, "POG_CAVE_GROUND_FALLOFF_11", "pog_cave_ground_falloff_11", "loctypes"),
            new GamevalEntry(49692, "POG_CAVE_GROUND_FALLOFF_12", "pog_cave_ground_falloff_12", "loctypes"),
            new GamevalEntry(49693, "POG_SEWER_PIPE_FLOOR_MID_01", "pog_sewer_pipe_floor_mid_01", "loctypes"),
            new GamevalEntry(49694, "POG_SEWER_PIPE_FLOOR_MID_02", "pog_sewer_pipe_floor_mid_02", "loctypes"),
            new GamevalEntry(49695, "POG_SEWER_PIPE_FLOOR_EDGE_01", "pog_sewer_pipe_floor_edge_01", "loctypes"),
            new GamevalEntry(49696, "POG_SEWER_PIPE_FLOOR_EDGE_02", "pog_sewer_pipe_floor_edge_02", "loctypes"),
            new GamevalEntry(49697, "POG_SEWER_PIPE_FLOOR_EDGE_CORNER", "pog_sewer_pipe_floor_edge_corner", "loctypes"),
            new GamevalEntry(49698, "POG_SEWER_PIPE_SIDE_01", "pog_sewer_pipe_side_01", "loctypes"),
            new GamevalEntry(49699, "POG_SEWER_PIPE_SIDE_FOR_LADDER", "pog_sewer_pipe_side_for_ladder", "loctypes"),
            new GamevalEntry(49700, "POG_SEWER_PIPE_SIDE_LADDER", "Ladder", "loctypes"),
            new GamevalEntry(49701, "POG_SEWER_LADDER_TOP", "Ladder", "loctypes"),
            new GamevalEntry(49702, "POG_SEWER_PIPE_SIDE_02", "pog_sewer_pipe_side_02", "loctypes"),
            new GamevalEntry(49703, "POG_SEWER_PIPE_SIDE_GRATE_SIDE", "pog_sewer_pipe_side_grate_side", "loctypes"),
            new GamevalEntry(49704, "POG_SEWER_PIPE_SIDE_GRATE_SIDE_MIRROR", "pog_sewer_pipe_side_grate_side_mirror", "loctypes"),
            new GamevalEntry(49705, "POG_SEWER_PIPE_SIDE_GRATE_MID", "pog_sewer_pipe_side_grate_mid", "loctypes"),
            new GamevalEntry(49706, "POG_SEWER_PIPE_SIDE_GRATE_MID_MIRROR", "pog_sewer_pipe_side_grate_mid_mirror", "loctypes"),
            new GamevalEntry(49707, "POG_SEWER_PIPE_CORNER", "pog_sewer_pipe_corner", "loctypes"),
            new GamevalEntry(49708, "POG_SEWER_PIPE_TOP_HALF_01", "pog_sewer_pipe_top_half_01", "loctypes"),
            new GamevalEntry(49709, "POG_SEWER_PIPE_TOP_HALF_02", "pog_sewer_pipe_top_half_02", "loctypes"),
            new GamevalEntry(49710, "POG_SEWER_PIPE_TOP_HALF_03", "pog_sewer_pipe_top_half_03", "loctypes"),
            new GamevalEntry(49711, "POG_SEWER_PIPE_TOP_HALF_01_OFFSET", "pog_sewer_pipe_top_half_01_offset", "loctypes"),
            new GamevalEntry(49712, "POG_SEWER_PIPE_TOP_HALF_02_OFFSET", "pog_sewer_pipe_top_half_02_offset", "loctypes"),
            new GamevalEntry(49713, "POG_SEWER_PIPE_TOP_HALF_03_OFFSET", "pog_sewer_pipe_top_half_03_offset", "loctypes"),
            new GamevalEntry(49714, "POG_SEWER_PIPE_TOP_HALF_BLEND_01", "pog_sewer_pipe_top_half_blend_01", "loctypes"),
            new GamevalEntry(49715, "POG_SEWER_PIPE_TOP_HALF_BLEND_01_MIRROR", "pog_sewer_pipe_top_half_blend_01_mirror", "loctypes"),
            new GamevalEntry(49716, "POG_SEWER_PIPE_TOP_HALF_BLEND_02", "pog_sewer_pipe_top_half_blend_02", "loctypes"),
            new GamevalEntry(49717, "POG_SEWER_PIPE_TOP_HALF_BLEND_02_MIRROR", "pog_sewer_pipe_top_half_blend_02_mirror", "loctypes"),
            new GamevalEntry(49718, "POG_SEWER_PIPE_TOP_HALF_BLEND_03", "pog_sewer_pipe_top_half_blend_03", "loctypes"),
            new GamevalEntry(49719, "POG_SEWER_PIPE_TOP_HALF_BLEND_03_MIRROR", "pog_sewer_pipe_top_half_blend_03_mirror", "loctypes"),
            new GamevalEntry(49720, "POG_SEWER_RAIL", "pog_sewer_rail", "loctypes"),
            new GamevalEntry(49721, "POG_SEWER_RAIL_END", "pog_sewer_rail_end", "loctypes"),
            new GamevalEntry(49722, "POG_SEWER_RAIL_END_MIRROR", "pog_sewer_rail_end_mirror", "loctypes"),
            new GamevalEntry(49723, "POG_SEWER_BRICK_WALL", "pog_sewer_brick_wall", "loctypes"),
            new GamevalEntry(49724, "POG_SEWER_BRICK_WALL_DOUBLE_SIDED", "pog_sewer_brick_wall_double_sided", "loctypes"),
            new GamevalEntry(49725, "POG_SEWER_BRICK_WALL_DOUBLE_SIDED_END", "pog_sewer_brick_wall_double_sided_end", "loctypes"),
            new GamevalEntry(49726, "POG_SEWER_BRICK_WALL_DOUBLE_SIDED_END_MIRROR", "pog_sewer_brick_wall_double_sided_end_mirror", "loctypes"),
            new GamevalEntry(49727, "POG_SEWER_BRICK_WALL_VAR", "pog_sewer_brick_wall_var", "loctypes"),
            new GamevalEntry(49728, "POG_SEWER_BRICK_WALL_END", "pog_sewer_brick_wall_end", "loctypes"),
            new GamevalEntry(49729, "POG_SEWER_BRICK_WALL_END_MIRROR", "pog_sewer_brick_wall_end_mirror", "loctypes"),
            new GamevalEntry(49730, "POG_SEWER_BRICK_WALL_PILLAR", "pog_sewer_brick_wall_pillar", "loctypes"),
        };
    }

    static Optional<GamevalEntry> byId(int id) {
        for (GamevalEntry entry : entries()) {
            if (entry.id() == id) return Optional.of(entry);
        }
        return Optional.empty();
    }

}
