package net.titan.gamevals.internal;

import java.util.Optional;

import net.titan.gamevals.GamevalEntry;
import net.titan.gamevals.QuestEntry;

final class ObjectIDEntries_15 {
    private ObjectIDEntries_15() {}

    static GamevalEntry[] entries() {
        return new GamevalEntry[] {
            new GamevalEntry(7680, "DISEASED_POISON_IVY_BUSH_7680", "Diseased Poison Ivy bush", "loctypes"),
            new GamevalEntry(7681, "DISEASED_POISON_IVY_BUSH_7681", "Diseased Poison Ivy bush", "loctypes"),
            new GamevalEntry(7682, "DISEASED_POISON_IVY_BUSH_7682", "Diseased Poison Ivy bush", "loctypes"),
            new GamevalEntry(7683, "DISEASED_POISON_IVY_BUSH_7683", "Diseased Poison Ivy bush", "loctypes"),
            new GamevalEntry(7684, "DEAD_POISON_IVY_BUSH", "Dead Poison Ivy bush", "loctypes"),
            new GamevalEntry(7685, "DEAD_POISON_IVY_BUSH_7685", "Dead Poison Ivy bush", "loctypes"),
            new GamevalEntry(7686, "DEAD_POISON_IVY_BUSH_7686", "Dead Poison Ivy bush", "loctypes"),
            new GamevalEntry(7687, "DEAD_POISON_IVY_BUSH_7687", "Dead Poison Ivy bush", "loctypes"),
            new GamevalEntry(7688, "DEAD_POISON_IVY_BUSH_7688", "Dead Poison Ivy bush", "loctypes"),
            new GamevalEntry(7689, "DEAD_POISON_IVY_BUSH_7689", "Dead Poison Ivy bush", "loctypes"),
            new GamevalEntry(7690, "DEAD_POISON_IVY_BUSH_7690", "Dead Poison Ivy bush", "loctypes"),
            new GamevalEntry(7691, "DEAD_POISON_IVY_BUSH_7691", "Dead Poison Ivy bush", "loctypes"),
            new GamevalEntry(7692, "REDBERRY_BUSH", "Redberry bush", "loctypes"),
            new GamevalEntry(7693, "REDBERRY_BUSH_7693", "Redberry bush", "loctypes"),
            new GamevalEntry(7694, "REDBERRY_BUSH_7694", "Redberry bush", "loctypes"),
            new GamevalEntry(7695, "REDBERRY_BUSH_7695", "Redberry bush", "loctypes"),
            new GamevalEntry(7696, "REDBERRY_BUSH_7696", "Redberry bush", "loctypes"),
            new GamevalEntry(7697, "REDBERRY_BUSH_7697", "Redberry bush", "loctypes"),
            new GamevalEntry(7698, "REDBERRY_BUSH_7698", "Redberry bush", "loctypes"),
            new GamevalEntry(7699, "REDBERRY_BUSH_7699", "Redberry bush", "loctypes"),
            new GamevalEntry(7700, "REDBERRY_BUSH_7700", "Redberry bush", "loctypes"),
            new GamevalEntry(7701, "REDBERRY_BUSH_7701", "Redberry bush", "loctypes"),
            new GamevalEntry(7702, "REDBERRY_BUSH_7702", "Redberry bush", "loctypes"),
            new GamevalEntry(7703, "DISEASED_REDBERRY_BUSH", "Diseased redberry bush", "loctypes"),
            new GamevalEntry(7704, "DISEASED_REDBERRY_BUSH_7704", "Diseased redberry bush", "loctypes"),
            new GamevalEntry(7705, "DISEASED_REDBERRY_BUSH_7705", "Diseased redberry bush", "loctypes"),
            new GamevalEntry(7706, "DISEASED_REDBERRY_BUSH_7706", "Diseased redberry bush", "loctypes"),
            new GamevalEntry(7707, "DISEASED_REDBERRY_BUSH_7707", "Diseased redberry bush", "loctypes"),
            new GamevalEntry(7708, "DEAD_REDBERRY_BUSH", "Dead redberry bush", "loctypes"),
            new GamevalEntry(7709, "DEAD_REDBERRY_BUSH_7709", "Dead redberry bush", "loctypes"),
            new GamevalEntry(7710, "DEAD_REDBERRY_BUSH_7710", "Dead redberry bush", "loctypes"),
            new GamevalEntry(7711, "DEAD_REDBERRY_BUSH_7711", "Dead redberry bush", "loctypes"),
            new GamevalEntry(7712, "DEAD_REDBERRY_BUSH_7712", "Dead redberry bush", "loctypes"),
            new GamevalEntry(7713, "WHITEBERRY_BUSH", "Whiteberry bush", "loctypes"),
            new GamevalEntry(7714, "WHITEBERRY_BUSH_7714", "Whiteberry bush", "loctypes"),
            new GamevalEntry(7715, "WHITEBERRY_BUSH_7715", "Whiteberry bush", "loctypes"),
            new GamevalEntry(7716, "WHITEBERRY_BUSH_7716", "Whiteberry bush", "loctypes"),
            new GamevalEntry(7717, "WHITEBERRY_BUSH_7717", "Whiteberry bush", "loctypes"),
            new GamevalEntry(7718, "WHITEBERRY_BUSH_7718", "Whiteberry bush", "loctypes"),
            new GamevalEntry(7719, "WHITEBERRY_BUSH_7719", "Whiteberry bush", "loctypes"),
            new GamevalEntry(7720, "WHITEBERRY_BUSH_7720", "Whiteberry bush", "loctypes"),
            new GamevalEntry(7721, "WHITEBERRY_BUSH_7721", "Whiteberry bush", "loctypes"),
            new GamevalEntry(7722, "WHITEBERRY_BUSH_7722", "Whiteberry bush", "loctypes"),
            new GamevalEntry(7723, "WHITEBERRY_BUSH_7723", "Whiteberry bush", "loctypes"),
            new GamevalEntry(7724, "WHITEBERRY_BUSH_7724", "Whiteberry bush", "loctypes"),
            new GamevalEntry(7725, "WHITEBERRY_BUSH_7725", "Whiteberry bush", "loctypes"),
            new GamevalEntry(7726, "WHITEBERRY_BUSH_7726", "Whiteberry bush", "loctypes"),
            new GamevalEntry(7727, "DISEASED_WHITEBERRY_BUSH", "Diseased whiteberry bush", "loctypes"),
            new GamevalEntry(7728, "DISEASED_WHITEBERRY_BUSH_7728", "Diseased whiteberry bush", "loctypes"),
            new GamevalEntry(7729, "DISEASED_WHITEBERRY_BUSH_7729", "Diseased whiteberry bush", "loctypes"),
            new GamevalEntry(7730, "DISEASED_WHITEBERRY_BUSH_7730", "Diseased whiteberry bush", "loctypes"),
            new GamevalEntry(7731, "DISEASED_WHITEBERRY_BUSH_7731", "Diseased whiteberry bush", "loctypes"),
            new GamevalEntry(7732, "DISEASED_WHITEBERRY_BUSH_7732", "Diseased whiteberry bush", "loctypes"),
            new GamevalEntry(7733, "DISEASED_WHITEBERRY_BUSH_7733", "Diseased whiteberry bush", "loctypes"),
            new GamevalEntry(7734, "DISEASED_WHITEBERRY_BUSH_7734", "Diseased whiteberry bush", "loctypes"),
            new GamevalEntry(7735, "DEAD_WHITEBERRY_BUSH", "Dead whiteberry bush", "loctypes"),
            new GamevalEntry(7736, "DEAD_WHITEBERRY_BUSH_7736", "Dead whiteberry bush", "loctypes"),
            new GamevalEntry(7737, "DEAD_WHITEBERRY_BUSH_7737", "Dead whiteberry bush", "loctypes"),
            new GamevalEntry(7738, "DEAD_WHITEBERRY_BUSH_7738", "Dead whiteberry bush", "loctypes"),
            new GamevalEntry(7739, "DEAD_WHITEBERRY_BUSH_7739", "Dead whiteberry bush", "loctypes"),
            new GamevalEntry(7740, "DEAD_WHITEBERRY_BUSH_7740", "Dead whiteberry bush", "loctypes"),
            new GamevalEntry(7741, "DEAD_WHITEBERRY_BUSH_7741", "Dead whiteberry bush", "loctypes"),
            new GamevalEntry(7742, "DEAD_WHITEBERRY_BUSH_7742", "Dead whiteberry bush", "loctypes"),
            new GamevalEntry(7743, "CACTUS_PATCH", "Cactus patch", "loctypes"),
            new GamevalEntry(7744, "CACTUS_PATCH_7744", "Cactus patch", "loctypes"),
            new GamevalEntry(7745, "CACTUS_PATCH_7745", "Cactus patch", "loctypes"),
            new GamevalEntry(7746, "CACTUS_PATCH_7746", "Cactus patch", "loctypes"),
            new GamevalEntry(7747, "CACTUS_7747", "Cactus", "loctypes"),
            new GamevalEntry(7748, "CACTUS_7748", "Cactus", "loctypes"),
            new GamevalEntry(7749, "CACTUS_7749", "Cactus", "loctypes"),
            new GamevalEntry(7750, "CACTUS_7750", "Cactus", "loctypes"),
            new GamevalEntry(7751, "CACTUS_7751", "Cactus", "loctypes"),
            new GamevalEntry(7752, "CACTUS_7752", "Cactus", "loctypes"),
            new GamevalEntry(7753, "CACTUS_7753", "Cactus", "loctypes"),
            new GamevalEntry(7754, "CACTUS_7754", "Cactus", "loctypes"),
            new GamevalEntry(7755, "CACTUS_7755", "Cactus", "loctypes"),
            new GamevalEntry(7756, "CACTUS_7756", "Cactus", "loctypes"),
            new GamevalEntry(7757, "CACTUS_7757", "Cactus", "loctypes"),
            new GamevalEntry(7758, "CACTUS_7758", "Cactus", "loctypes"),
            new GamevalEntry(7759, "DISEASED_CACTUS", "Diseased cactus", "loctypes"),
            new GamevalEntry(7760, "DISEASED_CACTUS_7760", "Diseased cactus", "loctypes"),
            new GamevalEntry(7761, "DISEASED_CACTUS_7761", "Diseased cactus", "loctypes"),
            new GamevalEntry(7762, "DISEASED_CACTUS_7762", "Diseased cactus", "loctypes"),
            new GamevalEntry(7763, "DISEASED_CACTUS_7763", "Diseased cactus", "loctypes"),
            new GamevalEntry(7764, "DISEASED_CACTUS_7764", "Diseased cactus", "loctypes"),
            new GamevalEntry(7765, "DEAD_CACTUS", "Dead cactus", "loctypes"),
            new GamevalEntry(7766, "DEAD_CACTUS_7766", "Dead cactus", "loctypes"),
            new GamevalEntry(7767, "DEAD_CACTUS_7767", "Dead cactus", "loctypes"),
            new GamevalEntry(7768, "DEAD_CACTUS_7768", "Dead cactus", "loctypes"),
            new GamevalEntry(7769, "DEAD_CACTUS_7769", "Dead cactus", "loctypes"),
            new GamevalEntry(7770, "DEAD_CACTUS_7770", "Dead cactus", "loctypes"),
            new GamevalEntry(7771, "ID_7771", "=", "loctypes"),
            new GamevalEntry(7772, "CALQUAT_PATCH", "Calquat patch", "loctypes"),
            new GamevalEntry(7773, "CALQUAT_PATCH_7773", "Calquat patch", "loctypes"),
            new GamevalEntry(7774, "CALQUAT_PATCH_7774", "Calquat patch", "loctypes"),
            new GamevalEntry(7775, "CALQUAT_PATCH_7775", "Calquat patch", "loctypes"),
            new GamevalEntry(7776, "CALQUAT_TREE", "Calquat tree", "loctypes"),
            new GamevalEntry(7777, "CALQUAT_TREE_7777", "Calquat tree", "loctypes"),
            new GamevalEntry(7778, "CALQUAT_TREE_7778", "Calquat tree", "loctypes"),
            new GamevalEntry(7779, "CALQUAT_TREE_7779", "Calquat tree", "loctypes"),
            new GamevalEntry(7780, "CALQUAT_TREE_7780", "Calquat tree", "loctypes"),
            new GamevalEntry(7781, "CALQUAT_TREE_7781", "Calquat tree", "loctypes"),
            new GamevalEntry(7782, "CALQUAT_TREE_7782", "Calquat tree", "loctypes"),
            new GamevalEntry(7783, "CALQUAT_TREE_7783", "Calquat tree", "loctypes"),
            new GamevalEntry(7784, "CALQUAT_TREE_7784", "Calquat tree", "loctypes"),
            new GamevalEntry(7785, "CALQUAT_TREE_7785", "Calquat tree", "loctypes"),
            new GamevalEntry(7786, "CALQUAT_TREE_7786", "Calquat tree", "loctypes"),
            new GamevalEntry(7787, "CALQUAT_TREE_7787", "Calquat tree", "loctypes"),
            new GamevalEntry(7788, "CALQUAT_TREE_7788", "Calquat tree", "loctypes"),
            new GamevalEntry(7789, "CALQUAT_TREE_7789", "Calquat tree", "loctypes"),
            new GamevalEntry(7790, "CALQUAT_TREE_7790", "Calquat tree", "loctypes"),
            new GamevalEntry(7791, "CALQUAT_TREE_7791", "Calquat tree", "loctypes"),
            new GamevalEntry(7792, "DISEASED_CALQUAT", "Diseased Calquat", "loctypes"),
            new GamevalEntry(7793, "DISEASED_CALQUAT_7793", "Diseased Calquat", "loctypes"),
            new GamevalEntry(7794, "DISEASED_CALQUAT_7794", "Diseased Calquat", "loctypes"),
            new GamevalEntry(7795, "DISEASED_CALQUAT_7795", "Diseased Calquat", "loctypes"),
            new GamevalEntry(7796, "DISEASED_CALQUAT_7796", "Diseased Calquat", "loctypes"),
            new GamevalEntry(7797, "DISEASED_CALQUAT_7797", "Diseased Calquat", "loctypes"),
            new GamevalEntry(7798, "DISEASED_CALQUAT_7798", "Diseased Calquat", "loctypes"),
            new GamevalEntry(7799, "DEAD_CALQUAT", "Dead Calquat", "loctypes"),
            new GamevalEntry(7800, "DEAD_CALQUAT_7800", "Dead Calquat", "loctypes"),
            new GamevalEntry(7801, "DEAD_CALQUAT_7801", "Dead Calquat", "loctypes"),
            new GamevalEntry(7802, "DEAD_CALQUAT_7802", "Dead Calquat", "loctypes"),
            new GamevalEntry(7803, "DEAD_CALQUAT_7803", "Dead Calquat", "loctypes"),
            new GamevalEntry(7804, "DEAD_CALQUAT_7804", "Dead Calquat", "loctypes"),
            new GamevalEntry(7805, "DEAD_CALQUAT_7805", "Dead Calquat", "loctypes"),
            new GamevalEntry(7806, "DEAD_CALQUAT_7806", "Dead Calquat", "loctypes"),
            new GamevalEntry(7807, "ID_7807", "", "loctypes"),
            new GamevalEntry(7808, "COMPOST_BIN_7808", "Compost Bin", "loctypes"),
            new GamevalEntry(7809, "ID_7809", "", "loctypes"),
            new GamevalEntry(7810, "ID_7810", "", "loctypes"),
            new GamevalEntry(7811, "SUPPLIES", "Supplies", "loctypes"),
            new GamevalEntry(7812, "ID_7812", "", "loctypes"),
            new GamevalEntry(7813, "COMPOST_BIN_7813", "Compost Bin", "loctypes"),
            new GamevalEntry(7814, "ALTAR_7814", "Altar", "loctypes"),
            new GamevalEntry(7815, "ID_7815", "", "loctypes"),
            new GamevalEntry(7816, "ID_7816", "", "loctypes"),
            new GamevalEntry(7817, "ID_7817", "", "loctypes"),
            new GamevalEntry(7818, "ID_7818", "", "loctypes"),
            new GamevalEntry(7819, "EXIT_PORTAL", "Exit portal", "loctypes"),
            new GamevalEntry(7820, "EXIT_PORTAL_7820", "Exit portal", "loctypes"),
            new GamevalEntry(7821, "BARRIER", "Barrier", "loctypes"),
            new GamevalEntry(7822, "BARRIER_7822", "Barrier", "loctypes"),
            new GamevalEntry(7823, "ID_7823", "", "loctypes"),
            new GamevalEntry(7824, "ID_7824", "", "loctypes"),
            new GamevalEntry(7825, "ID_7825", "", "loctypes"),
            new GamevalEntry(7826, "ID_7826", "", "loctypes"),
            new GamevalEntry(7827, "ID_7827", "", "loctypes"),
            new GamevalEntry(7828, "ID_7828", "", "loctypes"),
            new GamevalEntry(7829, "ID_7829", "", "loctypes"),
            new GamevalEntry(7830, "ID_7830", "", "loctypes"),
            new GamevalEntry(7831, "ID_7831", "", "loctypes"),
            new GamevalEntry(7832, "ID_7832", "", "loctypes"),
            new GamevalEntry(7833, "ID_7833", "", "loctypes"),
            new GamevalEntry(7834, "ID_7834", "", "loctypes"),
            new GamevalEntry(7835, "ID_7835", "", "loctypes"),
            new GamevalEntry(7836, "ID_7836", "", "loctypes"),
            new GamevalEntry(7837, "ID_7837", "", "loctypes"),
            new GamevalEntry(7838, "ID_7838", "", "loctypes"),
            new GamevalEntry(7839, "ID_7839", "", "loctypes"),
            new GamevalEntry(7840, "FLOWER_PATCH", "Flower Patch", "loctypes"),
            new GamevalEntry(7841, "FLOWER_PATCH_7841", "Flower Patch", "loctypes"),
            new GamevalEntry(7842, "FLOWER_PATCH_7842", "Flower Patch", "loctypes"),
            new GamevalEntry(7843, "FLOWER_PATCH_7843", "Flower Patch", "loctypes"),
            new GamevalEntry(7844, "FLOWER_PATCH_7844", "Flower Patch", "loctypes"),
            new GamevalEntry(7845, "FLOWER_PATCH_7845", "Flower Patch", "loctypes"),
            new GamevalEntry(7846, "FLOWER_PATCH_7846", "Flower Patch", "loctypes"),
            new GamevalEntry(7847, "ID_7847", "=", "loctypes"),
            new GamevalEntry(7848, "ID_7848", "=", "loctypes"),
            new GamevalEntry(7849, "ID_7849", "=", "loctypes"),
            new GamevalEntry(7850, "ID_7850", "=", "loctypes"),
            new GamevalEntry(7851, "LIMPWURT_PLANT", "Limpwurt plant", "loctypes"),
            new GamevalEntry(7852, "LIMPWURT_PLANT_7852", "Limpwurt plant", "loctypes"),
            new GamevalEntry(7853, "LIMPWURT_PLANT_7853", "Limpwurt plant", "loctypes"),
            new GamevalEntry(7854, "LIMPWURT_PLANT_7854", "Limpwurt plant", "loctypes"),
            new GamevalEntry(7855, "LIMPWURT_PLANT_7855", "Limpwurt plant", "loctypes"),
            new GamevalEntry(7856, "LIMPWURT_PLANT_7856", "Limpwurt plant", "loctypes"),
            new GamevalEntry(7857, "LIMPWURT_PLANT_7857", "Limpwurt plant", "loctypes"),
            new GamevalEntry(7858, "LIMPWURT_PLANT_7858", "Limpwurt plant", "loctypes"),
            new GamevalEntry(7859, "LIMPWURT_PLANT_7859", "Limpwurt plant", "loctypes"),
            new GamevalEntry(7860, "DISEASED_LIMPWURT_PLANT", "Diseased limpwurt plant", "loctypes"),
            new GamevalEntry(7861, "DISEASED_LIMPWURT_PLANT_7861", "Diseased limpwurt plant", "loctypes"),
            new GamevalEntry(7862, "DISEASED_LIMPWURT_PLANT_7862", "Diseased limpwurt plant", "loctypes"),
            new GamevalEntry(7863, "DEAD_LIMPWURT_PLANT", "Dead limpwurt plant", "loctypes"),
            new GamevalEntry(7864, "DEAD_LIMPWURT_PLANT_7864", "Dead limpwurt plant", "loctypes"),
            new GamevalEntry(7865, "DEAD_LIMPWURT_PLANT_7865", "Dead limpwurt plant", "loctypes"),
            new GamevalEntry(7866, "DEAD_LIMPWURT_PLANT_7866", "Dead limpwurt plant", "loctypes"),
            new GamevalEntry(7867, "MARIGOLD", "Marigold", "loctypes"),
            new GamevalEntry(7868, "MARIGOLD_7868", "Marigold", "loctypes"),
            new GamevalEntry(7869, "MARIGOLD_7869", "Marigold", "loctypes"),
            new GamevalEntry(7870, "MARIGOLD_7870", "Marigold", "loctypes"),
            new GamevalEntry(7871, "MARIGOLD_7871", "Marigold", "loctypes"),
            new GamevalEntry(7872, "MARIGOLD_7872", "Marigold", "loctypes"),
            new GamevalEntry(7873, "MARIGOLD_7873", "Marigold", "loctypes"),
            new GamevalEntry(7874, "MARIGOLD_7874", "Marigold", "loctypes"),
            new GamevalEntry(7875, "MARIGOLD_7875", "Marigold", "loctypes"),
            new GamevalEntry(7876, "DISEASED_MARIGOLD", "Diseased marigold", "loctypes"),
            new GamevalEntry(7877, "DISEASED_MARIGOLD_7877", "Diseased marigold", "loctypes"),
            new GamevalEntry(7878, "DISEASED_MARIGOLD_7878", "Diseased marigold", "loctypes"),
            new GamevalEntry(7879, "DEAD_MARIGOLD", "Dead marigold", "loctypes"),
            new GamevalEntry(7880, "DEAD_MARIGOLD_7880", "Dead marigold", "loctypes"),
            new GamevalEntry(7881, "DEAD_MARIGOLD_7881", "Dead marigold", "loctypes"),
            new GamevalEntry(7882, "DEAD_MARIGOLD_7882", "Dead marigold", "loctypes"),
            new GamevalEntry(7883, "NASTURTIUM", "Nasturtium", "loctypes"),
            new GamevalEntry(7884, "NASTURTIUM_7884", "Nasturtium", "loctypes"),
            new GamevalEntry(7885, "NASTURTIUM_7885", "Nasturtium", "loctypes"),
            new GamevalEntry(7886, "NASTURTIUM_7886", "Nasturtium", "loctypes"),
            new GamevalEntry(7887, "NASTURTIUM_7887", "Nasturtium", "loctypes"),
            new GamevalEntry(7888, "NASTURTIUM_7888", "Nasturtium", "loctypes"),
            new GamevalEntry(7889, "NASTURTIUM_7889", "Nasturtium", "loctypes"),
            new GamevalEntry(7890, "NASTURTIUM_7890", "Nasturtium", "loctypes"),
            new GamevalEntry(7891, "NASTURTIUM_7891", "Nasturtium", "loctypes"),
            new GamevalEntry(7892, "DISEASED_NASTURTIUM", "Diseased nasturtium", "loctypes"),
            new GamevalEntry(7893, "DISEASED_NASTURTIUM_7893", "Diseased nasturtium", "loctypes"),
            new GamevalEntry(7894, "DISEASED_NASTURTIUM_7894", "Diseased nasturtium", "loctypes"),
            new GamevalEntry(7895, "DEAD_NASTURTIUM", "Dead nasturtium", "loctypes"),
            new GamevalEntry(7896, "DEAD_NASTURTIUM_7896", "Dead nasturtium", "loctypes"),
            new GamevalEntry(7897, "DEAD_NASTURTIUM_7897", "Dead nasturtium", "loctypes"),
            new GamevalEntry(7898, "DEAD_NASTURTIUM_7898", "Dead nasturtium", "loctypes"),
            new GamevalEntry(7899, "ROSEMARY_7899", "Rosemary", "loctypes"),
            new GamevalEntry(7900, "ROSEMARY_7900", "Rosemary", "loctypes"),
            new GamevalEntry(7901, "ROSEMARY_7901", "Rosemary", "loctypes"),
            new GamevalEntry(7902, "ROSEMARY_7902", "Rosemary", "loctypes"),
            new GamevalEntry(7903, "ROSEMARY_7903", "Rosemary", "loctypes"),
            new GamevalEntry(7904, "ROSEMARY_7904", "Rosemary", "loctypes"),
            new GamevalEntry(7905, "ROSEMARY_7905", "Rosemary", "loctypes"),
            new GamevalEntry(7906, "ROSEMARY_7906", "Rosemary", "loctypes"),
            new GamevalEntry(7907, "ROSEMARY_7907", "Rosemary", "loctypes"),
            new GamevalEntry(7908, "DISEASED_ROSEMARY", "Diseased rosemary", "loctypes"),
            new GamevalEntry(7909, "DISEASED_ROSEMARY_7909", "Diseased rosemary", "loctypes"),
            new GamevalEntry(7910, "DISEASED_ROSEMARY_7910", "Diseased rosemary", "loctypes"),
            new GamevalEntry(7911, "DEAD_ROSEMARY", "Dead rosemary", "loctypes"),
            new GamevalEntry(7912, "DEAD_ROSEMARY_7912", "Dead rosemary", "loctypes"),
            new GamevalEntry(7913, "DEAD_ROSEMARY_7913", "Dead rosemary", "loctypes"),
            new GamevalEntry(7914, "DEAD_ROSEMARY_7914", "Dead rosemary", "loctypes"),
            new GamevalEntry(7915, "SCARECROW_7915", "Scarecrow", "loctypes"),
            new GamevalEntry(7916, "SCARECROW_7916", "Scarecrow", "loctypes"),
            new GamevalEntry(7917, "SCARECROW_7917", "Scarecrow", "loctypes"),
            new GamevalEntry(7918, "SCARECROW_7918", "Scarecrow", "loctypes"),
            new GamevalEntry(7919, "WOAD_PLANT", "Woad plant", "loctypes"),
            new GamevalEntry(7920, "WOAD_PLANT_7920", "Woad plant", "loctypes"),
            new GamevalEntry(7921, "WOAD_PLANT_7921", "Woad plant", "loctypes"),
            new GamevalEntry(7922, "WOAD_PLANT_7922", "Woad plant", "loctypes"),
            new GamevalEntry(7923, "WOAD_PLANT_7923", "Woad plant", "loctypes"),
            new GamevalEntry(7924, "WOAD_PLANT_7924", "Woad plant", "loctypes"),
            new GamevalEntry(7925, "WOAD_PLANT_7925", "Woad plant", "loctypes"),
            new GamevalEntry(7926, "WOAD_PLANT_7926", "Woad plant", "loctypes"),
            new GamevalEntry(7927, "WOAD_PLANT_7927", "Woad plant", "loctypes"),
            new GamevalEntry(7928, "DISEASED_WOAD_PLANT", "Diseased woad plant", "loctypes"),
            new GamevalEntry(7929, "DISEASED_WOAD_PLANT_7929", "Diseased woad plant", "loctypes"),
            new GamevalEntry(7930, "DISEASED_WOAD_PLANT_7930", "Diseased woad plant", "loctypes"),
            new GamevalEntry(7931, "DEAD_WOAD_PLANT", "Dead woad plant", "loctypes"),
            new GamevalEntry(7932, "DEAD_WOAD_PLANT_7932", "Dead woad plant", "loctypes"),
            new GamevalEntry(7933, "DEAD_WOAD_PLANT_7933", "Dead woad plant", "loctypes"),
            new GamevalEntry(7934, "DEAD_WOAD_PLANT_7934", "Dead woad plant", "loctypes"),
            new GamevalEntry(7935, "APPLE_TREE_7935", "Apple tree", "loctypes"),
            new GamevalEntry(7936, "APPLE_TREE_7936", "Apple tree", "loctypes"),
            new GamevalEntry(7937, "APPLE_TREE_7937", "Apple tree", "loctypes"),
            new GamevalEntry(7938, "APPLE_TREE_7938", "Apple tree", "loctypes"),
            new GamevalEntry(7939, "APPLE_TREE_7939", "Apple tree", "loctypes"),
            new GamevalEntry(7940, "APPLE_TREE_7940", "Apple tree", "loctypes"),
            new GamevalEntry(7941, "APPLE_TREE_7941", "Apple tree", "loctypes"),
            new GamevalEntry(7942, "APPLE_TREE_7942", "Apple tree", "loctypes"),
            new GamevalEntry(7943, "APPLE_TREE_7943", "Apple tree", "loctypes"),
            new GamevalEntry(7944, "APPLE_TREE_7944", "Apple tree", "loctypes"),
            new GamevalEntry(7945, "APPLE_TREE_7945", "Apple tree", "loctypes"),
            new GamevalEntry(7946, "APPLE_TREE_7946", "Apple tree", "loctypes"),
            new GamevalEntry(7947, "APPLE_TREE_7947", "Apple tree", "loctypes"),
            new GamevalEntry(7948, "APPLE_TREE_7948", "Apple tree", "loctypes"),
            new GamevalEntry(7949, "DISEASED_APPLE_TREE", "Diseased apple tree", "loctypes"),
            new GamevalEntry(7950, "DISEASED_APPLE_TREE_7950", "Diseased apple tree", "loctypes"),
            new GamevalEntry(7951, "DISEASED_APPLE_TREE_7951", "Diseased apple tree", "loctypes"),
            new GamevalEntry(7952, "DISEASED_APPLE_TREE_7952", "Diseased apple tree", "loctypes"),
            new GamevalEntry(7953, "DISEASED_APPLE_TREE_7953", "Diseased apple tree", "loctypes"),
            new GamevalEntry(7954, "DISEASED_APPLE_TREE_7954", "Diseased apple tree", "loctypes"),
            new GamevalEntry(7955, "DEAD_APPLE_TREE", "Dead apple tree", "loctypes"),
            new GamevalEntry(7956, "DEAD_APPLE_TREE_7956", "Dead apple tree", "loctypes"),
            new GamevalEntry(7957, "DEAD_APPLE_TREE_7957", "Dead apple tree", "loctypes"),
            new GamevalEntry(7958, "DEAD_APPLE_TREE_7958", "Dead apple tree", "loctypes"),
            new GamevalEntry(7959, "DEAD_APPLE_TREE_7959", "Dead apple tree", "loctypes"),
            new GamevalEntry(7960, "DEAD_APPLE_TREE_7960", "Dead apple tree", "loctypes"),
            new GamevalEntry(7961, "APPLE_TREE_STUMP", "Apple tree stump", "loctypes"),
            new GamevalEntry(7962, "ID_7962", "=", "loctypes"),
            new GamevalEntry(7963, "ID_7963", "=", "loctypes"),
            new GamevalEntry(7964, "ID_7964", "=", "loctypes"),
            new GamevalEntry(7965, "ID_7965", "=", "loctypes"),
            new GamevalEntry(7966, "PINEAPPLE_PLANT_7966", "Pineapple plant", "loctypes"),
            new GamevalEntry(7967, "PINEAPPLE_PLANT_7967", "Pineapple plant", "loctypes"),
            new GamevalEntry(7968, "PINEAPPLE_PLANT_7968", "Pineapple plant", "loctypes"),
            new GamevalEntry(7969, "PINEAPPLE_PLANT_7969", "Pineapple plant", "loctypes"),
            new GamevalEntry(7970, "PINEAPPLE_PLANT_7970", "Pineapple plant", "loctypes"),
            new GamevalEntry(7971, "PINEAPPLE_PLANT_7971", "Pineapple plant", "loctypes"),
            new GamevalEntry(7972, "PINEAPPLE_PLANT_7972", "Pineapple plant", "loctypes"),
            new GamevalEntry(7973, "PINEAPPLE_PLANT_7973", "Pineapple plant", "loctypes"),
            new GamevalEntry(7974, "PINEAPPLE_PLANT_7974", "Pineapple plant", "loctypes"),
            new GamevalEntry(7975, "PINEAPPLE_PLANT_7975", "Pineapple plant", "loctypes"),
            new GamevalEntry(7976, "PINEAPPLE_PLANT_7976", "Pineapple plant", "loctypes"),
            new GamevalEntry(7977, "PINEAPPLE_PLANT_7977", "Pineapple plant", "loctypes"),
            new GamevalEntry(7978, "PINEAPPLE_PLANT_7978", "Pineapple plant", "loctypes"),
            new GamevalEntry(7979, "PINEAPPLE_PLANT_7979", "Pineapple plant", "loctypes"),
            new GamevalEntry(7980, "DISEASED_PINEAPPLE_PLANT", "Diseased pineapple plant", "loctypes"),
            new GamevalEntry(7981, "DISEASED_PINEAPPLE_PLANT_7981", "Diseased pineapple plant", "loctypes"),
            new GamevalEntry(7982, "DISEASED_PINEAPPLE_PLANT_7982", "Diseased pineapple plant", "loctypes"),
            new GamevalEntry(7983, "DISEASED_PINEAPPLE_PLANT_7983", "Diseased pineapple plant", "loctypes"),
            new GamevalEntry(7984, "DISEASED_PINEAPPLE_PLANT_7984", "Diseased pineapple plant", "loctypes"),
            new GamevalEntry(7985, "DISEASED_PINEAPPLE_PLANT_7985", "Diseased pineapple plant", "loctypes"),
            new GamevalEntry(7986, "DEAD_PINEAPPLE_PLANT", "Dead pineapple plant", "loctypes"),
            new GamevalEntry(7987, "DEAD_PINEAPPLE_PLANT_7987", "Dead pineapple plant", "loctypes"),
            new GamevalEntry(7988, "DEAD_PINEAPPLE_PLANT_7988", "Dead pineapple plant", "loctypes"),
            new GamevalEntry(7989, "DEAD_PINEAPPLE_PLANT_7989", "Dead pineapple plant", "loctypes"),
            new GamevalEntry(7990, "DEAD_PINEAPPLE_PLANT_7990", "Dead pineapple plant", "loctypes"),
            new GamevalEntry(7991, "DEAD_PINEAPPLE_PLANT_7991", "Dead pineapple plant", "loctypes"),
            new GamevalEntry(7992, "PINEAPPLE_PLANT_STUMP", "Pineapple plant stump", "loctypes"),
            new GamevalEntry(7993, "BANANA_TREE_7993", "Banana tree", "loctypes"),
            new GamevalEntry(7994, "BANANA_TREE_7994", "Banana tree", "loctypes"),
            new GamevalEntry(7995, "BANANA_TREE_7995", "Banana tree", "loctypes"),
            new GamevalEntry(7996, "BANANA_TREE_7996", "Banana tree", "loctypes"),
            new GamevalEntry(7997, "BANANA_TREE_7997", "Banana tree", "loctypes"),
            new GamevalEntry(7998, "BANANA_TREE_7998", "Banana tree", "loctypes"),
            new GamevalEntry(7999, "BANANA_TREE_7999", "Banana tree", "loctypes"),
            new GamevalEntry(8000, "BANANA_TREE_8000", "Banana tree", "loctypes"),
            new GamevalEntry(8001, "BANANA_TREE_8001", "Banana tree", "loctypes"),
            new GamevalEntry(8002, "BANANA_TREE_8002", "Banana tree", "loctypes"),
            new GamevalEntry(8003, "BANANA_TREE_8003", "Banana tree", "loctypes"),
            new GamevalEntry(8004, "BANANA_TREE_8004", "Banana tree", "loctypes"),
            new GamevalEntry(8005, "BANANA_TREE_8005", "Banana tree", "loctypes"),
            new GamevalEntry(8006, "BANANA_TREE_8006", "Banana tree", "loctypes"),
            new GamevalEntry(8007, "DISEASED_BANANA_TREE", "Diseased banana tree", "loctypes"),
            new GamevalEntry(8008, "DISEASED_BANANA_TREE_8008", "Diseased banana tree", "loctypes"),
            new GamevalEntry(8009, "DISEASED_BANANA_TREE_8009", "Diseased banana tree", "loctypes"),
            new GamevalEntry(8010, "DISEASED_BANANA_TREE_8010", "Diseased banana tree", "loctypes"),
            new GamevalEntry(8011, "DISEASED_BANANA_TREE_8011", "Diseased banana tree", "loctypes"),
            new GamevalEntry(8012, "DISEASED_BANANA_TREE_8012", "Diseased banana tree", "loctypes"),
            new GamevalEntry(8013, "DEAD_BANANA_TREE", "Dead banana tree", "loctypes"),
            new GamevalEntry(8014, "DEAD_BANANA_TREE_8014", "Dead banana tree", "loctypes"),
            new GamevalEntry(8015, "DEAD_BANANA_TREE_8015", "Dead banana tree", "loctypes"),
            new GamevalEntry(8016, "DEAD_BANANA_TREE_8016", "Dead banana tree", "loctypes"),
            new GamevalEntry(8017, "DEAD_BANANA_TREE_8017", "Dead banana tree", "loctypes"),
            new GamevalEntry(8018, "DEAD_BANANA_TREE_8018", "Dead banana tree", "loctypes"),
            new GamevalEntry(8019, "BANANA_TREE_STUMP", "Banana tree stump", "loctypes"),
            new GamevalEntry(8020, "CURRY_TREE", "Curry tree", "loctypes"),
            new GamevalEntry(8021, "CURRY_TREE_8021", "Curry tree", "loctypes"),
            new GamevalEntry(8022, "CURRY_TREE_8022", "Curry tree", "loctypes"),
            new GamevalEntry(8023, "CURRY_TREE_8023", "Curry tree", "loctypes"),
            new GamevalEntry(8024, "CURRY_TREE_8024", "Curry tree", "loctypes"),
            new GamevalEntry(8025, "CURRY_TREE_8025", "Curry tree", "loctypes"),
            new GamevalEntry(8026, "CURRY_TREE_8026", "Curry tree", "loctypes"),
            new GamevalEntry(8027, "CURRY_TREE_8027", "Curry tree", "loctypes"),
            new GamevalEntry(8028, "CURRY_TREE_8028", "Curry tree", "loctypes"),
            new GamevalEntry(8029, "CURRY_TREE_8029", "Curry tree", "loctypes"),
            new GamevalEntry(8030, "CURRY_TREE_8030", "Curry tree", "loctypes"),
            new GamevalEntry(8031, "CURRY_TREE_8031", "Curry tree", "loctypes"),
            new GamevalEntry(8032, "CURRY_TREE_8032", "Curry tree", "loctypes"),
            new GamevalEntry(8033, "CURRY_TREE_8033", "Curry tree", "loctypes"),
            new GamevalEntry(8034, "DISEASED_CURRY_TREE", "Diseased curry tree", "loctypes"),
            new GamevalEntry(8035, "DISEASED_CURRY_TREE_8035", "Diseased curry tree", "loctypes"),
            new GamevalEntry(8036, "DISEASED_CURRY_TREE_8036", "Diseased curry tree", "loctypes"),
            new GamevalEntry(8037, "DISEASED_CURRY_TREE_8037", "Diseased curry tree", "loctypes"),
            new GamevalEntry(8038, "DISEASED_CURRY_TREE_8038", "Diseased curry tree", "loctypes"),
            new GamevalEntry(8039, "DISEASED_CURRY_TREE_8039", "Diseased curry tree", "loctypes"),
            new GamevalEntry(8040, "DEAD_CURRY_TREE", "Dead curry tree", "loctypes"),
            new GamevalEntry(8041, "DEAD_CURRY_TREE_8041", "Dead curry tree", "loctypes"),
            new GamevalEntry(8042, "DEAD_CURRY_TREE_8042", "Dead curry tree", "loctypes"),
            new GamevalEntry(8043, "DEAD_CURRY_TREE_8043", "Dead curry tree", "loctypes"),
            new GamevalEntry(8044, "DEAD_CURRY_TREE_8044", "Dead curry tree", "loctypes"),
            new GamevalEntry(8045, "DEAD_CURRY_TREE_8045", "Dead curry tree", "loctypes"),
            new GamevalEntry(8046, "CURRY_TREE_STUMP", "Curry tree stump", "loctypes"),
            new GamevalEntry(8047, "FRUIT_TREE_PATCH", "Fruit Tree Patch", "loctypes"),
            new GamevalEntry(8048, "FRUIT_TREE_PATCH_8048", "Fruit Tree Patch", "loctypes"),
            new GamevalEntry(8049, "FRUIT_TREE_PATCH_8049", "Fruit Tree Patch", "loctypes"),
            new GamevalEntry(8050, "FRUIT_TREE_PATCH_8050", "Fruit Tree Patch", "loctypes"),
            new GamevalEntry(8051, "ORANGE_TREE", "Orange tree", "loctypes"),
            new GamevalEntry(8052, "ORANGE_TREE_8052", "Orange tree", "loctypes"),
            new GamevalEntry(8053, "ORANGE_TREE_8053", "Orange tree", "loctypes"),
            new GamevalEntry(8054, "ORANGE_TREE_8054", "Orange tree", "loctypes"),
            new GamevalEntry(8055, "ORANGE_TREE_8055", "Orange tree", "loctypes"),
            new GamevalEntry(8056, "ORANGE_TREE_8056", "Orange tree", "loctypes"),
            new GamevalEntry(8057, "ORANGE_TREE_8057", "Orange tree", "loctypes"),
            new GamevalEntry(8058, "ORANGE_TREE_8058", "Orange tree", "loctypes"),
            new GamevalEntry(8059, "ORANGE_TREE_8059", "Orange tree", "loctypes"),
            new GamevalEntry(8060, "ORANGE_TREE_8060", "Orange tree", "loctypes"),
            new GamevalEntry(8061, "ORANGE_TREE_8061", "Orange tree", "loctypes"),
            new GamevalEntry(8062, "ORANGE_TREE_8062", "Orange tree", "loctypes"),
            new GamevalEntry(8063, "ORANGE_TREE_8063", "Orange tree", "loctypes"),
            new GamevalEntry(8064, "ORANGE_TREE_8064", "Orange tree", "loctypes"),
            new GamevalEntry(8065, "DISEASED_ORANGE_TREE", "Diseased orange tree", "loctypes"),
            new GamevalEntry(8066, "DISEASED_ORANGE_TREE_8066", "Diseased orange tree", "loctypes"),
            new GamevalEntry(8067, "DISEASED_ORANGE_TREE_8067", "Diseased orange tree", "loctypes"),
            new GamevalEntry(8068, "DISEASED_ORANGE_TREE_8068", "Diseased orange tree", "loctypes"),
            new GamevalEntry(8069, "DISEASED_ORANGE_TREE_8069", "Diseased orange tree", "loctypes"),
            new GamevalEntry(8070, "DISEASED_ORANGE_TREE_8070", "Diseased orange tree", "loctypes"),
            new GamevalEntry(8071, "DEAD_ORANGE_TREE", "Dead orange tree", "loctypes"),
            new GamevalEntry(8072, "DEAD_ORANGE_TREE_8072", "Dead orange tree", "loctypes"),
            new GamevalEntry(8073, "DEAD_ORANGE_TREE_8073", "Dead orange tree", "loctypes"),
            new GamevalEntry(8074, "DEAD_ORANGE_TREE_8074", "Dead orange tree", "loctypes"),
            new GamevalEntry(8075, "DEAD_ORANGE_TREE_8075", "Dead orange tree", "loctypes"),
            new GamevalEntry(8076, "DEAD_ORANGE_TREE_8076", "Dead orange tree", "loctypes"),
            new GamevalEntry(8077, "ORANGE_TREE_STUMP", "Orange tree stump", "loctypes"),
            new GamevalEntry(8078, "PALM_TREE_8078", "Palm tree", "loctypes"),
            new GamevalEntry(8079, "PALM_TREE_8079", "Palm tree", "loctypes"),
            new GamevalEntry(8080, "PALM_TREE_8080", "Palm tree", "loctypes"),
            new GamevalEntry(8081, "PALM_TREE_8081", "Palm tree", "loctypes"),
            new GamevalEntry(8082, "PALM_TREE_8082", "Palm tree", "loctypes"),
            new GamevalEntry(8083, "PALM_TREE_8083", "Palm tree", "loctypes"),
            new GamevalEntry(8084, "PALM_TREE_8084", "Palm tree", "loctypes"),
            new GamevalEntry(8085, "PALM_TREE_8085", "Palm tree", "loctypes"),
            new GamevalEntry(8086, "PALM_TREE_8086", "Palm tree", "loctypes"),
            new GamevalEntry(8087, "PALM_TREE_8087", "Palm tree", "loctypes"),
            new GamevalEntry(8088, "PALM_TREE_8088", "Palm tree", "loctypes"),
            new GamevalEntry(8089, "PALM_TREE_8089", "Palm tree", "loctypes"),
            new GamevalEntry(8090, "PALM_TREE_8090", "Palm tree", "loctypes"),
            new GamevalEntry(8091, "PALM_TREE_8091", "Palm tree", "loctypes"),
            new GamevalEntry(8092, "DISEASED_PALM_TREE", "Diseased palm tree", "loctypes"),
            new GamevalEntry(8093, "DISEASED_PALM_TREE_8093", "Diseased palm tree", "loctypes"),
            new GamevalEntry(8094, "DISEASED_PALM_TREE_8094", "Diseased palm tree", "loctypes"),
            new GamevalEntry(8095, "DISEASED_PALM_TREE_8095", "Diseased palm tree", "loctypes"),
            new GamevalEntry(8096, "DISEASED_PALM_TREE_8096", "Diseased palm tree", "loctypes"),
            new GamevalEntry(8097, "DISEASED_PALM_TREE_8097", "Diseased palm tree", "loctypes"),
            new GamevalEntry(8098, "DEAD_PALM_TREE", "Dead palm tree", "loctypes"),
            new GamevalEntry(8099, "DEAD_PALM_TREE_8099", "Dead palm tree", "loctypes"),
            new GamevalEntry(8100, "DEAD_PALM_TREE_8100", "Dead palm tree", "loctypes"),
            new GamevalEntry(8101, "DEAD_PALM_TREE_8101", "Dead palm tree", "loctypes"),
            new GamevalEntry(8102, "DEAD_PALM_TREE_8102", "Dead palm tree", "loctypes"),
            new GamevalEntry(8103, "DEAD_PALM_TREE_8103", "Dead palm tree", "loctypes"),
            new GamevalEntry(8104, "PALM_TREE_STUMP", "Palm tree stump", "loctypes"),
            new GamevalEntry(8105, "PAPAYA_TREE", "Papaya tree", "loctypes"),
            new GamevalEntry(8106, "PAPAYA_TREE_8106", "Papaya tree", "loctypes"),
            new GamevalEntry(8107, "PAPAYA_TREE_8107", "Papaya tree", "loctypes"),
            new GamevalEntry(8108, "PAPAYA_TREE_8108", "Papaya tree", "loctypes"),
            new GamevalEntry(8109, "PAPAYA_TREE_8109", "Papaya tree", "loctypes"),
            new GamevalEntry(8110, "PAPAYA_TREE_8110", "Papaya tree", "loctypes"),
            new GamevalEntry(8111, "PAPAYA_TREE_8111", "Papaya tree", "loctypes"),
            new GamevalEntry(8112, "PAPAYA_TREE_8112", "Papaya tree", "loctypes"),
            new GamevalEntry(8113, "PAPAYA_TREE_8113", "Papaya tree", "loctypes"),
            new GamevalEntry(8114, "PAPAYA_TREE_8114", "Papaya tree", "loctypes"),
            new GamevalEntry(8115, "PAPAYA_TREE_8115", "Papaya tree", "loctypes"),
            new GamevalEntry(8116, "PAPAYA_TREE_8116", "Papaya tree", "loctypes"),
            new GamevalEntry(8117, "PAPAYA_TREE_8117", "Papaya tree", "loctypes"),
            new GamevalEntry(8118, "PAPAYA_TREE_8118", "Papaya tree", "loctypes"),
            new GamevalEntry(8119, "DISEASED_PAPAYA_TREE", "Diseased papaya tree", "loctypes"),
            new GamevalEntry(8120, "DISEASED_PAPAYA_TREE_8120", "Diseased papaya tree", "loctypes"),
            new GamevalEntry(8121, "DISEASED_PAPAYA_TREE_8121", "Diseased papaya tree", "loctypes"),
            new GamevalEntry(8122, "DISEASED_PAPAYA_TREE_8122", "Diseased papaya tree", "loctypes"),
            new GamevalEntry(8123, "DISEASED_PAPAYA_TREE_8123", "Diseased papaya tree", "loctypes"),
            new GamevalEntry(8124, "DISEASED_PAPAYA_TREE_8124", "Diseased papaya tree", "loctypes"),
            new GamevalEntry(8125, "DEAD_PAPAYA_TREE", "Dead papaya tree", "loctypes"),
            new GamevalEntry(8126, "DEAD_PAPAYA_TREE_8126", "Dead papaya tree", "loctypes"),
            new GamevalEntry(8127, "DEAD_PAPAYA_TREE_8127", "Dead papaya tree", "loctypes"),
            new GamevalEntry(8128, "DEAD_PAPAYA_TREE_8128", "Dead papaya tree", "loctypes"),
            new GamevalEntry(8129, "DEAD_PAPAYA_TREE_8129", "Dead papaya tree", "loctypes"),
            new GamevalEntry(8130, "DEAD_PAPAYA_TREE_8130", "Dead papaya tree", "loctypes"),
            new GamevalEntry(8131, "PAPAYA_TREE_STUMP", "Papaya tree stump", "loctypes"),
            new GamevalEntry(8132, "HERB_PATCH", "Herb patch", "loctypes"),
            new GamevalEntry(8133, "HERB_PATCH_8133", "Herb patch", "loctypes"),
            new GamevalEntry(8134, "HERB_PATCH_8134", "Herb patch", "loctypes"),
            new GamevalEntry(8135, "HERB_PATCH_8135", "Herb patch", "loctypes"),
            new GamevalEntry(8136, "HERB_PATCH_8136", "Herb patch", "loctypes"),
            new GamevalEntry(8137, "HERB_PATCH_8137", "Herb patch", "loctypes"),
            new GamevalEntry(8138, "HERB_PATCH_8138", "Herb patch", "loctypes"),
            new GamevalEntry(8139, "BANK_BOOTH_8139", "Bank booth", "loctypes"),
            new GamevalEntry(8140, "BANK_BOOTH_8140", "Bank booth", "loctypes"),
            new GamevalEntry(8141, "CLOSED_BANK_BOOTH_8141", "Closed bank booth", "loctypes"),
            new GamevalEntry(8142, "CLOSED_BANK_BOOTH_8142", "Closed bank booth", "loctypes"),
            new GamevalEntry(8143, "ID_8143", "", "loctypes"),
            new GamevalEntry(8144, "DISEASED_HERBS", "Diseased herbs", "loctypes"),
            new GamevalEntry(8145, "DISEASED_HERBS_8145", "Diseased herbs", "loctypes"),
            new GamevalEntry(8146, "DISEASED_HERBS_8146", "Diseased herbs", "loctypes"),
            new GamevalEntry(8147, "DEAD_HERBS", "Dead herbs", "loctypes"),
            new GamevalEntry(8148, "DEAD_HERBS_8148", "Dead herbs", "loctypes"),
            new GamevalEntry(8149, "DEAD_HERBS_8149", "Dead herbs", "loctypes"),
            new GamevalEntry(8150, "ID_8150", "=", "loctypes"),
            new GamevalEntry(8151, "ID_8151", "=", "loctypes"),
            new GamevalEntry(8152, "ID_8152", "=", "loctypes"),
            new GamevalEntry(8153, "ID_8153", "=", "loctypes"),
            new GamevalEntry(8154, "ASGARNIAN_HOPS", "Asgarnian Hops", "loctypes"),
            new GamevalEntry(8155, "ASGARNIAN_HOPS_8155", "Asgarnian Hops", "loctypes"),
            new GamevalEntry(8156, "ASGARNIAN_HOPS_8156", "Asgarnian Hops", "loctypes"),
            new GamevalEntry(8157, "ASGARNIAN_HOPS_8157", "Asgarnian Hops", "loctypes"),
            new GamevalEntry(8158, "ASGARNIAN_HOPS_8158", "Asgarnian Hops", "loctypes"),
            new GamevalEntry(8159, "ASGARNIAN_HOPS_8159", "Asgarnian Hops", "loctypes"),
            new GamevalEntry(8160, "ASGARNIAN_HOPS_8160", "Asgarnian Hops", "loctypes"),
            new GamevalEntry(8161, "ASGARNIAN_HOPS_8161", "Asgarnian Hops", "loctypes"),
            new GamevalEntry(8162, "ASGARNIAN_HOPS_8162", "Asgarnian Hops", "loctypes"),
            new GamevalEntry(8163, "ASGARNIAN_HOPS_8163", "Asgarnian Hops", "loctypes"),
            new GamevalEntry(8164, "ASGARNIAN_HOPS_8164", "Asgarnian Hops", "loctypes"),
            new GamevalEntry(8165, "DISEASED_ASGARNIAN_HOPS", "Diseased Asgarnian Hops", "loctypes"),
            new GamevalEntry(8166, "DISEASED_ASGARNIAN_HOPS_8166", "Diseased Asgarnian Hops", "loctypes"),
            new GamevalEntry(8167, "DISEASED_ASGARNIAN_HOPS_8167", "Diseased Asgarnian Hops", "loctypes"),
            new GamevalEntry(8168, "DISEASED_ASGARNIAN_HOPS_8168", "Diseased Asgarnian Hops", "loctypes"),
            new GamevalEntry(8169, "DEAD_ASGARNIAN_HOPS", "Dead Asgarnian Hops", "loctypes"),
            new GamevalEntry(8170, "DEAD_ASGARNIAN_HOPS_8170", "Dead Asgarnian Hops", "loctypes"),
            new GamevalEntry(8171, "DEAD_ASGARNIAN_HOPS_8171", "Dead Asgarnian Hops", "loctypes"),
            new GamevalEntry(8172, "DEAD_ASGARNIAN_HOPS_8172", "Dead Asgarnian Hops", "loctypes"),
            new GamevalEntry(8173, "ID_8173", "", "loctypes"),
            new GamevalEntry(8174, "ID_8174", "", "loctypes"),
            new GamevalEntry(8175, "ID_8175", "", "loctypes"),
            new GamevalEntry(8176, "ID_8176", "", "loctypes"),
            new GamevalEntry(8177, "HAMMERSTONE_HOPS", "Hammerstone Hops", "loctypes"),
            new GamevalEntry(8178, "HAMMERSTONE_HOPS_8178", "Hammerstone Hops", "loctypes"),
            new GamevalEntry(8179, "HAMMERSTONE_HOPS_8179", "Hammerstone Hops", "loctypes"),
            new GamevalEntry(8180, "HAMMERSTONE_HOPS_8180", "Hammerstone Hops", "loctypes"),
            new GamevalEntry(8181, "HAMMERSTONE_HOPS_8181", "Hammerstone Hops", "loctypes"),
            new GamevalEntry(8182, "HAMMERSTONE_HOPS_8182", "Hammerstone Hops", "loctypes"),
            new GamevalEntry(8183, "HAMMERSTONE_HOPS_8183", "Hammerstone Hops", "loctypes"),
            new GamevalEntry(8184, "HAMMERSTONE_HOPS_8184", "Hammerstone Hops", "loctypes"),
            new GamevalEntry(8185, "HAMMERSTONE_HOPS_8185", "Hammerstone Hops", "loctypes"),
            new GamevalEntry(8186, "DISEASED_HAMMERSTONE_HOPS", "Diseased Hammerstone Hops", "loctypes"),
            new GamevalEntry(8187, "DISEASED_HAMMERSTONE_HOPS_8187", "Diseased Hammerstone Hops", "loctypes"),
            new GamevalEntry(8188, "DISEASED_HAMMERSTONE_HOPS_8188", "Diseased Hammerstone Hops", "loctypes"),
            new GamevalEntry(8189, "DEAD_HAMMERSTONE_HOPS", "Dead Hammerstone Hops", "loctypes"),
            new GamevalEntry(8190, "DEAD_HAMMERSTONE_HOPS_8190", "Dead Hammerstone Hops", "loctypes"),
            new GamevalEntry(8191, "DEAD_HAMMERSTONE_HOPS_8191", "Dead Hammerstone Hops", "loctypes"),
        };
    }

    static Optional<GamevalEntry> byId(int id) {
        for (GamevalEntry entry : entries()) {
            if (entry.id() == id) return Optional.of(entry);
        }
        return Optional.empty();
    }

}
