/// @file titan/gamevals.h
/// @brief Native gameval constants generated by SoxClientGhidraUpdater.
#pragma once

#include "generated/gamevals/types.h"
#include "generated/gamevals/manifest.h"
#include "generated/gamevals/item_id.h"
#include "generated/gamevals/npc_id.h"
#include "generated/gamevals/object_id.h"
#include "generated/gamevals/varbit_id.h"
#include "generated/gamevals/inventory_id.h"
#include "generated/gamevals/var_player_id.h"
#include "generated/gamevals/var_client_id.h"
#include "generated/gamevals/db_table_id.h"
#include "generated/gamevals/db_row_id.h"
#include "generated/gamevals/quest_id.h"
#include "generated/gamevals/animation_id.h"
#include "generated/gamevals/spotanim_id.h"
#include "generated/gamevals/interface_id.h"
