{
  "formatVersion": "1.1",
  "component": {
    "group": "net.titan",
    "module": "titan-plugin-api",
    "version": "0.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "7.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "titan-plugin-api-0.1.0.jar",
          "url": "titan-plugin-api-0.1.0.jar",
          "size": 22377,
          "sha512": "6a4a121f96aba7d51be9a34ab09e0107c784ecc845c3213202d262ae04bd11cf53a1d1314825f4c164b39dbb8fead217125a787ca13763ed14b0dc15cb2095de",
          "sha256": "a423ac422370b1d19fcbcf98e39a8820d227a18a704e36929e3bdc718496375c",
          "sha1": "68f527e155aab79100af6b943d35f674546c2bd8",
          "md5": "5e9faa8fa58b7f558b43516bc2c6ba96"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "7.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "titan-plugin-api-0.1.0.jar",
          "url": "titan-plugin-api-0.1.0.jar",
          "size": 22377,
          "sha512": "6a4a121f96aba7d51be9a34ab09e0107c784ecc845c3213202d262ae04bd11cf53a1d1314825f4c164b39dbb8fead217125a787ca13763ed14b0dc15cb2095de",
          "sha256": "a423ac422370b1d19fcbcf98e39a8820d227a18a704e36929e3bdc718496375c",
          "sha1": "68f527e155aab79100af6b943d35f674546c2bd8",
          "md5": "5e9faa8fa58b7f558b43516bc2c6ba96"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "titan-plugin-api-0.1.0-sources.jar",
          "url": "titan-plugin-api-0.1.0-sources.jar",
          "size": 13819,
          "sha512": "e061e181fa5ea95e29cd0560ff006a8f61065a801dbff0874665dad5b133483ca457c8ae2a71788a2cc111913a349a6fef603f1fc7b23439b8e310bc7d0a09ec",
          "sha256": "210cf650b382f4ee0dd0558fa7e91ec7872e5eaaf00a90837828db2e25a62b0c",
          "sha1": "0db910323ee044ac79876848a8b9f93305136c94",
          "md5": "28823474c2d236d7bb1b0201ac43744c"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "titan-plugin-api-0.1.0-javadoc.jar",
          "url": "titan-plugin-api-0.1.0-javadoc.jar",
          "size": 411352,
          "sha512": "acf1ed6b5f649175beca1a73c071530310662d347fe6dd3447e089eb5cefca8307deedb47f92312c69355c606053b2f2bf1c6b87a369dce9dd110dfbb9c5eb8c",
          "sha256": "f7f2bdc0d08c965cc72c5ed6602d8edb79a83e77eb8010eede262fa7aa19cad5",
          "sha1": "7ad5126263e9ed924477ae218efaa75a7d13281b",
          "md5": "37d03b0bc81110cbcf4169ccf24f3816"
        }
      ]
    }
  ]
}
