{
  "formatVersion": "1.1",
  "component": {
    "group": "net.titan",
    "module": "titan-plugin-api",
    "version": "0.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "7.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "titan-plugin-api-0.1.0.jar",
          "url": "titan-plugin-api-0.1.0.jar",
          "size": 8716,
          "sha512": "a166bfb055f330f2716127d51a2e1522b8f705fd4d9da4cce646c017dcb4f53f38d61434d008b01b0d88e946eaabfd1b5f1d3e8f5d62fccfa00ff39b798fb0b1",
          "sha256": "9a6136ff2607b5d07455304b1fa1abe6bf8f9cc91f21e775cd1a5937d9244530",
          "sha1": "0c460cc0cd0907f1e75cd105153908a859182f18",
          "md5": "10e5593673c9277f5e37854f09cb42dd"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "7.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "titan-plugin-api-0.1.0.jar",
          "url": "titan-plugin-api-0.1.0.jar",
          "size": 8716,
          "sha512": "a166bfb055f330f2716127d51a2e1522b8f705fd4d9da4cce646c017dcb4f53f38d61434d008b01b0d88e946eaabfd1b5f1d3e8f5d62fccfa00ff39b798fb0b1",
          "sha256": "9a6136ff2607b5d07455304b1fa1abe6bf8f9cc91f21e775cd1a5937d9244530",
          "sha1": "0c460cc0cd0907f1e75cd105153908a859182f18",
          "md5": "10e5593673c9277f5e37854f09cb42dd"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "titan-plugin-api-0.1.0-sources.jar",
          "url": "titan-plugin-api-0.1.0-sources.jar",
          "size": 6303,
          "sha512": "1c735fdafbeb6dc4cd19f368f8994e07058a2e883d32809d3df3d0e965b05a418e225a3101779ec2f3548dc299331c85fa13b14d6f8304b471af9f22b5d9b6bb",
          "sha256": "2b5ac912f9cef28318ce37582e75fcd06a80dc959d0e169fd93f3e055561a49e",
          "sha1": "a4e511a4959a0088dce0903cc2c92e9e12f5e2a7",
          "md5": "42ea924e07c0ba61094dd677cb136427"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "titan-plugin-api-0.1.0-javadoc.jar",
          "url": "titan-plugin-api-0.1.0-javadoc.jar",
          "size": 356445,
          "sha512": "6e2aec2c988d3c7aecf42e4de485872e724c64f9e633b1179925cd65228b56f5c1cf8cb8873cf20db0951ecb55f87f59f6c626038990ce4aff0116039589e4ac",
          "sha256": "3cb55bc16c6e86ba295b1b168517dec345a764b1887ce4d7f0cd766e8f5fcf83",
          "sha1": "ffddf6b06632104919670efcc89747d12ca160fd",
          "md5": "4bc4a0dc42c201f48e6ed578941ed5ff"
        }
      ]
    }
  ]
}
