{
  "formatVersion": "1.1",
  "component": {
    "group": "net.titan",
    "module": "titan-plugin-api",
    "version": "0.1.57",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "7.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "titan-plugin-api-0.1.57.jar",
          "url": "titan-plugin-api-0.1.57.jar",
          "size": 9072846,
          "sha512": "224db62477386afb61821c226c87e7e97842f500fa1858da2a2d0260b54d8dabd3dd02b22b7241a29bd710721ee9c64822a4ac17700c8dfef6de1860ebcdccc2",
          "sha256": "9471b223fdece9196a7b6f7a29a25bf635dde0e67bca494f7aa6caa645a7133c",
          "sha1": "880ec34bf8ea1ff5387b163fe7eaef0dd4553e91",
          "md5": "8522423fa110606ddd6640834277f0b2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "7.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "titan-plugin-api-0.1.57.jar",
          "url": "titan-plugin-api-0.1.57.jar",
          "size": 9072846,
          "sha512": "224db62477386afb61821c226c87e7e97842f500fa1858da2a2d0260b54d8dabd3dd02b22b7241a29bd710721ee9c64822a4ac17700c8dfef6de1860ebcdccc2",
          "sha256": "9471b223fdece9196a7b6f7a29a25bf635dde0e67bca494f7aa6caa645a7133c",
          "sha1": "880ec34bf8ea1ff5387b163fe7eaef0dd4553e91",
          "md5": "8522423fa110606ddd6640834277f0b2"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "titan-plugin-api-0.1.57-sources.jar",
          "url": "titan-plugin-api-0.1.57-sources.jar",
          "size": 4711077,
          "sha512": "bfaea9f7e8964b0ff72ff57a2da511f44f7dc8c252761d0bde413af5b860f290089e7f3ed2d94fa7b84a1938c85c1755d00b69238523fb328855b882c203f25a",
          "sha256": "6bd1c80ffc092a7a2a3843d2cebc12730a35da101b8de3046e15b352402f83ac",
          "sha1": "f68ff31382c9a5f1c4decfc41b4ad7f2d8803505",
          "md5": "51e4486c3b0b783ae6115e30b62231aa"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "titan-plugin-api-0.1.57-javadoc.jar",
          "url": "titan-plugin-api-0.1.57-javadoc.jar",
          "size": 22269883,
          "sha512": "691dcd9fcda2ba957442980fd4e110bb69e7ff781a08689c8c03c32979ccf3dae7a1a5ff70d4dcb27f7fff7b311757f2fcaed2c556daf0b53e674cd86d4d4969",
          "sha256": "c19d066e7798734b7c615bcf87e943bae82d181b7f1119575aa41517c1cf4cb4",
          "sha1": "97d2ae8b45e1b0d9c8f2105607e1897aba2c0858",
          "md5": "7a274063f41f13ebc825a24750ce73c6"
        }
      ]
    }
  ]
}
